### ISSUE TITLE
Linkify branch names in PRs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1]
So you can click them and jump directly to the correct repo and branch.

![image](https://cloud.githubusercontent.com/assets/170270/13054956/07f92b10-d43f-11e5-9b5d-e7caf30603a2.png)

**Comment by helix84** [comment]
Thank you for this. I don't know you but I love you :heart:

I wrote about this issue to GitHub support 2.5 years ago.

**Comment by sindresorhus** [comment]
@helix84 😃I've asked GitHub for it previously too. So have many of my friends.

**Comment by dylang** [comment]
I've fantasized about taking a two week vacation to fly to sf, get hired by Github, make this change, quit, fly home, and return to my job.

**Comment by paulmolluzzo** [comment]
@dylang get me one too while you're there. kthxbye

**Comment by lukehefson** [comment]
Wow. Feels pretty good to say that we've finally addressed #1: https://github.blog/changelog/2019-03-29-linking-branch-names-on-pull-request-headers/

Thanks as ever to this community. You are the BEST!

**Comment by bfred-it** [comment]
That's great but... deleted branches aren't marked with strikethrough. e.g. https://github.com/sindresorhus/refined-github/pull/1799

<img width="399" alt="" src="https://user-images.githubusercontent.com/1402241/55270976-f484b300-52e0-11e9-94b9-f73a54d9b601.png">

`busches:update-diff-settings` is a link that leads to a 404 and this could be clearer.

RGH can still strike through this linke at the bottom of the page, for example:

<img width="670" alt="" src="https://user-images.githubusercontent.com/1402241/55271011-52b19600-52e1-11e9-9e40-62b37225dc61.png">

<img width="667" alt="" src="https://user-images.githubusercontent.com/1402241/55270996-2f86e680-52e1-11e9-854a-d0cc987cd4ff.png">
