### ISSUE TITLE
Disable certain refinements

### ISSUE THREAD

**Issue by jonashaag** [sindresorhus/refined-github#10]
I'd like to disable the "hide comment box toolbar" refinement. Would be nice if there was a checkbox of each refinement to trigger whether it's enabled or disabled.

**Comment by sindresorhus** [comment]
See: https://github.com/sindresorhus/refined-github#contribute

I'm not interested in adding options. It's a lot more work, not including all the dumb boilerplate and hassle Chrome forces you to go through to add options. I would personally recommend just learning Markdown. It's a super simple syntax. Anyone is free to adapt the code here to do so, or you could just fork and modify it yourself ;)
