### ISSUE TITLE
Display "dependents" at top of repos, next to "stars"

### ISSUE THREAD

**Issue by TehShrike** [sindresorhus/refined-github#1000]
https://twitter.com/brianleroux/status/952567146185289729

Personally, I think "number of direct dependents" is more likely to be useful than "number of stars".  I think it would be good to include at the top of the repo next to watch/star.

Thoughts?

**Comment by bfred-it** [comment]
Refined GitHub has zero dependents, does that make it useless? 😋 

That said, it may be useful, my only concern is that it might be a bit long and cause the repo name to wrap

<img width="1005" alt="mockup" src="https://user-images.githubusercontent.com/1402241/35044027-60c194c0-fbc1-11e7-9c0a-d4c1ef755108.png">

**Comment by hkdobrev** [comment]
This feature is supported by too few languages at the moment to be useful to me. Also, as @bfred-it said, non-libraries would never have dependents.

**Comment by TehShrike** [comment]
Github's dependency detection still seems very young.  Even in languages where it is supported, I've seen times where it didn't show any dependents.

However, I expect it will get better.

It's already working in enough places to be useful to me more often than watch/fork counts.

**Comment by sindresorhus** [comment]
> Github's dependency detection still seems very young. Even in languages where it is supported, I've seen times where it didn't show any dependents.

This comment was a year ago and the situation has not improved. I don't think the dependents feature is good enough for us to prominently display it with stars.

**Comment by TehShrike** [comment]
For what repos is it inconsistent?

My experience is all with JS, and the dependency tracking has been 100% every time I've checked it for many months now.

Are there some non-JS languages where it still has issues?

**Comment by bfred-it** [comment]
https://twitter.com/github/status/1131468413983961088
