### ISSUE TITLE
Missing "shortcut to quickly delete a forked repo"

### ISSUE THREAD

**Issue by ntwb** [sindresorhus/refined-github#1001]
Per the "Adds a shortcut to quickly delete a forked repo" in the [More actions](https://github.com/sindresorhus/refined-github#more-actions) section:

<img width="743" alt="b2c9335c-e211-11e5-9e36-b0f325166356" src="https://user-images.githubusercontent.com/1016458/35037313-48c66436-fbcb-11e7-85ab-713d3a82eb24.png">

I'm not seeing the "Delete Fork" link on [this pull request](https://github.com/Automattic/jetpack/pull/8520) of mine that was just merged, what I see is:
![screen shot 2018-01-17 at 9 12 28 pm](https://user-images.githubusercontent.com/1016458/35037353-64769eee-fbcb-11e7-8689-3236de59f7ea.png)

Debug info: 
• Extension v18.1.15.1459
• Chrome Browser: Version 65.0.3315.3 (Official Build) dev (64-bit) 

----

p.s. It's only been a couple of days that I've been using this extension, it's awesome, thanks y'all 💯

**Comment by bfred-it** [comment]
I pushed a commit to fix a broken selector, however the feature is still broken in two ways:

- The link only appears if you can edit the **current** repo, which doesn't make much sense (see `canDeleteFork`)
- The link is only added after a page refresh, but not when GitHub updates the page dynamically (i.e. it should use `observeEl`)

**Comment by ntwb** [comment]
> The link only appears if you can edit the current repo, which doesn't make much sense (see `canDeleteFork`)

Thanks and agreed, more often than not if I _can_ edit a repo I'll use a branch on that repo to create PRs, rarely would I use my own fork
