### ISSUE TITLE
Fix the mention autocomplete

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1003]
See: https://twitter.com/jaffathecake/status/953247205200154624

Not sure what we could do, but we could at least put users that have commented on the issue first, with the author of the last comment at the top.

**Comment by hkdobrev** [comment]
I don't see why the autocomplete is not offline-first. If I don't have internet connection it should still complete users from the page, then continue with owners collaborators, contributors, but only online.

I think we can show it immediately based on the page contents:

If it's a PR/issue conversation:

0. Original poster first.
1. Last comment author (or previous comment author in inline review thread)
2. Everyone else.

If it's a commit page:

0. Author first (if not a bot).
1. Committer second (if different than Author and not GitHub or bot)
2. Last comment author.
3. Everyone else.

**Comment by hkdobrev** [comment]
Added an update to my suggestion since GitHub may now list multiple authors of a commit: https://github.com/blog/2496-commit-together-with-co-authors

**Comment by bfred-it** [comment]
Is this really possible? We'd have to hack their filter tool on the fly

**Comment by sindresorhus** [comment]
@bfred-it Probably not easy, yeah, but would be nice.

**Comment by dertieran** [comment]
I started hacking around with this [here](https://github.com/sindresorhus/refined-github/compare/master...dertieran:fix-mention-autocomplete), because I noticed all possible suggestions are available as an attribute in the `.suggester > ul` when it is loaded.

But I noticed that Github actually has a pretty good suggestion **initially**
![image](https://user-images.githubusercontent.com/9264728/48590163-cf4d6480-e93e-11e8-9687-a06a56a34e93.png)
this is when it loads the suggestion from the api **but then** if you search the cached results it fails...
![image](https://user-images.githubusercontent.com/9264728/48590155-c066b200-e93e-11e8-8a98-7212872414b0.png)
*(Example is for this issue)*

Maybe @lukehefson can help here or provide some information

**Comment by lukehefson** [comment]
> Maybe @lukehefson can help here or provide some information

I know we're talked internally about improving the picker and even spiked out some ideas – but I'm not 100% sure myself where we're at with it right now – I'll dig in.

From what I can tell across various feedback (including tweets in that original twitter thread) there are **a lot** of opinions on what the algorithm should be. So I guess what I'd love to know is… what do YOU, the refined-github community feel should be the right order of results? Is it https://github.com/sindresorhus/refined-github/issues/1003#issuecomment-358340622? Do you have a consensus?

**Comment by sindresorhus** [comment]
@lukehefson https://github.com/sindresorhus/refined-github/issues/1003#issuecomment-358340622 is pretty good, but I would like to propose making it even more comprehensive.

The list should be prioritized/sorted as follows:

Issue:

- The user that opened the issue.
- Last comment author.
- Users assigned to the issue.
- All comment authors.
- If the repo is in an org, members of org.
- Collaborators.
- Users I follow. (I often want to mention friends and co-workers!)
- Everyone else.

PR:

- The user that opened the PR.
- Last comment author (or previous comment author in inline review thread).
- Authors of the commits in the PR.
- Users assigned to the issue.
- Users request for review.
- All comment authors.
- If the repo is in an org, members of org.
- Collaborators.
- Users I follow.
- Everyone else.

Commit page:

- Authors.
- Committer, if different than Authors and not GitHub or bot.
- Last comment author.
- All comment authors.
- If the repo is in an org, members of org.
- Collaborators.
- Users I follow.
- Everyone else.

**Comment by dertieran** [comment]
I think everything that is a bit more tailored to the context then just "here is a alphabetic list of users that have ever commited to this repository".

Another question I have is if I should hack more around with it and try to make something working or if this will be changed soon anyway.

**Comment by lukehefson** [comment]
> The list should be prioritized/sorted as follows:

> I think everything that is a bit more tailored to the context

This is super useful – thanks folks!

> Another question I have is if I should hack more around with it and try to get something working or if this will be changed soon anyway.

@dertieran I wouldn't want you to stop you from working on refined-github! At this point I'm just doing investigatory work to understand the problem and scope a bit better – there wouldn't be any _immediate_ changes to this on GitHub I don't think.

**Comment by fregante** [comment]
News: https://twitter.com/ashtom/status/1462907830768640000?s=20
