### ISSUE TITLE
Show all PR merge status items instead of scrollable div

### ISSUE THREAD

**Issue by dylang** [sindresorhus/refined-github#1004]
Currently only 5 PR status items are displayed at a time, requiring users to scroll to see the rest, making it easy to miss status items.

## Current 
<img width="783" alt="screen shot 2018-01-17 at 12 07 58 pm" src="https://user-images.githubusercontent.com/51505/35056255-4ff4a7dc-fb7f-11e7-8da0-36727549daac.png">

*See that scroll bar?*

## Proposal
<img width="775" alt="screen shot 2018-01-17 at 12 08 35 pm" src="https://user-images.githubusercontent.com/51505/35056250-4d7531c0-fb7f-11e7-97ab-ae74bd0f3502.png">

*No more scrolling!*

## Implementation
`.merge-status-list` `max-height` needs to be `none`.

**Comment by hkdobrev** [comment]
@dylang I didn't know there was this limitation as I never saw so many status updates. It makes sense! Would you be able to send a pull request, please? Thank you!

**Comment by dylang** [comment]
Thanks @hkdobrev - PR submitted.
