### ISSUE TITLE
Limit search to current profile (restore feature)

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1011]
~~Organization pages already limit searches to the current organization:~~

<img width="312" alt="This organization | Search" src="https://user-images.githubusercontent.com/25517624/27594353-8705ac7e-5b27-11e7-9b46-44601d89c6e3.png">

User profiles should behave the same:

<img width="310" alt="This user | Search" src="https://user-images.githubusercontent.com/25517624/27594423-b4c45e94-5b27-11e7-9150-66fa65711edc.png">

---

This issue replaces #548

2018 edit: this type of search has been dropped from GitHub, this might not be easily possible

**Comment by bfred-it** [comment]
Reopening because this feature was dropped in the [last GitHub update](https://twitter.com/timdorr/status/999674789173358592)

<img width="366" alt="non-functional feature" src="https://user-images.githubusercontent.com/1402241/40501999-e433ff74-5f89-11e8-8340-6647f54ab1f6.png">

**Comment by sindresorhus** [comment]
@bfred-it It's unclear what the actionable thing to do here is?

**Comment by bfred-it** [comment]
Restoring the feature, somehow. This is on your profile:

<img width="378" alt="" src="https://user-images.githubusercontent.com/1402241/48153886-ddc1cd80-e2f9-11e8-88b1-7a515cd91394.png">

"Search this user" could appear up there, like "In this repository" appears when searching from a repo:

<img width="381" alt="" src="https://user-images.githubusercontent.com/1402241/48153941-ff22b980-e2f9-11e8-8885-7585b235db13.png">


Mockup:

<img width="374" alt="" src="https://user-images.githubusercontent.com/1402241/48154072-545ecb00-e2fa-11e8-91da-cd51388d3b4d.png">

**Comment by sindresorhus** [comment]
That makes sense. 👍

**Comment by yakov116** [comment]
https://blog.github.com/changelog/2018-11-26-searching-by-user-from-a-profile-page/
