### ISSUE TITLE
Reenables the jump caused by recently pushed branches by moving them to the side

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1018]
How to put it back where it was?

![image](https://user-images.githubusercontent.com/5332158/35195286-62b3f4e6-fea8-11e7-81fc-8c2f721e97ef.png)

My settings are:
```
add-gists-link-to-profile, linkify-urls-in-code, shorten-links 
add-delete-fork-link remove-projects-tab copy-on-y 
remove-projects-tab add-your-repositories-link-to-profile-dropdown 
```

**Comment by bfred-it** [comment]
What Browser/OS/repo are you seeing that on?

**Comment by evandrocoan** [comment]
1. Windows 10 build `15063`
1. Chrome `63.0.3239.132 (Official Build) (64-bit)`
1. https://github.com/evandroforks/python-language-server

Now it is not there, but anymore because I already created the pull request. But I am going to push a new branch so you can see it too.

**Comment by bfred-it** [comment]
Since it's a CSS feature there's no way to be disabled, but that's a bug and it's a good idea to fix it (perhaps just with some extra gray `padding-top`)

**Comment by bfred-it** [comment]
The bug was fixed in #1092.

Also why are you disabling these?

add-your-repositories-link-to-profile-dropdown 
add-gists-link-to-profile
add-delete-fork-link
copy-on-y
linkify-urls-in-code
shorten-links 
remove-projects-tab

**Comment by evandrocoan** [comment]
1. `add-your-repositories-link-to-profile-dropdown` I do not remember
1. `add-gists-link-to-profile` if it is what I think, I enabled it back
1. `add-delete-fork-link` Dangerous button. Most my forks will never go back to the upstream
1. `copy-on-y` I am not sure how it works, or why I need this instead of Ctrl+C
1. `linkify-urls-in-code` this is breaking most my URLs on git diffs
1. `shorten-links` this only helps me to build ugly reports for people not using `refined-github` addon
1. `remove-projects-tab` because it is a important tab

**Comment by bfred-it** [comment]
3 is not one-click, you still need 2 more clicks and typing the repo name like hahah requires

4 try pressing y when you are on files, it’s a GitHub feature, it will redirect you to a permalink. Refined GitHub will automatically copy that permalink. It’s not a ctrl+c replacement

5 that was a bug, it’s been fixed a while ago
