### ISSUE TITLE
Pagination options / endless scroll

### ISSUE THREAD

**Issue by alexanderadam** [sindresorhus/refined-github#1019]
Thank you very much for refined github. 👍 

There's something that bothers me since ages:
[github search for issues and similar objects currently shows 10 items per page](https://github.com/sindresorhus/refined-github/search?q=refined&type=Issues&utf8=%E2%9C%93).

It would be _wonderful_ if this could be changed to ie 100 items per page (with prefetching) and/or endless scroll.

**Comment by bfred-it** [comment]
I think this makes sense. We already do it for the newsfeed, but that only needs a `click()` and GitHub handles the loading.

**Comment by sindresorhus** [comment]
Big 👍. The 10 item limit is super annoying.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by fregante** [comment]
The limit has since been increased to 25, I think it's reasonable now. Plus in 1.5 years no one picked it up

**Comment by zadjii-msft** [comment]
note to self: this was added for a couple pages in #1516, but those pages just have simple "next" buttons to load, not a list of pages. I don't think that code could be easily modified as is to load the next button from that list. There'd have to be extra logic for tracking which page you've last loaded, probably similar to how RES does it. 

/_someone for whom 25 still isn't enough 😪_
