### ISSUE TITLE
Add unwatch and mark as read button to notifications

### ISSUE THREAD

**Issue by leggsimon** [sindresorhus/refined-github#1020]
I find my self being added as watching any new repos created in my organisation and so end up with loads of notifications. I'd like to be able to unwatch repos from here without having to navigate through to each one. 

Thoughts?

_Mock up idea_
![screenshot 2018-01-22 10 45 18](https://user-images.githubusercontent.com/11544418/35216992-85641656-ff61-11e7-8ff2-b4c0e60f2086.png)

**Comment by bfred-it** [comment]
It happens to me too, but I perhaps it's rare enough that it doesn't justify a destructive action like that made so easy. 

The "Mark all as read" button is right there so this could just be an extra "unwatch" button with a confirmation.

**Comment by leggsimon** [comment]
Yeah, that's fair. Sound's like a good compromise.

**Comment by bfred-it** [comment]
To unwatch it, the form requires an `autenticity_token`, that means that we'd have to fetch each repo's page on every `/notifications` page load. Not worth it
