### ISSUE TITLE
Don't add `archived` to filters if version of GitHub is too old

### ISSUE THREAD

**Issue by SimenB** [sindresorhus/refined-github#1022]
We're stuck on 2.11 of github enterprise, which does not have the archive function.

Adding `archive: false` to the filters means all issues are filtered out.

One potential way of checking for the version is to check the link in the footer to the API.

![image](https://user-images.githubusercontent.com/1404810/35234762-836f221e-ffa2-11e7-8bdc-4204b9ec8976.png)

**Comment by bfred-it** [comment]
I suggest deactivating the sorting feature for the time being

**Comment by bfred-it** [comment]
Closing this as few people need it and there's no PR.

**Comment by SimenB** [comment]
GHE at work was upgraded this weekend, so archive is now available for me at least 🙂

**Comment by bfred-it** [comment]
Lucky!

**Comment by busches** [comment]
Old versions of GHE are only supported for one year, which isn't long when it comes to Enterprise stuff, encouraging quicker adoption. We moved to 2.12 in February as well.
