### ISSUE TITLE
Hiding issue renaming

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1023]
I just renamed an issue, but it is not being showed:

![image](https://user-images.githubusercontent.com/5332158/35242209-11880424-ffa0-11e7-92ab-afecc02b969d.png)

___
If I disable the extension or using incognito mode, it shows up correctly:

![image](https://user-images.githubusercontent.com/5332158/35242157-e9193684-ff9f-11e7-8a3c-0ac69148b3d6.png)

Issue link:

1. https://github.com/tomv564/LSP/issues/252

**Comment by bfred-it** [comment]
It's a feature: https://github.com/sindresorhus/refined-github/pull/643

**Comment by evandrocoan** [comment]
Is this configurable currently?

**Comment by bfred-it** [comment]
No, but it's easily overridable via Stylish

https://github.com/sindresorhus/refined-github/pull/643/files
