### ISSUE TITLE
"null" appended to body on notification's page

### ISSUE THREAD

**Issue by jridgewell** [sindresorhus/refined-github#1026]
It's the `open-all-notifications` extension that's causing it. Likely https://github.com/sindresorhus/refined-github/blob/09041df0/source/features/open-all-notifications.js#L36?

<img width="1440" alt="screen shot 2018-01-22 at 11 12 21 pm" src="https://user-images.githubusercontent.com/112982/35262533-e9648f38-ffc9-11e7-9478-1be1888baf73.png">

**Comment by bfred-it** [comment]
It's a feature.

😛 

This should be solved by an IF; PRs welcome!
