### ISSUE TITLE
Add button to see the latest version of file/folder

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1029]
You ended up on a file in a random revision:

> <img width="240" alt="random revision" src="https://user-images.githubusercontent.com/1402241/35318397-bfb31d72-010d-11e8-8a11-813898a3112c.png">

How do you get to `master`?

> <img width="340" alt="bunch of branches" src="https://user-images.githubusercontent.com/1402241/35318415-cffd2a38-010d-11e8-88ec-f154f1dd461c.png">

Oh god.

What if... ?

> <img width="239" alt="goto HEAD" src="https://user-images.githubusercontent.com/1402241/35318432-eacf075a-010d-11e8-8033-b3efd9d2db01.png"> (better icon needed, perhaps)

However finding HEAD is not always easy. We can literally use `HEAD` in the link, but that would not enable the edit/delete buttons. Example: https://github.com/sindresorhus/refined-github/blob/HEAD/source/content.js

Only folders seem to have this piece of information available on the page, so we might at least provide a link on these pages:

<img width="446" alt="HEAD info on directories" src="https://user-images.githubusercontent.com/1402241/35318568-7336d500-010e-11e8-9abd-9f9d60456732.png">

**Comment by bfred-it** [comment]
Possible solution:

- link to `user/repo?rgh-head-redirect=file.js`
- detect `?rgh-head-redirect=file.js` as early as possible, find current branch, redirect to it

The current branch is found in the `<head>` so we might get away with this before the first paint:

```html
<!-- Example code found in a repo root, where `source` is the default branch -->
<link href="https://github.com/download-directory/download-directory.github.io/commits/source.atom" rel="alternate" title="Recent Commits to download-directory.github.io:source" type="application/atom+xml">
```

It requires an extra HTTP request, but it's _on demand_, we don't have to make it unless its necessary.

**Comment by sindresorhus** [comment]
> It requires an extra HTTP request, but it's on demand, we don't have to make it unless it's explicitly requested.

👍

**Comment by bfred-it** [comment]
Related feature that would/could/should be merged:

https://github.com/sindresorhus/refined-github/pull/395#issuecomment-301186914

![image](https://cloud.githubusercontent.com/assets/506129/26017093/96ba7a94-3770-11e7-84f2-462e475a846b.png) (but with the design I suggested)
