### ISSUE TITLE
Show base branch in PR list when different than master

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#103]
I am not sure how hard this is if even possible, but I would really like to have it.

So to reiterate I want the PR list to show a PR is made towards a base branch which is different than the default branch (usually `master`).

![screen shot 2016-03-29 at 01 05 48](https://cloud.githubusercontent.com/assets/506129/14091713/7da5b956-f54a-11e5-905b-c33241647763.png)

This is not so useful when all PRs are against master, but when some of them are against another branch in many cases towards another open PR it is very useful to see this from the PR list.

**Comment by sindresorhus** [comment]
:+1: I could see this being useful for many larger projects.

**Comment by paulmolluzzo** [comment]
👍  on this suggestion, but I don't know how to find the base branch except on the PR page. Wouldn't exactly want to `get` every page to parse out a single word...

**Comment by DrewML** [comment]
I *think* we might be able to pull this off with 1 HTTP request, but it might be a bit funky.

[The "List Pull Requests" API endpoint](https://developer.github.com/v3/pulls/#list-pull-requests) will return the base branch for a list of PRs.

The tricky part is, to make sure that we get all the PRs on the page in 1 request, we would need to match the filtering settings on the page to be included in our API request. However, more filtering options are exposed in the UI than in the API :laughing:.

**Comment by paulmolluzzo** [comment]
> The "List Pull Requests" API endpoint will return the base branch for a list of PRs.

This requires authentication...

> The tricky part is, to make sure that we get all the PRs on the page in 1 request, we would need to match the filtering settings on the page to be included in our API request. However, more filtering options are exposed in the UI than in the API :laughing:.

That seems super complex anyway.

The simplest "single request" I can think of is grabbing and parsing each PRs page. But that's 1 request _per PR_ so probably too many to make feasible.

**Comment by DrewML** [comment]
I believe you get a limited # of API requests from an I.P. without auth (can be verified by making an API call from the console in the browser). This is what `OctoTree` uses to get file info in the tree.

But I agree, it's super complex and isn't going to be very accurate.

I'll keep my eyes peeled for an easier way, but this one may just not be possible to do reasonably.

**Comment by paulmolluzzo** [comment]
Everything private is behind user auth.

**Comment by DrewML** [comment]
Ah yeah - forgot for a minute that people use this on Private repositories :laughing:

**Comment by bfred-it** [comment]
Is this needed in the main list or would https://github.com/sindresorhus/refined-github/pull/455 suffice? After https://github.com/sindresorhus/refined-github/pull/1115 we know what the default branch is for each repo (although we're currently only saving it in `sessionStorage`)

**Comment by sindresorhus** [comment]
@bfred-it This is for the main list, and #455 was never merged.
