### ISSUE TITLE
Enable data sync for Mark as Unread feature

### ISSUE THREAD

**Issue by shivapoudel** [sindresorhus/refined-github#1036]
Mark as unread data are not synced in other devices. Is this possible :)

**Comment by bfred-it** [comment]
This is possible. PR welcome for:

- changing `browser.storage.local` to `browser.storage.sync`
- adding a migration from `local` to `sync` if any threads are stored
- possibly handling storage limits because `sync` has only 4KB

**Comment by sindresorhus** [comment]
Now that GitHub has implemented notifications bookmarking, we don't intend to add more to the "mark as unread" feature as it will probably become moot in the near future.
