### ISSUE TITLE
Confirm dialog before closing the window if unsaved changes

### ISSUE THREAD

**Issue by lex111** [sindresorhus/refined-github#1037]
Yeah, I noticed that the entered data is saved, and when page (issue, eg) are reopened they are inserted into the input fields, it's good if there is a sudden light outage, for example. But if I have many many tabs and write a comment in the issue and accidentally close it (:man_facepalming:), then it would be nice if the confirm dialog was displayed before the page was closed so that this one would not close. How do you like this idea?

**Comment by bfred-it** [comment]
It's nice in theory, but probably annoying in practice.

GH does save comments... except inline comments, so this feature would also save those.

I wouldn't mind giving it a try, if you're willing to implement it.

**Comment by fregante** [comment]
I think this can be replaced by https://github.com/sindresorhus/refined-github/issues/1598
