### ISSUE TITLE
Feature suggestion: Toggle word diff

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1040]
Exactly what was proposed here: https://stackoverflow.com/questions/39055982/possible-to-enable-the-word-diff-option-in-github-to-see-more-granular-changes-t

Related discussion: https://github.com/isaacs/github/issues/832

Toggle the GitHub diff to have word-based diff. Similar to the `git-diff --word-diff` toggle.

![image](https://user-images.githubusercontent.com/506129/35454184-b5038a6e-02d5-11e8-95bd-e0ba21b92a15.png)

**Comment by hkdobrev** [comment]
Clarification and motivation:
- Sometimes GitHub would colour the changed words, but it's not consistent, it would not do it for long lines and not always at the right place.
- The word-based diff shows the difference on a single line merging the words before/after by just adding colours and +/- signs. When GitHub is colouring words in a diff they still show it on two lines for before and after. Very similar to how [`diff-so-fancy`](https://github.com/so-fancy/diff-so-fancy) works.

Suggested implementation:

- Use an external library for finding the different words in two lines. Preferably using the default Git algorithm. The default diff algorithm is `myers`, but this for finding the lines which changed, it doesn't actually work on words and presentation. I couldn't find if there's a specific algorithm for the word diff.
- Have a button when using the Unified diff which would merge the lines having differences, removing the green/red backgrounds, apply a slightly different background and would apply the `--word-diff=color` mode on the words that have changed colouring them in red/green. This would work especially well on Markdown and text where word-based diff is most useful.
- Probably the button should be per file as this may not be performant on a large changeset.

**Comment by bfred-it** [comment]
I think this would be pretty complicated to build since any tool that we might use for this works on plain text and we have to deal with syntax-highlighted dom.

**Comment by sindresorhus** [comment]
Would be nice to have, but I don't think it's worth the amount of work it would require to build and maintain.

**Comment by marchy** [comment]
@sindresorhus Imagine the work that it places upon the world to go through diffs that don't have this, use external tools to make diffing saner, and.

It is absolutely worth the effort of building this ONCE, to save the world of developers time from doing this over and over again for all their projects, all their PRs/commits, going forward.

Please re-open and reconsider making this a priority.

You can look to P4Merge for the best example of a tool that does this fantastically.

**Comment by bfred-it** [comment]
This can't be part of Refined GitHub. Feel free to request on https://github.com/sindresorhus/module-requests or at https://github.com/contact
