### ISSUE TITLE
Group dashboard events by day

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1046]
Something as easy as adding a `h4` between events:

<img width="677" alt="example" src="https://user-images.githubusercontent.com/1402241/35494815-cc6eff82-04ef-11e8-9982-0765ef7663fb.png">

(screenshot based on #1045)

**Comment by sindresorhus** [comment]
Why?

**Comment by sindresorhus** [comment]
> Just... more info?

Less is more?

Like, why does it matter when exactly it happened? What do you get from knowing `chnl` starred something yesterday and not today? If you really care you can just look at the relative times on the right. I don't really see any gain by grouping.

**Comment by bfred-it** [comment]
Consistency with the commits list? 😄 

https://github.com/sindresorhus/refined-github/commits/master
