### ISSUE TITLE
Collapse .snap files automatically inside PR

### ISSUE THREAD

**Issue by olso** [sindresorhus/refined-github#1047]

**Comment by bfred-it** [comment]
More info needed

**Comment by bfred-it** [comment]
I assume you're talking about Eclipse's snap files. These files should not be committed in the first place.

**Comment by sindresorhus** [comment]
@bfred-it I think he means test snapshot files. Example: https://github.com/sindresorhus/react-extras/blob/master/test/snapshots/test.js.snap

**Comment by sindresorhus** [comment]
Based on the arguments in https://github.com/github/linguist/pull/3579, this is not something we would want to do.

Also, note that which files are collapsed is controlled by metadata in https://github.com/github/linguist So future issues like this should just be opened there.
