### ISSUE TITLE
Default to Sources in the user repository tab

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1048]
Repositories tab:

https://github.com/bfred-it?tab=repositories

Desired default link:

https://github.com/bfred-it?tab=repositories&type=source

Implementation similar to: 

https://github.com/sindresorhus/refined-github/blob/0d47a23a4ece92a9b72f92f45e46e0fdca81bf3f/source/features/sort-issues-by-update-time.js#L24-L35

**Comment by sindresorhus** [comment]
Yes, please! :)
