### ISSUE TITLE
Branch name link points to 404 when branch is deleted

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#105]
We could detect when a branch for a PR is deleted and not linkify it.

For example see https://github.com/algolia/algoliasearch-client-php/pull/70, you could see the branch is deleted from the PR timeline, but have still linked to it.

**Comment by sindresorhus** [comment]
Not funkifying might be surprising. Maybe worth having a tooltip saying why it's not linkified? It will also not be able to detect when the branch is not in the same repo.

-

Also noticed the `master` branch is not linkified in the referenced pull request. Weird.

**Comment by hkdobrev** [comment]
> Also noticed the master branch is not linkified in the referenced pull request. Weird.
@sindresorhus The `master` branch is linkified for me in both occurrences.

**Comment by sindresorhus** [comment]
> The master branch is linkified for me in both occurrences.

Weird. Can't seem to reproduce anymore. I got the underline on hover, but it was unclickable and no cursor change. Anyways. Works now.

**Comment by paulmolluzzo** [comment]
> Maybe worth having a tooltip saying why it's not linkified?

I think we hid all the tooltips. 😉

**Comment by sindresorhus** [comment]
@paulmolluzzo And we have the 💪 to reverse that.

**Comment by sindresorhus** [comment]
So let's go with tooltip then.

**Comment by paulmolluzzo** [comment]
>  And we have the 💪 to reverse that.

Yeah, just pointing out we'd have to loosen the CSS.

How are we going to know the link is broken? `.get()` it in the background and if it responds 404 update the link?

**Comment by sindresorhus** [comment]
> How are we going to know the link is broken? .get() it in the background and if it responds 404 update the link?

That was my thinking. You could do a HEAD request which is pretty fast.

**Comment by hkdobrev** [comment]
> How are we going to know the link is broken? .get() it in the background and if it responds 404 update the link?

> That was my thinking. You could do a HEAD request which is pretty fast.

Why not just check for the deleted message in the timeline?

![screen shot 2016-10-24 at 23 46 05](https://cloud.githubusercontent.com/assets/506129/19663316/13b07122-9a44-11e6-82f3-444fd5620743.png)

**Comment by sindresorhus** [comment]
@hkdobrev I think a HEAD request would be much faster than parsing the timeline.

**Comment by bfred-it** [comment]
@sindresorhus in what world? `document.querySelector('.discussion-item-head_ref_deleted')` takes 0.1ms on the [most commented PR](https://github.com/sindresorhus/refined-github/pull/145) on this repo, that's outside the realm of HTTP timings.

**Comment by sindresorhus** [comment]
@bfred-it I'm confused too. I was definitely wrong. I might have misunderstood something.
