### ISSUE TITLE
Mark Merge Commits feature broken

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1052]
GitHub changed the style 

Demo page: https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104

Broken code: https://github.com/sindresorhus/refined-github/blob/373164c7f6cb094db746a44acabee967c7d9aff4/source/features/mark-merge-commits-in-list.js#L8

# Before

<img width="461" alt="screenshot" src="https://cloud.githubusercontent.com/assets/170270/14101222/2fe2c24a-f5bd-11e5-8b1f-4e589917d4c4.png">

# After

<img width="461" alt="screenshot" src="https://user-images.githubusercontent.com/1402241/35562248-5ed43bbc-05e5-11e8-90a3-e0d44532985b.png">

```
Uncaught (in promise) TypeError: Cannot read property 'prepend' of null
    at mark_merge_commits_in_list (content.js:1952)
    at enableFeature (content.js:816)
    at <anonymous>
```

**Comment by busches** [comment]
As always, this change hasn't happened to GHE yet, please keep that in mind when fixing it. :)

**Comment by salmanulfarzy** [comment]
Related: https://github.com/blog/2496-commit-together-with-co-authors
