### ISSUE TITLE
Link to commit page from PR commit

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1053]
PR commit: 
```
https://github.com/sindresorhus/refined-github/pull/1045/commits/b7137144f3df9a77f80c78ca63bf43322b2cf621
```

Commit page:
```
https://github.com/sindresorhus/refined-github/commit/b7137144f3df9a77f80c78ca63bf43322b2cf621
```

The commit page still has things missing from the PR commit page like:
- the conversation for a commit
- the commit parent
- a different rendering of the changed files.

Could we link the commit hash on the PR commit page to the commit-specific page?

**Comment by hkdobrev** [comment]
@bfred-it Just noticed the link shortener produces a bug here.

Converts that:
```
https://github.com/sindresorhus/refined-github/pull/1045/commits/b7137144f3df9a77f80c78ca63bf43322b2cf621
```
to
```
https://github.com/sindresorhus/refined-github/commit/b7137144f3df9a77f80c78ca63bf43322b2cf621
```

**Comment by bfred-it** [comment]
No, that's GitHub itself. The shortener doesn't change the `href`

**Comment by hkdobrev** [comment]
> No, that's GitHub itself. The shortener doesn't change the `href`

SAD :(

**Comment by bfred-it** [comment]
Live link in this comment: https://github.com/sindresorhus/refined-github/issues/212#issuecomment-317926159

We can't fix this, the original link does not appear in the DOM.

**Comment by bfred-it** [comment]
The only solution we could offer would be during the _posting_ of a link, by wrapping a raw link with `[]()` and GitHub won't break it.

**Comment by bfred-it** [comment]
I'm reporting it to GitHub, please do so too, even if just by copy-pasting this:

```
Commit link shortening bug: PR commit links only link to the commit
```

```
This is a PR commit link:

https://github.com/sindresorhus/refined-github/pull/1119/commits/0f51dfe30eb36e60369a188786d88b6e421f1543

Paste that into a comment, you'll see that it's shortened to "0f51dfe" and it will link to:

https://github.com/sindresorhus/refined-github/commit/0f51dfe30eb36e60369a188786d88b6e421f1543

Which is a link outside the PR, it's a different view.

Bug initially reported in: https://github.com/sindresorhus/refined-github/issues/1053
```

**Comment by borekb** [comment]
Does the GitHub bug block the original request? I'm not sure I entirely follow what the problem is but there are already `.patch` and `.diff` links that work correctly; the commit link is almost the same so it feels like it should be possible to extract it somehow and use it to linkify the commit hash as well?

**Comment by bfred-it** [comment]
Check out @hkdobrev this link:

```
https://github.com/sindresorhus/refined-github/pull/1045/commits/b7137144f3df9a77f80c78ca63bf43322b2cf621
```

Refined GitHub is taking care of linkifying it so it works correctly.

Now here's the same link pasted directly without wrapping it in `<pre>`:

https://github.com/sindresorhus/refined-github/pull/1045/commits/b7137144f3df9a77f80c78ca63bf43322b2cf621


As you can see, GitHub shortens it to be a commit link... but forgets the PR part. Opening it will not show any link to the PR #1045

**Comment by borekb** [comment]
Sorry, I might be slower today but I think the feature request is this (@hkdobrev, please correct me if I'm wrong):

![image](https://user-images.githubusercontent.com/101152/42960595-9129244c-8b8c-11e8-90f9-bef89f0aa73a.png)

How is this related to linkification inside the comment box?

**Comment by bfred-it** [comment]
That's not what he's asking

**Comment by bfred-it** [comment]
@borekb I might have missed that point entirely.

> Could we link the commit hash on the PR commit page to the commit-specific page?

@hkdobrev to clarify, do you want to link this 

<img width="1035" alt="" src="https://user-images.githubusercontent.com/1402241/42961370-e80cc06e-8b8e-11e8-90e6-50feb92ba3ab.png">

To this page?

<img width="1034" alt="" src="https://user-images.githubusercontent.com/1402241/42961378-ec3c6c0c-8b8e-11e8-817a-38ae754860e9.png">

If yes, why?

**Comment by bfred-it** [comment]
@borekb I think you're right, I got distracted by the GitHub bug.

**Comment by borekb** [comment]
Thanks for confirming, in my case, the reasons are similar to the OP:

- The commit page has slightly different (sometimes preferable) rendering
- The commit might be in multiple PRs, the commit page links to them
- There might be conversation for the plain commit
- The commit page shows commit parent

It's a small convenience, in my opinion similar to linkifying a branch name on the PR page.

**Comment by borekb** [comment]
`good first issue`, I might take it to contribute back to this awesome project! Can I start working on it or does this issue need further confirmation that this is something that you, maintainers, are interested in happening?

**Comment by bfred-it** [comment]
Yeah you can go ahead

**Comment by borekb** [comment]
PR: #1429. Most of the time, I didn't know what I was doing :) But making live changes to a Chrome extension was an interesting experience.

**Comment by bfred-it** [comment]
@lukehefson can we solve this long-standing papercut? 😅  https://github.com/sindresorhus/refined-github/issues/1053#issuecomment-375200239

**Comment by lukehefson** [comment]
I'll dig in!
