### ISSUE TITLE
Show link to tag a new release when a PR is merged

### ISSUE THREAD

**Issue by fenollp** [sindresorhus/refined-github#1054]
Saves a few clicks. Might help some to release more often!

To not clutter the PR page too much the link should appear after the PR is merged / branch deleted.

cc https://github.com/sindresorhus/refined-github/issues/1024

**Comment by bfred-it** [comment]
Source: https://github.com/sindresorhus/linkify-urls/pull/15

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but we're going to pass on this. I would find this more annoying than helpful. I don't release after every PR, and most projects cannot release directly from the GitHub UI.
