### ISSUE TITLE
Hide `${user} added ${user2} to ${repo}`

### ISSUE THREAD

**Issue by bevacqua** [sindresorhus/refined-github#106]
As annoying as ever. I never cared about who gets added where. I pretty much only care about people starring/forking interesting stuff, issues, and pull requests.

<img width="456" alt="screen shot 2016-03-29 at 14 10 03" src="https://cloud.githubusercontent.com/assets/934293/14116793/f5328572-f5b7-11e5-9409-5334ae3f6741.png">

**Comment by sindresorhus** [comment]
:+1: :+1: :+1:

**Comment by bevacqua** [comment]
Since posting this issue:

<img width="568" alt="screen shot 2016-03-29 at 14 22 27" src="https://cloud.githubusercontent.com/assets/934293/14117300/78a935fc-f5ba-11e5-866b-a3e382781bb2.png">

:cry:

**Comment by sindresorhus** [comment]
Ugh, yeah...

<img width="473" alt="screen shot 2016-03-30 at 00 18 58" src="https://cloud.githubusercontent.com/assets/170270/14117607/8d03ce04-f60f-11e5-8d8c-db622b51d240.png">
