### ISSUE TITLE
GitHub topics leaderboard - more stars?

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1060]
I've just read [GitHub latest blog post on topic pages](https://github.com/blog/2497-contribute-to-popular-topics-on-github) and I've noticed Refined GitHub is

- 2nd in [`chrome-extension`](https://github.com/topics/chrome-extension) 🥈 
- 2nd in [`browser-extension`](https://github.com/topics/browser-extension) 🥈 
- 1st in [`firefox-addon`](https://github.com/topics/firefox-addon) 🥇 

The above is based on the number of stars 🌟

🙌

The extension also has more than 11,000 users across Chrome Web Store and Firefox Add-ons.

🎉 

I was thinking whether we could post to HN /  Reddit to gather more users, stars and contributors or that would put an even bigger toll on maintainers?

**Comment by bfred-it** [comment]
Sharing elsewhere is fine. I think we'll get the extra 100 stars pretty soon anyway, I average 6 stars per day in the last 6 months

**Comment by bfred-it** [comment]
As expected :) 

<img width="606" src="https://user-images.githubusercontent.com/1402241/36416892-f838b26a-165c-11e8-81fb-e992eda63d6f.png">

**Comment by hkdobrev** [comment]
And 3rd in browser extension as a more popular extension started using topics.

Anyway, I'll close this one as it was mostly about celebration and gather thoughts :)
