### ISSUE TITLE
Open all unreads in tabs for a specific repository

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1062]
<img width="746" alt="screen shot 2018-02-04 at 11 46 19" src="https://user-images.githubusercontent.com/5759366/35776669-0cf86718-09a1-11e8-9d26-bdb57757cf7f.png">

Here I'd like to go through Arrow and have an open all tabs button that only opens Arrow related pages.

This helps breaking down changes on a repository based pattern.

I'd imagine that there could be a button to do so next to the checkmark icon.

**Comment by ramlmn** [comment]
RGH already has this https://github.com/sindresorhus/refined-github/pull/973

**Comment by vanniktech** [comment]
Interesting. Would it be possible to also show this button on the front page? It's more visible there and easier to find then selecting a single repository on the left navigation bar.

**Comment by yakov116** [comment]
@vanniktech it will clutter the page imho

**Comment by vanniktech** [comment]
Then let's wait for some feedback and use 👍 and 👎 on the initial post to see what users of this plugin would actually like?

**Comment by hkdobrev** [comment]
👍 for using an icon. The external icon is quite used throughout many websites so most GitHub users should recognise it. Let's do it!

@vanniktech Do you think you could try submitting a pull request for this? Thanks!

**Comment by vanniktech** [comment]
I for sure want to contribute to this repository in the future but currently time is tight. So don't wait for me to implement this in case anyone wants to grab this first.
