### ISSUE TITLE
Translate for issues (like twitter)

### ISSUE THREAD

**Issue by iamstarkov** [sindresorhus/refined-github#1064]
<img width="492" alt="screen shot 2018-02-04 at 9 07 36 pm" src="https://user-images.githubusercontent.com/559321/35781864-dbd4ceac-09ef-11e8-8ef2-4af20f5574cf.png">

or in action

![kapture 2018-02-04 at 21 10 03](https://user-images.githubusercontent.com/559321/35781867-e4f10424-09ef-11e8-8931-23bb481cefdf.gif)

Use cases:

a) Some project get a lot of international attention and sometimes new comers dont realize default language is english, so they file issues in their native languages.
b) you find an interesting project but, maintainers keep issues in their native language, but you still want to understand, what they are talking about

What do you think?

**Comment by bfred-it** [comment]
Agreed on all points. Yes, most browsers offer a way, natively or via extension, to translate the page.

**Comment by EmmanuelMess** [comment]
[Entire repos](https://github.com/search?q=%E8%AF%91) are in Chinese, and the problem of the language barrier isn't easy to fix, please add the posibility to autotranslate, as Google Translate usually [breaks the layout horribly](https://translate.google.com/translate?sl=auto&tl=en&u=https%3A%2F%2Fgithub.com%2Fscutan90%2FDeepLearning-500-questions).
