### ISSUE TITLE
Show actor real name in dashboard events

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1065]
Similar to comments where we show the user's name next to their username, that would be useful to show the full name of the actor performing the action.

![image](https://user-images.githubusercontent.com/506129/35797953-01bbd00a-0a6a-11e8-9de5-1a46ae42369d.png)

In this example, I didn't realise `gaeron` is Dan Abramov, but this would have been useful to know.

**Comment by bfred-it** [comment]
Do we really want to add the full name everywhere? 

#922 went the opposite way: leave only the avatar

**Comment by hkdobrev** [comment]
If you work with someone on a regular basis the avatar is definitely the thing you can recognise them by quickly while scanning content - that's just how the brain works - images are quicker to recognise as we process them on a very basic level very fast. This is what I constantly use in conversations to recognise who said what and who participated (I have another suggestion about that).

However, in the dashboard, I would have more people who I've followed, but don't see their avatars on a day-to-day basis. Here, I've recognised his avatar only because I was referred to some of his Tweets the other day. But I remember quite more names, so having the famous name there would bring my attention to that post if I read the name. I can decide to look further into the starred repo.

**Comment by busches** [comment]
I'd like the name, as 99% of people in my enterprise appears to be OK using the default avatar.
