### ISSUE TITLE
Remove user avatar from new comment form on threads

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1066]
While scanning a conversation, I inadvertently scan for my avatar as well to see if I've commented and on which threads I've participated in (related: #1065). However, I see my own avatar on each new comment form in each thread.

Suggestion: Remove your own avatar from the Reply form in PR review threads.

**Now**

![image](https://user-images.githubusercontent.com/506129/35822311-8e648070-0ab4-11e8-8b14-f80dc31a847c.png)

**After**

![image](https://user-images.githubusercontent.com/506129/35833209-e8fd7c52-0ad8-11e8-99d1-68cbf7ace7de.png)

Let me know your thoughts and I can submit a PR with an implementation!

---
> _Side note_
> I'm not sure how much your own avatar is useful on the new comment form at the bottom either, but the threads ones are more misleading as they could occur multiple times.
> ![image](https://user-images.githubusercontent.com/506129/35822327-9ad9e8f4-0ab4-11e8-8263-89573ea477ca.png)

**Comment by yakov116** [comment]
100% agree

**Comment by notlmn** [comment]
@hkdobrev Are you still working on this, or can I pick it up?
