### ISSUE TITLE
Keyboard shortcut for submitting the review changes on a PR

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1069]
Edit by @fregante: this issue can be solved by following https://github.com/sindresorhus/refined-github/issues/3095

---

Given I'm on a PR and review the files I'd like to hit a keyboard shortcut to let me review the changes. Possibly, `r` could be used.

Then for accepting, rejecting, or commenting we could use `a`, `r` and `c`.

Shortcuts for immediately accepting / rejecting / commenting from the PR file page itself would also be nice. Maybe something like

```
r + a => accept
r + r => reject
r + c => comment
```

**Comment by bfred-it** [comment]
I think these would make sense as shortcuts in the review popup, but if you're in there chances are you're typing the comment, so simply `r+*` wouldn't work, it needs a modifier key.

**Comment by vanniktech** [comment]
Is there any preference regarding a designated modifier key?

**Comment by bfred-it** [comment]
No preference

**Comment by hkdobrev** [comment]
`r` is already a shortcut provided by GitHub - it quotes selected text and replies to a conversation in a new comment.

`meta + r` is Reload in most browsers.

I'd like that to work on the Conversation view as well. There's a link in the footer which opens the Files changed tab with a review panel opened.

**Comment by bfred-it** [comment]
> There's a link in the footer which opens the Files changed tab with a review panel opened.

hmm which one? Screenshot?

**Comment by hkdobrev** [comment]
Hmm, it seems it shows only when you've requested changes, GitHub shows a shortcut "Approve changes" in the review status section at the bottom.

**Comment by bfred-it** [comment]
Are you talking about this? If not, screenshot please

<img width="789" alt="" src="https://user-images.githubusercontent.com/1402241/37026555-5e06a00c-2161-11e8-8c1a-96478b37f19a.png">

If yes, that's a one-click approval, it doesn't open the Files tab. Maybe it shouldn't have a shortcut

**Comment by hkdobrev** [comment]
Yes, I couldn't find it on my PRs at the moment.

Also, there's another button in a yellow bar when you first see a PR after a review was requested and you haven't added review comments. That button opens the Files changed tab with the review panel open. However, I can't find such an example either. I'll screenshot it when I see it.

**Comment by vanniktech** [comment]
Those approve changes and dismiss review buttons I'd not include in the initial version of the shorcuts. Instead I'd just include these:

![screen shot 2018-03-06 at 11 28 59](https://user-images.githubusercontent.com/5759366/37027447-9535b2be-2131-11e8-9448-0d7213f495cb.png)

**Comment by bfred-it** [comment]
@vanniktech sounds good! Keep in mind that `comment` already has a shortcut: `meta`+`enter`. I don't particularly like it, but it might be a hassle to prevent that. So let's just focus on the two buttons and add `aria-label` on them

**Comment by hkdobrev** [comment]
That's the link for opening Files changed tab with review panel open:

https://github.com/owner/repo/pull/ID/files#submit-review

**Comment by ProLoser** [comment]
I don't think I need a distinct shortcut for comment, reject and approve. I only need a shortcut to open and highlight this form after I've done all my inline-code comments. Once the form is focused, I can type any overall message and then tab to the relevant submission button.

**Comment by hkdobrev** [comment]
👍 I think the textarea should be focused by default when the review form is opened. You can always use Cmd+Enter or Tab. Not focused textarea doesn't give you focused buttons anyway.

**Comment by sindresorhus** [comment]
PR welcome :)

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by fregante** [comment]
This seems easy:

```tsx
select('.js-reviews-toggle')!.dataHotkey = 'g r';
delegate(',js-dropdown-details > details', 'toggle', ({delegateTarget}) => {
	if (delegateTarget.open) {
		select('textarea', delegateTarget)!.focus();
	}
}, true);
```

Anyone who wants it just needs to ensure this works, add this to `quick-review-buttons` and add documentation for it. Follow `contribute.md`

**Comment by pradeepgangwar** [comment]
ww

**Comment by fregante** [comment]
Unlocking this to discuss an alternative shortcut since [`g r` is used by `releases-tab`](https://github.com/sindresorhus/refined-github/pull/3149/commits/b477aad33a3dd3e83d1481c466b9c73210c28f1a)

**Comment by FloEdelmann** [comment]
I also don't like <kbd>v</kbd> as a shortcut for "Review" too much, but other options were already taken:

* <kbd>r</kbd>: Reply (quoting selected text) (native GitHub)
* <kbd>g</kbd> <kbd>r</kbd>: Go to Releases (RGH's `releases-tab`)
* <kbd>c</kbd> (for "review **c**hanges"): Create issue (native GitHub)
* <kbd>g</kbd> <kbd>c</kbd>: Go to Code (native GitHub)

<kbd>g</kbd> <kbd>5</kbd> would fit well alongside these (from RGH's `pull-request-hotkey`), but would wrongly imply that review was a separate tab.

![Screenshot_2020-05-30_13-22-37](https://user-images.githubusercontent.com/202916/83326972-a8ccf100-a278-11ea-94f2-1ec4bf899a52.png)


So I settled with <kbd>v</kbd> for "re**v**iew".

**Comment by sseo289** [comment]
https://crackzero.com/ccleaner-professional-crack/

https://crackzero.com/ccleaner-professional-crack/

https://crackzero.com/ccleaner-professional-crack/

https://crackzero.com/ccleaner-professional-crack/


https://crackzero.com/ccleaner-professional-crack/


https://crackzero.com/ccleaner-professional-crack/


https://crackzero.com/ccleaner-professional-crack/


https://crackzero.com/ccleaner-professional-crack/


https://crackzero.com/ccleaner-professional-crack/
