### ISSUE TITLE
J + K navigation for scrolling down / up when reviewing a PR

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1070]
Vim like shortcuts for scrolling in a PR by using `j` for scrolling down and `k` for scrolling up would be super beneficial.

**Comment by bfred-it** [comment]
`j`/`k` are previous/next... in this case what are we scrolling?

**Comment by vanniktech** [comment]
Basically scrolling up and down as you'd do with the arrow keys.

**Comment by bfred-it** [comment]
Why not use the arrow keys?

**Comment by vanniktech** [comment]
Further away plus if you use the other - to come - shortcuts you would not need to move your hands. Especially if you're used to typing blindly in the 10 finger system.

**Comment by bfred-it** [comment]
Nah, if you want to scroll with j/k you can likely set that up to be global rather than just on GitHub

**Comment by vanniktech** [comment]
Just for the record. This [chrome plugin](https://chrome.google.com/webstore/detail/shortkeys-custom-keyboard/logpjaacgmcbpdkdchjiaagddngobkck) works really well for this.

**Comment by hkdobrev** [comment]
I'd still like navigating to next/prev file with j/k similar to navigating issues/PRs and other lists on GitHub. That with a shortcut for collapsing files would make reviews of long PRs quite easier with the keyboard.
