### ISSUE TITLE
Highlight recent issues

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1073]
I noticed that since #935 it may be harder to notice what issues are newer (obviously), so perhaps when this feature is active, the issues should also be color-coded (`border-left`) like it happens in the blame view:

<img width="106" alt="blame view" src="https://user-images.githubusercontent.com/1402241/35900559-35c6622e-0c05-11e8-9ef7-62dc83071204.png">

One caveat: GitHub highlights unread items with a blue border, so we need to make sure that's preserved. This is the classes they use on the `li` to enable it: `js-issue-row unread`

<img width="123" alt="unread items" src="https://user-images.githubusercontent.com/1402241/35901750-ca3fbd42-0c0a-11e8-902a-20b6285851a8.png">

**Comment by sindresorhus** [comment]
I feel like the color coding would be more noisy than useful.
