### ISSUE TITLE
Linking to a single line in a diff still covered by header

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#1079]
Linking to single lines basically works everywhere now correctly.

But I found this issue left:
If you link to a single line in a diff the header will still cover the linked line.
That is the case for both, unified and split view!

I'm using 18.2.3.1507

**Comment by bfred-it** [comment]
It works in regular file views but not in some commits, like: https://github.com/sindresorhus/refined-github/commit/09041df0cba07b115bd0de437540bda271e6efb7#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L17

I think the selector needs to include also `.js-linkable-line-number.selected-line` here https://github.com/sindresorhus/refined-github/pull/1030/files

**Comment by bfred-it** [comment]
GH added this feature natively and RGH dropped it. Closing 🎉
