### ISSUE TITLE
Add option to hide people being added to repos.

### ISSUE THREAD

**Issue by thekemkid** [sindresorhus/refined-github#108]
![image](https://cloud.githubusercontent.com/assets/6907399/14119369/c20ed140-f5e5-11e5-87d4-c42180565d5a.png)

That pisses me off tbh, I hate seeing people shamelessly plugging themselves like that and it's unfair to popular devs to have to deal with that too. 

Related HN article/thingy: https://news.ycombinator.com/item?id=11382595

**Comment by sindresorhus** [comment]
This is already part of version 0.12.0 ;)

https://github.com/sindresorhus/refined-github/commit/40cee76e96c3ed3c48fe879fa19f47fd7f2d830c

(Might take up to 40 min before you see it if you had already installed the extension because of Chrome store slowness).

**Comment by thekemkid** [comment]
Oh! Thanks, I didn't see that :D
