### ISSUE TITLE
Issue with Vivaldi and support for GHE

### ISSUE THREAD

**Issue by diskostu** [sindresorhus/refined-github#1081]
Hey there,

I know there is already [a (closed) issue](https://github.com/sindresorhus/refined-github/issues/905) for Vivaldi support. The right-click-method to add a GHE domain does still not work in this browser.
Another extension named [Octotree](https://github.com/buunguyen/octotree/) allows to add a GHE url [within its settings](https://github.com/buunguyen/octotree/#enterprise-urls). Maybe this is something you can consider.

Thanks!

**Comment by sindresorhus** [comment]
Might be possible to improve something in https://github.com/bfred-it/webext-domain-permission-toggle, but closing this issue as Vivaldi is not a supported browser, so you're on your own here.
