### ISSUE TITLE
Use monospaced fonts for textareas

### ISSUE THREAD

**Issue by ramlmn** [sindresorhus/refined-github#1084]
Just an idea!

When writing code blocks inside comments on an issue or a PR, you don't know if the code indentation is right. This either requires you to use the *Preview* tab frequently or use an external editor (that swithes you from your browser for any small change).

This gets even complex when you write code blocks inside markdown list items (is it one space or two space?)
![image](https://user-images.githubusercontent.com/12368291/36138576-edc46114-10bf-11e8-840a-7ffe6c8229c5.png)

Which becomes easier when using monospaced fonts
![image](https://user-images.githubusercontent.com/12368291/36138530-c0afa76a-10bf-11e8-8aec-3959c9086fb5.png)

**Comment by rayfoss** [comment]
OMG THANK YOU... I WAS RIPPING MY HAIR AND ABOUT TO START WW3 over indentation issues, until I found this.
