### ISSUE TITLE
Re-enable some XO rules

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1086]
I had to disable them as I didn't have time to debug. These rules: https://github.com/sindresorhus/refined-github/blob/ffed6475d60c133d7e777947ec866e877537112e/package.json#L71-L72

I'm not sure why https://github.com/sindresorhus/refined-github/blob/ffed6475d60c133d7e777947ec866e877537112e/source/libs/page-detect.js#L40 is considered unsafe. https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/no-unsafe-regex.md

And `function-paren-newline` seems to not work well with JSX.

**Comment by bfred-it** [comment]
Addressed by https://github.com/sindresorhus/refined-github/commit/d919e73b79149824bb2fe04294a7fcbf1b69e652
