### ISSUE TITLE
unable to read long link in feeds 

### ISSUE THREAD

**Issue by mehdi-alouane** [sindresorhus/refined-github#109]
![screenshot from 2016-03-29 22 42 39](https://cloud.githubusercontent.com/assets/4208162/14124838/af9c27a0-f5ff-11e5-8db6-34b9c4ec891c.png)

**Comment by paulmolluzzo** [comment]
Is this a real scenario? I can only see the tops of the letters but it looks like random keyboard mashing.

**Comment by havenchyk** [comment]
@paulmolluzzo yes, it's real. ![example](http://i.imgur.com/zLBYq82.png)
Look at this [repo](https://github.com/jpwesselink/fbnpj0nifcpjy9x81nw5fnthimudcc2syslkucfrpqiivwizjqc7rgdw2upxre8v)

**Comment by paulmolluzzo** [comment]
@havenchyk LOL. OK
