### ISSUE TITLE
Cannot disable feature `show-recently-pushed-branches`

### ISSUE THREAD

**Issue by octref** [sindresorhus/refined-github#1091]
First, thanks for this extension!

However it seems I cannot disable the feature for showing recently pushed branches.

![image](https://user-images.githubusercontent.com/4033249/36294239-35b1644c-1294-11e8-8471-8f0501c17504.png)

**Comment by bfred-it** [comment]
Related #1018 

Why would you like to disable it?

**Comment by octref** [comment]
Sorry, should have tried searching for dups first.

#1092 is one reason. The other is in my private repo, I have multiple branches that represent multiple versions of a website. I constantly push to each branch independently to trigger rebuild and have no interest of merging any of them to master.

**Comment by bfred-it** [comment]
That's actually not a feature of Refined GitHub; this extension only moves it out of the way. Try disabling the extension and you'll see the branches there, but in a more annoying position.

If you want to hide it completely, use Stylish and:

```css
[data-url$='recently_touched_branches_list'] {
	display: none !important;
}
```
