### ISSUE TITLE
Customizable monospace font?

### ISSUE THREAD

**Issue by novemberborn** [sindresorhus/refined-github#1094]
#1089 is great, but jarring since it's not the monospace font I use when editing. #179 added 'Operator Mono' but it seems to have disappeared. Perhaps there could be an option for people to specify an explicit font preference?

**Comment by bfred-it** [comment]
No option, we just choose a good `font-family` for most and the others can disable or customize it with Stylish (which is perfect for this kind of customization)

**Comment by sindresorhus** [comment]
This is what we used to have https://github.com/sindresorhus/refined-github/blob/4666f169596665fada52adfd636d39d340c1c11a/extension/custom.css#L47

**Comment by bfred-it** [comment]
PR welcome to update it

**Comment by ganes1410** [comment]
@bfred-it  for which classes should i update?

**Comment by jerone** [comment]
Here is an article about the new fonts used on GitHub by the creator of Bootstrap: http://markdotto.com/2018/02/07/github-system-fonts/

**Comment by bfred-it** [comment]
@ganes1410 you can look for `monospace` in our CSS and replace it with Sindre's `font-family`

**Comment by bfred-it** [comment]
I remember we removed it once for a reason: https://github.com/sindresorhus/refined-github/issues/556

> If anyone misses this feature, see: https://github.com/sindresorhus/module-requests/issues/97
> [sindresorhus](https://github.com/sindresorhus/refined-github/issues/556#issuecomment-313517188)

**Comment by jef** [comment]
i found this from the previous comments:

https://github.com/sindresorhus/refined-github/blob/4666f169596665fada52adfd636d39d340c1c11a/extension/custom.css#L47

and added few extra CSS classes that GitHub has now. For example, in the Action's logs; `.text-mono`.

maybe we should add a wiki page to help demonstrate the CSS customization?

**Comment by i-am-the-slime** [comment]
I'd like to use a font that's hosted somewhere else, I tried importing it like this: 

```
@import url('https://cdn.jsdelivr.net/npm/victormono@1.4.2/dist/index.min.css');
code, pre, tt {
font-family: 'Victor Mono' !important;
}
```
Does anybody know what I'm doing wrong?

**Comment by aleclarson** [comment]
Sadly, Safari does not let websites reference user-installed fonts. Has anyone found a workaround for this? As @i-am-the-slime noted, using web-hosted fonts is a non starter.

**Comment by aleclarson** [comment]
Okay, so I found this ruby script that generates an webfont that is inline CSS via data URL: https://gist.github.com/glebm/6360088

But it seems that GitHub-Refined strips my `@font-face` statement, so it doesn't work. Why does it do this?

**Comment by fregante** [comment]
Options are limited to about 100KB so a whole font is unlikely to fit. You should install the font on your computer and use StackOverflow for further questions.
