### ISSUE TITLE
Easy copy code blocks from Markdown

### ISSUE THREAD

**Issue by lex111** [sindresorhus/refined-github#1095]
For example, insert some icon inside the code block, when you click on it, all the content will be copied to the clipboard.

**Comment by bfred-it** [comment]
I assume you're talking about code blocks in comments. I saw an extension like that a while ago but it wasn't particularly pretty.

Here's a code block for fun

```rust
for i in 1..101 {
    if i % 15 == 0 {
        println!("FizzBuzz");
    } else if i % 5 == 0 {
        println!("Buzz");
    } else if i % 3 == 0 {
        println!("Fizz");
    } else {
        println!("{}", i);
    }
}
```

**Comment by lex111** [comment]
No, how here's, for example https://store.docker.com/images/node

![image](https://user-images.githubusercontent.com/4408379/36355737-d7019018-14f8-11e8-93e4-285b69909ee3.png)

**Comment by lex111** [comment]
![image](https://user-images.githubusercontent.com/4408379/36356097-e25b78ca-14fd-11e8-836b-4d5f9c876adf.png)

**Comment by bfred-it** [comment]
That's what I said ;)

**Comment by Mottie** [comment]
If you're interested, I've got a userscript that'll allow you to [copy markdown code snippets](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-copy-code-snippet).

![](https://user-images.githubusercontent.com/136959/34900403-59897efc-f7c5-11e7-8a38-57bec1295305.gif)

**Comment by lex111** [comment]
@Mottie thank you! This is what I had in mind!

@bfred-it  Let's implement this in the extension!

**Comment by sindresorhus** [comment]
PR welcome.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by dguo** [comment]
If it helps, [CodeCopy](https://github.com/zenorocha/codecopy) is an open source extension that does this for many sites, including GitHub.

**Comment by bfred-it** [comment]
I'm not particularly fond of buttons like these (noise + they might get in the way) and since there are already options, maybe we don't need to include this in Refined GitHub

**Comment by fregante** [comment]
I think that there are existing options for this and we don't need to implement it in Refined GitHub.

**Comment by karlmutch** [comment]
I don't think the above statement is true.  It requires the reader to install a plugin/extension for their browser.  The script tag is also not permitted for very good reasons for very similar motivations.

I think this is a reasonable request please reconsider.

**Comment by busches** [comment]
@karlmutch having the feature in RGH also requires an extension.  RGH's goal is not to implement every feature possible, especially when existing options cover the feature.

**Comment by peters95** [comment]
+1 for this idea it would be better if this was supported out of the box vs client-side configuration.

**Comment by banagale** [comment]
+! Github has already implemented some form of this in the Settings -> Actions -> Add self-hosted runner page.:
<img width="723" alt="Screen Shot 2020-12-05 at 9 25 28 AM" src="https://user-images.githubusercontent.com/1409710/101259128-d7220200-36db-11eb-903c-2e8817111fb2.png">

It would be _very_ helpful if github wiki (and issues) got this as a markdown extension behavior.

**Comment by fregante** [comment]
Please use https://github.com/zenorocha/codecopy. It works and it's supported.

Reference: https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606764895

**Comment by fregante** [comment]
> requires the reader to install a plugin/extension for their browser.

I hope that people landing on this issue understand that **this repo is not owned by GitHub.** What people have been commenting on is already an extension. **This repo, Refined GitHub, is an extension**. Whatever is implemented by this repo **requires the reader to install a plugin/extension for their browser.**

Please use https://github.com/zenorocha/codecopy. It works and it's supported.

Reference: https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606764895

**Comment by fregante** [comment]
This is now supported natively by GitHub https://twitter.com/natfriedman/status/1391862005095485440?s=21
