### ISSUE TITLE
Add button to preview HTML files

### ISSUE THREAD

**Issue by benwaffle** [sindresorhus/refined-github#1096]
very useful for .html files

**Comment by sindresorhus** [comment]
Can you please elaborate a bit more about what you're looking for?

**Comment by benwaffle** [comment]
When i'm browsing a github repo and I want to see the webpage of an html file, i will paste it into rawgit.com

e.g. I see this file https://github.com/CodingTrain/website/blob/master/CodingChallenges/CC_11_PerlinNoiseTerrain_p5.js/index.html
so i go to http://rawgit.com, paste the URL, and get this: https://rawgit.com/CodingTrain/website/master/CodingChallenges/CC_11_PerlinNoiseTerrain_p5.js/index.html

**Comment by bfred-it** [comment]
The difference is subtle: 

```
RawGit serves raw files directly from GitHub with proper Content-Type headers.
```

I wouldn't add another Raw button that is _only sometimes_ different.

I probably wouldn't replace the current Raw button with one linked to rawgit (maybe? because it breaks expectations)

Not sure how discoverable it would be to add a _modifier_+click on the Raw button to open rawgit instead

**Comment by bfred-it** [comment]
Perhaps we can add a `View`/`Preview` button for HTML files, I think that's the only case where rawgit links are **visibly** different.

**Comment by benwaffle** [comment]
That would be useful

**Comment by theel0ja** [comment]
Something like this in Gists when the file is HTML:

![image](https://user-images.githubusercontent.com/5832930/39673027-75c8e3b0-513d-11e8-94e0-e0e8052e041b.png)

**Comment by sgabler** [comment]
I think this issue can be closed, as RawGit will soon shut down: https://rawgit.com/

> RawGit is now in a sunset phase and will soon shut down. It's been a fun five years, but all things must end.
> 
> GitHub repositories that served content through RawGit within the last month will continue to be served until at least October of 2019. URLs for other repositories are no longer being served.
> 
> If you're currently using RawGit, please stop using it as soon as you can.

**Comment by bfred-it** [comment]
Are there any alternative services?

**Comment by bfred-it** [comment]
No way! They’re closing it because of spam, no one here is gonna clone the service (and its issues) just to preview HTML files 😃

**Comment by bfred-it** [comment]
Staticaly.com seems to be an alternative service and it works correctly with HTML files:

Source: https://github.com/CodingTrain/website/blob/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html

Preview: https://cdn.staticaly.com/gh/CodingTrain/website/4f90eedb9618257d9166241e92e51a7f3f00a08e/code_challenges/PerlinNoiseTerrain_p5.js/index.html

**Comment by theel0ja** [comment]
Set up my own Rawgit instance (https://rawgit.theel0ja.info/) for my personal use

**Comment by berezovskyi** [comment]
https://raw.githack.com/ is the alternative that is not planning to shut down soon

**Comment by fregante** [comment]
This seems really easy:

```tsx
const rawButton = select('#raw-url');
if (rawButton && /\.html?/.test(rawButton.pathname)) {
	rawButton.after(
		<a href={rawButton.href.replace('https://github.com', 'https://cdn.staticaly.com/gh')}>Preview</a>
	);
}

features.add({
	...
	include: [
		isSingleFile
	],
	exclude: [
		isEnterprise
	]
})
```

Anyone who wants it, just needs to create a feature called `html-preview-link` and add documentation for it. Follow `contribute.md`
