### ISSUE TITLE
[Meta] XO did not report linter error on CI and allowed it to get merged

### ISSUE THREAD

**Issue by shroudedcode** [sindresorhus/refined-github#1101]
While working on #1099 I ran `npm run lint` and got the following error from XO:

```
source/features/monospace-textareas.js:2:3
  ✖    2:3   Expected indentation of 1 tab but found 2 spaces.    indent
```

<img align="right" src="https://ih1.redbubble.net/image.218566447.2648/flat,800x800,075,f.jpg" width=200>

I did not change that file and my editor also didn't touch it. I wondered how it got it got there since `npm run lint` is also run on Travis CI and pull requests are not merged when they contain linter errors.

I was confused but decided to not fix it since that was outside the scope of my pull request. So I committed my changes and created the pull request. Then, I waited for the build to fail. **But it didn't.**

That was weird, but I thought that `xo` maybe only lints new Git changes (or something like that) and decided to look for the commit that introduced this error. It turned out to be [this one](https://github.com/sindresorhus/refined-github/commit/e54b08875367e792a69a9677d8c083bcf8fb356f) — the squash commit of #1089. So, a pull request was indeed merged with a linter error. Why? Because XO [didn't report it while running on Travis CI](https://travis-ci.org/sindresorhus/refined-github/builds/341870231#L2983).

How on earth did XO report that error on my machine but not on Travis CI?
<sub>*Also, someone should fix the error.*</sub>

// @sindresorhus

**Comment by bfred-it** [comment]
Travis does have some warnings, can this be fixed?: 

```
npm WARN eslint-config-xo@0.20.0 requires a peer of eslint@>=4.9.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-unicorn@4.0.2 requires a peer of eslint@>=4 but none is installed. You must install peer dependencies yourself.

└─┬ xo@0.20.1
  ├── arrify@1.0.1 deduped
  ├── debug@3.1.0 deduped
  ├─┬ UNMET PEER DEPENDENCY eslint@4.17.0
```
