### ISSUE TITLE
Recently touched branches bar leaves white rectangle

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/refined-github#1106]
When running a custom theme with refined-github, a white rectangle is visible above the watch/star/fork buttons:

<img width="510" alt="screen shot 2018-02-21 at 19 12 09" src="https://user-images.githubusercontent.com/115237/36497299-d0c77794-1732-11e8-8d3f-c8324c2b2dbd.png">

When a recently touched branch is active, it renders like this:

<img width="521" alt="screen shot 2018-02-21 at 19 10 37" src="https://user-images.githubusercontent.com/115237/36497307-dbf8b31c-1732-11e8-9a0e-14730230d2b6.png">

This box's white background is used to overlay the watch/star/fork buttons and this effect is not compatible with non-white backgrounds.

Suggestion would be to instead hide the three buttons via CSS (triggered from JS) which would allow to remove the background.

**Comment by busches** [comment]
Since you're using a custom theme, isn't that a change that the theme should enable? Either change the white to the correct color or go with your solution to hide the buttons.

**Comment by silverwind** [comment]
We also support textured background (the default is one), so single colors won't do unfortunately.

**Comment by silverwind** [comment]
[Here's](https://github.com/StylishThemes/GitHub-Dark/issues/587#issuecomment-367421318) how it looks with the background removed.

Another suggestion might be to horizontally center the box. There's usually empty space there, especially on big screens.

**Comment by bfred-it** [comment]
We need a way to pick up the background color and reuse it. Suggestions?

**Comment by silverwind** [comment]
> We need a way to pick up the background color and reuse it. Suggestions?

Not possible as the background can be of non-uniform color when textured.

I think one solution could be a MutationObserver that hides `.pagehead-actions` via `opacity: 0` when the recently touched branches has non-empty content.

**Comment by Mottie** [comment]
Why does the container have to overlap the buttons?

<details>
<summary>In the screenshot on the main repo page, it is shown underneath.</summary>

![](https://user-images.githubusercontent.com/1402241/34099674-20433f60-e41b-11e7-8ca5-7ea23c70ab95.gif)
</details>

<details>
<summary>The width doesn't always match the width of the button group</summary>

![](https://user-images.githubusercontent.com/2352663/36467939-765fd9b4-16e1-11e8-8d26-2112f86d6b4f.png)
</details>
<details>
<summary>Also, please remove the extra whitespace when it's empty so we can use an `:empty` selector</summary>


![](https://user-images.githubusercontent.com/136959/36502839-bf9302f8-1710-11e8-9652-2d69ae4fb893.png)

</details>

**Comment by bfred-it** [comment]
> In the screenshot on the main repo page, it is shown underneath.

See https://github.com/sindresorhus/refined-github/issues/906#issuecomment-354484055

> The width doesn't always match the width of the button group

A few more pixels can be added

> Also, please remove the extra whitespace when it's empty so we can use an `:empty` selector

That element is added by GitHub, not Refined GitHub. To remove that space we'd have to listen for DOM changes and that's just unnecessary

**Comment by bfred-it** [comment]
> Not possible as the background can be of non-uniform color when textured.

Therefore this probably can't be fixed any better than how it's been fixed:

![](https://user-images.githubusercontent.com/115237/36497715-044a8b5a-1734-11e8-8206-3d084da61f08.png)

I'm opening an issue to discuss moving the feature somewhere else.

**Comment by jgierer12** [comment]
What if we `display: none;`/`opacity: 0; pointer-events: none;` GitHub's buttons instead?

**Comment by bfred-it** [comment]
Possible, we'd have to watch `include-fragment`, then watch the new `recently_touched_branches_list` div for branches inside. The current re-positioning is CSS-only

**Comment by Mottie** [comment]
> What if we `display: none;`...

Wouldn't it be better to set `visibility: hidden` on the GitHub buttons?

**Comment by silverwind** [comment]
> Wouldn't it be better to set visibility: hidden on the GitHub buttons?

Yes, `display: none` is bad as it affects the page layout. `opacity` or `visibility` are both better in that regard.

**Comment by bfred-it** [comment]
I'd rather just move it somewhere else than use two MutationObservers though

**Comment by bfred-it** [comment]
Heads-up: Color and position was updated https://github.com/sindresorhus/refined-github/pull/1909

![](https://user-images.githubusercontent.com/1402241/56466173-da517700-643f-11e9-8eb5-9b20017fa613.gif)
