### ISSUE TITLE
Consider moving Recently Pushed Branches elsewhere

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1109]
Following #1106 and #906 

How does this position look? 

<img width="686" alt="screen shot 2018-02-22 at 14 40 04" src="https://user-images.githubusercontent.com/1402241/36525858-572ff01c-17de-11e8-8cca-9ea6379d0c1c.png">

To achieve this, the element would have to be moved between the two elements and floated right:

```js
select('.pagehead-actions').after(select('.js-socket-channel'));
```

But probably it has to be move _inside_ and positioned absolutely in case the repo name or branch name are too long to fit in one line.

Alternatively there's this position, that expands on hover:

![](https://user-images.githubusercontent.com/1402241/36526234-fe0922e0-17df-11e8-9229-2bb12481e308.png)

**Comment by silverwind** [comment]
The space between repo name and the buttons can be limited on small screens.

Maybe try with `position: fixed`, which would allow the user to scroll potentially hidden content into view.

**Comment by bfred-it** [comment]
> Maybe try with position: fixed

That might make it more annoying (since it floats + it could cover _anything_ on the screen, on whatever border we fix it to)

**Comment by hkdobrev** [comment]
I personally don't mind it if it overlaps with something and especially if that's the repo name (even though it may hide the commit status link we add there).

I like the first suggestion.

**Comment by sindresorhus** [comment]
> Alternatively there's this position, that expands on hover:

I like this one.

**Comment by tonglil** [comment]
Personally I liked it when it stretched across the top of the page.

Honestly, the green "PR" button needs to be bigger to click on, and would love to see this bar/notification on any page in the repo.

Very rough image:
<img width="1028" alt="screen shot 2018-03-08 at 1 22 32 pm" src="https://user-images.githubusercontent.com/3250776/37174507-f1976de2-22d3-11e8-836a-f3a5ef79c15c.png">

**Comment by SuperSandro2000** [comment]
Did you think about moving out just under fork and star?

**Comment by bfred-it** [comment]
> Did you think about moving out just under fork and star?

I don't think there's enough space, it will feel cramped if there are tabs under it.

**Comment by jerone** [comment]
I hope we can fix this also for forks:

![image](https://user-images.githubusercontent.com/55841/48979226-ca638000-f0b7-11e8-961d-6e16b1612c5e.png)


**Steps to reproduce**
1. Fork project.
2. Create branch and commit.
3. Go to your forked project homepage.


**Expected**
Expected to see the top buttons and the recent-branches banner somewhere else:
![image](https://user-images.githubusercontent.com/55841/48979288-d734a380-f0b8-11e8-91cb-df74d9587cda.png)

**Comment by droidmonkey** [comment]
See the same issue as @jerone for regular repositories as well:

![image](https://user-images.githubusercontent.com/2809491/54881463-b2fa9080-4e26-11e9-9b23-a939964f2d3c.png)

**Comment by bfred-it** [comment]
The size won't actually always fit that area, it depends on the branch name. Also I'm hoping to extend the search box to fill that blank spot.

**Comment by bfred-it** [comment]
PR sent

**Comment by bfred-it** [comment]
Finally done! You can also disable it now: `recently-pushed-branches-enhancements`

![](https://user-images.githubusercontent.com/1402241/56466173-da517700-643f-11e9-8eb5-9b20017fa613.gif)
