### ISSUE TITLE
Shortcut to open notification in a new tab

### ISSUE THREAD

**Issue by vanniktech** [sindresorhus/refined-github#1110]
Currently one can use `o` to open the notification in the current tab. It would be nice if you could use `shift + o` to open the notification in a new tab.

Use case:

Browsing through the notifications with `j` & `k` while marking some as read (`e`) and the need to want to look at things later and hence opening a new tab.

**Comment by Maxscores** [comment]
@vanniktech @hkdobrev
This is my first contribution to this project and I'd love to tackle this issue. Let me know if someone else is already working on it and I'm happy to switch to something else!
Cheers

**Comment by vanniktech** [comment]
I'm not.

**Comment by Maxscores** [comment]
[PR is up](https://github.com/sindresorhus/refined-github/pull/1240)

Thanks, 
@tylermarshal @abarnes26
