### ISSUE TITLE
Automatic "has PR" tag

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1116]
Like #1078 shows what PR closed an issue, we can show what PR _will_ close an issue.

Like for #1078, we already have this information somewhere in the thread:

<img width="108" alt="info icon" src="https://user-images.githubusercontent.com/1402241/36638976-27004e34-1a34-11e8-9228-f5a347e56f88.png">

Perhaps we can use the same style GitHub uses to link to PRs in branch pages that have open PRs, example: https://github.com/sindresorhus/refined-github/tree/merge-commits

<img width="226" alt="branch with pr" src="https://user-images.githubusercontent.com/1402241/36638988-79b3e834-1a34-11e8-8b6c-7ba0c7e401df.png">

Mockup for this feature:

<img width="268" alt="link mockup" src="https://user-images.githubusercontent.com/1402241/36639008-f0122388-1a34-11e8-970b-81a6cc5acef0.png">

To keep in mind: there might be multiple PRs trying to close an issue so multiple buttons would be shown in that case.

**Comment by hkdobrev** [comment]
Best feature ever! :raised_hands:

**Comment by sangeeth96** [comment]
@bfred-it How should the layout of the buttons be if there are multiple PRs?

**Comment by hkdobrev** [comment]
I'd suggest to change the `View #XXX` button in the tree view to also use the icon to indicate it's a PR.

**Comment by bfred-it** [comment]
> I'd suggest to change the View #XXX button in the tree view to also use the icon to indicate it's a PR.

Separate feature? It matches different pages

**Comment by bfred-it** [comment]
Has PR! Check it out on this very issue.

**Comment by hkdobrev** [comment]
I've double checked that all of our open issues with the "has PR" tag has a closing PR link in the header. One didn't and I've updated the PR description. So I'm deleting the "has PR" label 🎉. We're losing the ability to filter by that filter, but it reduces the effort of adding that label back since only collaborators could edit labels.

**Comment by bfred-it** [comment]
No wait this doesn't appear in lists, it's nice to see what issues are already being fixed

**Comment by hkdobrev** [comment]
> No wait this doesn't appear in lists, it's nice to see what issues are already being fixed

OK, I'll add it back, but I think it's a bigger burden than the benefits. For me the bigger benefit is to not start working on an issue where an implementation has started and is being discussed. And you see that from the issue page.
