### ISSUE TITLE
When "add-delete-fork-link" is disabled, the extra whitespace is still present

### ISSUE THREAD

**Issue by varkor** [sindresorhus/refined-github#1122]
The "pull request merged" container currently looks like this with `add-delete-fork-link` disabled (which is just ugly):
![whitespace-for-missing-add-delete-fork-link](https://user-images.githubusercontent.com/1016458/35037353-64769eee-fbcb-11e7-8689-3236de59f7ea.png)

**Comment by yakov116** [comment]
@varkor Disable feature is intended to be a workaround not a perfect solution.

**Comment by varkor** [comment]
@yakov116: that was my impression, but it's still useful to keep track of the things that can be improved, even if they're not (yet) part of a polished feature!

**Comment by bfred-it** [comment]
This can be fixed by applying the spacing only when the feature is enabled, either by adding it directly on the link (I don't think that's possible) or by enabling it via class. It should be a ~2-lines change

**Comment by sindresorhus** [comment]
This is the exact situation I feared when we added ability to disable features; Us wasting time adding workarounds for disabled features… I see no good reason to disable this feature.

**Comment by varkor** [comment]
@sindresorhus: this was very much a "small touch" issue that was intended simply to document the existence of a tiny problem. It's obviously very trivial — but it could be something simple a beginner wanting to get involved with Refined GitHub could try to fix (it's not worth wasting anyone's time fixing this, if there are other issues to be addressed).

**Comment by bfred-it** [comment]
>  I see no good reason to disable this feature.

Yeah. I've seen stuff like `add-your-repositories-link-to-profile-dropdown` disabled. Nonsense.

I'll close this.

The only way changes like these should get in is if the requestor themselves will send a simple PR to fix it.
