### ISSUE TITLE
Endless 'Fetching latest commit…'

### ISSUE THREAD

**Issue by grahamperrin** [sindresorhus/refined-github#1124]
Here, for example, at <https://github.com/mozilla/addons-server/tree/2018.03.01-2>: 

![2018-03-02 00 00 03 github endlessly fetching latest commit](https://user-images.githubusercontent.com/192271/36876724-37167ffa-1dae-11e8-9717-2e6afb020af1.png)

Also affected: 

- pages such as https://github.com/MrAlex94/Waterfox/tree/56.0.4

## Workaround

1. Disable the extension
2. reload the affected page

## Environment

- Refined GitHub 18.2.26.1519
- Waterfox 56.0.4_4 (56.0 was based on Firefox 56.0.2)
- FreeBSD-CURRENT, 

```text
[grahamperrin@momh167-gjp4-hpelitebook8570p-freebsd] ~% date ; uname -v
Fri  2 Mar 2018 00:13:09 GMT
FreeBSD 12.0-CURRENT #0 r320869: Mon Jul 10 13:57:55 UTC 2017     root@releng3.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC 
```

**Comment by bfred-it** [comment]
Can't reproduce the bug on Waterfox 56.0.4 / macOS

I don't think we're touching anything in that table

**Comment by grahamperrin** [comment]
I confess to not disabling other extensions before testing! Apologies for the laziness/noise. 

> … assume that it's a coincidence that it worked without Refined GitHub. …

Agreed.

**Comment by kolojoe** [comment]
I am currently experiencing the same situation.  Is there any more information on this problem?

**Comment by marwamoaz-1** [comment]
how can I disable extension?

**Comment by aicsuva** [comment]
how can I disable extension?
