### ISSUE TITLE
Z-index not good on resolve conflict page

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#1126]
```
content.js:2275 Uncaught (in promise) TypeError: Cannot read property 'parentNode' of null
    at linkify_issues_in_titles (content.js:2275)
    at enableFeature (content.js:1125)
    at <anonymous>
```
![image](https://user-images.githubusercontent.com/16872793/36913904-6502a41e-1e19-11e8-9321-2010a4123db3.png)

**Comment by sindresorhus** [comment]
@bfred-it Maybe time to remove the overlay? It just causes so many problems, and I have to be honest, I find it more annoying than useful.

**Comment by bfred-it** [comment]
@yakov116 the console error is unrelated.

@sindresorhus I don't mind this _bug,_ but if it annoys others it's fine to remove it.

**Comment by yakov116** [comment]
@bfred-it I know I had the first issue, then right before I posted it I decided to look in the dev console.
