### ISSUE TITLE
Add delete button to files in a PR

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1127]
Very often people include files I don't want in PRs. Like `package-lock.json` or editor-specific config. I would like a quick way to remove such files.

<img width="1111" alt="screen shot 2018-03-03 at 01 54 18" src="https://user-images.githubusercontent.com/170270/36916277-0d0620c0-1e86-11e8-9955-c7acd526ba28.png">

<sub>(From https://github.com/sindresorhus/broccoli-svgo/pull/1/files#diff-32607347f8126e6534ebc7ebaec4853d)</sub>

Unless the PR submitter has unchecked the "Allow maintainers to edit" checkbox, we are allowed to delete it if we go directly to the file, like here: https://github.com/jaswilli/broccoli-svgo/delete/update/package-lock.json

So the implementation could be to find the branch and then go to:

```
https://github.com/<username>/<repo>/delete/<branch>/<filename>
```

**Comment by JackLaird0** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by sindresorhus** [comment]
@JackLaird0 No one is working on this. Go ahead 😀
