### ISSUE TITLE
Fork icon size

### ISSUE THREAD

**Issue by wayneashleyberry** [sindresorhus/refined-github#113]
All of the icons on the home page activity feed are larger except for the fork icon :(

<img width="583" alt="screen shot 2016-03-30 at 8 31 47 am" src="https://cloud.githubusercontent.com/assets/727262/14133702/e067f4e8-f651-11e5-902e-4ad6187c3f2e.png">

<img width="229" alt="screen shot 2016-03-30 at 8 32 07 am" src="https://cloud.githubusercontent.com/assets/727262/14133709/ea377f34-f651-11e5-8705-d3b86fa0b64d.png">

**Comment by hkdobrev** [comment]
This came to be like this because we have increased the size only of the star icon, but removed a few other events from the feed. Not sure if we want to emphasize on the fork and make it big as well though.

Related: #106 #107 #55 #44.

**Comment by wayneashleyberry** [comment]
It just feels a little strange @hkdobrev, all the icons in my feed are big _except_ one. If anything, forking activity could be removed completely... I don't think it's that important.

**Comment by paulmolluzzo** [comment]
I agree: Forking a repo isn't a big deal. I've forked stuff to almost no purpose before, why would anyone care?

**Comment by sindresorhus** [comment]
I would just remove it. I don't see value in knowing what people forked.

**Comment by wayneashleyberry** [comment]
Thanks @paulmolluzzo
