### ISSUE TITLE
Add links to issues and pull requests next to repo title

### ISSUE THREAD

**Issue by cg-cnu** [sindresorhus/refined-github#1130]
When working in organization with multiple repos... the org home page lists all the repos. clicking on the repo name will take to code and then we click on issues / pull requests. Being a maintainer, most of the times I work on issues / prs. It would be very handy if I can directly go on the repo's issues / prs page from the organization home page. 

One way to do is to have links to /issues and /pull requests next to the repo name itself.

![](https://user-images.githubusercontent.com/2767425/36937483-dfc5b904-1f39-11e8-94f6-595dc4b40e0e.png)

Let me know your comments and suggestions. Would be happy to do a pr 😄

**Comment by bfred-it** [comment]
Looks a big cluttered. If this is added, it should probably be just the PR and Issue icons on the third line, not large text next to the title

**Comment by cg-cnu** [comment]
@bfred-it Adding icons is a good idea, just wondering if we can add them next to the title 🤔

**Comment by salmanulfarzy** [comment]
There is a [user script with similar functionality for issues](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-issue-counts).

![github-repo-issues](https://cloud.githubusercontent.com/assets/136959/21301601/af93bbac-c574-11e6-88d4-691d66a04f21.gif)

**Comment by cg-cnu** [comment]
That sounds great, did a small mockup! 
![](https://user-images.githubusercontent.com/2767425/36984236-70997ed0-20ba-11e8-9dc3-e0ae6c7a96ed.png)

* **Bugs** Icon should list the issues count and clicking it should take to issues page
* **PR** Icon should list the open pr count and clicking it should take to pull requests page.

**Comment by bfred-it** [comment]
- That’s a misiconer (misnomer), not all issues are bugs. It’s best to use the regular icon. 
- For the counts you need API calls, one per repo, unless someone adds the API key to the options and uses the GraphQL API

**Comment by cg-cnu** [comment]
@bfred-it 
* Sure, what would be the **regular icon** for issues ?
* Others usage may vary but I usually don't depend on the count of issues or pr, am happy with just the link.

**Comment by hkdobrev** [comment]
> Sure, what would be the regular icon for issues

https://octicons.github.com/icon/issue-opened/

**Comment by cg-cnu** [comment]
Thanks for the link @hkdobrev. 

Here is the latest mockup! 

![mock](https://user-images.githubusercontent.com/2767425/37334997-6e0f9202-26d3-11e8-94db-e4157126c791.png)

**Comment by bfred-it** [comment]
Can you try sending a PR?

**Comment by cg-cnu** [comment]
@bfred-it on it 👍

**Comment by sindresorhus** [comment]
*Make sure to also send this feature request to GitHub: support@github.com*

**Comment by greg-hellings** [comment]
Has this been addressed or is it still outstanding? I would also like to see this (and having the counts included would be glorious as well!, but direct links would also be better than current).

**Comment by HardikModha** [comment]
It will look very congested when more details are present. e.g. 
![congested](https://user-images.githubusercontent.com/22439276/56375914-50799200-6224-11e9-9427-460cbbc59f85.png)

**Comment by HardikModha** [comment]
I've prepared a small adhoc change to display issues and PR. I've kept the look and feel same as displayed in the navbar. How about this? 

![Screen Shot 2019-04-18 at 9 51 23 PM](https://user-images.githubusercontent.com/22439276/56376007-828af400-6224-11e9-94d6-cca2dca605d2.png)

**Comment by greg-hellings** [comment]
OMG I love it.

**Comment by HardikModha** [comment]
What do you think about it? @bfred-it

**Comment by fregante** [comment]
Honestly I think we can just replace that `X issues need help` and display it there instead. It's not a very useful copy now that everyone uses the label as _"up for grabs"_ rather than _"we actually need someone who knows more than us to fix it"_.

**Comment by arnaudvalle** [comment]
Hello - has this not been done by GitHub?

<img width="684" alt="Screenshot 2019-11-04 22 03 55" src="https://user-images.githubusercontent.com/1215056/68158190-6c8a1a00-ff4f-11e9-81d1-64d9aac9469f.png">

**Comment by fregante** [comment]
I'm not seeing it on profiles: https://github.com/sindresorhus?tab=repositories&type=source

Only on organizations: https://github.com/h5bp?type=source

Maybe soon!

**Comment by arnaudvalle** [comment]
Ah yes you're right, I thought we were talking about orgs only here.
