### ISSUE TITLE
Search issues while a new issue is being typed

### ISSUE THREAD

**Issue by fenollp** [sindresorhus/refined-github#1138]
Exactly like what stackoverflow does when creating a new question:
* as soon as the title has a few words
* start a somewhat fuzzy search query in the background
* display the results in the space above the title of the issue
* continue updating results while issue is being typed

Maybe limit to 2-5 search requests per minute so as not to eat all the user's rate limiting quota.

[Here's a video of someone doing a SO submission.](https://www.youtube.com/watch?v=OmyqGI91ZBU)

**Comment by bfred-it** [comment]
This would be great and as much as it would be great as a separate extension, having the thousands of RGH users on it automatically would prevent a lot of useless issues. 👍 

> Maybe limit to 2-5 search requests per minute

For that frequency I think we can just show the suggestions when the user is done typing, i.e. `blur` event.

**Comment by fenollp** [comment]
> we can just show the suggestions when the user is done typing

I would add *done typing **the title***

**Comment by bfred-it** [comment]
Yes :)

**Comment by shroudedcode** [comment]
I quickly hacked this together with Primer:

![](https://user-images.githubusercontent.com/29176678/37058355-89d9b51a-218a-11e8-8a39-2565b5c25b0f.png)

What do you think?

**Comment by fenollp** [comment]
This looks great! Now I'm thinking Should this also appear on issue pages? hell yes that sounds amazing! Great work

**Comment by shroudedcode** [comment]
@bfred-it @fenollp I've [implemented the basic functionality](https://github.com/shroudedcode/refined-github/tree/display-issue-suggestions) but there are some things I need help with:

##### Design decisions

* How many suggestions should be displayed? How should we determine which ones are most relevant?
* Should we display excerpts when the issue title does not contain any of the title's words?
  And if yes, how do we determine what part and how much of issue is displayed?
* Should we filter out issues tagged with `invalid`, `spam`, et cetera?
* Should we remove already displayed issues as soon as the user starts typing again?
* Should only the title be used to search or also the issue body?

##### Implementation questions

* How I do I correctly escape a qualifier like `is:issue` so the API gives me issues that contain it?

**Comment by fenollp** [comment]
WRT design I’m thinking
* display at most 3-5 results with a link “X more results” to the actual results page
* if possible this should be using github’s search so that when clicking the link the same results can be found without surprise
That should answer the design questions. I love your ideas but maybe we can get something basic first then iterate on it with time and experience?

Can’t you double quote that string to escape it? `… "is:issue" …`?
Thanks for your great work I look forward to it getting merged!

**Comment by bfred-it** [comment]
How about matching StackOverflow? https://stackoverflow.com/questions/ask

<img width="589" alt="stackoverflow" src="https://user-images.githubusercontent.com/1402241/37565300-78094618-2ad9-11e8-9da4-fcdbe79de333.png">

It may seem a bit annoying to move the main comment area, but this only happens when the title field loses focus, which means that use probably already clicked/tabbed into the comment box, so they can start typing even if it moved.

**Comment by hkdobrev** [comment]
I think being that aggressive makes sense only for sites like SO and Quora where having duplicate content across the whole site is a bigger issue. With GitHub you would have quite a bit more false positives as the search is quite permissive and you are not searching all of GitHub, but just a single repo. It would be quite more often that the results are not the same issue compared to SO.

**Comment by hkdobrev** [comment]
> - Should we display excerpts when the issue title does not contain any of the title's words?
>   And if yes, how do we determine what part and how much of issue is displayed?
> - Should we filter out issues tagged with invalid, spam, et cetera?
> - Should we remove already displayed issues as soon as the user starts typing again?

I would answer "no" to all three of the above questions - keep it simple and predictable.
