### ISSUE TITLE
 A style guide for the README and the update log

### ISSUE THREAD

**Issue by shroudedcode** [sindresorhus/refined-github#1139]
Both the README and [the new update log](https://github.com/sindresorhus/refined-github/issues/1137) contain stylistic inconsistencies. They make the text harder to read and make Refined GitHub look less polished. That's why I wrote a little style guide:

### Formatting

* Keys should be written in lower case.
  * <kbd>shift</kbd> instead of <kbd>Shift</kbd>.
  * :arrow_right: *Used by GitHub.*
* Keys of key combos are only separated by a space.
  * <kbd>g</kbd> <kbd>t</kbd> instead of <kbd>g</kbd>+<kbd>t</kbd>.
  * :arrow_right: *Used by GitHub.*
* Mouse buttons ("clicks") are treated as keys.
  * <kbd>alt</kbd> <kbd>click</kbd> instead of <kbd>alt</kbd> click.
  * :arrow_right: *Just looks better. I guess.*
* Labels (of buttons, tabs, links, ...) are highlighted using backticks.
  * `Button` instead of 'Button' or "Button".
  * :arrow_right: *Already used in some places. Also more readable.*

### Wording

* Feature bullet points are sentences that start with an imaginary *Refined GitHub allows you to ...*.
  * *Toggle files* instead of *The ability to toggle files* or *Let's you toggle files*.

---

Anything to add or change? Otherwise, I'll open a PR to obey the rules in the README.

Should I also include (or link to?) the style guide in the contribution guide?

**Comment by bfred-it** [comment]
Excellent! Yes please :)

**Comment by hkdobrev** [comment]
Yes to everything in the PR description! 🎉
