### ISSUE TITLE
Issue with the merge commit tweaks

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#114]
From: https://github.com/chalk/ansi-styles/commits/master

<img width="481" alt="screen shot 2016-03-30 at 14 05 50" src="https://cloud.githubusercontent.com/assets/170270/14134309/725a57a0-f680-11e5-94d7-835c9b45871a.png">

**Comment by blackjid** [comment]
It happens if you navigate forwards and back... Every time you go back, a new icon gets in there
