### ISSUE TITLE
Stop opening tab with refined github updates

### ISSUE THREAD

**Issue by brunolemos** [sindresorhus/refined-github#1147]
Please disable that, it's annoying af. 😄

#1137

**Comment by salmanulfarzy** [comment]
> only ever happens once for everyone, and for new users only when they install the extension (which is fair)

https://github.com/sindresorhus/refined-github/pull/1141#issuecomment-371046716

**Comment by brunolemos** [comment]
Pretty sure it opened at least twice for me in the last 24h.

**Comment by brunolemos** [comment]
Closing as duplicate but hopefully this will be removed.

**Comment by brunolemos** [comment]
https://github.com/sindresorhus/refined-github/blob/6cdb75e8d564a37cac01d55aaaf6121e9633aafa/source/background.js#L44

Is this correct? Shouldn't it be `const userWasNotified = await browser.storage.local.get('userWasNotified');`?

**Comment by simonkberg** [comment]
Could you re-open? The tab has opened for me multiple times now. The getter looks correct ([ref](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/get)), but the setter however seems to be incorrect: https://github.com/sindresorhus/refined-github/blob/6cdb75e8d564a37cac01d55aaaf6121e9633aafa/source/background.js#L55

I believe this should be:
```js
browser.storage.local.set({ userWasNotified: true });
```

Refs: 
https://developer.chrome.com/extensions/storage#method-StorageArea-set
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/storage/StorageArea/set

**Comment by seiyria** [comment]
This is happening for me too - twice in the last day or so. Happy to see a PR is up already!

**Comment by nhaarman** [comment]
Yeah I uninstalled the plugin.

**Comment by jacob-long** [comment]
Tab has opened 3 times, maybe 4, for me.

**Comment by bfred-it** [comment]
Sorry about this! We added that feature hastily. You have seen it 3 times because the plugin has updated 3 times since then. #1148 will be merged before the next release, I'm just waiting for @sindresorhus to double check.
