### ISSUE TITLE
Removing top buttons from comment box removes saved replies button

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#115]
GitHub has introduced saved replies: https://github.com/blog/2135-saved-replies

I guess we can hide all buttons except the saved replies one. Since this extension might be particularly used by heavy GitHub users and project maintainers I think it would be useful to them to have the saved replies feature available.

Here's another extension specifically targeted towards maintainers which GitHub could now replace: https://chrome.google.com/webstore/detail/github-canned-responses/lhehmppafakahahobaibfcomknkhoina

**Comment by sindresorhus** [comment]
Yes, let's unhide just that one.
