### ISSUE TITLE
Add ability to open a git-flow pull request

### ISSUE THREAD

**Issue by wmonk** [sindresorhus/refined-github#1150]
I am often making pull requests from feature branches into `staging` and then `staging` into master. It would be super convenient to have a button that would open a PR from `staging` into `master`, as it's very repetitive to search for master each time.

**Comment by bfred-it** [comment]
Where would this button appear and what would it do **exactly**?

**Comment by wmonk** [comment]
Yes exactly! The process for picking branches is annoying as you have to type to search, this could just be a fixed button or make the New Pull Request button have an optional drop-down to open a new "deploy" pr as we call them at work. Also as staging is the default branch the default options are more to merge master into staging, but should be the other way around.

**Comment by bfred-it** [comment]
> as staging is the default branch the default options are more to merge master into staging, but should be the other way around

If it should be the other way around, master should be the default branch, right?

Either way this likely needs some configuration (what if someone wants dev->staging, **stage**->master, etc) and Refined GitHub doesn't do that. I suggest either using a bookmark or looking-for/developing a extension for all-things-git-flow

**Comment by bfred-it** [comment]
You could try suggesting to GitHub to sort branch selectors by usage, so `staging` and `master` will naturally float to the top.

<img width="372" alt="" src="https://user-images.githubusercontent.com/1402241/37269154-ce09a270-25fb-11e8-98a4-efb504c2503f.png">

**Comment by wmonk** [comment]
Thanks, that sounds like a good idea
