### ISSUE TITLE
Duplicate repository name on starred items

### ISSUE THREAD

**Issue by kevva** [sindresorhus/refined-github#1152]
Recently, GitHub made a change to the starred repositories in the news feed causing the repository name to show up twice. I guess they removed one of these classes: https://github.com/sindresorhus/refined-github/blob/adab738e34df21c01bcc1a4f18eb8bfc0dae8e2d/source/content.css#L867-L870.

<img width="695" alt="screen shot 2018-03-09 at 00 13 40" src="https://user-images.githubusercontent.com/709159/37181794-c3db0188-232e-11e8-873b-9dec82de60aa.png">

**Comment by bfred-it** [comment]
They’re playing so much with the size. This time it might be a f2
