### ISSUE TITLE
Mark :visited links (mainly for issues and PRs)

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1153]
Google Search and Hacker News are few of the sites that still have the useful `:visited` rule. 

Wouldn't make sense to mark `:visited` ~~or `:not(:visited)`~~ links as purple?

<img width="568" alt="isaacs-gtihub" src="https://user-images.githubusercontent.com/1402241/37203730-3d994a1a-23c1-11e8-9ce4-301c0e4427ad.png">

<details><summary>Edit: old mockup</summary>

Here's a quick mockup that highlights the **issues I haven't visited.** Sadly `:visited` only works with color so we can't get creative.

<img width="547" alt="screen shot 2018-03-09 at 15 25 11" src="https://user-images.githubusercontent.com/1402241/37197664-32f49b90-23ae-11e8-9ea1-f0a85a4de75a.png">

</details>

**Comment by hkdobrev** [comment]
I like what GitHub is doing with the blue bar on the left when there's a new activity since I last viewed. I don't think I'll need the visited state in addition to the blue bar.

**Comment by bfred-it** [comment]
> new activity since I last viewed

That's not it, the blue bar is only if you're subscribed to an issue, i.e. if you have a notification, it also highlights it with a blue bar.

This would be kin to what Google also does in search results. Pretty standard web functionality that many forget about (and mindlessly disable on their site).

<img width="648" alt="" src="https://user-images.githubusercontent.com/1402241/37203548-96997870-23c0-11e8-95c6-08e96b203084.png">

**Comment by bfred-it** [comment]
Additional mockup:

<img width="578" alt="isaacs-gtihub" src="https://user-images.githubusercontent.com/1402241/37203628-eee924a8-23c0-11e8-89bb-3dcd2860cceb.png">

```css
.link-gray-dark:visited {
    color: gray !important;
}
```

**Comment by bfred-it** [comment]
Here you can see how "unread items" don't always overlap with "never visited" items.

<img width="198" alt="" src="https://user-images.githubusercontent.com/1402241/37748397-a129e2c2-2dbe-11e8-8bfb-f60cde649b34.png">
