### ISSUE TITLE
Certain dropdowns are closed prematurely by close-out-of-view-modals

### ISSUE THREAD

**Issue by Spartan322** [sindresorhus/refined-github#1155]
I've found Notifications Preview can display notifications longer then my screen can display and I need to scroll down to see some of them, however by scrolling that closes the dropdown now. If there were a manner to dictate the modal closing behavior to specific vanilla and Refined Github elements that would be great, or perhaps this could be fixed in Notifications Preview over time but I ask because the change to the modal behavior was applied via Refined Github. This type of issue seems to be a kinda odd side effect and not sure exactly how to approach it in this case.

**Comment by bfred-it** [comment]
That's more likely to be an issue with Notifications Preview, I'm going to close this issue here but I'm looking into it
