### ISSUE TITLE
Username in comment thread messed up possibly because of accented character

### ISSUE THREAD

**Issue by sinstein** [sindresorhus/refined-github#1176]
The thread in question: https://github.com/w3c/webdriver/issues/385#issuecomment-373474056

How it looks like without refined-github:
<img width="802" alt="screen shot 2018-03-16 at 1 32 54 pm" src="https://user-images.githubusercontent.com/4283218/37509761-a5a1b9e6-291e-11e8-8d05-45f9c04efb59.png">

How it looks like with refined-github
<img width="796" alt="screen shot 2018-03-16 at 1 33 10 pm" src="https://user-images.githubusercontent.com/4283218/37509770-af13dcfc-291e-11e8-9637-7fd406d99478.png">

This seems to have occurred because the username had an accented character (ä)

**Comment by salmanulfarzy** [comment]
@sinstein see #1165, It's highlighting the linked comment.

**Comment by sinstein** [comment]
@salmanulfarzy The highlighting I understand, but the username above the comment, is that how it is supposed to look like?

> dwt (‮rekcäH nitraM‮) 15 hours ago 

vs 

> dwt

**Comment by salmanulfarzy** [comment]
Oh.. I'm sorry. This is how its displayed for me.

![image](https://user-images.githubusercontent.com/10276208/37513384-f71aa4f2-292a-11e8-9265-357df4702a54.png)

**Comment by sinstein** [comment]
Strange. Maybe there is another extension that is interfering with refined-github on my machine then. I will try to set up a clean instance of Chrome and see if this issue occurs with only refined-github enabled.

**Comment by bfred-it** [comment]
We had this [issue](https://github.com/sindresorhus/refined-github/pull/702) before and it was [resolved](https://github.com/sindresorhus/refined-github/issues/698).

It's still `&#8238;`, but this time it appears twice. Adding `display: inline-block` to `.timeline-comment-header-text bdo` fixes it
