### ISSUE TITLE
Link PR commit in merged PR header

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1184]
Similar to https://github.com/sindresorhus/refined-github/pull/1078 but for PRs, linking to the merge commit.

<img width="310" alt="Merged as commit" src="https://user-images.githubusercontent.com/1402241/37555252-380f7338-2a17-11e8-9fab-b93ae5f9128f.png">

This can probably be appended to the same [_feature_:](https://github.com/sindresorhus/refined-github/commit/fddb0b56a0b326a08a3cfba42e210f34036a6ce5) separate function but both functions in the same file.

**Comment by ramlmn** [comment]
Current implementation in https://github.com/ramlmn/refined-github/tree/extend-status-labels.

Need to merge #1199 before opening a PR because of possible merge conflicts.

**Comment by bfred-it** [comment]
Done!
