### ISSUE TITLE
Enhance "Press R to quote" with markdown

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1187]
For those who didn't know, pressing <kbd>r</kbd> will quote the selected text into the comment box. This is a native GitHub feature. Sadly this just quotes plain text and discards any style.

We could override the default hotkey with our GitHub-optimized [DOM-to-Markdown converter](https://github.com/sindresorhus/refined-github/blob/master/source/features/copy-markdown.js).

Context:

- initial suggestion https://github.com/sindresorhus/refined-github/pull/856#issuecomment-350432946
- GitHub's <kbd>r</kbd> handler: https://github.com/sindresorhus/refined-github/pull/856#issuecomment-350452982

**Comment by sindresorhus** [comment]
Yes, let's do it. That's a much better way to take advantage of our DOM-MD thing.

**Comment by bfred-it** [comment]
GitHub did it.

**Comment by ronjouch** [comment]
> GitHub did it.

Also, good thing GitHub made the feature available also through a "Quote reply" entry to the `...` hamburger menu of issues/comments. It makes the feature 1. more discoverable, and 2. usable (with two clicks) for Vimium users for who <kbd>r</kbd> is bound to reloading the page 🙂.

**Comment by bfred-it** [comment]
Speaking of which https://github.com/sindresorhus/refined-github/pull/1624
