### ISSUE TITLE
Problem with showing "open pull request" shortcut

### ISSUE THREAD

**Issue by tristanbes** [sindresorhus/refined-github#1189]
The screenshot speaks for itself.

I've cleared my cache and tried other pages but with the same result. (Chrome 65.0)

![pull_requests](https://user-images.githubusercontent.com/346010/37568803-96abe25a-2ada-11e8-888b-c43a4aa3aeff.png)

Thanks

**Comment by juliocanares** [comment]
same here

**Comment by bfred-it** [comment]
This was caused by some recent CSS removal. #1183

PRs welcome, it’s 3 lines of code with `z-index`
