### ISSUE TITLE
The PR creation popover is covered by github default buttons

### ISSUE THREAD

**Issue by jzhang012** [sindresorhus/refined-github#1192]
First of all, thanks for the great extension.

Looks like Github increased the z-index for these buttons recently.

<img width="526" alt="screen shot 2018-03-19 at 3 12 56 pm" src="https://user-images.githubusercontent.com/20664940/37616982-09632f08-2b88-11e8-9566-3887aa18fb11.png">

**Comment by lukaszklis** [comment]
This issue has been fixed in #1190 (originally reported in #1189). To make sure you are using the latest version of the extension, go to `chrome://extensions` and force an update. In order to do it, toggle the _Developer mode_ on the right and click _Update_ in the menu shown below the search bar).

**Comment by bfred-it** [comment]
Thanks for reporting the bug! Thankfully it’s been already fixed and you should receive the update soon 🙂
