### ISSUE TITLE
Extract all page detection checks to a new file

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#120]
As per this discussion in https://github.com/sindresorhus/refined-github/pull/99#discussion_r57682602.

We could extract all code related to page detection in a new file and expose a simple interface for them. This includes URL checks mostly using the latest `location`, but some DOM checks as well.

**Comment by paulmolluzzo** [comment]
I wonder if we might want to go one step further. Maybe pop this out into a npm module and we can just import it. This would be a useful utility for anyone regex-ing their way around GitHub. Thoughts?

**Comment by sindresorhus** [comment]
Wish Chrome had native support for ES2015 modules...

> Maybe pop this out into a npm module and we can just import it. This would be a useful utility for anyone regex-ing their way around GitHub.

That's a good idea, but let's wait with that until we're a bit more stable. Having to bump a version on that every time we need a new route will be annoying.

**Comment by paulmolluzzo** [comment]
> Wish Chrome had native support for ES2015 modules...

Using a package would change the workflow for this repo, and I don't know if it's worth it when the package in question is copying out stuff we have here already.

> Having to bump a version on that every time we need a new route will be annoying.

True, but the package is going to diverge at some point. This extension will check for URLs specific to our use case, and won't have useful URLs that we simply don't need. For example, we don't have any need to check if we're on the settings page, but someone else might want to know that.

**Comment by hkdobrev** [comment]
We can extract first, see it works properly, maintain for a bit to see how often it changes and then move to a separate repo.

**Comment by paulmolluzzo** [comment]
:+1: Works for me.
