### ISSUE TITLE
Toggle files button on repo root is broken

### ISSUE THREAD

**Issue by ramlmn** [sindresorhus/refined-github#1202]
![image](https://user-images.githubusercontent.com/12368291/37727771-b1c10eae-2d5e-11e8-87f0-4e61b3a3661d.png)

---------

Loading commit information takes some time, but https://github.com/sindresorhus/refined-github/blob/b5f1657ca231843cc53dc4addd1b3b74919df4df/source/features/add-toggle-files-button.js#L21-L25 immediately tries to append the toggle files button to container that doesn't yet exist!

------------

Doing `await safeElementReady('.commit-tease .float-right');` would not work too as https://github.com/sindresorhus/refined-github/blob/b5f1657ca231843cc53dc4addd1b3b74919df4df/source/libs/utils.js#L54-L62
cancels `waiting` immediately after page load.

**Comment by bfred-it** [comment]
**Sometimes** the file list is added/updated via ajax, so this needs something like:

```
observeEl(filelist) -> if ".commit-tease .float-right" exists, add button
```
