### ISSUE TITLE
Allow keeping the "Repositories you contribute to" dashboard sidebar box

### ISSUE THREAD

**Issue by ali** [sindresorhus/refined-github#1205]
The injected stylesheet removes the "Repositories you contribute to" menu from the dashboard sidebar: https://github.com/sindresorhus/refined-github/blob/b5f1657ca231843cc53dc4addd1b3b74919df4df/source/content.css#L27-L30

I think that menu is pretty useful, at least on Github Enterprise, for quick access to repos I work on that are owned by multiple Github Orgs.

![image](https://user-images.githubusercontent.com/515861/37749341-dda73bc0-2d5d-11e8-9fdd-c1cbcdaf15d7.png)

Could those styles be replaced with a `remove-repos-you-contribute-to-from-sidebar` plugin that can be enabled/disabled?

**Comment by ali** [comment]
I wanted to tinker, so I implemented the plugin: https://github.com/sindresorhus/refined-github/compare/master...ali:rm-contributed-repos-sidebar-box-plugin

If it's of interest, I'll open a PR.

**Comment by bfred-it** [comment]
> Could those styles be replaced with a remove-repos-you-contribute-to-from-sidebar plugin that can be enabled/disabled?

It's unlikely, but #1193 will help you override this without extra plugins

**Comment by bfred-it** [comment]
Now that #1193 is in, it can be re-enabled easily
