### ISSUE TITLE
PR notification layout issue

### ISSUE THREAD

**Issue by Mohamed3on** [sindresorhus/refined-github#1209]
![image](https://user-images.githubusercontent.com/12295159/37776026-b70a17f8-2de4-11e8-98a2-506d11ed4908.png)
Recently, this is how the 'make a PR from this branch' notification has been showing (instead of under the buttons, it's behind them'.

**Comment by lukaszklis** [comment]
It was fixed in #1190. Go to `chrome://extensions` and make sure you have the latest version of the extension installed (`18.3.22.713`).

**Comment by Mohamed3on** [comment]
So now it overlays the 'stars/forks/watches' buttons, shouldn't it be below/above them instead?

**Comment by bfred-it** [comment]
Correct, because of https://github.com/sindresorhus/refined-github/issues/906#issuecomment-354484055

Also: https://github.com/sindresorhus/refined-github/issues/1109

**Comment by aspiers** [comment]
Also reported in #1503 and #1506.
