### ISSUE TITLE
Full page width

### ISSUE THREAD

**Issue by jouni-kantola** [sindresorhus/refined-github#121]
I've been using [Github.ExpandinizR](https://github.com/thecodejunkie/github.expandinizr) a long time. To keep as few add-ons as possible, it would be great with the feature in refined-github as well. This is what the repo page looks without/with ExpandinizR:
![without](https://cloud.githubusercontent.com/assets/2670127/14154266/cd3a964a-f6bb-11e5-8fe5-a56b769de433.png)
![with](https://cloud.githubusercontent.com/assets/2670127/14154261/c787f6e8-f6bb-11e5-80c4-6f987c3d07be.png).

**Comment by sindresorhus** [comment]
Why? GitHub is already wide enough for any content, they even recently made the repo view wider.

**Comment by jouni-kantola** [comment]
Perhaps it's only file extensions nowadays that are a problem. This is a somewhat exaggerated example, without the full width extension:
![exaggerated-example](https://cloud.githubusercontent.com/assets/2670127/14154900/69b743f8-f6bf-11e5-9543-30eabca5e4fa.png)

**Comment by hkdobrev** [comment]
Is there a problem with running Refined GitHub and Github.ExpandinizR at the same time? If no, I'm against this change as I as well don't consider it very needed and there's another extension for this perfectly doing its job.

**Comment by jouni-kantola** [comment]
No, not really any problem. As I said, I wanted to keep number of extensions down.

**Comment by hkdobrev** [comment]
While Refined GitHub is quite the opposite of this, I support solutions which divide functionality into small tools and these tools could work together. Like Unix shell commands. So this functionality is quite good in a separate extension. I understand your desire to bring down number of extensions, but I don't endorse it.

Refined GitHub for me is combining things in a unified way which are sometimes too small for a separate extension or are too closely related. It emphasises on things which are helpful for heavy users of GitHub and removing clutter while still trying to use the original GitHub UI and workflow.

That said a full-page width of GitHub could live happily in a separate extension.
