### ISSUE TITLE
`author` filter added to every issue list

### ISSUE THREAD

**Issue by avdv** [sindresorhus/refined-github#1211]
I am part of a few Github organizations, and what I do usually is to open the dashboard, select one of those organizations from the "switch dashboard context" menu and click the "Pull Requests" button next to it.

This opens a list of pull requests which is filtered by the "user:organization". Now, with refined enabled, this list gets filtered by "author:avdv" automatically, which is rather useless because I don't want to find my PRs, I want to find PRs awaiting review / assigned to me.

The following is the default behaviour (refined *disabled*) I see:

* clicking on "Pull requests" in the top bar loads https://github.com/pulls and has `is:open is:pr author:<USERNAME> archived:false`
* clicking "Pull requests" on the dashboard, with a different "context" (ie. user/organization) selected, loads https://github.com/pulls?user=<USERNAME> and has `is:open is:pr user:<USERNAME> archived:false`

So, in the first case I get to see "my PRs", in the second case PRs for another "user".

The `sort-issues-by-update-time.js` feature always inserts an author filter... :crying_cat_face: 

Since there is no button for that filter, one has to manually edit the filter input field to remove the "author:..." entry which is rather clumsy.

**Comment by bfred-it** [comment]
Thanks for the report! Yeah that feature has to know what GitHub's default search queries are, and I never opened that link before 😄

**Comment by fregante** [comment]
@avdv this feature seems to have been removed.

On this page:
- https://github.com/orgs/GhostText/dashboard
The "Pull requests" link on the black header currently links to `/pulls`

Can you confirm that's the same for your GitHub?

**Comment by jerone** [comment]
> On this page: [github.com/orgs/GhostText/dashboard](https://github.com/orgs/GhostText/dashboard)
> The "Pull requests" link on the black header currently links to `/pulls`
> 
> Can you confirm that's the same for your GitHub?

Confirmed; the "Pull requests" link on the black header links to `/pulls`.

**Comment by avdv** [comment]
Oh, yes. Same for me. 

I did not really notice, since I changed my workflow using a few bookmarks where I also filter out PRs with several labels and other criteria.
