### ISSUE TITLE
Hide hovertext 'Open in Github Dekstop'

### ISSUE THREAD

**Issue by SuperSandro2000** [sindresorhus/refined-github#1212]
![](https://i.imgur.com/gKiah1C.png)

**Comment by bfred-it** [comment]
They should be hidden by adding their selector here: 

https://github.com/sindresorhus/refined-github/blob/7e3670b093f54e21ffd99ca0885766eb08f8d1eb/source/content.css#L77

**Comment by SuperSandro2000** [comment]
I don't want to hide them but they get overlapped by the other stuff above them.

**Comment by bfred-it** [comment]
Other tooltips are hidden and all of those icons are self-explanatory — except maybe the Clone in GitHub App, for which it's not worth moving them downwards with JS.

**Comment by SuperSandro2000** [comment]
Sounds reasonable.

**Comment by ganes1410** [comment]
@bfred-it  can i do it ?
