### ISSUE TITLE
Feature request: support for Microsoft Edge browser

### ISSUE THREAD

**Issue by psychelzh** [sindresorhus/refined-github#1213]
Will it be possible to develop an extension for Microsoft Edge browser, too?

**Comment by busches** [comment]
Based on this article, https://docs.microsoft.com/en-us/microsoft-edge/extensions/guides/porting-chrome-extensions, yes, but not sure if anyone on the team uses Windows or Edge.

**Comment by psychelzh** [comment]
Thanks. @busches 

I will be really nice and warm of you to develop one. 😄

**Comment by bfred-it** [comment]
You will need:

1. Someone to test, fix and maintain it on an ongoing basis
2. Setup autodeployment for it (or instructions to install it from Chrome Web Store)
3. Blessing from Sindre Sorhus in person.
4. Luck

**Comment by bfred-it** [comment]
No one else uses Edge here so until someone is interested in porting/adjusting this, it won't happen 😢
