### ISSUE TITLE
Ability to collapse certain files in PRs by default

### ISSUE THREAD

**Issue by roboslone** [sindresorhus/refined-github#1214]
We have a bunch of generated code (it has to be in the repo) that we don't want to look at during code review. I'd like refined-github to collapse such files by default using a list of path expressions, e.g. `generated/foo, generated/bar`.

**Comment by bfred-it** [comment]
A PR was submitted, but not accepted. https://github.com/sindresorhus/refined-github/pull/1085

You can try contacting the author to suggest publishing it as standalone

**Comment by roboslone** [comment]
Thanks!
