### ISSUE TITLE
Button to switch base and head in "Compare" page

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#1217]
I suggest to implement a function to switch the base and the header fork positions with each other into this currently unused icon:

http://funkyimg.com/view/2DKTW

On this way, it is easy to do git pull, as an example. :slightly_smiling_face:

**Comment by bfred-it** [comment]
Maybe I never put enough thought in that selector but I always find it a chore to set it to what I want. I feel like it should read my mind 😄 

Any ideas to improve it are welcome

**Comment by ShalokShalom** [comment]
To be honest, I am currently without my laptop and havnt looked yet into your project.

I missed to see a change to the compares page, is there one?

**Comment by bfred-it** [comment]
No we don’t have any changes there, I’m just saying that maybe we should 🙂

**Comment by ShalokShalom** [comment]
I see. As said, I think the shown icon is the perfect place for this, or maybe in the middle between the two compared repos. 

This does fits in the design nicely, without cluttering the UI, so its more probably "only" a question about the technical implementation. 

Do you guys have a process about asking the community how nicely accepted an idea is?

**Comment by bfred-it** [comment]
This would be _as easy as_ turning the arrow into a link that just flips the current URL from: 

```
https://github.com/sindresorhus/refined-github/compare/demo...master
```

to

```
https://github.com/sindresorhus/refined-github/compare/master...demo
```

It might not be "nice and ajaxed" but it should be pretty easy to implement and maintain! PR welcome!

**Comment by ShalokShalom** [comment]
Perfect :D

**Comment by bfred-it** [comment]
Regarding the process:

Either one of the maintainer is interested and marks it as "help wanted" and/or someone shows interest in implementing it directly. There are plenty of [good suggestions](https://github.com/sindresorhus/refined-github/labels/help%20wanted) who are just waiting for a contributor :)

**Comment by ShalokShalom** [comment]
I am no coder, otherwise would this already be done :D

**Comment by bfred-it** [comment]
Funny to find non-coders on GitHub :D

**Comment by ShalokShalom** [comment]
Well, I guess this is also a sane place for the button, maybe even more as on the left side (or both?)

**Comment by Insane96** [comment]
Has this been added in the end?

**Comment by yakov116** [comment]
Yes https://github.com/sindresorhus/refined-github/blob/main/source/features/swap-branches-on-compare.tsx

**Comment by MichaelDimmitt** [comment]
Was not working for me not sure if a version bump is needed?

Refined GitHub Version
`21.4.6`

However, I was able to swap them by changing the url
from:
compare/master...MichaelDimmitt:master
to:
MichaelDimmitt:master...compare/master
