### ISSUE TITLE
Running as a persistent background page on Firefox

### ISSUE THREAD

**Issue by rogersachan** [sindresorhus/refined-github#1219]
I see this error in the debugging page of Firefox.

```
Reading manifest: Error processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

I assume this is not optimal and have made an issue regarding such.

**Comment by bfred-it** [comment]
Thanks for the report! However nothing can be done, that’s just Firefox not supporting lighter event pages, there’s no other way to go about it.
