### ISSUE TITLE
tick is offset

### ISSUE THREAD

**Issue by domoritz** [sindresorhus/refined-github#1221]
Thanks for the awesome tool. I noticed a small visual annoyance. The tick to indicate CI status is not aligned with the text. 

<img width="243" alt="screen shot 2018-03-26 at 14 36 02" src="https://user-images.githubusercontent.com/589034/37934438-161d40d2-3103-11e8-97a2-a6f8d8737f6c.png">

**Comment by shroudedcode** [comment]
Can reproduce. I'm pretty sure it hasn't always been this way. :thinking:

**Comment by bfred-it** [comment]
They added a `margin-top: 5px`. Should be removed. PR welcome! :)
