### ISSUE TITLE
Feature Request: Hide self-love

### ISSUE THREAD

**Issue by idleberg** [sindresorhus/refined-github#1222]
I'm not sure what the `hide-own-stars` is supposed to do (it was enabled by default), I understood it as setting that hides people who star their own repositories. If it is, it doesn't work for me (see below). Otherwise, I think it would be a great option to add, I don't think anybody needs to see this.

**My settings:**

![screen shot 2018-03-27 at 09 46 59](https://user-images.githubusercontent.com/1504938/37953855-63f54178-31a4-11e8-8f2e-4c81d27a7dcd.png)

**My feed:**

![screen shot 2018-03-27 at 09 47 56](https://user-images.githubusercontent.com/1504938/37953891-765d1d72-31a4-11e8-9cc4-c8bbf432bdea.png)

**Comment by sindresorhus** [comment]
> I understood it as setting that hides people who star their own repositories

No, it hides people that star *your* repos.

**Comment by sindresorhus** [comment]
> I don't think anybody needs to see this.

Awkward 😝

**Comment by bfred-it** [comment]
Conflict of interest detected. 

_Before you love others, you must learn to love yourself._

**Comment by bfred-it** [comment]
I can suggest renaming it to `hide-stars-to-current-user-repos`

**Comment by ShalokShalom** [comment]
> No, it hides people that star *your* repos.

What is the sense of this?

**Comment by shroudedcode** [comment]
@ShalokShalom I'm pretty sure it's because big open source guys like @sindresorhus get so many stars on their repositories every day that they fill up their feed making more important events harder to find. I've disabled the feature because I don't get a lot of stars, so an occasional *someone has starred whatever* item in my feed doesn't clutter it.

**Comment by sindresorhus** [comment]
> What is the sense of this?

Because seeing who starred *your* repos doesn't provide any practical value.

**Comment by ShalokShalom** [comment]
I suggest an explanation below the text input field about all the possible settings, so that everyone can see whats available and what it does.

**Comment by bfred-it** [comment]
@ShalokShalom refer to https://github.com/sindresorhus/refined-github/issues/1043#issuecomment-360994160

It's currently not possible. Each file could however have a heading with a short description

**Comment by ShalokShalom** [comment]
+1
