### ISSUE TITLE
Could an extension like this add links to projects to the Github home/landing page?

### ISSUE THREAD

**Issue by lferrao** [sindresorhus/refined-github#1224]
Currently the Github landing page has side panels with repositories, it would be nice for people more involved with projects to have similar quick links to projects on the side. I am wondering if this is something that could be fixed with an extension, since this is not something that can be solved purely with CSS.

**Comment by bfred-it** [comment]
Refined GitHub hides projects whenever possible so I’m not sure it should make API calls to fetch your projects

**Comment by lferrao** [comment]
If you don't mind my asking, why does it hide projects whenever possible? I'm not questioning it, I'm genuinely curious.

**Comment by bfred-it** [comment]
Probably because most repos don't need projects so the extra tab is usually empty and therefore not useful to most.

This request should probably be its own extension
