### ISSUE TITLE
Add local time to hover cards based on user location

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1233]
When collaborating on open-source with people from around the world, it's good to know if the local time with the person you're communicating is in the morning/evening.

![image](https://user-images.githubusercontent.com/506129/38144868-3d868aee-344f-11e8-83ac-2353bbfda6fa.png)

**Comment by jorgegonzalez** [comment]
![image](https://user-images.githubusercontent.com/12901172/38399478-a3e4db1a-3918-11e8-95b7-91fd88535af8.png)
I almost have this working.

**Comment by fregante** [comment]
The previous attempt became rather large and added a permission to Google's servers, which isn't great.

I saw that @SamVerschueren made a CLI tool to get this information https://github.com/SamVerschueren/dev-time and perhaps its logic can be transposed to only use the API in the browser (that tool uses the API to [get the latest push](https://github.com/SamVerschueren/latest-push/blob/master/index.js#L8)) but then uses `git clone` locally to get the actual timezone.

**Comment by SamVerschueren** [comment]
Would be great if the tool didn't had to clone the repository. At the time I made it I couldn't find another way.

**Comment by sarpik** [comment]
Hello, sorry, any updates on this?
https://github.com/sindresorhus/refined-github/pull/1249 isn't ready, right?:/

**Comment by dertieran** [comment]
@fregante I found a way to do this without cloning the repository.
You are also able to find the `AuthorDate` in the `.patch` of a commit.
For example [`b92693c`](https://github.com/sindresorhus/refined-github/commit/b92693c4ee1c6302c74e633fee92876916864d0d.patch)
```
From b92693c4ee1c6302c74e633fee92876916864d0d Mon Sep 17 00:00:00 2001
From: Federico Brigante <opensource@bfred.it>
Date: Sat, 2 Nov 2019 22:01:35 +0700
Subject: [PATCH] Restore mistakenly-deleted function
```

A problems I found with this approach is that `latest-push` includes `PushEvents` where the user is only the committer not the author.
I couldn't find a way to get the `CommitterDate` just through the api except for the `commit.verification.payload` of a commit which isn't really reliable :smile:

This means it is possible but it might include several *(at least two)* requests.
Is this still a viable solution then?

/cc @SamVerschueren if he wants to use this somehow

**Comment by fregante** [comment]
> A problems I found with this approach is that `latest-push` includes `PushEvents` where the user is only the committer not the author.

If we were to use `dev-time` it'd have to adapted to use `fetch` everywhere instead of `got`, together with other changes to bring it down from its 500KB bundled size: https://bundlephobia.com/result?p=dev-time@1.0.1

Otherwise it's probably best to rewrite it from scratch just for RGH.

In short, you can use the `users/${user}/events` endpoint and then find an authored commit.

**Comment by dertieran** [comment]
Okay so I started to play around with this a bit here [`show-local-user-time`](https://github.com/dertieran/refined-github/blob/show-local-user-time/source/features/show-local-user-time.tsx)

It's still WIP, but it already works :smile:

<details>
<summary>Screenshot at 20:02 UTC</summary>

![image](https://user-images.githubusercontent.com/9264728/68534383-4809b580-0334-11ea-91e4-3670a18f9535.png)
</details>

I haven't solved the commiter issuer yet!
But my idea right now is to get a commit for each commit autor and then check the commits to match the event actor.

Also I needed a modified `api.v3` so I copied it for now, not sure how to integrate that yet.

Should I open a *(Draft?)* PR for this?

**Comment by fregante** [comment]
> A problems I found with this approach is that `latest-push` includes `PushEvents` where the user is only the committer not the author.

I don't see any way to find out. I tried looking at the requests being made and I can't find a way to programmatically tell if this commit was authored by me:

https://api.github.com/repos/dertieran/refined-github/commits/8d556c5d9dc0f5471abddacfe84667dd72b1bb23

You can click that link to see the API result in the browser, and here's the `patch` from that commit:

```patch
From 8d556c5d9dc0f5471abddacfe84667dd72b1bb23 Mon Sep 17 00:00:00 2001
From: Jimmy Gaussen <jimmygaussen@gmail.com>
Date: Fri, 8 Nov 2019 02:14:39 +0100
Subject: [PATCH] Allow PR merge-only bots in `dim-bots` (#2519)

---
 source/features/dim-bots.tsx | 4 ++--
 1 file changed, 2 insertions(+), 2 deletions(-)

diff --git a/source/features/dim-bots.tsx b/source/features/dim-bots.tsx
index 18298f96c..6cf43b6a6 100644
--- a/source/features/dim-bots.tsx
+++ b/source/features/dim-bots.tsx
@@ -5,8 +5,8 @@ import features from '../libs/features';
 function init(): void {
 	const bots = select.all([
 		/* Commits */
-		'.commit-author[href$="%5Bbot%5D"]',
-		'.commit-author[href$="renovate-bot"]',
+		'.commit-author[href$="%5Bbot%5D"]:first-child',
+		'.commit-author[href$="renovate-bot"]:first-child',
 
 		/* PRs */
 		'.opened-by [href*="author%3Aapp%2F"]'
```

Who is Jimmy? Who is @fregante? Are they the same person?

Side note: the `Date` above is the date **I** merged the PR, but the timezone matches the original user's, so even if it kinda _is_ the committer date, it's not in the right timezone (it should be `+0700`)

**Comment by dertieran** [comment]
It should be possible to check it the event `actor` is the same as the commit `author` _(from a commit request)_.

So a very simple approach would be:

```js
const event = await getPushEvent(login);
const lastCommit = event.payload.commits[event.payload.commits.length - 1];
const commit = await fetch(lastCommit.url);
if (commit.author.id === event.actor.id) {
    return commit;
}
// Check the next commit or event or load more events...
// This might take a bit but hopefully we are on the happy path 😄
```

<details>
<summary>Example <code>PushEvent</code></summary>

```json
{
    "id": "10820875487",
    "type": "PushEvent",
    "actor": {
        "id": 1402241,
        "login": "fregante"
    },
    "payload": {
        "push_id": 4251725913,
        "commits": [
            {
                "sha": "8d556c5d9dc0f5471abddacfe84667dd72b1bb23",
                "author": {
                    "email": "jimmygaussen@gmail.com",
                    "name": "Jimmy Gaussen"
                },
                "message": "Allow PR merge-only bots in `dim-bots` (#2519)",
                "url": "https://api.github.com/repos/dertieran/refined-github/commits/8d556c5d9dc0f5471abddacfe84667dd72b1bb23"
            },
            {
                "sha": "9a58274d9442427dafd6d533dd92a84e5c2594fa",
                "author": {
                    "email": "github@bfred.it",
                    "name": "Federico Brigante"
                },
                "message": "Merge branch 'master' into add-dashboard-label-links",
                "url": "https://api.github.com/repos/dertieran/refined-github/commits/9a58274d9442427dafd6d533dd92a84e5c2594fa"
            }
        ]
    }
}
```
*I removed some properties*
</details>

**Comment by fregante** [comment]
I think that's right! To put it plainly, `event.actor.id` is YOUR id and we just need to match it to `commit.author.id`. If they match, YOU are the author. Good job!

Now, back to the algorithm here. 😅 I think you need this:

```
function getTimezone(user): string
	while fetchNextEventsPage
		foreach event in eventPage
			if event is pushevent
				fetch commit
				if commit.author.id === event.actor.id
					fetch patch
					return patch.date.timezone
```

**Comment by fregante** [comment]
If you implement this I suggest keeping it in a single function/loop for now, we can optimize it later if needed. It’s easier to just `return` out of the whole loop instead of handling multiple layers of `if function !== NaN`

**Comment by dertieran** [comment]
Okay I [implemented](https://github.com/dertieran/refined-github/blob/show-local-user-time/source/features/show-local-user-time.tsx#L41-L83) it and it works pretty good.
As expected the first commit we check is *valid*.

A good place to test would be the [contributors](https://github.com/sindresorhus/refined-github/graphs/contributors) page.

I already found some interesting edge cases through that :smile:
For example a [commit](https://api.github.com/repos/notlmn-dump/BLUSTRINGS/commits/c63bbb9ddcaef840257aef1538330f28279de304) where the autor is `null` or that commits from a push event are not found *(404)*.

**Comment by gurrrung** [comment]
@fregante Is 12 hour format available?

**Comment by fregante** [comment]
It's not, but PR welcome to replace the `timeFormatter` with [`<local-time>`](https://github.com/github/time-elements#local-time) since it uses the browser's settings

```jsx
<local-time minute="numeric" hour="numeric" datetime={....}/>
```

**Comment by gurrrung** [comment]
I made a commit but I didn't understand how does it gives the 12 hour format. Doc says
  
``When this markup is viewed in a CDT timezone, it will show Apr 1, 2014 6:30PM. If it's viewed in a browser with European date preferences, it will read 1 Apr 2014 18:30.`` which I was not able to understand.

**Comment by gurrrung** [comment]
Hey, how will this further help me in setting 24 Hr format in my PC?
Doc says `When this markup is viewed in a CDT timezone, it will show Apr 1, 2014 6:30PM. If it's viewed in a browser with European date preferences, it will read 1 Apr 2014 18:30.` which I don't understand.

Btw I did some changes and got same 24 hr format. code is [here](https://github.com/gurrrung/refined-github/commit/f1c1d0ad8e41d119630b58a013b311c8c971e668).

**Comment by fregante** [comment]
> When this markup is viewed in a CDT timezone, it will show Apr 1, 2014 6:30PM. If it's viewed in a browser with European date preferences, it will read 1 Apr 2014 18:30.

"CDT timezone" is American and they prefer 12-hour.
European timezones generally prefer 24-hour.

```js
new Intl.DateTimeFormat(undefined,{hour:"numeric", minute:"numeric"}).format(new Date);
```
What does this output for you? It's 12-hour for me because my locale is `en-US`. I don't think it has anything to do with my timezone as their readme suggests, but just the browser's language. Even Safari ignores my OS' preference to display 24-hour so I'm guessing it's all about that locale string.

**Comment by gurrrung** [comment]
![Screenshot from 2019-12-09 09-41-41](https://user-images.githubusercontent.com/30543444/70406872-26513a80-1a68-11ea-8b39-9fa519072071.png)
It looks like 24-hour format because no AM is here.

**Comment by gurrrung** [comment]
![Screenshot from 2019-12-09 09-42-50](https://user-images.githubusercontent.com/30543444/70406909-4bde4400-1a68-11ea-83d8-267e5542094e.png)

**Comment by gurrrung** [comment]
I just did `hour12: true` and worked it out this way. I got my 12-hour format but I can give a PR if you want changes in the code.
