### ISSUE TITLE
Make "New pull request" button on repo page a toggle-able feature

### ISSUE THREAD

**Issue by thetiby** [sindresorhus/refined-github#1237]
This seems to have been the standard from the start: https://github.com/sindresorhus/refined-github/blame/e80442263e81fbbd964c8b94933e4871b4816269/extension/content.css#L166

Would you please allow us to toggle this? I just started using this extension, and I slowly find its benefits, but missing this button is huge for me and maybe others.

**Comment by bfred-it** [comment]
The button is there, but it’s named “Compare” in the “More” dropdown menu. The advantage is that it’s available on every page too.

**Comment by thetiby** [comment]
I see. Still, having it 1 click away as the default is way more convenient. I doubt this would be hard to implement (I could do it myself if needed).

**Comment by bfred-it** [comment]
“New pull request” is available exclusively on the main Pull Requests page, so in most cases you’re still two clicks away (one of which has to load a new page instead of opening a dropdown)

**Comment by thetiby** [comment]
I mean, if I want to navigate from the main repo to my own fork, I usually rewrite the url using my username instead of the main repo username, from where I switch to the branch that I pushed changes to, and, if the pop-up where I can create a PR doesn't appear, I use that button. Other times, I'm already on that fork page, so I just use that button. I have never used it on the Pull Requests page.

**Comment by bfred-it** [comment]
> I have never used it on the Pull Requests page.

Where else does it appear?

**Comment by thetiby** [comment]
![image](https://user-images.githubusercontent.com/2418978/38164730-50567054-3511-11e8-98e5-e7c93029e70d.png)
Main repo page

**Comment by bfred-it** [comment]
Oh that one. 

I think we can’t undo that because we have potentially too many buttons there now. If you need it you can add some CSS in the options.
