### ISSUE TITLE
Create a new Issue from anywhere in the repo

### ISSUE THREAD

**Issue by juliocanares** [sindresorhus/refined-github#1239]
**Description**

I was wondering if adding a button to create a new issue from anywhere in the repo could be a good idea, something just like the create pull request button that shows up when a new branch is pushed.

**Use case**

I always need to create new issues, after code reviewing or while refining the backlog. It usually takes me many clicks going to the main page of the repo or clicking on the issues tab and then pushing on the new issue button.

**UI proposal**

![image](https://user-images.githubusercontent.com/5007653/38176749-3ca90360-35ba-11e8-97ac-cf57eba695f4.png)

what do you guys think about it? I'd like to hear some feedback before coding 💻

**Comment by hkdobrev** [comment]
<kbd>g</kbd> <kbd>i</kbd>. <kbd>c</kbd> = Go to Issues. Create new issue.

**Comment by juliocanares** [comment]
@hkdobrev didn't know that. thank u.

**Comment by hkdobrev** [comment]
See the full shortcut list by typing <kbd>?</kbd>. It was [recently enhanced by Refined GitHub](https://github.com/sindresorhus/refined-github/pull/1107) adding the shortcuts we're registering as well. Cheers!
