### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#124]
Extracting logic into separate files with simple interface (see #99, #120) is allowing us to write unit tests for the functionality more easily. Do you think it's worth it?

**Comment by DrewML** [comment]
Would love to see this. With #99, I was a bit worried while getting my feet wet that I'd break other pages when modifying the URI checks. Would give more confidence to future contributors that need to modify those.

Testing the public methods of some of the modules (ex: `diffheader.js`) that rely heavily on GitHub DOM may be a bit difficult unless we want to hit GitHub.com in a test, or maintain a fixture for our target pages (this is what the [injector](https://github.com/octo-linker/injection/blob/master/test/fixtures/repo_browser.html) script we're using does).

**Comment by hkdobrev** [comment]
I'd prefer to test on top of a fixture page and some unit tests won't require a full-fledge fixture page. For example the URL checks (#120) could have just a few-lines long fixture page for a true unit test (as in the opposite of integration test).

**Comment by paulmolluzzo** [comment]
Creating a list of URLs to use as a test fixture for the regex is fairly easy, though has to be maintained of course. Dumping HTML into fixtures for those pages is a PITA. Trying to get tests for anything that checks rendered display is going to be a lot of effort for little payoff.

**Comment by hkdobrev** [comment]
> Trying to get tests for anything that checks rendered display is going to be a lot of effort for little payoff.

Agreed, I think we can just start testing easy things so there isn't so much initial dev cost and maintenance cost, but the payoff would be on each Travis CI build. Testing all of the UI changes would be harder and would require more maintenance indeed.

**Comment by DrewML** [comment]
Initial unit tests are in `master`, and test the page detector. We can open up new issues if there are different pieces we wish to add tests for.
