### ISSUE TITLE
Feature Request: wide formatting

### ISSUE THREAD

**Issue by gdevenyi** [sindresorhus/refined-github#1243]
There are a number of wide extensions available for github in working or partially working state.

An active project like this is a good place to add such a feature where breaking changes could be caught quickly and fixed :+1:

**Comment by gdevenyi** [comment]
https://chrome.google.com/webstore/detail/wide-github/kaalofacklcidaampbokdplbklpeldpj?hl=fr&gl=FR
https://github.com/mdo/github-wide
https://github.com/xthexder/wide-github
https://github.com/sqren/github-widescreen
https://chrome.google.com/webstore/detail/github-widescreen/elikdceclccjilahimjfceoalhdbndan?hl=en

**Comment by yakov116** [comment]
@gdevenyi #1171

**Comment by busches** [comment]
Closing as a duplicate of #1171 and #1172.

**Comment by gdevenyi** [comment]
Oh man come on, the word "wide" isn't anywhere. I promise I searched.
