### ISSUE TITLE
linkify the "into" and "from" branches in a PR

### ISSUE THREAD

**Issue by tallen1983** [sindresorhus/refined-github#1246]
The top line of a PR shows:

    	USER  wants to merge N commits into BRANCH1 from BRANCH2

It is much more convenient if BRANCH1 and BRANCH2 were linkified, taking us to the page REPO/tree/SYNC-10162

The branch name near the bottom of the PR in the text "Add more commits by pushing to the BRANCH2 branch on REPO." _is_ linkified (both BRANCH2 and REPO are actually).

**Comment by hkdobrev** [comment]
This was done as one of the first few features of the extension. Could you point us to a pull request where the branches are not linked? Thanks!

**Comment by tallen1983** [comment]
@hkdobrev you are right. I'm not sure what happened to one of my PR page loads, but it definitely didn't linkify that one time. Since posting this issue I bounced to different PRs and the branches are indeed linkified. Going back to the PR that had this issue, they are linkified again.

I can't seem to reproduce it now which is very strange. I'll keep my eye on it to see if it happens again, but for now I'll close it.

**Comment by hkdobrev** [comment]
The linkified branches and a couple of other changes are lost when GitHub updates dynamically some content like updating labels or the title of a PR. We could probably use an element observer there as well, but that is more difficult in some cases. It could possibly be done for the branch links, but not sure if someone already tried that.
