### ISSUE TITLE
Weird red highlighting

### ISSUE THREAD

**Issue by pedro-mass** [sindresorhus/refined-github#1251]
Can't tell if this is a feature I don't know about, but it makes reading diffs in a PR harder with all the red highlighting.

![image](https://user-images.githubusercontent.com/1165961/38514664-cc985304-3bff-11e8-8fa2-30da7458f150.png)

**Comment by bfred-it** [comment]
Where? Link please

**Comment by bfred-it** [comment]
Yeah this is definitely not Refined GitHub. That color is applied by GitHub when there's a syntax error. Example: https://github.com/bfred-it-obsolete/test/blob/master/a.json
