### ISSUE TITLE
remove-upload-files-button does not whitelist

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#1258]
In my opinion, adding 'remove-upload-files-button' to the whitelist is supposed to bring that line back: 

![screenshot_20180414_190158](https://user-images.githubusercontent.com/6344099/38770653-7aa2fb42-4016-11e8-9486-4d266f6467d5.png)

It does not. (Firefox, Linux)

What should I trigger instead?

**Comment by ShalokShalom** [comment]
Duplication: https://github.com/sindresorhus/refined-github/issues/1242

**Comment by bfred-it** [comment]
That line is hidden via CSS and you can undo it via custom CSS.

The feature you named actually removes the upload button on the repo file listing.

**Comment by bfred-it** [comment]
I saw your other comment. Perhaps you’re just missing this feature: https://github.com/sindresorhus/refined-github/issues/1242

The upload button is there but isn’t currently working.

**Comment by ShalokShalom** [comment]
Some documentation might be helpful.
