### ISSUE TITLE
Use LGTM.co service

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#126]
https://lgtm.co/ is a very neat service which works really well with GitHub Commit Status API and GitHub protected branches. Basically when a new PR is opened it will set the status of the PR to failed and it will keep listening to comments on the PR. When a certain regex check is detected in the comments by enough maintainers it will set the PR status to green which will allow the merge (based on GitHub protected branches settings).

So this is very useful for detecting if maintainers have approved the change and setting common rules like what text to be detected as an approval and how many maintainers need to approve before it's marked as approved.

I encourage you to go through the documentation and enable it.

@sindresorhus What do you think? Since you have admin rights to the repository you'd need to set it up and configure protected branches. With protected branches admins could merge a PR even if required checks have failed and collaborators cannot. I believe this would help you even more and ease you in the future when working with more collaborators. If not sure it's useful in general you could at least try it on this repo to see whether it's worth it adding on more of your repos.

**Comment by sindresorhus** [comment]
I was excited when it came out and added it to [AVA](https://github.com/sindresorhus/ava) immediately. After having it running for a month we decided to remove it. It turned out to be more of a burden than actually useful. I'd rather trust my collaborators. Our workflow is very simple anyways. We only require one other collaborator to LGTM something.

**Comment by hkdobrev** [comment]
@sindresorhus It seems you might have used it more than myself. When there's no LGTM and you just want to merge a PR you've opened, could you just write `LGTM` yourself and go ahead with the merge?

**Comment by sindresorhus** [comment]
@hkdobrev No, you would need a LGTM from another collaborator, unless of course you're the repo owner, then you can do anything.

**Comment by hkdobrev** [comment]
Well then I can see how it could be a burden sometimes. I'll go ahead and close this, but if you have any more feedback and how the service was useful and how it was a burden, I'd love to hear it. I was planning to introduce it to more and more company repositories.

**Comment by hkdobrev** [comment]
@sindresorhus Just a ping if you want to revisit this with the new changes to protected branches from GitHub: https://github.com/blog/2137-protected-branches-improvements

I've tried it out and it offers quite granular control.

**Comment by sindresorhus** [comment]
@hkdobrev I'm aware, but that was never really an issue. If you want to try out LGTM.io here, feel free.
