### ISSUE TITLE
Add info text how to separate names in features-to-disable

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#1260]
Currenty, there is no info text available, how to separate the different names in the features-to-disable field. Commas? Semicolons? Spaces?

**Comment by bfred-it** [comment]
There’s an example in the placeholder. It’s a space. Any white space works

**Comment by ShalokShalom** [comment]
Oh, I thought that is one unit :D

**Comment by bfred-it** [comment]
Actually anything works since we just search the whole string with `String#includes` 😅 you can even have it ❤-separated

**Comment by ShalokShalom** [comment]
Lol ^-^
