### ISSUE TITLE
Enable the extension to set merge commit title and message PR

### ISSUE THREAD

**Issue by alex-111-gh** [sindresorhus/refined-github#1264]
In Merge commit workflow it would be great to replace generic github behavior with the following, more sensible one:

**Merge commit title**: 
`PR title (#PR ID)` (follows the existing `fix-squash-and-merge-title` feature convention)
**Merge commit message**: 
PR description (top comment in a PR)

BTW, I already have a working code, can check in.

**Comment by alex-111-gh** [comment]
@sindresorhus FWIW, I've issued a PR #1265

**Comment by alex-111-gh** [comment]
@hkdobrev If I am not mistaken, the set of inconsistencies is in line with `fix-squash-and-merge-title` feature that is already in `refined-github` extension. I love that feature btw. Automating fill-up of a merge commit message with meaningful description from PR description is a huge productivity boost.

**Comment by hkdobrev** [comment]
@alex-111-gh The `fix-squash-and-merge-title` is fixing a functionality already provided by GitHub, but just not consistent for PRs with a single commit. We just unified it. See #276.

**Comment by alex-111-gh** [comment]
@hkdobrev Got it, I've noticed that annoyance too.

**Comment by hkdobrev** [comment]
Anyone have more thoughts on this (including @alex-111-gh)? I'm thankful for the contribution, but I'm concerned with the inconsistency. For example, my team members who are not using RG would start asking me why I am renaming every PR merge commit like that making it different than the merges they do.

**Comment by alex-111-gh** [comment]
In my view the default merge commit title and message are not useful. Assuming a developer enters relevant PR title and PR description, this enhancement streamlines merging process, projecting relevant info from GitHub into git repo.
Re: consistency: Using or not using RG is largely a team policy. In particular, if team elects useful merge commit information, then it has two choices: do it by hand and/or do it with RG.

**Comment by bfred-it** [comment]
> In my view the default merge commit title and message are not useful

Merge commits are pretty useless anyway since all the commits are visible below them. If the maintainers prefer using merge commits, the noise in the commit list is their own fault.

Like @hkdobrev said, it's best the merge commits keep their current format so people can mentally filter them out with or without RGH.

If we have to improve the commit message I'd just shorten it to "Merge of ###"

**Comment by sindresorhus** [comment]
I agree with @bfred-it.

**Comment by bfred-it** [comment]
Agree with **leave as is** or **change to "Merge of ###"**?

**Comment by busches** [comment]
@bfred-it given that he downvoted on the OP as well, going with **leave as is**

**Comment by hkdobrev** [comment]
@alex-111-gh Closing based on the discussion and lack of endorsement from maintainers. Refined GitHub would always stay an opinionated project of course, but please don't let not merging that functionality stopping you from contributing other awesome features!

**Comment by fregante** [comment]
GitHub implemented it

https://github.blog/changelog/2022-08-23-new-options-for-controlling-the-default-commit-message-when-merging-a-pull-request/
