### ISSUE TITLE
Add shortcut for hiding a comment as "Resolved"

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1268]
[GitHub introduced support for hiding comments](https://blog.github.com/2018-04-18-new-tools-for-open-source-maintainers/), but it requires many clicks to hide a comment as "Resolved". Since that's the most common use-case for hiding comments, it would be nice to make it faster.

Maybe a keyboard shortcut, so you hold a certain key down while clicking the comment?

// @jamiebuilds

**Comment by bfred-it** [comment]
Comments can’t be navigated via keyboard so the keyboard shortcut would feel weird. If GitHub’s menus support sub-menus we can just move the actions directly in the sub-menu of “hide” so they’d be one-click.

**Comment by sindresorhus** [comment]
@bfred-it That's why I suggested holding a key down while mouse clicking the comment. But your suggestion would work too. Maybe even both?

**Comment by bfred-it** [comment]
> holding a key down while mouse clicking the comment

Clicking where? That's an unusual interaction

**Comment by bfred-it** [comment]
The dropdown doesn't seem to support sub-menus. Maybe we can give this the same treatment we gave to the review box: 

<img width="331" alt="" src="https://user-images.githubusercontent.com/1402241/38982793-0f2d2d30-43ed-11e8-80c9-5619bf50d7c5.png">

Drop the drop-down, show 5 buttons (aligned top right)

**Comment by sindresorhus** [comment]
> Clicking where? That's an unusual interaction

Anywhere inside the comment box.

> Drop the drop-down, show 5 buttons (aligned top right), sort of like:

Yes, looks great!

**Comment by jamiebuilds** [comment]
You could go even further by expanding the dropdown:

<img width="204" alt="screen shot 2018-04-19 at 5 29 37 pm" src="https://user-images.githubusercontent.com/952783/39024672-4d013232-43f7-11e8-8072-19af30ae896d.png">

Maybe could be improved with some styling

**Comment by jamiebuilds** [comment]
> Comments can’t be navigated via keyboard so the keyboard shortcut would feel weird.

btw that sounds like it'd be a great feature to add

**Comment by sindresorhus** [comment]
> You could go even further by expanding the dropdown:

I thought about that, but it makes the menu very large. Better to optimize for the common use-case instead.

**Comment by bfred-it** [comment]
Perhaps the dropdown code can be abused to link "hide" to a new dropdown that would replace that. I'm not a fan of my own mockup's style 😄

**Comment by tgolen** [comment]
I would love to see this be done, so I'd like to re-ignite this conversation. I kind of opened a duplicate issue with an alternate proposal. I think doing something (anything) to improve this would have huge value, even if it's not perfect.

What about expanding the first dropdown to have all the hide options in it, and then have that dropdown menu display on hover (which removes one extra click)?

Even just expanding the first dropdown would be a great place to start, and we can iterate on it past that.

**Comment by yakov116** [comment]
@bfred-it was there a reason you did not implement this?
>Drop the drop-down, show 5 buttons (aligned top right), sort of like:
>![image](https://user-images.githubusercontent.com/16872793/42529439-7dcc7f76-844c-11e8-87a6-ba3e2b9eb1f0.png)

**Comment by bfred-it** [comment]
> @bfred-it was there a reason you did not implement this?

Time
