### ISSUE TITLE
Comment context diffs have non-working zoom cursor for collapsing

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#127]
When you are looking at diff comment in a PR, e.g. https://github.com/sindresorhus/refined-github/pull/112#discussion-diff-57938519 you still have the zoom cursor on the file headers for collapsing, but it's not working.

I guess we could try to remove them from there instead of supporting collapsing as I don't see them much needed in the inline diffs.

**Comment by DrewML** [comment]
Nice catch! My vote is to just remove the cursor, since GitHub already has a `Hide comments` button there that does the same thing.

![image](https://cloud.githubusercontent.com/assets/5233399/14161495/cb4982e0-f6a9-11e5-93cd-caf76c3e0b33.png)

**Comment by sindresorhus** [comment]
Yeah, just remove the zoom.

**Comment by hkdobrev** [comment]
That's what I meant, just remove the zoom cursor from these inline diffs with CSS. The functionality is not working here anyway.

**Comment by sindresorhus** [comment]
@hkdobrev Yup. I got what you meant. Was just agreeing :)
