### ISSUE TITLE
Feature Request: show link from GitHub Pages to GitHub repo

### ISSUE THREAD

**Issue by styfle** [sindresorhus/refined-github#1274]
Often times, users put up a HTML/JS demo on GitHub Pages but then don't link to the GitHub repo.

For example: https://mdn.github.io/dom-examples/streams/grayscale-png/
Actual repo: https://github.com/mdn/dom-examples/tree/master/streams/grayscale-png

This is pretty easy to derive from the URL but the question is:
Where should the "link" live?
Can this be added to the [options dialog](https://user-images.githubusercontent.com/229881/39069378-958239be-44ad-11e8-9e68-63703f0d6593.png)?

**Comment by styfle** [comment]
> I don't get how the options of the Refined GitHub extension are related to that.

This is a common pattern for tools like React Dev Tools which change the icon and content of the popover depending on if the current page is using React. For example:

### Not using react
![none](https://user-images.githubusercontent.com/229881/39070733-808aea2e-44b2-11e8-9fcd-779718dd7b0a.png)

### Using react in dev mode
![dev](https://user-images.githubusercontent.com/229881/39070757-90bd4a18-44b2-11e8-9102-475327eeebe4.png)

### Using react in prd mode
![prd](https://user-images.githubusercontent.com/229881/39070776-a331aa90-44b2-11e8-8c3a-170413b39e71.png)

I think that there could be something similar for the purple octocat to light up green when visiting github.io page and when you click it, it takes you to the corresponding repo.

**Comment by hkdobrev** [comment]
Got what you mean now, still what you describe is great for a specific extension for GitHub Pages.

**Comment by styfle** [comment]
> we'd need to ask for permissions for *.github.io/* as well and doesn't actually enhance GitHub, but just some of the GitHub pages

The thing is, GitHub Pages is a feature of GitHub.
"Refined GitHub" already shows the GitHub Pages build status.
Why not add a link the other direction?

I don't think users of "Refined GitHub" will be worried about requesting access to github.io because it is so closely coupled with GitHub.

![check](https://user-images.githubusercontent.com/229881/39071214-3c929810-44b4-11e8-8b41-65651cdb8f4d.png)

**Comment by bfred-it** [comment]
I don’t think this would make a lot of sense on its own but I see what you mean. My main concern is that our scripts/styles are injected on ALL domains we have permissions on, so adding a button on the page would complicate GHE support a lot (without even going into the “where to place the button without braking sites” issue)

How about adding another item in the BrowserAction dropdown? We wouldn’t need to add more permissions (other than `activeTab`) and it would solve all the issues. The only remaining issue is discoverability… and probably sub-optimal code to only show the item on github.io domains. 

Probably it’s just easier to implement it as a bookmarklet. 👍

**Comment by bfred-it** [comment]
Both those tools are enabled on all domains; RGH isnt

**Comment by bfred-it** [comment]
Finally, there's no straightforward way to do so (unlike what I thought with the bookmarklet)

https://webpack.github.io/ should point to
https://github.com/webpack/webpack.github.io, as described in the docs: https://pages.github.com/, but that repo is a 404.

Also subpages could either point to the main "user repo" or to a sub-repo, and there's no easy way to tell by looking at the URL.

Example:
https://user.github.io/folder/ 

Is this the `user/folder` repo or the folder `folder` in the `user/user.github.io` repo?

I'll have to close as it's a 50/50 chance that our link would be a 404
