### ISSUE TITLE
List of all the available features 

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#1275]
Hi there :) 

I am confused by all the available options sometimes, especially since they are named similar sometimes and without any additional description.

Is it appropriate to display the different options with a short description in an own Readme?

**Comment by bfred-it** [comment]
I think we can just add a header in the JS files so the docs are directly linked to the feature names and don’t risk being forgotten.

**Comment by ShalokShalom** [comment]
Very good

**Comment by yakov116** [comment]
@bfred-it any specific style?

**Comment by bfred-it** [comment]
I think we can probably just copy-paste the text from the readme, then place the screenshot link(s) on separate lines under it. Additional caveats and notes can go under it. 

I think this is Sindre’s style? 

```JavaScript
/*
Text
*/
```

**Comment by ShalokShalom** [comment]
Maybe a GIF?

**Comment by bfred-it** [comment]
Most of our features already appear in the readme. Those that need it have a gif or image attached.

**Comment by bfred-it** [comment]
??
No new wiki page. Just comments in the headers of JavaScript files. There’s already a link to the feature list in the options.

**Comment by bfred-it** [comment]
This has been happening for new features and old ones are updated when we touch thouse files.
