### ISSUE TITLE
Copy code feature no longer works

### ISSUE THREAD

**Issue by tongrhj** [sindresorhus/refined-github#1278]
Referring to the Copy feature implemented by https://github.com/sindresorhus/refined-github/pull/771

Has Github removed / modified their native `zeroclipboard` feature?

# To Replicate:
Try using the copy button in any of the test files in that PR. No text is copied. Example [test file](https://github.com/sindresorhus/refined-github/blob/master/license), [gist file](https://gist.github.com/addyosmani/fd3999ea7fce242756b1), [copy file path](https://github.com/sindresorhus/refined-github/pull/771/files)

**Comment by bfred-it** [comment]
Apparently they changed the implementation, we can probably still use it.

<img width="479" alt="clipboard-copy" src="https://user-images.githubusercontent.com/1402241/39179889-ae6e1ddc-47df-11e8-8cae-372f6e0b989c.png">

**Comment by bfred-it** [comment]
I figured out how this new `clipboard-copy` element works: it uses the `for` attribute like `label` elements do, to point to the element to be copied.

This means that `for` must be set to the element's `id` so we need to create an `id` on the spot and refer to it.

A simple counter would work:

```js
let button = 0;

...

contentToBoCopied.id = contentToBoCopied.id || `rgh-content-${button++}`;

<clipboard-copy for={contentToBoCopied.id}>
```

**Comment by bfred-it** [comment]
It doesn't work again
