### ISSUE TITLE
Expand diffs in either direction

### ISSUE THREAD

**Issue by aengelberg** [sindresorhus/refined-github#1288]
One thing that has always irked me about Github is that even though the diff expand button looks omnidirectional:

![image](https://user-images.githubusercontent.com/4122172/39450982-fd03eba6-4c81-11e8-8aa8-3bf74d741e8f.png)

It actually only expands the bottom chunk upward.

![image](https://user-images.githubusercontent.com/4122172/39450999-079443d6-4c82-11e8-8e4f-86a409c9e685.png)

There is literally no way to expand the top chunk downward if, for example, I wanted to see lines 27 and up. This is especially annoying when there are gaps of hundreds of lines in between the chunks.

I'd love a way to expand from either end, possibly by splitting the expand button into two separate buttons that each indicate which side they expand.

**Comment by Mottie** [comment]
It was a pain, but I figured out how to modify the expand button `data-url` in [this userscript](https://greasyfork.org/en/scripts/369373-github-diff-expander). Hopefully, I added enough comments to make it easy to add to this extension.

<table>
  <thead><tr><th>Before</th><th>After</th></tr></thead>
  <tbody>
    <tr>
      <td><img src="https://raw.githubusercontent.com/Mottie/GitHub-userscripts/master/images/github-diff-expander-before.png" alt="before"></td>
      <td><img src="https://raw.githubusercontent.com/Mottie/GitHub-userscripts/master/images/github-diff-expander-after.gif" alt="after"></td>
    </tr>
  </tbody>
</table>

**Comment by bfred-it** [comment]
Great job, Mottie! Given the complexity I'd be ok just leaving it as a userscript

**Comment by Mottie** [comment]
Sure, go for it!

**Comment by nsoranzo** [comment]
That's been finally implemented by GitHub: https://twitter.com/github/status/1090684311492165632

This issue can be closed.

**Comment by bfred-it** [comment]
Neat! We probably need to update the code we use to make the whole line clickable
