### ISSUE TITLE
Combine upvote/downvote with issue reaction

### ISSUE THREAD

**Issue by leocaseiro** [sindresorhus/refined-github#129]
I have a suggestion. it's nice having the sidebar for upvote/downvote, but the "new" reactions add more votes.

That would be nice we either combine all reactions at the sidebar or just add to the sum of the issue first author comment.

Any thoughts? I'm happy to work on it.

**Comment by hkdobrev** [comment]
> That would be nice we either combine all reactions at the sidebar or just add to the sum of the issue first author comment.

@leocaseiro Could you be more elaborate on how you want this to work?

**Comment by hkdobrev** [comment]
Also a bit related where you might want to chime in is #95.

**Comment by leocaseiro** [comment]
Exactly what is in #95
