### ISSUE TITLE
Remove whitespace toggle

### ISSUE THREAD

**Issue by levrik** [sindresorhus/refined-github#1292]
![image](https://user-images.githubusercontent.com/9491603/39513637-49af751e-4df5-11e8-99c5-a1da55b9672a.png)

GitHub itself offers this functionality now.

**Comment by sindresorhus** [comment]
I would prefer to hide the native GitHub toggle.

**Comment by bfred-it** [comment]
> I would prefer to hide the native GitHub toggle.

In that case, the current [add-diff-view-without-whitespace-option](https://github.com/sindresorhus/refined-github/blob/c88fb35916ffaf0201c7777de96188a8c99181fc/source/features/add-diff-view-without-whitespace-option.js) needs to be changed to something like "set diff settings faster" and also extract the Unified/Split form

**Comment by bfred-it** [comment]
What if we just replace the text with one of these icons?

<img width="82" alt="screenshot 2018-12-09 at 18 39 13" src="https://user-images.githubusercontent.com/1402241/49696778-c409f380-fbe1-11e8-94c1-388a194eda52.png">

**Comment by busches** [comment]
@bfred-it I like the icon idea, would we also want to hide the "Just for now" section, if the [add-diff-view-without-whitespace-option](https://github.com/sindresorhus/refined-github/blob/c88fb35916ffaf0201c7777de96188a8c99181fc/source/features/add-diff-view-without-whitespace-option.js) is enabled?
