### ISSUE TITLE
Expanding comment editor

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#1299]
I often find the comment editor too small and have to scroll down, and then drag down on the tiny little handle in the corner to make it bigger. Its really hard to click on too.

**Ideas**

- How about a button to expand the size of the editor?

- Or what about auto-expanding if the text overflows it?

- An easier handle, maybe in the center bottom of the text editor, seeing as the corner handle appears to afford resizing horizontal which is impossible.

- The bottom of the text editor sticks to the bottom of the viewport, and scrolling down expands the size of the editor to a maximum of the viewport height. Scrolling up reduces the size to a minimum of the default height.

![untitled 2](https://user-images.githubusercontent.com/281413/39664500-27e1473c-5084-11e8-863c-96affb0786c5.jpg)

**Comment by notlmn** [comment]
This might be a good idea.

The auto-expanding text field has been implemented already by @bfred-it in the extension options. This should be no different.

**Comment by vjpr** [comment]
Where do I find the extension options?

**Comment by notlmn** [comment]
* Click on the extension icon on the top right bar
* Or go to `chrome://extensions`, click `Details` for the extension, then select `Extension options`

**Comment by sindresorhus** [comment]
This was fixed by https://github.com/sindresorhus/refined-github/pull/1871.
