### ISSUE TITLE
hover over avatar in top bar disappears when on homepage.

### ISSUE THREAD

**Issue by joshmanders** [sindresorhus/refined-github#13]
Noticed if you're on your activity on the homepage, and you hover over your avatar on the topbar, the dropdown disappears if you hover try to access any links because of what I assume is `z-index` issues with the account switcher being moved.

**Comment by sindresorhus** [comment]
Confirmed, though a bit random. Would you be interested in looking into it?

**Comment by joshmanders** [comment]
Indeed when I get some free time I'll take a peek at it. Should be pretty easy to fix.

**Comment by joshmanders** [comment]
Was waiting for docker container to build, so I fixed it quickly. https://github.com/sindresorhus/refined-github/pull/16
