### ISSUE TITLE
Make issue status always visible when viewing an issue

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#1300]
I often find myself scrolling to the top to check whether an issue has been closed.

Even if I visit the issue at the top, I often don't notice the open/closed, or I forget by the time I have read through some comments because I am looking for a specific bug fix or mention of something.

And then there is the case where you navigate to a comment directly.

I also find that when there is a referenced issue at the bottom of the issue I confuse it with the status of the current issue, the "Open" badge next to the referenced issue could be made less prominent/lighter color.

We should add the status to the bar on the right.

**Comment by bfred-it** [comment]
Making the current issue status more visible sounds good, but making the others less visibile doesn’t.

**Comment by salmanulfarzy** [comment]
Something like this ?

| ![open issue](https://user-images.githubusercontent.com/10276208/39884967-1580b6a8-54a9-11e8-95c1-61bed42821f8.png)  | ![closed issue](https://user-images.githubusercontent.com/10276208/39885039-43b30918-54a9-11e8-8b1a-bf4add0c209e.png)  |
|:-:|:-:|

If we're making issue status sticky, 
- Should we also make the right sidebar sticky ? 
- What should we do about the issue status and (the related pull request reference) at the top ?
- Is this change applicable to pull request pages ?

**Comment by bfred-it** [comment]
Sticky sidebar has been talked about in a separate thread (more info there)

I think it should not be a full replacement of the one in the header because we don’t want race conditions with our `extend-issue-status` feature. Perhaps showing a red/green/purple circle/corner somewhere would be preferrable.

**Comment by salmanulfarzy** [comment]
May be too subtle, What about coloring `border-top` of `sidebar-item` ?

**Mockup**

<details>
<summary>Closed Issue</summary>

![issue-closed](https://user-images.githubusercontent.com/10276208/39912811-8fb3f1f0-551d-11e8-8527-14b5a6254753.png)
</details>

<details>
<summary>Open Issue</summary>

![issue-open](https://user-images.githubusercontent.com/10276208/39912814-904ef5ec-551d-11e8-9505-4f9edf8283b4.png) 
</details>

<details>
<summary>Merged PR</summary>

![pr-merged](https://user-images.githubusercontent.com/10276208/39912813-900f410e-551d-11e8-96fe-ec042798e9ba.png)
</details>

**Comment by Mottie** [comment]
I created a [userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-issue-show-status) that adds the issue status similar to @salmanulfarzy's screenshots, but without the icon.

![](https://cloud.githubusercontent.com/assets/136959/26712526/dee3c700-472c-11e7-9128-5573cd137f46.gif)

**Comment by salmanulfarzy** [comment]
Awesome @Mottie :clap: . But looks like it duplicates the **mark as unread** button.

![duplicate unread button](https://user-images.githubusercontent.com/10276208/39959487-03404c14-5630-11e8-990d-0c9ad97e3099.png)

**Comment by Mottie** [comment]
Hmm, that appears to be an issue with Refined GitHub. When the discussion sidebar is modified, it adds the mark unread button without checking to see if one is already there ([ref](https://github.com/sindresorhus/refined-github/blob/master/source/features/mark-unread.js#L373)).

**Comment by styfle** [comment]
I solved this for myself by making the entire header "sticky" using the following CSS.

### CSS

```css
#partial-discussion-header {
  position: sticky;
  top: 0px;
  z-index: 1;
  background: #fff;
}

.gh-header-meta {
  border-bottom:0px;
}

.gh-header-meta:before {
  content: "";
  position: absolute;
  left: 0;
  bottom: 0;
  height: 1px;
  width: 700px;
  margin-left: 60px;
  border-bottom: 1px solid #e6ebf1;
}
```

### Screenshot

![sticky header](https://user-images.githubusercontent.com/229881/42049986-b10295f4-7ad5-11e8-9ca4-2c410f776bb3.png)


Note the "Make issue status always visible when viewing an issue" title and the "Open" indicator stick to the top as you scroll down 😄

**Comment by lukehefson** [comment]
> Well, look at this beauty by GitHub :)
> 
> [image]

Hehe, you got us 😉. 

Just shipped!: https://blog.github.com/changelog/2019-01-04-sticky-coversation-headers/ 🚀 

Thanks (as ever) to y'all for helping to inspire us with this one 💛
