### ISSUE TITLE
Pinned Repository Selection Scrolling Broken in Firefox

### ISSUE THREAD

**Issue by alichtman** [sindresorhus/refined-github#1301]
<img width="1006" alt="image" src="https://user-images.githubusercontent.com/20600565/39707297-a47f6980-51d9-11e8-90ee-abd2ddbed01a.png">

Steps to reproduce: 

1. Open Firefox Quantum 59.0.2 (64-bit)
2. Navigate to https://github.com/username
3. Click "Customize Pinned Repositories"
4. Scrolling downwards scrolls in the background window (profile page), not the selection menu.

**Comment by yakov116** [comment]
```Uncaught (in promise) TypeError: Cannot set property 'textContent' of null
    at add_scoped_search_on_user_profile (content.js:3120)
```
Its working on chrome

**Comment by alichtman** [comment]
Updated title to more specifically define problem. @yakov116

**Comment by MasterOfTheTiger** [comment]
I was able to reproduce.

**Comment by alichtman** [comment]
Preview with Refined Github disabled:

<img width="521" alt="image" src="https://user-images.githubusercontent.com/20600565/39712675-8947a460-51e9-11e8-86ef-5fd5b3aec610.png">

This is definitely a bug.

**Comment by bfred-it** [comment]
This is definitely not a bug

![as](https://user-images.githubusercontent.com/1402241/39817810-dacaf818-53a7-11e8-9abf-08555fc6b491.gif)

Are you sure you don't have any conflicting CSS in the options?

That element is made scrollable by an `overflow: auto !important` on an element which uses classes we do not target anywhere.

Please check in the Developer Inspector to see what rule is overriding this property for you

**Comment by MasterOfTheTiger** [comment]
I am experiencing the same issue.

**Comment by bfred-it** [comment]
> Please check in the Developer Inspector to see what rule is overriding this property for you

or send a PR
