### ISSUE TITLE
Pinned Repository Selection/Deselection not Saving in Firefox

### ISSUE THREAD

**Issue by alichtman** [sindresorhus/refined-github#1302]
Maybe related to #1301.

Changes in the "Customize Your Pinned Repositories" menu aren't reflected on GitHub.

Steps to reproduce:

1. Open Firefox Quantum 59.0.2 (64-bit)
2. Navigate to github.com/username
3. Click "Customize Pinned Repositories"
4. Select/Deselect any repository.
5. Close the window and see that changes have not been applied.

**Comment by yakov116** [comment]
@alichtman Why is the this #1301?

**Comment by alichtman** [comment]
@yakov116, I think they're separate issues.

This relates to changes made in the selection menu not being applied, whereas #1301 relates to the scrolling being broken for the selection menu.

**Comment by MasterOfTheTiger** [comment]
Maybe a clearer title would be better. Maybe like: "Pinned Repository Selection/Deselection not Saving in Firefox" or something.

**Comment by bfred-it** [comment]
That’s not a Refined GitHub feature. Is RGH breaking a native GitHub feature?

**Comment by MasterOfTheTiger** [comment]
@bfred-it That is what it seems like.

**Comment by alichtman** [comment]
@bfred-it Yes. RGH breaks this native GitHub feature.

**Comment by bfred-it** [comment]
I tested. Cannot reproduce. Make sure you're clicking "Save pinned repositories"

If it still does not work, check the console.

**Comment by alichtman** [comment]
Tried this again today and also can not reproduce. 

Potentially fixed by any of the 4 commits made today.
