### ISSUE TITLE
Add onHover preview for `y` Profile on "x Started Following y" Newsfeed Events

### ISSUE THREAD

**Issue by alichtman** [sindresorhus/refined-github#1303]
Hovering over the `x` avatar works as expected.

<img width="447" alt="image" src="https://user-images.githubusercontent.com/20600565/39708947-25c82398-51de-11e8-80ac-5cc0b4c7affb.png">

But hovering over the `y` avatar does not.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/20600565/39708984-3b1afebe-51de-11e8-9ef5-61c842f3a779.png">

This doesn't seem to be the intended behavior. I looked through the features listed, and didn't see anything about this. If there's a way to disable this, it should be more clearly documented, otherwise this seems to be a bug.

Using Firefox Quantum 59.0.2 (64-bit)

**Comment by alichtman** [comment]
I was pretty confident that this was a feature of GitHub, but I just tested it on Chrome without Refined GitHub and got the same result.

My bad, this isn't a bug in the extension.

@sindresorhus, opinions on adding this feature to Refined GitHub?

**Comment by sindresorhus** [comment]
I think it would be better to report it to GitHub. Seems like they just missed adding it. I don't think it's worth the effort for us to add it.

**Comment by alichtman** [comment]
Reported. Closing this.

**Comment by bfred-it** [comment]
But... what else do you want to see? `chrisalbon`'s preview is _right there_

**Comment by alichtman** [comment]
> `chrisalbon`'s preview is right there

@bfred-it, it is not. Text that says `chrisalbon` is present, but a preview of his profile (as seen when I hover over `shobrook`) is not.

However, this is not a RGH issue -- it's been confirmed by GitHub Support to be a GitHub issue, and they're working on fixing it.
