### ISSUE TITLE
Create settings for features optional

### ISSUE THREAD

**Issue by leocaseiro** [sindresorhus/refined-github#131]
Hi, I really like this plugin. However, I'd like to keep some features, such as `tooltip` or keep `users starring/forking your repos from the newsfeed`. In my case I don't have as many and I appreciate it when happend :smile: 

Despite it would need a big refactor, every user could set as they would like to.

Something like:

- [x] Linkifies branch references in pull requests
- [x] Linkifies issue/PR references in issue/PR titles
- [x] Adds a 'Releases' tab to repos (g r hotkey)
- [x] Adds a quick edit button to the readme
- [x] Shows current filename in the sticky pull request header
- [x] Adds blame links for parent commits in blame view
- [x] Improves readability of tab indented code
- [x] Adds a shortcut to quickly delete a forked repo
- [x] Adds ability to minimize/maximize files in a pull request diff
- [x] Adds links to patch and diff for each commit
- [x] Differentiates merge commits from regular commits
- [x] Hides :+1: :-1: comments and shows their count in the sidebar
- [x] Supports indenting with the tab key in textareas like the comment box
- [x] Automagically expands the news feed when you scroll down
- [ ] Hides other users starring/forking your repos from the newsfeed
- [x] Prompts you when pressing Cancel on an inline comment in case it was a mistake
- [x] Moves the dashboard organization switcher to the right column
- [x] Removes annoying hover effect in the repo file browser
- [x] Removes the comment box toolbar
- [ ] Removes tooltips

**Comment by paulmolluzzo** [comment]
Asked and answered:

https://github.com/sindresorhus/refined-github/issues/57

https://github.com/sindresorhus/refined-github/issues/10

**Comment by hkdobrev** [comment]
Just going to mention these previous issues.

While I realise as this extension is getting more and more popular there would be more desire to opt-out of the more opinionated changes. Probably we could make it possible to opt-out of the different CSS changes in the future, but not right now. If ever go that way we could do it like Modernizr, based on options to put some classes in the body and then activate CSS changes only when the class for that change is present.

**Comment by sindresorhus** [comment]
I've seen the request for wanting to keep the stars many times. We might add a limited amount of options in the future, but right now we want to focus on getting everything right Using https://devspace.io/ might be a better way to keep up on when your projects gets starred btw.

I'm curious though why you want the tooltips back? Any specific ones?

**Comment by hkdobrev** [comment]
I also like https://gitnotifier.io/ which keeps tabs on follows/unfollows and stars of your projects. It can also send you weekly digests.

**Comment by sindresorhus** [comment]
@hkdobrev Maybe we should create an FAQ section where we recommend gitnotifier and devspaces for people wanting to see vanity stuff?

**Comment by leocaseiro** [comment]
Just saw #70 answer...never mind.

**Comment by sindresorhus** [comment]
> The tooltip as for participants name specially

That can indeed be useful. We can add that back.
