### ISSUE TITLE
Cancel confirmation in "Files changed" tab not working

### ISSUE THREAD

**Issue by levrik** [sindresorhus/refined-github#1310]
Follow up from #1252 

![2018-05-09_20-40-32](https://user-images.githubusercontent.com/9491603/39833147-8a4e7f78-53c9-11e8-9222-875aa4a10f00.gif)

Browser: Chrome
Disabled features: `reactions-avatars`, `monospace-textareas`

Also doesn't work with all features enabled.

_Edit:_
After trying a bit more I figured that under some conditions it works, under some not. Not sure under which exactly though. I will keep investigating and post my results here.

**Comment by bfred-it** [comment]
Any errors in the console?

**Comment by levrik** [comment]
@bfred-it Nope, none.

**Comment by bfred-it** [comment]
Implemented by GitHub #1521
