### ISSUE TITLE
Save gists with cmd-enter (feature request)

### ISSUE THREAD

**Issue by benjaminoakes** [sindresorhus/refined-github#1313]
I'd love to be able to save a gist when I cmd-enter (or ctrl-enter when not on a Mac).  This would be more consistent with the rest of GitHub.

**Comment by sindresorhus** [comment]
Cmd+Enter is mostly used to post comments / edits/ etc. Saving a Gist is different and should not be so easily triggered, IMHO. You don't use Cmd+Enter for saving files on GitHub either. I'm gonna pass on this as clicking the "Create" button there is not something you do so often that it needs a shortcut.

You could still submit this feature request to GitHub: support@github.com
