### ISSUE TITLE
"more" button on index doesn't work in Chrome Canary (68)

### ISSUE THREAD

**Issue by aleccool213** [sindresorhus/refined-github#1315]
<img width="358" alt="screenshot at may 11 09-52-54" src="https://user-images.githubusercontent.com/6475934/39927699-18ea909a-5501-11e8-82b3-24cf4ca6425c.png">

When it is pressed, nothing happens.

**Comment by yakov116** [comment]
@aleccool213 is there a console error?

**Comment by aleccool213** [comment]
@yakov116 nope.

**Comment by bfred-it** [comment]
That's not our button, plus it's canary
