### ISSUE TITLE
Hide test files in file view in Pull Requests

### ISSUE THREAD

**Issue by danielhusar** [sindresorhus/refined-github#1316]
Hi, first of all I totally love this extension, it makes my daily job so much easier.

I have one suggestion:

What would you think about adding a toggle in files view to hide test files?
Something like hide all files in `__tests__`, `tests`, `spec` directories?

I can take a look on implementing it, but would you be open to such a PR ?

**Comment by yakov116** [comment]
I think this is what your looking for
[Hide Files on GitHub](https://github.com/sindresorhus/hide-files-on-github) - Hides dotfiles from the file browser

**Comment by danielhusar** [comment]
Hmm its slightly different, it hides them in code browser too, I was thinking only in PRs. (sorry forgot to mention that)

My use-case is that sometimes you want to take one last look, what kind of changes will make it to production, and if you PR contain lot of tests, fixtures, etc changes, it can be quite noisy, and you can easily miss stuff.

**Comment by bfred-it** [comment]
Out of scope: https://github.com/sindresorhus/refined-github/pull/1085
