### ISSUE TITLE
Labels select pop up is not scrollable

### ISSUE THREAD

**Issue by pawelad** [sindresorhus/refined-github#1317]
See the video:

![kapture 2018-05-11 at 15 33 53](https://user-images.githubusercontent.com/7062874/39943413-c191e67e-5530-11e8-884a-0f8802aa6643.gif)

**Comment by yakov116** [comment]
Looks like the sticky broke this. #1311

**Comment by tommoor** [comment]
Agree, it does look like the position sticky was the cause although I'm at a loss as to why that would affect the scrolling in that popover…

**Comment by yakov116** [comment]
@tommoor Z-index on them is 20 yours is 10...
