### ISSUE TITLE
Links to issue/PR in titles from #61 not always present

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#132]
The change introduced in #61 is not always working for me, but I can reproduce only sporadically. At first I thought I was going crazy, but it's been 3 days now and I see it a few times a day. I thought it was from back-and-forward navigation, but it's not, I thought it was when loading a page in the background, but it's not. It's something else which prevents it from modifying the title in some cases.

Have you experienced this?

**Comment by DrewML** [comment]
I haven't experienced that (yet), but I'll keep an eye out for it now that I know to look.

**Comment by hkdobrev** [comment]
test comment

**Comment by hkdobrev** [comment]
Got it! It happens after you post a new comment or edit existing one!

**Comment by hkdobrev** [comment]
I'm not sure this is worth the effort though. What do you guys think?

**Comment by DrewML** [comment]
It seems like pretty low-hanging fruit. Maybe we just leave it open for now with a `Help Wanted` label and let new contributors pick it up if they're looking for something to work on?

**Comment by hkdobrev** [comment]
Perhaps this could be solved with these fancy mutation observers stuff.
