### ISSUE TITLE
Enable Auto Merging PRs when status checks are required.

### ISSUE THREAD

**Issue by pgrm** [sindresorhus/refined-github#1325]
This is a follow up to #865 and #975

If a branch is protected and has the flag *Require status checks to pass before merging* enabled, then I don't see how I could use the existing feature.

![image](https://user-images.githubusercontent.com/713456/40038439-67639582-5812-11e8-9938-09ce33a27ef0.png)

Because until those checks aren't successful, I just see a grayed out button and can't press anything:

![image](https://user-images.githubusercontent.com/713456/40038374-18d62e16-5812-11e8-82b4-51e0f649400e.png)

It would be awesome, if there would be another button (created by this extension) next to it, to merge as soon as all checks have passed.

**Comment by bfred-it** [comment]
If the form is just hidden but in the dom, then it’s feasible. It can be un-hidden and the checkbox would have to be `readonly`

**Comment by Sir4ur0n** [comment]
I just came across this exact problem too :(
I took a look at the DOM and the ID `merge_message_field` doesn't exist when `Require status checks to pass before merging` is checked. This is the ID of the text area with the squash message.
So it looks like it would be slightly harder than just unhiding it :(

**Comment by tony-scio** [comment]
This feature would be ✨

**Comment by android2221** [comment]
I'm adding some gasoline by noting that Azure DevOps currently provides this functionality

**Comment by fregante** [comment]
To add this feature, we'd have to recreate the whole form, including the logic between merging types. Additionally, we can't know which merging types are available (e.g. a repo only allows Squashing). Sounds impossible 🙁

I think you should ask GitHub to implement our `wait-for-build` feature (regardless of this requirement)

>  ### Adds the option to wait for checks when merging a PR 
> 
> ![](https://user-images.githubusercontent.com/1402241/35192861-3f4a1bf6-fecc-11e7-8b9f-35ee019c6cdf.gif)

**Comment by gunar-gessner-qatalog** [comment]
fwiw this works for me as a browser snippet

```js
function autoMerge() {
    const btn = window.$$('button').filter(el=>el.innerText === 'Merge pull request')[0]
    if (btn) {
        btn.click()
        const btn2 = window.$$('button').filter(btn=>btn.innerText === 'Confirm merge')[0];
        if (btn2) {
            btn2.click()
            return
        }
    }
    setTimeout(autoMerge, 1000)
}
window.$$ = $$;
autoMerge();
```

**Comment by fregante** [comment]
That only works if you're fine with the default commit title and message. It's a good workaround but probably most people would expect to be able to preview/edit them.

**Comment by graingert** [comment]
@fregante can you add a little message next to the merge button that explains why the feature isn't working? I thought there was an issue with GHR originally

**Comment by graingert** [comment]
this is now a build-in feature: 

https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/
> Auto-merge pull requests (https://github.com/github/roadmap/issues/107): when using protected branches. Rolling out over the next couple of weeks, enabled in your repo settings.

**Comment by fregante** [comment]
Thanks for the update!

That’s completely different from “Auto-merging” as intended by this extension (i.e. the user still has to click Merge whereas GitHub’s new feature will be completely automatic) but it’s probably what most people are after 🎉

**Comment by graingert** [comment]
> That’s completely different from “Auto-merging” as intended by this extension (i.e. the user still has to click Merge whereas GitHub’s new feature will be completely automatic) 

this isn't true. You still have to tick the "merge when pipeline passes" checkbox

**Comment by fregante** [comment]
Indeed, I think that changed since it came out of beta.

Too bad GitHub decided to make this a per-repo option rather than just allowing it on every repo like Refined GitHub does.

**Comment by graingert** [comment]
@fregante perhaps GitHub refined should automatically enable this feature on all repositories the user has access to on first install?

**Comment by fregante** [comment]
That's not something the extension should do. A cli tool would be better suited to do batch changes across multiple repos.
