### ISSUE TITLE
Upload attachments shouldn't trigger on secondary button click

### ISSUE THREAD

**Issue by sivaraam** [sindresorhus/refined-github#1327]
When I click the secondary button on the 'upload attachments' icon, shown while writing a comment, the file upload dialog is shown. This shouldn't happen as generally a secondary button shouldn't trigger the primary action (uploading files). At least that's what I expect :relaxed:.

FWIW, I observed this issues in Firefox Nightly 62.0a1 running on Debian GNU/Linux.

**Comment by bfred-it** [comment]
1. What's the "secondary button"?
2. What does that normally do?
3. What should happen when clicking the secondary button on the upload icon?

**Comment by sivaraam** [comment]
Sorry for the delayed response. I was out-of-town for the past week.

> 1. What's the "secondary button"?

I should have been more explicit. It's the secondary button of the **mouse** (the right mouse button, for me)

> 2. What does that normally do?

It usually brings up the context menu for the webpage being viewed. It's generally taken care by the browser and looks something like this (Sorry about the orientation, I'm not sure why it changed):
![20180522_163803](https://user-images.githubusercontent.com/12448084/40359020-e1f9e68a-5dde-11e8-8523-15117b0979e9.jpg)

> 3. What should happen when clicking the secondary button on the upload icon?

I would expect nothing to happen. But any secondary action would be meaningful. I filed this as the secondary button shouldn't trigger a primary action such as uploading files.

**Comment by bfred-it** [comment]
Thanks! I don't see this as a particularly problematic behavior (solution: "don't right click that button") but if you manage to find the solution and send a PR I can take a look at it :)
