### ISSUE TITLE
Add "favorites" feature

### ISSUE THREAD

**Issue by bruno02221** [sindresorhus/refined-github#1329]
I think that it would be really nice if we could make some repositories "favorited". The stars feature is not enough for this kind of scenario, neither are the pinned ones, which are a kind of our own highlighted repositories. But sometimes we want to mark some repositories as "special", so we can back later and read more about them, among other things.

I know this is a kind of feature where we can't customize github behavior, but instead, we have to support our own storage to maintain the data. Maybe we can use local storage or Google Drive or Dropbox APIs.

I was thinking about to create an extension for this feature on my own, but I think this project would be the better place for it.

I don't know if this is a reasonable feature for you guys, but if you approve that, I can try to implement that as a PR, maybe.

**Comment by bfred-it** [comment]
I don't think this would belong to Refined GitHub, plus it can be replicated easily already:

Browser bookmarks.
