### ISSUE TITLE
Stick the comment menu to right

### ISSUE THREAD

**Issue by LM450N** [sindresorhus/refined-github#133]
I'm using the extension [canned-responses](https://github.com/notwaldorf/github-canned-responses) and the new reply-saved feature. The menu options are not very well positioned. Maybe it's possible to push them on the right.

#### Now
With `.toolbar-group {margin-left: 20px;}`
<img width="1226" alt="capture d ecran 2016-03-31 a 15 51 30" src="https://cloud.githubusercontent.com/assets/2325091/14178091/6d1068e6-f759-11e5-87f1-9a06d0dad462.png">

#### Proposal
Without the margin-left.
<img width="1237" alt="capture d ecran 2016-03-31 a 15 51 46" src="https://cloud.githubusercontent.com/assets/2325091/14178109/7b47a262-f759-11e5-9642-0d25ac721bee.png">

_I have only tried on Chrome Version 49.0.2623.110 (64-bit) on OSX EC 10.11.4._

**Comment by sindresorhus** [comment]
Why would you need both?

**Comment by LM450N** [comment]
Why would I not be allowed ? :stuck_out_tongue: 

I just like the default messages of the `canned-responses` and I can't disable the GitHub feature (I can?). If I should choose I would keep the `canned-responses` extension and I would like to see it at the right not in the middle. :neutral_face:

**Comment by paulmolluzzo** [comment]
IMO this is an issue with the other extension, not this one. A similar issue was had here: https://github.com/DrewML/GifHub/pull/8

**Comment by sindresorhus** [comment]
@LM450N I was just curious why you would need both.

**Comment by sindresorhus** [comment]
> Without the margin-left.

Which extension adds this margin?

**Comment by paulmolluzzo** [comment]
>> Without the margin-left.

> Which extension adds this margin?

I don't have the other extension and see a `margin-left:20px` from GitHub. We don't have the number `20` anywhere in this repos CSS.

**Comment by LM450N** [comment]
This comes from [Primer](http://primercss.io/) (GitHub assets).

**Comment by paulmolluzzo** [comment]
> It comes from Primer (GitHub assets).

Then that's an issue for that extension. Refined GitHub has nothing to do with it.

**Comment by LM450N** [comment]
Which extension ? I'm lost. :confused: [Primer](http://primercss.io/) is a CSS toolkit created and used by GitHub itself. I think it's the default CSS.

**Comment by paulmolluzzo** [comment]
The button from the canned responses extension is broken because it relies on the CSS provided by Github. The CSS from this extension (Refined GitHub) is not the issue. Does that make it more clear?

**Comment by LM450N** [comment]
Yes, thank you. As you can see my English is pretty poor...

**Comment by LM450N** [comment]
There is still something I can't understand. Refined GitHub "redesigns" the whole GitHub interface when the `canned-responses` just adds a feature. I'm still thinking the standalone extension is built to work on the default interface. Moreover, if Refined GitHub removes the margin, all others extensions will be well placed.

I never said the Refined GitHub extension CSS was the cause. I only said it could fix the issue for all extensions.

I'm not sure to be clear. Feel free to re-open the issue if you want. :smiley:

**Comment by paulmolluzzo** [comment]
You're free to make a pull request :)
