### ISSUE TITLE
Starred repo names not displayed in activity feed on Firefox

### ISSUE THREAD

**Issue by alichtman** [sindresorhus/refined-github#1331]
Appearance with RGH enabled on Firefox 60.0.1 (64-bit):

<img width="673" alt="image" src="https://user-images.githubusercontent.com/20600565/40207452-2ae985d2-59fa-11e8-87c7-2e5dc206e2d4.png">

Appearance without RGH enabled: 

<img width="676" alt="image" src="https://user-images.githubusercontent.com/20600565/40207477-4ba1960c-59fa-11e8-9fed-d72639102d84.png">

**Comment by yakov116** [comment]
@alichtman does it happen even with #1330? Git hub just made a few changes

**Comment by alichtman** [comment]
I'd bet this is probably due to the Github UI refresh.

I haven't tried #1330, and won't have time to mess with it for a while. I just disabled the extension until the UI changes are figured out.

**Comment by bfred-it** [comment]
Yeah this is fixed by #1330
