### ISSUE TITLE
Commit entries are not listed in dashboard

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#1336]
Using Refined GitHub 18.5.18.1605 in both Chrome 66 and Firefox 60.

I've noticed that commit entries are not listed in the dashboard(https://github.com/ , while login) when the extension is enabled. 
_I haven't disabled any feature in the extension, nor do I use any custom CSS. It occurs in both Chrome and Firefox._ 

Example:

## with the extension disabled

![2018-05-18_224520](https://user-images.githubusercontent.com/723651/40254743-4442c216-5aed-11e8-853b-f5b5ee1d784c.jpg)

---

## with the extension enabled

![2018-05-18_224457](https://user-images.githubusercontent.com/723651/40255438-d2bd5b08-5aef-11e8-8a57-94727e226188.jpg)

Thank you

**Comment by yakov116** [comment]
@darkred you can disable it. Hide-usless-feed

**Comment by darkred** [comment]
@yakov116 
I made some additions in readme.md (PR #1337) regarding this.
I hope you find them useful.
