### ISSUE TITLE
Maybe group up stars that are repeated?

### ISSUE THREAD

**Issue by joshmanders** [sindresorhus/refined-github#134]
I'm noticing when a repo is heavily starred by people I follow, I get a lot of entries for it. Maybe a feature to grab all popular starred repos on the dashboard and group them together? Would be good to see quickly what people are finding and less clutter on the screen.

**Comment by sindresorhus** [comment]
Sounds good. PR welcome :)

**Comment by bfred-it** [comment]
I made a single-use extension https://github.com/bfred-it/GitHub-grouped-news

It doesn't replace the feed, it just adds a box above

**Comment by joshmanders** [comment]
Awesome @bfred-it, could you PR it into refined-github? I like it, but I'm trying to keep the number of extensions running to a minimum, and sindre said he'll accept this as a PR.

**Comment by bfred-it** [comment]
Nah, I prefer more [focused extensions to monoliths,](https://github.com/sindresorhus/ama/issues/10#issuecomment-117766328) especially because refine-github is not nearly as configurable as I'd like. And extension count is not really an issue.
