### ISSUE TITLE
"Copy" functionality broken?

### ISSUE THREAD

**Issue by LasaleFamine** [sindresorhus/refined-github#1340]
I have `refined-github` v18.5.19.1605 installed and the "Copy" command seems broken. A gif showing what happen:

![copy-broken](https://user-images.githubusercontent.com/13070349/40321258-c3e7e940-5d2e-11e8-8315-6079f7e42761.gif)

**Comment by e-volusian** [comment]
I am also having problems with the copy functionality. As an example, if I copy a file from the "Raw" display, I get this (truncated) text:

```bash
#!/bin/bash

# Bootstrap a host

```

Whereas when I use the "Copy" button, I get this (also truncated) text:

```bash

      
        
        #!/bin/bash
      
      
        
        

      
      
        
        # Bootstrap a host

```

So it seems to be adding additional spaces and lines.
