### ISSUE TITLE
Add PR review filter "Not reviewed by you"

### ISSUE THREAD

**Issue by DerTieran** [sindresorhus/refined-github#1345]
I often have the issue that some PRs are still pending review by other contributors,
but I want to just see the PRs I haven't reviewed yet.

There is a **"Reviewed by you"** option, but I want the negation of this
![image](https://user-images.githubusercontent.com/9264728/40417878-1caea106-5e81-11e8-91d6-38dc3eaef09f.png)

This can be achieved by prefixing the `reviewed-by:USERNAME` parameter with a `-`,
so e.g. `-reviewed-by:DerTieran`.

I'm happy to implement this functionality if it is wanted.
My idea would be to add the **"Not reviewed by you"** filter item to the above drop down menu.

**Comment by DerTieran** [comment]
Okay I just hacked something together that works (you can find it [here](https://github.com/sindresorhus/refined-github/compare/master...DerTieran:add-filter-not-reviewed-by-you))

There are still some issues, mainly that Github thinks `-reviewed-by` is the same as `reviewed-by` and checks the **"Reviewed by you"** option.

If someone here finds the time, I would be happy if someone could look over the code and tell me if I'm on the right track.
(Comments/Commits will be cleaned up before I open the PR :smile:)

Thanks for that in advance.

**Comment by busches** [comment]
Looks pretty good, I'd open a PR and get official feedback and testing.

**Comment by lukehefson** [comment]
Heads-up that we added this natively to GitHub! https://github.blog/changelog/2019-03-18-view-pull-requests-not-reviewed-by-you/

❤️ 💛 💜 💚

**Comment by bfred-it** [comment]
We pre-emptively removed it in #1831 😅 (the feature worked for all dropdowns)
