### ISSUE TITLE
.patch and .diff links duplicate in commit interface

### ISSUE THREAD

**Issue by martenson** [sindresorhus/refined-github#135]
when looking at a merge commit at https://github.com/galaxyproject/galaxy/commit/cdd44e610ec0180141f7086e75d42a0e42bbc62a I see
![screenshot 2016-03-31 13 50 40](https://cloud.githubusercontent.com/assets/1814954/14185409/ad05c62e-f747-11e5-8a92-0bbfa6891df4.png)
clicking on a link to one of the parents returning with the 'back' button on the browser it results in 
![screenshot 2016-03-31 13 52 36](https://cloud.githubusercontent.com/assets/1814954/14185449/da6ebd50-f747-11e5-8c4e-7c1257eacc83.png)

By repeating the process the links will duplicate further.

OSX 10.11.4 Chrome 49 Refined GH 0.13.0

**Comment by DrewML** [comment]
So pretty! :P
![image](https://cloud.githubusercontent.com/assets/5233399/14186850/fad2c566-f745-11e5-9539-da8b68bc76d4.png)

Thanks for the heads-up, @martenson!

**Comment by martenson** [comment]
@DrewML Don't do it! You will break the Internets!

**Comment by paulmolluzzo** [comment]
I can do this pretty easily I think.

**Comment by paulmolluzzo** [comment]
8 minutes!

![movie-car-action-ulZwxYQVqUWhW](https://camo.githubusercontent.com/48da8a4d5d20455acc0d389bb4e6e291dc8cec0a/68747470733a2f2f6d65646961322e67697068792e636f6d2f6d656469612f756c5a777859515671555768572f67697068792e676966)

**Comment by DrewML** [comment]
![reaction-dancing-applause-SWVEgnQvBZ7Ve](https://camo.githubusercontent.com/d92b700d6e2921b880cc014314368454984f36d2/68747470733a2f2f6d65646961312e67697068792e636f6d2f6d656469612f53575645676e5176425a3756652f67697068792e676966)
