### ISSUE TITLE
Since RG 18.5.25.1609 the options are no longer stored (and previously stored options are lost after update)

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#1350]
Since RG 18.5.25.1609 the Options are no longer stored (and previously stored are lost)

STR

- Install RG 18.5.25.1608 in fresh profile of Chrome 66/Firefox 60.
- Go to RG Options, 
add in "Features to disable" e.g. `hide-useless-newsfeed-events` 
and/or enable the 'Show the features enabled on each page in the console' checkbox.
- close and re-open Options: notice that your options are stored.
- Now update to either 18.5.25.1609 or 18.5.25.1610: notice that your previous options are lost and if you modify them and close+reopen Options, they are not stored.
- Note: when I access RG Options in 1609/1610: 
  - there's no relevant entry in Chrome extension's 'Background page'|Console. 
  - In Firefox Browser Console there are these errors _(the former -probably irrelevant- occurs as I mouseover on the RG toolbar button)_:
```
Security Error: Content at moz-extension://9644575b-2193-449d-a7f4-2c78cf89d053/options.html may not load or link to chrome://mozapps/skin/extensions/extensions.css.

TypeError: storm_textarea.init is not a function        options.js:74:5
```

**Comment by bfred-it** [comment]
Thanks for this report! Previous options were safe but they just weren't shown nor updated. I'll push a hotfix soon
