### ISSUE TITLE
PR popup appears even where there's already a PR for that branch

### ISSUE THREAD

**Issue by SUPERCILEX** [sindresorhus/refined-github#1351]
This popup:
![image](https://user-images.githubusercontent.com/9490724/40579680-15ac5b2e-60e2-11e8-9a08-251c1eb971fa.png)

If I click on it, I'm brought to the compare page where GitHub shows me that there's already a PR:
![image](https://user-images.githubusercontent.com/9490724/40579685-28d3a20c-60e2-11e8-8b67-9bbee9f0294f.png)

**Comment by bfred-it** [comment]
That's actually a GitHub feature, we just move it around. GitHub bug

**Comment by sindresorhus** [comment]
You can report it to GitHub here: https://github.com/contact
