### ISSUE TITLE
Enable spellcheck 

### ISSUE THREAD

**Issue by ShalokShalom** [sindresorhus/refined-github#1352]
[See](https://github.com/languagetool-org/languagetool-browser-addon/issues/219#issuecomment-381334482)

**Comment by bfred-it** [comment]
Out of Refined GitHub scope. If you want spellcheck use a global extension or switch to a OS that has <img src="https://user-images.githubusercontent.com/1402241/40583483-f70af03c-618f-11e8-9627-5808bd6832c4.gif" alt="spellcheck" height="21"> 😅

**Comment by sindresorhus** [comment]
@bfred-it I think he just wants us to change the attribute `spellcheck="false"` to `spellcheck`.

**Comment by bfred-it** [comment]
Where exactly though? My spellcheck works in comments and commit messages. Needs to be more specific than "look here"
