### ISSUE TITLE
Feature Request: In the activity feed make PR numbers link to the PR

### ISSUE THREAD

**Issue by dhirschfeld** [sindresorhus/refined-github#1354]
For example, in the picture below I'd like `#333` to link to PR-333 in that repo so that I can quickly check the PR to see what changes were merged in:

![image](https://user-images.githubusercontent.com/881019/40582350-cdefd3d0-61b6-11e8-981e-0f94ad61e4b8.png)

**Comment by marcobeltempo** [comment]
@bfred-it I would like to work on this issue

**Comment by yakov116** [comment]
@dhirschfeld go for it!

**Comment by sindresorhus** [comment]
Implemented by GitHub natively: https://github.com/sindresorhus/refined-github/pull/1408#issuecomment-418705266
