### ISSUE TITLE
Feature Request: In the repository page, modify copy to clipboard value to include `git clone` phrase 

### ISSUE THREAD

**Issue by Shriram-Balaji** [sindresorhus/refined-github#1355]
For example: 

I'd like to prepend `git clone` command to the clone url field because it is most likely the action we'd end up doing, right after we copy the url. 

<img width="1440" alt="clippy-git-clone-feature-request" src="https://user-images.githubusercontent.com/11358903/40599904-f316e048-626c-11e8-8970-72bed8f12fbb.png">

**Comment by bfred-it** [comment]
I've used it more often without `git clone` than with it. I usually pasted it to `git remote set-url origin`

**Comment by vanniktech** [comment]
Same here. I just want the URL.

**Comment by Shriram-Balaji** [comment]
Great! Looks like it's just me then 🙆‍♂️
