### ISSUE TITLE
Shift-Enter when posting a PR comment submits instead of adding newline

### ISSUE THREAD

**Issue by supremebeing7** [sindresorhus/refined-github#1356]
I believe this is a regression in v18.5.27.1609, because I don't remember encountering this issue until the last couple days.

### Expected
Given I am reviewing a Pull Request
When I click a line to add a code comment
And I type Shift-Enter
Then it should create a newline
And it should not submit the comment

### Actual
Given I am reviewing a Pull Request
When I click a line to add a code comment
And I type Shift-Enter
Then it submits the comment
And when I click Edit to edit the comment
And I type Shift-Enter
Then it creates a newline correctly

### Version
18.5.27.1609

### Browser
Chrome 66.0.3359.181

---
I haven't had time to look at the source for what might have changed to cause this, but may be able to in a few days unless someone has an immediate idea of what went awry. As of now, this is forcing me to disable the plugin because I use that feature frequently and this is an annoyance.

**Comment by supremebeing7** [comment]
Oh, that looks like it's a _feature_ - it's in the [More Shortcuts](https://github.com/sindresorhus/refined-github#more-shortcuts) section of the README. Is there a way to easily turn that off without having to manually edit the [source code](https://github.com/sindresorhus/refined-github/blame/f3e2f1d52dbeeb4090504f505714d2a7571ece23/source/features/add-keyboard-shortcuts-to-comment-fields.js#L23)?

**Comment by akwilliamson** [comment]
That's correct @supremebeing7 it's a feature. I'm unsure about whether there's a way to turn it off. Others will have to chime in.

**Comment by supremebeing7** [comment]
Looks like you can disable by filename. I added `add-keyboard-shortcuts-to-comment-fields` to the UI 
![](https://i.imgur.com/NrN0eyC.png)

That disables all of the other keyboard shortcuts on comment fields but I can live with that.

So, I guess we can close this. 

Side note: It might be nice to have a better UI around disabling features.
