### ISSUE TITLE
link for uploading files on issues is missing

### ISSUE THREAD

**Issue by martenson** [sindresorhus/refined-github#136]
I am not sure if it is removed on purpose but the link allowing file selection from local file system is missing with the extension and I do not know about a workaround.

![screenshot 2016-03-31 13 55 47](https://cloud.githubusercontent.com/assets/1814954/14185615/abedf3a0-f748-11e5-8f9b-0a28d82decc2.png)
![screenshot 2016-03-31 13 56 04](https://cloud.githubusercontent.com/assets/1814954/14185622/aed9e1a0-f748-11e5-9472-bfe806990492.png)

OSX 10.11.4 Chrome 49 Refined GH 0.13.0

**Comment by sindresorhus** [comment]
You just drag-n-drop or paste an image in the textarea.

**Comment by paulmolluzzo** [comment]
On purpose: https://github.com/sindresorhus/refined-github/blob/aa5df2b240feaba7ad9b1dc7b03de40a39685435/extension/content.css#L98-105

**Comment by martenson** [comment]
very well then, I miss the link though, Drag&Drop is clumsy :/
thanks you for answers @sindresorhus @paulmolluzzo

**Comment by DrewML** [comment]
@martenson If you're missing that functionality, you can install an extension that allows you to inject Custom CSS on arbitrary pages ([Stylebot](https://chrome.google.com/webstore/detail/stylebot/oiaejidbmkiecgbjeifoejpgmdaleoha?hl=en) is one of them) and just add our rule, but with a higher specificity for the selector.

```css
body .write-content .drag-and-drop {
    display: block !important;
}
```

**Comment by sindresorhus** [comment]
@DrewML Could you add a FAQ section about this to the readme? Would be useful for people disagreeing with some changes. They can easily override it themselves.

**Comment by martenson** [comment]
@DrewML thanks for the tip, but those extensions usually have very extensive permission requirements (read and change all sites) - may be a solution for others

**Comment by paulmolluzzo** [comment]
I don't use it, but it might be worth putting the link to use a "normal" file upload. We can keep it minimal and just put the word "upload" or something. Some people prefer to use that interface for finding files to upload.

**Comment by DrewML** [comment]
@sindresorhus No problem - left myself a note to do it tonight.

**Comment by hkdobrev** [comment]
@martenson I'm a bit confused with your statement drag-n-drop is clumsy. Could you tell me which OS are you using, what kind of peripherals etc.?

**Comment by martenson** [comment]
@hkdobrev I use OSX and Apple magic trackpad - so dragging things around is painful (especially on multiple large displays) - however my routine is set up so I do not drag a thing, everything is keyboard-controlled.

**Comment by hkdobrev** [comment]
@martenson Hmm, I've used that particular setup for about 2 years and I loved it because of how easy I was dragging things compared to a mouse. Now I use the trackpad of a Macbook Air and I still drag things around constantly. I so rarely touch a mouse, dragging is a problem for me without a trackpad made by Apple (a few Asus trackpads work as well).

**Comment by martenson** [comment]
@hkdobrev might be a matter of personal preference, I just don't drag - it feels slow to me - so I am clumsy with it because I lack the experience :)

**Comment by ianks** [comment]
I think the ability to upload without drag-ndrop/paste would be nice (for those of dont use full desktop environments)
