### ISSUE TITLE
Make branch name copyable on PR page

### ISSUE THREAD

**Issue by Empty2k12** [sindresorhus/refined-github#1364]
I am using https://github.com/bitcrowd/tickety-tick to generate branch names from Jira tickets, which can get pretty long.

Sometimes, when working on multiple PRs at the same time, I like to check the PR page first as part of my workflow, then switch to the branch locally. However, copying the branch name is a pain, as it is also a link to the branch overview page.

<img width="844" alt="screen shot 2018-06-05 at 16 40 26" src="https://user-images.githubusercontent.com/6954968/40983296-94aeb016-68df-11e8-93b0-4ad0434dbfef.png">

Adding a "Copy Branch Name" near the branch name on the Github PR page would be very helpful.

**Comment by hkdobrev** [comment]
Hi @Empty2k12! Thank you for opening an issue!

That was discussed in #77 and #78. Please see the discussion there first.

To summarise the discussions:
- Use good, short branch names
- Use `hub`
- Use Tab-completion
- Create a separate browser extension

I'll close this is a duplicate, but feel free to continue the discussion in #77 and contribute new ideas to the conversation to see what the users and maintainers think. 🍻
