### ISSUE TITLE
Show PR Link in Commits Page

### ISSUE THREAD

**Issue by eygraber** [sindresorhus/refined-github#1365]
Is it possible to show a link to the PR that a commit was added in?

I'm using rebase merging which doesn't create a merge commit, so there's no way to see what PR the commit came from on /commits. If you open the commit, it shows the PR, but it doesn't show it in the list of commits.

**Comment by bfred-it** [comment]
Unfortunately this would require a PR call for every commit on the screen, and that happens to be _up to 20_, so it's not very feasible
