### ISSUE TITLE
Filter for files in pull requests

### ISSUE THREAD

**Issue by M-Zuber** [sindresorhus/refined-github#1367]
It would be very helpful to be able to filter the files in a pull request based on extension and/or name.
For example, we have a repo using graphql, but I know the only files I care about in the pull request are the other files (and in some cases vice versa)

**Comment by bfred-it** [comment]
Refer to https://github.com/sindresorhus/refined-github/pull/1085#issuecomment-368478152

**Comment by M-Zuber** [comment]
My apologies, I missed that issue.
Too bad, all the existing solutions I tried so far are broken 😥

Time to really learn how to make Chrome extensions!

**Comment by bfred-it** [comment]
No worries, it was hard to find.

> Time to really learn how to make Chrome extensions!

Looking forward to seeing this extension! It's been asked a few times
