### ISSUE TITLE
Activity feed latency

### ISSUE THREAD

**Issue by 1138-4EB** [sindresorhus/refined-github#1371]
If I enable this extension on Firefox, the activies of the last 2-3 days disappear:

![refined_activity](https://user-images.githubusercontent.com/6628437/41187797-84e3af12-6bb2-11e8-9a39-9a31f66d80c6.png)

**Comment by notlmn** [comment]
This is part of the feature that hides useless news feed itels like pushes.

You can disable this behavior if you'd like using `hide-useless-newsfeed-events` option in disable features.

(Disabling features is discouraged as of now and don't work as expected in all cases)

**Comment by 1138-4EB** [comment]
Thanks! Good to know that it is a feature and not a bug. I don't really mind if those events are hidden, because I am using https://typicode.github.io/ghwn anyway. I was just curious about it. I'm closing this.

(Is there any issue I can suscribe to, in order to be aware of when feature disabling is properly supported?)

**Comment by notlmn** [comment]
As this is a highly opiniated project, disabling features was highly opposed by @sindresorhus initially as they require additional maintenance and handling edge cases.

Support for disabled features is not planned and likely will not be. But opening PRs to start a discussion is a good start.
