### ISSUE TITLE
Notifications re-sorted in unclear order, unable to disable it

### ISSUE THREAD

**Issue by kujenga** [sindresorhus/refined-github#1372]
Recently, the github-refined extension appears to have started re-ordering my notifications at: https://github.com/notifications

As far as I can tell, it is taking the default ordering of the repositories on that page, which is by most recent notification, and re-ordering them so that the repositories are in alphabetical order. When I disable the extension, the repositories remain in the expected order.

I would like to disable this functionality but cannot seem to find a way to, I've read through the list of features a few times and cannot seem to find a matching one, what might I be missing?

**Comment by bfred-it** [comment]
> re-ordering them so that the repositories are in alphabetical order

That's not the case. The ordering happens as part of `mark-unread` to bring all unread repos to the top:

https://github.com/sindresorhus/refined-github/blob/8daf6b816b83149d98eca32550bd1f3a568cde93/source/features/mark-unread.js#L220-L226

But it should only happen if you have anything marked as unread:

https://github.com/sindresorhus/refined-github/blob/8daf6b816b83149d98eca32550bd1f3a568cde93/source/features/mark-unread.js#L198-L200

**Comment by kujenga** [comment]
Ah! Yes, getting rid of my notifications that I had marked as "unread" resolve this issue, thank you!
