### ISSUE TITLE
API calls need Personal Token to support frequent calls and private repos

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1374]
Refined GitHub needs

- [x] [Personal token](https://github.com/settings/tokens) field in the options
- [x] Automatic token usage by https://github.com/sindresorhus/refined-github/blob/master/source/libs/api.js, if present

**Comment by notlmn** [comment]
Features that can use API:
* Embedded gists (https://developer.github.com/v3/gists/#get-a-single-gist)
* CI/CD status links (https://developer.github.com/v3/repos/statuses/#get-the-combined-status-for-a-specific-ref)
* Get users full name (https://developer.github.com/v3/users/#get-a-single-user)

Can also use GraphQL API to request only required data.

**Comment by yakov116** [comment]
Maybe its just me, I feel very unconformable with the token being displayed with one click. In your issue linker its 2 steps (1. click the ext. 2. Click options).

**Comment by bfred-it** [comment]
> In your issue linker its 2 steps (1. click the ext. 2. Click options).

How is it different here? The token appears in the options

**Comment by yakov116** [comment]
Its 2 steps

1.
![image](https://user-images.githubusercontent.com/16872793/41508166-2a22dcee-720e-11e8-8008-977e34dec904.png)
Then Step 2 opens the options

**Comment by bfred-it** [comment]
Right, so is Refined GitHub

**Comment by yakov116** [comment]
@bfred-it clicking on the ext shows the token.

**Comment by bfred-it** [comment]
Why is your button not hidden in the overflow? It's pretty much useless

**Comment by yakov116** [comment]
>Why is your button not hidden in the overflow? It's pretty much useless

What?

![image](https://user-images.githubusercontent.com/16872793/41510506-ca2fbdea-7233-11e8-8c06-38fcc3680135.png)

**Comment by bfred-it** [comment]
This overflow:

<img width="332" alt="extensions overflow" src="https://user-images.githubusercontent.com/1402241/41510511-2f8bad3e-7266-11e8-9cc5-fdbe662a66ec.png">

**Comment by yakov116** [comment]
@bfred-it 👍, ok...

Would rather not do that.

**Comment by bfred-it** [comment]
@sindresorhus thoughts?

**Comment by sindresorhus** [comment]
If someone has access/control of your computer, all bets are off anyway, so I don't fully agree with your reasoning. That being said, I don't mind making it a password type input. GitHub hides it too: https://github.com/settings/tokens

**Comment by yakov116** [comment]
The issue is not the access, it just doesn't feel right to have it displayed in plain text.
@bfred-it had an issue with using password as it gives a false sense of security.

**Comment by bfred-it** [comment]
@sindresorhus GitHub doesn't store them on your computer in plain text like Chrome does

**Comment by bfred-it** [comment]
`type=password` is the last resort, so how about making the field shorter so it won't be displayed in full?

<img width="511" alt="width: 50%" src="https://user-images.githubusercontent.com/1402241/41512065-438718e2-7283-11e8-8e9b-9e0843835bd3.png">

**Comment by sindresorhus** [comment]
> Also I work in an office and a screenshot is taken every min of my screen, so having it in plain text...

😔

**Comment by bfred-it** [comment]
@yakov116 now I wonder how you're going to get that token in the first place without having it on screen: 😅

<img width="771" alt="" src="https://user-images.githubusercontent.com/1402241/41512510-9ecaca2c-7289-11e8-9d40-eab0cd52a2e9.png">

**Comment by yakov116** [comment]
@bfred-it lol,
I have my ways :) 

Just want to point out its nothing to do with trust. My boss does it so we know that he CAN look back at what we were doing.
But knowing that he can....

**Comment by yakov116** [comment]
Can we collapse the text area after its full? And only show it with clicking the + symbol?

**Comment by borekb** [comment]
Which scopes should be selected for the token? Just `repo` or anything else?

**Comment by bfred-it** [comment]
Can you open a new issue for that? We can change the url to include the required scopes

**Comment by borekb** [comment]
Done: https://github.com/sindresorhus/refined-github/issues/1425

**Comment by archon810** [comment]
Some instructions on the scopes that should be given to the token would be very welcome. Right now, there are a lot, and I'm not sure which ones RG can utilize.

![image](https://user-images.githubusercontent.com/469543/63643861-9ee5e400-c68f-11e9-95ef-42f107c0bbd2.png)

**Comment by jerone** [comment]
@archon810  No need to do anything else. The "Repo" scope is automatically checked.

**Comment by archon810** [comment]
Understood, but to the user, it's not obvious. A small clarification that the right set has been pre-selected would go a long way.

**Comment by busches** [comment]
@archon810 PRs are welcome to make it more obvious or an issue with mockups of what you would propose to change.
