### ISSUE TITLE
Referer in code blocks linkified URLs

### ISSUE THREAD

**Issue by gwarser** [sindresorhus/refined-github#1376]
Is it possible to stop linkifing URLs in code blocks when they contain only links?
Or maybe somehow strip referer header?

I know I can disable `linkify-urls-in-code` completly, but this affect only me.

```
https://www.whatismyreferer.com/
http://example.com/
http://example.net/
```

**Comment by sindresorhus** [comment]
Why? What is the problem?

**Comment by gwarser** [comment]
These links are put inside code blocks to prevent sending referer to linked pages. That's why they are in code blocks. This forces to copy-paste (drag&drop) to new tab.

**Comment by bfred-it** [comment]
That's an easy fix and a fair request, even just for privacy/safety. PR welcome to add the attribute

**Comment by bfred-it** [comment]
Yep! That should do it

**Comment by gwarser** [comment]
Thank you :D
