### ISSUE TITLE
Add color highlighting when viewing source files

### ISSUE THREAD

**Issue by jorgegonzalez** [sindresorhus/refined-github#1378]
Example:

![image](https://user-images.githubusercontent.com/12901172/41435608-6e90a974-6fed-11e8-88af-b6f99f76db05.png)

Some editors have extensions that support the highlighting of hex and RGB color values in strings. It would be awesome if we could implement this when viewing source files and in the GitHub editor. Maybe even in issue threads.

https://github.com/sergiirocks/vscode-ext-color-highlight

Another example:

![image](https://user-images.githubusercontent.com/12901172/41435995-71ae303a-6fee-11e8-85ef-fd3f2752b547.png)

**Comment by bfred-it** [comment]
I think it would be language-dependent and/or error-prone and probably not super light on long files. Perhaps it should be its own extension.

This already exists for CSS: https://chrome.google.com/webstore/detail/github-css-highlighter/eodknooanbabbanekpbcgaldepnenoih

**Comment by jorgegonzalez** [comment]
Didn’t know there was an extension for this already. Feel free to close this issue.
