### ISSUE TITLE
Code Formatting and other handy menus are missing from comments box

### ISSUE THREAD

**Issue by pyus-13** [sindresorhus/refined-github#1379]
There are so many handy comment box features are missing, I have to add quotes manually around the text in the comment box for the code formatting, which is painful. Earlier I used to select all and press the button to format which is gone. 

The document says there are shortcuts but it is not published anywhere about the shortcuts.

Please add that back.

**Comment by bfred-it** [comment]
The shortcuts are the usual ones (ctrl+b for bold, ctrl+i for italics, etc, you can disable the extension to see them on hover) and the buttons can be restored by undoing their styles
