### ISSUE TITLE
Move Issue number into Issue state

### ISSUE THREAD

**Issue by hhsnopek** [sindresorhus/refined-github#1383]
## Proposal
I think we could reduce the amount of space used on longer titles by moving the issue number into the Issue State. However the downside to this is accessibility and newer users, or those that are unfamiliar with the color/icon set, will have to learn the interface.

### Preview
<img width="831" alt="screen shot 2018-06-18 at 9 10 22 am" src="https://user-images.githubusercontent.com/2363940/41541173-778ae890-72d7-11e8-8def-261513abaa9b.png">

**Comment by bfred-it** [comment]
I think this would conflict with https://github.com/sindresorhus/refined-github/pull/1078, making that label too long and with too many issue numbers
