### ISSUE TITLE
Pressing tab in "finish review" comment inserts tab instead of moving cursor to "comment"

### ISSUE THREAD

**Issue by jnothman** [sindresorhus/refined-github#1386]
When adding a final comment to "Review Changes", I tend to hit tab on the keyboard.

Expected: the "Comment" button should be selected (or "Request Changes" / "Approve" with more hits of tab).

Actual: a tab character is inserted.

If tab needs to be left as a character, to allow commenters to write code, then another keyboard shortcut should be provided to click "Approve", "Comment", "Request changes".

**Comment by bfred-it** [comment]
You should be able to press ESC to unfocus and then tab

**Comment by bfred-it** [comment]
Fixed! Thanks for the report
