### ISSUE TITLE
Copying An Issue From One Repo To Another

### ISSUE THREAD

**Issue by Skillz4Killz** [sindresorhus/refined-github#1388]
This is a pretty self-explanatory feature to copy Issues from one repository to another. 

# Use Case
Private Repo: Hosts all code and team coordination and management
Public Repo(Documentation): Users leave bugs/proposals on issues here.

To be able to transfer an issue from X repo to Y repo that you have maybe say admin access of both would be truly amazing and help save a lot of time.

P.S. I love refined-github it is really great stuff.

**Comment by bfred-it** [comment]
Issue copying was discussed before but it’s out of Refined GitHub’s scope. I’m sure there’s some service out there already.
