### ISSUE TITLE
Filenames in sticky header break UI with subset of changes

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#139]
When looking at a single commit inside of a PR, GitHub shows a message in the commit header saying:
> You are viewing a subset of the changes. **View all changes**

![screen shot 2016-03-31 at 22 54 47](https://cloud.githubusercontent.com/assets/506129/14189001/d576d7a0-f793-11e5-819f-7ee516158123.png)

However when you scroll down this message stays in the sticky header and it's not acting nicely with the filename we've added there.

![screen shot 2016-03-31 at 22 55 00](https://cloud.githubusercontent.com/assets/506129/14189038/faa1f190-f793-11e5-9c4e-e4c31a1223cf.png)

(Screenshots are from https://github.com/composer/composer/pull/5134/commits/9d360cf338930f18264994f0fa5643852372c156).

This is a bit similar to #122, but I don't think it depends on whether the filename is long or short.

**Comment by hkdobrev** [comment]
My personal suggestion is to remove the subset changes message from the sticky header, but keep it when the header is not stuck.

**Comment by paulmolluzzo** [comment]
Hiding it when it's stuck is super easy, but do we really want to do that? Is that an important message to keep?

The fix for when it's stuck is:
```css
.is-stuck .subset-files-tab {
    display:none;
}
```

**Comment by DrewML** [comment]
How about we just make it a bit smaller and move it a bit when it's set to `.is-stuck`? Example:

![image](https://cloud.githubusercontent.com/assets/5233399/14236409/da45e160-f9da-11e5-870b-0dee909fe74d.png)

**Comment by paulmolluzzo** [comment]
@DrewML why move it? Just keep it centered and smaller?

**Comment by DrewML** [comment]
We could totally do that, would just require more work to re-center it, due to the way GitHub has it right now. I'm open to either, I just suggested the other route initially because it was quicker/easier :smiley:

**Comment by paulmolluzzo** [comment]
You can make it a full width blue bar with center aligned text. That might look pretty good even.

I don't have a strong objection to just hiding it. But it seems like it might be worth keeping.

**Comment by DrewML** [comment]
Here is how it looks with full width + centered (smaller) text

![image](https://cloud.githubusercontent.com/assets/5233399/14237014/7c9b8e6c-f9e3-11e5-9a89-ada6fdbf0e26.png)

I think it's useful to keep the information around, but I don't have any strong opinions on the UI.

**Comment by paulmolluzzo** [comment]
Bangarang.

What do you think @hkdobrev and @sindresorhus?

**Comment by DrewML** [comment]
Note to self: There is also a message we'll need to take care of in that bar that identifies when the commit you're viewing is out of date (I believe in the case of a rebase, but need to try and replicate again).

**Comment by hkdobrev** [comment]
@DrewML Could you create a PR which tackles the subset-changes message and out-of-date message and we could discuss the actual implementation there? 😄
