### ISSUE TITLE
Monospace filenames/directories

### ISSUE THREAD

**Issue by zx8** [sindresorhus/refined-github#1390]
Similar to https://github.com/sindresorhus/refined-github/pull/1089

Would be great to see filenames & directories in a monospaced font.

**Use-case:** We have UUID filenames, e.g.

> 3013C652-0F83-4A0E-8C8D-B029901451BE.asc
> 5312A1C1-A048-4200-907B-85AA70679DC3.asc
> AD3EE609-279A-4509-B421-BBD369C5ABF.asc
> FB61610E-91E7-4B8E-A4AF-052D7379ED4C.asc

Looking at these without a monospaced font makes it hard to tell there's been a typo in one of them. Compare with:

```
3013C652-0F83-4A0E-8C8D-B029901451BE.asc
5312A1C1-A048-4200-907B-85AA70679DC3.asc
AD3EE609-279A-4509-B421-BBD369C5ABF.asc   <-- obvious that this one is wrong!
FB61610E-91E7-4B8E-A4AF-052D7379ED4C.asc
```

**Comment by bfred-it** [comment]
It kinda makes sense but I'm not sure it'd look decent as a new _default_. #1089 kinda works because there's often code in the textarea

**Comment by sindresorhus** [comment]
It looks ugly as monospaced and I don't think "spotting a typo" is good enough reasoning to make it look worse.
