### ISSUE TITLE
Expand file editor

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#1394]
It'd be very useful :) Also previewing changes would be easier.

**Comment by sindresorhus** [comment]
@szmarczak Can you elaborate? It's not really clear what you're asking for.

**Comment by szmarczak** [comment]
I meant this:

![image](https://user-images.githubusercontent.com/36894700/42218089-be55099e-7ec7-11e8-8f23-213fe28cb22d.png)

Should be as big as:

![image](https://user-images.githubusercontent.com/36894700/42218127-daac4e4a-7ec7-11e8-8691-1fe333c9bcb1.png)

And here the same:

![image](https://user-images.githubusercontent.com/36894700/42218250-39a11a52-7ec8-11e8-83ea-aa93ae77ed82.png)

I can do a PR for that 😄

**Comment by busches** [comment]
There are extensions that do this already. See discussion in #1171 #1172 #1243.

**Comment by szmarczak** [comment]
Oh, haven't seen that and couldn't find it. Thanks @busches 😃
