### ISSUE TITLE
Issues updates *delete in progress comments*

### ISSUE THREAD

**Issue by colemickens** [sindresorhus/refined-github#1397]
I had written a comment. I was about to send it. A bot/CI job/something posted an update to the Issue and the comment box was blanked.

I've never, ever experienced this, until installing this extension.

**Comment by colemickens** [comment]
Note, it may have been that the author force pushed a new commit. Regardless, the behavior exhibited is undesirable.

**Comment by bfred-it** [comment]
I don’t think it’s due to this extension, nowhere in the code we empty the field.

I’ve experienced something similar when editing a comment and a bot edited it before I saved it again. GitHub reset the field to what the bot left, without giving me the ability undo it. Even this is just GitHub

**Comment by colemickens** [comment]
Hm. It was very weird, and it wasn't a comment edit, since the button said "Comment" instead of "Update Comment".

Anyway, I'll go ahead and close this.
