### ISSUE TITLE
Safari version: help us setup the build and deployment

### ISSUE THREAD

**Issue by fantattitude** [sindresorhus/refined-github#14]
Would be great to have a Safari version as well 😁

**Comment by sindresorhus** [comment]
Shouldn't be hard to adapt the code. Feel free to steal the code and make a Safari extension. I'm not going to, though.

**Comment by fantattitude** [comment]
I'll probably PR later today then ;P

**Comment by sindresorhus** [comment]
I'm not interested in maintaining it. Just fork the repo and do your thing.

**Comment by fantattitude** [comment]
What if I propose you a PR making the build process automatic like what does Octotree (builds for every navigator are automated through Gulp) ? https://github.com/buunguyen/octotree

**Comment by sindresorhus** [comment]
@fantattitude No. Sorry, not trying to be difficult, but I've gone through this before and made extensions for all browsers, and it was such pain. Even if you automate the build-step, I will still receive issues regarding the Safari extension. Can't you just maintain it on your own, and I'd be happy to link to your repo.

**Comment by fantattitude** [comment]
Oh yeah don't worry 👌🏻
I was just asking I can totally understand your point. Supporting with several browsers can be painful. 

I'll do that then, thanks for your time and nice work on the extension !

**Comment by fantattitude** [comment]
Hi @sindresorhus, I made a repo with the Safari extension at https://github.com/fantattitude/refined-github-safari, feel free to tell me if everything's okay for you (regarding credits for example) and link to it on your README 😉

**Comment by sindresorhus** [comment]
@fantattitude Cool. Linked to it from the readme :)

**Comment by nesl247** [comment]
I suppose this could be reopened then?

**Comment by sindresorhus** [comment]
Yes! https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by ngyikp** [comment]
Running `xcrun safari-web-extension-converter` on the Chrome Web Store version without any modifications seem to work at first glance:

<img width="1440" alt="refined github" src="https://user-images.githubusercontent.com/6135313/85346258-d9592100-b4ec-11ea-81b9-aaff66e94815.png">

**Comment by nesl247** [comment]
@ngyikp Can you post some instructions on how you did this?

**Comment by tbodt** [comment]
Can you distribute a safari extension outside of the Mac App Store? If so do you need to notarize it (and thus pay for a $100 developer account)?

**Comment by sindresorhus** [comment]
I already have an App Store account and I have prepared the name "Refined GitHub". That's not a problem. What will be more difficult, however, is to automate the publishing. Maybe we could use [fastlane](https://fastlane.tools) for this.

**Comment by andreineculau** [comment]
Is it possible to publish Safari 14 webextensions and install them (say on Safari 14 TP on Catalina) already today? If so, would appreciate manual but less-often publishing to the App Store already now.

**Comment by sindresorhus** [comment]
We're not going to officially publish it until we have the process automated. We do fixes all the time for things that break, and if users don't get those fast, they'll complain with bad reviews on the App Store. I don't want to commit to having to manually upload new versions constantly.

For now, you can manually install it yourself: https://github.com/sindresorhus/refined-github/issues/14#issuecomment-647828485

**Comment by andreineculau** [comment]
Got it.
FWIW `xcrun safari-web-extension-converter` doesn't work on Catalina with Xcode 12 Beta and Safari 14 TP. Only works on Big Sur. Thus my request.

**Comment by gibfahn** [comment]
For anyone else who was trying to do this but not succeeding, from the docs I believe the steps are:

```shell
git clone https://github.com/sindresorhus/refined-github && cd refined-github
npm install && npm run build # Unsure if required
xcrun safari-web-extension-converter $PWD/source/
```

This opens Xcode, you then build it, and [allow unsigned extensions in Safari](https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension#2957925). You can then enable the extension in Preferences -> Extensions.

https://developer.apple.com/documentation/safariservices/safari_app_extensions/building_a_safari_app_extension#2957926
https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

---

This doesn't give you a way to enable the extension on GHE instances though, as you can't click the Refined GitHub icon, which is a bit of a limitation. I assume you could modify the source to fix it, but haven't managed to get that to work.

**Comment by fregante** [comment]
That's almost correct, except `distribution` instead of `$PWD/source/`

However I get this with Xcode 11.5

```
xcrun: error: unable to find utility "safari-web-extension-converter", not a developer tool or in PATH
```

**Comment by sindresorhus** [comment]
@fregante I think you need the Xcode 12 beta.

**Comment by wearhere** [comment]
@gibfahn I've followed [your steps](https://github.com/sindresorhus/refined-github/issues/14#issuecomment-670024407) but don't see any Refined GitHub features like, for instance, avatar photos next to the thumbs-up emoji at the top of this thread, despite the extension being enabled

<img width="904" alt="image" src="https://user-images.githubusercontent.com/110000/89841839-e081d000-db28-11ea-97c5-9d30a702bf4a.png">

and there not being any errors in the console… did you have to do anything else?

**Comment by nesl247** [comment]
@wearhere Been having the same issue for quite some time as well, thought it was just me.

**Comment by gibfahn** [comment]
>However I get this with Xcode 11.5

You might need the Big Sur beta as well as the Xcode 12 beta.

**Comment by gibfahn** [comment]
>@gibfahn I've followed your steps but don't see any Refined GitHub features like avatar photos next to the thumbs-up emoji at the top of this thread, despite the extension being enabled

Yeah, this process got me to the extension showing up in the preferences as in your screenshot. I haven't actually used it yet or confirmed any of the features actually work.

You'd probably need to use the devtools debugger (for the current page and for the background extension) to work out what's going on.

**Comment by iamstarkov** [comment]
safari 14 was released last week

**Comment by notlmn** [comment]
Uhh, shameless plug to similar discussion: https://github.com/notlmn/browser-extension-template/issues/31

**Comment by dvcrn** [comment]
There is https://github.com/lautis/refined-github-safari which is installable through `brew cask install refined-github-safari`. Last commit is 2 days ago so it's pretty up to date

**Comment by fregante** [comment]
What's needed here exactly?
Is Safari support official/stable?
Does Apple accept the new browser extensions?

**Comment by wearhere** [comment]
@dvcrn I tried out https://github.com/lautis/refined-github-safari but it has a couple of limitations relative to this project, most notably lack of support for GitHub enterprise: https://github.com/lautis/refined-github-safari/issues/8. Hoping that that might be easier if the project used the new Safari extensions (it doesn't atm) and/or if this project were ported directly.

@fregante I don't know if Safari support is stable or if Apple accepts the new browser extensions per se, since Big Sur is still in beta (and so I think Safari 14 is too?) _but_ the new extensions are usable in the beta. _This_ extension doesn't work as-is last I checked up-thread https://github.com/sindresorhus/refined-github/issues/14#issuecomment-671644151, but I would love to beta-test it as support becomes available.

**Comment by markdorison** [comment]
> @fregante I don't know if Safari support is stable or if Apple accepts the new browser extensions per se, since Big Sur is still in beta (and so I think Safari 14 is too?) _but_ the new extensions are usable in the beta.

Safari 14 was [released officially on September 16th](https://en.wikipedia.org/wiki/Safari_version_history#Safari_14) so no blockers on that specific front.

**Comment by fregante** [comment]
So we need help with

- [ ] Create an XCode "App" 
- [ ] Configure Fastlane: https://docs.fastlane.tools/getting-started/ios/appstore-deployment/
- [ ] Setup FastLane deployment action: https://github.com/marketplace/actions/fastlane-action

**Comment by lautis** [comment]
I'm looking into converting the current Safari app to use Web Extensions. Work in progress can be seen https://github.com/lautis/refined-github-safari/pull/21. The signing part looks quite puzzling as what used to be enough for the app extensions is not working for web extensions.

I'd be happy to merge the work to refined-github, although at least in short-term working on a separate repository is easier for me.

**Comment by fregante** [comment]
I noticed that Apple offers a conversion tool, would it be easier to use that? https://developer.apple.com/documentation/safariservices/safari_web_extensions/converting_a_web_extension_for_safari

**Comment by lautis** [comment]
Apple's conversion tool doesn't directly result in a working extension since there's Safari-incompatible syntax. After fixing that, the end result is pretty much same as in my branch.

**Comment by lautis** [comment]
Looking at Apple's materials, it might be that the missing part from my work is App Store. For Safari Extensions, [only App Store is listed as a distribution option](https://developer.apple.com/safari/extensions/), whereas simple applications can be distributed outside of App Store by signing and notarising the app with Developer Id certificate. The Developer Id certificate approach also worked with the previous Safari App Extensions.

**Comment by fregante** [comment]
Not to stop any efforts, but [Safari doesn't support negative lookbehinds yet](https://bugs.webkit.org/show_bug.cgi?id=174931) 🤦‍♂️ so no javascript code is running in my tests

<img width="563" alt="" src="https://user-images.githubusercontent.com/1402241/96800465-064e0f80-13cb-11eb-88e2-8660fbc12dd2.png">

**Comment by fregante** [comment]
Other than that, the difference I see it that there's a preference button and page, so the options don't need to be re-implemented like in your current wrapper:

<img width="884" alt="" src="https://user-images.githubusercontent.com/1402241/96800866-fb47af00-13cb-11eb-8c32-c8dce73d9e56.png">

**Comment by fregante** [comment]
## Refined GitHub is now available for Safari 🎉 

but you'll have to build it locally. Please help us set up auto-deployment in https://github.com/sindresorhus/refined-github/issues/3686
