### ISSUE TITLE
Visit default branch button is wrongly appears

### ISSUE THREAD

**Issue by chez14** [sindresorhus/refined-github#1413]
My repo have different default branch, so it's not `master` anymore, and visit default branch button is still showing up, and when clicked it does refresh the page.

![image](https://user-images.githubusercontent.com/5555026/42739817-888d32b8-88c8-11e8-883f-b44ad760db48.png)

Mentioned repo (for testing):
https://github.com/ftis-admin/pinjam-ruang

RefinedGithub Ver:
18.7.15.1636

Thank you!

**Comment by chez14** [comment]
Hmm it's just solved now, the button are now missing.

![image](https://user-images.githubusercontent.com/5555026/42853259-8d71fad2-8a5f-11e8-8492-699b6b4a304c.png)

Should i worry that this is GH's bug?

Anyway, thank you.

**Comment by bfred-it** [comment]
Nah it wasn't a GH bug, probably just cache issues.
