### ISSUE TITLE
Always take to master branch from search result

### ISSUE THREAD

**Issue by tamalsaha** [sindresorhus/refined-github#1415]
Thanks for this great extension. Could you add a feature so that when I click on a link from search result it takes to the master branch? I understand the file may be missing from master branch. May be there could be an extra link that opens a new tab which open the link in master. If that fails (404), I can open whatever git hash github search result in showing.

**Comment by bfred-it** [comment]
Can you give me an example where the search result doesn't take you to the master branch?

**Comment by bfred-it** [comment]
That's kinda weird. The search takes you to the last commit that touched that file.

Also, deleted/moved files don't appear in searches, so it could never 404.

The hard part is that we don't know what the default branch is without first visiting a non-default branch page… or via API call.

**Comment by tamalsaha** [comment]
How about just adding an extra button that I can click to go to the master page. It does not have to always work (assuming it is missing in master branch etc). 
![search branch](https://user-images.githubusercontent.com/94814/42815078-3261b6f8-897b-11e8-9a34-c270876d3353.png)

**Comment by bfred-it** [comment]
`master` != default branch.

**Comment by tamalsaha** [comment]
I don't have a clear idea. I can tell you why linking to to the last commit for a search result does not work for me. 

I mostly code in GO and I use Sourcegraph's chrome plugin to `go to definition` type thing from browser. Sourcegraph uses current branch of a file to `go to definition`. So, I almost always have to go to master so that I get the correct definition for a type.

**Comment by bfred-it** [comment]
> I mostly code in GO and I use Sourcegraph's chrome plugin to go to definition type thing from browser. Sourcegraph uses current branch of a file to go to definition. So, I almost always have to go to master so that I get the correct definition for a type.

That's unrelated. The change you're asking for will not affect Sourcegraph links because they are direct to the file, they don't go through the search (by judging the video here https://about.sourcegraph.com/)

**Comment by tamalsaha** [comment]
I do the searching from Github UI and then go the result page that github shows. Then  use Sourcegraph to visit function definitions etc.

I don't use Sourcegraph search directly because they are too slow to be usable.

**Comment by sindresorhus** [comment]
We now show a "master" button if you visit a file on a specific SHA. Example: https://github.com/sindresorhus/refined-github/blob/b99ffe66ad40a37140da05ca01f96dbe5c207e4e/package.json
