### ISSUE TITLE
Change default profile tab to repositories

### ISSUE THREAD

**Issue by tamalsaha** [sindresorhus/refined-github#1416]
When I click on someone's profile link, I always go to their `repositories` tab.

**Comment by sindresorhus** [comment]
We appreciate the suggestion, but it's not something we want to do. While the repositories tab is useful, we feel the main profile page is useful too.

However, what we could consider is showing maybe the user's 10 recently modified repos and the repo search box on the profile page landing page: https://github.com/sindresorhus/refined-github/issues/1423 https://github.com/sindresorhus/refined-github/issues/1424
