### ISSUE TITLE
👋 suggestions to maintainers to encourage first-time users?

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sindresorhus/refined-github#1419]
For repository maintainers seeing issues and pull requests sent from first-time users, sending some happy "thank you!"s and emojis to the users can be a very encouraging, inclusive behavior. For example: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/25007#issuecomment-381767908

Here is what GitHub shows for first-time users on their first pull requests:

![image](https://user-images.githubusercontent.com/3335181/42835492-c62db26a-89ad-11e8-8bc9-3773b1262eb1.png)

...which is easy to miss and doesn't give much indication that this is a good time to encourage the user.

We already have 👋 suggestions from GitHub on the user's side: 

![image](https://user-images.githubusercontent.com/3335181/42835691-4184d4f2-89ae-11e8-9411-b7a2b0eb0754.png)

How about adding versions of this for the maintainers' side?

* "👋 / It looks like this is <user-name>'s first issue on refined-github! How about sending some 🙌 emojis 🎈 and thanking them for their contribution?"

* "👋 / It looks like this is <user-name>'s first pull request! How about sending them some 🙌 emojis 🎈 and thanking them for their contribution?"
    * Alternate form: their first pull request _ever_
    * Alternate form: on completion of the pull request

Mockup:

![image](https://user-images.githubusercontent.com/3335181/42835849-b3238928-89ae-11e8-944a-fcb26f7d3a3c.png)

_(instigating Twitter thread: https://twitter.com/JoshuaKGoldberg/status/1019260761569280000)_

**Comment by jamiebuilds** [comment]
You could make a link in that popup on the maintainer's side to automatically populate the comment field with a message thanking them for their contribution that you then add feedback to. 

<img width="798" alt="screen shot 2018-07-18 at 12 07 26 pm" src="https://user-images.githubusercontent.com/952783/42902340-2bc697d8-8a83-11e8-88ee-1ff42a397dca.png">

**Comment by sindresorhus** [comment]
I like @jamiebuilds' suggestion, but I would randomize the emoji and text from a list of alternatives so it doesn't look machine generated.

**Comment by bfred-it** [comment]
Here's the native HTML for that popup:

```html
<div id="first-time-contributor" class="Popover js-prompt" style="top: 28%;">
  <div class="Popover-message Popover-message--left-top Box box-shadow-large">
    <button type="button" class="btn-octicon float-right p-2 js-prompt-dismiss" aria-label="Close" data-ga-click="New pr, click dismiss link in sidebar (new contributor), repo:babel/babel"><svg class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg></button>
    <div class="p-4">
      <p class="text-center"><g-emoji alias="wave" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f44b.png" class="emoji" title=":wave:">👋</g-emoji></p>

      <p>It looks like this is your first time opening a pull request in this project!</p>

      <p>
          Be sure to review the <a data-ga-click="New pr, click contributing link in sidebar (new contributor), repo:babel/babel" href="/babel/babel/blob/master/CONTRIBUTING.md">contributing guidelines</a> and <a data-ga-click="New pr, click code_of_conduct link in sidebar (new contributor), repo:babel/babel" href="/babel/babel/blob/master/CODE_OF_CONDUCT.md">code of conduct</a>.
      </p>

    </div>
  </div>
</div>
```

<img width="324" alt="screenshot" src="https://user-images.githubusercontent.com/1402241/52690095-7fab2300-2f97-11e9-8cd4-cc98cd0c981c.png">

**Comment by bfred-it** [comment]
I think this is a bit out of Refined GitHub's scope and its code would have to run forever even though it shouldn't be visible more often than twice a year or so.

I'd say GitHub should do this. cc @lukehefson

**Comment by lukehefson** [comment]
> I'd say GitHub should do this. cc @lukehefson

Thanks @bfred-it – I'll be sure to let the right folk/team know your thoughts!
