### ISSUE TITLE
[Seeking Feedback] Reporting on issues metadata

### ISSUE THREAD

**Issue by ahmadassaf** [sindresorhus/refined-github#1420]
Hi guys,

Where I work, we use Github extensively as the source of truth for our project management. We rely heavily on tags and have various reports that rely on correct labelling approaches. However, things can easily go out of control. In my local fork, I have created a little report that runs in the issues list and allows me directly to see where there are process breaks.

Below is a gif about how it is working in action

![ezgif com-gif-maker 1](https://user-images.githubusercontent.com/550726/42841595-7a119a54-8a02-11e8-8405-3d03ca4fcc2b.gif)

I can easily see what are the rules broken and then immediately filter the issues to the ones in question. 

Will be happy to see feedback on this and if others find it useful then I will happily PR this.

The code is extensible and it is easy for people to write their own custom rules .. I would still need to think how to expose this nicely but the configuration file in the end looks like:

```
	MULTIPLE_TYPES : {
            error: 'should not belong to more than one type',
            filter: (label) => {
                return label.startsWith('2: Type:')    
            },
            condition: (filteredLabels) => {
                return filteredLabels.length > 1
            }
        },
    ONE_PRODUCT_AREA: {
            error: 'should belong to at least one product area',
            filter: (label) => {
                return label.startsWith('3: Product Area:');
            },
            condition: (filteredLabels, labels) => {
                return (labels.includes('2: Type: Bug', '2: Type: Story')) && !!filteredLabels.length
            }
        }
```

Where you can easily define the error, the text message and the filter and condition to apply.

**Comment by ahmadassaf** [comment]
You closed this too soon @bfred-it :( I would have loved to hear the community opinion about this. The main idea behind the code snippet I added is that it can be extended easily to match any rule you define but of course needs programming know-how. I completely understand that this is not a `plug and play` feature but curious to see if there is value to it

**Comment by bfred-it** [comment]
I'm sure there's value to it. You can probably discuss it in https://github.com/sindresorhus/module-requests
