### ISSUE TITLE
Show recently modified repos on profile landing pages

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1423]
Maybe the 10 most recently modified repos? Where would be a good space for it?

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by tamalsaha** [comment]
This will be great.

**Comment by bfred-it** [comment]
Could this be implemented the same way as #1495?

**Comment by sindresorhus** [comment]
@bfred-it Yes
