### ISSUE TITLE
Show the repo search on profile landing pages

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1424]
Can be useful when you go to a user just to search for a repo of theirs.

Normally, you have to go to https://github.com/sindresorhus?tab=repositories to be able to search.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by bfred-it** [comment]
Possible since https://github.com/sindresorhus/refined-github/issues/1011#issuecomment-441217145
