### ISSUE TITLE
Pre-select personal access token scopes in a link from options

### ISSUE THREAD

**Issue by borekb** [sindresorhus/refined-github#1425]
The link from options added in #1374 could pre-select the required scopes.

**Comment by nesk** [comment]
Could  it be possible to list in this issue which scopes should be selected for the token? So we know what to check before the feature is ready. 🙂

**Comment by borekb** [comment]
So far, the `repo` scope seems to be enough. I haven't explored every possible feature of Refined GitHub though.

**Comment by idkjs** [comment]
Default repo options don't show up on Firefox

Clicking on 'your github token' in image:
![image](https://user-images.githubusercontent.com/2370391/50044871-4420d500-008a-11e9-914d-726f42985f0c.png)

Takes you to the github token page with no preselected defaults as intended.

![image](https://user-images.githubusercontent.com/2370391/50044861-1f2c6200-008a-11e9-83a7-6df8a2976720.png)

Just an FYI
