### ISSUE TITLE
Blame parent links could be duplicated when navigating back

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#143]
Follow-up to #24, similar to #114 and #135.

![screen shot 2016-04-01 at 22 11 31](https://cloud.githubusercontent.com/assets/506129/14217444/b8ed163a-f856-11e5-91f4-4d59a07fbdb2.png)

It's a bit strange only the first one is repeated.

**Comment by paulmolluzzo** [comment]
> It's a bit strange only the first one is repeated.

FWIW, it's because when it hits that `^Blame` link the regex test for splitting the `href` fails. The new link has extra stuff after the commit hash but the regex expects the EOL.
