### ISSUE TITLE
Filter is partially covered by first row in issue/PR page

### ISSUE THREAD

**Issue by pjessesco** [sindresorhus/refined-github#1431]
Hi, I'm using macOS 10.13.6, chrome 67. Thanks for the nice extension :)

Extension off
![2018-07-20 11 50 43](https://user-images.githubusercontent.com/11532321/42980676-61e0d748-8c13-11e8-9928-bd8bd30b94a8.png)

Extension on
![2018-07-20 11 50 56](https://user-images.githubusercontent.com/11532321/42980678-649ea122-8c13-11e8-88ca-2c079c634816.png)

**Comment by yakov116** [comment]
Looks like a z-index issue

**Comment by yakov116** [comment]
@bfred-it the filter z-index was moved to 1 (it was 30 before). Should we move it back up to 30?

**Comment by ryota-murakami** [comment]
According to a [code comment](https://github.com/sindresorhus/refined-github/pull/1320/files#diff-d2e7eab294822ea5cf4617ee54797b87R792), 

```
/* Must be above .modal-backdrop (z-index 20) #1317 and below .select-menu.active (z-index 30) */
```

the value have to set to below 30.

Might be 29 is fine?

refer: https://github.com/sindresorhus/refined-github/issues/1317

**Comment by bfred-it** [comment]
That comment is actually outdated and should be removed. Modal-backdrop isn’t visible anymore

**Comment by ryota-murakami** [comment]
@bfred-it I see, thanks!
