### ISSUE TITLE
Cannot enabled an enterprise domain in chrome canary

### ISSUE THREAD

**Issue by kirbyjs** [sindresorhus/refined-github#1432]
I cannot "Enabled Refined GitHub on this domain" when using the latest of chrome canary. I get an alert with this issue: "Error: This function must be called during a user gesture".

I know it's chrome canary, so it probably won't be high on your radar, but is it possible to set the domains manually somewhere?

**Comment by bfred-it** [comment]
It's best to open an issue for this regression on Chrome Canary. Currently there's no other way.
