### ISSUE TITLE
PR suggestion box overlays extra extensions' content

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sindresorhus/refined-github#1433]
Fun combination with SourceGraph. @sqs

![image](https://user-images.githubusercontent.com/3335181/43017401-d7192d02-8c0a-11e8-9289-fa858a4b6065.png)

Adding this CSS rule on top of the existing ones fixes it:

```
[data-url$="recently_touched_branches_list"] {
    background: transparent;
}
```

![image](https://user-images.githubusercontent.com/3335181/43017541-5876963c-8c0b-11e8-8e2f-3606da650cc1.png)

**Comment by sqs** [comment]
Thanks! We will test and submit a PR to this repository. Many of us use Refined GitHub here @sourcegraph and should have fixed this sooner!

**Comment by bfred-it** [comment]
Essentially a known issue tracked in https://github.com/sindresorhus/refined-github/issues/1109

**Comment by JoshuaKGoldberg** [comment]
@bfred-it that issue has been open since February and hasn't seen activity since March. Can we keep this open as a non-duplicate workaround until the dialog is moved?

I don't see any reason not to fix this small issue in the meantime.

**Comment by bfred-it** [comment]
The issue remains here for those who look for it. No reason to keep two issues open about the same thing.

> I don't see any reason not to fix this small issue in the meantime.

PR welcome to drop the background color and and this line https://github.com/sindresorhus/refined-github/blob/efcb2f5ed96e8a924f5fb56519a8665e864f7d7f/source/content.css#L778

It was added to cover all the buttons but I can't find the discussion about it anywhere, so maybe it's fine.

**Comment by bfred-it** [comment]
@JoshuaKGoldberg will you send a PR or can this be closed?

**Comment by bfred-it** [comment]
Thanks! We might as well push it down of about 25px to only overlap the buttons partially. Perfect alignment isn’t possible because the distance also depends on the possible “Forked from xxx/xxx” text. The gray background masked this issue before.
