### ISSUE TITLE
PR suggestion box has slightly more margin below the button than above

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [sindresorhus/refined-github#1434]
It looks like... maybe 1px more?

![image](https://user-images.githubusercontent.com/3335181/43017571-70cf6a88-8c0b-11e8-83a2-ebf2bf8d3b1e.png)

_you monsters!_

**Comment by bfred-it** [comment]
Where?

<img width="337" alt="screen shot 2018-07-20 at 23 15 04" src="https://user-images.githubusercontent.com/1402241/43025622-c128c0f8-8c72-11e8-844c-3b7230e2c7ac.png">

OSX/Chrome/Retina looks fine. PRs welcome to adjust it though

**Comment by JoshuaKGoldberg** [comment]
Oh sorry @bfred-it, didn't notice your response until now! The difference between above and below the green 'merge' button. 

![image](https://user-images.githubusercontent.com/3335181/48509504-52779900-e81f-11e8-92a8-c56845bc3369.png)

I'm on a Surface Laptop with Windows 10 on Chrome 70.

**Comment by bfred-it** [comment]
Can you submit a PR? I don’t see it here

**Comment by JoshuaKGoldberg** [comment]
I don't really have the time to get this set up locally. If nobody who does have the time minds, that works too!
