### ISSUE TITLE
Remove Shift + Enter shortcut in favour of GitHub own single comment shortcut

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1442]
#751 is being replaced by https://blog.github.com/changelog/2018-07-24-keyboard-shortcut-to-leave-a-single-comment-in-pull-requests-reviews/

I think we should remove the feature and move to https://github.com/sindresorhus/refined-github#previously-part-of-refined-github

What do you think?

**Comment by sindresorhus** [comment]
👍
