### ISSUE TITLE
GitHub added feature to highlight targeted comments

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#1443]
GH added the feature to highlight targeted comments, in their own way by adding a drop shadow. This affects #1165, and it looks like the change still doesn't affect review comments.

![image](https://user-images.githubusercontent.com/37769974/43272661-2e64f020-9118-11e8-8516-ce92e33d9b25.png)

**Comment by jdreesen** [comment]
https://blog.github.com/changelog/2018-07-26-highlighting-of-permalinked-comments/

**Comment by borekb** [comment]
I tried to undo the RGH style change but it's not so trivial :) The two together look a bit weird, IMO.

**Comment by sindresorhus** [comment]
I think we should just drop this feature from Refined GitHub then. The drop shadow looks better.

**Comment by notlmn** [comment]
But the GHs variant of highlight on review comments look hideous.

![image](https://user-images.githubusercontent.com/37769974/43654355-97e111ea-9768-11e8-9b18-e23714b9257d.png)

Why wouldn't they copy the same styling as RGHs. RGHs styling was very good and standing out. IMHO the drop shadow looks immature, and is not even recognizable.
