### ISSUE TITLE
Github now excludes + and - when copying from diffs

### ISSUE THREAD

**Issue by xt0rted** [sindresorhus/refined-github#1444]
A new change just went live that excludes `+` and `-` when copying the contents of a diff. That feature of the plugin shouldn't be needed now.

**Comment by kubukoz** [comment]
Could this be the cause of missing letters at the start of each line in diffs?
https://github.com/scala/scala.epfl.ch/commit/d8fcdfab9a2adf2d6cfe5e10979ba034cf38bf47

![image](https://user-images.githubusercontent.com/894884/43294100-06fc133a-913e-11e8-9510-c28bfa16b125.png)

**Comment by evanmcmahonf** [comment]
Also having this issue, you can disable the feature while we wait for it to be removed:

```remove-diff-signs```

![screen shot 2018-07-27 at 10 22 00 am](https://user-images.githubusercontent.com/35747865/43295239-f7aee56c-9186-11e8-82cc-94c325e2b49e.png)

**Comment by xt0rted** [comment]
FYI: GitHub disabled this a little while ago after a report of the first character missing on twitter. Looks like the person was using Refined GitHub based on their screen shot. Not sure when it'll be turned back on though.

**Comment by BrizzleRocker** [comment]
Jolly annoying! 

![](https://files.slack.com/files-pri/T5NQ9TQ4A-FBZAWNVQF/image.png)

The from @evanmcmahonf works a treat!

**Comment by kubukoz** [comment]
Latest solution by @KattMingMing in #1451.
