### ISSUE TITLE
Permalinks for volatile links in comments

### ISSUE THREAD

**Issue by sonicdoe** [sindresorhus/refined-github#1448]
Sometimes I stumble upon comments that link to a specific location on a repository’s default branch. For example: https://github.com/sindresorhus/refined-github/blob/master/source/libs/api.js#L3.

Such links are quite volatile, therefore, it would be awesome if Refined GitHub would add a “View link at the time of this comment” button next to such links.

This would be very similar to the existing “View repo at the time of this comment” functionality (https://github.com/sindresorhus/refined-github/issues/732), however, it would work for links to specific locations and for links to repositories other than the one where the comment was posted.

**Comment by bfred-it** [comment]
I’m wondering if this should just be automatic. It’s easier to reach the latest version than it is to reach the linked version.

**Comment by bfred-it** [comment]
That’s why I said it’s easier to reach the latest version than the other way around. I could see why this might not be desirable though. 

*However* if the link points to a line, I’d assume that the author meant that line *at that point in time* and nothing else. 

Whatever we do we have to also consider that we’re shortening the links so _that_ would have to be updated somehow too. 

I can’t think of a sensible way to do this (other than adding yet another icon next to each comment)

Perhaps in the new comment dropdown? Could the previous functionality also be moved in there?

**Comment by sindresorhus** [comment]
> However if the link points to a line, I’d assume that the author meant that line at that point in time and nothing else.

This I agree with. Here the intention is clear.

**Comment by sindresorhus** [comment]
PR welcome.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by bfred-it** [comment]
Implemented how? We discussed a few options.

I think the cleanest way would be to give a button to changes all the non-perma-links to permalinks. Ideally on the whole thread. Perhaps a keyboard shortcut (as undiscoverable as that may be)

_Better_ yet, add the "code" icon next to all non-perma-links, like we do in the comment headers. Perhaps a bit noisy but pretty straightforward.

**Comment by uschek** [comment]
After running into links where the line numbers didn't match anymore after some time, I believe that links to code lines should always be permalinks pointing to a specific commit.

I like the way Bitbucket implemented this: When clicking a link to a line of code, the branch name is automatically replaced by the current commit hash in `window.location`. This way users can always copy a real permalink pointing to the commit. It would be great if that also worked on GitHub.

For existing links in comments or links from users who don't use this great extension, I agree with the proposed solution.

**Comment by bfred-it** [comment]
PR
