### ISSUE TITLE
PR view removes first char of each line in some files

### ISSUE THREAD

**Issue by Najki** [sindresorhus/refined-github#1453]
Recently I started seeing a bug in pull request view. The first few files in the pull request have first char removed from every line. It's annoying to review code properly when what I see is different from what everyone else sees. 

Here is a screenshot of a PHP file (with some censored parts for any copyright or security reasons) where lines should begin with "use", but I can only see "se". 

![image](https://user-images.githubusercontent.com/765518/43388984-decb5a42-93ea-11e8-8cb5-0c7438e5528d.png)

What have I discovered on my own:

* It affects the "Files" tab of Pull Request view
* It does NOT affect Code view
* It also affects other types of files, like .env, Makefile and several others. 
* I think that it only applies to first one or two files cause most of the time other files are displayed properly. 
* It doesn't matter if affected files have any Github PR review comments attached or not.
* It's not a matter of display or scroll. I've checked the source code view in Chrome and there really is a "se" instead of "use".
* The proper version is visible for a really short time while loading the page and then first chars are removed.
* Disabling "Refined Github" extension fixes it but obviously that's not something that I would like to stick with. 

I really like this plugin, but I'm disabling it until this bug is fixed.

**Comment by jdreesen** [comment]
See https://github.com/sindresorhus/refined-github/issues/1444 and especially this comment: https://github.com/sindresorhus/refined-github/issues/1444#issuecomment-408274280

**Comment by Najki** [comment]
Oh, sorry for posting a duplicate. I was looking for similar issues but somehow didn't found this one. I'm closing this.
