### ISSUE TITLE
First column of characters disappeared in diffs

### ISSUE THREAD

**Issue by bitfactory-rik-vanderkemp** [sindresorhus/refined-github#1456]
Chrome: 
67.0.3396.99 (MacOs 10.13.4)

Chrome extension Version:
18.7.25.1641

<img width="405" alt="screen shot 2018-07-31 at 09 49 47" src="https://user-images.githubusercontent.com/41439582/43445668-41f98e74-94a7-11e8-935f-6d2ff36849e2.png">

Everywhere a diff is shown first column of characters are cut off. When I turn off the extension all is good again. When there is no diff it renders correctly.

**Comment by vinkla** [comment]
There was a fix released in `18.7.30.1747`. Try updating to the latest version.

**Comment by bitfactory-rik-vanderkemp** [comment]
That did the trick, thanks @vinkla
