### ISSUE TITLE
First character gets clipped in diffs

### ISSUE THREAD

**Issue by sloria** [sindresorhus/refined-github#1457]
![image](https://user-images.githubusercontent.com/2379650/43464541-5cdad4ee-94a9-11e8-92ae-8a204056d289.png)

There is an error in the console.

![image](https://user-images.githubusercontent.com/2379650/43464577-73eca9aa-94a9-11e8-86a9-4f8086bc89ab.png)

I am using Firefox 61.0.1 (latest stable as of this writing) on macOS 10.13.5 (High Sierra)

**Comment by yakov116** [comment]
Please search the issues, this is issue number 8.

**Comment by sloria** [comment]
Ah, I did do a quick search and I hadn't seen the other ones. Not sure how a missed those. Sorry for the noise!

Confirmed that this is fixed after updating to the latest version.
