### ISSUE TITLE
Double delete icons

### ISSUE THREAD

**Issue by lode** [sindresorhus/refined-github#1458]
I see double delete icons in the diff view. When I disable refined-github I only see one.

![afbeelding](https://user-images.githubusercontent.com/511245/43532420-54dbdbb2-95b2-11e8-9ba5-21f15aec3958.png)

**Comment by sindresorhus** [comment]
It seems GitHub added this feature natively, so we should remove our implementation.

They are doing a sprint to add a lot of Refined GitHub features: https://twitter.com/sindresorhus/status/1025060599691001856
