### ISSUE TITLE
[FF] add-filter-comments-by-you - select_dom_default(...)(...) is null

### ISSUE THREAD

**Issue by TheAifam5** [sindresorhus/refined-github#1466]
The feature `add-filter-comments-by-you` does not work, because `.subnav-search-context .js-navigation-item:last-child` selector can not be found. I checked with `document.querySelector(...)`.

Error log:
```
TypeError: "select_dom_default(...)(...) is null"
add_filter_comments_by_you moz-extension://82def1c9-2a9d-44a4-80d4-efe560a3dae2/content.js:3201:5
enableFeature moz-extension://82def1c9-2a9d-44a4-80d4-efe560a3dae2/content.js:1712:13
```

**Comment by bfred-it** [comment]
PR welcome to update the selector
