### ISSUE TITLE
Full-width comment boxes and resizing

### ISSUE THREAD

**Issue by ijstokes** [sindresorhus/refined-github#1468]
I'm entering a GitHub issue.  I need more space.  The comment box can be made longer, but not wider.  I cry.  I look to refined-github for help.  Here I am.

**Comment by sindresorhus** [comment]
Sorry, we're not going to change the layout in fundamental ways and I feel the comment box is already wide enough. 

https://ux.stackexchange.com/questions/108801/what-is-the-best-number-of-paragraph-width-for-readability
