### ISSUE TITLE
Changes of issue titles are hidden

### ISSUE THREAD

**Issue by aspiers** [sindresorhus/refined-github#1471]
If an issue is renamed, the normal GitHub UI displays the change chronologically within the issue's main (timeline) view.  However enabling refined-github will cause that change to vanish.  For example, viewing [this issue](https://github.com/nomacs/nomacs/issues/242#issuecomment-411727658) with refined-github disabled:

![visible](https://user-images.githubusercontent.com/100738/43896907-5269d174-9bd2-11e8-86a6-9cbfa58d4ba0.png)

and then after enabling it and reloading:

![invisible](https://user-images.githubusercontent.com/100738/43896929-5e8f4470-9bd2-11e8-9479-09977a66f283.png)

**Comment by yakov116** [comment]
@aspiers yup its intended #643

**Comment by aspiers** [comment]
Thanks for the quick reply!

Well this is definitely undesirable behaviour for my usage, so IMHO it needs to be configurable at least.  Also is it documented anywhere?  I couldn't find it.

**Comment by jdreesen** [comment]
You can show them again by adding this as _Custom CSS_ in the plugin options:
```CSS
.discussion-item-renamed {
    display: block !important;
}
```

**Comment by aspiers** [comment]
Thanks a lot @jdreesen!  But again this needs to be documented - both the default behaviour and the way to disable it.

**Comment by yakov116** [comment]
@aspiers all features have pr's and most can be configured vis the CSS or JS disable.
Please see https://github.com/sindresorhus/refined-github#customization

**Comment by aspiers** [comment]
@yakov116 I'm sorry but I really don't think it makes sense to expect users to search the whole PR database in order to find out that a feature exists, and then expect them to spend time writing CSS or JS to disable it.  That's way too much work for a good UX.

Also, why should this feature remain undocumented when all (or at least a lot of) other features are documented (fantastically well, I might add - I've rarely seen such great documentation complete with animated gifs!) ?  That seems inconsistent to me.

The fix is trivial here: just adding the feature to the `readme.md` and also how to disable it (this could be put elsewhere and linked to, if it was considered too much bloat for the `readme.md`.  So I'm struggling to see any good reason not to do that.

**Comment by yakov116** [comment]
@aspiers I am only responding since I would like other users to see this.

While I was on the same page as you when I started using this extension (I needed the renames just like you do). After looking around you will see that it is impossible to satisfy everyone and to document every little thing. 

However please read the Readme Selection I have linked.

>We're happy to receive suggestions and contributions, **but be aware this is a highly opinionated project**. There's a very high bar for adding options. Users will always disagree with something. That being said, we're open to discussing things. **If something doesn't make the cut, you can build your customized Refined GitHub locally, rather than installing it from the Chrome Store.**

It does not take much and you can compile yourself customizing the way you would like it

**Comment by aspiers** [comment]
[**@yakov116**](https://github.com/yakov116) commented on [9 Aug 2018, 13:26 BST](https://github.com/sindresorhus/refined-github/issues/1471#issuecomment-411739484 "2018-08-09T12:26:05Z - Replied by Github Reply Comments"):
> While I was on the same page as you when I started using this extension (I needed the renames just like you do). After looking around you will see that it is impossible to satisfy everyone and to document every little thing. (You found the rename however you don't even realize how many other things are hidden. Just take a look at the Css file)

Sure, but I wasn't asking for every single tiny little thing to be documented, just one feature which is a significant change in behaviour.  And you can see from #1473 that my request was so small that the fix is only a single line.

> However please read the Readme Selection I have linked.
> 
> > We're happy to receive suggestions and contributions, **but be aware this is a highly opinionated project**. There's a very high bar for adding options. Users will always disagree with something. That being said, we're open to discussing things. **If something doesn't make the cut, you can build your customized Refined GitHub locally, rather than installing it from the Chrome Store.**
> 
> It does not take much and you can compile yourself customizing the way you would like it

Sorry, but this is somewhat missing the point.  I'm not trying to say that my preference for having title renames visible is better than other people's preference for hiding renames, and that keeping them visible should be the default.  I'm not even saying that there needs to be a button to disable this feature, or any other changes to the code!  I'm simply saying:

1. The feature should be documented, to avoid violating the Principle of Least Surprise.
2. It should also be documented how to disable the feature.

Given that I have already proposed the solution to these in #1473, and given that the solution merely requires adding a single line to `readme.md`, hopefully merging this will be a no-brainer and we can end this discussion here.

**Comment by hkdobrev** [comment]
I think we could add a section for the more opinionated features with a quick link to the PR, way to disable and why it was added. Please send a PR for the title renames to be added in the readme and we could discuss the actual approach of how to structure in the readme based on your PR! Thank you!

**Comment by aspiers** [comment]
@hkdobrev I already did that, as mentioned in my last comment 😜

**Comment by aspiers** [comment]
Hiding changes to issue titles has been reverted in 5a55661e2513f21c3f96ca704c5490743f81e562 so this is no longer needed.
