### ISSUE TITLE
Warn about long `Squash and Merge` commit message

### ISSUE THREAD

**Issue by ark120202** [sindresorhus/refined-github#1475]
When merging pull requests with `Squash and Merge` button it's possible to write too long header message, resulting trauncated line in commit log.

It would be useful to add a warning, similarly to what GitHub shows for file edit interface
![image](https://user-images.githubusercontent.com/11750369/43998082-b8462aa2-9e06-11e8-9876-9bec7e3c93d1.png)

Not sure if the limit should be 50 characters, like github has, or 72, like in [commitlint/config-conventional](https://github.com/marionebl/commitlint/blob/d636811b4537904231c483a05e91aaf96deb7f6e/%40commitlint/config-conventional/index.js#L5) and vscode's `git.inputValidation` setting.

It may be also useful to add a per-line limit to commit body and add countdown, like in vscode with `"git.inputValidation": "always"`:
![image](https://user-images.githubusercontent.com/11750369/43998410-8fd3b9b0-9e0e-11e8-86f0-0f1f9b688a09.png)

**Comment by sindresorhus** [comment]
Makes sense. PR welcome.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by bfred-it** [comment]
I looked into this and we can just steal GitHub's own code (sadly it's not directly loaded in the PR page). Here's a few chunks to get started:

```js
	select('.commit-form-fields').prepend(html);
    delegate(".js-new-blob-commit-summary", 'input', function(t) {
        const n = t.currentTarget;
        n.closest('form').querySelector('.js-too-long-error').classList.toggle("d-none", n.value.length <= 50)
    }),
```
```html
	<p class="text-orange js-too-long-error d-none">
        <svg class="octicon octicon-light-bulb" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M6.5 0C3.48 0 1 2.19 1 5c0 .92.55 2.25 1 3 1.34 2.25 1.78 2.78 2 4v1h5v-1c.22-1.22.66-1.75 2-4 .45-.75 1-2.08 1-3 0-2.81-2.48-5-5.5-5zm3.64 7.48c-.25.44-.47.8-.67 1.11-.86 1.41-1.25 2.06-1.45 3.23-.02.05-.02.11-.02.17H5c0-.06 0-.13-.02-.17-.2-1.17-.59-1.83-1.45-3.23-.2-.31-.42-.67-.67-1.11C2.44 6.78 2 5.65 2 5c0-2.2 2.02-4 4.5-4 1.22 0 2.36.42 3.22 1.19C10.55 2.94 11 3.94 11 5c0 .66-.44 1.78-.86 2.48zM4 14h5c-.23 1.14-1.3 2-2.5 2s-2.27-.86-2.5-2z"></path></svg>
        <strong>ProTip!</strong> Great commit summaries contain fewer than 50 characters. Place extra information in the extended description.
      </p>
```

**Comment by bfred-it** [comment]
I think the solution should be simpler:

- [x] Set the field size to 70 (the actual git limit, afaik)
- [x] Set the font to monospace so you can just see how many characters are left
- [ ] **Limit** the input to 70 via `maxlength` attribute

This is easier to implement. PRs welcome
