### ISSUE TITLE
Feature Request: Sorting Conversations by Top Votes?

### ISSUE THREAD

**Issue by achillesrasquinha** [sindresorhus/refined-github#1476]
I'd like to even have it implemented if this can be open for consideration. How about sorting conversations (on issues and PRs) by the votes they receive? Similar to StackOverflow?

**Comment by notlmn** [comment]
Issues and PRs are not question and answers they are a conversion.

By sorting messages in this conversation you would also change the order in which they happened, which would be total confusion like on who is relying to what.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but this is not something we want for Refined GitHub.
