### ISSUE TITLE
Removing +1 from GitHub Issues

### ISSUE THREAD

**Issue by pavsidhu** [sindresorhus/refined-github#1478]
The number of +1 comments on issues make it difficult to read through issues and get to the information that's important. I'd be up for adding functionality to hide +1 comments from issues.

Let me know if this is a good suggestion and I'll get started.

**Comment by yakov116** [comment]
See #1231 and #1276

**Comment by franklinyu** [comment]
I would also like a bot that

1. Watch my repositories for +1.
2. Delete those comments.
3. Send an email to those users and explain about this.

**Comment by Kocal** [comment]
@franklinyu I don't really think Refined GitHub can do that, you should write your own bot or use webhooks.
