### ISSUE TITLE
Keyboard shortcut for starring a repository

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#1479]
What do you think of a keyboard shortcut to start/unstar the current repository?

- When browsing things you could star multiple things and look them up later.
- When you visit a repo from a link while doing something else, you might want to quickly star it and close the page.

Having a keyboard shortcut would allow you to keep your two hands at the keyboard.

<kbd>s</kbd> is already taken for focusing the search bar.

**It could be <kbd>g</kbd><kbd>s</kbd>**. Thoughts?

What do you think of using it toggle the starred state or should it be just for starring?

**Comment by sindresorhus** [comment]
I guess it could be useful. I would expect it to toggle.

**Comment by sindresorhus** [comment]
*Make sure you also send this feature request to GitHub: support@github.com*
