### ISSUE TITLE
GitHub has implemented the "Unselectable diff markers"

### ISSUE THREAD

**Issue by carusogabriel** [sindresorhus/refined-github#1482]
From `README.md`:

> The `+` and `-` signs in diffs are made unselectable for easier copy-pasting.

https://blog.github.com/changelog/2018-07-31-unselectable-diff-markers/

**Comment by yakov116** [comment]
@carusogabriel good morning america :) 

![image](https://user-images.githubusercontent.com/16872793/44313472-8afe0700-a3d7-11e8-9c30-74145199bbdd.png)
