### ISSUE TITLE
Remove feature to expand/collapse all PR diffs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1486]
Part of https://github.com/sindresorhus/refined-github/blob/7d81d68153c6ce72baaf7eed998a7b0867350ef7/source/features/toggle-all-things-with-alt.js

It was implemented by GitHub: https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/

// @vinkla

**Comment by notlmn** [comment]
Wouldn't removing this also require the file to be renamed back to `expand-collapse-outdated-comments.js`?

**Comment by bfred-it** [comment]
Oh wow they matched Refined GitHub's behavior (with <kbd>alt</kbd>)

**Comment by tonglil** [comment]
Hello @sindresorhus, it seems like removing this has also removed the ability to toggle/collapse all "outdated" comments in a PR page.

<img width="765" alt="image" src="https://user-images.githubusercontent.com/3250776/47928381-0bec7b00-debe-11e8-9ab7-1f348b5b1656.png">

I no longer seem to have the functionality that was implemented in https://github.com/sindresorhus/refined-github/pull/821.

The main [README](https://github.com/sindresorhus/refined-github#previously-part-of-refined-github) says this feature was implemented by papercuts, but I am not reading anything about it.

This GH release note does not mention anything about outdated comments: https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/

And this GH release note says outdated comments will no longer auto-collapse: https://blog.github.com/changelog/2018-10-30-outdated-comments/
