### ISSUE TITLE
Keep link to repository for deleted branch

### ISSUE THREAD

**Issue by franklinyu** [sindresorhus/refined-github#1487]
#1 discussed about link to branches. I delete all my merged branches (because they are available in PR anyway), and the branch link is no longer available, which makes sense. However I would like the “user” part still points to the repository. For example, in #1474 I want `stipsan` to link to <https://github.com/stipsan/refined-github>.

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by hkdobrev** [comment]
The code about that is in `linkify-branch-refs.js`. I think it wouldn't be too hard to add. :)
