### ISSUE TITLE
Add back tooltip for issue/PR participants

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#149]
https://github.com/sindresorhus/refined-github/issues/131#issuecomment-204553489

It can be useful.

**Comment by leocaseiro** [comment]
Perhaps would be nice to add back tooltip for Organizations as well.

**Comment by sindresorhus** [comment]
@leocaseiro Where exactly?

**Comment by leocaseiro** [comment]
User details -> Sidebar
![organizations](https://cloud.githubusercontent.com/assets/940070/14239866/59147512-fa83-11e5-82c3-912444c71086.png)

**Comment by sindresorhus** [comment]
Sure
