### ISSUE TITLE
Support translation in comments

### ISSUE THREAD

**Issue by nikhita** [sindresorhus/refined-github#1493]
We have seen issues in Kubernetes in other languages like Chinese, etc. It would be really cool if we could translate issue and PR comments.

Ref:
- https://github.com/kubernetes/kubernetes/issues/67865
- Thanks to @tamalsaha for suggesting to add to refined-github: https://twitter.com/tsaha/status/1034064256877002752.

**Comment by bfred-it** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/1064

Refer to the discussion there.

**Comment by nikhita** [comment]
Thanks for pointing to the issue, @bfred-it!

Closing this.
