### ISSUE TITLE
Smart Line Count

### ISSUE THREAD

**Issue by natew** [sindresorhus/refined-github#1494]
I see this was rejected a while ago, this would be the single feature I would use refined github for.

Basically have it exclude certain files from line count like `yarn.lock` and `package-lock.json`. Can be configurable.

I'd suggest just adding a count *next* to the current one, so you can see the smart one and the real one.

**Comment by bfred-it** [comment]
It was rejected before because it essentially needs configuration UI, possibly per-repo, so it's more than a "refinement"

This has the same issue.

**Comment by natew** [comment]
Why does it need configuration?

The smart version could be imperfect but still exclude just a pretty
standard regex of files.

It could also show somewhere below everything if some people don’t want to
see it at top.

Would be happy to help a PR.

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but we're going to pass on this. I would recommend you instead try to get GitHub to implement this natively.
