### ISSUE TITLE
[regression?] Auto-linking is not correctly applied to URLs in diffs *even if the link didn't change*

### ISSUE THREAD

**Issue by wearhere** [sindresorhus/refined-github#1499]
The emphasis in the PR title distinguishes this from https://github.com/sindresorhus/refined-github/issues/695 since the problem there appears to be that characters within the URLs were modified, causing a mid-URL color change.

But URLs appear to not be linked even if the URL _as a whole_ was added ([example](https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51)), or even if they're just in comments alongside changes ([example](https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51)—note that I unfolded the top of the diff to get there, not sure if that matters). I'm pretty sure this is a regression.

URLs do appear to be linked if they're in non-PR code blocks ([example](https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)).

**Comment by bfred-it** [comment]
:tada: https://github.com/sindresorhus/refined-github/pull/2066

**Comment by wearhere** [comment]
Woo thanks @bfred-it ! One follow-up issue: https://github.com/sindresorhus/refined-github/issues/2091
