### ISSUE TITLE
Hide/Group the contentless comments

### ISSUE THREAD

**Issue by tngan** [sindresorhus/refined-github#15]
Some comments like `+1` could be removed, or accumulated as one. (a single box showing e.g. +5, +10)

**Comment by sindresorhus** [comment]
Yes! I've been meaning to open an issue about this. Would you be interested in working on this?

**Comment by tngan** [comment]
@sindresorhus of course ! I also welcome others to make their own version.

**Comment by hkdobrev** [comment]
:+1: (as ironic as this may be)

**Comment by SpaceK33z** [comment]
I think it would be helpful to show them in the sidebar, like this:

<img width="418" alt="jeej" src="https://cloud.githubusercontent.com/assets/533616/13123398/3600b75c-d5bc-11e5-99c8-c1d4ffcac326.png">

**Comment by sindresorhus** [comment]
:+1:

**Comment by tngan** [comment]
I do think #17 is doing the same thing. @sindresorhus maybe you can consider to close this.

**Comment by sindresorhus** [comment]
@tngan It will be closed automatically when #17 is merged. (This is an issue, that is a pull request)

**Comment by tngan** [comment]
Oh yes, my mistake.
