### ISSUE TITLE
Copying file should include all linebreaks

### ISSUE THREAD

**Issue by denkristoffer** [sindresorhus/refined-github#1500]
I've noticed that when using the copy button to copy a file with CSS-in-JS into the clipboard, linebreaks are removed between selectors. For example, copying the following file:

```jsx
const Something = styled.div`
  color: red;

  &:focus {
    color: blue;
  }
`
```

Will result in the following being added to the clipboard:

```jsx
const Something = styled.div`
  color: red;
  &:focus {
    color: blue;
  }
`
```

System information

- Chrome 68.0.3440.106
- macOS 10.13.6

**Comment by sindresorhus** [comment]
Can you link to a file in a repo on GitHub that reproduces the behavior?

**Comment by denkristoffer** [comment]
https://github.com/denkristoffer/refined-github-reproduction/blob/master/file.js should show the issue. It copies without the linebreaks between media queries.
