### ISSUE TITLE
Closing "Recent Branches" Toast

### ISSUE THREAD

**Issue by achillesrasquinha** [sindresorhus/refined-github#1503]
It seems like the toast remains and hides the Watch, Star and Fork Buttons. There currently seems to be no way to Close it. I'm guessing this is more of a UI bug.

**Comment by bfred-it** [comment]
Refer to #1109

**Comment by aspiers** [comment]
Ah, you beat me to reporting this by a few seconds ;-)  See also #1506.

**Comment by achillesrasquinha** [comment]
Closing this! Tracking there. I'd suggest for a Close if required.
