### ISSUE TITLE
Faster way to edit comments

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#1504]
If you have to edit comments regularly, it would be nice if e.g. double clicking a comment text would be enough to trigger the actions that currently require clicking `...` and then `Edit`.

**Comment by bfred-it** [comment]
I use double-clicking to select content, so perhaps this has to be limited to blank areas in the header.

Also, you can [edit your last comment by pressing <kbd>up</kbd>](https://github.com/sindresorhus/refined-github/pull/961)

**Comment by janpio** [comment]
Makes sense to only trigger the "Edit" when no text is being selected by this action. Could also be a double click on the command "header", next to "x hours ago".

> Also, you can edit your last comment by pressing [up]

That's a nice feature that I will use in appropriate cases, but especially in long PRs where I have to update the description it will most probably not be my last comment etc - so I think this is still valid.

**Comment by vjpr** [comment]
I think it would be enough to have a dedicated edit button. I think there used to be one...

**Comment by bfred-it** [comment]
Yeah, they moved everything into the dropdown

**Comment by sindresorhus** [comment]
I would rather add a shortcut, like option-clicking the comment.

As a side-note, I actually think it's good that the edit button is less reachable. It forces me to write better comments on the first try, instead of always going back to edit typos afterwards.

**Comment by vjpr** [comment]
> It forces me to write better comments on the first try.

I use it often for fixing typos, adding syntax highlighting, formatting code.

By "better", you probably mean the content right?

**Comment by janpio** [comment]
Unfortunately I can't influence how random people don't format or misformat their code examples - and the edit button is the only way to make those readable. But I get your point.

Shortcut sounds good!

**Comment by bfred-it** [comment]
> I would rather add a shortcut, like option-clicking the comment.

I'd rather restore the edit button next to the `Reaction` button

**Comment by bfred-it** [comment]
https://github.com/sindresorhus/refined-github/pull/1880

**Comment by janpio** [comment]
Thanks @bfred-it, this is **awesome**! ❤️
