### ISSUE TITLE
recently pushed branch masks repo's Unwatch / Star / Fork buttons

### ISSUE THREAD

**Issue by aspiers** [sindresorhus/refined-github#1506]
Recently pushed branches don't appear below the Unwatch / Star / Fork buttons as shown in this image from the `readme.md`:

![](https://user-images.githubusercontent.com/1402241/34099674-20433f60-e41b-11e7-8ca5-7ea23c70ab95.gif)

but instead appear on *top* of those buttons:

![github](https://user-images.githubusercontent.com/100738/45061827-fca7a780-b09d-11e8-97e4-f9eb60e75d33.png)

meaning that it is no longer possible to click to unwatch, star, or fork a repo to another organisation if I recently pushed a branch to my fork.

**Comment by aspiers** [comment]
I tried to disable this feature by adding

    show-recently-pushed-branches
    add-branch-buttons

to `Features to disable`, but it had no effect.  What am I doing wrong?

**Comment by bfred-it** [comment]
`show-recently-pushed-branches` actually just adds that GitHub feature to more pages

`add-branch-buttons` is [this](https://user-images.githubusercontent.com/1402241/36961980-389bd2b0-2080-11e8-8bff-bb8af52e7128.png), IIRC

That feature can't be disabled as it's CSS-only, but check out #1109

> it is no longer possible to click to unwatch, star, or fork a repo to another organisation if I recently pushed a branch to my fork.

Honestly, how often do you want to do that after you pushed a branch to that repo?

**Comment by bfred-it** [comment]
> I notice that you yourself have starred 677 repos, so maybe you are occasionally in a similar situation :-)

Of course I star and watch repos, but not between pushing and opening a PR :D 



> If so, I suggest documenting how to disable it, for exactly the same reasons already mentioned in #1471.

There's no easy way to disable it, that's part of the extension. You'd have to figure out how to undo the CSS and perhaps leave a comment here.

... or the feature can just be changed as suggested in #1109. PR welcome :)

**Comment by aspiers** [comment]
[**@bfred-it**](https://github.com/bfred-it) commented on [5 Sep 2018, 13:01 BST](https://github.com/sindresorhus/refined-github/issues/1506#issuecomment-418704968 "2018-09-05T12:01:24Z - Replied by Github Reply Comments"):
> > I notice that you yourself have starred 677 repos, so maybe you are occasionally in a similar situation :-)
> 
> Of course I star and watch repos, but not between pushing and opening a PR :D

I'm not saying it happens often, but it can happen.  (I guess you are implying that once a PR is created, the recently pushed branch toaster vanishes?)  Anyway, the main point here was that it prevented me from forking, so it's a genuine problem regardless of (un)starring / (un)watching.

> > If so, I suggest documenting how to disable it, for exactly the same reasons already mentioned in [#1471](https://github.com/sindresorhus/refined-github/issues/1471).
> 
> There's no easy way to disable it, that's part of the extension. You'd have to figure out how to undo the CSS and perhaps leave a comment here.

Comment in issue != user-friendly documentation ;-)  But yeah that would be a start.

> ... or the feature can just be changed as suggested in [#1109](https://github.com/sindresorhus/refined-github/issues/1109). PR welcome :)

Yeah, well it seems this is a duplicate of #1503, and to some extent #1109 and #1209 - so I think I can close this.

**Comment by bfred-it** [comment]
Position changed. You can also disable it now: `recently-pushed-branches-enhancements`

![](https://user-images.githubusercontent.com/1402241/56466173-da517700-643f-11e9-8eb5-9b20017fa613.gif)

https://github.com/sindresorhus/refined-github/pull/1909
