### ISSUE TITLE
Add feature to filter issues by excluding labels

### ISSUE THREAD

**Issue by dertieran** [sindresorhus/refined-github#1507]
When I was looking for issues I could takle I wanted to filter all that included the **"help wanted"** but not the **"has PR"** label.

A query for that would look like this:
`label:"help wanted" -label:"has PR"`

The *Label* filter drop-down only allows to filter issues that include one or more labels.

I would love to have the possibility to select (or even toggle) a label to be excluded by pressing some key (maybe `alt` ?).
If this would be implemented there would be the need to indicate that that label in excluded instead of included in the filter drop-down, because right now it is still checked (which is more of a bug on Github's site I already encountered in #1363).

Also see: https://github.com/isaacs/github/issues/65

**Comment by sindresorhus** [comment]
Good idea. PR welcome :)

**Comment by notlmn** [comment]
This would be an awesome feature. I wonder why GH didn't implement this in the first place?

/cc @lukehefson

**Comment by lukehefson** [comment]
> I wonder why GH didn't implement this in the first place?

@notlmn – I have no idea. But I'll dig in and see what I can find! 😊

**Comment by DerTieran** [comment]
Again started to hack something together (see https://github.com/DerTieran/refined-github/tree/exclude-label-filter)

Right now I'm not to happy with it because it replaces the link destination in the last moment.
I thought about some `mouseover` but that got even more hacky :smile:.
I'm happy to get some input or suggestions here.

Then there is still the issue with the ✓, should it be replaced by a different icon then?
I thought about something like ✗, but it could be confusing.

**Comment by bfred-it** [comment]
Currently broken. `alt`+click won't exclude the label but it download the link (default behavior)

**Comment by benedikt-mayer** [comment]
There seems to be a bug in this:
I have an issue with labels "benchmarking", "report" and "simulation":
![image](https://user-images.githubusercontent.com/42207135/89778605-1b2a3f00-db0e-11ea-8d76-21582d5b9f25.png)
If I use -label:"feature-importance" on this as well, the issue disappears:
![image](https://user-images.githubusercontent.com/42207135/89778679-3a28d100-db0e-11ea-8778-394731de878c.png)
even though the issue does not have this label.

Is this intended behaviour?

I have had the same issue with other labels in the -label filters as well.
For "is:closed" the filter works as expected with the same filter:
![image](https://user-images.githubusercontent.com/42207135/89778869-88d66b00-db0e-11ea-95fa-86e5aa25704c.png)

**Comment by fregante** [comment]
This is a native feature now, unrelated to Refined GitHub: https://github.blog/changelog/2019-03-05-exclude-labels-from-search/


That one looks like a bug, perhaps report it to GitHub

**Comment by benedikt-mayer** [comment]
Oh, got the issues mixed up while searching, sorry for the inconvenience! 😄
