### ISSUE TITLE
Autoclick on Show all files new options

### ISSUE THREAD

**Issue by montogeek** [sindresorhus/refined-github#1508]
Hi!

I am using beta GitHub dashboard, just a minute ago I saw they deployed a new change to repositories pages, it is now collapsing file view by default:
![image](https://user-images.githubusercontent.com/1002461/45064182-a09b4e00-b0b2-11e8-9666-d8954e1eed6d.png)

I really dislike it, when I visit projects first time I check is its file structure, I don't want to click more to see file structure.

Would you accept a PR adding a feature which will automatically (when active), click on that button?

**Comment by bfred-it** [comment]
I almost said that the new button is fine, until I saw it and I hated it instantly.

Go ahead 😅
