### ISSUE TITLE
GitHub Projects: Double clicking "Add cards" search results adds issues/PRs

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#1510]
... to either a) the "ToDo" column or b) the left-most column.

This way adding issues or pull requests to to a project board would be much more convenient than drap&dropping each and every one.

**Comment by sindresorhus** [comment]
The problem here is that there's really no "one way" to do project boards, so what you propose here would only work for people that either have a "todo" column or want it in the left-most column, which I think is assuming too much.

**Comment by janpio** [comment]
Valid point.

GitHub offers a "todo automation" setting for a column:
![image](https://user-images.githubusercontent.com/183673/48129712-92bca180-e28a-11e8-805d-86e4fdb3ee5c.png)
This maybe could be considered a standard or at least common.

"Extracting" this information about a column from the CSS classes or content would probably be possible as well, but not trivial I guess (A `span` in the column HTML has a specific content or `aria-label`).

Shame, that drag and dropping is really tiring...

**Comment by sindresorhus** [comment]
Let's see what other people say. I don't personally use the "Projects" feature.

**Comment by bfred-it** [comment]
As previously mentioned, this would require additional configuration to specify **where** to place the selected issue but we don't have any options for any feature and this feature is too specific to get one there.

Also this is kinda possible with `enter` and `left`/`right` arrows (however it does need a click to re-focus the search results)

![r](https://user-images.githubusercontent.com/1402241/51428905-004a5e00-1c3c-11e9-816d-9750b5766546.gif)
