### ISSUE TITLE
Plugin is cutting off characters when reviewing files

### ISSUE THREAD

**Issue by rhanton** [sindresorhus/refined-github#1517]
This is what I see with refined-github turned on:
![screen shot 2018-09-07 at 1 12 16 pm](https://user-images.githubusercontent.com/26878180/45241209-5972b000-b2a0-11e8-8e7e-50b186f46747.png)

Here's what it should look like (refined-github off):
![screen shot 2018-09-07 at 1 12 44 pm](https://user-images.githubusercontent.com/26878180/45241223-6a232600-b2a0-11e8-81d9-f46aae321187.png)

**Comment by Phrynobatrachus** [comment]
this should be fixed in the latest release, try updating.

see #1455 #1456 #1457

**Comment by rhanton** [comment]
@Phrynobatrachus Awesome, that worked great. Weird that it hadn't auto-updated for me in Firefox 62, but it was a major version behind.
