### ISSUE TITLE
Add keyboard shortcuts for previous/next issue navigation

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#152]
From https://github.com/isaacs/github/issues/366.

**Comment by sindresorhus** [comment]
@paulmolluzzo @hkdobrev @DrewML Would you use this?

**Comment by DrewML** [comment]
@sindresorhus I totally would. I started looking at this the other week, though, and it's a pretty hard problem to solve, depending on how you do it.

Maybe we should discuss the ideal setup? If we just increment IDs, it'll switch between closed and open items, which would be less than ideal.

**Comment by paulmolluzzo** [comment]
@sindresorhus I want to say I would, but what would the shortcut be? `h` and `l` to match left/right like vim? Or `j` and `k` because it's numerically ordered? Or `n` and `p` for "next" and "previous"? Chances are I'm likely to forget the shortcuts in the long run.

**Comment by sindresorhus** [comment]
`j` and `k` are already global shortcuts on GitHub:

```
j	Move selection down
k	Move selection up
```

How about left/right arrow keys?

> Chances are I'm likely to forget the shortcuts in the long run.

We could maybe add our shortcuts to the GitHub shortcut thing: <kbd>Shift</kbd>+<kbd>?</kbd>

**Comment by paulmolluzzo** [comment]
> j and k are already global shortcuts on GitHub:

> How about left/right arrow keys?

I don't even know what those other shortcuts do, but we can't collide with them. Arrows are OK.

> We could maybe add our shortcuts to the GitHub shortcut thing: `Shift+?`

This is a good idea, and we should probably put any other shortcuts we made here too.

**Comment by revolunet** [comment]
a basic implem : https://github.com/sindresorhus/refined-github/pull/299

**Comment by bfred-it** [comment]
Closing for the same reason as (essentially based on it + keyboard shortcuts) https://github.com/sindresorhus/refined-github/issues/343#issuecomment-370390780
