### ISSUE TITLE
Comment cancellation confirmation feature no longer needed?

### ISSUE THREAD

**Issue by sharkykh** [sindresorhus/refined-github#1521]
Hello,

Seems like GitHub has incorporated the [`add-confirmation-to-comment-cancellation.js`](https://github.com/sindresorhus/refined-github/blob/bebc684d32a5c68647fac57d1251e0da0c627f3b/source/features/add-confirmation-to-comment-cancellation.js) feature natively.

As can be seen on this GIF, the alert is shown twice.
When I disable the feature in `refined-github`'s extension settings, it's only shown once.

This may need more confirmation, because I'm not sure as to the full scope of the feature.

<details>
<summary>GIF</summary>

![2018-09-11_21-39-02](https://user-images.githubusercontent.com/10238474/45380836-57944e00-b60c-11e8-9297-3892d817dd13.gif)
</details>

**Comment by notlmn** [comment]
@lukehefson Is this a feature that GH accidentally added while adding resolve conversation feature?
