### ISSUE TITLE
Add links to github URIs in go files 

### ISSUE THREAD

**Issue by mjarkk** [sindresorhus/refined-github#1528]
It would be great to have clickable Github links in go files  

In go files there is section for imports where you need to type the full Github link to a file / repo  
A usual go file:  
![screenshot](https://i.imgur.com/BloYxQT.png)

**Comment by bfred-it** [comment]
All files are linkified, but to avoid issues only full URLs are (i.e. it has to include http:// too)

**Comment by sindresorhus** [comment]
You want https://github.com/OctoLinker/OctoLinker
