### ISSUE TITLE
Show "Trending" in the top menu

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#153]
From https://github.com/isaacs/github/issues/245.

Currently the link to your starred repos is hidden in the avatar dropdown. Might be nice to add it to the top menu. Not entirely sure about this, so use "Reactions" to vote whether people want this or not.

<img width="743" alt="napkin 04-04-16 3 47 15 pm" src="https://cloud.githubusercontent.com/assets/170270/14242908/a06c21f0-fa7c-11e5-975c-a6b62539e8c3.png">

**Comment by sindresorhus** [comment]
// @necolas

**Comment by paulmolluzzo** [comment]
This isn't a lot of work, so why not?

**Comment by sindresorhus** [comment]
@paulmolluzzo It's not about the amount of work, rather, is this something you would use? Is it worth adding more stuff to the UI for this?

**Comment by paulmolluzzo** [comment]
@sindresorhus I don't often go to my starred repos, but having the link would be helpful. For others it might be more valuable.

**Comment by unluisco** [comment]
the same for Explore?

**Comment by sindresorhus** [comment]
@unluisco What tab do you want in Explore? Trending?

**Comment by unluisco** [comment]
@sindresorhus yes, always trending

**Comment by kevva** [comment]
Personally, I rarely go to my starred repos either (besides wanting to revisit something I forgot but I know starred). Or at least, not enough for having it in my top menu. I could see the value in having Explore though.

**Comment by sindresorhus** [comment]
Ok, so maybe we add `Trending` instead? You can easily go to your Stars from there.

**Comment by sindresorhus** [comment]
Alright. PR welcome for adding `Trending`.

**Comment by unluisco** [comment]
What happened with Trending? 😢
