### ISSUE TITLE
Regressions with Github Enterprise

### ISSUE THREAD

**Issue by ashrayjain** [sindresorhus/refined-github#1530]
Removal of functionality that public Github has added but has yet to be added to Github Enterprise can cause regressions for some users.

For example, the functionality provided here
https://blog.github.com/changelog/2018-08-17-collapse-all-diffs-in-a-pull-request-at-once/
which was removed with https://github.com/sindresorhus/refined-github/pull/1524 doesn't yet exist in the enterprise version. 

Not sure if this is feasible but maybe for things that get added to public GH, we should disable them by default with an option for users to opt in, instead of removing them entirely?

**Comment by sindresorhus** [comment]
We try not to break GitHub Enterprise and we accept Enterprise-only bug fixes, but we’re not going to hold back doing non-breaking changes like this. If you need more control, you can clone the repo and use the extension as a local extension. That way you can control when to update.
