### ISSUE TITLE
Hide useless comments in Linux

### ISSUE THREAD

**Issue by salmanulfarzy** [sindresorhus/refined-github#1536]
Reactions as comments are not hidden in Linux, Since emojis are png images from GH. Might be better to document that ? 
 
**System**: Linux/Firefox 62.0/Chromium 69

Expanded view from https://github.com/hayaku/hayaku/issues/303

![reactions](https://user-images.githubusercontent.com/10276208/45668071-1c78aa00-bb39-11e8-9eab-08cacf54dd65.png)

Related: #1526

**Comment by salmanulfarzy** [comment]
`textContent` is empty string for emojis in Linux.

**Comment by bfred-it** [comment]
PR welcome to detect the emoji element directly instead of via regex (which would only test for non-emoji comments)

**Comment by rzpio** [comment]
It can also be checked for an empty textContent (see my fix in PR #1538). Useless comments only with emojis will not be displayed anymore.

**Comment by rzpio** [comment]
That's right, I missed that, thank you. I'll have a look at it again later.
