### ISSUE TITLE
Do not hide PR reviews verdict (hide-useless-comments)

### ISSUE THREAD

**Issue by anthony-robin** [sindresorhus/refined-github#1543]
It seems the new `hide-useless-comments` feature is too gourmand as it also hides the PR review verdict completely when it has only a reaction comment.

<img width="785" alt="capture d ecran 2018-09-20 a 18 18 12" src="https://user-images.githubusercontent.com/5428510/45832380-0407bb80-bd02-11e8-80b0-75ef137d0361.png">

<hr>

<img width="775" alt="capture d ecran 2018-09-20 a 18 18 20" src="https://user-images.githubusercontent.com/5428510/45832381-04a05200-bd02-11e8-8183-83a3aeb69e5b.png">

Should the PR verdict still be visible by only hiding the comment below ?

Thanks !

**Comment by busches** [comment]
I would say yes, as what I care about is the `X approved these changes`. We'll see what others think.

**Comment by tandrewnichols** [comment]
We use the thumbs up for review where I work (and almost never do an _actual_ review), so now our thumbs are hidden. I get the goal of this feature, but I think it's too heavy-handed. Limiting it to issues only could be a start. I'd also think limiting it to public repositories could cut down on false negatives. You're not going to have the kind of "me too" spam in a private repo that you'd have in a public one.

**Comment by hkdobrev** [comment]
An emoji in an approval is always a nice touch!

**Comment by bfred-it** [comment]
Nice catch! Yes, PR reviews should definitely be excluded. The logic should have done that already (they are by team members and therefore never hidden) but the "Collaborator" tag doesn't appear there.

Anyway if you can't think of many occasions where PRs get dozens of useless comments, it might be easier to just drop the "isPR" filter.

https://github.com/sindresorhus/refined-github/blob/0a1ee62f83b21b113096fe576b23793dca693cb5/source/features/hide-useless-comments.js#L6

**Comment by yakov116** [comment]
@bfred-it what about excluding private repo's all together

**Comment by bfred-it** [comment]
On private repos everyone is a collaborator, so technically they're already excluded.

**Comment by tandrewnichols** [comment]
Well, then I think that isn't working because the thumb was hidden on a pull request in a private repo on which both I and the commenter are collaborators.

**Comment by bfred-it** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/1543#issuecomment-423378536

It’s not working in reviews because there’s no visible “collaborator” tag

**Comment by hkdobrev** [comment]
Pull request reviews are green/red if the reviewer has write access and gray if they don't. We can use that.

The problem of spamming with these short comments is definitely reduced with the emoji reactions, but I think when it's happening, PRs are no exception.

**Comment by yakov116** [comment]
@tandrewnichols 
https://github.com/sindresorhus/refined-github/blob/0a1ee62f83b21b113096fe576b23793dca693cb5/source/features/hide-useless-comments.js#L17-L21

This will exclude anyone that has a badge. Do you have some kind of example where it is?

**Comment by tandrewnichols** [comment]
It's in a private repo, but here's a screen shot:

<img width="798" alt="screen shot 7" src="https://user-images.githubusercontent.com/2755760/45892857-6ced4300-bd97-11e8-9148-e16797f72633.png">

The thumbs up comes from a user listed under the "Contributors" tab. I don't know what you mean in the previous comment by "has a badge."

**Comment by tandrewnichols** [comment]
Oh, you mean like this:

<img width="791" alt="screen shot 8" src="https://user-images.githubusercontent.com/2755760/45893056-12081b80-bd98-11e8-98f3-ecb994a69c73.png">

or this:

<img width="787" alt="screen shot 9" src="https://user-images.githubusercontent.com/2755760/45893061-16cccf80-bd98-11e8-8d83-12b2cef6d4c7.png">

**Comment by tandrewnichols** [comment]
Looks like #1544 would resolve this anyway?

**Comment by bfred-it** [comment]
Yep that badge. If nayrudin is a collaborator but does not have a badge it means that they’re not public members of the organization. If GitHub does not mark it as a collaborator there’s not much we can do.

**Comment by tandrewnichols** [comment]
I mean, you could ignore private repositories cause _everyone_ is a collaborator. Right?

**Comment by bfred-it** [comment]
You’re not wrong 😅

PR welcome to add that check

**Comment by bfred-it** [comment]
If I think about it… that 👍 is actually pretty useless. The review is already positive what does 👍 add? 😃 Maybe the selector should be updated to remove just the comment and not the review.
