### ISSUE TITLE
Firefox: Build status won't show when there is more than one item.

### ISSUE THREAD

**Issue by mohsenkhanpour** [sindresorhus/refined-github#1545]
Hello,
When using Firefox and the repository has only one build check it shows fine:
![image](https://user-images.githubusercontent.com/28626829/45950474-cf9b4480-c00c-11e8-8be2-4ff8041b57ee.png)
However when the repository has multiple CI frameworks attached to it, it fails to load the menu:
![image](https://user-images.githubusercontent.com/28626829/45950507-f35e8a80-c00c-11e8-8c13-7722df91f060.png)
I don't know if it helps or not but as soon as I put the cursor on the build status icon an error logs into the console:
![2018-09-24_15-21-43](https://user-images.githubusercontent.com/28626829/45950749-f0b06500-c00d-11e8-82b0-56e5f0d7b82d.gif)

And I have this problem only on Firefox, Chrome shows the build statuses just fine:
![image](https://user-images.githubusercontent.com/28626829/45950883-556bbf80-c00e-11e8-889b-6d3849c9ff20.png)

I have had this issue for a while, but I thought some other extension may be causing the problem, yesterday I disabled all my extensions and had only Refined Github enabled, but it just didn't work, so I thought I'd let you know.

**Comment by bfred-it** [comment]
They might have changed some code to make that appear

**Comment by bfred-it** [comment]
Cannot reproduce anymore on Firefox 63

<img width="758" alt="screenshot 2018-11-15 at 00 34 16" src="https://user-images.githubusercontent.com/1402241/48500760-33542800-e86e-11e8-8791-35a118bc30ef.png">
