### ISSUE TITLE
Feature request: Integrate notifier-for-github functionality.

### ISSUE THREAD

**Issue by timdorr** [sindresorhus/refined-github#1546]
You know what's cooler than 1 extension? 2 extensions! 

Wait...no, it's not!

I've got both refined-github and [notifier-for-github](https://github.com/sindresorhus/notifier-for-github) installed. Since Chrome made extension popup icons mandatory (but hideable), it's been weird having two icons that both work on GitHub showing up in my browser. Seems like a redundant bit of redundant functionality that is redundant.

'Twould be cool if refined-github made use of its icon badge to show the number of unread notifications. 'Twould also be cool if it showed notifications as `chrome.notifications` items on the desktop.

**Comment by sindresorhus** [comment]
That's unfortunately outside the scope of Refined GitHub.
