### ISSUE TITLE
Coverage and Copy position race condition while loading in background

### ISSUE THREAD

**Issue by SuperSandro2000** [sindresorhus/refined-github#1548]
This is the expected result:
![](https://i.imgur.com/PVz2AzK.png)
and this happens when the tab loads in the background:
![](https://i.imgur.com/HQ9CfDS.png)

**Comment by bfred-it** [comment]
It probably depends on element-ready’s requestAnimationFrame blocking everything from running until the tab is visible. It’s an unwanted side effect but I doubt it can be fixed, especially given the low gravity of the issue.

**Comment by SuperSandro2000** [comment]
Derp. I thought the coverage button is native but it comes from codecov extension

**Comment by sindresorhus** [comment]
Closing as it's not much we can do about this.
