### ISSUE TITLE
Do not populate name  for bots

### ISSUE THREAD

**Issue by electron0zero** [sindresorhus/refined-github#1549]
![image](https://user-images.githubusercontent.com/9503187/46302706-6c3e8300-c5c7-11e8-9cfc-7b7b3005dd10.png)

We are using todo bot [https://github.com/apps/todo](https://github.com/apps/todo) but Refined GitHub populated it's name as user todo [https://github.com/todo](https://github.com/todo)

**Comment by notlmn** [comment]
@electron0zero Can you also provide a link to the issue/PR with this issue!?

**Comment by electron0zero** [comment]
See this issue: https://github.com/nteract/nteract/issues/3381 or any other issue from [this search result](https://github.com/search?q=label%3A%22todo+%3Aspiral_notepad%3A%22)

**Comment by shroudedcode** [comment]
I've already fixed this in #959, but for some reason, GitHub has changed the `href` attribute of the profile link to use the full URL. What was `/apps/todo` before, is now `https://github.com/apps/todo`, so [my check using `.startsWith('/apps/')`](https://github.com/sindresorhus/refined-github/pull/959/files#diff-85b9e89075b70da2dd7ba1513051fb8bR39) is no longer working.

**Comment by shroudedcode** [comment]
@bushes Yes (although it's now a CSS selector, but the idea is the same). Working on a PR right now.
