### ISSUE TITLE
Disable escape keyboard shortcut

### ISSUE THREAD

**Issue by pzuraq** [sindresorhus/refined-github#1553]
A recent update seems to have added the ability to press escape to discard a comment. This is one of my pet peeves as I use a keyboard overlay to have escape be the same key as a modifier key (see [this article on the basics of the setup](http://stevelosh.com/blog/2012/10/a-modern-space-cadet/)) and as such I often hit escape by mistake and lose a small essay. In general, being able to configure keyboard shortcuts would be 👍, but especially being able to turn off that particular one (or any shortcuts that could cause content to be lost).

**Comment by busches** [comment]
You can disable this feature `add-keyboard-shortcuts-to-comment-fields` to remove the escape keyboard shortcut that is added by the feature. I don't think we want to go down the road of allowing shortcuts to be customized, as that goes against the principles of the project.

**Comment by pzuraq** [comment]
Works for me, thank you!
