### ISSUE TITLE
Squash+Merge title = PR title doesn't handle updated PR titles

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#1555]
Feature #276, `Force "squash and merge" title to be the pull request title`, doesn't take into account that a user might update the PR title before using the squash+merge button. They have to reload the page first to get the new PR title into the input field, which is unexpected.

**Comment by busches** [comment]
I wasn't able to recreate this. I opened a PR in two windows, changed the PR title in window two, saw the title update in the first, and hit `Squash and Merge` and it had the correct title. 

The title is chosen when you hit `Squash and Merge`, so it won't work if you were to hit that first, then change the title. The only other cause I can think of is the title change not syncing over, which would be on GitHub's end. If you have a way to recreate this, please list the steps.

**Comment by janpio** [comment]
1. Create a PR
2. Open PR
3. Use "squash and merge" to see how it fills the commit title with the current PR title
4. Click "Cancel"
5. Edit the PR title
6. Use "squash and merge" to see how it still fills the commit title with the old PR title, the new PR title is placed into the commit message:

![image](https://user-images.githubusercontent.com/183673/46403781-bb89ce00-c703-11e8-9ae5-1c844004b468.png)

Interesting enough this does not happen consistently. If it started placing the correct PR title after and edit, it will keep doing so. Reloading seems to trigger the correct behavior all the time, but it sometimes also just works starting with the second edit. Strange.

**Comment by bfred-it** [comment]
I don't see the issue and honestly I don't know why it would be there since the field is updated every time you click "Squash and merge"

![r](https://user-images.githubusercontent.com/1402241/49338986-f1dcbe80-f65c-11e8-9d65-4c9df1b12f80.gif)

**Comment by notlmn** [comment]
According to @janpio, the field doesn't automatically update when it is open and title is changed. You have to click cancel and squash button again to update the tile value inside the field.

#1651 allows you to do that without having to close and reopen the squash confirmation options.

**Comment by bfred-it** [comment]
Step 4 is “Cancel” so it doesn’t stay open

**Comment by janpio** [comment]
I just reproduced it by using the exact steps I posted above (including the cancel).
(I am using FF 63.0.3 on Windows 10, addon version is 18.12.1.1752)
I'll see if I can quickly produce a gif...

**Comment by janpio** [comment]
Here you go:
![repro](https://user-images.githubusercontent.com/183673/49343123-4899c680-f664-11e8-8d56-4562de7a1dbb.gif)

When creating a new PR I can repro it every time.

**Comment by bfred-it** [comment]
Lol I see a variety of funny business in your screencast.

1. Technically GitHub already uses the correct title when there's more than one commit; this feature only prevents GitHub from using the commit's message when there's only one (i.e. we don't know if it's working at all because the first title you see is provided by GitHub)
2. [fix-squash-and-merge-message](https://github.com/sindresorhus/refined-github/blob/master/source/features/fix-squash-and-merge-message.js) should copy the first comment's message to the commit message; in your screencast it doesn't happen (separate bug?)
3. After you change the title, the new title actually appears _as the commit message_ instead of the commit message. 🤷‍♂️

This shows that the bug is probably deeper than `observeEl` and these two features should probably be reviewed and merged

**Comment by janpio** [comment]
Re 1: So a better repro would be with a PR that has only 1 commit?
Re 2: Maybe because it is empty?
Re 3: Yep, I missed that in the initial report but mentioned it in my repro steps comment.

I have a strange warning in the console, but this seems to be coming from GitHub itself:

`` 
Failed to update content <div id="partial-discussion-header" class="gh-header js-details-container Details js-socket-channel js-updatable-content js-pull-header-details pull request js-transitionable Details--on" data-channel="pull_request:235277971" data-url="/janpio/ionic-epubjs/pull/56/show_partial?partial=pull_requests%2Ftitle" data-pull-is-open="true" data-gid="MDExOlB1bGxSZXF1ZXN0MjM1Mjc3OTcx"> Error: "element had interactions"
	e https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:137968
	v https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:5032
	_invoke https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:4799
	t https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:5208
	r https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:7338
	r https://assets-cdn.github.com/assets/frameworks-7fcedd2a70cd3dde438cbad4c2d08128.js:1:7432
 updatable-content.js:41:14
```
![image](https://user-images.githubusercontent.com/183673/49343672-2a38c880-f66e-11e8-9fb7-768d3611a6b5.png)

Might be related though.

**Comment by bfred-it** [comment]
1. Yes, although our code shouldn’t make a distinction between the two, it’s just that in this case it doesn’t clearly show if it works at least once. 
2. Our code doesn’t make a distinction between full and empty. It should either match the emptiness or throw an error

That console error is GitHub’s

**Comment by janpio** [comment]
Ok, let me know if I can do anything else to help debug this.

**Comment by bfred-it** [comment]
Closing in favor of https://github.com/sindresorhus/refined-github/issues/1790

**Comment by asvishnyakov** [comment]
And now in 2025 this issue appear again
