### ISSUE TITLE
Enforce PR reviews based on @Mentions

### ISSUE THREAD

**Issue by codef0rmer** [sindresorhus/refined-github#156]
Hey Sindre,

I've recently published a chrome extension to enforce PR reviews based on @Mentions in Github. I would like to merge it here to reach wider audience.

**PRampage:** https://github.com/codef0rmer/PRampage

Do you think its a good Idea?

**Comment by sindresorhus** [comment]
Nice! I don't see really the point in merging it in here though. It's useful even for people not using `refined-github`.

**Comment by hkdobrev** [comment]
Hi @codef0rmer, you might find https://lgtm.co/ useful which can restrict the merge with the help of GitHub protected branches and required status checks.

**Comment by codef0rmer** [comment]
@sindresorhus Makes sense. Thanks.
