### ISSUE TITLE
Color blind diff improvement

### ISSUE THREAD

**Issue by Munter** [sindresorhus/refined-github#1560]
The out of the box Github diff viewer is quite horrible to interact with as a red/green colorblind person.

Suggestions for improvements:
- Different colors. This might be hard because of different color blindness types, and also non-colorblind people have heavy associations with the red/green diff.
- Added contrast. Maybe there could be a subtle repeating background pattern the differs between the added and deleted categories. I'm told that color blind people have an improved contrast perception, so even a very subtle pattern might help here
- Different borders?

**Comment by maxcell** [comment]
@Munter This is such an excellent problem. A potential consideration is subscribing the CSS that determines additions and subtractions to a color palette set that could help people distinguish. Maybe where a user could select a different rendering of the same content. That would avoid all users having to be impacted but providing the same opportunity.

So things that would be addition/deletion could be reassigned.

**Comment by NamelessCoder** [comment]
One suggestion could be to add a high-contrast monochrome theme; for example an added line could be gray background with black text and a removed line the inverse.

**Comment by bfred-it** [comment]
I get the issue but any changes to such a base feature will likely receive a [huge](https://fortunedotcom.files.wordpress.com/2015/08/gettyimages-481219104.jpg) pushback unless done by GitHub themselves.

I suggest picking a color scheme that works for you and setting it in Stylus or Refined GitHub's option via CSS **and** sending the suggestion to GitHub.

**Comment by bcawrse** [comment]
Any way the lines themselves could be altered? Theres only a handful of useful combinations I can think of; jagged like lightning, curvy, dashed, dotted, alternating thin-thick, jagged left side curvy right, etc. If color is the problem, can the problem be removed entirely?

**Comment by bfred-it** [comment]
I’m closing this for the reasons I stated earlier. This is already possible through CSS for who is interested

**Comment by vitarb** [comment]
While it's possible to change colors through CSS plugins, it would be nice to have a theme that works out of the box. The one mentioned above, for example, only works on top of the light theme, and if you are on the "dark side", you are out of luck.
