### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by whatsadebugger** [sindresorhus/refined-github#1564]
Would it be easy to add a feature to save the previous reviewers on a PR. The current way is to type each individual in and it's really bad.

**Comment by busches** [comment]
Can you elaborate? GitHub has features in place to assist this already, such as [https://help.github.com/articles/about-codeowners/](CODEOWNERS file) and they auto suggest reviewers based on who changed the file(s) recently.

**Comment by whatsadebugger** [comment]
Something like code owners would have us maintaining a file and i might have different reviewers based on the pr. If it's too much for extra work I don't want to burden you. I'll see if I can come up with a solution.
