### ISSUE TITLE
The two last releases look like mistakes

### ISSUE THREAD

**Issue by LM450N** [sindresorhus/refined-github#157]
The two last releases look like mistakes/jokes, isn't it ?

<img width="363" alt="capture d ecran 2016-04-05 a 09 10 08" src="https://cloud.githubusercontent.com/assets/2325091/14273979/dc5140a0-fb0e-11e5-9b61-2900ec47bacd.png">

**Comment by DrewML** [comment]
Yikes - didn't realize that GitHub considered any tag on any non-default branch a release. Removed - thanks!
