### ISSUE TITLE
Show issue number in "Possibly related issues" panel

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/refined-github#1572]
When the "Possibly related issues" panel shows up, it'd be helpful to have the issue numbers on-hand instead of resorting to hovering over them.

**Comment by yakov116** [comment]
Would just be adding `#{issue.Number}` to the following line
https://github.com/sindresorhus/refined-github/blob/ad9900b427e7d1b5a4d061e7b95ac6a1663aa239/source/features/display-issue-suggestions.js#L57

**Comment by Qix-** [comment]
@sindresorhus not sure if you're participating but might be a good hacktoberfest issue.

**Comment by sindresorhus** [comment]
@Qix- Hacktoberfest this year works for any issue, so labeling one doesn't help.
