### ISSUE TITLE
Use static code analysis by Code Climate (free for open source projects)

### ISSUE THREAD

**Issue by sgabler** [sindresorhus/refined-github#1573]
I've seen this in multiple repositories: https://codeclimate.com/oss/

Would this or similar tools be interesting for this project? It'd be free

Example report for a project that uses Code Climate:
https://codeclimate.com/github/gitlabhq/gitlabhq

**Comment by sindresorhus** [comment]
Thanks for the suggestion, but I'm going to pass.
