### ISSUE TITLE
Compare branch highlights all branches

### ISSUE THREAD

**Issue by SuperSandro2000** [sindresorhus/refined-github#1574]
I think this picture describes the issue better than I can.
![](https://i.imgur.com/zDnGcZ8.png)
Link to the repo of the screen https://github.com/GioBonvi/GoogleContactsEventsNotifier/compare

**Comment by yakov116** [comment]
@SuperSandro2000 link?

**Comment by yakov116** [comment]
@SuperSandro2000 Not happening to me

![image](https://user-images.githubusercontent.com/16872793/46633284-3e06f900-cb1b-11e8-93c7-248e180ff98c.png)

**Comment by SuperSandro2000** [comment]
I did some research and it seems to be the fault of this extension https://chrome.google.com/webstore/detail/github-compare-tags/pjkolicadkdcfgjjoopdpleenckeajkk
