### ISSUE TITLE
Add Download button to file view

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#158]
The [file view](https://github.com/sindresorhus/ava/blob/master/cli.js) currently has a `Raw` button, but it only shows the file. Would be useful to have a button to directly download the file.

<img width="721" alt="napkin 06-04-16 5 24 41 pm" src="https://cloud.githubusercontent.com/assets/170270/14313567/78d3ccaa-fc1c-11e5-9357-240b20f065bb.png">

Thoughts?

**Comment by hkdobrev** [comment]
I think copying via #62 is a better option for text files. GitHub already provides a download link for binary or big files.

**Comment by bfred-it** [comment]
Also: `alt+click` downloads any link in Chrome and [Firefox + config](https://support.mozilla.org/en-US/questions/929585)

You can `alt+click` the Raw button to download the file.
