### ISSUE TITLE
Browser extension permissions: what are they used for?

### ISSUE THREAD

**Issue by StephanBijzitter** [sindresorhus/refined-github#1584]
I've been using the extension for many weeks now and it's absolutely amazing.

At the time of writing, the extension looks like this in Opera's interface:
![screen shot 2018-10-16 at 13 00 34](https://user-images.githubusercontent.com/1649903/47012018-90f83600-d143-11e8-8c21-a4ea2fbd7f24.png)

The common permissions/settings "Hide from toolbar" and "Allow in private mode" are very clear and are the same for all browser extensions.

"Collect errors" is not very clear. I don't mind collecting all the errors I encounter, but what happens to them? If it only collects them and doesn't automatically submit them to the author of the extension, I'd like to keep it off as I'll likely never use it. However if it does automatically submit error details to the author of the extension, I'd love to enable this and help out the author this way.

"Allow access to file URLs" is another permission that is not clear to me. Would Refined Github benefit from this permission? What would it be used for?

**Comment by StephanBijzitter** [comment]
I do realise that, but (for example) without access to file URLs, what would Refined Github be missing out on? I'm really just wondering if toggling any of these checkboxes make any difference at all.

**Comment by bfred-it** [comment]
- you can hide it from the toolbar
- you can probably allow it in the private mode, no information is collected and we only store some cache
- no idea what Collect errors is
- file URLs are not used
