### ISSUE TITLE
Quick way to mark read entire notification groups

### ISSUE THREAD

**Issue by OvermindDL1** [sindresorhus/refined-github#1585]
In the notification list on the left side of all the notification URL's, this list:
![image](https://user-images.githubusercontent.com/401605/47032820-85e7da80-d130-11e8-9249-34a7579648fe.png)
If possible then it would be really nice to have a red X on the right side of the number or so that can quick-mark that entire grouping as read, same as opening up that section then clicking on the Mark All As Read button then choosing to mark all as read in the group, but as a single action.

**Comment by sindresorhus** [comment]
As you said, you can already click it and click "Mark All". I don't really see the need to optimize this action with one click. It's not a common use-case to need to clear out everything without even looking at it. Sounds like you should just unsubscribe from those repos.

**Comment by OvermindDL1** [comment]
> As you said, you can already click it and click "Mark All". I don't really see the need to optimize this action with one click. It's not a common use-case to need to clear out everything without even looking at it. Sounds like you should just unsubscribe from those repos.

Mark All only marks what's on that page (50 items), not everything else without going through more clicks.  It is indeed unusual but during my work week I clear out the bulk without looking but on weekends I go through whatever appears in more detail.  Wish there was a better workstyle but it's what I've settled on that works best to minimize my weekly distractions...  ^.^;
