### ISSUE TITLE
Unselect selected lines on files or commits

### ISSUE THREAD

**Issue by anthony-robin** [sindresorhus/refined-github#1590]
Currently, when we click on a line to highlight it, there is no possibility to unselect it unless we select another one or by removing manually the anchor added to the URL.

Maybe that could be a nice feature to add to refined github ?

### Example for a file view

<img width="867" alt="capture d ecran 2018-10-17 a 11 06 46" src="https://user-images.githubusercontent.com/5428510/47076129-4e476400-d1fe-11e8-91c2-d5ee6eac2b7b.png">

### Example with a commit view

<img width="1255" alt="capture d ecran 2018-10-17 a 11 13 16" src="https://user-images.githubusercontent.com/5428510/47076239-8e0e4b80-d1fe-11e8-895f-c4951a9234ef.png">

Thank you !

**Comment by tanmayrajani** [comment]
When I accidentally select a line like that, I usually hit <kbd>Alt</kbd> + <kbd>←</kbd> i.e. go back to previous page. It might not be what we're looking for but worth mentioning.

**Comment by sindresorhus** [comment]
This would be very useful indeed. I've been bothered by this behavior too. PR welcome :)

Please also suggest the improvement to GitHub: https://github.com/contact

**Comment by bfred-it** [comment]
Feature added, press <kbd>esc</kbd>
