### ISSUE TITLE
New suggestion feature is hidden by refined-github

### ISSUE THREAD

**Issue by tristanbes** [sindresorhus/refined-github#1591]
Hello,

Announced during the Github Universe, the `Suggestion` feature **does not appear** when we have refined github activated.

![_article__fichiers_pour_page_article_et_slider_article_interne_by_clareo_ _pull_request__5022_ _yproximite_yprox](https://user-images.githubusercontent.com/346010/47077662-c1060e80-d201-11e8-8a90-b4e8268487dc.png)

**Comment by anthony-robin** [comment]
Duplicated of #1586

**Comment by timdorr** [comment]
In the meantime, you can add this to your custom CSS:
```css
.toolbar-group:first-child { display: inline; }
```

**Comment by tristanbes** [comment]
Thanks.

**Comment by Phrynobatrachus** [comment]
Builds publish nightly afaik so it should be fixed if you update. :)
