### ISSUE TITLE
Show conflict marker in PR list

### ISSUE THREAD

**Issue by Turbo87** [sindresorhus/refined-github#1593]
We already show the CI and review status in the PR overview. It would be nice to also have a marker that shows if a PR is currently blocked due to unresolved merge conflicts.

**Comment by bfred-it** [comment]
You want to show a marker on this list, correct?

https://github.com/sindresorhus/refined-github/pulls

> We already show the CI and review status in the PR overview

FYI GitHub does that natively, not us.

This can be done via [joint](https://github.com/sindresorhus/refined-github/issues/438#issuecomment-357871647) GraphQL API call: https://developer.github.com/v4/object/pullrequest/#mergeable

**Comment by Turbo87** [comment]
> You want to show a marker on this list, correct?
> 
> [sindresorhus/refined-github/pulls](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)

yes, correct

> FYI GitHub does that natively, not us.

I see, it's sometimes hard to figure out what GitHub improved and what comes from the extension 😉

**Comment by sindresorhus** [comment]
Sounds useful. PR welcome :)

**Comment by felixfbecker** [comment]
I'd love this. Dependency upgrade PRs often conflict after merging one of them, and it's so annoying to go through the list just to see that many are conflicting and are awaiting an automated rebase.

**Comment by fregante** [comment]
It looks like this is possible https://developer.github.com/v4/object/pullrequest/#mergeable

**Comment by Esemesek** [comment]
I'd like to implement this feature. Already worked a bit on this and I think I should be able to create a PR sometime this week.

**Comment by fregante** [comment]
Thanks for the PR @Esemesek

Suggestions welcome for the marker style. It should match GitHub’s style. Perhaps it should just be an icon from Octicons
