### ISSUE TITLE
Add "View Raw" button next to all View buttons for files

### ISSUE THREAD

**Issue by ahmetb** [sindresorhus/refined-github#1595]
Especially in pul request "Files changed" view, countless times I copied the link to "View" button and passed to curl, only to get a HTML page, because it wasn't the link to the raw file.

> ![image](https://user-images.githubusercontent.com/159209/47270559-5404b880-d522-11e8-9e9d-4e1985fcd3c0.png)

Would it be cool to have a "View Raw" button via this extension?

**Comment by sindresorhus** [comment]
Shouldn't it be `Copy raw URL` then?

**Comment by bfred-it** [comment]
Why are you `curl`ing PR files instead of `git`ting them?

**Comment by ahmetb** [comment]
I think sometimes you just need to. Like `command <(curl https://...)` or to `wget`.

**Comment by sindresorhus** [comment]
@ahmetb Alright. A `View raw` button sounds useful to me. PR welcome :)

**Comment by AlessandroFC15** [comment]
Hi, @sindresorhus,

I've recently discovered this project and I really enjoyed it.

I would really like to start contributing. Can I tackle this issue? 

Also I have a question regarding the implementation. Should `View raw` button have `target="_blank"` or it isn't necessary?

**Comment by ahmetb** [comment]
@AlessandroFC15 please take it over, I won't be able to send a patch anytime soon. IMO it's not necessary to have a target=_blank, most people know how to open links in a new tab.

**Comment by AlessandroFC15** [comment]
@ahmetb Alright then, thank you very much, appreciate the input.

**Comment by brettz9** [comment]
I filed #1668 to be able to link where the headers are properly set like https://raw.githack.com , not the raw URLs on Github which is what I understood this issue to be about...

**Comment by bfred-it** [comment]
@brettz9 my bad, I meant to link you to https://github.com/sindresorhus/refined-github/issues/1096
