### ISSUE TITLE
More friendly "Changes requested" state in PRs

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1602]
See: https://twitter.com/ashfurrow/status/1056944193669599233

We could change the color and icon to something more friendly, while still keeping it obvious that it's not approved.

**Comment by ashfurrow** [comment]
My personal favourite approach would be an orange “pending” badge, like when CI is still running. That conveys the “request changes” idea far more accurately than a red x, which is more “reject changes” imo.

**Comment by xavhan** [comment]
What about somekind of a turning back arrow suggesting the idea of a feedback instead of a refusal?

**Comment by AustinPaquette** [comment]
Could use the `diff` octicon?

https://octicons.github.com/icon/diff/

**Comment by manojchandrashekar** [comment]
Not sure if it can be implemented, but I like the idea of specifying if the "changes requested" was in fact,

* just feedback
* good-to-have, or
* must-have 

Anyway, it would be great to have the icon changed to a yellow alert ⚠ at least.

**Comment by bfred-it** [comment]
They did it. The color is still red, but it's no longer a ❌ 

<img width="368" alt="new changes requested icon" src="https://user-images.githubusercontent.com/1402241/51254887-9da35900-19d4-11e9-8d77-278c579950c6.png">

**Comment by sindresorhus** [comment]
I think we should still change the color.

**Comment by vanniktech** [comment]
How about orange?

**Comment by connorbrathwaite** [comment]
> I think we should still change the color.

```js
for (const reviewChangesSvg of select.all('.octicon-request-changes')) {
  reviewChangesSvg.classList.remove('text-red');
  reviewChangesSvg.classList.add('text-pending');
}
```

where

```css
.text-pending {
  color: #b08800!important;
}
```

<img width="786" alt="screen shot 2019-02-20 at 05 28 16" src="https://user-images.githubusercontent.com/13842856/53085204-5b3bd300-34d0-11e9-808c-e4be10062cc8.png"> ?

**Comment by sindresorhus** [comment]
The red circle and text too.

**Comment by nesl247** [comment]
I would not use the pending color IMO. It blends in too much with the icon on the left, and also blends in too much with other status checks that are in progress.

I'm in favor of keeping it as it is, as the red actually makes it stand out that changes are requested, and it's a blocker for the PR to be merged. Any blockers on a PR are red, therefore it makes sense to keep the color the same IMO.

**Comment by bfred-it** [comment]
> I would not use the pending color IMO

👍 

Also this feature should be CSS-only, it's just easier in every way.

**Comment by fregante** [comment]
We're going with yellow in #2611. Comment there if you disagree.
