### ISSUE TITLE
Double line breaks when pasting copied file

### ISSUE THREAD

**Issue by greggb** [sindresorhus/refined-github#1603]
Using the copy button on a file adds double spacing between lines. Appears to be an issue after https://github.com/sindresorhus/refined-github/pull/1559

Repro case:
- Use the `copy` button on this file - https://github.com/greggb/refined-gh-spacing-repro/blob/master/test.css

- Paste into an editor (I've done this here: https://codepen.io/anon/pen/XxwZwL)

Expect:
```
body {
  color: rebeccapurple;
}
```

Actual:
```
body {

    color: rebeccapurple;

}
```

**Comment by bfred-it** [comment]
Recent possibly-related PR: https://github.com/sindresorhus/refined-github/issues/1500

**Comment by sindresorhus** [comment]
// @denkristoffer
