### ISSUE TITLE
Show / filter subscribed issues

### ISSUE THREAD

**Issue by aspiers** [sindresorhus/refined-github#1604]
It would be great if refined-github could allow users to:

1. list issues they've subscribed to, either globally or within any given project (similar to what's described in https://github.com/isaacs/github/issues/283 and https://github.com/isaacs/github/issues/196)
2. when viewing a list of issues not filtered in the above way, to show an icon to the right of each subscribed issue denoting that they've subscribed to it (next to where the comments icon can appear if there are comments)

See also [marpo60/github-subscribed](https://github.com/marpo60/github-subscribed), although that is slightly different in that it is a Chrome extension which keeps track of your subscriptions to "threads" (I guess this means issues) and provides an extra view within https://github.com/notifications which shows notifications from subscribed "threads".

**Comment by sindresorhus** [comment]
Why do you need to see issues you're described to? What's your use-case / workflow?

1. For the per repo case, we could add a new item to the "Filter" dropdown on the issue page. Globally, we could add a new filter button to the top here: https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Asindresorhus+archived%3Afalse+sort%3Aupdated-desc We already add the "Yours" and "Commented" buttons there. Thought there is a problem of horizontal space.

2. I'm more reluctant to do this. Issue items already have a lot of noise and icons. The bar for adding more is very high.

**Comment by aspiers** [comment]
Hi @sindresorhus, thanks a lot for the reply!

[**@sindresorhus**](https://github.com/sindresorhus) commented on [7 Nov 2018, 11:14 GMT](https://github.com/sindresorhus/refined-github/issues/1604#issuecomment-436590329 "2018-11-07T11:14:31Z - Replied by Github Reply Comments"):
> Why do you need to see issues you're [sub]scribed to? What's your use-case / workflow?

A few use cases off the top of my head:

- Re-discovering an issue I'm interested in when I can't remember enough details to figure out exactly what to search for
- Getting a feel for how much activity is happening on the issues I care about
- Getting a single link in order to share issues of interest to me with other people
- When viewing a list of issue search results, avoiding the need to click on a particular interesting-looking issue in order to subscribe to it, because I can see that I already subscribed in the past (and later forgot that I did)

I'm sure there are others.

> 1.  For the per repo case, we could add a new item to the "Filter" dropdown on the issue page. Globally, we could add a new filter button to the top here: [github.com/issues?q=is%3Aissue+is%3Aopen+author%3Asindresorhus+archived%3Afalse+sort%3Aupdated-desc](https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3Asindresorhus+archived%3Afalse+sort%3Aupdated-desc) We already add the "Yours" and "Commented" buttons there. Thought there is a problem of horizontal space.

Agreed, that would be a perfect place.  The horizontal space issue could maybe be solved with a >> expanding button - click to reveal buttons which don't fit in the existing space.  Or just float the buttons so that they wrap onto the line below, and then slightly shrink their height.

> 2.  I'm more reluctant to do this. Issue items already have a lot of noise and icons.

They do?  Currently it looks very clean and empty to me:

![subscribed](https://user-images.githubusercontent.com/100738/48130052-3f932080-e283-11e8-8b69-dc79c6159458.png)

Seems like plenty of space for a "subscribed" icon next to the comments icon.

**Comment by sindresorhus** [comment]
> The horizontal space issue could maybe be solved with a >> expanding button

That wouldn't be my first choice. Would like to explore some other alternatives first.

> They do? Currently it looks very clean and empty to me:

I didn't say only the right side. I meant the issue item as a whole.

**Comment by sindresorhus** [comment]
> For the per repo case, we could add a new item to the "Filter" dropdown on the issue page. 

This is a no-brainer and could be added right now. PR welcome. The other items needs more discussion.

**Comment by aspiers** [comment]
[**@sindresorhus**](https://github.com/sindresorhus) commented on [7 Nov 2018, 12:07 GMT](https://github.com/sindresorhus/refined-github/issues/1604#issuecomment-436602411 "2018-11-07T12:07:09Z - Replied by Github Reply Comments"):
> > The horizontal space issue could maybe be solved with a &gt;&gt; expanding button
> 
> That wouldn't be my first choice. Would like to explore some other alternatives first.

Sure, just thinking out aloud ;-)

> > They do? Currently it looks very clean and empty to me:
> 
> I didn't say only the right side. I meant the issue item as a whole.

Ah right.  I was imagining the existing subscribe/unsubscribe icon pair which GitHub already uses appearing on the right, next to the comment icon (if present).  I think that would be a pretty low-noise approach.

**Comment by dalDevelo** [comment]
I hope it's ok too add my voice here? I personally would like to have a global list of my subscribed issues visible from my profile, possibly as its own button, added between 'stars' and 'followers', or as a sub selection of 'following', with a selector for 'people' or 'issues'. Whilst this implementation would not solve @aspiers 4th use case above, I feel this would be the best place for an overall list my my subs.

**Comment by bfred-it** [comment]
I see a few problems with this:

- we can't really see what the user is subscribed to and showing a what-I-saw list feels like a lie. A user can become subscribed with just a mention and you can mark a conversation as read without visiting the thread, or you can unsubscribe via email.
- there's already an extension that does this

But especially...

- if I watch a repo, I'm automatically subscribed to its dozens-or-thousands issues, whatcha-gonna do then?

Which probably explains why GitHub doesn't offer an API.

**Comment by aspiers** [comment]
[**@bfred-it**](https://github.com/bfred-it) commented on [null](https://github.com/sindresorhus/refined-github/issues/1604#issuecomment-455791766 "2019-01-19T15:56:13Z - Replied by Github Reply Comments"):
> I see a few problems with this:
> 
> *   we can't really see what the user is subscribed to

Are you referring to the fact that whilst [the API lets you retrieve a list of all issues you're subscribed to globally](https://developer.github.com/v3/issues/#parameters), it [doesn't provide a per-repo equivalent](https://developer.github.com/v3/issues/#list-issues-for-a-repository)?

> and showing a what-I-saw list feels like a lie.

I'm not exactly sure what you mean by "what-I-saw" but I suspect I would agree with you anyway ;-)

> A user can become subscribed with just a mention and you can mark a conversation as read without visiting the thread, or you can unsubscribe via email.

Yes, although I'm not quite following your point here, sorry; how are those facts relevant in this context?  I'm not sure why it would matter to the implementation of this feature *how* a user subscribes to or unsubscribes from an issue; AFAICS it would only matter whether they *are* currently subscribed.

> *   there's already an extension that does this

Oh, that's interesting!  Any chance of a link?!

> But especially...
> 
> *   if I watch a repo, I'm automatically subscribed to its dozens-or-thousands issues, whatcha-gonna do then?

This is easy to answer:

1. Show the proposed new "subscribed" icon for every issue, as it would be displayed if the user had subscribed to each one manually, but with a visual and interactive difference to make it clear that the subscription was inherited from a repo-level subscription.  For example, the icon could be a different colour (such as a lighter grey), and a mouse-over could show a tool tip explaining that the subscription was inherited.
2. Since (IIUC) GitHub lets you override the repo-level subscription by unsubscribing from individual issues, hide the icon in these cases.

> Which probably explains why GitHub doesn't offer an API.

Well, as mentioned above, it does offer an API - but just globally rather than per-repo.

**Comment by bfred-it** [comment]
My comment was based off the fact that:

- The extension `marpo60/github-subscribed` you suggested offer that functionality already
- and it does so by _"When visiting a subscribed thread it will automatically start tracking that thread._", i.e. only "what-I-saw"

So I thought that there was no other way, i.e. "no API"

---

Per-repo seems only possible by querying all the pages of my subscriptions and then filtering the array (240**KB** each page)

---

Reopening to maybe **add a paginated view with the subscribed threads** in the order GitHub returns them at

```js
https://api.github.com/user/issues?filter=subscribed
```

GraphQL doesn't seem to offer the same query, sadly. If you find it, please use that one because v3 is filled with crap: dozens of URLs for each issue.

**Comment by bfred-it** [comment]
Boom: https://github.com/notifications/subscriptions

**Comment by aspiers** [comment]
[**@bfred-it**](https://github.com/bfred-it) commented on [March 12, 2019 12:35 AM](https://github.com/sindresorhus/refined-github/issues/1604#issuecomment-471797129 "2019-03-12T00:35:28Z - Replied by Github Reply Comments"):
> Boom: [github.com/notifications/subscriptions](https://github.com/notifications/subscriptions)

Well, this only caters for the global case; it doesn't offer convenient access within each repo.  But I was one of GitHub's guinea pigs for the user testing of this new feature, and I told them they should add that too, so fingers crossed it will come later.

**Comment by bfred-it** [comment]
> Per-repo seems only possible by querying all the pages of my subscriptions and then filtering the array (240**KB** each page)

Because of this 👆 we can't implement it per-repo either way so this closes it for us. I'm happy to hear they contacted you to test it out though!

**Comment by bfred-it** [comment]
> it doesn't offer convenient access within each repo

Not entirely convenient, but totally possible 👍 

<img width="689" alt="Screenshot 2019-03-12 at 09 01 48" src="https://user-images.githubusercontent.com/1402241/54167614-99139200-44a5-11e9-83fe-50a3572e8d61.png">

https://twitter.com/github/status/1105194498362040320

**Comment by aspiers** [comment]
Exactly, couldn't we have a button in each repo which redirects to this?
