### ISSUE TITLE
Add functionality to collapse all outdated comments when needed!

### ISSUE THREAD

**Issue by vishnun** [sindresorhus/refined-github#1605]
Looks like a recent change where outdated comments have been showing up as expanded by default and I can't find a way to collapse them and only see the new comments. Please add the flexibility to see what is new and hide outdated comments.

**Comment by bfred-it** [comment]
Alt+click

The feature was in Refined GitHub already but then GitHub added it natively.

**Comment by salmanulfarzy** [comment]
Seems like they are now available only if the comment was resolved, but the previous behavior was to toggle if outdated. Outdated but unresolved comments don't have any ways to collapse now.

https://blog.github.com/changelog/2018-10-30-outdated-comments/

> if they are outdated as a result of code changes and they will no longer auto-collapse.

**Comment by bfred-it** [comment]
I see what you mean, apparently GitHub completely removed collapsible comments. Technically they did away with the concept of "outdated comment" so RGH would have to figure out which comments _are_ outdated.

Probably not feasible the same way, but it could provide a way to collapse whole reviews... but actually that's already there: "Mark conversation as resolved"

**Comment by salmanulfarzy** [comment]
Current GitHub solution feels the correct way to collapse comments, But just that now it requires interaction from author or collaborators to mark it as resolved. Resolved comments does have `alt`+`click` to toggle all on `Show resolved`.

Previously change in files relevant to review comments were collapsed even if they were not resolved. May be that's why they reverted it.

**Comment by sindresorhus** [comment]
GitHub's new behavior makes sense as "outdated" was often incorrect and hid important discussions. I don't think adding this feature makes sense now.

**Comment by w0rp** [comment]
Please add an option to hide all outdated comments when looking at a pull request. I've gotten used to not seeing outdated comments when using GitHub every day for a year, and now I find it difficult to view only comments which match current lines of code. I've been trained to view the site one way, and now the site has gone another way.

**Comment by bfred-it** [comment]
Make sure to suggest the correct way to GitHub: https://github.com/contact

**Comment by mingsheng88** [comment]
We employ the use of CI code quality tools that spit comments directly in Github - thus its actually a lot of clutter. Thus +1 for making it configurable.

(I know that alternative is to remove that CI, and hook a scanner before commit / before push, but that's not something we prioritise at the moment)

**Comment by bfred-it** [comment]
GitHub still offers a `Resolve conversation` button that will collapse each comment and will do so _for everyone._ Not automatic, but technically doable.

If you feel strongly about this, I wrote a userscript to automate it for you:

```js
for (const label of document.querySelectorAll('.file [title="Label: Outdated"]')) {
	label.closest('.file').querySelector('[data-disable-with="Resolving conversation…"]').click();
}
```
