### ISSUE TITLE
No collapse button on repository's browser file list

### ISSUE THREAD

**Issue by Glennmen** [sindresorhus/refined-github#1608]
I recently installed this extension and was scrolling through the README to see what features it has.

However I noticed that the `Collapse or expand a repository's browser file list.` action wasn't there, I also tried searching for it but couldn't find any issues about it or any PRs.

This is the feature I am talking about: https://user-images.githubusercontent.com/1402241/35480123-68b9af1a-043a-11e8-8934-3ead3cff8328.gif

Any info about this? Should it be removed from the README?

**Comment by sindresorhus** [comment]
I think this is the feature source: https://github.com/sindresorhus/refined-github/blob/master/source/features/add-toggle-files-button.js

It probably broke at some point because of GitHub changes.

**Comment by Glennmen** [comment]
I think I found the issue, will clone the repo and do some testing later after work.
