### ISSUE TITLE
Adding acutal emoji to useless content check?

### ISSUE THREAD

**Issue by hzoo** [sindresorhus/refined-github#161]
When you type `:+ TAB` in github now it replaces the message with the actual 👍 emoji rather than `:+1:`, so maybe we should add that to the content check (unless we remove it)

**Comment by hkdobrev** [comment]
Thanks for opening the issue @hzoo!

GitHub recently changed the emoji autocomplete in comments so you actually see the emoji visually before posting or going to the preview.

You can participate in the discussion whether to remove the feature of thumbs up/down in the sidebar in #74.

**Comment by hzoo** [comment]
Did my description get removed or did I do that?

**Comment by hkdobrev** [comment]
@hzoo I think you've deleted it, I haven't touched it. I closed the page for a bit and when got back to the page the description was gone 😱

**Comment by hzoo** [comment]
@hkdobrev ok I'm not crazy?
> We've fixed a defect that caused some issue and PR bodies to be overwritten when an assignee, label, or milestone was added.
https://twitter.com/githubstatus/status/717783352611368961

**Comment by hkdobrev** [comment]
OK, so it was me when added the labels. 😭

**Comment by paulmolluzzo** [comment]
I would freeze improvements on thumbsup stuff with #159 open.
