### ISSUE TITLE
Remove "related issues" feature

### ISSUE THREAD

**Issue by nesl247** [sindresorhus/refined-github#1610]
See https://blog.github.com/changelog/2018-11-05-related-issues/

**Comment by sindresorhus** [comment]
Yes, we should remove our feature for this. PR welcome.

Here's how it should be done: https://github.com/sindresorhus/refined-github/commit/ba34c09eaac05d54d5ff837edd4fbf504378a9a3

**Comment by yakov116** [comment]
Its still in beta @sindresorhus  can we leave it until it leaves beta?

**Comment by sindresorhus** [comment]
I think it’s fine to just remove it now. I tried the feature, and even though it’s marked as beta, it feels pretty polished.

**Comment by revolter** [comment]
It looks to me like GitHub actually removed this feature.

**Comment by ivirshup** [comment]
@revolter, it has definitely been removed 😢 (via [github staff on the support community site](https://github.community/t/resurrect-similar-issues/124135)). It was recommended that we open feature request support tickets if we'd like to see it come back.
