### ISSUE TITLE
Multiple PR templates

### ISSUE THREAD

**Issue by FWirtz** [sindresorhus/refined-github#1621]
So there is the option to [have multiple pr templates in GitHub](https://blog.github.com/2018-01-25-multiple-issue-and-pull-request-templates/), which I think is pretty cool.
However, to make actual use of this feature, I need to manually select the template via tampering with the url (i.e. appending `&template=first-template.md`).

This is how GitLab does it:
![How GitLab does it](https://user-images.githubusercontent.com/6052785/48432028-30244380-e76b-11e8-8d73-49b598422dc0.png)
([Source](https://docs.gitlab.com/ee/user/project/description_templates.html#using-the-templates))

So here is my feature request: I, as a user, want to select my pr template via a nice dropdown, and not via manually tampering with the url in a complicated way.

---

Do you guys see my point? Do you feel like this is something that would be a nice feature for this project?
Does anybody have an idea on how the options of the dropdown could be populated best? Simply search for the `PULL_REQUEST_TEMPLATE/` folder (maybe in `.github/`) and iterate over all entries?

Looking forward to your input!

PS Keep up the good work, I <3 this project so much!!! 👏 

---

*edit.* shared this with GH Support as well
*edit. 2* removed the "and issue templates" as @sindresorhus [pointed out](https://github.com/sindresorhus/refined-github/issues/1621#issuecomment-439688682) this already exists

**Comment by sindresorhus** [comment]
I don't understand this request. If you create multiple templates, GitHub already presents it nicely. Example: https://github.com/babel/babel/issues/new/choose

**Comment by FWirtz** [comment]
@sindresorhus wow I didn't even know they did this! 😮😍 
I only checked for PRs as I currently need that - couldn't find a similar UI there or am I just blind again?

**Comment by sindresorhus** [comment]
I haven't tried multiple PR templates. I never had the need for that. But if even if GitHub doesn't show any nice UI for it now, I don't think it's something we'll want to do. They will probably implement it soon and our work will be wasted. Better to contact GitHub about it: support@github.com

**Comment by FWirtz** [comment]
just got a reply from GH Support: PR template ui is on their agenda. 😊👏👍

**Comment by Ornias1993** [comment]
> just got a reply from GH Support: PR template ui is on their agenda. 😊👏👍

And now, almost 2 years later, it's still not even close to being available.
@sindresorhus You seriesuly closed this too easily.

**Comment by omerose** [comment]
Let's reopen this. It would help tremendously in our mono-repo team. Since we all need slightly 
different PR templates, and the URL solution is not robust.

@sindresorhus @flowirtz

**Comment by fregante** [comment]
This doesn't belong to Refined GitHub:

- it affects everyone (useless API calls) only to be useful to some
- it requires specific files existing on each repo
- the repo users need to know about the feature and be willing to use it
- the whole Refined GitHub itself would **have to** be installed just to enforce this workflow.

If your team needs something like this, you'd have to make an extension, or ask me to make one for your team.

**Comment by Betlista** [comment]
I do not understand why issue templates are ok, but PR templates no, I see those two to be very the same...

**Comment by fregante** [comment]
I'd love to have this feature too, but we need to wait for GitHub to add it natively.
