### ISSUE TITLE
Shortcuts help improvements no longer working

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1622]
GitHub updated their code

<img width="877" alt="screenshot 2018-11-14 at 14 20 26" src="https://user-images.githubusercontent.com/1402241/48466427-74215200-e818-11e8-9f51-aaeb3f38389f.png">

It was like this

![image](https://user-images.githubusercontent.com/1402241/48466541-ca8e9080-e818-11e8-9f61-dad1527d37af.png)

**Comment by dertieran** [comment]
Looked into it the main problem is that the shortcut dialog doesn't use the `#facebox` anymore.
When opening the dialog a `details` element is added to the body with a `details-dialog.kb-shortcut-dialog`.

Right now I see two possibilities
1. Add an observer to the body to detect `details > details-dialog.kb-shortcut-dialog`
2. Add a key listener to detect the shortcut shortcut (`?`), works with `keypress` and `keyup`

Both then would need to add a observer to wait for the spinner to be removed.
**I'm not to sure which of these options should be used.**

The second change is the structure of the dialog.
Only the shortcuts relevant to the current page are added to the page and the `View all keyboard shortcuts` button now point so the [help](https://help.github.com/articles/using-keyboard-shortcuts/).

So should the `refined-github` shortcuts still be added to the groups or should there be a separat "Refined Github Shortcut" group?

FYI: I play around with 2. and the old behavior at the moment.
