### ISSUE TITLE
Show the commit message for a diff

### ISSUE THREAD

**Issue by phraemer** [sindresorhus/refined-github#1625]
When reviewing a PR, often I'd love to know what the commit message was for a particular diff section.

![image](https://user-images.githubusercontent.com/143631/48537582-4be63180-e8b2-11e8-843a-2a206952c0b1.png)

Would be amazing to have something like that.

**Comment by bfred-it** [comment]
I think you're talking about diffs in a PR. It's a rather complex feature given that we'd have to rebuild a blame-like view for all the files in a PR.

**Comment by bfred-it** [comment]
Too big. It's best to suggest it to GitHub or create a separate "Blame view for PRs" extension or ask for one here: https://github.com/sindresorhus/module-requests
