### ISSUE TITLE
A way to quickly copy permalink of image files from GH explorer

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#1631]
When you are previewing a file in the GitHub viewer (like [this](https://github.com/sindresorhus/refined-github/blob/master/media/promo.png)), there is no way to copy a permalink to that image file.

![image](https://user-images.githubusercontent.com/37769974/48782257-d3450200-ed03-11e8-92a4-f2ad624bfea8.png)

------------------

One way is to go to the latest commit of that file, the find the file in that commit and then copy the URL of that button-like anchor tag.

![image](https://user-images.githubusercontent.com/37769974/48782589-87df2380-ed04-11e8-8d7f-7983b8067c51.png)

-------------------

Instead, we could add a button (or any other interactive element) to quickly copy permalink to that image (I had to spend almost 5 minutes to find the permalink to that image, even when I'm enough familiar with GH's UI)

**Comment by bfred-it** [comment]
<kbd>y</kbd> works perfectly

**Comment by bfred-it** [comment]
<kbd>y</kbd>

**Comment by notlmn** [comment]
Oh, I missed that one.

I'm very bad at remembering shortcuts for GitHub!
