### ISSUE TITLE
Better autocomplete of new collaborators

### ISSUE THREAD

**Issue by aymericbouzy** [sindresorhus/refined-github#1632]
When adding collaborators to a repository, I sometimes forget what is the username of the person I'm trying to add. I've even met people who don't remember their GitHub username. However I think we should be able to find some indications of who I could probably want to add:
* people I've added to other repositories I own
* people that have opened an issue / PR / commented in another repository I own

What do you think?

**Comment by bfred-it** [comment]
I think this is something that happens too rarely to justify the effort required to implement this (complex API call, autocomplete UI injection)

It's best to suggest it to GitHub or... copy-paste it before navigating into the settings.
