### ISSUE TITLE
FR: delay post (like gmail undo)

### ISSUE THREAD

**Issue by refack** [sindresorhus/refined-github#1633]
I have an itchy trigger finger and very often I only proof-read my posts after I click submit.
An amazing feature would be to add a "delay-actual-submit" feature that gives you X seconds to undo the submit (a la gmail).
A simpler option is to hook the submit button to the preview tab (`button.btn-link.tabnav-tab.preview-tab.js-preview-tab`), so that clicking it once will only switch the display to the "preview" tab, and only a second click will actually post (a la Wikipedia).

**Comment by sindresorhus** [comment]
In contrast to Gmail, comments can be edited after posting. I honestly think it would be better to just get into the habit of proofreading comments before posting instead of adding a feature that works around a bad habit (I have this problem too).

**Comment by bfred-it** [comment]
I’d also be concerned about data loss. Gmail handles the timer server-side but we don’t, so if internet goes off or the submission fails (when you’re not looking), there’s a chance you’ll lose the comment. 

Also this means you have to wait longer before you can close the tab and make sure it’s actuallt submitted. Not a great UX. 

As Sindre says, proofreading + edit button make this feature less useful.
