### ISSUE TITLE
Notifications that are manually "Marked as Unread" gets removed when pressing "Mark all {repository} notifications as read" in another (unrelated) repository

### ISSUE THREAD

**Issue by GGAlanSmithee** [sindresorhus/refined-github#1634]
As the issue title says, notifications that are manually "Marked as Unread" gets removed when pressing "Mark all {repository} notifications as read" in another (unrelated) repository.

To reproduce:

1. #### Manually mark an issue as unread

![image](https://user-images.githubusercontent.com/11805103/48930766-ee299900-eef2-11e8-9950-c6dc834d9170.png)

____

2. #### There are now two notifications, one from repo 1 (actually unread), one from repo 2 (manually marked as unread)

![image](https://user-images.githubusercontent.com/11805103/48892798-27083600-ee3f-11e8-8d4d-29d6baa174a9.png)

____

3. #### Clicking "mark all {repo} notifications as read" on repo 1
![image](https://user-images.githubusercontent.com/11805103/48892905-65055a00-ee3f-11e8-8f0e-81664c446fb1.png)

____

4. #### All repo 1 notifications are marked as read
![image](https://user-images.githubusercontent.com/11805103/48892949-7cdcde00-ee3f-11e8-81c8-f5f1260f3e3f.png)

____

5. #### After refreshing the page, the notifications from repo 2 is also marked as read, but should not be
![image](https://user-images.githubusercontent.com/11805103/48893028-a6960500-ee3f-11e8-8b33-d46234bcc938.png)

____

#### Expected results

Urelated (in another repo) notifications should not be affected 

____

#### Specs

**Browser**: Chrome, Version 70.0.3538.102 
**Refined Github Extension**: Version 18.11.21.1745

**Comment by notlmn** [comment]
Can verify that this is a bug from the RGH side, and the culprit being these lines https://github.com/sindresorhus/refined-github/blob/561af934726cf981743a53417051b306f920cb06/source/features/mark-unread.js#L370-L372

---------------------

The above lines remove all marked-as-unread-notifications, regardless of the notifications it was supposed to clear. The above code should been something like

``` js
  delegate('form[action="/notifications/mark"] button', 'click', ({delegateTarget}) => {
    const group = delegateTarget.closest('.boxed-group');
    const repo = select('.notifications-repo-link', group).textContent;
    storage.set(storage.get().filter(notif => notif.repository != repo));
 })
```
