### ISSUE TITLE
Search results type for PR

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#1635]
Repository [search results](https://github.com/sindresorhus/refined-github/search?q=jerone) are currently categorized in 4 types: Code, Commits, Issues and Wikis (if available).
Where issues is a combination of issues and PR. My suggestion is that we make another type for all PR's and separate them out of the issues type.

**Comment by bfred-it** [comment]
These are the URLs to make it happen:

https://github.com/sindresorhus/refined-github/search?q=diff+is%3Aissue&type=Issues
https://github.com/sindresorhus/refined-github/search?q=diff+is%3Apr&type=Issues

**Comment by jerone** [comment]
I understand this is under discussion, but as a learning project I build this feature: https://github.com/sindresorhus/refined-github/compare/master...jerone:features/jvw-1635-search-results-filter
If interested I can create an PR...
