### ISSUE TITLE
Display whether a repo is archived on SoftwareHeritage.org

### ISSUE THREAD

**Issue by katrinleinweber** [sindresorhus/refined-github#1643]
They are an industry-sponsored academic infrastructure project to "collect and preserve software in source code form" and are doing the former from [several major code hosting platforms](https://archive.softwareheritage.org/) already. See their archive of [`sindresorhus/refined-github`](https://archive.softwareheritage.org/browse/search/?q=sindresorhus%2Frefined-github) for example.

In order to protect the scientific record against programmers removing their code from one place, scientists can for example cite the SwH-copy of a software, rather than the original repo/project URL.

`refined-github` could help this, by adding a status icon like for "[build/CI status](https://github.com/sindresorhus/refined-github#more-info-at-a-glance)" to indicate whether SwH already archived a repo. This could possibly be done through [their API's](https://archive.softwareheritage.org/api/) `visit` datapoint.

cc @SoftwareHeritage.

**Comment by sindresorhus** [comment]
Feel free to archive this repo to any service you want, including SoftwareHeritage, but it's not something we're interested in taking part in.

**Comment by katrinleinweber** [comment]
Yeah, it's probably something they need to build into a browser extension of their own. The feedback was worth the post ;-)
