### ISSUE TITLE
Request repo archival to SoftwareHeritage.org

### ISSUE THREAD

**Issue by katrinleinweber** [sindresorhus/refined-github#1644]
Related to (& dependent on) #1643.

As a researcher browsing a GitHub repo that is not archived by SwH yet, I would like to get a 1-click option to "[[r]equest the saving of a software origin into the archive](https://archive.softwareheritage.org/api/1/origin/save/)" so that I can cite a long-term preserved copy of the code.

Since their "visit" might take a while, some kind of monitoring & notification by refined-github could additionally be convenient. However, the MVP would be to open the SwH tab in the background ;-)

**Comment by sindresorhus** [comment]
Same answer as https://github.com/sindresorhus/refined-github/issues/1643#issuecomment-442859536
