### ISSUE TITLE
Obsolete tag shown as latest revision

### ISSUE THREAD

**Issue by luzpaz** [sindresorhus/refined-github#1654]
Please see github.com/PointCloudLibrary/pcl/issues/2644

![image](https://user-images.githubusercontent.com/4140247/49446031-3d988080-f7a1-11e8-9adf-755f07b8c9fd.png)

The latest tag should be `1.9.0`

**Comment by sindresorhus** [comment]
In that case, we could maybe use the most recent tag?

**Comment by bfred-it** [comment]
Programmatically speaking, in what case? Do we run a regex first? What if ALL tags are something weird like `custom-1.4.0` and the repo won’t have a “latest tag”

**Comment by sindresorhus** [comment]
> If a repo has non-regular version tags it just tries to sort them alphabetically

Instead of sorting alphabetically in this case, we could sort by tag date.

**Comment by bfred-it** [comment]
PR sent
