### ISSUE TITLE
RecentBranches

### ISSUE THREAD

**Issue by denji** [sindresorhus/refined-github#1661]
UX button bug, blocks buttons `Start` & `Fork`.
source/features/show-recently-pushed-branches-on-more-page

### Init

![ublock](https://user-images.githubusercontent.com/3759759/49714307-0fa9b500-fc55-11e8-9a83-af4e1a173819.png)

#### Start "Refined GitHub"

![bugux](https://user-images.githubusercontent.com/3759759/49714276-fb65b800-fc54-11e8-8f12-427fb8ef4766.png)

**Comment by bfred-it** [comment]
That’s as expected

Discussion at https://github.com/sindresorhus/refined-github/issues/1109
