### ISSUE TITLE
Warn when creating a PR from master branch

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1664]
Creating a PR from master branch is an anti-pattern, but I still see many users that do it. This creates many problems, like accidentally committing to an older open PR by just committing to their fork's master branch. Would be nice to show a big warning with a link to an explanation why they should create a PR-specific branch instead if they try to create a PR from master.

---

_For anyone that wants this, please also send this feature request to GitHub: support@github.com_

**Comment by bfred-it** [comment]
This shouldn't be too hard.

The URL looks like this:

```
https://github.com/babel/babel/compare/master...bfred-it:master
```

If `feature.isCompare` and if it ends in `\`${getUsername()}:${getDefaultBranch()}\``, add warning somewhere on the page.

**Comment by vacuus** [comment]
Created  a PR for this here: https://github.com/sindresorhus/refined-github/pull/1758 .
