### ISSUE TITLE
Show warning if PR submitter tries to uncheck `Allow edits from maintainers`

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1665]
I often get PRs where the user has unchecked `Allow edits from maintainers.` when creating a PR. This is super annoying as it means I cannot easily do changes to the PR myself. There's no reason for users to do this. Would be nice to show a warning if a user tries to uncheck it that explains why unchecking it would be annoying to the maintainers.

<img width="828" alt="screen shot 2018-12-12 at 21 19 07" src="https://user-images.githubusercontent.com/170270/49896419-962be580-fe53-11e8-899c-2ecfe806809f.png">

**Comment by bfred-it** [comment]
_For anyone that wants this, please also send this feature request to GitHub: support@github.com_

**Comment by CEOehis** [comment]
@bfred-it 	I'd like to give this issue a go if no one is working on it yet.

**Comment by bfred-it** [comment]
Go ahead!

**Comment by CEOehis** [comment]
@bfred-it since there is no element to attach a warning message to, could triggering the pop-up from the `learn more` button work as a solution? (with maybe a modified message)

<img width="673" alt="screenshot 2019-02-11 at 12 45 42 pm" src="https://user-images.githubusercontent.com/25967737/52561206-fe1e8e00-2dfa-11e9-9e97-281f7cfeb3dc.png">

**Comment by bfred-it** [comment]
It needs to be a visible warning. The code should probably be similar to this:

https://github.com/sindresorhus/refined-github/pull/1758#issuecomment-462204170

**Comment by CEOehis** [comment]
> It needs to be a visible warning. The style and code should probably be similar to this:
> 
> [#1758 (comment)](https://github.com/sindresorhus/refined-github/pull/1758#issuecomment-462204170)

Thanks @bfred-it , that's exactly what I needed. I am open to suggestions on the final wording that could be used, but this is what I have so far.

<img width="771" alt="screenshot 2019-02-11 at 3 22 26 pm" src="https://user-images.githubusercontent.com/25967737/52569259-0da8d180-2e11-11e9-8835-5be39c4c112c.png">
