### ISSUE TITLE
Link HTML pages to (development pages of) raw.githack.com

### ISSUE THREAD

**Issue by brettz9** [sindresorhus/refined-github#1668]
If one has navigated to say https://github.com/SVG-Edit/svgedit/blob/master/editor/svg-editor.html , it'd be very convenient to have a link (next to say "Raw", "Blame", "History") leading to https://raw.githack.com/SVG-Edit/svgedit/master/editor/svg-editor.html

**Comment by bfred-it** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/1595

**Comment by bfred-it** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/1096
