### ISSUE TITLE
Add button to insert summary

### ISSUE THREAD

**Issue by erasche** [sindresorhus/refined-github#1670]
When I'm submitting issues I often find that I have the need to paste some long stack trace in, and I always forget the syntax for doing it! It would be really nice if the github issue/comment field could be modified to include a button to insert a snippet for that, next to the bold/italic/insert comment/quote/link buttons :)

The syntax is

```html
<details>
  <summary>Some text</summary>
  then here is some long text you want to hide
</details>
```

Which renders like this, if you haven't used it before:

<details>
  <summary>Some text</summary>
  then here is some long text you want to hide
</details>

**Comment by sindresorhus** [comment]
👍 PR welcome :)

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by erasche** [comment]
Wow, thanks @doms! Great work!
