### ISSUE TITLE
Separate merge buttons

### ISSUE THREAD

**Issue by andreiho** [sindresorhus/refined-github#1675]
In my team we mainly use squashing, but once in a while we have to do a merge commit or rebase. This sometimes causes accidents because when a team member switches their merge setting to do a merge commit, the next time they want to merge a PR by squashing, that setting is remembered and they accidentally merge all their commits to the branch. This could easily be avoided by laying out all buttons next to each other.

I took a quick shot at it and got the layout right, however the behaviour needs more work. When selecting from the dropdown, various things are changed in the DOM. I'm not sure how that would work when moving from a 2 step process to just 1 step.

<img width="785" alt="screenshot 2018-12-18 11 03 14" src="https://user-images.githubusercontent.com/9000674/50148318-829bd700-02b8-11e9-85db-0f6a539beea3.png">

**Comment by bfred-it** [comment]
It’s a bit noisy and it’s not getting much interest, I’m closing for now

**Comment by liamkeily** [comment]
This would be useful 👍

**Comment by weshooper** [comment]
Our team also regularly experiences the issue described 👍

**Comment by BHare1985** [comment]
Our team needs this. I actually implemented [this extension ](https://chrome.google.com/webstore/detail/github-merge-helper/pdbfjlgaikbfadbajlelnooicnajamgb) in effort to fix this problem in that we always "squash" unless someone adds a label "DontSquash".

This forces squashing unless the label exists. Unfortunately github had a code change and the extension was brittle and doesnt work properly anymore. I'd love it if I can just suggest everyone switch to refined-github
