### ISSUE TITLE
Hide/collapse bots in commits

### ISSUE THREAD

**Issue by mike-north** [sindresorhus/refined-github#1676]
With the rise in popularity of dependency management bots and other non-human commit-generating entities, commit logs can get [very noisy](https://github.com/typed-ember/ember-cli-typescript/compare/v2.0.0-beta.3...v2.0.0-rc.1) relative to the typical experience in the pre "rise of the bots" era.

It would be nice to have an option for filtering these types of commits out of the list, particularly in the `/compare/X...Y` UI.

**Comment by bfred-it** [comment]
There’s a problem with including this feature: it’s a very minor feature and might cause problems (i.e. hiding commits some people might not want to hide), including false positive and thus constant tweaking of the selector.

**Comment by sindresorhus** [comment]
It's nice to remove noise, but not sure if this is a good idea. What if a rogue bot commits something bad to your repo and we hide that commit.

**Comment by sindresorhus** [comment]
> including false positive and thus constant tweaking of the selector.

Don't all bot usernames end with `[bot]`, like `sindresorhus[bot]`?

**Comment by bfred-it** [comment]
> Don't all bot usernames end with `[bot]`, like `sindresorhus[bot]`?

> false positives

https://github.com/Sobot

**Comment by sindresorhus** [comment]
@bfred-it That's just a bot using a normal user account. I don't think we should care about that. It's good enough if it just handles proper `[bot]` accounts.

**Comment by bfred-it** [comment]
> That's just a bot

Where are you seeing that? What I'm saying is that there might be usernames ending in -bot and a blanket `bot$` selector would ghost all those commits.

That, plus what you said in your first comment.

**Comment by sindresorhus** [comment]
> Where are you seeing that?

Look for `renovate[bot]` here: https://github.com/typed-ember/ember-cli-typescript/compare/v2.0.0-beta.3...v2.0.0-rc.1 And `greenkeeper[bot]` here: https://github.com/lukechilds/cacheable-request/commits/master It seems GitHub adds `[bot]` to bot usernames.

**Comment by bfred-it** [comment]
I was referring to https://github.com/Sobot

**Comment by mike-north** [comment]
> There’s a problem with including this feature: it’s a very minor feature and might cause problems (i.e. hiding commits some people might not want to hide), including false positive and thus constant tweaking of the selector.

My thinking was that this filter would default to "off". I definitely agree that starting to filter stuff without telling anyone is a bad idea.

RE: concerns around false positives, there's a knowable and relatively small set of bots that produce this kind of noise

* greenkeeper
* dependabot
* renovate
* etc...

Could we not just have a hardcoded list of "noisy bots"? 

I wouldn't necessarily want to remove _all_ bots, since there may be some whose contribution to changelogs is far more meaningful (i.e., auto-fixing a security vulnerability or something)

**Comment by bfred-it** [comment]
Whitelist sounds good too.

Could these commits be faded out like we do we merge commits? Safer.

**Comment by fregante** [comment]
Sounds like all our discussion was for nothing 😅
Bots have `/marketplace/` or `/apps` in the URL, make it very easy to filter out. Example of noisy commit list: https://github.com/OctoLinker/OctoLinker/commits/master

**Comment by kidonng** [comment]
> Could these commits be faded out like we do we merge commits? Safer.

![1](https://user-images.githubusercontent.com/44045911/63224429-95bfc780-c1f6-11e9-9e9f-094657809bcd.png)

Something looks like this? Cool 😁

**Comment by fregante** [comment]
Yes please, also in PR/Issue lists

**Comment by fregante** [comment]
PR ready!
