### ISSUE TITLE
Merge adjacent +1/-1 comments with the same content

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#168]
Follow-up from https://github.com/sindresorhus/refined-github/issues/74#issuecomment-204128892

We could collapse all adjacent +1/:+1: comments and all adjacent -1/:-1: comments into a single comment inside of the comment timeline with the number of comments combined. This way we still streamline old issues with a ton of +1 votes, while showing relatively when and after which comments or changes the votes occurred.

**Comment by DrewML** [comment]
How would you feel about collapsing/expanding headers, similar to what we implement on the file headers in diffs? We'd just keep the comments where they are now, but collapse them by default, just to the relevent information (name, avatar, date/time, badge), and give some indicator it's a +1 comment.

Mockup:
![image](https://cloud.githubusercontent.com/assets/5233399/14344530/c28b254a-fc6d-11e5-9ca5-6f2792ed36aa.png)

No benefit over your suggestion, just another option.

**Comment by hkdobrev** [comment]
@DrewML Hmm, some issues have hundreds of +1 comments. That's why I suggested combining them with a number. I was looking at one such issue the other day, but can't find it now.

Although I prefer the simplicity of your approach.

**Comment by DrewML** [comment]
> I was looking at one such issue the other day, but can't find it now.
Was it this one? https://github.com/isaacs/github/issues/9 :laughing:

**Comment by hkdobrev** [comment]
@DrewML 
> Was it this one? isaacs/github#9 :laughing:

Exactly the one! 😆

**Comment by sindresorhus** [comment]
Don't put too much energy into this. It's a fading problem.

**Comment by DrewML** [comment]
@sindresorhus In that case, rather than address in this extension, how do you feel about just linking to the [other extension that handles this](https://github.com/ryanflorence/github-plusone-extension) in the readme?

**Comment by sindresorhus** [comment]
Sounds good
