### ISSUE TITLE
Are "Implemented by GitHub" features still available to activate for GitHub Enterprise?

### ISSUE THREAD

**Issue by jondavidi** [sindresorhus/refined-github#1681]
Are the features listed as "Implemented by GitHub" still available to activate? Or have they been removed from the repository? I'm specifically interested in:

> Implemented by GitHub: The + and - signs in diffs are made unselectable for easier copy-pasting.

The scenario I have is that, while it's true that feature has been implemented in public GitHub, I'm using a version of Enterprise GitHub that seems to have not yet implemented that change. So I'm wondering if I download the extension if I'm able to enable that feature for use with my current GitHub Enterprise version.

Sorry if I'm missing any obvious answer to this question, I looked through the documentation as best I could but didn't see an answer. Thanks!

**Comment by busches** [comment]
They've been removed, you can go back to a previous version or revert the
commit in a fork.

**Comment by bfred-it** [comment]
That’s right, if you want to use those it’s best you download an earlier version and build it following Contributing.md

If you use Firefox you can download earlier versions from the store directly.
