### ISSUE TITLE
First changed file header overlaps tags dropdown

### ISSUE THREAD

**Issue by nanoander** [sindresorhus/refined-github#1683]
Without the extension:
![screenshot_20181224_112003](https://user-images.githubusercontent.com/37919309/50404843-7669bb00-078b-11e9-929c-d7f30da2a52e.png)

With the extension:
![screenshot_20181224_112043](https://user-images.githubusercontent.com/37919309/50404846-7ec1f600-078b-11e9-8d0e-9c5c68eb9531.png)

**Comment by busches** [comment]
I'm not able to reproduce this, are you able to? I'm opening a new PR and attempting to add an issue label there.
![image](https://user-images.githubusercontent.com/857700/52529388-7e87a680-2cb6-11e9-8ac5-901e82c29cb2.png)

**Comment by bfred-it** [comment]
Can't reproduce anymore
