### ISSUE TITLE
remove 'Join GitHub today' banner

### ISSUE THREAD

**Issue by geeseven** [sindresorhus/refined-github#1689]
If you are not logged in, GitHub will sometimes show a 'Join GitHub today' banner on repository's main page.  It is displayed just above the description.  Not only is the banner annoying on its own, the dismiss button is broken in Firefox.  Instead of making the banner go away, it redirects you to the sign up page.  

It would be great if this plugin could remove that banner.

**Comment by geeseven** [comment]
Hey @busches,

Thanks for the timely reply.  I did not realize that RGH only works when logged in.  It is probably not worth changing that just for this request.  Curious if that is something that might get changed, or is it a hard no.

CSS was my first thought, and I will look into that.      

For a few different reasons, I do not want to be permanently logged into GitHub.

Also, I am filing a bug with GitHub to fix the dismiss issue with Firefox.

**Comment by bfred-it** [comment]
It’s annoying indeed but for me it’s a clear cue that I’m logged out and shouldn’t be.

**Comment by sindresorhus** [comment]
“Logged out” is outside the scope of RGH. You can probably easily hide it with the Stylish extension or similar.
