### ISSUE TITLE
wiki search

### ISSUE THREAD

**Issue by guaka** [sindresorhus/refined-github#169]
Wiki search functionality would be nice.

There's this already, https://github.com/linyows/github-wiki-search, it may be possible to integrate this

**Comment by sindresorhus** [comment]
:-1: Not something I would ever use and there's already a separate extension.

**Comment by hkdobrev** [comment]
I'm using this from Algolia: https://chrome.google.com/webstore/detail/github-awesome-autocomple/djkfdjpoelphhdclfjhnffmnlnoknfnd

I don't know if they index the wiki, but if they don't we can to talk with them and integrate it.

However I also think this is better as a separate extension, however we could have a quite better extension than the one above.

@redox Do you think we could use Algolia GitHub index to have full-blown wiki search?

**Comment by leocaseiro** [comment]
@hkdobrev how about add this extension to Related at `readme.md` or perhaps create a repo like **Awesome github extensions**?

**Comment by sindresorhus** [comment]
> how about add this extension to Related at readme.md

Which one?

> perhaps create a repo like Awesome github extensions?

https://github.com/stefanbuck/awesome-browser-extensions-for-github

**Comment by leocaseiro** [comment]
@sindresorhus I suggest to add the Awesome list one.

**Comment by paulmolluzzo** [comment]
@guaka I agree about not really needing this, but probably more importantly, I'm not keen on copying another extension or supporting some sort of parity between this and the source repo. That repo is still active, so I expect the two would diverge quickly.

@sindresorhus this is a recurring request to integrate it other extensions. Maybe we can just put a one liner in the README saying that this isn't meant to be a catchall extension and we can't just wholesale copy extensions in?

**Comment by sindresorhus** [comment]
> Maybe we can just put a one liner in the README saying that this isn't meant to be a catchall extension and we can't just wholesale copy extensions in?

:+1:

**Comment by redox** [comment]
> @redox Do you think we could use Algolia GitHub index to have full-blown wiki search?

Unfortunately, that would consume a lot of additional resources on our side (we're already consuming a bunch of SSD & RAM to index all public repo & users) so I think we would like to stick to that.

> @hkdobrev how about add this extension to Related at readme.md or perhaps create a repo like Awesome github extensions?
+
> @sindresorhus this is a recurring request to integrate it other extensions. Maybe we can just put a one liner in the README saying that this isn't meant to be a catchall extension and we can't just wholesale copy extensions in?

We would love to be included in that list :+1: Let us know if there is any PR to do or so :)
