### ISSUE TITLE
Error for 19.1.3.1808

### ISSUE THREAD

**Issue by Darkilen** [sindresorhus/refined-github#1695]
This add-on don't work for Firefox Developer Edition 65.0b7 (64 bits) in latest version (19.1.3.1808) but work fine in 19.1.2.1808 (from AMO)

He sent me a 404 error in console for every file by trying access to this URL : `https://github.githubassets.com/app/node_modules`

**Comment by bfred-it** [comment]
> for every file

What do you mean? On what pages do you see the error?

**Comment by Darkilen** [comment]
I test it on this issue or on https://github.com/sindresorhus/refined-github/issues/595 (to see "like profile image" feature).

I can't reproduce the 404 error, I'm sorry, but all paths was related to Github, maybe a Github error, i don't know.

But what I'm sure, it's when i update to 19.1.3.1808, this add-on doesn't work anymore. I have no the default config of this add-on, except that I checked "Show the features enabled on each pages in the console".

**Comment by bfred-it** [comment]
Indeed. 19.1.3 doesn't work on Firefox, it seems to be caused by #1692 / https://github.com/sindresorhus/refined-github/commit/e4a66fe4f91a1a3a0f0fbe9d8800ec2c5bcede35

**Comment by bfred-it** [comment]
Firefox extension debugging is annoying as hell. Apparently Firefox is choking on a regex introduced by https://github.com/sindresorhus/linkify-urls/commit/5d04065cef99effbd18f6b368a0afa11a3cc1878 (I had to use a diff tool on `content.js` between 19.1.2 and 19.1.3 to find out) and it just doesn't run `content.js`, without throwing any errors 🙄

**Comment by vanniktech** [comment]
This is still broken for me with: Refined GitHub 19.1.7.1811
