### ISSUE TITLE
Missing open all pull requests button on users' Pull Requests page

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1699]
https://github.com/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+author%3Aevandrocoan+
![image](https://user-images.githubusercontent.com/5332158/50737688-67cfca80-11b3-11e9-9361-9b0a8b62cdf5.png)

___
https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc
![image](https://user-images.githubusercontent.com/5332158/50737710-85049900-11b3-11e9-9c01-456f6d44e4f9.png)

___
The original feature was implemented on:
1. https://github.com/sindresorhus/refined-github/issues/1179 Open all issues/PRs in tabs
1. https://github.com/sindresorhus/refined-github/pull/1229 Missing open all pull requests button on users' Pull Requests page

**Comment by vanniktech** [comment]
Is it also missing for issues?

**Comment by evandrocoan** [comment]
Yes. You can check: 
1. https://github.com/pulls
1. https://github.com/issues

**Comment by bfred-it** [comment]
That’s because the feature isn’t enabled on those pages. Easy PR welcome to add the two missing checks for those two pages
