### ISSUE TITLE
Show reactions popover on mouseover

### ISSUE THREAD

**Issue by leocaseiro** [sindresorhus/refined-github#170]
I believe a click is a waste of time/click to show the reactions. The popover should show on mouseover.

![screen shot 2016-04-08 at 4 51 37 am](https://cloud.githubusercontent.com/assets/940070/14363074/c3a2f1aa-fd45-11e5-9bb0-90cfcdb566b7.png)

Do you guys agree?

**Comment by sindresorhus** [comment]
I like it. It's more in line with the Facebook reactions, which is IMHO better done. I would also remove the useless "Pick your reaction" text so you can more quickly click the reaction.

**Comment by hkdobrev** [comment]
An alternative would be to actually place the reaction buttons to the comment header itself without the dropdown.

**Comment by paulmolluzzo** [comment]
> An alternative would be to actually place the reaction buttons in the comment header itself without the dropdown.

This might be confusing to see all the options there. Unless you mean that when you hover they show in that area, that would be good (like an expanded block).

Whoever does this should keep in mind that the `click` listener on the reaction icons from #145 is tied to class names, so if you move things around test that the listener selector isn't broken.

**Comment by sindresorhus** [comment]
> Unless you mean that when you hover they show in that area, that would be good (like an expanded block).

👍 I like that idea ✨

-

Anyone interested in doing this one?

**Comment by paulmolluzzo** [comment]
@sindresorhus I started working on a solution before and just didn't push. I'll try to push at least a WIP tonight.

**Comment by paulmolluzzo** [comment]
@leocaseiro there are two PRs for this if you want to check them out: #186 and #187

**Comment by leocaseiro** [comment]
My vote is #186
