### ISSUE TITLE
Make tag button on main repo view ignore pre releases

### ISSUE THREAD

**Issue by Stanzilla** [sindresorhus/refined-github#1701]
I think it would make sense if the feature that adds the latest tag on the main repo view ignored pre-releases or instead of getting the latest by name, get it by date.

![image](https://user-images.githubusercontent.com/75278/50769208-8bfadc80-1283-11e9-8d89-ed03d6c27901.png)

**Comment by bfred-it** [comment]
Prereleases are normally ignored, but I think RGH is just showing the latest tag because the list of tags contains unsupported versions, like `7.0.build12` (`build` isn't supported), as decided in https://github.com/sindresorhus/refined-github/issues/1654

**Comment by Stanzilla** [comment]
Hrm but going after the date instead of name by default sounds like the better idea anyway?

**Comment by bfred-it** [comment]
We get the last version that appears in the list. The last version is 2.10.11 but there's a 8.0 version in the tags... either way it doesn't sound right.

Even the API returns 8.0-beta2 as "the latest"

https://api.github.com/repos/WeakAuras/WeakAuras2/tags


And there appears to be no way to query tags by date even in API v4, only releases: https://developer.github.com/v4/object/repository/

**Comment by Stanzilla** [comment]
Uh, the API is right here, no? https://api.github.com/repos/WeakAuras/WeakAuras2/releases

**Comment by bfred-it** [comment]
We can’t pick releases over tags because lots of repos have tags but not releases, or have had some releases but have not kept up. So to fix this we’d have to break many others
