### ISSUE TITLE
add-filter-comments-by-you feature broken on GHE

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#1702]
GHE is still using `a` elements instead of `li` elements all over the place in the UI. Which results in this selector:https://github.com/sindresorhus/refined-github/blob/3737e091b697bf87f0ec4964eb726ab8eaf5ad10/source/features/add-filter-comments-by-you.js#L9 returning a null then the `.before` call failing.

Selector for GHE will be: `.subnav-search-context a:last-child`.

Also the markup is different, here is a sample:
```html
<a href="https://<URL>/<org>/<repo>/issues?q=is%3Aopen+mentions%3Abusches+sort%3Aupdated-desc" class="select-menu-item js-navigation-item">
    <div class="select-menu-item-text">
      Everything mentioning you
	</div>
</a>
```

Note, we're still on GHE 2.14 series and 2.15 is out, if 2.15 has fixed the markup issue then this can be ignored.

**Comment by bfred-it** [comment]
Did 2.15 fix it?

**Comment by busches** [comment]
They haven't upgraded yet. "Soon", it's like [Blizzard's soon](https://wow.gamepedia.com/Soon).
