### ISSUE TITLE
V3 API calls no longer work for GHE

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#1703]
Currently `fetch3` calls the following URL for v3 endpoints on GHE domains:
`${location.origin}/api/` when the actual endpoint is `${location.origin}/api/v3/`.

`fetch4` works correctly as `graphql` is added for both GH and GHE endpoints.

**Comment by bfred-it** [comment]
Did they just change the endpoint like that? 😳
Can you find any notice about it online?

**Comment by busches** [comment]
I don't see it called out in the release notes from 2.10 -> 2.15 and they have it in the documentation as v3 for all of those versions. https://developer.github.com/enterprise/2.15/v3/#current-version

Probably a leftover path to the v3 API that was never intended to be used that got removed sometime.

**Comment by bfred-it** [comment]
Indeed: https://developer.github.com/enterprise/2.0/v3/#current-version

PR welcome, can be merged before #1694

**Comment by dongs0104** [comment]
GHE version api uri is wrong think fetch4 use api v3 uri

https://github.com/sindresorhus/refined-github/blob/7af18883aa400ab463d0c121be6fcf84c1cba142/source/libs/api.ts#L46

**Comment by bfred-it** [comment]
Good catch! Fixed
