### ISSUE TITLE
Filter out notifications from certain bots.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#1705]
There are a number of bots who I don't want to fully block from a repo, but I also don't care about being notified when they comment (looking at you, various bug bounty bots).

**Comment by yakov116** [comment]
@jamestalmage 	how would it be possible? I think this is only something that Github can do (maybe I'm wrong)

**Comment by bfred-it** [comment]
To filter them out and avoid the blue bubble we’d have to keep fetching the notifications and (if possible) see who caused the notification. 

However if a user comments, then a bot comments… you’re gonna lose that notification. 

Also it looks like it’s not possible to see how caused that at all, even through the API, so I’m gonna close this https://developer.github.com/v3/activity/notifications/

**Comment by jamestalmage** [comment]
bummer
