### ISSUE TITLE
"Mark all as read" button is gone

### ISSUE THREAD

**Issue by mwz** [sindresorhus/refined-github#1708]
It looks like the "Mark all as read" button no longer shows up on the notifications page 😢 

![screen shot 2019-01-10 at 18 36 14](https://user-images.githubusercontent.com/1190768/50989229-b3151080-1506-11e9-92dd-c7e0ad143096.png)

**Comment by vanniktech** [comment]
Similiar to open all notifications - https://github.com/sindresorhus/refined-github/issues/1695#issuecomment-453039539

**Comment by OvermindDL1** [comment]
Both in Chrome and Firefox for note.

**Comment by vanniktech** [comment]
Yeah it seems like.
