### ISSUE TITLE
CI link: Doesn't play well with github actions

### ISSUE THREAD

**Issue by gossi** [sindresorhus/refined-github#1709]
Hey,

I found, that the added CI link next to the repo name has some hickups with github actions.

- It shows duplicated checks: some that were run in an earlier commit, will be shown again: <img width="441" alt="bildschirmfoto 2019-01-12 um 14 00 22" src="https://user-images.githubusercontent.com/283700/51073542-ae6d6b00-1672-11e9-8314-e4f484e7b7f2.png">
- It is ok for some of the github actions to be cancelled, as this is expected behavior. E.g. if the "Filter" action from github is used, to only proceed once this is a "tag", then those actions afterwards will be cancelled. The CI status will show the red cross, while actually it should be the green check.

**Comment by bfred-it** [comment]
We just pick the link from the commits list as-is and let GH handle the rest. Can you link to a repo where this happens? Does the native status icon work correctly in the commits list?

**Comment by gossi** [comment]
I understand. Here is what I was playing around with github actions the morning: https://github.com/gossi/sparkles-decorators/commits/master

I deleted the action after all, since it didn't do what I wanted. However, there is one commit which I consider to have a false negative indicator: "Rename publish.workflow to main.workflow" -> https://github.com/gossi/sparkles-decorators/commit/3627aacb47667d17e233b59e89a44ed0e8e3dffa
The two actions are cancelled appropriately (= expected behavior). Since I lost track whether these indiciators and hovers are coming from GH itself or this plugin 🤷‍♂️ - that might help. 

The following commit "Change Tag to Filter" has the duplicates.

Can you say, whether this is related to github or this plugin?

**Comment by bfred-it** [comment]
When you disable  Refined GitHub you’ll see what feature are native and which aren’t. What you’re describing depends on GitHub (commit list)
