### ISSUE TITLE
Viewing PRs - File header bar is no longer sticky

### ISSUE THREAD

**Issue by bttf** [sindresorhus/refined-github#1727]
This must've happened in a recent update, but the file header bar that accompanies each file in the 'Files changed' tab no longer sticks to the top while scrolling down.

This was a super convenient and useful feature for me - was the change intentional? And if so, what was the reasoning, and how can we bring it back?

**Comment by yorch** [comment]
Agree, it was a super useful feature since I often find myself collapsing files when going through code reviews so didn't have to scroll all the way up to the start of the file to do it.
