### ISSUE TITLE
Show number of subscribers to an issue

### ISSUE THREAD

**Issue by isiahmeadows** [sindresorhus/refined-github#1728]
[This is actually possible to compute](https://gitter.im/mithriljs/mithril.js?at=5c34273112db9607e7531d68) using GH's GraphQL API; it just requires a bit of processing and is a relatively heavy request. This would also be useful to calculate within issue lists themselves. The linked Gitter conversation has a bit more context as for why I would like this. (Note: I don't have the script I mentioned I was considering writing.)

One interesting thing is that you can view this even if you don't have commit access, so you could show this data on all repos and issues.

**Comment by isiahmeadows** [comment]
The linked Gitter conversation has a bit more context as for why I would like this.

One other interesting thing is that you can view this even if you don't have commit access.

**Comment by bfred-it** [comment]
Where do you see it's possible to compute?

**Comment by isiahmeadows** [comment]
Closing since I'm noticing my experiment locally to try to hack this in isn't working.

<details>
<summary>Hidden, because apparently, this won't work. GitHub could at *least* expose this via their GraphQL API.</summary>
I was thinking you'd do it this way, using the GraphQL API:

1. Run this [GraphQL](https://developer.github.com/v4/) query:\*

	```graphql
	# For user/repo#123
	query {
		repository(name: "repo", owner: "user") {
			issue(number: 123) {
				timeline {
					nodes {
						__typename
						... on SubscribedEvent { actor { login } }
						... on UnsubscribedEvent { actor { login } }
						# etc.
					}
				}
			}
		}
	}
	```

2. Filter out all timeline events whose `.__typename` is neither `SubscribedEvent`, `UnsubscribedEvent`, or an event that auto-subscribes you.

3. Create a set of subscribers, and interpret those events in order of date, adding their `.actor` for `SubscribedEvent`s and events that auto-subscribe you and removing their `.actor` for `UnsubscribedEvent`s.

4. Return the size of the set - this is the number of subscribers. This can be cached with a 10 second timeout to reduce the number of network requests, and the rest of the data is just garbage now.

The lists could be large, so this would probably need optimized some. For one, it might be better to do this in a single `for` loop.

\* I may have the syntax slightly wrong; I haven't tested it. Also, if the events are unordered, you'll also need to include `createdAt` in addition to `actor` for each type and sort by that.
</details>

**Comment by isiahmeadows** [comment]
I'll note that it seems [this, gained from `timelineItems` in `issue`](https://developer.github.com/v4/object/issuetimelineitemsconnection/) seems promising, but it doesn't appear it would be any different. @github Could you *maybe* add a field for this?

**Comment by isiahmeadows** [comment]
Just filed https://github.com/isaacs/github/issues/1463 with a corresponding support email.
