### ISSUE TITLE
Preview hidden comments without opening them

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1731]
Collapsing comments is great, but I think a preview should still be shown to get an idea of what it was about without having to open them. Maybe just the resolved/outdated comments.

# From

<img width="784" alt="" src="https://user-images.githubusercontent.com/1402241/51300940-1ac7e000-1a60-11e9-8ebb-d16ea2175059.png">

# To

<img width="773" alt="" src="https://user-images.githubusercontent.com/1402241/51300939-1ac7e000-1a60-11e9-857e-7aec81056577.png">

**Comment by sindresorhus** [comment]
Would be useful to show the contents in a popover when hovering over, but that's a lot more work.

**Comment by bfred-it** [comment]
Maybe GitHub's `hovercard` is flexible enough to be enabled with a couple of classes on the gray bar and the hidden comment. Worth exploring if anyone wants to pick up this feature.

However I think it's better to just show the first line for all, instead of having to hover each one (which almost defeats the purpose since you might as well click the whole gray bar)

**Comment by hkdobrev** [comment]
This would be very useful to me as I often go back to collapsed reviews and then expand all to see which are really properly resolved and which to comment on. So with this I'd be able to hover through and expand only the ones I'm interested in and then carry on to the conversation.
