### ISSUE TITLE
GitHub added Mark as Unread

### ISSUE THREAD

**Issue by nesl247** [sindresorhus/refined-github#1733]
See: https://blog.github.com/changelog/2019-01-11-mark-as-read/

I wonder if the extension could be changed to use their API instead of using storing it locally.

**Comment by bfred-it** [comment]
Refined GitHub can create notifications from any issues. 

GitHub can only mark **existing** notifications as unread: 
https://github.com/isaacs/github/issues/236#issuecomment-455290482

**Comment by nesl247** [comment]
Even so, it's only done locally. It would be nice if it's a notification that existed, we could use their API so it shows up correctly across systems.

**Comment by bfred-it** [comment]
Refined GitHub's "Mark as unread" feature won't receive any more upgrades since we expect GitHub to add it natively soon. Related: https://github.com/sindresorhus/refined-github/issues/1036#issuecomment-436582843

**Comment by klonos** [comment]
A year later, I am missing this feature badly, and it seems that the only "mark unread" functionality that was added in GitHb is to its notifications (https://github.com/isaacs/github/issues/236), not the issue list/thread (https://github.com/isaacs/github/issues/456 - untouched since March 2019).

Can we please bring this back as an option in refined-github?? 🙏

**Comment by fabiospampinato** [comment]
This you be amazing to have back, the way github implemented this is not very handy as you have to search for the issue to mark as unread from the notifications page, and you can't really search those with a query either.

**Comment by fregante** [comment]
The final resolution was that the feature, while useful, was too big to be part of Refined GitHub and indeed it was mostly cruft we carried over for years without improvements. This won't happen again and I suggest creating a new extension for it.
