### ISSUE TITLE
Create issues from Project view

### ISSUE THREAD

**Issue by mmiller42** [sindresorhus/refined-github#1736]
Projects can be associated with one or more repositories. Unfortunately, to create a new issue on your board, you have to navigate away from the Project and go directly to a repository to create an issue before adding the issue to the project. This makes sense for open source projects where issues are commonly contributed and it's up to the maintainer to add and prioritize them to a roadmap. However, for teams that use GitHub Projects for development, creating issues from within the project view would be more convenient.

Proposal:

Add a "Create issue" button near the "+ Add cards" button in Project view. This opens a modal with the standard fields for creating an issue, in addition to a "Repository" dropdown where the user can select one of the repositories that this Project is linked to. The "Projects" field would either not be displayed or would just be pre-populated to include the current project.

Example modal contents:

![image](https://user-images.githubusercontent.com/11927375/51402850-e4479f00-1b0b-11e9-9aa6-f0cf095a9c60.png)

This is probably only feasible if the existing GitHub UI for creating issues is somehow reusable, which I'm not sure.

**Comment by chadfawcett** [comment]
It's a bit of a two step process, but you can already create issues from projects. If you add a note to a column, you can convert it to an issue.

![screen shot 2019-03-01 at 9 04 49 am](https://user-images.githubusercontent.com/3250463/53653956-6b0a9400-3c01-11e9-9e0d-fcd300ea25f4.png)

![screen shot 2019-03-01 at 9 07 58 am](https://user-images.githubusercontent.com/3250463/53654032-92616100-3c01-11e9-9ae7-fc5ecedca074.png)

**Comment by bfred-it** [comment]
I think this is the kind of feature that belongs more to a project management extension like ZenHub. Projects don't seem to be used by any of the maintainers.

In the meanwhile Chad's solution seems only one more click away
