### ISSUE TITLE
[Feature Request] Add "options" page for configuring certain features

### ISSUE THREAD

**Issue by therealklanni** [sindresorhus/refined-github#174]
I love this extension, it has a ton of things that are quite useful. However, there are one or two things I wish I could opt in/out of. In particular I like seeing the "starred" activity in the feed. However, I would love to be able to toggle on/off the comment activity in the feed, because in my own workflow I look at that activity elsewhere (usually on a repo-by-repo basis). Just a couple examples of where configurable options would be a great addition, IMHO.

Seems like there's also a good use-case for this configurability with many other existing and requested features.

Thanks for yet another great project, @sindresorhus!

**Comment by paulmolluzzo** [comment]
@therealklanni Please see here: #57

**Comment by hkdobrev** [comment]
Explained more in https://github.com/sindresorhus/refined-github/issues/10#issuecomment-184663384, https://github.com/sindresorhus/refined-github/issues/75#issuecomment-195170518 and https://github.com/sindresorhus/refined-github/issues/131#issuecomment-203949498
