### ISSUE TITLE
Hide/collapse bots in conversations

### ISSUE THREAD

**Issue by danielcompton** [sindresorhus/refined-github#1745]
The Codecov bot is extremely noisy, and most of the time I find myself scrolling past it's (numerous and large) comments. It would be nice if they could just be collapsed automatically, and I could open it on the occasion I need to view it. Even removing it entirely wouldn't be the worst outcome for me.

Similar to #1705, but this would only be in the context of the issue view.

**Comment by bfred-it** [comment]
It was discussed before, I'd make this part of the `hide-useless-comments` feature

**Comment by bfred-it** [comment]
Related to https://github.com/sindresorhus/refined-github/issues/1676

**Comment by fregante** [comment]
On second thought, maybe not. Bots may be useful. Perhaps we should deemphasize them. Make their header white. Suggestions welcome.

**Comment by ProLoser** [comment]
@fregante I like a white header, that's a good start.

**Comment by fregante** [comment]
We need some real URLs to test this. Can anyone provide examples with various bots?

@vscodebot: https://github.com/microsoft/vscode/issues/84165

**Comment by fregante** [comment]
I don't think this is a safe operation. Some bots are required (think CLA bots) so we can't hide them.

Dimming their bar isn't particularly useful as far as _noise_ goes.
