### ISSUE TITLE
Use package octicons instead of including icons.tsx

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#1752]
https://www.npmjs.com/package/octicons

Import as plain text:

```js
import doma from 'doma';
import alertIcon from 'octicons/build/svg/alert.svg';

document.body.append(doma.one(alertIcon))
```

Or as JSX with https://github.com/janjakubnanista/svg-jsx-loader

```js
import alert from 'octicons/build/svg/alert.svg';

document.body.append(alert());
```

There's also the official `@githubprimer/octicons-react` package but I don't think it's being built+published correctly yet.

Also possibly: https://github.com/siddharthkp/jsxo but it needs Babel

**Comment by sindresorhus** [comment]
Why change it now though? Our way is already working fine. GitHub might also sometimes use new icons that are not yet added to that package.

**Comment by bfred-it** [comment]
For the same reason why we prefer to `npm install` features instead of maintaining them in a project.

 If a new icon isn’t present (🤷‍♂️) we can still copy-paste it (like we did before) directly in the feature that needs it.

**Comment by sindresorhus** [comment]
Alright then 👍

**Comment by HardikModha** [comment]
@bfred-it  Seems like https://www.npmjs.com/package/@githubprimer/octicons-react is being published regularly now. Probably we can use it. What do you think?

**Comment by bfred-it** [comment]
Sadly they use too much React stuff in there, it's bloated for us
