### ISSUE TITLE
New “Projects” tab messes up profile if “gists” tab enabled

### ISSUE THREAD

**Issue by yeskunall** [sindresorhus/refined-github#1757]
GitHub added a new “Projects” tab. AFAICT, this wasn’t a thing couple of hours ago 🤨

Here’s what it looks like right now:

![image](https://user-images.githubusercontent.com/14703164/52444709-2191c200-2af7-11e9-8992-7664de9d6e9f.png)

For now, my workaround is to simply disable the “gists” tab by adding `profile-gists-link` to my list of features to disable.

![image](https://user-images.githubusercontent.com/14703164/52444939-bb596f00-2af7-11e9-98cd-4eda34c52a96.png)

That fixes it, but I’m sure a lot of people appreciate quick access to their gists, so I’m opening an issue instead. 😅

**Comment by bfred-it** [comment]
The line above isn’t broken. What can be done is hiding the project tab in the existing feature that hides it from the repos

**Comment by jerone** [comment]
A little CSS fixes it:
```css
.UnderlineNav-item {
    margin-right: 8px;
}
```

Then there is enough room for 17 numbers in the counters...

![image](https://user-images.githubusercontent.com/55841/52487688-72202280-2bbe-11e9-8d86-9e7f080e4ba6.png)

**Comment by bfred-it** [comment]
@jerone that's good, we can also limit that to when there are 7+ items, with a quantity query: https://alistapart.com/article/quantity-queries-for-css
