### ISSUE TITLE
Stops working when navigating files with Octotree

### ISSUE THREAD

**Issue by elreeda** [sindresorhus/refined-github#1759]
[Screen cast](https://monosnap.com/file/eBp2ZUbtzcvY0Bzh0BjqQOznSSb9KK)

**Comment by bfred-it** [comment]
This is OctoTree's fault, they're loading GitHub pages in a custom way and they're not firing [the right event](Refined GitHub is not). OctoTree is likely breaking lots of other extensions

**Comment by jdreesen** [comment]
> OctoTree is likely breaking lots of other extensions

Yes, sadly it is :/

**Comment by elreeda** [comment]
hmm alright then thanks for the clarification.
