### ISSUE TITLE
Thank You!

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#1760]
I know that this maybe a random, however I just have to express my thanks.
Refned Github reached 1000 Commits a few moments ago!
![image](https://user-images.githubusercontent.com/16872793/52486402-07082900-2b89-11e9-9a0f-ce22f272f332.png)

I am an active user of github and this extension has made my work and my life 1000 times easier.

Thank you @sindresorhus!

A special shout out to @bfred-it for all your contributions. I have learned JS just from  your comments and additions!

**Comment by bfred-it** [comment]
Thank you @yakov116 for your contributions!

For anyone who wants to give a hand, we have a [contributing](https://github.com/sindresorhus/refined-github) file with more info and plenty of [good first issues](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+sort%3Areactions-%2B1-desc) to tackle.

**Comment by yakov116** [comment]
Refned Github reached **2000** Commits a few moments ago!

![2020-07-27_153053](https://user-images.githubusercontent.com/16872793/88583408-31b89c80-d01e-11ea-8b14-a098f95d8737.jpg)

A huge shout out to all of refined-github contributers!


Thank you @sindresorhus!

A special shout out to @fregante for your time and patience when working with all of us!

**Comment by yakov116** [comment]
Belated 3000 commits!!

![image](https://user-images.githubusercontent.com/16872793/174160519-4576bd6f-7a40-4555-b31f-c3162c3056bd.png)

Special shout out @cheap-glitch for all your week over the past few months!
