### ISSUE TITLE
Broken tooltip when hovering members in notifications page

### ISSUE THREAD

**Issue by anthony-robin** [sindresorhus/refined-github#1762]
When I hover members picture in a notification I already opened (in another tab for example), the tooltip is half hidden whereas it works fine when the notification is still unread:

<img width="738" alt="capture d ecran 2019-02-09 a 08 13 43" src="https://user-images.githubusercontent.com/5428510/52517962-cae5ce80-2c43-11e9-8123-8f08aca46d71.png">

(Note: 🐛reproduced in both Chrome with refined github `19.2.8.1826` and Safari)

**Comment by bfred-it** [comment]
Refined GitHub is not running on Safari, it's GitHub's own bug
