### ISSUE TITLE
`Original Poster` is implemented by GitHub

### ISSUE THREAD

**Issue by Ash258** [sindresorhus/refined-github#1775]
Today github release update, which add `Author` label to issue / PR comments. `Original poster` label could be removed from Refined Github.

![Proof](https://i.imgur.com/JYi8Eqy.png)

https://twitter.com/github/status/1095749010030129152

https://github.blog/changelog/2019-02-13-comment-author-label/

**Comment by AnthonyLenglet** [comment]
The feature list here is starting to noticeably shrink and I couldn't be any happier, glad to see those features get implemented !

**Comment by bfred-it** [comment]
Closed by #1776
