### ISSUE TITLE
Fix reaction avatars with new GitHub changes

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#178]
GitHub has added Oxford comma to the tooltip for Emoji reactions and more text to the end of it. We'd need to adjust the way we extract usernames from the tooltip.

Example: https://github.com/composer/composer/pull/5174#issuecomment-209524734

The tooltip used to say:
> hkdobrev, nikolas-grekas and Nikofuma

Now it says:
> hkdobrev, nikolas-grekas, and Nikofuma reacted with +1 emoji

Expected result:
We should extract the correct usernames and show avatara for "hkdobrev", "nikolas-grekas" and "Nikofuma".

Actual result:
We show avatars for "hkdobrev", "nikolas-grekas" and "Nicofuma reacted with +1 emoji" which results in a broken image. The problem is reproducible when there are maximum of 3 people reacted.

**Comment by DrewML** [comment]
Huh, looks like you must have caught this super early on after they pushed it - I'm not seeing their updates quite yet.

![image](https://cloud.githubusercontent.com/assets/5233399/14523685/9618d222-01fa-11e6-9160-d84870f26693.png)

**Comment by hkdobrev** [comment]
@DrewML Try on a comment with 3 people reacted and you're one of them.

**Comment by hkdobrev** [comment]
@DrewML OK, it seems they've fixed it back actually. On the same comment, I'm now seeing what you're seeing. It could have been something they've reverted quickly. If you look closely at the message above you'd see it said "reacted with +1 emoji" when people were reacting with the tada emoji 🎉 . So they might have reverted the the change partially to fix it or drop the copy altogether.

I'll close this and we can reopen if they change it back.

**Comment by DrewML** [comment]
Hahaha, @hkdobrev, I went to go react to your reply, and then this happened

![image](https://cloud.githubusercontent.com/assets/5233399/14543691/00e15894-025b-11e6-81bc-cd35887bce93.png)

**Comment by DrewML** [comment]
@sindresorhus Did this ever get pushed to the Chrome store? I just installed this from the Chrome store on a new machine (I normally use the copy from master) and avatars are broken in a similar way.

**Comment by paulmolluzzo** [comment]
@DrewML unless @sindresorhus manually pushed it, no. There hasn't been an automated since we only whitelisted tag branches as of #182 and that hasn't been pushed. Really, if someone just wants to make a v1.0.3 tag and push that to `master` it should deploy. We have #189 in `master` so that's a good reason to deploy on its own.

**Comment by sindresorhus** [comment]
Yeah, go ahead. Hopefully it will work now :)

**Comment by paulmolluzzo** [comment]
Just pushed 1.0.3

**Comment by paulmolluzzo** [comment]
😞  https://travis-ci.org/sindresorhus/refined-github/builds/126706051

I'm pushing a fix directly on `master`. It's not worth all the trouble. I am pretty sure it's the camelCase task name.

**Comment by paulmolluzzo** [comment]
https://travis-ci.org/sindresorhus/refined-github/builds/126708620 🎆 

It probably takes a bit to be publicly visible, but the build passed entirely and looks like it deployed.
