### ISSUE TITLE
Unnecessary offset for filenames in comments

### ISSUE THREAD

**Issue by KarboniteKream** [sindresorhus/refined-github#1784]
Hello!

I'm wondering about this offset: https://github.com/sindresorhus/refined-github/blob/abebd9fc7b9f07d8ea0981b0f6e196ef0c5483ca/source/content.css#L713

![screenshot 2019-02-15 at 14 59 54](https://user-images.githubusercontent.com/1769968/52837513-61c5f580-3132-11e9-8751-1871d7b168b3.png)

If I change it manually to `0px`, it's stickied to the top of the page, which I think is much better.

**Comment by bfred-it** [comment]
I think the offset is due to the sticky header now visible on PRs and Issues, but it shouldn’t be applied everywhere. 

PR welcome to limit the selector for that specific property

**Comment by bfred-it** [comment]
Fixed by GitHub https://github.com/sindresorhus/refined-github/pull/647#issuecomment-474000547
