### ISSUE TITLE
Remove the `delete-fork-link` feature (Implemented by GitHub natively)

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#1786]
https://github.blog/changelog/2019-02-14-prompt-to-clean-up-merged-forks 🎉

Here's how it looks in a PR:

<img width="793" alt="screen shot 2019-02-15 at 14 14 17" src="https://user-images.githubusercontent.com/170270/52840544-317b5880-312c-11e9-9483-8949127d52df.png">

---

See a previous removal on how to do it: https://github.com/sindresorhus/refined-github/commit/e8105c631a11e7fa4022a80e2c47fa5d2145f6f8

**Comment by Ishaan28malik** [comment]
Hey can I work on this ?

**Comment by sindresorhus** [comment]
@Ishaan28malik Go ahead :)
