### ISSUE TITLE
Add "Operator Mono" as <pre>'s default font

### ISSUE THREAD

**Issue by sorrycc** [sindresorhus/refined-github#179]
![image](https://cloud.githubusercontent.com/assets/35128/14524297/3bfc9a24-026a-11e6-88c7-22ec5b2e8d84.png)

**Comment by sindresorhus** [comment]
Maybe we should add the most popular mono programming fonts in order so the user will get the one they have installed?

**Comment by sorrycc** [comment]
```
12px Consolas, "Liberation Mono", Menlo, Courier, monospace
```

This is the font definition which github used. I just think "Operator Mono" is beautify, and suggest if we can change to `12px "Operation Mono" Consolas, "Liberation Mono", Menlo, Courier, monospace`. And it won't affect users who don't have installed this font.

**Comment by sorrycc** [comment]
http://www.typography.com/blog/introducing-operator

**Comment by sindresorhus** [comment]
I really like this idea. I would also include `Droid Sans Mono` which is my favorite code font.

@paulmolluzzo @hkdobrev @DrewML Thoughts?

**Comment by DrewML** [comment]
I like it. If people don't want the font, they can always use a 3rd party extension to inject their own styles and revert the font.

**Comment by paulmolluzzo** [comment]
It's not the font that I use in my terminal, but I'm cool with this. Changing a font because you like it is about as opinionated as it gets. :smile:

**Comment by sindresorhus** [comment]
@paulmolluzzo It would only change if you have the font locally already, which is a good indicator of you wanting it. What font do you use in your terminal? We could potentially include that one too in the definition.

**Comment by paulmolluzzo** [comment]
@sindresorhus that's a good point, I didn't think of that.

I use [Sauce Code Powerline](https://github.com/powerline/fonts)

**Comment by sindresorhus** [comment]
@paulmolluzzo So `Source Code Pro` then.

**Comment by jacobbearden** [comment]
I'm interested in doing this real quick.

So the wanted font stack is `12px "Source Code Pro", "Droid Sans Mono", "Operation Mono" Consolas, "Liberation Mono", Menlo, Courier, monospace`?

**Comment by paulmolluzzo** [comment]
Go for it @jacobbearden!

**Comment by jacobbearden** [comment]
@paulmolluzzo Should it go in `content.css` or `custom.css`?

**Comment by jacobbearden** [comment]
Also, should the font apply to viewing a file/commit? Those do not use a `<pre>`

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo Should it go in content.css or custom.css?

@jacobbearden I think `content.css` is just fine.

> Also, should the font apply to viewing a file/commit? Those do not use a <pre>

Anything that is using monospace should have this applied, otherwise we'll have different monospace fonts and it'll look weird. Any `pre` or `code` tags, and then any other elements with a class that applies monospace, so `.blob-code-inner` is on that list. Whatever makes it consistent.

**Comment by pzi** [comment]
Sorry to go on about this, but the font stack now includes "Operation Mono". Was that intentional @jacobbearden or a typo? @sorrycc was talking about **Operator Mono**. And googling for '"Operation Mono" font' bears no useable results.

**Comment by sindresorhus** [comment]
@pzi That's a typo. Fixed.
