### ISSUE TITLE
Pull requests automatically attempt to merge

### ISSUE THREAD

**Issue by SEAPUNK** [sindresorhus/refined-github#1795]
I noticed that (very recently) when I reload the page on a pull request that is ready to be merged, it automatically opens the merge UI, which breaks some of the PR's UI elements. It's more worrysome because once I disable the extension, the automatic merge functionality persists, until I restart Chrome itself.

Can this be disabled? It's a really bad experience, merging PRs is something I don't want to shortcut by saving a single click.

Before reload:
<img width="787" alt="screen shot 2019-02-15 at 1 03 25 pm" src="https://user-images.githubusercontent.com/4400726/52884976-87e49900-3124-11e9-8558-9559b9f01c07.png">

After reload:
<img width="783" alt="screen shot 2019-02-15 at 1 03 32 pm" src="https://user-images.githubusercontent.com/4400726/52884977-87e49900-3124-11e9-82e3-5f29451d0a48.png">

**Comment by bfred-it** [comment]
If it persists after you disable the extension, then it’s not the extension, it’s GitHub’s own bug

**Comment by SEAPUNK** [comment]
@bfred-it after I disable the extension, however, and restart Chrome, the problem does not happen in the first place. It's a combination of the extension automatically showing the pre-merge UI, and GitHub persisting it after the extension has been disabled.

**Comment by busches** [comment]
The extension doesn't have anything for pre-merge to my knowledge.

**Comment by SEAPUNK** [comment]
Well, I just confirmed that the extension triggers this behavior.

Repro:

Be on Google Chrome (latest) on a brand new profile, have just the extension installed (19.2.15.1830)

- Create a simple repo
- Create a PR on the repo
- Refresh the open pull request page a few times
- Eventually, the merge message UI will show up and persist after you disable the extension

**Comment by SEAPUNK** [comment]
This is what it looks like (note that I have never pressed the "merge pull request" button

<img width="839" alt="screen shot 2019-02-15 at 7 20 29 pm" src="https://user-images.githubusercontent.com/4400726/52893948-e3c81580-3156-11e9-947d-429be767b41b.png">

**Comment by busches** [comment]
Could be a bug from https://github.com/sindresorhus/refined-github/commit/8f20ceeba0c61ca5c2d9ab3cff0d7f1d469efd7a

**Comment by bfred-it** [comment]
Indeed. The form probably stays open after disabling RGH because GitHub remembers it.

I dropped the change. This is kind of weird because that change only change the value of a field, and that doesn't even trigger any events GH listens to. 🤷‍♂️

**Comment by SEAPUNK** [comment]
Thanks for the fix!
