### ISSUE TITLE
Scroll-to-top button in new sticky header

### ISSUE THREAD

**Issue by Stanzilla** [sindresorhus/refined-github#1798]
Ever since GitHub introduced sticky conversation headers (https://github.blog/changelog/2018-12-14-sticky-coversation-headers/), I was thinking a quick way to scroll back to the top would be nice to have. So maybe a button could be added to either the header or a bottom corner of the page?

**Comment by bfred-it** [comment]
The whole bar can be a scroll-to-top button

**Comment by bfred-it** [comment]
`jump-to-bottom` was dropped https://github.com/sindresorhus/refined-github/pull/1879. You can scroll to top by pressing <kbd>⌘</kbd>+<kbd>↑</kbd>

**Comment by Stanzilla** [comment]
I don't agree that this is a good enough reason

**Comment by bfred-it** [comment]
For the record, the issue title in that fixed bar will scroll back to top, so this specific feature has been added by GitHub

<img width="475" alt="" src="https://user-images.githubusercontent.com/1402241/56451189-21b30700-635d-11e9-866f-14c4fb5e5363.png">
