### ISSUE TITLE
Would be nice if I can do multiple selection with keyboard

### ISSUE THREAD

**Issue by j33n** [sindresorhus/refined-github#1801]
I happened to copy a list of items while creating a PR and I had to literally go on each and every line editing. It would be really cool if we could do multiple selection with keyboard. I'm not familiar with the code so I'm not sure how possible this is 🙌

**Comment by jerone** [comment]
"multiple selection" of what?

**Comment by bfred-it** [comment]
Probably Jean wants an editor like CodeMirror in each comment box (that's the only way to get multiple cursors, like https://i.stack.imgur.com/TLZpd.gif)

**Comment by sindresorhus** [comment]
I think this is outside the scope of Refined GitHub and better solved by a dedicated extension like GhostText.
