### ISSUE TITLE
FIXED: Clicking Review Changes flashes the popup and is closed immediately

### ISSUE THREAD

**Issue by nesl247** [sindresorhus/refined-github#1805]
Clicking Review Changes on the files tab of a PR causes it to flash and close immediately. While the extension is enabled, I cannot review any PRs. This happens on any PR that I've tried to review today. My guess is GitHub rolled out some change.

**Version**: 19.2.21.1833

**Comment by lachlancooper** [comment]
I have the same version and issue.

One workaround until this is fixed is clicking "Add your review" on the conversation tab of the PR, which switches to the files tab with the review box already open.

**Comment by pauls-ai2** [comment]
Any idea what filename we can disable in the short term?

**Comment by brandonb927** [comment]
From process of elimination, it looks like this is the culprit PR/commit (https://github.com/sindresorhus/refined-github/pull/1800 ). If you want this to work again, go to the Extension settings and add `close-out-of-view-modals` to the "Features to disable" list.

**Comment by bfred-it** [comment]
Sorry for the trouble! This is fixed in v19.2.22.1531

**Update your extension** in `chrome://extensions/` and you can re-enable `close-out-of-view-modals`

Reopening this for visibility
