### ISSUE TITLE
Add an option to filter PR search by passing/failing/running CI checks

### ISSUE THREAD

**Issue by Zac-HD** [sindresorhus/refined-github#1806]
When a project has many open pull requests, just finding one which is ready for review can be tricky.  For example, [pytest](https://github.com/pytest-dev/pytest/pulls) and [matplotlib](https://github.com/matplotlib/matplotlib/pulls) would both find this useful, along with smaller projects.  Terrible mockup:

![image](https://user-images.githubusercontent.com/12229877/53211679-342efe00-3696-11e9-9049-f0f5421540c1.png)

I know I'd love to be able to filter down to just the PRs with passing tests to review, or tests+approval to merge, or ...  You get the idea.  No idea why this doesn't already exist, so Refined Github seemed the place to suggest it 😄

**Comment by busches** [comment]
Is this something you can search GitHub for?

**Comment by bfred-it** [comment]
> Is this something you can search GitHub for?

Yep. It's not even in the help pages or the search page, but it's been there for almost 4 years: 

https://github.blog/2015-06-02-filter-pull-requests-by-status/

Demo passing: https://github.com/sindresorhus/refined-github/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+status%3Asuccess

**Comment by jarl-dk** [comment]
It's great that the feature exists.

I wonder why this is not documented on https://docs.github.com/en/github/searching-for-information-on-github/searching-on-github/searching-issues-and-pull-requests

**Comment by dannysauer** [comment]
It's currently in the docs, for anyone who stumbles across this.
https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-commit-status
