### ISSUE TITLE
GitHub new feature "Reference in new issue" not working when the extension is enabled

### ISSUE THREAD

**Issue by mmarchini** [sindresorhus/refined-github#1807]
**Browser**: Google Chrome 72.0.3626.109
**OS**: Mac OS X
**Extension**: 19.2.21.1833

GitHub added a new option `Reference in new issue` in the comments context menu:

![image](https://user-images.githubusercontent.com/4048656/53243733-97fdfa80-3687-11e9-9512-9aeb3c0ffa80.png)

When clicked, it should open a modal:

![image](https://user-images.githubusercontent.com/4048656/53243797-c4197b80-3687-11e9-883a-9ed2a24cfd47.png)

With Refined GitHub enabled, the modal won't open. Disabling the extension fixes the issue.

I saw this behavior in [this comment](https://github.com/iovisor/bpftrace/issues/218#issuecomment-461724193), but it's likely happening on any comment.

**Comment by busches** [comment]
Same issue as root cause of #1805, the feature to disable is listed there.

**Comment by mmarchini** [comment]
Thanks!
