### ISSUE TITLE
Show Notifications Summary when hovering over notification icon

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#181]
I could have sworn GitHub used to do this, but maybe I'm thinking of Facebook.

This is a nitpick for sure, but when I have new notifications, having to do a full page nav just to see if I care about any of them is a bit of a pain. Would be nice to fetch/render a preview when hovering over the icon, when it shows new notifications.

**Comment by DrewML** [comment]
If there happens to be interest, I have a rough cut of this going. We'd obviously have to change the UI up a bit (it's way too wide right now). Good news is, GitHub JS on pages other than the notifications page still works, so you can mark as read or unsubscribe without a page change.

![image](https://cloud.githubusercontent.com/assets/5233399/14548296/268fa986-027b-11e6-8dc8-5d9268cc663a.png)

**Comment by paulmolluzzo** [comment]
This is super cool looking. I happen to use my email inbox for managing notifications (like inbox 0 without the dogma), so this won't be much of a game changer for me, but I still dig it.

About the design, I don't think you're going to get away with anything too much narrower than that. It can already use some left/right padding for the date.

**Comment by sindresorhus** [comment]
Cool idea. Not yet sure whether I would use it or not, but I think it's worth exploring.

**Comment by bfred-it** [comment]
This should probably be its own extension, it'd be a pretty big feature to maintain.

**Comment by sindresorhus** [comment]
@bfred-it Could you move it to https://github.com/sindresorhus/module-requests/issues ? Maybe we should also have a link to it in the readme for discovery? Same with https://github.com/sindresorhus/module-requests/issues/99

**Comment by bfred-it** [comment]
It's happening: https://github.com/tanmayrajani/notifications-preview-github

![screenshot](https://github.com/tanmayrajani/notifications-preview-github/raw/master/media/screenshot.png)
