### ISSUE TITLE
Add option to hide Projects tab from my GitHub profile

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1810]
Recently GitHub added the `Project` tab to everybody profile. For me, it is a completely useless thing. If I would like to do something like this `"Projects"`, I would definitely use Trello, which is on business of `"Projects"` much time before GitHub trying to put his nose into it.

![image](https://user-images.githubusercontent.com/5332158/53293225-9b3fd600-37ae-11e9-84d4-de02ed19511d.png)

Related:
1. https://github.com/sindresorhus/refined-github/issues/984 Hide "Projects" tab on Organization page
1. https://github.com/sindresorhus/refined-github/issues/1757 New “Projects” tab messes up profile if “gists” tab enabled

**Comment by bfred-it** [comment]
Are you using the latest version? This was already done several days ago

https://github.com/sindresorhus/refined-github/pull/1788

<img width="1023" alt="screenshot 2019-02-24 at 11 16 32" src="https://user-images.githubusercontent.com/1402241/53294653-a8e47280-3825-11e9-86d5-469e08894a15.png">

**Comment by evandrocoan** [comment]
I am not sure how, but I already had added `remove-projects-tab` to the ignore settings list. Then, I just removed and it is working now. Thanks!
