### ISSUE TITLE
PR review dialog doesn't appear

### ISSUE THREAD

**Issue by sh7dm** [sindresorhus/refined-github#1816]
URL: N/A
Reproduction:
1. Go to PR page
2. Click review button

Fixed after disabling `quick-review-buttons` via config, but I haven't got quick review buttons now :sob: 
Browser: FF 64
Broken after GH update
Extension version: `19.2.27.1835`, last updated on 28 February.
Please fix :pray:

**Comment by sh7dm** [comment]
And it looks like menu appears and disappears just after appear. Sorry for my English :smiley:

**Comment by bfred-it** [comment]
Can't reproduce the bug, try refreshing the page or restarting, maybe you still have an old version running in that tab. This bug was fixed a few days ago: https://github.com/sindresorhus/refined-github/issues/1805

**Comment by sh7dm** [comment]
@bfred-it is it fixed?

**Comment by bfred-it** [comment]
> Can't reproduce the bug,
