### ISSUE TITLE
Collapse/hide deleted files by default

### ISSUE THREAD

**Issue by itaranto** [sindresorhus/refined-github#1817]
I would be nice if deleted files were not shown by default in the diff and PR views, just like Github does with renamed files or with LFS files.

If hiding the content is not possible, at least collapse them by default.

Thanks.

**Comment by bfred-it** [comment]
For reference, this is what it looks like by default

<img width="1211" alt="" src="https://user-images.githubusercontent.com/1402241/53646910-54068900-3c77-11e9-89c8-24add685b517.png">

**Comment by sindresorhus** [comment]
@itaranto It's not clear how what you want is different from what @bfred-it showed above?

**Comment by itaranto** [comment]
> @itaranto It's not clear how what you want is different from what @bfred-it showed above?

That's nice, although I don't remember seeing it for non-PR diffs. Let me check that.

**Comment by itaranto** [comment]
I tested this in Enteprise Github 2.13 with both a regular diff and a PR diff, and it's seems not to be working (deleted files are not collapsed).

I already enabled the add-on selecting "Enable Refined Github on this domain".

Also, I'm using Firefox 65.0.2.

**Comment by bfred-it** [comment]
> it's seems not to be working (deleted files are not collapsed).

That may be an old version. It's not a feature of RGH, it's native from GitHub.

PR example: https://github.com/sindresorhus/refined-github/pull/1831/files#diff-51b6bc4d9e03fdb37ae07b9f2fa96e3e

Commit example: https://github.com/sindresorhus/refined-github/commit/10a6b30c335e2d196b33d8eb8d8b0d6576f94372#diff-51b6bc4d9e03fdb37ae07b9f2fa96e3e

**Comment by itaranto** [comment]
I'm seeing the diff of the deleted file in both cases.
So, I guess it's a Github bug then.

**Comment by bfred-it** [comment]
Are you sure you don't have a conflicting GitHub extension?
