### ISSUE TITLE
Refined GitHub version history: compatibility with versions of Firefox

### ISSUE THREAD

**Issue by grahamperrin** [sindresorhus/refined-github#1819]
Somewhere between (not within) these two records: 

1. https://web.archive.org/web/20181002162604/https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/ (ending at 18.9.28.1714)  
2. https://addons.mozilla.org/addon/refined-github-/versions/ ([no longer allowing more than 25 versions](https://github.com/mozilla/addons-frontend/issues/7542))

– there'll be the last version that was compatible with Firefox 56 (or _55.0 and later_). 

Please, can you tell which version? Plus a link to the `.xpi`, if you can. 

Thanks

**Comment by grahamperrin** [comment]
(Sorry, the _bug_ label was not intended; I can't remove it.)

**Comment by bfred-it** [comment]
What version of Firefox do you need exactly? And why are you on an old version of Firefox?

**Comment by grahamperrin** [comment]
Thanks for identifying the commits. 

I have [Waterfox](https://www.waterfoxproject.org/) 56.2.7.1. Waterfox 56.0 was based on Firefox 56.0. 

Re: <https://redd.it/aw8rqm> whilst I happily use slightly outdated 19.1.31.1822 (for Firefox 61.0 and later, not expecting full compatibility with Waterfox 56.x), _other_ users of Waterfox might prefer the most recent version of the extension that was compatible with Firefox 56. 

I'll raise a question in the Mozilla area. If we can be given a real-world  example of how to use the API – resulting in an AMO link to the required `.xpi` – then future situations such as might become less complicated for people (like me) who are not developers …

**Comment by bfred-it** [comment]
There's no other way to get the xpi, we don't save each version. You can find the URLs on Wayback. To download them, strip everything before the second `https` in the URL:

```

https://web.archive.org/web/20181002162604/https://addons.mozilla.org/firefox/downloads/file/1092770/refined_github-18.9.28.1714-an+fx.xpi?src=version-history

Becomes:

https://addons.mozilla.org/firefox/downloads/file/1092770/refined_github-18.9.28.1714-an+fx.xpi?src=version-history
```

The commit I mentioned was on version 18.12.30

**Comment by bfred-it** [comment]
Also: https://blog.mozilla.org/firefox/firefox-64-default-64-bit-windows/

I don't suggest using a browser based on Firefox 56 (released on September 28, 2017)

**Comment by grahamperrin** [comment]
Thanks, Waterfox is patched for MFSAs and so on. 

> You can find the URLs on Wayback. 

Unfortunately not for what's required here, that's why I began the opening post with a Wayback Machine link. 

There's a slim possibility that someone captured a non- `en-US/` variation of the required page at the required point in time, but this is _very_ slim. https://web.archive.org/web/*/https://addons.mozilla.org/en-GB/firefox/addon/refined-github-/versions/ captured only once (by me), and so on.

**Comment by grahamperrin** [comment]
I experimented with https://addons.mozilla.org/firefox/downloads/file/1092770/refined_github-18.12.30-an+fx.xpi but this results in version 18.9.28.1714 (not version 18.12.30).

**Comment by grahamperrin** [comment]
Lateral thinking, I installed an overly outdated version then looked to see what might be found with a check for updates. 

Found: **18.12.22.1803**

![image](https://user-images.githubusercontent.com/192271/53695374-d051b700-3db2-11e9-960c-7f309130ecf5.png)

I can't tell the URL of the `.xpi`, but it's one way to get _close to_ 18.12.30.
