### ISSUE TITLE
Contributor guide instructions should be updated

### ISSUE THREAD

**Issue by snowe2010** [sindresorhus/refined-github#1821]
The contributor/getting started guide states to create a feature that will be loaded on every page, but fails to mention that you need to add the import for the file to `content.ts`

**Comment by bfred-it** [comment]
Thank you for the report! The mention was there but it pointed to the old pre-typescript file. I updated the link now.

> Each JavaScript feature lives in its own file under source/features and it's imported in source/content.js.
