### ISSUE TITLE
Mention autocomplete inserts \t

### ISSUE THREAD

**Issue by cpojer** [sindresorhus/refined-github#1826]
When mentioning people in a comment and autocompleting with the tab-key instead of pressing enter, the refined-github extension inserts both a `\t` and a space instead of just a space. Disabling the extension only inserts a space.

**Comment by bfred-it** [comment]
This should normally be prevented but for some reason this isn't working. The class seems to be unchanged

https://github.com/sindresorhus/refined-github/blob/67d3ed78c6e8b7e471c4222c83513cff9cf288fb/source/features/comment-fields-keyboard-shortcuts.tsx#L25-L28

**Comment by bfred-it** [comment]
Can no longer reproduce

**Comment by cpojer** [comment]
Thanks! Does seem indeed like it was fixed between last week and now :)
