### ISSUE TITLE
Branch name is missing in "created a new branch" dashboard entry

### ISSUE THREAD

**Issue by nesl247** [sindresorhus/refined-github#1827]
Prior to the dashboard redesign the entry was simply stripped out. It doesn't make sense to me now since the entry is there, but there is no context of what the branch is.

**Comment by bfred-it** [comment]
Please provide a screenshot

**Comment by nesl247** [comment]
Here you go:

![image](https://user-images.githubusercontent.com/1037526/53815318-71fe1300-3f2f-11e9-9a1d-a36002d2e78c.png)

![image](https://user-images.githubusercontent.com/1037526/53815387-93f79580-3f2f-11e9-9fc2-0395d887d55b.png)

**Comment by bfred-it** [comment]
#1824 may or may not fix it
