### ISSUE TITLE
Provide a shortcut for "your" issues?

### ISSUE THREAD

**Issue by ben-eb** [sindresorhus/refined-github#183]
Find myself typing this search term in a lot, think it would be beneficial to have a shortcut for it, something like this?

<img width="1102" alt="screen shot 2016-04-19 at 11 35 41" src="https://cloud.githubusercontent.com/assets/1282980/14636384/0d8770e4-0623-11e6-8520-2054bece2771.png">

https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Aben-eb+

**Comment by sindresorhus** [comment]
Similar to https://github.com/sindresorhus/refined-github/issues/153.

I like the idea of a `Todo` link, but I think it should be both issues and PRs.

-

@paulmolluzzo @hkdobrev @DrewML ?

**Comment by paulmolluzzo** [comment]
Just to be clear, the Todo list is "Issues you are assigned to"? Would (Could...?) that include PRs?

**Comment by sindresorhus** [comment]
@paulmolluzzo I was thinking it's open issues and PRs in your repos, but it's a good idea to include stuff you're assigned to too. Maybe only include issues you haven't yet commented on?

**Comment by ben-eb** [comment]
Sorry if it wasn't clear, the 'Todo' link is from ZenHub. :)

https://www.zenhub.io

**Comment by paulmolluzzo** [comment]
Just to circle back around on this: The suggestion is that button group for Created, Assigned, Mentioned, Yours.

What are everyone's thoughts on that idea? @sindresorhus?

**Comment by sindresorhus** [comment]
Oh, I get it now. I like that.

@paulmolluzzo Created, Assigned, Mentioned are already there.

**Comment by paulmolluzzo** [comment]
@sindresorhus I have a "Filters" dropdown.

**Comment by sindresorhus** [comment]
@paulmolluzzo Are you sure we're looking at the same thing? Could you share a screenshot?

**Comment by paulmolluzzo** [comment]
@sindresorhus I was looking at the issues for a specific repo, so that was the confusion.

![screen shot 2016-04-27 at 4 03 09 pm](https://cloud.githubusercontent.com/assets/737065/14866404/9be72388-0c91-11e6-9f5f-c9e62969bd09.png)

**Comment by paulmolluzzo** [comment]
Also, I'm not working on this at all, so this is still open to someone else taking on.

**Comment by sindresorhus** [comment]
Yeah, this is an easy one, so let's leave it up to some external contributors.

**Comment by jacobbearden** [comment]
Should there also be one for pull requests?

**Comment by jamestalmage** [comment]
FYI, https://github.com/jamestalmage/gh-nag does this already. This proposal would do so with less clutter.

**Comment by sindresorhus** [comment]
> Should there also be one for pull requests?

Yes, on the [pull request page](https://github.com/pulls).

**Comment by jacobbearden** [comment]
I've got this mostly done on my [fork](https://github.com/jacobbearden/refined-github/tree/your-issues), but I'm a little lost on handling highlighting (`.select`) as I can't recognize a consistent pattern it uses.

**Comment by sindresorhus** [comment]
@jacobbearden Open a PR and we can take it from there. Easier to give review and answer question when we have some context ;)

**Comment by Mottie** [comment]
In case anyone is interested, I created a userscript that allows you to customize the header icons

https://greasyfork.org/en/scripts/20830-github-custom-navigation

GitHub
![github-custom-navigation-after](https://cloud.githubusercontent.com/assets/136959/16217335/1aaa6970-3738-11e6-9791-4e1c1f61f8d3.png)

Gist 
![github-custom-navigation-gist-after](https://cloud.githubusercontent.com/assets/136959/16217822/bc0b27f6-373c-11e6-861c-33dedd68a0c2.png)

Drag and drop to customize
![github-custom-navigation-usage](https://cloud.githubusercontent.com/assets/136959/16253396/eac0039a-37fb-11e6-8200-5e727915297c.gif)
