### ISSUE TITLE
PR review tools covers file actions when scrolling

### ISSUE THREAD

**Issue by matthieubouchard** [sindresorhus/refined-github#1841]
1. Make sure the bug is caused by Refined GitHub. Try disabling the extension first.
File actions was covered when scrolling down the page by the pr-review-tools container of buttons. Updated the margin so that both file actions (copy path, view file, edit etc remains clickable when scrolling down the page.

2. Include a URL where the bug appears.
This occurs on the 'files changed' tab when reviewing a PR. I'm verified this change works using the chrome extension source viewer.

**Comment by matthieubouchard** [comment]
CSS fix. The pr-review tools container covers file actions when scrolling down the page on the 'files changed' tab when reviewing a PR.

**Comment by bfred-it** [comment]
Are you talking about this? It works for me

![d](https://user-images.githubusercontent.com/1402241/54327605-a8c9dc80-4645-11e9-8f3b-29ae7b3b8c47.gif)
