### ISSUE TITLE
Full names next to usernames are no longer displayed

### ISSUE THREAD

**Issue by rzpio** [sindresorhus/refined-github#1842]
Hey,

since when are the full names no longer displayed next to the username? Has the function been removed because of the hover card? If so, then the line in the README.md would have to be deleted. Tested under GNU/Linux and Windows.

> Full names of comment authors are shown next to their username.

![screenshot](https://user-images.githubusercontent.com/33252305/54068901-ccf67980-4251-11e9-8c66-c37f9d280f8b.PNG)

**Comment by jerone** [comment]
For me everything still works...

![image](https://user-images.githubusercontent.com/55841/54071435-bf022200-426c-11e9-9457-e48c45199435.png)

You have some other extension/userscript conflicting?

**Comment by notlmn** [comment]
@rzpio they are not displayed by default if the comment or action is performed by __you__. You won't see your name displayed by your username.

Is that what you are seeing?

**Comment by rzpio** [comment]
Haha, the example was perhaps chosen somewhat unluckily. 🤣 No, I don't see the full name for others either. I have not activated any other extensions or user scripts. Works neither in Firefox nor in Brave.

![screenshot](https://user-images.githubusercontent.com/33252305/54072349-0347ef00-427a-11e9-8ea9-9e9adf296e65.PNG)

**Comment by jerone** [comment]
This feature is using [GraphQL API v4](https://github.com/sindresorhus/refined-github/blob/master/source/features/show-names.tsx#L30). Did you added an [API token](https://github.com/sindresorhus/refined-github/blob/2d1019c84da36c749357627304c221f6b399c1d5/source/options.html#L25)? If not, maybe you hit your [GraphQL API resource limitations](https://developer.github.com/v4/guides/resource-limitations/).

**Comment by rzpio** [comment]
I didn't add a token. I'm not familiar with the API, but I don't think I've reached the limit in my home network. I probably can't see how many points I've used for the API anywhere, can I?

**Comment by jerone** [comment]
Try to create one (instructions are in the Settings of GitHub Refined) and see if it solves your problem.

**Comment by rzpio** [comment]
Yeah, it worked. Thank you very much, @jerone! Interesting, some time ago it worked without a token.

**Comment by jerone** [comment]
Oh and you can check your rate limit [here](https://developer.github.com/v4/explorer/?variables=%7B%7D&query=query%20%7B%0A%20%20viewer%20%7B%0A%20%20%20%20login%0A%20%20%7D%0A%20%20rateLimit%20%7B%0A%20%20%20%20limit%0A%20%20%20%20cost%0A%20%20%20%20remaining%0A%20%20%20%20resetAt%0A%20%20%7D%0A%7D).

**Comment by jerone** [comment]
[**@rzpio**](https://github.com/rzpio) commented on [Mar 9, 2019, 4:51 PM GMT+1](https://github.com/sindresorhus/refined-github/issues/1842#issuecomment-471193413 "2019-03-09T15:51:58Z - Replied by Github Reply Comments"):
> Yeah, it worked. Thank you very much, [@jerone](https://github.com/jerone)! Interesting, some time ago it worked without a token.

Great. The more you work on GitHub, the more API calls you do. There are multiple API call in GitHub Refined. At some point that might add up. But with the token you should be fine.

**Comment by rzpio** [comment]
> Oh and you can check your rate limit here.

Cool, I didn't know that.

> Great. The more you work on GitHub, the more API calls you do. There are multiple API call in GitHub Refined. At some point that might add up. But with the token you should be fine.

Ah, that could explain that. Thanks for the help. :smile:
