### ISSUE TITLE
Conflation between more-dropdown and extra tab links

### ISSUE THREAD

**Issue by mxmilkb** [sindresorhus/refined-github#1844]
I'm not keen on the extra click required more-dropdown adds to the process of navigating, but I am in favour of having extra links to navigate a project with.

I feel that there is a conflation of concerns here - adding extra links to a projects 'tabs', and hiding those extra links in a dropdown menu.

Might it be possible to separate these changes out?

**Comment by mxmilkb** [comment]
(I don't remember adding a 'bug' label? Can I even do that by accident? It's entirely arguable as to whether this is a bug report or a feature request, so personally I'd say it's not worth trying to classify it either way)

**Comment by busches** [comment]
Can you clarify what you're after? You don't like the more drop-down but still want all the links it offers?

**Comment by mxmilkb** [comment]
Yes, that's it. Possibly, if there is worry of a performance hit, the extra links can be in the drop down menu by default, but disabling the menu could put the extra links beside the other tab links?

**Comment by busches** [comment]
You can disable the feature and the links won't move there, but the extra links we add won't go in the top bar. You'd have to fork and code that up. Hope that helps.

**Comment by mxmilkb** [comment]
Fair enough.
