### ISSUE TITLE
filter/search bar for issues/pr's at github overlays buttons

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#1845]
Addon version: 19.3.8.1841

The `Label` and `Milestones` are overlayed... and the `New issue` button is semi covered.
Shouldn't the buttons be pushed to the side, or at least the overlay look nicer for all resolutions?
I'm running on 1366x768 by the way.

![filter bar](https://user-images.githubusercontent.com/9874850/54086580-d9123200-434a-11e9-9133-6ac758433044.png)

**Comment by bfred-it** [comment]
That's a feature, the search field only expands when it's focused. Click outside and it will become smaller

**Comment by tooomm** [comment]
I know that it's a feature. But shouldn't it expand to all right then at least (matching the table with the listed issues), and cover all `New issue` button at least?
Or only expand to right before the button?

**Comment by bfred-it** [comment]
I think this feature actually depends on the font. On macOS it looks correctly but on your OS (Win?) "Filters" is about _that much_ shorter.

I was actually working on making the field larger for all, just to fit the empty space we have on that line. That should fix it correctly (via `display: flex`) but it's slightly more complicated. https://github.com/sindresorhus/refined-github/tree/wider-search-field

**Comment by tooomm** [comment]
I'm on Windows with Firefox, yes.

Happy to see you looking into further improvements for all platforms. 👍
