### ISSUE TITLE
Turn GitHub's native "Delete branch" & "Delete fork" toggle into 2 single-click links

### ISSUE THREAD

**Issue by katrinleinweber** [sindresorhus/refined-github#1846]
As suggested in https://github.com/sindresorhus/refined-github/pull/1791#issuecomment-470229212, #1786 might have been implemented prematurely, because GitHub's design requires more clicks than the removed `delete-fork-link`.

Having no working experience with [this addon's notions](https://github.com/sindresorhus/refined-github/blob/master/contributing.md#notions), please let me summarize @bfred-it's reply there as an FR here:

1. "make both buttons visible"
1. "unhide the Delete Fork button via CSS only"
1. "make it look like the old text link"

**Comment by sindresorhus** [comment]
I agree, it should have been two buttons natively.

**Comment by katrinleinweber** [comment]
Thank you :-)
