### ISSUE TITLE
Options modal dialog blinking/glitching in Chrome

### ISSUE THREAD

**Issue by kvolkovich-sc** [sindresorhus/refined-github#1847]
OS: Ubuntu 18.04
Browser: Chrome Version 70.0.3538.77 (Official Build) (64-bit)

**See attached GIF**

![github-refined-resize](https://user-images.githubusercontent.com/24652543/54088314-d412aa00-436d-11e9-836f-d80889ce3220.gif)

Sorry, I can't try it on another OS.
Firefox is OK.

**Comment by bfred-it** [comment]
Chrome bug, we probably can't do much about it. If you can, try dropping the `min-width` from `body` and perhaps setting it to `html`. If that fixes the issue, good. If not, https://www.chromium.org/issue-tracking

**Comment by kvolkovich-sc** [comment]
Looks like `body` => `html` swap of `min-width` works normally.

**Comment by bfred-it** [comment]
Do you mind sending a PR?
