### ISSUE TITLE
Watcher and fork tallies are missing.

### ISSUE THREAD

**Issue by wlandau** [sindresorhus/refined-github#1850]
They come back when I disable/remove the extension on Firefox and Chrome.

![Capture](https://user-images.githubusercontent.com/1580860/54125816-6ce00e80-43dc-11e9-9235-4a6874953ef8.PNG)

**Comment by yakov116** [comment]
@wlandau #1843

**Comment by sindresorhus** [comment]
Duplicate of #1843

**Comment by wlandau** [comment]
Ah, thanks @yakov116.
