### ISSUE TITLE
Add personal "Projects" link to GitHub header menu

### ISSUE THREAD

**Issue by camillevilla** [sindresorhus/refined-github#1852]
Hi! [User-owned project boards](https://github.blog/2019-02-07-user-owned-projects-your-personal-workspace/) are still a relatively new feature, but it would nice to have quick access to these in the GitHub header menu (`.HeaderMenu`). Adding a "Projects" link that goes to `https://github.com/{username}?tab=projects` would be great. 

### Current UI
![main GitHub header menu](https://user-images.githubusercontent.com/5402927/54222678-1b568300-44b3-11e9-9ff6-6600f0f63827.png)

### Proposed UI
![main GitHub header menu with Projects link](https://user-images.githubusercontent.com/5402927/54222677-1abdec80-44b3-11e9-9b74-7d7160824c49.png)

### The problem
For now, personal project boards don't show up in global search. In the search below, I was able to pull up a project board associated with a repo, but I can't find personal project boards. 

![GitHub global search showing "Mirador 3" project board](https://user-images.githubusercontent.com/5402927/54223072-f6aedb00-44b3-11e9-989d-5717ded0837b.png)

I execute a search and can't select projects from the filtering options. 
![GitHub global search results displaying several filtering options (e.g. commits, issues)](https://user-images.githubusercontent.com/5402927/54223080-fa426200-44b3-11e9-9a6d-5f8e3fdf4be0.png)

To use personal project boards I need to go to my profile and select from these options that don't have a huge bearing on my day-to-day workflow.
![Current location of "Your projects" highlighted](https://user-images.githubusercontent.com/5402927/54225962-02050500-44ba-11e9-96d0-85b32f65459c.png)

Thanks for your consideration. And thank you to the maintainers + community for making such a useful browser extension!

**Comment by bfred-it** [comment]
The Projects link is already 2-clicks away on every page, this wouldn't be a big improvements. 

Additionally, projects are used relatively little and Refined GitHub actually [hides references to them](https://github.com/sindresorhus/refined-github/blob/master/source/features/remove-projects-tab.tsx) whenever possible.
