### ISSUE TITLE
Convert the repository homepage to an overview tab

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#1855]
This might be a bit much for Refined GitHub, but it would be cool if repository homepages were more of a stripped-down overview:

![Screenshot 2019-03-13 at 13 10 15](https://user-images.githubusercontent.com/25517624/54299644-b45bcb80-4591-11e9-8143-dacb938c17b3.png)

Then, the “Code” tab could link to `https://github.com/:user/:repo/tree/:default_branch` and display just the code:

![Screenshot 2019-03-13 at 13 12 36](https://user-images.githubusercontent.com/25517624/54299703-d1909a00-4591-11e9-9ace-c4b838e5d16d.png)

This mirrors the behavior of the mobile version of the site, except it takes advantage of the extra available space on desktop computers to show the entire README instead of an excerpt. This also creates an opportunity to display more information on the repository overview page.

The [`/tree/:default-branch` page](https://github.com/sindresorhus/refined-github/tree/master/) currently looks identical to the repo homepage.

What do you think?

**Comment by bfred-it** [comment]
> This might be a bit much for Refined GitHub

Indeed

**Comment by bfred-it** [comment]
Creating a whole new view is too hard, especially to maintain, given the recent frequent changes by GH
