### ISSUE TITLE
Tabnav overlay on PR page

### ISSUE THREAD

**Issue by rohmanhm** [sindresorhus/refined-github#1857]
When you have very long git diff history I think it'll be nice if we have overlay tabnav PR on top, so it's more easy to switch between `Conversation`, `Commit`, `Checks`, and `Files` rather than just scroll to top to switch between those.

![image](https://user-images.githubusercontent.com/7524911/54337534-c442e080-4661-11e9-8a38-e8d2183360a0.png)

**Comment by bfred-it** [comment]
I think it would become too tall and complex to stack 3 lines (tabs, issue header, file header)

**Comment by rohmanhm** [comment]
Yeah I agree with you @bfred-it .

Maybe we could do with different approach like we positioning it on the left or we will have settings for `refined-github` so the user can choose what refined features the would to enabled/disabled.

But option number 2 seems too complicated to be implemented.

I don't know maybe you have a better idea.

**Comment by nesl247** [comment]
Maybe a scroll to top button would work?

**Comment by bfred-it** [comment]
#1798

**Comment by bfred-it** [comment]
Closing because we can't handle 3 lines. Press `Home` or `cmd+up` to scroll to the top
