### ISSUE TITLE
Automatically expand all textareas

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1862]
Having to scroll a 200px-tall textarea with pasted-content (code, logs) is awful.

GitHub actually fits most comment boxes to their content, up to a limit. I looked into the code and there's no way to remove the limit, but thankfully we just have to drop the `js-size-to-fit` class and use [fit-textarea](https://github.com/bfred-it/fit-textarea):

<img width="361" src="https://user-images.githubusercontent.com/1402241/54336211-66fd5e00-4666-11e9-9c5e-111fccab004d.gif">

Same applies to CodeMirror instances, but the change is probably a matter applying some CSS (as part of the same JS feature)

**Comment by sindresorhus** [comment]
Yes, would be useful, but I would still want RG to increase the default height of textareas.
