### ISSUE TITLE
Button (visual) issues in notifications

### ISSUE THREAD

**Issue by jaymickey** [sindresorhus/refined-github#1865]
On the [notifications](https://github.com/notifications) page the `Open all unread in tabs` and `Mark all as read` buttons have no padding between each other, and the `Mark all as unread` button seems to get cut off on the right hand side. I've included an image.

**Browser**: Chrome 73
**Refined GitHub Version**: 19.3.17.1846

![image](https://user-images.githubusercontent.com/7720995/54566903-153c3700-49ca-11e9-97a2-d60e0ef5b2ec.png)

**Comment by bfred-it** [comment]
They might have changed some classes or positions. `groupButtons` may need a fix
