### ISSUE TITLE
Auto-expand auto-linked issues to display title.

### ISSUE THREAD

**Issue by markdorison** [sindresorhus/refined-github#1867]
I'd love to have auto-linked issues be expanded to display the title of the issue.

## Screenshot
![image](https://user-images.githubusercontent.com/20355/54709874-c4892300-4b1c-11e9-82ea-773f6107e8b1.png)

**Comment by bfred-it** [comment]
That's too much injected content. The title already appears on hover thanks to GitHub's new popup

**Comment by jerone** [comment]
I like the way Azure DevOps does it...

![image](https://user-images.githubusercontent.com/55841/54881845-9ecd8800-4e54-11e9-8b07-1322eb462801.png)
