### ISSUE TITLE
Change fork button number link dest to Network page?

### ISSUE THREAD

**Issue by mxmilkiib** [sindresorhus/refined-github#1869]
IIRC this was the original GitHub behaviour. Much more useful to see what forks are active by which users and how they are connected, rather than see just a list of users who have created a fork.

**Comment by bfred-it** [comment]
In a recent version we hid the number, so this feature would be the opposite of what we have.

**Comment by mxmilkb** [comment]
It would be different to how it is now but it would still be a change from the GH default.

In the comment regarding hiding it, it was said not to be useful (as a link to /network/members). I'm suggesting that having it instead as a 'one click path from the project main page' to /network would actually be useful in terms of reducing user actions to get to /network, which, and I might be going out on a limb here, is one of the most handy of pages; for checking out project history, branches, fork divergence, etc.

Maybe others feel the same way? Or maybe most don't care?

**Comment by bfred-it** [comment]
They deprecated that page 😅 https://github.blog/changelog/2019-05-01-deprecating-the-network-graph

**Comment by mxmilkb** [comment]
That link is a 404 (Twitter chat says it was a 404 three days ago)? (My initial thought is that there was such an outcry that they reversed the decision.)

**Comment by yakov116** [comment]
@bfred-it 
>That link is a 404 (Twitter chat says it was a 404 three days ago)? (My initial thought is that there was such an outcry that they reversed the decision.)

https://github.com/sindresorhus/refined-github/network

**Comment by rachmadaniHaryono** [comment]
https://github.community/t5/How-to-use-Git-and-GitHub/Network-Graph-Missing/m-p/23048#M6679

**Comment by fregante** [comment]
Reopening this for discussion since we partially undid this feature: https://github.com/sindresorhus/refined-github/pull/4249

Still valid? Wanted? Thoughts?

**Comment by carlosedp** [comment]
Since GitHub recently removed the link to network... can this be re-added?
Sorry about being late to the discussion.
Thanks!

**Comment by fregante** [comment]
Even before, we had a feature to drop the number, so we won't add it now. 

Anyway there's now a link to stars, watchers, forks on the main repo tab, inclusive of number.
