### ISSUE TITLE
Copy File is missing again

### ISSUE THREAD

**Issue by jordanbtucker** [sindresorhus/refined-github#1875]
The [copy file feature](https://cloud.githubusercontent.com/assets/170270/14453865/8abeaefe-00c1-11e6-8718-9406cee1dc0d.png) is missing again.

![copy-file-missing](https://user-images.githubusercontent.com/468153/54836420-2919be80-4c92-11e9-84b9-444953ed749d.png)

**Comment by bfred-it** [comment]
Thanks for the report! Lately GH has been changing the UI a lot and I'm sure lots of features will be breaking
