### ISSUE TITLE
Mark as unread button is missing on the issue/PR page

### ISSUE THREAD

**Issue by ilyam8** [sindresorhus/refined-github#1884]
Not sure this is a bug or not, i guess it is.

I see it in [highligths](https://github.com/sindresorhus/refined-github#highlights)

refined-github v:19.3.25.1851
___

![Screenshot_20190326_153030](https://user-images.githubusercontent.com/22274335/54997273-69ec3d00-4fdc-11e9-9fa0-beb841c41dcc.png)

**Comment by bfred-it** [comment]
Thanks for the report! They had changed a class name

**Comment by ilyam8** [comment]
Thanks for the quick fix :+1: 	

It would be nice to have browser extension updated asap, lack of `Mark as unread` button is very annoying, i use it a lot.

**Comment by bfred-it** [comment]
Coming hot https://github.com/sindresorhus/refined-github/releases/tag/hotfix

**Comment by ilyam8** [comment]
you rock @bfred-it
