### ISSUE TITLE
Add Solarized color palette

### ISSUE THREAD

**Issue by szepeviktor** [sindresorhus/refined-github#1885]
Please add Solarized as an option.
https://ethanschoonover.com/solarized/

GitLab uses it as a default
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/.gitlab-ci.yml

Thank you for considering.

**Comment by szepeviktor** [comment]
See https://github.com/jrunning/github-solarized

any problems are - I think - solved in GitLab

**Comment by bfred-it** [comment]
This is best served by a separate userstyle/extension
