### ISSUE TITLE
Add button to copy cross-reference

### ISSUE THREAD

**Issue by edouard-lopez** [sindresorhus/refined-github#1889]
Hi thanks for the addon, appreciate it a lot.

I'm often working on **issues that spread across downstream and upstream projects**, e.g. [rafaelrinaldi/pure](https://github.com/rafaelrinaldi/pure) (for fish) and [fish](https://github.com/fish-shell/fish-shell/) itself, thus cross-reference issues.

Currently, to do so I do:
1. switch to upstream project issue
1. select URL
1. copy to clipboard
1. switch back to downstream issue
1. paste URL
1. edit to get `owner/project#xxx`

A button to directly get `owner/project#xxx` from upstream would speed up the process. 

This feature is native in Gitlab, and I miss it on Github :cry:

**Comment by bfred-it** [comment]
I'm not sure I follow. Where should this `owner/project#issue` link be added?

**Comment by edouard-lopez** [comment]
Take for exemple this issue we are on, and say I want to reference it on another project.
I want a button on this page to copy its reference so I can paste it on said project

**Comment by bfred-it** [comment]
You can copy it’s URL from the URL bar

**Comment by edouard-lopez** [comment]
Indeed they render in the same way, I remembered them as full URL

> https://github.com/elves/elvish/issues/805 

    https://github.com/elves/elvish/issues/805 

vs.

> elves/elvish#805

    elves/elvish#805

Good for me.
