### ISSUE TITLE
Hide editable PR warning after the PR is merged

### ISSUE THREAD

**Issue by pietroalbini** [sindresorhus/refined-github#1893]
A warning was added recently to encourage contributors to enable "Allow edits from maintainers", and it's great! Unfortunately, the warning is shown needlessly after the PR is merged even if the setting was correctly enabled.

Would it be possible to hide it on merged PRs?

![2019-03-30--15-19-59](https://user-images.githubusercontent.com/2299951/55277341-58b66f80-52ff-11e9-8a91-b9f21fddcb62.png)

**Comment by bfred-it** [comment]
Does the checkbox and message stay there even after you refresh the page?

**Comment by pietroalbini** [comment]
Yes, that screenshot was taken days after the PR was merged and the tab was just opened.

**Comment by bfred-it** [comment]
It looks like a bug by GitHub. The checkbox keeps appearing even after the branch is deleted. I'm hiding it in #1894

**Comment by pietroalbini** [comment]
Thanks for the really quick fix, and for this great extension :tada:
