### ISSUE TITLE
Readd the jump-to-bottom` feature

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1897]
I was using this button. You guys removed because think no one is using it:

1. https://github.com/sindresorhus/refined-github/pull/1879

If you do not like the button on the UI, why not add a setting `hide-jump-to-bottom-button`?

**Comment by sindresorhus** [comment]
You can just use the keyboard shortcut, as mentioned in https://github.com/sindresorhus/refined-github/issues/892.

**Comment by yakov116** [comment]
@sindresorhus 	true but not it was a nice shortcut and it was not _intrusive_

**Comment by evandrocoan** [comment]
I am glad to use the keyboard shortcut, if I am with my hands on the keyboard. But most times I am not. Then, I just the `Jump to Bottom`.

**Comment by bfred-it** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/892
