### ISSUE TITLE
Account switcher closes itself immediately after click

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#19]
1. Open https://github.com in a new tab.
2. Click the account switcher quickly.

Expected: The account switcher opens and it stays open.
Actual: The account switcher opens and closes itself immediately. It fixes itself after you hold down your mouse for longer when clicking or after a few times of clicking it.

I'm on Chrome dev channel on Mac OS.
Chrome Version 50.0.2652.0 dev (64-bit)

**Comment by sindresorhus** [comment]
I've noticed this too.
