### ISSUE TITLE
Remove file from PR

### ISSUE THREAD

**Issue by zephraph** [sindresorhus/refined-github#1901]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2480%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/1901)

Basically a duplicate of #1127.

Sometimes in a PR file changes slip in that you didn't intend. Maybe you didn't correctly stash, a commit hook made a formatting change, or some other thing happened. 

The ultimate result is that you want to undo changes to a particular file in your PR. It'd be nice to have a button on the header of every file in the diff to revert that change. 

Something like this...

<img width="1027" alt="image" src="https://user-images.githubusercontent.com/3087225/55346192-e6b96400-547f-11e9-90b7-031c9dc0d34e.png">

It seems like this was added in #1398, but it's no longer present or working now. At least not in the FF version of the plugin. GitHub added the trashcan icon to actually _delete_ a file... heh, I almost did that >_>.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $80.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($80.00)
### Submitted pull Requests
- [#2182 Add `revert-file` feature](https://issuehunt.io/r/sindresorhus/refined-github/pull/2182)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by bfred-it** [comment]
They’re different. 

“Delete file” fully deletes the files, it’s a feature that was added by GitHub. 

“Revert all changes in file” is a feature that would indeed be nice to have.

**Comment by HardikModha** [comment]
@bfred-it I would be more than happy to contribute to this. Can you point me towards the starting point? Thanks!

**Comment by bfred-it** [comment]
Honestly I don’t know if there’s an easy way to do this, you’d have to look the API for reverting

**Comment by zephraph** [comment]
Yeahhh... I was looking into this. It's definitely non-trivial.

I think the easiest way to is to follow this path:

1. Get the base branch of the PR
2. Use the [contents api](https://developer.github.com/v3/repos/contents/#get-contents) to grab the base version of the file
3. Use the [contents api](https://developer.github.com/v3/repos/contents/#update-a-file) to create a new commit of the file as it was at its original state.

**Comment by bfred-it** [comment]
1. Not the base branch, but the parent commit of the first commit in the PR. The base branch might have changed.
2. Maybe you can skip this step if you can just `revert` the file like you can in git: https://stackoverflow.com/questions/215718/reset-or-revert-a-specific-file-to-a-specific-revision-using-git

**Comment by zephraph** [comment]
GitHub's api doesn't really expose higher level git actions like checkout. We could use the [commit api](https://developer.github.com/v3/git/commits/) to try to replicate this process, but I'm not sure how to go about doing that.

**Comment by bfred-it** [comment]
The correct API seems to be Contents API

https://developer.github.com/v3/repos/contents/#update-a-file

Use it for steps 2 and 3
