### ISSUE TITLE
Show real date for recent releases

### ISSUE THREAD

**Issue by tommy-muehle** [sindresorhus/refined-github#1902]
I often struggle a bit when I look over recent releases and see something like this "released this 4 days ago" or "... 29 days ago".

So in my opinion it would be very nice to see the real release-date also for recent releases. Just like for releases which are older then one month.

**Comment by tommy-muehle** [comment]
Maybe also with the release time when multiple releases were on that day.

**Comment by sindresorhus** [comment]
Why do you need to know the exact date for recent releases? I have personally never needed to know that myself and I'm curious about the use-case. You can actually already see the real date by just hovering over the relative date which then shows a tooltip.
