### ISSUE TITLE
fit-textareas feature is expanding the edit dialog up to hundreds of pages

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#1905]
If I have an issue with thousands of lines, i.e., and hit the edit button, and the option `fit-textareas` is enabled, the text box area is expanded and the save and cancel button are hard to reach.

![image](https://user-images.githubusercontent.com/5332158/55441426-37fd4c80-5581-11e9-8609-7cad38567467.png)

**Comment by busches** [comment]
What are you suggesting as the work around? Not applying the box on edit functionality? I personally use the keyboard shortcuts and never hit the buttons.

**Comment by evandrocoan** [comment]
Maybe limit the maximum size?

Also, I kept trying to hit `Esc` key, but it did not work to cancel it, it just did nothing.

**Comment by bfred-it** [comment]
I feel the pain. Here are 2 solutions that don't involve setting a limit:
- `esc` should press Cancel or blur the field, this is actually already a feature of RGH and it isn't working (at least in this case) https://github.com/sindresorhus/refined-github/blob/0b6c7330c21f8570519143ad3d0decc328d4db47/source/features/comment-fields-keyboard-shortcuts.tsx#L33
- the field's size can re-set to its regular height on `blur`, which coupled with `esc`-to-blur could also fix it, but I think I want the field to _always_ fit the content.

So I think if the `esc`-to-cancel feature if fixed (or extended to edited comments), then this would at least fix the specific use case.

**Comment by evandrocoan** [comment]
I just disabled the setting and it seems more than enough because GitHub by itself, already autoexample the edit box size up to a page size and it seems more than enough. 

I just do not understand why this problem happened rigth now. Did you add this `fit-textareas` setting recently? I looked over the changelog and could not find any mention of `fit-textareas`.

**Comment by bfred-it** [comment]
The changelog mentions it as “Comment boxes expand with their content and no longer show scroll bars”

**Comment by fregante** [comment]
Replaced with a more specific issue: 2413
