### ISSUE TITLE
Singleton Plugin/Feature Injection

### ISSUE THREAD

**Issue by ctsstc** [sindresorhus/refined-github#1906]
## Reason

I am running a couple forks of this project, it would be nice to have features only inject once rather than needing to choose to blacklist features for the other extensions. 

One could argue I should only run one of these extensions at a time, but they have features I enjoy that have been rejected for merging, or have not made it in for whatever reason.

Feature injection could check a global to see if something with the same name has already been injected. Or maybe it uses a selector on an element that gets injected to see if it exists already.

## Cons

I know that forks could become outdated and would require to be updated to this version for this to be useful. I also don't believe there's any extension loading priority, so it would be a race to see which extension could load first. If an extension was behind you could have mixed feature variations when one loaded and the other did not resulting in confusion.

## Conclusion

Not sure if this is a feasible idea or one that should even exist. Is there any other way that something like this could be accomplished? I don't think there's any communication that could exist between extension settings that I know of, without some convoluted way where they talk to each other on a page.

You could try to have versioning in there, but I'm not sure that you could know when all possible extensions of the same kind were done loading and reporting. This would all add too much wait time to the page to get features loaded, it would also require so much engineering too to (the first extension to load could load up data and then other extensions could feast on the data that was loaded in the cases where there's a redundant request but one of the extensions had a feature the other doesn't)

**Comment by bfred-it** [comment]
If you want to keep a fork just for some features, simply drop the features you don't use (or that existing in Refined GitHub), there's no need to keep them in there if they're never used.

Many features already check whether they've been loaded, but not all, and they don't need to
