### ISSUE TITLE
Add button to download diff of PR

### ISSUE THREAD

**Issue by tterranigma** [sindresorhus/refined-github#1907]
For instance, here https://github.com/ansible/ansible/pull/54740, a button that reads 'Patch' with a download icon could appear next to the `Files changed` tab or next to the title of the PR.

**Comment by jerone** [comment]
One can use my UserScript as reference for this feature: https://github.com/jerone/UserScripts/tree/master/Github_Commit_Diff

**Comment by bfred-it** [comment]
RGH already shows [diff/patch links](https://github.com/sindresorhus/refined-github/blob/master/source/features/patch-diff-links.tsx) **in commit pages**, but not in PRs.

For the record, you can always access that by appending `.diff` to the URL: https://github.com/ansible/ansible/pull/54740.diff

But before we go further, why? How do you use the downloaded `.diff` file?

**Comment by tterranigma** [comment]
I might be blind but I can't see the links even in commit pages.

Following the link in my original comment, I needed to add those fixes to my local installation (a git clone) of ansible asap to get on developing my project. I had two options.

First option:
1. Copy the branch of the fork that the fixes were worked on
1. Add an extra remote to my local git clone:
    1. `cd into/ansible/folder`
    1. `git remote add bcoca https://github.com/bcoca/ansible/tree/only_cacheable_update_cache`
    1. 32x <kbd>Backspace</kbd>
    1. <kbd>Enter</kbd>
1. `git fetch bcoca`
1. `git merge bcoca/only_cacheable_update_cache`
1. `git remote remove bcoca`

Second option:
1. <kbd>Ctrl+L</kbd>, <kbd> :arrow_right: </kbd>, type `.diff` and <kbd>Enter</kbd>
1. `cd into/ansible/folder`
1. `patch -p1 < ~/Downloads/54740`

Making `1.` of the second option would replace 8 keystrokes with a single mouse click.

**Comment by bfred-it** [comment]
> I might be blind but I can't see the links even in commit pages.

They do blend in pretty well. Here's a screenshot of the feature working also in PR commits:

<img width="1180" alt="shot" src="https://user-images.githubusercontent.com/1402241/55485086-49ffed80-565c-11e9-961a-39c48f407e50.png">

**Comment by bfred-it** [comment]
Third option:

```sh
hub checkout https://github.com/ansible/ansible/pull/54740
```

https://hub.github.com/

Also #963

**Comment by tterranigma** [comment]
> Here's a screenshot

Oh right! Thanks for pointing out.
