### ISSUE TITLE
Add option to disable whitespace diff via URL parameter

### ISSUE THREAD

**Issue by anselmh** [sindresorhus/refined-github#191]
According to Alex’ tweet (https://twitter.com/SlexAxton/status/725193003220893696) this is possible by adding `?w=1` to the URL:

> ProTip: Add a w=1 query param to github diffs to ignore whitespace. Usually way easier to read.

Possible as option for the extension?

**Comment by sindresorhus** [comment]
We don't add options, but we can consider adding a button to the UI for it. You wouldn't want to have it on all the time anyways as it hides important changes and disables inline comments.

**Comment by anselmh** [comment]
Fair enough, it really shouldn’t be enabled by default, I agree. A button would be cool though for sites showing diffs.

**Comment by DrewML** [comment]
Seems like quite a half-baked way for GitHub to add that feature 😆. I think adding a button for it would be cool. Probably won't know how often I'll use it until it's there, though

**Comment by sindresorhus** [comment]
Alright. PR welcome.

**Comment by nadim** [comment]
I love the checkbox that's been added for Hide Whitespace Changes. Can we add an option to make it the default parameter?

**Comment by anselmh** [comment]
@nadim Hi, not sure about the "default" option for this but Github has recently added this feature natively as well, although also just as temporary option: 
<img width="422" alt="screen shot 2018-08-10 at 08 04 22" src="https://user-images.githubusercontent.com/399345/43941354-12cb61de-9c74-11e8-9e7f-d7c7a52be100.png">

**Comment by AmazingJaze** [comment]
Adding as a temporary option is not sufficient in my opinion. With team wide adoption of estlint and prettier whitespace is effectively never a concern in PRs for me. I hate having to load the diff twice just to hide white space changes.
