### ISSUE TITLE
Copy file path in PR discussion

### ISSUE THREAD

**Issue by Cretezy** [sindresorhus/refined-github#1912]
A feature to copy file paths in PRs would be useful. This would be shown in the main discussions for comments, next to the file name.

Mockup:

![copyfilepath](https://user-images.githubusercontent.com/2672503/55586810-e1664e80-56f7-11e9-8462-6e9d1150b827.png)

**Comment by bfred-it** [comment]
It’s already there natively

![](https://user-images.githubusercontent.com/1402241/55601847-62bfee80-5795-11e9-9d76-305de2dc973d.jpeg)

**Comment by Cretezy** [comment]
Nope. That's for the "Files" tab, which does (my bad!), but discussions do not have it:

![image](https://user-images.githubusercontent.com/2672503/55603498-f6af9d00-5738-11e9-933c-f24c815254e7.png)

**Comment by bfred-it** [comment]
“Nope” what? That’s what you asked for before changing your post

![5B0B9B37-E781-4797-A3C9-3D0015F19565](https://user-images.githubusercontent.com/1402241/55621943-7c7f2700-57d1-11e9-8d10-9b83c9ef99f7.jpeg)

**Comment by Cretezy** [comment]
I listed 2 use cases in my post, one was already there (hence the "my bad!"), but you dismissed my second one. Anyhow, I think this would be a great addition

**Comment by bfred-it** [comment]
GitHub did it

**Comment by bfred-it** [comment]
Discussions are already pretty busy, I don't wanna add any more buttons. Just click the filename and keep reviewing from the Files tab
