### ISSUE TITLE
"close and comment"  button float left, Easy to make a mistake

### ISSUE THREAD

**Issue by elzup** [sindresorhus/refined-github#1915]
This is feedback. And the same record for those in need. `[transrated by google]`
これはフィードバックです。そして同じように困っている人のための記録です。

Version
19.4.7.1857

It feels like the wrong operation is increased by changing the button position.
ボタン位置の変更によってむしろ誤って操作することが増えたように感じます。
![](https://user-images.githubusercontent.com/2284908/55855101-832ae700-5ba1-11e9-93ea-fbd190ddd92c.png)

Code in.

https://github.com/sindresorhus/refined-github/blob/0b6c7330c21f8570519143ad3d0decc328d4db47/source/content.css#L476-L478

For now, I turned off like this.
とりあえず私はこのようにオフにしました。
![Extensions](https://user-images.githubusercontent.com/2284908/55854738-9093a180-5ba0-11e9-813a-c8b359f72fb3.png)

**Comment by bfred-it** [comment]
Good idea. We already do this for the “Cancel” buttons when leaving comments and for “Cancel review”

**Comment by bfred-it** [comment]
Ah, I misunderstood. We already use `float:left` to **avoid** mistakes. What if we colored the button red? Or maybe just the text

**Comment by elzup** [comment]
GitHub changes works for me. and reconsidered that `float: left;` is better.
Thank you for the discussion.

![_WIP__Add_trigger_modal_by_gn-spawn_·_Pull_Request__47_·_elzup_farm-controller-front](https://user-images.githubusercontent.com/2284908/57266675-f6981980-70b7-11e9-9811-c7abbdfd7da2.png)

**Comment by bfred-it** [comment]
Thanks for following up!
