### ISSUE TITLE
Hide milestone drag icon when no permission

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#1918]
![image](https://user-images.githubusercontent.com/55841/55895374-589a5780-5bbc-11e9-8f13-21f813bb1391.png)

The icon to allow dragging of milestone issues is shown when you don't have permissions to edit milestones. Why not just hide this distracting functionality for users without milestone edit permissions.

```html
      <div class="d-table-cell v-align-top pt-2 pr-1 text-gray-dark Box-row--drag-button  pl-2" style="width:21px;"> <!-- To line up with checkbox in filter bar -->
          <span class="tooltipped tooltipped-ne tooltipped-multiline" aria-label="You do not have permission to edit this milestone." style="/*! display: none; */">
            <svg class="octicon octicon-grabber v-align-text-bottom" style="width: 12px" viewBox="0 0 8 16" version="1.1" width="8" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M8 4v1H0V4h8zM0 8h8V7H0v1zm0 3h8v-1H0v1z"></path></svg>
          </span>
      </div>
```

It can be linked to the `aria-label`-attribute with the specific text "_You do not have permission to edit this milestone._".

Test url: https://github.com/ForkIssues/TrackerWin/milestone/9

**Comment by sindresorhus** [comment]
Accepted. PR welcome :)
