### ISSUE TITLE
Display repository activity level

### ISSUE THREAD

**Issue by hschne** [sindresorhus/refined-github#1920]
When I browse for existing solutions on Github it happens quite a bit that I find something that seems to fit the bill only to notice later that there hasn't been any activity on that project in years. 

It would be nice to have a banner / notification in that case that displays, that I am currently viewing an inactive repository - as this keeps me from checking various branches for any commit history. 

This notification could be displayed on a repositories page, similar to what GitHubs archived projects does. Maybe something like: 'You are currently viewing a repository that hasn't seen any activity in a while'. 

![Screenshot from 2019-04-12 09-54-05](https://user-images.githubusercontent.com/5294464/56021128-f9962900-5d08-11e9-9d51-f7d9e3e15fca.png)

If a banner is too noisy an alternative could be a simple badge next to the repository name (where `refined-github` currently also displays the build status). 

The only question is when a repository should be considered inactive - I personally would consider a repository without any activity (no new commits on any branches, no closed issues, ....) in the last 3 years inactive, but I guess that's up for debate :)

**Comment by notlmn** [comment]
Kinda disagree here, sounds more like a feature that says "Nothing interesting here, move on" for non-active repositories. 🤷‍♂️

**Comment by hschne** [comment]
@notlmn What do you mean to say? That a feature that says "Nothing interesting here" makes no sense? :) 

Or put differently: What exactly do you disagree with?

**Comment by notlmn** [comment]
> What do you mean to say? That a feature that says "Nothing interesting here" makes no sense?

Yes, that project could be something the user might be looking for. They wouldn't know that that's what they are looking for until they take a look at the project.

----------------

> What exactly do you disagree with?

That having a banner like that would only make the user go away from the project that they might be interested in, that they might contribute to if they can.

-----------------

Even if we were to decide to implement this, what would the minimum time be for a repository to be considered to be inactive. Is it the commits? Issues? Pull requests?

(I keep saying might because you can't really know what a user is looking for in a project, saying that it is inactive adds no value)

**Comment by hschne** [comment]
Thanks for clearing that up, I see your point now. 

> That having a banner like that would only make the user go away from the project that they might be interested in, that they might contribute to if they can. 

The users can still make that decision for themselves, this feature only means that it makes the fact that a repository hasn't seen any activity in a long time more easily recognizable - which IMO does add value. 

However, I concede that this might still be somewhat of a niche improvement, so you may close this issue if you still feel that it won't fit with refined-github :)

**Comment by bfred-it** [comment]
How about something more generic like “last active 3 years ago” or better yet “last commit 3 years ago”

This would be neutral, while still showing possibly-useful information. It’s up to the user to decide whether it’s still good enough then. 

We could show this info only if the last commit was 1y+ ago or cache a `isFresh:true` value for months (1y - time from last commit)

**Comment by sindresorhus** [comment]
I'm against making assumptions based on date of last commit. I'd rather see something like @bfred-it is proposing, but I think we already have that information available:

- On the repo front-page, you can already easily see the date of the last commit.
- On a repo list, it shows you the last time a repo was updated. (Example: https://github.com/avajs)

**Comment by bfred-it** [comment]
> we already have that information available natively

Indeed. I was thinking that if a user lands on an issue page from Google, they might want to understand if the repo is still active and the issue has a chance of being solved/reviewed, but yes that information is one-click away even in that case _(click on Code tab)_

**Comment by hschne** [comment]
> but yes that information is one-click away even in that case (click on Code tab)

That does indeed show that information for the default branch, but there might be other  branches with more recent activity. At least AFAIK :man_shrugging:

**Comment by muescha** [comment]
maybe it can include the sparkline which can be found on the repo overview at  https://github.com/sindresorhus?tab=repositories&type=source

![Bildschirmfoto 2019-05-16 um 21 43 45](https://user-images.githubusercontent.com/184316/57882359-cc66fa00-7823-11e9-8fe3-96afda21e48c.png)

**Comment by bfred-it** [comment]
That would be good to include on the main page but it would be unnecessary in most places. The code is simple enough:

```html
<poll-include-fragment src="/USER/REPO/graphs/participation?w=155&amp;h=28&amp;type=sparkline)" />
```

**Comment by fregante** [comment]
Closing because this would give false signals on repos that just don't need frequent updates.

I think a large number of open issues _and_ old "last commit" dates on the homepage are good enough when you actually find such repos. I hope it's not a daily occurrence
