### ISSUE TITLE
Pull requests page navigation buttons clashes with search bar

### ISSUE THREAD

**Issue by iamogbz** [sindresorhus/refined-github#1938]
1. Make sure the bug is caused by Refined GitHub. Try disabling the extension first. ✅

2. Include a full URL where the bug appears.
https://github.com/pulls

3. Include a screenshot/gif 
<img width="1016" alt="Screen Shot 2019-04-18 at 8 36 52 AM" src="https://user-images.githubusercontent.com/2528959/56361438-58e6b400-61b5-11e9-859f-6b712a496518.png">

Screen resolution: 1440x1080

4. Possible solution
Remove the `subnav-search-input-wide` class on the search input element
<img width="232" alt="Screen Shot 2019-04-18 at 8 37 54 AM" src="https://user-images.githubusercontent.com/2528959/56361439-58e6b400-61b5-11e9-8173-e1bafcb03930.png">
<img width="1001" alt="Screen Shot 2019-04-18 at 8 38 09 AM" src="https://user-images.githubusercontent.com/2528959/56361440-597f4a80-61b5-11e9-8d3d-63f470933b08.png">

**Comment by bfred-it** [comment]
This was fixed by https://github.com/sindresorhus/refined-github/commit/ca8b1e13f78c50a5a3283982fba41e8be49e12c0, which caused https://github.com/sindresorhus/refined-github/issues/1959

![](https://thumbs.gfycat.com/FlickeringLeadingBengaltiger-small.gif)
