### ISSUE TITLE
show-names no longer shows names

### ISSUE THREAD

**Issue by dotconnor** [sindresorhus/refined-github#1940]
Names no longer show up next to a person's username on discussions.
Disabled:
<img width="776" alt="Screen Shot 2019-04-18 at 12 28 42 PM" src="https://user-images.githubusercontent.com/14323370/56376333-8b080e00-61d5-11e9-849c-87de93f68131.png">
Enabled:
<img width="780" alt="Screen Shot 2019-04-18 at 12 29 28 PM" src="https://user-images.githubusercontent.com/14323370/56376381-a70baf80-61d5-11e9-8fa0-98fe0c9a9192.png">
Expected:
<img width="794" alt="Screen Shot 2019-04-18 at 12 31 02 PM" src="https://user-images.githubusercontent.com/14323370/56376646-6c564700-61d6-11e9-936b-b429b068d7c4.png">

**Comment by HardikModha** [comment]
@dotconnor It requires the personal authentication token. You can add it from extension options.

**Comment by Phrynobatrachus** [comment]
I have a token and it is still broken at the moment. I'm looking into it.

**Comment by dotconnor** [comment]
@HardikModha I have a token set, I even confirm it by creating a new token with all permissions; I can also see the network request made for the feature and it does, in fact, return the correct data.

**Comment by HardikModha** [comment]
@dotconnor @Phrynobatrachus I've debugged the issue. For the currently logged in user, the name is not present in the `names` array returned from the API. That's where it is breaking.

**Comment by Phrynobatrachus** [comment]
Yeah I have it working locally. I'm not sure how it was working before with the `{name}` interpolation since that's not defined from what I see? I also don't know why your own username wasn't included before, I'm just adding it to the set after the `getUsername()` and it seems to work ok.

**Comment by bfred-it** [comment]
This was likely broken by some of my changes in #1783, you can see how it was before that PR: https://github.com/sindresorhus/refined-github/tree/5d66c95516e6f5f4ea4943acbe96c168be517910
