### ISSUE TITLE
Empty notification that doesn't go away.

### ISSUE THREAD

**Issue by saulojoab** [sindresorhus/refined-github#1944]
Just opened my GitHub page, and it seems like I have a notification, as you can see here: 
![image](https://user-images.githubusercontent.com/37988252/56399962-9edc6000-6227-11e9-90a1-d1273b5771dc.png)

When I open it, it says I have one unread notification and that it's coming from your repository. However, when I open it, there's nothing. As you can see below:
![image](https://user-images.githubusercontent.com/37988252/56399992-c92e1d80-6227-11e9-97fe-9b5b3ecb2b3e.png)
![image](https://user-images.githubusercontent.com/37988252/56399994-ce8b6800-6227-11e9-8b18-1df80feffee2.png)

I don't know how to reproduce it, I just opened GitHub and it was there. I tried refreshing the page and browsing into other pages, but it's still there. Maybe it's a GitHub related glitch but because it has your repository on the notifications, maybe it's a bug or something. Any clue on what's causing that?

**Comment by notlmn** [comment]
Just experienced it [on mobile](https://twitter.com/ramlmn/status/1119048443400294400) too, it's not a bug from the extension.

Something from the GitHub's end is acting weird.

**Comment by bfred-it** [comment]
Yeah I've seen this bug before, it wasn't ours
