### ISSUE TITLE
timely api requests

### ISSUE THREAD

**Issue by janat08** [sindresorhus/refined-github#1946]
I don't know what the stance is on use of api, but if you're modifying a page and calling api, it would be cool if you made the api request as soon as user navigates to a page to be modified.

Issues #977 would've benefited from this. Watch links to issues/pr, if they're clicked make an api call, to help modify page to avoid flicker.

I thought about doing myself but got too worried about user navigating straight to the page without redirects, ensuring a call then, since I'm not sure how the features are actually loaded (or basically ajax for that matter), nor that the loading behavior would actually let you do something like this.

**Comment by bfred-it** [comment]
I think you're asking to trigger an API call when the user clicks on a link that _will_ require an API call, so it doesn't have to wait for the whole page to be loaded first.

Most of the time we rely on the info on the actual page to make the API call, but if we don't, then sure.

This is somewhat possible already I think, at least on ajaxed pages where the URL changes before `pjax:end` so we just have to add a new `features.onNavigation = cb => addEventListener('pjax:start', cb)` and the page detections will automatically work.

You can have two `features.add`, on `onNavigation` and the other `onAjaxedPage`, for example like I did in 

https://github.com/sindresorhus/refined-github/blob/bd98bb5a9812a9f0fc63c3992127a2d72f1f1180/source/features/pr-merge-info-enhancements.tsx#L75-L91

**Comment by bfred-it** [comment]
Closing this since you’re already working on it 🙂

**Comment by janat08** [comment]
for example, this should be implemented in #977
