### ISSUE TITLE
api v4 won't return data if there're errors

### ISSUE THREAD

**Issue by janat08** [sindresorhus/refined-github#1956]
I'm querying about organizations, and those may restrict third-party api access regarding them, and then I'm querying about users as I don't know if repository owner is actually an organization or a user, at which point one of those will definitely error.

Given that with graphql you might be asking for plenty of data/fields in a single query it is wrong to throw errors and not return data. I suspect that even rate limiting/depth might be field dependent.

**Comment by bfred-it** [comment]
> it is wrong to throw errors and not return data

Indeed, that's one of the drawbacks of throwing errors, as I mentioned here: https://github.com/sindresorhus/refined-github/pull/1679

> I don't know if repository owner is actually an organization or a user, at which point one of those will definitely error.

Can you show the query you're talking about specifically? Maybe we can see if it can be done in another way.

> I suspect that even rate limiting/depth might be field dependent.

We can't handle "partial API calls", it's just too much work. If we need some information and we can't get it because of rate limiting, I'm ok with the feature breaking.

**Comment by janat08** [comment]
I very much doubt that there's a field for checking out if organization gives aways info about itself to third-party apps.
```
		{
			repository(owner: "${ownerName}", name: "${repoName}") {
				projects(states: [OPEN, CLOSED]){
					totalCount
				}
				issue(number: ${number}){
    				viewerCanUpdate
    			  	projectCards{
    			    	totalCount
    				}
    			}
			}
			organization(login: "${ownerName}"){
			    projects(states: [OPEN, CLOSED]){
        			totalCount
    			}
			}
			user(login: "${ownerName}"){
				projects(states: [OPEN, CLOSED]){
					totalCount
				}
			}
			
		}
```

**Comment by janat08** [comment]
There's an option of simplifying feature im working on to be obtuse about when it applies itself.

**Comment by bfred-it** [comment]
Making this change would bring the error checking into each feature and make the code more complex. I think we're good for now since it's not needed, until we really can't do without it.
