### ISSUE TITLE
The tags dropdown seems to align weirdly

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1959]
The tags dropdown seems to align weirdly...

![image](https://user-images.githubusercontent.com/55841/56472481-265fe400-645f-11e9-8da0-d982bf364481.png)

_Originally posted by @jerone in https://github.com/sindresorhus/refined-github/pull/1896#issuecomment-485262710_

That's due to https://github.com/sindresorhus/refined-github/commit/ca8b1e13f78c50a5a3283982fba41e8be49e12c0 and I don't know how to fix it since they dropped the `.issues-listing` class I was relying on. 

PR welcome

**Comment by HardikModha** [comment]
@bfred-it I'll look into it.

**Comment by bfred-it** [comment]
I found a solution just now

**Comment by HardikModha** [comment]
That's great. What's your approach?

**Comment by bfred-it** [comment]
Actually it's just this

```css
/* For `widen-search-field`: Move extra buttons to the right on Releases */
.subnav-links {
	margin-right: auto;
}
```

Which works for one:

<img width="1016" alt="" src="https://user-images.githubusercontent.com/1402241/56474102-a90c9180-64a7-11e9-8298-639f6d1cdc68.png">

But it would require even more CSS if there are 2:

<img width="996" alt="" src="https://user-images.githubusercontent.com/1402241/56474106-b4f85380-64a7-11e9-8f8e-226af9154ff0.png">

So a proper solution for `widen-search-field` would be appreciated.

**Comment by HardikModha** [comment]
I kind of did the same but using `flex-grow: 1`.

```
.subnav-links {
	flex-grow: 1;
}

.subnav-links + .float-right {
	order: 1;
}
```

![Screen Shot 2019-04-22 at 12 13 42 AM](https://user-images.githubusercontent.com/22439276/56474151-82446000-6493-11e9-9384-ba23f6c44060.png)

**Comment by bfred-it** [comment]
That works too. Send a PR?

**Comment by HardikModha** [comment]
On it...

**Comment by HardikModha** [comment]
@bfred-it Should I drop your change? The build is failing because of the duplicate selector.

**Comment by HardikModha** [comment]
Didn't mean to spam with commits but don't know something weird happened and I had to force-push and merge again.

**Comment by Loilo** [comment]
For the record, the distance between the buttons still seems to be messed up in several ways.

With no API key entered:

<img alt="Screenshot of the &quot;Draft a new release&quot; button snuggling up to the &quot;Tags&quot; button on the left" src="https://user-images.githubusercontent.com/1922624/57241774-0e2cbf00-7032-11e9-8726-1223bbe85b23.png" width="392">

---

With API key entered:

<img alt="Screenshot of the &quot;Draft a new release&quot; button snuggling up to the &quot;Select tag&quot; button on the right" src="https://user-images.githubusercontent.com/1922624/57241853-43391180-7032-11e9-86e1-5284d2ed0e00.png" width="407">

**Comment by jerone** [comment]
Confirmed. This seems only to happen when you have admin rights to the repo, hence the "Draft a new release" button.

**Comment by Loilo** [comment]
Yep. The first screenshot is due to the expanded search bar — the parent element is now a flex container and therefore the floats collapse. This was fixed with a `margin-left: auto` on the right part, but that's only included when the Select Tag feature is enabled (i.e. when an API key is entered).

The collapsing in the second screenshot was handled in the tag selection PR, the "Select Tag" button actually has a margin — but to the wrong side (right instead of left).

Should be easy to fix, I'll attach a PR if I can find the time to do so today.

**Comment by bfred-it** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/2013
