### ISSUE TITLE
Display issues after creating a new repo

### ISSUE THREAD

**Issue by Kocal** [sindresorhus/refined-github#1964]
Hi,

I created a new private repository and this is what happens after:
![chrome_2019-04-22_11-36-27](https://user-images.githubusercontent.com/2103975/56495805-26132780-64f7-11e9-83ce-ce0b39ac3651.png)

When unzooming the page:
![chrome_2019-04-22_12-05-45](https://user-images.githubusercontent.com/2103975/56495850-48a54080-64f7-11e9-95ae-4be67414286b.png)

It looks like there is a page that is injected in the topbar. We can see that in the Elements Inspector:
![chrome_2019-04-22_12-04-31](https://user-images.githubusercontent.com/2103975/56495873-712d3a80-64f7-11e9-9b53-ae352ead8525.png)

This is weird because I don't have this issue on another pages, like: 
  - https://github.com/sindresorhus/refined-github
  - https://github.com/Kocal
  - https://github.com/settings/profile

Note that I don't have this issue when disabling the extension, this is what the page looks like:
![chrome_2019-04-22_12-06-18](https://user-images.githubusercontent.com/2103975/56495912-8e620900-64f7-11e9-98c9-6216abfc50dd.png)

Thanks!

**Comment by notlmn** [comment]
Have seen this while testing out #1909, thought that it was something that I did while trying to use flexbox and didn't bother to open and issue.

Looking at the log, that's not the case.

![image](https://user-images.githubusercontent.com/37769974/56500104-25928500-6527-11e9-826d-70fb1d0e572d.png)

**Comment by notlmn** [comment]
Thought this has to do with add the feature twice, but just that GitHub returns different DOM for repos which are not empty and which are empty when we use `<include-fragment>`

| Refined GitHub | Empty repository |
|:------:|:----:|
| ![image](https://user-images.githubusercontent.com/37769974/56500660-64293f00-6529-11e9-9698-c2a84231917d.png) | ![image](https://user-images.githubusercontent.com/37769974/56500711-920e8380-6529-11e9-81cd-b8fb62d1a80a.png) |

**Comment by Kocal** [comment]
Ah, nice catch!

**Comment by Kocal** [comment]
Thanks! :)

**Comment by bfred-it** [comment]
Thanks for reporting the bug! We had this, we had a fix, but in the latest rewrite of the feature I couldn't reproduce it and I dropped the workaround. Well, I was wrong!
