### ISSUE TITLE
Addon goes weird on opening uninitialized repos

### ISSUE THREAD

**Issue by SreeChandan** [sindresorhus/refined-github#1968]
https://github.com/SreeChandan/nostalgia (Private uninitialized repo)
Screenshot with the extension enabled:
![image](https://user-images.githubusercontent.com/20862449/56522928-83918d80-6564-11e9-9a29-b310a73c8a2b.png)

Screenshot with extension disabled:
![image](https://user-images.githubusercontent.com/20862449/56523338-fbf84e80-6564-11e9-8e92-b7fd60275bd7.png)

TLDR: UI goes hayfire on opening uninitialized repo. I suppose since the initialize phase is so small it might have been ignored.

**Comment by yakov116** [comment]
@SreeChandan can update the extension?

**Comment by SreeChandan** [comment]
updated the extension, solved. tnx.
