### ISSUE TITLE
Open issue to latest comment

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#1969]
Sometimes I'm only interested in the latest comment. What if the comment number is linked to the _latest_ comment...

![image](https://user-images.githubusercontent.com/55841/56532041-60131680-6555-11e9-9328-aa1861e908a6.png)

**Test:**
https://github.com/sindresorhus/refined-github/issues for issues with multiple comments.

**Comment by bfred-it** [comment]
"Latest comment" can just be the footer, so no API calls are required

**Comment by sindresorhus** [comment]
PR welcome.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*
