### ISSUE TITLE
Update docs with permissions requirements

### ISSUE THREAD

**Issue by pauby** [sindresorhus/refined-github#1971]
The Firefox (and I assume the Chrome) extensions have an optional requirement for some features to use the GitHub API with the following permissions:

![image](https://user-images.githubusercontent.com/12760779/56566646-15bc8480-65ab-11e9-99cc-30c15f735c46.png)

Those permissions are fairly wide ranging. I can't see anywhere that tells me which features require them or why.

I'd like to see the docs / README be updated with which features require the GitHub API OR an explanation as to what the permissions are for and why.

**Comment by bfred-it** [comment]
You can keep using Refined GitHub without API access and see what fails in the console, we don't keep a list of what features need what, but you can search this:

All API v4 features need it: https://github.com/sindresorhus/refined-github/search?q=api.v4&unscoped_q=api.v4

API v3 only need it for private repos and rate limiting: https://github.com/sindresorhus/refined-github/search?q=api.v3&unscoped_q=api.v3

**Comment by pauby** [comment]
Can you add that to the docs / README. It will at least stop somebody asking that in the future. Alternatively I'll drop a PR in as soon as I can if it's something that will be accepted. 

Asking for those permissions without clarifying what they are for is going to put a lot of people off using the add-on. I can't surely be the _only one_, can I? 😄

**Comment by bfred-it** [comment]
How so? The extension works fine without a token and the user doesn’t even find out until they open the options or see which specific feature is broken because of the lack of a token. 

Once in the option it does say that “some features use the API” and maybe “some features” could be a link to a search for "libs/api”

**Comment by pauby** [comment]
> How so?

In this security concious climate if I use an app / extension that requires the wide ranging permissions that yours does and nobody has clarified why it needs them I tend to uninstall and walk away as I see that as suspicious. Transparency is far more important. That's my personal feelings on this. My 2 cents worth or whatever you want to call it. But I do know I'm not alone.

> Maybe “some features” could be a link to a search for "libs/api”

That's an excellent idea. I would (personally) still like to see it in the docs / README for complete coverage but that's just me.

**Comment by bfred-it** [comment]
You skipped the second sentence. You don’t need to add a token at all, so I’m not sure of what you’re talking about about.

**Comment by pauby** [comment]
I didn't skip the second sentence. I read everything you said.

What I'm trying to say is that being opaque rather than transparent about WHY you need the permissions (whether they are optional or not) then that is suspicious. 

To NOT be suspicious, be transparent and make it easy for people to find out WHY you need these permissions and WHAT they are for (optional or not). Yeah you can wait for things to break. Awesome. How does that help me? So something's not working and I have a look and find out that I need to give your extension complete control over my repo's to fix it? Can you not see how that seems suspicious.

You're right, you could probably search and find out where it's needed but why not help the users but showing them wwhat they need to search for? Help the user. Make it easy for them to use your extension by providing them the info they need and not make them trawl through the codebase for it.
