### ISSUE TITLE
Comment fields stay tall after the comment is submitted

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#1977]
1. Write a long comment on this issue
2. See the `textarea` expand
3. Submit the content
4. The `textarea` height should reset but it doesn't

This is probably because GitHub resets the content via `.value = ''` and that doesn't trigger the `input` event that [`fit-textarea`](https://github.com/bfred-it/fit-textarea) waits for.

However, GitHub's own `textarea` resizer works correctly so they must have some other way to trigger this reset, like a custom event.

**Comment by notlmn** [comment]
g
asd
g
af
ga
sg
adsf
g
asf
ga
sfg
a
sdfg
ad
fg
as
fg
asd
ga
fg
a
sdg
adfgs
fghdfg
sd
fhdsfs
d

**Comment by notlmn** [comment]
fasdfasdfasdf
as
df
asdf
as
df
as
df
asdf
as
df
as
dg
as
g
asdg
as
df
as
dg
asdg
as
dg
as
dg
asd
g
asd
g
asdg
as
dg
as
dg
as
df
as
df
as
df
asdg

asd
gasdf

**Comment by notlmn** [comment]
fasdfasf



fa
sdf
as
d

**Comment by notlmn** [comment]
fasdf
as
df
asd
f
asd
f
as
df
as
df
as
df
as
df
asd
f
asdf
a
sdf
a
sdf
as
df
as
df
asd
f
asd
f
asdf
a
sdf
a
sdf
as
df
as
df
as
df
as
df
asd
fa
sdf
a
sdf
as
df
as
df
as
d

**Comment by notlmn** [comment]
I don't see this, after submitting the comment, the `textarea` does reset back to normal height.

----------------------

> This is probably because GitHub resets the content via `.value = ''` and that doesn't trigger the `input` event that [`fit-textarea`](https://github.com/bfred-it/fit-textarea) waits for.
> 
> However, GitHub's own `textarea` resizer works correctly so they must have some other way to trigger this reset, like a custom event.

GitHub uses `reset` events on the inputs elements `form` nodes (👌) to cleanup all the things. ([source](https://github.com/github/textarea-autosize/blob/bfe53e621f8f5b36a8475856a92f7700f10def32/textarea-autosize.js#L67-L71))

**Comment by bfred-it** [comment]
Ah that’s great! 

I’m using Firefox so perhaps chrome fires an `input` event and it works for you. 

So there are two things I should do:

- add a `reset` handler in “comment field shortcuts”
- add a `reset` handler in `fitTextarea.watch`

**Comment by notlmn** [comment]
asd
fa
sdf
as
df
asd
f
asdg
as
df
as
df
asdf
as
df
as
df
asdf
a
sdf
as
df
asd
fa
sdf
as
df
asd
f
asdf
a
sdf
asd
f
afds
m

**Comment by notlmn** [comment]
fasd
fa
sdf
a
sdf
as
df
as
df
a
sdf
a
sdf
a
sdf
as
df
asdf
as
df
as
df
asd
f
asd
fa
sd
fa
sd
f
asd
f
as
df
as
df
asd
fa
sdf

**Comment by notlmn** [comment]
fasd
as
df
as
df
as
df
as
df
as
df
as
df
asd
f
asd
f
asd
f
asd
f
asd
fa
sdf
a
sdf
a
sdf
as
df
asd
f
asd
fa
sdf
a
sdf
as
df
asd
f
asd
f
asd
fa
dsf

**Comment by notlmn** [comment]
dfasdf
f
as
df
asd
f
asd
fa
sdf
as
df
as
df
as
df
as
df
as
df
asd
f
asdf

asd
fa
sdf
a
sdf
as
df
as
df
asd
f
asd
f
asdf
a
sdf
as
d

**Comment by fregante** [comment]
I can't reproduce anymore. `fit-textarea` has a `reset` handler now
