### ISSUE TITLE
`show-names` feature  broken

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#1978]
```
❌ show-names
content.js:1880 Error: GraphQL:
Parse error on "[" (LBRACKET) at [1, 61]
    at content.js:1992
```

https://github.com/highlightjs/highlight.js/pull/2023

**Comment by bfred-it** [comment]
Interesting. The bot has a link but:

- the link is a 404
- the hovercard also fails to load

Since `[` isn't allowed in a real username, we could do one of these two things:

- skip names with `[` (they're bots)
- don't add names to commits, which I think is duplicate info anyway 🤔

cc @sindresorhus and @DrewML (original author) thoughts?

**Comment by notlmn** [comment]
> Interesting. The bot has a link but:
> 
> * the link is a 404
> * the hovercard also fails to load

That's an issue from GitHub, the bot has a valid username (`greenkeeper`), but GH mistakenly appends `[bot]` to the link. GH was only supposed to append it to the text inside link, not the `href` of the anchor tag too (github.com/greenkeeper _is_ a valid link).

-------------------------

> * skip names with `[` (they're bots)

How about removing that while querying, for now. Can be documented as a case for bot names.

-------------------------

> * don't add names to commits, which I think is duplicate info anyway 🤔

Yup agree, emails always exists, names may not (can be empty).

**Comment by sindresorhus** [comment]
> skip names with [ (they're bots)

👍 

> don't add names to commits, which I think is duplicate info anyway 

👍

**Comment by lukehefson** [comment]
> /cc @lukehefson @shayfrendt

Going to throw a comment out to my rad rad colleague @jmilas who I _believe_ would have more context around this 😄

**Comment by jmilas** [comment]
> That's an issue from GitHub, the bot has a valid username (greenkeeper), but GH mistakenly appends [bot] to the link. GH was only supposed to append it to the text inside link, not the href of the anchor tag too (https://github.com/greenkeeper is a valid link).

:wave: I work with the GitHub Apps and API teams at GitHub, so I can help to dig in on this.

Bots and Apps are a bit tricky, so to make sure I fully understand - can you share a bit more detail around when/where you're seeing this behavior? If there's a specific query you could point me to, that'd be super helpful.

**Comment by bfred-it** [comment]
https://github.com/highlightjs/highlight.js/pull/2023

On this page there are two links to greenkeeper

- the comment author
- the commit author

The first one links to the real account while the second one includes `[bot]` in both the name and the URL, making it incorrect and pointing to a 404

**Comment by bfred-it** [comment]
![3A9689BE-BAD4-4EDE-8422-C0D6928FE362](https://user-images.githubusercontent.com/1402241/56830596-53662980-6899-11e9-905c-0f608ad1fa01.jpeg)

**Comment by jmilas** [comment]
Thanks for the details @bfred-it. We'll get that fixed.

**Comment by yakov116** [comment]
@bfred-it it was fix but...

```
❌ show-names
content.js:1880 Error: GraphQL:
Could not resolve to a User with the login of 'greenkeeper'.
    at content.js:1992
```

It still errored out Since the link changed (its now marketplace)

**Comment by bfred-it** [comment]
New error even on the current page 😅
```
TypeError: "names[userKey] is undefined"
    show_names_init moz-extension://03ea1fad-5d68-ca45-a1c5-6257313c7f47/content.js:4586
```

**Comment by yakov116** [comment]
@bfred-it not seeing that 😕

**Comment by fregante** [comment]
@jmilas there's a similar bug in "Edit history" modals: https://github.com/sindresorhus/refined-github/issues/2161 (+ related feature request)
