### ISSUE TITLE
In file History pages, add links to the file itself

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#1979]
Example: https://github.com/sindresorhus/refined-github/commits/2190e1a6f68e483f43bfda3a03d82542cda6f05f/source/features/show-names.js

There's a `<>` icon that points to the whole repo at the time of the commit, but this lacks a link to the file itself.

I think GitHub doesn't have a link here because they reused a regular "commits list", so the link to the whole repo makes sense. e.g. https://github.com/sindresorhus/refined-github/commits/master

But if a file is selected, then this fundamental link is missing.

**Comment by sindresorhus** [comment]
Accepted

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by bfred-it** [comment]
Suggested look:


<img width="957" alt="" src="https://user-images.githubusercontent.com/1402241/56788132-2d0ca380-6831-11e9-87b1-d6ff351eeca4.png">

Via 

- `icons.file`
- `groupButtons()`
