### ISSUE TITLE
Sort organization list

### ISSUE THREAD

**Issue by blainsmith** [sindresorhus/refined-github#198]
GitHub seems to order the Organization list however it wants to. Unfortunately, my most frequently accessed ones are at the bottom. I might be useful for people who are apart of a lot of Organizations, that cause the dropdown to be scrollable, to allow us to sort them anyway we want. Perhaps save the order in local storage?

**Comment by sindresorhus** [comment]
How about sorting it by usage?

**Comment by blainsmith** [comment]
Even better! I've looked through most of the Organization lists in Settings, Profile pages, etc to see if there was any rhyme or reason behind the order and I don't see any. If the plugin can track usage somehow and self sort that way I would love that more.

**Comment by hkdobrev** [comment]
FWIW I think the current default order by GitHub is the following:

0\. Your own personal account.
1. Oldest created organisation you are a member of
2. Second oldest
.
.
.
3. The youngest organisation you are a member of.

So it's based on the date creation of the organisation, not the date you've joined it.
