### ISSUE TITLE
«Show All Files» and «Collapse All Files» work the other way around

### ISSUE THREAD

**Issue by karol-majewski** [sindresorhus/refined-github#1982]
Seems like these two are doing something else than they say. See the attached GIF:

![https://i.imgur.com/ZKqlPMd.gif](https://i.imgur.com/ZKqlPMd.gif)

URL: https://github.com/prettier/prettier-vscode/pull/812/files

**Comment by bfred-it** [comment]
We don't add those buttons. Probably another extension is conflicting

**Comment by karol-majewski** [comment]
You are correct. These buttons disappear when I disable GitHub Refined, which made me think that's the culprit, but in reality, it was GitHub Diffs.
