### ISSUE TITLE
Update feature `linkify-branch-refs`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#1985]
It's been added by GitHub, however their version doesn't add a strike-through to deleted branches. Perhaps the feature should just add a strike-through.

Testing threads:

- deleted branch: https://github.com/sindresorhus/refined-github/pull/576
- deleted branch (from fork): https://github.com/sindresorhus/refined-github/pull/872
- restored branch (on fork): https://github.com/sindresorhus/refined-github/pull/909

**Comment by sindresorhus** [comment]
> Perhaps the feature should just add a strike-through.

👍

**Comment by bfred-it** [comment]
Ah, GitHub's own linkifier doesn't linkify the branch in the QuickPR page, so maybe we should only limit the scope: https://github.com/sindresorhus/refined-github/issues/691

**Comment by jerone** [comment]
The feature [`linkify-branch-refs`](https://github.com/sindresorhus/refined-github/blob/master/source/features/linkify-branch-refs.tsx) currently adds double links on [PR](https://github.com/sindresorhus/refined-github/pull/576):

![image](https://user-images.githubusercontent.com/55841/60004890-bb54a880-966d-11e9-9929-b1dc25d205fc.png)

**Comment by gurrrung** [comment]
@jerone So we have to remove unwanted one right?

**Comment by fregante** [comment]
This issue is to be solved in 3 parts:
1. Avoid linkifying the branches on PRs
2. Only add a strike through on deleted branches in PRs
3. Keep linkifying “quick PR” pages

**Comment by fregante** [comment]
This is now mostly solved. I'm moving back to #2274 because it's more specific.
