### ISSUE TITLE
Drop feature `mark-merge-commits-in-list`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#1988]
Merge commits are not highlighted at all on GitHub anymore, which is awful.

Our feature can't work anymore and should be dropped. 

Example of how to drop a feature: https://github.com/sindresorhus/refined-github/commit/76cc04d4b69974ce4aa8c02ed2afedb66ad66cd8

**Comment by sindresorhus** [comment]
@bfred-it Can you report that to GitHub? That must be a bug.

**Comment by bfred-it** [comment]
As discussed in chat, not a bug since they never actually highlighted the merge commits https://github.com/sindresorhus/refined-github/issues/94

Feature can be dropped
