### ISSUE TITLE
Last comment editing time

### ISSUE THREAD

**Issue by lex111** [sindresorhus/refined-github#1990]
It would be nice to display in the comments the date (relative time) of the last edit like this:

![image](https://user-images.githubusercontent.com/4408379/56849511-036d7e00-68fe-11e9-95fe-7964b5cb44d7.png)

**Comment by bfred-it** [comment]
Sadly this probably requires additional HTTP requests (maybe one per comment) and it's not immediately useful information (it's already available on click, when necessary)

**Comment by lex111** [comment]
No need to make HTTP requests, I just suggest showing the first item from the dropdown. Isn't that easy to do?

![image](https://user-images.githubusercontent.com/4408379/56850617-abd70e80-690d-11e9-9226-d7c4f20e2765.png)

**Comment by bfred-it** [comment]
1. Load the current page
2. Go offline
3. Click edited

You'll see that that information is **loaded** in after the user clicks on Edited

**Comment by sindresorhus** [comment]
I don't think this is info is important enough to add extra overhead and clutter the UI.

**Comment by lex111** [comment]
I agree, I didn't know that this would entail overhead.
