### ISSUE TITLE
`Blame parent` link in blame view

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#2]
Often when I blame something there are useless noise commits obscuring what I'm actually looking for, which means I need to go one commit back from that commit that made the noise, and then blame again to get what I'm actually after. Would be useful to have a link to go one commit back in the blame view.

**Comment by paulmolluzzo** [comment]
Some sort of annotated screenshot would clarify this ticket a bit.

**Comment by sindresorhus** [comment]
In the blame view, like https://github.com/sindresorhus/refined-github/blame/master/extension/content.js, I would like to to change the blame view to the parent commit of the one currently on the left side, as I want to know what happened to that piece of code before the commit currently there.

![image](https://cloud.githubusercontent.com/assets/170270/13157567/252fd386-d6bb-11e5-887a-645f6dda90dd.png)

So in the above screenshot I would like an extra link for each blame that says `Blame parent` and goes to the blame view of the commit before the one referenced.

Is that clear?

**Comment by hkdobrev** [comment]
I get exactly what you need, because I've wanted that for so long. I will submit a PR in a few minutes if everything goes to plan.

**Comment by sindresorhus** [comment]
For reference, here's how it looks now:

![napkin 26-02-16 1 58 44 pm](https://cloud.githubusercontent.com/assets/170270/13345493/bd1eee30-dc91-11e5-85dc-e4bdda3d18a8.png)
