### ISSUE TITLE
Bring networks graph back?

### ISSUE THREAD

**Issue by HardikModha** [sindresorhus/refined-github#2001]
So today, GitHub announced on their blog that they are deprecating the Network graph. https://github.blog/changelog/2019-05-01-deprecating-the-network-graph/ 
(Update: Seems like it's already gone)

Personally, I used this feature for finding the active forks for any unmaintained project but there are people who also used this feature for various purposes. 

What do you guys think? Should we have some functionality in-place as a replacement for this?

//cc @bfred-it @sindresorhus

**Comment by bfred-it** [comment]
This one https://github.com/sindresorhus/refined-github/network

There’s no way we can replicate that
