### ISSUE TITLE
Drop `bypass-checks` feature

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2003]
It appears that GitHub no longer links to the Checks page on PRs' "mergeability details" box. If this is confirmed, we should drop the feature.

See a previous removal on how to drop it: [e8105c6](https://github.com/sindresorhus/refined-github/commit/e8105c631a11e7fa4022a80e2c47fa5d2145f6f8)

**Comment by gurrrung** [comment]
I can't find the changelog post for this.

**Comment by bfred-it** [comment]
Indeed, the links point to Travis if Checks aren't set up (like in this repo) but they still point to the useless Checks page otherwise. Example: https://github.com/microsoft/TypeScript/pull/32386
