### ISSUE TITLE
`batch-open-issues` isn't working unless you select issues

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2004]
1. Visit https://github.com/pulls
2. No "Open all" link visible

![image](https://user-images.githubusercontent.com/5332158/50737688-67cfca80-11b3-11e9-9361-9b0a8b62cdf5.png)

**Comment by sindresorhus** [comment]
// @ahmadassaf

**Comment by ahmadassaf** [comment]
hmm looks like Github changed some class names. Will look into this :)

**Comment by ScopeyNZ** [comment]
`.table-list-header` has been removed. Just removing that from the selector should fix the issue?

**Comment by bfred-it** [comment]
Can you send a PR? 🙂

**Comment by ScopeyNZ** [comment]
Done :) #2015
