### ISSUE TITLE
Rename "Blame" to "Praise"

### ISSUE THREAD

**Issue by gaborcsardi** [sindresorhus/refined-github#2005]
To stay positive, how about renaming the "Blame" button in the source code view, to "Praise", and potentially also in the pop-up menu when you click on a line, and then on the "..."?

E.g. on 
https://github.com/sindresorhus/refined-github/blob/master/source/content.css

<img width="490" alt="Screen Shot 2019-05-02 at 9 59 58 PM" src="https://user-images.githubusercontent.com/660288/57106583-b20e2600-6d25-11e9-8ad9-adab4988a247.png">
<img width="590" alt="Screen Shot 2019-05-02 at 10 00 08 PM" src="https://user-images.githubusercontent.com/660288/57106584-b20e2600-6d25-11e9-8d99-dffb076d79e3.png">

**Comment by lazarljubenovic** [comment]
To stay positive, never let a well-established command name affect you negatively.

**Comment by bfred-it** [comment]
I understand the intent but this would confuse people rather than help them, so we’re not the right place to do this.

**Comment by sindresorhus** [comment]
Instead, request it at support@github.com.
