### ISSUE TITLE
Convert LOC links to point to specific commits, not branches.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#201]
When linking to specific lines of code, it's often better to provide a link to a specific commit, rather than a branch:

1 - https://github.com/sindresorhus/refined-github/blob/7cccdf21946695dc943ee4f77e174978085e17d6/test/page-detect.js#L1

2 - https://github.com/sindresorhus/refined-github/blob/master/test/page-detect.js#L1

Code changes over time, so linking to a branch can cause the link to go out of sync with that branch if line numbers change.

I think links written as `2` should be automatically converted to `1` before submitting the comment.

Perhaps we could append the original intended branch as a parameter `...#L1?refinedGH_originalBranch=master`, and allow refined-github users to see both the original link and the modified one. Alternatively, if we think this rewrite would cause some negative side effects that prevent us from doing it, we could append a `currentCommit` parameter and use refined GH to rewrite (I don't love that because it drastically reduces the number of people who benefit).

**Comment by sindresorhus** [comment]
👍 I always press `y` before copying the URL to some code to get the canonical link, but I rarely see people doing this and it's super annoying looking through old issues with broken master-pointing code references.

**Comment by DrewML** [comment]
@jamestalmage How would you feel about doing this when a user of the extension copies the link, rather than when they paste it? That way, we'd avoid the additional XHR that we'd need to fetch the current commit hash.

**Comment by sindresorhus** [comment]
@DrewML How are you gonna do that? Most copy from the browser URL bar.

**Comment by DrewML** [comment]
`pushState` :)

**Comment by paulmolluzzo** [comment]
I also always press `y` ([it's the right way to do this after all](https://help.github.com/articles/getting-permanent-links-to-files/)), and pretty much always do that because I'm copying the URL. What if we just append copying to the clipboard to the `keypress` event? That way if you press `y` it changes the URL and automatically copies it to the clipboard. This makes the usual behavior a "new feature" and all new links work for non-extension-users.

**Comment by DrewML** [comment]
@paulmolluzzo I'm not 100% opposed to the idea, but I would guess a good number of users don't know about `y`, or they'd already be using it. Additionally, some extensions ([Vimium](https://chrome.google.com/webstore/detail/vimium/dbepggeogbaibhgnhhndojpepiihcmeb?hl=en) is one example) break some of the hotkeys on GitHub, including `y`.

**Comment by paulmolluzzo** [comment]
@DrewML that's why I said we'd have to promote it as a "new feature". As for other plugins, IDK that we could do anything about that, but avoiding a feature because another extension disables it isn't a great idea IMO. Anyone with both extensions would have to reconcile that conflict on their own.

**Comment by jamestalmage** [comment]
> How would you feel about doing this when a user of the extension copies the link, rather than when they paste it? 

I was thinking of just intercepting the submit, and scanning the text area for links then, but doing it on paste might be easier.

> I would guess a good number of users don't know about `y`

Agreed, I didn't.

Now that I do, I kinda like the idea of just copying to the clipboard on `y`. Seems easier to implement.

**Comment by DrewML** [comment]
Cool - sounds like majority consensus is a copy on `y`.

A quick note to whoever ends up working on this: We already have code in `copy-file.js` that handles the bit of DOM work needed to do a copy. We should move that out to `util.js`.
