### ISSUE TITLE
Add the tag button provided by "branch-buttons" to the compare page

### ISSUE THREAD

**Issue by ScopeyNZ** [sindresorhus/refined-github#2018]
Example URL: https://github.com/sindresorhus/refined-github/compare/19.5.6.1914...master

Often when comparing branches I want to make the base the latest tag. Using the dropdown - you cannot select tags, you need to type them. I find myself often opening the home page of the repo in a new tab and looking at the button provided by the "branch-buttons" for the latest tag.

It'd be awesome if the button would also set the "base" dropdown to the tag, but maybe that's a little too opinionated?

This is very similar to #1197 - I'm not sure if it's sufficiently different to have a separate issue 😅

**Comment by bfred-it** [comment]
Tags already kind of work this way:

1. Open the tags page
2. Click the “XX commits on master since this tag”

Alternatively, once #1197 is in:

1. Visit the latest tag
2. Then click compare
3. Then select the branch (the tag will be filled in)

**Comment by bfred-it** [comment]
> Using the dropdown - you cannot select tags, you need to type them

Send them a feature request. This kinda annoys me too, but I rarely need it

**Comment by bfred-it** [comment]
Comparing a random branch is a little too opinionated to need a specific button.

If you need to do this, it's best to go the other way


1.    Visit the latest tag (even from the repo root)
1.    Then click compare
2.    Then select the branch (the tag will be filled in)
