### ISSUE TITLE
Show status of linked-to PR/Issue

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#202]
If there is a link to another issue/PR, I should somehow be able to identify it's status (green/red/purple color coding, or inline a badge).

**Comment by sindresorhus** [comment]
👍 That would indeed be useful.

**Comment by adjohnson916** [comment]
@jamestalmage I've discovered (but not tried or inspected source so cannot yet recommend) https://justineo.github.io/github-hovercard/.

**Comment by hkdobrev** [comment]
Duplicate issue with some useful discussion: #373

**Comment by bfred-it** [comment]
I'd love to see this. Relevant comments from that repo:

> Would be useful indeed, but we would have to use the GitHub API for this, which has limits on how many requests we can do, so it gets complicated fast. We would also need to have an options page for the user to save their token. We could fetch the whole page instead and have no limits, but that's wasteful.

> Regarding the actual UI, I'd go with an icon of open/closed issue/PR. This way you'll also know what's this number is referring to.

What's the preferred course of action? I think we should start using the API without a token and add a `token` field in the options to enable private repos support and increase the limits.

**Comment by bfred-it** [comment]
There's one issue with the icons though: change of layout. We already change links on load in #473 and that causes text to move around, but it happens once right after the page load. This would happen many times as the fetches finish loading and it could get annoying fast.

Either we skip the icon (and keep the color) or we make replace the # with it, making sure it's the same exact width.

**Comment by jgierer12** [comment]
We could add a padding via CSS and make the icon absolutely positioned

**Comment by bfred-it** [comment]
Hey, that's an easy way out. 👍 It'll also need a temporary icon then because otherwise the extra padding will look bad until the icons are in.

**Comment by bfred-it** [comment]
Here you go! 

https://github.com/bfred-it/github-issue-link-status

https://chrome.google.com/webstore/detail/github-issue-link-status/nbiddhncecgemgccalnoanpnenalmkic

<img width=640 src="https://raw.githubusercontent.com/bfred-it/github-issue-link-status/master/screenshot.png">
