### ISSUE TITLE
`link-to-file-in-file-history` redirects to 404

### ISSUE THREAD

**Issue by dotconnor** [sindresorhus/refined-github#2024]
The icon should not show up when on the branch's commits page for example: https://github.com/sindresorhus/refined-github/commits/master, as it just redirects to a 404 page.

@HardikModha

**Comment by Abraham6754** [comment]
Si, you need some help?

**Comment by Abraham6754** [comment]
Sorry...

So, you need some help?

**Comment by bfred-it** [comment]
Ahhh I saw this bug and forgot to fix it

**Comment by Abraham6754** [comment]
Hahaha, relax Bro, u can do that

**Comment by Abraham6754** [comment]
Just need do nice the work
