### ISSUE TITLE
Native browser textarea resize does not work when refined is enabled

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#203]
I haven't looked into _why_ yet, but vertical resizing doesn't seem to work when I have the extension enabled. Anyone else see similar behavior?

![image](https://cloud.githubusercontent.com/assets/5233399/15094869/31e78516-1477-11e6-9f8f-515302fafd50.png)

**Comment by sindresorhus** [comment]
Wild guess, might be: https://github.com/sindresorhus/refined-github/commit/60c56b0ddd06cc1aca93945b5b86235789f52d1c
