### ISSUE TITLE
Drop `emojis-title` feature

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2035]
> [`emojis-title`] takes the `alias` attribute (provided by GH) of the emoji, and adds it as a title (if any of its closest parent doesn't provide one).
>
> Presumably so that anyone without access to an emoji keyboard (picket) can use this info to insert emojis in comments.
>
> Considering that GitHub already provides autocomplete for emojis in desktop view and that the `title` attribute is useless on mobile devices, I think this feature can be dropped. 🤷‍♂️

_Originally posted by @notlmn in https://github.com/sindresorhus/refined-github/pull/1881_

**Comment by sindresorhus** [comment]
I was about to open the same issue. Let's drop it.
