### ISSUE TITLE
Feature `hide-empty-meta` is broken

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2037]
> I think it's broken as it's supposed to hide this italics text
> 
> <img width="1123" alt="Screenshot 2019-05-13 at 23 30 11" src="https://user-images.githubusercontent.com/1402241/57634045-26bf4b00-75d7-11e9-802f-09f105f9610e.png">
>
> Live demo: https://github.com/bfred-it/temp

_Originally posted by @bfred-it in https://github.com/sindresorhus/refined-github/pull/2030/files/5ac58f64b8e7d4479b84acc56b1fe1723ae042e2_

**Comment by yakov116** [comment]
New Selector is `d-flex flex-items-start`

**Comment by bfred-it** [comment]
😬 rather generic

**Comment by manuel678** [comment]
Unsubscribe me plese now
