### ISSUE TITLE
Add newsfeed autoload option

### ISSUE THREAD

**Issue by Kinrany** [sindresorhus/refined-github#2039]
As far as I can tell there's no option to disable autoloading newsfeed.

This is a problem for me because it makes the footer of the main page unreachable. The links in the footer are convenient, and it doesn't make sense to navigate to another page just to reach them.

(There's also that autoloading makes the experience slightly more addictive because you don't get to make an explicit decision to view more content.)

Example URL: https://github.com/

**Comment by bfred-it** [comment]
It’s called `infinite-scroll` and it can already be disabled

**Comment by Kinrany** [comment]
Thanks!
