### ISSUE TITLE
Tabbing behavior in textareas should be limited to comments

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#204]
Right now, this feature is targeting [any textarea on the page](https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L224-L235).

I'm working on [this extension](https://github.com/DrewML/OctoEdit) at the moment, and `refined` is adding tabs on top of the tabs already inserted by `CodeMirror`.

I'd like to limit this behavior to just comments, rather than all `textarea` elements.

/cc @blackjid since he's working in that area for #162.

**Comment by blackjid** [comment]
You are right, in fact in the codemirror PR work I was working (#197) I used only the comment textarea, I'll change that...

**Comment by bfred-it** [comment]
I think this has since been fixed 

https://github.com/sindresorhus/refined-github/blob/6b0a6d0/src/content.js#L522
