### ISSUE TITLE
Allow rendering of large diffs

### ISSUE THREAD

**Issue by MarkTiedemann** [sindresorhus/refined-github#2043]
```
Load diff
Large diffs are not rendered by default.
```

However, when I click the `Load diff` button, GitHub still doesn't render the diff:

`16,294 additions, 0 deletions not shown because the diff is too large. Please use a local Git client to view these changes.`

Would be nice if (Refined) GitHub would render the diff, even if that means freezing my browser window for a few seconds (perhaps this would need a warning and confirmation dialog before starting the rendering...).

**Comment by bfred-it** [comment]
We can't do this because if GitHub refuses to give us a diff HTML page we have to build that ourselves, and that would be too big of a feature to include.

**Comment by MarkTiedemann** [comment]
GitHub does give us the raw patch, though, for example: https://github.com/sindresorhus/refined-github/pull/2042.patch

From that, I believe we could build a simplified diff, for example, without language-specific syntax highlighting:

```diff
 		element,
 		tag,
 		commit: select('[href*="/commit/"]', element)!.textContent!.trim(),
-		...parseTag(tag) // `version`, `namespace`
+		...parseTag(decodeURIComponent(tag)) // `version`, `namespace`
 	};
 }
 

 ```

**Comment by bfred-it** [comment]
That’s not the HTML diff I mentioned and that view doesn’t contain all the info around it and what users expect from a diff on GitHub (line numbers, linkable lines, syntax highlighting, etc)

If others think that’s “good enough” then maybe send a PR to understand what an HTML diff entails 😅
