### ISSUE TITLE
Bug with pull request helper and Github Entreprise

### ISSUE THREAD

**Issue by tristanbes** [sindresorhus/refined-github#2044]
Hello,

Better than words, here's a screenshot of the problem occuring on a Github Entreprise server resulting in breaking the header:

<img width="1135" alt="Yproximite_store-factory__StoreFactory_reborn" src="https://user-images.githubusercontent.com/346010/57857391-52b51900-77ef-11e9-94e3-15821c73e56b.png">

The difference with Public Github is that there is no text "Entreprise" in the header.

**Comment by busches** [comment]
Yea, I shimmed this fix in when RGH redid the feature last time, as it was horribly broken on GHE. Until GHE adds support for the full page width header, I'm not sure what to do. I don't want to support two versions of the code as each GHE version will be slightly different. What would you like to see happen?

**Comment by tristanbes** [comment]
maybe if you're on GHE, while they support full header, do not display "less than a minute ago" to gain spaces, that should fix it no ?

**Comment by bfred-it** [comment]
Since this feature only moves a pre-existing item, I'd suggest to just disable it for the time being.

**Comment by bfred-it** [comment]
As for the fix, it looks like it’s missing `position:absolute` because normally the bar should not affect the layout.

One element is the position holder and it’s 0px wide with `position:relative` and then the bar is inside with with `position:absolute; right:0`

Can you paste here the HTML of the whole header? Without the branches bar is fine

**Comment by tristanbes** [comment]
Sure, here's the gist:
https://gist.github.com/tristanbes/22f287a5bb2896810a3f302c68810502

**Comment by bfred-it** [comment]
It looks like the position is correct, but my guess is that this selector isn't being applied (or `position: absolute` is overridden)

https://github.com/sindresorhus/refined-github/blob/1e631d2624916afc4a3afeeb6e1f675bda50e9ee/source/features/recently-pushed-branches-enhancements.css#L7-10

**Comment by notlmn** [comment]
Couldn't this be easily solved by expanding the header to be full width!?

**Comment by busches** [comment]
> Couldn't this be easily solved by expanding the header to be full width!?

Yes and eventually GHE will be have the same header as GH and it will just work. I personally have no problem with the way the feature works on GHE, is it 100% ideal? No, but is it better compared to the feature being disabled? Yes. If someone disagrees, then they can disable it or offer a minimal patch to make it look better.

I will take a look at @bfred-it's suggestion on Monday, but I'm 99% sure I tried that originally and it was worse than the current state.

**Comment by simonkotwicz** [comment]
I agree that overriding the max-width of the header seems like the easiest solution.
```
.Header .container-lg {
    max-width: none
}
```

**Comment by bfred-it** [comment]
We’re not gonna drop max-width because that’s an unrelated changed and only solves the problem if your window is wide enough. 

That position:static is exactly the issue. Can you take a screenshot of what it looks like without it?

**Comment by simonkotwicz** [comment]
> We’re not gonna drop max-width because that’s an unrelated changed and only solves the problem if your window is wide enough.

Sorry, I meant ideally we'd fix the absolute positioning and the header width.

With... 
```
/* Fix positioning on GHE */ 
.rgh-recently-pushed-branches.enterprise [data-url$="recently_touched_branches_list"] .mb-3 {
    top: -1px;
}
```
it looks like:

<img width="995" alt="Screen Shot 2019-05-20 at 9 04 25 AM" src="https://user-images.githubusercontent.com/12237902/58024188-9f467000-7adf-11e9-963c-f5268fb37916.png">

Without the `top: -1px;`, it's a bit too high.

**Comment by bfred-it** [comment]
Ok 🙂
