### ISSUE TITLE
Custom CSS doesn't work in Firefox

### ISSUE THREAD

**Issue by mohd-akram** [sindresorhus/refined-github#2047]
URL: https://github.com/sindresorhus/refined-github

Custom CSS:
```css
body {
  background-color: red;
}
```

Firefox version: 68.0b2
Extension version: 19.5.17.1704

Console:

```
Webconsole context has changed
Updating form options.js:218:17
disabledFeatures : options.js:223:21
customCSS : body {
   background-color: red;
} options.js:223:21
personalToken : options.js:223:21
logging : true
```

![rg](https://user-images.githubusercontent.com/1823771/57962833-0cfe6a80-792d-11e9-98ef-960f16c74868.PNG)

**Comment by gwarser** [comment]
Does it work at all?

On extension startup I see this in browser console:

     SyntaxError: invalid regexp group 4 content.js:1:1

**Comment by bfred-it** [comment]
> Does it work at all?

Indeed. It wasn't working for me in Firefox but I thought it was just Firefox being broken.

cc @HardikModha the regex used in `semver-regex` isn't supported by Firefox, like https://github.com/sindresorhus/refined-github/pull/1936#discussion_r276515991

**Comment by HardikModha** [comment]
I just noticed this comment, I was on vacation. Acknowledged. I didn't check that on Firefox. 🤦‍♂ 😅
