### ISSUE TITLE
Show tags for commits that are not in the master/main branch

### ISSUE THREAD

**Issue by simonkotwicz** [sindresorhus/refined-github#2048]
Github only shows tags for commits that are in the main/master branch. I don't see any reason not to display tags for commits outside the master branch since tags don't necessarily need to point to a commit in the master branch in the first place.

Commits not in the master branch should show tag information the same way as a commit in the master branch does: https://github.com/sindresorhus/refined-github/commit/3cfdb31c80dce46ba592e0a520ae0e3ac25f69d9

**Comment by bfred-it** [comment]
If https://github.com/sindresorhus/refined-github/pull/2026 is merged, then we'll be able to do this, however I'm not a fan of potentially downloading multiple pages of tags just to find it so that PR is stalled too.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/2026 has been merged so you can use its mechanism and cached data to display this information. But I don’t see this feature getting a lot of interest. 

PR welcome if you send it though
