### ISSUE TITLE
Green arrow in the release notes issue is pointing too far down

### ISSUE THREAD

**Issue by lode** [sindresorhus/refined-github#2051]
With the clean issue/PR sidebar feature https://github.com/sindresorhus/refined-github/pull/2011 (which is great!) the green arrow in https://github.com/sindresorhus/refined-github/issues/1137 is not pointing to the subscribe button anymore.

![afbeelding](https://user-images.githubusercontent.com/511245/57973276-c77e8380-79a6-11e9-8c82-5e0aa14a9250.png)

**Comment by bfred-it** [comment]
Self-xkcd
[![](https://imgs.xkcd.com/comics/workflow_2x.png)](https://xkcd.com/1172/)

**Comment by bfred-it** [comment]
How does it look now? I had to guess its position because my sidebar is different:

<img width="1110" alt="" src="https://user-images.githubusercontent.com/1402241/57973482-d7648a80-79db-11e9-8cae-069e7d739feb.png">

**Comment by lode** [comment]
Perfect!

![afbeelding](https://user-images.githubusercontent.com/511245/57973490-b125f700-79a9-11e9-9e95-4d62ea044e32.png)

(For people without edit rights then :))

**Comment by bfred-it** [comment]
Thanks for the report and followup!
