### ISSUE TITLE
19.5.19.1032 breaks home page news feed and show all feeds

### ISSUE THREAD

**Issue by iamsauravsharma** [sindresorhus/refined-github#2054]
New updated version 19.5.19.1032 breaks out news feed design of GitHub home page. News feed starts to show all unwanted feed instead of hiding it
. It was properly working on older versions of extension 19.5.18.1919 checked by installing older version

**Specs:**
Browser:- Firefox 66.0.5
Extension version:- 19.5.19.1032

**Expected news feed (older version news feed)**
![Screenshot_20190519_205104](https://user-images.githubusercontent.com/38726015/57984318-5c9e7c80-7a7a-11e9-9be0-a2f83ce40652.png)

**Actual news feed(current Version news feed)**
![Screenshot_20190519_205626](https://user-images.githubusercontent.com/38726015/57984320-60320380-7a7a-11e9-861e-764079b0368d.png)

**Comment by bfred-it** [comment]
Yeah for some reason there was a new version pushed with an old tag. I released a new version now
