### ISSUE TITLE
Disabling clean-sidebar does not disable clean-sidebar

### ISSUE THREAD

**Issue by sunjay** [sindresorhus/refined-github#2057]
Here are the settings I have configured:

---
![image](https://user-images.githubusercontent.com/530939/57988565-dbd18780-7a5d-11e9-91c0-5f77aa4f6372.png)

---

This is [the PR](https://github.com/rust-lang/rustup.rs/pull/1860) sidebar with refined-github enabled:

---

![image](https://user-images.githubusercontent.com/530939/57988572-f7d52900-7a5d-11e9-94e3-09d6d28b46a6.png)

---

This is the PR with refined-github disabled:

---

![image](https://user-images.githubusercontent.com/530939/57988583-11767080-7a5e-11e9-8e6c-06d214c3ff81.png)

---

As you can see, disabling the clean-sidebar feature does not bring back anything in the sidebar. Am I disabling the wrong feature?

I can't find clean-sidebar listed in the console whether I have it in my disabled features list or not. That makes me think that maybe it is actually called something else? It's in the files list, so I'm not sure why this wouldn't be working.

**Comment by busches** [comment]
The name of the feature in the file is wrong, https://github.com/sindresorhus/refined-github/blob/dfee7e87714c07941119809f6674fd742524c52b/source/features/clean-sidebar.tsx#L86
