### ISSUE TITLE
Unread notifications from GHE appear on Github and vice versa

### ISSUE THREAD

**Issue by simonkotwicz** [sindresorhus/refined-github#2065]
Can we display notifications marked as unread from the same domain only?

**Comment by bfred-it** [comment]
This needs a filter in `getNotifications`, like
```js
unreadNotifications = unreadNotifications.filter(({url}) => url.startsWith(location.origin));
```

**Comment by simonkotwicz** [comment]
thanks, just wanted to make sure it would be accepted first before making a PR.
