### ISSUE TITLE
Add total story points to project columns

### ISSUE THREAD

**Issue by reyraa** [sindresorhus/refined-github#2069]
### Description
Could we add total story points of the tickets in each project column right by the name of the column?
The story points can be defined using labels. Say we create labels like `SP: 1`, `SP: 2`, `SP: 3` and so on, then use them to estimate each ticket.
This feature sums up the story points of all tickets, considering the applied filters, and shows up the sum right by the name of the column.
This will help us understand the total story points assigned to each team member.

### Motivation
Eliminate the need for using a secondary project management tool like Zenhub or Jira.

### Requirements
Every ticket must have an estimation label which followed certain syntax.

**Comment by bfred-it** [comment]
This is very specific to a certain workflow and content formatting, it should be its own extension or part of a productivity/management extension.

**Comment by yacc** [comment]
@reyraa I came across this extension that does pretty much what you're describing: 
https://github.com/elastic-coders/github-project-story-points
