### ISSUE TITLE
Pulse tab gone ?

### ISSUE THREAD

**Issue by tristanbes** [sindresorhus/refined-github#207]
Hello,

After installing your extension, where the pulse tab has gone (to get repository stats, push activity over 30 days...) :-)

thanks.

**Comment by hkdobrev** [comment]
@tristanbes The Refined GitHub extension intentionally removes this tab. It aims to reduce clutter and the Pulse tab is not so often used and admittedly is rarely helpful. You could override the extension styles and show it. See how at [Customisation](https://github.com/sindresorhus/refined-github#customization). 

I'm closing this as a wontfix for now, but feel free to share thoughts on why you think the Pulse tab is important. Keep in mind the Pulse page is still accessible at its URL, just the link to it is removed.
