### ISSUE TITLE
it doesn't manages 20+ starred repos 

### ISSUE THREAD

**Issue by gurrrung** [sindresorhus/refined-github#2071]
When someone stars 20+ repo it still shows all of them in expanded form, I think there should be a minimum number after which it should be a collapsed form.
![Screenshot from 2019-05-24 18-43-50](https://user-images.githubusercontent.com/30543444/58330600-da84ce00-7e54-11e9-845a-951ecc42e844.jpg)

**Comment by bfred-it** [comment]
The uncollapsing is done via CSS so we can’t count. Also I don’t see the difference between one person starring 20 repo and 20 people starring the same amount of repo, they’re all interesting to me. 

With all of our newsfeed cleanup, stars are basically the only thing left so it makes sense to show them.

**Comment by bfred-it** [comment]
Closing because of the comment above
