### ISSUE TITLE
List of repository tabs is too long

### ISSUE THREAD

**Issue by enumag** [sindresorhus/refined-github#2072]
In my case the bar has so many tabs that the last one appears on second line.

![Screenshot_2019-05-24 ifm24 ifm24_7 cz](https://user-images.githubusercontent.com/539462/58332862-76eea680-7e3c-11e9-9a11-e1e3d771f431.png)

**Comment by bfred-it** [comment]
We should probably move Security to More. Maybe even actions

**Comment by enumag** [comment]
Agreed. Both are rarely needed.
