### ISSUE TITLE
Releases counter is missing

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2077]
Regression:

It's detected on the repo root but it's not cached from there like it should. We don't need to fetch it with the API but just remember it after visiting the root.

![3](https://user-images.githubusercontent.com/1402241/58372410-5a8f5e80-7f4f-11e9-83ad-86adba721608.gif)

**Comment by gavinhenderson** [comment]
Can I take this?

**Comment by bfred-it** [comment]
Yes!
