### ISSUE TITLE
mis-alignment of button element of `highlight-closing-pr-in-open-issues`

### ISSUE THREAD

**Issue by gurrrung** [sindresorhus/refined-github#2082]
This is the current look of the button whose element is not properly centred.
![Screenshot from 2019-05-27 17-32-23](https://user-images.githubusercontent.com/30543444/58418650-01860e80-80a6-11e9-943a-df225074114f.png)

**Comment by bfred-it** [comment]
This OS and font-dependent, on my computer it's centered

<img src="https://user-images.githubusercontent.com/1402241/58622417-1e1c8380-82fe-11e9-9ea9-68297859f538.png">
