### ISSUE TITLE
Diff: shifted indentation

### ISSUE THREAD

**Issue by pdonias** [sindresorhus/refined-github#2089]
Hi! It looks like some lines are sometimes weirdly indented:
![Capture_2019-05-28_14:29:51](https://user-images.githubusercontent.com/10992860/58478355-276aec00-8156-11e9-8119-0196514b3e7f.png)
Here's what it looks like without Refined GitHub:
![Capture_2019-05-28_14:30:30](https://user-images.githubusercontent.com/10992860/58478530-9d6f5300-8156-11e9-91a1-58b983bfb254.png)
And here's the URL to reproduce:
https://github.com/vatesfr/xen-orchestra/pull/3155/files#diff-37458fb9e51d193ef360403ba893e2e2R47

(Might be related to #2085)

**Comment by bfred-it** [comment]
I don't see any weird indentation, I think you're just noticing the missing `+` sign, which leaves the empty space behind

**Comment by pdonias** [comment]
Notice how line 50 is shifted right compared to line 49 while they should be aligned. And here's how it looks like when you select it:
![Capture_2019-05-28_14:30:07](https://user-images.githubusercontent.com/10992860/58483460-a49b5e80-8160-11e9-96ed-33fb2e694597.png)

**Comment by bfred-it** [comment]
Indeed, maybe #2088 will fix it

**Comment by pdonias** [comment]
Hopefully :)

**Comment by pdonias** [comment]
I tried to run the fix manually (simply adding the extra CSS directly in the browser) and it fixes #2085 but it doesn't seem to work for this issue so there might be something more to it.
