### ISSUE TITLE
"collapsible" file diff make it difficult to select file names. 

### ISSUE THREAD

**Issue by Carreau** [sindresorhus/refined-github#209]
Almost all in title, there is a long filename in a diff I want to copy past, 
but I can only get the magnifying glass and clicking collapse/expand the files. 

Would be nice to still have the ability copy/past filenames. 

Otherwise thanks for this great extension !

---

[update] The text seem to be selectable again, it would just be nice do not collapse expand if something is selected.

**Comment by paulmolluzzo** [comment]
Good idea! :+1:  PR welcome.

**Comment by jacobbearden** [comment]
I'm still able to highlight the text for file names and copy/paste, it just toggles collapsed/expanded when I do.

Am I looking at what this is referencing?

![pic](https://i.imgur.com/395P26a.png)

**Comment by jacobbearden** [comment]
// @Carreau @paulmolluzzo

**Comment by paulmolluzzo** [comment]
> I'm still able to highlight the text for file names and copy/paste, it just toggles collapsed/expanded when I do.
> 
> Am I looking at what this is referencing?

@jacobbearden Yup.

It does allow highlighting, but it triggers the toggle and with the cursor being the magnifying glass it's not obvious that you can still select.

Adding `cursor: text;` to that `span` makes it more obvious, but it'll need a little JS to not trigger the collapse/expand when you're selecting text.

**Comment by Carreau** [comment]
> I'm still able to highlight the text for file names and copy/paste, it just toggles collapsed/expanded when I do.
> 
> Am I looking at what this is referencing?

Hum I'm definitively able to select it now, It was clearly impossible when I opened that. 
The collapsing/expanding after releasing the click is annoying but really minor. I'll change the issue title to reflect that.

**Comment by hkdobrev** [comment]
This problem is no more. GitHub has implemented its own collapsing and we've removed collapsing from the extension: #405. Also, there's a copy button next to each file now thanks to #417 and @AshikNesin.
