### ISSUE TITLE
Apply auto-linking after unfolding diffs

### ISSUE THREAD

**Issue by wearhere** [sindresorhus/refined-github#2091]
This is a follow-up from https://github.com/sindresorhus/refined-github/issues/1499. Of the repro cases I provided there

>  URLs appear to not be linked even if the URL _as a whole_ was added ([first example](https://github.com/sindresorhus/refined-github/pull/546/files#diff-36280fbf56b6409696e3d46d6b30118fR51)), or even if they're just in comments alongside changes ([second example](https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51)—note that I unfolded the top of the diff to get there, not sure if that matters).

> URLs do appear to be linked if they're in non-PR code blocks ([third example](https://github.com/sindresorhus/refined-github/blob/3f5fc489e417d4f4a14da5ea423775e9ca9246fd/source/features/copy-markdown.js#L45)).

The first is fixed with https://github.com/sindresorhus/refined-github/pull/2066, and the third remains fixed, but the second is still broken.

I can repro both if I visit the unfolded part directly ([link](https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51)) and if I go to the folded diff ([link](https://github.com/sindresorhus/refined-github/pull/636/files)), then unfold the top (one unfold should be sufficient to see the link, at line 51).

Not sure if this is a regression or no.

**Comment by bfred-it** [comment]
Yeah this was never supported, it would be good to support it if there's a simple event to listen to. The same goes for all other features that work on diffs and code

**Comment by wearhere** [comment]
>  it would be good to support it if there's a simple event to listen to

You mean like an event for more code becoming visible on-screen? Hm… I don't know what kind of events you might be thinking of. I guess my first approach would be to detect clicks on the fold/unfold buttons and re-run any diff-processing logic after that. Probably also good to do the same after the user clicks the "this diff is too long, click to expand" button for default-collapsed files.

**Comment by bfred-it** [comment]
GitHub fires their own events, like “load” and whatnot. Someone needs to find out by looking into their code (using dom breakpoints in chrome)

**Comment by notlmn** [comment]
https://github.com/sindresorhus/refined-github/pull/2073/files#diff-ed524e4099f52cf2d11f30949a25d4e5 should fix this right!?

**Comment by bfred-it** [comment]
Indeed!

**Comment by fregante** [comment]
@notlmn we missed that part at some point I guess. The link here is not auto-linked:

https://github.com/sindresorhus/refined-github/pull/636/files#diff-36280fbf56b6409696e3d46d6b30118fR51
