### ISSUE TITLE
Filter for issues/PRs auto-sugestions

### ISSUE THREAD

**Issue by AuHau** [sindresorhus/refined-github#2092]
When you want to reference certain issue (eq. writing `#123` in textbox/editor), there is a suggestion window opened, through where you can filter out the entries using the title of the issue/PR, but if the repo has a lot of issues/PRs it is sometimes hard to find the entry you are looking for.

It would be nice to use some basic filters that would simplify this search. I believe that the most sense would be text-based filters and I think the Issue search has already pretty good system available (maybe it could be reused?).
 
For example, with using the Issue search syntax:
 - `#:type:issue` - would display only issues
 - `#:author:AuHau` - would display my issues
 - `#:label:bug` - would display bugs

In this case the syntax is `:<filter name>:<value>` where the first `:` signals that filter is following.

To be honest, this syntax seems to me still too verbose for quick and efficient search, so I would propose some custom filters and/or shortcuts like (only examples, there might be more of them that might make sense):
 - `#:t:i` = type:issues
 - `#:t:pr` = type:pr
 - `#:me` = author: me
 - `#:t:i:me` = type: issue that I am author of

Potential problem is that it would not be possible to use both filters and filtration based on the title. This problem could be resolved using a special delimiter, that would tell the parser that "from now on it is title".

For example, using `::` --> `#:me::Crash` would filter out my Issues/PRs that have "Crash" in title.

What are your thoughts on this? Is it feasible? Would PR be accepted for this sort of feature? If so, I could give it a try.

**Comment by bfred-it** [comment]
This is one of those invisible features that nobody would know that it even exists, plus it’s not easy to implement and needs documentation. We have to skip it. Perhaps try suggesting it to GitHub and creating a separate extension

**Comment by AuHau** [comment]
Well, I do not necessarily agree with you as lots of the `refined`'s features need actually discovery phase (eq. reading up on what it can do). Moreover, this could be advocated with small help on the side of the pop-up window.

But alright, I will then have a look on it as a separate extension.
