### ISSUE TITLE
Cannot see Marketplace link in default location

### ISSUE THREAD

**Issue by drewswaycool** [sindresorhus/refined-github#2093]
I have `move-marketplace-link-to-profile-dropdown` turned off, however the link still does not appear in the header links.

<img width="976" alt="Screen Shot 2019-05-28 at 3 12 25 PM" src="https://user-images.githubusercontent.com/3419661/58512817-4029d080-815b-11e9-8c3e-6db1d792ab82.png">

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/1ec1b32ec19d54d8c7b063ca5f5a36a29a7906d5/source/content.css#L38-L41

Needs to be move to the feature

**Comment by busches** [comment]
For now you can override the case rule from above.

**Comment by bfred-it** [comment]
Indeed the CSS is the way to go. I'm leaving this open for a bit if anyone wants to:

1. remove the CSS
2. rename the feature to `move-marketplace-link-to-profile-dropdown`
3. implement `elementReady` like in `trending-menu-item` to detect the header link, remove it, and add the link to the dropdown.
