### ISSUE TITLE
Cannot compile project (TS2345 error)

### ISSUE THREAD

**Issue by niftylettuce** [sindresorhus/refined-github#2096]
```sh
npm install
```

```sh
npx webpack --development

ERROR in /Users/user/chromium-extensions/refined-github/source/features/show-names.tsx
[tsl] ERROR in /Users/user/chromium-extensions/refined-github/source/features/show-names.tsx(35,19)
      TS2345: Argument of type 'unknown' is not assignable to parameter of type 'string'.
```

**Comment by bfred-it** [comment]
Run `npm run watch`, not `npx`

It's unlikely that the types aren't correct because it works on Travis and other contributors

**Comment by niftylettuce** [comment]
This also happens when I run `npm run build` and `npm run watch`.

**Comment by bfred-it** [comment]
What’s your OS and node version?

**Comment by bfred-it** [comment]
On the reported line, `username` is of type `string` as inherited from `element.textContent`, I don’t know how that could say it’s unknown. 

Ensure you’re in the latest version of the project and dependencies and if the error is still there maybe you can open an issue on the typescript repo.

**Comment by bfred-it** [comment]
I'm seeing this when manually updating to TypeScript 3.5, but since we have a package-lock I don't know why it was failing for you.
