### ISSUE TITLE
lack of some elements in the reply section

### ISSUE THREAD

**Issue by ilyam8** [sindresorhus/refined-github#2104]
Following elemets are missing:
 - attach files ... field (bottom)
 - add header text
 - add bold text
 - add italic text

### w/ refined 
<details>
<summary>click</summary>

![Screenshot_20190530_234540](https://user-images.githubusercontent.com/22274335/58663678-aec28600-8335-11e9-9433-316cba25ed8b.png)

</details>

### w/o refined 
<details>
<summary>click</summary>

![Screenshot_20190530_234557](https://user-images.githubusercontent.com/22274335/58663705-c00b9280-8335-11e9-987b-5dcd9354b914.png)

</details>

**Comment by busches** [comment]
These are intentional changes, see bullet four under declutter in the read me. https://github.com/sindresorhus/refined-github/blob/master/readme.md#declutter
