### ISSUE TITLE
need to be logged in or no?

### ISSUE THREAD

**Issue by SolveAllProblemsRightNow** [sindresorhus/refined-github#2106]
on twitter one https://chrome.google.com/webstore/detail/refined-twitter/nlfgmdembofgodcemomfeimamihoknip

it says 'need to be logged into Twitter for this extension to work.'

this is clear

is that also the case for github https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

github info is unclear, please make clear

---

if you dont need to be logged in, where's list of added functions/things that help with a gif to show what is being added?

**Comment by bfred-it** [comment]
Yes, it only works if you're logged in, but we don't say this anywhere. Maybe we should update the stores' descriptions

**Comment by SolveAllProblemsRightNow** [comment]
thx that would be great and very very helpful, thank you for updating

**Comment by bfred-it** [comment]
Actually we do have a notice about this already:

https://github.com/sindresorhus/refined-github/blob/1a03fbb8da5936e4c1411aa573f10bcc146053f1/source/libs/features.tsx#L81

If anything doesn't work, it's best to open the console and check out why.

**Comment by SolveAllProblemsRightNow** [comment]
99% of ppl dont know what this 'console' thing is

and it'd be helpful if it's on the chrome extension page
