### ISSUE TITLE
Question: "new pull request" button

### ISSUE THREAD

**Issue by jsumners** [sindresorhus/refined-github#2107]
Which option do I need to disable to get the "new pull request" button back on the main repo page? I have to do PRs from the `master` branch into `staging`/`production` branches after merging feature branches into `master`. With this great extension installed this button is gone.

**Comment by busches** [comment]
I don't have that button with the extension disabled. It doesn't ring a bell as existing to me either. Can you attach a screenshot with the extension on and then disabled? Please disable other extensions as well, as they may be creating/hiding this button.

**Comment by jsumners** [comment]
![image](https://user-images.githubusercontent.com/321201/58720663-d00c8c00-83a0-11e9-9b0b-950f756f1788.png)

That's with the plugin disabled. With it enabled, the button "New pull request" simply wouldn't exist. Clicking the button takes you to the diff between branches tool so that you can choose which branches to compare and generate the PR from.

I have no other plugins installed that interact with GitHub.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/09d6a69f4dcc14546b0b7cabfb3e619f376774c1/source/content.css#L51-L54

**Comment by jsumners** [comment]
@yakov116 does that mean there isn't an option in the extension's settings I can toggle to disable that style?

**Comment by busches** [comment]
Thanks for the screenshot. I always create my PRs from the branch push popup or the PR page and never noticed the button there.

You're correct in that it's not directly tied to a feature to be disabled, but what yakov116 linked shows you the CSS you can override to enable it again. 

This is one of many UI cleanups we do and I can't see us adding a feature to disable it in the future, with it being easily overridden via CSS.

**Comment by jsumners** [comment]
Well this is an unfortunate outcome.

**Comment by jerone** [comment]
[**@jsumners**](https://github.com/jsumners) commented on [Jun 3, 2019, 1:50 PM GMT+2](https://github.com/sindresorhus/refined-github/issues/2107#issuecomment-498224992 "2019-06-03T11:50:33Z - Replied by Github Reply Comments"):
> Well this is an unfortunate outcome.

Why is this unfortunate? Go to GitHub Refined options, and paste the following in the "Custom CSS" textbox:
```css
 .file-navigation .new-pull-request-btn { 
 	display: inline-block;
}
```

**Comment by jsumners** [comment]
Hmm, I didn't know(overlooked?) the extension has a user CSS section. I assumed I'd have to setup some other user CSS extension to do the override and just removed Refined GitHub.
