### ISSUE TITLE
Create branch from issue

### ISSUE THREAD

**Issue by magick93** [sindresorhus/refined-github#2113]
Similar to what gitlab.com has, a user should be able to create a branch from an issue.

Example URL:
 
Please see https://github.com/isaacs/github/issues/1125

**Comment by bfred-it** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/pull/1927#issuecomment-482845843

**Comment by yakov116** [comment]
This will be added to GitHub see https://github.com/github/roadmap/issues/218

**Comment by fregante** [comment]
Added https://github.blog/changelog/2022-03-02-create-a-branch-for-an-issue/ 🎉
