### ISSUE TITLE
Show colors on hover

### ISSUE THREAD

**Issue by sumanthratna** [sindresorhus/refined-github#2119]
For hex colors and RBG codes, it would be nice to show a box above the cursor when the user hovers over the code.

**Comment by sindresorhus** [comment]
Would be useful, but not sure it's worth the implementation complexity. You should definitely request the feature at support@github.com.

Tip: You can see colors `#FF6347` in comments.

**Comment by jerone** [comment]
There is a great well-maintained userscript from Mottie which does exactly this, "[GitHub code colors](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-code-colors)".

**Comment by jerone** [comment]
Maybe we can use above mention userscript as a reference, because I think this would be great addition to this extension.
