### ISSUE TITLE
Also allow to disable features by listing them, instead of only checking boxes

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#2120]
I share my settings across diference users by coping and pasting the things I disabled as: `shorten-links add- move-marketplace-link-to-profile-dropdown set-default-repositories-type-to-sources infinite-scroll hide-useless-comments hide-watch-and-fork-count fit-textareas`

Now https://github.com/sindresorhus/refined-github/issues/2040 was implemented, there is no option to copy and paste them to share settings across computers. I have to check boxes into that long list.

**Comment by busches** [comment]
They're synced into chrome settings and should be shared that way, are you logged in to the same account on each computer?

**Comment by evandrocoan** [comment]
I use different google accounts, that is why it is not syncing.

**Comment by sindresorhus** [comment]
Sorry, the checkboxes are staying. Your use-case is not a common-case.
