### ISSUE TITLE
Include git clone command in "Clone or download" section

### ISSUE THREAD

**Issue by loilo** [sindresorhus/refined-github#2121]
I'm usually copying the URL of my repos just to do `git clone [paste] && cd [type-name-here]`. I'd find it very useful to have that command right at my fingertips in GitHub.

This is basically what was suggested in #1355, but instead of modifying the existing behavior, I would include the command as an additional option:

<img alt="Prototype of the desired functionality (screenshot)" src="https://user-images.githubusercontent.com/1922624/58941343-dbcec880-877b-11e9-9045-d8813736a473.png" width="380">

I think this change would be subtle/unobtrusive, but it would be interesting to get maintainer/community feedback on whether this a more widely requested feature or it's just me. 🙂

If this proposal gets any approval, I'd be happy to implement it.

**Comment by bfred-it** [comment]
I'm indifferent to this one. `Open in Desktop` works perfectly for me, [GitHub Desktop](https://desktop.github.com/) is a pretty neat GitHub companion. It also lets me check out PRs.

<img width="812" alt="Screenshot 2019-06-05 at 17 07 37" src="https://user-images.githubusercontent.com/1402241/58944436-721ee080-87b4-11e9-8584-b7b5f80cf69a.png">

**Comment by bfred-it** [comment]
I think you can just have a shortcut on your computer instead: https://unix.stackexchange.com/a/97922/32466

You can include a command like `pbpaste` so you don't even have to paste the URL every time.
