### ISSUE TITLE
"Add suggestion to batch" on "Suggested changes" doesn't work

### ISSUE THREAD

**Issue by webknjaz** [sindresorhus/refined-github#2122]
Clicking on that button just does nothing. _**Disabling the extension** fixes it_.

![suggested-changes-add-to-batch](https://user-images.githubusercontent.com/578543/58945283-dd9c8a00-8783-11e9-9366-fb06c542507e.png)

**Comment by bfred-it** [comment]
That's GitHub's bug, sadly can't fix it

**Comment by webknjaz** [comment]
Why? In only appears with the extension enabled.

**Comment by bfred-it** [comment]
I did notice the bug a while ago but I didn't think it could be RGH breaking it. I have to double-check.

**Comment by bfred-it** [comment]
I just tested in a Guest profile without any extension, it does not depend on Refined GitHub.

![sdfsfd](https://user-images.githubusercontent.com/1402241/58946078-b790dd00-87b7-11e9-80d8-c22b8bf7cebd.gif)

The error is from GitHub, I do have access to that branch [as this manual commit shows](https://github.com/sindresorhus/refined-github/pull/2008/commits/2e9a6669ce83c27806648cb22cc8a91f22f35f4f)

**Comment by webknjaz** [comment]
@bfred-it no, that's different. The bug on your animation is related to the fact that you are not the branch owner. 

My bug is about `Add suggested branch` button. **Not** ~`Commit suggestion`~

**Comment by webknjaz** [comment]
And what I reported is UI-only, while your bug is about backend validation on the GitHub side.

**Comment by webknjaz** [comment]
Btw in the closed EAP group, GH folks told me that you have to assign the PR to yourself in order for that to work (but I'm not sure whether they implemented that).

**Comment by webknjaz** [comment]
Demo on your own PR: https://github.com/sindresorhus/refined-github/pull/2111#pullrequestreview-245905635. It should help you understand what I'm reporting.

**Comment by bfred-it** [comment]
D'oh! Thanks for the report. Fixed

**Comment by webknjaz** [comment]
Thanks! Any chance to get it into Chrome webstore soon?

**Comment by bfred-it** [comment]
In about 9 hours

**Comment by webknjaz** [comment]
Cool, thanks. I haven't found anything mentioning the release process/automation in the readme. So it may be worth mentioning :)

**Comment by yakov116** [comment]
>In about 9 hours

@bfred-it 	There has not been a release since 6/3

**Comment by webknjaz** [comment]
Yeah, the previous tag looks existing in Git, but not in the Chrome Web Store

**Comment by yakov116** [comment]
@webknjaz 	has been an issue lately

**Comment by webknjaz** [comment]
Oh
> Details: Application error (6): hlepfoohegkhhmjieoechaddaejaokhf pending review so can't be edited
