### ISSUE TITLE
Hide status filter for PR list if there are no checks

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#2127]
From https://github.com/sindresorhus/refined-github/pull/2114#issuecomment-499763367.

Part of `filter-pr-by-build-status` feature, if the repository doesn't have any checks then there is no need to create and add the filter dropdown.

**Comment by bfred-it** [comment]
We could piggyback on `ci-link` to see if CI is enabled on the repo. `ci-link` could probably export a promise that `filter-pr-by-build-status` can listen to

**Comment by HardikModha** [comment]
Can we just export [`fetchStatus`](https://github.com/sindresorhus/refined-github/blob/master/source/features/ci-link.tsx#L8) function with a better name (Maybe `fetchCIStatus`) and use that? It's already wrapped with `onetime` so it won't be called again.
