### ISSUE TITLE
Cannot add Personal Access Token in Vivaldi Browser

### ISSUE THREAD

**Issue by Darthagnon** [sindresorhus/refined-github#2129]
I'm trying to use Refined GitHub with the Vivaldi browser (Chromium-based). Unfortunately, when I try to paste in my Personal Access Token to be able to use it, nothing happens, and I'm prompted with "Please match the format requested" (even though I'm copypasting my token exactly as generated by GitHub.

Guessing it's not compatible with the Vivaldi Browser?

**Comment by sindresorhus** [comment]
The supported browsers are mentioned in the readme. For anything else, you’re on your own.

**Comment by bfred-it** [comment]
Vivaldi has the same Chrome options interface, I just tried and it works. Make sure you're not copying any spaces. Click the "copy" button instead of selecting the key manually

**Comment by RodEsp** [comment]
I'm having the same issue on Chrome. I did click the "copy" button, there aren't any spaces in my paste or anything.

**Comment by RodEsp** [comment]
Ah, never mind. Just saw https://github.com/sindresorhus/refined-github/pull/4188.
