### ISSUE TITLE
Created repository - Different Style

### ISSUE THREAD

**Issue by delvedor** [sindresorhus/refined-github#213]
Hi, I've noticed that the `user created repository user/repo` has a different style than all the other news in the news feed.  
It is done on purpose or is it a mistake?

Here is an example:
![screen shot 2016-05-14 at 5 10 58 pm](https://cloud.githubusercontent.com/assets/4865608/15269174/9d9b556e-19f7-11e6-8827-69df438d22d6.png)

Thanks for the awesome extension! :)

**Comment by paulmolluzzo** [comment]
That's actually the default provided by GitHub. :)

**Comment by delvedor** [comment]
Yeah, I know :)

What I'm asking is:
It is done on purpose that **is not modified**?
Because with *refined-github* active in my browser all the other news are different from the original GitHub style.

Maybe something related to #188?

**Comment by sindresorhus** [comment]
We should definitely style this too.

**Comment by paulmolluzzo** [comment]
The style for starred repos should be an easy fix and would match. They're both `.simple` notifications

**Comment by delvedor** [comment]
It's enough update `content.css` ?

**Comment by paulmolluzzo** [comment]
> It's enough update content.css ?

Yes, put it in that file.

**Comment by delvedor** [comment]
I've opened this pull request, let me know :)
#215

**Comment by AshikNesin** [comment]
@hkdobrev I'll pick up and fix this issue :)

**Comment by hkdobrev** [comment]
@AshikNesin Thanks! You could cherry-pick some commits from #215 if you think it will be useful to you.

**Comment by busches** [comment]
@sindresorhus @bfred-it looks like this can be closed thanks to #436
