### ISSUE TITLE
Increase contrast of favicon in dark mode

### ISSUE THREAD

**Issue by gavinhenderson** [sindresorhus/refined-github#2130]
The favicon on GH is almost invisible if you have a browser in dark-mode. Now that you can detect the theme of the browser with `prefers-color-scheme` we could make the favicon more visible on dark theme browsers.

![favicon](https://i.imgur.com/St5w3pm.png)

Initially suggested on twitter: https://twitter.com/PhilippSpiess/status/1136985270874714117?s=20

**Comment by bfred-it** [comment]
The problem is that the favicon is dynamic in PRs (e.g. see the favicon in https://github.com/sindresorhus/refined-github/pull/2073) and I think I've also seen a blue dot on the favicon in some cases before.

**Comment by gavinhenderson** [comment]
Yeah the dynamic favicon would definitely need to be preserved, a brief look into the source shows that it would be possible to detect what favicon is currently being served so we wouldn't need to reimplement that feature.

Yeah it would definitely miss some people, but I think it would catch a large amount of users. The only issue is its a CSS query but we want to use the result in JS, from what I can see there isn't an *elegant* way to do that, but it is possible.

If we were okay with it only working on firefox the have their own API to get the theme in JS.

**Comment by notlmn** [comment]
> The only issue is its a CSS query but we want to use the result in JS

There's `window.matchMedia()` you can use in JS to run CSS media queries.

But if you are talking about `prefers-color-scheme` CSS media query, then I'd like to mention beforehand that it is highly unreliable on browsers that don't support the query. All the queries report back `false` if the browser can't handle the query.

![image](https://user-images.githubusercontent.com/37769974/59112761-49881980-8961-11e9-8e6c-bb622e9555f0.png)

**Comment by bfred-it** [comment]
Using `prefers-color-scheme: dark` makes sense. If it's false, leave untouched; if it's true, it's supported by the browser and that's what we want.

**Comment by gavinhenderson** [comment]
Perfect, didn't know that was possible!

What do we want the favicon to be if the user is in dark mode?

**Comment by notlmn** [comment]
> What do we want the favicon to be if the user is in dark mode?

Something like https://github.com/sindresorhus/notifier-for-github/blob/master/source/icon-notif.png should work for both light and dark modes (view the png on dark background to see how it looks).

**Comment by bfred-it** [comment]
That's a good one too, so it would work for everyone

**Comment by gavinhenderson** [comment]
Perfect, ill work on this feature.

Is there an easy way to host images from an extension?

**Comment by bfred-it** [comment]
You can use `web_accessible_resources`

**Comment by dotconnor** [comment]
You can also use [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to listen to the changes made on `.js-site-favicon`, and update the favicon again to a dark theme friendly one.

**Comment by gavinhenderson** [comment]
@dotconnor thanks 👍🏻

I'm busy for a few days but will try and get to this in the next week or so

**Comment by fregante** [comment]
PR welcome for `favicon-contrast`

**Comment by fregante** [comment]
Thanks, GitHub!

<img width="186" alt="native dark mode icon" src="https://user-images.githubusercontent.com/1402241/78069835-0937d300-739b-11ea-8257-1c18e6fc0545.png">

**Comment by yakov116** [comment]
> Thanks, GitHub!
> 
> <img alt="native dark mode icon" width="186" src="https://user-images.githubusercontent.com/1402241/78069835-0937d300-739b-11ea-8257-1c18e6fc0545.png">

Wow i was wondering why my github tabs started sticking out
