### ISSUE TITLE
`comments-time-machine-links` should only appear on hover

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2131]
Follows https://github.com/sindresorhus/refined-github/pull/1863

I find the icon added next to each link ugly, especially like https://github.com/sindresorhus/refined-github/blob/master/readme.md in blocks of text where it's rather distracting.

Should we show this only when hovering the link? With `position: absolute` so it doesn't change the layout. Better yet, perhaps we should just show a tooltip that invites the user to alt-click the link.

**Comment by sindresorhus** [comment]
> Better yet, perhaps we should just show a tooltip that invites the user to alt-click the link.

👍

**Comment by fregante** [comment]
Alternative I just found, just FYI https://github.com/josephfrazier/octopermalinker

**Comment by fregante** [comment]
Closing in favor of https://github.com/sindresorhus/refined-github/issues/2618
