### ISSUE TITLE
Add date to PR requested changes comment

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#2132]
# Feature request
When someone requests changes on an PR with a comment, it is added without date. The date of the comment is above the box. But I'm so used to the date being in the comment box header, that I always wonder when the comment was made (maybe it's just me). 

What if we add the date (ago) there too...

# Example
![image](https://user-images.githubusercontent.com/55841/59122407-fa3eea80-895a-11e9-9be9-dd910501bf2c.png)

https://github.com/sindresorhus/refined-github/pull/2115#pullrequestreview-247017754

**Comment by bfred-it** [comment]
But… it’s still there, 50pixels away?

**Comment by jerone** [comment]
I know, but I'm so used to the date being present in the comment box header. 

The only reference that the whole comment box is linked to above (50px) event, is a very small arrow:
![image](https://user-images.githubusercontent.com/55841/59124473-fe213b80-895f-11e9-8421-a8845f91dd88.png)

Like I said, maybe it's just me 😅

**Comment by bfred-it** [comment]
I do find it slightly annoying but it's not adding more code over, IMHO
