### ISSUE TITLE
Compact Discussions

### ISSUE THREAD

**Issue by jamiebuilds** [sindresorhus/refined-github#2143]
## Problem

Right now on GitHub there is tons of visual noise around even a single inline comment on a diff:

<img width="1018" alt="Screen Shot 2019-06-09 at 12 20 55 PM" src="https://user-images.githubusercontent.com/952783/59163146-be6a6900-8ab1-11e9-8ff4-b982f0d06490.png">

## Proposed Changes

Like why do we need double borders:

<img width="1006" alt="Screen Shot 2019-06-09 at 12 21 12 PM" src="https://user-images.githubusercontent.com/952783/59163157-eb1e8080-8ab1-11e9-8779-95b886265696.png">

Why does "Resolve Conversation" need its own line:

<img width="1003" alt="Screen Shot 2019-06-09 at 12 21 37 PM" src="https://user-images.githubusercontent.com/952783/59163162-025d6e00-8ab2-11e9-96ea-a20f09ebea00.png">

If there's only a single comment, why even have the reply line? Just turn it into a button (reactions are already there...):

<img width="1005" alt="Screen Shot 2019-06-09 at 12 22 55 PM" src="https://user-images.githubusercontent.com/952783/59163176-1c974c00-8ab2-11e9-97f3-497f0cf2c59c.png">

Resolve Conversations could also be a button or it could get the dropdown treatment:

<img width="1006" alt="Screen Shot 2019-06-09 at 12 23 53 PM" src="https://user-images.githubusercontent.com/952783/59163187-5d8f6080-8ab2-11e9-99f3-61ccedc1175a.png">

This change would take the above comment from taking up 240px of vertical space to 120px.

On a pull request with 40 comments, this makes a huge difference.

**Comment by bfred-it** [comment]
I just fear it will be short lived because they’ve been messing with classes and design a lot lately. 

However this would be nice to have, and it’s welcome.

**Comment by sindresorhus** [comment]
> But respond and resolve should stay there because they’re common actions.

👍

**Comment by jerone** [comment]
> Like why do we need double borders

"Double borders" are there because people can start 2 or more conversations on a single line of code. Each conversation can be closed separately.
![image](https://user-images.githubusercontent.com/55841/59217063-6c166e80-8bbd-11e9-86bb-ca4c7098ee87.png)

**Comment by jamiebuilds** [comment]
There are better ways of achieving that. They don't do a particularly good job of it now anyways

**Comment by bfred-it** [comment]
A fix for that would be to add margins just between them:

`.discussion + .discussion { margin-top: 2em }

**Comment by jamiebuilds** [comment]
So what if it looked something like this:

![Screen Shot 2019-06-14 at 10 39 22 AM](https://user-images.githubusercontent.com/952783/59527560-c569f080-8e90-11e9-8e0c-def39ff3bdb1.png)

**Comment by fregante** [comment]
PR welcome for `compact-discussions.css`

**Comment by fregante** [comment]
The reason why they do this is because PR diff views can span the whole screen. If we add this feature, the "contextual" dropdown menu and the Resolve button can be very far from the content. Not a good idea
