### ISSUE TITLE
Filter-as-you-type searchbox in Options features list

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#2147]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2147)

It's great that you have recently added the ability to enable/disable features with a click in the extension's Options.

The features list of checkboxes however is a quite large one. 
How about adding a **filter-as-you-type searchbox**, to only display/filter the matching ones as you type? (hoping that it's possible of course)

PS. Using Refined Github 19.6.9 in Chrome 75/Firefox 67 in win10.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/55841?v=4' alt='jerone' width=24 height=24> jerone](https://issuehunt.io/u/jerone) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by jerone** [comment]
Yes please. I tried the build-in search box above the extension settings, but it's only for finding new Firefox extensions. I tried inspecting the XUL with the Developer Tools, but it won't let me access the `<browser>` element. So, supplying it's own searchbox would be great.

**Comment by sindresorhus** [comment]
Command+F works well for me in Chrome.

**Comment by darkred** [comment]
> Command+F works well for me in Chrome.

Not for me.
Furthermore, using Ccommand + F is not very convenient because in most cases the words that make up the feature titles are also included in the relevant feature descriptions, and so you get two (or more) matches for the same criteria.

**Comment by jerone** [comment]
[**@sindresorhus**](https://github.com/sindresorhus) commented on [Jun 11, 2019, 6:40 AM GMT+2](https://github.com/sindresorhus/refined-github/issues/2147#issuecomment-500683907 "2019-06-11T04:40:02Z - Replied by Github Reply Comments"):
> Command+F works well for me in Chrome.

Not in Firefox! It gives focus to the "find more extensions"-searchbox.
