### ISSUE TITLE
When completing a username, a tab is erroneously appended

### ISSUE THREAD

**Issue by isiahmeadows** [sindresorhus/refined-github#2148]
With Refined GitHub:

![refined-gh-enabled](https://user-images.githubusercontent.com/4483844/59270045-8a608680-8c1e-11e9-8f82-624e4c1dec36.gif)

Without Refined GitHub:

![refined-gh-disabled](https://user-images.githubusercontent.com/4483844/59270064-92b8c180-8c1e-11e9-9aed-8bcae24ca611.gif)

This may seem similar to #1412, but the name completes as normal where that one apparently didn't. (BTW, I experience the same issue with issue completion, too.)

**Comment by yakov116** [comment]
When submitting (or Commenting) the issue it does not appear
