### ISSUE TITLE
Sorting repositories (sidebar)

### ISSUE THREAD

**Issue by gusbemacbe** [sindresorhus/refined-github#2149]
In the sidebar or at the left, I would like sort alphabetically the repositories. 

![image](https://user-images.githubusercontent.com/2257024/59282682-afb1bc80-8c3f-11e9-9940-ca1c2d9011ef.png)

Since this extension does not offer a option of customising JavaScript, it is totally impossible to sort, using only CSS.

**Comment by notlmn** [comment]
Why do you want it sorted, when you can always search for a repo easily using the search bar above the list in real-time!?

**Comment by jerone** [comment]
I always thought it was sorted on which project you used/contributed the most.

**Comment by zcernigoj** [comment]
> Why do you want it sorted, when you can always search for a repo easily using the search bar above the list in real-time!?

Doesn't help when you have repositories that start with the same n characters. Then it takes you a lot of time to either find it with the order changing every time or typing out 10 characters to finally list less than 5 repositories between which you can quickly see the one that you need.

Even better would be a user-defined order.

**Comment by fregante** [comment]
If you want user-defined order, just bookmark them in your browser. Why waste time sorting them when you click a button and your browser remembers them?
