### ISSUE TITLE
Ability to expand all collapsed code in PR diffs

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/refined-github#2151]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2460%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2151)

When reviewing PRs, sometimes it's useful to view the entire file with the diffs in context. To do this, one needs to click the expand diff button multiple times until the entire file is exposed.

I'd like to be able to alt-click one of the expand markers in collapsed code and have all code blocks expand at once (perhaps limited to the current file). A similar feature was [recently added to VSCode](https://code.visualstudio.com/updates/v1_35#_compare-merge-conflicts-with-complete-context), btw, so there's precedence for this.

There is already a [feature to view the file](https://github.com/sindresorhus/refined-github/blob/ff62ae6c36e1b19db4feddaefa5b57ed6a7e8435/source/features/raw-file-link.tsx#L13) at the commit associated to the diff being viewed, but then the full code is shown unmarked, without the diff indicating what changed.

Also, please note that this is about expanding/collapsing code within a diff, rather than folding entire files, which was a previous feature and was removed after it was implemented directly by GitHub (see #1486). What I'm talking about is this:

![screenshot](https://user-images.githubusercontent.com/6978877/34470024-eee4f43e-ef20-11e7-9036-65094bd58960.PNG)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $60.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)
- [<img src='https://avatars2.githubusercontent.com/u/1585276?v=4' alt='adriantp' width=24 height=24> adriantp](https://issuehunt.io/u/adriantp) ($10.00)
### Submitted pull Requests
- [#2434 Add `expand-all-collapsed-code` feature (#2151)](https://issuehunt.io/r/sindresorhus/refined-github/pull/2434)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by bfred-it** [comment]
Easiest solution: click all "expand" buttons until there are no more left, but this will cause multiple sequential loads and will look messy.

Ideal solution: load file from its "View file" link and then merge it with the current dom. This is probably a bit hard, especially on the split diff view.

Other solutions welcome

**Comment by qti3e** [comment]
You can also clone the DOM node and replace it with the original one, then click on `expand` (from the original DOM tree) until there is no more left, and then put it back and remove the fake DOM.

**Comment by maricn** [comment]
+1

I believe this is called unfold rather than expand in GH terms, because expand means expand/collapse of a file. 

_Just wanted to add a comment to make the issue searchable with `unfold` tag. Thank you for the future implementation <3 _

**Comment by bfred-it** [comment]
> I believe this is called **unfold** rather than **expand** in GH terms

It doesn't look like it:

<img width="341" alt="" src="https://user-images.githubusercontent.com/1402241/61703540-f67cf100-ad6b-11e9-8698-2294e1e6043d.png">

**Comment by maricn** [comment]
True, anyways, in their original blog post it was called unfold.. https://github.blog/2013-12-02-expanding-context-in-diffs/

Anyways, looking forward to seeing this feature :)

**Comment by AdrianTP** [comment]
Thanks, @tiramisu77 and @fregante! I just updated my extension to 19.9.19 and gave it a little test. It is indeed a little slow, as you noted, but considering that all you have to work with is UI elements, it works perfectly. Just alt-click one of the "expand" gutter buttons and all of the folded lines unfurl within a couple of seconds (depending on the size of the file and how many folded sections exist, obviously). Wonderful!

**Comment by asbjornsabo** [comment]
This seems to be just the thing I have been looking for.  But how does one use it?
(I tried to Alt-click on the "expand" buttons at the side of the file, but it only expands as it would if I had clicked the button normally - no "expand all" to be seen.
Can someone please explain?

**Comment by fregante** [comment]
I just tried it and it still works. Here's a demo

> ![](https://user-images.githubusercontent.com/44227187/64923605-d0138900-d7e3-11e9-9dc2-461aba81c1cb.gif)

**Comment by asbjornsabo** [comment]
And what you do is "Alt-Click" on this symbol?  (That is, clicking when holding the Alt button?)

Does not work for me.  Tested with Firefox and Chromium under Linux, and with Firefox (I believe) under Windows 10.
Would really like to have this working.

**Comment by antoniorosario** [comment]
Not working for me either on macOS (trying option + click).

Really would like to use this tool!

**Comment by kgemmert-r7** [comment]
me too! this is a big thing for me that is missing when viewing PR's. I don't just want to see the lines change, but I want the full context at times. I cannot get this to work on mac OS :(

**Comment by fregante** [comment]
I'm on Firefox/macOS and can always make it work.

1. Visit https://github.com/sindresorhus/refined-github/pull/2434/files
2. Hold `alt` and click here: 
<img width="520" alt="Screen Shot 2020-07-10 at 00 39 25" src="https://user-images.githubusercontent.com/1402241/87097576-d036b680-c245-11ea-9215-c10f38e917df.png">

Click exclusively on the blue area in that screenshot, _not_ on the whole line, even if it highlights.

**Comment by asbjornsabo** [comment]
@fregante 
Lucky you ;-)

I hold alt, and click in that blue box with the up-arrow and dots, and I get 20 more lines unfolding.  Not all lines.
Firefox 68.10.0esr (64bit) on Windows 10.

**Comment by fregante** [comment]
Firefox 68 is not supported. Firefox 78 is the minimum version https://github.com/sindresorhus/refined-github/blob/f2a96713692c2227035b86a63714704d82b6f6bd/source/manifest.json#L8-L12

**Comment by fregante** [comment]
Linux users that can't make it work can try remapping the alt key: https://github.com/sindresorhus/refined-github/issues/3436#issuecomment-670446085
