### ISSUE TITLE
`Shift+O` shouldn't work when writing inside an editable element

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/refined-github#2152]
GitHub ~recently added a list of similar issues when opening a new issue:

---

<img width="684" alt="Screen Shot 2019-06-13 at 01 58 35" src="https://user-images.githubusercontent.com/1812093/59394117-d7f40500-8d7e-11e9-8b41-bc32af47ee7f.png">

---

The problem is that whenever I type an uppercased O, i.e. `Shift+O` is pressed, the first of those listed issues is opened in a new tab.

`Shift+O` should be ignored when an editable element has the focus.

**Comment by bfred-it** [comment]
The listener needs to detect and exclude events in fields, e.g. via `if event.currentTarget.matches('input, textarea') return`

**Comment by fabiospampinato** [comment]
> The listener needs to detect and exclude events in fields, e.g. via if event.target.matches('input, textarea') return or target instanceof HTMLInputTextarea

A more reliable implementation of this is available here: https://github.com/kenwheeler/cash/blob/8694089659167f84a106467881991e52b2fd68f1/src/core/matches.ts#L4-L10

**Comment by fabiospampinato** [comment]
Also the selector should porbably be `'input, textarea, [contenteditable]'

**Comment by bfred-it** [comment]
We don’t need any of that. Only the latest chrome and Firefox are supported so no polyfills necessary
