### ISSUE TITLE
Repo homepage inserted into top of issues page?

### ISSUE THREAD

**Issue by joshmanders** [sindresorhus/refined-github#216]
Not exactly sure how to explain this, but I ran into it on a private repo that has zero code but I use the issues of that repo. I can't reproduce it on any other repo but this one.

I disable refined github and it goes away. Re-enable and it comes back.

![](http://i.imgur.com/3CYmYLC.png)

**Comment by hkdobrev** [comment]
@joshmanders Does that happen on full page reload or only when you go back and forwards?

**Comment by hkdobrev** [comment]
@joshmanders could you try and set up public test repo and see if you could reproduce?

**Comment by joshmanders** [comment]
@hkdobrev This happens on full page reload. I can't get it to happen on any other repo, I can make that repo public and test again, If it doesn't happen unless it's private, I can add you to it.

**Comment by joshmanders** [comment]
It's public and I get it still. https://github.com/joshmanders/ideas/issues

**Comment by jacobbearden** [comment]
I've identified [this function](https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L220-L231) as the cause. Gonna take a crack at fixing it.

**Comment by jacobbearden** [comment]
So when the function highlighted above creates `uri`, the resulting link appear as follows:
[Empty repository](https://github.com/jacobbearden/empty-repo/show_partial?partial=tree/recently_touched_branches_list), [repository with files](https://github.com/sindresorhus/refined-github/show_partial?partial=tree/recently_touched_branches_list)
Causing `include-fragment` to load the entire repository main page.

Should the function just `return` if the repository is empty? If so, what's the best way to check if it's empty? Ajax call?

**Comment by jacobbearden** [comment]
@sindresorhus @paulmolluzzo @hkdobrev

**Comment by paulmolluzzo** [comment]
> What's the best way to check if a repository is empty?

Check that there are files in the file navigation? Or that the number of commits is `>= 1`? If you make a fake empty repo and visit in an incognito window there might be even more obvious stuff.

**Comment by joshmanders** [comment]
Any momentum?

**Comment by DrewML** [comment]
@joshmanders submitted a PR
