### ISSUE TITLE
Layout Jumping During Fetching of Latest Commit

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#2160]
During fetching of latest commit on any `tree` page, the layout of the files list jumps vertically, causing potential for mis-clicking during this loading period.

Look here at the height of the blue commit bar during fetching and afterwards (and the offset in the file list that this causes):

![Kapture 2019-06-18 at 13 46 12](https://user-images.githubusercontent.com/1935696/59679694-d20f8100-91cf-11e9-8398-8c249447abe3.gif)

This appears to be potentially caused by the Toggle Files Section `chevron-down` (at least visually):

<img width="62" alt="Screen Shot 2019-06-18 at 13 47 25" src="https://user-images.githubusercontent.com/1935696/59679790-10a53b80-91d0-11e9-829c-5b4a37a5eb19.png">

This is somewhat confirmed by the fact that disabling the `toggle-files-button` causes this problem to go away:

<img width="397" alt="Screen Shot 2019-06-18 at 13 56 43" src="https://user-images.githubusercontent.com/1935696/59680146-f0c24780-91d0-11e9-8dc3-5fb8717aeb26.png">

**Comment by jerone** [comment]
What browser are you experiencing this? Because I can't reproduce it on Firefox.

**Comment by karlhorky** [comment]
@jerone macOS Chrome `75.0.3770.90` (Official Build) (64-bit)

Note: it doesn't always happen - just when the "Fetching latest commit..." message appears.

**Comment by karlhorky** [comment]
Thanks for the fix @bfred-it !
