### ISSUE TITLE
Linkify users in edit history popup

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#2161]
### Description
Users in the edit history popup don't have a link to their profiles. Those users didn't necessary have commented on the thread, they can just edit someone's comment (with the correct rights). This is also the case for bots.

### Screenshot
![image](https://user-images.githubusercontent.com/55841/59688155-60d6ca80-91dd-11e9-92c8-c32b3c941448.png)

### Examples
* `https://github.com/Mottie/GitHub-userscripts/issues/88#issuecomment-502933879` (with bot)
* `https://github.com/sindresorhus/refined-github/pull/1766#issue-251741293`

### STR
1. Open any of the above URLs.
2. Click on the "edited by" dropdown.
3. Click on any history item.
4. Popup will open. See that the username is not linkified.

_P.s. The users full name and hovercard are also missing, but I don't think that's necessarily useful there._

**Comment by sindresorhus** [comment]
This seems more like an oversight by GitHub. Can you report it to support@github.com first?
