### ISSUE TITLE
Avoid adding real names when the user is using a real name

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2165]
This isn't useful:

<img width="381" src="https://user-images.githubusercontent.com/1402241/59960378-3f861f00-94fa-11e9-81ac-3f51135ef877.png">

I'd rather see this:

<img width="272" alt="" src="https://user-images.githubusercontent.com/1402241/59960403-76f4cb80-94fa-11e9-9a69-0613b978b5c7.png">

--- 

Feature: `show-names`

```
If name matches username
	replace username with name (to keep capitalization)
```

- Either we drop the space altogether (so in this case there won't be any changes for these users, but there would be for `sindresorhus`, which would become `SindreSorhus`), or 
- we replace it with `<span style="margin-left:0.2em"/>` so it won't break copy-pasting.

Example URL:
https://github.com/microsoft/TypeScript/issues/30442#ref-pullrequest-433925264

**Comment by notlmn** [comment]
Wouldn't this break #2146, in a way 🤷‍♂️.

**Comment by sindresorhus** [comment]
Sounds good, but there should be a space visually, I don't want to see `SindreSorhus`.

**Comment by bfred-it** [comment]
> Wouldn't this break #2146

As far as `textContent` is concerned, only the case will change. `sindresorhus -> SindreSorhus` so to fix that feature we just need a `.toLowercase()` in a couple of places.

To make it even safer if could use `<u>s</u>indre<s/><u>s</u>orhus` where `s` and `u` are `margin-left: 0.2em` and `text-transform: uppercase` respectively.

**Comment by bfred-it** [comment]
One more: Punctuation.

<img width="424" alt="punctuation" src="https://user-images.githubusercontent.com/1402241/60043673-2f855f80-96f3-11e9-8160-4d2aa0e46f50.png">


https://github.com/bfred-it/webext-options-sync/issues/13#issuecomment-497941181
