### ISSUE TITLE
Settings don't save when updating from extension menu

### ISSUE THREAD

**Issue by ahatzz11** [sindresorhus/refined-github#2170]
Whenever I change a setting nothing happens. There is no save button so the only option that I have is to hit the 'x' at the top. I can't even add a token to this page.

Here is the url it's happening: chrome://extensions/?id=hlepfoohegkhhmjieoechaddaejaokhf

Here is a gif of this: http://www.giphy.com/gifs/f6VZUcc5iS6XTwt0bV

I want to disable the edit-files-faster option, because who wants a repo page to look this huge? This last update with the fast file editing should have the edit button next to the existing files icon to maintain the vertical space

![image](https://user-images.githubusercontent.com/6256032/60037576-86e5ea00-9677-11e9-815e-7895221357db.png)

Chrome Version 76.0.3809.36 (Official Build) beta (64-bit)

**Comment by bfred-it** [comment]
This has been fixed in a5dd228721f2659773c4d9a9f0a0e5c8d7398b9b and will be published to the stores within 3 hours.

By the way `edit-files-faster` is not supposed to look like that, you might have some conflicting extension.

![](https://user-images.githubusercontent.com/1402241/60038476-08c12c00-96e7-11e9-8af2-99fe6d5e1e6f.gif)

**Comment by ahatzz11** [comment]
@bfred-it that looks awesome! but the attach screenshot is from an incognito window with only refined github enabled

**Comment by bfred-it** [comment]
I'll leave this open just in case someone else encounters it.

> @bfred-it that looks awesome! but the attached screenshot is from an incognito window with only refined github enabled

Weird, can you open an issue about it? Are you on Chrome? Any errors in the console? Is it GitHub Enterprise?

If that happens, some CSS is not being applied.

**Comment by ahatzz11** [comment]
@bfred-it I'll make a new issue for it so we can track it separately from the settings persistence issue

**Comment by gibfahn** [comment]
I'm also encountering the `edit-files-faster` UI issue in Github Enterprise, but not in github.com .

**Comment by tknickman** [comment]
Seeing the UI issue as well. GHE v2.16.10

![demo](https://dl.dropboxusercontent.com/s/76bc5l4bq7van03/Screenshot%202019-06-24%2016.12.02.png?dl=0)

**Comment by ahatzz11** [comment]
For the record, this issue is also happening to me on GHE.
