### ISSUE TITLE
Auto-focus on PR form title broken in Firefox

### ISSUE THREAD

**Issue by lode** [sindresorhus/refined-github#2172]
When creating a new PR the form used to auto focus on the title so you can start typing directly. Since a few days this is broken, specifically in Firefox, in Chrome it is still working.

GitHub native also had the same bug, but they fixed this today.

When I now create a PR from the 'New pull request' button:

![afbeelding](https://user-images.githubusercontent.com/511245/60043570-af460680-96c0-11e9-908b-aeb0087397f7.png)

it works correctly. Also when disabling Refined GitHub and use the native shortcut 'Compare & pull request' for newly pushed branches:

![afbeelding](https://user-images.githubusercontent.com/511245/60043646-d7ce0080-96c0-11e9-874e-6052c74e021c.png)

it works correctly.

Only when using the Refined GitHub version of that:

![afbeelding](https://user-images.githubusercontent.com/511245/60043699-f633fc00-96c0-11e9-9a0e-900f64c817a2.png)

the resulting form for a PR doesn't auto focus on the title field in Firefox. In Chrome I do see this working correctly from all three places.

I would love to get this back, it is such a great time -and rsi- saver!

**Comment by fregante** [comment]
I can reproduce without Refined GitHub. It's weird because the field has an `autofocus` attribute but sometimes it doesn't work 🤷‍♂️
