### ISSUE TITLE
Reaction icons are defaulting to a huge size when there is no real profile picture.

### ISSUE THREAD

**Issue by ahatzz11** [sindresorhus/refined-github#2173]
The profile pictures next to reactions are great, but one of the most recent updates has made this feature really annoying. 

Note: this is on GHE 2.16.9

example:
![image](https://user-images.githubusercontent.com/6256032/60051271-3e8af400-9698-11e9-8000-6f01365de190.png)

I know there have been some other css related issues today https://github.com/sindresorhus/refined-github/issues/2170#issuecomment-505163026 https://github.com/sindresorhus/refined-github/issues/2171#issuecomment-505158159 so I don't know if this is related or not.

**Comment by bfred-it** [comment]
Same as #2174
