### ISSUE TITLE
Question: how to disable limiting the merge commit message length

### ISSUE THREAD

**Issue by pkoch** [sindresorhus/refined-github#2178]
Limiting the merge commit message really cramps my style. It forces me to have custom messages (i.e., automation can't rely on the standard anymore) and it just adds friction to merging commits and adds no real value to me.

Is there a way to disable adding this check?

**Comment by sindresorhus** [comment]
You can disable this and most of the features in the extension options.

**Comment by pkoch** [comment]
Can you point out how? I've tried scanning the list visually a few times and failed.

**Comment by bfred-it** [comment]
The limit is on GitHub’s servers. We actually added a feature to make the limit more visible client-side, but the limit was already there 

https://github.com/sindresorhus/refined-github/pull/2115

**Comment by pkoch** [comment]
> The limit is on GitHub’s servers
For reference, this is not what I observe. If I turn off refined-github, I can merge the PRs just fine and things do show up in the repo just fine.

> #2115
Thank you for referring the issue! This was super helpful! I now know what I need to disable. :two_hearts:

Thanks for helping!

**Comment by notlmn** [comment]
> For reference, this is not what I observe. If I turn off refined-github, I can merge the PRs just fine and things do show up in the repo just fine.

GitHub doesn't exactly stop you from merging PRs but any commit title with length above 72 characters is automatically broken down to "commit title" and "commit description" components in GitHub's UI (eg: https://github.com/sindresorhus/refined-github/commit/ed0ace7f1f1fa9b49dbc5733a9606e42031b3188).

![image](https://user-images.githubusercontent.com/37769974/60186175-e21b0680-9848-11e9-86f4-9ade1d6c3271.png)

If GH does this anyway, we figured it'd be best practice to limit commit title length while merging PRs itself.

(And when using RGH to merge PRs the PR number is appended to the end of commit title. Ff the PR title is too long the PR number at the end of merged commits, like example above, is separated from actual title)

**Comment by pkoch** [comment]
The way that you're presenting the problem tackles a side of it that's really not relevant to me, which is how GH has decided to present info in their interface. If GH wants to do funny UI things with it, so be it, but I care much more about what actually goes into the commit message on git.

I'm not trying to advocate to change the default behaviour, just exuding how I see the world.

(Yeah, I have that turned off too, since that gets in my way for my workflow and tooling.)

**Comment by notlmn** [comment]
Yup, the ability to disable features is just there so that you can tailor it to your workflow.

We implemented this to be a best practice, to write everything you want to say in commit description and only a short single descriptive line in commit title (that is less than 72 characters).

TBH, GH doesn't do funny things with it's UI (maybe in some cases but not when it comes to the **Git** part). GH has professionals working on interfacing GitHub's UI with Git, and they have a lot more experience with Git than you or me. We respect their decision on the 72 char text break, as it doesn't actually make sense to write anything more in the title.

We try to follow GHs style as much as possible.

**Comment by pkoch** [comment]
> We implemented this to be a best practice
One man's best practice is another man's demise.

> they have a lot more experience with Git than you or me
I find it surprising that you're aware of my experience with git.

> TBH, GH doesn't do funny things with it's UI
I'm sensing that my use of the word "funny" was triggering to you. I was trying to be light-hearted, perhaps I ended up being read as facetious. I'm sorry if I've upset you, that was not my intention.

> We respect their decision on the 72 char text break, as it doesn't actually make sense to write anything more in the title.
In your scenarios, perhaps. I have my reasons to want that in merge commits.

> We try to follow GHs style as much as possible.
Makes perfect sense, and it'll probably serve most people very well.

I'm sorry if I've made your day worse when all that your extension has done is help me. I'd like to underline how grateful I am to be able to use it, and I'm very open to receive feedback on how to make your life better when investing in it for all of us.

**Comment by bfred-it** [comment]
Indeed, there's no actual limit, GH only clips the length on the website


Committed on the website, shows clipped:
https://github.com/sindresorhus/refined-github/commit/3a55f541b11e78eff2484eb409f704e0eae9b32e

But in reality it's not:

![](https://user-images.githubusercontent.com/1402241/60196237-3c2ec280-986f-11e9-8d55-052498121b92.png)

**Comment by pkoch** [comment]
Indeed, that's what I observe too! It was surprising to me that RGH limited the input field so harshly (not just a warning, but outright preventing submission), but I see how it can make sense given the philosophy that's being followed.

Thanks for taking the time to confirm, @bfred-it!
