### ISSUE TITLE
Notification `Customize` is replaced with `Details `

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2179]
Not sure if this is on purpose.

With RGH 

![image](https://user-images.githubusercontent.com/16872793/60186322-8d03d400-97f9-11e9-87e6-fa29692a24b8.png)

Without

![image](https://user-images.githubusercontent.com/16872793/60186363-9f7e0d80-97f9-11e9-986a-f820e559cd2d.png)

**Comment by bfred-it** [comment]
This is a bug of `clean-sidebar`, it's supposed to hide the "Notifications" title but now the header has been changed so it breaks the style.

**Comment by yakov116** [comment]
@bfred-it  	But i want to see the customize

**Comment by bfred-it** [comment]
?

Of course.

We can drop the line of code that hides the Notifications header. PR welcome
