### ISSUE TITLE
Issue notifications "Customize" box overlaps repo header buttons

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2189]
1. Visit a repo you can edit
2. Click on Customize:

	<img width="235" alt="Screenshot 2019-06-28 at 17 43 37" src="https://user-images.githubusercontent.com/1402241/60333696-46b29e80-99cc-11e9-9728-e01573cb9bbc.png">

3. See bug:

	<img width="1047" alt="Screenshot 2019-06-28 at 17 42 45" src="https://user-images.githubusercontent.com/1402241/60333677-3d293680-99cc-11e9-9d27-51a78157f3b6.png">

**Comment by notlmn** [comment]
This doesn't look like RGHs fault.

![image](https://user-images.githubusercontent.com/37769974/60379584-31348780-9a53-11e9-8cbd-67d6756dffb0.png)

Changing that `z-index` value from `31` to `26` solves the issue, but these styles are from GitHub's stylesheet.

**Comment by bfred-it** [comment]
Disabling RGH seems to fix it though, this might be due to our fixed sidebar feature

**Comment by jerone** [comment]
More weird things happen when you scroll the page with the popup box open.

**Comment by fregante** [comment]
Fixed by https://github.com/sindresorhus/refined-github/commit/f8c2fab4cfd8f85f19552a897f1a6df49ea441d9
