### ISSUE TITLE
Add link to http://forked.yannick.io/ next to the fork button to enable finding most recent fork

### ISSUE THREAD

**Issue by koppor** [sindresorhus/refined-github#2194]
When searching GitHub for interesting projects, some of them are abandoned. Sometimes, there are forks existing. GitHub presents the forks just as plain list. There is no indication which one is the most active, etc. Now, there is the service http://forked.yannick.io/ which list all forks an metrics on the forks. Example:

![image](https://user-images.githubusercontent.com/1366654/60397454-d03daa00-9b4d-11e9-92ce-363daaadd782.png)

It would be very helpful if one could jump from a repository directly to the respective page in there. For instance from this extension to http://forked.yannick.io/sindresorhus/refined-github.

**Comment by sindresorhus** [comment]
I think it could be useful, but can you illustrate how you image it would look? I don't think putting it next to the Fork button would look good.

**Comment by bfred-it** [comment]
Prior art: https://github.com/musically-ut/lovely-forks

I never actually found this useful.

GitHub offers a "network" page showing that information as well: https://github.com/sindresorhus/refined-github/network

**Comment by 1138-4EB** [comment]
It seems that `yannick.io` is no longer available. I'd say that the corresponding repo is https://github.com/ys/forked.

I think that a feature such as this should use the multiple metrics available in the 'Pulse' view of each repo/fork. Precisely, I submitted the following suggestion through https://www.research.net/r/J7BJ7XF:

> Allow to 'zoom out' (to have a better view of the 'big picture').
>
> It is hard to tell apart forks which just add custom details (such as changing titles/names/assets for a company/project), from actual forks that contribute useful features for other users (probably because the 'original' repo is stalled). I think that adding statistics about the forks (stars, contributors, opened/closed PRs, etc.) would really help here. There is enough info already available in the 'Pulse' view of each repo/fork that could be used for this task.

However, this might be difficult to implement outside of GitHub, due to API rate limits: https://github.com/ys/forked/issues/9#issuecomment-304769045.

**Comment by koppor** [comment]
@1138-4EB  It used to work when I opened the issue. Thank you for the pointers.

@bfred-it Quite useful tool.

**Comment by koppor** [comment]
> I think it could be useful, but can you illustrate how you image it would look? I don't think putting it next to the Fork button would look good.

I would indeed put it right of the fork button. Keeping the number of forks, but replacing the link from the normal GitHub fork network to a more useful list.

Since http://forked.yannick.io/ is down, I will close this request. If it comes back, I will reopen it.

**Comment by bfred-it** [comment]
If you're interested in this feature, I suggest you just use this extension: https://github.com/musically-ut/lovely-forks

**Comment by NightMachinary** [comment]
[This](https://techgaun.github.io/active-forks/index.html) one works well. I also like `lovely forks`. I think adding these to this project is a good social move; Letting forks be more visible will help people find them and this can make revitalizing unmaintained projects easier.

**Comment by fregante** [comment]
This feature was recently added https://github.com/sindresorhus/refined-github/pull/3955
