### ISSUE TITLE
Hide "Yours" category in branch lsit

### ISSUE THREAD

**Issue by AlexejheroYTB** [sindresorhus/refined-github#2196]
The title is self explanatory.

Hide the "Yours" category in the branch list of repos. It's just annoying

Example URL:

https://github.com/sindresorhus/refined-github/branches

**Comment by sindresorhus** [comment]
Why is it annoying?

**Comment by AlexejheroYTB** [comment]
When I check the branch list, I personally expect to see a clear list of branches, but Github categorizes them and the "Yours" category isn't really useful. It just makes the branch appear two times.

**Comment by fregante** [comment]
It might be useful in repos with multiple contributors. Let's not drop hide it
