### ISSUE TITLE
other github issues repos

### ISSUE THREAD

**Issue by oprogramador** [sindresorhus/refined-github#2198]
There are at least 2 repos which do the same job:
- https://github.com/isaacs/github
- https://github.com/dear-github/dear-github

So it would be good to:
- decide which repo we're using for reporting GitHub feature requests and bugs
- move all the issues from the remaining repos
- in the remaining repos README post such info `This repo is deprecated, please go to {link} instead`

**Comment by bfred-it** [comment]
**Refined GitHub** is not a repo to report feature requests and bugs to GitHub, it's an extension that actually adds those features.

The original repo for this purpose was https://github.com/isaacs/github while https://github.com/dear-github/dear-github is being misused.

**Comment by oprogramador** [comment]
Sorry.
