### ISSUE TITLE
Fix sponsorship configuration

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#2200]
When you click the Sponsor button there's an error since @bfred-it is added to `.github/FUNDING.yml`, but not registered for receiving sponsorships.

I'm all for this to work, just want to make sure when people use it, it actually reaches the people who are configured and there are no errors when you click a button on this repo.

**Comment by bfred-it** [comment]
Indeed, it looks like my account hasn’t been enabled yet

**Comment by hkdobrev** [comment]
@bfred-it I didn't mean to remove it, just wanted to flag it up so you can apply. Not sure what the process is, though, so up to you.

**Comment by bfred-it** [comment]
I think I’m on their waiting list, so I’ll just have to wait
