### ISSUE TITLE
Bug on pull request files tab

### ISSUE THREAD

**Issue by sharkykh** [sindresorhus/refined-github#2202]
**RGH Version:** 19.6.30 (Chrome)

GitHub recently added a new feature for marking files as viewed when reviewing a pull request.
The following bugs happen when Refined GitHub is enabled.
Confirmed by disabling all browser extensions but RGH.

1. When the length of the PR title + number is too long,
	it wraps the right-floated elements to a new line.
2. When the filename of the file currently in view is too long,
	the scrolling "file actions" bar is malformed (for lack of a better term).
	**Edit:** It's possible that it only happens if the **first** filename is too long, as on the example PR below, the second filename is even longer, yet it looks just fine.

**Edit 2:** When I disable [`faster-pr-diff-options`](https://github.com/sindresorhus/refined-github/blob/19.6.30/source/features/faster-pr-diff-options.tsx) it fixes both bugs.

This is an example PR: https://github.com/pymedusa/Medusa/pull/6893/files

---
## RGH **disabled**
![chrome_XwwqDu9Y0Q](https://user-images.githubusercontent.com/10238474/60498592-9391c000-9cbf-11e9-803a-54499147e411.png)

---
## RGH **enabled**
![chrome_ePXSiihJ2e](https://user-images.githubusercontent.com/10238474/60498661-b58b4280-9cbf-11e9-91c5-14d79f9b8298.png)

**Comment by fjeremic** [comment]
I'm seeing the same issue on RGH 19.6.30 on Firefox 67.0.3 on Windows.

**Comment by bfred-it** [comment]
There's not enough space in the header, we'd have to reduce the title width: 

![](https://user-images.githubusercontent.com/1402241/60576497-1db95180-9db0-11e9-87e1-38610136eba3.gif)

Or rather... we should drop #1799. Instead of extracting the two pieces like we do now, we can keep the dropdown: 

<img width="261" alt="Screenshot 2019-07-03 at 16 36 46" src="https://user-images.githubusercontent.com/1402241/60576847-c5cf1a80-9db0-11e9-8f44-e99cf45bd1b7.png">

And just drop the "Apply and reload" button, making it a two-clicks operation.

**Comment by jerone** [comment]
We can keep #1799, if we can reduce the "No Whitespace" button text. What if we use `␣` character (`\u2423`):
![image](https://user-images.githubusercontent.com/55841/60742188-a1b83880-9f6c-11e9-87ad-744ae3fbeba2.png)


<small>I used it in [my UserScript](https://github.com/jerone/UserScripts/tree/master/Github_Commit_Whitespace#readme).</small>

**Comment by abdelrahmanrifai** [comment]
@jerone that will still wouldn't fit with a long PR titles:

Refined Github Enabled:

![with-refined-github](https://user-images.githubusercontent.com/4334778/60822016-efb78100-a1a4-11e9-8d5e-dbedfa385d6b.png)

Refined Github Disabled:
![without-refined-github](https://user-images.githubusercontent.com/4334778/60822020-f219db00-a1a4-11e9-9127-5e48423568b5.png)

You could also check it yourself here https://github.com/abdelrahmanrifai/git/pull/1

I'd suggest to drop #1799 as @bfred-it mentioned.

**Comment by jerone** [comment]
My suggestion would still be to keep #1799, change the whitespace button text to `␣` and limit the length of the title.

```diff
a.js-issue-title.css-truncate.css-truncate-target.link-gray-dark {
-	max-width: 35em;
+	max-width: 30em;
}
```

Title max length can be shortened further because it's not important information in this context. You already know what you are reviewing. I rather keep those most used buttons while reviewing.

**Comment by waldyrious** [comment]
@jerone `30em` doesn't seem to be sufficient in my experiments. I managed to get it to work with `24em`:

<img width="1025" alt="Screenshot 2019-07-09 at 16 27 40" src="https://user-images.githubusercontent.com/478237/60901921-ac254b80-a266-11e9-8361-0da01e8b9e85.png">

**Comment by sharkykh** [comment]
@waldyrious I'm assuming @jerone meant `30em` + replacing `No Whitespace` with `␣`

**Comment by waldyrious** [comment]
Good point, I forgot that detail. Sorry for the noise :)

**Comment by bfred-it** [comment]
I'm not sure I like the position of this feature either, it makes me feel I'm always on the fork:

<img width="329" alt="Screenshot 2019-07-10 at 14 04 15" src="https://user-images.githubusercontent.com/1402241/60944529-a89fcc00-a31b-11e9-9140-56d99fd61f7b.png">

<img width="287" alt="Screenshot 2019-07-10 at 14 04 48" src="https://user-images.githubusercontent.com/1402241/60944540-b2c1ca80-a31b-11e9-876c-b86ca5023490.png">

**Comment by yakov116** [comment]
@bfred-it I think it should have a different color

**Comment by sindresorhus** [comment]
> My suggestion would still be to keep #1799, change the whitespace button text to ␣ and limit the length of the title.

Let's do that. But the button should have a tooltip as `␣` is not clear enough.

**Comment by bfred-it** [comment]
How do you differentiate "Whitespace" from "No whitespace"? `␣` is the default state (visible) and `✕␣` is hidden?

**Comment by jerone** [comment]
Use the `selected` class, just like "Unified diffs" buttons.

**Comment by waldyrious** [comment]
> Use the `selected` class, just like "Unified diffs" buttons.
>
> And maybe drop the `btn-outline` class...

...as well as `bg-gray-light` and `text-gray-light`.

Here's how it'd look like:

<img width="1020" alt="Screenshot 2019-07-11 at 09 39 31" src="https://user-images.githubusercontent.com/478237/61035966-084fb300-a3c0-11e9-86ec-1b28381e637a.png">

<img width="1016" alt="Screenshot 2019-07-11 at 09 38 25" src="https://user-images.githubusercontent.com/478237/61035965-084fb300-a3c0-11e9-98c7-04260700c8aa.png">

**Comment by bfred-it** [comment]
Sounds good, but perhaps it should be the opposite: 

- Whitespace visible: `.selected`
- Whitespace invisible: ``

**Comment by jerone** [comment]
This feature is not really about showing or hidding whitespace. It's about **ignoring** whitespace in code compare. With that in mind, what about:
* Don't ignore whitespace: `.btn`
* Ignore whitespace: `.btn.selected`

**Comment by bfred-it** [comment]
> it's about **ignoring** whitespace in code compare

Yeah, that's what I meant.

> Ignore whitespace: `.btn.selected`

The current button has a "No" in front of it, so it makes sense: _selected_ "no whitespace" = whitespace ignored.

If we shorten it to a simple "Whitespace", its selected state shouldn't mean "ignore" IMHO. In your suggestion, it will be read as: `Whitespace: selected` while the whitespace is actually ignored.

**Comment by bfred-it** [comment]
If we used literally <kbd>-w</kbd> instead of <kbd>␣</kbd> at least it might make sense to CLI users.

`-w` regular state: off
`-w` selected: on, ignore whitespace

**Comment by wearhere** [comment]
Hey folks, this appears to have regressed, unfortunately. I opened a new issue to track: https://github.com/sindresorhus/refined-github/issues/2291.
