### ISSUE TITLE
Pressing ' conflicts with Korean keyboard composition

### ISSUE THREAD

**Issue by soomtong** [sindresorhus/refined-github#2203]
in korea some use not typical keyboard layouts like me.
common korean word made by automatas that state seleted mode
in this case, some key use `'` for typo, not a quote.

see this image

![auto-quotes](https://user-images.githubusercontent.com/906974/60508770-5997dc80-9d06-11e9-9f38-e4a6d4e5dba8.gif)

we want to disable this automatically quite feature.
but can't see disable option.

Example URL:

**Comment by bfred-it** [comment]
@notlmn the `event` might have `isComposing` property we need to check

**Comment by bfred-it** [comment]
Are you using Windows? I can't replicate that behavior on macOS though

![오빠](https://user-images.githubusercontent.com/1402241/60570235-b8f7fa00-9da3-11e9-90c6-5393115d6dcb.gif)

**Comment by soomtong** [comment]
in korean typically use standard type layout, that korean characters not use special key like quote, question... it likes qwerty layout. 
but someone use another layout. it needs more keys for each korean characters.
normally non-korean can't reproduce this situation i think.
as u see I saw `fix-composing-events` patch and confirm it solved. 
so we can close this issue and relates.
and u may know I am happy with refined-github more!
