### ISSUE TITLE
`indented-code-wrapping` causes the "No newline" character moves to new line

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#2205]
With Refined GitHub, the "no newline" character is placed on a new line (hehe).

<img width="483" alt="Screen Shot 2019-07-03 at 17 40 30" src="https://user-images.githubusercontent.com/1935696/60605905-a50bc280-9dba-11e9-9cf5-347e433cd6f2.png">

It should probably look more like without the extension enabled:

<img width="409" alt="Screen Shot 2019-07-03 at 17 41 33" src="https://user-images.githubusercontent.com/1935696/60605962-be147380-9dba-11e9-9789-80698d5ea900.png">

Reference: https://github.com/microsoft/TypeScript-Website/pull/1/files

**Comment by notlmn** [comment]
That's me 😅.

This is because of: https://github.com/sindresorhus/refined-github/blob/6d852ce1d75bf9ce59bedb902300d9d5a2a8b4e6/source/features/indented-code-wrapping.css#L12

I know that I could've used `inline-block` but for the love of science I can't exactly remember why I went with `block`.

**Comment by arnaudvalle** [comment]
Hello there - is this still a problem? I've had a look at the link provided in the description (https://github.com/microsoft/TypeScript-Website/pull/1/files) and it seems fine to me in both Firefox and Chrome with the extension?

**Comment by fregante** [comment]
@arnaudvalle thanks for checking! `indented-code-wrapping` has been disabled, that's why the problem doesn't appear.

**Comment by fregante** [comment]
Closed until the feature is restored: https://github.com/sindresorhus/refined-github/issues/2729
