### ISSUE TITLE
Improve file path and name visibility in PR Files changed section

### ISSUE THREAD

**Issue by igorwojda** [sindresorhus/refined-github#2206]
Currently, long file names are not displayed properly (filename is not visible).
Also with a long path, it's quite hard to get filename at first glance.

It would be nice to
1. Make path fully visible
2. Make filename bold

Example URL:

![image](https://user-images.githubusercontent.com/530122/60650763-ada4dd00-9e3c-11e9-9417-1c8c6ae651f0.png)

**Comment by bfred-it** [comment]
Example URL missing

**Comment by igorwojda** [comment]
https://github.com/igorwojda/kotlin-coding-puzzle/pull/22/files

**Comment by fregante** [comment]
This probably needs to be implemented via flexbox because currently the path length limit is set in pixels

**Comment by fregante** [comment]
<img width="1006" alt="Screen Shot 2020-03-19 at 02 11 29" src="https://user-images.githubusercontent.com/1402241/77021446-f975c300-6986-11ea-8ece-1e8a0bc06ffd.png">


Can no longer reproduce, they probably fixed it
