### ISSUE TITLE
Remove links for folders containing only a .gitkeep

### ISSUE THREAD

**Issue by AlexejheroYTB** [sindresorhus/refined-github#2208]
## Suggestion
In some repos, there may be empty folders containing a `.gitkeep` file. This is usually done so that the folders appear in the repo, even though they dont contain any files (maybe the folders themselves store information in their name).

The link to open the folder is redundant because inside it there is only a 0 KB `.gitkeep` file.

Refind github could check if there is only one file in the folder and if it has 0 KB, and if that is the case, completely remove the link to open the folder.

## Example URL

https://github.com/AlexejheroYTB/Dlockly/tree/master/blocks/custom

Example of folder that this could apply to: `002 [sep]`'

## Images
This feature could look something like this: 

![image](https://user-images.githubusercontent.com/32238504/60742653-dd580000-9f76-11e9-8014-54f1e655e563.png)

**Comment by bfred-it** [comment]
I’m not a fan of completely hiding files, but this can be a generic feature that changes folder links to `folder/single-file.ext` like GitHub already does natively for folder/single-subfolder` if I remember correctly

**Comment by jerone** [comment]
This could be a feature for [Hide Files on GitHub](https://github.com/sindresorhus/hide-files-on-github).

**Comment by fregante** [comment]
Implementation suggestion:
1. Watch for changes in the files list. Refer to the Hide Files extension suggested above, there’s good code for this in there. 
2. Fetch the contents of ALL the visible folders in a single GraphQL query. Look for pre-existing features that do this: search `api.v4`‘s usage in our code
3. For each folder that has a single file, change the link to point to that file.

It’s not an easy feature, but not a super complex one either.

**Comment by fregante** [comment]
This needs to ask info for every folder you ever see... just to possibly skip a click that you might not ever make. This is of limited use and not worth the complexity.
