### ISSUE TITLE
Oddballs testing links

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2209]
If you find some rare pages on GitHub that would be useful when implementing new features, post them here.

## PR with 250 files

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/34748/files

## TypeScript file with 18K lines

https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts

**Comment by jerone** [comment]
## Readme file in subfolder
https://github.com/davidbailey/tum/tree/master/handbook#readme

**Comment by fregante** [comment]
## Multiple pages of labels 

https://github.com/sourcegraph/sourcegraph/labels?page=7&sort=name-asc
