### ISSUE TITLE
Linkify JS code.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#221]
It would be awesome to linkify JS code.

- Variable names link to the line of their declaration / import.
- Relative imports / requires link to the relative file in the same repo.
- External module imports link to the appropriate `npmjs.org` page.

**Comment by sindresorhus** [comment]
Have you seen https://github.com/OctoLinker/browser-extension ?

**Comment by jamestalmage** [comment]
Oh wow! So awesome!
