### ISSUE TITLE
The footer is incredibly hard to read in Explore page

### ISSUE THREAD

**Issue by kumarharsh** [sindresorhus/refined-github#2212]
When navigating to https://github.com/explore, the refined github plugin causes the footer to be extra light and rendering any text unreadable. I'm kinda OK with this in the github repository view, but on the rest of the site, I think the footer should be more visible.

With Refined Github:
![image](https://user-images.githubusercontent.com/760112/60788419-507d9400-a17a-11e9-8972-164fe215d620.png)

Without Refined Github:
![image](https://user-images.githubusercontent.com/760112/60788437-5bd0bf80-a17a-11e9-9a1f-3037f4a0e74a.png)

**Comment by lukaszklis** [comment]
How about using `opacity: 0.5` instead?
![github com_explore](https://user-images.githubusercontent.com/11782/61033083-fd4a5200-a3c2-11e9-88cb-7b3947c1ef66.png)

**Comment by bfred-it** [comment]
A while ago `:not(:hover) { opacity: 0.3 }` was also suggested

**Comment by kumarharsh** [comment]
`:not(:hover)` is a decent compromise I guess

**Comment by fregante** [comment]
PR welcome

**Comment by kumarharsh** [comment]
@fregante done!

I was wondering if it'd be better if the footer is always visible on *content* pages of Github, like the [About page](https://github.com/about) or the [Enterprise](https://github.com/enterprise) page? That's a company-level page, and I think people would be more interested to peruse the footer links in *that* context.

If you agree, I can make a separate PR or include it in this one, whichever way you see fit.
