### ISSUE TITLE
Duplicated “Update Branch” button

### ISSUE THREAD

**Issue by marcobiedermann** [sindresorhus/refined-github#2213]
### Description

When “Require branches to be up to date before merging” is enabled in branch protection and branch in PR is not up to date, I see two buttons to update it

### Environment

```
https://github.com/<USERNAME>/<REPO>/pull
```

### Screenshot

![image](https://user-images.githubusercontent.com/5244986/60791474-05f11d00-a164-11e9-84d1-9bcb0c8f4aba.png)

**Comment by bobvanderlinden** [comment]
I'm seeing the same problem. Not sure yet what's going on, but the related piece of code is here:

https://github.com/sindresorhus/refined-github/blob/90226744b60546d48006db95cf1352d1e7a7d580/source/features/update-pr-from-base-branch.tsx#L59-L86

Maybe GitHub changed the way they impementated their update branch button. It is possible to look up the button using:

```
if (select('.branch-action-btn')) {
  return;
}
```

**Comment by bfred-it** [comment]
Yep, that'd be great. Line 60 should probably be:

```js
 if (select.exists('.rgh-update-pr-from-master, .branch-action-btn')) { 
```

But I think `.branch-action-btn` includes other similar buttons nearby, so it needs to be more specific.
