### ISSUE TITLE
Duplicated unified/split diff buttons

### ISSUE THREAD

**Issue by anowlcalledjosh** [sindresorhus/refined-github#2217]
On PRs, it looks like Refined GitHub adds icon buttons for unified/split diffs, but doesn't remove the existing textual buttons:

![image](https://user-images.githubusercontent.com/9433472/60888046-d0286300-a24d-11e9-83e2-7a313595038b.png)

With the extension disabled, the icon buttons don't appear.

**Comment by sharkykh** [comment]
I think it should be clarified that this is visible on a single commit view, and not in the context of a PR.
Example: https://github.com/sindresorhus/refined-github/commit/75624f2acf21abf14fa75ea512cfcab42eeb6a2c

**Comment by bfred-it** [comment]
The feature is supposed to replace those buttons with our “icon-only” version. 

The future of the feature itself is being discussed in https://github.com/sindresorhus/refined-github/issues/2202
