### ISSUE TITLE
Add color wheel for picking label colors

### ISSUE THREAD

**Issue by allejo** [sindresorhus/refined-github#2224]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2224)

I may just be overcomplicating a simple feature within GitHub, but when selecting colors for my labels, I always randomly shuffle colors. Sometimes I find a color I like but my obsessiveness drives me to find a slightly different shade of that color.

Would anyone else want a color picker to exist?

Example URL: https://github.com/sindresorhus/refined-github/labels

I'd imagine it'd look something like this:

![image](https://user-images.githubusercontent.com/1246453/61071239-6df26e00-a3c5-11e9-9ded-69812eaf09af.png)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/55841?v=4' alt='jerone' width=24 height=24> jerone](https://issuehunt.io/u/jerone) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
We could use the native color picker: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/color

**Comment by allejo** [comment]
Sure, that'd suit my needs perfectly!

**Comment by Mottie** [comment]
If you have Tampermonkey installed, I have a userscript that'll do this - https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-label-color-picker

**Comment by fregante** [comment]
This is extremely easy:

```js
for (const field of select.all('.js-new-label-color-input')) {
	field.type = 'color';
}
```

Anyone who wants it, just needs to create a feature called `label-color-picker` and add documentation for it. Follow `contribute.md`

**Comment by fregante** [comment]
@notlmn does your OS not show a text input together with the color picker?

**Comment by fregante** [comment]
I guess the alternative is to duplicate the field and bind them together (`text` field updates `color` field and viceversa). Something like:

```jsx
for (const field of select.all('.js-new-label-color-input')) {
	field.after(<input type="color" className={field.className} style={{width:'2em'}}>);
}
delegate('.js-new-label-color-input', 'input', event => {
	event.delegateTarget.nextElementSibling.value = event.delegateTarget.value;
});
delegate('.js-new-label-color-input + input', 'input', event => {
	event.delegateTarget.previousElementSibling.value = event.delegateTarget.value;
});
```

However it would look something like:

<img width="193" alt="Screenshot 2019-09-14 at 22 45 38" src="https://user-images.githubusercontent.com/1402241/64910511-65117600-d741-11e9-9e57-47f7e79f8097.png">

**Comment by johnletey** [comment]
I've started work on this!

**Comment by KarlHeitmann** [comment]
I've made a PR here #2591 with the enhancement. But I closed it by accident, since it is my first PR on a big project and didn't know what is the workflow to submit a PR. I will appreciate some help on reopenning the PR, apparently I don't have the necesary privileges. Or maybe I'll have to upload another branch, I don't know.

The feature I've built has some little bugs that are commented on the file with FIXME tags: The most important is that if you press the "save button" to save the new color for your label, if you press the edit button again on the same label, the color palette will disappear. You will have to refresh the whole page again to see the color palette if you will like to edit the same label color again.

**Comment by fregante** [comment]
The PR can’t be reopened because the branch was deleted. Maybe try to restore the branch and then reopen. 

Also include a screenshot in your PR to see how it looks first

**Comment by KarlHeitmann** [comment]
Thanks, I'll take a look

**Comment by fregante** [comment]
I think the [userscript](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-label-color-picker) will have to do, we don't have to include every feature.
