### ISSUE TITLE
Restore `edit-readme-button` on all repos

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2225]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2225)

We used to add an **Edit** button to readmes but GitHub added it: 
- a953ed4948e4dd5a73fc94413a1368b4b1c3665a 
- https://github.com/sindresorhus/refined-github/commits/master/source/features/add-readme-buttons.js

Sadly they only show it on repos you have push access to, not all of them. Our button would prompt you to create a fork if you didn't have access to the repo.

Normally [`edit-files-faster`](https://github.com/sindresorhus/refined-github/blob/73bef2da95b640e7ed39767ec181edb081d465e1/source/features/edit-files-faster.tsx) would be a replacement for this button, but I also use https://github.com/sindresorhus/hide-files-on-github which hides the `readme` file from the file list 😅

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#2231 Add `edit-readme` feature](https://issuehunt.io/r/sindresorhus/refined-github/pull/2231)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by gurrrung** [comment]
Is it just about restoring back to the old state by reading commits history or am I missing some other stuff ? @bfred-it

**Comment by jerone** [comment]
Thanks @sindresorhus 😊

Can you have a look at the other [not yet rewarded issues](https://github.com/sindresorhus/refined-github/issues?utf8=%E2%9C%93&q=is%3Aclosed+label%3A%22%3Adollar%3A+Funded+on+Issuehunt%22). 🎁💸

**Comment by sindresorhus** [comment]
Done

**Comment by jerone** [comment]
Appreciate it!
