### ISSUE TITLE
Broken tests

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-github#223]
I have failing tests on `master`:

```
~/extension/page-detect.js:37
		const [, ownerName, repoName] = location.pathname.split('/');
		      ^

SyntaxError: Unexpected token [
```

It looks like this was introduced by @DrewML here: https://github.com/sindresorhus/refined-github/commit/40db4fba4e2f3c9bf9d3599f933ef184fab092ae

**Comment by paulmolluzzo** [comment]
This looks to be a local issue. Any ideas why?

// @sindresorhus

**Comment by jamestalmage** [comment]
The commit you link to appears to actually be a fix for this issue (he deleted the offending code). Is the branch you're working on a bit behind?

**Comment by jamestalmage** [comment]
> This looks to be a local issue. Any ideas why?

You probably aren't running new enough node to support destructuring, needs to be 6 I think.

**Comment by DrewML** [comment]
`You probably aren't running new enough node to support destructuring, needs to be 6 I think.`

Yeah, that's what should be causing the failures. Valid code in before/after commits, just needs to run in a newer version of v8 than node <=5 had

**Comment by jamestalmage** [comment]
so close?

**Comment by sindresorhus** [comment]
Yup, tests must be run in Node.js 6.

**Comment by paulmolluzzo** [comment]
Ah, thanks.
