### ISSUE TITLE
Colors for `highest-rated-comment` decorations 

### ISSUE THREAD

**Issue by loilo** [sindresorhus/refined-github#2237]
This is a very minor (possibly even nitpicky) complaint:

I love the recent `highest-rated-comment` feature (thanks @lubien!). However, the orange-y border around the comment and the jump link always looks a little bit "off" to me.

While the border is clearly noticeable, it has two main flaws in my opinion:

1. It does not fit with any other style used on github.com.
2. The color does not communicate its intent. Maybe this is a personal thing, but to me the orange border always communicates a "warning!"/"caution!" instead of a "heads up, possible solution below!"

I have been using a different style locally for a while now. It's a bit more "githubby" (main color taken from GitHub's green tone as in the "successful check" icon in PRs) and to me it feels a little more inherently positive, so I think it might be worth sharing:

![Original test screenshot of the `highest-rated-comment` feature](https://user-images.githubusercontent.com/1922624/61234106-8ac6d280-a732-11e9-9465-20b585646540.png)

What do you think @lubien? Is that something you've come across before, or even dismissed in your coloring decision? Would be curious for feedback. 🙂

**Comment by lubien** [comment]
> the orange border always communicates a "warning!"/"caution!"

Agreed!

> Is that something you've come across before

This was definitely something I left out on the process. I'd love to update to a more fitting color.

Although successful-green fits the role it also feels out of place I don't know if it's just me. 

Before I go for it **I'd like suggestions** of other kinds of colors (I'm not really the best person to be asked for colors :sweat_smile:) before we (once again) just put a color.

**Comment by loilo** [comment]
Very much agreed! 👍
