### ISSUE TITLE
Differentiate between releases and pre-releases

### ISSUE THREAD

**Issue by mattnelson** [sindresorhus/refined-github#2239]
Releases can be created from tags, which can then be further classified as pre-release or the default of the latest release.
<img width="604" alt="Screen Shot 2019-07-15 at 6 47 35 PM" src="https://user-images.githubusercontent.com/1894657/61256118-1dff0880-a731-11e9-9aa6-8e98da1527ae.png">

The latest release widget displays a release marked as pre-release as the latest release.
<img width="332" alt="Screen Shot 2019-07-15 at 6 46 31 PM" src="https://user-images.githubusercontent.com/1894657/61256119-1dff0880-a731-11e9-9cff-11bc487f6fca.png">

The API supports the ability to differentiate between the two.
https://developer.github.com/v3/repos/releases/#list-releases-for-a-repository

**Comment by sindresorhus** [comment]
PR welcome :)

**Comment by bfred-it** [comment]
The Tags endpoint doesn’t include this info and the Releases endpoint doesn’t include all tags (so it would only work if a repo uses releases)

> This returns a list of releases, which does not include regular Git tags that have not been associated with a release. To get a list of Git tags, use the Repository Tags API.

The Tag object doesn’t include references to the related release either: https://developer.github.com/v4/object/tag/

The only way to do this seems to be making 2 queries and then check filter out any tags that are in prereleases.

More generically, I think we can just detect and discard tags that include `-` which seems to be used for prereleases

**Comment by kidonng** [comment]
> we can just exclude tags that include `-`

Quite a few repos have dates in their tag names (for example `YYYY-MM-DD`).

**Comment by fregante** [comment]
We’ll never catch all the edge cases but, maybe: 

- exclude specifically `x.y.z-b` tags
- in our existing v4 query, also check if we have information about a tag being a pre-release or “latest release”
