### ISSUE TITLE
`forked-to` shows the current fork

### ISSUE THREAD

**Issue by ScopeyNZ** [sindresorhus/refined-github#2246]
A picture is worth a thousand words: 

![image](https://user-images.githubusercontent.com/3260989/61340356-1016c800-a896-11e9-88c5-e7c374de5bbf.png)

Minor issue but when you're looking at a fork it shows "forked to [current repo]" below the actual current repo name. Seems like an unnecessary double-up.

**Comment by jerone** [comment]
This is a result of removing the current page check; https://github.com/sindresorhus/refined-github/pull/2216/files#diff-ff16301f232100bd87e910eb98614f66L13

**Comment by bfred-it** [comment]
The check was moved to line 44
