### ISSUE TITLE
open comments in editor

### ISSUE THREAD

**Issue by kidd** [sindresorhus/refined-github#2253]
Years ago I developed a userscript that adds a button in code comments that are pinned to a file+line. When clicked, it opens emacs in the correct file/line.

Here's a small demo: https://vimeo.com/51362143

It's not straightforward to install as it is now (tampermonkey+script, emacs plugin (maps repo to a local directory), and a way to open "emacs://" links with the right app).

I'm happy with it as it is now, but I was thinking that maybe you would accept a PR into refined-github that adds some of its capabilities. Does it sound interesting enough? If so, we can keep discussing the details, if not, I totally understand it (much more hacky and not ready-to-use extension than other things in refined-github).

Awesome project you have here!

**Comment by bfred-it** [comment]
Interesting concept, but it’s too complex for Refined GitHub, it’d have to work on all OSs and editors.

Related: 
- GitHub has some “Clone in GitHub Desktop” buttons across the site, including PRs, and that’s the only thing we could augment in this extension
- https://github.com/GhostText/GhostText
