### ISSUE TITLE
Number files in review interface

### ISSUE THREAD

**Issue by leventov** [sindresorhus/refined-github#2254]
It would be nice if the files were numbered in the review interface, like this:

![image](https://user-images.githubusercontent.com/609240/61549058-c675db00-aa57-11e9-99c6-19499af2ad3f.png)

**Comment by bfred-it** [comment]
Why?

**Comment by leventov** [comment]
To see your progress into a PR. Browser's scroll bar may be quite deceptive because of a huge number of unloaded changes at the end of a PR.

**Comment by bfred-it** [comment]
It doesn't sound like something that'd help me. I'll leave the discussion open for now

**Comment by fregante** [comment]
Looks like there was no interest, sorry
