### ISSUE TITLE
Extend `format-discussion-titles` to issue sticky header #321

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2255]
Example URL:

![image](https://user-images.githubusercontent.com/16872793/61551831-3ec2a900-aa24-11e9-86fd-0329d8983639.png)

For both the backticks and the linkify issue numbers

**Comment by jerone** [comment]
Same thing happens on PR when your scroll:

![image](https://user-images.githubusercontent.com/55841/61556085-376dc080-aa61-11e9-87cc-b785dc6de5b3.png)

Example: https://github.com/sindresorhus/refined-github/pull/2229
