### ISSUE TITLE
`edit-files-faster` and `edit-readme` should not be added to commits and tags

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2261]
Files are only editable when you're on a branch, not on a specific commit or tag. Clicking the "Edit file" button will lead you to a 404 page

# Test urls
### `edit-file-faster`
- https://github.com/sindresorhus/refined-github/tree/4a03e4e8c29612c9e4aceefef70842cc3640e38e
- https://github.com/sindresorhus/refined-github/tree/19.7.19

### `edit-readme`

- https://github.com/chartjs/Chart.js/tree/6632b8ba8475e020fd0533e2630117376a9cbc73
- https://github.com/chartjs/Chart.js/tree/v2.8.0

**Comment by jerone** [comment]
> ### `edit-readme`
> 
> * https://github.com/chartjs/Chart.js/tree/v2.8.0

This is my view after clicking the button:

![image](https://user-images.githubusercontent.com/55841/61578816-bb28bb00-aafc-11e9-9308-cc069932c0dc.png)

**Comment by bfred-it** [comment]
Yes, now click that button, it's a 404

**Comment by jerone** [comment]
Hmmm, I could swear this worked before. 🤔

**Comment by bfred-it** [comment]
The fun part is that GitHub themselves add those broken “edit readme” links on your own repos as well:

1. Open a repo you own
2. Visit a tag
3. You’ll find a non-functioning “Edit readme” links without  Refined GitHub
