### ISSUE TITLE
`edit-readme` feature is broken

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#2262]
The feature adds an Edit button on repos you don't have access to. GitHub already adds it on your own repos.

1. Visit https://github.com/chartjs/Chart.js
2. No "Edit" button in the readme:

<img width="1004" alt="" src="https://user-images.githubusercontent.com/1402241/61576119-4b203200-ab08-11e9-8f91-7ef283281c43.png">

cc @jerone

**Comment by jerone** [comment]
It's there for me. 

Is there another extension/userscript blocking this? Any errors in the console? You are in some beta testers group from GitHub?

![image](https://user-images.githubusercontent.com/55841/61578803-700ea800-aafc-11e9-875b-9adb57f15ad2.png)

**Comment by bfred-it** [comment]
Indeed. It's working now, I'm not sure why it wasn't there before. I'm on Firefox
