### ISSUE TITLE
Add option to only render boundary whitespace

### ISSUE THREAD

**Issue by leggsimon** [sindresorhus/refined-github#2266]
I really like the new rendering of whitespace in PRs (I always have it enabled in my text editor) however personally I think it’d be nice to be able to choose to only render “boundary” whitespace instead of all of it.

VSCode’s definition of “boundary” whitespace is “Whitespace characters except for single spaces between words”.

Small example (ignore the squiggly):
<img width="189" alt="Screen Shot 2019-07-23 at 13 37 09" src="https://user-images.githubusercontent.com/11544418/61712778-ff12fe80-ad4e-11e9-9f9e-703c131419ba.png" alt="Code screenshot showing `, async  () => { `">

Here it’s not rendering the space character between the comma and the `async` keyword, but then there’s two spaces between `async` and the opening bracket so they get rendered and then finally any trailing whitespace gets rendered.

I can’t recall whether any features allow for different options rather than just on/off which might be a blocker to this potentially. My thought being that the options become `Off`, `Boundary`, & `All`

**Comment by bfred-it** [comment]
This is not possible without parsing the file itself, in each language. It's out of RGH's scope

**Comment by leggsimon** [comment]
Ahh yeah I guess, I wonder if you could do a rudimentary (pseudocode)
```
if two_spaces_together
	render_spaces_as •
else if spaces_at_end_of_line
	render_spaces_as •
else
	dont_render
```

I wonder if this might cover most cases (although I don’t really know the semantics of most other languages)

**Comment by bfred-it** [comment]
I never have “two spaces together” in my code, your example wouldn’t pass `xo` lint. “Two spaces together” don’t mean what you mean

**Comment by leggsimon** [comment]
Yeah, that’s fair. I’ll close this in that case
