### ISSUE TITLE
pr-branch-auto-delete should be disabled by default

### ISSUE THREAD

**Issue by cmccandless** [sindresorhus/refined-github#2267]
I discovered the addition of `pr-branch-auto-delete` (#2186) when I noticed that branches were being deleted without my explicit action. The feature functions as designed, but as this affects user repositories directly (and not just how they are presented), this is a feature that should not be enabled by default.

**Comment by bfred-it** [comment]
When do you not want a branch to be deleted?

**Comment by sindresorhus** [comment]
Also note that the action is easily reversible.
