### ISSUE TITLE
Find open PRs on your forks

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2268]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%245%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2268)

Usually forks are only useful to send PRs. When your open PRs are merged, they should be deleted.

Finding out whether your fork is still needed takes too long (open _source repo_, go to PRs, look for your PRs). 

**Refined GitHub should mention your open PRs** in:

- your forked repo's header (perhaps even adding a tab next to the original "Pull requests (0)" tab)
- In the "Delete repo" lightbox ("you have x PRs open" or "no PRs are open, you can delete it")

Ideally this should check whether there are any branches ahead of source like https://github.com/denis-sokolov/remove-github-forks does, but checking for PRs alone would make this feature a good companion to that CLI tool.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $5.00)

- [<img src='https://avatars0.githubusercontent.com/u/55841?v=4' alt='jerone' width=24 height=24> jerone](https://issuehunt.io/u/jerone) ($5.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fregante** [comment]
Possible starting point: https://stackoverflow.com/a/55125453/288906

**Comment by Esemesek** [comment]
I can take care of it. Already played with GraphQL queries for this and I found a possible solution.
```graphql
{
  search(query: "repo:sindresorhus/refined-github is:pr is:open author:Esemesek", type: ISSUE, last: 100) {
    edges {
      node {
        ... on PullRequest {
          url
          title
          createdAt
          isCrossRepository
          headRepository {
            owner {
              login
            }
            name
          }
        }
      }
    }
  }
}
```

With this query, we should be able to find out all the open PRs for a fork.

**Comment by fregante** [comment]
Sounds good

**Comment by dertieran** [comment]
I think there are two approachs to do this

1. By checking the PRs of the *parent* repository
2. Or by checking the *refs/branches* of the fork for open PRs

I think this really depends on what this feature should do.
With the second aproach it would be possible to check if there are any open PRs on any repository.

The query for this could look like this:
*(Maybe also hoping no one has over 100 branches in their fork :see_no_evil:)*
```gql
{
  repository(name: "refined-github", owner: "busches") {
    refs(refPrefix: "refs/heads/", first: 100) {
      nodes {
        associatedPullRequests(states: OPEN) {
          totalCount
        }
      }
    }
  }
}
```

<details>
<summary>Example Response</summary>

```json
{
  "data": {
    "repository": {
      "refs": {
        "nodes": [
          {
            "associatedPullRequests": {
              "totalCount": 1
            }
          },
          {
            "associatedPullRequests": {
              "totalCount": 0
            }
          }
        ]
      }
    }
  }
}
```
</details>

If the sum of all `associatedPullRequests` is greater then zero then this repo should probably not be deleted.
But these PRs could also include open PRs to the fork itself, not sure if that should be handled.

It would also be possible to check for `isCrossRepository` and get the `url` of the PR if that is needed.

I already have a working example for this [here](https://github.com/dertieran/refined-github/tree/open-prs-of-fork).

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/9264728/70256374-a8034880-1788-11ea-9cd5-1b2d820c9d7f.png)
![image](https://user-images.githubusercontent.com/9264728/70256433-c0736300-1788-11ea-9e07-f3521c277b68.png)
</details>

So I guess it now depends what should be displayed where and if all PRs of the fork count or just cross repository or even only to the *parent*.

**Comment by fregante** [comment]
My guess is that associatedPullRequests includes both local and cross-repo PRs, so if if there are 5 local PRs and 2 cross repo, the count returned should be 7. The Pull Request tab would show 5 and we could attach a `+2` right next to it. 

Additionally we could show “there are X open PRs from this repo” on the deletion page/popup

**Comment by dertieran** [comment]
This might require to only count the `isCrossRepository` PRs, because the PR tab also could contain PRs from other repository (e.g. the fork got forked again. 
Maybe we could also just ignore those edgecases but I just wanted to point that out.

So the query would then be like this:
*(I included the PR count of the current repository, we can also just parse the html)*
```gql
{
  repository(name: "refined-github", owner: "busches") {
    pullRequests(states: OPEN) {
      totalCount
    }
    refs(refPrefix: "refs/heads/", first: 100) {
      nodes {
        associatedPullRequests(states: OPEN, first: 100) {
          nodes {
            isCrossRepository
          }
        }
      }
    }
  }
}

```

**Comment by fregante** [comment]
No you don’t need to query it from the API because the number is already in the tab itself, right?

**Comment by dertieran** [comment]
> No you don’t need to query it from the API because the number is already in the tab itself, right?

Yes it wouldn't be needed but it doesn't really complicate the query so I think it wouldn't matter where to get it from.
It might be usfull if we also would like to know how many `pullRequests` are cross repository.

**Comment by loilo** [comment]
Wow, I did not find anything about this via search, so I just typed out a whole issue to suggest this feature... but I guess GitHub's "similar issues" feature got the better of me. 😁

I'm not familiar with the v4 API, but I found a very easy v3 request to get the according PRs using the `/search/issues` endpoint (example for my fork of `mautic/mautic`):

https://api.github.com/search/issues?q=repo:mautic/mautic+is:pr+is:open+author:loilo

---

I'd be happy to implement this. The visualization in the header could be like this:

<img src="https://user-images.githubusercontent.com/1922624/76341523-7953bb80-62fd-11ea-9778-53332ea55559.png" alt="Head area of the loilo/mautic repo with the secondary headline stating &quot;forked from mautic/mautic with 1 open PR&quot; with the &quot;1 open PR&quot; part as a link" width="410" height="120">

What do you think?

**Comment by fregante** [comment]
It looks great! API v4 should work similarly, the query should be something like, off of my head:

``` GQL
{
  search(query: 'blah blah', type: ISSUE) {
    issueCount
  }
}
``` 

You can use GitHub GraphQL Explorer to figure it out

**Comment by loilo** [comment]
Good point. I'll try to figure it out.
