### ISSUE TITLE
Should Subscribe reason be hidden in Sidebar?

### ISSUE THREAD

**Issue by trivikr** [sindresorhus/refined-github#2269]
### Issue
The feature `clean-sidebar` hides the subscribe reason in the code below:
https://github.com/sindresorhus/refined-github/blob/4bc3f3aa213de18d89c32df454957752400f249f/source/features/clean-sidebar.css#L6-L9

### Screenshots
* UX (without refined-github on left, and with refined-github on right)
![Before](https://user-images.githubusercontent.com/16024985/61831574-0dcae580-ae23-11e9-96bd-0fe3dd060800.png)![After](https://user-images.githubusercontent.com/16024985/61831219-0e16b100-ae22-11e9-9a60-bf43930396c8.png)

* DevTools
![DevTools](https://user-images.githubusercontent.com/16024985/61831227-12db6500-ae22-11e9-9c6a-db085a888015.png)

### Expected behavior
* Power GitHub users who use refined-github extension are subscribed to multiple issues and might want to know the reason why they're subscribed to particular issue in order to decide if they want to Unsubscribe. The reason shown below Unsubcribe button is helpful.
* clean-sidebar feature description states `Hide all empty sections (or just their "empty" label) in the discussion sidebar`. As per description, it shouldn't hide non-empty reason for subscription.

**Comment by trivikr** [comment]
What do you feel about showing reason in sidebar?

As of now, I'm overriding this behavior by writing following custom CSS in my extension:
```css
.sidebar-notifications .reason {
	display: inline-block !important;
}
```

**Comment by trivikr** [comment]
Any update on this request?

Can we at least move the following CSS to a new feature (say `hide-subscription-reason`) so that it doesn't break existing users? https://github.com/sindresorhus/refined-github/blob/4bc3f3aa213de18d89c32df454957752400f249f/source/features/clean-sidebar.css#L6-L9

**Comment by trivikr** [comment]
Any update on this request?

I'll post a PR over the weekend to move the below CSS to new feature `hide-subscription-reason`:
https://github.com/sindresorhus/refined-github/blob/4bc3f3aa213de18d89c32df454957752400f249f/source/features/clean-sidebar.css#L6-L9

**Comment by fregante** [comment]
This is not big enough to justify a whole feature for it. Either it goes or it stays and you keep the CSS in the `Custom CSS` field.

cc @sindresorhus

**Comment by fregante** [comment]
The copy looks a bit messy there with the `Mark as unread` button but perhaps it can be moved _above_ `Subscribe` via flexbox

**Comment by trivikr** [comment]
This is how "Mark as unread" button will look like if moved above `Subscribe`
![Screen Shot 2019-08-05 at 7 18 47 AM](https://user-images.githubusercontent.com/16024985/62471344-636f8e00-b751-11e9-998d-7e1415c77e93.png)

**Comment by fregante** [comment]
I meant _the copy_ can be moved above the subscribe button:

> subscribe reason
> [unsubscribe button]
> [mark as unread button]

**Comment by trivikr** [comment]
Screenshot as per suggestion from @fregante 
![Screen Shot 2019-08-05 at 11 14 12 PM](https://user-images.githubusercontent.com/16024985/62515316-d838db80-b7d6-11e9-8e02-17b6188ba8ca.png)

**Comment by sindresorhus** [comment]
Sure, we can bring back the subscribe reason.

**Comment by trivikr** [comment]
> Sure, we can bring back the subscribe reason.

Cool! Where should the subscribe reason be placed?

1. Original location (below Subscribe/Unsubscribe button)
![61831574-0dcae580-ae23-11e9-96bd-0fe3dd060800](https://user-images.githubusercontent.com/16024985/62721583-5d7fe400-b9c1-11e9-9efb-b70f33aca8d1.png)

2. Original location, with "Mark as Unread" button moved to top
![62471344-636f8e00-b751-11e9-998d-7e1415c77e93](https://user-images.githubusercontent.com/16024985/62721626-79838580-b9c1-11e9-83d2-c053ec308edc.png)

3. New location, above Subcribe/Unsubscribe button
![62515316-d838db80-b7d6-11e9-8e02-17b6188ba8ca](https://user-images.githubusercontent.com/16024985/62721665-8e601900-b9c1-11e9-8f9c-fe2909c62182.png)

My vote goes for 2, as it's minimal changes from the default behavior from UX perspective

**Comment by fregante** [comment]
I think 3 is best. We shouldn't flip the two buttons like in 2, especially because `Mark as unread` is added later so you'll see the `Unsubscribe` button move
