### ISSUE TITLE
Pull request diff page crashes and is super slow, dropdowns not opening

### ISSUE THREAD

**Issue by montchr** [sindresorhus/refined-github#2273]
I can't use the dropdowns in the pull request header. When I leave the tab and come back a little bit later, the entire page is blank. When the page is visible, performance is in general super janky and slow. Oftentimes the entire page seems to hang.

I've isolated this to the Refined GitHub extension in Chrome.

This is occurring on a private repo when I view the diff. The pull request in question has nearly 4,000 lines added and about 100 commits.

I've been using Refined GitHub every day for a while but today was the first time this issue came up.

On every page load, there's an error in the console, coming from `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/content.js`:

```
content.js:2082 Uncaught (in promise) TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at onNewsfeedLoad (content.js:2082)
onNewsfeedLoad @ content.js:2082
async function (async)
onNewsfeedLoad @ content.js:2082
add @ content.js:2195
async function (async)
add @ content.js:2161
(anonymous) @ content.js:5366
__webpack_require__ @ content.js:12
(anonymous) @ content.js:64
(anonymous) @ content.js:65
```

Here's a screenshot of the dropdowns not working:

![](http://c.loop.garden/9367c13cb944/Screen%252520Recording%2525202019-07-26%252520at%25252014.31.gif)

**Comment by fregante** [comment]
Can you try to disable`show-whitespace`? It could help with the slowdown. 

I’m not sure what the problem with the dropdowns is

**Comment by montchr** [comment]
I'm not sure what changed but this no longer seems to be an issue for me. I'll reopen and try some more things if it comes up again.

**Comment by anderssonjohan** [comment]
Found this issue when googling for "github diff slow" because github diff/PR reviewing have been so slow that I can't use it for things larger that 100 lines or so. Now I had this PR of 1500 changed files and really needed to create a review comment but couldn't, so after finding this issue I disabled the Refined Github extension and I can now use GitHub (web) again! 🍾

**Comment by fregante** [comment]
@anderssonjohan could you see which feature caused the slowdown?

**Comment by anderssonjohan** [comment]
@fregante Silly me, didn't know that there was feature toggles. I re-activated the plugin now but couldn't get the error immediately. Will try the feature toggles if the problem arises again and post here. Thanks!

**Comment by huchenme** [comment]
There are too many options to try but it is also super slow if there are hundreds of files and it hangs when I am typing to add a comment. Have to disable it for now 😢

**Comment by squatto** [comment]
I have been struggling with the PR screen as well. The page would lock up while it attempted to render, and after scrolling down a bit the diffs would be completely blank. Eventually the tab would hang and Chrome would ask me to kill it. Disabling the `show-whitespace` option did the trick though. With that option disabled everything seems to be working great. Thanks for the suggestion @fregante!

**Comment by DeividasJackus** [comment]
Can we please reopen this?
Reviewing PRs with Refined Github enabled becomes a painful experience even on a monstrous workstation, let alone a laptop.
I'll see if I can figure out which option specifically causes the slow down, but the issue has made me use a VS Code extension for moving the PR review workflow out of GitHub altogether as I didn't want to ditch Refined Github 😞

**Comment by notlmn** [comment]
That's probably `show-whitespace` again. But you'll have to provide us with a PR as example so that we can confirm this behavior.

**Comment by DeividasJackus** [comment]
Doesn't seem to be it alone.

I've solved it on my end and found 3 culprits (sorted starting with the biggest bottleneck) I've now disabled:
1. `show-whitespace`
2. `highlight-deleted-and-added-files-in-diffs`
3. `linkify-code`

Tested with a PR containing 100+ file changes on a 3900x, the entire PR normally takes < 1 second to render while scrolling.
Enabling either of these 3 options introduced a notorious lag of 10+ seconds any time significant scroll occurs.
`show-whitespace` is however indeed the biggest show stopper, introducing a lag of at least 30 seconds.

**Comment by notlmn** [comment]
> `show-whitespace` however was indeed the biggest show stopper, introducing a lag of at least 30 seconds.

We do not have any concept of vdom as such that we can use to render only the things in viewport as VSCode does natively. Which is why these features end up being a bit heavy on _very-very-long_ PRs.

For example, the laptop I'm on right now would crash if I tried to load all 100+ diffs of a PR even _without_ having this extension installed.

----------------

> Tested with a PR containing 100+ file changes on a 3900x, the entire PR normally takes < 1 second to render while scrolling.

I'm not sure if GitHub would let you render 100+ diffs on the same page in < 1 second, but that's another issue.

--------------

Also, can't help you if you can't provide an example of a public PR.

**Comment by fregante** [comment]
I opened https://github.com/sindresorhus/refined-github/issues/3567 but real-life links are needed to see what's going on effectively. `show-whitespace` doesn't do anything but just `observe` all elements via `IntersectionObserver`, which in my tests on large PRs had no effect #2737

**Comment by paterasMSFT** [comment]
I was having severe performance issues with this page myself. I removed the LastPass Chrome extension, and it resolved the issue. I found it by taking a performance snapshot while using the page like normal, and I noticed that Onloadwff.js was taking up a lot of time. A google search yielded [this](https://www.solvusoft.com/en/files/error-missing-download/js/windows/lastpass/lastpass/onloadwff-js/).

Just FYI for anyone else struggling with this.

**Comment by fregante** [comment]
Make sure this doesn't already happen without Refined GitHub as well. In some PRs the Changes tab is unusable without any extensions in Safari for example.

**Comment by xmo-odoo** [comment]
@fregante I tried capturing a profile of a very large PR (specifically odoo/odoo#94125), after having followed the suggestions of @DeividasJackus above it's still very *very* slow when "load diff"-ing, according to the profile 75% of the time was still spent in `linkifyContent` (https://share.firefox.dev/3SgIQxC).

I tried disabling a few more "linkify" options, but it didn't do anything (https://share.firefox.dev/3zlFgcD I assume the higher ratio is beause I just hit a few "load diff" and stopped the profiling once firefox let me, so the timeline is pretty much only load diff and the consequences on refined).

**Comment by xmo-odoo** [comment]
Third attempt: disabled everything which showed up as "linkify", that finally fixed it. So it looks like even when the features from the diff page are seemingly disabled, when loading large diffs on a large page `linkifyContent` running, calling `getRepo`, then finding out it has nothing to do, is sufficient to make the experience... less than ideal (in the second profile, all the runtime of `linkifyContent` is spent in `getRepo`, in `querySelector`).
