### ISSUE TITLE
Add a link to symbolic links

### ISSUE THREAD

**Issue by szepeviktor** [sindresorhus/refined-github#2276]
Currently GitHub displays symlinks as a string

![image](https://user-images.githubusercontent.com/952007/62020506-8b944580-b1c3-11e9-902f-3db365c52574.png)

Please add a link on the string to the actual file.

**Comment by fregante** [comment]
Given that we still have to wait for the file to load before detecting the synlink, this looks more like something OctoLinker can do

**Comment by fregante** [comment]
https://github.com/OctoLinker/OctoLinker/issues/414

**Comment by szepeviktor** [comment]
Thank you.

Oh no! I have to install a complete extension to have this 1 feature :(

**Comment by fregante** [comment]
> Oh no! I have to install a complete extension to have this 1 feature :(

Such is life

**Comment by fregante** [comment]
But for the time being, since it's a relatively simple feature, we can probably implement it in Refined GitHub.

PR welcome

**Comment by tonglil** [comment]
Does this still work? I'm not sure if the new code view UI broke this feature?

Also for some reason the `Symbolic Link` link itself is broken as well, missing the `/blob/$ref` in the url.
