### ISSUE TITLE
Hide "0 packages" info on repos

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2286]
"0 packages" here is useless and should be removed:

<img width="1002" alt="" src="https://user-images.githubusercontent.com/1402241/62122264-7b798480-b2ef-11e9-8a13-33f1b090e783.png">

For new repos, the same page is accessible through the Releases page if necessary.

Example URL: https://github.com/sindresorhus/refined-github

**Comment by doc-han** [comment]
can I crush this 0?

**Comment by fregante** [comment]
It’s all yours
