### ISSUE TITLE
`list-prs-for-file` feature does not provide

### ISSUE THREAD

**Issue by GROwen** [sindresorhus/refined-github#2288]
When viewing a file blob there is no list of open PRs that include changes to the file.

**URL:** https://github.com/dpc-sdp/tide_core/blob/develop/tests/behat/features/scheduled_updates.feature
**Screenshot:** ![Screen Shot 2019-07-31 at 08 13 23](https://user-images.githubusercontent.com/3916040/62169260-1b282880-b36b-11e9-8ff3-6f5c93c9bd08.png)
**Browser:** Vivaldi 2.4.1488.35 (Stable channel) (64-bit)

Expected result:
The behaviour shown in #2197 

Actual result:
See screenshot

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/62170703-62c29c00-b2fa-11e9-86a2-e697fe54afc7.png)

Working fine in chrome

**Comment by sindresorhus** [comment]
> Vivaldi 2.4.1488.35 (Stable channel) (64-bit)

Note that we don't officially support this browser. You're on your own when using Refined GitHub with it.

**Comment by GROwen** [comment]
Thanks for the quick response @sindresorhus. I tried with Firefox as well but same result.
