### ISSUE TITLE
Drop `pr-branch-auto-delete` feature

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#2289]
It was implemented by GitHub: https://github.blog/changelog/2019-07-31-automatically-delete-head-branches-of-pull-requests/

On a repository's settings page, there is now a checkbox to enable the feature:

![Screenshot_2019-07-31_13-53-31](https://user-images.githubusercontent.com/202916/62209738-b5539500-b39a-11e9-94b1-8df26037412a.png)

**Comment by fregante** [comment]
Lol that was fast!

cc @sindresorhus

**Comment by fregante** [comment]
This is good, but their feature has a few big disadvantages:

- it has to be enabled in each repo: our feature works everywhere.
- it has to be enabled by the owner: if the owner doesn't enable it, collaborators won't benefit from it.

For this, I think we should still keep it.

I wish GitHub at least enabled it by default in forks, where our feature doesn't apply.

**Comment by sindresorhus** [comment]
I agree, we should keep the feature. I have no intention of manually enabling that setting on 1000+ repos.
