### ISSUE TITLE
[regression] PR scroll header breaks to multiple lines / overlaps content

### ISSUE THREAD

**Issue by wearhere** [sindresorhus/refined-github#2291]
https://github.com/sindresorhus/refined-github/issues/2202 appears to be happening again, alas. 

With the latest Refined GitHub, 19.7.30:
![image](https://user-images.githubusercontent.com/110000/62235338-9399e400-b381-11e9-84f4-f39df077b62e.png)

Without:
![image](https://user-images.githubusercontent.com/110000/62235347-98f72e80-b381-11e9-81b6-df8aebed0a3a.png)

These screenshots show a particular commit selected but I can confirm that the bug happens on the files tab (e.g. `/pull/7418/files`) too.

**Comment by sharkykh** [comment]
Weird, I don't experience this.
Does anyone have a public PR where we can see it live?

**Comment by wearhere** [comment]
@sharkykh, sure happens to me here: https://github.com/mixmaxhq/custody/pull/79/files

![image](https://user-images.githubusercontent.com/110000/62256712-37ea4d80-b3b7-11e9-9755-7efcf38261d0.png)

I do see that it doesn’t happen for all PRs, like doesn't happen for https://github.com/mixmaxhq/custody/pull/78/files —maybe it depends on the length of the PR, that one's shorter.

**Comment by sharkykh** [comment]
I'm still not experiencing this even with your PR.
Maybe it's related to screen resolution or Windows' display scaling? I'm on 1920x1080 at 100% scaling.

**Comment by wearhere** [comment]
Hm… I'm on Chrome 75.0.3770.142 on OS X 10.14.5, with my resolution at 1680x1050 and the webpage at 100% scaling. The problem also happens for me at 1920x1200.

**Comment by jerone** [comment]
Can you check the 24em is actually applied?

![image](https://user-images.githubusercontent.com/55841/62275874-25b5f100-b443-11e9-9dcf-dc1410456c0a.png)

Any errors in the console?

**Comment by wearhere** [comment]
Thanks for your help thus far folks.

The 24em does seem to be applied and it still breaks:
![image](https://user-images.githubusercontent.com/110000/62277217-8b31bf80-b3fa-11e9-8fca-ce61edd038f2.png)

One error in the console:
![image](https://user-images.githubusercontent.com/110000/62277160-69383d00-b3fa-11e9-9e9c-b1a5c619ee2b.png)

**Comment by sharkykh** [comment]
Error is unrelated: #2292

**Comment by jerone** [comment]
> The 24em does seem to be applied and it still breaks:

So, what is your magic number for the title?

And you are not zoomed-in?

**Comment by fregante** [comment]
Can confirm, Firefox/macOS and see the issue. 23em works, but the suggestions in the previous thread still apply (shorter button)

Alternatively we could use flexbox to ensure it works for every size, but last time I tried it wouldn't shrink due to the `white-space: nowrap` needed for the ellipsis. You're welcome to try

**Comment by wearhere** [comment]
> > The 24em does seem to be applied and it still breaks:
> 
> So, what is your magic number for the title?

Do you mean, what `em` causes the problem to go away? Seems like `23em` would be fine, like @fregante writes above.

> And you are not zoomed-in?

No.

**Comment by fregante** [comment]
Additional button breaks it even more:

<img width="1028" alt="" src="https://user-images.githubusercontent.com/1402241/62343178-ec00eb00-b513-11e9-9f55-30cb56fc2712.png">

**Comment by fregante** [comment]
Additional button breaks it even more:

<img width="1028" alt="" src="https://user-images.githubusercontent.com/1402241/62343178-ec00eb00-b513-11e9-9f55-30cb56fc2712.png">

**Comment by fregante** [comment]
Again I'd suggest:

- restoring the regular dropdown
- dropping its "apply and reload"
- perhaps opening the dropdown on hover

There's already a keyboard shortcut to toggle the whitespace.

I enjoy the diff buttons being easily accessible but I prefer a non-broken site. This feature has been causing the same issue for a while

**Comment by nesl247** [comment]
Just ran into this myself. Is there a feature we can disable to fix this temporarily?

**Comment by kidonng** [comment]
@nesl247 try disable `faster-pr-diff-options` feature

**Comment by felixfbecker** [comment]
See this all the time :/

![image](https://user-images.githubusercontent.com/10532611/64185887-e280e080-ce3b-11e9-8333-c912e9391038.png)

**Comment by fregante** [comment]
I disabled this feature in PRs because its an ugly bug that many reported. Continue the discussion in #2597
