### ISSUE TITLE
`minimize-user-comment` breaks hidden comments

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2298]
1. Visit https://github.com/sindresorhus/refined-github/pull/2146
1. My first comment is hidden, but `minimize-user-comment` opens it

Gif of me reloading the page. It shows the  hidden comment being unhidden by the feature:

![](https://user-images.githubusercontent.com/1402241/62389193-5dc74c00-b589-11e9-8ea8-79e27c4e6f08.gif)

cc @notlmn

**Comment by fregante** [comment]
The current hijacking of the GitHub's hidden comments also causes the "Unhide" menu item to appear in comments that the feature hid and viceversa:

<img width="785" alt="" src="https://user-images.githubusercontent.com/1402241/62389727-c3680800-b58a-11e9-8f4d-601bfe9cd9e7.png">

I think we should move away from these:

https://github.com/sindresorhus/refined-github/blob/7db0c217842e3eb05a38aefd97743b7f0ea9963e/source/features/minimize-user-comments.tsx#L30-L32

and just hide the comments with `[hidden]` and our own UI (a simple icon placed by the username, for example):

![](https://user-images.githubusercontent.com/1402241/62390267-10001300-b58c-11e9-9c76-eb4c63398b36.gif)

```js
// Pseudo code used for that
$('.timeline-comment-header').addEventListener('click', 
	e => event.currentTarget.nextElementSibling.toggleAttribute('hidden')
)
```

**Comment by notlmn** [comment]
It ain't a feature implemented by me if it ain't broke.

------------------

> hide the comments with `[hidden]` and our own UI (a simple icon placed by the username

That makes sense, will try to whip up something in the meanwhile using https://octicons.github.com/icon/eye/ for the icon.

**Comment by fregante** [comment]
We all write bugs 😃

**Comment by fregante** [comment]
I think this icon would make more sense as a muted/ignored/minimized **status,** but we need more of a toggle, so perhaps a simple chevron-right should work. On the left of the username

**Comment by mgatespot** [comment]
any update? really need this feature
