### ISSUE TITLE
Webpack: Dynamic `runtimeValue`

### ISSUE THREAD

**Issue by sharkykh** [sindresorhus/refined-github#2299]
(Meta, Suggestion)

https://github.com/sindresorhus/refined-github/blob/8122efcb50393092f7c0534c458fe06e2ac9e30c/webpack.config.ts#L94-L103

It's undocumented, but you can use `true` as the second parameter to re-evaluate the callback with every file change:
https://github.com/webpack/webpack/pull/8267

It would need to be something like this, though:

<details>
<summary>Code changes</summary>

https://github.com/sindresorhus/refined-github/blob/8122efcb50393092f7c0534c458fe06e2ac9e30c/webpack.config.ts#L39-L41
to =>
```ts
function getFeatures(): string[] {
	return readdirSync(path.join(__dirname, 'source/features'))
		.filter(filename => filename.endsWith('.tsx'))
		.map(filename => filename.replace('.tsx', ''));
}
```
and
https://github.com/sindresorhus/refined-github/blob/8122efcb50393092f7c0534c458fe06e2ac9e30c/webpack.config.ts#L95-L97
to =>
```ts
// Passing `true` as the second argument makes these values dynamic — so every file change will update their value.
// @ts-ignore
__featuresList__: webpack.DefinePlugin.runtimeValue(() => {
	return JSON.stringify(getFeatures());
}, true),
// @ts-ignore
__featuresInfo__: webpack.DefinePlugin.runtimeValue(() => {
	return JSON.stringify(getFeatures().map(parseFeatureDetails));
}, true),
```
</details>

**But there is the question of performance - I don't know how much this affects it.**

**Comment by fregante** [comment]
> **But there is the question of performance - I don't know how much this affects it.**

There's only one way to find out:
```js
try {
	console.time()
	return JSON.stringify(getFeatures().map(parseFeatureDetails));
} finally {
	console.timeEnd()
}

**Comment by sharkykh** [comment]
Thanks. It looks like 7-12 ms.

**Comment by fregante** [comment]
Sounds fine
