### ISSUE TITLE
Show expanded issue/PR preview when hovering over an issue/PR tag in 

### ISSUE THREAD

**Issue by gilbitron** [sindresorhus/refined-github#230]
Currently in issue/PR comments tags to other issues/PRs (e.g. #123) get linked. It would be cool if when you hovered over the link it showed an expanded tooltip with the issue title + description (or some kind of summary of the issue).

**Comment by paulmolluzzo** [comment]
Like this? https://github.com/Justineo/github-hovercard

**Comment by gilbitron** [comment]
Yes that's what I had in mind :)

**Comment by gilbitron** [comment]
Yes that's what I had in mind 😄

**Comment by paulmolluzzo** [comment]
OK, closing as solved by a different extension then. :)
