### ISSUE TITLE
show-whitespace can't be disabled for gists

### ISSUE THREAD

**Issue by anowlcalledjosh** [sindresorhus/refined-github#2300]
I have the show-whitespace feature disabled, but whitespace is still shown in gists.

Example: https://gist.github.com/trueadm/17beb64288e30192f3aa29cad0218067

![image](https://user-images.githubusercontent.com/9433472/62413139-23e75b80-b604-11e9-95d6-2a3ba777775f.png)

I have verified that disabling the extension stops whitespace being shown.

**Comment by fregante** [comment]
Indeed, this is due to #2293. Options are not being considered on gist.github.com
Fixing

**Comment by fregante** [comment]
A fix will be published in ~10 hours
