### ISSUE TITLE
Options can no longer be disabled for custom domains

### ISSUE THREAD

**Issue by Xapphire13** [sindresorhus/refined-github#2304]
After a small amount of digging I think it's related to https://github.com/sindresorhus/refined-github/commit/703cc571f62610ff25fd8a624bc8694387dc841b.

Options are successfully disabled for github.com, but the on/off state is ignored for custom domains.

![image](https://user-images.githubusercontent.com/3392349/62498148-144a4d00-b793-11e9-8e0a-4b2c61525dc1.png)

**All of the above are `true`, despite my config looking like:**

![image](https://user-images.githubusercontent.com/3392349/62498182-2fb55800-b793-11e9-9790-49a0f0619c59.png)

I have also tried selecting and configuring both github.com and custom domains in the drop down, to no avail.

**Comment by fregante** [comment]
Thanks for the report! I broke it in 9a6c65ae
