### ISSUE TITLE
`deprioritize-marketplace-link` broken on Enterprise

### ISSUE THREAD

**Issue by MartonEstok** [sindresorhus/refined-github#2308]
URL: Company hosted GitHub enterprise

Looks like `Line 10` in `refined-github/source/features/deprioritize-marketplace-link.tsx` is accessing undefined returned by the selector `'.Header-link[href="/marketplace"]'`.

Probably because Enterprise edition doesn't have a marketplace link.

`document.querySelector('.Header-link[href="/marketplace"]')` also returns `null` when ran manually.

This is `GitHub Enterprise Server 2.16.12`.

Issue occurs even if I disable the rule in the extension settings.

![image](https://user-images.githubusercontent.com/11502444/62523278-b883d080-b833-11e9-80cf-99d45d035d2b.png)

**Comment by fregante** [comment]
This just need a `exclude:[isEnterprise()]`

> Issue occurs even if I disable the rule in the extension settings.

That's #2304

**Comment by fregante** [comment]
Fixed by https://github.com/sindresorhus/refined-github/pull/2353
