### ISSUE TITLE
Provide a quick option to go back from the search results page to the project page

### ISSUE THREAD

**Issue by jdtzmn** [sindresorhus/refined-github#2309]
For example, when at [this repo's search page](https://github.com/sindresorhus/refined-github/search?q=example+search&unscoped_q=example+search), I would ideally like to be able to click a button to go back to the [project home](https://github.com/sindresorhus/refined-github) or maybe even just hit ESC.

One might also consider whether it makes more sense to go to the last viewed page instead of the project home page 🤔.

Example URL: https://github.com/<user\>/\<project\>/search

**Comment by fregante** [comment]
The "last viewed page" is already in the browser’s back button.

The link to the project home is already there.

<img width="1025" alt="Screenshot 2019-08-07 at 02 57 36" src="https://user-images.githubusercontent.com/1402241/62573000-30e3a380-b8bf-11e9-9afb-20c9f65671d0.png">

**Comment by jdtzmn** [comment]
I realized that after, however I would still love to be able to press `esc` and have it go back.

**Comment by fregante** [comment]
`esc` doesn't make sense in this case because it's not a modal. You can press `backspace` if your browser supports it (Chrome needs an extension)
