### ISSUE TITLE
`sticky-discussion-sidebar` feature broken

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#2313]
The `.discussion-sidebar` class doesn't exist anymore, will need to use `#partial-discussion-sidebar` to target the sidebar element instead.

![image](https://user-images.githubusercontent.com/37769974/62704463-14538280-ba09-11e9-8015-05687784758d.png)

**Comment by fregante** [comment]
This was changed last week, did they change class again? 🤔

**Comment by notlmn** [comment]
That class existed on the element with the id mentioned above, but we always used the class to target the sidebar since the feature was originally introduced. It doesn't exist anymore on the page.

I think they're dropping classes for all the elements that already have an id. If that's the case, we should expect some more broken features.

**Comment by sharkykh** [comment]
Hi.
Actually, it looks like they made our job easier with this clean-up.
I will address this issue now.
