### ISSUE TITLE
[Bug] Repo title and buttons in the wrong line

### ISSUE THREAD

**Issue by linhuiw** [sindresorhus/refined-github#2316]
Link: https://github.com/amejiarosario/dsa.js-data-structures-algorithms-javascript

❌ With refined-github screenshot
![image](https://user-images.githubusercontent.com/722603/62751874-eec18a00-ba97-11e9-9102-61e96b917be4.png)

👌🏻No refined-github screenshot
![image](https://user-images.githubusercontent.com/722603/62751931-23cddc80-ba98-11e9-85cf-c78116a9286c.png)

**Comment by fregante** [comment]
“Used by” is added by GitHub. Reload and you’ll find out it behaves the same even without Refined GitHub. 

If anything, Refined GitHub makes the Fork and Watch buttons smaller so this should happen less often
