### ISSUE TITLE
`ci-link`: hide duplicate status icon

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#2317]
![1](https://user-images.githubusercontent.com/44045911/62791420-b35aa600-baff-11e9-8ad6-671b01e3c067.png)

It seems that lately GitHub added a build status icon on the repo homepage and commit details page for *repos using GitHub Actions*. The latter is fine, while the former duplicates Refined GitHub's `ci-link` feature.
I think it's better to hide one of them, GitHub's one for consistency, or Refined GitHub's one for fewer HTTP requests/DOM manipulation (though I don't care about these expenses 😂).

<details>
<summary>Off topic</summary>

![2](https://user-images.githubusercontent.com/44045911/62792031-f8cba300-bb00-11e9-97f3-706169668c33.png)

GitHub hurried this feature...

</details>

Example URL: https://github.com/zeit/now-builders

**Comment by yakov116** [comment]
@kidonng 	its only  GitHub Actions so I dont think there is a need hide it at all

**Comment by kidonng** [comment]
It's to keep the interface neat, and I think this is easy to archive (might just need to add a CSS rule).

**Comment by fregante** [comment]
I'm not seeing it, are you using an extension? Your style is different

**Comment by kidonng** [comment]
I'm using a user style written by myself 😀 I do have some other GitHub related extensions but I don't think they will add the icon.
I disabled Refined GitHub and found the icon still exists, without a `rgh-xxx` class, so I believe it is from GitHub.
But now I'm not seeing it either, maybe GitHub is doing A/B testing. We can close this for now and wait for it to roll out to the public if you like.

**Comment by yakov116** [comment]
@fregante checkout bootstrap

**Comment by fregante** [comment]
>  I disabled Refined GitHub and found the icon still exists, without custom classes like `rgh-xxx`, so I believe it is from GitHub.

`rgh` is `Refined GitHub`, I suppose you're talking about the icon still being after the repo title after you disable the extension. It's still there because you have to fully refresh the page to let the JavaScript _unload_

I like the 2 new positions you're showing me, they make sense and I hope to see them soon.

**Comment by kidonng** [comment]
> `rgh` is `Refined GitHub`, I suppose you're talking about the icon still being after the repo title after you disable the extension. It's still there because you have to fully refresh the page to let the JavaScript _unload_

Of course I've refreshed 😄 I was saying that the icon looks ordinary thus it is from GitHub.

> I like the 2 new positions you're showing me, they make sense and I hope to see them soon.

Me too, and hope they don't limit it to repos using GitHub Actions only.

**Comment by fregante** [comment]
> I was saying that the icon looks ordinary thus it is from GitHub.

Sorry I misread 🤦‍♂️

**Comment by yakov116** [comment]
@fregante 	looks like they added it for all ci's!

**Comment by fregante** [comment]
I like their position and we should keep them there, but at the same time I also like to be able to see whether a project is failing from any page.

The only change I'd suggest here is to revert #1502 so our icon only ever points to the default branch

**Comment by kidonng** [comment]
Just wonder if we can add something like:

```css
.rgh-repo-root .rgh-ci-link {
  display: none;
}
```

```js
document.body.classList.toggle('rgh-repo-root', isRepoRoot())
```

**Comment by busches** [comment]
@kidonng if you want to hide the icons added by RGH, you could disable the feature or use the existing class you listed.

```
.rgh-ci-link {
  display: none;
}
```

No need to add a new class or to add a user script, RGH supports overriding styles already.

**Comment by kidonng** [comment]
@busches I agree with what @fregante said:

> At the same time I also like to be able to see whether a project is failing from any page.

From the beginning of this issue I'm not going to disable this useful feature 😁

**Comment by busches** [comment]
@kidonng sure and if you want to hide everything with `.rgh-ci-link` then you can do that, without needing an extra class on the body.

**Comment by kidonng** [comment]
Oh... to make it clear, I just want to hide one of the icons **on repo's root**, and the code above is just an example.

**Comment by fregante** [comment]
> I just want to hide one of the icons **on repo's root**

It's not a terrible idea... but I think it's best to always show it there just not to break expectations.

**Comment by kidonng** [comment]
This seems more like a personal preference to me now... maybe I just got used to seeing both of them 🤣 closing this for the moment.

Just in case someone needs it, here's a quick solution with Stylus:

```css
@-moz-document regexp("https://github.com/[^/]+/[^/]+$") {
  .rgh-ci-link {
    display: none;
  }
}
```
