### ISSUE TITLE
Potentially destructive actions should be opt-in and easily identifiable in settings

### ISSUE THREAD

**Issue by ChadLevy** [sindresorhus/refined-github#2318]
I found that branches were automatically being deleted after pull requests. This causes conflicts with my project's workflow and is nothing something I wish to do.

Github has the option to automatically delete branches after pull requests are closed. I double checked to make sure this option was not enabled. It was not. Then, I looked in Refined Github's settings for this option and found it, automatically enabled, 2/3 of the way down a large list of other options:

![image](https://user-images.githubusercontent.com/909190/62808715-7e7a2f00-babe-11e9-864b-f4a2df835d28.png)

I believe potentially destructive actions should be opt-in and easily identifiable in settings. While restoring a branch is trivial, there is still a potential for data loss and as such, whether or not this is done should be left up to the user.

**Comment by sindresorhus** [comment]
> there is still a potential for data loss

What is the potential data loss? You can restore any deleted branch.

**Comment by ChadLevy** [comment]
I was under the impression there was a time limit to restoring deleted branches and beyond that limit Github support would need to be involved. It looks like there is no time limit, so you're right, there is no potential for data loss given you can restore at any time.
