### ISSUE TITLE
Make Clone/Download shown at all times

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-github#232]
GitHub made the Clone/Download button require two clicks to download or copy the URL to the repo. It'd be better if there were just two buttons (or a split button) that you could click to directly download or copy the URL to the repo. That's how it used to be and I don't know why they changed it.

![do not like](https://cloud.githubusercontent.com/assets/737065/15560561/c0993be6-22ba-11e6-8954-cc8a42f997f0.png)

**Comment by jamestalmage** [comment]
Why not just two buttons "clone" and "download"?

Clone should just copy to the clipboard and default to `ssh` (tiny downward carrot for HTTPS). Download just downloads.

--

Or maybe better yet. Just put a copy icon to the right of clone/download. Clone/download is unchanged, but there's a shortcut for copying SSH to clipboard.

--

Also, it would be great to make the button always default to SSH.

On the rare occasion I switch it to HTTPS, I always forget to switch it back.

**Comment by paulmolluzzo** [comment]
Yeah @jamestalmage we have pretty much the same ideas.

> Why not just two buttons "clone" and "download"?
> 
> Clone should just copy to the clipboard and default to ssh (tiny downward carrot for HTTPS). Download just downloads.

This is exactly what I mean, I think I just worded it poorly. From a style perspective a split button with the copy icon as one of the "splits" could be perfect.

> Just put a copy icon to the right of clone/download

That could totally work, except for the SSH/HTTPS switch part. That has to be handled somehow.

> Also, it would be great to make the button always default to SSH.
> 
> On the rare occasion I switch it to HTTPS, I always forget to switch it back.

I'm in the same boat, but there are probably a fair number of HTTPS-folk. (If your work computer blocks SSH connections or whatever, IDK.)

**Comment by jamestalmage** [comment]
If SSH connections are blocked, you can't push, so it wouldn't be a dev machine.

I only ever use it when copying to a CI server/ Windows VM that I will never push from.

**Comment by sindresorhus** [comment]
I personally just copy the URL from the URL bar and use it for cloning. For example:

```
$ git clone https://github.com/sindresorhus/refined-github
```

You can't push then, but I never push to repos I clone randomly anyways.

-

> If SSH connections are blocked, you can't push, so it wouldn't be a dev machine.

Not true: https://help.github.com/articles/which-remote-url-should-i-use/#cloning-with-https-urls-recommended

**Comment by hkdobrev** [comment]
@sindresorhus I think this works only because you're using `hub`. Without hub shouldn't the URL end in `.git`?

**Comment by sindresorhus** [comment]
@hkdobrev No, GitHub redirect it to `.git` when it's a clone. Works with plain `git`.

**Comment by hkdobrev** [comment]
@sindresorhus Nice! I thought the redirect was only the other way around - `.git` URL to normal when pasting it in the browser.

**Comment by jacobbearden** [comment]
What is the consensus on this?

Swap the "Clone or download" dropdown for both a Download and Copy SSH button?

**Comment by sindresorhus** [comment]
I vote to just close this. As already commented, you can just copy-paste the browser URL.
