### ISSUE TITLE
Linkified symbolic link applies only to first word (due to `show-whitespace`)

### ISSUE THREAD

**Issue by kevinvanrijn** [sindresorhus/refined-github#2321]
When the path of a symlink includes spaces a clickable link is applied only the the first "word" of that symlink.

The link itself points to the correct location still.

Example: https://github.com/EIGHTFINITE/jdownloader-portable/blob/db9daffce2c7c243a1523080def7955c2cfd873c/LICENSE.txt

![Image Example](https://user-images.githubusercontent.com/6368561/62860408-68f44780-bd00-11e9-9450-43766da63a90.png)

**Comment by fregante** [comment]
It looks like it's conflicting with `show-whitespace`; disabling this feature fixes it.
