### ISSUE TITLE
Show lines changed for current commit

### ISSUE THREAD

**Issue by dorian-marchal** [sindresorhus/refined-github#2326]
When I'm on a specific commit of a pull request, I'd like to see the number of lines changed in this commit, only.

Currently, the total number of lines changed in the whole pull request is shown: ![Screenshot from 2019-08-13 09-52-59](https://user-images.githubusercontent.com/6225979/62924345-2f7b1500-bdb0-11e9-9750-404cec38b100.png)

Example URL: [sindresorhus/refined-github#2182/commits/7e8bb264c](https://github.com/sindresorhus/refined-github/pull/2182/commits/7e8bb264cda190a5ce2e09e51196cb8f4b230696)

This number of lines changed could also appear on [the commit page](https://github.com/sindresorhus/refined-github/commit/7e8bb264cda190a5ce2e09e51196cb8f4b230696) (outside of the pull request).

**Comment by sindresorhus** [comment]
Yeah, makes sense. I'm surprised GitHub doesn't already do this.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by fregante** [comment]
This one should be relatively simple, the data is available on the API. However I'm not sure of the logic used to fill those green blocks.

**Comment by yakov116** [comment]
@fregante I looked into it. Added in the blocks I think is something beyond the extention to add. We would have to figure out the pattern github uses.

I have another issue, not really related to this feature per say.
We added the tag feature, merge commits, not we want to add this one.

For each feature we are make a new request for the same commit. Is there any way we can combine the api requests. For 2 reasons:

1.  For a list of 50 commits, it's 150 requests (if not more)
2. There is no need to wait for 3 requests when it's all waiting for the same info.

Should I open a new issue?

**Comment by fregante** [comment]
This feature request is about showing this info on the `isCommit` and `isPRCommit` pages, not `isCommitList`. The features you mention don’t have any overlap

**Comment by yakov116** [comment]
I'm lost... doesn't github show the amount on the commit??

**Comment by fregante** [comment]
What you do with the PR specifically is up to you, as long as the final feature only includes  this information on `isCommit` and not on the lists.

**Comment by yakov116** [comment]
Ok I rewrote most of the code (Did not push yet)

We want to replace GitHub's header or add a new one?
