### ISSUE TITLE
Fix PR commit links on submission (GitHub’s bug)

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2327]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2418.81%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2327)

GitHub has had this really annoying bug that changes PR commit links (e.g. [this one](https://github.com/sindresorhus/refined-github/pull/3/commits/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb)) into non-PR-related links like this: https://github.com/sindresorhus/refined-github/commit/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb

This only happens to auto-linked URLS like `https://...etc` and not to `[text](https://...etc)`

We can't fix these links **after** they've been submitted but we can do it **before** submission.

---

This feature should should:

1. Listen to comment form submissions
2. Detect plain URLs to PR commits (and skip markdown links)
3. Replace plain urls with identical markdown links, like `[https://...etc](https://...etc)`

Step 2 is easy to implement in most places (e.g. find a URL surrounded by spaces) but it can be tripped with content like `[this url https://... is the problem](https://...)` (which... probably does not happen)

Test comment content:

```
https://github.com/sindresorhus/refined-github/pull/3/commits/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $18.81)

- [<img src='https://avatars3.githubusercontent.com/u/1402241?v=4' alt='fregante' width=24 height=24> fregante](https://issuehunt.io/u/fregante) ($18.81)

### Submitted pull Requests
- [#3085 Added feature to stop GH from replacing Pr links to commit links](https://issuehunt.io/r/sindresorhus/refined-github/pull/3085)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by fregante** [comment]
cc @lukehefson just in case he can fix this internally.

**Comment by lukehefson** [comment]
Thanks for the ping @fregante! Did you submit a bug report to our Support team? And if so, do you think you could DM (twitter, email) me the ticket reference?

**Comment by max-arias** [comment]
looks like this was solved?

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/3/commits/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb

**Comment by fregante** [comment]
Nope. I just posted `https://github.com/sindresorhus/refined-github/pull/3/commits/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb` but the link points to `https://github.com/sindresorhus/refined-github/commit/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb

**Comment by max-arias** [comment]
I'll give this a shot!

**Comment by max-arias** [comment]
Pr up: https://github.com/sindresorhus/refined-github/pull/3085

**Comment by wearhere** [comment]
This is really cool—the find of feature that makes me proud to use Refined GitHub. Nice work everyone. The styling of the warning is especially nice.

**Comment by fregante** [comment]
Glad you like it, this bug annoyed me for a long time.

Some fixes to this feature are coming in #3223

**Comment by mig4** [comment]
This doesn't really explain why GitHub changing the link is a problem. I.e. what is wrong with the link they transform the original into?

**Comment by Maxim-Mazurok** [comment]
Great feature! Minor inconsistency with GitHub:

When publishing a link in another repo, it should be like this:

> Maxim-Mazurok/google-api-typings-generator@`429318c`

and not like this:

> `429318c`

**Comment by fregante** [comment]
> This doesn't really explain why GitHub changing the link is a problem. I.e. what is wrong with the link they transform the original into?

The difference is subtle, but you can open the 2 links in the first paragraph of this PR and compare them. 

```js
What the user pastes:
// https://github.com/sindresorhus/refined-github/pull/3/commits/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb

What GitHub displays:
// https://github.com/sindresorhus/refined-github/commit/cb44a4eb8cd5c66def3dc26dca0f386645fa29bb
```

In short: The correct link shows the commit **on the PR page**, while GitHub drops this piece of information, showing a link to the plain commit, without any connection to the PR. 

@Maxim-Mazurok I opened an issue about that, thanks!

**Comment by mig4** [comment]
So if you want to link to commit, it's fine to go with GitHub's version and if you want to show the commit in context of the PR then use the button to fix the link. Makes sense.

I wondered if they do that because the link in PR context can become stale, like if the commit is rebased, but I guess the direct commit link could also then become stale after GC.

Anyway, thanks for the feature and the explanation.
