### ISSUE TITLE
Cannot click 're-run all checks' on Actions page

### ISSUE THREAD

**Issue by paambaati** [sindresorhus/refined-github#2328]
If you're on the latest beta of GitHub Actions, there's a drop-down for re-running all checks that you can't click.

I can confirm that it works fine on Firefox and in Chrome after I've disabled the extension.

Example URL — https://github.com/paambaati/websight/pull/10/checks?check_run_id=193115347

Screenshot of the dropdown in question (from Firefox)

<img width="1272" alt="Screenshot 2019-08-14 at 2 41 10 PM" src="https://user-images.githubusercontent.com/5381764/63009252-bd82f880-bea1-11e9-9bf2-3413b2d3279a.png">

**CSS selector**
```
details.dropdown:nth-child(1) > summary:nth-child(1)
```

**Markup**
```html
<div>
          <details class="dropdown details-reset details-overlay d-inline-block ml-4 mt-n1" open="">
            <summary class="btn btn-sm" aria-haspopup="true">
              <svg></svg>
              Re-run checks
              <div class="dropdown-caret"></div>
            </summary>

            <template id="js-check-suite-rerequest-form-success">
              <div class="flash flash-full flash-notice">
  <div class="container">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg></svg>
    </button>
    
                You have successfully requested checks from GitHub Actions.

  </div>
</div>
            </template>

            <template id="js-check-suite-rerequest-form-error">
              <div class="flash flash-full flash-error">
  <div class="container">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg></svg>
    </button>
    
                There was a problem requesting checks from GitHub Actions.

  </div>
</div>
            </template>

            <ul class="dropdown-menu dropdown-menu-sw" style="width: 170px">
              <li>
              </li>
              <li>
                    <input type="hidden" name="only_failed_check_runs" value="false">
                    <button class="dropdown-item btn-link" type="submit">
                      Re-run all checks
                    </button>
</form>              </li>
            </ul>
          </details>

    </div>
```

**Comment by fregante** [comment]
What's its container? Is it inside `.pr-toolbar`?

**Comment by paambaati** [comment]
@fregante It is, yes.

**Comment by notlmn** [comment]
Had a chance to test this, it looks like [`close-out-of-view-modals`](https://github.com/sindresorhus/refined-github/blob/master/source/features/close-out-of-view-modals.tsx) is the culprit.

![image](https://user-images.githubusercontent.com/37769974/63180311-a0018a80-c06b-11e9-9862-29a02d36eb00.png)

GitHub uses some `<template>` tags for internal UI use, that which https://github.com/sindresorhus/refined-github/blob/372e282cfd2e207704e99c4b4538e110b4a4d1a4/source/features/close-out-of-view-modals.tsx#L16 picksup, `<template>` tags are `display: none` by default, causing them to report as "out of view" in this case.

![image](https://user-images.githubusercontent.com/37769974/63180554-29b15800-c06c-11e9-884d-94bbafab79d8.png)

---------------

Out of context, GitHub should provide an option to re-run tests (individually if possible) for recent comments and PR that pass too, not just for PRs that have failed steps.

I don't who to ping about this, so pinging @lukehefson as a start.

**Comment by fregante** [comment]
Not GitHub’s fault here, the feature should look for other siblings of `summary`, I suppose, that are not `template`

PR welcome
