### ISSUE TITLE
Reaction Avatars should update on "remote" changes

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-github#233]
If you're on an issue/PR and there are reactions to comments the avatars will disappear if someone else reacts. There should be a Mutation Observer or something to track those elements and re-add the avatars on an update.

It's actually hiding the avatars, so _something_ is happening.

**Comment by DrewML** [comment]
Rather than a mutation observer, I think we can just leverage the fact that GitHub's JS emits events on change.

```javascript
$(document).on('socket:message', (e, data) => {
	// data will be an object of the format:
	// {timestamp: 1464274232, reason: "reaction #1209345 updated"}
});
```

**Comment by paulmolluzzo** [comment]
> We'd know to go run our updates on reactions anytime the reason prop mentions a reaction has been updated

We can just run them all or we can run just the one comment that was updated, but that latter option is not currently supported.

**Comment by AshikNesin** [comment]
I'll work on it this week :)

**Comment by bfred-it** [comment]
Would `$(document).on('socket:message')` actually work? I got no events when testing it for #132, even though I saw GH's own code triggering the event.

**Comment by AshikNesin** [comment]
@bfred-it  I also tried `$(document).on('socket:message')` but it didn't work :(

**Comment by bfred-it** [comment]
I _thiiiink_ this happens because jQuery doesn't trigger real DOM events but it just short-circuits within its own event Map. So unless we use GH's own jQuery (we can't) we probably won't be able to listen to them.

Pinging jQuery experts around the world. It'd be nice to plug into GH's own events rather than rely on MutationObservers

**Comment by bfred-it** [comment]
I'm reopening this issue hoping for a proper resolution. My fix doesn't work all the time and especially doesn't work on ajax-loaded comments + their new reactions.
