### ISSUE TITLE
`clean-discussion-sidebar` isn't re-applied after changes to the sidebar

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2333]
1. Visit an issue
2. Post a comment or add a label
3. Notice that the sidebar is _dirty_ again

![asd](https://user-images.githubusercontent.com/1402241/63040838-90aa0200-bef0-11e9-9f05-2538a58c8f36.gif)

There should either be an even listener on the ajaxed element (it's probably called `socket:message`) or a `MutationObserver`

**Comment by sharkykh** [comment]
It tries to observe `.discussion-sidebar`. I wonder if simply changing it to observe `#partial-discussion-sidebar` instead would be enough to fix it.

**Comment by fregante** [comment]
> ~I wonder if simply changing it to observe `#partial-discussion-sidebar` instead would be enough to fix it.~
> Looks like the answer is no...

So in that case this also won't work? https://github.com/sindresorhus/refined-github/pull/2336

**Comment by sharkykh** [comment]
Good point.
I just tried #2336 again, and after it updates the sidebar, the button is gone.
That's unfortunate.

**Comment by sharkykh** [comment]
FYI, this works for #2336.
```ts
		observeEl('#discussion_bucket > :last-child', addMarkUnreadButton);
```
However, [I remembered this conversation](https://github.com/sindresorhus/refined-github/pull/2314/files/43d1de3702843b21bb1b3937ce1b1f2e809f6171#r312140123).
