### ISSUE TITLE
`Mark as unread` button is missing

### ISSUE THREAD

**Issue by ilyam8** [sindresorhus/refined-github#2335]
SSIA

 - `chromium` Version 76.0.3809.100 (Official Build) Arch Linux (64-bit)
 - `refined-github` 19.8.14

![2019-08-15-095955_3840x2160_scrot](https://user-images.githubusercontent.com/22274335/63078227-86fdba00-bf43-11e9-9250-32117058925b.png)

___
The feature is very important for me, i use it every day, please fix asap :pray:

**Comment by sharkykh** [comment]
I'll take this on.
