### ISSUE TITLE
"Open All" button from `batch-open-issues` doesn't work

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#2338]
The `batch-open-issues` feature adds a "Open All" button on pages like https://github.com/issues?q=org%3Aprisma+milestone%3A%22Preview+7%22+is%3Aopen

![image](https://user-images.githubusercontent.com/183673/63093920-3304cc80-bf67-11e9-8b47-f547e87d195b.png)

That would be _exactly_ what I need in a current workflow I am using, but clicking the button unfortunately doesn't do anything for me there.

Here is the code: https://github.com/sindresorhus/refined-github/blob/2e4a24d3957c205c7bc49525c69e1fa08593d2ca/source/features/batch-open-issues.tsx

Am I missing something here or is this really broken?

**Comment by kidonng** [comment]
I want to take this one 😀
