### ISSUE TITLE
Watch button dropdown not on top of issue details.

### ISSUE THREAD

**Issue by velddev** [sindresorhus/refined-github#2339]
Hey there, Whenever I hover over the watch button, there's a issue with the z-ordering of the panels. This does not happen without the extension on my side.

I'm running chrome v76.0.3809.100 on macOS Mojave 10.14.5

![image](https://user-images.githubusercontent.com/13852840/63096103-47e45e80-bf6d-11e9-8215-f06271a6cba7.png)

**Comment by fregante** [comment]
This is due to f8c2fab4cfd8f85f19552a897f1a6df49ea441d9
