### ISSUE TITLE
Empty comment field displays unnecessary "please fill out this field" tooltip when hovered over in Firefox

### ISSUE THREAD

**Issue by Luke18033** [sindresorhus/refined-github#2349]
As stated in the title, this tooltip appears when mousing over the comment field while it is empty. I know how issue comments work, I don't need this appearing and obscuring my text every time I go to write a comment. This is something which happens in normal GitHub, so I was hoping Refined GitHub would be able to fix it. I guess that makes this a feature request?

This only happens in Firefox as far as I can tell, which is possibly why it seems to have gone unnoticed. It's definitely a part of the site itself though, and not the browser: this message *will* appear in Chrome, but only when hovering over the issue title field, and not the comment field. In that case it's not really a problem though, since that's the default focused text box and the tooltip appears low enough that it doesn't cover the text anyway.

Here's a screenshot of the tooltip in question.
![image](https://user-images.githubusercontent.com/19228201/63220373-9c890480-c13a-11e9-98a0-d84aec51070a.png)

**Comment by kidonng** [comment]
The tip comes from [`required`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#Attributes) attribute of `<textarea>`, removing it when the comment field is empty will break GitHub's form validation and cause the comment button to be disabled.

> ...this message will appear in Chrome, but only when hovering over the issue title field, and not the comment field...

That's because the issue title field is a `<input>` with `required` attribute as well, but I have no idea why Chrome doesn't show the tip for `<textarea>`.

**Comment by fregante** [comment]
Would adding a `title=''` attribute avoid the tooltip? If so, in both browsers, this can be added as a feature. 

PR welcome

**Comment by kidonng** [comment]
@fregante Yes, works on both browsers

**Comment by Luke18033** [comment]
Not sure if I should open a new issue for this, but this now happens again in issue forms.

**Comment by Luke18033** [comment]
This has started happening again
