### ISSUE TITLE
github template repository bug

### ISSUE THREAD

**Issue by dl0312** [sindresorhus/refined-github#2350]
Recently, I made several repositories using a new feature called github template, and all the repositories made out of templates were with fork. I don't know if it was intended, but it feels so messy.

### Without refined-github
<img width="1008" alt="스크린샷 2019-08-18 오후 10 49 28" src="https://user-images.githubusercontent.com/3915393/63225404-83e81f80-c20a-11e9-928c-33c4bf5e37cc.png">

### With refined-github
<img width="1001" alt="스크린샷 2019-08-18 오후 10 45 06" src="https://user-images.githubusercontent.com/3915393/63225403-83e81f80-c20a-11e9-9f60-126c669daefc.png">

**Comment by jerone** [comment]
This is a feature called `forked-to`.
There is an PR to change it's design: https://github.com/sindresorhus/refined-github/pull/2230

**Comment by fregante** [comment]
As @jerone said it will be fixed soon
