### ISSUE TITLE
Console error in `forked-to` feature

### ISSUE THREAD

**Issue by tanmayrajani** [sindresorhus/refined-github#2355]
The following occurs on any page:
![image](https://user-images.githubusercontent.com/8295888/63320684-27851d00-c33c-11e9-946d-25cc00059ecf.png)

Looks like it is because of some DOM changes by GitHub as it's not able to find this selector: 

**`details-dialog[src*="/fork"] include-fragment`**

**Comment by jerone** [comment]
Duplicate https://github.com/sindresorhus/refined-github/issues/2334
