### ISSUE TITLE
Show associated projects/issue when listing issues

### ISSUE THREAD

**Issue by funkyremi** [sindresorhus/refined-github#2356]
It would be nice to see the projects associated to each issue when listing issues.

**Comment by sindresorhus** [comment]
I'm -0 as we have way to many features now and this doesn't seem essential.

Can you request it from GitHub itself? => support@github.com

**Comment by funkyremi** [comment]
Ok thanks, I just send an email to github.

**Comment by fregante** [comment]
Refined GitHub mostly hides projects where possible. The maintainers don’t use the feature. 

There are more appropriate extensions for this feature, like ZenHun
