### ISSUE TITLE
Bug: "More" dropdown always expanded

### ISSUE THREAD

**Issue by corysimmons** [sindresorhus/refined-github#2357]
Refined GitHub enabled on Chrome:

![image](https://user-images.githubusercontent.com/224636/63393581-b2403900-c389-11e9-9bd1-c88c2dd48360.png)

Disabled:

![image](https://user-images.githubusercontent.com/224636/63393594-bff5be80-c389-11e9-8d5a-a7d6a1b95692.png)

It just started today, and I've only noticed it does this when viewing a Repo (not other views afaik).

Clicking the dropdown, or anything, doesn't hide the dropdown. Seems like it's just stuck in this state.

**Comment by joscha** [comment]
> It just started today, and I've only noticed it does this when viewing a Repo (not other views afaik).

Also happens in pull requests and is overlaying the file tab and branch name, which is quite unfortunate:

<img width="352" alt="fix__some_dependencies_by_joscha_·_Pull_Request__64857_·_Canva_canva" src="https://user-images.githubusercontent.com/188038/63393924-a8a5e800-c400-11e9-91b1-f3267f830995.png">

**Comment by Nightfirecat** [comment]
Not a fix for the issue, but disabling `more-dropdown` removes this while it is being fixed.

**Comment by rohitkrishna094** [comment]
For anyone having trouble, you can find `more-dropdown` in the extension's settings. For chrome, just right click on the extension(refined github in this case) and click on `options`. Once there, just scroll down and you will find `more-dropdown` as Nightfirecat mentioned.

**Comment by busches** [comment]
Looks like we're on the legacy markup and they removed support for it today. We'll need to convert it to the `<details><summary>` markup you can find in the other drop downs. Most likely GHE will still need the current markup though.

**Comment by casz** [comment]
As a temporary solution, I created #2358 till we get a proper fix

**Comment by coreysnyder** [comment]
Seeing the same thing just now.

**Comment by kidonng** [comment]
@busches Nice catch! Created a fix PR.

**Comment by alerque** [comment]
Just a confirmation ... the original report states this happens on Chrome. I'm on Firefox and seeing the same thing today. The menu is stuck open whether on old or new tabs and cannot be closed.

**Comment by cocoonkid** [comment]
Same on Brave

**Comment by rajatkantinandi** [comment]
Same issue here
<img width="1204" alt="Screenshot 2019-08-21 at 4 34 09 PM" src="https://user-images.githubusercontent.com/17743895/63427023-c8a1cf80-c431-11e9-8221-bd0a3c0160a5.png">

**Comment by MRamonLeon** [comment]
Same issue here

**Comment by alerque** [comment]
Hey guys please stop with the "me too" comments unless you have something to add. I think the point is made, this is broken, we have screen shots, we have browsers it's confirmed in, it's pretty universal. Vote up the initial report if you must, but as with almost any project's Github issues, adding new comments just to say the same thing wastes a lot of people's time at attention. In case you missed it in comments there is a mitigation you can use for now and a permanent fix in the works.

**Comment by kidonng** [comment]
@busches can you pin the issue? Before a new release we need to keep people informed

**Comment by busches** [comment]
> @busches can you pin the issue? Before a new release we need to keep people informed.
> If not then we should keep this issue open

Good idea, done.

**Comment by kidonng** [comment]
@busches Let's also add the following line at the top of the issue description:

> **NOTE:** A new version (19.8.21) has already been released, please restart your browser and wait for the plugin to update.
> For Chrome users, you can go to `chrome://extensions/`, toggle on "developer mode" on the top right corner, and click the "Update" button to immediately receive the update.

**Comment by StormPooper** [comment]
Firefox users can hit 'Check for Updates' in Manage Add-ons too (at least, it worked for me): 
![image](https://user-images.githubusercontent.com/1657182/63445197-dbb3a000-c42f-11e9-87ee-daebb6ab92bb.png)

**Comment by wachunei** [comment]
Chrome users: v19.8.21 includes the fix, you can force update by using developer tools and clicking on update.

<img width="684" alt="Screen Shot 2019-08-21 at 12 49 07 PM" src="https://user-images.githubusercontent.com/1024246/63451397-19093500-c412-11e9-8625-472529da31eb.png">

**Comment by corysimmons** [comment]
Thanks for quick fix 👌

**Comment by grahamperrin** [comment]
<https://github.com/sindresorhus/refined-github/issues/2357#issuecomment-523254108>: 

> … scroll down and you will find `more-dropdown` …

:+1: – thanks – and for Waterfox Classic users of version 19.1.31.1822, which requires a manual entry: 

![image](https://user-images.githubusercontent.com/192271/63493221-0561db00-c4b3-11e9-9c82-82e741e01619.png)

**Comment by cocoonkid** [comment]
Can confirm brave and chrome fixed. thanks a bunch!

**Comment by IzzySoft** [comment]
For users on classic Waterfox, where the menu doesn't open anymore, here's an easy fix per UserStyle:

```css
@namespace url(http://www.w3.org/1999/xhtml);

@-moz-document domain("github.com") {
  .btn-link.reponav-item:hover + .dropdown-menu-content.js-menu-content, .dropdown-menu-content.js-menu-content:hover { display:block !important }
  .dropdown-menu-content.js-menu-content { display:none; }
}
```

@busches maybe that could be integrated with refined-github?

**Comment by busches** [comment]
@IzzySoft, that seems like a bandaid solution. We're mimicking the native GH dropdowns and shouldn't need extra classes, assuming the native ones work without that fix. If the native ones do work and ours don't, that's the fix I'd want, which should be markup, not extra styling.

**Comment by IzzySoft** [comment]
Understood. Just thought to share what worked for me (might still be useful to other affected users then).

I still need this CSS fix, otherwise I cannot open that menu (where before it always remained open, it now always remains closed). For reference: I'm using the latest Waterfox Classic (56.2.14) on Linux Mint.

**Comment by IzzySoft** [comment]
Besides: where can one get it for Waterfox Classic now when installing fresh? AMO only has versions for FF61+, WF Classic would be FF57.

**Comment by grahamperrin** [comment]
> … where can one get it for Waterfox Classic …

https://redd.it/aw8rqm

**Comment by IzzySoft** [comment]
Thanks! Maybe adding that link to the Readme here (in the "Install" section), to make it easier to find?

**Comment by grahamperrin** [comment]
I would hesitate. From the Reddit post, with added emphasis: 

> Version 19.1.31.1822 appears to be the last version that will show *Jump to bottom* in GitHub issues with Waterfox 56.2.7.1. Direct link: 
> 
> * https://addons.mozilla.org/firefox/downloads/file/1668887/refined_github-19.1.31.1822-an+fx.xpi
> 
> **Any number of other features may be incompatible** – [all recent versions](https://addons.mozilla.org/addon/refined-github-/versions/) for desktop are for *Firefox 61.0 and later* – I just noticed the disappearance (of Jump to bottom) when I updated too far.

**Comment by IzzySoft** [comment]
I'm running 18.12.22.1803 here, which still works – but receive no updates anymore. Afraid that version is no longer available at AMO, though. Maybe providing it (or any other APK you think should be used with Waterfox) at a separate URL – e.g. attach it to its tag/release here at Github – and link there?

**Comment by maniator** [comment]
This is happening again and I am not sure what to do as I cannot disable more options...


This is in Chrome
