### ISSUE TITLE
copy-on-y.js is too much

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/refined-github#236]
if you type a y into this response, you lose focus and it's very irritating when trying to type up this issue.

The scope of this functionality needs to be limited to when you are not actively inside a textbox.

cc @DrewML

**Comment by jamestalmage** [comment]
Argh. This has been driving me crazy. I've definitely noticed the loss of focus. Didn't put it together with `y`.

**Comment by paulmolluzzo** [comment]
This should have a test to make sure you're not inside a `textarea` or `input`.

**Comment by DrewML** [comment]
![](https://media.giphy.com/media/11tIB893VLShXi/giphy.gif).

We've got `Good for Beginner` on this, but I'll probably just tackle this tonight since it's causing people trouble.

**Comment by DrewML** [comment]
Ah, ok - so this isn't an issue of whether or not you're inside a text area. This is an issue with the event handler only being bound on "single file" pages, but then not removed when you navigate elsewhere (text area will never be present on a "single file" page).

Will submit a PR shortly.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/refined-github/pull/238.
