### ISSUE TITLE
`releases-tab` does not work without `more-dropdown`

### ISSUE THREAD

**Issue by sharkykh** [sindresorhus/refined-github#2361]
When `more-dropdown` is disabled or have failed to initialize due to an error,
`releases-tab` fails to inject.
It's not really a bug, but rather an enhancement request - to make `releases-tab` isolated.

`more-dropdown` enabled + `releases-tab` enabled:
![image](https://user-images.githubusercontent.com/10238474/63421570-7c469780-c411-11e9-81ed-1e120876c51c.png)

`more-dropdown` disabled + `releases-tab` enabled:
![image](https://user-images.githubusercontent.com/10238474/63421888-0a228280-c412-11e9-80fb-7a02e301a829.png)

Error in console:
```
❌ releases-tab
content.js:2709 TypeError: Cannot read property 'before' of null
    at releases_tab_init (content.js:3509)
    at async features_run (content.js:2704)
```

**Comment by kidonng** [comment]
It seems that we can't isolate `releases-tab`` because we need to place it after all buttons but before the dropdown. So a dirty check is inevitable.
