### ISSUE TITLE
Bug: Latest update expands more options dropdown

### ISSUE THREAD

**Issue by mmphego** [sindresorhus/refined-github#2364]
After disabling the extension, I came to the conclusion that there's a bug with the latest update.

**Note:** This occurs on all the pages, I've opened.

Below is a screenshot of the bug.
![image](https://user-images.githubusercontent.com/7910856/63434186-e157b880-c424-11e9-8926-1847fb44cc3d.png)

**Comment by busches** [comment]
Duplicate of #2357

**Comment by mmphego** [comment]
Duplicate of #2357
