### ISSUE TITLE
More dropdown is stuck open

### ISSUE THREAD

**Issue by NoahAndrews** [sindresorhus/refined-github#2365]
Can be seen at any URL within a repository, such as https://github.com/sindresorhus/refined-github

![image](https://user-images.githubusercontent.com/10224994/63437210-20bbe000-c3f8-11e9-9735-f0a8cdb8c16b.png)

**Comment by kidonng** [comment]
Duplicate of #2357

**Comment by NoahAndrews** [comment]
Ah, thank you.
