### ISSUE TITLE
The more drop-down is always open

### ISSUE THREAD

**Issue by LalyStana** [sindresorhus/refined-github#2369]
![Screenshot from 2019-08-21 12-31-20](https://user-images.githubusercontent.com/11777927/63450301-b1ea8100-c40f-11e9-97ab-aa357a8e7b9c.png)

**Comment by goodevilgenius** [comment]
I had to disable the extension because of this. I just noticed it this morning, but I wasn't on GitHub at all yesterday, so it could've started yesterday as well.

**Comment by jalessio** [comment]
@LalyStana This is a duplicate of https://github.com/sindresorhus/refined-github/issues/2357

**Comment by wachunei** [comment]
duplicate of #2357

**Comment by yakov116** [comment]
@LalyStana 	update your extension
