### ISSUE TITLE
New feature: fixed header?

### ISSUE THREAD

**Issue by jacobbearden** [sindresorhus/refined-github#237]
It would make it so the notification bell is always on screen, as are the pull request and issue links.

Thoughts?

**Comment by DrewML** [comment]
This would get a bit weird on diff pages, which already have the sticky diff header as you scroll down the page. We _could_ account for that, but the inconsistent behavior (and the double sticky headers height) on the diff page may be a little strange

Not necessarily against it, but definitely require some thought regarding how that would be addressed.

![fixed](https://cloud.githubusercontent.com/assets/5233399/15764384/289e8be8-28f0-11e6-89c0-dba49833db44.gif)

**Comment by sindresorhus** [comment]
👎 There's nothing important in the global header and having it fixed would waste vertical space and be annoying. This is a good use for keyboard shortcuts, `g+n` to go to Notifications. There's also [`notifier-for-github`](https://github.com/sindresorhus/notifier-for-github-chrome).

**Comment by jamestalmage** [comment]
I've always liked google's mobile behavior: 

The search bar slides up like normal as you scroll down, but slides back into view as you scroll up.

This gets it out of the way when reading a long page, but you don't have to scroll up all the way to the top to get to it.

**Comment by sindresorhus** [comment]
Just press <kbd>s</kbd> and it scrolls up and focuses the search bar.

**Comment by jamestalmage** [comment]
Yes. But that requires knowing, and remembering to use the shortcut. Maybe it's too hard to implement and not worth the effort. Keyboard shortcuts are awesome and all, but magically doing what I want is better.
