### ISSUE TITLE
Remove projects tab when 0 (empty?) from repos not working

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/refined-github#2370]
Found similar issues, but they are quite old, so opening a new one.

It's is checked on the options, it shows it on the devtools as enabled, but it stills stays there as `Projects (0)`. It's not working only on a repo pages and org page (should it be removed from there too?), correctly hides the profile projects tab.

I have `more-dropdown` and `releases-tab` disabled/unchecked.

Example: https://github.com/tunnckoCore/resources
![refined-github-fkjshdfjksdhfkjshdfkjhsdfkj](https://user-images.githubusercontent.com/5038030/63452930-2a713200-c450-11e9-913a-65860b23f5aa.png)

I know GitHub added an option to hide that tab from the settings, but you should do it for every single repo, which is kind of too much for me.

Also, a good thing will be to have `hide-wiki` too.

**Comment by busches** [comment]
This is working as designed. As you suggested, the current code is written to display when you have the option to turn it off in the repo.

https://github.com/sindresorhus/refined-github/blob/master/source/features/remove-projects-tab.tsx#L54-L55

I'll leave this open to discuss changing that behavior and hiding it all the time now.

**Comment by tunnckoCore** [comment]
> the current code is written to display when you have the option to turn it off in the repo.

Which is all the time, since GH added that setting. So at least the description should be updated or to be renamed to `remove-profile-projects-tab` or similar, because basically, it is currently only for profile's project tab.

> The same is true for Wikis, if you disable the feature in the repo, GH will remove the tab.

I know. Exactly, the thing is that you should disable them manually for each and every repo one by one, and when you have tons of repos and orgs it's too much repetition. You will one day have disabled them from GH for most of your repos, but until then you can use refined github for this to hide them all the time everywhere.

**Comment by kidonng** [comment]
@tunnckoCore CSS is our friend:

```css
.reponav a[data-selected-links^="repo_wiki"] {
  display: none;
}
```

**Comment by tunnckoCore** [comment]
Yes, but still, not that functional. I may use it for some time until/if PR come for this issue.

**Comment by fregante** [comment]
Sorry, I think it’s best for all of your users (rather than Refined GitHub’s users only) to just disable it on your repos.
