### ISSUE TITLE
`highlight-closing-prs-in-open-issues` feature is now implemented by Github

### ISSUE THREAD

**Issue by dotconnor** [sindresorhus/refined-github#2372]
This feature is now built into Github. Also with the update, the feature implemented by RGH is actually broken.

<img width="735" alt="Screen Shot 2019-08-21 at 10 01 26 PM" src="https://user-images.githubusercontent.com/14323370/63480277-3adcd900-c45f-11e9-9476-c0411651bf87.png">
<img width="1075" alt="Screen Shot 2019-08-21 at 10 02 18 PM" src="https://user-images.githubusercontent.com/14323370/63480306-5a740180-c45f-11e9-8a02-9cf16f65c7bf.png">

**Comment by yakov116** [comment]
Like our way much better!

**Comment by gabro** [comment]
FWIW, I would love to have a way to disable the one from GH and keep the one from refined-github, which is much easier to spot and way nicer to look at.

**Comment by kidonng** [comment]
Let's make it clear, GitHub has **partly** implemented RGH's two features: `highlight-closing-prs-in-open-issues` and `extend-status-labels`.

What GitHub provides:

- `highlight-closing-prs-in-open-issues`

![image](https://user-images.githubusercontent.com/44045911/63526213-98415a80-c531-11e9-9154-4fa4bee4ae8b.png)

While our lovely button links to the related commit, GitHub gives the closing PR.

But sometimes RGH will lose the game:

![image](https://user-images.githubusercontent.com/44045911/63526181-8bbd0200-c531-11e9-8b88-f5644ce7a3df.png)

- `extend-status-labels`

![image](https://user-images.githubusercontent.com/44045911/63526231-a2fbef80-c531-11e9-99cc-7e58cd70038c.png)

Yeah, RGH's is much nicer.

**Comment by fregante** [comment]
GitHub has the advantage of being instant. We have to wait for the whole page to load before adding those links. 

If GitHub shows ALL the possibly-closing PRs, we can drop our feature. 

I think the style is a minor issue. Later we can discuss if it’s worth bringing GitHub’s information and display it like RGH does. At the moment it might just be a “I liked it the way it was before”

**Comment by gabro** [comment]
> Later we can discuss if it’s worth bringing GitHub’s information and display it like RGH does.

That would also be nice. 

My personal gripe with the way it's implemented in GitHub is the relative importance of that piece of info wrt the rest of the page. When I'm on an issue that has a linked PR, I care about that quite a lot and I frequently switch over, so, in that respect, the weight RGH gives to that info is quite good.

**Comment by fregante** [comment]
It doesn't seem to work consistently. Example https://github.com/sindresorhus/issue-regex/issues/3

<img width="752" alt="Screenshot 2019-09-07 at 02 52 01" src="https://user-images.githubusercontent.com/1402241/64456512-90c9a600-d11a-11e9-812b-cb74272fe13f.png">

**Comment by fregante** [comment]
I'm removing these features since they are duplicate/non-working.

If anyone wants to improve its style it would be a new feature with a new name anyway. Any related code can be found in the commits that closes this issue.

<img width="851" alt="" src="https://user-images.githubusercontent.com/1402241/68082349-40d33b00-fe4e-11e9-9e26-31cde0a2cd11.png">

**Comment by yakov116** [comment]
@fregante I miss our way

**Comment by fregante** [comment]
Send a PR then
