### ISSUE TITLE
Can't click buttons on `All gists` page.

### ISSUE THREAD

**Issue by garyking** [sindresorhus/refined-github#2378]
I was able to fix this problem by disabling this extension, so I can confirm that it's the cause.

I can't click on the buttons as seen on the screenshot, on the `All gists` page. (Go to [Gists](https://gist.github.com) then click on `See all of your gists`).

![All gists - Buttons](https://user-images.githubusercontent.com/343940/63629608-16a90580-c5e1-11e9-9253-859f2a32a915.png)

**Comment by kidonng** [comment]
Confirmed. But actaully you *can* click the button when you point to the top edge 🤣
![image](https://user-images.githubusercontent.com/44045911/63633697-e1eb8b80-c67e-11e9-8585-022c4110f472.png)
