### ISSUE TITLE
Improve "Hide whitespaces changes": do not highlight trailing comma

### ISSUE THREAD

**Issue by jmfayard** [sindresorhus/refined-github#2382]
Hello,
It happens really often that I'm adding one parameter to a lot of functions. 
The diff on Github now looks like this:

```diff
fun myFunction(
-   oldParameter: Int
+   oldParameter: Int,
+  newParameter: Int
) {

}

fun otherFunction(
-   oldParameter: Int
+   oldParameter: Int,
+  newParameter: Int
) {

}
```

Two thirds of this diff is noise, I'm not modifying `oldParameter` in any way, other than adding a comma exactly at the end of the line in order to add a new parameter. There is no chance to forget adding this comma because the compiler would complain immediatly.

So what I would really like Github to be smarter about that exact use case.

Specifically, If I choose the option `Hide whitespace changes`

![image](https://user-images.githubusercontent.com/459464/63582838-1a656980-c59a-11e9-86f8-a443d211d617.png)

Then I would love to see this:

```diff
fun myFunction(
   oldParameter: Int,
+  newParameter: Int
) {

}

fun otherFunction(
   oldParameter: Int,
+  newParameter: Int
) {

}
```

**Comment by busches** [comment]
I'm not for suppressing changes from the diff itself, outside of what git already supports. There are other ways to get around this, such as leading commas or always adding the trailing comma to start with (not all languages support this).

**Comment by fregante** [comment]
I wouldn’t be totally against this, but that breaks expectations about git (and also is unrelated to whitespace) so we can’t add it to RGH

It would be nice as its own extension/userscript though, if it still highlighted in green that comma at the end
