### ISSUE TITLE
hide dependabot PRs in issue threads

### ISSUE THREAD

**Issue by AnthonyLenglet** [sindresorhus/refined-github#2384]
So when dependabot finds a new release for a dependency, it'll add the changelog, the problem is: those changelogs sometimes have links to issues, and doing this completely swamps the issues with hundreds upon hundreds of "This was referenced ..." PR links

Being able to hide those would be amazing !

Example URL:
https://github.com/FortAwesome/Font-Awesome/issues/15396

![image](https://user-images.githubusercontent.com/36004334/63694083-ef874980-c815-11e9-8668-e45c74d38f39.png)
![image](https://user-images.githubusercontent.com/36004334/63694096-f4e49400-c815-11e9-9325-f06086d56e67.png)

**Comment by fregante** [comment]
I'd just suggest staying away from such noisy bots. There's 0 reason to update each dependency separately each time a `patch` version is released.

Anyway, issue tracked in https://github.com/sindresorhus/refined-github/issues/615

**Comment by AnthonyLenglet** [comment]
> I'd just suggest staying away from such noisy bots. There's 0 reason to update each dependency separately each time a `patch` version is released.

this also depends in the case of security apps, but for most apps, I definitely agree on this, `patch` versions don't need automatic PRs like this
But sadly, this is something out of our control, they'll keep making noise as long as they're used :/

> Anyway, issue tracked in #615

Thanks for the info !
