### ISSUE TITLE
Warn before merging a PR if it contains fixup or squash commits

### ISSUE THREAD

**Issue by dorian-marchal** [sindresorhus/refined-github#2385]
Our team uses `fixup!` and `squash!` commits to add changes to pull requests that have already been reviewed. 

This is helpful for the reviewers because they can quickly identify the changes since their last review.

The commit history can look like this:

```
Commit A
Commit B
Commit C
fixup! Commit B
squash! Commit A
```

Note: Fixup and squash commits can be created with `git commit (--fixup|--squash) <ref>`, as shown in [this crappy GIF](https://user-images.githubusercontent.com/6225979/63809133-cf44b100-c921-11e9-80a3-915d99941b1c.gif).

When the pull request is ready to be merged, these commits are squashed/fixed up with `git rebase -i --autosquash`.

These commits are temporary and shouldn't be merged. I think it would be helpful to show a warning next to (and maybe disable) the "Merge" button when the current pull request contains at least one fixup/squash commit.

**Comment by dorian-marchal** [comment]
Here is a pull request with fixup commits: https://github.com/dorian-marchal/refined-github/pull/1

**Comment by fregante** [comment]
Tracked in https://github.com/sindresorhus/refined-github/issues/2579
