### ISSUE TITLE
Show your own Avatar for Reactions?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#239]
I find the blue shading that indicates I myself have reacted to something too subtle. I think it would be more intuitive if my pretty face was just there smiling back at me. Especially if there aren't so many people reacting that the list is being truncated.

**Comment by paulmolluzzo** [comment]
I like this idea a lot!

**Comment by sindresorhus** [comment]
Why not just make the blue shading less subtle? The avatar space is precious and I would rather see it being used for other avatars than my own.

**Comment by jacobbearden** [comment]
@sindresorhus `#e0eef3` works pretty well. Maybe not enough of a change though?

![image](https://cloud.githubusercontent.com/assets/5340692/19491281/ad3ce2f4-952f-11e6-9dac-8af1649034fc.png)

**Comment by hkdobrev** [comment]
Personally, I'd like to keep as-is - no need to waste space for your own avatar, the colour is enough for me.
