### ISSUE TITLE
More menu constantly expanded and not colapsible

### ISSUE THREAD

**Issue by intiocean** [sindresorhus/refined-github#2390]
I've disabled the extension and the menu dissapears. 

It happens on all repos.

I'm using Chrome on Mac Version 76.0.3809.100 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/725843/63844928-5c6f2080-c989-11e9-8a28-8cf194922eb7.png)

**Comment by fregante** [comment]
Duplicate of #2357

Update the extension, it's already fixed

**Comment by intiocean** [comment]
🤦‍♂ Thanks @fregante!
