### ISSUE TITLE
Search Organization option in Fork Window

### ISSUE THREAD

**Issue by shujaatak** [sindresorhus/refined-github#2394]
It's time consuming and hard to scroll and look for the organization in the **Fork Window**, it would be awesome if there was a search box where one could enter the starting characters of the organization name and matching organization or orgnaizations automatically get filtered and shown in the window.

Right now fork window is like this:
 
![Before](https://user-images.githubusercontent.com/14161646/64063482-14acfb00-cc0e-11e9-985d-559215f798e1.png)

And one way of required fork window could be:

![After](https://user-images.githubusercontent.com/14161646/64063507-50e05b80-cc0e-11e9-87f6-1a258dc42ba3.png)

**Comment by jerone** [comment]
Wow 😲, how many organizations do you have?

There was [design suggestion](https://github.com/sindresorhus/refined-github/pull/2230#issuecomment-520178324) that could have included an searchbar.

**Comment by fregante** [comment]
I don't think most people have nearly that many organizations. I think you'll just have to ctrl+f
