### ISSUE TITLE
`wait-for-build` throws error on PR page

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#2399]
(Firefox 68.0.2 (64-bit) on Windows 10, plugin version 19.9.2)

Happens for me on for example this PR: https://github.com/fastlane/fastlane/pull/15255

![image](https://user-images.githubusercontent.com/183673/64195618-357d8680-ce82-11e9-9cd4-eaff34fd1b2f.png)

```
19:36:52.676 ❌ wait-for-build content.js:2837:15
19:36:52.702
TypeError: "select_dom_default.a.last(...) is undefined"
    getLastCommit moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:5401
    addEventListener moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:5436
    wait_for_build_init moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:5519
    features_run moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2833
    add moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2880
    onAjaxedPages moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2795
    onAjaxedPagesRaw moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2790
content.js:2838:15
    features_run moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2838
    add moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2880
    onAjaxedPages moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2795
    onAjaxedPagesRaw moz-extension://57b5be31-7fbe-4b7d-bae1-b2f5de44e6b4/content.js:2790
```

I don't know if this actually breaks anything, but I guess it should be fixed anyway.

---

Same on Chrome:
![image](https://user-images.githubusercontent.com/183673/64196251-be48f200-ce83-11e9-9cee-5e9de5f91841.png)

**Comment by jerone** [comment]
I cannot confirm this. Is there any other extension interfering?

**Comment by janpio** [comment]
No, I tested with only Refined Github enabled.

I can only reproduce on repos where I am admin or can merge PRs (feature probably only runs there).

Any way I can help debugging this?

**Comment by janpio** [comment]
This seems to be the code failing here:
https://github.com/sindresorhus/refined-github/blob/be74449658e54b01397eca2766d8aab3ac0a54ce/source/libs/pr-ci-status.ts#L7-L9

This is the full HTML code of the page as it is shown to me:
https://pastebin.com/Ry8HbgF2

This is the only occurence of `commit-id`:
```
  <div class="text-right">
    <code>
      <a href="/fastlane/fastlane/pull/15255/commits/e27e62e21686e4a9ae2962a8d0589c9f41aaf26b" class="commit-id">e27e62e</a>
    </code>
  </div>
```
`commits-pushed` does not appear at all, but if I understand the code snippet correctly that is exactly what _should_ not appear for a match, correct?

**Comment by jerone** [comment]
> I can only reproduce on repos where I am admin or can merge PRs (feature probably only runs there).

I still can't confirm this error. For example https://github.com/jerone/PackageSize/pull/2, this is an PR and I'm admin of this repo. Checkbox is visible and no errors in console.

> `commits-pushed` does not appear at all, but if I understand the code snippet correctly that is exactly what _should_ not appear for a match, correct?

I'm not familiar with this feature, so I'll let @fregante answer your questions.

**Comment by janpio** [comment]
New unclosed PR where I get this error:
https://github.com/fastlane/fastlane/pull/15269

> What do you get in the console when you execute the following snippet `$$('[id^="commits-pushed"] .commit-id');`?

```
22:54:17.015 $$('[id^="commits-pushed"] .commit-id');
22:54:17.026 Array []
```

![image](https://user-images.githubusercontent.com/183673/64291071-9c28a000-cf67-11e9-8b0a-87dbfa78ba35.png)

**Comment by jerone** [comment]
Ah yes, I can confirm. It needs to be an **unclosed** PR.

That selector probably needs to be changed to `select.last('.js-commit-group-commits .commit-id')`.
