### ISSUE TITLE
Show more than three Avatars for Reactions?

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#240]
I kinda think it should just show as many as possible, only truncating when we run out of space.

Right now we are leaving a whole bunch of unused whitespace to the right of the reactions.

**Comment by paulmolluzzo** [comment]
The hard part is figuring out how many to show. I guess you can show all of them and then `max-width` each container with `overflow:hidden. Maybe there's a better way.

**Comment by paulmolluzzo** [comment]
This one would work nicely with #241 I think. If we have more space to show avatars then we won't only see the owners/collaborators avatars.
