### ISSUE TITLE
Go to Profile is broken

### ISSUE THREAD

**Issue by AuHau** [sindresorhus/refined-github#2400]
The `g m` shortcut is not working, after a bit of digging into the code it is because of the selector `#user-links a.dropdown-item[href="/${getUsername()}"]` does not work because `#user-links` is not used anymore.

I would create a PR, but I am not sure how to best target the button as they don't use any ID for that specific dropdown. Any ideas? Maybe since it is not needed since there is very strict part of the selector: `[href="/${getUsername()}"]`? That should lead always the element which is needed?

**Comment by fregante** [comment]
Your suggestion is fine. As long as the HREF is exactly what we need **and** as long as the element is always available on the page, it doesn’t matter which link we select: we're only using it as a proxy for the keyboard shortcut.
