### ISSUE TITLE
Disable `Request changes` button when no comment left

### ISSUE THREAD

**Issue by mcristina422** [sindresorhus/refined-github#2401]
When reviewing a pull-request the `Comment`, `Request changes`, and `Approve` buttons are enabled. 

![image](https://user-images.githubusercontent.com/132966/64275358-02330a00-cf0b-11e9-98e6-870d432b7f79.png) 
To request changes, a comment must be left. If you click the button without leaving a comment the message is presented: 
`You need to leave a comment indicating the requested changes.`

# Feature Request:
Disable the `Request changes` button when the text field is empty, preventing the user from accidentally attempting to leave an empty review

**Comment by fregante** [comment]
Regular comment fields have a similar behavior: the comment button is disabled until a comment is entered. We should use the same behavior, it’s probably triggered by a `required` attribute on the field plus some class on the buttons. 

Then, to allow a comment-less Approve, the approve button’s click should skip validation, probably via `approve.onclick = form.submit()`, making sure that this doesn’t break when the Approve button is completely disabled (e.g. on your own PRs)

Does this make sense? 😅
