### ISSUE TITLE
Keyboard shortcut should add a single comment instead of "StaRTinG A REVieW"

### ISSUE THREAD

**Issue by LoganDark** [sindresorhus/refined-github#2405]
May be related to #2063

I like to use keyboard shortcuts when I'm writing comments, because I'm a totally sane person and don't like wasting 2 seconds to click a button with my mouse. But unfortunately when writing a comment on a pull request Ctrl+Tab STARTS A REVIEW instead of adding the fucking comment, and now I'm stuck with this stupid comment I have to delete and re-post using the stupid mouse.

I don't have this extension installed and frankly without this feature it isn't useful to me, so if you could add the feature it would be great

Thanks

**Comment by fregante** [comment]
We can’t change the default shortcut, but you can use the feature you suggested to do send it as a comment

**Comment by LoganDark** [comment]
> We can’t change the default shortcut

Yeah you can but ok

**Comment by fregante** [comment]
Yeah we can but we won’t because it breaks user expectations.

**Comment by LoganDark** [comment]
Well not by default, don't extensions like these have a settings menu of some sort?
