### ISSUE TITLE
"Open all issues" for GitHub Projects

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#2406]
The feature [`open-all-notifications`](https://github.com/sindresorhus/refined-github/blob/master/source/features/open-all-notifications.tsx) adds a button the the Notifications list to open all of them in new tabs; feature [`batch-open-issues`](https://github.com/sindresorhus/refined-github/blob/master/source/features/batch-open-issues.tsx) adds a similar link for issues that are selected in issues lists.

I would love to have a similar button for GitHub Projects board columns. 
Example URL: https://github.com/orgs/apache/projects/9

It could appear somewhere in the column header, possible area highlighted yellow here: 
![image](https://user-images.githubusercontent.com/183673/64420068-a4372b80-d09e-11e9-9ce9-285e0a9da25e.png)

When clicking it, it would open all the currently displayed issues of the column (which is influenced by the "Filter Cards" input on the top right).

Using this button would make it much easier to go through many issues in one column in batches. Right now I have to scroll through the column and click them one by one.

**Comment by fregante** [comment]
None of the maintainers use Projects, this feature would be best part of ZenHub

**Comment by janpio** [comment]
Out of curiosity: If someone else would contribute the feature code for that, would you accept it or is Projects stuff generally out of scope for the extension?

**Comment by fregante** [comment]
It's out of scope, at most we hide stuff via CSS but other than that Projects requirements vary too much across teams and suggestions are rather large. I'd still have to review such PRs and there's already too much on the plate.

**Comment by janpio** [comment]
I totally understand.

Will fork and see if I can create my own variant then.
