### ISSUE TITLE
Prioritize reaction avatars

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#241]
Not sure how easy this one would be to pull off, but I think it would be good to prioritize reaction Avatars:
- Owners / Contributors (people with commit rights)
- The OP of the issue.
- People involved in the discussion. Especially people being replied to. The 👍 reaction is increasingly being used as "OK", or "Good point, you win", in lieu of leaving an actual comment.

I'm not sure which of the above should take priority.

**Comment by paulmolluzzo** [comment]
One thought I'm having is: If we rearranged these tiny avatars, how would we even know who they are? Should we also be adding some styled element (like a badge or border or something) to indicate the owner or OP or whatever?

> Owners / Contributors (people with commit rights)

Is this easily accessible? There are labels on the comment header, but if the owner or collaborators don't comment on the issue/PR you'd have to find them some other way.

> People involved in the discussion. Especially people being replied to.

Do you mean that if you, @jamestalmage, add a reaction to this comment yours should be the first reaction? And following that, if you quote/reply to this comment that my reaction is first on yours?

> The 👍 reaction is increasingly being used as "OK", or "Good point, you win", in lieu of leaving an actual comment.

I agree. I've been doing that a lot and I doubt anyone notices. 😢 

Possibly relevant: https://github.com/hzoo/contributors-on-github

**Comment by jamestalmage** [comment]
> Do you mean that if you, @jamestalmage, add a reaction to this comment yours should be the first reaction? And following that, if you quote/reply to this comment that my reaction is first on yours?

That sounds about right. Honestly, the idea was only loosely formed. I noticed the problem in a rather contentious debate on the `nodejs/node` repo. There were lots bystanders leaving 👍 / 👎 reactions, and there were a few places where the main parties involved in the debate had left a reaction, but it wasn't shown.

In some ways, the reaction system has complicated communications on GitHub. Overall, it's resulted in fewer useless comments, which is definitely good, but if you miss the 👍 from someone it can be easy to miss the later critique (i.e. "Does this person hate my idea, or do they love it and are just trying to sort out potential challenges in their head?"). I now feel I need to go back and double check all the reactions to make sure I'm not misinterpreting the tone of some comments before replying.

I'm not certain on the best weighting to give any of the above metrics, and somehow I doubt we will get it right our first try.

I think perhaps the most weight should be given to "who has commented the most in this issue". If there is a heated debate, the people involved should probably be first no matter what.

After that, I think probably the repo owner. In general, the 👍 from the repo owner on a proposal means work can proceed. That gets complicated for orgs, I think, I doubt there's an easy way to infer which org member is the final decision maker, but we can look into that after the initial implementation.

> One thought I'm having is: If we rearranged these tiny avatars, how would we even know who they are?

It would be better if mousing over an avatar, that persons name was first and bold in the "personA and personB reacted with the thumbs up emoji" message.

> Should we also be adding some styled element (like a badge or border or something) to indicate the owner or OP or whatever?

I like that idea.

**Comment by bfred-it** [comment]
I'd close this.

- Now we show more avatars than before (https://github.com/sindresorhus/refined-github/pull/644). 
- Either way we're still limited to the first 11 users GH decides to show for each reaction
- Also to know who is a contributor means crafting a huge GraphQL query with all the reactors on all the comments. Not worth it.
- It's been 2.5 years and nobody picked this up. We should have an expiration date 😅
