### ISSUE TITLE
GitHub Project Overflow UI Fix

### ISSUE THREAD

**Issue by Tbhesswebber** [sindresorhus/refined-github#2411]
**Rationale:** The current GitHub Projects UI isn't all that user-friendly and, with the closing of Waffle.io, GitHub Projects has become a go-to for many people working on products either outside of a corporation or within a corporation that doesn't value project management tools.

**Current Behavior:** The UI uses horizontal scrolling to see all of the columns within the kanban and vertical scrolling only within a column, not for the full page.

**Expected Behavior:** When not hovering over a column, the scroll-wheel on a mouse should scroll horizontally rather than doing nothing.  When hovering over the contents of a column that is "overflowing", the scroll wheel should scroll vertically over the column.  When hovering over a column that is not "overflowing", the scroll wheel should scroll the entire page horizontally.

**Potential Alternative Solutions:** 

- Change the container for all of the columns to be a flexbox (could cause issues for kanbans with many columns).
- Transpose the entire "table" so that both vertical and horizontal scrolling are used while making vertical scrolling the primary direction. (May also want to add a set of "quick jump" links to the top of the table to jump to a specific column)

**Comment by fregante** [comment]
None of the maintainers use Projects, this feature would be best part of ZenHub

**Comment by Tbhesswebber** [comment]
@fregante I'm confused by your response.  Projects is a part of GitHub and therefore a something that refining GitHub would cover.

My assumption is that your response was intending to convey that none of the maintainers could make educated decisions about what feature requests would be best suited to include because they don't use GitHub Projects, but that's kind of the point of _having_ feature requests... expecting a small group of maintainers to all have all of the knowledge is silly and, hopefully, none of us expect that to be the case.

I think that I was even more taken aback by the fact that the suggested solution was to go and pay for a service rather than supporting, and contributing to, the open source community.

If I have any of the above incorrect, please correct me, but I'd love more insight into what the rationale for not supporting pieces of GitHub within this repository and, possibly, finding a way forward that doesn't involve paying for privately maintained software.

**Comment by fregante** [comment]
Refined GitHub is not a community, it’s not a federation of features. The maintainers have to review and maintain **all** the features and you can see that there are already over a hundred, with bugs being opened every day.

We cannot add features we don’t care about, nobody has time for that. 

If you want this feature, you can write it and maintain it as a separate extension, nobody is preventing you to. 

Also, ZenHub has a free plan.

**Comment by Tbhesswebber** [comment]
I didn't mean to imply that Refined GitHub is a community, but that it is something that is directly in support of the open-source community.  Looking at the contributors, there are basically three, including yourself, who are truly putting effort into this and that's effort that I, at least, value. I honestly can't remember the last time I wished a part of GitHub were different and that's largely because of the work that gets done in this repository (and Octotree).

ZenHub does have a free plan, you are right, but that only works for public repositories.  I would assume that most of the people who use Refined GitHub are software engineers by trade and they use it specifically because of the pain points that come with being in GitHub for a healthy chunk of their day.  

We could all go and pay for ZenHub, but I don't think that solves any of the real issues.  If you want me to just shut up and go away, I will. But that also doesn't solve any issues.  I'm about to begin a three-month contract, but I would be more than happy to help find ways to solve problems in a sustainable way (and hopefully contribute) as I have availability.
