### ISSUE TITLE
Merge/match `highlight-own-issues-and-prs` and `highlight-collaborators-in-lists` 

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2419]
I think that the style of `highlight-own-issues-and-prs` (https://github.com/sindresorhus/refined-github/pull/1782) wasn't very effective, I always have to squint to find my own discussions.

`highlight-collaborators-in-lists` (https://github.com/sindresorhus/refined-github/pull/2351) made this more obvious, its style it's much more visible:

<img width="496" alt="" src="https://user-images.githubusercontent.com/1402241/64495022-a24bb300-d2be-11e9-8d92-30717ac22500.png">

I'm wondering... since `highlight-collaborators-in-lists` never highlights your own issues, why not just use the same style for both? Perhaps just with a slightly different color.

The features can be merged into one (`highlight-collaborators-and-own-discussions`) because they affect the same exact area, even if they're applied at different times.

cc @jerone

**Comment by jerone** [comment]
Agree. The simplest is to use `highlight-collaborators-in-lists` as the basis and append a different class when own username is found.

I would like to extend this with another check for repo owner (if exists).

Wondering what the styling should be, agree on the different color...

**Comment by fregante** [comment]
> Wondering what the styling should be, agree on the different color...

Maybe collaborators could have a light grey color and your name a bit more saturated gray-blue
