### ISSUE TITLE
Code is getting indented extra due to `indented-code-wrapping`

### ISSUE THREAD

**Issue by danawillow** [sindresorhus/refined-github#2421]
URL: https://github.com/terraform-providers/terraform-provider-google-beta/pull/1116/files#diff-1ae139f5fb2f3b78fda661a248925628
Screenshot: 
![oNnZZYmXgn5](https://user-images.githubusercontent.com/1130694/64550468-d4253f80-d2e7-11e9-922e-5379e350f2f6.png)

On version 19.9.8

**Comment by fregante** [comment]
Ouch, I suppose you're on Chrome because it works correctly on Firefox.

You can disable `indented-code-wrapping` until this issue gets solved

**Comment by danawillow** [comment]
Yup, Chrome indeed. Thanks for the workaround!

**Comment by notlmn** [comment]
Hey @danawillow, I'm on RGH 19.9.8 and running stable Chrome 76 and I'm not able to see any glitches like that in either split or unified diffs.

![image](https://user-images.githubusercontent.com/37769974/64599623-54769e00-d3d7-11e9-94fc-c0fe39af4c44.png)

Can you mention the exact steps you went through to end up at the situation, it helps a lot for me to debug this thing. And also can I know the exact version and channel of Chrome you are running this on...?

Thanks!

**Comment by fregante** [comment]
I think both of us are on macOS, it may be font-related

**Comment by dfawley** [comment]
FWIW I'm on linux and am having the same experience.  Disabling `indented-code-wrapping` also works for me.

**Comment by KubaJastrz** [comment]
May be helpful, based on https://github.com/sindresorhus/refined-github/pull/2436/files

macOS Mojave 10.14.6
Chrome 77.0.3865.75
Font `Menlo`

<details>
<summary>Doesn't work ✖</summary>

![gh-mac](https://user-images.githubusercontent.com/6443113/64920119-d25def00-d7b3-11e9-9ffa-9adc25fc37d5.png)

</details>

---

Windows 10 build 1903
Chrome 77.0.3865.75
Font `Consolas`

<details>
<summary>Works ✔</summary>

![gh-win](https://user-images.githubusercontent.com/6443113/64920121-d853d000-d7b3-11e9-9069-e58a84a3ad5f.png)

</details>

---

Arch Linux 5.2.14
Chromium 77.0.3865.75
Font `Liberation Mono`

<details>
<summary>Doesn't work ✖</summary>

![gh-lin](https://user-images.githubusercontent.com/6443113/64920123-ddb11a80-d7b3-11e9-924d-f550bcf23237.png)

</details>

**Comment by muescha** [comment]
@fregante 

the code wrap can also done by adding .soft-wrap class to #discussion_bucket element

**Comment by fregante** [comment]
Replaced by https://github.com/sindresorhus/refined-github/issues/2729
