### ISSUE TITLE
Permit submitting reviews without top-level comments

### ISSUE THREAD

**Issue by wearhere** [sindresorhus/refined-github#2422]
I'm not sure why GitHub has added the `required` attribute to this comment field, forcing you to add a top-level comment, when you have all the comments in the review to speak for themselves.

![image](https://user-images.githubusercontent.com/110000/64589604-59493c80-d35a-11e9-9c23-560f52099713.png)

Weirdly though, I can't reproduce this for RGH's open PRs. This made me think that it was an repo-specific setting but I went and looked through the repo in question's settings and couldn't find anything.

I then checked in Incognito, without RGH, and can't repro it either
![image](https://user-images.githubusercontent.com/110000/64589543-3028ac00-d35a-11e9-9a3d-77907ad90717.png)

which makes me wonder if it's an RGH feature (that I would hope to disable)?

**Comment by jerone** [comment]
I think it's already fixed: https://github.com/sindresorhus/refined-github/issues/2418.

**Comment by fregante** [comment]
Indeed 19.9.10 should fix this
