### ISSUE TITLE
Permit to copy the single line code block with a click

### ISSUE THREAD

**Issue by oktapodia** [sindresorhus/refined-github#2423]
Might be interesting to have a feature permitting to copy a code block via a click on a clipboard icon

Example URL:

![image](https://user-images.githubusercontent.com/2752200/64599415-3d24ba00-d3b1-11e9-81fa-ece84802b2c4.png)

**Comment by jerone** [comment]
I'm afraid there was already an (closed) request for this request: https://github.com/sindresorhus/refined-github/issues/1095

Hopefully @fregante will reconsider, because I'm also 👍

**Comment by fregante** [comment]
As suggested, this is similar to #1095 but also worse in that there are dozens of `code` elements on any given page that definitely don't need such a button.

**Comment by oktapodia** [comment]
Most of them are useful + that permits to directly copy a commit hash via a simple click as well... And not intrusive because it's only displaying the `clippy octicon` when hovering the code block..
