### ISSUE TITLE
Looking for input from the refined-github community!

### ISSUE THREAD

**Issue by lukehefson** [sindresorhus/refined-github#2426]
Hello friends – I hope this isn't inappropriate place to post (and if y'all think so, feel free to close this issue!) – but at GitHub my team is currently running a couple of surveys. And as refined-github has been so welcoming to me, I thought that you might like to help by taking 5mins to jot down some thoughts/feelings.

If you use them, specifically we'd love to know what you think about Issues & Project boards:

- Issues quick-survey: https://t.co/K1lLTIBHJb
- Project boards quick-survey: https://t.co/WcXZai0AHp

Feel free to mention refined-github features that you might like to see! We're always trying to figure out how we can bring some of the amazing goodness from this extension 'natively' into GitHub!

Thanks you!!! ❤️

**Comment by Tbhesswebber** [comment]
What does your team use to manage projects within it?  Might I suggest attempting to use GitHub projects to manage anything at all and that will help you to find some great places for improvement.

You could also search through the closed issues as most of the Projects issues get closed immediately.

**Comment by lukehefson** [comment]
> What does your team use to manage projects within it? Might I suggest attempting to use GitHub projects to manage anything at all and that will help you to find some great places for improvement.

We do in fact use Project and Issues – so that helps us a lot when thinking about the problems. But we do not always represent our users so we're definitely very interested in other opinions!

> You could also search through the closed issues as most of the Projects issues get closed immediately.

Not quite sure what you mean by this sorry 😬

**Comment by Tbhesswebber** [comment]
Refined GitHub closes Projects focused requests immediately because they don't use Projects and that adds an entire subset of GitHub that would need support, bug fixes, etc. By looking through closed issues that have the term "projects" in them, you can find full-fledged feature requests that you could then use or ask for more context on before deciding. Hopefully that helps provide some clarity (and I apologize for the lack thereof previously)!

**Comment by fregante** [comment]
@Tbhesswebber is referring to _us_ closing **Projects**-related PRs as "out of Refined GitHub's scope. Here are the closed feature requests:

https://github.com/sindresorhus/refined-github/issues/2411 
https://github.com/sindresorhus/refined-github/issues/2406
https://github.com/sindresorhus/refined-github/issues/2356
https://github.com/sindresorhus/refined-github/issues/1736
https://github.com/sindresorhus/refined-github/issues/1510
https://github.com/sindresorhus/refined-github/issues/2069

**Comment by lukehefson** [comment]
Ah gotcha! Thanks @Tbhesswebber & @fregante - as ever refined-GitHub is a goldmine of qualitative feedback! 🤗

**Comment by SAM389** [comment]
Hi

**Comment by fregante** [comment]
@lukehefson are responses still helpful or can this be closed?

**Comment by lukehefson** [comment]
> are responses still helpful or can this be closed?

My bad! should have closed this earlier!! Thanks everyone! ❤️
