### ISSUE TITLE
New Issue editor toolbar cuts out buttons, like "Add a link", "Insert code", and more

### ISSUE THREAD

**Issue by archon810** [sindresorhus/refined-github#2428]
Love the extension but this has been bothering me ever since I installed it. Some editor buttons end up missing - and a different set is missing in different cases.

`New Issue` without extension:
![image](https://user-images.githubusercontent.com/469543/64642550-7bc37000-d3c3-11e9-95f1-ad181005d597.png)

`New Issue` with extension:
![image](https://user-images.githubusercontent.com/469543/64642579-88e05f00-d3c3-11e9-8477-570438c2686e.png)

As you can see, on `New Issue` pages, the link, insert code, and a few other buttons are missing. However, they're present in the `Leave a comment UI` and a different set of buttons is missing there. 

`Add a comment` without extension:
![image](https://user-images.githubusercontent.com/469543/64642999-61d65d00-d3c4-11e9-8bc9-9ac2227aa11e.png)

`Add a comment` with extension:
![image](https://user-images.githubusercontent.com/469543/64643010-6733a780-d3c4-11e9-810e-b4c8b6d9fe94.png)

Why is this happening and can it be fixed?

Thanks.

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/64643110-bb975100-d3dd-11e9-8b13-a190932f8416.png)

Disable this option

**Comment by fregante** [comment]
> Why is this happening and can it be fixed?

It's happening because all those buttons can be replicated via keyboard shortcuts, you don't need to press those buttons.

**Comment by archon810** [comment]
Thanks. Can we have a discussion about:

- Why some of those are considered unnecessary, especially the `Add link` button?
- Why the sets of what's hidden differ between `New Issue` and `Add a comment`?

**Comment by archon810** [comment]
By the way, https://user-images.githubusercontent.com/1402241/53629083-a4fe8900-3c47-11e9-8211-bfe2d254ffcb.png, which is the image used by https://github.com/sindresorhus/refined-github/blob/master/source/features/clean-rich-text-editor.tsx, actually shows these buttons as still being there:
![image](https://user-images.githubusercontent.com/469543/64645074-ea56fc80-d3c8-11e9-92cc-5179fb8fdecc.png)

**Comment by fregante** [comment]
> while in fact they're removed in the `New Issue` UI, so I believe the real issue is it's removing the wrong buttons:
> ![image](https://user-images.githubusercontent.com/469543/64645074-ea56fc80-d3c8-11e9-92cc-5179fb8fdecc.png)

Ouch, indeed!

**Comment by fregante** [comment]
This is broken again.

# Issue page ❌ 

<img width="756" alt="Screenshot 2019-11-12 at 13 47 20" src="https://user-images.githubusercontent.com/1402241/68648504-1cb0e180-0553-11ea-80de-44ac708a4e69.png">

# Open PR ✅


<img width="756" alt="Screenshot 2019-11-12 at 13 47 45" src="https://user-images.githubusercontent.com/1402241/68648607-55e95180-0553-11ea-83fc-9a0051d80406.png">

# Closed PR ✅


<img width="756" alt="Screenshot 2019-11-12 at 13 47 26" src="https://user-images.githubusercontent.com/1402241/68648528-2df9ee00-0553-11ea-81f3-26832085870f.png">
 cc @arnaudvalle

**Comment by fregante** [comment]
As a solution, we should drop the ` markdown-toolbar > :nth-last-child` lines altogether and target the button specifically, like we do for `md-mention` and `md-ref`. The downside is that there will be extra spacing in some cases but that's much better than hidden buttons.

**Comment by arnaudvalle** [comment]
Hello there - I'll have a look at it in the next few days

**Comment by arnaudvalle** [comment]
@fregante Ah well too fast for me :) Thanks for sorting it out 👍
