### ISSUE TITLE
Highlight notifications of issues/PRs were you were mentioned

### ISSUE THREAD

**Issue by orium** [sindresorhus/refined-github#2430]
Currently the notifications view shows notifications for every issue/PR that you are subscribed to, with no visual feedback about mentions to you.  There is a "Participating" tab, but that's a click away and easy to miss.

It would be really nice to have a visual indicator of the importance of the notification.  In my mind they would have this order of importance:

1. Issues/PRs that I opened.
2. Issues/PRs where I was mentioned in the conversation or marked as a reviewer.
3. Issues/PRs that I explicitly subscribed to.
4. Issues/PRs that I implicitly subscribed to (i.e. because I subscribe to the organization or the project).

Not really sure if all this is doable with github's API, though.

Just to give an example, it would convey the information as I show here (but probably with a nicer design):

![](https://i.imgur.com/1pnAvvp.png)

**Comment by fregante** [comment]
It's [possible](https://developer.github.com/v3/activity/notifications/#notification-reasons) but I don't think it's useful to show such info for all notifications.

**Comment by orium** [comment]
Those 4 level I mention are just an idea.  What I think is useful is to have *some* sort of visual indication of how important the notification is. 

And if that can be configurable that would be even better (for instance the ability to configure a color for each type of notification reasons).

**Comment by jerone** [comment]
There is an online tool available that filters the notifications in different reasons:
* comment
* author
* state change
* assign
* subscribed
* team mention
* security alert

[Octobox](https://octobox.io/)

**Comment by sindresorhus** [comment]
I wish GitHub auto-sorted notifications based on importance. "Importance" being calculated based on what I usually prioritize and other hints, using machine learning. One can dream though.

**Comment by fregante** [comment]
The available information is incomplete and not particularly useful. Each notification could hide multiple comments and actions, but GitHub will only choose one of them. We can’t trust that it will choose the one you’re looking for so we shouldn’t show this info.

**Comment by fregante** [comment]
It's coming from GitHub: https://github.blog/2019-11-13-universe-day-one/#notifications

![](https://i0.wp.com/user-images.githubusercontent.com/158833/68600698-e31c9f80-049a-11ea-8967-61e4a615fad3.png?resize=2880%2C1800&ssl=1)

**Comment by jtagcat** [comment]
Necro!

I feel like the current situation is inadequate, as this is filtering (without `not` statements¹), not highlighting.

¹ With not statements you could have a few tabs/buttons/bookmarks for gh notifications. For example, 1 for mentions, 1 for repos you own, 1 for everything else. The 'everything else' is the notable part here, no `not` statements.
