### ISSUE TITLE
Show the list of open PRs for a particular file 

### ISSUE THREAD

**Issue by anikethsaha** [sindresorhus/refined-github#2438]
Example URL:

This may be somewhat referenced here But I guess it may differ!
#1323 

**Feature**: I guess there can be a sidebar or side-panel when opening a file, it will show the list of open PRs where this particular file is changed!
I think there is an API for getting the list of file changes from PRs and filtering these files with the opened file.

I guess this is the API: https://developer.github.com/v3/pulls/#list-pull-requests-files

**Benefits**: this will help a lot with reducing the duplicate PRs and will save time for contributors

**Comment by fregante** [comment]
I don't understand how this is different from #1323

**Comment by anikethsaha** [comment]
Here I am mentioning only opened PR to show in the list.

**Comment by jerone** [comment]
That is exactly how #1323 works.

Go to https://github.com/sindresorhus/refined-github/blob/master/source/features/reactions-avatars.tsx and you'll see "_This file is touched by PR 2416_" linkbutton in the breadcrumb header.
