### ISSUE TITLE
Suggestion: put font-style italic on comments in code blocks

### ISSUE THREAD

**Issue by eramdam** [sindresorhus/refined-github#244]
I discovered that the extension was using (among others) Operator Mono for code blocks, so I thought it would be a nice touch to add this bit of CSS to enjoy the full advantages of Operator Mono:

``` css
.pl-c {
 font-style: italic;
}
```

Here is how it looks 
![screen shot 2016-06-09 at 9 33 37 am](https://cloud.githubusercontent.com/assets/1409924/15937838/58d1401e-2e25-11e6-86e2-33e7040ace41.png)

**Comment by DrewML** [comment]
My concern with this change would be that it would make all comments italic, even for users of the extension that don't have `Operator Mono` installed

**Comment by eramdam** [comment]
Yup, that's the issue, if the extension had an Options page that would be a good fit 😊  But that's okay I can do myself a little userstyle 😁

**Comment by DrewML** [comment]
Cool, that sounds like a good solution for the interim. I'll leave this open for a bit for @sindresorhus to comment, since it's his extension and I know he's a user of `Operator Mono`, so it's possible he has some opinions re: this.

**Comment by sindresorhus** [comment]
We can leave it open in case we add options at some point.

**Comment by bfred-it** [comment]
Closing this as a consequence of #575
