### ISSUE TITLE
Mark all files as viewed/not-viewed

### ISSUE THREAD

**Issue by umanghome** [sindresorhus/refined-github#2444]
While reviewing PRs with 10+ files, the workflow gets easier by marking files as viewed. However, when I need to re-review the PR, it gets very tedious marking all files as not-viewed before going ahead with the review.

Would be great if we had a button that would mark all files as view or not-viewed.

**Comment by fregante** [comment]
This would make sense as part of `toggle-everything-with-alt` added in https://github.com/sindresorhus/refined-github/pull/2087

One thing to note, such feature can only affect files that have already been loaded, which means that on long PRs you'll have to first scroll to the bottom of the page, then `alt``click` the Viewed checkbox.

**Comment by Pyton** [comment]
As temporary solution I wrode JS bookmark:

    javascript:boxes=document.getElementsByClassName("js-reviewed-checkbox"),counter=0;for(let e=0;e<boxes.length;e++){const t=boxes[e];"File viewed, click, value:true"==t.dataset.gaClick&&(t.click(),counter++)}alert("Unfolded "+counter);

Just save it as Bookmark and put JS in URL.

**Comment by bbugh** [comment]
I would love this feature. I love the Viewed GitHub feature but the UX is incomplete. (PS thanks for the excellent extension)

---

If anyone wants a "set all viewed" equivalent of @Pyton's "unview all" snippet:

```
javascript:boxes=document.getElementsByClassName("js-reviewed-checkbox"),counter=0;for(let e=0;e<boxes.length;e++){const t=boxes[e];"File viewed, click, value:false"==t.dataset.gaClick&&(t.click(),counter++)}alert("Folded "+counter);
```

**Comment by leocaseiro** [comment]
I was thinking that a better feature would be on the scroll, as you scroll down the file, it would mark file per file as viewed.

**Comment by Pyton** [comment]
> I was thinking that a better feature would be on the scroll, as you scroll down the file, it would mark file per file as viewed.

Nop. Viewed feature (GH) collapse the code so You no longer see the code but only names.

**Comment by fregante** [comment]
> I was thinking that a better feature would be on the scroll, as you scroll down the file, it would mark file per file as viewed.

_Seeing a file_ is different from _being done reviewing it._ You might **see** the whole file in a viewport, but it doesn't mean that you actually read all of it.

The "Viewed" checkbox must be an explicit action

**Comment by fregante** [comment]
I'm thinking that the most reasonable solution to this is to put a "Mark all as read" at the end of the page, which is the obvious position to place it **and** avoids this issue ⬇️, since when you reach the button, everything was loaded.

> such feature can only affect files that have already been loaded.

**Comment by mfulton26** [comment]
If such a feature can only affect files that have already been loaded then perhaps a "Load All" button/feature should be added first.

If everything isn't loaded the button could be present, otherwise the button isn't shown and other commands are (e.g. "Mark all as read", "Mark all as unread", etc.).

**Comment by fregante** [comment]
The solution in my last comment already solves that issue.

**Comment by mfulton26** [comment]
Have you ever reviewed a PR that contains 2000+ files? I have. It took for ever just to load all the files and it would have been super nice to have just had a button that would have loaded everything for me instead of me scrolling down over and over again. 😄

**Comment by lukasz-tc** [comment]
> Have you ever reviewed a PR that contains 2000+ files? I have. It took for ever just to load all the files and it would have been super nice to have just had a button that would have loaded everything for me instead of me scrolling down over and over again. 😄

AFIR when you scroll till loading starts it fetch rest of the code.

**Comment by mfulton26** [comment]
that wasn't my experience, I had to keep scrolling down… oh, you're saying
maybe it was asynchronous loading for me even if I hadn't scrolled down
repeatedly; that's plausible; thank you

**Comment by leocaseiro** [comment]
In that case, just run the following on your dev tools:

```js
// toggle all to viewed
document.querySelectorAll('.js-reviewed-checkbox').forEach((elem => {
    if (elem.checked) { return }
    var clickEvent = new MouseEvent('click');
    elem.dispatchEvent(clickEvent);
}))

// toggle all to not-viewed
document.querySelectorAll('.js-reviewed-checkbox').forEach((elem => {
    if (!elem.checked) { return }
    var clickEvent = new MouseEvent('click');
    elem.dispatchEvent(clickEvent);
}))
```

**Comment by fregante** [comment]
> Have you ever reviewed a PR that contains 2000+ files?

What's the point of marking all files as viewed if you haven't viewed them?

**Comment by mfulton26** [comment]
> > Have you ever reviewed a PR that contains 2000+ files?
> 
> What's the point of marking all files as viewed if you haven't viewed them?

I do review them. I just don't want to click "Viewed" 2,000+ times. 😄 

This doesn't happen too often but on some projects it does happen from time to time. I typically like to quickly scan all the files looking for anything suspicious and then just call it good. However, once I review it I'd like to be able to see what changed if someone pushes another commit which only affects a subset of the files, I don't want to have to quickly scan everything again just see what changed.

**Comment by fregante** [comment]
The point I'm trying to make is that if you do review them, you also scrolled all the way to the bottom to see the button there.

**Comment by Ian1971** [comment]
Just to add a use case. On a large PR we may get all the changes and review them locally in an IDE. In which case mark all as viewed helps a lot.

**Comment by fregante** [comment]
Indeed, I didn’t think of checking it via git 👌

**Comment by fregante** [comment]
Can you check for an API to mark them as viewed? Marking “2000+ files” means making 2000+ HTTP requests. I think it’s gonna take a lot of time and maybe overwhelm GitHub. You might want to change strategy because GitHub didn’t account for it. 

I suggest sending this feature request to GitHub

**Comment by AliSoftware** [comment]
A more interesting feature to me would be to mark all files **up to a specific one** to be Viewed. Not all files, just all the files from the first one up to one I select.

That way we could have a way of tracking where we were at when we got interrupted while reviewing a super long PR

Perhaps a menu item under the "..." menu of each file like "Mark all files up to and including this one as Reviewed".

To me this is what the "Viewed" feature of GitHub was meant to be: to kind of bookmark where you were at during a review, which means only marking files as Viewed up to a certain one.

**Comment by Pyton** [comment]
@AliSoftware this could be realized by Click select like: click first item, click last item with Shift == Select all between

**Comment by pvinis** [comment]
I'll just add the reason I would like this feature and the reason I made #2865. 

Sometimes in big PRs I mark files as viewed when they are finalized for that PR, and leave some unviewed to make sure I clean up before finishing with that PR.

Some other times, while I'm in the middle of working in a big PR, I need to do a "PR Party" and explain the changes to the rest of the team, and to do that it's useful to mask everything unviewed, then with the team go through the files and mark them as viewed as we go. Finally, after that is done, I either uncheck the unfinished views, or uncheck all again and mark the finished files viewed.

**Comment by Decat-SimonA** [comment]
Hello, another use-case would be to mark files containing some texts as viewed.
For example, we commit some jOOQ auto-generated code: marking all files containing `@Generated` as viewed could be useful

**Comment by fregante** [comment]
@Decat-SimonA you can use `gitattributes` to hide/collapse those files like it happens automatically for `package-lock.json`, for example.

https://github.com/github/linguist#generated-code

Marking files `marking all files containing `keyword` as viewed` is too specific to be part of GitHub.

**Comment by mfulton26** [comment]
FYI: I've been using a [custom search engine in Google Chrome](chrome://settings/searchEngines) to mark all files as read/unread, switch to the rich diffs, etc.; this could be modified to use `%s` in the search URL to take "arguments" to a "Mark all as viewed" function to match file names or contents of files (you'd have to modify the script to detect such, etc.)

| Search engine                    | Keyword | Query URL                                                                                                           |
| -------------------------------- | ------- | ------------------------------------------------------------------------------------------------------------------- |
| GitHub: Display all rich diffs   | ghrd    | javascript: document.querySelectorAll('.js-rendered').forEach(button => button.click());                            |
| GitHub: Display all source diffs | ghsd    | javascript: document.querySelectorAll('.js-source').forEach(button => button.click());                              |
| GitHub: Mark all as not viewed   | gh-v    | javascript: document.querySelectorAll('.js-reviewed-checkbox').forEach(input => !input.checked \|\| input.click()); |
| GitHub: Mark all as viewed       | gh+v    | javascript: document.querySelectorAll('.js-reviewed-checkbox').forEach(input => input.checked \|\| input.click());  |

**Comment by fregante** [comment]
I'm implementing this via shift-click to mark multiple files at once like you can select multiple issues at once.

**Comment by mfulton26** [comment]
> I'm implementing this via shift-click to mark multiple files at once

would alt-click not make more sense? e.g. I believe alt-click is already natively supported by GitHub for expanding/collapsing all files

**Comment by fregante** [comment]
Alt-click would make sense if it acted on *all*, but that's not how it works (currently).

Shift-click is the standard for selecting "from X to Y"

> I believe alt-click is already natively supported by GitHub for expanding/collapsing all files

That applies to the toggle icon. This feature acts on "Viewed"

**Comment by 55Omar** [comment]
![4rkC9-data-online-holiday-mobile-shopping-statistics-download](https://user-images.githubusercontent.com/62673547/80036835-2fb0e000-84fb-11ea-9785-594c25d557da.jpg)

**Comment by 55Omar** [comment]
![4rkC9-data-online-holiday-mobile-shopping-statistics-download](https://user-images.githubusercontent.com/62673547/80036872-40615600-84fb-11ea-9c1f-773c5ec10913.jpg)

**Comment by 55Omar** [comment]
# #3028 #3029

**Comment by 55Omar** [comment]
`



`

**Comment by fregante** [comment]
> would alt-click not make more sense?

I opened an issue for that: #3043, to extend the feature I implemented.

**Comment by Flabbergasted-1** [comment]
In this covid 19 pandemic, I have taken to downloading viewing material which consists of a series with several episodes. I view one episode each night and sometimes forget where I am up to, so needing a way to mark the file that I viewed last. Here is my suggestion to solve the problem...
hover cursor over the file you need to mark and right-click.
From the options choose 'properties'
Tick the box marked 'hidden'
Left-click 'apply' and left-click 'ok'
You will see that the file displayed is now much paler than the others. and thus effectively MARKED!!
My only concern is what other effects this may have on the file structure and behavior.
Suggestions, please...

**Comment by lordzsolt** [comment]
I see this PR hasn't moved since it was created 😭 

My use case:
- I review a PR, mark each file individually as "Viewed"
- PR gets approved and merged
- After the release, something breaks, so we need to revisit the PR to see what change could've caused it.
- All files are collapsed, so I individually have to expand all of them....

**Comment by fregante** [comment]
@lordzsolt the feature already exists, you just need 2 clicks instead of 1: https://github.com/sindresorhus/refined-github/pull/3007
