### ISSUE TITLE
Show whitespace is disabled but it still shows whitespace

### ISSUE THREAD

**Issue by ahatzz11** [sindresorhus/refined-github#2445]
No matter what I do I can't seem to disable the whitespace option. I've enabled and disabled again, I've even uninstalled the extension and re-installed.

Here is the setting, disabled:

![image](https://user-images.githubusercontent.com/6256032/65055407-b6ce2200-d934-11e9-8594-8ba35cfc4ede.png)

Here is my github:
![image](https://user-images.githubusercontent.com/6256032/65055433-c188b700-d934-11e9-9de0-6164854917ab.png)

Note that this is a GHE instance.

**Comment by fregante** [comment]
I think:
- either you're not using the domain picker added in https://github.com/sindresorhus/refined-github/pull/2293
- or you're not waiting long enough for the setting to be saved (currently [delayed by 600ms](https://github.com/fregante/webext-options-sync/commit/f7365dcbe09d4cb68f6e2d035c76e93f62b47069), I should probably reduce this)

Let me know, it seems to work correctly for me in Chrome if I follow those two notes.

One more check: Is the setting actually saved?

1. Pick your domain from the domain picker
2. Uncheck the feature
3. Wait a second or two
4. Refresh the options page
5. Pick the domain again 
6. verify that the option is still unchecked

**Comment by ahatzz11** [comment]
I think the domain picker was it! Didn't see that get added, thanks!
