### ISSUE TITLE
Legend icons missing from the thread timeline

### ISSUE THREAD

**Issue by raisedadead** [sindresorhus/refined-github#2451]
Facing an issue where some of the legend icons like 'closed', 'opened', 'project', 'edit' etc. on the events are missing in the thread timeline. 

Seems to be affecting both issues and pull requests.

With the extension enabled:

![image](https://user-images.githubusercontent.com/1884376/65361462-40c20780-dc21-11e9-9d09-1ce646b430d7.png)

With the extension disabled:

![image](https://user-images.githubusercontent.com/1884376/65361477-4f102380-dc21-11e9-8eda-268a3c3ee849.png)

Sample thread: `https://github.com/freeCodeCamp/freeCodeCamp/pull/36808`

**Comment by busches** [comment]
This is intentional.
https://github.com/sindresorhus/refined-github/blob/eca0a5319db1f77bb252fe7c9fe71a98dc26e6da/source/features/deemphasize-unrelated-commit-references.css

You can override that style in the extension if you prefer to see them:
```
.TimelineItem:not(.TimelineItem--condensed) ~ .TimelineItem .TimelineItem-badge {
	visibility: unset;
}
```

**Comment by fregante** [comment]
`deemphasize-unrelated-commit-references` should not hide those icons, but just the icons of commits that don't belong to the current PR.


<img width="786" alt="before-explanation" src="https://user-images.githubusercontent.com/498274/46896331-58014e00-ce31-11e8-9571-b59762f33a9b.png">

**Comment by fregante** [comment]
To fix this specific problem we can change the selector to only hide the commit icon:

```css
.TimelineItem:not(.TimelineItem--condensed) ~ .TimelineItem .TimelineItem-badge .octicon-git-commit {
    display: none;
}
```

However it would leave a white gap:

<img width="142" alt="" src="https://user-images.githubusercontent.com/1402241/65368278-2b70cb80-dc69-11e9-9450-9aa4569de072.png">


---

If anyone wants to help, here's a testing link:

https://github.com/sindresorhus/refined-github/pull/2415#ref-commit-16050d5

**Comment by fregante** [comment]
I implemented the fix suggested above because this was an ugly bug.

The bug now is reduce to:

<img width="142" alt="" src="https://user-images.githubusercontent.com/1402241/65368278-2b70cb80-dc69-11e9-9450-9aa4569de072.png">

To fix that, the feature needs to be re-implemented via JavaScript, sadly.

I think we can leave it as is until someone opens an issue for that.
