### ISSUE TITLE
Restore "Delete branch" button in responsive branch list

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2452]
1. Visit https://github.com/sindresorhus/refined-github/branches
2. Resize the window to less than 1000px
3. See "Delete branch" icon disappear

This makes it impossible to delete a branch unless you make your window bigger or zoom out.

The trash icon should always be visible. The `New PR` button can be hidden (leave as is). There still are alternative ways to create PRs, but there's no other way to delete a branch.

![Button gone](https://user-images.githubusercontent.com/1402241/65368453-670c9500-dc6b-11e9-85ce-d6e99a76a6bd.gif)

**Comment by rajatjindal** [comment]
Hi 

I have little to no experience working on UX/CSS, and am trying my hand to address this. I've a branch where I've made some changes, but ofcourse they are not working right now.

could you pls take a look at it, and provide me some feedback if approach to keep delete button visible is OK or not.

https://github.com/sindresorhus/refined-github/compare/master...rajatjindal:issue-2452?expand=1

Thanks
Rajat Jindal

**Comment by fregante** [comment]
This should be a CSS-only feature; the button is already in the DOM and it only needs some CSS to unhide it.
