### ISSUE TITLE
Move the status icon

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#2454]
### Current layout

![image](https://user-images.githubusercontent.com/36894700/65377770-ecfeff00-dcb0-11e9-8349-3d7df1082c7e.png)

### Would be nice to see

![image](https://user-images.githubusercontent.com/36894700/65377955-326ffc00-dcb2-11e9-80aa-52f229aaf75f.png)

### Why the change?

There's that extra annoying space (highlighted):

![image](https://user-images.githubusercontent.com/36894700/65377972-68ad7b80-dcb2-11e9-87f5-f3650a5d9678.png)

**Comment by fregante** [comment]
The current layout is this, there's no extra space, the text is aligned right:

<img width="303" alt="" src="https://user-images.githubusercontent.com/1402241/65382608-c504af80-dd33-11e9-98c7-8ae1c4fcb950.png">

**Comment by szmarczak** [comment]
You didn't get it right. I'm not saying it should be centered. I mean the icon should be moved to top, because the text is *already* centered (at least on my side) and it doesn't look well.

> The current layout is this, there's no extra space, the text is aligned left:

That's weird. On my side it's centered. I'll investigate and will let you know.
