### ISSUE TITLE
Create an Issue from browsing through code

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#2459]
what i do:

- i read the current code at Github and like to comment on some thing

what i see:

- i can not comment (like in PullRequests or Commits with the blue plus sign)
- i have to go to blame and find the last commit to this code and there i can comment

what i expect:

- select a line (or range), get an blue plus sign. 
- when i click on plus sign i get an textfield for an comment
- when i save the comment then a new issue should be created
- the issue should include a link with a range (`#L12-L14`) and my comment

Example URL:

example how issue could be expected:
https://github.com/bvlktech/GatsbyFinds/issues/1

current work around (comment on commit):
https://github.com/bvlktech/GatsbyFinds/commit/6e87f1ad2af2b8ba2e0ddd17f983ee50856a59e5#diff-b9e136416b90437fa1dac910280b45fcR17

**Comment by fregante** [comment]
It's there natively

<img width="298" alt="Reference in new issue" src="https://user-images.githubusercontent.com/1402241/65703366-d7be1200-e0ae-11e9-846b-a856107a5df8.png">

**Comment by muescha** [comment]
great !

**Comment by muescha** [comment]
mhh - just not work with "choose a template"

**Comment by fregante** [comment]
Yeah I reported that on May 3rd, they confirmed the bug but not fixed yet
