### ISSUE TITLE
urlencode branch names

### ISSUE THREAD

**Issue by Ma27** [sindresorhus/refined-github#246]
when using branches like ``#123-refactor-foobar``, the branch link in the PR section is wrong as the hash is not url encoded and therefore the link will be invalid:
![bug report](https://cloud.githubusercontent.com/assets/6025220/15989577/609efd52-307a-11e6-84be-2384417643b0.PNG)

The link from this place will end up here:
![url](https://cloud.githubusercontent.com/assets/6025220/15989573/1869afdc-307a-11e6-9de2-0da3a3f01a3e.PNG)

In order to solve this, the link should be url encoded.

**Comment by adjohnson916** [comment]
GitHub doesn't seem to URL encode forward slashes in its links to branches that include them, though it seems to work anyway with our `%2F` encoding.
