### ISSUE TITLE
Show file tree in pull requests

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/refined-github#2462]
I've seen a few people use a [Chrome extension](https://chrome.google.com/webstore/detail/better-pull-request-for-g/nfhdjopbhlggibjlimhdbogflgmbiahc) that (among other things) shows a file tree (of the changed files only) in pull request pages, like this:

![screenshot](https://lh3.googleusercontent.com/9Z2KdLdZpYt2gLe6wI5XPJ9BMzuJgCtOFUmg8ZFQ8nLgNy9UYDUWYVP6-rFEvUu6E6wjRMEt3wA=w640-h400-e365)

Would this be something that refined-github could consider?

**Comment by fregante** [comment]
That's a rather complex feature and an extension already exists, no need to add the same thing to Refined GitHub

**Comment by waldyrious** [comment]
> an extension already exists

Not for Firefox 😢

But sure, I understand your position, and kind of expected it. Just wanted to make sure this possibility was explicitly discussed and decided upon.

**Comment by waldyrious** [comment]
For Firefox users out there, I found an extension that implements this and integrates well with Refined Github: [Github Tree Structure](https://addons.mozilla.org/en-US/firefox/addon/github_tree_structure).

There's also another extension called [Octotree](https://www.octotree.io/), which is available for both Chrome and Firefox (and others), but it doesn't seem to work well with the sticky header (reported as https://github.com/ovity/octotree/issues/802).
