### ISSUE TITLE
`sticky-discussion-sidebar` resets on leaving a comment (and other interaction)

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#2463]
`sticky-discussion-sidebar` is really a nice feature, unfortunately it "resets" when you leave a comment (or interact with the discussion in other ways):

![refined-sticky-discussion-sidebar](https://user-images.githubusercontent.com/183673/65764693-818cb580-e126-11e9-8186-da7e9596f29a.gif)

This makes it pretty nasty to use, as you get used to have the sidebar in view all the time and are pretty confused when it is not.

**Comment by fregante** [comment]
I think this needs to be updated to use `on-updatable-content-update`
