### ISSUE TITLE
Fix "Undo close tab" strangeness

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#2465]
If you open an issue in Firefox, then for example change the labels, close the tab with `Ctrl + W` then undo closing the tab with `Ctrl + Shift + T` it will load the issues as it was _before_ you changed the labels. This is super confusing if this is a typical workflow for you (as is it for me when triaging hundreds of issues).

It would be super impressive if Refined Github could somehow fix this problem somehow.

**Comment by fregante** [comment]
I think this is because Firefox doesn't restore the DOM but just reloads the HTML from cache, which doesn't have the latest changes.

I don't think this is fixable other than by reloading the whole page, which is not great.

**Comment by janpio** [comment]
Interesting. The underlying problem is the way Github updates its DOM then?

The problem also exists in Chrome, if you close the tab quickly enough after e.g. adding or removing a label - when reopening the tab the previous state is shown.

In theory an extension (I am not saying this should be in Refined GitHub, just that this could theoretically be solved via an extension) by tracking if you make any changes to an issue, so that when you close and re-open a tab it could automatically reload in these cases, correct?

**Comment by fregante** [comment]
Not really. Even if we save the DOM/HTML, we can't guarantee that events still work correctly if we inject it. I think Chrome preserves the whole application state in memory, we can't do that from an extension.

**Comment by janpio** [comment]
Oh sorry, I was unclear. I meant:
The extension takes care of tracking changes to a discussion, then if a tab is reopened (`Ctrl + Shift + T`) and it detects the "this is probably showing outdated information now" it reloads the page manually instead of letting the browser show an outdated version of it.

**Comment by fregante** [comment]
> if a tab is reopened

I don't think we can detect that without adding `tabs` permission, which we can't.

I think you'll just have to press `Ctrl + Shift + T``Ctrl + R` and be done with it :D

**Comment by janpio** [comment]
... or I can add another side project to my plate that I might get to one day: https://github.com/janpio/github-fix-reopened-tabs ;)

Thanks for the conversation here.

**Comment by fregante** [comment]
This may be possible after all. I noticed that an outdated page is updated by GitHub when the issue/PR is updated.

Example:

1. Have outdated tab
2. In another tab, leave a comment
3. The outdated tab is updated to the latest version.

Perhaps this behavior can be triggered locally, rather than by the server.

**Comment by fregante** [comment]
Boom:

```js
const marker = document.querySelector('.js-timeline-marker');
marker.dispatchEvent(new CustomEvent("socket:message", {
	bubbles: true,
	detail: {data: {gid: marker.dataset.gid}}
}))
```

**Comment by janpio** [comment]
This would improve my life so much <3

**Comment by fregante** [comment]
Feels like yesterday that I left that comment. Unfortunately it wasn't. 

Nobody took this for years, closing.
