### ISSUE TITLE
"File Finder" improvements

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2467]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2415.16%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2467)

1. Visit https://github.com/sindresorhus/refined-github
2. Press `t`
3. A file finder will load

There are 3 improvements that can be made:

- `t` only works while you're on `/tree/` and `/blob/` pages; it should work on every page of the repo, including issues.
- When **navigating back** to the File Finder (e.g. open finder, open file from list, go back to finder), the previous input is lost; this should instead be preserved.
- After pressing `t`, you have to wait for the page to load before typing a file name; usually software will buffer your keyboard input even if the UI takes a while to load; we should simulate the same behavior so you can type `t` and start typing your query right away.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $15.16)

- [<img src='https://avatars3.githubusercontent.com/u/1402241?v=4' alt='fregante' width=24 height=24> fregante](https://issuehunt.io/u/fregante) ($15.16)

### Submitted pull Requests
- [#2825 File Finder improvements](https://issuehunt.io/r/sindresorhus/refined-github/pull/2825)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
> t only works while you're on /tree/ and /blob/ pages; it should work on every page of the repo, including issues.

I think it's too easy to accidentally press it. Maybe if we put it behind a modifier? Shift+T?

**Comment by fregante** [comment]
> I think it's too easy to accidentally press it.

Unless we're going to disable all of these we shouldn't change that either:

<img width="424" alt="Screenshot 2019-09-29 at 10 28 37" src="https://user-images.githubusercontent.com/1402241/65825684-fafde280-e2a3-11e9-8542-d0ce7fed264a.png">

`t` is not a big deal imho

**Comment by danedavid** [comment]
Can I have a shot at this one?

**Comment by fregante** [comment]
Please!
