### ISSUE TITLE
Displayed build status relates to the globally latest build instead of latest build in the default branch

### ISSUE THREAD

**Issue by OrBin** [sindresorhus/refined-github#2468]
Refined-GitHub [adds a build/CI status icon next to the repo’s name](https://user-images.githubusercontent.com/1402241/32562120-d65166e4-c4e8-11e7-90fb-cbaf36e2709f.png).

It seems like the build status is displayed for the latest build all over the repository, which is weird and I'd expect it to display the latest build for the default branch.
Maybe it works as designed, but I believe that the build status icon next to the repo's title should describe the build status for the current/stable state of the project, therefore I expect it to relate to the default branch.

For example, in [OrBin/gramhopper](https://github.com/OrBin/gramhopper) repository, I currently see a failing build icon:
![](https://i.imgur.com/0hhMY0L.png).
The linked build is [Build #199](https://travis-ci.org/OrBin/gramhopper/builds/583890949?utm_source=github_status&utm_medium=notification) from  branch `feature/run-ci-with-python-3.8`, which is some experiment I've made.
The build I'd expect to see is [Build #198](https://travis-ci.org/OrBin/gramhopper/builds/583742889) - the latest build on `dev` branch (the default branch).

**Comment by fregante** [comment]
According to GitHub, the current/stable branch is `dev`. We don’t know what your logic is to decide which branch is current/stable other than just selecting the default branch. 

And the default branch is currently failing, hence the red cross 

https://github.com/OrBin/gramhopper/commits/dev

**Comment by OrBin** [comment]
Interesting... Builds 198 and 199 refer the same commit and use the same configuration...
Anyway, you're right.
Thanks for the explanation!
