### ISSUE TITLE
Hotlink to GHE personal token

### ISSUE THREAD

**Issue by mcristina422** [sindresorhus/refined-github#2469]
It would be nice if when selecting a domain that is not `github.com` that this linked to `https://${domain}/settings/tokens/new?description=Refined%20GitHub&scopes=repo`

https://github.com/sindresorhus/refined-github/blob/f36d4f10c725b4511e0d28d5c1fec2cf1b2a22b6/source/options.html#L9

**Comment by busches** [comment]
If you don't want to do this, I'll see if I can crank out some of the GHE issues this week.

**Comment by fregante** [comment]
Duplicate of 

https://github.com/sindresorhus/refined-github/issues/2408
