### ISSUE TITLE
Hotkey for copying the most recent hash stub

### ISSUE THREAD

**Issue by Asa-Dawson** [sindresorhus/refined-github#2471]
Provide a hotkey for copying the most recent commit hash stub from a pull request. In my use case it's for accessing resources with names identical to the current hash stub related to their commit.

It'd also allow me to avoid the horror that is trying to copy it from the page ![this](https://user-images.githubusercontent.com/43134130/66044890-7668c980-e51a-11e9-83b9-ce5fc55380db.gif)

Even if you do copy it from that part of the page, it comes suffixed with a space.

Example URL:

Any pull request URL

https://github.com/$USERNAME/$REPONAME/pull/$NUM I suppose

**Comment by fregante** [comment]
Can you explain your use case a little more? I don’t understand

**Comment by Asa-Dawson** [comment]
Sure! As a normal part of my day to day development I'll need to grab the stub from the SHA hash of the latest commit in a pull request, these stubs are then used in the URL to the deployed version of that commit.

It's really fiddly to copy that hash stub, especially with a trackpad. If there were a copy icon (like so, shown underneath) that would also work. 
<img width="320" alt="image" src="https://user-images.githubusercontent.com/43134130/66200482-14829e00-e699-11e9-9dad-194b1d8ebdaa.png">


Anything to escape the frustration of accidentally copying the entire bottom half of the pull request page!

**Comment by sindresorhus** [comment]
In Chrome, you can just right-click the SHA link and click "Copy" to copy the text (not link).

**Comment by Asa-Dawson** [comment]
I'm using firefox, where that feature isn't available sadly 😭

**Comment by fregante** [comment]
This seems very specific, we can’t add a button

You can probably improve the selection by adding some padding to that element instead (via Stylus or our own CSS field in the Options page)
