### ISSUE TITLE
Separate "Create Draft PR" from "Create PR" dropdown

### ISSUE THREAD

**Issue by tdtm** [sindresorhus/refined-github#2473]
A PR created as a "full" (non-draft) PR is impossible to convert to a draft PR.

Half the PRs I make, meaning for them to be a draft, end up accidentally created as a full PR just because I hit the button rather than the drop-down. That requires deleting that PR and creating a new one - this time as a draft.

Judging by [this thread on the Github community forum](https://github.community/t5/How-to-use-Git-and-GitHub/Feature-Request-Switch-from-ready-to-draft-in-pull-requests/td-p/19107), I'm not the only one.

I would suggest for refined-github to pull the "Create Draft PR" button from the dropdown to instead be besides the main "Create PR" button.

Mockup:
![2019-10-02 at 17 33](https://user-images.githubusercontent.com/7750012/66083788-0c145100-e53b-11e9-9c81-0bf715b8c7a2.png)

**Comment by Daenyth** [comment]
I'd love if this had a configuration option to make the "create draft" separated button more prominent than the non-draft button (basically the UI in the screenshot but with the behaviors swapped in position). The config could default to "off" to avoid surprising people

**Comment by tdtm** [comment]
Yeah, _personally_, draft-as-default would make more sense. I was just mindful of not forcing that on anyone, but having that as a config as you suggest would be even better.

**Comment by muescha** [comment]
Or extend this plugin with an option (default for all is "no") to additional hide the "create pull request"
