### ISSUE TITLE
create participant tab for all issues for user's header

### ISSUE THREAD

**Issue by anikethsaha** [sindresorhus/refined-github#2476]
Please ignore this issue or close it if this feature or any ongoing PR or Issue is opened about this 

It would be very helpful if there is one more tab where there will be a list of issues where the user has participated ( like commented or subscribed or liked ). It gets easy to keep tracking and searching 

Before 
![image](https://user-images.githubusercontent.com/26347874/66253760-8edf1b00-e78a-11e9-8763-e23afb8e3a34.png)

After
![image](https://user-images.githubusercontent.com/26347874/66253831-863b1480-e78b-11e9-9359-e18515ad6044.png)

Similarly for PRs as well.

I guess it might not be possible maybe because there isn't any API available for that. right?

**Comment by fregante** [comment]
We already have a `commented` tab and GitHub offers a `subscribed` one in the notifications page. The two can’t be merged.

The most we can do, maybe, is include posts you reacted to… but that’d change the existing “Commented” view, we can’t add another view that’s slightly different.

**Comment by anikethsaha** [comment]
The subscribed thing from github is too crowded. That can be categorized with issues and PRs ! I know they separated it with repos and all. 
YEah this is quite more work for small outcome thing .
