### ISSUE TITLE
Backtick parsing is not bulletproof, ` | ` example

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#2483]
https://github.com/stdedos/robotframework-debuglibrary/issues/3
![image](https://user-images.githubusercontent.com/133706/66464650-0ca36f00-ea88-11e9-995b-de7d13aa2cf9.png)

Visually, it appears as if I wrote:
```
` |  `as
```

whereas I wrote:

```
` | ` as
```

**Comment by tanmayrajani** [comment]
maybe we should add `white-space: pre`?

**Comment by fregante** [comment]
Test ` | ` test

**Comment by fregante** [comment]
It looks like GitHub parses that as a plain:

```
Test `|` test
```

Instead of

```
Test ` | ` test
```

So instead of complicating things, we should just match GitHub's parser and just trim the content of the backticks.

**Comment by stdedos** [comment]
It seems you are right:
```md
Test `|` test
```
Test `|` test

```md
Test ` | ` test
```
Test ` | ` test
![image](https://user-images.githubusercontent.com/133706/68479433-021cf680-023b-11ea-9d36-e18b775a18ca.png)
