### ISSUE TITLE
Feature request: Enable Emmet when editing HTML files

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#2489]
When the user is editing a file which has the `.html` extension, automatically activate [Emmet](https://emmet.io/) in the editor.

Example URL:
https://github.com/sindresorhus/refined-github/edit/master/source/options.html

**Comment by fregante** [comment]
This is an advanced non-GitHub-specific language-specific editor feature; it should be implemented as its own extension/userscript rather than in Refined GitHub

**Comment by fregante** [comment]
GhostText could be useful if you want more of your editor’s features https://github.com/GhostText/GhostText
