### ISSUE TITLE
blame parent useless when moving files

### ISSUE THREAD

**Issue by Ma27** [sindresorhus/refined-github#249]
Especially when relying on an autoloader and changing the namespace of a class, the ``blame parent`` feature becomes useless as it always refers to the same file.
During my work on #248 I had a short look at it and it will be quite difficult to fix as there's no information about file movements.

If anyone has an idea how to determine file movements (I failed in finding a well-working approach), I'd attempt to solve this in another PR.

**Comment by hkdobrev** [comment]
As far as I know this cannot be done from GitHub.com. It could be done with the shell using Git and it would be a nice addition to the Git tooling. I think we should accept the Blame parent links could not work in many cases without support from GitHub.com back-end. The feature is quite useful though in many cases for me. Sometimes it fails and I just default to manually finding the blame of the parent commit.

**Comment by Ma27** [comment]
ok, so we can close this...
