### ISSUE TITLE
Stop adding scroll bar on quoted blocks/images

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#2491]
1. With Redefined Github:
   1. ![image](https://user-images.githubusercontent.com/5332158/66932521-2572ce00-f00e-11e9-80fb-18cd88579edf.png)
1. Without:
   1. ![image](https://user-images.githubusercontent.com/5332158/66932609-43d8c980-f00e-11e9-886a-633fe160dd04.png)

Markdown of the post https://github.com/SublimeTextIssues/Core/issues/2150#issuecomment-542749182:
````
> After you see Sublime Text hanging, can open the menu `Tools -> Developer -> Profile Plugins` and post here the results? 
> ![image](https://user-images.githubusercontent.com/5332158/66932224-a7162c00-f00d-11e9-816b-5cd4811e3340.png)
> Can you also post the Sublime Text console output after Sublime Text hangs? (You can view the console by going on the menu `View -> Show Console`:
> ![image](https://user-images.githubusercontent.com/5332158/66932244-ada4a380-f00d-11e9-9df9-efdf17b460ec.png)
> https://forum.sublimetext.com/t/sublime-stuck-while-coding/46752
````

**Comment by fregante** [comment]
It’s a CSS feature that can be disabled with some CSS. Refer to

https://github.com/sindresorhus/refined-github/pull/1146#issuecomment-475872046
