### ISSUE TITLE
Issues, Pull Request: Filter unread

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#2492]
### where:
- in [issue list](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc)
- in [pull request list](https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)

### what i see:
- i can see rows marked as:
  - unread with a blue line and (css class `read`)
  - read without blue line (css class `unread`)
![Bildschirmfoto 2019-10-17 um 01 13 24](https://user-images.githubusercontent.com/184316/66966074-43771780-f07c-11e9-8f91-1d7ec066317b.png)

### what i expect:
- an button/setting to hide the read rows to only see the unread

### why: 
- i like to see all the new comments and new discussions in the repo

### known issues:
- i know this can result only in zero/one or some lines per page when too much is hidden. but this ok.

### search filter:
- i don't find a search filter how to filter only the unread messages - that would be the best solution ;)

**Comment by sindresorhus** [comment]
Is there a GitHub search filter for unread status? I couldn't find it: https://help.github.com/en/articles/searching-issues-and-pull-requests

**Comment by muescha** [comment]
I also can't find it there. I tried brute force for `is:read`/`is:unread` And with `status:`/`type:`/... But no luck :(

**Comment by sindresorhus** [comment]
Then you’ll have to send a feature request to GitHub: support@github.com We cannot do this until the search syntax is supported natively.

**Comment by muescha** [comment]
still requested Mandy times :/

But we can filter the result rows by:

- search result row divs for class: 'read'
- set this divs visibility to hidden

**Comment by fregante** [comment]
“Unread” threads are just notifications. Open the notifications page, by repo.

**Comment by muescha** [comment]
i can use it in notifications like: https://github.com/notifications/beta?after=Y3Vyc29yOjUw&query=repo%3Agatsbyjs%2Fgatsby+is%3Aunread+is%3Apr+is%3Aclosed

but there is not the function "open selected"

**Comment by muescha** [comment]
i can hide it with this line in console:
```javascript
document.querySelectorAll(".js-navigation-container:first-child div.Box-row:not(.Box-row--unread)").forEach(el => el.remove());
```

is there any way to add my own scripts into the "Refined Github" ecosystem to have some of the helper functions (api, libs, utils) available?

**Comment by TheGeniusSavant** [comment]
I would also like to see a sort option, something to the effect of...
`lastUpdatedBy:USERNAME`
...or...
`lastCommenter:USERNAME`
...that would accept a '!@me' USERNAME, perhaps?
