### ISSUE TITLE
File header takes less width than available in diff section

### ISSUE THREAD

**Issue by trivikr** [sindresorhus/refined-github#2496]
Confirmed that bug is caused by Refined GitHub, as it's not reproducible with the extension disabled.

URL here bug appears https://github.com/aws/aws-sdk-js-v3/pull/404/files/c76e142623095f22ade1532079a262d678877276..d481a6ab569e7bef240f9a8170ae14069e0f9e6a
* This issue happens in "changed since last view" URL, user will have view some files in previous diff to reproduce this issue.
* Not reproducible in default diff URL https://github.com/aws/aws-sdk-js-v3/pull/404/files

![file-header-less-space](https://user-images.githubusercontent.com/16024985/67225545-4c534a80-f3e8-11e9-96fc-09d324cb5daa.png)

![file-header-less-space-dev-tools](https://user-images.githubusercontent.com/16024985/67225557-5117fe80-f3e8-11e9-828b-e9f3d70940da.png)

**Comment by fregante** [comment]
Thanks for the report!

It’s being tracked in https://github.com/sindresorhus/refined-github/issues/2291

**Comment by trivikr** [comment]
Refs: https://github.com/sindresorhus/refined-github/issues/2291#issuecomment-517538323
