### ISSUE TITLE
Cannot read property 'addEventListener' of null

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2497]
on a private repos pull request detail page I get a js error 

https://github.com/complex-gmbh/kunzmann/pull/401

![grafik](https://user-images.githubusercontent.com/120441/67264288-f98e9700-f4aa-11e9-882e-8daa571176df.png)

using Version 80.0.3946.0 
Refined Github 19.10.13

**Comment by dertieran** [comment]
Duplicate #2334
