### ISSUE TITLE
More detailed fork list

### ISSUE THREAD

**Issue by TheLastZombie** [sindresorhus/refined-github#2498]
Sometimes, when a reasonably popular (but no longer updated) module no longer works properly, I check the list to see if anyone has got it working again. I usually look for forks which, in turn, have forks themselves to determine the most popular ones.

A more detailed list would make this a lot easier. Take GitHub's [dependency graph](https://github.com/github/fetch/network/dependents) for example:

![image](https://user-images.githubusercontent.com/8181990/67273453-bd653180-f4be-11e9-8d50-e379c793037c.png)

In addition to star and fork counts, the [/forks API endpoint](https://api.github.com/repos/github/fetch/forks) also returns when the repo was last updated etc.

In addition to that, one could add a sort button at the top, which would allow for sorting all forks alphabetically (GitHub default), by the most recent commit or by the most stars/forks.

Example URL: https://github.com/github/fetch/network/members

**Comment by fregante** [comment]
The Network page is already sorted by most recently-committed https://github.com/github/fetch/network

**Comment by fregante** [comment]
There’s also the Lovely Forks plugin that just shows the single most-starred fork if it’s more recent than the current repo. 

https://github.com/musically-ut/lovely-forks

You could ask them to show more forks, perhaps the 10 most starred forks, on the page you suggested.

 Only *sorting* usually isn’t useful because most forks are useless anyway.

**Comment by TheLastZombie** [comment]
Tried Lovely Forks for the past few days and it works really well for my case, thanks for the link. Closing this now.

**Comment by FranklinYu** [comment]
I was almost submitting similar feature request for sorting forks, before GitHub’s [related issues](https://github.blog/changelog/2018-11-05-related-issues/) guided me here. I like the extension Lovely Forks; would it make sense to be mentioned in “Related” section?

**Comment by fregante** [comment]
> would it make sense to be mentioned in “Related” section?

We can't mention them all. There are already lists for that:
https://github.com/collections/github-browser-extensions

**Comment by FranklinYu** [comment]
Then how about mentioning this list in the “Related” section? I wasn’t aware of this list.

**Comment by fregante** [comment]
We can't mention them all. There are already lists for that:
https://www.google.com/search?q=list+of+browser+extensions+for+github
