### ISSUE TITLE
Show real names in addition to handles.

### ISSUE THREAD

**Issue by jamestalmage** [sindresorhus/refined-github#250]
I've made incorrect assumptions about a persons real name from their handle before. There is plenty of space to show the real name in addition to the handle:

<img width="481" alt="screenshot 2016-06-15 13 31 21" src="https://cloud.githubusercontent.com/assets/4082216/16090549/f586a156-32fd-11e6-967d-68d41ce6cab6.png">

<img width="461" alt="screenshot 2016-06-15 13 31 39" src="https://cloud.githubusercontent.com/assets/4082216/16090553/f7b43e70-32fd-11e6-8f1c-23b3680dc827.png">

**Comment by sindresorhus** [comment]
Yes! I keep forgetting people's real name because I only see their username all day.

**Comment by DrewML** [comment]
This is one of the few features where I can't believe it's not already in the core product.

**Comment by paulmolluzzo** [comment]
> This is one of the few features where I can't believe it's not already in the core product.

I agree, this is such an obvious thing now that I see a screencap. In their defense, we haven't thought of it either though. 😛 

@DrewML I'd say more than a "few" though. I just looked over the readme and counted nearly a dozen that I forgot weren't in GH out of the box.

**Comment by lukehefson** [comment]
Hey hey!

Just for anyone watching – we added a version of this idea [natively to GitHub](https://github.blog/changelog/2019-06-24-organization-setting-for-profile-names-in-comments/)!

😍

**Comment by Lexicality** [comment]
That's so weird, why only private repos? Surely this should just be a per-user display option

**Comment by fregante** [comment]
@lukechilds I'm not seeing that in any of my organizations, was the feature removed?

**Comment by lukechilds** [comment]
@fregante I think you meant @lukehefson 😉

**Comment by lukehefson** [comment]
It wasn’t removed as far as I know. @fregante are the orgs on Team or Enterprise plans (not legacy per-repo plans)?

We scoped quite tightly to Team and Enterprise plans on private repos as we wanted to continue to encourage open source communities to use handles over full names. However, it’s definitely something that we might reconsider in the future so I’m always interest in y’all’s feedback!

**Comment by Lexicality** [comment]
@lukehefson A couple of thoughts:
- Why do you want to encourage usernames only? 
- It's more enforcement than encouragement if you don't provide the option? 🤔 
- Notification emails only use full names without any mention of the user's handle which has been confusing to me multiple times in the past and seems to go against the "usernames only" policy.
