### ISSUE TITLE
Remember "no-whitespace" setting 

### ISSUE THREAD

**Issue by zbstof** [sindresorhus/refined-github#2503]
If I click once on "no-whitespace", I shouldn't ever need to click on it again, until want to disable it.

That is to say, this setting should have global scope - across all repos and PRs

Example URL:
https://github.com/sindresorhus/refined-github/pull/2499/files ->
https://github.com/sindresorhus/refined-github/pull/2499/files?w=1

I know this has been opened before in #824, but Github has added comments in "no-whitespace" view since:
https://github.blog/2018-05-01-ignore-white-space-in-code-review/

I would add that this behaviour is a default in Gerrit.
https://gerrit-review.googlesource.com/Documentation/user-review-ui.html#ignore-whitespace

**Comment by sindresorhus** [comment]
We're are going to pass on this. The whitespace setting is meant to be temporary. If you ignore whitespace, you'll miss mistakes in PRs.

**Comment by hackel** [comment]
There definitely needs to be an option to remember the ignore whitespace setting.  You'll only miss "mistakes in PRs" if you're not using proper linting tools.  The job of a code reviewer isn't to manually check the syntax, it's to check logic, structure, etc.

**Comment by fregante** [comment]
This is not GitHub, Inc. Send your complaint to them if you want the Whitespace setting to stick. That’s a native GitHub feature.
