### ISSUE TITLE
Add "Expand whole file" option/button for each file in PR

### ISSUE THREAD

**Issue by zbstof** [sindresorhus/refined-github#2504]
Currently, if I want to understand the context in which change occurs I have several options, all of which have their own issues:
- I need to click `Expand Up`/`Expand Down` buttons
<img width="108" alt="Screen Shot 2019-10-26 at 9 15 14 AM" src="https://user-images.githubusercontent.com/1374723/67615151-273c4e80-f7d1-11e9-9d2a-2f584cceb8c1.png">
Problems: If relevant lines are too far away (like 100 lines above/below), I am doomed to click those for all eternity (it adds only 20 more lines per click)
- I can open the file in another tab `...` -> `View file`
Problems: I cannot use browser search to look for matches across files now, or I have to switch back-and-forth between tabs. And I also lose any PR comments in the file I opened this way.

I would like each file in PR to have a button which will expand the whole file and allow me to do browse text searches on all context without compromises.

One usability suggestion I would add - maybe if the file is not that large, then clicking `Expand Up`/`Expand Down` buttons would:
- on first click - works are normal
- on second click - expands the whole file (we can change icon/tooltip to reflect this)

This will avoid cluttering the interface with new buttons while keeping the intent.

Example URL:
https://github.com/sindresorhus/refined-github/pull/NNNN/files

**Comment by fregante** [comment]
You’re in luck! It’s already there 

https://github.com/sindresorhus/refined-github/pull/2434
