### ISSUE TITLE
Linkable labels in dashboard

### ISSUE THREAD

**Issue by NN---** [sindresorhus/refined-github#2509]
https://github.com/dashboard

There is 'Recent Activity' list in the dashboard.
Unfortunately labels are not linkable.
Expected behavior: Click on label opens issues filtered by label.

Workaround: open the issue and then click on the label in the issue.

**Comment by sindresorhus** [comment]
Accepted. PR welcome :)

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*
