### ISSUE TITLE
dim-bots dims human author commits

### ISSUE THREAD

**Issue by nmussy** [sindresorhus/refined-github#2517]
`dim-bots` (#2447) dims commits authored by humans, but committed by bots. See [aws-cdk](https://github.com/aws/aws-cdk/commits/master), which uses [mergify](https://mergify.io/):

![image](https://user-images.githubusercontent.com/2505696/68108641-9cea9d80-fee8-11e9-8c59-071678565e1d.png)

**Comment by nmussy** [comment]
I gave it a quick glance, and it doesn't look like there's anyway to tell an author and committer user apart, except for the tags position. Something like this selector will have to be used:
`.commit-author:not([href$="%5Bbot%5D"]):not([href$="renovate-bot"]) + .commit-author`

**Comment by fregante** [comment]
I think it just needs `:first-child` to be added so it only hides commits that have a bot listed _first_

```js

	const bots = select.all([
		/* Commits */
		'.commit-author[href$="%5Bbot%5D"]:first-child',
		'.commit-author[href$="renovate-bot"]:first-child',

		/* PRs */
		'.opened-by [href*="author%3Aapp%2F"]'
	].join());
```
