### ISSUE TITLE
Repository creation date

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#2526]
It would be nice if we could have a quick access to the repository creation date (to know if it's a recent or an old project).

Example URL:

github.com/user/repo

**Comment by sindresorhus** [comment]
I sometimes needed this too. Where should it be shown if so?

**Comment by yakov116** [comment]
@sindresorhus under the repo name

**Comment by sindresorhus** [comment]
@yakov116 I disagree. It's not important enough to clutter up that area. It should be in a more subtle place.

**Comment by fregante** [comment]
> I sometimes needed this too. Where should it be shown if so?

<img width="1006" alt="" src="https://user-images.githubusercontent.com/1402241/68539749-b729ed00-03ba-11ea-8705-1c4d82203f54.png">

This should be possible with this query, but for some reason it requires a `before` cursor. `history(first: 1)` works (but it's the latest commit, not the first)


```js
{
  repository(owner: "typelevel", name: "cats") {
    defaultBranchRef {
      target {
        ... on Commit {
          history(last: 1) {
            nodes {
              committedDate
            }
          }
        }
      }
    }
  }
}
```

**Comment by Androz2091** [comment]
I don't know how the extension works, it was just a suggestion that I can't make myself but I see a `created_at` property when I use the REST API to get repository informations (for example https://api.github.com/repos/Androz2091/AtlantaBot) with only one query. Wouldn't it be better to use that?

**Comment by fregante** [comment]
> I see a `created_at` property when I use the REST API

Duh. Indeed. It should be pretty easy to implement then. Ideally this information should be found on the GraphQL API though. Only as a last resort we should use the REST API.



> Knowing that the first commit is not necessarily equal to the date of creation of the project, right?

Technically I'd say that the first commit is **the** birth of the project. I think `created_at` is the time you created a GitHub repo but one could create a GitHub repo long after starting work locally.

However this is kind of a nitpick so `created_at` should be good enough.

**Comment by yakov116** [comment]
@fregante 

```graphql
{
  repository(owner: "sindresorhus", name: "refined-github") {
    createdAt
  }
}
```
=>
```graphql
{
  "data": {
    "repository": {
      "createdAt": "2016-02-15T16:45:02Z"
    }
  }
}
```

**Comment by maxmclau** [comment]
I like the idea of this, I'm going to give adding it a shot. Does anyone have issues with @fregante's idea of adding it to the stats/number's bar?

**Comment by maxmclau** [comment]
<img width="1000" alt="Screen Shot 2019-11-20 at 5 16 48 PM" src="https://user-images.githubusercontent.com/3848317/69256318-95e6af00-0bb9-11ea-84c8-c6996d39da80.png">


This is using the repo's `created at` value, but I'd like to base it off the time of first commit as discussed

**Comment by Androz2091** [comment]
Wow, that's awesome. Personally, the date of creation of the repository is perfect for me.

**Comment by fregante** [comment]
> This is using the repo's `created at` value, but I'd like to base it off the time of first commit as discussed

As long as it can be determined in one HTTP request

**Comment by CrypTO-BtSB** [comment]
You can find the date out by doing this:
{
  repository(owner: "owner_name", name: "repo_name") {
    defaultBranchRef {
      target {
        ... on Commit {
          history(last: 1) {
            nodes {
              committedDate
            }
          }
        }
      }
    }
  }
}

**Comment by CrypTO-BtSB** [comment]
{
  repository(owner: "CrypTO-BtSB", name: "get_creation_date") {
    createdAt
  }
}
