### ISSUE TITLE
Merge status information is hidden

### ISSUE THREAD

**Issue by MaximDevoir** [sindresorhus/refined-github#2527]
Some merge status information is hidden while the GitHub Redefined (GR) extension is enabled.

Merge status with GR enabled:

![merging-with-RG](https://user-images.githubusercontent.com/10104630/68549246-13851080-03ab-11ea-8a4d-8d9518b7c8c8.png)

Merge status with GR disabled:

![merging-without-RG](https://user-images.githubusercontent.com/10104630/68549252-1e3fa580-03ab-11ea-8fef-18049b0b5a1e.png)

No URL to reproduce this :( but the problem seems to be stemming from

https://github.com/sindresorhus/refined-github/blob/7ba1fe2af7ca3b0b7e1a8661bfcfd428dbae2618/source/features/clean-mergeability-box.css#L3-L6

This may be "clean", as the source file responsible for this is named, but it is took me a while to figure out why merging was blocked.

**Comment by fregante** [comment]
Indeed, perhaps we need to restore the last line, it’s the only one that includes non-redundant information about the blocked merged. PR welcome to adjust the selector, if it’s possible.
