### ISSUE TITLE
Idea: Have an obvious badge for "draft" pr's in the list of open pr's

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2531]
The grey colored PR logo and tiny *Draft* text in the subtitle are just not very visible and eye catching!

![draft](https://user-images.githubusercontent.com/9874850/68629841-927e6400-04e5-11ea-830d-b6c454fb7f65.png)

Addon version: 19.11.10

**Comment by fregante** [comment]
Indeed! We agree

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/2450

**Comment by tooomm** [comment]
Thanks for linking the other request! I couldn't find it
