### ISSUE TITLE
Button to `@` mention in discussion

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2532]
We could add a button to quickly mention someone. It can either go by the "Edit comment" button or near/below the user/avatar, as such:

<img width="359" alt="" src="https://user-images.githubusercontent.com/1402241/68647928-aeb7ea80-0551-11ea-8e91-5d5f1ff7b128.png">

Clicking it would instantly `@mention` the user and focus the comment field, like the <kbd>r</kbd> key does when quoting the selection.

This would also be a solution/replacement for https://github.com/sindresorhus/refined-github/issues/1003 and fix the _annoyance_ caused by [`show-names`](https://github.com/sindresorhus/refined-github/issues/2165) (it makes it harder to copy-paste usernames)

**Comment by jerone** [comment]
If anyone is interested, I maintaining the [Github Reply Comments](https://github.com/jerone/UserScripts/tree/master/Github_Reply_Comments#readme) userscript.

**Comment by fregante** [comment]
It’s not clear what that does. What does “reply to a comment” entail? Why does it depend on a markdown parser?

**Comment by jerone** [comment]
[**@fregante**](https://github.com/fregante) commented on [Nov 12, 2019, 1:17 PM GMT+1](https://github.com/sindresorhus/refined-github/issues/2532#issuecomment-552869404 "2019-11-12T12:17:02Z - Replied by Github Reply Comments"):
> It’s not clear what that does. What does “reply to a comment” entail? Why does it depend on a markdown parser?
> 
> I think it’s different from what is being asked here.

It adds the content above ⬆. The Markdown parser is there to support (most) Markdown syntax.

**Comment by fregante** [comment]
You should probably include that in the readme or screenshot. 

Anyway the feature I’m suggesting only includes the username, e.g. 

@jerone

**Comment by Tiramisu77** [comment]
Maybe add this behavior to alt click on username instead of making it a button?

**Comment by fregante** [comment]
Currently we use only such shortcut to mean "click this and all the buttons like this," it's not great for discoverability.

I'd rather show the button on hover rather than hide it under a click modifier.

**Comment by fregante** [comment]
PR ready
