### ISSUE TITLE
Visual Issues When Scrolling Down in "Files" view in PR

### ISSUE THREAD

**Issue by macintacos** [sindresorhus/refined-github#2534]
When you're dealing with files that have long names, Refined Github seems to not render properly when you scroll down. 

1. The issue is caused by RG; disabling the extension resolved the issue and it renders properly. 
2. The URL for a page where you'd see this is the "Files" page of a PR, e.g. https://github.com/username/repo/pull/pr#/files
3. [Screenshot of RG when it's _on_](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/12uEjJO0/Image+2019-11-12+at+09.43.11.png?v=6122a955aa1e43a875e9432c6cd79ea2) - [Screenshot when RG is _off_](https://p-37FYgJ.b1.n0.cdn.getcloudapp.com/items/12uEjJJo/Image+2019-11-12+at+09.46.29.png?v=ef40c5e598c93b81522bc06d6cc4b17b).

**Comment by fregante** [comment]
Thank you for the report. It’s being tracked in https://github.com/sindresorhus/refined-github/issues/2291
