### ISSUE TITLE
Display `May be fixed by` on discussion lists

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#2535]
Example URL: https://github.com/sindresorhus/got/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

![image](https://user-images.githubusercontent.com/36894700/68700484-47b42900-0585-11ea-83cc-ffa52a2ae084.png)

It would be useful to see `May be fixed by #...` here

**Comment by fregante** [comment]
This would be lovely but unless this information is exposed via the API the only way I can think of is to fetch each issue’s HTML page separately and parse that information. We can’t fetch 20 pages

**Comment by sindresorhus** [comment]
If it's not exposed through the API, it's definitely worth emailing support@github.com to suggest it.

**Comment by szmarczak** [comment]
I'll email them :fire:

**Comment by szmarczak** [comment]
![Screenshot_20191115-131105_Gmail](https://user-images.githubusercontent.com/36894700/68942779-ae199100-07a9-11ea-99c7-4fdab9c3b76b.png)

**Comment by fregante** [comment]
Closing as impossible at the moment, sadly.

The API doesn't show this piece of information: https://developer.github.com/v4/interface/closable/

**Comment by fregante** [comment]
Yo! GitHub did it! There's also the reverse for PRs (i.e. "this will close x issues")

<img width="910" alt="" src="https://user-images.githubusercontent.com/1402241/73771027-162bb200-47b0-11ea-8127-11c2df5ade33.png">

Time to drop our "has pr" label

**Comment by szmarczak** [comment]
Great news! :D
