### ISSUE TITLE
Approve / Reject buttons should show your current approval status

### ISSUE THREAD

**Issue by ProLoser** [sindresorhus/refined-github#2537]
Sometimes I double check if I've already approved a PR or if it was waiting for changes (with a rejection) or if I just made comments. It would be nice to not have to switch back to the comments page to see what the PRs current approval status is.
![image](https://user-images.githubusercontent.com/67395/68703022-a99d7000-053e-11ea-8f55-dd307b3982f8.png)

I was thinking if you already approved the PR, the 'approve' button appeared already pressed. Alternatively it would be nice to see the current 👍 👎 stats much like you see reactions to the left of the buttons:

`1 (you) 👍 1 👎 [Comment] [Request Changes] [[Approve]]`
or
`[Comment] [Request Changes (1)] {Approve (you+1)}`

**Comment by fregante** [comment]
How do you end up on the Files tab without coming from the Discussion tab? Like, why are you there if you don’t know whether you need to review at all.
