### ISSUE TITLE
Important conflict resolution instructions filtered out by Refind Github

### ISSUE THREAD

**Issue by archon810** [sindresorhus/refined-github#2541]
Without RG:
![image](https://user-images.githubusercontent.com/469543/68829742-8bc72c80-065e-11ea-9185-47ebb373253e.png)

With RG:
![image](https://user-images.githubusercontent.com/469543/68829727-7d791080-065e-11ea-9abe-3472bb788e19.png)

Why is RG filtering out these important PR conflict resolution instructions?

This issue is similar to https://github.com/sindresorhus/refined-github/issues/963, but has a more severe impact IMO.

**Comment by fregante** [comment]
The CSS that affects this is the same as https://github.com/sindresorhus/refined-github/issues/2527

**Comment by fregante** [comment]
Why is it missing the Resolve conflicts button? In my case I see the button and it includes that notice, rendering this specific issue (the lack of explanation) void

<img width="754" alt="" src="https://user-images.githubusercontent.com/1402241/68832419-721bf880-06e3-11ea-9939-e56569a309fb.png">

**Comment by archon810** [comment]
I'm not sure. Perhaps because it was a merge across repos?

**Comment by fregante** [comment]
Are you on GitHub Enterprise?

**Comment by archon810** [comment]
No, just regular free github.
