### ISSUE TITLE
Make `Fixes` tooltip show the title of the issue

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#2543]
Example URL: https://github.com/sindresorhus/got/pull/921

![image](https://user-images.githubusercontent.com/36894700/68957505-7b33c500-07ca-11ea-9a62-ffe46f606e8c.png)

Expected:

<code>This pull request closes issue #925: Don't throw on `204 No Content` when parsing response</code>

It's quite similar to https://chrome.google.com/webstore/detail/github-hovercard/mmoahbbnojgkclgceahhakhnccimnplk (see the 4th screenshot)

**Comment by fregante** [comment]
It's already there for _all_ issue links.

<img width="444" alt="" src="https://user-images.githubusercontent.com/1402241/68964986-4dbc3b00-080d-11ea-89c4-1407128979b0.png">

**Comment by szmarczak** [comment]
Then the tooltip is useless I think :P

**Comment by szmarczak** [comment]
Consider reopening the issue. Showing the big tooltip instead of the small one would be nice IMO.

**Comment by fregante** [comment]
If it’s considered obvious it can be hidden (we already hide many tooltips like that) but I noticed that many people don’t even know about that keyword so it’s good to keep it. 

The tooltip and the hovercard are for two separate pieces of information and IMHO it doesn’t make much sense to show the issue information while hovering the `fixes` keyword.

**Comment by szmarczak** [comment]
> The tooltip and the hovercard are for two separate pieces of information

Then why not merge them into one? Just place `This pull request closes issue #...` above the [tooltip] issue title.

**Comment by yakov116** [comment]
I think its important to show this info it teaches people how to open a pull request that will close another issue

**Comment by szmarczak** [comment]
> I think its important to show this info it teaches people how to open a pull request that will close another issue

> Then why not merge them into one?

**Comment by fregante** [comment]
Why *do* merge into one? Just because they’re both important it doesn’t mean that they should be merged. One appears on the issue, like everywhere on the site. The other one appears on the trigger word. I don’t think it’s worth the time to merge them.

**Comment by szmarczak** [comment]
Sometimes I just hover on the `Fixes` text (the cursor is only a few pixels away from `#...`) and I'm annoyed that I have to move my mouse again just to point at `#...` 

Anyway, if you think these shouldn't be merged, feel free to close this issue.

**Comment by fregante** [comment]
What you say makes sense and I too am mildly annoyed by the two different tooltips, but:

1. Moving that information inside the large hovercard will get lost in the rest of the text
2. It's such a nitpick that IMHO it's not worth the discussion/complexity of code and UI

**Comment by szmarczak** [comment]
Hmmm. Fair point 🙂 Anyway, I'll try to do this. I don't think this would be to complicated, but I may be wrong.
