### ISSUE TITLE
Notifications beta: Mark as Done, and Save

### ISSUE THREAD

**Issue by danielcompton** [sindresorhus/refined-github#2546]
The [GitHub Notifications beta](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/about-notifications-beta) introduces a new inbox metaphor for notifications. There is also a new "Done" state that a notification can be in. You can manage this from within the notifications view, but if you are in "normal" GitHub, then there is no way to mark a notification as "Done".

Example URL:

Any issue or PR page, e.g. https://github.com/technomancy/leiningen/issues/2566.

For example (but with full-width buttons):

<img width="299" alt="Screenshot of Google Chrome (18-11-19, 3-19-30 PM)" src="https://user-images.githubusercontent.com/811954/69019755-d659f780-0a16-11ea-8c4b-3a2c8fb3bd32.png">

**Comment by fregante** [comment]
Can you try something for me? What happens when you have a notifications and then you open the issue in "normal" GitHub? Doesn't that automatically mark it as "done"?

Also it's probably best to suggest this to GitHub themselves since it's still in beta. We'd all love a Save button that replaces our "Mark as read" (which will be completely broken once the new notifications are out of beta)

**Comment by fregante** [comment]
> What happens when you have a notifications and then you open the issue in "normal" GitHub? Doesn't that automatically mark it as "done"?

I checked, the notification is marked as Read like before, but not as Done.

---


As for this feature, we can't display any of those buttons unless there's a notification for it **and** we know its Notification ID.

There's no API to find out, unless we list ALL the notifications, maybe over multiple pages. This would need to happen for every single issue you open.

Plus we need to fetch the Authenticity token from the form in `/notification`.

I don't think they're worth all this extra traffic, if you want them it's best to ask GitHub (who are hopefully already looking into it. cc @lukehefson)
