### ISSUE TITLE
Shortcut for editing issue/comment text in-place

### ISSUE THREAD

**Issue by sarpik** [sindresorhus/refined-github#2547]
Hello,

I've got a [long roadmap as a single issue](https://github.com/sarpik/turbo-schedule/issues/1). I update it oftenly. Sometimes I find something that needs to be edited somewhere down in the text, and if I want to edit it - I have to scroll all the way up to find the "Edit" button, click it, scroll back down and find what I wanted to edit.

I thought it'd be great if you could have some shortcut, for example <kbd>Shift</kbd> + <kbd>Mouse1</kbd>, which would allow you to hold shift and click exactly on where you want to edit inside the issue description / comment etc, and get into edit mode with your cursor placed where you clicked.

Would that be possible to do? 

Thank you for the great extension btw - it's been great for a while now:) 

Example URL:

https://github.com/sarpik/turbo-schedule/issues/1

P.S.

I know that this way of setting up a roadmap might not be the best approach, but I'm just trying to illustrate a point that you sometimes have some long text, and editing it is a little annoying. Thanks:)

P.P.S.

Having the `Update comment` button available in your view without having to scroll down would be great too:D

**Comment by staabm** [comment]
Alternative Ideas: Maybe it would make sense to keep the comment header sticky, so the edit button is reachable without scrolling all the way back

**Comment by fregante** [comment]
Preserving scroll position between two versions (rendered vs markdown) is not something we can easily do.

For your usecase specifically, I suggest at least splitting that list into multiple comments, so you can **Edit** each section separately
