### ISSUE TITLE
 Sort commits topologically first instead of by author date

### ISSUE THREAD

**Issue by graingert** [sindresorhus/refined-github#2548]
https://github.com/isaacs/github/issues/386
Example URL: https://github.com/sindresorhus/refined-github/pull/2513/commits

**Comment by sindresorhus** [comment]
I don't think we can easily do this as to correctly to it, we would have to sort across pages, which would be very difficult to implement correctly.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by graingert** [comment]
That is a shame, the main place in want it is the next/previous buttons on the PR

**Comment by fregante** [comment]
Unless GitHub has a URL parameter to achieve this, we'd have to not only manage pagination, but also **recreate the whole UI around the commits** we have to fetch and sort from the API.

Closing as impossible to achieve (i.e. way out of Refined GitHub's scope)
