### ISSUE TITLE
Merge the several events when different users start following a single user

### ISSUE THREAD

**Issue by GaurangTandon** [sindresorhus/refined-github#2550]
Right now, on my dashboard, the following events exist:

```
UserA started following UserC
UserB started following UserC
UserC started following UserA and UserB
```

As you can see the last two events are cleanly merged into one.

So, is it possible to also merge the first two events? I would imagine something like: `UserA and UserB started following UserC`. Criterion of merging such events could be anything: if the events occur within one hour of each other, or simply if they are consecutive in the dashboard feed.

**Comment by sindresorhus** [comment]
Please also send this feature request to GitHub: support@github.com

**Comment by fregante** [comment]
"Follow" events are hidden by default https://github.com/sindresorhus/refined-github/blob/f6bc74d48707a74ca18c0300e30c225d639c2f13/source/features/hide-useless-newsfeed-events.css#L12

**Comment by GaurangTandon** [comment]
@fregante Thanks but I there was a checkbox in the settings that allowed users to display "Follow" events. I was just talking about such types of users. It could be a useful feature to add.
