### ISSUE TITLE
Copy PR as a dependency git URL

### ISSUE THREAD

**Issue by dominykas** [sindresorhus/refined-github#2552]
At the moment, GitHub already provides a copy button to copy the branch name of the PR.

It would be awesome, if there was also a button to copy the full git URL for that branch, so that it can be used in `package.json`, e.g. for the `new-feature` branch in this repo, it would copy `git+https://github.com/sindresorhus/refined-github.git#new-feature` into clipboard.

npm does support GitHub shorthands (e.g. `sindresorhus/refined-github#new-feature`), but that's not very useful for those on GitHub Enterprise.

**Comment by fregante** [comment]
This feature request is too specific to a language and workflow.

The closest you can get is https://github.com/sindresorhus/refined-github/issues/963, which will restore the button to copy the git URL and then you can click to copy the branch name with the other copy button in the header

**Comment by dominykas** [comment]
Do other package managers not offer ways to install from git? Could the feature be adapted to work for them as well, assuming they use a different format?

**Comment by fregante** [comment]
I think those 2 clicks would have to suffice
