### ISSUE TITLE
Set <title> when viewing a beta notification 

### ISSUE THREAD

**Issue by danielcompton** [sindresorhus/refined-github#2555]
When viewing a notification in the new beta notifications feature, the <title> of the window is just "Notifications". If you have several notifications open, it makes it difficult to find which one you were looking for.

`https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDQyMjY0MjY5Njo4MTE5NTQ=?query=is%3Aunread`

<img width="246" alt="Screenshot of Google Chrome (20-11-19, 1-45-27 PM)" src="https://user-images.githubusercontent.com/811954/69199158-10a0d180-0b9c-11ea-84b0-74f46b54ee3d.png">

My suggestion is that the title of the window is updated to match the name of the issue/PR that you're looking at, like regular issues are.

`https://github.com/tobias/dynapath/issues/12`

<img width="394" alt="Screenshot of Google Chrome (20-11-19, 1-45-43 PM)" src="https://user-images.githubusercontent.com/811954/69199162-14ccef00-0b9c-11ea-9c4a-2419538a0788.png">

Perhaps you'd also add " - Notification" to the end of it to distinguish the tab from an issue view.

Example URL: https://github.com/notifications/beta/MDE4Ok5vdGlmaWNhdGlvblRocmVhZDQyMjY0MjY5Njo4MTE5NTQ=?query=is%3Aunread

**Comment by sindresorhus** [comment]
We are not in the beta, so we cannot do anything about this until it’s out of beta. I would strongly recommend that you suggest this using the feedback link in the notifications beta.

**Comment by danielcompton** [comment]
Sorry, I should have mentioned I did suggest this change in the beta, but it was declined.

**Comment by fregante** [comment]
They did it. Also thankfully the URL is not under `/notifications/` but it's from the real issue 🎉 so all our features work

<img width="858" alt="title tag in notifications beta" src="https://user-images.githubusercontent.com/1402241/74756273-434b8a80-52af-11ea-91c9-4a056e12208a.png">
