### ISSUE TITLE
Filter trending repository

### ISSUE THREAD

**Issue by dikiaap** [sindresorhus/refined-github#2557]
Filter the list of [trending repos](https://github.com/trending) based on their description to hide repos that have the majority non-Latin alphabetic characters (eg. CJK, Arabic, Hebrew, Cyrillic, etc.). Sometimes I just read the repository name and open it but then I can't read the contents.

`Default: off`

**Comment by fregante** [comment]
I feel the pain but we can’t hide these by default. If it’s not on by default most people won’t use it and thus we don’t need it in Refined GitHub. 

I think we’ll just have to visually ignore them (or create a standalone userscript/extension)

**Comment by fregante** [comment]
Good news! GitHub supports this natively https://github.com/settings/profile#trending-settings-heading

Set it to English

<img width="718" alt="" src="https://user-images.githubusercontent.com/1402241/70937080-4db29380-2076-11ea-8052-216deccad3dd.png">
