### ISSUE TITLE
Make the dropdown of GitHub Actions a single button, if there's only one action

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/refined-github#2561]
[Here](https://github.com/sindresorhus/refined-github/commit/0ae4e39ec1d10e88cf8605a6a0536cbdc5c50fe0/checks?check_suite_id=321434835) you should see a dropdwon "Re-run checks", which has only one item "Re-run all checks". I propose to make the dropdown a button "Re-run all checks" directly. At least for now, until we get more items in that dropdown.

More: https://twitter.com/tunnckoCore/status/1197456822891896833

**Comment by fregante** [comment]
This feature should be something like:

```js
if dropdown has 1 action
	add 'btn' class to action
	dropdown.replaceWith(action)
```

**Comment by mehrdadn** [comment]
Just wanted to request that there also be a button for canceling the run :)

**Comment by tunnckoCore** [comment]
@fregante true.

**Comment by tunnckoCore** [comment]
<3
