### ISSUE TITLE
Merge multiple pull request

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#2563]
I have several projects and I use DependaBot for dependency management. I usually have about fifteen pull requests per month and I have to merge them on all my projects. I don't know if it's possible, but a "Merge selected pull request" button would be very useful to save time!

Example URL:

https://github.com/user/repo/pulls

**Comment by fregante** [comment]
Batch-merging PRs is not advisable. If you want to automatically merge bot PRs you can probably use another bot to do so

**Comment by Androz2091** [comment]
Why is it not advisable? I don't want the merge automatically I want two or even three merge at once

**Comment by sindresorhus** [comment]
It's also a security issue, as merging without looking at the diff, means a bot can easily sneak in some malicious code.
