### ISSUE TITLE
Clear PR merge commit description field

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2564]
On PRs, when squashing, the commit description is filled with every commit's title.

I think that if you squash, probably aren't interested in _every commit's title_ and should therefore be dropped. If they're useful, maybe you should merge or rebase instead, IMHO.

Thoughts?

Perhaps we should just preserve a deduplicated list of `Co-authored-by`

# Currently

<img width="757" alt="" src="https://user-images.githubusercontent.com/1402241/69406614-0a922880-0d35-11ea-9262-1e21e731881c.png">

# Expected

<img width="756" alt="" src="https://user-images.githubusercontent.com/1402241/69406863-acb21080-0d35-11ea-8449-33c1c9c49081.png">

**Comment by sindresorhus** [comment]
I sometimes find it useful to be able to quickly scan what commits are included in the squash and I do think we should preserve a deduplicated list of co-authors. How about we present a list of commit titles underneath or something? So I can still scan it, but it's not included by default.
