### ISSUE TITLE
Add hover-cards for popular website-links in comments

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2565]
could refined github add popup/hover-cards for popular urls, like e.g. twitter

**expected result:**
a url like https://twitter.com/markusstaab/status/1197832308470034433 when used in e.g. a comment should open a card-overlay on mouse-over.
the card-overlay could/should contain the schema.org defined properties like `og:title`, `og:image`, `og:description` etc. like e.g. popular chat systems do (slack, mattermost)

that way people can get a impression on what the actual link will provide/contain without leaving github.com

**example how mattermost renders a similar feature:**
![grafik](https://user-images.githubusercontent.com/120441/69421140-8afa5e80-0d20-11ea-9656-7d74aca5364c.png)

this feature could be used for several services (as long as the `og:*` schema is supported by the website) but should not open hover-cards for all links (for security reasons) but just whitelisted domains.

examples I can think of righw now are
- stackoverflow
- medium

**Comment by busches** [comment]
This seems something that should exist as it's own extension and apply to multiple websites.

**Comment by fregante** [comment]
I totally thought about the same thing. This is a big feature and it would have to include an open graph parser and wide permissions to fetch each page.

**Comment by fregante** [comment]
Interesting feature nonetheless. Perhaps suggest it to https://github.com/sindresorhus/module-requests
