### ISSUE TITLE
`remove-diff-signs` not active inside markdown

### ISSUE THREAD

**Issue by sarpik** [sindresorhus/refined-github#2569]
I'm not sure if this is the expected behaviour,
but the diff (+-) signs are shown inside markdown,
for example inside README's or issue/PR descriptions/comments etc.

* README's

* Sample pr description: https://github.com/sindresorhus/refined-github/pull/1866

* here:

```diff
- the +- signs
+ seem to be showing up here
```

And once you copy the selection, they're not removed.

![image](https://user-images.githubusercontent.com/29430509/69482878-62aa5700-0e29-11ea-9414-55a363c30be9.png)

**Comment by fregante** [comment]
Yeah we decided to leave those visible to make people realize they’re copy-pastable

https://github.com/sindresorhus/refined-github/pull/1866#issuecomment-475528334

**Comment by sarpik** [comment]
Oh I missed that comment, sorry.

> I don't think people would realize they could still copy-paste it and use it as a .diff with Git if they don't see the + and -.

Yeah that makes sense since it's a diff.

I'd love a feature from github where you could select whether or not you want the +- signs to appear, but that's outside the scope of this extension:D

Thank you!
