### ISSUE TITLE
Hitting browser 'back' to a project page displays as if signed out

### ISSUE THREAD

**Issue by coreyfarrell** [sindresorhus/refined-github#2570]
To reproduce:
1. Make sure you are signed in to github.
2. Navigate to https://github.com/sindresorhus/refined-github/
3. Click "Issues"
4. Hit browser "back" button.

At this time the display will (falsely) indicate that you are not signed in:
![Screenshot from 2019-11-24 07-33-27](https://user-images.githubusercontent.com/903597/69494723-eea19a80-0e8c-11ea-939e-6d91185628e4.png)

Refresh the page and it shows that you are signed in again.  This only seems to happen when hitting 'back' to the main project page, it doesn't happen when the back button brings you to issues or PR's for example.

I'm seeing this on firefox-70.0.1-4.fc30.x86_64 (Fedora 30).

**Comment by fregante** [comment]
This is not something we can or should fix. Please report it to GitHub if it keeps happening

**Comment by coreyfarrell** [comment]
This only happens if Refined-Github is enabled.  I verified that disabling the extension makes the issue stop.

**Comment by fregante** [comment]
I use the same browser and it doesn't happen to me; We don't interfere with cookies nor web requests, the extension should not affect GitHub's `fetch`

Are you a new Refined GitHub user? When did it start happening?

**Comment by coreyfarrell** [comment]
I'm a new user of Refined GitHub so I can't say when this started.  I do have github.com in a container using "Firefox Multi-Account Containers".  This multi-account containers is the only thing I cannot easily disable as doing so is very destructive to the browser profile.

**Comment by fregante** [comment]
That's more likely to be the cause. I just tried installing that one too and I can't reproduce the issue either when using a container

**Comment by fregante** [comment]
From your screenshot, it looks like the whole page is being reloaded without cookies, so the containers are more likely to be the cause. This extension’s permissions literally cannot mess with cookies.
