### ISSUE TITLE
View and Raw links on files in PR are broken

### ISSUE THREAD

**Issue by GolezTrol** [sindresorhus/refined-github#2571]
Refined github adds a View File and View Raw links to a file in a pull request
The URLs for these have the pattern:
https://github.com/[organisation]/[repository]/[blob]/[user]:[branch]/[path]
https://github.com/[organisation]/[repository]/[raw]/[user]:[branch]/[path]

These links don't seem to work anymore. With the extension disabled, I only get Github's own View link, which does work and points to:
https://github.com/[organisation]/[repository]/blob/[somehash]/[path]

From there you can click to raw, which points to:
https://raw.githubusercontent.com/[organisation]/[repository]/[somehash]/[path]

I'm not sure this hash is easy to come by, but if not, maybe a solution could be to link to the branch on the fork instead?

https://github.com/[user]/[repo]/tree/[branch]

https://github.com/[user]/[repo]/raw/[branch]/[path]

**Comment by fregante** [comment]
Thank you for the report! How ironic that a feature called `fix-view-file-link-in-pr` was _breaking_ those links 😬

In the future, it's easier to just paste a real URL so I can just click it and see the bug 😄  (plus it's easier for you to report!)
