### ISSUE TITLE
Comment edit icon hides in the dots menu after you react to a comment

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/refined-github#2572]
1. yes, it's Refined GitHub
2. Happens in all repos
3. screenshots below

before

![image](https://user-images.githubusercontent.com/5038030/69653612-2cb0e100-107c-11ea-8603-9ec7346db8e2.png)

after

![image](https://user-images.githubusercontent.com/5038030/69653646-3afefd00-107c-11ea-9e4b-d1e97bf22fb6.png)

**Comment by fregante** [comment]
Other features also affected by this:

- `show-names`
- `shorten-links`
- `reaction-avatars` (... strange, I thought I fixed this in #2533!)

**Comment by yakov116** [comment]
@fregante 

https://github.com/sindresorhus/refined-github/blob/073b65379a8e5f6a6cb1597b2339416d30a25686/source/libs/on-new-comments.ts#L44

Adding `subtree: true` will work it would also fix #2852 

Is this a good idea or allowing it to run on subtree is too much?

**Comment by fregante** [comment]
`subtree` isn't allowed, our events needs to be specific, I don't want to listen to every change on the page.

**Comment by yakov116** [comment]
Any other idea's?

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/blob/073b65379a8e5f6a6cb1597b2339416d30a25686/source/libs/on-updatable-content-update.ts is my last attempt at handling ajaxed contentainers, but I'm not sure if would work in this case.

Ideas come from looking for events in GitHub's code. Sometimes we use those events to start `observ`ing new elements.
