### ISSUE TITLE
Remove is:open/is:closed issue search query with a click

### ISSUE THREAD

**Issue by mikhaelkh** [sindresorhus/refined-github#2574]
<table><td>
@fregante said:
<tr><td>
For the bounty:

1. Use this https://github.com/sindresorhus/refined-github/issues/2574#issuecomment-559944187
2. Remove icons as suggested in https://github.com/sindresorhus/refined-github/issues/2574#issuecomment-564284650
3. Add `is:merged` filter in PRs

</table>

[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2415%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2574)

To see all issues (open and closed) you need to manually remove is:open/is:closed search query. Maybe add "All" next to "Open", "Closed", with or without counter, to remove this query with a click?

Example URL:
https://github.com/sindresorhus/refined-github/issues

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $15.00)

- [<img src='https://avatars3.githubusercontent.com/u/1402241?v=4' alt='fregante' width=24 height=24> fregante](https://issuehunt.io/u/fregante) ($15.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by muescha** [comment]
i also like to remove the `is:pr` and `is:issue` and leave the `sort:updated-desc`:

![Bildschirmfoto 2019-11-30 um 01 57 11](https://user-images.githubusercontent.com/184316/69893636-c397ca80-1314-11ea-87d3-2bbfae9f438d.png)

the one click link under the search bar reset it to `is:pr is:open` if i am in PR :(

**Comment by jerone** [comment]
[**@muescha**](https://github.com/muescha) commented on [Nov 30, 2019, 1:58 AM GMT+1](https://github.com/sindresorhus/refined-github/issues/2574#issuecomment-559900976 "2019-11-30T00:58:46Z - Replied by Github Reply Comments"):
> i also like to remove the `is:pr` and `is:issue` and leave the `sort:updated-desc`:
> 
> [![Bildschirmfoto 2019-11-30 um 01 57 11](https://user-images.githubusercontent.com/184316/69893636-c397ca80-1314-11ea-87d3-2bbfae9f438d.png)](https://user-images.githubusercontent.com/184316/69893636-c397ca80-1314-11ea-87d3-2bbfae9f438d.png)
> 
> the one click link under the search bar reset it to `is:pr is:open` if i am in PR :(

There is an useful UserScript for that: [GitHub Latest](https://github.com/Ede123/userscripts/blob/master/GitHub_Latest.md).

**Comment by fregante** [comment]
> i also like to remove the `is:pr` and `is:issue` and leave the `sort:updated-desc`:

https://github.com/sindresorhus/show-all-github-issues

**Comment by fregante** [comment]
> remove this query with a click?

I think we can just replace the selected **Open** or **Closed** link:

<img width="310" alt="Screenshot 2019-11-30 at 17 27 47" src="https://user-images.githubusercontent.com/1402241/69899313-db179780-1396-11ea-950b-d4174178bd7c.png">

In this case, the **Open** links to the same page you're on, which is useless. 

---

On https://github.com/sindresorhus/refined-github/issues?q=is%3Aopen+is%3Aissue, if the **Open** (or **Close**) link has the same query as the search field (`new URL(link.href).searchParams.get('q') === select('#js-issues-search').value`) then it should be replaced from:

- https://github.com/sindresorhus/refined-github/issues?q=is%3Aopen+is%3Aissue

to: 

- https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue

**Comment by gurrrung** [comment]
> On [sindresorhus/refined-github/issues](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), the **Open** link should be replaced from:

Open button will show all the queries this ways (which I don't felt intuitive), I think adding a all button is much better.

**Comment by fregante** [comment]
1. Open an issue that has a `bug` label
2. Open the label selector
3. Click `bug`

What happens? The bug label is deselected.

This is the same behavior I'm suggesting here: clicking Open (or Closed) will _deselect_ it.

**Comment by mikhaelkh** [comment]
That sounds good, but the downside of this approach is that it is silent. You need to read changelog or stumble on this change by accident to know that now it's working.

**Comment by fregante** [comment]
> That sounds good, but the downside of this approach is that it is silent. You need to read changelog or stumble on this change by accident to know that now it's working.

We have a lot of features like that. GitHub's own very useful <kbd>r</kbd> shortcut isn't available anywhere else in the UI, but that doesn't justify making it an additional button.

**Comment by jerone** [comment]
> clicking **Open** (or **Closed**) will _remove_ `is:open` (or `is:closed`)

If this is implemented, I would suggest to alter the closed icon. 
If you select an author, label or any other dropdown, it is checked with an ✔ (check).
Currently, the closed status has that same ✔ (check) icon. Which confuses me; is the closed status now checked or not?!
Maybe just removing both icons, and prepending the ✔ (check) icon when it *is* selected.

**Comment by fregante** [comment]
Interesting point, I wouldn't mind removing the icons altogether simply to reduce noise and add space for a possible `is:merged` toggle in the future.

**Comment by muescha** [comment]
i would suggest to have: 
- `1,353 All | 80 Open | 1,273 Closed`
or
- `80 Open | 1,273 Closed | 1,353 All`
