### ISSUE TITLE
Expand all Assets on Releases pages

### ISSUE THREAD

**Issue by mikhaelkh** [sindresorhus/refined-github#2575]
Add a feature to expand all assets either automatically or with a shortcut like Ctrl/Shift + Click on unexpanded asset.

Example URL:
Any Releases page with assets, e.g.
https://github.com/gorhill/uBlock/releases

**Comment by fregante** [comment]
How often do you need to download more than one version of a repository?

**Comment by mikhaelkh** [comment]
Better question is "How often do you need to view/download unexpanded asset?"
Pretty often. Latest pre-release assets more frequently that others.
Sometimes second latest pre-releases and releases.
I guess others are pretty rare and mostly on projects which mixes different assets types into one release page.

**Comment by fregante** [comment]
Yeah perhaps the Assets should be automatically expanded when:

- it's the latest release and/or pre-release
- there are any asset other than the repo itself

My comment was replying to 

> expand all assets [...] with a shortcut like Ctrl/Shift + Click on unexpanded asset.

**Comment by fregante** [comment]
I just checked, that's already the logic, with the exception of prereleases.

The assets are already open on the latest release or when you open a single release.
