### ISSUE TITLE
`z-index` problem when modal is opened in issue detail page

### ISSUE THREAD

**Issue by usameavci** [sindresorhus/refined-github#2576]
Hi,

I found a bug in issue detail page. Some elements appeared on the modal backdrop when the modal is opened.

I tested on Chrome(v78.0.3904.108) and Microsoft Edge Dev(v79.0.287.3).

**Sample Url**
`https://github.com/sindresorhus/refined-github/issues/1137`

**Screenshot**
![image](https://user-images.githubusercontent.com/6714468/69867401-b13b7380-12b7-11ea-9339-0e167815d313.png)

**Comment by muescha** [comment]
also the Sticky Header:

![Bildschirmfoto 2019-11-30 um 01 50 24](https://user-images.githubusercontent.com/184316/69893594-1329c680-1314-11ea-80e3-14f487435e3e.png)

**Comment by fregante** [comment]
Probably due to `sticky-discussion-sidebar`

**Comment by usameavci** [comment]
> also the Sticky Header:
> 
> ![Bildschirmfoto 2019-11-30 um 01 50 24](https://user-images.githubusercontent.com/184316/69893594-1329c680-1314-11ea-80e3-14f487435e3e.png)

Sticky header looks the same on production.

![image](https://user-images.githubusercontent.com/6714468/69945951-b12bb580-14fb-11ea-88a5-5efbc9ceb4b8.png)
