### ISSUE TITLE
`fix-view-file-link-in-pr` breaks View file/raw link for PRs using default branch

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2580]
These PRs should suffice as examples (at least one of them shouldn't get merged that *soon* so hopefully someone will be able to reproduce it by then 😄)
https://github.com/Cog-Creators/Red-DiscordBot/pull/3027/files
https://github.com/Cog-Creators/Red-DiscordBot/pull/3080/files

Both of those link to:
https://github.com/[PR_AUTHOR]/Red-DiscordBot/blob/[PATH_TO_FILE]
While they should point to:
https://github.com/[PR_AUTHOR]/Red-DiscordBot/blob/[BRANCH_NAME]/[PATH_TO_FILE]

**Comment by fregante** [comment]
Thanks for the report!

Related to #2571 and https://github.com/sindresorhus/refined-github/commit/3c0ad6da97a69d36ca7ceb737340eb8c81f5084a

To be noted, PRs from the default branch are not a good idea: https://github.com/sindresorhus/refined-github/blob/master/source/features/warn-pr-from-master.tsx#L22

**Comment by jack1142** [comment]
> To be noted, PRs from the default branch are not a good idea
Oh yeah, I know, but you can't control all the contributors.

**Comment by jack1142** [comment]
But thanks for quick fix.
