### ISSUE TITLE
`linkify-user-location` breaks location edits in profile

### ISSUE THREAD

**Issue by romansp** [sindresorhus/refined-github#2581]
1. Yes, works correctly without extension (or disabled `linkify-user-location` feature)
2. "Your profile" page. Click "Edit Profile" button.
3. 
![image](https://user-images.githubusercontent.com/3474842/69911971-ff479880-13d7-11ea-84ae-282780f96e1b.png)

As `linkify-user-location` wraps underlying `<input>` inside `<a>` it's impossible to click that input field and instead you get navigated to google maps.

Relates: #2544

**Comment by fregante** [comment]
This just needs a `except: [features.isOwnProfile]` in the feature's init
