### ISSUE TITLE
Make filters dropdown inline on user Stars page

### ISSUE THREAD

**Issue by dmnsgn** [sindresorhus/refined-github#2589]
Until recently, it was possible to filter a user stars directly on the stars profile page. It now requires an extra click to open a dropdown. That extra click is required every time you need to do another filtering action (change input or languages, sort).

If you use stars as bookmarks of repo, this makes the process of searching them very painful.

Example URL:
https://github.com/sindresorhus?tab=stars

That would be more usable this way (styling and topics tags aside):

<img width="1440" alt="Screen Shot 2019-12-03 at 14 14 27" src="https://user-images.githubusercontent.com/1636460/70058751-697a5c00-15d7-11ea-9749-a931f3377996.png">

**Comment by sindresorhus** [comment]
I don't use the stars page, so I don't have any strong opinions about this. However, I don't think it should be permanently at the top center. If we were do anything about it, I'd rather see either the filter view permanently moved to the right sidebar, or add a keyboard shortcut to toggle the filter view.

**Comment by dmnsgn** [comment]
My mockup above might be a bit overwhelming indeed, and to be honest, I am mainly interested in having the searchbar back (sort and language filters usually don't vary as much as keywords when doing a search). 

As a reference, the following version was more or less satisfying for me:
![image](https://user-images.githubusercontent.com/1636460/70312490-a6c72f80-180b-11ea-87d8-dd9ff2d4a605.png)

**Comment by fregante** [comment]
This is due to their recent "responsification" efforts of GitHubs. It's happening to more and more places and it's honestly annoying.

I don't particularly need this feature either and unless it's a 10-lines `$('.list').appendTo('.sidebar')` equivalent I'm not sure it's worth the effort, especially because we can't break smaller screens (where the dropdown would be preferrable)

**Comment by yakov116** [comment]
The stars page now does not even have a tab in repository refresh view. (the page works but there is no visible tab)

**Comment by dmnsgn** [comment]
@yakov116  It's still accessible, in the left column, under the `Edit profile` button.
