### ISSUE TITLE
Incorrect content loaded on Issues/PRs tabs when repo is empty

### ISSUE THREAD

**Issue by wyze** [sindresorhus/refined-github#259]
Check out the below screenshot:

<img width="1006" alt="screen shot 2016-07-08 at 11 22 47 pm" src="https://cloud.githubusercontent.com/assets/186971/16706235/0a2c9150-456a-11e6-8af0-88148428d554.png">

I narrowed it down to [`showRecentlyPushedBranches`](https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L198-L209) being the culprit here.

I'd like to take a stab at the PR to fix this, but not sure the best way to go about checking if the repo is empty before adding the `include-fragment` element.

**Comment by hkdobrev** [comment]
@wyze Hi! Thanks for reporting this issue! However this has already been reported in #216 and is being worked on over at #258. I'm closing this as a duplicate, but feel free to chime in in the linked issue and PR and probably help solve this problem.

**Comment by wyze** [comment]
Oh shoot, I should have searched better first. Sorry for the duplicate issue! I'll subscribe to the other issue and PR. Thank you.
