### ISSUE TITLE
Show watchers count of the pinned repos.

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/refined-github#2593]
It would be cool to show the watchers count of a pinned repo, alongside the stars and forks count.

On the personal and org profiles.

**Comment by fregante** [comment]
We have a feature that [does the opposite](https://github.com/sindresorhus/refined-github/blob/master/source/features/hide-watch-and-fork-count.tsx) in regular repos.

**Comment by tunnckoCore** [comment]
And?

Yep exactly, I have it disabled.

**Comment by fregante** [comment]
And we're not gonna have two opposite features, one requiring the other one to be disabled.
