### ISSUE TITLE
feature request - save labels & assignee when changing PR branch

### ISSUE THREAD

**Issue by shaharmor** [sindresorhus/refined-github#260]
When creating a PR in GitHub, if you add a label (or an assignee for that matter) and then you change the base branch in which you want the PR to be merged into, it will remove your labels & assignee.

Is it possible to add a feature that will listen to that change and reset those properties?

**Comment by hkdobrev** [comment]
@shaharmor I don't think this is still happening. If you can reproduce it, please report to GitHub as it's most surely a bug. I'm closing this as GitHub should fix that for sure.
