### ISSUE TITLE
Override Font Stack

### ISSUE THREAD

**Issue by zeke** [sindresorhus/refined-github#261]
I am not a fan of the new github.com font stack. It's supposed to be objectively better, but to me it looks clunky and unrefined. Maybe my 👀  just need time to adjust?

Context: http://furbo.org/2015/07/09/i-left-my-system-fonts-in-san-francisco/

![screen shot 2016-07-11 at 11 44 51 am](https://cloud.githubusercontent.com/assets/2289/16742600/2d1bfa4e-475d-11e6-911f-d01c8bc750ca.png)

**Comment by DrewML** [comment]
I saw an email popup for this issue, and went to go read it on my computer, and that's when I noticed the new fonts 😞 

+1 on the "not a fan" train

**Comment by sindresorhus** [comment]
Pull request very much wanted.

**Comment by sindresorhus** [comment]
Fixed and published.

**Comment by stevemao** [comment]
@zeke We got a GitHub staff disliking the new font :)

**Comment by zeke** [comment]
In retrospect, opening this issue felt like a betrayal to the GitHub design team. I have disabled the extension for now, so as not to diverge too far from the experience of the majority of github users.

That said, I think it would behoove the GitHub design team to watch repositories like this for inspiration and indirect product feedback.

**Comment by karlhorky** [comment]
Opened #293 to reconsider this change.
