### ISSUE TITLE
`user-local-time` shows empty time for people with no commits

### ISSUE THREAD

**Issue by gurrrung** [sindresorhus/refined-github#2612]
Maybe a nicer message will help.

![Screenshot from 2019-12-10 19-52-58](https://user-images.githubusercontent.com/30543444/70537660-d6b56080-1b86-11ea-9030-8f0a9a296b06.png)

**Comment by fregante** [comment]
We do already show this on hover:

<img width="423" alt="" src="https://user-images.githubusercontent.com/1402241/70547255-299d1100-1ba3-11ea-941e-811efeb25992.png">

**Comment by gurrrung** [comment]
In my system, it comes only when I hover over that time area.

**Comment by fregante** [comment]
Right, it's a `title` attribute

**Comment by gurrrung** [comment]
Will that be enough? How about not adding time part for such users?

**Comment by fregante** [comment]
Yeah ideally we wouldn't show the icon at all, but sometimes it might take several seconds until it appears, so we have a "loading" in place. The loading is then replaced by the time or `-`. Perhaps we could:

- show `Not found`, instead
- check the cache first, if it's there and it's false, we shouldn't add the icon at all.

**Comment by sindresorhus** [comment]
> how Not found, instead

👍

**Comment by darkred** [comment]
I believe that it would be better if no icon nor message was displayed for people with no commits, 
i.e. as @fregante described as a different approach:

> check the cache first, if it's there and it's undefined, we shouldn't add the icon at all.

I agree with the OP that having a plain clock icon (followed by a `-` or not) doesn't help, 
but I also find the current `Not found` message distracting, and, at first glance, it always gives me the wrong impression that the relevant account itself no longer exists/has been deleted, instead that's just a RG feature message. e.g.:
![2020-08-30_133947](https://user-images.githubusercontent.com/723651/91657005-4e853b80-eac6-11ea-95d8-a49e6bf0d47e.jpg).

**Comment by yakov116** [comment]
What if we do `Timezone not found`?

**Comment by darkred** [comment]
I think it will be a long, distracting string (even if it's in smaller font) 
which doesn't offer any info to the user apart from RG debugging
*(i.e. that RG is indeed enabled and that it couldn't find the user timezone)*. 
Here is a mockup:
![2020-08-30_160831~](https://user-images.githubusercontent.com/723651/91659945-a0848c00-eadb-11ea-9f58-bf23a74ec7e7.jpg)
I prefer it in its initial form:
![2020-08-30_160859~](https://user-images.githubusercontent.com/723651/91659947-a4181300-eadb-11ea-8eb4-914b611f4261.jpg)

**Comment by fregante** [comment]
If we show the clock icon while loading and then hide it without a reason, it might look like a bug.

If we don't show the clock icon while loading, the user doesn't know whether some information is coming… or if it tried and failed.

"Timezone unknown" would be the more appropriate response.

There could be an additional optimization: if the time is already cached as "missing", then don't show the icon at all.

**Comment by darkred** [comment]
That's what I also had in mind. Just to summarize:

- at the initial mouse hover, show the clock icon while loading. Then:
  - if the information has been found, append the found timezone 
  - if the information has not been found, append "Timezone unknown" instead
- at next mouse hover:
  - if there's information stored in cache, show the clock icon and the retrieved timezone
  - if the time is already cached as "missing", then don't show anything at all, not the icon not any text message.

**Comment by fregante** [comment]
Code-wise, this could be done with a timer instead of manually checking the cache, etc.

Example to be inserted on [line 104](https://github.com/sindresorhus/refined-github/blob/b09477f0cdb0de44810f7b5eb372d331deb161c0/source/features/user-local-time.tsx#L104)

```js
const timeout = delay(300);
const date = getLastCommitDate();
// This will delay adding the icon for 300ms, enough to check if the date is store as "not found"
const race = await Promise.race([timeout, date]);
if (race === false) {
	// `date` was cached as "not found", so don't add the icon at all
	return;
}
```
