### ISSUE TITLE
convert issue to pull request

### ISSUE THREAD

**Issue by graingert** [sindresorhus/refined-github#2614]
by creating a PR with the API using `{"issue": <issuenumber>}` you can convert that issue into a PR

Here's an example of this undocumented API feature in use by Hub:

https://github.com/github/hub/blob/7b02a665ddacd885ad017a7c6904e662c8417bf8/commands/pull_request.go#L53-L59
https://github.com/github/hub/blob/7b02a665ddacd885ad017a7c6904e662c8417bf8/commands/pull_request.go#L350-L353

Example URL:

**Comment by graingert** [comment]
Here's some discussion around that API https://github.com/github/hub/commit/2a748a048d6903eca78332a484e63f8d647caf02

**Comment by fregante** [comment]
Interesting, thanks for the links. However I can't find a way to do this outside `hub`; we can't use a command line tool.

**Comment by graingert** [comment]
@fregante that's odd, hub is just using the v3 API which is available to refined-github

**Comment by fregante** [comment]
No reference to it in its pages though

https://developer.github.com/v3/issues/
https://developer.github.com/v3/pulls/

**Comment by graingert** [comment]
I think it's undocumented

**Comment by graingert** [comment]
Although it seems it was documented and marked deprecated: https://github.com/github/hub/issues/2038#issuecomment-473795000

**Comment by graingert** [comment]
Here's some more discussion about the API being un-deprecated https://github.com/github/hub/issues/1927

**Comment by fregante** [comment]
Honestly it's not a workflow I'd like to highlight on the web. It may sound good on private projects but sometimes an issue ends up with many PRs. The current "PR fixes Issue" standard is preferable on most projects.

If you need this feature, I'd suggest creating a separate extension so only those who need it have it.

From what I understand, you call the "update issue" API¹ and provide all the parameters you'd send to the "create PR" API ²

¹ https://github.com/github/hub/blob/7b02a665ddacd885ad017a7c6904e662c8417bf8/github/client.go#L778
² https://github.com/github/hub/blob/7b02a665ddacd885ad017a7c6904e662c8417bf8/commands/pull_request.go#L335-L353
