### ISSUE TITLE
Alternative approach for `comments-time-machine-links`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2618]
The timemachine link is useful but I never click it unless I really need that version, and most of the time I don't know this until I click the main link.

I suggest dropping the icon (closes #2131) and, instead, waiting for the user to click the link. 

On the resulting page:

- if the linked file still exists, add the timemachine permalink near `branch-buttons`:
	<img width="564" alt="linked" src="https://user-images.githubusercontent.com/1402241/70611422-c4dfc600-1c37-11ea-94d0-54509ffd43b6.png">
- if the linked file is gone, add the timemachine link somewhere on the 404 page
 
This also makes it easier to enable https://github.com/sindresorhus/refined-github/issues/1953 because we don't have to query each link on the page before adding the link: we just query the current page.

---

For this to be possible, instead of adding an icon to these links, we should add a `?linked-time=${timestamp}` parameter so this information is available on the linked page.

## Test

- Still exist: https://github.com/sindresorhus/refined-github/blob/master/source/features/comments-time-machine-links.tsx#L6-L8
- File deleted: https://github.com/sindresorhus/refined-github/blob/master/source/features/default-to-rich-diff.tsx#L19

**Comment by sindresorhus** [comment]
Sounds good 👍

**Comment by fregante** [comment]
Here's something easy to add in both cases (existing file or 404 page) and easy to understand:


<img width="533" alt="Screen Shot 2020-02-28 at 23 32 56" src="https://user-images.githubusercontent.com/1402241/75561949-c8d6f380-5a82-11ea-9f0f-80e4ebb5f298.png">

Example code:

```html
<div id="js-flash-container">

    <div class="flash flash-full flash-notice">
  <div class="container-lg px-2">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg class="octicon octicon-x" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M7.48 8l3.75 3.75-1.48 1.48L6 9.48l-3.75 3.75-1.48-1.48L4.52 8 .77 4.25l1.48-1.48L6 6.52l3.75-3.75 1.48 1.48L7.48 8z"></path></svg>
    </button>You can also <a href="">view this file as it at the time of the comment</a> (4 days ago)</div>
</div>
</div>
```
