### ISSUE TITLE
`view-markdown-source` is not being loaded on `*.md` pages

### ISSUE THREAD

**Issue by jsumners** [sindresorhus/refined-github#2619]
When I load https://github.com/fastify/fastify/blob/master/docs/Getting-Started.md with `view-markdown-source` and "Show the features enabled on each page in the console" enabled, I can see that the option is not loaded. This is happening on any markdown document in that repository, as well as on other repositories.

Extension version: 19.11.30

**Comment by fregante** [comment]
The classes changed:

https://github.com/sindresorhus/refined-github/blob/126a5f90e52ef8649c97c6e78064aad152e14cb8/source/features/view-markdown-source.tsx#L76

It appears to be `.markdown-body` now
