### ISSUE TITLE
Edit Pen does not Appear for New Comments

### ISSUE THREAD

**Issue by Modelmat** [sindresorhus/refined-github#2622]
When you add a new comment, the edit pen does not appear. It only appears after you refresh the page.
Before refreshing:
![image](https://user-images.githubusercontent.com/25718989/70689032-46525980-1d07-11ea-87a9-27fce9f9dbdd.png)
After refreshing:
![image](https://user-images.githubusercontent.com/25718989/70689069-5cf8b080-1d07-11ea-8cf3-24e4fe2d21e4.png)

**Comment by fregante** [comment]
Test

**Comment by fregante** [comment]
Duplicate of #2572

**Comment by Modelmat** [comment]
Ah, didn't see this.
