### ISSUE TITLE
Spacing issue on repository discussion lists

### ISSUE THREAD

**Issue by sharkykh** [sindresorhus/refined-github#2631]
**Version:** 19.12.9
**Test ~URL~**: Basically any repository discussion list, preferably the pull requests tab, and a repository where you have moderator/admin privileges.

**Without RGH:**
![chrome_JnaqmjVnR8](https://user-images.githubusercontent.com/10238474/70855012-6c752680-1ecc-11ea-81b6-4312762a5734.png)

**With RGH:**
![RoZbEys0mx](https://user-images.githubusercontent.com/10238474/70855014-70a14400-1ecc-11ea-91ff-06dcf1c98a1a.png)

Not sure if it's related but `filter-comments-by-you` is also failing:
```
content.js:2997 TypeError: Cannot read property 'before' of null
    at filter_comments_by_you_init (content.js:5257)
    at features_run (content.js:2992)
    at content.js:3039
    at content.js:2949
```

**Comment by fregante** [comment]
Yes I see two issues: that feature is failing, and the status filter feature has the wrong spacing.

I remember that at some point we reduced the space between those filters specifically to avoid this problem; there’s a chance that that selector needs to be updated as well.

**Comment by nikolao313** [comment]
> **Version:** 19.12.9
> **Test ~URL~**: Basically any repository discussion list, preferably the pull requests tab, and a repository where you have moderator/admin privileges.
> 
> **Without RGH:**
> ![chrome_JnaqmjVnR8](https://user-images.githubusercontent.com/10238474/70855012-6c752680-1ecc-11ea-81b6-4312762a5734.png)
> 
> **With RGH:**
> ![RoZbEys0mx](https://user-images.githubusercontent.com/10238474/70855014-70a14400-1ecc-11ea-91ff-06dcf1c98a1a.png)
> 
> Not sure if it's related but `filter-comments-by-you` is also failing:
> 
> ```
> content.js:2997 TypeError: Cannot read property 'before' of null
>     at filter_comments_by_you_init (content.js:5257)
>     at features_run (content.js:2992)
>     at content.js:3039
>     at content.js:2949
> ```

**Comment by arnaudvalle** [comment]
I took the liberty of creating a separate bug for the `filter-comments-by-you` issue (see https://github.com/sindresorhus/refined-github/issues/2647).
