### ISSUE TITLE
Incorrect spacing on tabs for repo homepage

### ISSUE THREAD

**Issue by alichtman** [sindresorhus/refined-github#2632]
Screenshots taken from: https://github.com/alichtman/shallow-backup, although I can only reproduce this on my own repos, so I imagine it'll be the same for you.

With Refined Github enabled:

<img width="1030" alt="image" src="https://user-images.githubusercontent.com/20600565/70874850-46c34c80-1fb4-11ea-8d98-c89cb5e3746f.png">

Without:

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/20600565/70874868-5a6eb300-1fb4-11ea-96e3-a9ba038a2b07.png">

## Env Info

**OS**: macOS 10.14.6
**Browser**: Firefox 71.0 (64-bit)

**Comment by busches** [comment]
Do you have the `more-dropdown` feature disabled? If not, do you have a console error you can share? I correctly see the `Security` and `Insights` tab under `More`.

**Comment by alichtman** [comment]
> Do you have the more-dropdown feature disabled?

I don't remember disabling that feature, as I haven't modified these settings in about half a year and this bug is new, but that did fix the issue.

Thanks :)

**Comment by fregante** [comment]
You probably disabled it when it had a bug that prevented you from using the repo (it was stuck open)
