### ISSUE TITLE
Highlight TODO and FIXME.

### ISSUE THREAD

**Issue by MickaToast** [sindresorhus/refined-github#2634]
Would be nice to have a way to easily find/see **TODO** and **FIXME** written in files.

i.e: See if a Pull Request stills contain new TODO/FIXME.

**Comment by sindresorhus** [comment]
Can you elaborate more on how you imagine it would look? For example, would TODO comments be bolded or something.

**Comment by fregante** [comment]
It could also be shown in https://github.com/sindresorhus/refined-github/issues/2579, e.g. _"This PR **adds** 2 TODOs"_ but it would require a fetch of all the changes, which might be heavy (or heavy PRs could be excluded, if possible)

**Comment by MickaToast** [comment]
> Can you elaborate more on how you imagine it would look? For example, would TODO comments be bolded or something.

Not sure here what could be the best, either write it somewhere to show the total added TODO, or something like this:

<img width="690" alt="Capture d’écran 2019-12-19 à 14 24 30" src="https://user-images.githubusercontent.com/9471827/71177041-5c15d080-226b-11ea-8cdb-8f88e6d6604d.png">

But again, I don't really know how to make it to best user friendly

**Comment by Zeko369** [comment]
Maybe also show `FIXME`s

**Comment by MickaToast** [comment]
> Maybe also show `FIXME`s

Indeed, will change the title

**Comment by fregante** [comment]
Note: I think eslint can automatically show this information inline as GitHub annotations. Example:

<img width="662" alt="Screen Shot 2020-04-18 at 12 13 32" src="https://user-images.githubusercontent.com/1402241/79634976-31327f00-816e-11ea-9863-81378c3622d4.png">

Hopefully XO will soon too. https://github.com/xojs/xo/issues/465

**Comment by ocarreterom** [comment]
What do you thing about something like this?

<img width="886" alt="Captura de pantalla 2020-10-25 a las 19 37 02 2" src="https://user-images.githubusercontent.com/11599942/97115847-8b9e3080-16f9-11eb-8899-fb2923f5c653.png">

<img width="886" alt="Captura de pantalla 2020-10-25 a las 19 37 02" src="https://user-images.githubusercontent.com/11599942/97115964-7e357600-16fa-11eb-8239-71f9ac12a65e.png">

**Comment by fregante** [comment]
Too complex, plus that line is already super crowded and we had to disable a feature on it already. 

On the files tab, I think XO or eslint already takes care of that. 

On the Conversation tab it would be useful to show this piece of information before the Mergeability box as suggested. I wonder if it’s useful to just show a compact list of GitHub annotations as a generic feature.

**Comment by MickaToast** [comment]
Not sure what's actually the idea behind the project, but handling features via Github Actions would add some restrictions to the project. For instance, I don't use and don't intend to use Github Actions, such features wouldn't be accessible to me if it's handled this way.

**Comment by fregante** [comment]
Indeed. Adding this piece of information is actually not too difficult on the Files tab since the content is already there; the problem is finding a way to place it other than inline/per-file like you showed in your mockup in December. 

Perhaps this feature can initially be just that since it doesn’t require any API calls.

**Comment by fregante** [comment]
Tracked in https://github.com/sindresorhus/refined-github/issues/2579
