### ISSUE TITLE
Make the default branch link smaller in `branch-buttons`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2635]
At some point we showed the default branch button as a small chevron by the branch selector (https://github.com/sindresorhus/refined-github/pull/1115) but we moved it away to group it with the “latest release” link. https://github.com/sindresorhus/refined-github/issues/1198

Since the space on that line is limited (https://github.com/sindresorhus/refined-github/issues/2624) (and I don’t need to know the name of the default branch in that particular view) I suggest moving the “default branch” link back to where it was, either as a chevron on the left or as an X on the right (of the branch selector)

The “latest release” button can stay as is. 

This is what it used to look like 

![](https://user-images.githubusercontent.com/1402241/36638960-e0dd71e8-1a33-11e8-9591-937ba6e117de.png)

The feature could also be split since the two links wouldn’t be shown together anymore.

**Comment by sindresorhus** [comment]
I would move it back to the previous look (chevron).
