### ISSUE TITLE
Filename in diff header not showing after recent GitHub update

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#264]
```
diffheader.js:29 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of undefined`
```

It looks like the `.diff-toolbar-filename + .right` selector that we're using to calculate one of the offsets doesn't resolve to an element in the DOM anymore.

Will try to take a look tomorrow evening when I have some free time if no one addresses it sooner.

**Comment by hkdobrev** [comment]
Apparently GitHub has changed something again and the feature doesn't work anymore.
