### ISSUE TITLE
Status filters on PR list page display JS code

### ISSUE THREAD

**Issue by arnaudvalle** [sindresorhus/refined-github#2646]
![Screenshot 2019-12-20 at 09 14 52](https://user-images.githubusercontent.com/1215056/71240355-350ddc00-2309-11ea-879d-e2d9a55548ae.png)

1. You need a repo that has some checks
2. Go to the PR list page (i.e. https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
3. Click on the Status filter and see that it shows JS code in the dropdown items, i.e.:
```
function() {
    return dom_chef_default.a.createElement("svg", {
      class: "octicon octicon-check",
      xmlns: "http://www.w3.org/2000/svg",
      width: "12",
      height: "16",
      viewBox: "0 0 12 16"
    }, dom_chef_default.a.createElement("path", {
      "fill-rule": "evenodd",
      d: "M12 5l-8 8-4-4 1.5-1.5L4 10l6.5-6.5L12 5z"
    }));
  }
```

**Comment by fregante** [comment]
Thank you for the report!
