### ISSUE TITLE
`filter-comments-by-you` not displayed any more on PR list page

### ISSUE THREAD

**Issue by arnaudvalle** [sindresorhus/refined-github#2647]
(Note: Initially reported as part of https://github.com/sindresorhus/refined-github/issues/2631 but they're two different issues)

![Screenshot 2019-12-20 at 09 56 16](https://user-images.githubusercontent.com/1215056/71242830-17437580-230f-11ea-99d5-45fd66b63425.png)

Example url: https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

1. The link `Everything commented by you` added by the `filter-comments-by-you` is not showing up anymore.
2. ~The icon of the button seems misaligned.~ (separate issue https://github.com/sindresorhus/refined-github/issues/2651)

```
content.js:2997 TypeError: Cannot read property 'before' of null
    at filter_comments_by_you_init (content.js:5257)
    at features_run (content.js:2992)
    at content.js:3039
    at content.js:2949
```

**Comment by GF-Huang** [comment]
The problem arises again.

**Comment by fregante** [comment]
The feature works, the item has just been changed to "involved in"
