### ISSUE TITLE
Highlight **created** repository count 

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#2649]
I would like it to be possible to highlight the number of repositories a user **has created**, not the ones he has forked. Indeed, some users fork hundreds of repositories without making any changes to them, and this distorts a little bit the number of repositories. 
Actually, the number is the forks + the created repositories. It would be nice if the number of created repositories were highlighted and the number of forks and if the number of forks was put a little bit in the background.

Example URL:

https://github.com/user

**Comment by AleksandrHovhannisyan** [comment]
I kinda like this idea, but you can already determine those counts using the `Type` dropdown:

![image](https://user-images.githubusercontent.com/19352442/71426525-cc13c480-2678-11ea-8f65-0312effd5009.png)

**Comment by Androz2091** [comment]
Oh, you're right. Couldn't we do something more visible? Like, for example, when you hover over the span, it displays something like this? (and when you're now hovering it, it displays the fork + owned repository count)
<img width="404" alt="Capture d’écran 2019-12-25 à 11 14 20" src="https://user-images.githubusercontent.com/42497995/71442846-f3fe3900-2707-11ea-989a-e1b96060e0d0.png">

**Comment by fregante** [comment]
Since we already show the “Source” repos by default, it would make sense to update that number in the sidebar to only count those. 

The global search has a counter widget, we might be able to use that so that this feature can be implemented as easily as 

```js
tabNumber.replaceWith(<counter query="...."/>) // I don’t remember the widget name actually 
```

**Comment by AleksandrHovhannisyan** [comment]
That's a good point! I didn't notice that :)

**Comment by fregante** [comment]
No longer applies since there are no counters anymore, but refer to https://github.com/sindresorhus/refined-github/pull/3286
