### ISSUE TITLE
New font still used in "Private" badge

### ISSUE THREAD

**Issue by sotojuan** [sindresorhus/refined-github#265]
<img width="232" alt="screen shot 2016-07-14 at 1 16 28 pm" src="https://cloud.githubusercontent.com/assets/8217766/16848757/4f740fea-49c5-11e6-8f27-e88658a952e3.png">

**Comment by anselmh** [comment]
Can you confirm that still? It’s using the Helvetica font here and the extension’s CSS for me. Tested with refined-github 1.6.0.

**Comment by sotojuan** [comment]
Seems to be fixed now for me, not sure why it was happening 😅
