### ISSUE TITLE
Allow disabling `align-issue-labels`

### ISSUE THREAD

**Issue by tbodt** [sindresorhus/refined-github#2650]
The Custom CSS box can *technically* be used to do this, but it's always a huge pain, involving looking up the source for the particular thing you want to disable and carefully overriding each thing it does with !important. Would be much nicer to just be able to click a checkbox.

**Comment by fregante** [comment]
What CSS features do you want to disable?

**Comment by tbodt** [comment]
This issue was motivated by trying to disable align-issue-labels. I've also overridden a few things in content.css: the file icon opacity change and issue line height.

**Comment by fregante** [comment]
Why override the issue line height? That was done to prevent some content that RG adds from touching https://github.com/sindresorhus/refined-github/pull/2585

**Comment by tbodt** [comment]
I prefer that the issue display be higher density, which is also why I disabled align-issue-labels.

**Comment by fregante** [comment]
We do have some disableable CSS features, but usually only if they are controversial enough or too complex to override.

In this case `align-issue-labels` is kinda both so feel free to send a PR for it, including screenshot (which I think is already on the readme)

In `features.add`, the `load` setting needs to be absent
