### ISSUE TITLE
Filters selection box on issues page is blank

### ISSUE THREAD

**Issue by tbodt** [sindresorhus/refined-github#2651]
Part of widen-search-field.css hides the "Filters" text, but now there's nothing left other than this weird indecipherable down arrow.

URL where bug occurs: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
<img width="388" alt="image" src="https://user-images.githubusercontent.com/5678977/71319835-592c0300-2458-11ea-91fa-c1b68c3f341a.png">

**Comment by fregante** [comment]
It’s not a bug, it’s a feature. The arrow’s position however is a bug, it should be centered
