### ISSUE TITLE
CTRL + Enter on approval window does not approve

### ISSUE THREAD

**Issue by Jamesking56** [sindresorhus/refined-github#2654]
When approving a PR, entering in your approval comment and pressing CTRL+Enter does not click the 'Approve' button. It clicks the 'Comment' button.

![image](https://user-images.githubusercontent.com/253237/71410304-a23cac80-263c-11ea-9b1e-7f096fd0dd38.png)

As you can see in the screenshot, the 'Approve' button is `primary` so looks like it'll be the one clicking upon CTRL+Enter. But this is not the case.

**Comment by fregante** [comment]
Correct, that’s the default action even without Refined GitHub (unless you change the checkbox). There are three choices, we can’t assume you mean “Approve” so we default to the least destructive one. If you change your mind you can then Approve the PR in a second “review”
