### ISSUE TITLE
Clicking the "issue" link of a repo with no code redirects to the "get started page" with double header

### ISSUE THREAD

**Issue by vendethiel** [sindresorhus/refined-github#266]
With the extension installed, going to https://github.com/vendethiel/projects/issues (one such example) redirects me to the project's "get started" page, with double header.

**Comment by DrewML** [comment]
What version of the extension are you running? Will say in `chrome://extensions`?

**Comment by vendethiel** [comment]
V 1.5.0. Tried installed it on another machine (this one runs mac, the other windows) and I can reproduce the bug.

From a little bit of digging around, the request seems to come from `function showRecentlyPushedBranches() {`

**Comment by vendethiel** [comment]
Okay, I was wrong on one point: it doesn't actually redirect me to the page.

What actually happens is that `showRecentlyPushedBranches` fetches "show_partial?partial=tree/recently_touched_branches_list", and since there's no branch (because it's an issue-only repo), GitHub goes insane and returns the whole view for the repo:

https://github.com/vendethiel/projects/show_partial?partial=tree/recently_touched_branches_list

instead of returning a few divs like
```

  <div class="js-socket-channel js-updatable-content"
       data-channel="tenant:1:repo:441269:post-receive:199499"
       data-url="/vendethiel/projects/show_partial?partial=tree%2Frecently_touched_branches_list">

  </div>
```

So it seems this is, to start with, a @github bug...

**Comment by hkdobrev** [comment]
@vendethiel I don't think this is still reproducible. Could you confirm if you could still reproduce this and close the issue if you can't? Thanks!

**Comment by vendethiel** [comment]
Not sure, I stopped using the extension because of this. Feel free to close it.

**Comment by hkdobrev** [comment]
@vendethiel OK, closing then. Please consider re-installing the extension again if you like it as this should not be an issue now! And any other feedback is always welcome!
