### ISSUE TITLE
`repo-age` should display the date of the first commit

### ISSUE THREAD

**Issue by webknjaz** [sindresorhus/refined-github#2660]
PR https://github.com/sindresorhus/refined-github/pull/2560 uses the repo creation time to show the age. This may be confusing and misleading by tricking people into thinking it's a project age.

Some projects may migrate between code hostings over time. For example, for https://github.com/cherrypy/cherrypy Refined GitHub shows the age of 3 years while it's way older: the first commit is dated 2004 (I think the project started ~2002 but the version control doesn't have that info).

So it would be nice to have some switch to enable using the oldest commit date instead of the repo creation time.

**Comment by yakov116** [comment]
see
https://github.com/sindresorhus/refined-github/issues/2526#issuecomment-556219779

**Comment by webknjaz** [comment]
Well, I'm okay with an extra query. Plus this mode could be disabled by default if this many queries is too much for someone.

**Comment by yakov116** [comment]
> "Disabled by default" means most people don't need it, so it doesn't belong to Refined GitHub. In that case, it's best to keep it as a standalone userscript or extension.
https://github.com/sindresorhus/refined-github/pull/2625#issuecomment-565821485

**Comment by sindresorhus** [comment]
Projects imported to GitHub is too much of an edge-case. What we could do is to add a tooltip that says that the age is the GitHub repo ago.

**Comment by fregante** [comment]
> What we could do is to add a tooltip that says that the age is the GitHub repo ago.

And/or this issue can stay open as a wish to improve on the feature if possible.

**Comment by webknjaz** [comment]
> is too much of an edge-case

Not at all. Most of the today's well-established projects were hosted somewhere else. A lot of them survived multiple migrations and CVSs.

A good example would be CPython: migrated ~2 years ago, first commit ~20 years ago. https://github.com/python/cpython/commit/7f777ed95a19224294949e1b4ce56bbffcb1fe9f

**Comment by yakov116** [comment]
I think the tootip says it all "Repository Created...." is has nothing to do with the commit date. Its when the github project was created

>Not at all. Most of the today's well-established projects were hosted somewhere else. A lot of them survived multiple migrations and CVSs.

I think (IMHO) the repo age is most beneficial for repo's that are not widely known and the user would like to know its age. For the large projects there is not real benefit knowing when they went into existence.
Again JMO

**Comment by fregante** [comment]
Edge case or not, if it was easy to get the first commit date I’d prefer that over “repo created”, which is just a GitHub event rather than the source’s birth date. 

We could still also display the Created date in the tooltip for clarity

**Comment by hardikmodha** [comment]
Just stumbled upon this and after a quick Google search, found a way to fetch the first commit date for a repository. Reference: https://stackoverflow.com/a/49647826/4248342

This certainly is not feasible with 1 HTTP request, we need to make 2 HTTP requests.

e.g. I tried it for https://github.com/python/cpython/ and it seems to be working fine. Number of commits: `106075` (Count is available on the repo code page)

1. Navigate to the commits page. (_1st request_)
2. Pick the URL from the pagination `Older` button which is https://github.com/python/cpython/commits/master?after=b19c0d77e6f25ea831ab608c71f15d0d9266c8c4+34. 
3. Modify the count after `+` with 106075 - 34 - 1 (last commit) = 106040
New URL:  https://github.com/python/cpython/commits/master?after=b19c0d77e6f25ea831ab608c71f15d0d9266c8c4+106040 and visit it. (_2nd request_)
4. The last item on this page is the first commit on this default branch. We can pick the date and time from there which is `1990-08-09T14:25:15Z`

What do you all think?

**Comment by yakov116** [comment]
@hardikmodha You have the last commit and count on the repo page.
See https://github.com/bpceee/oldest/blob/master/oldest.js

**Comment by hardikmodha** [comment]
Haha..just realized it after your comment. We do have the last commit. It will be only 1 HTTP request.

**Comment by yakov116** [comment]
@hardikmodha but it will have to wait until the page loaded

**Comment by hardikmodha** [comment]
Yeah, that is there but wouldn't that be okay? Since it would be a one-time request and first commit isn't supposed to change so we can cache it forever. What do you think?

**Comment by yakov116** [comment]
@hardikmodha maybe a loader? like https://github.com/hardikmodha/refined-github/blob/fix_tags_dropdown/source/features/tags-dropdown.tsx#L26-L28

**Comment by fregante** [comment]
🎉  Indeed it takes one HTTP request if you have the latest commit and commit count:

https://github.com/sindresorhus/refined-github/commits/master?after=a76ed868a84cd0078d8423999faaba7380b0df1b+1571

a76ed868a84cd0078d8423999faaba7380b0df1b is the latest commit and 1573 is the visible commit count (-2)

**Comment by hardikmodha** [comment]
I don't think that would be feasible here since we need to wait for the `.overall-summary` to load to figure out a place to append the repo age. https://github.com/sindresorhus/refined-github/blob/master/source/features/repo-age.tsx#L44 So I'm not sure where to display the loader.

**Comment by yakov116** [comment]
Maybe say Loading...

**Comment by webknjaz** [comment]
> so we can cache it forever.

It can change because it can be force-pushed or the default branch can be switched to a different tree.

**Comment by hardikmodha** [comment]
@webknjaz Yeah, it is possible. If default branch is changed then it will display wrong first commit date. E.g. Just found out that ydkjs has changed it's default branch from `master` to `2nd-ed` https://github.com/getify/You-Dont-Know-JS. If we have some way of knowing the oldest branch then this would be correct. 

@fregante Not sure which one can be more frequent. Migrated repos vs different default branches. 🤔

**Comment by fregante** [comment]
In this situation specifically, you're talking about force-pushes and default branch updates that change the very first commit. I'd say that's so rare it's not even worth discussing.

I'm not particularly worried about displaying slightly-off age information in that situation, it's not critical information.

Ideally yes, we'd show the earliest date between first commit and `createdAt`, but it's not worth 2 requests.

**Comment by hardikmodha** [comment]
> Ideally yes, we'd show the earliest date between first commit and createdAt, but it's not worth 2 requests.

I get your point but the request will be made only for the first time (and when the cache expires that is 30 days). Also, the requests are independent of each other.
