### ISSUE TITLE
Displaying tabs as 4 spaces breaks repos that indent with both tabs and spaces

### ISSUE THREAD

**Issue by tbodt** [sindresorhus/refined-github#2661]
For example, gnuplot: https://github.com/gnuplot/gnuplot/blob/90e47a608f36fd4f0c8457dc6c96a8ad3a3ea2ee/src/term.c#L1532

<img width="589" alt="image" src="https://user-images.githubusercontent.com/5678977/71636926-b78d7a00-2bec-11ea-8fa7-46a40176a6aa.png">

**Comment by tbodt** [comment]
I also can't figure out how to disable this with custom css. This doesn't work, as the rule is somehow overridden by the `tab-size: 4` rule in content.css:
```
* {
    tab-size: inherit !important;
    -moz-tab-size: inherit !important;
}
```

**Comment by fregante** [comment]
Don’t indent with both tabs and spaces, use a linter

**Comment by tbodt** [comment]
I'm not the one who's indenting with tabs and spaces. Generally you need to display a tab as 8 spaces to be able to display unknown code correctly (such as anything written by Richard Stallman.)

**Comment by fregante** [comment]
Whoever wrote it it’s based on a wrong or outdated assumption. I’m leaving this issue open if anyone can suggest a better selector to override the tab-size. I think you need to add `:root:root` to make it stronger

**Comment by tbodt** [comment]
Could the selector in content.css be made weaker?

**Comment by fregante** [comment]
I just checked. The selector is `*` so it literally can’t be weaker. Your code should work already if you change `inherit` to `8` or use `:root *` as the selector.

**Comment by tbodt** [comment]
Changing inherit to 8 didn't help, but using `:root *` did. This feels a bit insane though. Could you do something like removing !important or changing `*` to `.blob-code`?

**Comment by fregante** [comment]
Any changes means increasing the specificity of the selector, which helps in no way, it just lengthens it and leads to play wack-a-mole with selectors
