### ISSUE TITLE
GitHub added `add-co-authored-by`

### ISSUE THREAD

**Issue by casz** [sindresorhus/refined-github#2663]
I think we can safely disable/remove the add-coauthored-by feature

This should be handled by the recent change, see the changelog:
https://github.blog/changelog/2019-12-19-improved-attribution-when-squashing-commits/

**Comment by fregante** [comment]
Can’t confirm at the moment but this would be great! PR welcome to remove it

**Comment by casz** [comment]
Tested and worked:
![image](https://user-images.githubusercontent.com/1661688/71758268-c8b0e200-2e9d-11ea-98eb-e79f82882cd4.png)

I specially disabled Refined GitHub and closed and reopend the tab before clicking squash and merge.
