### ISSUE TITLE
Ability to disable new options by default

### ISSUE THREAD

**Issue by jhpratt** [sindresorhus/refined-github#2664]
How hard would it be to have the ability to disable any new options by default? There have been a number of changes recently that I don't care for, and I find myself struggling to find the name of the preference that was added.

**Comment by fregante** [comment]
Like you can’t disable new features in any websites, we shouldn’t do it here either. We don’t actually guarantee that features don’t depend on each other and some CSS is injected anyway.

**Comment by jerone** [comment]
I like the way how [Tab Session Manager](https://github.com/sienori/Tab-Session-Manager) **highlights** new settings:

![image](https://user-images.githubusercontent.com/55841/71767771-10705180-2f10-11ea-9d92-45bdf5283f31.png)

Very easy to author if the new setting is relevant for me.

**Comment by fregante** [comment]
@jerone not a terrible idea, but then the extension needs to keep track of new features locally (I don't want to have to remember to un-mark a feature as _new_ nor have to add a `dateAdded` date right before merging a PR)
