### ISSUE TITLE
Allow clearing the extension storage

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2669]
I tried out a non working branch of RH and I need to clear the extention storage.
I would like for one of 2 things

- A button to clear all.
- when disabling a feature it should clear the storage for the feature.

**Comment by fregante** [comment]
I've long thought of a "service" dropdown in the options for this and [options export](https://github.com/fregante/webext-options-sync/issues/23), but we could just list them **after** the features list.

The first item this should be super easy to implement:

```jsx
<button type="button" id="clear-cache">Clear cache</button>
async function clickHandler(event) {
	await cache.clear();
	event.target.disabled = true;
	event.target.textContent = 'Cache cleared';
}
```

**Comment by fregante** [comment]
Oops, depends on this: https://github.com/fregante/webext-storage-cache/issues/4

**Comment by fregante** [comment]
**Added**

<img width="681" alt="" src="https://user-images.githubusercontent.com/1402241/72054359-69b6f700-32fb-11ea-9d54-8de90961cf01.png">

**Comment by yakov116** [comment]
@fregante thanks!

Is clearing on disable still an option? Or you don't see the need?

**Comment by fregante** [comment]
It sounds like a good idea, but I don't think it's worth the trouble. I'd have to add yet another method on the cache (to get/delete more than one at once) and it's not something that happens that frequently. If you're intention is to flush the cache, now there's a button.
