### ISSUE TITLE
XSS with user name

### ISSUE THREAD

**Issue by LoicMahieu** [sindresorhus/refined-github#268]
Just visit this issue: https://github.com/wpscanteam/wpscan/issues/242
![capture d ecran 2016-07-18 a 15 18 59](https://cloud.githubusercontent.com/assets/900947/16916012/fbd60d00-4cfa-11e6-8655-5534a5e7f7d2.png)

**Comment by paulmolluzzo** [comment]
Um, this card isn't part of refined github. It's from a different extension https://github.com/Justineo/github-hovercard

Unless I'm missing something?

**Comment by hkdobrev** [comment]
@paulmolluzzo The XSS is reproducible with Refined GitHub though.

**Comment by LoicMahieu** [comment]
Yes I should specify that, sorry :) The card is well from another plugin but it show clearly where the problem is :D Thanks for fixing, awesome team !
