### ISSUE TITLE
Mozilla Addons reviewer: "Please add a privacy policy"

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2685]
Just to keep you in the loop to help you understand why Firefox is stuck on version 19.12.9:

> More information requested by Cse a day ago
>
> Please add a privacy policy to this add-on that details which user data is being sent and to what services. The critical things to describe in the policy are how your extension collects, uses, stores, and shares or discloses information about people.If your add-on makes it apparent to websites that it is installed, this must also be mentioned. The policy should be about the extension only, not a copy of the website's privacy policy. It should also be the actual text, as opposed to a link to a privacy policy on a website. The privacy policy can be added in the add-on settings under “Manage Authors & License” on AMO.

My response:

> Refined GitHub does not collect, use, store, nor share any data; we don't have servers. The extension only operates locally and on GitHub itself.

Help wanted to add a `privacypolicy` file in case they make this a hard requirement.

**Comment by fregante** [comment]
Latest: 

> There should be a privacy policy that states what kind of data is sent to github servers

Help.

**Comment by jerone** [comment]
I was just about to open an issue about the missing Firefox version.

---

Some info I found on the internet about privacy policies for extensions:
* Documentation: https://extensionworkshop.com/documentation/publish/add-on-policies/
* Examples of privacy policies:
  * https://addons.mozilla.org/en-US/firefox/addon/weather-extension/privacy/
  * https://addons.mozilla.org/en-US/firefox/addon/lastpass-password-manager/privacy/
  * https://addons.mozilla.org/en-US/firefox/addon/decentraleyes/privacy/

English is not my native language, so I'm not the best person to write a policy.

**Comment by fregante** [comment]
Perhaps:

> This extension communicates with GitHub to display additional data related to files, repositories and users. GitHub will receive the same unmodified cookies from GitHub.com or your Personal Access Token, if you provide one. Some actions like "Revert Changes to File" will use the GitHub API to create a commit only when initiated by the user. The authentication is done directly between the extension and GitHub, no third party server is involved. There's no advertising and no analytics. All features that cause additional HTTP request can be disabled.

@sindresorhus can you add it here? It's read-only for me https://addons.mozilla.org/en-US/developers/addon/refined-github-/ownership

**Comment by fregante** [comment]
@sindresorhus also Chrome is stuck on 4 versions ago and the 20.1.6 publish command returned "OK". Does the Chrome Store say anything about it?

**Comment by sindresorhus** [comment]
> can you add it here? It's read-only for me addons.mozilla.org/en-US/developers/addon/refined-github-/ownership

✅ Very well written.

**Comment by sindresorhus** [comment]
> also Chrome is stuck on 4 versions ago and the 20.1.6 publish command returned "OK". Does the Chrome Store say anything about it?

<img width="1020" alt="Screenshot 2020-01-11 at 18 21 33" src="https://user-images.githubusercontent.com/170270/72203527-43ca5780-349f-11ea-9700-4fe1e9dfcddc.png">

**Comment by fregante** [comment]
Wow... worse waiting times than AMO.

Let's see if the policy is enough. Could still be rejected for being too vague

**Comment by jerone** [comment]
It looks like the Firefox version was accepted; I got an update to 20.1.6 today. 🐰

**Comment by fregante** [comment]
Hallelujah!

**Comment by fregante** [comment]
@sindresorhus also Chrome:

>                 "message": "Publish condition not met: To publish your item, you must provide mandatory privacy information. This can be done in the new Developer Dashboard."

**Comment by sindresorhus** [comment]
<img width="1190" alt="Screenshot 2020-02-14 at 17 30 45" src="https://user-images.githubusercontent.com/170270/74523505-bff90480-4f4f-11ea-9783-98a14a52ce6c.png">

Why do we need the `activeTab` permission (specifically)?

**Comment by fregante** [comment]
To enable GH on Enterprise https://github.com/fregante/webext-domain-permission-toggle

**Comment by sindresorhus** [comment]
Ok, submitted. They warned that it could take up to several weeks to review...

**Comment by sindresorhus** [comment]
While we wait for Google, maybe there's something we can improve with the privacy form I filled out?

---

> **Single Purpose Description**
> The extension adds power-user features to GitHub.com.

> **activeTab**
> We need this to be able to enable the extension on GitHub Enterprise. `activeTab` lets us read the URL of the tab where the user clicks "enable". https://github.com/fregante/webext-domain-permission-toggle

> **Host Permission**
> We need access to `https://github.com/*` to add the features and access to `https://api.github.com/*` to fetch required data for some of the features we add.
