### ISSUE TITLE
shorten-links hides https protocol in URLs

### ISSUE THREAD

**Issue by HenryQW** [sindresorhus/refined-github#2689]
For instance https://abc.com will be rendered as abc.com, if you have shorten-links enabled right now you will see it.

Whereas http://abc.com is rendered correctly as http://abc.com

I noticed this problem while communicating on [a github issue](https://github.com/HenryQW/Awesome-TTRSS/issues/117#issuecomment-573420245), which caused some confusion. 

With shorten-links enabled:
![image](https://user-images.githubusercontent.com/5896343/72220640-96ad1900-354a-11ea-80e2-356111685ed3.png)

With shorten-links disabled:
![image](https://user-images.githubusercontent.com/5896343/72220667-dc69e180-354a-11ea-9251-2cb58b5fea31.png)

**Comment by fregante** [comment]
Yeah `shorten-links` makes links more readable at the expense of "exactness". I know it's not a real fix, but since `SELF_URL_PATH` is code/configuration, it should have been written as code: `SELF_URL_PATH=https://mydomin.com`, which isn't shortened.

**Comment by HenryQW** [comment]
Thanks for the reply. I guess this can be used as a feature for shaming “who is still using http”.
