### ISSUE TITLE
`always-show-branch-delete-buttons` appears even after the branch deletion

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2697]
1. Visit the Branches page of a repo you own
2. Resize the window to less than 900px of width
3. Click the Delete icon
	- -> The branch is deleted but the icon is still shown

![yo](https://user-images.githubusercontent.com/1402241/72249926-0693d000-362d-11ea-80af-ec04ba34dfc8.gif)

In the gif I click the icon again and the site obviously throws an error.

A solution would still be preferred to be CSS-only.

**Comment by yakov116** [comment]
Is this still an issue. I cant reproduce.

**Comment by fregante** [comment]
`always-show-branch-delete-buttons` only applies when the window less than ~1000px wide, and so does the bug

**Comment by fregante** [comment]
Fixed

![Fixed](https://user-images.githubusercontent.com/1402241/76807297-2dfd4980-67e4-11ea-90a6-59002efe8788.gif)
