### ISSUE TITLE
`All Activity` background renderd incorrectly when using together with octotree plugin monokai background

### ISSUE THREAD

**Issue by Zhenye-Na** [sindresorhus/refined-github#2698]
### Description

I am currently using [`octotree`](https://github.com/ovity/octotree) and [`refined-github`](https://github.com/sindresorhus/refined-github) plugin together. I have changed the theme in octotree to `Monokai` but there seems to have some error rendering the background in the GitHub **All Activities** page. More details can be found in the screenshot.

After disabling the extension, the problem disappears. So this is caused by `refined-github`.

### Environment

* Octotree version: latest
* Browser & version: Google Chrome Version 79.0.3945.117 (Official Build) (64-bit)
* OS & version: Mac OS X
* Screenshot, if any (drag an image here)

![Screen Shot 2020-01-13 at 080438](https://user-images.githubusercontent.com/32248549/72275497-e63f2380-35e2-11ea-8644-39ff17c50b8b.jpg)

Thanks

**Comment by fregante** [comment]
Octotree's dark mode isn't free so we can't even test it. You should contact them to improve compatibility with Refined GitHub.

Alternatively I suggest using [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark), which is compatible with Refined Github.
