### ISSUE TITLE
Reposition `tag-changelog-link`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2699]
GitHub [implemented](https://github.blog/changelog/2020-01-13-shortcut-to-compare-across-two-releases/) a more generic (i.e. less efficient) version of `tag-changelog-link`

<img width="120" alt="" src="https://user-images.githubusercontent.com/1402241/72285036-e8ea5900-3674-11ea-8659-eb17d167d2ab.png">

Their feature is not a strict replacement, but now `tag-changelog-link` needs to be moved above it (or... alternative solutions welcome)

## Test

https://github.com/sindresorhus/refined-github/releases/tag/20.1.6

**Comment by jerone** [comment]
I won't change it. This feature is visually loaded late, introducing an jump in UI if it were placed before the dropdown. Or we need to reserve the place immediately with some CSS.

**Comment by fregante** [comment]
> introducing an jump in UI if it were placed before the dropdown

True.

**Comment by fregante** [comment]
I'm kinda disappointed that they just put the button there. Now we have 3 "compare" links on the page.

<img width="753" alt="" src="https://user-images.githubusercontent.com/1402241/72286338-8777b980-3677-11ea-8259-93a7b0f115ec.png">

**Comment by yakov116** [comment]
@fregante #2686

**Comment by lukehefson** [comment]
> Now we have 3 "compare" links on the page.

Noted! We might combine them in a future iteration – but there aren't any plans to _as of right now_.

> GitHub [implemented](https://github.blog/changelog/2020-01-13-shortcut-to-compare-across-two-releases/) a more generic (i.e. less efficient) version of `tag-changelog-link`

A little background here if it helps– we originally spiked out a version that was almost identical to  the refined-github version. But when we tested it with some organisations who run different 'release channels/lines' at a time – it actually made things more confusing for their users. So this was a way to mitigate and make comparing release more 'self serve'.

Ideally, I'd love to see us have better support all-round for different Release workflows (hence [my tweet](https://github.com/sindresorhus/refined-github/issues/2686)) and it's something I'll be advocating for internally 😄.

**Comment by fregante** [comment]
Yeah I figured that you can’t make a solution that makes everyone happy. Extensions have the privilege of making feature that only work for a subset of users.

**Comment by fregante** [comment]
For Refined GitHub: we could also combine this to:

---

Compare to: [master (+7)]() | [previous tag]() | [tag...]()

---

However I do like the current “Changelog” label.

**Comment by fregante** [comment]
> However I do like the current “Changelog” label.

For this reason, I suggest we just move our Changelog link above the "Compare" dropdown, that's all.

**Comment by notlmn** [comment]
Wait, I thought GitHub was adding this link on releases all along. Damn!
