### ISSUE TITLE
Audit extension for XSS vulns

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#270]
https://github.com/sindresorhus/refined-github/pull/269#issuecomment-233547355

We likely have more than just that 1. Note that the risk factor is lower than usual thanks to GitHub using a strict content security policy, but it's still worthwhile.

**Comment by devoxel** [comment]
Yeah this seems like a good idea. I have some friends who can help.

Maybe switching to "use strict;" in the javascript would ease up the issues? Though I haven't read all the source and don't know what unit testing this actually passes through, but a quick lint can help uncover issues pretty quickly.

**Comment by bfred-it** [comment]
It happened #510 

Also relevant: 
> What you can do, if that's important to anyone here, is to **review each string composition** to make sure we're sanitizing the input, wherever necessary
> https://github.com/sindresorhus/refined-github/issues/439#issuecomment-306419652

**Comment by bfred-it** [comment]
Sanitized `addReadmeButtons`: #538 

All over the extension we create elements via `$('html')` and similar methods. We should start restricting this HTML to our own strings and limit as much as possible user content.

Example:

```js
domify(`<a class="one two" href="${ element.title }">${ name }`);
// becomes
a = domify('<a class="one two">');
a.href = element.title;
a.textContent = name
// or
$('<a class="one two">', {
  href: element.title,
  text: name
})
```

**Comment by bfred-it** [comment]
We're done here!
