### ISSUE TITLE
 Restore `quick-review-button` feature

### ISSUE THREAD

**Issue by avaly** [sindresorhus/refined-github#2700]
I can not approve/request changes/comment on any pull request.

![github-refined-bug-review](https://user-images.githubusercontent.com/356100/72351627-9cd10000-36d8-11ea-821a-6e74997229be.gif)

The behavior works if I disable the add-on.

Browser: Firefox 72.0.1
Add-on version: 20.1.14

**Comment by mauriciord** [comment]
![Screen Shot 2020-01-14 at 11 23 31](https://user-images.githubusercontent.com/1128701/72352063-566fa700-36c0-11ea-868e-be49d986e7e3.png)

**Comment by mauriciord** [comment]
![Screen Shot 2020-01-14 at 11 23 31](https://user-images.githubusercontent.com/1128701/72352063-566fa700-36c0-11ea-868e-be49d986e7e3.png)

Browser: Firefox Developer Edition 73.0b4 (64-bit)
Add-on version: 20.1.14

**Comment by dsiebel** [comment]
Same here, looks like the `quick-review-button` is having issues. I disabled it and the "old" buttons are working.

Browser: Firefox Developer Edition 73.0b4 (64-bit)
Add-on version: 20.1.14

**Comment by fregante** [comment]
I just pushed a hotfix. Chrome isn't affected because `20.1.14` was rejected.

Try updating soon, you should see `20.1.4.1820`

**Comment by dsiebel** [comment]
Thanks for the quick reaction!
I am on 20.1.14.1820 now, but I can not re-enable the feature. It says its "Disable because of #2700" and I can not tick the box:
<img width="1373" alt="Screen Shot 2020-01-07 at 09 31 45" src="https://user-images.githubusercontent.com/145283/72428168-6f925980-378d-11ea-82ee-72a1be9acaac.png">

**Comment by yakov116** [comment]
@dsiebel hot fix was to disable

**Comment by fregante** [comment]
I think this bug is due to https://github.com/sindresorhus/refined-github/pull/2639

I haven’t had time to investigate to I just disabled the feature since it broke GitHub.

**Comment by fregante** [comment]
It was actually https://github.com/sindresorhus/refined-github/commit/4c502f50b45d339f9eb6fb3964b4eabc7ba7a36f

It forced me to add a `type=button` attribute on buttons, which removes the default `submit` behavior; in 2 cases, the button actually had to submit.

**Comment by mobilutz** [comment]
> It was actually [4c502f5](https://github.com/sindresorhus/refined-github/commit/4c502f50b45d339f9eb6fb3964b4eabc7ba7a36f)
> 
> It forced me to add a `type=button` attribute on buttons, which removes the default `submit` behavior; in 2 cases, the button actually had to submit.

@fregante Did you look into configuration the `button-has-type` eslint plugin?
https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/button-has-type.md
