### ISSUE TITLE
Make "Edit/delete file" clickable on compare page

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2704]
Example URL:
https://github.com/Cog-Creators/Red-DiscordBot/compare/V3/develop...jack1142:pr/ghactions?expand=1

"Edit/delete file" links are already there, but they're not active, IMO it would be useful to be able to quickly edit files from there if you notice some error in files:
![image](https://user-images.githubusercontent.com/6032823/72428140-63a69780-378d-11ea-9730-2ca2d5381f7e.png)

Of course that link should only be active when you can edit the head branch.

Edit: I also noticed that "View file" link there doesn't link you to branch but to commit so that makes it take even longer to edit a file.

**Comment by fregante** [comment]
Where would the file be edited? This could be kind of confusing

**Comment by jack1142** [comment]
@fregante What do you mean by where? Cause I just meant for it to be a link to:
`https://github.com/[ORG_OR_USER]/[REPO_NAME]/edit/[BRANCH]/[FILE_PATH]`
Same as it works when you're on the PR page:
![image](https://user-images.githubusercontent.com/6032823/72467116-9034d080-37da-11ea-8a71-6155bdd4b749.png)
Or on file page:
![image](https://user-images.githubusercontent.com/6032823/72467145-a0e54680-37da-11ea-9c0c-3a3ddfbd2599.png)

**Comment by fregante** [comment]
On which of the two branches should the edit happen? As a user, I’m seeing the comparison between two branches so an edit button isn’t instantly clear which of the two will edit.

**Comment by fregante** [comment]
I meant “which of the 2 branches will receive the edit?”

But yeah this is comparable to a PR view so the right-hand branch will be edited. 

This feature is similar to one we recently added so perhaps that one can be extended, it could become `enable-file-links-in-compare-view` 

https://github.com/sindresorhus/refined-github/pull/2529

I remember trying to also “fix” the edit link in that view but it didn’t make sense (I don’t remember why)

**Comment by yakov116** [comment]
@fregante and @jack1142 

Have this done in https://github.com/yakov116/refined-github/tree/enable-file-links-in-compare-view

But I need to wait for #3138 to be merged first.

**Comment by yakov116** [comment]
@fregante and @jack1142 

Have this done in https://github.com/yakov116/refined-github/tree/enable-file-links-in-compare-view

But I need to wait for #3138 to be merged first.

**Comment by fregante** [comment]
> I remember trying to also “fix” the edit link in that view but it didn’t make sense (I don’t remember why)

I think I remember now. The link only makes sense if the version on the right points to a branch and not a permalink (commit, tag), and this information might not be available on compare views. 

If you compare 2 commits, the edit and delete links don’t make sense.

@yakov116 can you reliably detect whether the head branch (right) points to a permalink? If not, this feature should probably be scrapped.

**Comment by yakov116** [comment]
Yes I can except for one case. (I wish I had a fork of your's I can give you a link to test on)
https://github.com/yakov116/refined-github/compare/upstream...FloEdelmann:faster-reviews
In this case I am comparing a fork to my own repo and I don't have rights to edit the forked repo. Clicking edit/delete will not lead to a 404 rather to the page offering me to fork the repo.

Github gives us an easy detection for permalink's, since it will not give you an option to create a PR if you are comparing a permalink. In that case I only enabled the feature for the view and **not** the edit/delete. (Link to the branch/tag instead of a commit)

**Comment by fregante** [comment]
> I wish I had a fork of your's I can give you a link to test on

I just made this: https://github.com/fregante/refined-github

**Comment by yakov116** [comment]
This is the one case
https://github.com/fregante/refined-github/compare/a@b...FloEdelmann:faster-reviews
Permalink
https://github.com/fregante/refined-github/compare/20.5.27...FloEdelmann:faster-reviews

Where you should be able to edit
https://github.com/fregante/refined-github/compare/a@b...sindresorhus:incremental-tag-changelog-link

**Comment by qaisjp** [comment]
A suggestion: the button text could be changed to "Edit latest file" to make it clear that it edits the latest file on that branch.

Or to make it clearer which branch it would edit on:

![image](https://user-images.githubusercontent.com/923242/83360637-9509b380-a37a-11ea-825d-83d7fd3edd98.png)


The above screenshot requires the `<details-menu ... style="width: 185px; ...">` to be changed to `<details-menu ... style="width: initial; ...">`, otherwise the menu will be too thin:

![image](https://user-images.githubusercontent.com/923242/83360633-8ae7b500-a37a-11ea-9aa0-8917929f4166.png)

**Comment by fregante** [comment]
Good point. I wonder if that can be displayed any other way since it applies to all of the 3 links.

<img width="227" alt="" src="https://user-images.githubusercontent.com/1402241/83401479-23c31280-a405-11ea-87d0-22e7dacdaa14.png">

```html
<div class="dropdown-header">Dropdown header</div>
```

Not a great default style though

**Comment by qaisjp** [comment]
I like that idea.

What about the "View file" button? i.e. in the case of https://github.com/fregante/refined-github/compare/a@b...FloEdelmann:faster-reviews, "View file" always views at point of 1ab3f6f and not the latest.

Maybe something like this?

![image](https://user-images.githubusercontent.com/923242/83426501-220a4680-a427-11ea-8ccf-71d1293018e9.png)

(The first "View file" button is GitHub's original button.)

----

If branch name was shown in the dropdown, this is another edge case to consider: a user might be confused about whether it shows the latest file the left branch vs. the right branch.

i.e. this case, where the `base` branch name matches the `compare` branch name.

![image](https://user-images.githubusercontent.com/923242/83426791-9cd36180-a427-11ea-8d78-db8b0c5ed5e2.png)

I suppose in that case you could show this (if repo names are different)

![image](https://user-images.githubusercontent.com/923242/83427090-14a18c00-a428-11ea-95c1-a991efc98858.png)

(if repo names are the same)

![image](https://user-images.githubusercontent.com/923242/83427162-36027800-a428-11ea-84a0-b1b8262942e8.png)

p.s. the `width: initial` thing is applied here, but it seems that only the buttons themselves can widen the dropdown, and not the headers. Can't figure out the CSS fix here.

**Comment by fregante** [comment]
Definitely interesting, but I wonder if it’s useful to ever link to the commit from that dropdown. If you can open the branch link, why would you ever open the commit link?
