### ISSUE TITLE
Notification beta filter drop-down auto completion is overlapping

### ISSUE THREAD

**Issue by casz** [sindresorhus/refined-github#2705]
- I disabled both Refined and GitHub Dark turning them on and off. This is definitely located in Refined GitHub.
- https://github.com/notifications/beta?query=is%3Aunread\
With Refined GitHub enabled.
![image](https://user-images.githubusercontent.com/1661688/72415403-b1fb6c80-3774-11ea-8a39-f05965fe1379.png)
With Refined GitHub disabled
![image](https://user-images.githubusercontent.com/1661688/72458098-3c20f080-37c8-11ea-912d-6be5074df72d.png)

I located the issue, it's related to the form parent element being set to a `display: flex` instead of how GitHub intended it to be `display: block`

This is the CSS in question.

https://github.com/sindresorhus/refined-github/blob/cfbc2d4c7166eea2bd4d653ff93a746b87e53d93/source/features/widen-search-field.css#L16-L24

**Comment by yakov116** [comment]
#2703

**Comment by casz** [comment]
I searched only in issues 😭 my bad @yakov116

**Comment by fregante** [comment]
Thank you for reporting. Closing as duplicate
