### ISSUE TITLE
Travis failed to publish release for Chrome

### ISSUE THREAD

**Issue by casz** [sindresorhus/refined-github#2707]
https://travis-ci.org/sindresorhus/refined-github/builds/637034089#L4475
Response code 400 (Bad Request)
```json
{
    "error": {
        "errors": [
            {
                "domain": "global",
                "reason": "badRequest",
                "message": "Publish condition not met: The single purpose description is required.; A justification for activeTab is required.; A justification for the broad host permission is required.; A justification for remote script is required."
            }
        ],
        "code": 400,
        "message": "Publish condition not met: The single purpose description is required.; A justification for activeTab is required.; A justification for the broad host permission is required.; A justification for remote script is required."
    }
}
```

**Comment by fregante** [comment]
Yep. We have no idea of what that error means, it doesn’t exist online, nobody ever mentioned it.

**Comment by fregante** [comment]
@sindresorhus can you try uploading the extension manually? They might have some new fields to fill in

**Comment by sindresorhus** [comment]
I have manually submitted an update. I didn't get any new fields to fill in. I only got this after publishing:

<img width="589" alt="Screenshot 2020-01-16 at 18 12 08" src="https://user-images.githubusercontent.com/170270/72520329-caaa7600-388b-11ea-9509-b7b90d0bdd47.png">

**Comment by yakov116** [comment]
@sindresorhus you can email them. I have done it in the past and thing took a day to go through.

**Comment by fregante** [comment]
Your version was published. Let's try again with Travis

**Comment by Jongkeun** [comment]
Did you solve this problem? 
I have the same problem when I update my chrome extension that is working well before I did.
I think Google's algorithm was changed something.

**Comment by allcracked** [comment]
> Did you solve this problem?
> I have the same problem when I update my chrome extension that is working well before I did.
> I think Google's algorithm was changed something.

I also have the same issue with an extension that I basically changed on or two lines, it was published correctly a couple of weeks ago and now it's showing these errors, I would try to email support to see what's going on.

**Comment by fregante** [comment]
It looks like a manual upload fixes the issue.
