### ISSUE TITLE
`link-to-file-in-file-history` only works for first page of history

### ISSUE THREAD

**Issue by garyking** [sindresorhus/refined-github#2711]
https://github.com/typescript-eslint/typescript-eslint/commits/master/packages/eslint-plugin

![First page of results](https://user-images.githubusercontent.com/343940/72690326-53721d80-3ae9-11ea-9b0f-570a1de9b093.png)

https://github.com/typescript-eslint/typescript-eslint/commits/master?after=63c63517ada7013b141f82e1fa14927dbf66f231+34&path%5B%5D=packages&path%5B%5D=eslint-plugin

![Second page of results](https://user-images.githubusercontent.com/343940/72690329-5bca5880-3ae9-11ea-8b92-fa0a75de5f19.png)

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/2692 the same fix should work for both. (I wanted to send a pr but did not have time)
