### ISSUE TITLE
Link to review from the overview at the end of a PR

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2712]
I miss the possibility to see a link in the summary at the end of a PR to each review and requested changes etc.
I want to click the text `requested changes` or `approved` next to a reviewers name to jump to that review and read it again without searching for it in between all the comments.

Example URL:
Any PR which has a review added. E.g. https://github.com/sindresorhus/refined-github/pull/2667

**Comment by fregante** [comment]
Sounds good, but this is already possible by clicking on the sidebar (which is always visible on the right)

<img width="1024" alt="click to visit" src="https://user-images.githubusercontent.com/1402241/72798224-2ce0ed80-3c75-11ea-8e0a-a0aa93a33498.png">

**Comment by tooomm** [comment]
- 1. The link on the right is not visible if you scroll down for me, as it stick to the top and the widget(s) doesn't follow the page scrolling down.
That is an inconsistent behavior as it works in this issue right now. I always see the tags and notification settings as they keep scrolling down with the content.
But in the linked PR this does not work. I'm using Firefox 72.0.1, no other GitHub addons installed.
- 2. That link brings you to the changes tab. I requested a link to the review in comments itself, e.g: https://github.com/sindresorhus/refined-github/pull/2667#pullrequestreview-341590546

**Comment by fregante** [comment]
> The link on the right is not visible if you scroll down for me,

The sidebar is sticky in Refined GitHub https://github.com/sindresorhus/refined-github/blob/master/source/features/sticky-discussion-sidebar.tsx

>     1. That link brings you to the changes in files tab. I requested a link to the review in comments itself,

👍

**Comment by tooomm** [comment]
>The sidebar is sticky in Refined GitHub

As I said, it does work in this issue for example...
But it does NOT work for whatever reason in the PR I linked and others as well. Seems to not work for any PRs for me. Some other issue posts I tried don't work too.

Refined Github 20.1.14.1820, Firefox 72.0.1

Any idea for troubleshooting?

**Comment by fregante** [comment]
@tooomm the sidebar isn't sticky if it doesn't fit your screen vertically. Try pressing `ctrl -` to _zoom out_ the page until it definitely fits, and then try scrolling. If it still doesn't work, please record a gif and open a new issue

**Comment by tooomm** [comment]
>If it still doesn't work, please record a gif and open a new issue

Done. #2770

<br>

Back to topic then:
**This issue request a direct link to the review comment at the bottom of a PR in the list of reviews.**

**Comment by fregante** [comment]
Test PR: https://github.com/facebook/react/pull/17968#partial-pull-merging

**Comment by xtianproject** [comment]
Hello, created a PR for this [#3710](https://github.com/sindresorhus/refined-github/pull/3710).

It's actually my first time contributing. Let me know if I need to change my implementation.
