### ISSUE TITLE
`sync-pr-commit-title` renames PR to "Merge pull request #XXX from <branch>"

### ISSUE THREAD

**Issue by Blaisorblade** [sindresorhus/refined-github#2713]
Thanks to #1743, PRs are renamed to the merge commit title. However, that's typically an uninformative message, such as "Merge pull request #XXX from <branch>" — the PRs then shouldn't be renamed, but are, per the screenshot. The automated rename is
> Blaisorblade changed the title ~~Complete supporting guarded pDOT: Allow paths as value definitions, try 2~~ Merge pull request #155 from Blaisorblade/path-defs-rebase-2

(I later renamed this back by hand).

Disabling `sync-pr-commit-title` fixes the problem. Unfortunately, I'm only merging PRs in a private repo, so I can't (yet) give a public link (but I should be able to, soon).

![image](https://user-images.githubusercontent.com/289960/72699201-ba262400-3b47-11ea-89e7-90b0bd082245.png)

**Comment by fregante** [comment]
`sync-pr-commit-title` lets you disable the feature before merge:

![](https://user-images.githubusercontent.com/1402241/51669708-9a712400-1ff7-11e9-913a-ac1ea1050975.png)

You can just click `cancel`

**Comment by Blaisorblade** [comment]
Thanks for the answer; the real bug is the default title, but that isn't due to this extension.
GitHub proposes `Merge pull request #XXX from ...` as commit title, but only on some repos :-(.

**Comment by fregante** [comment]
Actually `sync-pr-commit-title` is made of two parts:

1. First it copies the PR title to the PR commit title (even for merge commits, it should replace the default `Merges...`)
2. Then if the user make changes to this title, it should also update the PR title

So in this case it appears that the first part failed (so it remained `Merges...`) while the second part succeeded (so it set the PR title to `Merges...`)

If this behavior is reproducible, this is a bug somewhere here:

https://github.com/sindresorhus/refined-github/blob/22764b8ba0475cef2a87adf134acb828852daaa8/source/features/sync-pr-commit-title.tsx#L87-L89

**Comment by jsumners** [comment]
@Blaisorblade thank you for filing this issue. It helped me figure out what to disable to get rid of this annoyance.

**Comment by Blaisorblade** [comment]
@jsumners A request: has it occurred on a *public* repo? Can you post a link? All my examples are on a private repo 😕.

**Comment by jsumners** [comment]
@Blaisorblade sorry, I am only seeing this in my private repos at the moment.

**Comment by thibaudcolas** [comment]
This just happened to me on a public repo if it helps: https://github.com/wagtail/vagrant-wagtail-develop/pull/24

This was the first time I used this feature (I’ve just installed the extension), I did notice the messaging announcing the change and offering to cancel, but thought I’d see what happens.

I can confirm that part 1. “First it copies the PR title to the PR commit title” (https://github.com/sindresorhus/refined-github/issues/2713#issuecomment-576419830) didn’t work – the PR commit was using the default merge commit wording.

**Comment by Amorymeltzer** [comment]
I think @thibaudcolas' report is sufficient, but FWIW I've been running into this same thing multiple times (one example: https://github.com/azatoth/twinkle/pull/808).  This is an awesome help, but simply clicking GH's merge button shouldn't default to something much less useful.

**Comment by MathieuDerelle** [comment]
I've made a public just for it if that can help.
https://github.com/MathieuDerelle/refined-github-issue
(mode details in the closed (dupe) issue linked above)

**Comment by casz** [comment]
https://github.com/jenkinsci/bom/pull/180 was also affected

**Comment by fregante** [comment]
I'll limit this feature to squashing commits.

**Comment by fregante** [comment]
Fixed. At some point we'll publish a new release. Currently we're still waiting for the Chrome Web Store to publish the last update.
