### ISSUE TITLE
Back arrow and tag menu gets broken when the filepath is long

### ISSUE THREAD

**Issue by tbodt** [sindresorhus/refined-github#2719]
URL: https://github.com/openjdk/jdk/blob/jdk8-b120/jdk/src/share/classes/sun/security/ssl/X509TrustManagerImpl.java

<img width="1038" alt="image" src="https://user-images.githubusercontent.com/5678977/72751435-7f86b080-3b74-11ea-80d2-8b03cfaa5f75.png">

Sorry if the title is incomprehensible, the screenshot should be enough of an explanation.

**Comment by fregante** [comment]
Thank you for the report! This is a duplicate of https://github.com/sindresorhus/refined-github/issues/2624
