### ISSUE TITLE
Add RefinedGitHub Addon to Microsoft Edge extensiosn

### ISSUE THREAD

**Issue by mobilutz** [sindresorhus/refined-github#2722]
I would like to switch to Microsoft Edge, and it would be awesome, if you could add the plugin directly to their Addon list:
https://microsoftedge.microsoft.com/addons/search/github?hl=en-GB

Yes, it is possible to install any Chrome Plugin on MS Edge, but official Edge Addon would be cool.

**Comment by sindresorhus** [comment]
I don't think we'll want to do this yet. Each store adds a lot of overhead and the new Edge just came out.

We first need:
1. A more mature store.
2. API endpoint so we can auto-publish.
3. A Node.js CLI to publish to that store (https://github.com/sindresorhus/refined-github/blob/42fa0d72e3a2328cebf4044691949fd918dcfef4/package.json#L16)

**Comment by fregante** [comment]
Not worth it at the moment, you install it from the Chrome Web Store natively.

<img width="759" alt="" src="https://user-images.githubusercontent.com/1402241/72794288-577b7800-3c6e-11ea-87bd-9144a3bbf4bf.png">

**Comment by mobilutz** [comment]
@fregante @sindresorhus Thanks for answering.

Yes, I know that normal Chrome Addons can be installed. But I would like to use Edge as secure as possible.
But I do understand, that the MS store would mean more effort for a very small audience right now.

Lets hope, that Edge based on Chromium will not have more success than the old Edge.
