### ISSUE TITLE
Make `update-pr-from-base-branch`'s button smaller

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2723]
Currently the "Update branch" is rather large and it looks like an action that should be taken. It's not really something the user should do that often, so we should probably de-emphasize it.

<table><td>
<img width="753" alt="" src="https://user-images.githubusercontent.com/1402241/72798583-fc4d8380-3c75-11ea-8972-08c10b385d34.png">
</table>

This is an alternative, it just replaces `.btn` with `.btn-link`:

<table><td>
<img width="749" alt="" src="https://user-images.githubusercontent.com/1402241/72798798-67975580-3c76-11ea-8df3-e8ed31ae15bc.png">
</table>

Also:

- [ ] it should probably use a `window.prompt()` window to ask for confirmation
- [ ] it could have an "info" icon with a link to https://github.com/sindresorhus/refined-github/issues/1236 or any other post with a clearer explanation of when this action may be useful

**Comment by fregante** [comment]
Keep in mind: drafts have a different copy. 

<img width="759" alt="Screen Shot 2020-01-22 at 12 08 02" src="https://user-images.githubusercontent.com/1402241/72866997-fad09980-3d0f-11ea-89f7-f425bb2b3ab5.png">

Maybe it can be added as:

>  Draft pull requests cannot be merged. You can [update the base branch](#).

**Comment by daxa298** [comment]
晕过头了我。
