### ISSUE TITLE
Gtihub Actions & Refined : chrome tab crash / freeze / performance

### ISSUE THREAD

**Issue by tristanbes** [sindresorhus/refined-github#2725]
Hello,

I've been actively using Github Actions last week;
I've been noticing that the page performs slowly when `Github Refined` is enabled (and especially when it runs our cypress tests).

For example, when running cypress tests, the page slows down util the page is completely unresponsive and the Chrome (v79.0.3945.130) is totally frozen (even a close tab does not work). And this happens very quickly (few seconds)

I've disabled the extension for now and i've not encountered tab crash/ total freeze once since, even though the page is still slow because I guess of the size of the output log of our cypress tests.

Is there any text parsing or dom computing/analysis that could explain why it crashes the tab ?

![upgrade_JS_deps_by_tristanbes_·_Pull_Request__794_·_Yproximite_condictio](https://user-images.githubusercontent.com/346010/72810814-a6211600-3c5e-11ea-8549-b62ba7107666.png)

Thanks.

**Comment by tristanbes** [comment]
I've tested in private mode under chrome, it's not slow.

I suspect that LastPass extension is performing heavy DOM search looking for input login / input password for its helper; Sorry for the noise;

**Comment by fregante** [comment]
So is it LastPass or Refined GitHub?
