### ISSUE TITLE
Support exporting and importing the extension’s features configuration

### ISSUE THREAD

**Issue by thibaudcolas** [sindresorhus/refined-github#2726]
I’d like to have a way to save the settings of the extension (whether features are enabled or not), and ideally also a way to load saved settings back. For me this would be useful to:

- Sync the extension’s settings between my two installations – one on Chrome stable, one on Canary. Currently I have to do this manually, which feels more tedious than it could be considering the number of features.
- Have a backup. While all of my extension’s settings are saved with Chrome’s sync feature, I’d also like to have an offline backup (e.g. in a dotfiles repository, where I store configuration for my IDE / terminal / etc).
- Share my config with coworkers / others. Like people share snippets of JSON config for VS Code.

Example URL:

I think this would live under the extension’s options modal: [`chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf`](chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf).

---

For implementation, I think this could either be:

- A pair of "Save configuration" and "Load configuration" buttons, which save (and prompt for) a JSON file with key-value pairs for all the features. Potentially JSON5 with the features’ descriptions as comments. Or any other key-value format.
- Inspired by VS Code settings, a toggle to switch between the current features checkboxes UI, and a JSON version of it. Then exporting/importing the config would just be a matter of copy-paste.

**Comment by fregante** [comment]
I thought about adding an import/export feature, but it would be rather simple: just export/import buttons that save/load a plain JSON file.

This is tracked here: https://github.com/fregante/webext-options-sync/issues/23

If you’d like this, the only *option* would be to send a PR to that project. I’m thinking `OptionsSync#syncForm` could automatically listen to `.js-options-export` and `.js-options-import` `<input>` elements.

**Comment by thibaudcolas** [comment]
I think I’ll pass, thank you. https://github.com/fregante/webext-options-sync/issues/23 references #2120, which is quite similar to what I’m suggesting here, and was also downvoted / closed. I have the same use case as the the comment marked as off-topic https://github.com/fregante/webext-options-sync/issues/23#issuecomment-568515263, (different Chrome profiles for work and personal projects). So for now manual syncing it is.

**Comment by fregante** [comment]
This is the right way to import/export it programmatically:

## Export 
1. Open `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/options.html`
2. Open the developer tools
3. Run this to copy the options to your clipboard (it's a compressed string) **and** the command needed to import it
	```js
	copy('browser.storage.sync.set(' + JSON.stringify(await browser.storage.sync.get('options')) + ')')
	```

## Import

1. Open `chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/options.html`
2. Open the developer tools
3. Paste what you copied and run it
