### ISSUE TITLE
Can we filter our issues by specifying a wildcard for a title?

### ISSUE THREAD

**Issue by atreeon** [sindresorhus/refined-github#2727]
`title:"monet*"`
should return `monetisation` and `monetization`

`title:"*onet*"`
should return `bonet` and `monetisation`

When there are many issues it becomes difficult to find them without this feature so it would be a great help if it existed.  

Does it exist already?  Could it be implemented if not?

**Comment by sindresorhus** [comment]
I think it would be better to send this feature request to GitHub: support@github.com

This is not something we can easily implement, if even at all.

**Comment by atreeon** [comment]
ok, I will close then.  Thank you

**Comment by fregante** [comment]
I think only Algolia can do this, it requires knowing the whole content of the repo, it's not something we can do in the front end.
