### ISSUE TITLE
🌶 💵 ✨ Fund the features you want to see! 

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2730]
Is there a feature you'd really like to see?

Fund it! 💵

How much time would a feature save you? Is it worth $10? $20?

IssueHunt makes it easy to fund issues, which helps them get completed much faster!

## How

1. [Sign into IssueHunt](https://issuehunt.io/)
1. [Find an issue](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22help+wanted%22) you'd like closed.
1. Paste its URL in [IssueHunt's search box](https://issuehunt.io/r/sindresorhus/refined-github)
1. Fund what you want in the sidebar of that page.

Just one note: ensure that the issue has the `help wanted` label.

## Help

Leave a comment if you have questions

## Earn

We have a few [funded issues](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22%3Adollar%3A+Funded+on+Issuehunt%22), send a thoughtful PR to earn the bounty! Make sure the objective of the issue is clear before opening a PR.

**Comment by xplendour** [comment]
Does it really work?

**Comment by Hamdikhalid43** [comment]
SAMSUNG GALAXY C9 PRO
POWERD BY ANDROID 8.
