### ISSUE TITLE
Feature request: add tag to users

### ISSUE THREAD

**Issue by connorjclark** [sindresorhus/refined-github#2740]
Would be very useful to be able to tag a user (ex: "works @Shopfiy", "Amplitude UX eng", etc.) and have that label appear next to a comment author's name.

Example URL: any issue / pr page

**Comment by fregante** [comment]
That sounds useful but anything that requires storing data/settings probably doesn’t belong to Refined GitHub, also because we’re limited to 5MB and each feature has to share it.

**Comment by sindresorhus** [comment]
I think it would be better to send this feature request to GitHub: support@github.com
