### ISSUE TITLE
Mark all merged PR notifications as read

### ISSUE THREAD

**Issue by Nachtalb** [sindresorhus/refined-github#2741]
Example URL: https://github.com/notifications

A button next to the ones already there which marks all notifications of merged PR's as read. This is especially useful when the user is in a team and gets notified about all packages maintained in this team.

**Comment by fregante** [comment]
You will be able to create your own filter in the new Notifications Beta, probably [`is:pr reason:state-change`](https://help.github.com/en/github/managing-subscriptions-and-notifications-on-github/managing-notifications-from-your-inbox#supported-queries-for-custom-filters):

![](https://i2.wp.com/user-images.githubusercontent.com/158833/68600698-e31c9f80-049a-11ea-8967-61e4a615fad3.png?resize=2880%2C1800&ssl=1)

**Comment by MarkWareham** [comment]
I don't see how it's possible to filter to "merged PR's" from your response @fregante ?
state-change does not indicate merge status. I see no other appropriate filter keyword in the linked page

**Comment by fregante** [comment]
Indeed. Refer to https://github.com/sindresorhus/refined-github/issues/3229 for a future solution though.
