### ISSUE TITLE
Link to you subscribed discussion in the current repo

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2746]
GitHub lets you see which discussions you're subscribed to: https://github.com/notifications/subscriptions

It also lets you filter them by repo: https://github.com/notifications/subscriptions?repository=MDEwOlJlcG9zaXRvcnk1MTc2OTY4OQ%3D%3D

Perhaps we can find a place for a link to that view from the repo itself, in the discussion list: https://github.com/sindresorhus/refined-github/issues

I'm guessing we can add a link in this dropdown, even though it would link to a completely different view:

<img width="318" alt="Filters dropdown" src="https://user-images.githubusercontent.com/1402241/73590990-adc4a280-451b-11ea-8e98-4a2892babd6c.png">

---

Initially suggested by @aspiers in https://github.com/sindresorhus/refined-github/issues/1604#issuecomment-472001432

Useful?

**Comment by fregante** [comment]
You might have seen that the link is "encrypted" and it doesn't say it's for `sindresorhus/refined-github`:

```
https://github.com/notifications/subscriptions?repository=MDEwOlJlcG9zaXRvcnk1MTc2OTY4OQ%3D%3D
```

Thankfully this is just a base64 of the repo ID:

```js
searchParams.set('repository', btoa(`010:Repository${select('[name="repository_id"]').value}`))
```

**Comment by aspiers** [comment]
That would be great!  And well done on figuring out the base64-ness.  I can't quite believe that GitHub didn't implement this properly per repo, as it's such an obvious flaw in the design.  It's pretty frustrating that they went to all the effort of interviewing people about the UX design prior to releasing the feature, and yet ignored or disagreed with my feedback that this would be needed.

**Comment by donmedinasr69** [comment]
#2671

**Comment by donmedinasr69** [comment]
Open this issue

**Comment by donmedinasr69** [comment]
@fregante
