### ISSUE TITLE
See "Last updated" date on Pinned issues

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#2747]
Example URL: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

I am so used to seeing when the last time an issue was updated (thanks RH 😉), it would be nice to have it on pinned issues.
The only time I would want to see it, is if there is a comment. (not a label update etc..)

Draft:
![image](https://user-images.githubusercontent.com/16872793/73609928-59173b00-45a0-11ea-9243-15eda94ee027.png)

something like this should do the job 

```graphql
{
  repository(owner: "sindresorhus", name: "refined-github") {
    issue (number:2671){
      comments(last:1) {
          nodes {
            updatedAt
          }
      } 
    }
  }
}
```

**Comment by fregante** [comment]
Sounds reasonable. Does GitHub ever show anything else on that line? Like any tags and such

**Comment by yakov116** [comment]
@fregante did some spot checking. Not that I noticed.

**Comment by fregante** [comment]
That wouldn’t match the time that GitHub shows, we’d have to use the issue’s update time, not the last comment (which also doesn’t include review comments, as far as I know)

**Comment by yakov116** [comment]
@fregante exactly my point. I don't see the need to know when a `help wanted` label has been added. I wish github had an option sort by last comment added.

I want to know when the last comment was added.

**Comment by yakov116** [comment]
What if we would write instead of updated, commented?

**Comment by fregante** [comment]
My point is that we can't change the how GitHub's regular sorting works so it's best to match its definitions as well. If an issue appears both pinned and at the top of an issue list the user will see 2 different dates, labelled slightly different. We shouldn't do that.

**Comment by yakov116** [comment]
@fregante OK.. 

I started writing a PR. I got so lost with typescript that I sort of gave up :(

**Comment by fregante** [comment]
If it works but types give you grief, open a draft PR and ask for help

**Comment by yakov116** [comment]
@fregante will do
