### ISSUE TITLE
Add "Bugs" tab

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2749]
<img width="454" alt="" src="https://user-images.githubusercontent.com/1402241/73672788-16f51300-46e0-11ea-862b-c1ea5a584aab.png">

It would strictly link to the [`bug` label](https://github.com/sindresorhus/refined-github/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug), which is the most common label name. The "Pinned issues" section would be hidden like it's hidden in the PR tab.

If no issues are found under the label, the tab wouldn't be added.

Useful or annoying? I feel that the current "Issues" tab hides bugs that need to be fixed by merging them with feature requests and all kinds of other noise.

**Comment by jerone** [comment]
Maybe not limit it to issues only, but also to PRs: https://github.com/sindresorhus/refined-github/labels/bug

**Comment by yakov116** [comment]
why not be like the is merged?

**Comment by fregante** [comment]
> but also to PRs

I don't think it would be very useful. While PRs may have that label, they aren't bugs, they're bugfixes 😅

**Comment by jdreesen** [comment]
Maybe they're a failing test case to showcase the bug ;)

**Comment by fregante** [comment]
Feedback wanted in #2750, there are a couple of points to discuss

**Comment by NN---** [comment]
> I don't think it would be very useful. While PRs may have that label, they aren't bugs, they're bugfixes 😅

Same way as not every issue is a bug, not every PR is a bugfix.
Probably there should be another BugFix tab ?
