### ISSUE TITLE
Display latest release version next to repo name

### ISSUE THREAD

**Issue by muuvmuuv** [sindresorhus/refined-github#2756]
I would like to see the latest pre/-release version (with a link to it) next to the repositories name with highlighting for states like `rc`, `beta` or anything else.

![Bildschirmfoto 2020-02-04 um 12 29 12](https://user-images.githubusercontent.com/11534760/73741167-f497df80-4749-11ea-8ea8-0d07cbf67d4d.png)

<details>
<summary>Code:</summary>

```css
font-size: 10px;
color: rgb(19, 151, 27);
background: rgba(18, 228, 32, 0.62);
border: 1px solid rgb(26, 211, 37);
border-radius: 3px;
padding: 2px 6px;
font-weight: bold;
```

In `//*[@id="js-repo-pjax-container"]/div[1]/div[1]/div/h1`:
```html
<h1 class="public  d-flex flex-wrap flex-items-center break-word float-none " style="display: flex;align-items: center;">
    <svg class="octicon octicon-repo" viewBox="0 0 12 16" version="1.1" width="12" height="16" aria-hidden="true" style="width: 14px;height: 18px;margin-top: 2px;margin-right: 3px;"><path fill-rule="evenodd" d="M4 9H3V8h1v1zm0-3H3v1h1V6zm0-2H3v1h1V4zm0-2H3v1h1V2zm8-1v12c0 .55-.45 1-1 1H6v2l-1.5-1.5L3 16v-2H1c-.55 0-1-.45-1-1V1c0-.55.45-1 1-1h10c.55 0 1 .45 1 1zm-1 10H1v2h2v-1h3v1h5v-2zm0-10H2v9h9V1z"></path></svg>
  <span class="author ml-1 flex-self-stretch" itemprop="author">
    <a class="url fn" rel="author" data-hovercard-type="user" data-hovercard-url="/users/sindresorhus/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/sindresorhus">sindresorhus</a>
  </span>
  <span class="path-divider flex-self-stretch">/</span>
  <strong itemprop="name" class="mr-2 flex-self-stretch">
    <a data-pjax="#js-repo-pjax-container" href="/sindresorhus/refined-github">refined-github</a>
  </strong>
  <span itemprop="version" class="mr-2 flex-self-stretch" style="font-size: 10px;color: rgb(19, 151, 27);background: rgba(18, 228, 32, 0.62);border: 1px solid rgb(26, 211, 37);border-radius: 3px;padding: 2px 6px;font-weight: bold;/* line-height: 1.4; */">v2.3.4
  </span>
  
</h1>
```

</details>

**Comment by fregante** [comment]
Context: We already show the latest version on the Code tab: https://github.com/sindresorhus/refined-github/blob/master/source/features/latest-tag-button.tsx

**Comment by muuvmuuv** [comment]
@fregante Ah! Needed to add a GitHub Token. This should be noted somewhere since the extension hasn't opened the options tab on installation like other extension do to note that I have to add a Token for some features. 

Anyway I suggest a new or additional position for it, so it can be seen on every page.

**Comment by fregante** [comment]
Refined GitHub opens https://github.com/sindresorhus/refined-github/issues/1137
I only recently added a mention of the token on that page.

**Comment by fregante** [comment]
> Anyway I suggest a new or additional position for it, so it can be seen on every page.

I don't think it's a piece of information important enough that needs to be see on every single page of the repo. Usually this info doesn't change that frequently so visiting the Code tab (or the new Releases tab) should be enough.

**Comment by muuvmuuv** [comment]
Oh, my bad 🤦‍♂️, I have totally overseen that passage. Just read "receive updates", subscribed and closed it. I will learn from this and take a closer look next time.

Okay, agreed :) Just missed that little feature from one of my older extensions (can't remember which it was).
