### ISSUE TITLE
latest-release not correctly recognized

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2758]
in a private repo we have several releases.

release numbers like 1.9.7, 1.9.8 and since today 1.10 and 1.10.0

![image](https://user-images.githubusercontent.com/120441/73764494-6c2e3480-4773-11ea-97fa-e4a323d7a597.png)

refined github does not correctly recognize that the latest version is 1.10.0.
instead it tells me that 1.9.8 is the latest version:

![image](https://user-images.githubusercontent.com/120441/73764451-4f91fc80-4773-11ea-98e2-fcc74c872743.png)

**Comment by fregante** [comment]
This is due to the cache. It's set to expire after 1 day so it's bound to show some out of date information for up to 24 hours

**Comment by staabm** [comment]
Maybe the cache should/could be pruned when the browser is used the create a new release?

**Comment by sindresorhus** [comment]
Also, FYI, `1.10.0` and `1.10` are semantically the same version.
