### ISSUE TITLE
Duplicate forks in `forked-to`

### ISSUE THREAD

**Issue by Kinrany** [sindresorhus/refined-github#2759]
![Screenshot_2020-02-04 Kinrany cargo](https://user-images.githubusercontent.com/1634186/73782491-3d2fb700-47a3-11ea-8f2c-46fb305ee03a.png)

The dropdown that shows my forks next to the "Fork" button contains two links to the same repo: one with username in lowercase and one in Uppercase.

Browser: Firefox

**Comment by Kinrany** [comment]
Aaand it's gone.

But now the link-to-my-fork button sometimes shows up in my own repo, and sometimes does not show up in the upstream repo. Sometimes it goes away when I reload the page, sometimes it doesn't.

I'm assuming someone is working on this feature right now :D

**Comment by fregante** [comment]
> I'm assuming someone is working on this feature right now :D

That's not how it works, the extension takes days to be published, we don't push code updates in real time like the website owner could 😅

**Comment by fregante** [comment]
My guess is maybe `show-names` is interfering with the repo name and due to the username capitalization it doesn't think that the repo is the same.

Can you look into it if happens again? We copy that list from the overlay that appears when clicking on "Fork"; `show-name` shouldn't apply there.

**Comment by Kinrany** [comment]
Happened again with https://github.com/rust-lang/cargo

The dropdown contains `kinrany/cargo` and `Kinrany/cargo`, but the overlay list only shows `Kinrany/cargo`.

**Comment by fregante** [comment]
I found a problem, I don't know if it's related but: 

- when we're on a fork, the Forks list doesn't include the current fork and `forked-to` things there are no other forks available:

<img width="770" alt="" src="https://user-images.githubusercontent.com/1402241/73844690-a2db7c00-4853-11ea-98c3-fb80553ef6a2.png">

When `forked-to` loads this, the list of forks is reset and the button disappears.

cc @jerone

**Comment by fregante** [comment]
I wonder if the list of **your** forks can be reliably retrieved via API, that would solve a lot of issues.

**Comment by Kinrany** [comment]
Can you just get the intersection of the list of all forks with the list of your repos?

**Comment by jerone** [comment]
> I found a problem, I don't know if it's related but:
> 
>     * when we're on a fork, the Forks list doesn't include the current fork and `forked-to` things there are no other forks available:

I have noticed this too. In [early version](https://github.com/sindresorhus/refined-github/pull/2216/files#diff-ff16301f232100bd87e910eb98614f66L27-L30) of the code, the cache was extended with forks. Currently, the [whole cache](https://github.com/sindresorhus/refined-github/blob/master/source/features/forked-to.tsx#L51-L55) is replaced with new forks, which when you are on a fork, doesn't contain all forks.

We need to extend [`saveAllForks`](https://github.com/sindresorhus/refined-github/blob/master/source/features/forked-to.tsx#L24-L30) with [this](https://github.com/sindresorhus/refined-github/blob/master/source/features/forked-to.tsx#L51) check.

---

Back to the original issue; interference with `show-names` is my only thought too.

**Comment by fregante** [comment]
> We need to extend saveAllForks with this check.

Sounds good, it can probably be _moved_ to `save`

I think that line is exactly the issue as well and `show-names` might not be the culprit after all. That piece of code uses the current page URL… which could be `aNyThInG/repo` so it won’t match the filters (`'aNyThInG/repo' !== 'anything/repo'`) and will be added twice.

**Comment by jerone** [comment]
Makes sense :+1:
