### ISSUE TITLE
cannot revert changes in PR

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2761]
I tried reverting the changes in the first file of this PR: https://github.com/redaxo/redaxo/pull/3056/files

using FF 74.0a1 (2020-02-04) (64-bit)

I am getting the "Revert failed. See console for details" error, but no errors printed in the console. A access token is configured for the Refined Github extension.

![image](https://user-images.githubusercontent.com/120441/73828522-ae9e5280-4801-11ea-8065-cee8e58dab34.png)

**Comment by staabm** [comment]
PS: the text is only visible on hover. otherwise its white text on white background

![image](https://user-images.githubusercontent.com/120441/73828683-fde48300-4801-11ea-89cf-d163e9f404cf.png)

**Comment by fregante** [comment]
Does it fail after "Committing..." or "Reverting..."?


Did you set a personal token and does it still have access to the repo? I just tested it and it works for me.

**Comment by staabm** [comment]
it fails after "Committing"

a PAT was configured. I just created a fresh one to be sure it is valid. the same error happens with the new token.

**Comment by fregante** [comment]
Can you try in Chrome? Firefox hides console errors

**Comment by staabm** [comment]
just tried in MS Edge. it works there.

**Comment by fregante** [comment]
Check for errors in the [browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console), it should include every error of the browser, so open it, clear it, and then try reverting it.

**Comment by staabm** [comment]
oh, I was looking into the wrong console.

in the browser console I can see a http `422 Unprocessable Entity` error
![image](https://user-images.githubusercontent.com/120441/73846433-d226c480-4824-11ea-9d1a-9e9e460b799a.png)

Request headers for this request:
![image](https://user-images.githubusercontent.com/120441/73846582-0b5f3480-4825-11ea-98ee-0d9dfbb818d8.png)

**Comment by fregante** [comment]
I can't reproduce any of these issues in Firefox 74 (not alpha); the dropdown message is visible without hovering it (the hover never appears, we're just using GitHub's own style for the dropdown anyway)

<img width="210" alt="\" src="https://user-images.githubusercontent.com/1402241/77157274-536aab80-6aa1-11ea-8053-7ca50f167082.png">

My guess is that Firefox alpha was misbehaving

**Comment by fregante** [comment]
This was the request the browser sent ("Copy as Fetch" from the Network tab)

```js
await fetch("https://github.com/fregante/sandbox/tree-save/fregante-patch-2/history.csv", {
    "credentials": "include",
    "headers": {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0",
        "Accept": "*/*",
        "Accept-Language": "en-US,en;q=0.5",
        "Content-Type": "application/x-www-form-urlencoded"
    },
    "referrer": "https://github.com/fregante/sandbox/pull/6/files",
    "body": "authenticity_token=uaxzu4EZ5HmxA7MJ%2BK0P41zrhP9yNamzdmmQqeHoVq%2B6DxqAXpkkFRQJaW%2FUX77EA%3D%3D&filename=history.csv&new_filename=history.csv&commit=5b76c86b858897fdcb1e0ab4dedd65c138532fee&same_repo=1&pr=&content_changed=&value=lol%0A&message=Revert+history.csv&placeholder_message=Update+history.csv&description=&author_email=opensource%40bfred.it&commit-choice=direct&target_branch=fregante-patch-2&quick_pull=",
    "method": "POST",
    "mode": "cors"
});
```

## Request headers
```
POST /fregante/sandbox/tree-save/fregante-patch-2/history.csv HTTP/1.1
Host: github.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:74.0) Gecko/20100101 Firefox/74.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://github.com/fregante/sandbox/pull/6/files
Content-Type: application/x-www-form-urlencoded
Origin: https://github.com
Content-Length: 435
DNT: 1
Connection: keep-alive
Cookie: ..................
```

## Response headers

```
HTTP/1.1 302 Found
Date: Fri, 20 Mar 2020 10:53:50 GMT
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Server: GitHub.com
Status: 302 Found
Location: https://github.com/fregante/sandbox/blob/fregante-patch-2/history.csv
Cache-Control: no-cache
Set-Cookie: .................
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
X-Frame-Options: deny
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Expect-CT: max-age=2592000, report-uri="https://api.github.com/_private/browser/errors"
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; connect-src 'self' uploads.github.com www.githubstatus.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src github.githubassets.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; frame-src render.githubusercontent.com; img-src 'self' data: github.githubassets.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; manifest-src 'self'; media-src 'none'; script-src github.githubassets.com; style-src 'unsafe-inline' github.githubassets.com
Vary: X-PJAX, Accept-Encoding, Accept, X-Requested-With
X-GitHub-Request-Id: C9A5:3F635:2F771DB:444AE45:5E74A0BD
```
