### ISSUE TITLE
Extra padding on CI status indicator

### ISSUE THREAD

**Issue by Vehmloewff** [sindresorhus/refined-github#2762]
It should look like this:
![image](https://user-images.githubusercontent.com/45398751/73867758-d5ae5180-480c-11ea-8abe-d27c31c1e21d.png)

It actually looks like this:
![image](https://user-images.githubusercontent.com/45398751/73867830-f5de1080-480c-11ea-9d4c-78851a608825.png)

**Comment by fregante** [comment]
Are you on Chrome Windows?

**Comment by Vehmloewff** [comment]
No.  Browser is Chrome, OS is `Ubuntu 18.04.4 LTS`

**Comment by Vehmloewff** [comment]
If you look at the two pictures, you might also notice that the 'repo' icon is a little too low also.  

This is the case even when the extension is disabled.

**Comment by jerone** [comment]
Same with Firefox 72.0.2 (64-bit) on Windows.

![image](https://user-images.githubusercontent.com/55841/73880822-74639e00-485f-11ea-86ab-aa0b2697ea58.png)
