### ISSUE TITLE
Wrong `releases-tab`  position if repo name contains "settings"

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#2763]
![image](https://user-images.githubusercontent.com/55841/73887396-b8f53680-486b-11ea-9955-5f38e02d4b23.png)

# Test
* https://github.com/atom-community/sync-settings

# Fix
https://github.com/sindresorhus/refined-github/blob/master/source/features/releases-tab.tsx#L61 should be 
```diff
-appendBefore('.reponav', '.reponav-dropdown, [href$="settings"]', releasesTab);
+appendBefore('.reponav', '.reponav-dropdown, [href$="/settings"]', releasesTab);
```
Same as https://github.com/sindresorhus/refined-github/blob/master/source/features/releases-tab.tsx#L17

**Comment by fregante** [comment]
I think the selector would still apply to repos named `settings`. Is there anything more specific? Maybe they added a class now or we can just add `:last-child` (which will break if other extensions added extra tabs, but by “break” I mean the tab will be added at the very end. Not a big deal)

**Comment by arnaudvalle** [comment]
How about using something like `[data-selected-links^="repo_settings"]`?

**Comment by fregante** [comment]
I think that's right
