### ISSUE TITLE
Add copy-pr-link feature

### ISSUE THREAD

**Issue by oswaldoacauan** [sindresorhus/refined-github#2764]
Would be useful to have an option where we copy to clipboard the URL of newly created PRs. 

Scenario: 
- Open PR
- Copy the URL in the address bar
- Post the URL in a Slack channel so it get reviewed

Example URL: https://github.com/sindresorhus/refined-github/pulls

**Comment by fregante** [comment]
I don't think a web page should automatically copy a URL to the clipboard upon loading, that sounds like unexpected behavior.

I think the fastest way to do this is:
1. ctrl+l (focuses the URL bar)
1. ctrl+c (copies it)

Same on macOS with cmd
