### ISSUE TITLE
allow multiline selection in diff view without having both views intermingled

### ISSUE THREAD

**Issue by timotheecour** [sindresorhus/refined-github#2765]
This feature request is to allow multiline selection in diff view without having both views intermingled.
Basically, exactly what's described here: https://stackoverflow.com/questions/48446463/how-to-cleanly-clipboard-copy-code-from-a-github-com-diff

Is that even possible within the extension or would that require upstream github changes?

**Comment by fregante** [comment]
This is almost impossible, unless there’s a way to exclude text from selection exactly before the copy happens. Maybe something like:

```
on before copy
  Start/end selection position determine which side user intends to select
  apply user-select: none on the other side
  setTimeout undo user-select change 
```

**Comment by timotheecour** [comment]
would adding a button avoid having to mess with timeout?
then i'm assuming it's a matter of post-processing the clipboard so that it'd strip from each line the right half (or left half), modulo edge cases

**Comment by fregante** [comment]
I would be less comfortable post-process the clipboard, if anything changes we might end up removing something we don’t want. If this can be done “natively” with CSS then it might just work

**Comment by fregante** [comment]
Preliminary testing shows that this is feasible and relatively easy too. PR welcome.

Instead of "on before copy" I'd use `mousedown`/`mouseup` instead because, once the text is selected, applying `user-select` doesn't deselect it
