### ISSUE TITLE
[BUG] Invalid bot (GitHub app) page URLs in the contributors hovercard

### ISSUE THREAD

**Issue by webknjaz** [sindresorhus/refined-github#2766]
This is visible @ https://github.com/swinton/github-rest-apis-for-insomnia.

1. Hover that "3 contributors" text.
2. A first icon is a person, followed by two bots (greenkeeper and dependabot).
3. Their links lead to https://github.com/greenkeeper%5Bbot%5D and https://github.com/dependabot%5Bbot%5D
4. Instead, they should point to https://github.com/apps/greenkeeper and https://github.com/apps/dependabot

**Comment by jerone** [comment]
This is actually an GitHub bug. It's better to report this to GitHub https://support.github.com/contact

**Comment by webknjaz** [comment]
What do you mean? GitHub has this bug in widgets it renders. But in this case, the widget is rendered by Refined GitHub AFAICS.

**Comment by jerone** [comment]
Maybe you can attach an screenshot, because the hoverbox I can see is **not** created by GitHub Refined:

![image](https://user-images.githubusercontent.com/55841/74108535-a59fdf00-4b7b-11ea-882f-fa94e9086c6a.png)

**Comment by webknjaz** [comment]
Oh, I thought it was... It doesn't appear in browser incognito mode so I assumed that it must be coming from the extension.

Sorry for bothering you.

**Comment by jerone** [comment]
> It doesn't appear in browser incognito mode

You have to login to get that hoverbox.
