### ISSUE TITLE
[Marketing] How to list the extension in the GitHub Browser Extensions showcase?

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#277]
https://github.com/showcases/github-browser-extensions

Any ideas how to enlist the extension in the showcase? Probably contact GitHub?

@sindresorhus You have two more extensions in there.

**Comment by hkdobrev** [comment]
@zeke You could probably give us some insight? I know you've used the extension at one point. Thanks!

**Comment by zeke** [comment]
👋 I didn't know about that showcase. I will look into who's behind it and report back.

**Comment by zeke** [comment]
cc @leereilly who works on the showcase.

**Comment by sindresorhus** [comment]
Any updates? :)

**Comment by zeke** [comment]
Just pinged Lee in Slack...

**Comment by leereilly** [comment]
Added :metal:

**Comment by DrewML** [comment]
Thanks @leereilly and @zeke!
