### ISSUE TITLE
Sidebar is not sticky

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#2770]
![no-widget](https://user-images.githubusercontent.com/9874850/74180045-0512f300-4c3f-11ea-8b1e-c36c8127b241.png)

Zooming out makes it appear (Zoom in as well!) - then it sticks, also when returning to 100% zoom...

My laptops resolution is 1366x768
Firefox 72.0.2 on Windows 10
Addon version 20.2.3

**Comment by fregante** [comment]
Can you take a screenshot of the whole sidebar at 100%?

When the sidebar refreshes the listener forgets about it (because it’s a new element) so we need to use or helper (I think called onUpdatableContent…) to make sure it’s listened to again.

**Comment by tooomm** [comment]
Which screenshot do you need me to take exactly? Can you explain a bit further, please?
Same as above, but after zooming to make the sidebar appear?
Or the normal view at the very top?

**Comment by fregante** [comment]
1. Zoom at 100%
2. Refresh the page
3. Scroll just enough that the whole sidebar is visible

**Comment by tooomm** [comment]
>Can you take a screenshot of the whole sidebar at 100%?

![widget2](https://user-images.githubusercontent.com/9874850/74248168-75754f00-4ce7-11ea-864c-c769a557ea6d.png)

<br>

>And also, is the sidebar sticky after doing this?

Making the sidebar appear via zooming in or out work, going back to 100% after that keeps it. Refreshing the page then makes the sidebar disappear.

<br>

I also realized that moving out of fullscreen makes the sidebar sticky again. Going back to keep it. Refreshing the page in fullscreen removes it again.

**Comment by fregante** [comment]
Avoid using the zoom/fullscreen to test it, it's irrelevant: the stickiness is determined on `resize`, so just resize the window.

Anyway, it's not working for me at all now

**Comment by tooomm** [comment]
Resizing has the same result.
Moving down leads to the sidebar disappearing. Making the window narrower suddenly makes it appear. Going back to normal width keeps it until hitting refresh.

How does the sidebar update in between?
It **never** works for me

**Comment by fregante** [comment]
Please record a screencast because I have no idea

**Comment by fregante** [comment]
Also try in chrome and see if there are any errors in the console

**Comment by tooomm** [comment]
>Please record a screencast because I have no idea

https://screencast-o-matic.com/watch/cYn2oPwyaf

**Comment by fregante** [comment]
So I think that at the first load, the sidebar is not found and the feature fails silently. Then `resize` does find it and it keeps working.

**Comment by fregante** [comment]
I looked at the code and it should not fail silently. Can you open the Browser Console, clear it, and refresh this page?

Firefox doesn’t show errors in the regular console, so open the Browser Console from the Developer menu

**Comment by tooomm** [comment]
> ℹ️ Refined GitHub: `show-names`: Personal token required for this feature features.tsx:85:20
ℹ️ Refined GitHub: `bugs-tab`: Personal token required for this feature features.tsx:85:20
undefined pageModifier.js:585:17
Use of Mutation Events is deprecated. Use MutationObserver instead. pageModifier.js:81:24
This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features! 2770

​

**Comment by dertieran** [comment]
Can't reproduce this in Firefox 74 *(Developer Edition)*, but I also get the waring when scrolling down and the sidebar starts beeing sticky.
> This site appears to use a scroll-linked positioning effect. This may not work well with asynchronous panning; see https://developer.mozilla.org/docs/Mozilla/Performance/ScrollLinkedEffects for further details and to join the discussion on related tools and features!

**Comment by jerone** [comment]
> ℹ️ Refined GitHub: `show-names`: Personal token required for this feature features.tsx:85:20

@tooomm Does the issue presets when you add an GitHub personal access token in GitHub Refined settings?:
![image](https://user-images.githubusercontent.com/55841/74604172-96f58280-50bb-11ea-8b62-d3a4111b04f6.png)

**Comment by tooomm** [comment]
> Can't reproduce this in Firefox 74 _(Developer Edition)_, but I also get the waring when scrolling down and the sidebar starts beeing sticky.

@dertieran Exactly. When the sideboard should start moving/being sticky the warning appears in the log for me, too.
I'm on Firefox 73.0 (64bit), Windows 10. Do you use the 32bit version or a different OS?

**Comment by dertieran** [comment]
@tooomm I'm running on Arch Linux.
Do you know where `pageModifier.js` is from?
That doesn't look like rgh, maybe it's some extensions clashing?

**Comment by tooomm** [comment]
>Do you know where `pageModifier.js` is from?
That doesn't look like rgh, maybe it's some extensions clashing?

It's from [Citavi Picker](https://addons.mozilla.org/en-GB/firefox/addon/citavi-picker/)

I disabled all extensions except uBlock Origin, NoScript and a search provider next to Refined GitHub. No change, even disabling those one by one didn't change the result.

**Comment by fregante** [comment]
We don’t have pageModifier.js and the warning is not caused by this feature. The warning is about scroll event listeners, which we don’t have. The sidebar is handled via sticky. We only listen to `resize`

**Comment by tooomm** [comment]
I'm sorry @fregante. But with only `Refined GitHub` enabled I still get those:
![refined gh](https://user-images.githubusercontent.com/9874850/74672850-65a9af00-51ae-11ea-89e2-9f5c92133eb1.png)

**Comment by dertieran** [comment]
@fregante is right the warning doesn't have anything to do with this issue either. :disappointed:
It is caused by the way Github makes the *issue* header sticky, they listen for the `scroll` event.
Coincidentally that happens around the same time as the sidebar getting sticky, you can test that by also disabling `rgh`.

**Comment by tooomm** [comment]
That makes sense!
Ok, the console events don’t help us here then.

Can you try FF 73 maybe @dertieran ?

**Comment by tunnckoCore** [comment]
It's not working for Chrome too. Along with other features

![2020-02-18-123553_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/74728287-22514e00-524b-11ea-9199-6d00cb575d6b.png)

**Comment by fregante** [comment]
@tooomm are you checking the Browser Console? That looks like the Web Console, it won't show errors from extensions.

**Comment by fregante** [comment]
@tunnckoCore Are you sure those errors are from the current page? `link-to-file-in-file-history` does not run on issues.

**Comment by tooomm** [comment]
>@tooomm are you checking the Browser Console? That looks like the Web Console, it won't show errors from extensions.

You are so right. First time using either of them, thanks for pointing out. 🙈 

I get these messages there (only Refined GitHub enabled):
>NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84
NS_ERROR_FAILURE: Component returned failure code: 0x80004005 (NS_ERROR_FAILURE) [nsIInterfaceRequestor.getInterface] network-response-listener.js:84

**Comment by fregante** [comment]
Maybe I know the reason. Try this:

1. Make the window as big as possible
2. Zoom out
3. Refresh the page

This should _guarantee_ that the sidebar has enough viewport space to be always visible so the feature _should_ always work.

**If it works,** this is probably due to `clean-sidebar`:
1. `sticky-discussion-sidebar` runs, the sidebar doesn't fit, so it doesn't make it sticky
2. `clean-sidebar` runs, reduces the sidebar height, but it's too late for `sticky-sidebar`.

At this point you think that the sticky feature doesn't work because _"the sidebar fits!11!1"_

**Comment by fregante** [comment]
Possible fix: move

https://github.com/sindresorhus/refined-github/blob/master/source/content.ts#L48

after

https://github.com/sindresorhus/refined-github/blob/master/source/content.ts#L127

**Comment by tooomm** [comment]
>Maybe I know the reason. Try this:
>
>   1. Make the window as big as possible
>   2. Zoom out
>   3. Refresh the page

That made it work for me.
After doing so and changing zoom to 100% again the sidebar was sticky and stayed sticky when scrolling.

**Comment by tooomm** [comment]
Thanks for taking care! It works :)
