### ISSUE TITLE
'Attach files' button not working / throwing `Cannot read property 'click' of null`

### ISSUE THREAD

**Issue by jennifer-shehane** [sindresorhus/refined-github#2774]
When clicking the 'Attach Files' button, the file dialog does not open. An error is logged to DevTools console:

```
content.js:8271 Uncaught TypeError: Cannot read property 'click' of null
    at HTMLDocument.triggerUpload (content.js:8271)
    at HTMLDocument.listenerFn (content.js:369)
```

Stack trace goes to this line of code in `content.js`

<img width="595" alt="Screen Shot 2020-02-12 at 3 49 09 PM" src="https://user-images.githubusercontent.com/1271364/74320817-ad47c980-4daf-11ea-97e4-cc22b1c05a99.png">

I can't use the button in this very issue, so I guess this issue url is a good url. 😝 

**Gif of behavior**

![](http://g.recordit.co/OexWG8EVmB.gif)

When turning off Refined GitHub, the 'attach files' works from plain GitHub.

![](http://g.recordit.co/Q9hUo7ziME.gif)

It's a bit weird because I only noticed this in the last 24 hours, maybe my extensions didn't update until today? Maybe GitHub changed something in their UI. I'm not sure. Let me know if you need anymore information. 

---

Side Note, how do I disable this feature?? I thought I could click on the icon in the Extensions in Chrome while on a GitHub site and the settings would be there, but that literally just reroutes to github.com.

![](http://g.recordit.co/zvPGOl1VRo.gif)

**Comment by fregante** [comment]
You can just drag and drop files into the comment area.

Probably today GitHub changed the class name so we need to fix it. It should be an easy fix

**Comment by fregante** [comment]
You can access the settings like for every other extension: right click on the icon, click Options

Or `chrome://extensions/` -> Details -> Extension options

**Comment by jennifer-shehane** [comment]
@fregante Thanks! Yeah, didn't see the little arrow to open that link. Thanks for the fast fix also.
