### ISSUE TITLE
Fix "Commit range not found" pages linked from notifications

### ISSUE THREAD

**Issue by waldyrious** [sindresorhus/refined-github#2779]
When pull request branches are force-pushed, the links in the notification tries to open the diff of the new changes, but that does work, resulting in a "Commit range not found" message (and the notification remains marked as unread).

Example URL (copied from the links in the notifications page):
https://github.com/alif-type/libertinus/pull/297/files/4371c159cc447047d55a3012f13ee229c2e9e616..aaf70cbb6f3a5377786da765f635c0f54b7b0569

In such cases, the page should show instead the main PR page — in the example above, https://github.com/alif-type/libertinus/pull/297.

**Comment by fregante** [comment]
This is a bug from GitHub, not refined GitHub

**Comment by waldyrious** [comment]
Fair enough. I'll open an issue at https://github.com/isaacs/github.

**Comment by fregante** [comment]
Report it at github.com/contact

**Comment by waldyrious** [comment]
Update: I've opened https://github.com/isaacs/github/issues/1733.

Note that working around this bug would be quite simple: we would just need to replace `pull/297/files` with `compare` in the link. It works as expected:

https://github.com/alif-type/libertinus/compare/4371c159cc447047d55a3012f13ee229c2e9e616..aaf70cbb6f3a5377786da765f635c0f54b7b0569

**Comment by fregante** [comment]
We can’t do that because we don’t know if the link is valid in the first place, we can just drop that because the link would be less useful in all other cases.
