### ISSUE TITLE
Add "title" attr to emojis

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#278]
Sometimes I have absolutely no idea what an emoji is that someone has used. The markup GitHub uses when rendering emojis is:

``` html
<g-emoji alias="cat" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f431.png">🐱</g-emoji>
```

It would be nice to be able to hover on the icon to actually see what it's name is. This would just involve copying the `alias` value to `title`.

Any objections?

**Comment by sindresorhus** [comment]
I find the `g-emoji` thing annoying. They make emoji render different than the native. Example: https://github.com/sindresorhus/skin-tone (See the first emoji in the description): 
<img width="110" alt="screen shot 2016-08-08 at 23 21 59" src="https://cloud.githubusercontent.com/assets/170270/17496756/f119f5f0-5dbe-11e6-8e40-f74948432b0d.png">

I actually wanted to remove it, but if you see a value in it, we should at least remove the `g-emoji` style that makes it different.

**Comment by jacobbearden** [comment]
Might be platform based but for me, emojis do have a title attribute:

![image](https://cloud.githubusercontent.com/assets/5340692/17613303/e8ef92f2-6018-11e6-85a8-c8ac5b7f7f3f.png)

and the markup is:
```html
<g-emoji alias="ok_hand" fallback-src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44c.png"><img class="emoji" title=":ok_hand:" alt=":ok_hand:" height="20" width="20" src="https://assets-cdn.github.com/images/icons/emoji/unicode/1f44c.png"></g-emoji>
```

On an Ubuntu based operating system, using Chrome

**Comment by lukaszklis** [comment]
What is the expected result here in the end? Adding the `title` attribute for `g-emoji` and removing the styling?

**Comment by hkdobrev** [comment]
@jacobbearden It seems on Ubuntu the fallback-src is transferred to an `<img>` element with a title. Probably the raw emoji there is not supported.

**Comment by hkdobrev** [comment]
@lukaszklis I think we should at least have the title attribute before anything else as it's quite annoying. This is what the original issue is about.

@sindresorhus could you clarify what you mean? Perhaps revert the whole `<g-emoji>` and in practice force the fallback?
