### ISSUE TITLE
Issue count appears as "NaN" for repositories with more than 5,000 open issues

### ISSUE THREAD

**Issue by Calinou** [sindresorhus/refined-github#2780]
- **Browser:** Firefox 72
- **Refined GitHub version:** 20.2.14

Since GitHub displays issue counts above 5,000 as "5,000+", it seems Refined GitHub fails to parse this and displays "NaN" instead. It should probably be changed to subtract the number of bugs from 5,000 and display a trailing `+` to indicate the number of issues is approximate. This happens on https://github.com/godotengine/godot, specifically.

![image](https://user-images.githubusercontent.com/180032/74578428-ed1bd600-4f94-11ea-8395-42f8017d7e33.png)

**Comment by fregante** [comment]
I didn’t anticipate that. 😅

But
- if there’s a total of 7001 issues of which 2000 are bugs, the tab should still display 5000+

So we shouldn’t touch the counter, but:

- if there’s a total of 5001 issues of which 4000 are bugs, now it looks like there are 9001 issues

🤷‍♂️ The only full solution is to also count non-bug issues in the same query

**Comment by Nightfirecat** [comment]
This is an issue for repositories which do not have `+` in the total as well. I'm seeing `NaN` for the total for this repository as well. (addon is disabled for this screenshot to show the unaltered view)

![Screenshot_2020-02-15 runelite runelite](https://user-images.githubusercontent.com/2199511/74584236-02f6be80-4fc8-11ea-826d-9d245fb589f5.png)

**Comment by fregante** [comment]
We need to use:

``` js 
counter.textContent = Number(counter.textContent.replace(/\D/g, '') - bugsCount;
```

**Comment by cajames** [comment]
@fregante This also happens on repos with over 1000 open issues, due to the `,`.

Please see: https://github.com/typeorm/typeorm
<img width="542" alt="Screen Shot 2020-02-19 at 4 04 56 pm" src="https://user-images.githubusercontent.com/1523286/74803650-d0372800-5331-11ea-93b3-2930fff3e12b.png">

Quite like this feature, I've submitted a first attempt at a fix, based on the conversation here. :)
