### ISSUE TITLE
Selectors are broken for tags-dropdown

### ISSUE THREAD

**Issue by hardikmodha** [sindresorhus/refined-github#2781]
tags-dropdown isn't working as expected due to broken selectors.

Actual:
![Screen Shot 2020-02-15 at 12 49 09 PM](https://user-images.githubusercontent.com/22439276/74583845-a4ded100-4ff1-11ea-860d-3b6f865fdb00.png)

Expected:
![Expected Tags Dropdown](https://user-images.githubusercontent.com/22439276/56373231-27ee9980-621e-11e9-9b21-601919d3dddf.png)

**Comment by Esemesek** [comment]
Investigated this issue for a while and it seems that links to tags aren't replaced correctly.
