### ISSUE TITLE
`highlight-collaborators-and-own-discussions` not working on milestone issues list

### ISSUE THREAD

**Issue by jerone** [sindresorhus/refined-github#2792]
Example page: https://github.com/ForkIssues/TrackerWin/milestones/1.45

`highlight-collaborators-and-own-discussions` are not highlighted there.

Maybe more features are not active on that list.

**Comment by dertieran** [comment]
I guess that's just because `/milestones/xxx` isn't supported by `isRepoDiscussionList`.
https://github.com/sindresorhus/refined-github/blob/244052c16032f93623b968e1550372bd71231c84/source/libs/page-detect.ts#L257-L260
