### ISSUE TITLE
‼️❎ More menu always open (Version 20.2.14.922 is broken)

### ISSUE THREAD

**Issue by betatim** [sindresorhus/refined-github#2796]
Hi,

I have been using refined-github for a long time on Firefox (beta update channel) without problems. A few days ago (I think) I noticed that the GitHub UI had changed. This turned out to be because RG has stopped modifying it (and the plain GH looks "weird'). For example the CI status has vanished.

![Screenshot 2020-02-18 at 10 25 50](https://user-images.githubusercontent.com/1448859/74722350-1066af80-5239-11ea-926d-a0766c296507.png)

I am not sure what changed but it seems like basic features that should be there have stopped working. There are errors in my JS console when I visit [this page](https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md):

![Screenshot 2020-02-18 at 10 20 34](https://user-images.githubusercontent.com/1448859/74721906-5f601500-5238-11ea-8c8a-9c8be88cb729.png)

I think this is the source of the problem, but I am not sure how to further  debug it. If I hover over the "injectGlobalHook.js" link in the console it links me to moz-extension://c22f98a5-2aa6-4346-9f98-f4bc11b4aa78/build/injectGlobalHook.js I am guessing this is RG but if you know how to match the UUID to an installed extension that would be great so I can confirm it.

I am running Firefox 73.0 (64-bit) from the beta updates channel on OSX 10.14.6 (18G103). I think the only other noteworthy extension I have installed is Privacy Badger. On version 20.2.14.922 of refined github.

What else should I look at to try and debug what happened/changed?

**Comment by jdreesen** [comment]
You're right, it's not working for me anymore either :(

I'm using Firefox 73.0 (64 bit) on Ubuntu 18.04

**Comment by dwelle** [comment]
Doesn't work on Chrome either, but I'm not seeing any errors in console.

**Comment by darkred** [comment]
> Doesn't work on Chrome either, but I'm not seeing any errors in console.

I confirm the same has happened to me.

Using Chrome 80.0.3987.106 on win10.

I had RGH 20.2.3 . It was working fine 
(I had a personal token in its settings and the "Show the features enabled on each page in the console" checkbox was enabled).

Today I clicked "Update" in chrome://extensions 
and RGH got updated to 20.2.14.922 .
From that point it stopped working,

Additionally, in its settings the personal token no longer exists
and the `Show the features enabled on each page in the console` checkbox is now unchecked.

<details>
 <summary>Options screenshot</summary>

![2020-02-18_122211](https://user-images.githubusercontent.com/723651/74727548-039e8780-524a-11ea-94f8-d35e8f31c020.jpg)
</details>

**Comment by fregante** [comment]
I have Firefox 73.0 on macOS and RG 20.2.14 and most feature work:

<img width="1011" alt="repo header" src="https://user-images.githubusercontent.com/1402241/74732486-5184b100-5285-11ea-956f-13c149b619bf.png">

None of the errors in any of those consoles are related to Refined GitHub.

Have you tried turning it off and on again?

**Comment by darkred** [comment]
> I have Firefox 73.0 on macOS and RG 20.2.14 and most features work.

I also have no problem with RG in Firefox 73.0 on win 10.

For me, RG is not working only in Chrome, and, disabling and re-enabling RG in chrome://extensions doesn't help.

**Comment by fregante** [comment]
I know what happened: 20.2.14.922 is a broken version, I stopped it in Firefox but it was published in Chrome just today. Also you might have downloaded that version in Firefox while it was available

**Comment by fregante** [comment]
# Fix ready

Update your extension as soon as your store shows 20.2.18

<img valign="middle" src="https://img.shields.io/chrome-web-store/v/hlepfoohegkhhmjieoechaddaejaokhf.svg">
<img valign="middle" src="https://img.shields.io/amo/v/refined-github-.svg">

**Comment by jdreesen** [comment]
For me it works again, thx for the quick reaction & fix! :)

**Comment by betatim** [comment]
After upgrading to 20.2.18 on Firefox everything works again. Thanks for the super quick fix.

Closing as it is resolved.

**Comment by silverwind** [comment]
I see some discrepancy in the shipped CSS in Firefox vs. Chrome extensions. Below style is only present in the Firefox extension. Is this related here?

```css
.rgh-collaborator {
  border: 1px solid #c0d3eb;
}

**Comment by dwelle** [comment]
@silverwind chrome store is still on `20.2.14.922`, so that's what you're possibly seeing.

**Comment by silverwind** [comment]
Not sure, that version is 5 days old while the feature should've been there since many months.

Source file [here](https://github.com/sindresorhus/refined-github/blob/master/source/features/highlight-collaborators-and-own-discussions.css).

**Comment by silverwind** [comment]
Yeah, after closer investigation, it's the broken version which seems to come from a very old codebase.

**Comment by fregante** [comment]
Reopening for visibility

**Comment by s-kocher** [comment]
Same problem and console errors with : 
- Windows 10 x64 1803
- Chrome  78.0.3904.87 (64 bits)
- Extension version 20.2.14.922
- GitHub Enterprise Server 2.17.6

**Comment by s-kocher** [comment]
Is there a provided package somewhere so we can sideload it in chrome without waiting the official publishing on chrome webstore ?
I didn't find this kind of package on releases page

**Comment by kidonng** [comment]
> Is there a provided package somewhere so we can sideload the last working version 20.2.19 in chrome without waiting the official publishing on chrome webstore ?
> I didn't find this kind of package on releases page

I've built one for myself using the latest code. If you would like to use it, [here it is](https://github.com/sindresorhus/refined-github/files/4230180/distribution.zip).

If you do not trust this, you can build one easily, just follow [the contributing guide](https://github.com/sindresorhus/refined-github/blob/master/contributing.md#workflow) (but replace `npm run watch` with `npm run build`).

**Comment by yakov116** [comment]
@s-kocher just go to the github action of the last commit and download the artifact

**Comment by s-kocher** [comment]
Thanks @kidonng & @yakov116 I tested both of our solution are working fine :)
I never used github action artifact result, thanks for the information !

**Comment by fregante** [comment]
I added more info in https://github.com/sindresorhus/refined-github/issues/2796#issuecomment-587428669

**Comment by Enrico2** [comment]
Has it been verified that the new version has been pushed to the Chrome web store? I'm surprised it'd take them this long to update.

**Comment by tunnckoCore** [comment]
@Enrico2 don't worry. It gets even more surprising and interesting how i'm getting pretty old version and even already not existing or renamed features while I just installed that version before 2-3 days when started to report tons of other bugs :D 

I'm waiting for new chrome store version too :)

**Comment by sindresorhus** [comment]
Status: https://twitter.com/DotProto/status/1230746697883508737

**Comment by fregante** [comment]
Update your extensions! A new version has finally been published by the Chrome extensions team :tada:

**Comment by fregante** [comment]
Don’t forget to restore `more-tab` extension, if you previously disabled it
