### ISSUE TITLE
A few of problems, just after waking up

### ISSUE THREAD

**Issue by tunnckoCore** [sindresorhus/refined-github#2797]
1. #2770 
2. The "More" dropdown is always like when clicked (in every page). I think we had similar issue before few? Hm. I don't remember how we fixed it.
3. The extension "Options" is doing something strange, constantly moving/resizing  - can't show that.. Maybe from few pictures below you can see it has different size. It stops when you, for example, somehow successfully click on some of the inputs and "save" the options with "Enter".

![2020-02-18-124209_1280x1024_scrot_001](https://user-images.githubusercontent.com/5038030/74730835-8f66e280-524f-11ea-8759-b5709459d322.png)
![2020-02-18-124209_1280x1024_scrot_000](https://user-images.githubusercontent.com/5038030/74730841-8fff7900-524f-11ea-80d3-1857999ef92e.png)

4. Reinstalled the extension
5. errors in console (when in an Issue)

```
 ❌ make-discussion-sidebar-sticky
content.js:1896 TypeError: Cannot read property 'offsetHeight' of null
    at updateStickiness (content.js:3269)
    at make_discussion_sidebar_sticky_init (content.js:3276)
    at features_run (content.js:1891)
    at content.js:1944
    at onAjaxedPagesRaw (content.js:1843)
features_run @ content.js:1896
 
❌ link-to-file-in-file-history
content.js:1896 TypeError: Cannot read property 'children' of null
    at cleanSection (content.js:5986)
    at clean (content.js:6024)
    at clean_sidebar_init (content.js:6039)
    at features_run (content.js:1891)
    at content.js:1944
    at content.js:1848
    at onAjaxedPagesRaw (content.js:1843)
```
6. more errors in Repo pages

![2020-02-18-125917_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/74730339-993c1600-524e-11ea-91dc-64143f66e0b8.png)

7. What permissions the token need? Mine has `gist, notifications, repo, user, workflow` and it's new.
8. The "hide marketplace" wraps the anchor `a` tag with a `div` that makes too much space between the "Issues" and "Trending"? You can see it from above screenshot.

```html
<div class="mr-0 mr-lg-3 py-2 py-lg-0 border-top border-lg-top-0 border-white-fade-15">
      <a class="js-selected-navigation-item Header-link" data-ga-click="Header, click, Nav menu - item:marketplace context:user" data-octo-click="marketplace_click" data-octo-dimensions="location:nav_bar" data-selected-links=" /marketplace" href="/marketplace">
        Marketplace
</a>      

    </div>
```

**Comment by fregante** [comment]
I don't know how but you're using an extremely old version of Refined GitHub. `make-discussion-sidebar-sticky` hasn't existed since August 2019 because it was renamed https://github.com/sindresorhus/refined-github/commits/master/source/features/sticky-discussion-sidebar.tsx

**Comment by tunnckoCore** [comment]
I don't know either. As I said, I just reinstalled it from the chrome store, and it's `20.2.14.922`

![2020-02-18-133434_1280x1024_scrot](https://user-images.githubusercontent.com/5038030/74732648-60527000-5253-11ea-9fa3-8d66f51e2c66.png)


In anyway, there is ton of other stuff in this issue other than the sticky thing.

And I'm continuing:

9. Disabling more-dropdown, removes the releases tab too (while releases-tab is enabled)
10. disabling depreoritize marketplace seems to not work, it still hides it.
11. "repo age" doesn't appear too.

**Comment by fregante** [comment]
This is due to https://github.com/sindresorhus/refined-github/issues/2796

Sorry about that

**Comment by tunnckoCore** [comment]
Ah yea, thanks. I'll just leave it and try later or tomorrow :)
