### ISSUE TITLE
Display PR reviewer options bar after selecting self as a reviewer

### ISSUE THREAD

**Issue by sdgluck** [sindresorhus/refined-github#2798]
Something that I find a little annoying with the reviewing system for PRs, when you want to review something but are not already selected as a reviewer: you need to select yourself, and then refresh the page to see the bar above the PR title which allows you to submit your review (e.g. approve/request changes).

It would be nice if Refined GitHub showed the bar immediately after selecting yourself as a reviewer. 

Thanks!

Example URL:

On any pull request that is reviewable.

**Comment by fregante** [comment]
> you need to select yourself, and then refresh the page to see the bar above the PR title which allows you to submit your review

That's not how it works; you just need to visit the `Files Changed` tab and the Review button is on the header of every PR

<img width="806" alt="Review Changes button" src="https://user-images.githubusercontent.com/1402241/74734385-682d0700-5289-11ea-801e-844fc95bc577.png">

**Comment by sdgluck** [comment]
> That's not how it works

Just to clarify, see below for what I meant by "the bar above the PR title".

![image](https://user-images.githubusercontent.com/3265173/74743027-985bb200-5257-11ea-99b9-c95ba07811d4.png)

**Comment by fregante** [comment]
Right, but if your intent is to leave a review right away, just click the `Files changed` tab, you don't **need** to assign yourself as you mentioned.

"Check out locally" is the only unique thing I see, that was discussed here: https://github.com/sindresorhus/refined-github/issues/2767

**Comment by sdgluck** [comment]
> Right, but if your intent is to leave a review right away, just click the Files changed tab, you don't need to assign yourself as you mentioned.

I didn't notice that - good to know. Thanks
