### ISSUE TITLE
Meta: settings are now less friendly in Chrome version of extension

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2800]
I don't know why but it seems like #1780 got somehow reverted in latest version that is available currently on Chrome Webstore (20.2.14.922):
![image](https://user-images.githubusercontent.com/6032823/74774027-4cc6f980-5293-11ea-97c8-cc494663ffa1.png)

Affected URL: `chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf`

**Comment by jack1142** [comment]
Leaving this open until that version reaches Chrome Webstore (feel free to close it if you know that it's fixed) but it's most likely connected to #2796

**Comment by fregante** [comment]
Indeed it's due to #2796, that version is broken, all of it.
