### ISSUE TITLE
"More" menu is always opened in chrome

### ISSUE THREAD

**Issue by TheBestPessimist** [sindresorhus/refined-github#2806]
I cannot close it by clicking more, or the dropdown next to it. It's always opened.
![image](https://user-images.githubusercontent.com/4482210/74807203-8843e100-52f0-11ea-95eb-471589b79529.png)

If it helps, i have the following features disabled, however the menu stays open even if i remove those:
![image](https://user-images.githubusercontent.com/4482210/74807301-c50fd800-52f0-11ea-8b43-50de52adbad7.png)

Plugin version: 20.2.14.922

**Comment by fregante** [comment]
This is due to #2796
Either temporarily disable the extension or enter `more-tab` in the options to disable. Touching the options page however will make the extension lose any previously-saved options

**Comment by mrfijas** [comment]
I had to add `more-dropdown` option, as the filename is: https://github.com/sindresorhus/refined-github/blob/20.2.19/source/features/more-dropdown.tsx
