### ISSUE TITLE
Keep the labels when changing the base branch of a new PR

### ISSUE THREAD

**Issue by dorian-marchal** [sindresorhus/refined-github#2807]
When you add some labels on a pull request and you change the base branch before opening it, the labels are removed. It would be nice to keep them.

![ezgif-6-982587f425ae](https://user-images.githubusercontent.com/6225979/74816665-dca08e00-52fb-11ea-8f02-f9827c013ddb.gif)

Example URL: https://github.com/sindresorhus/refined-github/compare/master...ava?expand=1

**Comment by fregante** [comment]
Oh god. This is a bug that GitHub should solve. I don't think it's worth it for us to fix it since technically you _can_ avoid it (i.e. change the base _before_ making any changes)
