### ISSUE TITLE
Automatically expand failed steps in GitHub Actions

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2811]
For some reason GitHub Actions will show which step has failed but won't open it.

I think that it should automatically open if there's only one failed step.

<img width="263" alt="" src="https://user-images.githubusercontent.com/1402241/74860990-8f1c3380-5384-11ea-803d-480c2f0159a3.png">

Example URL: https://github.com/sindresorhus/refined-github/runs/455877426

Likewise, if there's only a failed job, it should be selected, unless one is already selected.

Example URL: https://github.com/sindresorhus/refined-github/actions/runs/41929537

**Comment by yakov116** [comment]
https://github.blog/changelog/2020-09-23-github-actions-log-improvements/
