### ISSUE TITLE
`bugs-tab` doesn't work with uppercase `Bugs` tag

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2816]
I am wondering why I don't get a "Bugs" tab on https://github.com/redaxo/redaxo but i can see it on other reposes with the same browser?

using FF 75.0a1 (2020-02-19) (64-bit) and refined github 20.2.19

**Comment by fregante** [comment]
Because `label:bug` doesn’t match `Bug`

**Comment by staabm** [comment]
ok, so we should change the label form "Bug" to "bug"?

or should refined github be case-insensitive in this case?

**Comment by fregante** [comment]
It’s not Refined GitHub but GitHub themselves. Their tags are case sensitive

**Comment by yakov116** [comment]
@fregante https://github.com/redaxo/redaxo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug
will bring up the bugs tab (the search is not case sensitive)

**Comment by fregante** [comment]
GitHub search may not be, but the labels API is. Maybe we need to change it to use the search API instead

**Comment by jdreesen** [comment]
I think it makes sense to be case-insensitive here.

**Comment by luwes** [comment]
On enterprise there also seems to be an issue. Only shows when manually searching `label:bug`. Bug count in the tab says `0`.

<img width="343" alt="Screen Shot 2020-03-18 at 2 14 37 PM" src="https://user-images.githubusercontent.com/360826/76993306-0365da80-6923-11ea-8de7-2b517c76111c.png">

**Comment by fregante** [comment]
Link?

**Comment by fregante** [comment]
Are you using Firefox? Any errors in the console?

**Comment by luwes** [comment]
it's behind a VPN, scusi.

**Comment by fregante** [comment]
No need to check Firefox, Chrome is always preferred for debugging.

**Comment by fregante** [comment]
Did you set a token specifically for your GH Enterprise?

**Comment by luwes** [comment]
Yes, I set a new one for the GH enterprise domain.

**Comment by luwes** [comment]
ow snap, I cleared cache and it works now! thanks for the quick answers!

**Comment by luwes** [comment]
Beautiful feature!

<img width="391" alt="Screen Shot 2020-03-18 at 2 41 02 PM" src="https://user-images.githubusercontent.com/360826/76995644-8b011880-6926-11ea-867b-2e1e8f96652c.png">

**Comment by staabm** [comment]
the initially reported does still not show the "Bugs" tab for me even when using the refined-github latest release:

https://github.com/redaxo/redaxo

![grafik](https://user-images.githubusercontent.com/120441/77327824-00505d00-6d1c-11ea-863c-bf9a9867da30.png)

**Comment by staabm** [comment]
I dont have the permission to re-open this issue, but since the bug still exists I guess we should @fregante ..?

**Comment by fregante** [comment]
It works both in Firefox

<img width="762" alt="Screen Shot 2020-04-08 at 13 07 32" src="https://user-images.githubusercontent.com/1402241/78777499-ef4d5000-7999-11ea-82d0-170f13b4f888.png">

And Chrome

<img width="559" alt="chrome" src="https://user-images.githubusercontent.com/1402241/78777537-02f8b680-799a-11ea-9766-6cc59d15ae68.png">

Did you set your token in the options?

**Comment by staabm** [comment]
I am on 20.4.5 and testing in firefox 77.0a1.

the feature works for me in other repositories.

I get a error in the browser-console, not sure this is related
![grafik](https://user-images.githubusercontent.com/120441/78781135-0858ff80-79a0-11ea-8782-21c3cbbcb0e2.png)

**Comment by staabm** [comment]
I also can reproduce the problem in Chrome 84 with refined github 20.4.1

![grafik](https://user-images.githubusercontent.com/120441/78781542-bebce480-79a0-11ea-913c-31a255757f30.png)

**Comment by yakov116** [comment]
@staabm can you try to clear the cashe?

**Comment by staabm** [comment]
> can you try to clear the cashe?

which cache? how to clear it?

**Comment by yakov116** [comment]
open the extension options all the way on the bottom

**Comment by fregante** [comment]
1. Open https://github.com/redaxo/redaxo **in Chrome**
2. Clear the cache
3. Open the dev tools
3. Refresh the page
3. Search "graphql"
4. Find the query that looks like this
<img width="462" alt="" src="https://user-images.githubusercontent.com/1402241/78783181-7bb04080-79a3-11ea-957a-4d269bb266b5.png">

One of the queries should be (in the Headers tab):

```gql
{
	search(type: ISSUE, query: "label:bug is:open is:issue repo:redaxo/redaxo") {
		issueCount
	}
}
```

**Comment by staabm** [comment]
thx for the hint. clearing the cache did it.

I guess there is some cache eviction problem going on?
