### ISSUE TITLE
Anyone who has trouble with using options recently?

### ISSUE THREAD

**Issue by djkeh** [sindresorhus/refined-github#2820]
![Feb-21-2020 13-46-42](https://user-images.githubusercontent.com/4949544/75005100-a22c2200-54b0-11ea-8d75-b9a28f2b759b.gif)

A few days ago, I got into a Github repository like usual days, and I noticed something went wrong.
I checked my extention setting, and found all my custom css options were gone.
I tried to put my css option in again, but it didn't work.
It seems like it's not memorizing options anymore. I have no idea what's wrong with it.

Please help, thx.

**Comment by dikiaap** [comment]
Yes. This is happened to me. I don't have a backup either and all my settings were gone too.

**Comment by jdreesen** [comment]
Do you use Chrome? Your RGH version is 20.2.14.922? Look here: #2796
