### ISSUE TITLE
More dropdown is always open

### ISSUE THREAD

**Issue by juristr** [sindresorhus/refined-github#2822]
I just installed RefinedGithub for the first time. The "More" panel however seems to always remain open 🤔. Don't think this is intentional.

Happens on all repos

![image](https://user-images.githubusercontent.com/542458/75028267-4194e900-54a0-11ea-8ff4-089fdb97f434.png)

This is the error I see in the console

![image](https://user-images.githubusercontent.com/542458/75028292-4c4f7e00-54a0-11ea-8cfa-58c69b661558.png)

**Comment by fregante** [comment]
#2796
