### ISSUE TITLE
Open all your notifications at once is missing

### ISSUE THREAD

**Issue by netniV** [sindresorhus/refined-github#2826]
GitHub seem to be changing the way that their notifications are working.  Since their change, the open all in tab options seem to have disappeared so I have to now manually open all tabs.  This has been a really useful feature as we often have lots of issues and it saves me needing to click every single one whilst holding done the ctrl/option key for a new tab.

**Comment by netniV** [comment]
I am using Chrome fwiw.

**Comment by jdreesen** [comment]
Are you on RGH v20.2.14.922? This version is broken and the new one hasn't been approved in the store yet. Pleast have a look at #2796.

**Comment by netniV** [comment]
You know, I tried to find a similar issue, and I didn't but I'm normally pretty good at that.  Yes, that is my version: 20.2.14.922

Guess I'll just wait for Chrome to catch itself up.
