### ISSUE TITLE
Add `dim-merge-commits` feature

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2827]
This would solve the "noise" concern mentioned in #2768

It would have to use a combined GraphQL query to determine which commits on the current page are merge commits, and then just apply `opacity: 0.6` on their whole line. Or something like that.

"Combined GraphQL query" example: https://github.com/sindresorhus/refined-github/pull/2795/files#diff-04c19a6c246911e079b45f999eab501cR14-R22

### Test URL

https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/2768#issuecomment-590036267_

**Comment by sindresorhus** [comment]
So bringing back https://github.com/sindresorhus/refined-github/issues/1988? Sounds good!

**Comment by yakov116** [comment]
@sindresorhus we only dropped it, since github removed the class to be able to check that it was there.

**Comment by fregante** [comment]
@sindresorhus exactly! Except now it requires an API request for every `isCommitList` page load

**Comment by yakov116** [comment]
@fregante wouldn't it be the same as add-tags-to-comits

I started looking into the code and then I realized your going to want to save each summit to storage. 

Just curious are we not already that we can use it for both things?

**Comment by fregante** [comment]
That feature is too complex and I don’t want a copy of it. If anything we should drop/simplify the caching from it.

**Comment by yakov116** [comment]
@fregante do you have any idea how we can figure out if its a merge commit. I tried all ways I cant figure out a normal way.

**Comment by fregante** [comment]
I think only merge commits have 2 parent commits

**Comment by yakov116** [comment]
@fregante Im working on it
