### ISSUE TITLE
Extension seems to hide assignees menu from issues and PRs

### ISSUE THREAD

**Issue by akmadian** [sindresorhus/refined-github#2836]
Refined GitHub seems to be removing or otherwise hiding the assignees menu from issues and PRs. I tried disabling and re-enabling the extension to test it, and it always disapears when enabled, and reappears when disabled. 

Oddly, the assignees menu shows, and I can interact with it when there is already someone assigned, but does not show when there is no one assigned.

**No assignees (Refined GitHub enabled):**
![no-assignees](https://user-images.githubusercontent.com/28791774/75392802-a2a62d80-58a1-11ea-9f9a-297549452790.PNG)

**With Assignees (Refined GitHub disabled):**
![w-assignees](https://user-images.githubusercontent.com/28791774/75392852-bc477500-58a1-11ea-8bd0-e55d2d97632a.PNG)

The same thing happens when viewing a PR.

**Comment by akmadian** [comment]
Forgot to add version info:
Browser: Firefox Dev Edition 74.0
OS: Win 10 Pro 1809
Extension: 20.2.19

**Comment by fregante** [comment]
Empty sections are completely removed if RGH doesn’t think you can edit them. Here either this detection is broke for Assignees, or some other selector needs to be updated

**Comment by akmadian** [comment]
I'm not a full member of the Creative Commons org, I'm a collaborator, so maybe that's affecting it? Is there a toggle for this in settings? I love RGH, but I can't use it if there's no way to turn this off :/

**Comment by fregante** [comment]
This is the `clean-sidebar` feature you can disable temporarily in the options. 

The detection happens in the DOM: if there’s a “settings” icon, then you can edit it, so the section should not be removed.

**Comment by akmadian** [comment]
Yep, just found it and was about to comment with the name of the setting. It does have a gear icon on it, so I'm not sure what the deal is.

Do you consider this to be a proper bug that needs fixing? If so, I could investigate further if I can find the time.

**Comment by fregante** [comment]
> Do you consider this to be a proper bug that needs fixing?

Yep, it's a bug

**Comment by akmadian** [comment]
Sounds good, will investigate soon :)

**Comment by yakov116** [comment]
@fregante wasn't this fixed?

**Comment by fregante** [comment]
@yakov116 thanks! I forgot to close it in https://github.com/sindresorhus/refined-github/pull/2916

**Comment by Visne** [comment]
I'm still having this issue Firefox 85.0.2 (64-bit), addon version 21.2.9.
