### ISSUE TITLE
Keyboard shortcut to open a dialog, to enter an issue/PR number, to jump directly to it

### ISSUE THREAD

**Issue by garyking** [sindresorhus/refined-github#2837]
For instance, when viewing a repo, perhaps there could be a keyboard shortcut, that, when pressed, shows a dialog box, which allows us to enter an issue/PR number, to jump directly to it? 

Right now, if I have the number, then I have to go to a repo, click on Issues, search for the number, then click on the issue. All issues that mention this issue, will also appear in the results, so I have to find the issue myself, among the results.

**Comment by fregante** [comment]
Makes sense, a “go to issue” feature. 

How do you get these issue numbers though? Usually if I have an issue number I also have a link to it

**Comment by fregante** [comment]
This is something GitHub could/should implement in their search box:

- if the input looks like an issue number (starts with #) go to it directly.

We could implement it the same way, so no further UI is required

**Comment by fregante** [comment]
> How do you get these issue numbers though? Usually if I have an issue number I also have a link to it

Closing for this reason
