### ISSUE TITLE
Merge strategy per branch

### ISSUE THREAD

**Issue by philonor** [sindresorhus/refined-github#2838]
**Description**
We are using different merge strategies for different branches, e.g. squashing for feature branch PRs and merging for staging/production branches.
It would be helpful to have the right merge strategy auto-selected in a PR if it matches a certain pattern or name.

**Possible Implementation**
- Add possibility to define a list of branch names/patterns and the corresponding pre-selected merge strategy

**Example URL**:
https://github.com/sindresorhus/refined-github/pull/2832

**Comment by fregante** [comment]
Anything that requires configuration most likely does not belong to Refined GitHub. It’s just extra complexity and we already have 130+ features to attend to.
