### ISSUE TITLE
Don't exclude bugs from Issues tab (`bugs-tab`)

### ISSUE THREAD

**Issue by SuperSandro2000** [sindresorhus/refined-github#2844]
The bug tab is rather annoying and shouldn't be enabled by default as it drastically complicates the search for an issues as you effectively need to search two times or remove the search filter before you can find what you are searching for. There is no way I can know if my particularly issue is labeled with a bug label or not.

**Comment by yakov116** [comment]
I think the default tab should not exclude the bugs

**Comment by fregante** [comment]
The `Bugs` tab is good to understand how many bugs a repo has and possibly to tackle them more promptly.

But, it does make it difficult if you're looking for issues: most repos don't have issue templates like we do, so the `bug` label has to be added manually.

> I think the default tab should not exclude the bugs

That's a good compromise. PR welcome, but let's see what others say as well.

---

The ideal way to display this would be "100 issues, 50 of which are bugs", not necessarily as a whole separate tab. I can't think of any other visualization though. Mockups welcome
