### ISSUE TITLE
Update Chrome Webstore version (20.2.18) to latest version

### ISSUE THREAD

**Issue by IronicallySerious** [sindresorhus/refined-github#2846]
The Chrome Webstore release is at version 20.2.18 and the master is at 20.2.28 as of this date. 
https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf
---
No screenshots/URL since this is not an issue with the plugin, however, it is an issue with a release platform.

**Comment by fregante** [comment]
Chrome takes a long time to release updates
