### ISSUE TITLE
Notification list keyboard shortcuts

### ISSUE THREAD

**Issue by tonglil** [sindresorhus/refined-github#2850]
Keyboard shortcuts for the new notifications page, to go through notifications like you would emails in Gmail:

```
j go up a notification
k go down a notification
x select/unselect a notificaiton
[exists] d mark selected notification(s) as done
[exists] u mark selected notification(s) as unread
[exists] r mark selected notification(s) as read
s save selected notification(s)
o open selected notification(s) in a new tab
```

Example URL:
https://github.com/notifications/beta

**Comment by fregante** [comment]
Notifications beta definitely already has some shortcuts like “mark as done”, what’s missing? Since it’s still in beta I suggest contacting GitHub to add them

**Comment by tonglil** [comment]
Sorry I should have tried shift+? first.

Currently there are only these: 
<img width="449" alt="image" src="https://user-images.githubusercontent.com/3250776/75820536-5f403900-5d51-11ea-9dd5-5855c207a399.png">

Thinking up/down is the top priority.

Already submitted suggestions to GH, not sure if/when they will be implemented. Maybe keep this issue as a tracker?
