### ISSUE TITLE
'Commented' Tab missing on Firefox

### ISSUE THREAD

**Issue by wwallace18** [sindresorhus/refined-github#2855]
There used to be a tab when clicking on PR that showed the pull requests you've commented on. I see it working on Chrome (71.0.3578.98) like this: 
<img width="549" alt="Screen Shot 2020-03-03 at 2 04 33 PM" src="https://user-images.githubusercontent.com/47335909/75814846-117aff00-5d58-11ea-852c-6be0e1f516c5.png">

On Firefox 73.0.1 this is what I see. 
![Screen Shot 2020-03-03 at 2 04 50 PM](https://user-images.githubusercontent.com/47335909/75814825-0a53f100-5d58-11ea-8600-c4e4da1594c8.png)

**Comment by wwallace18** [comment]
Upon further inspection it seems like the refined-github isn't working at all for me on firefox even after uninstalling and reinstalling it.

**Comment by jdreesen** [comment]
I just created an issue because it's not working for me anymore, too.

See #2856
