### ISSUE TITLE
🔥🔥🔥 Version `20.3.3` is broken in Firefox (Fixed in `20.3.4`)

### ISSUE THREAD

**Issue by jdreesen** [sindresorhus/refined-github#2856]
Since today's update RGH doesn't work in my Firefox 73.0.1 (64-Bit) anymore :(

I can't tell what's wrong, cause there's nothing in the console.

The features aren't active in GitHub and the extension's settings are completely empty, though (my token is gone, etc.)
![grafik](https://user-images.githubusercontent.com/424602/75815440-b36c0d00-5d93-11ea-8dce-8e44b651d26c.png)

I tried disabling/enabling and uninstalling/installing it, but it doesn't help.

**Comment by igozali** [comment]
Just to add, I tried adding my token back and closing the preferences, but the extension also swallowed the token into the void :D

**Comment by fregante** [comment]
On it, a non-supported regex appears in the code now and I'm looking for it. Firefox doesn't run any code when that happens

**Comment by fregante** [comment]
Reopening for visibility. 20.3.4 is already available and it should work: https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions/

**Comment by jdreesen** [comment]
I just installed the new version and its working again, even my settings are back :)

Thx for the quick fix, @fregante ❤️
