### ISSUE TITLE
"refined-github" class absent on html node in 20.3.3

### ISSUE THREAD

**Issue by silverwind** [sindresorhus/refined-github#2857]
20.2.28 and possibly later versions added a class `refined-github` to the `<html>` node which we use at GitHub Dark to scope RGH-specific CSS rules. On 20.3.3 (Firefox), I only see a `class="  "` (double space) being added. Could you please restore the old class again?

Related: https://github.com/StylishThemes/GitHub-Dark/issues/1082

**Comment by jdreesen** [comment]
20.3.3 ist broken. See: #2856
