### ISSUE TITLE
@me returns empty page for the search-query for old Enterprise Version

### ISSUE THREAD

**Issue by stenalpjolly** [sindresorhus/refined-github#2859]
We have enabled refined-github on Enterprise Github, which doesn't support "@me" feature yet. As a result of this, We are getting a blank page whenever we uss advanced search query.

**Comment by fregante** [comment]
This was resolved by https://github.com/sindresorhus/refined-github/pull/2819 and https://github.com/sindresorhus/refined-github/pull/2809 and it's already in version 20.2.28 and later
