### ISSUE TITLE
Automatically assign user on PR creation

### ISSUE THREAD

**Issue by br0p0p** [sindresorhus/refined-github#2863]
I'd like an option to automatically be assigned to issues/PRs I create.

**Comment by sindresorhus** [comment]
Why?

**Comment by br0p0p** [comment]
At least for me, when I create a PR or issue I have some amount of interest in the issue's progress and would like to be assigned for accountability.

**Comment by busches** [comment]
Assigning means you're going to fix it, which isn't always true. What you're after sounds like being subscribed, which should already be happening automatically.

**Comment by fregante** [comment]
It takes a single click to assign yourself before or after the creation.
