### ISSUE TITLE
A way to uncheck all `viewed` files in a PR.

### ISSUE THREAD

**Issue by pvinis** [sindresorhus/refined-github#2865]
In all PRs, in the `Files changed` tab, we have `Viewed` checkboxes. It would be very helpful to have a button above all these or somewhere to click and uncheck all files' `viewed` checkbox.

It helps a lot in PRs where the files are a lot, (more than 100), and he PR still going. I often go in my PRs and check `viewed` in the files that are finished, and keep the rest open, while the PR is not finalized.

**Comment by fregante** [comment]
Unchecking `viewed` means that your previous "view" should be discarded. If your workflow is that, why check `viewed` in the first place?

I think your intention is to just see the all files at once, even if you already `viewed` them. In that case, you should use the toggle button on the very left, not `viewed`.

Also, using `alt`+`click` on that button will toggle all the files open or closed.

<img width="241" alt="" src="https://user-images.githubusercontent.com/1402241/76087528-65d7e600-5fc7-11ea-9a92-66aeaa3b5163.png">

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/2444

**Comment by pvinis** [comment]
my workflow is actually about unchecking viewed, but thank you for marking as duplicate, I failed to find it before making the issue.

**Comment by sandesh-allen** [comment]
Updated one after github new UI if someone needs

```
document.querySelectorAll('button[aria-pressed="true"][aria-label="Viewed"]').forEach(btn => btn.click());
```

**Comment by fregante** [comment]
As suggested by the duplicate issue, the feature was implemented:

- https://github.com/refined-github/refined-github/pull/3007

However it's currently broken in the new PR files view:

- https://github.com/refined-github/refined-github/issues/8504
