### ISSUE TITLE
`link-to-file-in-file-history` is failing

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2871]
https://github.com/sindresorhus/refined-github/commits/master/source/features/releases-tab.tsx

```
❌ Refined GitHub: feature `link-to-file-in-file-history`

 TypeError: "rootLink.closest(...) is null"
    link_to_file_in_file_history_init moz-extension://f449a952-bd7e-9d45-8185-d66afa8184e6/content.js:8043
```

<img width="989" alt="error" src="https://user-images.githubusercontent.com/1402241/76125666-57f98380-600e-11ea-9f4c-60705804a638.png">

**Comment by yakov116** [comment]
I think we should wait a day. Looks like they are change a whole bunch of css there. would not be surprised to see other things break
