### ISSUE TITLE
Improve <table> input in the comment field

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2875]
There are many ways to simplify creation of tables. This is the simplest UI I've [seen]((https://www.tablesgenerator.com/html_tables)) but I'm open to suggestions. It's only 2 clicks to add a table.

1. Click on "add table" button (dropdown opens)
1. Click the desired table size

![UI](https://user-images.githubusercontent.com/1402241/76141464-9c6c3a00-6075-11ea-9935-f708b6946055.gif)

The grid is too big for us, but a 5x5 would be plenty. No need to get fancy with alignment options and headers; those can be more easily added by the user if desired.

Example table usage: https://github.com/sindresorhus/refined-github/issues/2874

Output would be a simplified HTML5 table markup:

```html
<table>
	<tr>
		<td> A1
		<td> B1
	<tr>
		<td> A2
		<td> B2
</table>
```
<table>
	<tr>
		<td> A1
		<td> B1
	<tr>
		<td> A2
		<td> B2
</table>

**Comment by jerone** [comment]
GFM can be used instead of HTML5: https://github.github.com/gfm/#tables-extension- & https://help.github.com/en/github/writing-on-github/organizing-information-with-tables

**Comment by fregante** [comment]
Indeed. The problem with those tables is that they’re unreadable unless there’s a only a couple of words in each cell. The moment a table row “wraps” good luck finding the separator for the next cell (especially here since there’s no syntax highlighting)
<table><tr><td> *test*

**Comment by fregante** [comment]
I think, yeah, while Markdown tables are unreadable they’re easier to use

**Comment by esakki-selvaraj** [comment]
Can I work on this? and also don't you think entering numbers of columns and rows will be more efficient than dragging and it is also not restricted to any size??

**Comment by fregante** [comment]
> entering numbers of columns and rows will be more efficient

No, because that requires at least 4 clicks and 2 key presses, while this is only 2 clicks (no dragging, just a click)

> not restricted to any size??

Nobody needs 100 columns in a GitHub comment; rows can be trivially added by copy-pasting the result as many times as needed, if you need more than 7 rows.

> Can I work on this?

You can, but please keep it as simple as possible, probably around 50 lines due to the dropdown’s JSX. You can copy the DOM from the canned replies (but the dropdown content would of course be like in the very first gif): 
<img width="313" alt="" src="https://user-images.githubusercontent.com/1402241/94226445-40f08500-febd-11ea-9625-493308e0a7b2.png">

**Comment by esakki-selvaraj** [comment]
Sure I will keep it simple..

**Comment by cheap-glitch** [comment]
This looks fun, imma try it too.

**Comment by cheap-glitch** [comment]
|     |     |     |     |
|-----|-----|-----|-----|
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |
|     |     |     |     |
