### ISSUE TITLE
Latest release/tag button refers to older, incorrect tag

### ISSUE THREAD

**Issue by marzer** [sindresorhus/refined-github#2879]
Per title. Screenshot:
![image](https://user-images.githubusercontent.com/3958019/76293602-06752100-62ba-11ea-91e9-a5c4ebcbfc78.png)

Repository: https://github.com/marzer/tomlplusplus

It was updating the button correctly with each release up until `v0.3.0`, at which point it seems to have decided that's the favorite and no further releases are important O_o

Perhaps also of note is the "new commits" indicator; it's stuck at `+3` even though it should actually say something closer to `+11`, with respect to the tag it's stuck on.

**Comment by jdreesen** [comment]
It must have something to do with caching. For me it shows `v0.4.3`:
![grafik](https://user-images.githubusercontent.com/424602/76296597-ae88eb00-62b6-11ea-8cfa-47a40e9f804b.png)

**Comment by marzer** [comment]
@jdreesen I just cleared my browser's cache, as well as disabling browser extensions, and it still shows `v0.3.0 +3`

**Comment by marzer** [comment]
Oh! After using the Clear Cache button in Refined Github's extension options it's now showing the correct version. I guess that's the culprit. Something like this shouldn't be so sticky in the cache, though, so I still consider that a bug.

**Comment by jdreesen** [comment]
Maybe related to, or even fixed by, #2868? (not sure this made it into the latest release)

**Comment by marzer** [comment]
Yeah seems related. I have the latest release installed so I guess it was too late.

**Comment by fregante** [comment]
> Maybe related to, or even fixed by, #2868? (not sure this made it into the latest release)

100% correct. Not yet released. So consider this fixed
