### ISSUE TITLE
Link to the readme of the latest version in the main readme

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#288]
Often the readme you land on when you go to a repo is in `master` and might contain unreleased features. Would be useful to have a quick link to the readme of the latest version.

**Comment by hkdobrev** [comment]
👍 

Thinking out loud:
We'd either need to use the API for that or cache the latest release when the user visits the Releases page which is not that useful here. We can of course make an AJAX request to releases, but for every readme you visit that would be an overkill. But I guess we can assume semver and try to read the branch/tag selector in the top left corner of the repo page and get the latest version from there.

**Comment by sindresorhus** [comment]
Yes, I was thinking just reading the git tags.
