### ISSUE TITLE
Notification count

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#2883]
Automatically put the unread notification count inside the blue circle:
![image](https://user-images.githubusercontent.com/29491356/76537229-5c2c1200-64e2-11ea-9316-541449194065.png)

Example URL:
github.com

**Comment by jdreesen** [comment]
You can use the extension [Notifications Preview for GitHub](https://github.com/tanmayrajani/notifications-preview-github) for this. (I don't think it works when you have the new notification page enabled, though.)

**Comment by fregante** [comment]
Correct. That’s the right extension, also maintained by me. Notifications Beta isn’t supported yet

**Comment by jenniferbillings** [comment]
Fuck you

**Comment by jenniferbillings** [comment]
Fuck you bye

**Comment by Richienb** [comment]
@fregante Please moderate.

**Comment by busches** [comment]
> @fregante Please moderate.

Patience.
