### ISSUE TITLE
CI link next to the repo's title always displays failure.

### ISSUE THREAD

**Issue by kublaios** [sindresorhus/refined-github#2884]
<img width="400" alt="failed" src="https://user-images.githubusercontent.com/1839554/76539425-0c692e80-6481-11ea-82c9-d6e216c41e23.png">

No matter which branch I am on or what the status of the latest CI job, I always see failure icon which opens a menu where the failure is from a job that is from 3 months ago.

This has been an issue since we had the CI and I had the plugin. The result is the same no matter the plugin has a personal token or not.

**Comment by fregante** [comment]
That mark is taken from the main brain’s Commits view: /user/repo/commits

How does it look there? The first icon found in the list is shown next to the title. 

This icon used to depend on the current branch but recently we just made it stick to the default one.

**Comment by kublaios** [comment]
> That mark is taken from the main brain’s Commits view: /user/repo/commits
> 
> How does it look there? The first icon found in the list is shown next to the title.

Well in my case it's a repo of an Organization so I assume the path should be `/organization-name/repo-name/commits`? The icon is still the same.

> This icon used to depend on the current branch but recently we just made it stick to the default one.

👍

**Comment by fregante** [comment]
> The icon is still the same.

Do you mean it’s red on that page?

**Comment by kublaios** [comment]
> > The icon is still the same.
> 
> Do you mean it’s red on that page?

Yes, it's the red 'x' icon.

**Comment by fregante** [comment]
Then the repo is failing the icon we show is correct

**Comment by kublaios** [comment]
> Then the repo is failing and the icon we show is correct.
> 
> GitHub has been showing each branch’s status icon for a few months now, so our icon just uses the default branch. If that’s failing, the repo is failing.

Do you mean that the icon will turn green after a couple of months? A failure from 3 months ago shouldn't mean that the repo is failing the tests.

**Comment by samuelmeuli** [comment]
I also think the current behavior is somewhat unintuitive. Take this repo as an example: https://github.com/samuelmeuli/font-picker. I removed CI one year ago but because the last check was a failure, this is still displayed on the repo page. IMO the check status of the most recent commit should be used and earlier ones should be ignored.

**Comment by fregante** [comment]
> I removed CI one year ago

That's a separate issue and a valid one. Fixed in #2990

**Comment by samuelmeuli** [comment]
Awesome, thanks @fregante! :)

**Comment by kublaios** [comment]
Still stuck on a failure that's from 3 months ago... I did a reinstall but it didn't help, also cleared the caches through the extension settings on Firefox. I also re-ran the CI on the failed branch and succeeded, but still displaying the old failure. Is there another way to reset everything?
