### ISSUE TITLE
`forked-to` is broken

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#2885]
This is similar to #2759, but with more problems:

- Sometimes the link to my own fork is there, but sometimes it's not.
![CopyQ TPzjkH](https://user-images.githubusercontent.com/44045911/76548915-75c15f80-64ca-11ea-852f-b5793f673718.png)
![image](https://user-images.githubusercontent.com/44045911/76549089-b8833780-64ca-11ea-99ed-2651744a85b2.png)
- Sometimes the relationship is reversed.
![image](https://user-images.githubusercontent.com/44045911/76549213-fbdda600-64ca-11ea-81b5-a8700868b61f.png)
- Sometimes both source repo and fork repo are displayed.
![image](https://user-images.githubusercontent.com/44045911/76549456-70b0e000-64cb-11ea-8e13-0a6007878ba0.png)

**Comment by fregante** [comment]
There’s an existing issue for `forked-to` and I think it’s the same issue

**Comment by fregante** [comment]
I’ll reopen just in case it’s not

**Comment by jenniferbillings** [comment]
Fuck you

**Comment by kidonng** [comment]
> and I think it’s the same issue

Sorry, I missed https://github.com/sindresorhus/refined-github/issues/2759#issuecomment-582094588, this is very likely a duplicate issue. But keep it open is fine.

Just in case it would be helpful, I'm a member of @ncuhome which the repository belongs to (though not a collaborator of the repository), in the second and third images.
