### ISSUE TITLE
`link-to-file-in-file-history` only works for latest commit

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2886]
Link: https://github.com/sindresorhus/refined-github/commits/master/source/options.css
Screenshot:
![image](https://user-images.githubusercontent.com/6032823/76564570-13a43280-64a9-11ea-862a-dc7b6e7daa24.png)

Might be regression from #2731

**Comment by yakov116** [comment]
Duplicate of #2871

**Comment by jack1142** [comment]
Ah, my bad.
