### ISSUE TITLE
Incorrect amount of bugs shown (due to cache)

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#2889]
![image](https://user-images.githubusercontent.com/36894700/76682971-ac999180-6600-11ea-866d-25a62b2c0309.png)

https://github.com/szmarczak/cacheable-lookup

**Comment by fregante** [comment]
Cache. It expires within an hour and is refreshed in the next pageload

**Comment by szmarczak** [comment]
Well then it should update when somebody clicks on the tab, right?

**Comment by fregante** [comment]
There’s currently no mechanism to force a refresh manually. I’m thinking of changing the cache API so that you could set the cache manually in these cases. For example:

```js
const countBugs = cache.function(…, {options});

…

if (isBugsPage) {
  countBugs.set(getCountFromDom()); // this sets the cache using the options already defined for cache.function
}

const bugs = await countBugs()
``` 

cc @sindresorhus a new API isn’t strictly necessary, but it helps reuse the logic/options without having to manually create additional constants. 

API suggestions welcome

**Comment by szmarczak** [comment]
> Cache. It expires within an hour and is refreshed in the next pageload

It never expires for me. It has been days and I still see `1`. Reload doesn't do anything.

**Comment by fregante** [comment]
Chrome or Firefox?

Try this in the background script inspector

```
await browser.storage.get('bugs-tab: szmarczak/cacheable-lookup')

**Comment by fregante** [comment]
The cache should be there for 4 days, but if you reload the page twice after half an hour it should be expired/updated

**Comment by szmarczak** [comment]
> Chrome or Firefox?

Chrome.

![image](https://user-images.githubusercontent.com/36894700/76700644-cf3bb100-66b9-11ea-908d-24b5de976f7f.png)

> So if you load the page now it should definitely show 0, otherwise it’s not working as expected

It still shows `1`.

**Comment by fregante** [comment]
My bad,

```
await browser.storage.local.get('bugs-tab:szmarczak/cacheable-lookup')
```

**Comment by szmarczak** [comment]
![image](https://user-images.githubusercontent.com/36894700/76868913-da344400-6867-11ea-9920-e25822bde51d.png)

**Comment by fregante** [comment]
I suggesting emptying the cache, it's at the bottom of the options page

**Comment by szmarczak** [comment]
Yep, that worked!

**Comment by szmarczak** [comment]
Why has this been closed? Is it solved already?
