### ISSUE TITLE
Add a better emoji picker

### ISSUE THREAD

**Issue by rigwild** [sindresorhus/refined-github#2890]
Hi,

The current way of using emojis on GitHub is not that great. You start typing `:` and don't get a lot of choices.

See:
![image](https://user-images.githubusercontent.com/26366184/76684285-ef606700-660a-11ea-8016-550324f8e631.png)

My current workaround is to go to this gist, listing all emojis: https://gist.github.com/rxaviers/7360908
which is not ideal.

It would be nice to have a real emoji picker. A cool feature would be a search box, last used emojis, categories...

Have a nice day :bowtie: :relieved: :blush:

**Comment by fregante** [comment]
https://blog.emojipedia.org/how-to-use-the-new-windows-emoji-picker/
