### ISSUE TITLE
Support additional image diff mode

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2894]
Github natively support several options to compare changes of images, see https://help.github.com/en/github/managing-files-in-a-repository/rendering-and-diffing-images

There is no compare mode which allows spotting differences of images quickly (even if only small areas change).

Would it be possible to support e.g. diffing using https://github.com/mapbox/pixelmatch as a additional compare mode.
the added compare mode would be especially useful for visual regression testing purposes.

**Comment by staabm** [comment]
(Also send as feature request to github itself)

**Comment by sindresorhus** [comment]
Would definitely be useful, but not sure it would be worth the amount of work required.

**Comment by fregante** [comment]
I'd suggest it to https://github.com/Mottie/GitHub-userscripts or to be published as its own diff-enhancing extension.
