### ISSUE TITLE
Add a button to clone branches

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#2895]
To clone a branch manually:

1. Go to the branch you want to clone.
2. Click `Edit` on any file. Do not make any changes.
3. Make sure you have selected this:

![image](https://user-images.githubusercontent.com/36894700/76700475-37899300-66b8-11ea-98b5-6df00963cede.png)

4. Open Chrome Dev Tools.
5. Inspect the `Propose file change` button.
6. Remove the `disabled` attribute.
7. Click `Propose file change`.

:tada: In other words, it makes a spin off from your branch and makes an empty commit (I don't know of any solution that wouldn't create an empty commit).

**Comment by yakov116** [comment]
Only way it through v3 api
https://gist.github.com/potherca/3964930

**Comment by fregante** [comment]
You can already clone it:
1. Visit branch
2. Open branch selector
3. Type new branch name
4. Click create

**Comment by yakov116** [comment]
@fregante wow I never knew that!!

**Comment by fregante** [comment]
If this “Duplicate” button is added to the branch list, it can replace this feature request: https://github.com/sindresorhus/refined-github/issues/2500, also because renaming isn’t a safe operation

**Comment by yakov116** [comment]
@fregante curious why is renaming not a safe option?

**Comment by fregante** [comment]
Explained in that thread

**Comment by yakov116** [comment]
```graphql
query GetBranchInfo {
  repository(owner: "yakov116", name: "TestR") {
    id
    ref(qualifiedName: "Test") {
      target {
        oid
      }
    }
  }
}

mutation CreateBrach {
  createRef(input: {repositoryId: "MDEwOlJlcG9zaXRvcnkyNDQyMTU0NzY=", oid: "a1a98b7b5460f87a31cc6e12699a6e71e2390988", name: "refs/head/yes"}) {
    clientMutationId
    ref {
      id
    }
  }
}
```
@fregante like this? Or do you want to hack the drop down menu?

**Comment by fregante** [comment]
If v3 only requires a `fetch` we can use that instead of v4, we don't get about its `body` anyway

**Comment by fregante** [comment]
1. Add icon-only button next to each `delete` button
2. On click, ask name via `prompt` ("cancel" or empty name will cancel the action)
3. Change the icon to "Creating..."
4. Update UI (I think just `location.reload()`)

**Comment by yakov116** [comment]
> If v3 only requires a `fetch` we can use that instead of v4, we don't get about its `body` anyway

They both require 2 calls. One to get the commit the brach is up to. And one to create the branch

**Comment by fregante** [comment]
Ugh. The GraphQL schema for this is awful. Private IDs should not be exposed at all.

2 calls are fine since it's a specific user action.

Not exactly a high-priority feature though

**Comment by yakov116** [comment]
await api.v3(`repos/${user}/${repo}/git/refs/heads`);
Gives all the branches
Only make the call after the user clicks?
To create is
POST /repos/:owner/:repo/git/refs

**Comment by fregante** [comment]
The last OR sounds good. V4 GET, V3 POST

**Comment by yakov116** [comment]
V3 I can get the direct info

**Comment by fregante** [comment]
What’s direct info? V4 also has the commit info, it’s just what we need. V4 requests are light, v3 GET requests aren’t

**Comment by yakov116** [comment]
await api.v3(`repos/${user}/${repo}/git/refs/heads/${branchName!}`);

**Comment by yakov116** [comment]
I have every thing done I am having a hard time making a post

**Comment by fregante** [comment]
> Only make the call after the user clicks?

Why do you keep asking this? I said it before. Is this going to be like your last PR of me saying the same thing 4 different ways before the code was updated?

**Comment by yakov116** [comment]
No no. I know I know. Your right.

**Comment by fregante** [comment]
@szmarczak why do you need to clone a branch?

**Comment by yakov116** [comment]
Owh... I thought you closed the issue

![image](https://user-images.githubusercontent.com/16872793/77024434-e3efa180-6964-11ea-819a-43117ab92115.png)

**Comment by szmarczak** [comment]
Sometimes I need to rebase a PR I'm working on (e.g. start from scratch with a different implementation) and I don't want to lose the current progress.

**Comment by fregante** [comment]
Commits aren't lost, you just need to save the commit hash

**Comment by szmarczak** [comment]
IKR, but I'm lazy to do so :(

**Comment by szmarczak** [comment]
I think that the `clone-branch` feature would be a safer option :)
