### ISSUE TITLE
Ability to customize what label(s) are considered bugs

### ISSUE THREAD

**Issue by isiahmeadows** [sindresorhus/refined-github#2897]
Some projects use a convention other than "bug"/["Bug"](https://github.com/sindresorhus/refined-github/issues/2816)/etc.

- [Mithril uses "Type: Bug"](https://github.com/MithrilJS/mithril.js/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3A%22Type%3A+Bug%22)
- TypeScript used "Type: Bug" and variants of it in the past.

This is explicitly not a dupe of #2816 (which is arguably itself a bug), but a feature request. Not sure what the hooks involved would be, though.

**Comment by fregante** [comment]
I know this is a limitation, but simply the repos that aren’t standard aren’t covered by Refined GitHub. Such configuration would have to be configured per-repo *or* would have to extend the query for *every* repo. Neither one is ideal. 

An ad-hoc extension would be more appropriate for this purpose.

**Comment by isiahmeadows** [comment]
Okay. (FWIW, I'm tempted to disable the bugs bit anyways - it's not useful for my workflow.)

**Comment by SirWindfield** [comment]
> An ad-hoc extension would be more appropriate for this purpose.

Could you elaborate on how an ad-hoc extension would be able to do this? Do you mean another browser extension on top of refined github (if that is even possible) or a custom fork?

**Comment by fregante** [comment]
I mean a whole new extension unrelated to Refined GitHub. *How* it actually does it is irrelevant in this repo since it’s why it’s not being implemented here (i.e. not straightforward and likely needs options or API calls)
