### ISSUE TITLE
`recently-pushed-branches-enhancements` doesn't seem to work anymore

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2906]
Despite having `recently-pushed-branches-enhancements` enabled, "Your recently pushed branches:" only shows as a widget above below tabs

URL won't really be useful here since it's about recently pushed branch, but here's the screenshot:
![image](https://user-images.githubusercontent.com/6032823/77193175-1a046100-6ade-11ea-9b92-c31f46dfb04f.png)

Let me know if you need anything else.

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/77193480-b0bc2800-6ab4-11ea-94f6-c7238123a7ed.png)


![image](https://user-images.githubusercontent.com/16872793/77193522-c29dcb00-6ab4-11ea-9f41-1634ac4d070a.png)

**Comment by jack1142** [comment]
Okay, so I just checked on `sindresorhus/refined-github` and I'm not able to reproduce it on that repo.

So to add more info, it happens for me on this repo:
https://github.com/Cog-Creators/Red-DiscordBot

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/2e4a24d3957c205c7bc49525c69e1fa08593d2ca/source/features/recently-pushed-branches-enhancements.tsx#L28

The same slash issue

**Comment by jack1142** [comment]
Another update: I have 28 branches on my fork, I was also able to reproduce it on other test repo with 23 branches.

**Comment by jack1142** [comment]
> The same slash issue

The linked code isn't the problem here as far as I can tell - `location.pathname` doesn't contain branch name in it.

**Comment by yakov116** [comment]
Ok the issue is that `getRepoURL()` returns "yakov116/red-discordbot" instead of "/yakov116/Red-DiscordBot" notice the lower case

**Comment by yakov116** [comment]
@fregante you changed this 4 days ago https://github.com/sindresorhus/refined-github/blame/master/source/libs/utils.ts#L77

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/blob/3c27b3ca262d10265740ca69297ad7b6a2123dd7/source/features/recently-pushed-branches-enhancements.tsx#L9

CSS selectors are case-sensitive
