### ISSUE TITLE
Extension options are reset when changing site access

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2908]
When I change this to "When you click the extension", all my extension options get reset:
![image](https://user-images.githubusercontent.com/6032823/77210983-aaed3380-6b02-11ea-9375-638f5d39d188.png)

**Comment by fregante** [comment]
That's nuts. It doesn't seem to happen for https://github.com/fregante/github-issue-link-status (but it uses a slightly older `webext-options-sync` version)

**Comment by jack1142** [comment]
And you've just recommended me another great extension 😄 
Yeah, it's really weird but on the plus side for me, I finally found some possible explanation why my token in the extension was disappearing sometimes, I never had anything specific to report so I might have ignored it...

**Comment by fregante** [comment]
> I finally found some possible explanation why my token in the extension was disappearing sometimes

I definitely like this bug report than a "my data is inexplicably lost" issue, I dread that in my https://github.com/fregante/webext-options-sync/

**Comment by fregante** [comment]
This bug might be related to `permissions.onRemoved` and the features around GH Enterprise support. Help debugging this would be appreciated.

**Comment by fregante** [comment]
Well, yeah. This removes the permission to github.com and when you do that, Refined GitHub cleans the options for that domain.

https://github.com/sindresorhus/refined-github/blob/7c5745bb4a7db9c07aceff98f54c58bfb3771838/source/options-storage.ts#L74-L80

PR welcome to filter out `github.com` from the `origins`
