### ISSUE TITLE
"Mark all as read" button should clear extension's unread notifications

### ISSUE THREAD

**Issue by vadimdemedes** [sindresorhus/refined-github#291]
"Mark all as read" button does not clear notifications, that were "remembered" by the extension's "Mark as unread" feature.

<img width="140" alt="screen shot 2016-09-04 at 7 22 57 pm" src="https://cloud.githubusercontent.com/assets/697676/18232283/191a200e-72d5-11e6-913b-f7aac2d31ca8.png">

See https://github.com/sindresorhus/refined-github/pull/284 for "mark as unread" feature.

**Comment by AshikNesin** [comment]
I'm working on it :)

**Comment by AshikNesin** [comment]
@jgierer12 Just checked. The bug still exists.

![screen recording 2017-05-14 at 08 57 pm](https://cloud.githubusercontent.com/assets/4201088/26035344/4bd1506a-38e8-11e7-874c-d9e8e5422c2a.gif)

**Comment by jgierer12** [comment]
My bad, I thought @vadimdemedes was talking about the checkmark button in the per-repo header

**Comment by AshikNesin** [comment]
@jgierer12 No problem 😄

Have fixed it 🔥
