### ISSUE TITLE
Option to choose indent mode in comments editor

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2910]
Now that suggestions are a thing in reviews, it would be great if I could use tabs when making review comments the same way I can use them in GitHub's editor - GitHub's editor inserts 2, 4 or 8 spaces instead of a tab when "Spaces" indent mode is chosen:
![image](https://user-images.githubusercontent.com/6032823/77214804-058d8c00-6b11-11ea-85d1-364fe5cde02b.png)

Example URL:
https://github.com/sindresorhus/refined-github/pull/2896/files
![image](https://user-images.githubusercontent.com/6032823/77214928-b3009f80-6b11-11ea-81ba-baca0f4c6183.png)

**Comment by fregante** [comment]
> No because while editors might provide some help treating each indentation as a single piece, textareas don't offer that, so using 4 spaces requires you to press left 4 times instead of once, for example.

https://github.com/fregante/indent-textarea/issues/8#issuecomment-520009734
