### ISSUE TITLE
Notifications Beta: `open-all-notifications` doesn't work

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2911]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/2911)

Not entirely sure if you are currently interested in fixing issues related to new notifications (still in beta I think?) but the [`open-all-notifications`](https://github.com/sindresorhus/refined-github/blob/master/source/features/open-all-notifications.tsx) doesn't work anymore - there's no "Open all in tabs" button anywhere.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/183673?v=4' alt='janpio' width=24 height=24> janpio](https://issuehunt.io/u/janpio) ($10.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by gibfahn** [comment]
I no longer see the option to go back to the old version, so can no longer work around this.

I'll take a look if I get the time, but I'm unikely to get the time 😁 .

**Comment by SuperSandro2000** [comment]
I got also forced into the new notification system and already missing the new tab button.

**Comment by riyathawani1** [comment]
yes, sometime it does not work for me as well. 

https://babatax.com/gstin/

**Comment by Jolg42** [comment]
I just created the PR #3046 that fixes it 😉 (First commit to Refined GitHub 🎊)

**Comment by Jolg42** [comment]
@fregante I didn't want to be mean in PR comments 🙃
From my point of view your comments were confusing sometimes 🤷‍♂️ 

Now it looks like I don't need to do anything anymore in PR #3046 as you copied what I did into your own PR #3047 👀 

Thanks for the speedy feedback anyway.

**Comment by fregante** [comment]
I closed your PR because I can't ask the same thing 3 times and then be told that screenshots are confusing. I didn't copy what you did, almost nothing is the same.
