### ISSUE TITLE
Strange, broken bugs tab behavior

### ISSUE THREAD

**Issue by Geo1088** [sindresorhus/refined-github#2917]
I stumbled upon #2750 after observing some strange behavior in version 20.3.16 on Firefox 74.0 under Windows 10. I have the `bugs-tab` feature enabled, so I'm assuming it's enabled by default. The tab doesn't show up if I just view [some repository's issues](https://github.com/toolbox-team/reddit-moderator-toolbox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc), but if I [filter specifically for the "bug" label](https://github.com/toolbox-team/reddit-moderator-toolbox/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug) then the tab shows up. The counter in the tab always displays 0.

<details>
<summary>Screenshots</summary>

![image](https://user-images.githubusercontent.com/4165301/77241023-62e21580-6bc3-11ea-851b-98e17989e944.png)
![image](https://user-images.githubusercontent.com/4165301/77241035-6fff0480-6bc3-11ea-9b57-ba2cb5ce54f5.png)

**Comment by fregante** [comment]
Any errors in the console? It might be https://github.com/sindresorhus/element-ready/issues/29

**Comment by fregante** [comment]
The tab appears for me in that repo, I think that's the issue

**Comment by Geo1088** [comment]
Oh, huh. I didn't realize a personal token was required for this feature. After setting one, it works as expected.

Is it a bug that it tries to add the tab anyway when viewing the "bug" label?

**Comment by fregante** [comment]
Generally if there's a bug, look for errors in the console. In this case it says specifically:

```
ℹ️ Refined GitHub: `bugs-tab`: Personal token required for this feature
```

When you're on the Bug label the tab is shown before the fetch happens (and fails, in this case)

https://github.com/sindresorhus/refined-github/blob/eca9e80d26e7e9bc07d27b862c00f795c91f9ed1/source/features/bugs-tab.tsx#L29-L31

0042dac hides the counter now.
