### ISSUE TITLE
Deployment shortcut in pull request headers

### ISSUE THREAD

**Issue by galacemiguel** [sindresorhus/refined-github#2918]
Not sure how widespread the use of the GitHub deployments API is, but we use it at my company to report staging deployments for all our pull requests. Problem is, as a pull request timeline grows, it becomes more and more of a pain to dig through to find the link to the latest deployment.

![image](https://user-images.githubusercontent.com/7394331/77244684-c8311780-6c52-11ea-816c-280996d3771d.png)

I actually built this into my own Chrome extension already, but I think more people could get some use out of it, so I'm opening an issue here.

Demo:
![Kapture 2020-03-22 at 15 39 46](https://user-images.githubusercontent.com/7394331/77244715-71780d80-6c53-11ea-952f-3496354571e2.gif)

Example URL: https://github.com/zeit/next-site/pull/553

**Comment by yakov116** [comment]
Is this acceped?

**Comment by fregante** [comment]
> Is this accepted?

These are https://github.com/sindresorhus/refined-github/labels/Please%21%20%E2%99%A5 😄

**Comment by yakov116** [comment]
But those are over my head 😆

**Comment by yakov116** [comment]
I made the base feature https://github.com/sindresorhus/refined-github/tree/deploy

@dwelle @galacemiguel do you have any repo I can play around with. (I want to test what happens on new deployments)

**Comment by dwelle** [comment]
Cool. Depends on what you mean by play around with, but lots is happening in [excalidraw](https://github.com/excalidraw/excalidraw/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)

**Comment by yakov116** [comment]
I dont want to test on an active repo. No one needs to get notifications when I am testing.

**Comment by galacemiguel** [comment]
> @dwelle @galacemiguel do you have any repo I can play around with. (I want to test what happens on new deployments)

None on my personal account, @yakov116. But thanks for working on this!
