### ISSUE TITLE
Show unread indicator on the bell icon when there are unread notifications

### ISSUE THREAD

**Issue by vadimdemedes** [sindresorhus/refined-github#292]
Currently, if there are only notifications marked as unread via the extension (no "native" github notifications), the notifications (bell) icon at the top right does not show a blue circle, but would be nice if it was.

<img width="131" alt="screen shot 2016-09-04 at 7 24 58 pm" src="https://cloud.githubusercontent.com/assets/697676/18232298/714edd14-72d5-11e6-9cf2-af293c326afa.png">

See https://github.com/sindresorhus/refined-github/pull/284 for "mark as unread" feature.

**Comment by sindresorhus** [comment]
Can you add the context? Not clear that you're talking about the "mark unread" feature. Same with other issues about this.

**Comment by vdemedes** [comment]
Sure.

**Comment by AshikNesin** [comment]
@jgierer12 I'm working on it.

Don't have any unread github notification.

Can you reply to my comment ? 😄

**Comment by jgierer12** [comment]
@AshikNesin 👍
