### ISSUE TITLE
`list-prs-for-file` shows merged PRs

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2922]
For me, it's showing already merged #2905 on `https://github.com/sindresorhus/refined-github/edit/master/source/libs/utils.ts` but that depends on cache state.

Would be great if the feature would check if the OPEN state is still true for PRs in cache.

**Comment by fregante** [comment]
We can't avoid these bugs. Either we have cache and deal with slightly out-of-date info or we trigger unnecessary/slow API calls at every page load.

**Comment by jack1142** [comment]
@fregante I know you closed this, but would it be possible to update the cache when you go to that PR? That would be possible to do using DOM so it wouldn't require an API call and at least for me, it would make the cache much more accurate.
