### ISSUE TITLE
Milestone value doesn't appear in Firefox

### ISSUE THREAD

**Issue by mgol** [sindresorhus/refined-github#2924]
Steps to reproduce in Firefox 74 with latest Refined GitHub (20.3.22):
1. Open an issue with a milestone set on a repo where you have edit access for milestones. For me it's https://github.com/jquery/jquery/issues/4453.
1. See that the milestone value doesn't show up. Only if you press the edit button you can see it on the list (see the screenshot).

The issue doesn't exist in Chrome 80 (with Refined GitHub 20.3.16) or in Firefox with the extension disabled.

<img width="256" alt="Screen Shot 2020-03-23 at 17 50 53" src="https://user-images.githubusercontent.com/1758366/77341441-026fe700-6d2f-11ea-846b-5f6b2b7afb6d.png">
<img width="329" alt="Screen Shot 2020-03-23 at 17 51 03" src="https://user-images.githubusercontent.com/1758366/77341445-03087d80-6d2f-11ea-8b7b-083d1245c8e4.png">

**Comment by fregante** [comment]
Due to #2916

**Comment by jerone** [comment]
`firstElementChild` maybe...

**Comment by alexdima** [comment]
Is there a simple workaround until a new version is published to the Chrome Store?

**Comment by yakov116** [comment]
Yes... download from the latest master build and load it your self
Here is the direct link
https://github.com/sindresorhus/refined-github/suites/558475923/rtifaacts/3598735

**Comment by alexdima** [comment]
That method works well, thanks! (The direct link didn't work due to a typo, but I found my way to it -- https://github.com/sindresorhus/refined-github/suites/558475923/artifacts/3598735)

**Comment by fregante** [comment]
This was published a while ago, 20.3.26 is on Chrome's store
