### ISSUE TITLE
Consider enabling new font again?

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#293]
This extension has lots of awesome features, but it disables GitHub's new larger and more legible fonts. Also, like @zeke mentioned in https://github.com/sindresorhus/refined-github/issues/261#issuecomment-232524434 having the major design features the same as other users can be useful when helping others out.

Are you open to considering reenabling the new fonts? They are quite nice after you adjust to them...

**Comment by zeke** [comment]
> They are quite nice after you adjust to them...

Agreed. It took me 24 hours to adjust.

**Comment by karlhorky** [comment]
Ping contributors @sindresorhus @paulmolluzzo @DrewML, any feedback for this one?

I guess @hkdobrev is against this change... can you post your reasoning shortly? Is it because the text is larger and you can fit less on your screen?

**Comment by hkdobrev** [comment]
I just can't get used to the font. I've tried to give it a try twice and I don't read it as easily as the previous one. It looks to me like something with the anti-aliasing is off and I feel like this is a font which one would use for a terminal / source code. Even if it gets reverted I'd probably add a custom css override for me for the old fonts.

**Comment by zeke** [comment]
> Even if it gets reverted I'd probably add a custom css override for me for the old fonts.

Judging by emoji reactions, it's what most people want.

**Comment by lipis** [comment]
Yes please.. the new font (right side) is much better... :)

<img width="1268" alt="screen shot 2016-11-06 at 00 23 10" src="https://cloud.githubusercontent.com/assets/125676/20034266/590f32ae-a3b7-11e6-8c81-79d498f3554a.png">

**Comment by sindresorhus** [comment]
Ok, done. GitHub has tweaked the font usage a lot since its inception and I think it's good enough now to adopt. And it's honestly a bit more readable. I'm leaving the old tweaks commented out for people wanting to preserve the old font. In the future, we might consider making the `custom.css` file editable in the options as it contains some highly opinionated overrides.

**Comment by hkdobrev** [comment]
@sindresorhus I was about to do a PR with the same as it seems I was the only one against it. I tested the new font this week as well and even used GitHub without the extension for a few days. I still have troubles with the new font on long texts, but I'll see if I'll get used to it or modify it for myself. Cheers!
