### ISSUE TITLE
Github image scaling on comment stream

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#2935]
Example issue: https://github.com/sublimehq/Packages/issues/1781#issuecomment-604070962

The scaling done on the images in issue comments is annoying. Basically, if the image width is bigger than the issue box, then you _must_ open the image to read it on a separate tab.

For me (i.e. _my JS level_), it is very easy to solve, and I already love it:

![image](https://user-images.githubusercontent.com/133706/77585636-7952de80-6eed-11ea-8a8d-b41b1effae8b.png)

_i.e. disable `max-width: 100%;` on the element and the class_

----

However, for Refined Github's level:

* Add a horizontal scrolling bar; the "normal" one or one of those cute round "invisible" gray ones, and/or
* Add an "expand" button that would widen the issues a little bit (there _is_ more space in WQHD monitors) / pop up the image

**Comment by yakov116** [comment]
It looks fine by me??

**Comment by fregante** [comment]
I see your point, ideally clicking the image would show it full size.

Then clicking it again would reset it.

You're lucky! Clicking the image already _does_ show it as big as possible, in a new tab, automatically, thanks to Markdown's automatic image linking.

The best part is that it even fits your screen, you can easily pan/scroll it if it doesn't, etc.

You can close it with a click on the X of the new tab that opened or by pressing `ctrl+w`/`cmd+w`

---

The alternative would be to show it in a lightbox... but what's the advantage? Too much work just to avoid opening a new tab

**Comment by FichteFoll** [comment]
For other purposes, I suggest using a browser addon like Imagus that provides a dynamic popup for all images and even special handlers for some sites.
