### ISSUE TITLE
normalize backslashes in 'find file' command

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#2937]
using the great shortcut `t` in the code tab allows to navigation across the repo by filename.

sometimes you get the filename/filepath you are searching for from a tool.
when working on windows this paths might contain windows directory separators instead of linux separators.
github does not support finding files, when the search term contains a windows separator

it would be great if refined-github would support searching within the files view when path contain windows style separators, e.g. it would normalize a path like `.\app\shared\models\Produkt.php` to `./app/shared/models/Produkt.php` so the native github file-finder will provide results

*Repro*
- open https://github.com/bmitch/churn-php
- press `t`
- type (or paste from clipboard) the string `Managers\FileManager`
ACTUAL: -> no results
EXPECTED: -> get the same results as for the search string `Managers/FileManager`
- instead type (or paste from clipboard) the string `Managers/FileManager`
-> you get the expected results

Tested on FF Nightly 76.0a1 (2020-03-25) (64-Bit) with refined-github 20.3.22

**Comment by fregante** [comment]
This doesn't sound like a terribly-difficult feature, however probably not a super common one. It sounds like it would be roughly something like

```js
function handler(event) {
	if (event.key === '\')) {
		insertTextTextarea('/');
		return false;
	}

	if (event.value.includes('\')) {
		insertTextTextarea(event.value.replace(/\\/g, '/'));
		return false;
	}
}

delegate('.file-tree-input', 'input', handler, true); // capture
```


Could you implement it yourself?

**Comment by staabm** [comment]
Thx for your feedback.

> Could you implement and support it yourself?

I dont think so.. no experience with typescript and browser extrnsions on my end, sorry
