### ISSUE TITLE
`pr-branches` doesn't show the branches when they're from a fork

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2943]
I'm sorry that I don't have anything more specific, the branches just don't show on the pull requests list. `pr-branches` is showing in the console but none of the PRs have info about their head branch below them and there's 20 PRs on that page and all of them are mine.

URL: https://github.com/Cog-Creators/Red-DiscordBot/pulls?q=is%3Apr+sort%3Aupdated-desc+author%3Ajack1142+is%3Aopen
Screenshot:
![image](https://user-images.githubusercontent.com/6032823/77700083-cc8f6480-6fb3-11ea-9c63-c72c6f18c189.png)

Maybe this will help a little - on refined-github's closed PRs list, the branch is showing for PRs made from the `sindresorhus/refined-github` repo, but it doesn't show for my PRs (made from the fork):
![image](https://user-images.githubusercontent.com/6032823/77700616-cea5f300-6fb4-11ea-92c5-d772842adc76.png)

**Comment by yakov116** [comment]
It only shows if the branch is a local branch

**Comment by jack1142** [comment]
> It only shows if the branch is a local branch

Well, yes, that's the bug I'm reporting here, I guess I should have made the title more clear.

I'm rather sure that is not intended behaviour, as there's an `if` that depending on whether the repo's head is on same repo or fork will add (or not) the repo's owner:
https://github.com/sindresorhus/refined-github/blob/6cd2344a487baca79dfea1bb918705f0e069fdd3/source/features/pr-branches.tsx#L45-L49

**Comment by fregante** [comment]
The exact situations in which to display the branch name was discussed in the original PR. 

This was done because often this piece of information isn’t useful, e.g. I don’t care what branch `user-x` created the PR from, especially on the list, which is already crowded. 

I’m guessing in this case that again it’s due to the case, rather than our logic.

**Comment by jack1142** [comment]
> I’m guessing in this case that again it’s due to the case, rather than our logic.

@fregante sorry to bother, but I don't quite get what you meant to say in this sentence? Maybe it's just late but figured I'll ask.

---

As for the issue, I don't quite get what's the use case of "From branch-name" that shows for source repo that isn't common with use cases of showing user's own branch names from a fork. You're right that user doesn't care what branch `user-x` created the PR from but I do think that when user is in fact `user-x` this changes cause it can become quite useful for managing *your* branches.

My use case is mostly the same as #190 which the original PR was supposed to solve too.
I'm guessing that having #2914 instead would be enough but I didn't get any feedback there and I was pretty sure that I saw `pr-branches` showing for my PRs from a fork before so I'm actually surprised to hear it isn't a bug.

**Comment by fregante** [comment]
> @fregante sorry to bother, but I don't quite get what you meant to say in this sentence? Maybe it's just late but figured I'll ask.

As your previous issues, they're because your organization and repo are not in lower case, so we have issues match it.

**Comment by fregante** [comment]
I checked, this is working as intended, it's in the logic: 

- only show local branches.

As shown by:

https://github.com/sindresorhus/refined-github/blob/6cd2344a487baca79dfea1bb918705f0e069fdd3/source/features/pr-branches.tsx#L122-L124

We do have some code that appears to support cross-repo branches, but it was probably left behind.

https://github.com/sindresorhus/refined-github/blob/6cd2344a487baca79dfea1bb918705f0e069fdd3/source/features/pr-branches.tsx#L47-L49

---

Honestly it's not a feature I find particularly useful in the first place, it's mostly just clutter to me. I'll disable it on my install.

---

Why do you need this information in the list?

**Comment by yakov116** [comment]
I would love for to work on forks

**Comment by jack1142** [comment]
> Why do you need this information in the list?

My use cases involve branch management of both local repo and remote repo:
- when I have list of all (both open and closed/merged) PRs
  - check what some branch is for (but I probably would need that rarely)
- when I have list of closed/merged PRs
  - removing branches on both local and remote (I can't use `git branch --merged` cause we're using squash merging)

As I mentioned earlier though, for my use cases #2914 would work quite great too, but I don't know if it's something that could be added to refined-github.

**Comment by fregante** [comment]
Both of those would be better solved by auto-deletion, which Refined GitHub already provides (and GitHub too, if you set it in your fork’s settings)

As for the local forks, I usually just delete everything locally and pull again. 

Your current situation requires a lot of manual work that you could skip altogether with these 2 suggestions.

**Comment by jack1142** [comment]
If you mean the "Automatically delete head branches" in repo's settings, it does not work if the PR is not done in same repository
