### ISSUE TITLE
Drop clipping the commit title when merging in `sync-pr-commit-title` feature

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#2944]
https://github.com/sindresorhus/refined-github/blob/9457eff9c6ec62ac13c853ba16184801258478cc/source/features/sync-pr-commit-title.tsx#L9

**Comment by fregante** [comment]
I’d leave the logic around to enable the red highlight, but without using `setValidity()`

**Comment by anorth** [comment]
Clipping could be appropriate if `limit-commit-title-length ` is enabled, but otherwise yes please.

**Comment by bradzacher** [comment]
I spent a while trying to figure out this - I find it super annoying.
I find that more often than not this clipping feature causes me to spend more time when merging, because it'll clip a long title if there are multiple commits (which is generally the case in typescript-eslint).
