### ISSUE TITLE
`deep-blame` doesn't support renamed files

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2949]
Feature: https://github.com/sindresorhus/refined-github/pull/2881

1. Visit https://github.com/sindresorhus/refined-github/blame/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/source/options.html#L1
2. Click Deep Blame button
3. See 404 page

The file is currently `source/options.html` but was [renamed](https://github.com/sindresorhus/refined-github/commits/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/src/options.html) [twice](https://github.com/sindresorhus/refined-github/commits/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/extension/options.html).

The link we generate should point to the file that existed at the time: `extension/options/index.html`

The regular blame follows renames, but I'm not sure we (`deep-blame`) can.

**Comment by yakov116** [comment]
@fregante I'll look into it tomorrow

**Comment by yakov116** [comment]
@fregante looked into it. I dont see a way

**Comment by fregante** [comment]
Yeah when we implemented the “follow renames” feature we had to pull the rename commit specifically and get the new name from there. 

Here we don’t know that commit at all, and even then there may be more than one. 

One thing we can do to avoid opening a 404 page is to check the filenames in the PR first. `If !associatedPr.fileList.includes(currentFile), alert(file was renamed)`

**Comment by yakov116** [comment]
Hmm, That would not work if the PR had more than 100 files No?

**Comment by fregante** [comment]
Yeah that'd break this feature on some 100+ files PRs. Maybe not worth the change

**Comment by fregante** [comment]
Is it possible to reach the file from the PR? Not just the files that the PR touches.

Example: `associatedPr.lastCommit.tree.file(name: currentFileName)`

**Comment by yakov116** [comment]
Yes but you would have the same issue if more than 100 files were changed For example #2925

**Comment by fregante** [comment]
Yep, possible:

```gql
{
  repository(owner: "sindresorhus", name: "refined-github") {
	# New
    file: object(expression: "1bd2494431d9ddc26ad27f9c32b1c8d711f3b263:source/options.html") {
      ... on Blob {
        text
      }
    }

	# Same as before
    commit: object(expression: "1bd2494431d9ddc26ad27f9c32b1c8d711f3b263") {
      ... on Commit {
        associatedPullRequests(last: 1) {
          nodes {
            number
            mergeCommit {
              oid
            }
            commits(last: 1) {
              nodes {
                commit {
                  oid
                }
              }
            }
          }
        }
      }
    }
  }
}

**Comment by yakov116** [comment]
Ok will send a PR in a few
