### ISSUE TITLE
File filter in compare page

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2951]
Something similar to file filter from PR's "Files changed" tab:
![image](https://user-images.githubusercontent.com/6032823/77836131-c20bd100-7153-11ea-8d39-561f160c80da.png)
Because of updates in `.po` files, GitHub's compare page isn't too useful:
https://github.com/cog-creators/red-discordbot/compare/3.3.1...3.3.2

I'm not sure if this is a kind of change that you do in refined-github but I can at least post it 😛

**Comment by fregante** [comment]
Implementing and maintaining such UI is a lot of work and neither Sindre (as far as I know) nor I use that picker at all

**Comment by sindresorhus** [comment]
While it would be useful for some people, it's too much work to make this and maintain than it's worth. I would recommend submitting this feature request to GitHub instead: https://github.com/contact
