### ISSUE TITLE
Folder style code difference

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#2959]
It would be awesome if we can have a folder style code diff, like how Beyond Compare has:

![image](https://user-images.githubusercontent.com/16418197/77986836-bba96080-72dd-11ea-9dbe-622c97d68d3a.png)

or how Code Compare offers:

![image](https://user-images.githubusercontent.com/16418197/77987386-4d659d80-72df-11ea-9832-12a4b246b686.png)

When we click on a file, we should see the Github's normal code difference for that particular file.
![image](https://user-images.githubusercontent.com/16418197/77987229-e5af5280-72de-11ea-8a4a-14fbe908c7c0.png)

This should appear wherever a code difference is shown, most importantly in pull requests (other URLs have less priority). This can help to review the pull requests much easier.

Example URL:
https://github.com/JunoLab/atom-indent-detective/pull/17/files

**Comment by fregante** [comment]
This feature requires considerable effort, it would be its own "app". It can't belong to Refined GitHub.

I'll leave it open for a little longer in case anyone knows anything like this or wants to build a separate extension for it.

**Comment by aminya** [comment]
Just to clarify, in this request I just wanted the **folder representation of differences**, not other features of Beyond Compare or Code Compare.

**Comment by fregante** [comment]
Yeah, that’s still pretty complex, it’s not just a button added somewhere but the whole navigable custom diff view just for folders. 

There’s nothing like it in GitHub’s components too so it also needs to be designed from scratch.
