### ISSUE TITLE
Desktop notifications

### ISSUE THREAD

**Issue by Turbo87** [sindresorhus/refined-github#296]
I wonder if it was possible to use the [Notification API](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) to show desktop notifications for incoming notifications from GitHub. Is that something that would potentially get merged or would that be wasted energy?

**Comment by devoxel** [comment]
I would love that personally.

I would work on a fork with you if you'd like, for sure.

**Comment by Turbo87** [comment]
I've looked into this a bit more now and it might not be possible to implement this in a reliable way after all. The reason for that is GitHub not having an official WebSocket API and polling the Notifications API isn't a great solution. Additionally it seems that there is currently way to access the API directly in this plugin due to the missing auth token required for authenticated API requests.

An alternative would be opening https://github.com/notifications in some sort of invisible iframe maybe and watching it for updates, but unfortunately that page only updates on browser refresh and not via their internal WebSocket pubsub system.

**Comment by DrewML** [comment]
There is a dedicated extension for this functionality [here](https://github.com/sindresorhus/notifier-for-github-chrome).

**Comment by Turbo87** [comment]
Oh cool, last time I tried that plugin I think it didn't have that functionality yet...

**Comment by DrewML** [comment]
I'm going to close this for now, since there is another (maintained) extension that (as I understand it) accomplishes this functionality. If there is a really good reason that can be made for pulling this into `refined-github`, we can re-open this issue to discuss more.
