### ISSUE TITLE
Broken link in README file

### ISSUE THREAD

**Issue by gimenete** [sindresorhus/refined-github#297]
Link "Adds user avatars to Reactions" in the highlights section is broken.

**Comment by gimenete** [comment]
It looks like GitHub processes the Markdown differently if you go to the homepage of the repo or you if you go to the readme file itself:

https://github.com/sindresorhus/refined-github (link doesn't work in this page)

https://github.com/sindresorhus/refined-github/blob/master/readme.md (link works here)

**Comment by sindresorhus** [comment]
GitHub bug: https://twitter.com/sindresorhus/status/775256735766355968

**Comment by SpaceK33z** [comment]
Looks like it has been fixed.
