### ISSUE TITLE
Incorrect first tab’s size in .md files’s diffs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#2970]
1. Visit https://github.com/sindresorhus/refined-github/pull/2925/files#diff-cc4aac3e9be04e0413c9520f223b493c
1. The tab is 1-space wide instead of 4

<img width="620" alt="bug" src="https://user-images.githubusercontent.com/1402241/78386588-24deeb80-75de-11ea-9b71-c2220dc759e8.png">

For some reason this doesn't happen to other filetypes, they're displayed with the right size:

<img width="422" alt="no-bug" src="https://user-images.githubusercontent.com/1402241/78386686-4d66e580-75de-11ea-90fd-61a4dfe554cf.png">

**Comment by fregante** [comment]
I double-checked and this doesn't seem to be due to `show-whitespace`

**Comment by notlmn** [comment]
Can confirm happening on Firefox version with `20.4.1`, but not on Chrome version which is still on `20.3.26`.

**Comment by yakov116** [comment]
Not seeing it at all on master in chrome

**Comment by yakov116** [comment]
Its `remove-diff-signs` and only in firefox

**Comment by fregante** [comment]
Then probably this just needs to change `content:none` to `visibility:hidden`
