### ISSUE TITLE
Add "Move to top/bottom" items to project board card context menus

### ISSUE THREAD

**Issue by felixfbecker** [sindresorhus/refined-github#2984]
It is very difficult to reorder items in projects with many cards, because you can only drag & drop them. It would be much easier if I could scroll through the column, and move cards to the top or bottom to reorder (and then do another pass to order those top cards with drag & drop).

GitHub doesn't have such a function in the UI, but it's a feature of the API: https://developer.github.com/v3/projects/cards/#move-a-project-card

Example URL:
GitHub projects

**Comment by fregante** [comment]
Projects are too big of a feature and everyone wants to make a Jira out of it. None of the maintainers use Projects, this feature would be best part of ZenHub or alternatives.

**Comment by fregante** [comment]
Also this is possible via GitHub's keyboard shortcuts: https://help.github.com/en/github/getting-started-with-github/keyboard-shortcuts#project-boards


Keyboard shortcut | Description
-- | --
enter or space | Start moving the focused column
escape | Cancel the move in progress
enter | Complete the move in progress
← or h | Move column to the left
command ← or command h or control ← or control h | Move column to the leftmost position
→ or l | Move column to the right
command → or command l or control → or control l | Move column to the rightmost position

**Comment by justinbarry** [comment]
@fregante out of curiosity what do the maintainers use?

**Comment by fregante** [comment]
Nothing, just regular labels

**Comment by Kietpawpan** [comment]
This is a issue of a tablet user, without a keyboard.

**Comment by jfritz** [comment]
Can we re-open this? How did this get closed by one person stating "Hey no one uses this feature"?
I would HEAVILY use this feature, and the listed keyboard shortcuts don't work for Github Projects Beta.

**Comment by yakov116** [comment]
No https://github.com/refined-github/refined-github/wiki/%22Can-you-add-this-feature%3F%22#7-it-doesnt-enhance-projects
