### ISSUE TITLE
Show mergeability of pull requests in PR list

### ISSUE THREAD

**Issue by FranklinYu** [sindresorhus/refined-github#2989]
In my PR list, I would like to know whether a PR is mergeable (no merge conflict). It’s available through [official API](https://developer.github.com/v3/pulls/#get-a-single-pull-request) (the `mergeable` key).

Example URL:
https://github.com/pulls

**Comment by fregante** [comment]
Related: We already show the conflict marker: https://github.com/sindresorhus/refined-github/issues/1593

I think this was already asked but I can’t find it. 

The problem with this is that there’s a lot of information around PRs and we can’t display it all on the lists, they’re already pretty cluttered

**Comment by FranklinYu** [comment]
Is #2310 rolled-back? I currently cannot see the marker. I tried the React Native repository mentioned there.

**Comment by yakov116** [comment]
@FranklinYu it should be workinf

**Comment by fregante** [comment]
> I currently cannot see the marker. I tried the React Native repository mentioned there.

That's because none of the PRs on the first page have conflicts. Here's some conflict when you sort by oldest: https://github.com/facebook/react-native/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-asc

**Comment by fregante** [comment]
Apparently "mergeability" is whether it can be merged without conflict, so it's exactly https://github.com/sindresorhus/refined-github/issues/1593 🎉
