### ISSUE TITLE
`show-whitespace` isn't wrapped to next line properly

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#2991]
https://github.com/discord/discord-api-docs/pull/1396/files#diff-99b76a48d014c043f2f8804f6653ed82
![image](https://user-images.githubusercontent.com/6032823/79006779-2cf8d700-7b5a-11ea-9fe5-4a8c6dbce886.png)

There's also a little different problem happening when GitHub Dark is enabled but I'm not sure if this is something you want to fix as well:
![image](https://user-images.githubusercontent.com/6032823/79006869-56b1fe00-7b5a-11ea-8b5c-9ea388f87713.png)

**Comment by fregante** [comment]
This one is though. There's no easy way to show the whitespace without compromising the copy-paste.

Currently we just overlay the •→ symbols via `:before` pseudo-element with `position: absolute`; this can't support the regular `inline` line breaking.

**Comment by fregante** [comment]
A solution could be wrapping each whitespace in its own element. This feature is already set up to only act on the visible lines so it might handle the extra operations without slowing down (except when the user scrolls past a lot of files very quickly)

**Comment by fregante** [comment]
I'm trying this out now, I can't replicate that wrapping behavior at all in both Chrome and Firefox. The spaces never wrap:

## With RG

<img width="882" alt="" src="https://user-images.githubusercontent.com/1402241/87654642-83784180-c757-11ea-8804-3152d0a23eda.png">

## Without RG

<img width="892" alt="" src="https://user-images.githubusercontent.com/1402241/87654754-a99de180-c757-11ea-9d08-dc30219b64fd.png">


cc @notlmn
