### ISSUE TITLE
Add "Cancel run" button to GitHub Actions to avoid having to go through the menu

### ISSUE THREAD

**Issue by mehrdadn** [sindresorhus/refined-github#2993]
Hi, I just wanted to request a new feature: Currently, to cancel a workflow on GitHub Actions, you have to click the "..." menu and then click "Cancel run". It'd be great if the button was right there so the extra menu indirection wouldn't be necessary, as it becomes quite burdensome when iterating on a workflow fix.

(I think #2561 is asking for a similar feature, but for re-running rather than canceling.)

Thank you!

Example URL:
https://github.com/sindresorhus/refined-github/actions

**Comment by fregante** [comment]
It's the same feature, add a comment there mentioning that it should also work for Cancel
