### ISSUE TITLE
use wext-manifest-loader for manifest.json

### ISSUE THREAD

**Issue by abhijithvijayan** [sindresorhus/refined-github#2995]
I suggest using https://www.npmjs.com/package/wext-manifest-loader for handling `manifest.json`

Even the publishing to stores is done using scripts, I think the changes to use this loader would be as minimal as building to two directories for publishing and providing a `TARGET_BROWSER` env variable with vendor name

@fregante What is your thought on this?

**Comment by fregante** [comment]
It serves no purpose here, it already works.
