### ISSUE TITLE
Forces twitter into mobile mode 

### ISSUE THREAD

**Issue by devoxel** [sindresorhus/refined-github#300]
# Summary

I'm noticing a new issue on my Ubuntu 16.04 LTS version of chrome. It seems to be a regression bug, maybe lying in Chrome but more probably lying in the Javascript behind Twitter.

# Versions

![chrome 53.0.2785.113, os Linux: 4.4.0-36-generic](https://cloud.githubusercontent.com/assets/1924007/18493962/546530b2-7a0b-11e6-8c5a-0484278f082f.png)

Ubuntu 16.04 LTS updated fully.

Chrome PPA link `/etc/apt/sources.list.d/`

```
# google-chrome.list
deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
```

**Comment by hkdobrev** [comment]
Is it possible that the issue is with https://github.com/sindresorhus/refined-twitter not with this extension about GitHub?

**Comment by devoxel** [comment]
nope, i did the standard turn off all extensions and it was this one that was causing the issue. I'll double check though. I dont use very many extensions in the first place

**Comment by devoxel** [comment]
Okay, seems after a reboot or two it's still fucked.

**Comment by devoxel** [comment]
:cry:
