### ISSUE TITLE
Bugs and Issues tabs are selected at the same time after the Back button

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3001]
1. You're on this issue (it works with any issue, not just bugs)
1. Click the repository’s Code tab
1. Go back in the browser (`history.back()`)

<img width="336" alt="bugs-tab-bug" src="https://user-images.githubusercontent.com/1402241/79167277-68f49c00-7de7-11ea-854a-e26210c0438e.png">

Semi-related possible enhancement: the bugs tab should be selected when opening a "bug" issue like this one

**Comment by yakov116** [comment]
And here https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+label%3Abug
