### ISSUE TITLE
Thumbsup first post should also subscribe to issue

### ISSUE THREAD

**Issue by fenollp** [sindresorhus/refined-github#3002]
Say you really are looking forward to a certain feature and an issue has already been filed.
Now GitHub [registers interest by counting thumbs-ups (`sort:reactions-+1`)](https://github.com/isaacs/github/search?q=sort%3Areactions-%2B1+is%3Aissue+is%3Aopen+is%3Aissue&type=Issues) so you go and **thumb up the first comment on that issue**.

Months later you realize someone posted a workaround on that thread but you were never made aware of this as you forgot to subscribe to the thread (or like me you assumed that `+1` automatically subscribed oneself).

Example URL: https://github.com/isaacs/github/issues/66#issue-16434919

I think **only adding a +1 to the first post of the issue should auto-sub** as it is colloquially at least how interest is registered. Moreover you don't want to be subscribed to a thread just because you've +1'd a random comment buried deep within.

Note: I couldn't find a related issue in this repo, however the thread of https://github.com/isaacs/github/issues/283 shows I am not the only one that assumed "+1 of 1st comment = subscribe".

Thanks for your life saving work.

**Comment by fregante** [comment]
>  (or like me you assumed that `+1` automatically subscribed oneself).

That's the wrong assumption, none of the social networks I know work that way. 

It kinda makes sense (`+1` shows interest) but also I don't want to know every single update to the issue until years later it's solved.

The Subscribe button is right there; If you want updates, it should be explicit.

**Comment by TPS** [comment]
Maybe don't fully subscribe, but be notified only whenever issue is thereafter closed?

**Comment by fregante** [comment]
I think it's still unwanted/unexpected behavior. #3005 would be useful to make _on-closed_ subscription faster.
