### ISSUE TITLE
Some features don't work on branches with slashes

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3004]
Any feature that makes use of `pathnameParts[4]` or `getReference` don't support branch names that contain `/`.

The problem with extracting the branch from the URL is that `branch/folder/folder/folder` is indistinguishable from `branch/still/branch/folder`, so the branch **cannot** be safely determined from the URL.

`fix-view-file-link-in-pr` and `link-to-file-in-file-history` both have solutions for it, but I think they're not easily copy-able.

For example `getReference` could be changed to:

```js
// Tested on the Code tab
return select('#branch-select-menu summary .css-truncate-target').textContent
```

Originally discussed in https://github.com/sindresorhus/refined-github/pull/2998#issuecomment-613125320
cc @yakov116

**Comment by yakov116** [comment]
@fregante getReference is not always on the code tab. For example in the deep blame we use it to replace the commit with the new commit.

Anyways the only time it will fail is if you are in a directory. Since any commit/blob will not have the dir anyway it will be repo/commit/jhfdskjlfhalsdkjfh <- will be the ref.

I am not sure how you want to proceed. I dont mind changing the other 2 features to use the dom.

**Comment by yakov116** [comment]
@fregante going to need direction.

https://github.com/yakov116/TestR/tree/a/b/sub

What was you idea? We need the file name and we need the path. (`edit-files-faster`)

**Comment by fregante** [comment]
> Anyways the only time it will fail is if you are in a directory.

No, **it fails anywhere a branch can appear in the URL.** `deep-reblame` is also affected: https://github.com/sindresorhus/refined-github/blame/broken/reblame/demo/test/utils.ts

`deep-reblame` will need to avoid using `getReference` altogether since we only use it to get the filename and generate a URL.
- the filename is in the breadcrumbs
- the URL can be generated from scratch: user/repo/blame/prBlameCommit/path

---

I think the best way forward would be to have `getReference` always use the DOM and **error** if the DOM isn't found. This is better than giving false promises that the received reference is correct.

**Comment by yakov116** [comment]
> @fregante going to need direction.
> 
> [yakov116/TestR:b/sub@`a`](https://github.com/yakov116/TestR/tree/a/b/sub) [](/yakov116/TestR/tree/HEAD@{2020-04-17T13:38:20Z}/b/sub)
> 
> What was your idea? We need the file name and we need the path. (`edit-files-faster`)

Can you direct me here. I need an idea how to handle this case.

>I think the best way forward would be to have getReference always use the DOM and error if the DOM isn't found. This is better than giving false promises that the received reference is correct.

This is going to need some work. Will try over the next week, hope this is not over my head.

**Comment by fregante** [comment]
> Can you direct me here. I need an idea how to handle this case.

If I have to write the whole thing I'll just push it myself

**Comment by yakov116** [comment]
> > Can you direct me here. I need an idea how to handle this case.
> 
> If I have to write the whole thing I'll just push it myself

Lets do that. From my experience (or lack of) when it comes to getting things from the dom your the number 1 man.

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/79693061-89cd4f00-8236-11ea-86c8-d0b1ab858112.png)

You want me to give it a go. No problem I'll try.

**Comment by notlmn** [comment]
Can use the last part of RSS link tag to extract branch name, similar to how we use link tags to get currently logged in user (if that is what we are still doing).

``` html
<link href="https://github.com/microsoft/PowerToys/commits/dev/PowerLauncher.atom"
	rel="alternate" title="Recent Commits to PowerToys:dev/PowerLauncher"
	type="application/atom+xml">
```

The last part after `/commits/` and before `.atom` in `href` above is always the branch name, same goes for `/commits/master.atom`.

Example: https://github.com/microsoft/PowerToys/tree/dev/PowerLauncher

**Comment by fregante** [comment]
I think we use that somewhere else. If we don’t, *used to use it and then replaced it*

If it appears on all the pages that use getReference that would be good

**Comment by fregante** [comment]
Indeed we still have it https://github.com/sindresorhus/refined-github/blob/453d3f8566695ce1ea7edd729fb319084bdb7fc2/source/libs/utils.ts#L79-L86

Maybe dropping `getReference` and just using `getCurrentBranch` will work, but it needs to be tested.

**Comment by yakov116** [comment]
@fregante that worked better than expected! The `more-dropdown` will always get the correct commit too now. (Happens to be that getReference() was added for that feature)

I tested on https://github.com/yakov116/TestR/tree/a/b/sub both the `edit-files-faster` and `edit-readme`

https://github.com/yakov116/refined-github/commit/068e8e51b6cb471b3b6bc4d8d4299cf70111956f

**Comment by fregante** [comment]
Can you also add every route where `getReference` is expected to work? e.g.

```js
/** Should work on isCommitList, isSingleFile, blah blah */
function getCurrentBranch() {……..}
```

**Comment by yakov116** [comment]
> Can you also add every route where `getReference` is expected to work? e.g.
> 
> ```js
> /** Should work on isCommitList, isSingleFile, blah blah */
> function getCurrentBranch() {……..}
> ```

Sure.

I dont see a place it does not work. (Even if your on the settings page it will give you the current branch)

**Comment by fregante** [comment]
> I dont see a place it does not work

I don't think it works on `isCommit` since that tag doesn't end in `.atom` but `.diff`, which means the function returns `0abcdef.diff`

**Comment by yakov116** [comment]
@fregante we are doing a select.last. That will give you .atom
