### ISSUE TITLE
From a GitHub Action workflow file add a button to see the workflow in action

### ISSUE THREAD

**Issue by maelle** [sindresorhus/refined-github#3008]
Thanks for refined-github!

Could a button help going from e.g. https://github.com/r-hub/docs/blob/master/.github/workflows/pr.yml to https://github.com/r-hub/docs/actions?query=workflow%3ACommands using the [workflow name](https://github.com/r-hub/docs/blob/b57f8a2001ef48270ae5ce3d039ea049013a982f/.github/workflows/pr.yml#L5)?

This way when trying to assess the use of an action, one would use GitHub search, then find workflow files, then from the files easily see logs of the action.

**Comment by maelle** [comment]
There can be several names by file, actually. https://github.com/tidyverse/ggplot2/blob/master/.github/workflows/pr-commands.yaml

**Comment by fregante** [comment]
Definitely. The UI around GH Actions is patchy. This feature should be very similar to [`html-preview-link`](https://github.com/sindresorhus/refined-github/blob/master/source/features/html-preview-link.tsx)

**Comment by maelle** [comment]
I know nothing about TypeScript (yet?) so I'm not sure _I_ could help but is there an example of feature reading a YAML field from a document?

**Comment by fregante** [comment]
It doesn't have to be perfect, something like this should cover most cases:

```js
$$('.blob-code-inner')
.find(line => line.textContent.startsWith('name'))
.textContent.replace(/^name:\s+/, '').trim()
```

Plus an extra `.replace` to trim quotes.

**Comment by maelle** [comment]
I'll give it a try then, thank you!
