### ISSUE TITLE
From a GitHub Action create a button to code search for the action use

### ISSUE THREAD

**Issue by maelle** [sindresorhus/refined-github#3009]
Related to #3008 :slightly_smiling_face: 

From e.g. https://github.com/marketplace/actions/urlchecker-action to https://github.com/search?q=urlstechie%2Furlchecker-action+path%3A.github%2Fworkflows%2F+language%3AYAML&type=Code&ref=advsearch&l=YAML&l= (searching GitHub Actions workflow files that reference the action)

**Comment by maelle** [comment]
Maybe under "Links" like "Open issues" :thinking:

**Comment by fregante** [comment]
Sounds a "Used by" link. This makes sense and probably GitHub will add it themselves.

Try also sending this feature request to GitHub: https://github.com/contact

**Comment by maelle** [comment]
I sent the feature request to GitHub, but haven't heard back yet.

To clarify, would the feature also be welcome here?

**Comment by maelle** [comment]
I'll work on that and hopefully this time give you less work in my PR! :smile_cat:

**Comment by maelle** [comment]
Too bad one cannot add the version number to the code search :crying_cat_face: (because of the "@").

**Comment by maelle** [comment]
but I'll use "recently indexed" as a search order, which might help.
