### ISSUE TITLE
New GitHub PR review feature - Hovering on reactions is semi-broken

### ISSUE THREAD

**Issue by DrewML** [sindresorhus/refined-github#301]
Adding a reaction for the first time works:
![image](https://cloud.githubusercontent.com/assets/5233399/18525533/7cbe4e64-7a82-11e6-99ad-2441573fe1e4.png)

Hovering over an existing reaction
![image](https://cloud.githubusercontent.com/assets/5233399/18525523/7105d182-7a82-11e6-831f-cd0d2e8de9b1.png)

**Comment by hkdobrev** [comment]
@DrewML I don't experience this. Possible A/B test?

**Comment by DrewML** [comment]
@hkdobrev It's on a private repo. If you open up a sample PR, I can leave review feedback and we can use that as a test-case for this issue?

**Comment by hkdobrev** [comment]
@DrewML I'm sorry. At the time of my comment I wasn't familiar with the new GitHub features. (They sound awesome BTW!). So I've read the title in a different way. I see what you mean now.

**Comment by hkdobrev** [comment]
@DrewML I think GitHub has patched that now. Could you confirm it's fixed for you as well?

**Comment by DrewML** [comment]
Yeah, it's fixed in GitHub. Closing
