### ISSUE TITLE
Github Actions: add a Link to open pull requests from the workflow view

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#3010]
it would be really helpful to have a link to the pull request open for a given branch (in case there is one).

right now we only have the branch name and can jump into the files view of it

Example URL:
https://github.com/redaxo/redaxo/actions

![grafik](https://user-images.githubusercontent.com/120441/79454690-f6084280-7feb-11ea-9ba3-25bf463fafc9.png)

**Comment by fregante** [comment]
It's there and it's clickable

![79454690-f6084280-7feb-11ea-9ba3-25bf463fafc9](https://user-images.githubusercontent.com/1402241/79483919-37f8af00-8013-11ea-824c-85f1a50df1cc.png)
