### ISSUE TITLE
Notification Beta: restore `open-all-notifications`

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3013]
in Issues and in Pull Request there is a "Open Selected" function
i like to have it also at the notifications beta

Example URL:
https://github.com/notifications/beta?after=Y3Vyc29yOjUw&query=repo%3Agatsbyjs%2Fgatsby+is%3Aunread+is%3Apr+is%3Aclosed

**Comment by fregante** [comment]
Duplicate of #2911
