### ISSUE TITLE
Add a `Convert to draft` button on release pages

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#3014]
Example URL: https://github.com/sindresorhus/got/releases/tag/v11.0.0-beta.1

Possible layout:

![image](https://user-images.githubusercontent.com/36894700/79641669-453fa600-8199-11ea-9eed-a26f27f425de.png)

Possible solution:

1. Prompt the user to type the release tag.
2. Remove the release.
3. Draft a new release release.

Why:

Sometimes you publish a release instead of making a draft.

**Comment by yakov116** [comment]
How will this handle release assets?

**Comment by fregante** [comment]
> How will this handle release assets?

We don't have to concern ourselves with that. Apparently there's an API endpoint to change the `draft` status, so this looks like an easy feature: https://docs.github.com/en/rest/reference/repos#update-a-release (we can use `api.v3` in this case)

**Comment by yakov116** [comment]
2 things.

1. We need to make an api request to get the release id.
2. I tried it out. It dumps everything and just places it into a draft. it does not copy the text etc. We would need to pass that along

**Comment by szmarczak** [comment]
Thank you, amazing work 🙌👌
