### ISSUE TITLE
`Update branch` button is misaligned on a draft PR

### ISSUE THREAD

**Issue by trollixx** [sindresorhus/refined-github#3017]
Noticed a misaligned `Update branch` button on my draft PR. The button is not there at all with the extension disabled. I am about to update the PR, hence no link, but here's a screenshot:

![image](https://user-images.githubusercontent.com/714940/79692880-a1f09e80-8235-11ea-9e05-c15d8255b53f.png)

**Comment by yakov116** [comment]
I think #2723 should take care of this too.

**Comment by fregante** [comment]
Duplicate of #2723
