### ISSUE TITLE
Store rejected the latest version

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3025]
Chrome Again https://github.com/sindresorhus/refined-github/runs/606725851?check_suite_focus=true#step:3:17

> Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab.

**Comment by sindresorhus** [comment]
Why do we require `contextMenu` and `storage`?

<img width="773" alt="Screenshot 2020-04-22 at 12 46 48" src="https://user-images.githubusercontent.com/170270/79941643-56d5c600-8497-11ea-8063-b372c60d21a1.png">

**Comment by fregante** [comment]
- Storage is for our options
- ContextMenus is to show this toggle https://github.com/fregante/webext-domain-permission-toggle

**Comment by sindresorhus** [comment]
Ok. Submitted.

**Comment by fregante** [comment]
All good

**Comment by fregante** [comment]
> 
> Response code 400 (Bad Request)
> {
>     "error": {
>         "code": 400,
>         "message": "Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab.",
>         "errors": [
>             {
>                 "message": "Publish condition not met: To publish your item, you must provide mandatory privacy information in the new Developer Dashboard: https://chrome.google.com/webstore/devconsole. Click on your item from the home page and enter this information on the Privacy tab.",
>                 "domain": "chromewebstore.access",
>                 "reason": "badRequest"
>             }
>         ]
>     }
> }

May be due to https://github.com/sindresorhus/refined-github/commit/2dc5f263b97730b82ceee8cb64edc5da76fe5893 and https://github.com/fregante/webext-storage-cache/pull/23

**Comment by fregante** [comment]
All good! Thanks
