### ISSUE TITLE
Add open in codesandbox button

### ISSUE THREAD

**Issue by abhijithvijayan** [sindresorhus/refined-github#3026]
See this tweet https://twitter.com/dferber90/status/1252594897619759104?s=19

**Comment by fregante** [comment]
From what I understand, CodeSandbox is just an editor online (one of many). It seems that its use cases aren't that many/frequent to justify a button to it for everyone.

Why would you use CodeSandbox instead of your local editor? Does that happen often?

**Comment by abhijithvijayan** [comment]
Some repositories require codesandbox example to be included before opening an issue.

I thought perhaps that might be useful.

**Comment by fregante** [comment]
Can you link to these repositories?

**Comment by abhijithvijayan** [comment]
@fregante https://github.com/final-form/final-form/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by fregante** [comment]
There's a fundamental difference between the tweet and reproducible examples.

If Refined GitHub adds a "Open in CodeSandbox" link, the sandbox will start with the repo's content.

Reproducible examples **do not** start from the current repo, their content is actually something like `require('current-repo-module')` where you add your own _broken_ code.
