### ISSUE TITLE
Automatically disable some features on large PRs

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#3029]
On some large pages, mostly PR changed files, there is sometimes a considerable slow down.

It would be good to have an option to prevent any changes running on certain pages, or to detect large PRs and disable things.

**Comment by sindresorhus** [comment]
We're unlikely to add a setting for this, but we definitely improve the default performance.

Do you have any public PR you could link us to where you experience large slow downs when Refined GitHub is enabled, where it's faster when Refined GitHub is disabled?

**Comment by vjpr** [comment]
@sindresorhus Just logged this one -> https://github.com/sindresorhus/refined-github/issues/3028

Although...after I disabled it, it improved things a bit but there are still 1s lags sometimes coming from `github-bootstrap.js`, so not sure how much blame can be made for this extension.

**Comment by vjpr** [comment]
> Do you have any public PR

Sorry! Misread your previous comment. Maybe I can put one together in a sample repo for testing.

**Comment by fregante** [comment]
> sometimes coming from `github-bootstrap.js`

That's not Refined GitHub

**Comment by vjpr** [comment]
@fregante 

> coming from `github-bootstrap.js`, so **not sure how much blame can be made for this extension.**

Yep I know - which made me think perhaps my #3028 issue is not to do with the extension...

**Comment by fregante** [comment]
Disabling _everything_ on a page isn't possible. We can't prevent CSS from being injected.

Disabling _everything_ on a page probably isn't desirable, I'm sure that there are a few features you'll instantly miss.

I think it's best to improve the specific features that slow down, like I did in https://github.com/sindresorhus/refined-github/pull/2737 and like your specific issue in #3028

**Comment by fregante** [comment]
It would be interesting however to proactively track possible slow features: https://github.com/sindresorhus/refined-github/issues/3032

**Comment by fregante** [comment]
I wonder if, like GitHub does for large comparison, we could disable some/all features on large PRs and show a notice like **"Some RG features were disabled because this page is gargantuan."**
