### ISSUE TITLE
Show status of PR in overview

### ISSUE THREAD

**Issue by SpaceK33z** [sindresorhus/refined-github#303]
With the new PR review features GitHub introduced today, it's possible to "review" a PR. It is possible to approve the PR, or to request changes.

My problem is, that after I approve or request changes, I can't see in the overview what I've done. I need to click on every PR and check what the status is.

**Comment by sindresorhus** [comment]
What kind of status are you interested in? Like `Approved`, `Pending requested changes`, etc?

**Comment by SpaceK33z** [comment]
Yeah, those two statuses.

**Comment by sindresorhus** [comment]
Seems like many people agree: https://twitter.com/dan_abramov/status/777224519543128064

Anyone wanna do a pull request?

**Comment by DrewML** [comment]
I like the idea a lot, but this is could be brutal for people on slow connections if we don't offer a setting to disable. We'll have to make (up to) 25 requests on page load anytime you visit `/pulls/`. The GitHub API doesn't have the ability to batch requests (and the new GraphQL API doesn't have the functionality we'd need quite yet), so we'd just be fetching the DOM for each PR page

**Comment by SpaceK33z** [comment]
@DrewML, is it correct that the GitHub API doesn't even have the ability to see the status at all? I've browsed [through it](https://api.github.com/repos/sindresorhus/refined-github/pulls/304), but the ["review comments"](https://api.github.com/repos/sindresorhus/refined-github/pulls/304/comments) API also doesn't seem to have it.

**Comment by DrewML** [comment]
@SpaceK33z Yeah, doesn't look like it :( We'd have to do fetch + DOM parsing/scraping like we do with [real names](https://github.com/sindresorhus/refined-github/blob/master/extension/show-names.js) functionality.

**Comment by hkdobrev** [comment]
While these reviews could prove to be immensely useful I think they are in very early stage at the moment and GitHub would significantly improve them in the next 6 months (as stated at GitHub Universe). They could fix some nagging problems in the review process, but could also improve the API and the rest of the UI around them. I'm not sure this is worth doing before we see what they'll do with them. I guess we could contact GitHub and urge them to add the review status to the PR list. I'd also like to add them to the search filters.

**Comment by SpaceK33z** [comment]
Looks like GitHub implemented exactly what I wanted:

![pull_requests_ _webpack_webpack_js_org](https://cloud.githubusercontent.com/assets/533616/20519416/33ab75e2-b0a3-11e6-899c-862da4ce502b.png)

If you hover over them you see more details. Super awesome! Closing this.
