### ISSUE TITLE
Hide explore repositories section

### ISSUE THREAD

**Issue by dareenzo** [sindresorhus/refined-github#3040]
Please add an option to hide the explore repositories section on the home page (https://github.com/). It is very distracting

**Comment by fregante** [comment]
I don’t see a section named “Explore repositories”, can you take a screenshot?

**Comment by dareenzo** [comment]
Look on the right side

![Screenshot from 2020-04-28 11-28-14](https://user-images.githubusercontent.com/6130991/80471219-66e02080-8943-11ea-8fb2-20ca0bf0c495.png)

**Comment by fregante** [comment]
Indeed, I was looking on my phone.

I don't find it annoying and we can't make it an option, but you can hide it by pasting this CSS in the "Custom CSS" field in Refined GitHub’s options

```css
[aria-label="Explore"] {
    display: none;
}
```

**Comment by dareenzo** [comment]
Thanks, I'll do that.
