### ISSUE TITLE
Commit timestamp in commit list (instead of 'x days ago')

### ISSUE THREAD

**Issue by actuallymentor** [sindresorhus/refined-github#3042]
On url pattern `https://github.com/<org>/<repo>/commits/<branch>` commits currently show pretty times like `committed 9 days ago`.

It would be great to have this as `xx:zz, Day Month Year`.

**Comment by actuallymentor** [comment]
Note: the data is already in the DOM:

```
<relative-time datetime="2020-04-21T18:41:06Z" class="no-wrap" title="21 Apr 2020, 20:41 CEST">8 days ago</relative-time>
```

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/47
