### ISSUE TITLE
Add "toggle all with alt-click" to `batch-mark-files-as-viewed`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3043]
Follows #3007 

- [ ] Add alt-click to toggle all ("all _loaded_ files")
- [ ] Add a "in progress" indicator next to the counter, because the marking might take a few seconds:
	<img width="167" alt="counter" src="https://user-images.githubusercontent.com/1402241/80626709-2372d880-8a4f-11ea-98b9-9e3c2419f60f.png">

**Comment by fregante** [comment]
>  * Add a "in progress" indicator

I saw GitHub using this, it might be less troublesome than adding elements to that bar. It can also be used for other features.

 <img width="360" alt="" src="https://user-images.githubusercontent.com/1402241/80818201-0d8e2080-8bd3-11ea-8a96-5e2ab57c37dc.png">

```html
<div role="log" style="z-index: 101;" class="
  position-fixed bottom-0 left-0 ml-5 mb-5
  anim-fade-in fast Toast
  Toast--loading">
  <span class="Toast-icon">
      <svg class="Toast--spinner" viewBox="0 0 32 32" width="18" height="18">
        <path fill="#959da5" d="M16 0 A16 16 0 0 0 16 32 A16 16 0 0 0 16 0 M16 4 A12 12 0 0 1 16 28 A12 12 0 0 1 16 4"></path>
        <path fill="#ffffff" d="M16 0 A16 16 0 0 1 32 16 L28 16 A12 12 0 0 0 16 4z"></path>
      </svg>
  </span>
  <span class="Toast-content">Bulk actions currently being processed.</span>
</div>
```

<img width="364" alt="" src="https://user-images.githubusercontent.com/1402241/80818203-0e26b700-8bd3-11ea-9d81-d54f7ef6a557.png">

```html
<div role="log" style="z-index: 101;" class="
  position-fixed bottom-0 left-0 ml-5 mb-5
  anim-fade-in fast Toast
  Toast--success" >
  <span class="Toast-icon">
      <CheckIcon />
  </span>
  <span class="Toast-content">Bulk action processing complete.</span>
    <button class="Toast-dismissButton" type="button" aria-label="Close">
      <XIcon />
    </button>
</div>
```

**Comment by borriglione** [comment]
It seems it doesn't work for me anymore. Can you confirm?

**Comment by fregante** [comment]
Why did you ignore this message?

<img width="955" alt="Image" src="https://github.com/user-attachments/assets/b59d8e5d-899d-4892-81c9-42bf498c94c0" />


It works:

![Image](https://github.com/user-attachments/assets/402eae4b-810a-469d-a31f-be4e30e08d73)
