### ISSUE TITLE
User's Local Time Does Not Consider Changes in Their Region's Zone Offset

### ISSUE THREAD

**Issue by sshaw** [sindresorhus/refined-github#3049]
Can be seen in this with this fellow (or even myself!): https://github.com/samuelneff/MimeTypeMap

<img width="550" alt="Screen Shot 2020-05-02 at 12 17 46 AM" src="https://user-images.githubusercontent.com/17570/80854971-8fe60700-8c0a-11ea-80a4-44e6ab02bc1b.png">

US Eastern Time's offset can be -4 or -5. Currently it's -4 but it shows the user's time as -5. 

A quick look at the code shows that the zone is taken from the last commit but is not adjusted.

**Comment by fregante** [comment]
Likely impossible, this is all the information we have
```
From 299ed7c1f3e4711867b4d0f1c030da474d846fc4 Mon Sep 17 00:00:00 2001
Date: Fri, 1 May 2020 03:07:39 -0400
Subject: [PATCH] Add support for Metafield and Product
```

and https://api.github.com/repos/ScreenStaring/recharge-api/commits/299ed7c1f3e4711867b4d0f1c030da474d846fc4

---

At some point we used to use geolocate the user with their bio information, but that's less accurate (made up or missing) and required API calls to a 3rd party (Google)

**Comment by sshaw** [comment]
Hi, this would't work:

```js
const timeAdjustment = new Date().getTimezoneOffset() - new Date(commitTime).getTimezoneOffset()
```

?

**Comment by fregante** [comment]
As [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date/getTimezoneOffset) says:

```js
const date1 = new Date('August 19, 1975 23:15:30 GMT+07:00');
const date2 = new Date('August 19, 1975 23:15:30 GMT-02:00');

console.log(date1.getTimezoneOffset());
// expected output: your local timezone offset in minutes
// (eg -120). NOT the timezone offset of the date object.
```

**Comment by sshaw** [comment]
We want to display the user's time in my local timezone which may differ if it's currently daylight savings time. Given this (in Chrome):


```
> new Date() 
Sat May 02 2020 13:54:50 GMT-0400 (Eastern Daylight Time)
> new Date().getTimezoneOffset()
240
> new Date('August 19, 1975 23:15:30 GMT+07:00').getTimezoneOffset()
240
// Time change is in effect during this time
> new Date('December 24, 1975 23:15:30 GMT+07:00').getTimezoneOffset()
300
> new Date('December 24, 1975 23:15:30 GMT+07:00').getTimezoneOffset() - new Date().getTimezoneOffset()
60
```

Seems like it would work, no?

**Comment by fregante** [comment]
Can you do a test?

1. Run this on a repo you just committed to:

```
git log -1
```

2. Google [Current time](https://www.google.com/search?q=Current+time)

What are your values?

---

I get
```diff
commit a351ce6baf0d83d41892e079f9c1eb05c6d3940c (HEAD -> master)
Author: Federico Brigante <opensource@bfred.it>
Date:   Sat May 2 20:16:42 2020 +0200

    Avoid duplicate event handlers in `toggle-everything-with-alt`
```
```
9:20 PM
Saturday, May 2, 2020 (GMT+2)
Time in Province of Lecce 
```

It appears that GIT saves daylight savings in the timestamp since my timezone should be GMT+1 but we're currently in Daylight Savings Time, so the log’s `+0200` is correct and should work correctly.

**Comment by sshaw** [comment]
```
~/code/ruby/file_types >git --no-pager log -1
commit 32306b5e5e8151f3f3691a20bfd686a232925588
Author: sshaw <skye.shaw@gmail.com>
Date:   Sat May 2 17:13:25 2020 -0400

    Initial commit
````
---
<img width="685" alt="Screen Shot 2020-05-02 at 5 31 54 PM" src="https://user-images.githubusercontent.com/17570/80892820-05011d00-8c9b-11ea-815f-60d64b98fc38.png">

**Comment by fregante** [comment]
`-0400` appears to be EDT, so yeah git is giving us the right time *and* we're showing the right time as well. 

This is what Refined GitHub shows for you:

<img width="348" alt="" src="https://user-images.githubusercontent.com/1402241/80893252-01888880-8cd1-11ea-95a2-07a3f484dc7e.png">

**Comment by sshaw** [comment]
> This is what Refined GitHub shows for you: ...
> Looks correct. Where's the bug?

When figuring out the zone, [you're taking the last commit](https://github.com/sindresorhus/refined-github/blob/a351ce6baf0d83d41892e079f9c1eb05c6d3940c/source/features/user-local-time.tsx#L42) on the first page (though comment indicates otherwise, not sure this is the case). 

For myself, this is https://api.github.com/repos/sshaw/class2/commits/c4154aed352d8b2b91f40536f3abdc1bb0cf6ee4:

```
~/code/js/prototoy >curl -s https://api.github.com/users/sshaw/events | tail
          "message": "v0.5.2",
          "distinct": true,
          "url": "https://api.github.com/repos/sshaw/class2/commits/c4154aed352d8b2b91f40536f3abdc1bb0cf6ee4"
        }
      ]
    },
    "public": true,
    "created_at": "2020-04-25T03:12:21Z"
  }
]
~/code/js/prototoy >curl -sH'Accept: application/vnd.github.v3.patch' https://api.github.com/repos/sshaw/class2/commits/c4154aed352d8b2b91f40536f3abdc1bb0cf6ee4 | head
From c4154aed352d8b2b91f40536f3abdc1bb0cf6ee4 Mon Sep 17 00:00:00 2001
From: sshaw <skye.shaw@gmail.com>
Date: Fri, 24 Apr 2020 23:11:57 -0400
Subject: [PATCH] v0.5.2

---
 Changes               | 4 ++++
 lib/class2/version.rb | 2 +-
 2 files changed, 5 insertions(+), 1 deletion(-)

```


Date of `Fri, 24 Apr 2020 23:11:57 -0400`, -4, which is the current offset, so there's no discrepancy.


For samuelneff, this is https://api.github.com/repos/ice1e0/MimeTypeMap/commits/70d1aa85c102753af5e7d1e09d2042649c5666b2:

```
~/code/js/prototoy >curl -s https://api.github.com/users/samuelneff/events | tail
          "message": "Update emf -> images/emf",
          "distinct": true,
          "url": "https://api.github.com/repos/ice1e0/MimeTypeMap/commits/70d1aa85c102753af5e7d1e09d2042649c5666b2"
        }
      ]
    },
    "public": true,
    "created_at": "2020-02-25T22:27:09Z"
  }
]
~/code/js/prototoy >curl -sH'Accept: application/vnd.github.v3.patch' https://api.github.com/repos/ice1e0/MimeTypeMap/commits/70d1aa85c102753af5e7d1e09d2042649c5666b2 | head
From 70d1aa85c102753af5e7d1e09d2042649c5666b2 Mon Sep 17 00:00:00 2001
From: Samuel Neff <samuelneff@users.noreply.github.com>
Date: Tue, 25 Feb 2020 17:27:07 -0500
Subject: [PATCH] Update emf -> images/emf

---
 src/MimeTypes/MimeTypeMap.cs | 3 ++-
 1 file changed, 2 insertions(+), 1 deletion(-)

diff --git a/src/MimeTypes/MimeTypeMap.cs b/src/MimeTypes/MimeTypeMap.cs
```

Date of `Tue, 25 Feb 2020 17:27:07 -0500`, `-5`, which _is not_ the current offset. Therefore the time being displayed is off by one hour.

**Comment by fregante** [comment]
So the user lives in the same timezone as you? How is Refined GitHub supposed to know? We see -0400 for you and -0500 for them. As far as we’re concerned, their timezone is -0500 and there’s nothing we can fix. 

Again, we can’t fix bad data. 

The only thing we could change is the source of data:
- why is that 500 instead of 400?
- is there any other way to determine their correct timezone?

**Comment by sshaw** [comment]
It's not bad data. You need to **1**) get the most recent commit and **2**) adjust for daylight savings time as pointed out [here](https://github.com/sindresorhus/refined-github/issues/3049#issuecomment-622991195). 

Though I suppose **1** will address most occurrences of this issue. 

Maybe I will open a PR ⏳

**Comment by fregante** [comment]
1. What is the user’ exact timezone?
2. What time does it show for me?
