### ISSUE TITLE
GitHub bug: tabs are missing 2 characters in diffs

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#3052]
I think that GitHub changed markup for diff UI containing diff markers. Right now markers are being hidden using `visibility: hidden` ([link](https://github.com/sindresorhus/refined-github/blob/8311dce05d80d0f899853344fe8099a582ec62b6/source/features/remove-diff-signs.css#L1-L4)), but we may need to use `display: none`.

This fails when the first character of the line is a tab, in which case it gets collapsed. This can be clearly seen code starting with spaces ([demo](https://github.com/notlmn/.dotfiles/pull/3/files#diff-bc7b4362a437c9cab951fbbadd89e764R14-R16)).

And yes, using `display: none` on the pseudo elements did fix this for me, for code indented with tabs and spaces.

## Test

- PR diff: https://github.com/sindresorhus/refined-github/pull/3051/files#diff-3607e5002f8b54915e7c24d1741d078bR1-R4
- Compare UI: https://github.com/sindresorhus/refined-github/compare/clean-notifications?expand=1

## Screenshot

![image](https://user-images.githubusercontent.com/37769974/80863162-04b35280-8c98-11ea-8234-a37ea17d7c82.png)

**Comment by fregante** [comment]
I changed that recently (https://github.com/sindresorhus/refined-github/commit/35303dc98eaab5eea46d8f9f2fb3afb48eb64bcf) because it caused https://github.com/sindresorhus/refined-github/issues/2970

**Comment by fregante** [comment]
I'm pretty sure what you're seeing is due to `tab-size: 4`, not those 2 features. Is this the "interference" you're seeing?

![](https://user-images.githubusercontent.com/1402241/80864828-80f06a80-8c85-11ea-9a36-ae32052abedb.gif)

The first tab does seem to be collapsed to 2 spaces instead of 4

**Comment by notlmn** [comment]
> I'm pretty sure what you're seeing is due to `tab-size: 4`, not those 2 features. Is this the "interference" you're seeing?

I think that might be it, but not sure why that is happening.

----------------

> I changed that recently ([35303dc](https://github.com/sindresorhus/refined-github/commit/35303dc98eaab5eea46d8f9f2fb3afb48eb64bcf)) because it caused #2970.
> 
> Edit: I tested this and `display: none` still causes #2970 so the suggested change can't be applied.

Tabs on https://github.com/sindresorhus/refined-github/pull/2925/files#diff-cc4aac3e9be04e0413c9520f223b493c, sample for #2970 is now being translated to 3 spaces instead of 4 in markdown files.

![image](https://user-images.githubusercontent.com/37769974/80873556-1e27bf00-8cd7-11ea-87e5-9691ebf34d9a.png)

**Comment by fregante** [comment]
So is that the issue you’re talking about?

**Comment by fregante** [comment]
This is likely happening because the line (as far as the browser is concerned) includes the diff signs and the space after it. That’s 2 extra characters that shouldn’t be there. 

I don’t know if there’s an easy way to *convince* the browser to start *after* the diff signs. My guess is that a **block element** resets the tabulations. Maybe we can fix **their** bug.

**Comment by fregante** [comment]
Perhaps it’s better to open a new, clearer issue for a feature request. Can you open it?
