### ISSUE TITLE
Automatically close the notification top bar

### ISSUE THREAD

**Issue by evandrocoan** [sindresorhus/refined-github#3061]
This new notification system keeps a top bar top when I open a notification. That bar is completely useless because I always open all notifications in a new tab from the main page, then, I never use anything on it other than the close button (because it keeps a persistent top bar covering my precious page vertical space).

**Comment by fregante** [comment]
I also don’t use it, but I don’t see the problem with keeping it there for those who do use it.

We even just added a feature for it https://github.com/sindresorhus/refined-github/pull/3036

**Comment by evandrocoan** [comment]
I am not saying to close it by default for everyone, but just when someone configure to always close it.

**Comment by evandrocoan** [comment]
I installed [`Tampermonkey`](https://chrome.google.com/webstore/detail/tampermonkey/dhdgffkkebhmkfjojejmpbldmpobfkfo?hl=en) and created this script:
```js
// ==UserScript==
// @name         Close GitHub Notifications bar
// @namespace    *
// @version      0.1
// @description  https://github.com/sindresorhus/refined-github/issues/3061
// @author       You
// @include http://*github.com/*
// @include https://*github.com/*
// ==/UserScript==

(function() {
    'use strict';
    console.log('Closing notifications button');
    document.querySelector('btn-octicon js-flash-close').click();
})();
```

**Comment by fregante** [comment]
Thank you for sharing your solution!

**Comment by mpratt14** [comment]
> ```js
>     clickButton('button[aria-label="Close notification controls"].btn-octicon.js-flash-close');
> ```

it is now

```
clickButton('button[aria-label="Close notification controls"].js-flash-close');
```

**Comment by evandrocoan** [comment]
Thanks. I updated the answer.
