### ISSUE TITLE
"This pr has conflicts" pop-up is hidden by table title

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#3063]
As you can see, the "This PR has conflicts that must be resolved" is hidden.

**Bug URL**: https://github.com/owner/project/pulls
**Screenshot**:
![Capture d’écran 2020-05-05 à 15 14 34](https://user-images.githubusercontent.com/42497995/81070445-8814b400-8ee3-11ea-9255-664f72212984.png)
**Priority**: very low

**Comment by H4mza96** [comment]
I have Pressure

**Comment by H4mza96** [comment]
Then refresh
