### ISSUE TITLE
Clicking `x/y files viewed` should take you to the first unviewed file

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3069]
1. Open PR like https://github.com/sindresorhus/refined-github/pull/3062/files
2. See this <img width="170" alt="Screen Shot 2020-05-06 at 17 54 06" src="https://user-images.githubusercontent.com/1402241/81199232-ae5d5100-8fc2-11ea-8ec8-516db617de2a.png">
3. Good luck finding the the 9 files you should review

Clicking `x/y files viewed` should take you to the first unviewed file.

If it can't be found on the page (because not yet loaded) it should scroll to the bottom of the page. At that point the user can click again.

**Comment by yakov116** [comment]
If anyone wants to send a pr (needs a but more testing) I put together something.

```ts
import select from 'select-dom';
import delegate from 'delegate-it';
import * as pageDetect from 'github-url-detection';

import features from '.';

function jumpToFirstUnviewed(): void {
	const firstNotView = select('.js-reviewed-checkbox:not([checked])')!;
	if (!firstNotView) {
		window.scrollTo(0, document.body.scrollHeight);
		return;
	}

	firstNotView.closest('.Details--on')!
		.scrollIntoView({
			block: 'start'
		});
}

async function init(): Promise<void> {
	delegate(document, 'progress-bar', 'click', jumpToFirstUnviewed);
}

void features.add({
	id: __filebasename,
	description: 'Jumps to first unviewed pr file.',
	screenshot: false
}, {
	include: [
		pageDetect.isPRFiles
	],
	init
});
```

**Comment by fregante** [comment]
Perhaps it’s less troublesome to let the browser handle the scrolling natively (also because of the fixed header). 

So instead of scrollIntoView, change location.hash

**Comment by yakov116** [comment]
I tried that out. We then have a an issue with the history state. (Going back after clicking it 5 times will need back 5 times)
