### ISSUE TITLE
Show currently viewed file in PR header

### ISSUE THREAD

**Issue by shaharmor** [sindresorhus/refined-github#307]
It would be awesome to have the currently viewed file in the header of the PR: (In the white space in the middle)

![screen shot 2016-09-20 at 10 19 59 am](https://cloud.githubusercontent.com/assets/10861920/18660904/b1f65386-7f1b-11e6-9a1b-3ac0136ee8f5.png)

**Comment by hkdobrev** [comment]
@shaharmor This was already implemented in #99 then got broken in #264 and fixed again in #274. Apparently it's broken again so I've reopened #264 and will close this "feature request" as a duplicate as it had already been working, but got broken so it's a bug.
