### ISSUE TITLE
Open Unread / open-all-notifications no longer works on Enterprise GitHub

### ISSUE THREAD

**Issue by StephenBrown2** [sindresorhus/refined-github#3071]
This is sort of a bug, sort of a feature request.

Unfortunately, GitHub has moved to a more email-like notification structure.

More unfortunately, my company's on-premise GitHub instance hasn't been updated to the new UI, so I've lost the "Open Unread" functionality I loved from Refined GitHub.

Is it possible to add a switch in [open-all-notifications](https://github.com/sindresorhus/refined-github/blob/master/source/features/open-all-notifications.tsx) for the old way of doing things, for those companies that are constantly behind the times?

URL: https://github.mycompany.com/notifications
Screenshot:
<img width="1430" alt="Screenshot 2020-05-07 at 14 06 47" src="https://user-images.githubusercontent.com/1148665/81340085-7ca0c480-906c-11ea-82c6-c65591431aa6.png">

**Comment by yakov116** [comment]
We try not to break GitHub Enterprise and we accept Enterprise-only bug fixes, but we’re not going to hold back doing non-breaking changes like this. If you need more control, you can clone the repo and use the extension as a local extension. That way you can control when to update.

_Originally posted by @sindresorhus in https://github.com/sindresorhus/refined-github/issues/1530#issuecomment-421553029_

**Comment by StephenBrown2** [comment]
Note: I'm not being snippy.

If by "non-breaking" you mean "removing a previously working feature", then sure.

/me Reads linked issue comment.

Makes sense. Thanks for the reference!

**Comment by busches** [comment]
For the record, if you have a PR that restores the support to GHE and it's not a drastically different implementation, we're open to that. Notifications is not something I use on GHE and have basically ignored all of those PRs to ensure they were still compatible.
