### ISSUE TITLE
Number of forks is not shown

### ISSUE THREAD

**Issue by sai-manoj-kumar** [sindresorhus/refined-github#3074]
[URL](https://github.com/mafintosh/hash-to-port)
![image](https://user-images.githubusercontent.com/647333/81412310-4e50e100-9161-11ea-9599-8bf499459f94.png)

**Comment by fregante** [comment]
It's a feature, it can be disabled: https://github.com/sindresorhus/refined-github/blob/master/source/features/hide-watch-and-fork-count.tsx

**Comment by sai-manoj-kumar** [comment]
Yes, just found it while trying to find a "fix" for it.

**Comment by fregante** [comment]
Update: the forks count was restored in v21.4.23 (on wide viewports) since it points to a potentially-useful forks list page.

https://github.com/sindresorhus/refined-github/pull/4249
