### ISSUE TITLE
Group Action checks by job name

### ISSUE THREAD

**Issue by EvanPurkhiser** [sindresorhus/refined-github#3075]
Would be great to have a way to group checks that are part of one job

Example of how it is now:
![image](https://user-images.githubusercontent.com/1421724/81451929-724cfc00-913a-11ea-9da2-64a382cced33.png)

What it could look like:

![image](https://user-images.githubusercontent.com/1421724/81452293-57c75280-913b-11ea-9d56-e7e260ffc818.png)

![image](https://user-images.githubusercontent.com/1421724/81452233-39f9ed80-913b-11ea-9bed-a262e598798b.png)

**Comment by fregante** [comment]
We'll have to pass on this feature.

If the tests are completed and pass, GitHub already collapses the whole list.

If the tests are in progress or failed, they must be shown to the user as-is.

**Comment by fregante** [comment]
@EvanPurkhiser how about just sorting #3136

**Comment by EvanPurkhiser** [comment]
Yeah that looks great @fregante
