### ISSUE TITLE
Convert PR to Draft button missing in PR

### ISSUE THREAD

**Issue by glensc** [sindresorhus/refined-github#3076]
https://github.blog/changelog/2020-04-08-convert-pull-request-to-draft/

Seems when this plugin enabled, the "convert to draft" disappears from side bar. It should be between reviewers and assignees.

**Comment by fregante** [comment]
Are you using the latest version? I see it:

<img width="246" alt="draft" src="https://user-images.githubusercontent.com/1402241/81501330-1e781980-92d8-11ea-9ea2-2e0fc69528b1.png">

**Comment by yakov116** [comment]
I see it when there is a a child element 

Maybe this?
https://github.com/sindresorhus/refined-github/blob/d092435a8016b312b2ed55e78ab57bb3d95be742/source/features/clean-sidebar.tsx#L38-L41


|Ext Enabled |Disabled|
|---	|---	|
|![image](https://user-images.githubusercontent.com/16872793/81501468-8ca3e880-92a6-11ea-8522-324c1eb55ab9.png)|![image](https://user-images.githubusercontent.com/16872793/81501491-a34a3f80-92a6-11ea-96e8-9ad82a493afb.png)|




But here I Do 
![image](https://user-images.githubusercontent.com/16872793/81501448-6bdb9300-92a6-11ea-801b-6393d6cb1162.png)

**Comment by alex0811** [comment]
seems this feature only appears in public repository

**Comment by dev-sareno** [comment]
It would be great if the `Convert to draft` button is highlighted (like a hyperlink in blue color)
