### ISSUE TITLE
Repo page completely broken when new feature preview enabled

### ISSUE THREAD

**Issue by SUPERCILEX** [sindresorhus/refined-github#3081]
Enable this feature preview: https://gist.github.com/broccolini/2245234ac3a4936049e8ffc13f376986. Go to a [repo front page](https://github.com/sindresorhus/refined-github) and you'll see a brief flash of content before it's all wiped out.

**Comment by isaacrlevin** [comment]
The New GitHub UI causes tons of errors in console, here is the UI update

more-dropdown → TypeError: Cannot read property 'append' of null
edit-readme → TypeError: Cannot read property 'textContent' of null
repo-age → TypeError: Cannot read property 'append' of null
edit-files-faster → TypeError: Cannot read property 'textContent' of null
latest-tag-button → TypeError: Cannot read property 'textContent' of null

**Comment by auscompgeek** [comment]
Interestingly, I haven't seen RGH wipe out the page completely. (Firefox 76, Refined GitHub 20.5.27)

The console errors I get are different too:

- more-dropdown → TypeError: "parent is null"
- edit-readme → TypeError: "The element wasn’t found, the selector needs to be updated."
- edit-files-faster → TypeError: "The element wasn’t found, the selector needs to be updated."
- repo-age → TypeError: "commitInfo is undefined"

latest-tag-button seems to work for me.

**Comment by fregante** [comment]
`more-dropdown` is kind of a problem now since the new design has an automatic "overflow" hamburger menu:

<img width="588" alt="" src="https://user-images.githubusercontent.com/1402241/84262936-d50d2b00-ab1e-11ea-82da-85002d1e62f1.png">

The obvious solution is to add all those elements to the navigation and let them naturally flow into the overflow, but that's noisy. Until now we added items to the dropdown without much trouble, since it's "out of the way", but this change forces us to reconsider it.

**Comment by aminya** [comment]
I get similar errors in the new design:
![image](https://user-images.githubusercontent.com/16418197/84381779-1fd68380-abaf-11ea-8dd3-49bcfff96519.png)

**Comment by fregante** [comment]
Sizes need to be updated too:

<img width="338" alt="" src="https://user-images.githubusercontent.com/1402241/84260284-13541b80-ab1a-11ea-925f-0db5f75b20d2.png">

I think it's only a matter of adding `if branchselector.is('.btn-sm'), mybutton.classList.add('btn-sm')`

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/3205#issuecomment-641926371_

**Comment by FloEdelmann** [comment]
@fregante I think we can close this issue now, as all the reported console errors (and more that was noticed) are fixed now. The only problems left have separate issues (#3204 and #3215).

If more problems come up, they should get separate issues anyway to track them more efficiently.

**Comment by fregante** [comment]
Thanks for fixing these, Flo!

**Comment by isaacrlevin** [comment]
Awesome, now push it to the extension store ;)

**Comment by yakov116** [comment]
It was, 3 hours ago. https://github.com/sindresorhus/refined-github/releases/tag/20.6.18
You just need to wait for chrome to release

**Comment by sridhar-vadlamani-ck** [comment]
> It was, 3 hours ago. https://github.com/sindresorhus/refined-github/releases/tag/20.6.18
> You just need to wait for chrome to release

How long does that usually take?

**Comment by yakov116** [comment]
> How long does that usually take?

Depends on their mood. Anywhere from an hour to a week.

**Comment by RussKie** [comment]
Still seeing issues opening this page https://github.com/dotnet/winforms/pull/3525/files in in v20.6.25
```
refined-github.js:2841 ❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'append' of null
    at appendBefore (refined-github.js:3195)
    at createDropdown (refined-github.js:3209)
    at more_dropdown_init (refined-github.js:3222)
    at async runFeature (refined-github.js:2863)
    at async setupPageLoad (refined-github.js:2871) 
```

I have disabled all other extensions to be sure too.

**Comment by busches** [comment]
> Still seeing issues opening this page [#3525 (files)](https://github.com/dotnet/winforms/pull/3525/files) in in v20.6.25
> 
> ```
> refined-github.js:2841 ❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'append' of null
>     at appendBefore (refined-github.js:3195)
>     at createDropdown (refined-github.js:3209)
>     at more_dropdown_init (refined-github.js:3222)
>     at async runFeature (refined-github.js:2863)
>     at async setupPageLoad (refined-github.js:2871) 
> ```
> 
> I have disabled all other extensions to be sure too.

This is being tracked here: https://github.com/sindresorhus/refined-github/issues/3215
