### ISSUE TITLE
Make pull request number a link in "Files changed"

### ISSUE THREAD

**Issue by koppor** [sindresorhus/refined-github#3082]
Example URL: https://github.com/JabRef/jabref/pull/6240/files/870ce0da24cdc28a7e84820e7662df61e7178291..85290507c5f381371caa1e2b693a0dc2d9894fb5

In the big bold heading, there is the pull request number. I am used to click the big fat things on web pages. However, I have to go to "Conversion" to go to the "normal" pull request view (https://github.com/JabRef/jabref/pull/6240 in the example case). It would be great if the pull request number in the heading would be linked to conversion.

![grafik](https://user-images.githubusercontent.com/1366654/81638275-e75d5180-9418-11ea-9277-a5a635ea9a15.png)

**Comment by fregante** [comment]
> However, I have to go to "Conversion" to go to the "normal" pull request view

Yes, that’s enough and it’s big button too. If we make that number clickable people can’t select it easily anymore… just to add one more button that does something that’s already possible. Not worth it

**Comment by koppor** [comment]
Different workflows, I always copied the link from the URL field 😅.

**Comment by fregante** [comment]
We'll have to pass on this feature because of https://github.com/sindresorhus/refined-github/issues/3082#issuecomment-627191258
