### ISSUE TITLE
Explore using `selector-observer` to run features

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3084]
GitHub uses [selector-observer](https://github.com/josh/selector-observer) to enable logic on simple classes, which is why adding or removing classes like `.js-fit-content` will enable or disable their features.

It's built around `MutationObserver` with various optimizations on top of it. Its performance might not be _super_ (https://bugzilla.mozilla.org/show_bug.cgi?id=1422522) but it seems to work well enough for GitHub.

It's worth investigating if anyone has time, it would elegantly solve issues around dynamic content and all the specific listeners we have. 

I think `observe` calls would go inside each feature’s `init`, which could only be called once.

**Comment by fregante** [comment]
Many of the bugs currently open can be fixed with this, so I really hope that someone can figure it out.

**Comment by fregante** [comment]
Let’s avoid any more conversions to selector-observer for the time being. There are some outstanding drawbacks we need to solve first. For example:

- it always automatically waits for domready, so it’s not as fast as one using element-ready.
- sometimes it should be disabled on `deinit`, like for that recent feature to remove labels. 
- some features should only be applied when the elements are visible (I have some code about this in the first related PR)

We should find a common, efficient way to cover all of these issues. Either via code or via documentation (e.g. “if feature requires X, then you must use deinit”)

**Comment by fregante** [comment]
cc @yakov116 @kidonng

**Comment by kidonng** [comment]
> * it always automatically waits for domready, so it’s not as fast as one using element-ready.

I don't have a strong feeling about this so I can't say anything.

> * sometimes it should be disabled on `deinit`, like for that recent feature to remove labels.

I think most of the time this could be solved with carefully chosen selectors.

> * some features should only be applied when the elements are visible (I have some code about this in the first related PR)

Are you referring to [this one](https://github.com/sindresorhus/refined-github/pull/3091/files#diff-97fdf073abb60110f8e6719ed5280bd0)?

---

I'm not familiar with all existing and pending usage of selector-observer, but I would say it is definitely useful for dealing with ajaxed components. For sure we don't want to convert every feature into using it, but I think our original intention is to fix bugs which will be hard/verbose without it. Take my two open PR converting into selector-obsever as an example, I think there's a good reason to use it.
Existing usage like `linkify-user-edit-history-popup` and `remove-label-faster` may be rewritten to reduce the usage of selector-observer (judge from a glance, correct me if I'm wrong).

**Comment by fregante** [comment]
> I think most of the time this could be solved with carefully chosen selectors.

That may be right. Do you want to try reverting https://github.com/sindresorhus/refined-github/pull/3476?



> Are you referring to [this one](https://github.com/sindresorhus/refined-github/pull/3091/files#diff-97fdf073abb60110f8e6719ed5280bd0)

Yes, I used that function for a couple of features. But yes, it's probably not useful in many cases.

It doesn't need to be rewritten, it worked well, it only lacked `:not(.rgh-class)` but I did not have time to investigate back then. If anything, https://github.com/sindresorhus/refined-github/pull/3091 should be used instead of https://github.com/sindresorhus/refined-github/pull/3516. Notice how the observer looks for the specific elements instead using `select.all` again inside.

> In short, if a feature works well, we don't need to use selector-observer

Until we sort this out, yes. No need to rewrite anything at the moment.

For the future, this is a little more complicated: `selector-observer` makes code declarative, so in a perfect world we'd almost always prefer it.

What do you think about this?

> ## Always use `selector-observer` when...
> 
> ... the feature affects a number of elements across the page, e.g. `parse-backticks` can find elements to modify anywhere on the page. `element-ready` would not have any advantages here.
> 
> ## Always use `element-ready` when...
> 
> ... the feature only affects a specific part of the page and it's not in an ajaxed "hot zone" (e.g. conversation header and sidebar, and list of files)
> 
> ## For the rest of them...
> 
> ... we need to evaluate whether it's worth giving up "faster features" (https://github.com/sindresorhus/refined-github/issues/2671) in exchange for reliability.


> Existing usage like linkify-user-edit-history-popup and remove-label-faster may be rewritten to reduce the usage of selector-observer (judge from a glance, correct me if I'm wrong).

I think those are exactly the features that are fine with `selector-observer`

- `linkify-user-edit-history-popup` needs complicated listeners for the popup, and doesn't benefit from `element-ready` because it appears well after `dom-ready`
- `remove-label-faster` affects the sidebar, which is:
	- a ajaxed "hot zone"
	- loaded last on the page, so `element-ready` wouldn't save a lot of FOUC

**Comment by fregante** [comment]
I'll try rewriting that:


"Ajaxed hot-zones" are areas that have nested ajaxed widgets and require a number of listeners and mutation observers to detect changes.

1. Features in ajaxed hot-zones: Always use `selector-observer`
2. Features with many elements across the page: use `select.all`
3. Features with a limited number of elements, e.g. `forked-to` only affects links in the header

**Comment by fregante** [comment]
## Urgent debugging wanted

Is https://github.com/josh/selector-observer/issues/30 a real bug?
Did https://github.com/sindresorhus/refined-github/issues/3527 happen for that reason?
How can we work around it?

Further features and refactoring using `selector-observer` won't be accepted until we know how to avoid this from happening.

cc @kidonng @yakov116 this is why I temporarily closed related PRs.

**Comment by yakov116** [comment]
https://github.com/kylekyle/monitoring what about this? It's actively maintained and it looks like it runs before dom ready too!

**Comment by yakov116** [comment]
@fregante should I try https://github.com/kylekyle/monitoring and play around with it? Or do you want to stick to select-observer?

**Comment by fregante** [comment]
We need to verify those 3 points first, there's no point in changing library if has the same issue (or if the issue doesn't exist)

**Comment by fregante** [comment]
I confirmed the bug and found a workaround:

- if the selector has `:not(.rgh-this-feature)` and we add the class right away, `selector-observer` will no longer call the `add` method because the original selector no longer applies. This avoids the loop.

We almost always do that already, but #3517 didn't because it didn't seem necessary.

- I'll open the previously-locked PRs
- @kidonng you can resubmit #3517 with the workaround described
- @yakov116 if you want to explore Monitoring anyway, try it out on `linkify-code`, which is the heaviest feature making use of `selector-observer`

**Comment by fregante** [comment]
@yakov116 if you also want to look into any other features that use `selector-observer` but don't have this class, please send a PR for that
