### ISSUE TITLE
Show the earliest tag after a merged PR

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3088]
1. Visit a merged PR, like https://github.com/fregante/github-url-detection/pull/2
2. **_Has this PR been published/tagged yet?_**

Currently, the fastest way to do this:

1. Open the More menu
1. Visit Commits
1. Look for the current PR in the list and figure it out

---

If you open the commit itself, GitHub will show both the branch and the tag that commit appears in, for example: https://github.com/fregante/github-url-detection/commit/329d756f66df44cfb97dbe8fa84c1cb3bcbe8e03

<img width="348" alt="" src="https://user-images.githubusercontent.com/1402241/81814545-35fa1100-9529-11ea-9e32-96fb90f457fd.png">

We could show a similar information on the PR event list:

<img width="701" alt="" src="https://user-images.githubusercontent.com/1402241/81814631-4e6a2b80-9529-11ea-917f-5a3b1aca7ec4.png">

**Comment by yakov116** [comment]
If someone wants to send A PR
I figured out how github gets the info

Get the merge commit from the DOM
Example url would look like https://github.com/fregante/github-url-detection/branch_commits/329d756
```js
const getAssociatedTag = async (mergeCommit: string): Promise<string | undefined> => {
	const tags = await fetchDom(`/${getRepoURL()}/branch_commits/${mergeCommit}`, 'ul.branches-tag-list');
	if (!tags) {
		return undefined;
	}

	const firstAssociatedTag = select.last('a[href]', tags)!.textContent!;
	return firstAssociatedTag;
};
example URL https://github.com/fregante/github-url-detection/branch_commits/329d756
```
To get the time it was tagged
```js
const getTagDate = async (firstAssociatedTag: string): Promise<Date> => {
	const {repository} = await api.v4(`
		repository(${getRepoGQL()}) {
			refs(refPrefix: "refs/tags/", query: "${firstAssociatedTag}", last: 1) {
				nodes {
					target {
						... on Tag {
							tagger {
								date
							}
						}
					}
				}
			}
		}
	`);

	return repository.refs.nodes[0].target.tagger.date;
};
```

**Comment by yakov116** [comment]
@fregante I think here.
![image](https://user-images.githubusercontent.com/16872793/81840162-959af100-9516-11ea-99a7-2c982836b524.png)

Since sometimes it can be really long PR and many ref and it would get lost.

**Comment by fregante** [comment]
> I think here.
> ![image](https://user-images.githubusercontent.com/16872793/81840162-959af100-9516-11ea-99a7-2c982836b524.png)

Yeah that would also avoid the API call.

The code looks simple, however the PR header is dynamic. Can you try using #3084 like here? 

https://github.com/sindresorhus/refined-github/blob/ed1708daa89189937ad8411e6ecc5de719ce55b1/source/features/linkify-code.tsx#L22-L26
