### ISSUE TITLE
Remove Projects (0) from repo navigation

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#309]
Since GitHub has introduced projects there is this Projects tab on every repo. I am yet to see a repository using them. So I'd suggest removing the tab if there are 0 projects. It would reduce clutter and you will only see it when a repository is actually using projects.

That said I understand why GitHub did it like that - showing it for every repository even though nobody is using it at first - they want people to know about the feature, to open the tab and see the intro copy there. However I think users of Refined GitHub are heavy GitHub users and already know about it.

Implementation should be fairly easy as GitHub already show the number of projects in the tab button.

**Comment by sindresorhus** [comment]
👍

**Comment by paulmolluzzo** [comment]
If we take out the navigation then how else will people discover Projects? We'd be kneecapping the discovery of a new feature that people worked hard on. 😢

**Comment by sindresorhus** [comment]
@paulmolluzzo We don't have to do it right now, but eventually I'd like to see it gone when unused.

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo We don't have to do it right now, but eventually I'd like to see it gone when unused.

OK, I'm just offering a counterpoint. Again, I don't want to take away the opportunity for all the GH people that worked on this feature to have their work gain traction.

**Comment by sindresorhus** [comment]
@paulmolluzzo It's a good point. I just assumed everyone knew about it from the blog post, but I'm sure that's only a small portion of users.

**Comment by hkdobrev** [comment]
@paulmolluzzo I get your argument, but I don't think we're actually preventing people to know about it. Here are the two use cases I think about:

1. **People using the extension already**: They are certainly heavy users of GitHub, they might have even read the blog post or watched the GitHub Universe keynote. They certainly look at GitHub repositories at least a few days a week. I assume they already know about the projects feature, because they are used to how the tabs are ordered there. They saw that Refined GitHub has removed Pulse and added Releases. So they have also noticed the Projects tab and clicked it to look around. If they have started using it, this change would not affect the repositories where they already have projects.
2. **People who are yet to install the extension**: If they are heavy GitHub users arguments for 1. apply for them as well. If they are new to GitHub they would spend quite some time dealing with GitHub and repository pages before finding and installing Refined GitHub extension. I wouldn't entertain the idea that they would discover GitHub through the extension or they'd install it in the first few days of GitHub usage. I'm quite certain that most users of the extension would have become GitHub regulars before installing any GitHub extension and especially one such as Refined GitHub which changes a lot of things in a lot of different places.

In both cases however the thing which actually concerns me is that even if people know about projects would not be easily able to create a new project. They could either guess the URL, disable the extension to create the project, copy the URL from another repo with projects, but none of these are straightforward.  Perhaps we shouldn't do this change or at least should add a button for adding a new project. I haven't found a good solution to this yet.

I just know that I won't use the projects feature for the foreseeable future - excluding the cases where someone is using them on an open-source repository I'm interacting with, but that case won't be affected. So I wanted to suggest this change and see what others think about it. I'm glad there's a discussion :)

**Comment by sindresorhus** [comment]
If we decide to go for this, we could simply add a button in the Settings page that points to `https://github.com/sindresorhus/refined-github/projects/new`. That's really where GitHub should have put the button, instead of littering the main nav with something most repos won't use.

**Comment by hkdobrev** [comment]
FWIW this is the first repo I've seen to use projects and I admit their use case is quite nice: https://github.com/algolia/instantsearch.js/projects

I've used Trello boards almost since the launch of Trello and I'm a big fan of such layouts, but what I don't understand is why GitHub launched this in addition to milestones instead of upgrading milestones to that.

\</rant>

**Comment by superkhau** [comment]
I think user should be allowed to disable the projects tab just like the Wiki tab. I don't mind if it's left it on by default, but allow users to turn it off like you already do for wiki/issues, etc.

**Comment by hkdobrev** [comment]
> allow users to turn it off like you already do for wiki/issues, etc.

To clarify disabling of wiki and issues is functionality provided by GitHub. This is just a browser extension changing the DOM on the page.

**Comment by superkhau** [comment]
@hkdobrev Sorry, you're right, I'm posting in the wrong repo. ;)

**Comment by hkdobrev** [comment]
GitHub added a setting to disable projects just like issues and wiki: https://github.com/blog/2339-disabling-projects-on-repositories 🎉

**Comment by paulmolluzzo** [comment]
So we can close this issue then?

**Comment by sindresorhus** [comment]
@paulmolluzzo No, it only works if everyone disables it if they don't use it, which very few will.

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo No, it only works if everyone disables it if they don't use it, which very few will.
> 
> I just don't want unnecessary noise in general, and maybe 1 out of 1000 repos I visit actually use `Projects`.

@sindresorhus Fair point and you're probably right that most people won't bother disabling it.

**Comment by sindresorhus** [comment]
I'm marking this issue as pull request welcome. We can add a `Create Project` button in the the Settings where you can turn off `Projects`.

**Comment by paulmolluzzo** [comment]
@sindresorhus you think we need to remove the `good for beginner` label? I think this is still pretty accessible for a beginner and we have a lot of info in this issue for someone to use in the solution. Just a 💡 .

**Comment by sindresorhus** [comment]
I guess
