### ISSUE TITLE
Mute dependabot notifications in dashboard

### ISSUE THREAD

**Issue by tjrgg** [sindresorhus/refined-github#3090]
Similar to how dependabot PRs and commits are muted in the issue list, I'd love to see a similar approach used for them in the dashboard for repositories I watch. Personally, I'm not a fan of the spam created by dependabot, so it'd be cool if these could either be hidden or muted.

For clarity, when I say dashboard, I'm referring to the feed that most users see at https://github.com when logged in.

**Comment by fregante** [comment]
Can you show an screenshot? This should already be covered by `hide-useless-newsfeed-events`, did you disable it?

**Comment by Hornet171717** [comment]
Tell me what do think it’s worth 



Sent from my iPhone

**Comment by tjrgg** [comment]
@fregante I think the hide-useless option you referred to hides more than I want it to, so I did disable it. I want to see fork and follower information. Perhaps this could be split from that?

**Comment by Hornet171717** [comment]
You think you going shut me up

**Comment by fregante** [comment]
> Perhaps this could be split from that?

The first one is CSS only, what you're suggesting requires much more effort to detect and hide.

Plus we can't have a feature that hides *everything but dependabot commits* and then another one that *hides dependabot commits.*  I hope you see how that sounds silly, especially when considering that this change requires a lot more code.

I suggest implementing this with a userscript

**Comment by fregante** [comment]
You can try suggesting it to https://github.com/muan/github-dashboard
