### ISSUE TITLE
Add a 'new gist' button to the GitHub Gist home page.

### ISSUE THREAD

**Issue by HarshKapadia2** [sindresorhus/refined-github#3098]
1. Add a green `new gist` button on top of the page (beside the starred tab). The current `+` sign at the top right of the page is not intuitive at all...

2. URL for where the feature should appear: https://gist.github.com/HarshKapadia2 (GitHub Gist home page.)

**Comment by fregante** [comment]
As you said, the button is there:
<img width="1139" alt="" src="https://user-images.githubusercontent.com/1402241/82132172-2c003880-97dd-11ea-8f59-9435b0e03f7b.png">

And I'd say that's enough; it's the same position as GitHub’s "New..." menu

<img width="238" alt="" src="https://user-images.githubusercontent.com/1402241/82132187-54883280-97dd-11ea-8248-641d74d55381.png">

**Comment by HarshKapadia2** [comment]
Agreed, but the new repo and new gist buttons are really not intuitive. People usually ask or have to really search for those buttons.
I was going to raise an issue for the GitHub button as well, but I though that I should start with the GitHub Gist one first...

So my issue is that the `+` buttons are really too much in the corner, too small, inconvenient and not that intuitive for a user.

The solution could be to add a green button with the same options as the `+` button, but placed in much better place that makes it easy to access.

**Comment by fregante** [comment]
We'll have to pass on this feature. 

However you can add it via userscript with this line:

```js
document
	.querySelector('.Header-link[aria-label^="Create new"]')
	.classList.add('btn', 'btn-primary')
```



<img width="184" alt="" src="https://user-images.githubusercontent.com/1402241/82148954-bbe1c900-9855-11ea-931c-9b2e6174f1d7.png">
