### ISSUE TITLE
Bugs tab shows a wrong number of issues

### ISSUE THREAD

**Issue by Androz2091** [sindresorhus/refined-github#3099]
Hello,
The number of bugs on the bugs tab remains at 1 even though I closed all the issues... I tried to deactivate and then reactivate Refined Github, to clear my cache, to reload the page many times, nothing worked.

![Capture d’écran 2020-05-17 à 10 32 12](https://user-images.githubusercontent.com/42497995/82139670-efa6f980-9829-11ea-9f94-e8da60f97b26.png)

**Comment by fregante** [comment]
Which cache? Did you click Clear Cache in the Refined GitHub’s options page?

**Comment by Androz2091** [comment]
Um, no, I meant I cleared the cache using the "Empty Cache and Reload Hard" button.

**Comment by fregante** [comment]
That doesn't empty Refined GitHub’s cache. For that feature, the cache lasts 30 minutes

**Comment by Androz2091** [comment]
Oh all right.
