### ISSUE TITLE
The review "red X" icon is overly scary

### ISSUE THREAD

**Issue by TehShrike** [sindresorhus/refined-github#310]
https://twitter.com/yaypie/status/776888659492483072

How would people feel about replacing it with something more neutral - perhaps a gray circle, like slicknet suggested?

**Comment by hkdobrev** [comment]
There's a lot of things I don't like with the new review features, but on this I'm more inclined to say it's useful. A neat thing for me though would be to gray it out once the same person has approved the PR.

**Comment by TehShrike** [comment]
That happens already - when the user approves the review, the icon at the bottom of the pull request changes from a scary red X to a green circle with a checkmark.

I am only suggesting that the scary "unapproved" red X be made less angry and aggressive-looking.

**Comment by hkdobrev** [comment]
@TehShrike But it doesn't mark the original review as _outdated_ or taken care of. When multiple people are reviewing it's nice to see that a review of one person has later being approved. The notation in the bottom just shows which people approved and which don't and whether all people approved. But when looking at specific reviews in the timeline you don't know if that's taken care of.

**Comment by TehShrike** [comment]
Sure, that's fair.  I'd be in favor of that change too.

I only meant to bring up the red X to consider changing it to something less aggressive when it was displayed, but I don't know if it's worth opening a second issue to discuss these two things separately.

**Comment by hkdobrev** [comment]
My comments here are less valid/needed now as GitHub now collapses review comments when the line which was commented on has been updated just like they've been doing before the new code review features. They've also introduced the ability to [dismiss reviews if needed](https://github.com/blog/2265-dismissing-reviews-on-pull-requests). So my problems with the code reviews are very much addressed.

On the original request of this issue I'm neutral as I don't really need it, but won't be a problem for me either.

**Comment by hkdobrev** [comment]
Anyone else wants this? I don't think we should do this with all of the recent developments on PR reviews.

**Comment by busches** [comment]
@hkdobrev agree it's no longer needed with the improvements they've pushed to code reviews.
