### ISSUE TITLE
Project tabs don't fit on their line

### ISSUE THREAD

**Issue by yallie** [sindresorhus/refined-github#3102]
Page url: https://github.com/sindresorhus/refined-github

Screenshot with refined-github enabled:
![image](https://user-images.githubusercontent.com/672878/82202229-4dab0e00-990a-11ea-9e2f-96ca35873277.png)

Screenshot with refined-github disabled:
![image](https://user-images.githubusercontent.com/672878/82201948-ce1d3f00-9909-11ea-865a-bb79db31c7af.png)

**Comment by notlmn** [comment]
That's ZenHub extension flexing out the `.repo-nav` element, causing elements we add there to flow down.

![image](https://user-images.githubusercontent.com/37769974/82204748-0ed58200-9923-11ea-9c54-fb3c5ead94d0.png)

This is more of a compatibility issue between ZenHub and this extension than a bug from this issue.

----------------

Also @fregante WDYT about adding "more dropdown" and "releases tab" inside the `ul` as opposed to beside it?

**Comment by yallie** [comment]
>That's ZenHub extension flexing out the .repo-nav element, causing elements we add there to flow down.

Oh, I thought I've disabled all github-related extensions before posting this issue.  
I forgot about ZenHub, indeed. Thank you!

**Comment by fregante** [comment]
> Also @fregante WDYT about adding "more dropdown" and "releases tab" inside the `ul` as opposed to beside it?

Sounds good, GitHub must have changed the DOM.

Also I suggest reporting this to ZenHub. Why are they setting `flex` on the whole element? Doesn't look necessary.

**Comment by notlmn** [comment]
> > That's ZenHub extension flexing out the .repo-nav element, causing elements we add there to flow down.
> 
> Oh, I thought I've disabled all github-related extensions before posting this issue.
> I forgot about ZenHub, indeed. Thank you!

That did help us find this issue where the elements we add now appear after the settings tab. Sending in a fix for this.

![image](https://user-images.githubusercontent.com/37769974/82222062-6a613900-993e-11ea-96d1-0355174de1bb.png)

**Comment by fregante** [comment]
This also explains why I’ve been seeing the Releases being added AFTER the settings tab. That’s not right
