### ISSUE TITLE
Show next scheduled time of a GitHub Action

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#3104]
GitHub shows a list of historical runs for a specific deployment in order. Some of these Actions could have been triggered from a scheduled run, with cron. But we do not know when the next scheduled run is going to be.

We could add an information bar here on the top if there is going to be a scheduled job for that Action and when.

![image](https://user-images.githubusercontent.com/37769974/82209639-39c3d400-992b-11ea-9345-b785ba4b55a8.png)

This feature request is similar to what Travis shows in their cron job settings, like "**Scheduled in 20 hours from now**".

![image](https://user-images.githubusercontent.com/37769974/82209834-93c49980-992b-11ea-908a-7b41d2965855.png)

This can be computed based on the last _scheduled_ run of an Action added with the schedule values for that Action.

Example: https://github.com/notlmn/copy-as-markdown/actions?query=workflow%3ADeployment

**Comment by fregante** [comment]
GitHub Actions needs so much work still...

This suggestion sounds good, maybe we can display it here:

<img width="301" alt="" src="https://user-images.githubusercontent.com/1402241/82212888-8c919180-9913-11ea-83cc-fd13c7130515.png">

But... we need an API for this, we can't load a YAML parser. Best case scenario GitHub lets us read configs as JSON (?) so we only need a cronjob parser module (I didn't find one)

**Comment by notlmn** [comment]
I tried a bit but couldn't find an API for that, the closest I could find was [listing workflows](https://developer.github.com/v3/actions/workflows/#list-repository-workflows) and [details of a workflow](https://developer.github.com/v3/actions/workflows/#get-a-workflow).

But these are v3, couldn't find anything related to actions or workflows in v4.

/cc @lukehefson

**Comment by fregante** [comment]
Impossible for the time being

**Comment by fregante** [comment]
✅ The YAML regex would be enough to extract it.

💡 The crontab parser doesn't have to be huge. Here's some code I found to parse it and it's only 11KB. It'd have to be reverse-engineered to find out how each part fits into each other and unnecessary code should be dropped: [crontab-parser.zip](https://github.com/sindresorhus/refined-github/files/5273822/crontab-parser.zip)

**Comment by cheap-glitch** [comment]
> 💡 The crontab parser doesn't have to be huge. I found a 11KB implementation but it'd have to be reverse-engineered: [crontab-parser.zip](https://github.com/sindresorhus/refined-github/files/5273822/crontab-parser.zip)

This sounds like an interesting exercise, I'll try my hand at it.

**Comment by fregante** [comment]
If you do send a PR, make sure to drop all unrelated code, like warnings and such. We only need to know when the next date is.

**Comment by cheap-glitch** [comment]
Published https://www.npmjs.com/package/@cheap-glitch/mi-cron if you want to use it for this issue. I wish I could help more with this but I know zilch about Github Actions.

**Comment by fregante** [comment]
Thank you!

To fix this issue, there's little to know about GH Actions, it just needs to:

1. Fetch all (or the visible ones) the [workflows’ YML files](https://github.com/sindresorhus/refined-github/tree/master/.github/workflows) in the most efficient way possible
2. Find the [`cron` line](https://github.com/sindresorhus/refined-github/tree/master/.github/workflows) with regex
3. Parse it and display it on the sidebar of https://github.com/sindresorhus/refined-github/actions, as shown in my mockup:

<img width="301" alt="" src="https://user-images.githubusercontent.com/1402241/82212888-8c919180-9913-11ea-83cc-fd13c7130515.png">

**Comment by cheap-glitch** [comment]
Thanks @fregante for the detailed break up!
Do you have any example(s) of similar feature(s) that can help me get started on this?

**Comment by yakov116** [comment]
@cheap-glitch which part do you need help with.

If you ask me start with a dummy cron (dont fetch the yaml) and then we can work on getting the yaml

**Comment by notlmn** [comment]
> If you ask me start with a dummy cron (dont fetch the yaml) and then we can work on getting the yaml

The last time I worked on this, if I remember it right, we'll have to fetch all yaml files in `.github/workflows` and compare them with entries (of action names) on the actions page, would probably require caching too.

**Comment by fregante** [comment]
Good point. If the filenames aren’t available in the sidebar, then the regex will also have to parse `name:`

**Comment by cheap-glitch** [comment]
> If you ask me start with a dummy cron (dont fetch the yaml) and then we can work on getting the yaml

That was the plan, as I think the fetching part is what's gonna give me the most trouble.
