### ISSUE TITLE
Make milestones a button appear next to Code/Issues/Pull Requests

### ISSUE THREAD

**Issue by jchannon** [sindresorhus/refined-github#311]
I feel Milestones should be a top level link not hidden under Pull Requests.

Could this plugin make that happen?

**Comment by sindresorhus** [comment]
Doesn't really make sense to me. It's related to Issues/PRs, so available under those tabs. I don't think it's important enough to get to that page that it deserves its own repo-wide tab. Let's see what others think.

**Comment by sindresorhus** [comment]
// @hkdobrev @paulmolluzzo @jacobbearden

**Comment by jacobbearden** [comment]
I don't think they're significant enough to warrant their own tab. Plus the tab list is already a little crowded.

**Comment by hkdobrev** [comment]
Most repositories don't use milestones and so I don't think this would be much useful to most people (hence my suggestion of #421). Also, milestones are not accessible in the DOM of the main repo page so we won't be able to check if the repo is using milestones from there like we do with counting releases and cache it. I think a good addition was #375 which was strangely missing from the UI.

Closing this for now, we could re-open if there's more support for it.
