### ISSUE TITLE
Add indicator when a line in a commit message exceeds 72 characters

### ISSUE THREAD

**Issue by ashughes** [sindresorhus/refined-github#3112]
It would be really helpful if RGH could assist in managing the [recommended 72 character line limit on git commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html). Similar to [suggest-commit-title-limit](https://github.com/sindresorhus/refined-github/blob/058739be808589610608f3383edff3087625ddf4/source/features/suggest-commit-title-limit.tsx), this wouldn't prevent a user from typing a line that is over 72 characters, but would warn them if they do.

**This is how I'm imagining it would work:**
For each line of text in the commit description, characters after 72 are highlighted in color (red/orange/yellow?) as a visual indicator that this line has exceeded 72 characters. If the user chooses, they can then wrap the line where desired.

Alternatively (or as a separate feature) RGH could automatically wrap the text at 72 characters, but not *force* the line to be 72 characters. This would still allow the user to backspace to undo the automatic wrapping if they don't want that particular line to wrap at 72 characters. This is similar to how `vim` works when used with `git commit`.

This would affect all locations where a commit message is written on GitHub. This is primarily PR merges, but also committing changes to individual files or any other place a commit can be made.

**Comment by fregante** [comment]
It's there already: https://github.com/sindresorhus/refined-github/blob/master/source/features/suggest-commit-title-limit.tsx

**Comment by fregante** [comment]
> Similar to [suggest-commit-title-limit](https://github.com/sindresorhus/refined-github/blob/058739be808589610608f3383edff3087625ddf4/source/features/suggest-commit-title-limit.tsx), this wouldn't prevent a user from typing a line that is over 72 characters, but would warn them if they do.

I don't understand the difference; that feature already only _warns_ the user by changing the field’s color.

**Comment by fregante** [comment]
Like https://github.com/sindresorhus/refined-github/issues/2944 showed, people don't like to be limited.

It's a good idea to keep a short **title** simply because the title needs to be _scannable_ and appear in one line. This doesn't apply to the **commit message.**

Manual wrapping is counterproductive to anyone with monitors that can display more than 80 columns

**Comment by fregante** [comment]
> Manual wrapping is counterproductive to anyone with monitors that can display more than 80 columns

This is excellently demonstrated by your own link, where pre-formatted 72-chars become scrollable whereas the _regular, auto-wrapped_ content just fills the page:

![](https://user-images.githubusercontent.com/1402241/82453200-84bb2400-9ab0-11ea-8434-6f488439d6af.gif)

**Comment by ashughes** [comment]
I'm not suggesting that this should _force_ users to adhere to a 72 character line width, but rather to make it easier to detect and adhere to it if you prefer. This is a fairly common practice and is the default behavior when using `vim` with `git commit`. Here's another link about writing git commit messages that is used as a reference for many: https://chris.beams.io/posts/git-commit/#wrap-72

I definitely understand your point about wrapping based on the screen width. However, I often use `git` in a terminal that spans the full width of my monitor and I don't want the commit messages to span the full width when I run `git log` as it makes them extremely difficult to read.

It looks like there's also a good discussion about this at https://github.com/desktop/desktop/issues/62.

**Comment by fregante** [comment]
There's no super-easy way to detect where the text wraps in the browser, especially in textareas. The closest thing I can think of is to calculate the content height (via the `fit-textareas` feature) and compare it to the amount of `\n` characters, but even then the message would be _"Your message is being soft-wrapped **somewhere**, but who knows on which line"

Additionally I don't think it's particularly [useful for most people](https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382), so I'll close this for now

**Comment by ashughes** [comment]
What about doing something like [this suggestion](https://github.com/desktop/desktop/issues/62#issuecomment-373916443):
> My 2 cents, line length indicator would be enough. Possibly faint grey to give the impression that it's a guide and not necessarily a hard rule. On hard-wrapping, I find it idealistic ... in the sense that not everything can be hard-wrapped e.g. a long URL.

I don't know very much about what's possible for RGH to detect or even modify. I'm an Android developer and don't have much web experience. However, I assume you could get the text, split on `\n` characters, and then count the number of characters in each line. Some ideas:
- Change the color of the characters **after** 72 to be a different color (such as light gray).
- If possible, draw a light gray vertical line at the 72 character mark.

I totally understand the [useful for most people](https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382) stance and I read that before submitting the idea. I don't have any hard statistics to back it up, but I would argue that there's precedent that this **is** useful to most people (as seen by the articles on the topic and the discussion at https://github.com/desktop/desktop/issues/62). I'm definitely not arguing that it's *clearly* useful for most people (it's not clear whether it is or isn't). However, I was trying to suggest it in such a way that it would be *extremely* useful for those who do prefer to wrap at 72 characters, while not being a burden for those who don't.

Just for reference, my current process is to start writing my commit message, copy it into a character counter to find where the first line exceeds 72 characters, insert a `\n`, then copy it back and use the first line as a reference for the rest of the message.

**Comment by fregante** [comment]
> However, I assume you could get the text, split on `\n` characters, and then count the number of characters in each line.

True. I think you could go one step further and automatically add linebreaks once the line reaches 72 characters, but then again this would have to be its own extension or userscript. Probably one already exists

**Comment by marcphilipp** [comment]
If anyone finds such an extension or user script, I'd be very interested! 🙂

**Comment by ashughes** [comment]
I would be as well! At the moment I just copy 72 characters into the textbox and align the text to that. So far I've only accidentally committed the string of 72 characters a couple of times and then had to force-push to fix it. :man_facepalming: I'd really appreciate a better way to visualize it!

**Comment by AuHau** [comment]
Yeah, I have the same problem. My suggestion could be a shortcut/button that would wrap the text just before you want to submit it.
