### ISSUE TITLE
Ability to re-run/trigger a GitHub Actions Workflow

### ISSUE THREAD

**Issue by notlmn** [sindresorhus/refined-github#3113]
### Explanation

GitHub Actions API has the ability to [re-run a specific workflow](https://developer.github.com/v3/actions/workflow-runs/#re-run-a-workflow), but the GitHub UI doesn't have any option to re-run a workflow unless the workflow has some failed jobs inside it.

(Well, GitHub doesn't exactly let you re-run the entire workflow, only specific failed jobs inside it, which is no exposed in their API).

The feature adds a button that should:
- be _available_ on workflow ([example](https://github.com/sindresorhus/refined-github/actions/runs/109721204)), preferably beside "create status badge" dropdown.
- be _enabled_ if the workflow is is _not running_.
- be _disabled_ if the workflow is _already running_.

#### Re-running workflows

![image](https://user-images.githubusercontent.com/37769974/82413556-30557b80-9a93-11ea-94bb-11ba7edd01cd.png)

#### Triggering new workflows

![image](https://user-images.githubusercontent.com/37769974/82413836-b245a480-9a93-11ea-9501-d046c381647b.png)

### How can this be used?

- Testing pull requests.
- Triggering manual builds for publishing extensions, that we used to do on Travis for hotfixes.

People do seem to need this for their own reasons ([GH forum](https://github.community/t5/forums/searchpage/tab/message?q=%22actions%22%20%22manual%22)).

### Existing alternatives

- Something that uses [repository dispatch events](https://help.github.com/en/actions/reference/events-that-trigger-workflows#external-events-repository_dispatch).
  - https://goobar.io/2019/12/07/manually-trigger-a-github-actions-workflow/
  - https://medium.com/@christinavhastenrath/how-to-run-github-actions-manually-afebbe77d325
- Something that uses in-UI tricks to trigger events.
  - https://dev.to/s_abderemane/manual-trigger-with-github-actions-279e
- Using empty dummy commits.

These "tricks" work, but they do not work on specific run that we want to re-run or require adding new actions to handle them.

### Things I'm not sure about

There are basically two "types" or "ways" of running a workflow (if you could call them that)

1. "re-running" an existing workflow (which is previously failed or has passed), from first screenshot above
2. "creating" a new workflow run, that is done on a per-branch basis, this is related to Travis' "Trigger Build", second screenshot above.

Option 1 can be easily done, now sure how we can tackle option 2 (which also may not be possible).

**Comment by fregante** [comment]
This is impossible, you can’t run random workflows like that, they have to be pre-setup with those specific listeners. 

The only thing possible would be if you’re referring to running OUR ci, not as a feature of refined GitHub

**Comment by notlmn** [comment]
> This is impossible, you can’t run random workflows like that, they have to be pre-setup with those specific listeners.

I'm assuming by me saying _"creating a new workflow run"_ you are thinking of creating new workflow file, with a custom event, jobs and stuff. Yes, that's impossible.

What I'm referring to is a way to trigger a workflow is already configured by the user in the repo, let's say like "Deployment" which they would want to trigger on a specific branch. Feels like I'm explaining Travis' "Trigger Build" feature, but for a specific workflow that the user already has in their repo.

I understand that this might not be possible, but was just brainstorming that idea as it is similar to my actual feature request being able to re-run an already run workflow ([example](https://github.com/sindresorhus/refined-github/actions/runs/109721204)), using the API GitHub provides.

--------------

> The only thing possible would be if you’re referring to running OUR ci, not as a feature of refined GitHub.

I'm referring to the feature that is actually possible using GH API be added as a feature of RGH.

**Comment by fregante** [comment]
Indeed that’s not possible. 

A workflow only runs after the events specified in the workflow itself. 

For most repos, where the events are `on: push`, the only way to trigger it is to push a commit, unsurprisingly. That can’t be worked around by us and, as I said, pushing a whole new (empty) commit for this is a no-go. 

Users of each repos can **configure their workflows** to run one of the solutions you suggested, but RGH can’t.

**Comment by fregante** [comment]
... at last officially. Can you try hacking the “Re-run all jobs” to work on any run?

**Comment by notlmn** [comment]
> Can you try hacking the “Re-run all jobs” to work on any run?

There is an API for that, as mentioned above.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/37769974/82521423-4cfdbc00-9b44-11ea-9f7e-677349731844.gif)

-------------------


> Edit: tried, GitHub responds with _"What‽"_

How were you trying to do that?

**Comment by fregante** [comment]
> There is an API for that, as mentioned above.

Like GitHub’s own UI, it only works if the run failed, like in your demo. Otherwise you get a 403

![](https://user-images.githubusercontent.com/1402241/82531429-ae6f5c00-9b3f-11ea-88dd-0deff4a946ba.jpeg)

This is what happens when I try to rerun the latest (successful) workflow run on this repo.

**Comment by fregante** [comment]
> How were you trying to do that?

I found a failed run’s “Re-run all jobs” form, changed its URL to use a different run id, and submitted it. It failed either because their `once` is linked to the run or because the backend has the same limitation: only rerun failed runs.

**Comment by notlmn** [comment]
> or because the backend has the same limitation: only rerun failed runs.

That's a bummer!

**Comment by notlmn** [comment]
https://github.blog/changelog/2020-05-26-github-actions-re-run-successful-jobs/

**Comment by notlmn** [comment]
https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/

**Comment by fregante** [comment]
Awesome! Can you open an issue on your repo to add manual deployment?

**Comment by notlmn** [comment]
> Awesome! Can you open an issue on your repo to add manual deployment?

https://github.com/notlmn/browser-extension-template/issues/32
