### ISSUE TITLE
Add a keyboard shortcut for "Add line comment"

### ISSUE THREAD

**Issue by jbrooksuk** [sindresorhus/refined-github#312]
Since introducing reviews the CMD/Ctrl+Enter shortcut now adds a Review comment, rather than a single line. This would be fine, but we've been used to this shortcut adding a single line comment for years.

**Comment by hkdobrev** [comment]
I see your point, but I'm using the new reviews extensively and the new default is more convenient for me. I use <kbd>Cmd</kbd> + <kbd>Enter</kbd> almost always to start a review and then on subsequent comments I continue using <kbd>Cmd</kbd> + <kbd>Enter</kbd> to add more comments to that review (the default green submit button then changes to "Add a comment to review").

When I do need to add a single comment I either use the mouse or tab navigation to select the "Add a single comment" button. It's a bit frustrating indeed given the old habit we old have, but the new default is quite productive for me with the new reviews.

**Comment by sindresorhus** [comment]
👎 I think reviews as default is good. Very often you start with one comment and then you suddenly find more things to comment on and realize you should have done a review. Better to just do reviews all the time.

**Comment by jbrooksuk** [comment]
Okay, well how about adding a new shortcut to create single-line comments?

**Comment by sindresorhus** [comment]
Sure, that would be useful.

**Comment by hkdobrev** [comment]
@jbrooksuk Could you suggest a concrete keyboard shortcut? Thanks!

**Comment by jbrooksuk** [comment]
Maybe CMD+Shift+Enter?

**Comment by hkdobrev** [comment]
@jbrooksuk Do you think you could work on a PR about this?

**Comment by fwextensions** [comment]
I have a PR open to add a keyboard shortcut for a single comment, but due to the way the event handling is done in public GitHub (it's different in Enterprise GitHub), I don't think a shortcut containing both <kbd>ctrl</kbd> and <kbd>enter</kbd> is going to work.  The PR currently uses <kbd>shift</kbd><kbd>enter</kbd>, which is a little wonky, but is at least somewhat related to <kbd>ctrl</kbd><kbd>enter</kbd>.  But I'm open to suggestions.

**Comment by woidda** [comment]
Why is there no option to change the behavior in https://github.com/settings/accessibility ?

**Comment by fregante** [comment]
@woidda you're commenting on the repo of a browser extension. This feature is now native to GitHub: https://blog.github.com/changelog/2018-07-24-keyboard-shortcut-to-leave-a-single-comment-in-pull-requests-reviews/

For questions about native features, contact GitHub directly.
