### ISSUE TITLE
Wrong avatars on reactions

### ISSUE THREAD

**Issue by Almo7aya** [sindresorhus/refined-github#3120]
This bug happens in any PR or issue reactions when it shows the people who react to something, it always keeps showing the same accounts 

![image](https://user-images.githubusercontent.com/17254073/82555299-d1156b00-9b67-11ea-9b21-40066c2580a2.png)

Starting from user https://github.com/1 and increases the id as the count of the people reacted to the issue increased

![image](https://user-images.githubusercontent.com/17254073/82555809-c7403780-9b68-11ea-8954-c00a7545f6b1.png)

**Comment by yakov116** [comment]
Link?

**Comment by Almo7aya** [comment]
I'm facing it in everywhere 
@yakov116 
![image](https://user-images.githubusercontent.com/17254073/82557035-39b21700-9b6b-11ea-9c09-f78050f237c8.png)

**Comment by yakov116** [comment]
![image](https://user-images.githubusercontent.com/16872793/82557421-b1ffe480-9b39-11ea-84dc-f455ccc3544c.png)

**Comment by Almo7aya** [comment]
How? I disabled the extension and it worked fine

**Comment by yakov116** [comment]
Maybe its another github extension interfering. Did you to disable all other extentions?

**Comment by fregante** [comment]
> I'm facing it in everywhere
> ![image](https://user-images.githubusercontent.com/17254073/82557035-39b21700-9b6b-11ea-9c09-f78050f237c8.png)

You added both reactions so the same avatar appears on both. What do you expect if not this?

![](https://user-images.githubusercontent.com/1402241/82559730-6583cb80-9b70-11ea-8b28-860bea41352e.gif)

**Comment by fregante** [comment]
Something weird is going on for sure though, this can't happen:

> ![image](https://user-images.githubusercontent.com/17254073/82555299-d1156b00-9b67-11ea-9b21-40066c2580a2.png)

It shows that you clicked on the second reaction, but it also shows 1 avatar.
 
> ![image](https://user-images.githubusercontent.com/17254073/82557035-39b21700-9b6b-11ea-9c09-f78050f237c8.png)

Here it shows your avatar… that should never happen. Could it be that your username is causing problems (since it has an uppercase letter)?

**Comment by fregante** [comment]
> How? I disabled the extension and it worked fine

Try disabling _other_ extensions, not Refined GitHub.

**Comment by dwelle** [comment]
I can confirm this happening. Couldn't figure out what extension is interfering (tried disabling each one in turn). Reinstall doesn't work.

Doesn't happen in chrome canary clean install, though, so some interference indeed must be happening.

**Comment by dwelle** [comment]
Ok, I thought this was a crazy idea, but signing out makes it work correctly. Signing in to my account again breaks it.

**Comment by Almo7aya** [comment]
@fregante That isn't my avatar it belongs to the user https://github.com/1 and the avatar changes same as the number of the reactions as you see in the snip there are 2 rocket reaction so the avatar is for user https://github.com/2 same as for the thumps up https://github.com/7

![](https://user-images.githubusercontent.com/17254073/82555809-c7403780-9b68-11ea-8954-c00a7545f6b1.png)

I tried to only enable refined-github in incognito and the bug occurred there

**Comment by webknjaz** [comment]
I was just about to report the same issue (visible @ https://github.com/dephell/dephell/issues/440 for me).

**Comment by webknjaz** [comment]
I copied this from devtools:
```html
<div class="comment-reactions-options rgh-reactions">
          <button class="btn-link reaction-summary-item js-reaction-summary-item tooltipped tooltipped-se tooltipped-multiline user-has-reacted" name="input[content]" type="submit" value="THUMBS_UP unreact" aria-label="webknjaz reacted with thumbs up emoji">
            <g-emoji alias="+1" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png" class="emoji mr-1"><img class="emoji" alt="+1" height="20" width="20" src="https://github.githubassets.com/images/icons/emoji/unicode/1f44d.png"></g-emoji>
            1
          <a href="/1"><img src="/1.png?size=20"></a></button>
      </div>
```

**Comment by webknjaz** [comment]
So it's both avatar and the link that point to `/1`.

**Comment by webknjaz** [comment]
Here's some interesting entries logged in the console:

<img width="677" alt="rf_gh_1" src="https://user-images.githubusercontent.com/578543/82564402-fced1c80-9b78-11ea-89e9-3b232715934a.png">
<img width="677" alt="rf_gh_2" src="https://user-images.githubusercontent.com/578543/82564395-fbbbef80-9b78-11ea-9f50-b3e1f1e1b723.png">

**Comment by webknjaz** [comment]
Just confirmed that in Incognito mode (with only Adblock and Ghostery enabled additionally to Refined GitHub) it points to my profile (and avatar), as expected. Also, I'm logged out in Incognito.

**Comment by webknjaz** [comment]
When I logged in, in Incognito mode, it became broken again.

**Comment by webknjaz** [comment]
By the way, it's Version 81.0.4044.122 (Official Build) (64-bit) @ Gentoo Linux.

**Comment by webknjaz** [comment]
I must admit that I'm a member of EAP so GitHub may have enabled some extra code on my profile.

**Comment by webknjaz** [comment]
So I asked my wife to log in in my browser and in her account, my (and other people's) reactions are visible. I liked https://github.com/sindresorhus/refined-github/issues/3120#issuecomment-632089299 using her account and now that I'm under my account I see weird avatars/profiles shown.

By the way, the tooltip (on mouseover) on those reactions, mentions the correct usernames.

**Comment by webknjaz** [comment]
So I'm inclined to believe that Refined GitHub may rely on some DOM node that is not available for some GitHub accounts in EAP based on the feature flags or something... That's why some people can reproduce it while others can't.

**Comment by dwelle** [comment]
I'm not EAP and it happens to me, too.

**Comment by webknjaz** [comment]
Okay, but the root cause is still the same. You're right that A/B may have hit us. And yes, it only started happening to me a few hours ago too.

**Comment by fregante** [comment]
Can one of you two [add some breakpoints](https://developers.google.com/web/tools/chrome-devtools/javascript/breakpoints#loc) to see where this `1` is coming from?

Maybe this line is using the wrong `aria-label`, but I don't understand why

https://github.com/sindresorhus/refined-github/blob/59ac9213f867b567de219d38564442623add3ba9/source/features/reactions-avatars.tsx#L22

**Comment by anujbiyani** [comment]
@fregante I have the same bug. Here's what happened when I set a breakpoint on that line and checked what that code was doing:
![image](https://user-images.githubusercontent.com/305254/82584464-60f7ec80-9b49-11ea-8312-9b04c375d315.png)

Maybe the `container.getAttribute('aria-label')` no longer returns the user ID starting some A/B test?

**Comment by yakov116** [comment]
Happens by me too. Looks like they are rolling it out

**Comment by yakov116** [comment]
Did some debugging. Github no longer loads who reacted in the aria-label until you hover 😞

**Comment by fregante** [comment]
This kills the feature. 

The alternative is to query the API. The response will not be super light. 

PR welcome to detect situations where the names haven’t yet loaded and **ignore** them for the time being. This will avoid loading the wrong avatar

**Comment by fregante** [comment]
This feature requires a rewrite and it doesn't work as is, possibly doesn't work at all. I'll open a new issue and create a new version.

For now I just made sure that it never loads unrelated avatars.

**Comment by fregante** [comment]
"Fixed" in 20.5.21

**Comment by jef** [comment]
I'm not receiving any avatar now :cry:

![image](https://user-images.githubusercontent.com/12074633/82716689-cd1c4280-9c66-11ea-9750-d58204eb751d.png)

**Comment by fregante** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/3122

The feature is essentially broken by GitHub now and needs to be changed.
