### ISSUE TITLE
"View file" is broken when using RefinedGithub

### ISSUE THREAD

**Issue by FearlessTobi** [sindresorhus/refined-github#3123]
As a reproduction case, click `View file` in the dropdown here:
https://github.com/yuzu-emu/yuzu/pull/3976/files

This causes me to end up on 
https://github.com/yuzu-emu/yuzu/blob/qdarkstyle_fix_prop/dist/qt_themes/qdarkstyle/style.qss whereas it should lead me to 
https://github.com/yuzu-emu/yuzu/blob/ea14af2164934faa0761a88c6236b3652d8cdaea/dist/qt_themes/qdarkstyle/style.qss.

This issue doesn't occur when the plugin is not installed.

**Comment by yakov116** [comment]
@FearlessTobi my fault, it was fixed already and was released.

However it may take a day or 2 for it be published the chrome store.

https://github.com/sindresorhus/refined-github/pull/3111

**Comment by FearlessTobi** [comment]
Thanks for the info and my bad for not checking the PR list beforehand. :D

Thanks for developing this awesome plugin!

**Comment by yakov116** [comment]
@FearlessTobi update the extension. It looks like it published already!

**Comment by fregante** [comment]
Not your fault, I think the issue has been there forever, but I just noticed it when reviewing your PR 😃

**Comment by FearlessTobi** [comment]
I don't want to open a new issue for this and I'm not sure if this fixed already from glancing at the commit history, but "View file" seems to be broken again.

For example here https://github.com/yuzu-emu/yuzu/pull/3953/files#diff-41128cb4d8543fc3dc355acefa28cd61L137, it redirects me to https://github.com/GodKratos/yuzu/src/yuzu/main.cpp whereas it should lead to https://github.com/yuzu-emu/yuzu/blob/60b184377ee15e487e630a3cadc18f3c1b4312b3/src/yuzu/main.cpp.

**Comment by yakov116** [comment]
I know about it I have a fix for it. The issue is that the PR was opened from the default branch. 
I am waiting for after https://github.com/sindresorhus/refined-github/pull/3152
