### ISSUE TITLE
CI Job Status hidden behind commits

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#3124]
open a commit stream which contains greyed-out commits, like

![grafik](https://user-images.githubusercontent.com/120441/82642282-f1980080-9c0d-11ea-80a1-a7ba30dc74e0.png)

hover the first commit to get it into the foreground and click the "X" for the CI status:

![grafik](https://user-images.githubusercontent.com/120441/82642340-0379a380-9c0e-11ea-96d9-4497cb08be7f.png)

the checks panel is hidden behind the greyed-out commits

occured on google chrome canary 85.0.4150.0 with refined github 20.5.21

**Comment by notlmn** [comment]
Why are the greyed-out merge commits in your case collapsed. We don't collapse them, we only change their opacity ([source](https://github.com/sindresorhus/refined-github/blob/master/source/features/mark-merge-commits-in-list.css)).

Disable other extensions to see if they might be interfering with commits listing.

(Example URL to test: https://github.com/substack/tape/commits/master)

**Comment by staabm** [comment]
> Why are the greyed-out merge commits in your case collapsed. We don't collapse them, we only change their opacity ([source](https://github.com/sindresorhus/refined-github/blob/master/source/features/mark-merge-commits-in-list.css)).

tried disabling other extensions, but it seems only refined github is the cause.

**Comment by staabm** [comment]
collapsing might be a github native feature, when commit messages are "long enough"

**Comment by fregante** [comment]
We do collapse them in the “dim bots” feature. Disable it if you use bots

**Comment by fregante** [comment]
But yeah we need to drop `overflow:hidden` once it uncollapses to avoid the CI panel being clipped

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/38b48a560b339610461b4acdcf8192ca3cd349e9/source/features/dim-bots.css#L33-L38

```css
/* Dont hide the CI Job Status on focus*/
.rgh-dim-bot.Box-row.navigation-focus {
	overflow: inherit;
}
```

Adding this after that seems to work

**Comment by fregante** [comment]
The overflow is required during the animation or else the content will be outside the box. That code simply drops the overflow: hidden

**Comment by tanettrimas** [comment]
@fregante Would a possible solution to this issue be to listen for the end of the transition, catch that event and just remove the overflow attribute with JavaScript?

If so, I would like to try to implement that in this case :)

**Comment by fregante** [comment]
I think this can be done with transition delays, no js needed

**Comment by tanettrimas** [comment]
I can try to fix that if no one else suddenly volunteers :)
