### ISSUE TITLE
Getting "PR is already touching this file" warning even though PR is closed

### ISSUE THREAD

**Issue by LewisTehMinerz** [sindresorhus/refined-github#3125]
On a file in the PreMiD/Schemas repository (specifically https://github.com/PreMiD/Schemas/blob/master/schemas/metadata/1.0.json) Refined GitHub thinks that an already merged PR is still open and always warns me that it's touching the file. However, said PR is merged: PreMiD/Schemas#1.

When PreMiD/Schemas#2 was created and closed normally, however, the warning disappeared saying that multiple PRs were touching the file.

![image](https://user-images.githubusercontent.com/8019327/82668984-7d238880-9c32-11ea-95f3-35a6ce73f00b.png)
![image](https://user-images.githubusercontent.com/8019327/82669189-e6a39700-9c32-11ea-973e-576b7611fb2c.png)

**Comment by fregante** [comment]
The PR was merged recently. What you’re seeing is just cache that hasn’t expired yet

**Comment by swrobel** [comment]
I just saw this today for a [PR that closed in Feb](https://github.com/que-rb/que/pull/273) ... how long does the cache last?

**Comment by fregante** [comment]
It should only last 1 + 9 days: https://github.com/sindresorhus/refined-github/blob/2235c23dedef9f5ef91cc07c53175e28e5f64b6d/source/features/list-prs-for-file.tsx#L91-L92 (meaning that if you open it after 24 hours of the closure, it will revalidate the cache, so if you refresh the page it should be gone)

Is is still there for you now? I never see it for very long

**Comment by swrobel** [comment]
I already opened the PR and it's since been merged so it's impossible to test again with this scenario. If I see it again, I'll try refreshing the page.
