### ISSUE TITLE
Make exploring topics always focus the code tab

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/refined-github#3127]
Currently, Github sometimes focuses the issues tab when exploring repositories through topics:
![image](https://user-images.githubusercontent.com/36224762/82734491-9448a000-9d30-11ea-9996-8492a2303e70.png)

I want it to always focus the code tab that actually explains what the repo is for:
![image](https://user-images.githubusercontent.com/36224762/82734512-ac202400-9d30-11ea-97d9-0f84567384e5.png)

**Comment by fregante** [comment]
Yeah honestly the decision to show a random issue is mind-boggling for an "explore" section.

**Comment by fregante** [comment]
@NightMachinary is that a mockup or did you take a screenshot? If I click `Code` I get redirected to the repo itself

**Comment by fregante** [comment]
Not worth the trouble since we'd have to rebuild the UI *and* hide content they decided to show.

**Comment by NightMachinary** [comment]
I opened an upstream [issue](https://github.com/github/feedback/discussions/5700).
