### ISSUE TITLE
Play nice with Expandinizr

### ISSUE THREAD

**Issue by gep13** [sindresorhus/refined-github#313]
In addition to this extension, I use the excellent plugin from @thecodejunkie to maxmize the amount of space on the page:

https://github.com/thecodejunkie/github.expandinizr

Having just installed your extension, I immediately noticed this:

![image](https://cloud.githubusercontent.com/assets/1271146/19223216/6548aa92-8e62-11e6-9e0f-269b3e561cbf.png)

Is there anyway that these two extensions can work together?

**Comment by sindresorhus** [comment]
// @thecodejunkie

**Comment by gep13** [comment]
@sindresorhus thanks to @khellang for pointing this out:

https://github.com/thecodejunkie/github.expandinizr/pull/60

I believe this problem has already been fixed 😄 Will re-open this if I still see issues after the next release of expandinizr.
