### ISSUE TITLE
Preview HTML feature broken

### ISSUE THREAD

**Issue by benwaffle** [sindresorhus/refined-github#3132]
The CDN used, https://statically.io, does not allow serving HTML files by default. For example, try clicking on the 'preview' button when viewing https://github.com/sindresorhus/refined-github/blob/master/source/options.html. We could try using https://rawgit.org/ instead.

**Comment by fregante** [comment]
Thanks for the report Ben!

**Comment by kidonng** [comment]
Thank you! I also noticed that Statically stopped serving HTML files several days ago, but forgot I submitted the feature to Refined GitHub 😅
