### ISSUE TITLE
`show-names`: GraphQL:Could not resolve to a User with the login of 'allcontributors'

### ISSUE THREAD

**Issue by CarlRosell** [sindresorhus/refined-github#3133]
Just found that I got an graphql error when trying to get the real name of an app. this can be shown on all comments made by an app. 

here is one example https://github.com/testing-library/which-query/pull/3

**Comment by fregante** [comment]
Thanks for the report! This should be fixed by https://github.com/sindresorhus/refined-github/pull/3130

cc @yakov116
