### ISSUE TITLE
`clean-sidebar`: can't access property "nextElementSibling", header is null

### ISSUE THREAD

**Issue by CarlRosell** [sindresorhus/refined-github#3134]
When having a repository with "projects" turned off, this `header` is null https://github.com/sindresorhus/refined-github/blob/173e39faf0fadc97e134d06d61911ebd86b418fb/source/features/clean-sidebar.tsx#L37-L43
but there is only a null check for `nextElementSibling` and not `header`

A link to a repo is not so valuable as you have to be an owner of the repo in order to see this bug. 😛

**Comment by fregante** [comment]
That’s strange, I regularly test the feature on this repo and Projects are disabled here too.

**Comment by CarlRosell** [comment]
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/2036823/82794939-8d767600-9e73-11ea-8a23-847ac328920d.png">

this is as far as I came to debugging. It did not throw when I had projects enabled. but when I did disable it threw again. I should say that this is not under personal repo, it's in an organization and there you can disable projects.

**Comment by fregante** [comment]
Can you post a screenshot of your sidebar without RGH enabled?

**Comment by CarlRosell** [comment]
<img width="257" alt="Untitled" src="https://user-images.githubusercontent.com/2036823/82806728-ab010b00-9e86-11ea-9bca-9ef7af57435d.png">

**Comment by yakov116** [comment]
I get it on https://github.com/download-directory/download-directory.github.io/pull/29

**Comment by fregante** [comment]
I can’t replicate, but my guess is that the container itself is missing. Let’s add a `if !container, return`

**Comment by fregante** [comment]
I can’t replicate, but my guess is that the container itself is missing. Let’s add a `if !container, return false`
