### ISSUE TITLE
`index` is part of feature list in settings

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3139]
`index` is part of feature list in Refined GitHub settings:
![image](https://user-images.githubusercontent.com/6032823/82846530-8db15880-9ee9-11ea-8732-18bf4c516e92.png)

It doesn't seem to be intended to be there but I might be wrong

**Comment by fregante** [comment]
Aren't you happy to have a NEW feature? Can't make everyone happy...
