### ISSUE TITLE
Add stargazers-you-know from friendly-github

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/refined-github#3142]
If you think it's intrusive, just make it disabled by default.

https://github.com/Hermanya/friendly-github

**Comment by yakov116** [comment]
See https://github.com/sindresorhus/refined-github/pull/1393#issuecomment-403977822

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/pull/1392

**Comment by NightMachinary** [comment]
@fregante Have can I use friendly-github without conflict with refined-github?
