### ISSUE TITLE
GitHub icon redesign for "more" sidebar

### ISSUE THREAD

**Issue by KTibow** [sindresorhus/refined-github#3146]
GitHub has updated their icons:
### New version
![new icons](https://user-images.githubusercontent.com/10727862/83066847-8a69ba00-a01a-11ea-8323-1aca682f9666.jpg)
### Old version
![old icons](https://user-images.githubusercontent.com/10727862/83067178-095ef280-a01b-11ea-9946-d4ddfb0fe2b0.jpg)
Example URL: https://github.com/sindresorhus/refined-github/
But the "More" dropdown's icons haven't changed:
![dropdown](https://user-images.githubusercontent.com/10727862/83066982-be44df80-a01a-11ea-9994-743be2c1391c.jpg)

**Comment by yakov116** [comment]
https://github.com/primer/octicons/pull/370

**Comment by KTibow** [comment]
So GitHub is using the new icons even though they haven't been merged yet?

**Comment by yakov116** [comment]
@fregante this can get closed

**Comment by fregante** [comment]
Thanks for opening this issue! I noticed and updated the icons in #3147 and now I saw this 😄
