### ISSUE TITLE
Add support for GitHub Enterprise domains

### ISSUE THREAD

**Issue by mwakerman** [sindresorhus/refined-github#315]
I think it's great that you've limited the extension to only accessing data on the github.com domain but this prevents me from using it with GitHub Enterprise which runs on an internal domain.

**Comment by hkdobrev** [comment]
I don't use GHE, but I'm open to supporting it in the extension. However I don't know if it's easily possible without getting access to all domains. Any ideas on how this could be implemented are welcome!

@nobso has described a work-around in #318:

> i could manually add an origin in the manifest.json and import it into my browser to make it work for now.

**Comment by nobso** [comment]
@hkdobrev Why cant we allow the user to input an additional domain (just one domain at least)?

**Comment by mwakerman** [comment]
Yep, I think building the plugin locally and setting the domain is a suitable workaround for me.

**Comment by hkdobrev** [comment]
@nobso 
> Why can't we allow the user to input an additional domain (just one domain at least)?

The list of domains which the extension could access is a static list in the manifest and the user is prompted to approve this list upon installation. To the best of my knowledge, we don't have the ability to add domains to that list dynamically based on something the user enters in an options screen.

We can ask for permission to modify sites on every domain, but this is not a good practice and normal GitHub users could be disturbed to give permission to modify all websites to an extension meant to operate on GitHub only.

> Yep, I think building the plugin locally and setting the domain is a suitable workaround for me.

That could be a good workaround for now.

---
If anyone knows if we can add such domains dynamically or if you think asking for permission on all websites in order to support GitHub enterprise is reasonable, please chime in.

**Comment by theckman** [comment]
@hkdobrev I think I found an extension that does something similar (after reading this issue).

I'm trying to find a way to be able to minimize my diffs on GitHub enterprise, and came across this:

* https://chrome.google.com/webstore/detail/pretty-pull-requests-gith/ljnjpkadhhcdniohpfilddnhahoigdec

It allowed me to provide a URL in its options and then Chrome asked if I'd like to give that extension permission to that page. Maybe that method would work for you too? Skimming their code very briefly it seems to use this:

* https://developer.chrome.com/extensions/permissions

Might be worth mentioning that I couldn't get the above extension to work, so either Chrome asking for permission did nothing or the extension itself has some bugs.

**Comment by hkdobrev** [comment]
From Chrome extension docs you've linked:
> If you want to request hosts that you only discover at runtime, include `"http://\*/"` and/or `"https://\*/"` as an optional_permission. This lets you specify any origin in [Permissions.origins](https://developer.chrome.com/extensions/permissions#property-Permissions-origins) as long as it has a matching scheme.

I've reopened the issue. I wanted it to stay open exactly for this kind of suggestions. Thank you @theckman for finding and sharing this!

I'm labeling it as _help wanted_.

@sindresorhus Let us know if you think providing options for this is not worth it.

**Comment by theckman** [comment]
@hkdobrev Ugh. My eyes went _right_ over that section. I'm sorry.

**Comment by thefotios** [comment]
This extension provides a simple way of managing and enabling GHE:
https://github.com/buunguyen/octotree#enterprise-urls

**Comment by hkdobrev** [comment]
@mwakerman @theckman @thefotios Would one of you be interested in creating a pull request for this?

**Comment by derimagia** [comment]
Sounds like this this is dependent on #193, correct? How else would this work?

**Comment by busches** [comment]
@derimagia could easily add it as a one off option to input domain(s) and not worry about encompassing all possible options.

**Comment by bfred-it** [comment]
I tried this already, adding an option is not enough, you'll need to also inject the scripts manually. [Context](https://github.com/npmhub/npmhub/pull/31#issuecomment-279136772)

**Comment by busches** [comment]
@bfred-it correct, you need to request permission for the site and then when on the site inject the scripts. Here's an example: https://github.com/buunguyen/octotree/blob/master/src/config/chrome/background.js

**Comment by hkdobrev** [comment]
@busches @bfred-it Would one of you be willing to start a PR on this? I'm sure it will have good community support if any problems/questions arise. Many thanks!

**Comment by jgierer12** [comment]
➡️ see how this was done in https://github.com/npmhub/npmhub/pull/31

**Comment by bfred-it** [comment]
My intention is to package those files up, that's why they're very generic and read directly from `manifest.json`. You may import them into a `vendor` folder for now.
