### ISSUE TITLE
Prepare for GitHub Redesign

### ISSUE THREAD

**Issue by loilo** [sindresorhus/refined-github#3151]
The new icons (#3146) are part of [a bigger redesign](https://twitter.com/broccolini/status/1265746006974611461) of GitHub.

Is anyone aware how this will impact the markup and therefore existing CSS classes Refined GitHub is using? Would be kind of annoying if those stopped working...

**Comment by FloEdelmann** [comment]
This is the video (aka "GIF") from the tweet: https://video.twimg.com/tweet_video/EZDTS1EWsAIofb9.mp4

It looks like a lot is going to change, but GitHub changes HTML markup and CSS classes here and there all the time. It's something RGH just has to deal with and keep updating/fixing its broken features.

As more RGH users use the feature preview, those bugs will be reported over time and some features are likely going to be updated to work in both interfaces, while others will need a bigger rewrite when the redesign rolls out to everyone.

**Comment by fregante** [comment]
Features will break. PR and issues welcome when noticed

**Comment by FloEdelmann** [comment]
For reference, there is an issue for feature breakages caused by the redesign: https://github.com/sindresorhus/refined-github/issues/3081
