### ISSUE TITLE
Change the wording of `revert-file` commit

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3161]
Currently the wording is `Revert {fileName}`. [Revert follow-file-renames.tsx](https://github.com/sindresorhus/refined-github/pull/3153/commits/aefc57224678e5019380cb68d5742895dddfbea7)

I would like it to say `Revert changes made to {filename}`

**Comment by fregante** [comment]
I just found out that there’s a command called `git restore` and we should probably match its wording

**Comment by yakov116** [comment]
> I just found out that there’s a command called `git restore` and we should probably match its wording

I tried it out `git restore` is just a `git-reset` on a file and does not commit anything

**Comment by fregante** [comment]
Indeed. However given that [`restore` is the right term](https://git-scm.com/docs/git#_reset_restore_and_revert) for the operation, the Menu item should probably say `Restore file` and the commit `Restore {filename}`. 

I think "changes" is implied when talking about git.

**Comment by yakov116** [comment]
Should the feature be renamed to `Restore file`?

**Comment by yakov116** [comment]
@fregante ?

**Comment by yakov116** [comment]
Bump
