### ISSUE TITLE
New GitHub UI Causes Issues

### ISSUE THREAD

**Issue by isaacrlevin** [sindresorhus/refined-github#3164]
The New GitHub UI causes tons of errors in console, here is the [UI update](https://gist.github.com/broccolini/2245234ac3a4936049e8ffc13f376986)

- more-dropdown → TypeError: Cannot read property 'append' of null
- edit-readme → TypeError: Cannot read property 'textContent' of null
- repo-age → TypeError: Cannot read property 'append' of null
- edit-files-faster → TypeError: Cannot read property 'textContent' of null
- latest-tag-button → TypeError: Cannot read property 'textContent' of null

**Comment by yakov116** [comment]
Duplicate of #3081
