### ISSUE TITLE
`link-to-file-in-file-history` doesn't appear on some URLs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3165]
These 2 pages are equivalent: 

- https://github.com/yakov116/refined-github/commits/f23b687b3b89aa95a76193722cdfeff740646670/source/features/release-download-count.tsx?after=f23b687b3b89aa95a76193722cdfeff740646670+34
- https://github.com/yakov116/refined-github/commits/f23b687b3b89aa95a76193722cdfeff740646670?after=f23b687b3b89aa95a76193722cdfeff740646670+34&path%5B%5D=source&path%5B%5D=features&path%5B%5D=release-download-count.tsx

But the latter doesn't show `link-to-file-in-file-history`

**Comment by yakov116** [comment]
Fixed by #3153
