### ISSUE TITLE
Improve copy-paste from diff

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#317]
Context: https://github.com/sindresorhus/refined-github/pull/282#issuecomment-239410508

Still one issue with consecutive lines being prefixed with one space. Seems to be an Chrome issue. Ideas welcome on how to work around it.

**Comment by bfred-it** [comment]
This is no browser bug, the space is actually there and it's being added by #282

<img width="128" alt="whitespace node" src="https://cloud.githubusercontent.com/assets/1402241/26560104/79147cd2-44e6-11e7-8c50-6ab2dd80957f.png">

**Comment by bfred-it** [comment]
Possible solution:

* temporarily add the rule `.add-line-comment {display: none!important}` on `copy` event
