### ISSUE TITLE
sort issues by reactions

### ISSUE THREAD

**Issue by nektro** [sindresorhus/refined-github#3178]
In issue and PR pages, adding `sort:interactions-desc` to the search result by default.

Reference:
https://help.github.com/en/github/searching-for-information-on-github/sorting-search-results#sort-by-interactions

Example:
- https://github.com/golang/go/issues?q=is%3Aissue+is%3Aopen+sort%3Ainteractions-desc
- https://github.com/rust-lang/rust/issues?q=is%3Aissue+is%3Aopen+sort%3Ainteractions-desc

Alternative to:
`sort-issues-by-update-time`

**Comment by nektro** [comment]
actually, I'd prefer it to use `sort:reactions-desc`

**Comment by fregante** [comment]
I understand that this might be a good way to focus on the most request items by the community, but it’s a terrible default because new conversations will always be on the last page.
