### ISSUE TITLE
`format-discussion-titles`: Cannot read property 'parentElement' of null

### ISSUE THREAD

**Issue by mecampbellsoup** [sindresorhus/refined-github#3182]
![image](https://user-images.githubusercontent.com/2043821/83895137-4b292080-a720-11ea-9ab8-665c6fb4523e.png)

[github.com-1591371193237.log](https://github.com/sindresorhus/refined-github/files/4737002/github.com-1591371193237.log)

**Comment by yakov116** [comment]
I think `isPR` should exclude `isConflict`

**Comment by fregante** [comment]
This will be fixed by @yakov116 in the next dependency update. Thank you for the issue!
