### ISSUE TITLE
AngularJS repository marked as being 51 years old

### ISSUE THREAD

**Issue by tobimori** [sindresorhus/refined-github#3185]
![](https://user-images.githubusercontent.com/29142128/83941766-50ed3780-a7ee-11ea-82a0-e5225fae7742.png)

I know that this is probably caused due to broken unix timestamps in the repository, but it should be possible to exclude those broken timestamps.

[angular/angular.js](https://github.com/angular/angular.js)

**Comment by fregante** [comment]
Good point. In this case the broken timestamp is the unix epoch, so it's easy to detect and discard:

https://github.com/angular/angular.js/commit/866346e1ada583daeb649c253516c8f8a879c387.patch

Repos that have this timestamp will simply be cached with `false` and ignored

**Comment by FloEdelmann** [comment]
I'm wondering why it says 51 years though, as 2020 minus 1970 equals 50. Is that GitHub's `<relative-time>` element rounding up?

**Comment by tobimori** [comment]
I guess it's rounding up, because we're already in June.

**Comment by yakov116** [comment]
we could use this and filter out the 1990 ones
```GraphQL
{
  repository(owner: "angular", name: "angular.js") {
    ref(qualifiedName: "master") {
      target {
        ... on Commit {
          history(first: 5, after: "72fbd48f2a805e789fc574176e7a9a87979418d7 8996") {
            nodes {
              committedDate
              resourcePath
            }
          }
        }
      }
    }
  }
}
```

**Comment by fregante** [comment]
Only it that replaces the current `fetchDom` request
