### ISSUE TITLE
Add a button for enabling/disabling refinement.

### ISSUE THREAD

**Issue by taeguk** [sindresorhus/refined-github#319]
If I want to disable a refinement, I must remove extension.
I suggest that adding a button for enabling/disabling refinement.

**Comment by taeguk** [comment]
Oh, you are right. I can enable/disable in the extensions page. 
But, I just want a bit comfortable method without opening extensions page.

**Comment by sindresorhus** [comment]
I'm gonna pass on this. I don't see the use-case being important enough to warrant such button.
