### ISSUE TITLE
`GitHubURL`: 'pathname' called on an object that does not implement interface URL

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#3193]
This line causes the error in Firefox 77:

https://github.com/sindresorhus/refined-github/blob/8b135715bbd73609a67ffd3ab104b1dbbe39edc1/source/github-helpers/github-url.ts#L19

It appears to happen only for some links, not all. It doesn't matter whether I have the "Repository refresh" beta enabled or disabled. Places where I have spotted it:

### ```edit-files-faster```

https://github.com/sindresorhus/refined-github/blob/8b135715bbd73609a67ffd3ab104b1dbbe39edc1/source/features/edit-files-faster.tsx#L17

<details>
<summary>Sometimes only the last link or even more links are affected, but they seem to always keep working up to some point.</summary>

![Screenshot_2020-06-06_18-20-58](https://user-images.githubusercontent.com/202916/83949179-7a27bb00-a822-11ea-8993-758e8e914b31.png)

</details>

### `edit-readme`

https://github.com/sindresorhus/refined-github/blob/8b135715bbd73609a67ffd3ab104b1dbbe39edc1/source/features/edit-readme.tsx#L20

Sometimes it works just fine, sometimes it errors (in the same repo).

### `latest-tag-button`

https://github.com/sindresorhus/refined-github/blob/8b135715bbd73609a67ffd3ab104b1dbbe39edc1/source/features/latest-tag-button.tsx#L97

Sometimes it works just fine, sometimes it errors (in the same repo).

**Comment by yakov116** [comment]
Whats the error?

**Comment by FloEdelmann** [comment]
As the title says, `'pathname' called on an object that does not implement interface URL`.

**Comment by yakov116** [comment]
> As the title says, `'pathname' called on an object that does not implement interface URL`.

I saw that I was asking for the stack-trace.

I did some debugging it is `edit-files-faster`. Disable that and everything works fine. I cant see why everything looks ok.

**Comment by FloEdelmann** [comment]
The stacktrace looks like this:

```
20:53:46.200 ❌ Refined GitHub → edit-files-faster → TypeError: "'pathname' called on an object that does not implement interface URL."
    github_url_GitHubURL moz-extension://2b7c51a0-9289-43d1-ae10-396bc8aa59bc/refined-github.js:4671
    edit_files_faster_init moz-extension://2b7c51a0-9289-43d1-ae10-396bc8aa59bc/refined-github.js:6469
    runFeature moz-extension://2b7c51a0-9289-43d1-ae10-396bc8aa59bc/refined-github.js:2832
    setupPageLoad moz-extension://2b7c51a0-9289-43d1-ae10-396bc8aa59bc/refined-github.js:2840
    add moz-extension://2b7c51a0-9289-43d1-ae10-396bc8aa59bc/refined-github.js:2874
```

**Comment by fregante** [comment]
The error is really weird and there's not much literature about it online. Are you sure there aren't other extensions running? Perhaps you'll have to open the debugger and make it stop on error. That way you can see exactly what’s happening (you might have to disable sourcemaps)

**Comment by yakov116** [comment]
I have the error too (only firefox). Really weird

**Comment by FloEdelmann** [comment]
> What even more weird is I could not get it to error on any other repo besides RG

It fails consistently for me here: https://github.com/OpenLightingProject/open-fixture-library

> Are you sure there aren't other extensions running?

yes

> Perhaps you'll have to open the debugger and make it stop on error. That way you can see exactly what’s happening

I just tried that, but it doesn't help me find the cause.

**Comment by yakov116** [comment]
> > What even more weird is I could not get it to error on any other repo besides RG
> 
> It fails consistently for me here: [OpenLightingProject/open-fixture-library](https://github.com/OpenLightingProject/open-fixture-library)

Thanks

Can you try to disable `edit-files-faster`and see if it does not error? By me it does not.
 (Just want to make sure were seeing the same thing)

**Comment by yakov116** [comment]
Wacky!!  If there is a file called config.json it errors

https://github.com/yakov116/TestR

**Comment by kidonng** [comment]
I'd like to fix the "mess" of `GitHubURL`, and tried to revert #3208. Interesting results on Firefox 93.0:

![image](https://user-images.githubusercontent.com/44045911/136355962-998d796b-42c3-4681-836e-831043f4a358.png)

Compared to Chrome 94:

![image](https://user-images.githubusercontent.com/44045911/136355992-3af7d46b-31fa-4b3d-b41d-ff9140d489c8.png)

It seems Firefox failed to extend `URL`, and all related code operate on the raw `URL` object instead of `GitHubURL`.
