### ISSUE TITLE
Feature request:  Comments in user's profile

### ISSUE THREAD

**Issue by siddharthkp** [sindresorhus/refined-github#320]
Feature request: Comments in user's profile

Something like this?

<img width="638" alt="comments" src="https://cloud.githubusercontent.com/assets/1863771/19620383/f5b86c2a-9899-11e6-9cb2-a8dffe039eb0.png">

**Comment by jitendravyas** [comment]
+1

**Comment by sindresorhus** [comment]
I'm surprised too that GitHub doesn't show comment activity.

@siddharthkp Can you look into how this could be practically solved?

**Comment by siddharthkp** [comment]
Possible ways of doing this at a user level - 
1. Events API `/users/siddharthkp/events` and filtering for type `IssueCommentEvent`
Downside: returns more data than needed which has to be filtered.
Upside: can be clubbed with another feature than depends on events.
2. Search API `/search/issues?q=commenter:siddharthkp`
Downside: Returns issues, not comments - it would be difficult to show the correct count if there were multiple comments on the issue.

**Comment by bfred-it** [comment]
I think this is rather a large feature to be part of RGH. Can you post this to https://github.com/sindresorhus/module-requests/issues?
