### ISSUE TITLE
Combine Github Statuses from GitHub actions with multiple jobs

### ISSUE THREAD

**Issue by tomardern** [sindresorhus/refined-github#3200]
When viewing a PR, it'll be great to combine GitHub statuses which have come from GitHub actions with multiple Jobs.

Example of problem:
All of these are the same Github actions file:
![image](https://user-images.githubusercontent.com/1135454/84038096-5f2a8780-a997-11ea-92d6-44678f7c46ba.png)

But would be nice to be combined to one item (and the ability to click to expand).

Keep up the good work with this extension :)

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/3075

**Comment by tomardern** [comment]
@fregante Amazing, thanks for linking, sorry for duplicate. I did search through but couldn't find it! Will subscribe to the other issues. Thanks again.

**Comment by fregante** [comment]
No worries, that issue didn't initially mention "GitHub Actions" so that's why you might not have found it
