### ISSUE TITLE
`file-finder-buffer`’s field is now white

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3212]
It used to be seamless:

![visible](https://user-images.githubusercontent.com/1402241/75542106-1c811700-5a5a-11ea-8aa5-bea0472c59e2.gif)

Now it looks like this:

<img width="583" alt="" src="https://user-images.githubusercontent.com/1402241/84258013-89ef1a00-ab16-11ea-86c4-b4bc860ea316.png">

Also perhaps its `placeholder` should be "Start typing…" or "Search file…"

**Comment by esakki-selvaraj** [comment]
and also it doesn't show the white box when invoked from other tabs other than code.

**Comment by notlmn** [comment]
I suppose `file-finder-buffer` isn't working anymore. Or maybe that's just me.

**Comment by esakki-selvaraj** [comment]
it is working for me when I click 't'

**Comment by notlmn** [comment]
The `t` works for me, but not the part where it puts in the text I typed before the page loading into the field after the page loading.

**Comment by fregante** [comment]
The feature sadly can only work on ajaxed pages like the repo home.
