### ISSUE TITLE
`more-dropdown` compatibility with "Repository refresh" design

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3215]
`more-dropdown` is kind of a problem now since the new design has an automatic "overflow" hamburger menu:

<img width="588" alt="" src="https://user-images.githubusercontent.com/1402241/84262936-d50d2b00-ab1e-11ea-82da-85002d1e62f1.png">

The obvious solution is to add all those elements to the navigation and let them naturally flow into the overflow, but that's noisy. 

Until now we added items to the dropdown without much trouble, since it was "out of the way", but this change forces us to reconsider it.

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/3081#issuecomment-641942885_

cc @sindresorhus

**Comment by aminya** [comment]
Not sure if these errors are related to this, but I get them in the new design:
![image](https://user-images.githubusercontent.com/16418197/84377496-4513c380-aba8-11ea-8cc4-f12b5b6d5487.png)

**Comment by yakov116** [comment]
@aminya thats https://github.com/sindresorhus/refined-github/issues/3081

**Comment by fregante** [comment]
Is it possible to have the dropdown on the bar, but when it "overflows" its contents end up in the native dropdown?

E.g.


```
Wide viewport
 _________________________________________________________________________
|                                                                         |
| Code - Issues - Pull requests - Actions - [ More ▼ ]                    |
|                                            Commits                      |
|                                            Branches                     |
|                                            Compare                      |
|_________________________________________________________________________|
```

Becomes


```
Small viewport
 ___________________________________________
|                                           |
| Code - Issues - Pull requests - [ ... ]   |
|                                 Actions   |
|                                 Commits   |
|                                 Branches  |
|                                 Compare   |
|___________________________________________|
```

**Comment by kidonng** [comment]
> Is it possible to have the dropdown on the bar, but when it "overflows" its contents end up in the native dropdown?

Isn't this what we have in #3186?

**Comment by notlmn** [comment]
We can start by adding a `max-width` to `.js-repo-nav`, but that still keeps the dropdown trigger to the right.

There's some layout issues using `position: relative` on nav, and there's also figuring out `max-width` in the first place.

Just some thoughts.

**Comment by fregante** [comment]
I like the max-width solution, but it’s a little risky because other extensions add tabs too. 

@kidonng yes, but that’s just 1 item out, 1 item in. I’m talking about 1 item out (the More dropdown) and 5 items in (once it overflows): could that work?

**Comment by kidonng** [comment]
I underestimated the problem. Just navigated through GitHub's code:

![image](https://user-images.githubusercontent.com/44045911/85128656-4d34c880-b264-11ea-907a-57b697df6437.png)

So insert all the `.js-responsive-underlinenav-item` before the listener is added? Impossible. Hook `window.addEventlistner`? Dirty. Make another listener? Tedious and error-prone. Well, I don't really have more ideas.

**Comment by fregante** [comment]
GitHub’s selectors are "live", so new elements are automatically picked up.

I looked into it just now and it looks somewhat possible:

- The link on the horizontal nav is a different DOM element from the one in the native dropdown
	```css
	nav
		a[data-tab-item="issues-tab"]

		.js-responsive-underlinenav-overflow
			li[data-tab-item="issues-tab"]
	```
- These 2 links are connected by the `data-tab-item` attribute
	- when `[data-tab-item="insights-tab"]` is **hidden** from the nav, the other element in the dropdown with the same attribute is **shown**
- items are removed from the nav regardless of whether they have a matching item in the dropdown (I think as long as they have the `js-responsive-underlinenav-item` class)

Given this, I think that this could be a solution:

```css
nav
	a[data-tab-item="issues-tab"]
	.more-dropdown.js-responsive-underlinenav-item
		a[data-tab-item="dependencies"]
		a[data-tab-item="commits"]

	.js-responsive-underlinenav-overflow
		li[data-tab-item="issues-tab"]
		li[data-tab-item="dependencies"]
		li[data-tab-item="commits"]
```

**Comment by kyleknighted** [comment]
My biggest concern was with the non-centering aspect. I just created a little CSS snippet and it seems to keep everything intact during each media query resize

```css
.UnderlineNav-body {
    width: 100%;
	max-width: 1280px;
    justify-content: space-between !important;
	margin: 0 auto;
	padding-left: 4px !important;
	padding-right: 4px !important;
}
@media (min-width:768px){
	.UnderlineNav-body {
		padding-left: 8px !important;
		padding-right: 8px !important;
	}
}
@media (min-width:1012px){
	.UnderlineNav-body {
		padding-left: 16px !important;
		padding-right: 16px !important;
	}
}
```

Sorry if this isn't exactly what you were wanting to accomplish with this Issue, but wanted to share in case it helped solve anyone else's concerns. 

Mods, feel free to delete if it doesn't properly help the discussion.
