### ISSUE TITLE
Disable all feature that require personal token

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3217]
I get a lot of these messages:
![image](https://user-images.githubusercontent.com/16418197/84377680-a2a81000-aba8-11ea-9307-56257e86978f.png)

I prefer to disable those features instead. Also, I am not sure why I need tokens for the public repositories.

**Comment by notlmn** [comment]
> I prefer to disable those features instead.

You are free to and you can, in the extension's settings view.

-----------

> Also, I am not sure why I need tokens for the public repositories.

GitHub has a limit of 60 API requests per hour for unauthenticated requests (and 5000 for authenticated requests, using token).

https://developer.github.com/v3/#rate-limiting

**Comment by aminya** [comment]
> > I prefer to disable those features instead.
> 
> You are free to and you can, in the extension's settings view.
> 

But I don't know which features require such access.

**Comment by fregante** [comment]
> But I don't know which features require such access.

You do, the console tells you:

![image](https://user-images.githubusercontent.com/16418197/84377680-a2a81000-aba8-11ea-9307-56257e86978f.png)

and there's a link in the options page as well:

https://github.com/sindresorhus/refined-github/blob/14304aef8804280496aeb3564a81d79fd67b6504/source/options.html#L10

> Also, I am not sure why I need tokens for the public repositories.

GitHub API v4 requires a token for any call, regardless of repo status.
