### ISSUE TITLE
Fix button for diffs without whitespace

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#322]
Since the new code reviews functionality on GitHub there has been some interface changes. GitHub changed the diff options from a drop down to a button group so the feature initially implemented in #196 stopped working.

We should change the code putting the button to make checks and modifications against the updated DOM structure.

---

The key to fixing this is changing how we check for the current DOM here: https://github.com/sindresorhus/refined-github/blob/b12ad0b07d24602fe400d887004540734b742500/extension/content.js#L240 and how we insert the button here: https://github.com/sindresorhus/refined-github/blob/b12ad0b07d24602fe400d887004540734b742500/extension/content.js#L269-L275

**Comment by hkdobrev** [comment]
@anselmh @steveoh or anyone else who wants to work on this?

**Comment by anselmh** [comment]
I’ll fix that. Sorry, totally had forgotten about this.

**Comment by anselmh** [comment]
And here you go with https://github.com/sindresorhus/refined-github/pull/425.
