### ISSUE TITLE
`linkify-code` runs multiple times on the same URL

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3226]
This became visible when running [the `github-issue-link-status` extension](https://github.com/fregante/github-issue-link-status):

<img width="758" alt="" src="https://user-images.githubusercontent.com/1402241/84527576-71316080-acde-11ea-856e-db9f72915a36.png">

<img width="761" alt="" src="https://user-images.githubusercontent.com/1402241/84527918-03d1ff80-acdf-11ea-9453-956095f8ef40.png">

Test: https://github.com/sindresorhus/refined-github/pull/3225#discussion_r439535538

**Comment by yakov116** [comment]
From my quick debugging, look like it gets run 2 times
Here:
https://github.com/sindresorhus/refined-github/blob/0fa514dbeeab6395ef095cff80beac41443a6574/source/features/linkify-code.tsx#L20-L23
and Here:
https://github.com/sindresorhus/refined-github/blob/0fa514dbeeab6395ef095cff80beac41443a6574/source/features/linkify-code.tsx#L25-L28

**Comment by fregante** [comment]
`linkifyIssues` doesn't affect URLs though, just issue references like `#3226`

**Comment by yakov116** [comment]
>linkifyIssues doesn't affect URLs though, just issue references like #3226

Your right my bad.

> From my quick debugging

I guess that was too quick 😃.

**Comment by kidonng** [comment]
> look like it gets run 2 times

Thanks for the tip, come up with a fix

**Comment by yakov116** [comment]
Having this issue again
https://github.com/sindresorhus/refined-github/pull/3589/files

![image](https://user-images.githubusercontent.com/16872793/118850010-4eb8a780-b89e-11eb-9fbe-b5dc20e1b7e7.png)
