### ISSUE TITLE
Notifications "select all" by status/type

### ISSUE THREAD

**Issue by mcataford** [sindresorhus/refined-github#3229]
Hello!

I've been a user of Refined Github (RG) for a while now and it's become a must-have for my development and project management workflow. The features offered by RG pretty much satisfy all my needs, except in the case of Github Notifications management. My notification feed usually contains thousands of items from tens of different repositories, issues and PRs mixed in. Github offers a **Select all** feature which allows you to grab items in bulk as well as a very limited set of **filters** that can be used to coerce lists of notifications into a set that you can "select all" on and bulk update / review manually. However, there is no set of filters that allow you to select items by status. For example, the flow of "I want to mark all notifications pertaining to a merged PR as read" has no filter shortcut and can be quite tedious.

## Proposed solution

I suggest a dropdown button component not unlike the "..." button that hides the "Mark as read/unread", but for selecting in bulk based on item type and status. With some tinkering, I've put together a mockup of what it could look like:

![image](https://user-images.githubusercontent.com/6210361/84574216-ecdced00-ad72-11ea-8d5d-fe3ff4db536c.png)

This would sit on the top bar of the [notifications screen](https://github.com/notifications), alongside the "Select all" checkbox so that users can quickly bulk-select items with some granularity. I've also put together a crude [CodePen](https://codepen.io/marccataford/pen/LYGZRMe) based off whatever styles and components are already available on the page to give an idea of what the menu would feel like in the UI.

The filtering would only operate on elements that are already in the DOM and would not require to do any sort of network request; each row is already aware of the information that would be used as filter (based on other information displayed in each row already).

I think that this feature would be tremendously helpful for folks that, like me, are flooded by notifications and want to quickly triage through their queue. It could easily be made accessible and even be associated with hotkeys if there's desire to (depending on what the stance of RG is on tacking hotkeys onto the UI via an extension).

I would be happy to take on some of that work and put a PR together if there's any interest in this! It's certainly something that I would use every day and I'm sure others would too. I'd be more than happy to polish this further if this proposal is missing bits and pieces.

**Comment by fregante** [comment]
It doesn't look like GitHub’s own filtering allows this, so it could make sense to add it as a _select_ dropdown.

However I'd like to see it as a multi-select instead:

<img width="299" alt="" src="https://user-images.githubusercontent.com/1402241/84576989-fb4df780-adb8-11ea-9fb0-0849ed1bcbbc.png">

```
Select ↩
  Header: Type
  [ ] PR
  [ ] Issue
  Header: Status
  [ ] Open
  [ ] Closed
  [ ] Merged
  Header: Read
  [ ] Read
  [ ] Unread
```

**Comment by mcataford** [comment]
I love that idea! I can amend the mock up to see what that would look like and go from there! :rocket:

**Comment by nyarly** [comment]
Is there progress on this issue? Without being able to mark merges read (or filter them out), the noise of merged PRs makes Github notifications effectively useless.

**Comment by smartcontracts** [comment]
+1. I use notifications frequently but this is the single biggest missing feature for me. I end up spending a ridiculous amount of time going through all of my notifications and manually selecting every merged/closed PR to mark it as read. I still find notifications useful but without this feature notification management becomes an active chore that takes up at least 5-10 minutes every day.

**Comment by cheap-glitch** [comment]
I'm working on this. Will open a PR in a few days.

**Comment by wouter-n** [comment]
I was looking for this feature but I can't find the drop-down `Select-By` as shown in the video from the PR. Did this get removed or do I need to enable a setting to be able to use it?

**Comment by fregante** [comment]
It works well for me:

<img width="476" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/185076601-2ff8e708-2d7b-48bf-99db-5c775202c00e.png">
