### ISSUE TITLE
Poor performance on collapsed lists

### ISSUE THREAD

**Issue by dakshshah96** [sindresorhus/refined-github#3232]
The transitions are very sluggish while hovering over PRs. Would love to see them become more smooth and help if required.

![Kapture 2020-06-14 at 22 09 52](https://user-images.githubusercontent.com/7896438/84598939-f9a13400-ae8b-11ea-8a23-5e8cd37a7b8d.gif)

Also, sorry if this is not the right place to ask this, but is there a way to disable this collapse behaviour? I couldn't find the name of this feature in the list of features.

**Comment by FloEdelmann** [comment]
The feature is called `dim-bots`:

https://github.com/sindresorhus/refined-github/blob/master/source/features/dim-bots.tsx
https://github.com/sindresorhus/refined-github/blob/master/source/features/dim-bots.css

**Comment by fregante** [comment]
Confirmed. This was broken by the last “fix” we applied to that feature. PR welcome to revert that and/or fix it again, but preserving the way it was working before.
