### ISSUE TITLE
Minor, icon disalignment

### ISSUE THREAD

**Issue by mindrones** [sindresorhus/refined-github#3236]
In the popover suggesting to open a new PR, the icon seems to be a bit off:

<img width="257" alt="Screenshot 2020-06-15 at 13 35 27" src="https://user-images.githubusercontent.com/1309648/84658632-14b48800-af0e-11ea-923a-b0014e4ba1b9.png">

**Comment by fregante** [comment]
Are you using the latest version? This should have been fixed in https://github.com/sindresorhus/refined-github/pull/3196#issuecomment-641176517

Just tested in Chrome:
<img width="398" alt="" src="https://user-images.githubusercontent.com/1402241/84660172-c0fb6c00-af18-11ea-8587-2f1e35673ba1.png">

**Comment by mindrones** [comment]
Hi!

I'm using `20.6.11`, `updated 12 June 2020`. Checking for an update returns `No updates found`.

**Comment by mindrones** [comment]
Oh sorry, I totally forgot, this is Firefox `77.0.1 (64-bit)`, not Chrome.

**Comment by fregante** [comment]
Indeed, Firefox had that issue
