### ISSUE TITLE
Reaction icons smooshed

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#3237]
Reaction icons' width is squashed. Tested on 20.6.11 Chrome & FF.

Without refined-github:

![image](https://user-images.githubusercontent.com/5153846/84692221-d20ea200-af45-11ea-98a0-a8d92db41433.png)

With refined-github:

![image](https://user-images.githubusercontent.com/5153846/84692236-d63abf80-af45-11ea-89df-4fdbc0306d87.png)

Appears on any issue, e.g. this one ↓

**Comment by fregante** [comment]
Can't reproduce on macOS. What's your OS?

**Comment by dwelle** [comment]
Windows 7

**Comment by dwelle** [comment]
Seems to be coming from:

![image](https://user-images.githubusercontent.com/5153846/84698347-f2435e80-af4f-11ea-8760-e1c8540e8314.png)

Setting:

```
max-width: none;
```
fixes it

**Comment by fregante** [comment]
I see why. You don't have native emojis so GitHub uses an image.

Native emojis are not `<img>`-based, which is why I don't see it.

**Comment by dwelle** [comment]
Right, that's it. I thought GH uses imgs for everyone to account for these inconsistencies. Thanks for the fix!
