### ISSUE TITLE
Adjust font in code editor

### ISSUE THREAD

**Issue by Turbo87** [sindresorhus/refined-github#324]
The code editor on GitHub seems to introduce its own styles and overwrites `font` for `<pre>` tags. This makes our `font-family` styling disappear. From short testing in the dev tools it seems that we only need to include the following style in our CSS to make our fonts work in the editor as well:

``` css
pre.CodeMirror-line {
  font: inherit;
}
```

Note that I have only tested this in the dev tools so far and it might not work if our stylesheet is loaded before the editor stylesheet.

**Comment by hkdobrev** [comment]
@Turbo87 Could you create a pull request with this proposal so we could review and merge? Thanks!
