### ISSUE TITLE
Show "me" at Author to add the filter `author:<my-username>`

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3240]
### Summary

Show an `me` label near Autor to select my issues/pull requests.

### Where:
- in issues
- in pull requests

### Function

- Show label "me" near Author drop down
- when click "me" then add the filter `author:<my-username>`

### Motivation

- i often use this filter to look only for my issues
- the drop down already show me on the top list
- but when i click on the Author drop down, it takes about **7-10 seconds** to show to list on large repos (for example: [Gatsby Pull Requests](https://github.com/gatsbyjs/gatsby/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc))

### Mockup

<img width="246" alt="Bildschirmfoto 2020-06-16 um 14 17 44" src="https://user-images.githubusercontent.com/184316/84773352-9377f680-afdc-11ea-9277-b90645531486.png">

added `<sup>me</sup>`

**Comment by busches** [comment]
I don't think it's worth the cluttered UI, when you're the first option in the dropdown. I know we're about saving clicks, but this only saves one.

**Comment by muescha** [comment]
i added a large repo link where you can try it

**Comment by muescha** [comment]
if it would show up my name before it fetched all the authors it would be nice and not worth, but depending on where i click i see:

a) i click on `Author`: i see nothing changing for about 10 seconds

b) i click on the drop down icon: i see this dialog for about 10 seconds with empty data:
<img width="351" alt="Bildschirmfoto 2020-06-16 um 14 31 17" src="https://user-images.githubusercontent.com/184316/84774581-51e84b00-afde-11ea-835f-0b0a63537434.png">

**Comment by fregante** [comment]
We could generate the list item in that dropdown so that it’s available before the full list loads. 

This way it’s still 2 clicks, but you don’t have to wait. 

If we prepend it inside the `include-fragment` element, GitHub will automatically remove it once the list loads and the native link will appear in its place. 

We do something similar with the “buffer file finder” feature

**Comment by muescha** [comment]
for my "use case" it would be enough just include my username here, so they show up before the list is full fetched.

so we don't need to prefetch something.

**Comment by fregante** [comment]
Your solution is definitely easier, but that line is already too crowded, in fact we have a feature to trim it: https://github.com/sindresorhus/refined-github/blob/master/source/features/clean-issue-filters.tsx

**Comment by fregante** [comment]
> If we prepend it inside the `include-fragment` element, GitHub will automatically remove it once the list loads and the native link will appear in its place.

Tested: (no CSS adjustments made though)

![s](https://user-images.githubusercontent.com/1402241/84800143-a2bb6c00-affd-11ea-9b5a-2fa1c3c50049.gif)

**Comment by muescha** [comment]
just a side note:

i see some weird things going on with user filter

this link:
`https://github.com/gatsbyjs/gatsby/pulls?q=is%3Apr+is%3Aopen++author%3Amuescha`

becomes:
`https://github.com/gatsbyjs/gatsby/pulls/muescha`
and sometimes:
`https://github.com/gatsbyjs/gatsby/pulls/created_by/muescha`

hard, when i try to read the `location.pathname` and it gets added.

**Comment by muescha** [comment]
i have done the `me` one click as a userscript: [muescha/GitHub-userscripts](https://github.com/muescha/GitHub-userscripts#add-me-as-author-filter)

**Comment by muescha** [comment]
FYI: i find just now that there is also an other way for a 2-click search:

<img width="336" alt="Bildschirmfoto 2020-06-20 um 18 09 42" src="https://user-images.githubusercontent.com/184316/85206296-5fc10780-b321-11ea-9bd4-deda8c2cdb4f.png">

note: screenshot done with Refined Github off, to see if it is original from github
