### ISSUE TITLE
`forked-to` disappears after navigating from main repo page & back again

### ISSUE THREAD

**Issue by swrobel** [sindresorhus/refined-github#3241]
Firefox 78
Refined Github 20.6.11

Fresh page load:
<img width="225" alt="Screen Shot 2020-06-16 at 7 52 44 AM" src="https://user-images.githubusercontent.com/157270/84790639-6d376400-afa6-11ea-98e0-8634ffb834e7.png">

Click Issues tab:
<img width="219" alt="Screen Shot 2020-06-16 at 7 52 50 AM" src="https://user-images.githubusercontent.com/157270/84790653-71fc1800-afa6-11ea-8072-e44c1c9b301e.png">

Click Code tab:
<img width="226" alt="Screen Shot 2020-06-16 at 7 52 33 AM" src="https://user-images.githubusercontent.com/157270/84790678-77f1f900-afa6-11ea-9041-b43fd9c4c97e.png">

**Comment by fregante** [comment]
It's https://github.com/musically-ut/lovely-forks

**Comment by swrobel** [comment]
oops, sorry for the confusion 🤦
