### ISSUE TITLE
`show-names` showing duplicate names

### ISSUE THREAD

**Issue by timdorr** [sindresorhus/refined-github#3245]
This is on a private PR, so I can't share the link. It appears GitHub is already adding the real names of users to the comment header: 

![image](https://user-images.githubusercontent.com/17882/84941002-b83c9e80-b0ae-11ea-975e-e9f6424ce34b.png)

This occurs for other users in the thread, but my co-founder's name is long enough to take notice. I haven't seen this in public repos, only private ones in orgs. 

Here's the HTML I'm getting:
```html
<strong>
  <a class="author link-gray-dark css-truncate-target rgh-fullname" show_full_name="true" data-hovercard-type="user" data-hovercard-url="/users/thephw/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="/thephw">thephw</a>
  <span class="css-truncate expandable">
    <span class="css-truncate-target text-normal ml-1" style="max-width:175px;">(Patrick Howard Wiseman)</span>
  </span>
</strong>```

**Comment by yakov116** [comment]
Duplicate of #3204

**Comment by timdorr** [comment]
Thanks, missed that one!

**Comment by fregante** [comment]
Did you set the token in the options? It's strange that it's happening only on private repos
