### ISSUE TITLE
Compatibility with the "Design updates" feature preview

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#3248]
The new Github UI currently in feature preview is most likely going to break some things around here.

Something in particular that needs to be changed is the user profile images for reactions. The new design focuses on circles rather than squircles so it should be updated accordingly.

![image](https://user-images.githubusercontent.com/29491356/84995060-a981e480-b19f-11ea-9e17-b588c751b28c.png)

**Comment by notlmn** [comment]
If you are specifically talking about reaction avatars, it is already being worked on in #3247.

**Comment by fregante** [comment]
Let's not start fixing things yet. I'll leave this open so new discussions can happen here, but no PRs yet please.

**Comment by kidonng** [comment]
They are updating profile page as well:
![image](https://user-images.githubusercontent.com/44045911/85106319-98d47b80-b23e-11ea-8600-9ed61aabdd2d.png)
1. Add an icon and remove the number?
2. Maybe something like this looks better?
![image](https://user-images.githubusercontent.com/44045911/85106663-24e6a300-b23f-11ea-9409-a3ec1760caf0.png)

**Comment by rarkins** [comment]
Has anyone identified anything *breaking* that would prevent me using the preview plus the extension for day to day work?

**Comment by kidonng** [comment]
@rarkins Most broken features have been fixed, but GitHub is changing markup/style from time to time so no one can promise something won't break. At least for me, Refined GitHub and the new design are getting along well.

**Comment by sharkykh** [comment]
Both design changes (overall site and repository refresh) have just been made the standard for me.
Not sure if this is in gradual rollout or flat-out for everyone.

Some failures I can see (nothing too major):
### `more-dropdown`
```
refined-github.js:2815 ❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'append' of null
    at appendBefore (refined-github.js:3157)
    at createDropdown (refined-github.js:3171)
    at more_dropdown_init (refined-github.js:3184)
    at async runFeature (refined-github.js:2837)
    at async setupPageLoad (refined-github.js:2845) 
```

### `repo-age`
```
refined-github.js:2815 ❌ Refined GitHub → repo-age → TypeError: Cannot read property 'append' of null
    at repo_age_init (refined-github.js:8105)
    at async runFeature (refined-github.js:2837)
    at async setupPageLoad (refined-github.js:2845) 
```

**Comment by yakov116** [comment]
Same here
@fregante looks like we should disable more-dropdown until we have a better solution

**Comment by notlmn** [comment]
Nothing in RGH is _actually_ broken here, we usually aim to target the public version of GitHub (also GitHub Enterprise).

As long as GitHub repository refresh is in beta, we should be expecting issues, and that is completely fine IMO. We could disable features, but that would impact regular GitHub users (users that do not have beta features enabled) and Enterprise users.

These issues let us keep track of things that we would need to change when (and possibly before) GH makes their changes public. Their "beta feature" is for users to submit feedback to GitHub.

**Comment by mgol** [comment]
@notlmn Well, I'm using the public version of GitHub, I haven't enabled the preview and yet I no have the new GitHub interface. The "Feature preview" option in the dropdown says "No features available".

The GitHub repository refresh is very much public now and issues in working with it will affect regular users.

**Comment by notlmn** [comment]
Geez, was assuming that they were still beta testing this. I remember toggling buttons on another account this morning. No official update from GitHub on any social media platforms yet though (especially on [changelog](https://github.blog/changelog/)).

Right now we are discussing `more-dropdown` in #3215, working on `repo-age` in #3264. This issue is also being worked on in #3247 (will re-open that when we hear officially from GitHub).

Meanwhile if you find any new issues, please do open new issue, or comment on respective issues already opened.

Thanks! 😃

**Comment by muescha** [comment]
now the design update is official: https://github.blog/changelog/2020-06-23-design-updates-to-repositories-and-github-ui/

**Comment by borekb** [comment]
A big issue for me is readability. The new line length in issues and pull requests is around 130 chars which is way too much (it used to be like 80 chars, i.e., around the generally recommended value). I don't see much hope in GitHub fixing this so perhaps it would be a useful feature of RGH.

**Comment by westurner** [comment]
Some way to revert the main content to `col-md-12` (so that 25% of the window isn't wasted on a bright white empty sidebar gutter) would be great.

**Comment by fregante** [comment]
Thanks for reporting this! As mentioned by others, each problem already as an issue or PR open.

If you find anything specific that hasn't been reported, please open a new issue for it.
