### ISSUE TITLE
Add file icons

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/refined-github#3249]
Different types of files should have distinguishing icons to tell them apart, just like icon themes in vs code.

**Comment by notlmn** [comment]
We operate under what GitHub provides through their Octicons package (https://primer.style/octicons/).

This either requires us to include any other icon pack (which would be inconsistent with existing icons) or create our own icon pack (huge effort to create and maintain).

One way I could see is swapping out all of file icons from Octicons with a different set, but again, is it worth the effort?

**Comment by fregante** [comment]
This already exists: https://github.com/homerchen19/github-file-icon
