### ISSUE TITLE
Auto-link "GH-<num>" in PR titles, similar to "#<num>"

### ISSUE THREAD

**Issue by macintacos** [sindresorhus/refined-github#3262]
Right now, if you place #SOME_NUMBER in a PR title, you'll get a nice link to the issue that is referenced. This is a Refined Github feature (I think?).

[According to the documentation](https://help.github.com/en/github/writing-on-github/autolinked-references-and-urls#issues-and-pull-requests), there are a few other ways of linking issues, and I personally like to link them as "GH-SOME_NUMBER" (they work really well as branch names). It'd be nice if Refined Github also recognized this shorthand when it sees it in a PR title.

**Comment by fregante** [comment]
We use the package `linkify-issues` for this. Can you open an issue there?
