### ISSUE TITLE
Fix GitHub's buggy "scroll to focused comment" feature

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3263]
GitHub adds an annoying and buggy double-scroll that happens every time a comment is focused.

![](https://user-images.githubusercontent.com/1402241/85280422-67e78700-b488-11ea-998c-c8dc909ddae0.gif)

I think the reason behind this is the fixed header: when a comment is focused, by default it ends up under the header, so GitHub tries to push it lower.

The problem is that this fix is visible and buggy (you can see that the position changes every time you _focus_ a comment)

**Comment by fregante** [comment]
Test comment

**Comment by fregante** [comment]
This also happens for files in PRs, e.g. https://github.com/sindresorhus/refined-github/pull/3257/files#diff-b3df289d90dbc15afa339bff816f4838

![](https://user-images.githubusercontent.com/1402241/85281062-a893d000-b489-11ea-9daa-a1f298725519.gif)

**Comment by notlmn** [comment]
This is impossible to solve because of the sticky header.

If you keep pressing it fast enough, you see all three behaviors happening.

- Fixed view with glitching.
- Fixed view without glitching.
- Incorrect view, ignoring the fix completely.

We can not say when we see each of these behaviors, except for adding smooth scroll ourselves, overriding GH's offsetting logic.

**Comment by fregante** [comment]
Yeah it looks like it's buggy because there are several pieces of code that try to change the scroll position in various event handlers. If we try to replace that logic, we have to implement all of it (e.g. there's logic that opens collapsed comments when they're `:target`ed and logic that starts loading the rest of the file in a diff when a specific line is `:target`ed)

Perhaps we can just find a way to fix https://github.com/sindresorhus/refined-github/pull/3242 since we control the URL changing. We need to do this without triggering `hashchange`:

- set `location.hash`
- trigger the `:target` style (<- this might not be possible)
- scroll the element into view

**Comment by notlmn** [comment]
> Perhaps we can just find a way to fix #3242 since we control the URL changing. We need to do this without triggering `hashchange`:
> ...

What we could do to avoid glitching in #3242:
1. scroll the element into the position where it is supposed to be
1. replace hash (this triggers `:target`, also `hashchange`)
1. GH will try to scroll page to where it is supposed to be

As of 3, browser in most cases should not do anything, because 3 happens immediately invalidating 2. Not an exact solution, but should avoid some amount of glitch.

**Comment by notlmn** [comment]
Just realized I essentially explained everything GH does after `hashchange` 😅

**Comment by fregante** [comment]
I think this can be fixed "easily" by copying GitHub’s CSS and avoiding the `:target` selector altogether

- Copy GitHub’s CSS and adjust it:
	```diff
	- .comment:target {
	+ .comment.rgh-target {
	```
- On anchor click:
	1. Use `location.replace` to set `location.hash`
	1. Use `comment.scrollIntoView()`
	1. Add `rgh-target` class to `comment`
- `onhashchange` / click on `body`:
	1. Remove `rgh-target` class
	1. Remove `location.hash`

**Comment by notlmn** [comment]
Modifying hash in any way (using `location.hash` or `location.replace`) immediately triggers GH targeting behavior.

In Firefox, even where using `scrollIntoView()` to set comment in desired position and then changing hash causes it to glitch.

The only way to fix this I think would be to hijack GH's handler somehow.

**Comment by fregante** [comment]
This doesn't:

```js
history.replaceState({}, document.title, 'https://github.com/sindresorhus/refined-github/issues/3263#issuecomment-658685481')
```

**Comment by fregante** [comment]
However I think it's not worth getting into the trouble of recreating this behavior and very likely stumbling on conflicts and causing further bugs. Let's hope GitHub fixes it
