### ISSUE TITLE
`restore-file` error

### ISSUE THREAD

**Issue by MaxLeiter** [sindresorhus/refined-github#3265]
When I try to 'restore' a file I deleted this error occurs

**Comment by yakov116** [comment]
That error does not sound related.
The more-dropdown error is https://github.com/sindresorhus/refined-github/issues/3215

Do you get any other error when using the restore file?

**Comment by MaxLeiter** [comment]
Originally I got an error about no token, but then I added one. When I try to restore the file it says "Committing..." then to check in console.

**Comment by yakov116** [comment]
Can you paste the **full** error from the console after you got that message?

**Comment by MaxLeiter** [comment]
The only error in my console:

```

**Comment by yakov116** [comment]
That error is https://github.com/sindresorhus/refined-github/issues/3081 and its followup #3215

**Comment by fregante** [comment]
The error reported is unrelated, but there might still be an error to debug, especially if is says to check the console and there’s nothing there.

**Comment by fregante** [comment]
However, we need a link to the page where your error appears and a screenshot of it, like the issue template suggests

**Comment by fregante** [comment]
Closing as unreproducible/incomplete
