### ISSUE TITLE
Add button in project pages to toggle assigned to me filter

### ISSUE THREAD

**Issue by nkakouros** [sindresorhus/refined-github#3267]
In a project (I mean [these pages](https://github.com/ansible/ansible/projects/42)) there may be a lot of issues. It is often useful to see only the tasks that are assigned to you. There is the search box where you can type `assignee:<my-username>`. 

It would be helpful if there was a button to the left of the search box that toggled the `assignee:<my-username>` filter.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-619437895
>## 7. It doesn't enhance "Projects"
>
>[Projects](https://github.com/features/project-management/) are too big of a feature and everyone wants to make a Jira out of it. None of the maintainers use Projects, so it’s best to suggest it to ZenHub or alternatives.
