### ISSUE TITLE
Revert "Design updates"

### ISSUE THREAD

**Issue by szepeviktor** [sindresorhus/refined-github#3268]
Hello!

1. Everything is round
1. The content is very wide

I propose "Revert Design updates" as a GitHub Refined option.

**Comment by notlmn** [comment]
This extension builds upon what GitHub already provides. This extension is not intended as a "theme for GitHub", but mostly try to fix some annoyances with it.

You can use an extension like [Stylish](https://userstyles.org/) to customize UI as you please, and also provide feedback on beta features at https://support.github.com/contact.

**Comment by szepeviktor** [comment]
Thank you for your response.

I hope others will request the revert.

**Comment by FranklinYu** [comment]
Some of the changes can be reverted with https://chrome.google.com/webstore/detail/old-school-github/blkkkhifjoiedclojflfcenbjigdajeb.

**Comment by szepeviktor** [comment]
Thank you!

https://addons.mozilla.org/en-US/firefox/addon/old-school-github/ for Firefox.

**Comment by fregante** [comment]
Excellent! Thanks for posting the links, I'm sure others will find it useful.
