### ISSUE TITLE
Really small padding issue

### ISSUE THREAD

**Issue by jacobbearden** [sindresorhus/refined-github#327]
![image](https://cloud.githubusercontent.com/assets/5340692/19793797/a5a85e20-9c8b-11e6-94ab-59e0f7d6fbf6.png)

Notice the bottom vs the top.

Seen [here](https://github.com/sindresorhus/refined-github/pull/284#r76823674).

Definitely good for a beginner.

**Comment by mmlanders23** [comment]
Hey @jacobbearden, I would be happy to help out with this but the padding on the linked paged seems to have resolved. Is that true or is this still an open issue?

**Comment by jacobbearden** [comment]
@mmlanders23 

It appears the top padding was reduced, so this is no longer an issue, thanks for noticing! :smile:
