### ISSUE TITLE
Show latest commit message on project page

### ISSUE THREAD

**Issue by Aaron1011** [sindresorhus/refined-github#3277]
The most recent Github update hides the latest commit message on a project page. Instead, it only shows the author, commit date, and SHA:

<image src="https://imgur.com/wDLHkZn.png">

This seems like a misfeature to me - there's always enough space to display at least part of the commit message. Seeing a commit message by default is much more useful than a SHA - I have no reason to want to copy a SHA until I know what the commit does.

I think it would be useful to hide the SHA and use the extra space to display as much of the commit message as will fit.

**Comment by kidonng** [comment]
Maybe we can just expand the commit message by default.

**Comment by Aaron1011** [comment]
@kidonng: That's what I ended up implementing: https://github.com/sindresorhus/refined-github/pull/3278

**Comment by fregante** [comment]
This piece of information is actually already on the page. What if we inconspicuously highlighted the latest commit in the filelist?

Bold:

<img width="783" alt="" src="https://user-images.githubusercontent.com/1402241/86258199-d5975f80-bbba-11ea-83c7-3256056b99d5.png">


Blue line:

<img width="787" alt="" src="https://user-images.githubusercontent.com/1402241/86258469-273fea00-bbbb-11ea-9793-106f9efaa8d1.png">

**Comment by sersorrel** [comment]
That's not much help for repositories with many top-level files (e.g. [git](https://github.com/git/git)), though it's an interesting idea.

**Comment by kidonng** [comment]
I agree with @sersorrel, it's hard to discover in my opinion.
Can we always show the first line of the commit message (and user click expand to see the rest of the message and description)? (https://github.com/sindresorhus/refined-github/pull/3278#issuecomment-649488947)

**Comment by fregante** [comment]
This doesn't look great

<img width="920" alt="" src="https://user-images.githubusercontent.com/1402241/86413641-02826a00-bcc2-11ea-8eaa-e12c96b5e444.png">

But messing with negative margins and `text-gray` might fix it:

<img width="911" alt="" src="https://user-images.githubusercontent.com/1402241/86413651-09a97800-bcc2-11ea-9463-1e09bd56c572.png">

---

- Can this feature be implemented with CSS only?
- Would the negative margins cause conflicts?
- Would this cause the content to jump? i.e. is the commit message lazily loaded?

**Comment by fregante** [comment]
I realized I want this. PR welcome to fix it as described above (only the commit title + centered on the avatar)

**Comment by yakov116** [comment]
its comming back
![image](https://user-images.githubusercontent.com/16872793/86847814-f6f4c180-c07a-11ea-93af-82c2fd387af0.png)

**Comment by fregante** [comment]
They're onto us!!

However that change moves 2 links next to the branch selector, breaking `latest-tag-button`

**Comment by kidonng** [comment]
@fregante Changing the selector from `.breadcrumb` to `.file-navigation .flex-auto` works on both layout, but... 
![image](https://user-images.githubusercontent.com/44045911/86869076-7aa8bf80-c108-11ea-9069-6ad3bb80b994.png)
