### ISSUE TITLE
Malpositioned close button in fork popup 

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3283]
This is a bug of GitHub itself. I don't know if they forget to update the fork popup's style, but now we have this annoying close button:

![chrome_FWVDi4gPHg](https://user-images.githubusercontent.com/44045911/85743949-0f89e100-b737-11ea-8c71-59f2aabdeff0.png)
![chrome_9cOl5yBsVb](https://user-images.githubusercontent.com/44045911/85743952-10bb0e00-b737-11ea-8c34-2f341f172fbd.png)

If you compare it to other popups you will notice the difference:

![image](https://user-images.githubusercontent.com/44045911/85744421-77402c00-b737-11ea-8d28-5526a652e6b8.png)

Checkout fork popup's title style:

![image](https://user-images.githubusercontent.com/44045911/85744494-8626de80-b737-11ea-9ddb-9463cbb4f92f.png)

`position: relative` seems to be the culprit. Let's try `position: static` then:

![image](https://user-images.githubusercontent.com/44045911/85746048-bfac1980-b738-11ea-8089-9503e958455c.png)

Fine, but the position is still wrong. Now add some style to make it looks consistent with other popups:

```css
font-size: 14px;
font-weight: 600;
min-height: unset;
```

![image](https://user-images.githubusercontent.com/44045911/85746266-ea966d80-b738-11ea-8cb6-0955e2d462c5.png)

It definitely looks better! Maybe we should include these styles in Refined GitHub. I will email GitHub about the wrong style too.

**Comment by fregante** [comment]
It’s worth sending this feedback to GitHub instead since they’re working on the redesign.

**Comment by fregante** [comment]
This can be done in a few CSS lines, maybe even just `margin-top: 5px`

PR welcome, add stright to `refined-github.css`
