### ISSUE TITLE
`bug #1234` sometimes creates a link, sometimes doesn't

### ISSUE THREAD

**Issue by timotheecour** [sindresorhus/refined-github#3285]
in https://github.com/nim-lang/Nim/pull/14796/files `bug #1235` (or `issue #1235`) does not create a link to the corresponding github issue; 

![image](https://user-images.githubusercontent.com/2194784/85810411-cbcfb100-b70f-11ea-8f1c-85285add5d47.png)

in other cases it does: https://github.com/nim-lang/Nim/pull/14795/files

![image](https://user-images.githubusercontent.com/2194784/85810394-c1151c00-b70f-11ea-8f24-1fecc59e648c.png)

How do we make it always work?

**Comment by notlmn** [comment]
This is because of https://github.com/sindresorhus/refined-github/blob/master/source/features/linkify-code.tsx#L26-L28, only issue references that are inside "code comments" are linkified.

In this case, GitHub doesn't highlight `rst` diffs enough for us to tell if it is a comment we have to process or part of code that should be ignored.

@fregante, maybe we should also linkify issue references that are outside of comments. Is something stopping us from doing that?

**Comment by fregante** [comment]
I don’t think so. That’s a comment so our logic is correct: GitHub issues appear in comments. 

This is more about GitHub not recognizing its a comment.

We don’t linkify issues numbers *everywhere* to avoid unnecessary processing since *GitHub issues appear in comments.*

**Comment by timotheecour** [comment]
can we have the option to linkify everywhere? at very least in diffed text? that's the whole reason I'd want to use this

**Comment by notlmn** [comment]
> that's the whole reason I'd want to use this

This feature is to linkify issue references inside _code comments_, where we can say if a particular part of code is a comment.

In this particular case where you have a `nim` code block inside an `rst` file, GitHub doesn't process that code block. This seems to also happen in `md` files too ([example](https://github.com/notlmn-dump/github-playground/pull/3/files#diff-04c6e90faac2675aa89e2176d2eec7d8R9)).

By your own example it _does_ work inside [regular `nim` file](https://github.com/nim-lang/Nim/pull/14795/files#diff-229704f5b4526367104ca68ee080d55aR768) diffs, as you expect it to.

**Comment by fregante** [comment]
I suggest asking on https://github.com/github/linguist or https://github.com/Varriount/NimLime to properly support `nim` code highlighting in other files. Those are [the libraries GitHub uses](https://github.com/github/linguist/blob/master/vendor/README.md)
