### ISSUE TITLE
Fix the `border-radius` CSS property of labels

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#3291]
https://github.com/sindresorhus/got/issues

![image](https://user-images.githubusercontent.com/36894700/85862691-67b9f500-b7c2-11ea-8dcd-e0d0cd887307.png)

Before (2em):

![image](https://user-images.githubusercontent.com/36894700/85862851-9a63ed80-b7c2-11ea-8691-0c5bd08a2c29.png)

After (6px):

![image](https://user-images.githubusercontent.com/36894700/85862890-a8b20980-b7c2-11ea-8921-6a8a65f02106.png)

Also please note that buttons are perfect for instance. They got 6px too.

*This is rather a feature request, sorry.*

**Comment by szmarczak** [comment]
I think that the issue status should be fixed too:

![image](https://user-images.githubusercontent.com/36894700/85863671-ca5fc080-b7c3-11ea-893f-41a04b343155.png)

**Comment by szmarczak** [comment]
Another inconsistency (I think that should be a separate issue):

![image](https://user-images.githubusercontent.com/36894700/85863785-f2e7ba80-b7c3-11ea-960c-49606a9fdfea.png)

<hr>

![image](https://user-images.githubusercontent.com/36894700/85863838-009d4000-b7c4-11ea-972d-5fec838cf3ff.png)

**Comment by kidonng** [comment]
Border radius problem is being worked on #3247

**Comment by kidonng** [comment]
> Another inconsistency (I think that should be a separate issue):

Actually they are both `2em` (`.IssueLabel`).

Personally I don't mind the difference, but `6px` of label/status looks fine too.
