### ISSUE TITLE
Feature Request: on an 404 with master try to redirect to main

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3301]
### When
- a repo renames the default branch from `master` to `main`
- GitHub has no default redirect :(
- i open a deep link to a file at the `master` branch

### Expected

- redirect to master
- or a default button to main without requesting the default branch

### Current

- i see an 404
- i see the path and strike for dirs which are deleted
- but i don't always see the `try default branch` button (maybe when it not possible to query for the default branch?)

#### Link: 
  https://github.com/remarkjs/remark-lint/tree/master/packages/remark-lint-no-reference-like-url

#### Screenshot

<img width="1022" alt="Bildschirmfoto 2020-07-01 um 13 59 56" src="https://user-images.githubusercontent.com/184316/86241444-2ef39480-bba3-11ea-90a1-3bb03e7f3007.png">

**Comment by yakov116** [comment]
We already show a link to the master branch

![image](https://user-images.githubusercontent.com/16872793/86244326-cc37d400-bb75-11ea-8469-f476cbb4ad4f.png)

**Comment by notlmn** [comment]
We [do check](https://github.com/sindresorhus/refined-github/blob/master/source/features/useful-not-found-page.tsx#L10-L13) if the same file is available on the default branch. But that does not use the GH API, only basic public 404 validation.

Can you see if you have any errors in the browser console when the link doesn't show up.

**Comment by notlmn** [comment]
@yakov116 looks like the user here is facing an issue where the default branch link doesn't show up as per the screenshot, even though that feature is enabled. Maybe something is happening while [checking for the file on default branch](https://github.com/sindresorhus/refined-github/blob/master/source/features/useful-not-found-page.tsx#L10-L13).

**Comment by yakov116** [comment]
Did not check it out. But maybe they have the default branch already in the cache.
We do a 404 check before and on the cache default branch it does not exist.

**Comment by notlmn** [comment]
@yakov116 yup, looks like a cache issue.

@muescha can you try clearing your extension cache from inside the extension options page and trying this out again. Because as @yakov116 mentioned we do already show that link as you are expecting it.

**Comment by fregante** [comment]
Closing in favor of https://github.com/sindresorhus/refined-github/issues/3302

**Comment by muescha** [comment]
@notlmn clear cache worked, it show up the link again

**Comment by muescha** [comment]
but since the get renamed often, maybe if there is no cache hit, then retry to fetch from api?

**Comment by notlmn** [comment]
@muescha people rarely _rename_ branches, but they do _delete_ them often.

#3302 should reduce the amount of caching annoyances by some bit.

**Comment by muescha** [comment]
> @muescha people rarely _rename_ branches, but they do _delete_ them often.

yes - but in case of missing the `master` branch but the repo is still there, then the chance it is renamed to `main` is very high.

> 
> #3302 should reduce the amount of caching annoyances by some bit.

i hope this helps

and i hope github do this redir by default ...
