### ISSUE TITLE
Reduce all caches to 1 hour or less

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3302]
We had many "issues" related to cache. We do want requests to be cached, but maybe days-long caches are more troublesome than it's worth.

Also it would be great if someone picked this up first: https://github.com/fregante/webext-storage-cache/issues/19

**Comment by muescha** [comment]
how long is the current cache? 

today i have to reset the cache for a "2days before" change is not show up

**Comment by kidonng** [comment]
> how long is the current cache?

It depends on the features. `webext-storage-cache` has a [30 days `maxAge` default](https://github.com/fregante/webext-storage-cache#maxage-1), but most features have a relatively short `maxAge`.

**Comment by muescha** [comment]
in my case it was at the branches view and missing pull requests - i think it is this error and there is a 12h cache: https://github.com/sindresorhus/refined-github/blob/d073d1480fa2b88e16632377b6835f93903716b2/source/features/show-associated-branch-prs-on-fork.tsx#L57

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/blob/d073d1480fa2b88e16632377b6835f93903716b2/source/features/show-associated-branch-prs-on-fork.tsx#L57-L58

`staleWhileRevalidate` means that you'll see cached data for 4 days after it expires, but one more page refresh will show the latest information
