### ISSUE TITLE
Clone or Download > Open in Desktop button is missing

### ISSUE THREAD

**Issue by lautis** [sindresorhus/refined-github#3307]
Open in Desktop button is missing in the "Clone or Download" dialog.

With extension:

<img width="395" alt="Screenshot 2020-07-01 at 23 00 24" src="https://user-images.githubusercontent.com/19264/86286220-c29e8280-bbee-11ea-8793-fda3d7e3ab3b.png">

Without extension:

<img width="380" alt="Screenshot 2020-07-01 at 23 00 35" src="https://user-images.githubusercontent.com/19264/86286233-c8946380-bbee-11ea-930f-24a5db34423d.png">

This seems to be caused by https://github.com/sindresorhus/refined-github/pull/3211. It used to be that in Chrome (but not Firefox) the CSS for `js-remove-unless-platform` was not used and GitHub's own CSS took higher precedence for the element. However, after latest changes to HTML this isn't the case.

**Comment by fregante** [comment]
Thanks for the report! I think that selector just needs to be made more specific

**Comment by raoam488** [comment]
Clone or Download > Open in Desktop button is missing.

Clone or Download Button not showing on Chrome but Showing on Firefox. [Firefox Browser](https://www.mozilla.org/en-US/firefox/download/thanks/) 
So use Firefox as a web browser. And Problem fixed.

**Comment by coderdev27** [comment]
Clone or Download > Open in Desktop button is missing.
Button not showing in firefox.
