### ISSUE TITLE
Full names are not shown

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#331]
This -> [Shows user's full name in comments](https://cloud.githubusercontent.com/assets/170270/16172068/0a67b98c-3580-11e6-92f0-6fc930ee17d1.png) doesn't work anymore for me.

I think I last saw it a week ago.

Probably something in the DOM structure changed?

P.S. It seems it is working on some pages and not others, see below.

**Comment by hkdobrev** [comment]
OK, to clarify - it is obviously working somewhere.

I see it on the current issue, but not on [this PR](https://github.com/sindresorhus/refined-github/pull/330) for example.

**Comment by jacobbearden** [comment]
It fails on [line 131](https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L131).

I believe it's because that line is checking for an element only present on PRs from a fork, but that pull request is just from a different branch.

**Comment by hkdobrev** [comment]
I think the issue is now fully resolved. Probably from #333. Please re-open if you spot it somewhere.
