### ISSUE TITLE
Options page in Edge Chromium has fixed width

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3312]
Not really a *bug*, but I would like to open it here to track the issue.

This is how options page looks in Edge Chromium (85.0.552.1, Windows 10):

![image](https://user-images.githubusercontent.com/44045911/86469932-fa333900-bd6c-11ea-889a-af5398c50cdf.png)

The width is defined by the following line, which is initially added by #934:

https://github.com/sindresorhus/refined-github/blob/4e0245d3faf0518e3e22358cdc5315e4e0c2f13c/source/options.css#L3

It seems Edge has a fixed width for options popup and won't adjust it responsively:

![image](https://user-images.githubusercontent.com/44045911/86470065-3b2b4d80-bd6d-11ea-8c4f-ea347ca6ef57.png)

**Comment by fregante** [comment]
I think we went back and forth on this. It’s worth looking at the History of the file to see why it’s there in the first place. 

Should it be dropped?
Should it be reduced to 400px?

**Comment by kidonng** [comment]
History: 400px (#934) -> 430px (#1193) -> 550px (#1780)

> Should it be dropped?

I tried to remove it in Chrome and it looks fine (at first view).

> Should it be reduced to 400px?
> Should we exclude Edge from this width with `@media not screen and (width:400px) {}`?

I think either would be fine.

**Comment by fregante** [comment]
I prefer this if it works:

```css
@media not screen and (width:400px) { /* Excludes Edge */
	html {
		min-width: 550px;
	}
}
```

**Comment by kidonng** [comment]
It works in both Edge and Chrome 😄

**Comment by yakov116** [comment]
Threw it into #3314
