### ISSUE TITLE
Label for "Filters" dropdown menu is missing

### ISSUE THREAD

**Issue by yuqio** [sindresorhus/refined-github#3315]
The "Filters" dropdown menu in the issue and pull request search bar has no label. This can be seen on any issue and pull request page (e.g. https://github.com/sindresorhus/refined-github/issues)

Without the extension:
![2020-07-04-190656_617x80_scrot](https://user-images.githubusercontent.com/41170571/86517463-6f644400-be29-11ea-8775-d84d7b9234b9.png)

With the extension enabled:
![2020-07-04-190710_409x77_scrot](https://user-images.githubusercontent.com/41170571/86517455-67a49f80-be29-11ea-9323-5c5e900d3e09.png)

**Comment by kidonng** [comment]
This is a feature called `widen-search-field` (wrong icon position due to GitHub design update), which is dropped by #3270. Unfortunately, it's a CSS only feature and can't be toggled off, please wait for a new release (which is on July 9).

**Comment by fregante** [comment]
Fixed by https://github.com/sindresorhus/refined-github/issues/3315
