### ISSUE TITLE
Fix octicons v2 usage

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3317]
Following https://github.com/sindresorhus/refined-github/pull/3147

There are two "issues" described in that PR: the first one has been fixed and the second one probably just means we have to append `-16` to each and every icon import.

Perhaps there's an easy way to map `bug.svg` to `bug-16.svg` file. Maybe not. Exploration wanted on this issue. 

https://github.com/sindresorhus/refined-github/blob/43a7b4066424f46604a4b0358b3faaadd8fbba7d/package.json#L38-L39

**Comment by fregante** [comment]
I forgot that there's a related PR already open 😅: https://github.com/sindresorhus/refined-github/pull/3227

**Comment by yakov116** [comment]
I this was done already reopen if I'm wrong
