### ISSUE TITLE
Bug at "Shows PRs that touch the current file."?

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3324]
### Summary

i not see anymore PR-info when i look at a file, not when in commit (when i see the file in a previous PR)  - and not at master/main or other branch:

### Example

File: https://github.com/jmeridth/jmeridth.github.io/blob/gh-pages/_posts/2012-03-30-do-not-issue-pull-requests-from-your-master-branch.md
PR: https://github.com/jmeridth/jmeridth.github.io/pull/6

### Screenshots

<img width="1232" alt="Bildschirmfoto 2020-07-08 um 13 48 05" src="https://user-images.githubusercontent.com/184316/86915249-f3684580-c121-11ea-906a-39f8d720be7f.png">
<img width="956" alt="Bildschirmfoto 2020-07-08 um 13 48 16" src="https://user-images.githubusercontent.com/184316/86915259-f6fbcc80-c121-11ea-8f9b-2a027ffeea38.png">

**Comment by kidonng** [comment]
Can't reproduce. Try clearing the extension cache (at the bottom of extension settings).

**Comment by fregante** [comment]
I also see it

<img width="455" alt="Screen Shot 2020-07-08 at 18 56 10" src="https://user-images.githubusercontent.com/1402241/86947886-b5344b80-c14c-11ea-801d-232d54aa1be8.png">

**Comment by muescha** [comment]
- today it was still not visible, also force refreshed the page
- i cleared the cache and then this is visible

should the cache not invalidate after one hour?

**Comment by fregante** [comment]
> that was the second time i reported an error because of the cache

Please clear the cache if any new problems arise
