### ISSUE TITLE
Use first commit for PR title and description

### ISSUE THREAD

**Issue by zachwhaley** [sindresorhus/refined-github#3329]
If your branch has just one commit, then GitHub will use that commit message as the PR title and description, which is nice.

However, if your branch has more than one commit, then GitHub uses the branch name as the PR title and leaves the description blank.

I would rather GitHub always use the first commit in a PR branch as the PR title and description.

Example URL: https://github.com/zachwhaley/squashed-merge-message/compare/pr-title-example?expand=1

Screenshots:

Current:
![Screen Shot 2020-07-09 at 11 03 29 AM](https://user-images.githubusercontent.com/2996465/87063503-14896e80-c1d4-11ea-84f2-3f77c25e4af1.png)

Desired:
![Screen Shot 2020-07-09 at 11 03 59 AM](https://user-images.githubusercontent.com/2996465/87063527-1ce1a980-c1d4-11ea-8d27-1ebccb10414a.png)

**Comment by fregante** [comment]
I don’t think that the first commit (of many) is consistently descriptive of of whole PR; sometimes it is, sometimes it isn’t.

**Comment by yakov116** [comment]
@fregante  but it's better then the branch name

**Comment by zachwhaley** [comment]
> I don’t think that the first commit (of many) is consistently descriptive of of whole PR; sometimes it is, sometimes it isn’t.

For me this fits with my workflow where my first commit has a good message and all, but then I often keep testing and make smaller fixup commits.  Since I use Squashed merges I find it easier to just add basic commits instead of using `--amend` or `--rebase`.

I know for some, this might go against their workflow as they might fine tune a list of commits, but I figured it was worth adding a suggestion :)

**Comment by yakov116** [comment]
This does the trick
```
async function init(): Promise<void | false> {
	const commitCount = await elementReady<HTMLElement>('.overall-summary > ul > li:nth-child(1) .text-emphasized')!;
	if (!commitCount) {
		return false;
	}

	if (looseParseInt(commitCount.textContent!) < 2) {
		return false;
	}

	const [prTitle, ...prMessage] = select('#commits_bucket .commit-message code a')!.title.split(/\n\n/);
	textFieldEdit.set(
		select<HTMLInputElement>('.discussion-topic-header input')!,
		prTitle
	);
	textFieldEdit.insert(
		select<HTMLTextAreaElement>('textArea[aria-label="Comment body"]')!,
		prMessage.join('\n\n')
	);
}
```

**Comment by yakov116** [comment]
@fregante what would the feature be called?

**Comment by markalfred** [comment]
Not to beat a dead horse or anything, but just want to throw this out there: @zachwhaley's described workflow is the exact opposite of mine. My branches tend to look like: 

```
A tiny fix for something I noticed while working
A small refactor that will make my feature easier
Setting up the foundation for my feature
✨The Feature!✨
```

So for me, the _last_ commit message tends to be a better descriptor for my PR's.

Not sure this is true for anyone else or if I'm the odd man out, but I wanted to throw it out there in case there are others like me. Either way, it's easy enough to just disable this option for me, and thank you all for the excellent project, it makes a huge difference in my day-to-day. 🙇🙇🙇

**Comment by DamienCassou** [comment]
> Not sure this is true for anyone else

I have exactly the same kind of branch history you describe and the first commit message is never the one I want to see. The last would be a much better alternative for me. In the meantime, I will switch back to GitHub's default.

**Comment by fregante** [comment]
Please don't bump 2-year-old issues. The feature can be disabled.

Also related:

- https://github.com/refined-github/refined-github/issues/5155
