### ISSUE TITLE
FIXED: Repo headers compressed to right side on Github Enterprise

### ISSUE THREAD

**Issue by jeff-minard-ck** [sindresorhus/refined-github#3330]
Looks like there's some kind of injected CSS malarky going on here:

When the window is narrow:

<img width="1214" alt="Screen Shot 2020-07-09 at 11 28 03 AM" src="https://user-images.githubusercontent.com/1210963/87077097-77c8d000-c1d7-11ea-93b2-6f5ed95b3232.png">

When you get wider, the info starts running off to the right:

<img width="2293" alt="Screen Shot 2020-07-09 at 11 28 15 AM" src="https://user-images.githubusercontent.com/1210963/87077131-831bfb80-c1d7-11ea-8208-742c727de4ee.png">

I would _suspect_ that this is a "Github Enterprise is older with different CSS" issue?

Turning off RefinedGithub for the domain and the issue goes away. Turn it back on, and issue returns.

**Comment by epmatsw** [comment]
Adding:

```css
body:not(.full-width) .repohead > * {
    padding-left: 0 !important;
}
```

to the custom CSS for our enterprise domain fixes the issue.

**Comment by fregante** [comment]
We can push a hotfix for this. Does enterprise have any classes on body or html?

**Comment by jeff-minard-ck** [comment]
> Adding:
> 
> ...
> 
> to the custom CSS for our enterprise domain fixes the issue.

Confirmed to fix it for my case.

**Comment by jeff-minard-ck** [comment]
My enterprise page 
```html

<!DOCTYPE html>
<html lang="en">
...
<body class="logged-in enterprise env-production emoji-size-boost min-width-lg">
```

**Comment by fregante** [comment]
Will be fixed by https://github.com/sindresorhus/refined-github/commit/120de1b0ebaba019d9775705907c652bbdd770a1 when it's deployed

**Comment by jeff-minard-ck** [comment]
Removed my override, updated, problem gone. Thanks!

**Comment by rastersize** [comment]
Can confirm that 20.7.10 fixed it for me! Thanks for the quick turnaround 👍
