### ISSUE TITLE
Menu/Header is centred (instead of left-aligned)

### ISSUE THREAD

**Issue by stephenpope** [sindresorhus/refined-github#3332]
This is a great tool but I noticed today that the header menu is now centred when I have refined-github enabled.

Refined-Github = Disabled

![image](https://user-images.githubusercontent.com/689099/87140388-57f9e080-c299-11ea-85db-224fbeadffdc.png)

Refined-Github = Enabled

![image](https://user-images.githubusercontent.com/689099/87140285-2ed95000-c299-11ea-99cc-14c86c2b905e.png)

Now I do use a modification (Stylus) to make github use a wide layout but this happens identically using either of the top two stylus plugins :
https://github.com/mdo/github-wide
https://github.com/xthexder/wide-github

.. so this issue seems like something changed with GitHubs styles and so this has effected refined-github in some way.

**Comment by jfcherng** [comment]
![image](https://user-images.githubusercontent.com/6594915/87152591-8fdc4480-c2e8-11ea-9a17-e538e5e0ccc2.png)

I have similar problem in a gist page.

**Comment by fregante** [comment]
Does the issue happen even when you disable those 2 extensions?

**Comment by stephenpope** [comment]
Thanks for taking a look :)

Here are the different states ..

refined-github: OFF / wide-github: OFF

![image](https://user-images.githubusercontent.com/689099/87164112-411ab480-c2c0-11ea-8b08-2c6c6f83dcbf.png)

refined-github: ON / wide-github: OFF

![image](https://user-images.githubusercontent.com/689099/87164545-ce5e0900-c2c0-11ea-8d7c-e401cd4cd3ed.png)

refined-github: OFF / wide-github: ON

![image](https://user-images.githubusercontent.com/689099/87164684-f9e0f380-c2c0-11ea-9b3a-2c49c593680f.png)

refined-github: ON / wide-github: ON

![image](https://user-images.githubusercontent.com/689099/87164767-13823b00-c2c1-11ea-8e4c-8c825ec10ff2.png)

**Comment by fregante** [comment]
Gists support is easily fixable, but if you want this to work correctly with those extensions, try asking them to specifically override our style (once we’re done adjusting it). It’s easier for them to override our style than it is for us to detect them and exclude them.

**Comment by stephenpope** [comment]
Sure .. i totally get that. Could you just ping this thread when you guys are done and I can either submit a patch or ask them to lok at it :)
Any hints about what has chnaged / what to tweak would also be very much appreciated :D

**Comment by fregante** [comment]
Those extensions can cancel/override the padding we add in `align-repository-header.css`. It would be a change specific to Refined GitHub

**Comment by fregante** [comment]
@stephenpope after #3335, I think it can be undone with:

```css
body:not(.full-width):not(.enterprise) .repohead:not(.gisthead) > * {
	padding-left: 0 !important;
}
```

You can try it in the CSS field in the options before suggesting it to them

**Comment by stephenpope** [comment]
@fregante Im afraid not .. correct selector but doesnt seem to override (sorry ive not done CSS in a long time!) ..
![image](https://user-images.githubusercontent.com/689099/87292800-41ea5b00-c4f9-11ea-8017-3efac87e6c3e.png)

Thanks for the help though.

**Comment by lamont-granquist** [comment]
I think after https://github.com/sindresorhus/refined-github/commit/2fa584de28950e268e519c82d853877cdaa354d7 this is required:

```
body:not(.full-width):not(.enterprise) main > .hide-full-screen > * {
	padding-left: 0 !important;
}
```

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
