### ISSUE TITLE
`recently-pushed-branches-enhancements` breaks when there is more than one PR available

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3333]
![Video_2020-07-10_123439](https://user-images.githubusercontent.com/16872793/87177833-47059b00-c2aa-11ea-98bd-f8537daea015.gif)

**Comment by fregante** [comment]
The widget needs to be restyled (and perhaps temporarily disabled on GHE to avoid CSS clashes) but for now it's not as buggy

![](https://user-images.githubusercontent.com/1402241/88466494-a24ba600-cec4-11ea-8e19-d59726561ed3.gif)
