### ISSUE TITLE
Automatically expand URL when viewing definition/references

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3337]
GitHub has a feature for quickly jumping to definition/references when hovering the code:

![image](https://user-images.githubusercontent.com/44045911/87231780-a966b480-c3ec-11ea-88f5-46ed0548016a.png)

Notice that the links always point to full URL, and when you click it without expanding current page's URL (by pressing <kbd>y</kbd> or whatever, I bet everyone forgets to do this at some time 😄), the page will do an unnecessary (and annoying) full load.

I think it would be convenient if you can just click the definition/references links without worrying about expanding the URL manually.

**Comment by fregante** [comment]
Can you post a link to that file? 

Also I don't know why but it doesn't appear most of the times for me. Maybe they didn't enable it on Firefox?

**Comment by kidonng** [comment]
Link: https://github.com/sindresorhus/refined-github/blob/master/source/github-helpers/api.ts#L50

**Comment by fregante** [comment]
This can be implemented via `delegate`. If the user clicks that exact link, without any modifier keys, change `location.hash` directly instead of following the link. Probably just

```js
function followLocalLink(event) {
  if (event.delegateTarget.pathname === location.pathname) {
    location.hash = event.delegateTarget.hash;
    event.preventDefault()
  }
}
delegate(document, selector, 'click', followLocalLink)
```
