### ISSUE TITLE
Padding left on repohead breaks for gists

### ISSUE THREAD

**Issue by MiniDigger** [sindresorhus/refined-github#3339]
Example URL:
https://gist.github.com/MiniDigger/872365b35245bec55660e64d2ca46c47
Example Screenshots:
https://i.imgur.com/ME0pTsX.png https://i.imgur.com/DDFYwJa.png
![https://i.imgur.com/ME0pTsX.png](https://i.imgur.com/ME0pTsX.png)
![https://i.imgur.com/DDFYwJa.png](https://i.imgur.com/DDFYwJa.png)
16:9 (1080p) and 21:9 (1440p)
Browser:
Chrome 83 on Win10

**Comment by fregante** [comment]
This has been fixed and will be released tomorrow.
