### ISSUE TITLE
Scroll sidebar on repositories 

### ISSUE THREAD

**Issue by piranna** [sindresorhus/refined-github#3349]
With new projects page layout, project info has been moved from page top to a column on the right side. When scrolling down, this info gets out of view, getting an empty space. My suggestion is to don't scroll it beyond its bottom, so when scrolling down the page, it gets fixed an visible all the time.

**Comment by fregante** [comment]
We can do that if it fits the viewport vertically like we do for the conversation sidebar

**Comment by piranna** [comment]
Yes, it's a something similar behaviour :-)

**Comment by shinenelson** [comment]
This could be as easy as duplicating `source/features/sticky-conversation-list-toolbar.css` and changing the CSS selector to `.BorderGrid`. However, most repositories have many sections that usually do not fit in the viewport height. What do we do about that?

Personally, I like to see the Languages section, but most often, I have to scroll to find it. Making the sidebar sticky would mean that I have to get the bottom of the page before I can see the Languages section.

**Comment by piranna** [comment]
What about allowing to scroll just only itself, like a subsection in the page?

**Comment by fregante** [comment]
@piranna scrollable frames on web pages don’t belong to this decade 😃

**Comment by shinenelson** [comment]
@fregante I did try hooking into `sticky-conversation-sidebar` but I hit 2 problems : 
1. the `.rgh-sticky-sidebar` class is toggled with the condition `sidebarHeight < window.innerHeight`. As mentioned previously, most repositories have sidebar sections that will invalidate the expression, hence not enabling stickiness on the sidebar.
2. the value of `top` is hard-coded in the CSS of `.rgh-sticky-sidebar`.

For 2, we could create an extra class for the `top` value specifically for the different kinds of elements ( for example, `rgh-conversation-sidebar`, `rgh-repo-sidebar`, `rgh-issues-list-toolbar` ). Even then, it still does not solve 1 though.

For 1, if we were to over-engineer, we could hide / remove a few sections that could be un-necessary ( Sponsors, Contributors and empty sections like Packages ) and then make the sidebar sticky. But then, that could be a new feature altogether though.

It was when I was digging around the CSS that I found `sticky-conversation-list-toolbar` and tested with that and it worked ( at least for making the sidebar sticky ).

**Comment by fregante** [comment]
> 1. most repositories have sidebar sections that will invalidate the expression, hence not enabling stickiness on the sidebar.

Right. That's what we want. If it doesn't fit, it can't be sticky. That's the right behavior.

> 2\. the value of `top` is hard-coded in the CSS of `.rgh-sticky-sidebar`.

That can be easily fixed by extending the selector. e.g. `.repo .rgh-sticky-sidebar { 123px } .conversation .rgh-sticky-sidebar {456px}` (with the right selectors and value of course)



> we could hide / remove a few sections that could be un-necessary

That's actually what we do in `clean-conversation-sidebars`, it's an unrelated feature that could also be added for the repo home (but the code is likely completely different in this case)



> found `sticky-conversation-list-toolbar`

That feature does not take the height into consideration, so it's not a good match.

**Comment by shinenelson** [comment]
> That's actually what we do in clean-sidebar, it's an unrelated feature. A similar feature could also be added for the repo home (but the code is likely completely different in this case)

We could probably extend `clean-sidebar` to the repository root page as well to clean out empty sections. Releases and Packages are the only 2 sections that are in the sidebar even if they are empty. Other sections are hidden by default.
If we extend `clean-sidebar`, then it would supersede #3572 and possibly make many more repositories 'stickable'.

**Comment by fregante** [comment]
> We could probably extend `clean-sidebar`

Unlikely. That feature is fine-tuned to clean the issues sidebar, as you noticed and as I previously mentioned:

> but the code is likely completely different in this case

**Comment by shinenelson** [comment]
> Given that clean-sidebar.tsx is already huge, it's best to write another feature for the repo root.

Can we merge it with #3573 and perhaps rename that feature?

**Comment by fregante** [comment]
- `releases-tab` already hides the section because it makes it redundant
- `hide-zero-packages` works on both profiles and repos

There's no reason to either extend an existing feature nor add a new one, it all already works out.
