### ISSUE TITLE
`bugs-tab` feature seems not working most of the time

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3350]
1. Still cannot see the Bugs tab most of the time.  

2. I know I can visit the Bugs tab through: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug, but the counter of Bugs tab seems failed:

![image](https://user-images.githubusercontent.com/49396421/87553162-3c516880-c6e5-11ea-8e7c-502a2fddbe07.png)

Or these bugs are being fixed?🤦‍♂️

**Comment by fregante** [comment]
Did you enter a personal access token in the extension’s settings page?

**Comment by Geeyun-JY3** [comment]
> Did you enter a personal access token in the extension’s settings page?

My bad🤦‍♂️. I didn’t enter a personal access token.
Just ignore this issue.
