### ISSUE TITLE
Fix official github defects

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3351]
This is a problem caused by the new version of 🐈github last update,
### `🅶 ⥅ 🆆` cannot goto `WiKi` 

Please press <kbd>Shift+?</kbd> to popup a dialog box for github-shortcut help.

![0716075524](https://user-images.githubusercontent.com/10995302/87611097-b9a6c880-c739-11ea-8752-e4bd830dd8e4.png)

Is it necessary to fix it?

----
Another problem is 👇
![0716083219](https://user-images.githubusercontent.com/10995302/87613103-ee694e80-c73e-11ea-8f65-cfa3901c6c54.png)

This extension is valid 👇
GitHub 发行版下载
https://chrome.google.com/webstore/detail/ncgomhdgmkicjeclohgokhciihpfdlhi

![0716083500](https://user-images.githubusercontent.com/10995302/87613218-3f794280-c73f-11ea-974c-e82a685a089a.png)

**Comment by fregante** [comment]
I'll rewrite:

# `g w` should go to Wiki instead of Actions

👍 let's fix that

# The `release-download-count` doesn't work

It works for me. Have you added the token to the extension’s settings page?

Test URL: https://github.com/google/material-design-icons/releases

<img width="435" alt="Screen Shot 2020-07-16 at 11 41 28" src="https://user-images.githubusercontent.com/1402241/87656101-56c52980-c759-11ea-9536-b04ffc3683d9.png">

**Comment by yakov116** [comment]
I'll take it. @fregante what should I call the feature or what should i combine it with?

**Comment by fregante** [comment]
Maybe `wiki-tab-shortcut-fix`, but on second thought I don’t know if we should fix it. Actions appear on most repos; wikis don’t. While it’s technically incorrect, some might prefer the current situation. It’s best to report it to GitHub instead.

**Comment by fregante** [comment]
https://support.github.com/contact

**Comment by dnknn** [comment]
[**@fregante**](https://github.com/fregante) commented on [2020年7月16日 GMT+8 下午8:58](https://github.com/sindresorhus/refined-github/issues/3351#issuecomment-659393584 "2020-07-16T12:58:05Z - Replied by Github Reply Comments"):
> Maybe `wiki-tab-shortcut-fix`, but on second thought I don’t know if we should fix it. Actions appear on most repos; wikis don’t. While it’s technically incorrect, some might prefer the current situation. It’s best to report it to GitHub instead.


The official definition of 🐈github is 🅶⥅🆆 Go to Wiki.
This is also in line with the beginning of `WiKi`'s word, which is logical.

**Comment by dnknn** [comment]
> > ### The `release-download-count` doesn't work
> 
> It works for me. Have you added the token to the extension’s settings page?

I want to ask how it should be set up, I didn't touch it.
If it works, I uninstall that extension.👇

> GitHub 发行版下载
> https://chrome.google.com/webstore/detail/ncgomhdgmkicjeclohgokhciihpfdlhi

**Comment by fregante** [comment]
Open Refined GitHub’s options page. Google how to do it for your specific browser.

**Comment by dnknn** [comment]
> Open Refined GitHub’s options page. Google how to do it for your specific browser.

![0716223642](https://user-images.githubusercontent.com/10995302/87684548-f4017b80-c7b4-11ea-996d-2024e1280e79.png)

I'm not a developer, I don't how to use Console  to ⛨🐞Debug at all

**Comment by dnknn** [comment]
It's ok now, just fill in the token, I don't understand token, sorry.
