### ISSUE TITLE
Move "Security" and "Insights" repository tab to `more-dropdown`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3354]
https://github.com/sindresorhus/refined-github/pull/3346 restored `more-dropdown` but now we also need to move the Security and Insights tabs to it, like it was before the "Repository refresh"

Possible way to do it:

- remove tabs from dom and show/enable the items in the dropdown

Gotchas:

- the DOM order of the menu **matters**, so you probably need to also move them at the end of the dropdown, _after_ "Settings"

**Comment by yakov116** [comment]
Currently the . . . is always shown (even if nothing is inside) This would also fix that.

**Comment by fregante** [comment]
The dropdown can never be empty, regardless of circumstances. I don’t know if #3347 is related, but I think not. If it’s empty, the creation is failing, **not** the native resize listener.

**Comment by yakov116** [comment]
What is a repo does not have releases such as https://github.com/yakov116/pulse

**Comment by fregante** [comment]
Open a new issue. It’s a bug.

**Comment by Xottab-DUTY** [comment]
This is ridiculously inconvenient! We need some mechanism to be able to configure what should be in the `more-dropdown` and what should be on top.

I just spent 15+ minutes to find out what the heck and where is my Insights button...

**Comment by busches** [comment]
@Xottab-DUTY you can disable the feature and keep the tabs where they started. We won't be adding a configuration option for this, at most we could split each tab into it's own feature.

**Comment by fregante** [comment]
It's good as is. If you need those tabs, you can disable `more-dropdown`, it can't be split
