### ISSUE TITLE
Some other scripts in use for github

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3355]
About First Commit, 
> Check the warehouse's first Commit submission, the main purpose is to check the warehouse's project establishment time.

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/87679267-8eaa8c00-c7ae-11ea-89d8-dff64ec4cd95.png)

</details>

GitHub First Commit   &emsp;&emsp;show "1st commit"
https://greasyfork.org/scripts/38557

After entering the commits page, add the earliest and latest pages at the bottom page
https://greasyfork.org/scripts/402250

This doesn't feel very good   🗑https://greasyfork.org/scripts/38238

---
Github Reply Comments:	add a ⤺ button to add Inline comments
https://greasyfork.org/scripts/38372

<details>
<summary>Details</summary>

![image](https://user-images.githubusercontent.com/10995302/87679817-388a1880-c7af-11ea-81f4-6e0a5c1472d9.png)

</details>

**Comment by fregante** [comment]
You can already access the first commit by clicking “4 years old” in the repository header/sidebar. The feature is called `repo-age` if I remember correctly. 

As for the Quote button, it was already discussed and rejected for 2 reasons:

- it’s bad practice to quote an entire message
- you can already quote part of a message by selecting the text you want and then pressing the `r` key

Also in the future please open one issue per request/report

**Comment by dnknn** [comment]
> You can already access the first commit by clicking “4 years old” in the repository header/sidebar. The feature is called `repo-age` if I remember correctly.

Thanks, can you explain it with a screenshot. I can't find it.
If github itself is okay, there is no need to install scripts

**Comment by dnknn** [comment]
![image](https://user-images.githubusercontent.com/10995302/87876692-7fc11500-ca0c-11ea-843d-4420ba16c681.png)
Thanks♪(･ω･)ﾉ
