### ISSUE TITLE
Categories in options page

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3357]
`chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/options.html
`

There are many functions and the list is very long, which makes it difficult to locate the mess.

If possible, I think the layout of the classification should be restructured.
Classification is based on some large category rules.
The benefits are many, Entering the options page no longer feels like entering the maze.
1 Users can find the function options in this category very quickly.
2 It is also useful for ordinary users (not developers) 
3 E.g,if I don’t use the Pull requests feature, I can find the category and disable it all. Because in this category, it’s all about Pull requests.

4 In short, with the classification options, you can clearly view or find the options corresponding to the category.
Unlike the current, many options do not know where they correspond.

category for examples 👇

- `⌨hotkey/shortcut` &emsp;&emsp; All about shortcuts.

- `Code`

- `Issues`

- `Pull requests`

- `Releases`

- `more`

- `.etc.....`

----
<fieldset>
    <legend></legend>
</fieldset>

![0717003105](https://user-images.githubusercontent.com/10995302/87697570-d20ff500-c7c4-11ea-9dbf-55500d889c7a.png)

![0717003720](https://user-images.githubusercontent.com/10995302/87698166-b0633d80-c7c5-11ea-8837-1ef84c25e955.png)

Or other classifications, in short, it is better to have a classification induction.

**Comment by sindresorhus** [comment]
> There are many functions and the list is very long, which makes it difficult to locate the mess.

Did you try the search?

**Comment by dnknn** [comment]
> Did you try the search?

![0717013522](https://user-images.githubusercontent.com/10995302/87703672-cf65cd80-c7cd-11ea-8dfb-62269e41c57a.png)

Yes, I knew would say that 🔍⏳. But this is two different things.
🔍The search requires Typing and you have to specify keywords, which can't be wrong.

In addition, they are different uses and functions.
🔍⏳ Search is just for quick filtering,
▓🏷️ The catalog classification is used for indexing and manage.

Suppose: `chrome://settings/`  Chrome's settings options page ((Of course, its options are longer)), 
If there is no catalog classification, what will be the effect?

![image](https://user-images.githubusercontent.com/10995302/87704494-10121680-c7cf-11ea-8c64-32c7e67a796f.png)

**Comment by fregante** [comment]
The problem with groups is that they’re arbitrary and incomplete. 

Refined GitHub adds features that benefit everyone or almost everyone, so we don’t expect people to look around and pick what they want. 

You should only deactivate features if you find something you disagree with. None of us wants to spend hours on the options UI to *slightly* improve it.

**Comment by dnknn** [comment]
> None of us wants to spend hours on the options UI to _slightly_ improve it.

Yes, that's right.

But how do know if there are 🆕 or changed options?
In other words, how do users know what is newly added or changed?

**Comment by fregante** [comment]
No classification will be added. New features already have a NEW marker

**Comment by dnknn** [comment]
Ok

**Comment by asmeurer** [comment]
> The problem with groups is that they’re arbitrary and incomplete.

> Refined GitHub adds features that benefit everyone or almost everyone, so we don’t expect people to look around and pick what they want.

> You should only deactivate features if you find something you disagree with. None of us wants to spend hours on the options UI to slightly improve it.

This seems to be an argument for having all the features enabled by default, which seems fine. But I don't see how that's related to whether the options are sorted by category in the options page. For those who *do* want to go through and only enable the things they want, this would make things a lot easier.

Sure, no sorting will be "perfect", but anything would be better than what is there now. They're already categorized in the README. Why not use the same thing in the options page?

As an aside (I can open a new issue for this if you like), something that I would find really helpful in particular would be to find those options that are "destructive" in some sense, that is, those options that affect things other than just my personal view of GitHub. An example is the feature that disables wikis on new repos. These change my mental model of how GitHub works in a way that affects other users, so I prefer to disable them. ("Destructive" isn't really the right word here, but you get the idea)

**Comment by fregante** [comment]
> None of us wants to spend hours on the options UI

Unfortunately this still applies. We can only add that if someone presents a very-minimal PR that:

- Adds headers in the options list (while preserving the filter functionality)
- Categorizes each feature in such list
- Ensures that new features will be categorized (likely via TypeScript type)

and 

- The PR doesn't require a lot of reviews/rewrites to ensure it works

Unfortunately most requests like this fall short of actually sending a full PR, so we're back to _None of us wants to spend hours on the options UI._



> those options that affect things other than just my personal view of GitHub. An example is the feature that disables wikis on new repos. These change my mental model of how GitHub works

I like this argument, can you open a new issue listing the current features that would fall into this category and what could be done to improve the current situation? I'd be hesitant to have disabled-by-default features because they'd be forgotten and lost in the long Options list, while they're still likely useful to many.

**Comment by asmeurer** [comment]
I opened https://github.com/sindresorhus/refined-github/issues/3964.
