### ISSUE TITLE
Can custom add `Commits` to `Tab`?

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3358]
Can custom add `Commits` to `Tab` section?

![0717052009](https://user-images.githubusercontent.com/10995302/87723976-35158200-c7ed-11ea-9a95-4e5a248cfa96.png)
I wonder if it can be achieved with 🅲🆂🆂

**Comment by fregante** [comment]
Everyone wants every page as a tab, but that will look messy. `more-dropdown` already makes it available on every page, so that's enough.
