### ISSUE TITLE
Firefox 77.0.1 compatibility issue

### ISSUE THREAD

**Issue by yevhenshymotiuk** [sindresorhus/refined-github#3359]
![image](https://user-images.githubusercontent.com/44244245/87727274-4fd5ff80-c7c9-11ea-91a6-ad4f53519506.png)

**Comment by fregante** [comment]
Yes, update Firefox to version 78

**Comment by yevhenshymotiuk** [comment]
Oh, of course. Is is not updated in nixos-unstable yet
