### ISSUE TITLE
Copy Button for Gists

### ISSUE THREAD

**Issue by deadcoder0904** [sindresorhus/refined-github#336]
Usually I always select the text to copy a particular gist. It'd be nice to have a copy button :smile:

**Comment by sindresorhus** [comment]
👍 PR welcome :)

We already have an implementation for GitHub.com that could easily be adapted to Gist: https://github.com/sindresorhus/refined-github/blob/007857235f51438ec92060f5f69f2fd2194a6e50/extension/copy-file.js

**Comment by deadcoder0904** [comment]
Yup I'll definitely try :+1:

**Comment by deadcoder0904** [comment]
Closing this. Check #338
