### ISSUE TITLE
Bug in "open your fork" button design

### ISSUE THREAD

**Issue by dakshshah96** [sindresorhus/refined-github#3364]
I noticed that the "open your fork" button has border radiuses on the wrong corners and looks really out of place:

![Screenshot 2020-07-17 12 32 29](https://user-images.githubusercontent.com/7896438/87758439-18e40600-c82a-11ea-89d3-d42a3dcc721c.png)

The button can look better, maybe something like this:

![Screenshot 2020-07-17 12 31 08](https://user-images.githubusercontent.com/7896438/87758547-45981d80-c82a-11ea-9d67-36e10549088e.png)

I would be happy to send a PR if this is something the maintainers want to see land!

**Comment by fregante** [comment]
It looks correct in my case:

<img width="291" alt="Screen Shot 2020-07-17 at 11 23 16" src="https://user-images.githubusercontent.com/1402241/87770936-efbe7800-c81f-11ea-8f4a-fefadef218ac.png">

 Are you on GitHub Enterprise?
Are you using the latest version?
Any errors in the console?

**Comment by dakshshah96** [comment]
> Are you using the latest version?

Yes, version 20.7.16.

> Any errors in the console?

![Screenshot 2020-07-17 15 01 30](https://user-images.githubusercontent.com/7896438/87771893-9ade2a00-c83e-11ea-8cb0-d70e73a4a4e5.png)

> Are you on GitHub Enterprise?

No

> Do you have any additional CSS interfering with it?

No

**Comment by fregante** [comment]
Can you send a screenshot of the DOM and CSS applied to that element?

<img width="965" alt="" src="https://user-images.githubusercontent.com/1402241/87772715-665c7500-c822-11ea-81fe-5dbb8f643d7d.png">

<img width="317" alt="" src="https://user-images.githubusercontent.com/1402241/87772782-7bd19f00-c822-11ea-8523-6fbcef548888.png">

**Comment by dakshshah96** [comment]
![Screenshot 2020-07-17 17 10 55](https://user-images.githubusercontent.com/7896438/87782735-b4886d00-c850-11ea-8024-59219223636b.png)

![Screenshot 2020-07-17 17 12 15](https://user-images.githubusercontent.com/7896438/87782745-b7835d80-c850-11ea-90ec-6c1b4c2111d8.png)

**Comment by fregante** [comment]
It looks like `.rgh-forked-button` is being overridden by `.btn`... in Chrome only.
