### ISSUE TITLE
Render issue/PR templates

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3365]
EDIT: this has been partially implemented, but your help is needed to improve it as described in: https://github.com/sindresorhus/refined-github/pull/3504

You can pick up where I left off

---

Issue/PR templates are easy to dismiss and the links in it are not clickable.

What if we rendered them? (via GitHub’s "preview comment" feature)

<table><th>Before<th>After
<tr><td valign=top>
<img width="940" alt="" src="https://user-images.githubusercontent.com/1402241/87771615-e84b9e80-c820-11ea-931c-a30feea4c074.png">
<td><img width="925" alt="" src="https://user-images.githubusercontent.com/1402241/87771636-ec77bc00-c820-11ea-85df-b80f5ef1beda.png">
</table>

To keep in mind:

- this won't work for all templates (like https://github.com/babel/babel/issues/new/choose), but it may be worth trying
	- it could be opt-in by each template, for example _"Only if it starts with **Instructions:** or similar keywords"_
- we might have to display the render **under** the field to avoid moving the field down
- we probably can't delete the field’s content because some templates have to be filled by the user

**Comment by notlmn** [comment]
@fregante using this as a basic non-intrusive checklist for tasks sounds a lot useful than having to handle user input inputs along with it too. It just sounds more complicated (even if we find a very optimised solution for it).

**Comment by yakov116** [comment]
https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/ !!

**Comment by fregante** [comment]
Yooooooooo! Turning this into a meta issue 👇
