### ISSUE TITLE
`recently-pushed-branches-enhancements` filter branches by prefix

### ISSUE THREAD

**Issue by droidmonkey** [sindresorhus/refined-github#3366]
Should be able to define a prefix to filter for recently-pushed branches. For example, I do not care to be reminded to merge my pending `release/*` branch.

![image](https://user-images.githubusercontent.com/2809491/87854792-42f8ff00-c8e2-11ea-9b16-ed1ad51323b5.png)

**Comment by fregante** [comment]
Features don’t have options and this should be customizable. Can’t do. 

The branches list is actually a GitHub feature, we only move it, so it can be implemented separately.

**Comment by droidmonkey** [comment]
Good point, will redirect energy to GitHub
