### ISSUE TITLE
`ci-link`: Cannot read property 'append' of null

### ISSUE THREAD

**Issue by dakshshah96** [sindresorhus/refined-github#3367]
`ci-link` is not visible on any page where it's supposed to be.

![Screenshot 2020-07-18 20 35 50](https://user-images.githubusercontent.com/7896438/87855492-546bf680-c936-11ea-9604-32eb094a2c73.png)

Also getting a bunch of other errors along with this error:

![Screenshot 2020-07-18 20 36 05](https://user-images.githubusercontent.com/7896438/87855506-6d74a780-c936-11ea-9b3a-0109919c3b3f.png)

**Comment by yakov116** [comment]
Will be fixed by #3362

**Comment by dakshshah96** [comment]
Thanks for letting me know about `ci-link`!

> For the other errors do you have the feature previue enabled?

Yes, I have all Refined GitHub features turned on in extension options.

**Comment by yakov116** [comment]
@dakshshah96 there is an open issue on `github-url-detection` (I think that is the name) about that one. It's an issue that we are not correctly detecting what page your on.

**Comment by yakov116** [comment]
@dakshshah96 there is an open issue on `github-url-detection` (I think that is the name) about that one. It's an issue that we are not correctly detecting what page your on.
