### ISSUE TITLE
Latest commit design updates and default branch button

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3370]
On smaller screens this does not work well

![image](https://user-images.githubusercontent.com/16872793/87875491-84031900-c99f-11ea-83fd-5b74eaaa48de.png)

![image](https://user-images.githubusercontent.com/16872793/87875510-a432d800-c99f-11ea-803b-09b0d4ff2a00.png)

**Comment by kidonng** [comment]
I noticed this too, it can be easily seen at https://github.com/v2fly/V2FlyBleedingEdgeBinary.

**Comment by fregante** [comment]
To fix it, we can add `d-flex` on the those `BtnGroup`

**Comment by kidonng** [comment]
This feature preview is now out of beta.

**Comment by fregante** [comment]
We could also hide the text from those buttons and restore/leave just the icons like it was before. 

Maybe “go to file” and “add file” could even be one .BtnGroup
