### ISSUE TITLE
Display of `show-whitespace` for comments is hard to distinguish from code

### ISSUE THREAD

**Issue by orrc** [sindresorhus/refined-github#3375]
The non-trailing whitespace now feels pretty distracting, to the point that it's very close to the syntax highlighting of comments.

For example, looking at a PR diff with version `20.7.19`:
![image](https://user-images.githubusercontent.com/138615/88075758-86b96600-cb79-11ea-85d7-0d653c1dc913.png)

Looking at recent history, this may be related to #3292.

**Comment by fregante** [comment]
@notlmn can you use the previous color [as requested here](https://github.com/sindresorhus/refined-github/pull/3292#issuecomment-651332709)?

**Comment by notlmn** [comment]
We _are_ using the [same color](https://github.com/sindresorhus/refined-github/pull/3292/files#diff-1034120c49056be4c8f62f895cbd18e0R10), and with the same opacity of `0.5`, but considering the _weight_ of the SVG path being used is a bit thick, we could get that opacity down to `0.1` or `0.2`.

**Comment by fregante** [comment]
The color was the same, but the opacity wasn't:

https://github.com/sindresorhus/refined-github/blob/d4e158776dca70a0bd339872a5b005bf5382aceb/source/features/show-whitespace.css#L13
