### ISSUE TITLE
Only `show-whitespace` for leading or trailing whitespace

### ISSUE THREAD

**Issue by orrc** [sindresorhus/refined-github#3376]
Related to #3375, it would be nice if `show-whitespace` could have an option (or split it into separate features, if that's how it works) to only make whitespace visible when it's at the start or end of the line, i.e. whitespace _within_ a line is not made visible.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/issues/3375 will be fixed and this change is not worth making it more complex and less performant. I suggest using a userscript or forking Refined GitHub (but only keep that feature)
