### ISSUE TITLE
Add (quicker) way to filter for "open issues without a pr"

### ISSUE THREAD

**Issue by dertieran** [sindresorhus/refined-github#3379]
I recently noticed the *linked* prs/issues in the issue/pr list and was wondering if it was possible to add a filter for it.
I couldn't find any filter option in the UI, so I searched the docs and found that it is possible to [filter for them](https://docs.github.com/en/github/searching-for-information-on-github/searching-issues-and-pull-requests#search-for-linked-issues-and-pull-requests) and even to filter for issues/prs without a linked pr/issue.

This allows to build queries like **"open issues without a *(linked)* pr"** *(`is:issue is:open -linked:pr`)*.
Which might be quite useful for open source contributes to find issues that are available to work on.
*(This was one of the main reasons why I opened #1507, to add a way to exclude the `has PR` label more easily)*

I'm not quite sure where to add this and if all filter options should be added to the issues and prs lists.
But I think it might be useful to make this filter easier to access and maybe even more prominent?
Interested to know what others think about this or if that even would be useful to have.

---

For more reference the [blog post](https://github.blog/2020-02-06-get-more-information-at-a-glance-with-issue-and-pull-request-linking/#use-development-information-anywhere-you-view-issues) about this feature.

![](https://i2.wp.com/user-images.githubusercontent.com/22751162/73796206-7fd09f80-4761-11ea-93e9-a43c777df0d1.png?ssl=1)

**Comment by kidonng** [comment]
GitHub will treat custom queries as keywords, which will filter out search results. I don't think intercepting search filters is a good idea, probably you should ask GitHub to add it if you really want it.

That said, we can possibly think about other methods, like adding an option to existing `pr-filters`.

**Comment by fregante** [comment]
Every filter is useful to someone, but we can't add a link to each one. `pr-filters` does add some filters but honestly it's already too much.

I'm sure that GitHub will bring the Notifications’ search field to the conversations as well

<img width="261" alt="" src="https://user-images.githubusercontent.com/1402241/88170033-e1ec6680-cc14-11ea-8dff-524c44bcd76d.png">

**Comment by dertieran** [comment]
@fregante Yea I can see that, I would also be fine with not adding it :+1: 

It was just something I figured out late at night yesterday and thought way isn't this a more prominent feature.
I don't really use the notifications so I didn't see the filter yet, but that looks like the better way then having a button for one thing in some sub menu :smile:

So happy with closing this if it doesn't seem that useful to everybody.

**Comment by sshkhr** [comment]
Hi @dertieran I had a similar thought as you did (five years later!) and created a small extension to add a UI button for filtering issues with a linked PR. It is largely inspired by the refined-github UI, and tries to be minimalistic in terms of changing the default GitHub Issues toolbar. 

The extension is available here under MIT License if you want to install locally:  

[noPR: Filter GitHub Issues with(out) Linked PR](https://github.com/sshkhr/noPR)

It's also available on the Chrome and Firefox extensions store:

- [Chrome Web Store](https://chromewebstore.google.com/detail/nopr-filter-github-issues/dlnlangdknflcflghjooahacifckneeg)
- [Firefox Add-Ons Store](https://addons.mozilla.org/en-GB/firefox/addon/nopr-filter)

![Image](https://github.com/user-attachments/assets/f9a12f21-1f02-44cd-b79c-9b1216737254)

As a nice bonus, it also works with refined-github's Bugs tab:

![Image](https://github.com/user-attachments/assets/0d9ffaec-a731-4b86-bea7-505da1c514e0)
