### ISSUE TITLE
I forgot to set the token

### ISSUE THREAD

**Issue by tomkerkhove** [sindresorhus/refined-github#3381]
Age of [Promitor](https://github.com/tomkerkhove/promitor) is miscalculated since it says it's 19 years old.

![image](https://user-images.githubusercontent.com/4345663/88162511-bcaa2900-cc11-11ea-84b9-c618796c4d47.png)

**Comment by sindresorhus** [comment]
Related to https://github.com/sindresorhus/refined-github/issues/3185. You have a broken Unix timestamp in the repo.

**Comment by kidonng** [comment]
Also, try cleaning the extension cache and refresh the page and see if it's correct.

**Comment by tomkerkhove** [comment]
It's gone but will pop back up I presume, thanks for the quick help

**Comment by fregante** [comment]
**If it happens again, please take a screenshot with the tooltip,** like this, to understand why it's being misparsed.

<img width="316" alt="Screen Shot 2020-07-22 at 12 09 43" src="https://user-images.githubusercontent.com/1402241/88169696-4824b980-cc14-11ea-84f8-8625ee86d175.png">

**Comment by tomkerkhove** [comment]
I'm using Windows indeed!

**Comment by tomkerkhove** [comment]
I'll keep an eye on it but it's hidden for now.

**Comment by kidonng** [comment]
> but it's hidden for now.

What do you mean by "hidden"? It doesn't display? Could you please check if there is something like `Cannot read property 'split' of undefined` in your console? I encountered this issue several times and after cleaning the cache everything backs to normal. Not sure if it is related to this wrong age issue though.

**Comment by yakov116** [comment]
> Could you please check if there is something like `Cannot read property 'split' of undefined` in your console?

That error is https://github.com/sindresorhus/element-ready/issues/29. On first load sometimes the element is not ready on time

**Comment by tomkerkhove** [comment]
> **If it happens again, please take a screenshot with the tooltip,** like this, to understand why it's being misparsed.
> 
> <img alt="Screen Shot 2020-07-22 at 12 09 43" width="316" src="https://user-images.githubusercontent.com/1402241/88169696-4824b980-cc14-11ea-84f8-8625ee86d175.png">

@fregante from another Windows machine without clearing the cache:
![image](https://user-images.githubusercontent.com/4345663/88176640-de160f80-cc27-11ea-8855-512690af4545.png)

After clearing it doesn't show up but console has this entry:
> ℹ️ Refined GitHub → repo-age → Personal token required for this feature

**Comment by yakov116** [comment]
Hmm, if you have it again can you see if there is an error. Also if you can get the commit its linked to.

**Comment by fregante** [comment]
It was a token issue then.

**Comment by tomkerkhove** [comment]
Hold your horses, this was only because I cleared the cache but setting it seems to work.

Why do I need a token for this while it worked before?

**Comment by yakov116** [comment]
We used to use a method that would load the commits page and detect it from there. Currently we are using an API request, which requires a token.

**Comment by fregante** [comment]
Discussion may continue on https://github.com/sindresorhus/refined-github/issues/3340
