### ISSUE TITLE
Show precise watch/star count on hover

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3382]
GitHub omits and rounds up the watch/star/fork counts if they are above 1000 (that is, if you have 1050-1099 stars, it shows 1.1k). The precise counts are stored in `aria-label`, but I think they are useful to everyone.

I propose a new feature (or maybe extending existing `hide-watch-and-fork-count` feature) to show precise counts on hover:

![CnK4WRLAQl](https://user-images.githubusercontent.com/44045911/88166331-addf6880-cc49-11ea-870c-e8b0cab41ad0.gif)

Or show the info not only in `aria-label`, but in `title` attribute as well:

![image](https://user-images.githubusercontent.com/44045911/88166816-77561d80-cc4a-11ea-83e4-79aeaa195340.png)

**Comment by sindresorhus** [comment]
How are they useful? It's IMHO just vanity.

**Comment by kidonng** [comment]
I end up rolling my own user script: https://github.com/kidonng/cherry/tree/master/scripts#github-precise-counters
