### ISSUE TITLE
Cache not invalidates

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3383]
### Descriptiion

on my setup the cache not invalidates correct.

### symptom i faced

this results in some "errors" because of stale cache:

- #3324 `Bug at "Shows PRs that touch the current file."?`
- #3301 `Feature Request: on an 404 with master try to redirect to main`
- `show-associated-branch-prs-on-fork` shows old data after 2 days

### Suggested: page refresh

*source https://github.com/sindresorhus/refined-github/issues/3302#issuecomment-662129283*
> ```javascript
>  maxAge: 1 / 2, 
>  staleWhileRevalidate: 4, 
>```
> staleWhileRevalidate means that you'll see cached data for 4 days after it expires (half a day), but one more page refresh will show the latest information. 

i have done the page reload (<kbd>⌘</kbd>+<kbd>r</kbd>) and hard reload (<kbd>⌘</kbd>+<kbd>⇧</kbd>+<kbd>r</kbd>) many times before i reported an issue here.

### How can i help 

- is there a way to track this problem?
- how can i help to find the cause of the cache problem?

**Comment by fregante** [comment]
Please stop opening more issues about the cache.

I just verified that it works exactly as expected:

- I had `bugs-tab` with this cached data: `{ data: 20, maxAge: 1595771254270 }`
- That maxAge is in 4 days and 13 minutes (`bugs-tab` is set to expire in 30 minutes + 4 days)

1. I waited those 13 minutes
2. I refreshed this page
3. The tab still reported `20` because of the `staleWhileRevalidate` behavior
4. I refreshed this page
5. The tab reported `21` and the cached object was `{ data: 21, maxAge: 1595773212201 }`, which is 4 days and 28 minutes

**Comment by muescha** [comment]
thanks for your patience and pointing me to the direction that i can check it myself.

1) break point

i found the cached data while creating a breakpoint in sources tab on `refined-github.js` at point `const cachedItem = storageData[internalKey];` which would be here:

https://github.com/fregante/webext-storage-cache/blob/master/index.ts#L135

is this the only way i see the cached data? i don't find it in the dev-tools at `Application`/`Cache`


2) refresh page

i understand it right that i have to do 2 normal page refreshs (<kbd>⌘</kbd>+<kbd>r</kbd>) before i get fresh data?

**Comment by fregante** [comment]
1. Run `await browser.storage.local.get()` in the [extension  console context](https://developer.chrome.com/extensions/tut_debugging#debug_cs)
2. Yes. The first load after the expiration date will show the cached data, but also trigger the API request which updates the cache. The second load will use this new cache.

**Comment by fregante** [comment]
@muescha did you set the token?

**Comment by muescha** [comment]
the token is set in plugin:

<img width="103" alt="Token in Plugin" src="https://user-images.githubusercontent.com/184316/88336605-95e51300-cd35-11ea-9288-fec23a732615.png">


and it seems to be used (in last week - no more detailed info is there):

<img width="768" alt="Token" src="https://user-images.githubusercontent.com/184316/88336196-e0b25b00-cd34-11ea-8a09-c9802af14935.png">

Setup with this permissions only:

<img width="614" alt="Permissions" src="https://user-images.githubusercontent.com/184316/88336236-ee67e080-cd34-11ea-9b87-75984e731c0a.png">

the console is filtered for `refined` and show this:

<img width="359" alt="Console" src="https://user-images.githubusercontent.com/184316/88336262-f9227580-cd34-11ea-8935-7792cbef7a3d.png">
