### ISSUE TITLE
Backtick parsing issue when inside code block

### ISSUE THREAD

**Issue by francislavoie** [sindresorhus/refined-github#3385]
Example: https://github.com/lucaslorentz/caddy-docker-proxy/pull/170/files/d7b7e438515d8d05bf86d42de17c8f5983ab6963..fa5dd9cb1b4257fd48c8ff1cd1b8132d94660e9b#r458945992

This comment has backticks inside the code block, but when viewed on this page, they go missing. See here instead on the main issue page instead of the review page: https://github.com/lucaslorentz/caddy-docker-proxy/pull/170#discussion_r458945992

**Comment by kidonng** [comment]
https://github.com/sindresorhus/refined-github/blob/a82f849bd4a745542642b9453c12a6ec18c381aa/source/features/parse-backticks.tsx#L31
