### ISSUE TITLE
`dim-bots` is broken on commit lists

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3386]
`.commit-meta` no longer exists.
https://github.com/OctoLinker/OctoLinker/commits/master

We now have a very specific selector `p + div.d-flex`. Thanks github

**Comment by kidonng** [comment]
I can feel the commit list style change when I open GitHub today 😄
`parse-backticks` selectors on that page needs to be updated too.

**Comment by fregante** [comment]
Feels like this stuff will become increasingly difficult to maintain and fickle as they replace content classes with utility classes. Refined GitHub might go the way or Refined Twitter.
