### ISSUE TITLE
Up arrow to edit own comment is broken

### ISSUE THREAD

**Issue by stowball** [sindresorhus/refined-github#3388]
When trying to quickly edit your own PR comment with Up arrow, it now results in the following error:

```
refined-github.js:3466 Uncaught TypeError: Cannot read property 'click' of null
    at eventHandler (refined-github.js:3466)
    at HTMLDocument.Object.capture (refined-github.js:3446)
    at HTMLDocument.listenerFn (refined-github.js:568)
```

![refined-github-edit-error](https://user-images.githubusercontent.com/853552/88257525-4258d200-cd01-11ea-9a8b-e306ec1ff4fc.gif)

Happens on all PR urls where you're trying to amend a comment

**Comment by kidonng** [comment]
It will work when you have hovered the three dots icon.

More interestingly:

![KaQYm5LObj](https://user-images.githubusercontent.com/44045911/88266928-a5973400-cd02-11ea-807d-0db24fe09c80.gif)

**Comment by piegamesde** [comment]
Sorry for the necrobump, but is there a way to disable up-arrow editing while keeping the quick edit button?

**Comment by fregante** [comment]
The feature is called `comment-fields-keyboard-shortcuts` and is independent from `edit-comments-faster`
