### ISSUE TITLE
The create project button cannot be found

### ISSUE THREAD

**Issue by ishitatsuyuki** [sindresorhus/refined-github#339]
This was belonging to the dashboard, but it's gone with the extension:
![image](https://cloud.githubusercontent.com/assets/12389383/20859748/fab3385e-b9aa-11e6-8dca-e3b28c97eb8a.png)

**Comment by sindresorhus** [comment]
That's intentional. We do a lot to cleanup the interface. There's already `+` button to create a new repo at the top-right.
