### ISSUE TITLE
`fork-source-link-same-view`: The `forked from` link will be broken if the case doesn't match

### ISSUE THREAD

**Issue by JohnTitor** [sindresorhus/refined-github#3393]
If you set your personal token and visit https://github.com/johntitor/rust-forge (note that the capitalization!), the `forked from` link will be broken.

The link will be:

![image](https://user-images.githubusercontent.com/25030997/88294529-54edfe00-cd37-11ea-8883-cc9efd0a1a41.png)

The link causes 404 instead of moving to parent repo (e.g.: https://github.com/rust-lang/rust-forge/undefined/master).
But if you don't set the token or visit with the correct capitalization, the issue doesn't happen.

## Steps to reproduce

1. Set your personal token.
1. Find any fork repo that username has an upper case.
1. Visit there ignoring capitalization.

## Expected behavior

The link should be such as `https://github.com/owner/repo`

## Actual behavior

It points to `https://github.com/owner/repo/undefined/master`

## Environment

- Browser: Firefox 78.0.2
- Extension version: 20.7.19
- OS: Windows 10

**Comment by yakov116** [comment]
Can you give us a direct link?

**Comment by JohnTitor** [comment]
> Can you give us a direct link?

![image](https://user-images.githubusercontent.com/25030997/88296533-c62eb080-cd39-11ea-80ca-e41825892a92.png)

![image](https://user-images.githubusercontent.com/25030997/88296699-fe35f380-cd39-11ea-8d8d-f7accdbbf020.png)


It seems fine.

**Comment by yakov116** [comment]
No i mean what page were you on the I can try to reproduce the issue?

**Comment by JohnTitor** [comment]
> No i mean what page were you on the I can try to reproduce the issue?

Hm then I think I cannot, you can go to a parent repo that you have fork repo.

**Comment by fregante** [comment]
You can, this is the link: https://github.com/JohnTitor/rust-forge

**Comment by fregante** [comment]
It works correctly in my case:

<img width="347" alt="" src="https://user-images.githubusercontent.com/1402241/88309765-adf16e00-cd06-11ea-8153-cfdaa4ffc197.png">

Did the repo change the name of the main branch recently?

**Comment by kidonng** [comment]
I can't reproduce. Also, this doesn't seem to have relationship with `forked-to`.

**Comment by kidonng** [comment]
> Did the repo change the name of the main branch recently?

It is still using `master`

**Comment by JohnTitor** [comment]
> You can, this is the link

Nah, this issue occurs only when you go to the repo using the shortcut link.

**Comment by kidonng** [comment]
> Nah, this issue occurs only when you go to the repo using the shortcut link.

We don't have special logic for that button, it's just a normal link. It should reproduce if you directly visit https://github.com/JohnTitor/rust-forge

**Comment by fregante** [comment]
> We don't have special logic for that button

We kind of have logic, but only if you're in a file or folder. Following these steps doesn't trigger that logic however:

> ## Steps to reproduce
> 
>   1. Visit a repo that you have fork repo.
>   2. Click the shortcut and go to (your) fork repo.
>   3. See `forked from owner/repo` link.

**Comment by JohnTitor** [comment]
Ahh, yep this isn't the shortcut issue but still extension issue, I guess.

Could someone confirm the issue happens if you set your personal token and visit my fork repo e.g. `johntitor/rust-forge` (note that the capitalization, it should be `johntitor`, not `JohnTitor`)?

**Comment by kidonng** [comment]
> note that the capitalization, it should be `johntitor`, not `JohnTitor`

Confirmed

![image](https://user-images.githubusercontent.com/44045911/88315710-3c86df00-cd49-11ea-895f-3d34453a4eac.png)

**Comment by JohnTitor** [comment]
Thanks! Sorry for confusing, now we could say it's extenstion issue?

**Comment by kidonng** [comment]
> it's extension issue?

We know that it's caused by Refined GitHub, but it's not due to `forked-to` (the fork button) but `fork-source-link-same-view`

**Comment by yakov116** [comment]
@kidonng how did you get it to error? What link?

**Comment by kidonng** [comment]
> how did you get it to error? What link?

https://github.com/johntitor/rust-forge

**Comment by yakov116** [comment]
its `isRepoHome` failing

**Comment by fregante** [comment]
👆 this is why we ask for the exact link when opening an issue.

**Comment by kidonng** [comment]
> 👆 this is why we ask for the exact link when opening an issue.

They did give us the right link in the image, but we ignored the case difference 😂

**Comment by kidonng** [comment]
So the fork button will give you all lowercase link, and when you visit it, boom, `getDefaultBranch` gives wrong info

**Comment by yakov116** [comment]
its not supposed to run on that page at all

**Comment by fregante** [comment]
@yakov116 do you think https://github.com/fregante/github-url-detection/pull/25 will fix it?

**Comment by yakov116** [comment]
I think  so (I did not have time to test the PR)
