### ISSUE TITLE
Prevent accidentally creating duplicate pull requests

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3398]
If you accidentally clicked the "Create pull request" button multiple times, you may end up with creating duplicate pull requests (just like I did in #3274 and #3392 😅).

The button should be disabled right after you click it, just like "Comment" and "Update comment" button, but somehow GitHub doesn't enforce it (or should it be considered GitHub's bug?).

I don't know how often this could happen (or it's just me who suffers from this 😂), but I think it makes sense to disable the button after you click it, to prevent the problem.

EDIT: I remembered it wrong, "Submit new issue" button doesn't have this issue.

**Comment by sindresorhus** [comment]
Please also report this to GitHub.
