### ISSUE TITLE
Support editor indent/deintent in new-issue editor

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#3414]
The improvements to textarea (around indenting at least) added to replies editor does not extend to the editor when creating a new issue.

In other words, I can't use `tab`/`Shift+tab` in editor while creating new issues.

Was this intended or an oversight?

**Comment by fregante** [comment]
It was mistakenly limited by https://github.com/sindresorhus/refined-github/pull/3256

That code just need an extra line now: `pageDetect.isNewIssue` I think

**Comment by yakov116** [comment]
@fregante I will fix it
