### ISSUE TITLE
`forked-to` feature always redirects to `HEAD` branch on the fork

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3415]
The enhancement that was made to `forked-to` that makes the forked-to link go to the currently open file is really useful, but it's a bit limited - no matter on what branch the file I'm browsing is currently on, the fork link will go to that file on `HEAD` commit. This has two issues:
- to edit file, you need to switch to an actual branch as `HEAD` is just using HEAD commit and you can't use edit button from there
- this feature only works properly for default branch; otherwise the link will go to location that doesn't exist

So to illustrate with an example, it would be great if clicking the fork button on:
`https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/__main__.py`
would make me go to:
`https://github.com/jack1142/Red-DiscordBot/blob/V3/develop/redbot/__main__.py`
rather than:
`https://github.com/Cog-Creators/Red-DiscordBot/blob/HEAD/redbot/__main__.py`

Similarly, going from non-default branch:
`https://github.com/Cog-Creators/Red-DiscordBot/blob/develop/red.py`
should go to:
`https://github.com/jack1142/Red-DiscordBot/blob/develop/red.py`
rather than non-existent:
`https://github.com/jack1142/Red-DiscordBot/blob/HEAD/red.py`

About the second situation, I'm not sure what should happen if the branch doesn't exist on fork (or the file you're looking at isn't in it), but imo just showing 404 isn't all that bad in such cases as they're probably not going to be as common.

**Comment by fregante** [comment]
- To preserve the current branch, it could send a small request to verify that it also exists on the fork
- If it doesn't exist, use the default branch instead of `HEAD`, with a customized `getDefaultBranch` function
