### ISSUE TITLE
Make `forked-to` link to edit page when you're on edit page

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3416]
Basically, I would want the `forked-to` feature to link to edit page when I'm already on edit page, i.e:
When I'm on:
`https://github.com/Cog-Creators/Red-DiscordBot/edit/V3/develop/redbot/logging.py`
Clicking the button should make it go to:
`https://github.com/jack1142/Red-DiscordBot/edit/V3/develop/redbot/logging.py`
Rather than the "home page" of repository.

**Comment by fregante** [comment]
This should be easy, it only needs to support `isEditingFile`

**Comment by yakov116** [comment]
@fregante sending a pr
