### ISSUE TITLE
`restore-file` can't restore deleted files in forks

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3417]
> I wasn't able to undo the deleted file, the console reported this 404:
> 
> ```
> https://github.com/sindresorhus/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
> ```
> 
> <img width="1147" alt="Screen Shot 2020-07-30 at 12 48 58" src="https://user-images.githubusercontent.com/1402241/88919543-2efab900-d263-11ea-9fa1-d923b3efda54.png">
> 
> _Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/3409#issuecomment-666318532_

This is probably because that 404 URL should be this instead:

```diff
- https://github.com/sindresorhus/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
+ https://github.com/kidonng/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
```

**Comment by yakov116** [comment]
Needs to be done like this

https://github.com/sindresorhus/refined-github/blob/81c11b9f1ac60a307591c88fb560bf56f725138c/source/features/enable-file-links-in-compare-view.tsx#L19


Make it its own function and export it?
