### ISSUE TITLE
`bypass-checks` only works sporadically since ~1 week ago

### ISSUE THREAD

**Issue by beaugunderson** [sindresorhus/refined-github#3418]
Screenshot; mouse is over the underlined "Details" link, you can see in the bottom left that the URL is incorrect (it goes to the GitHub checks page):

![image](https://user-images.githubusercontent.com/61791/88990090-f7efcc00-d291-11ea-91ba-db234e1ec785.png)

(this is in a private repository so unfortunately I can't provider a URL)

**Comment by yakov116** [comment]
@beaugunderson is there a link on the checks page that it should go to?? If yes can to try to debug it.

**Comment by beaugunderson** [comment]
yes--about 10% of the time the link changes correctly

github URL: https://github.com/canvas-medical/canvas/pull/8989/checks?check_run_id=930242255

correct URL: https://circleci.com/workflow-run/d8d5689f-19e5-447b-a749-311c5bfdd2a7?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link

![image](https://user-images.githubusercontent.com/61791/88993123-ee6a6200-d299-11ea-9198-f9ce4cbcd826.png)

"View more details on CircleCI Checks" HTML:

```html
<a class="text-small text-gray-light" target="_blank" rel="noopener noreferrer" data-hydro-click="{&quot;event_type&quot;:&quot;check_suite.external_click&quot;,&quot;payload&quot;:{&quot;check_suite_id&quot;:987749495,&quot;check_run_id&quot;:930242255,&quot;link_url&quot;:&quot;https://circleci.com/workflow-run/d8d5689f-19e5-447b-a749-311c5bfdd2a7?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-checks-link&quot;,&quot;link_text&quot;:&quot;View more details on&quot;,&quot;originating_url&quot;:&quot;https://github.com/canvas-medical/canvas/pull/8989/checks?check_run_id=930242255&quot;,&quot;user_id&quot;:61791}}" data-hydro-click-hmac="40d67556f3f00cb80ec894a6129260f8ea27594b0d8b527f44db099999949159" href="https://circleci.com/workflow-run/d8d5689f-19e5-447b-a749-311c5bfdd2a7?utm_campaign=vcs-integration-link&amp;utm_medium=referral&amp;utm_source=github-checks-link">
        <svg class="octicon octicon-link-external mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M10.604 1h4.146a.25.25 0 01.25.25v4.146a.25.25 0 01-.427.177L13.03 4.03 9.28 7.78a.75.75 0 01-1.06-1.06l3.75-3.75-1.543-1.543A.25.25 0 0110.604 1zM3.75 2A1.75 1.75 0 002 3.75v8.5c0 .966.784 1.75 1.75 1.75h8.5A1.75 1.75 0 0014 12.25v-3.5a.75.75 0 00-1.5 0v3.5a.25.25 0 01-.25.25h-8.5a.25.25 0 01-.25-.25v-8.5a.25.25 0 01.25-.25h3.5a.75.75 0 000-1.5h-3.5z"></path></svg>View more details on CircleCI Checks
</a>```

**Comment by yakov116** [comment]
Can you check if `$('[data-hydro-click*="check_suite.external_click"]')` exists on the checks page?

**Comment by beaugunderson** [comment]
yes, that’s visible in my last comment :) (the html blob is from the checks
page and contains that string)

**Comment by fregante** [comment]
It's possible that the DOM is updated but we don't fix the links again.

This feature should probably use `selector-observer`: #3084
