### ISSUE TITLE
consider installing 'goodfirstissue' bot on 'refined-github' repo

### ISSUE THREAD

**Issue by rajatjindal** [sindresorhus/refined-github#3423]
Hi `refined-github` Team

thank you for this wonderful extension to make for a better UX when using github.

I noticed that this repo has quite a few issues labeled `good first issue`, so I thought I will ask this.

I've developed a github bot [goodfirstissue](https://github.com/rajatjindal/goodfirstissue) which tweets 'good first issues' via twitter handle [@goodfirstissue](https://twitter.com/goodfirstissue). 

I wanted to see if the team would find it useful to let the bot tweet `goodfirstissues` from this repo/org.

the targeted audience for twitter account are first time contributors, and to encourage open source contributions.

## Some details:

**Permissions this app need:** read permission on issues and metadata.
**Twitter Handle used to tweet:** [@goodfirstissue](https://twitter.com/goodfirstissue)
**Source code of the app/webhook:** https://github.com/rajatjindal/goodfirstissue
**Instructions to install github app**: https://github.com/rajatjindal/goodfirstissue#how-to-install
**Current Users**: https://github.com/rajatjindal/goodfirstissue#current-users

Many thanks for considering.

**Comment by sindresorhus** [comment]
I'm sure your bot is great, but I just don't like bots, so I'm going to pass on this.

**Comment by rajatjindal** [comment]
No worries, thank you for quick turnaround. 👍🏻👍🏻
