### ISSUE TITLE
Cant't see following peoples activity

### ISSUE THREAD

**Issue by howdyAnkit** [sindresorhus/refined-github#3424]
I recently found that I can't see the activity of people who I Follow 
for Eg: I was not able to see the people I follow activities.

after disabling the Extension I was able to see the activity of people who I follow for 

Eg: after Disabling the Extension I was able to check their activity like who they follow to.

I have attached a short gif below for reference 
![ezgif com-video-to-gif (1)](https://user-images.githubusercontent.com/40737659/89095354-b1fa4b80-d3ea-11ea-895b-93d3e0e0572e.gif)

**Comment by fregante** [comment]
It's a feature:

https://github.com/sindresorhus/refined-github/blob/be7c091c7ab53c05437b886b7f3f99a48a580e26/source/features/hide-useless-newsfeed-events.css#L12-L14

Uou can disable `hide-useless-newsfeed-events`

**Comment by howdyAnkit** [comment]
facepalm
