### ISSUE TITLE
Show an `archived` tag for archived projects in topics

### ISSUE THREAD

**Issue by NightMachinary** [sindresorhus/refined-github#3425]
For example, here I am in the REPL topic, looking for good REPLs. This `Rusti` project has been archived, but it doesn't say so on this page, so I'd waste time by opening the link.

![image](https://user-images.githubusercontent.com/36224762/89100505-b46d9d00-d40c-11ea-85eb-707f25a73ff1.png)

**Comment by sindresorhus** [comment]
That seems like just an oversight by GitHub. Please report this to GitHub support.

**Comment by NightMachinary** [comment]
[**@Sindre Sorhus**](https://github.com/sindresorhus) commented on [Aug 1, 2020, 4:03 PM GMT+4:30](https://github.com/sindresorhus/refined-github/issues/3425#issuecomment-667517624 "2020-08-01T11:33:17Z - Replied by Github Reply Comments"):
> That seems like just an oversight by GitHub. Please report this to GitHub support.

Well, I copied this to their [forum](https://github.community/t/fr-show-an-archived-tag-for-archived-projects-in-search-and-explore/125523), but I don't have high expectations.

**Comment by fregante** [comment]
What search? All search boxes already exclude archived repositories. 

Also, always include URLs to the exact pages you’re referring to, to avoid misunderstandings.

**Comment by NightMachinary** [comment]
[**@fregante**](https://github.com/fregante) commented on [Aug 2, 2020, 1:22 AM GMT+4:30](https://github.com/sindresorhus/refined-github/issues/3425#issuecomment-667585716 "2020-08-01T20:52:36Z - Replied by Github Reply Comments"):
> What search? All search boxes already exclude archived repositories.
> 
> Also, always include URLs to the exact pages you’re referring to, to avoid misunderstandings, like the “New issue” template requests.
> 
> ```
> 2. Include a full URL where the feature should appear.
> ```

Oh, so that's what that meant. I didn't understand what it meant.

https://github.com/topics/repl

You're right, I don't know about search pages, I only saw this on this URL. Sorry.

**Comment by fregante** [comment]
This is such a minor annoyance on a minor page that it's not worth building a whole feature based on the API just for it. Hopefully GitHub will address it.
