### ISSUE TITLE
Left and right navigation to quickly go through issues and commits

### ISSUE THREAD

**Issue by gnu-user** [sindresorhus/refined-github#343]
I'm wondering if something like this has already been added, if not myself or someone else who has the time should try and add this functionality. If you've ever used a system such as Taiga, there's nice left and right navigation buttons to quickly go through issues, especially if you have a lot of them.

Currently with Github, every time you read an issue and comment / close it, you then have to go back to the entire list of issues, remember where you left off and somehow keep track of the next issue to open.

This lack of functionality has bothered me so much that I actually sent Github staff a long email about it over a year ago. They replied but since then have not added this basic functionality, for a reference this is precisely what I'm describing, if you've ever used Taiga they already have this.

![github-annoyances](https://cloud.githubusercontent.com/assets/820947/11196742/da7ebb46-8c86-11e5-9500-3791b29400fb.png)

As well, a similar type of functionality when you want to quickly go through commits, review changes, pull requests, etc. would also be extremely helpful.

![github-annoyances2](https://cloud.githubusercontent.com/assets/820947/11197029/a53bcef4-8c88-11e5-8df6-28f0b613c537.png)

**Comment by sindresorhus** [comment]
Would definitely be useful, but there were some issues with implementing it previously: https://github.com/sindresorhus/refined-github/pull/299

Related issue → https://github.com/sindresorhus/refined-github/issues/152, but only for keyboard shortcuts.

**Comment by hkdobrev** [comment]
In terms of UI and specific shortcuts, commits in pull requests now have this with Next/Prev buttons and <kbd>n</kbd> / <kbd>p</kbd> shortcuts.

**Comment by gnu-user** [comment]
I've read both, maybe I should just pester Github again and see if they'll ever get around to adding it. It's such a simple feature that it boggles my mind that none of their employees have gotten around to implementing out of frustration dealing with many issues.

One solution I did think of, would be perhaps scraping the list of issues from the main page and then keeping track of that state when you navigate through issues, this may be a possible workaround.

**Comment by hkdobrev** [comment]
@gnu-user I could see some reasoning why GitHub are not implementing it (besides that it's mostly useful for maintainers of popular packages or private projects). You can have filtering, and search, and sorting in issues listing and then you go to an issue and it's not always intuitive which issue is next and which is previous. Also, issues and PRs share the incremental IDs. Some users would expect the system to remember their search, others would not, some would even to go through adjacent ID disregarding if it's an issue or PR, open or closed.

The next/prev buttons on PR commits are quite easier from UX perspective as their predictable - Git commits has parents and therefore you have a linear history in a PR (in most cases).

**Comment by bfred-it** [comment]
Closing this as stale, hard to do and because of what @hkdobrev said

**Comment by iamandrewluca** [comment]
A proposal. If I will have some time, I'll try to start a PR.

Shortcuts used:
- `p` for previous
- `n` for next

Activate shortcuts only when on issue or pull request page.  
And [`document.referrer`](https://developer.mozilla.org/en-US/docs/Web/API/Document/referrer) is a issue list or pull request list page.

GitHub is reflecting in URL filters used for issue or pull request list.  
Using `document.referrer` we can extract the filters and query GraphQL API, to get the list of filtered issues or pull requests, and navigate through them.

User flow:
- Go to issues or pull requests list page
- Apply some filters
- Open a issue or pull request from the list
- Expect shortcuts to navigate through issue or pull requests with previous filters

**Comment by iamandrewluca** [comment]
Status update:

I tried a implementation here https://github.com/iamandrewluca/refined-github/commit/3f54cf968de54a3683d787befdd8e2a8d0bb19d8 I almost want to give up on this :slightly_smiling_face: 

It kind of works, there are may be still some edge cases.
Also there is some different behaviour between issues and pull requests
because issues navigation does a full page navigate, pull request do a ajax navigation.

Maybe I'll come back to it later, who wants to give a try and improve the implementation feel free to copy it.

**Comment by fregante** [comment]
> Also there is the case, when you fetch a page from a discussion list,
> and a new discussion was added to that list query, on next page fetch,
> you may get an issue from previous page. This is a known issue with offset pagination.

Yeah that sucks but the only solution would be to fetch after the user clicks the button… which sounds a little slow.

You can open a new draft PR and avoid force-pushing new commits, it makes reviewing harder and causes this mess:
<img width="466" alt="" src="https://user-images.githubusercontent.com/1402241/81598441-97a26a00-93c7-11ea-8a10-699058fd83f9.png">

Anyway, it seems to work great and without issues. The code can be improved.

A couple problems I found:

- we can't use the a global `cache` to store data because if you open 2 issues from 2 repos they will try to use the same cache and fail. My suggestion is to append parameters to the next-prev, for example

**Comment by fregante** [comment]
Any updates @iamandrewluca?

**Comment by iamandrewluca** [comment]
@fregante Unfortunately no. Someday maybe I'll retry the PR. Till then whoever wants, feel free to experiment with that PR.

**Comment by fregante** [comment]
I wonder if this feature can actually exist without it being frustrating. There are multiple possible conflicting expectations of how this should work:
- should navigate by issue number? i.e. #333 is followed by #334 and preceded by #332 
- should it use the exact order of the _last seen list_ or should it query at every navigation?
  - former: we have load the entire list from the API and if the tab remains open for a while, the stored order might become completely out of date.
  - latter: impossible, what does it do if the current discussion leaves the list? (e.g. the list is `is:open` but the current issue has just been closed)

I think we should give up on this. What I usually do is "Open all" issues and deal with the tabs in order. This has a clear beginning and end and it's visual, the list will stay in the tab bar, not hidden behind **Prev/Next** buttons.

**Comment by fregante** [comment]
I'll close this, I think this feature will give us headaches. 

@iamandrewluca if you want the feature, feel free to publish your current code as a standalone, I'm sure many will disagree and accept the compromise:

1. Unfork the repository
2. Drop every other feature
3. Drop the options list
4. Update the readme/manifest/name/deployment
5. Publish as a standalone extension
