### ISSUE TITLE
Add feature to toggle visibility of inline Check annotations on Files tab

### ISSUE THREAD

**Issue by orrc** [sindresorhus/refined-github#3431]
When a [Check run](https://developer.github.com/v3/checks/runs/) adds annotations to files in a PR, they take up quite a lot of space on the Files tab.
There doesn't currently appear to be any way to dismiss, collapse, or otherwise hide these annotations.

It would be nice to have a feature that has annotations collapsed by default, with the option to expand them individually (or all, via Alt-click), and then collapse them again.

**Example PR with annotations:**
https://github.com/XiongKezhi/codingstyle/pull/4/files#diff-835eeb0e6f1f24bdcb7fb2ec14495a29

**Screenshot from that PR:**
![image](https://user-images.githubusercontent.com/138615/89215418-f17e8e80-d5c8-11ea-944a-d9efbfca2023.png)
(the icon placed waaay over on the top-right of the annotation just links to the Checks tab; I can't see any option to hide the annotation)

**Potential mockup:**
![image](https://user-images.githubusercontent.com/138615/89217968-723f8980-d5cd-11ea-907f-0954769f9f94.png)

---

I guess that actually _dismissing_ annotations should probably be a GitHub-native feature, similar to the "Viewed" checkbox for files. But either way, it would be nice to to make diffs readable when faced with annotations.

**Comment by fregante** [comment]
Definitely. I feel that they should disappear with <kbd>i</kbd> just like the review comments do.

Implementing this safely might be a little difficult though.  Try also sending this feature request to GitHub: https://support.github.com/contact

**Comment by jglick** [comment]
https://github.com/jenkinsci/plugin-pom/pull/356 was largely motivated by unwanted annotations.

**Comment by fregante** [comment]
https://twitter.com/natfriedman/status/1366417484698578953?s=20

It’s <kbd>a</kbd>
