### ISSUE TITLE
Turn fork PR into local branch PR that can run CI with secrets

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#3434]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2410%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/refined-github/issues/3434)

Github Actions does not allow running CI for PRs from forks, as a user could extract secrets and other credentials by sending them to a remote location in the code. That makes sense and is a good default.

But sometimes it would be neat to be able to do that anyway: The diff of the PR is small enough to be reviewed, and then you are just missing a button to trigger that CI to double check that your tests are still passing.

An example: https://github.com/prisma/e2e-tests/pull/664

Refined Github could offer a button "Turn fork PR into local PR" or similar, that creates a new PR with the same code changes as the PR from the fork, a "closes #123" for the original PR and adds appropriate `Co-Authored by` attribution to the commit message or PR content. 

This PR would get a normal CI run and could be safely merged with confidence.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $10.00)

- [<img src='https://avatars0.githubusercontent.com/u/183673?v=4' alt='janpio' width=24 height=24> janpio](https://issuehunt.io/u/janpio) ($10.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/refined-github/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by fregante** [comment]
The easiest way to accomplish this I can think of is, one API call at a time:

1. Create a branch on `origin`
2. Change the PR base to that new branch
3. Merge the current PR into it, possibly as a "rebase" so commits are preserved
4. Open a new PR from that new branch

This is a _niche and substantial_ feature, which is a bad combination as far as Refined GitHub is concerned.
