### ISSUE TITLE
Make file view in Pull Request show "file added/modified/deleted" status

### ISSUE THREAD

**Issue by zbs** [sindresorhus/refined-github#3438]
When reviewing a PR and viewing all the files (with diffs collapsed) it's difficult to quickly tell which files were added/modified/removed. Some sort of status indicator, such as the A/M/D output in `git show --raw`, would be ideal.

**Comment by fregante** [comment]
Not a bad idea. We could just cross ~~deleted files~~ and make **added files** somehow. The rest of them would be unchanged.

The unfortunate part is that I don't think the page tells us whether a file is **added** at all, so we'd have to query the API for them ☹️

**Comment by yakov116** [comment]
Can't we see from here?

![image](https://user-images.githubusercontent.com/16872793/89593239-9e047e80-d81c-11ea-895c-6da39d684e29.png)

**Comment by fregante** [comment]
Indeed we can! But that's also loaded on demand, here's the fragment for example: https://github.com/sindresorhus/refined-github/pull/3420/show_toc?base_sha=0706bf161fa63580d628887d780af61901187703&sha1=0706bf161fa63580d628887d780af61901187703&sha2=1c5494edcf4be3678cf47f9c7ca2b4b98f0b7403

**Comment by zbs** [comment]
> Indeed we can! But that's also loaded on demand, here's the fragment for example: https://github.com/sindresorhus/refined-github/pull/3420/show_toc?base_sha=0706bf161fa63580d628887d780af61901187703&sha1=0706bf161fa63580d628887d780af61901187703&sha2=1c5494edcf4be3678cf47f9c7ca2b4b98f0b7403

We can make the same network call that is triggered by clicking the button. I looked in the DevTools network tab and saw a call to `/show-toc?...other_get_parameters`.

**Comment by kidonng** [comment]
> Not a bad idea. We could just cross ~deleted files~ and make **added files** somehow. The rest of them would be unchanged.

I like @fregante's idea. I think adding an icon like in #3439 is redundant because the diffstat blocks are distinct enough. Also this can apply to all commits, not just PR.

**Comment by yakov116** [comment]
> because the diffstat blocks are distinct enough

👎

**Comment by kidonng** [comment]
Well, how about change the filename's color like in `git diff`

**Comment by yakov116** [comment]
I am ok with that.

@fregante WDYT?

**Comment by kidonng** [comment]
What it may look like:

![image](https://user-images.githubusercontent.com/44045911/89739021-c35ceb00-daaf-11ea-8f32-0bdca958e5dc.png)

**Comment by yakov116** [comment]
Just because a file does not have deletions does not mean that its a new file...

**Comment by kidonng** [comment]
> Just because a file does not have deletions does not mean that its a new file...

So what's wrong with the code?

**Comment by zbs** [comment]
I think there's a lot less inference required if you parse the results of the "jump to..." network call. For example, the modification icon, which looks like this:
![image](https://user-images.githubusercontent.com/1444551/89739761-4ef35f00-da51-11ea-88f0-d9575c0a7b92.png)
Has the following SVG:
```
<svg class="octicon octicon-diff-modified select-menu-item-icon" title="modified" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true">...</svg>
```
We could simply parse the `title="modified"` attribute.

**Comment by kidonng** [comment]
> if you parse the results of the "jump to..." network call

But parsing diff blocks works on regular commits as well.

**Comment by yakov116** [comment]
If it is accepted to add to regular commits we can take it from.

![image](https://user-images.githubusercontent.com/16872793/89740109-199c4080-da54-11ea-8bd9-6872ee9d5099.png)

**Comment by kidonng** [comment]
> If it is accepted to add to regular commits we can take it from.

That means separate logic for the two pages, and also it will need to loop through A list of elements to get status and change B list of filenames, which is inefficient than just matching substrings.

**Comment by yakov116** [comment]
> hat means separate logic for the two pages (the PR one has lazyload logic while the one on commit page doesn't), and also it will need to loop through A list of elements to get status and then change B list of filenames, which is inefficient than just selecting diffblocks and matching substrings.

???

Did you see the pr?

**Comment by fregante** [comment]
I think the icons as designed in https://github.com/sindresorhus/refined-github/pull/3439 are clean and clear enough. Coloring the text might be a bit much.

**Comment by fregante** [comment]
@kidonng the information we’re targeting is not available on the the PR Files page. We’re only highlighting CREATED and DELETED files, not just “all green” and “all red” files. 

As for the regular commits page, I think it’s *as easy as*

``` 
if isPRFiles
  await deferred
else
  // nothing, it’s already on the page

**Comment by kidonng** [comment]
> We’re only highlighting CREATED and DELETED files, not just “all green” and “all red” files

My fault. Sorry @yakov116!
