### ISSUE TITLE
Easy remove of labels

### ISSUE THREAD

**Issue by AuHau** [sindresorhus/refined-github#3440]
I would like to propose a simple enhancement that would make removing labels from Issues very easy.

When would you hover over label simple crosshair would appear at the edge of the label which opon clicking on it, it would remove the label from the Issue. This would be restricted only to those who have rights to change labels in the repo.

Currently, you have to open the labels popup, find the right issue and then remove it. I find this flow very cumbersome while managing my Issues.

Happy to write PR for it if it would be accepted.

**Comment by fregante** [comment]
It doesn't sound like a bad idea. You're welcome to send a PR
