### ISSUE TITLE
Add a option: fold the repo file list by default

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3452]
![208_10225118](https://user-images.githubusercontent.com/10995302/89796955-e396b380-db5c-11ea-9187-361f59626e3b.png)
<details>
<summary>Details</summary>

![demo](https://user-images.githubusercontent.com/1402241/35480123-68b9af1a-043a-11e8-8934-3ead3cff8328.gif)

</details>

Can  add an option:  ✅ fold the repo file list **by default** !
> After the page is reloaded, it is also fold/collapsed by **default**.
> Click to expand only when need to view it.
![208_10230331](https://user-images.githubusercontent.com/10995302/89797654-c1e9fc00-db5d-11ea-9210-f436ef1adf2f.png)

**Comment by fregante** [comment]
No options available in RG: https://github.com/sindresorhus/refined-github/issues/2960

> ## 3. It doesn't require options.
> 
> Anything that requires configuration most likely does not belong to Refined GitHub. It’s just extra complexity and we already have 130+ features to attend to.
> 
> Imagine you want a feature to be "per branch", someone else wants it "per organization", etc. The options’ UI would just balloon because of different needs.

If you know some CSS, you can achieve what you need by writing the opposite of this and pasting it in the CSS field in the options:

https://github.com/sindresorhus/refined-github/blob/ecad0ae6b0c8929ee264f5e810bd27511c6ece2b/source/features/toggle-files-button.css#L7-L19

**Comment by dnknn** [comment]
> If you know some CSS, you can achieve what you need by writing the opposite of this and pasting it in the CSS field in the options:

@fregante 
I added this 🅲🆂🆂 code to Refined GitHub options, then, it doesn't work (invalid)
![208_10235431](https://user-images.githubusercontent.com/10995302/89803007-d978b300-db64-11ea-9554-79b247f705bf.png)

I also tried to add it to `Stylus` extension, and found that it didn't work also.

**Comment by dnknn** [comment]
I understand what you mean, I will try to write reverse CSS to see if it can be achieved

**Comment by fregante** [comment]
Excellent! Thanks for sharing the CSS

**Comment by dnknn** [comment]
I updated it on it, and users who need it can take it directly.
