### ISSUE TITLE
Show Pending Comments Overview in PR Review

### ISSUE THREAD

**Issue by zbs** [sindresorhus/refined-github#3453]
Before finishing a review iteration, it would be great to see all pending comments shown in one place. For example, instead of this:
![Picture](https://i.imgur.com/h8LHA0A.png)

It would be great to show the list of pending comments, so you can quickly double-check your comments instead of having to walk through all the files, which could be cumbersome in PRs spanning numerous files.

**Comment by fregante** [comment]
They’re already waiting for you in the Conversation tab

**Comment by mruhlin** [comment]
^ note that you have to reload the page for those to be visible.  If you open up a PR, make a bunch of pending comments, then tab back over to the conversations tab, you'll still see a cached version of the conversation that doesn't include them (in Firefox, at least)

**Comment by geoffromer** [comment]
> They’re already waiting for you in the Conversation tab

Not necessarily. If they're replies to existing comments, they don't show up neatly at the bottom like in that screenshot; instead they appear attached to the comments you're replying to, which could be anywhere in the Conversation history (including hidden behind a "Load more..."). Worse, if someone marked a comment thread resolved, your reply won't be visible in the Conversation view at all, unless you manually go through and expand resolved comments until you find it. For PRs with extensive discussions, this can be very onerous.

**Comment by fregante** [comment]
### This issue was closed 3 years ago. Please consider opening a new issue instead of leaving a comment here.
