### ISSUE TITLE
`keyboard-navigation` is slightly broken in some PRs with reviews

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3457]
1. Visit ~~https://github.com/sindresorhus/refined-github/pull/3454~~ (Edit: can't replicate here anymore, I don't know what's causing the issue)
2. Press J multiple times

You'll notice that it gets stuck on my first review, even if there are more comments below.

Hard to show in a gif, but here's what it looks like (I'm pressing JJJJKJJJJJ)

![](https://user-images.githubusercontent.com/1402241/90073718-9e57ba80-dcf1-11ea-87f2-77adee17185c.gif)

I can't replicate this issue in every PR, I don't know what's blocking it here

**Comment by dertieran** [comment]
Found some other PRs where it doesn't seem to work correctly:
- #3497 
- #3482 
- #3421
