### ISSUE TITLE
Edit CSV file using table editor

### ISSUE THREAD

**Issue by zhang699** [sindresorhus/refined-github#3459]
since github has [rendering-csv-and-tsv-data](https://docs.github.com/en/github/managing-files-in-a-repository/rendering-csv-and-tsv-data) feature, but cannot render it when editing by clicking the pen icon. 

- it it very convenient for table editor cause the presentation is easier to edit than comma-separated

![截圖 2020-08-13 下午12 02 50](https://user-images.githubusercontent.com/5291552/90093284-d399f200-dd5d-11ea-9400-7bc81b7010d4.png)

By the way, I doesn't know github if has roadmap to support it.

there is no public roadmap found for it : https://github.com/github/roadmap/projects/1?card_filter_query=csv

my test repo: https://github.com/zhang699/csv-repo/blob/master/test.csv

**Comment by fregante** [comment]
This would be interesting, but it needs a whole editor to add/delete columns and UI to configure CSV parsing; We can’t add it to Refined GitHub
