### ISSUE TITLE
Add the most recent edit time next to the `edited` button 

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3460]
Add the most recent edit time next to the `edited` button for every edited comment. 
![image](https://user-images.githubusercontent.com/49396421/90108526-08697180-dd7d-11ea-8519-8728bf8cc11d.png)
What’s more, I hope that tooltip would show the exact time when the mouse hovers over the edit time.

**Comment by fregante** [comment]
GitHub used to have this natively, I don’t know why they removed it, maybe because it makes the header text too long. 

In our case this needs an API call for each edited comment, is this information worth it the call and the extra text?

**Comment by Geeyun-JY3** [comment]
> GitHub used to have this natively

What a pity😑. And I don’t know this actually. Embarrassing🤦‍♂️.

I think this information worth it.

My reason is that I can see the update time in the issue tab (if I sort it), but I cannot get what has been changed quickly if it refered to an edited comment.

**Comment by fregante** [comment]
> My reason is that I can see the update time in the issue tab (if I sort it), but I cannot get what has been changed quickly if it refered to an edited comment.

In that case you'd have to scroll the entire thread and look for the edited date: It's still not efficient.

I had that problem too, what if we highlight the "latest changes" instead? For example by adding a "Latest comment" bubble like we do for `highlight-highest-rated-comment` 

<img width="789" alt="" src="https://user-images.githubusercontent.com/1402241/90143133-2501ab80-dd75-11ea-8440-6f989b3dbc77.png">

Instead of adding it at the top of the page, we add it at the bottom **IF** the bottommost comment is not the latest comment.

**Comment by Geeyun-JY3** [comment]
> what if we highlight the "latest changes" instead? For example by adding a "Latest comment" bubble like we do for `highlight-highest-rated-comment`
> 
> Instead of adding it at the top of the page, we add it at the bottom **IF** the bottommost comment is not the latest comment.

I think this is an acceptable alternative solution😄.

**Comment by fregante** [comment]
Closing in favor https://github.com/sindresorhus/refined-github/issues/3462

**Comment by Geeyun-JY3** [comment]
I come up with another feature request relating to the latest comment:
Change the update information`updated <time> ago/ on <date>` to `updated <time> ago/ on <date> by ***` in issue lists if sorted by update date, and make it clickable, linking to "Latest comment" bubble you have mentioned above.
(Would it be a kind of duplicate feature of the `open-issue-to-latest-comment`🤔? Though I still hope this feature can be added.)
