### ISSUE TITLE
`open-issue-to-latest-comment` doesn't work consistently

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3469]
Make the “comment” icon and “star”icon in `https://github.com/` clickable.
1. Makes the “comment” icon in `https://github.com/` link to the latest comment of the issue.
![image](https://user-images.githubusercontent.com/49396421/90413621-4a7a1680-e0e1-11ea-92e8-cc06d7c4f020.png)
2. Makes the “comment” icon in `https://github.com/` link to the Stargazers page of the repository.
![image](https://user-images.githubusercontent.com/49396421/90416158-b1e59580-e0e4-11ea-98f3-1ebf91c0c0ce.png)

**Comment by fregante** [comment]
The comments icon should already be clickable and it should point to the last comment on the page. It’s one of our features. 

Looking at a list of stargazers doesn’t seem very useful.

**Comment by fregante** [comment]
This is the feature: https://github.com/sindresorhus/refined-github/blob/master/source/features/open-issue-to-latest-comment.tsx

**Comment by fregante** [comment]
> This is the feature: [https://github.com/sindresorhus/refined-github/blob/master/source/features/open-issue-to-latest-comment.tsx](https://github.com/sindresorhus/refined-github/blob/master/source/features/open-issue-to-latest-comment.tsx?rgh-link-date=2020-08-17T17%3A02%3A33Z)

I tested and it works

**Comment by Geeyun-JY3** [comment]
That’s strange. I remembered it doesn’t work sometimes🤦‍♂️. Perhaps I am wrong.

**Comment by Geeyun-JY3** [comment]
@fregante I have recorded a GIF which shows that it doesn’t work sometimes: 
![ggg](https://user-images.githubusercontent.com/49396421/90763089-b1354500-e318-11ea-8432-fa3d323e1538.gif)
Maybe something wrong with this feature?

**Comment by Geeyun-JY3** [comment]
I cannot reproduced it all the time actually.

**Comment by fregante** [comment]
@yakov116 can you replicate this issue? If yes, perhaps `selector-observer` could help (Dashboard features could all probably benefit from it)

**Comment by yakov116** [comment]
I can't but definitely it would gain from select observer. I think all dashboard features should be moved to select-observer. 
This is the perfect use case as they all are looking for events that happen after dom ready.
