### ISSUE TITLE
Number of forks is not visible

### ISSUE THREAD

**Issue by gingerbeardman** [sindresorhus/refined-github#3470]
Bug
- Number of forks is not visible

Explanation
- I use the number of forks as a button to see all available forks of the repo.

URL
- https://github.com/sindresorhus/refined-github

SCREENS

- ![Screen shot 2020-08-17 at 16 59 18](https://user-images.githubusercontent.com/49612/90417482-aa55ca80-e0ab-11ea-9558-89050cd9d8bf.png)

- ![Screen shot 2020-08-17 at 16 59 43](https://user-images.githubusercontent.com/49612/90417486-ab86f780-e0ab-11ea-9e77-81f1de600a12.png)

NOTES
- number of Watches is also hidden.

**Comment by fregante** [comment]
It’s a feature. It can be disabled
