### ISSUE TITLE
Increase the number showing how many forks there are in total

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#3475]
page of  `{repo}/network/members`   
Can the number showing how many forks there are in total ?

![208_18071842](https://user-images.githubusercontent.com/10995302/90453385-10316900-e123-11ea-9a2f-fa5847733e6d.png)

**Comment by fregante** [comment]
GitHub already shows it in the upper-right corner of every repository page. 
Refined GitHub hides it with `hide-watch-and-fork-count`

If you want the number, disable `hide-watch-and-fork-count`

**Comment by dnknn** [comment]
Haha, I'm sorry, I was wrong. It turns out that 🐈github officially has this function.
