### ISSUE TITLE
Why is the "Clone in Desktop" disabled?

### ISSUE THREAD

**Issue by dudeofawesome** [sindresorhus/refined-github#348]
I see that #38 intentionally disabled the "Clone in Desktop" button. What is the reasoning for this?

**Comment by jacobbearden** [comment]
The main contributors of the project, and afaik most people, use the command line rather than a desktop application. Because of this the "Open in Desktop" button was likely deemed unnecessary.

**Comment by dudeofawesome** [comment]
Oh, I forgot there were buttons on each file for opening in desktop. Those ones are kinda pointless.

The main one I'm concerned about is the one in the "Clone or Download" pane on the main page of a repo.

![image](https://cloud.githubusercontent.com/assets/1683595/21830352/f2bfbdc0-d750-11e6-8257-d0ac6ea52d7b.png)

Looks kinda odd with a half-width button there.

**Comment by sindresorhus** [comment]
> The main contributors of the project use the command line rather than a desktop application. Because of this the "Open in Desktop" button was likely deemed unnecessary.

Yes

**Comment by hkdobrev** [comment]
@dudeofawesome You can just copy-paste the URL from the browser, it works.

**Comment by dudeofawesome** [comment]
I feel like the "Clone in Desktop" button inside the "Clone or Download" popover isn't useless, 
![image](https://cloud.githubusercontent.com/assets/1683595/21863150/23d5aa50-d7f1-11e6-85c4-ab9c2f8fdddf.png)
especially for people who use the Github Desktop app, who would otherwise have to clone through the CLI and then open up the Github Desktop app and manually add the repo to the app.


Again, I agree that the Clone buttons on each file are basically useless and should be gone.
![image](https://cloud.githubusercontent.com/assets/1683595/21863673/3f7ca8e2-d7f3-11e6-9c48-5662516dd9be.png)


Regardless, if you still feel that there shouldn't be any "Clone in Desktop" button anywhere, then the "Download ZIP" button should be full-width in the popover.

![image](https://cloud.githubusercontent.com/assets/1683595/21863637/1edb44a4-d7f3-11e6-8ad5-403fcfdcd580.png)


@hkdobrev Where are you suggesting to paste the git URL?
