### ISSUE TITLE
Linkifies branch reference incorrect when repo was renamed

### ISSUE THREAD

**Issue by derimagia** [sindresorhus/refined-github#349]
Example link: https://github.com/terminus-plugin-project/terminus-pancakes-plugin/pull/17

Notice the url is incorrect and 404s for the PR branch since it was renamed mid-pull request.

Not sure if this is possible to fix, but I didn't see any issue for it after some searching.

**Comment by hkdobrev** [comment]
This would be fixed with #422. @derimagia Could you please take a look at it? Thanks!

**Comment by derimagia** [comment]
LGTM! Works like a charm.
