### ISSUE TITLE
`hide-readme-header` needs more padding

### ISSUE THREAD

**Issue by probablykasper** [sindresorhus/refined-github#3495]
Not sure if this should be a bug report or feature request, but as you can see here, no feature toggle shows up when searching for `hide-readme-header`:

![image](https://user-images.githubusercontent.com/11315492/90992111-e0181900-e5ad-11ea-909f-dcc35121f597.png)

**Comment by fregante** [comment]
This is such a minor visual adjustment that doesn’t need a toggle. Why do you want to disable it?

**Comment by probablykasper** [comment]
@farnabaz Because I don't like the lack of padding
![image](https://user-images.githubusercontent.com/11315492/90995464-57ed4000-e5bc-11ea-878e-49e4fbbd3c29.png)

**Comment by fregante** [comment]
Can you post a link to that repo? It should not appear so close to the border

**Comment by probablykasper** [comment]
@fregante Turns out a the padding is decreased a little by the [GitHub Dark](https://github.com/StylishThemes/GitHub-Dark). Without it, it's still pretty minimal padding though:

![image](https://user-images.githubusercontent.com/11315492/91003146-dd7aeb00-e5d0-11ea-906e-dacffa08943d.png)

Repo: https://github.com/probablykasper/vidl

**Comment by fregante** [comment]
I think that this can be solved by adding `padding-top: 30px` to `.Box-body`
