### ISSUE TITLE
`clone-branch` is broken on GHE

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#3499]
The selectors used do not exist on GHE 2.20. I've never had need for the functionality, so never cared, but noticed it is throwing an exception today.

```
❌ Refined GitHub → clone-branch → TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at observeElement (refined-github.js:3399)
    at init (refined-github.js:8942)
    at runFeature (refined-github.js:2898)
    at setupPageLoad (refined-github.js:2906)
    at HTMLDocument.<anonymous> (refined-github.js:2943) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Failed%20to%20execute%20'observe'%20on%20'MutationObserver'%3A%20parameter%201%20is%20not%20of%20type%20'Node'.
```

Upgrading to 2.21 is on the docket for "soon", maybe the markup will finally be updated. Otherwise opening for awareness and I'll address it when I get a chance.

**Comment by yakov116** [comment]
Can you see what the selector is?

![image](https://user-images.githubusercontent.com/16872793/91083298-0bcfe900-e618-11ea-83b2-5f6ed260eaf3.png)

**Comment by yakov116** [comment]
@busches please check this tomorrow when the next released is out. We changed the way it works and you should not get an error.

**Comment by yakov116** [comment]
@busches is this still an issue?

**Comment by busches** [comment]
@yakov116 probably. I will hopefully get some time to look into everything enterprise in the coming weeks.

**Comment by busches** [comment]
FYI, saw this was working today.
