### ISSUE TITLE
Add link to Chrome web store in GitHub repo URL

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#35]
There is a link to install the repo from the web store in the readme, but we can make use of the URL next to the repo description on the top. This could make it easier for new people to go the web store and install it to try it out.

https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

@sindresorhus Only people able to edit the repo settings can edit the repo description and URL.

**Comment by paulmolluzzo** [comment]
:+1:

**Comment by sindresorhus** [comment]
Done
