### ISSUE TITLE
Showing and disabling features on Firefox does not work on GH Enterprise

### ISSUE THREAD

**Issue by zachwhaley** [sindresorhus/refined-github#3501]
I have the `clear-pr-merge-commit-message` feature disabled in refined-github, however it continues to work on my companies GitHub enterprise instance.  Also, refined-github is not printing to the console the list of enabled/disabled features 😕 

I tried to showcase that the feature was not disabled by adding a breakpoint in refined-github where I think I could verify this; see below.

![Screen Shot 2020-08-25 at 10 10 56 AM](https://user-images.githubusercontent.com/2996465/91192219-4d65a000-e6bb-11ea-8fed-60c318f1f047.png)

![Screen Shot 2020-08-25 at 10 09 06 AM](https://user-images.githubusercontent.com/2996465/91191971-07104100-e6bb-11ea-83e4-86caaaf8ebd5.png)

This is working fine on github.com

![Screen Shot 2020-08-25 at 10 09 52 AM](https://user-images.githubusercontent.com/2996465/91192105-2d35e100-e6bb-11ea-8d27-ed8448c0e0ac.png)

**Comment by busches** [comment]
Features are per domain, so I just want to confirm you swapped the domain dropdown before turning off the feature and having it log them out.

**Comment by zachwhaley** [comment]
I totally forgot this. That was it 😝 

Thanks!
