### ISSUE TITLE
Alignment Issue on Pull Request Page

### ISSUE THREAD

**Issue by stenalpjolly** [sindresorhus/refined-github#3502]
![image](https://user-images.githubusercontent.com/8219855/91338906-4772da80-e7f3-11ea-85f9-c3e91a5a79c3.png)

**Browser: Chrome 84**

![image](https://user-images.githubusercontent.com/8219855/91338951-5bb6d780-e7f3-11ea-9f23-3160e337ff89.png)

**Comment by fregante** [comment]
This can't happen because that element has `display: flex` without a wrap. 

Can't replicate:
![a2a](https://user-images.githubusercontent.com/1402241/91346643-d4189b00-e7e9-11ea-9966-1658d82869c5.gif)

**Comment by busches** [comment]
I can recreate this on GHE, it didn't appear to have the style that I saw at quick glance. If I get some free time I can dig into it, but this isn't a page I use.

**Comment by fregante** [comment]
The fix is simple if anyone has GHE: we likely just need to add `display: flex` to the right element. The CSS goes in this file:

https://github.com/sindresorhus/refined-github/blob/master/source/features/global-conversation-list-filters.css

**Comment by fregante** [comment]
Nobody fixed it in 6 months, closing because it's more likely that GHE has been updated or will be updated sooner than this is fixed.
