### ISSUE TITLE
Black square in options tab.

### ISSUE THREAD

**Issue by uKaigo** [sindresorhus/refined-github#3506]
## Report
Hi! There's a black square with a HUGE scroll in the "Options" section, I don't know if it's a bug of the browser or of the extension, but I'm reporting here first.

Screenshot
![Black square](https://i.imgur.com/MJii2DP.png)

## System Information

- **Browser:** Firefox v80.0 (64-bit)
- **Extension:** v20.8.23
- **OS:** Windows 10 Pro x64 v1909

**Comment by fregante** [comment]
Can you try reloading the page? Firefox’ add-ons page is a little buggy sometimes

**Comment by uKaigo** [comment]
I reloaded the page, and restarted both browser and pc. It's still not working.

But when I open the options tab for the first time in the session, it shows the options for a sec and the black square appears.

**Comment by fregante** [comment]
I sue the same configuration except it's on Mac:

<img width="775" alt="Screen Shot 2020-08-28 at 01 02 47" src="https://user-images.githubusercontent.com/1402241/91499520-3943bd80-e8ca-11ea-98db-4fe1ab832fa4.png">

Can you open this page directly and see if it works there? moz-extension://e9494ddf-4135-504b-90e9-82ced8cb8b15/options.html

**Comment by fregante** [comment]
Possible? https://support.mozilla.org/en-US/questions/1034763

**Comment by fregante** [comment]
This is not a bug we can fix, it's likely to be another extension conflicting

**Comment by uKaigo** [comment]
I created a new profile without themes and extensions (only refined-github). It still occurs. But i'll send a report to firefox.
