### ISSUE TITLE
Hiding comment toolbar removes ability to upload images

### ISSUE THREAD

**Issue by alexkrolick** [sindresorhus/refined-github#351]

**Comment by sindresorhus** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/136, but I would be willing to add it back if someone would make it more subtle and nice looking. Maybe using an icon instead.

**Comment by pmbenjamin** [comment]
@sindresorhus would you be open to perhaps the keyboard shortcut: `⌘ + u`

**Comment by sindresorhus** [comment]
Sure

**Comment by Loilo** [comment]
Just for the record: You can still insert an image via plain ol' `⌘V` resp. `Ctrl + V`.

**Comment by hkdobrev** [comment]
> You can still insert an image via plain ol' `⌘V` resp. `Ctrl + V`.

Actually, I didn't know that! I was always using drag-n-drop. Thanks for the tip!

**Comment by Loilo** [comment]
I was actually only trying it out today for the and it worked. Not sure if it has been around for long. :)

**Comment by Loilo** [comment]
However, it makes snipping & pasting screen shots blast! 👍

**Comment by sindresorhus** [comment]
Cmd+V is useful, but for some reason it doesn't work with GIF. They end up as static PNG. I think it's Chrome being dumb though.

**Comment by alexkrolick** [comment]
Yeah, I think the image pasteboard does that. I've been using drag n drop,
but it's a pain with full screen windows.

**Comment by sindresorhus** [comment]
@alexkrolick https://twitter.com/sindresorhus/status/862584385534435328
