### ISSUE TITLE
`recently-pushed-branches-enhancements` may cause duplicate banners

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3518]
URL: https://github.com/sindresorhus/refined-github
Screenshot: ![image](https://user-images.githubusercontent.com/44045911/91540535-8321b780-e94d-11ea-814f-5e1ca9fd6b59.png)

I can't always replicate this, but it happened to me yesterday as well so I think it's better to report it here.

**Comment by fregante** [comment]
I've never seen this happen. The position seems peculiar

**Comment by fregante** [comment]
I think this happened:

1. the bar is added/moved to the header
2. the native bar loads, but is **not** moved/removed as it should: https://github.com/sindresorhus/refined-github/blob/835b0a0d6d1b5cbb60e7a93cf43b3535602e599e/source/features/recently-pushed-branches-enhancements.tsx#L19

**Comment by kidonng** [comment]
#3748
