### ISSUE TITLE
duplicated #js-repo-pjax-container for empty project on Issues Page

### ISSUE THREAD

**Issue by leocaseiro** [sindresorhus/refined-github#352]
Something is happening on the issues page for empty projects.

To reproduce this behaviour, follow these steps:

1. Create a new repository without readme
2. Go to Issues page

![screen shot 2017-02-08 at 12 42 52 pm](https://cloud.githubusercontent.com/assets/940070/22719949/292b3986-edfc-11e6-9eaf-3ec4e597bbed.png)

**Comment by hkdobrev** [comment]
This has been previously reported in #216 and #259 and fixed in #258. It seems we have a regression and it's now reproducing again.
