### ISSUE TITLE
Add Copy Button to branch name after merge & should only copy branch name without username 

### ISSUE THREAD

**Issue by muescha** [sindresorhus/refined-github#3522]
### what:

1) when a PR is merged then i can delete my branch. add here a copy button
2) both copy buttons should only copy the value without my username

### why: 

with that i can past it direct into a `git branch -d ` or past it into the git branches dialog in WebStorm

### screenshots:
<img width="470" alt="Bildschirmfoto 2020-08-31 um 21 04 00" src="https://user-images.githubusercontent.com/184316/91863168-1bca7700-ec6f-11ea-8fa5-e53ab3cfea6d.png">
<img width="375" alt="Bildschirmfoto 2020-08-31 um 21 03 17" src="https://user-images.githubusercontent.com/184316/91863180-1ff69480-ec6f-11ea-9431-316b04bbbc09.png">

**Comment by fregante** [comment]
We consider those copy buttons useless and were initially rejected as a feature: https://github.com/sindresorhus/refined-github/issues/77

For the same reason, we won't extend them.

Also, if you want to deleted local branches that don't exist on the remote, there's a git command that does that automatically (I don't remember which one)
