### ISSUE TITLE
Add Search "In this organisation" also from in-repo search

### ISSUE THREAD

**Issue by ofirnk** [sindresorhus/refined-github#3524]
Allow searching for something in the same org even when I'm not in the org-view.

### Current:
I'm in a repo ( https://github.com/yeoman/yo ) and search for yo:
![image](https://user-images.githubusercontent.com/8449713/91867592-7cac7c00-ec7c-11ea-9a18-d1ad0f7cb689.png)

##### but if I'm in the org view like https://github.com/yeoman , I can search in org:
![image](https://user-images.githubusercontent.com/8449713/91867837-bbdacd00-ec7c-11ea-943e-5d17f03977dc.png)

### Wanted:
To be able to search in:
1. Current repo
2. In "this" org
3. All github

**Comment by yakov116** [comment]
Looks like this was added already by GH

![image](https://user-images.githubusercontent.com/16872793/108916098-c9ee2280-75fb-11eb-9fa1-a2c692c1e43f.png)

**Comment by fregante** [comment]
Indeed this already exists on both the Organizations page and in each repository:

<img width="634" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/108917518-7b3d8a00-75f5-11eb-9c33-10e752f99f5d.png">

**Comment by fregante** [comment]
I'm not sure why it's not showing for you:

<img width="638" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/108917582-93150e00-75f5-11eb-838d-3cca0b9f9a78.png">

**Comment by ofirnk** [comment]
Thanks, looks like Github added this natively :+1: 
(perhaps they follow issues in here)
