### ISSUE TITLE
Document outline for READMEs/markdown

### ISSUE THREAD

**Issue by tom-sherman** [sindresorhus/refined-github#3526]
As in Google Docs, an outline of the README floating to the side would be a massive help for navigation.

![image](https://user-images.githubusercontent.com/9257001/92145957-e78ebc00-ee10-11ea-8fb7-8dadc0ae9cb6.png)

This could potentially float on the left hand side on larger monitors, not sure about smaller ones though.

It should highlight in the outline which header section you are currently looking at too.

**Comment by fregante** [comment]
This already exists, likely called GitHub TOC or something like that.

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/151

**Comment by fregante** [comment]
There's however this open suggestion for something similar: https://github.com/sindresorhus/refined-github/issues/3224
