### ISSUE TITLE
Support compare diff URLs in `prevent-pr-commit-link-loss`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3528]
Copy-paste this URL in a comment a click "Preview"

```
https://github.com/sindresorhus/got/compare/v11.5.2...v11.6.0#diff-6be2971b2bb8dbf48d15ff680dd898b0R191
```

GitHub changes the URL to the following, breaking it

```
https://github.com/sindresorhus/got/compare/v11.5.2...v11.6.0diff-6be2971b2bb8dbf48d15ff680dd898b0R191
```

This is a similar GitHub bug to https://github.com/sindresorhus/refined-github/issues/2327, which was fixed by https://github.com/sindresorhus/refined-github/pull/3085 ([prevent-pr-commit-link-loss](https://github.com/sindresorhus/refined-github/blob/master/source/features/prevent-pr-commit-link-loss.tsx)), so it'd make sense to extend that feature

**Comment by esakki-selvaraj** [comment]
can I work on this issue?

**Comment by yakov116** [comment]
@esakki-selvaraj go for it!

**Comment by esakki-selvaraj** [comment]
@yakov116 Can i get some more links so that I can check my Reg Expression!

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/compare/20.9.11...master#diff-67ba01fa3e792891b585fa43e92c78ea

**Comment by fregante** [comment]
Keep in mind that there's already a pretty advanced regex (which avoids selecting the url twice) already set up:

https://github.com/sindresorhus/refined-github/blob/6d339762d762b669bb48b2977f40a83c48305a2d/source/github-helpers/index.ts#L98-L99

And tested:

https://github.com/sindresorhus/refined-github/blob/6d339762d762b669bb48b2977f40a83c48305a2d/source/github-helpers/index.ts#L98-L99

You should start from that regex: copy the regex, copy the tests (changing **only** the URLs) and make sure they pass.

**Comment by esakki-selvaraj** [comment]
@fregante  how to run the tests??

If I run npm run test it shows

 No files matching the pattern "'source/**/*.css'" were found.

**Comment by esakki-selvaraj** [comment]
But it's working when I'm doing it manually
