### ISSUE TITLE
`batch-open-conversations` on repo without access fires too early

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3534]
![image](https://user-images.githubusercontent.com/16872793/92327412-a0c6df00-f027-11ea-866f-0325c3ac4f9e.png)
Notice the last 2 do not have check boxes.

https://github.com/primer/octicons/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
Go into an issue and then click back
(The same happens on refined-github but gave an external link for maintainers to test)

The issue is `waitfordomready: false`. select-observer can be used or wait for domReady here ⬇️ 

https://github.com/sindresorhus/refined-github/blob/e1d836a2f542bb77e9510e5c5aaed2af8c572c91/source/features/batch-open-conversations.tsx#L83-L84

**Comment by fregante** [comment]
waitfordomready doesn’t make sense here because the last item is near the end of the page, so the DOM is ready a few milliseconds later anyway.

**Comment by yakov116** [comment]
@fregante I think there should be 2 inits. The if and the else do have anything in common. WDYT?

**Comment by fregante** [comment]
Agreed

**Comment by yakov116** [comment]
@fregante if we wait for dom ready there is a terrible jump
![Video_2020-09-06_173729](https://user-images.githubusercontent.com/16872793/92335738-e1464d00-f067-11ea-8f98-a3fad02adc3e.gif)

**Comment by yakov116** [comment]
https://github.com/yakov116/refined-github/commit/ee4b8637d3b55f6bfb95a226ffee0f04248716db WDYT?

**Comment by fregante** [comment]
I’m not accepting any more selector-observer refactoring until we figure out how to avoid https://github.com/sindresorhus/refined-github/issues/3527

Also I’m not particularly fond of this this looks. 

As an immediate solution, you can add a single line before the for loop: `await domLoaded`

The jump isn’t that big, we have other features that do the same, like `shorten-links` and `reaction-avatars`

**Comment by yakov116** [comment]
Yeah I agree. That why I didn't open a pr before asking.
https://github.com/yakov116/refined-github/commit/8aa9447d281a4ae2cab6ddc29d29de1eb13b2e7c what about that?

**Comment by fregante** [comment]
No, just the await `domLoaded`. Let's undo the rest, it's completely unnecessary

**Comment by fregante** [comment]
> you can add a single line
