### ISSUE TITLE
Enable/Disable All button for options

### ISSUE THREAD

**Issue by pastelmind** [sindresorhus/refined-github#3535]
Currently we have a large list of options. I'd like to enable only some of them and disable the rest, but going through all of them is very tedious. An "Enable/disable all" toggle button would be great.

Alternative ideas that would probably take more development resources:

- A filterable, sortable dynamic config list
- A search bar in the config page that supports filters like `is:disabled` or `is:enabled`

**Comment by fregante** [comment]
As said before:

> Refined GitHub adds features that benefit everyone or almost everyone, so we don’t expect people to look around and pick what they want.
> 
> You should only deactivate features if you find something you disagree with.

**Comment by fregante** [comment]
> * A search bar in the config page that supports filters like `is:disabled` or `is:enabled`

Disabled features float to the top automatically, just refresh the page
