### ISSUE TITLE
navigate thru pull request annotations

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#3536]
more and more checks in github actions or github marketplace add annotations to the 'Files Changed' tab.
these annotations are rendered inline with the corresponing sources lines when scrolling thru a PR, e.g.

![grafik](https://user-images.githubusercontent.com/120441/92384399-50777c00-f110-11ea-811d-5e016b882d02.png)

when PRs get long and it only contains a few annotations, its pretty time consuming to scroll thru the whole 'Files changed' tab from top to bottom, to find the actual spots so we can finally fix them.

wouldn't it be great to have a prev/next navigation, like we have in e.g. the merge-conflicts view to navigate the conflicting lines.

the nav I am talking about:
![grafik](https://user-images.githubusercontent.com/120441/92405843-ce4e7e00-f136-11ea-87d4-8dff764f89ae.png)

that way one could easily jump tru a PR from top to bottom - from annotation to annotation - and work thru them, without the manual hassle to find them first..

**Comment by fregante** [comment]
Could be a part of `keyboard-navigation`

**Comment by staabm** [comment]
> The issue template asks for one thing, please always include it so one doesn't have to scour GitHub to find it.
> 
> > 1. Include a full URL where the feature should appear.

I am really sorry. didn't read it properly.

I have prepared a repo and a pull request in which one can test the annotations:
https://github.com/staabm/gh-annotation-example/pull/1/files

I will make sure this url is stable and can be used for regression tests in the future.

**Comment by yakov116** [comment]
> Could be a part of [`keyboard-navigation`](/sindresorhus/refined-github/blob/main/source/features/keyboard-navigation.tsx)

Looked into this, There is no hash we can anchor it to. (Unless maybe we add our own?)

**Comment by fregante** [comment]
GitHub is taking care of this https://twitter.com/GHchangelog/status/1397299450712821763
