### ISSUE TITLE
Button to move to next change in diff

### ISSUE THREAD

**Issue by pmalbu** [sindresorhus/refined-github#3537]
If this could easily be implemented as a userscript I would be happy to go that route, but I am entirely new to all of this so I thought a good first step would be to open a feature request.

When reviewing a code change (side-by-side diff) I prefer to expand the entire file (this feature is already provided by refined-github by Alt+Clicking the expand button). However, with the entire file expanded, it is possible to miss a change (if the part is, say, 6000 lines long). I work with OS code and so it is important to see changes with a lot of context surrounding them. I don't want to miss a change by accident.

Could a button be added to the diff page which would advance the window to the next change? I have a bit of webdev knowledge and can see by inspecting the html that additions (highlighted in green) are in a td that have the class "blob-code-addition" and deletions (highlighted in red) are in a td that have the class "blob-code-deletion". I imagine that having a button which navigates to the next td with either of those classes shouldn't be too difficult to implement. I am not sure if this would be best added to refined-github or put into a userscript. To me it seems like something that everyone would benefit from, but I could be wrong.

**Comment by fregante** [comment]
I feel you, however there's a lot of pieces like this:

- jump to files
- jump to reviews: #3242 
- jump to annotations: #3536 

We can't add a button for each
