### ISSUE TITLE
batch-open-conversations not displaying properly

### ISSUE THREAD

**Issue by faucherb94** [sindresorhus/refined-github#3541]
This is an issue when used with GitHub Enterprise 2.20.9.

The batch-open-conversations feature does not display the checkboxes properly, and the top-level checkbox, when checked, does not cause all the other boxes to get checked.

![unchecked](https://user-images.githubusercontent.com/33888130/92943823-db11f100-f418-11ea-8e89-5e2f743f8acc.png)
![toplevel-checked](https://user-images.githubusercontent.com/33888130/92943819-da795a80-f418-11ea-80aa-1ee226f8b5f1.png)

I've disabled the feature in my plugin config for now.

**Comment by fregante** [comment]
Thanks for the report. This is because GHE hasn't been updated with the new design yet. I'll disable that part of the feature on GHE and release a hotfix
