### ISSUE TITLE
`show-whitespace` causes lines to wrap

### ISSUE THREAD

**Issue by jeff-minard-ck** [sindresorhus/refined-github#3542]
When RefinedGithub is enable, diffs and other views are doing line wrapping on code. I would like to disable this behavior. I searched around the open/closed PRs, as well as through the options for "wrap" but couldn't find this option.

Thanks!

**Comment by fregante** [comment]
Where are you seeing the code wrapping? Post a link and/or screenshot as requested by the template

**Comment by jeff-minard-ck** [comment]
Disabled:

<img width="1007" alt="Screen Shot 2020-09-16 at 9 25 57 PM" src="https://user-images.githubusercontent.com/1210963/93420171-4b7aa100-f863-11ea-86e5-73e7b01b65d8.png">

Enabled:

<img width="1006" alt="Screen Shot 2020-09-16 at 9 26 11 PM" src="https://user-images.githubusercontent.com/1210963/93420196-559c9f80-f863-11ea-88a0-d82ac64265b8.png">

Oddly, the text file seems to always wrap.

This is also on Github Enterprise; version 2.19.6

> Post a link and/or screenshot as requested by the template

The template for "Feature request" doesn't ask for that, fyi.

**Comment by fregante** [comment]
Thanks for the screenshots, but without a URL now I have to recreate your condition, making it harder for us to find the issue. 

> The template for "Feature request" doesn't ask for that, fyi.
It does ask for a URL:

> 2. Include a full URL where the feature should appear.

**Comment by jeff-minard-ck** [comment]
It happens under a PR diff view, something like `http://our-ghe.com/org/repo/pull/295/files`

**Comment by fregante** [comment]
Here: https://github.com/sindresorhus/refined-github/commit/4cb59bea8b78a2d3b8ea4fa888df5e70ca286ff4

It looks like it's due to `show-whitespace`

**Comment by notlmn** [comment]
The wrapping is because of https://github.com/sindresorhus/refined-github/blob/f13db9b420cc351680b15fc86344ad099bd4f96a/source/features/show-whitespace.css#L3 which was added in #3292, to fix another wrapping issue #2991.

**Comment by fregante** [comment]
It looks like GitHub wraps some file type while it doesn't wrap others. Is this easily detectable? Perhaps that `white-space` only needs to be applied to some filetypes.

**Comment by jeff-minard-ck** [comment]
Seems like there's a div in the chain that adds `.soft-wrap` which adds this for files which GH thinks should be wrapped.

**Comment by notlmn** [comment]
I'm thinking this should be easy fix, haven't tested, might be wrong.

``` css
[rgh-observing-whitespace] {
	// other props
}

.soft-wrap [rgh-observing-whitespace] {
	white-space: break-spaces;
}
```

GitHub is likely wrapping files that it thinks don't have code in them, again, I might be wrong.
