### ISSUE TITLE
`more-dropdown` will overlap the tabs on non-responsive pages

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3548]
This might or might not be an easy bug. Not to be confused with: https://github.com/sindresorhus/refined-github/issues/3347

On responsive pages, like **this issue**, tabs will disappear into the dropdown menu:

![12](https://user-images.githubusercontent.com/1402241/93028983-b469db00-f60f-11ea-9b64-93f85607ddd0.gif)

On non-responsive pages, where shouldn't be a dropdown menu, but `more-dropdown` forces it to become visible and sticky to the right side of the window. 

![1](https://user-images.githubusercontent.com/1402241/93028993-cfd4e600-f60f-11ea-9f52-f6798027b9cc.gif)

The solution should be to ensure that its container has the correct minimum width and does not "fit the window" on non-responsive pages.

Example URL: https://github.com/sindresorhus/refined-github/pull/3547

**Comment by fregante** [comment]
I found the solution: testing needed. Stick this CSS in the CSS field and let me know if you have any issues in the following days:

```css
main > :first-child {
	position: relative;
}
```

**Comment by yakov116** [comment]
> I found the solution: **testing needed.** Stick this CSS in the CSS field and let me know if you have any issues in the following days:
> 
> ```css
> main > :first-child {
> 	position: relative;
> }
> ```

Tested the past day with no issues and issue fixed

**Comment by yakov116** [comment]
3 days with no issues. @fregante you want to push to master or I should open a pr?

**Comment by fregante** [comment]
Fixed by https://github.com/sindresorhus/refined-github/commit/112d671648a3c021e37a5de0075d2c463e0cb993
