### ISSUE TITLE
'Select all' checkbox appears in odd place (and doesn't have any effect)

### ISSUE THREAD

**Issue by alexfoxgill** [sindresorhus/refined-github#3550]
Just installed this extension, noticed this bug:

![Screenshot 2020-09-14 at 16 05 33](https://user-images.githubusercontent.com/3819573/93103332-66eb7d80-f6a4-11ea-814f-8eb2b926069c.png)

This is in a search results page, eg. https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3AQuanTemplate

**Comment by fregante** [comment]
Does it appear on that page or on GitHub Enterprise only? Because we has this issue already https://github.com/sindresorhus/refined-github/issues/3541

**Comment by fregante** [comment]
Thanks for the report! That part of `batch-open-conversations` shouldn't have been enabled on global search pages.
