### ISSUE TITLE
Quick hyperlink to visit someone's github.io

### ISSUE THREAD

**Issue by yashshah1** [sindresorhus/refined-github#3560]
When you're ~stalking~ visiting a random github profile and happen to see that they have a `<username>.github.io` repository, there is no quick way to visit that homepage. Your only options are

* Type out the URL, or
* Copy and paste that specific part of the webpage into the URL Box.

## Request
Some sort of a quick "Go" button next to the repository name (both on the repository listing, and when you open the repository) which takes you to the webpage.

## URLs where this should work
* [Repository List](https://github.com/yashshah1?tab=repositories)
* [User Homepage](https://github.com/yashshah1) - In the case that the user has the repository pinned (I don't)
* [In the repository page](https://github.com/yashshah1/yashshah1.github.io)

## Additional Request
Maybe add it next to the Users profile photo if we detect that the user has a github.io page.

**Comment by notlmn** [comment]
It's already available as a feature on GitHub, if the user opts-in to let it be on their profile. The same goes for repository view.

![image](https://user-images.githubusercontent.com/37769974/93335107-97b5e900-f843-11ea-95a1-e071145b56a6.png)

-----------

Also some people have a custom domain name connected to their `user.github.io` domain, which again, is a duplicate thing to be handled.

**Comment by fregante** [comment]
It would kind of make sense, but @notlmn has a point: if the user wants that page to be visited, it should be set as their URL or mentioned in the user’s README which is now so prominently displayed.

**Comment by kidonng** [comment]
Just want to mention that you can also drag the repository name (`example.github.io`) to browser's tab bar to quickly open it. I use this trick myself.

Regarding the feature, it may not be qualified to go into Refined GitHub, in which case I can write a user script for it (if I found the time).

**Comment by fregante** [comment]
Yeah actually my comment only applied to the User’s profile, but both other locations make sense. 

- on the repository list: add an icon (globe?) next to the name
- on repository root: if the URL isn’t already set in the sidebar, we can automatically add it there.

**Comment by yashshah1** [comment]
> Just want to mention that you can also drag the repository name (`example.github.io`) to browser's tab bar to quickly open it. I use this trick myself.


@kidonng oh this is really smart, will use this. 



@fregante Can I work on this?

**Comment by fregante** [comment]
Yes please! This can be a single feature with two `init` functions: one for lists and the other one for the repo root.
