### ISSUE TITLE
Rebase button

### ISSUE THREAD

**Issue by aminya** [sindresorhus/refined-github#3563]
It would be nice if we have a rebase button next to the update base branch (which merges master to this branch). I usually prefer the rebase because it helps to keep the commit history cleaner.

![image](https://user-images.githubusercontent.com/16418197/93389785-481af180-f832-11ea-97c0-ebb43d7cd01e.png)

**Comment by fregante** [comment]
This isn't possible via the API. Even merging only recently became possible: https://developer.github.com/v3/pulls/#update-a-pull-request-branch

I don't think the API offers _any_ such destructive options (rebase rewrites history and thus `--force`)

**Comment by aminya** [comment]
For anyone that wants this, there is a GitHub action that does it:
https://github.com/cirrus-actions/rebase

**Comment by fregante** [comment]
If anyone wants to build an extension for this, it's possible but you'll need a third-party server to clone and force push (which is basically what that action does on GitHub’s own Action servers)
