### ISSUE TITLE
Automatically disable some features on large PRs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3567]
A few times people reported some features being slow on large PRs.

I wonder if, like GitHub does for large comparison, we could disable some/all features on large PRs and show a notice like *"Some RG features were disabled because this page is gargantuan."*

However, this need your help. **Please post links to such large PRs.** No real-life examples, no chances of this being fixed.

**Comment by kidonng** [comment]
Is #1783 large enough?

**Comment by fregante** [comment]
Not for me, it's buttery smooth on my 2013 laptop. We need the users who report slowdowns to post their slow URLs.

**Comment by yakov116** [comment]
https://github.com/RudiDeVos/UltraVNC/commit/4fbe8afcacc9cf181413402c1441d17ea79fdf25

With RH can barley get past the first file without chopping up. This is on a solid desktop computer.

Without RH freezes bus it moves.

**Comment by fregante** [comment]
<img width="253" alt="" src="https://user-images.githubusercontent.com/1402241/93537567-7d4a4100-f911-11ea-8fdc-3972ff0fb977.png">

Is my 2013 mac suddenly a super computer? That page also loads without a hitch. It does flash white for ~300ms but that happens even without RG.

![](https://user-images.githubusercontent.com/1402241/93537551-6f94bb80-f911-11ea-9fd1-1639279da43f.gif)

**Comment by fregante** [comment]
That gif was recorded inside `npm run start`, so no other extensions running.

**Comment by yakov116** [comment]
@fregante I should have recorded it... maybe next week

**Comment by fregante** [comment]
What's your CPU? Also try it in `npm run start`

**Comment by kidonng** [comment]
> RudiDeVos/UltraVNC@4fbe8af

It does lag a bit, but after a few seconds it's totally fine. I guess it's because GitHub folded most of the files so RGH doesn't really need to process a huge amount of lines. We probably need a PR that consists of lots of files that aren't long enough to be folded by GitHub.

**Comment by yakov116** [comment]
@fregante maybe it was not a fair test. I did it on my work computer (in middle of work shhh). I did have about 45 (if not more) other chrome tabs open and work items too. I will test again next week with only that one page open and only RH enabled. 

When I posted the link I incorrectly assumed that you would see the same results so I did not bother recording.

**Comment by fregante** [comment]
Closing. New issues can be opened with specific "feature + large PR" combination.
