### ISSUE TITLE
Bulk select checkbox broken on github.com/issues

### ISSUE THREAD

**Issue by aheckler** [sindresorhus/refined-github#3568]
URL affected: https://github.com/issues

With Refined GitHub disabled: 

![Markup on 2020-09-16 at 20:25:29](https://user-images.githubusercontent.com/5512652/93405361-c8ede380-f85a-11ea-826f-26e683c82b0a.png)

With Refined GitHub enabled: 

![Markup on 2020-09-16 at 20:25:03](https://user-images.githubusercontent.com/5512652/93405338-b70c4080-f85a-11ea-99ca-8804f00d2089.png)

**Comment by yakov116** [comment]
@aheckler it was fixed on master and will be released tomorrow.

The feature was not supposed to run on that page.

Thanks for the report.
