### ISSUE TITLE
support more emoticons

### ISSUE THREAD

**Issue by staabm** [sindresorhus/refined-github#3569]
when working with comments and emoji github provides a small picker for the most relevant (I guess?) emojis in 

![grafik](https://user-images.githubusercontent.com/120441/93439598-0be99e80-f8cf-11ea-8cdc-9e2e168116ab.png)

but a lot more are supported, see e.g.
https://gist.github.com/rxaviers/7360908

when I want to add one of the emoticons which is not listed in the overlay, I need to look them up in a cheat sheet (or learn them by heart).

I feel the current experience can be improved in the following ways:
- add some kind of "show more"/"show all" emoji button in the overlay, to ease looking up all/most of them
- the overlay could take into account which emoji I use at most and it would show me other recently used emojis in the overlay - for a more personalized experience
- in https://github.com/sindresorhus/refined-github/issues/2890 there was a suggestion to use [the native windows picker](https://blog.emojipedia.org/how-to-use-the-new-windows-emoji-picker/)  .. wouldn't it be cool, if the overlay emoji UI would contain a hint for windows users, how the native emoji picker can be invoked? maybe even with a link to this article?

example link, on which this feature could be tested: https://github.com/sindresorhus/refined-github/issues/3569

**Comment by sindresorhus** [comment]
> but a lot more are supported, see e.g.
https://gist.github.com/rxaviers/7360908

Those are for use in the comment text. The picker you're showing in the screenshot is for comment reactions, which cannot be extended with more emoji by us. You'll have to send a feature request to GitHub for that.

> in #2890 there was a suggestion to use the native windows picker .. wouldn't it be cool, if the overlay emoji UI would contain a hint for windows users, how the native emoji picker can be invoked? maybe even with a link to this article?

It's IMHO neither GitHub nor Refined GitHub's job to teach people how to do things in Windows.

---

As for a better emoji picker for comment text. We don't intend to do that as that's the job for the system emoji picker.

**Comment by Nico-Connor** [comment]
I think this issue should be re-opened for discussion

Desktop operating systems do not allow for an easy way to add emoji in comments.  Unlike smartphones you can't swap your keyboard at a press of a button.  

This leaves a sub-par experience for desktop users when adding emojis.  In recognition of this downfall, many online platform have added an in-line option to add emojis to their comments.

Exhibit A Facebook:

![image](https://user-images.githubusercontent.com/93364146/170200697-1544acfa-47e3-4848-bbbe-996739f782c9.png)


Exhibit B twitter:

![image](https://user-images.githubusercontent.com/93364146/170200384-2cc93c8a-66e7-4d20-81ca-57f079b2ac51.png)


Exhibit C Google Messages for the web:

![image](https://user-images.githubusercontent.com/93364146/170199774-7b676a60-94eb-46f4-ad63-9ef17038a270.png)


I think it's only fair to expect GitHub to have the same feature for desktop users as other major communication/social websites.  Especially knowing that many developers are finding it to be a frustrating process to add emojis.

**Comment by fregante** [comment]
> Desktop operating systems do not allow for an easy way to add emoji in comments. Unlike smartphones you can't swap your keyboard at a press of a button.

They literally do. The only difference is that the button is on the keyboard and the display isn't touch. 

![image](https://user-images.githubusercontent.com/1402241/170222343-d2014ac3-6232-4e2e-abad-a09d81c6b48a.jpeg)

You're just suggesting to recreate the same UI only to have a button that must be clicked with a mouse instead of pressed on the keyboard. Social networks do it because emojis create engagement and because they're billion-dollar companies. Refined GitHub doesn't care about that. 

Locking because you also opened an issue, duplicating the existing 2.
