### ISSUE TITLE
re-activate `hide-zero-packages`

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#3572]
I noticed that repository sidebars lists empty Packages sections ( see screenshot attached for the Refined GitHub repository ). I was unaware that we previously had a feature that hid zero packages section and it was dropped in #3297. I don't know if this is only me but I see the Packages section back again. Maybe something changed at GitHub? Should we bring the feature back again?

![image](https://user-images.githubusercontent.com/4771718/93512820-843d7780-f942-11ea-8ce2-bf7cd49c5d31.png)

**Comment by fregante** [comment]
@kidonng thoughts?

**Comment by kidonng** [comment]
You are right, GitHub changed their logic of showing packages.
