### ISSUE TITLE
Jumping to the top of github

### ISSUE THREAD

**Issue by esakki-selvaraj** [sindresorhus/refined-github#3576]
1. As of now when we press the icon , It will open the Github page in the new tab
	But when we are inside Github , It will be nice if it works like jumping to the top of the page
	I have to scroll to the top in the Trending ,Explore pages etc.

2. Pages where it will be useful
	https://github.com/trending
	https://github.com/explore

**Comment by fregante** [comment]
“Back to top” buttons should not be provided by each website. Find a way to do on any website, for example by pressing the Home key on windows or CMD->up on Mac.
