### ISSUE TITLE
Add contributor's repository address to pull request pages. 

### ISSUE THREAD

**Issue by shepmaster** [sindresorhus/refined-github#3578]
As a maintainer, I sometimes need to push changes to contributor's PRs. The nature of my projects means that I get many one-off submissions from new contributors.

Right now, I have to click on the user's repo link:

![image](https://user-images.githubusercontent.com/174509/93655321-a261b100-f9f0-11ea-973b-40c6bb891d29.png)

Then open the repo dropdown and copy the link:

![image](https://user-images.githubusercontent.com/174509/93655297-7e05d480-f9f0-11ea-8c09-e11e317669ec.png)

Honestly, I don't know that I've ever had a usage for the clipboard icon on the PR (which copies `username/branchname`).

Instead, it would be nice to short-circuit that and allow copying the contributor's repository address directly from the PR. Either by repeating the green dropdown or by just copying the SSH address (since I need to be authenticated to push to the branch).

Example URL: `https://github.com/shepmaster/snafu/pull/251` (any pull request).

Thanks so much for an awesome project!

**Comment by notlmn** [comment]
There's https://github.com/github/hub and https://github.com/cli/cli trying to solve this for checking out using PR numbers, but as someone who uses plain `git` and SSH based auth, I feel your pain.

**Comment by fregante** [comment]
In the mergeability box before the comment box at the bottom of the PR conversation, you’ll find copy-pastable commands that will automatically clone the PR. 

Also there’s a dropdown at the top-right corner with copy-pastable `gh` commands and a button to open in GitHub Desktop (which is what I use and it’s super handy)

**Comment by fregante** [comment]
We could however, if there's a good reason to, split that link in 2 parts like:

- [Henning-K](/Henning-K) : [patch-1](#-) 

But it feels like it's gonna break the `copy` button and it might not be worth it

**Comment by notlmn** [comment]
> Why? What's stopping you from installing `gh-cli`?

- An SSD which I recently got
- Heavy `git` muscle memory if I wanted to switch to `hub`
- The idea of using another tool only to checkout PRs

**Comment by shepmaster** [comment]
> for checking out using PR numbers

Ah, sorry for not clarifying this better. I actually already *have* something for that so I can type `git pr NNNNN` and it downloads and checks out the branch:

```
[alias]
	pr = "!f() { git fetch -fu upstream refs/pull/$1/head:pr/$1; git checkout pr/$1; } ; f"
```

The problem comes when I need to *push changes* to the PR, which requires me to push to the authors branch, AFAIK:

> Add more commits by **pushing to the patch-1 branch on Henning-K/snafu**.

Specifically, I need to run this first command (and ideally some variant of the second):

```
git remote add Henning-K git@github.com:Henning-K/snafu.git
git checkout Henning-K/patch-1
```

The first command requires the repository address.

**Comment by fregante** [comment]
> > someone who uses plain `git` and SSH based auth, I feel your pain

So you still prefer manually selecting the source repo and all that (hence the pain) instead of just setting up a new tool. It's not like gh is larger than a few megs, it's not Electron like GitHub Desktop 😄

**Comment by notlmn** [comment]
> @notlmn So you still prefer manually selecting the source repo and all that (hence the pain) instead of just setting up a new tool. It's not like gh is larger than a few megs, it's not Electron like GitHub Desktop 😄

I have 2FA setup on my GitHub account, which requires me to either do [token based authentication](https://stackoverflow.com/a/56262114) (a pain in the ass, and nasty overall), or [setup SSH](https://docs.github.com/en/github/using-git/which-remote-url-should-i-use#cloning-with-ssh-urls) (easy, no password required, but cloning/checking out PRs is a pain).

Regular cloning with both `hub` and `gh` set remote to `https://...` (tried setting [`git_protocol` to `ssh`](https://cli.github.com/manual/gh_config_set#examples) that doesn't work too). But for any form of pushes, you require SSH-based auth, which would _not work_ if the remote is in the form `https://...`.

Which is what @shepmaster is trying to explain in their `[alias]` example, *__pull__* works either with `https://` or `git@` protocols, but you will have to add remote as `git@` for *__push__* to work.

Apologies for the very bad explanation, correct me if I'm wrong wherever possible.

**Comment by fregante** [comment]
I also have 2FA but I don't see how the token is nasty. I set it up months ago and it's painless 😅 It's a once-in-a-(computer-)lifetime configuration versus manually setting up origins for every repo I work on.

**Comment by shepmaster** [comment]
@fregante you may be addressing my original issue, but I'm at a loss for how. Are you stating that one of

- GitHub Desktop
- GH cli
- HUB cli

Allows me to go from a PR number / URL to **adding the remote** that the PR comes from so that I can **push** to that remote? I don't mean solely checking out a PR locally, nor do I mean cloning the repository that the PR is being submitted to. As [mentioned earlier](https://github.com/sindresorhus/refined-github/issues/3578#issuecomment-695210297) I already have a solution for that by itself.

**Comment by fregante** [comment]
I'm at a loss, too, I just tried with `hub` and it doesn't automatically also set a remote [like this cheatsheet suggests](https://kapeli.com/cheat_sheets/Hub.docset/Contents/Resources/Documents/index#//dash_ref_Hub/Entry/checkout/0) and I assumed that this new `gh` tool was actually useful.

So, yeah. @sindresorhus how do you check out PRs while also setting their remote?

I've been ignorant of the whole process because GitHub Desktop does with certainty allow pushes with extreme ease:

```sh
❯ git clone https://github.com/sindresorhus/refined-github.git
Cloning into 'refined-github'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 15244 (delta 4), reused 6 (delta 1), pack-reused 15221
Receiving objects: 100% (15244/15244), 11.70 MiB | 996.00 KiB/s, done.
Resolving deltas: 100% (11615/11615), done.
❯ cd refined-github/
❯ github .
```

<img width="672" alt="" src="https://user-images.githubusercontent.com/1402241/93816992-e2f24200-fc1d-11ea-92ed-b9d6bf5c06bc.png">

```sh
❯ git remote
github-desktop-yashshah1
origin
```

**Comment by fregante** [comment]
Kinda makes me want to bring proper `git`-based instructions for everyone, adding a third tab here:

<img width="327" alt="" src="https://user-images.githubusercontent.com/1402241/93817416-8b080b00-fc1e-11ea-878f-0adab0d826fc.png">

**Comment by fregante** [comment]
Closing in favor of #2767, which tackles the issue directly.
