### ISSUE TITLE
Why RG wants access to google.com, twitter.com, etc.?

### ISSUE THREAD

**Issue by nsa** [sindresorhus/refined-github#3579]
First of all, thank you for refined-github extension I really like it. But, I am wondering why refined-github requires access to google.com and twitter.com. Google and twitter are here just some examples, RG wants to access every site not just github related ones. I don't seem to understand this behaviour.

![](https://user-images.githubusercontent.com/4787945/93668114-49972480-fa93-11ea-8cdd-711110a05f53.png)

![](https://user-images.githubusercontent.com/4787945/93668117-4bf97e80-fa93-11ea-9876-fac4768a212a.png)

P.S. I have no experience in browser extensions. maybe it's needed, idk.

**Comment by kidonng** [comment]
Refined GitHub supports GitHub Enterprise, which may be deployed to any domain, so Refined GitHub comes with this [optional permissions](https://github.com/sindresorhus/refined-github/blob/f13db9b420cc351680b15fc86344ad099bd4f96a/source/manifest.json#L25-L27) to let you active it on domains beside `github.com`, however it won't proactively request access, it's just a missleading tip from Chrome.

**Comment by nsa** [comment]
I totally forgot about Github Enterprise :/ Now it makes sense to me, thank you for your quick response.

**Comment by fregante** [comment]
Wow it’s great to see that they offer this, finally, but that’s poor copy on Chrome’s part. It should say “these extensions are also available on google.con, enable them?”
