### ISSUE TITLE
Edit button doesn't work on repo settings->Webhooks page when using RGH

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3584]
I ran into this weird bug where clicking on the edit button in repo's Webhooks settings doesn't do anything when I'm using Refined GitHub and I have to manually go to the site the link goes to so that the sudo mode prompt shows up.

Here's the page I'm referring to, the "Edit" button (as well as the blured webhook link that also goes to same page) doesn't do anything:
![image](https://user-images.githubusercontent.com/6032823/93788823-66695e80-fc31-11ea-815e-b2f210700f20.png)
Example link: `https://github.com/REPO_OWNER/REPO_YOU_HAVE_ADMIN_PERMS_ON/settings/hooks` (I can't give you my link since you obviously don't have admin access on the repo I have this issue on)

When clicking the edit button, the URL in the browser's URL bar gets updated (`https://github.com/REPO_OWNER/REPO_YOU_HAVE_ADMIN_PERMS_ON/settings/hooks/WEBHOOK_ID`) and if I refresh the site, it properly shows the sudo mode prompt, but that's really just a workaround for this issue.

Here's sudo mode prompt if you don't know what I'm referring to:
![image](https://user-images.githubusercontent.com/6032823/93788231-0d012f80-fc31-11ea-8d11-62eca8875b3f.png)

**Comment by fregante** [comment]
This is due to `stop-pjax-loading-with-esc`

@artusm thoughts on what's causing this?

**Comment by artusm** [comment]
> @artusm thoughts on what's causing this?

https://github.com/sindresorhus/refined-github/blob/175e48aa5b643d49601c738d79bc05850f1bac23/source/features/stop-pjax-loading-with-esc.tsx#L40-L45
