### ISSUE TITLE
Make `toggle-files-button` feature persistent across pages

### ISSUE THREAD

**Issue by cheap-glitch** [sindresorhus/refined-github#3588]
Currently the `toggle-file-button` feature is not extremely useful, as it basically gets you to the readme quicker, and that's it. Ever since a new link popped up on the right side of the page, it might make sense to remove this feature as mentioned in #3580 and #3587.

But I think it would be very nice to keep this feature, and to give more usefulness by making it persist during navigation -- meaning if the file list is toggled off, it will be off when reloading or navigating to a different repo page.

I seldom browse the repo files directly on GitHub, so having the list hidden by default would save quite a bit of scrolling (and yes I do know and use "Hide Files on GitHub", but it doesn't really help with [this kind of repo](https://github.com/nvie/git-toolbelt) for example).

**Feature checklist**:
 1. _It doesn't already exist as a userscript or extension._
 2. _It makes sense as a default for everyone_: if you hide the files on a repo page, there's a good chance you might want it hidden on the other pages as well. Otherwise if you just want to jump to the readme, there's a link for that.
 3. _It doesn't require options_: if the list is open, it stays open ; if it's closed it stays closed.
 4. _It doesn't require a lot of view/UI, code and effort to maintain_: no new UI, but the business logic might be a tad tricky (I tried a naive implementation by adding a check in [`init()`](https://github.com/sindresorhus/refined-github/blob/835b0a0d6d1b5cbb60e7a93cf43b3535602e599e/source/features/toggle-files-button.tsx#L36) but it creates some annoying jitter on page load)
 5. _It doesn't require an external server._
 6. _It doesn't require too much HTTP traffic._
 7. _It doesn't enhance "Projects"_

I'm willing to try implementing this if you accept it as a valid feature request.

Thank you for maintaining and improving this indispensable extension! 👍

**Comment by kidonng** [comment]
This feature already persists across pages, did you encounter a bug?

That said, I support your point. This feature may not be useful on the repo's home page, but it does in other pages. For example, Telegraf.js has [a standalone docs website](https://telegraf.js.org/), but it uses docute and initial loading takes a long time, so I go to see [the source](https://github.com/telegraf/telegraf/tree/develop/docs) instead, where `toggle-files-button` makes it easy to hide the files section so I can concentrate on the docs. Yeah I know I can click the file to achieve the same effect, but `toggle-files-button` is more convenient.

**Comment by yakov116** [comment]
@cheap-glitch thank you for the detailed and clear issue!

I agree, the reason we wanted to drop the feature was due to the Readme link already existing. However even that, only exists on the root of the repository.

**Comment by cheap-glitch** [comment]
> This feature already persists across pages, did you encounter a bug?

Really? That's news to me! I've been using RG on Firefox for quite a while now, and it was never persistent -- even before the big redesign of the repo page.

Should I change the template into a bug report?

**Comment by notlmn** [comment]
> This feature already persists across pages, did you encounter a bug?

Hey @kidonng, I don't think this feature is persistent across pages. Just tried it on Firefox, and checked https://github.com/sindresorhus/refined-github/blob/master/source/features/toggle-files-button.tsx, couldn't find anything that handles persistence.

--------------------

> However even that, only exists on the root of the repository.

@yakov116 Yup, we should not drop this feature. /cc @fregante on https://github.com/sindresorhus/refined-github/issues/3580#issuecomment-696236432

**Comment by fregante** [comment]
> I agree, the reason we wanted to drop the feature was due to the Readme link already existing. However even that, **only exists on the root of the repository.**

Good point, let's not drop the feature for this reason.

**Comment by fregante** [comment]
I think we can apply this suggestion.

1. Update the feature to use `elementReady`: https://github.com/sindresorhus/refined-github/issues/2671
2. Use the cache to remember whether the file list was closed
