### ISSUE TITLE
Ability to preview `user-local-time` in 12h format

### ISSUE THREAD

**Issue by Daksh777** [sindresorhus/refined-github#3597]
I do not see any option in the extensions settings to change the `user-local-time` format to 12h, it would be great if it were possible to change it.
![image](https://user-images.githubusercontent.com/43648146/94336535-98980900-0001-11eb-9eaa-fd30945a460e.png)

**Comment by cheap-glitch** [comment]
I think this breaks the two following requirements:
 * _It makes sense as a default for everyone_: I don't know about Asia, but here in Europe where I live, most people use the 24h time format (with the exception of England ofc, and maybe others?)
 * _It doesn't require options_: seems that it would be a setting of `user-local-time`

**Comment by Daksh777** [comment]
> * _It makes sense as a default for everyone_: I don't know about Asia, but here in Europe where I live, most people use the 24h time format (with the exception of England ofc, and maybe others?)

I agree that it makes sense as a default format for everyone, but it would be great if it could be customized/changed to 12h format. Also this is a feature request and you can always close the issue if you don't want to implement it, it's totally on you.
> * _It doesn't require options_: seems that it would be a setting of `user-local-time`

Yes, that's what I meant.

**Comment by fregante** [comment]
Times are displayed as 24h across the site by GitHub as well, and also are the standard for flight travel, so it’ll just have to stay (because we don’t offer per-feature options)

If/when web pages will be able to read the system settings, maybe that can change.

**Comment by cheap-glitch** [comment]
> If/when web pages will be able to read the system settings, maybe that can change.

Wait, can't we do something like
```javascript
timeFormat = /[AP]M$/.test((new Date()).toLocaleString()) ? 12 : 24;
```
?

**Comment by fregante** [comment]
That follows the locale, not the system’s settings (which may vary), but it looks like GitHub uses the local format as well.

Accepted.

I think the solution is to just pass `undefined`  here:

```
const timeFormatter = new Intl.DateTimeFormat(undefined, {
	hour: 'numeric',
	minute: 'numeric'
});
```

**Comment by Daksh777** [comment]
Thank you very much!
