### ISSUE TITLE
Enable `bypass-checks` on more commit statuses

### ISSUE THREAD

**Issue by benwaffle** [sindresorhus/refined-github#3609]
Right now, clicking on "details" for a travis build goes to this page, which is mostly useless:

<img width="697" alt="image" src="https://user-images.githubusercontent.com/1713819/94846538-4e42cd80-03ef-11eb-94de-b8f914d3a3fa.png">

100% of the time, I just click on "The build" to get to travis, where I can see logs and restart a build.

The feature request is to add a "Build log" link here:

<img width="495" alt="image" src="https://user-images.githubusercontent.com/1713819/94846720-982bb380-03ef-11eb-9e30-205c7eb593e4.png">

**Comment by fregante** [comment]
This already exists on the PR page, but I think nowhere else. The problem is that it requires fetching each and every Check page, so we can’t do that *for every commit, everywhere*

The feature is called `bypass-checks`

**Comment by benwaffle** [comment]
I've confirmed it's enabled in my console, but the feature isn't working

**Comment by yakov116** [comment]
URL?

**Comment by fregante** [comment]
It works for me on Firefox

URL:  https://github.com/xojs/xo/pull/497

## No RG

Notice the the underlined "Details" link and the URL in the status bar

<img width="637" alt="" src="https://user-images.githubusercontent.com/1402241/94861509-438f3500-03fd-11eb-84e1-5e906c3eb3f8.png">

## RG

<img width="579" alt="" src="https://user-images.githubusercontent.com/1402241/94861543-4f7af700-03fd-11eb-8827-fc07d2b1976d.png">

**Comment by benwaffle** [comment]
That section works for me, but I'm clicking on the build status dot

<img width="1149" alt="image" src="https://user-images.githubusercontent.com/1713819/94862656-48f17d00-0407-11eb-8bbf-0e4b5664e0b3.png">

**Comment by fregante** [comment]
Yeah, the feature only works on the Mergeability box. 

I wonder if we can change the feature to work on _any_ of those popups, by waiting for them to open and fetching just in time. This might be fast enough for some. 

`selector-observer` should make this relatively easy. Separately, it'd be good to know whether the GraphQL API has this piece of information so that we could reduce the HTTP calls.

**Comment by yakov116** [comment]
GraphQL needs a next of 7 to get the status check and it would have to check each commit. I would just do mem around the request. My question is will it be fast enough to replace the link which is created on the fly.

**Comment by fregante** [comment]
Next of 7?

**Comment by yakov116** [comment]
Nest

**Comment by yakov116** [comment]
I see now my auto correct took over sorry.
GraphQL need to be a nest 7 deep in order to get the details url

**Comment by fregante** [comment]
GQL is a bit verbose but if it’s fast it’s worth it, especially if we enable this “on open”

However it’s a separate improvement, I’d rather see this feature working in more places, even if sometimes it’s not fast enough (nothing breaks if it’s not fast enough anyway)

**Comment by benwaffle** [comment]
thanks @yakov116 and @fregante - the feature works perfectly!
