### ISSUE TITLE
Inline emoji dropdown

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#361]
What do you say? This can be done with a little CSS. Can send PR

# GitHub

<img width="259" alt="screen shot 2017-03-02 at 14 45 33" src="https://cloud.githubusercontent.com/assets/1402241/23497752/81ba4360-fed9-11e6-9d5a-7f63c7bc0db3.png">

# Refined GitHub

<img width="250" alt="screen shot 2017-03-02 at 14 44 41" src="https://cloud.githubusercontent.com/assets/1402241/23497758/8acb00fc-fed9-11e6-8769-5ffdbccb94d2.png">

# Suggested

<img width="316" alt="screen shot 2017-03-02 at 14 47 43" src="https://cloud.githubusercontent.com/assets/1402241/23497765/920deef6-fed9-11e6-829d-d9a5bc4a9ac9.png">

**Comment by hkdobrev** [comment]
:-1: In your proposed version the path to select most emoji is longer. Especially for the most popular one - the +1 emoji.

**Comment by bfred-it** [comment]
Longer but it's straight. The main reason why I thought of this is that since this comes up on `hover` now it covers other parts of the UI and you have to move farther to close it

**Comment by sindresorhus** [comment]
👎 I think we tried it out initially when making this feature, but we rather optimized for mouse distance. You can just move your mouse if something is beneath. It has honestly never been a problem and I pretty much live on GitHub.
