### ISSUE TITLE
Show forks by default when the search is sorted by stars

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#3613]
[GitHub doesn't show forks by default when searching](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-in-forks), this is fine most of the time, but it often leads to notable forks being ignored.

<details>
<summary>Example</summary>

- https://github.com/search?o=desc&q=deno&s=stars&type=Repositories

![image](https://user-images.githubusercontent.com/44045911/94982636-caafea80-056e-11eb-9904-69ea5f15d332.png)

- https://github.com/search?o=desc&q=deno+fork%3Atrue&s=stars&type=Repositories

![image](https://user-images.githubusercontent.com/44045911/94982646-d6031600-056e-11eb-893d-483aac7cc49f.png)

</details>

Notice in the example, how [denolib/awesome-deno](https://github.com/denolib/awesome-deno) isn't shown by default even it has plenty of stars.

There are existing solutions to this problem such as [Lovely forks](https://github.com/musically-ut/lovely-forks), but we can solve this from another aspect. When a user sorts the search result by stars, we can append `fork:true` automatically so notable forks show up in the search result by default.

This feature should appear on all `https://github.com/search?s=stars&type=Repositories` URL.

**Comment by fregante** [comment]
I'm conflicted about this because those projects deserve more visibility but `fork:true` often doubles the result count while almost never really affecting your search; it just makes it seem like there's a lot of choice but then you end up in the long fork-only tail as you go through the pages.

I really wish GitHub had an official "meaningful fork" state. They even reinvented forking as "Repository templates" but forks are still hidden.

**Comment by fregante** [comment]
Given how forks are treated by GitHub, I’m hesitant to always include forks in search results, which in the vast majority of times it just adds noice. 

I advice suggesting to GitHub to differentiate meaningful forks from PR-only

**Comment by kidonng** [comment]
I know this is closed, but please let me confirm it's not a misunderstanding:

> always include forks in search results

Not always, just when the user choose to sort by most stars. This is stated in the title and the description from the beginning.

Alternatively, we can add a toggle for showing forks in the search page. I'm pretty sure lots of people doesn't know the `fork: true` trick so this is still useful while being less aggressive.

That said, if this should be a script/extension of itself, I'm happy to make one.

**Comment by fregante** [comment]
Yeah I missed that part. I think it’d make sense
