### ISSUE TITLE
Limit reaction avatars to 2 when there are too many

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#362]
See it here: https://github.com/babel/babel/pull/3646

CSS-only change. Can send PR

# GitHub

<img width="704" alt="screen shot 2017-03-02 at 14 57 03" src="https://cloud.githubusercontent.com/assets/1402241/23498076/ce2d3bf2-feda-11e6-975e-caa502fecb85.png">

# Refined GitHub

<img width="705" alt="screen shot 2017-03-02 at 14 55 30" src="https://cloud.githubusercontent.com/assets/1402241/23498089/d8873b48-feda-11e6-8a39-89ad095ce206.png">

# Suggested

<img width="710" alt="screen shot 2017-03-02 at 14 55 11" src="https://cloud.githubusercontent.com/assets/1402241/23498098/dfd45dc2-feda-11e6-9ba0-c4da1e8dee81.png">

**Comment by jacobbearden** [comment]
:+1:

**Comment by sindresorhus** [comment]
👍 PR welcome :)

**Comment by bfred-it** [comment]
Can you leave all the reactions on this post so I can test it out with a non-locked thread?
