### ISSUE TITLE
Unable to see target for Pull Request?

### ISSUE THREAD

**Issue by IPWright83** [sindresorhus/refined-github#3622]
So I just noticed on a pull request that there was no way for me to see where the pull request was being merged to, so I wasn't sure if it was going to our `dev` or `master` branch. I disabled Refined GitHub and then it was immediately obvious.

The URL was from that of a pull request `https://github.com/university-of-york/redacted/pull/52` which I'm afraid is private. The top title had changed, but unfortunately there's no where else on the page that details the target branch that you're about to merge into.

I've logged as a bug, as I think it's quite a key bit of information to be able to see somewhere on the page.

**Without** Refined GitHub
![image](https://user-images.githubusercontent.com/1374775/95210095-0652ea80-07e3-11eb-811d-806f9acbbe4b.png)

**With** Refined GitHub
![image](https://user-images.githubusercontent.com/1374775/95210173-1ff43200-07e3-11eb-981a-9db0f2776843.png)

**Comment by busches** [comment]
See comments in #3590 and the other prs linked there, but this is a feature.

**Comment by IPWright83** [comment]
Thanks @busches, sorry to raise as an issue. Didn't think to search closed too.
