### ISSUE TITLE
Rich Text Editor HTML Shortcuts

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3628]
![image](https://user-images.githubusercontent.com/16872793/95381618-6797be00-08b6-11eb-9471-be2eb65f4812.png)

Currently when you click on the above links it puts in markdown things (sorry for the lack of better name).

I would like if `alt` is pressed it should do the equivalent in HTML

My use case: https://github.com/sindresorhus/refined-github/pull/3621 I am using a HTML table and need to put links that need to be surrounded by `<a href="LINK">LINK</a>` VS `[LINK](Link)`

**Comment by fregante** [comment]
What for?

**Comment by yakov116** [comment]
`https://github.com/webpack/webpack/pull/11438` => `<a href="https://github.com/webpack/webpack/pull/11438"></a>`

Instead of 
`https://github.com/webpack/webpack/pull/11438` => `[](https://github.com/webpack/webpack/pull/11438)`

**Comment by fregante** [comment]
Right but why

**Comment by yakov116** [comment]
@fregante the issue is that markdown links were not working for me in a table. Thats why I switched to html.

Also on such a big table working with markdown is almost impossible.

**Comment by fregante** [comment]
> markdown links were not working for me in a table

Add linebreaks after `<td>`. Edit this comment to see:

<table><td>

[link][#link] 

</table>

**Comment by fregante** [comment]
It seems unnecessary and could lead to a slipper slope. I don't want to have to reconstruct every button to print HTML just because it's not supported by a table.

**Comment by yakov116** [comment]
>It seems unnecessary and could lead to a slipper slope.

Agree
