### ISSUE TITLE
Meta-feature: Add information box to each `feature` file

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3630]
On this same repo, when visiting a feature file (https://github.com/sindresorhus/refined-github/blob/master/source/features/action-used-by-link.tsx) we could display a box with parsed information about the feature, both as documentation and as a debug helper.

<img width="1043" alt="" src="https://user-images.githubusercontent.com/1402241/95401399-b6ebe780-08d2-11eb-90ba-1649af885c5c.png">

Content the box could include:

- the screenshot as a `<img>`
- the formatted description
- links to PRs that implemented it, like the [history page](https://github.com/sindresorhus/refined-github/commits/master/source/features/action-used-by-link.tsx) without clutter (skips any meta PRs) — discussed [here first](https://github.com/sindresorhus/refined-github/pull/3621#issuecomment-704596791)
- an issue ego-search, like https://github.com/sindresorhus/refined-github/issues?q=%22show-whitespace%22, displaying the text: _34 conversations, 3 open_

**Comment by yakov116** [comment]
Can't we get the description/screenshot from the options page? That would avoid parsing the Readme.

**Comment by fregante** [comment]
We could, we’d just need to use the `__featuresMeta` magic variable to have them instantly available.

**Comment by yakov116** [comment]
I would like to discuss the following points.

> - links to PRs that implemented it, like the history page without clutter (skips any meta PRs) — discussed here first

I don't see any benefit over using history, plus using history follows renames. Another issue is that some features went through so many renames/dir changes that there is no way to even find its implementation. 

> - an issue ego-search, like https://github.com/sindresorhus/refined-github/issues?q=%22show-whitespace%22, displaying the text: 34 conversations, 3 open

What problem are we solving with this?

**Comment by fregante** [comment]
The benefit is that it could skip clutter like meta and lint commits, specifically linking to the meaningful PRs. As for the renames… yes, that’d be a problem. Are we really sure that still there isn’t a way to list commits following renames via the API?

Second part: it’s useful to know where it’s been discussed and the text would show us whether it currently has issues. But I guess a simple link could also be useful.

**Comment by yakov116** [comment]
See https://github.com/sindresorhus/refined-github/pull/3693 for details on how the layout should be.

**Comment by yakov116** [comment]
See https://github.com/sindresorhus/refined-github/pull/3693 for the code to get the featues and api call for history.
