### ISSUE TITLE
Tooltip of `bugs-tab` shows the number of issues

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3633]
Tooltip of `bugs-tab` shows the number of issues.

URL: https://github.com/sindresorhus/refined-github/issues
![image](https://user-images.githubusercontent.com/49396421/95469802-9f842b80-09b2-11eb-9390-096aefd97987.png)

**Comment by fregante** [comment]
Thanks for the report!

**Comment by Geeyun-JY3** [comment]
Why not show the number of bugs instead of removing this tooltip?

**Comment by yakov116** [comment]
What information does it provide in addition to what you already see?

**Comment by Geeyun-JY3** [comment]
> What information does it provide in addition to what you already see?

Yeh, I know, actually nope🤣. I just think it can be more decent, just like what GitHub does to the issue tab. If you think that is unnecessary, I am OK with not adding this tooltip.
