### ISSUE TITLE
`user-local-time` occasionally appears twice

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3634]
I don't really know what's causing it and how to replicate it consistently, but the time appears twice. First as "Guessing…" then the time is updated at the same time.

<img width="385" alt="" src="https://user-images.githubusercontent.com/1402241/95492581-eba68000-0960-11eb-8fed-57df93419c5c.png">

**Comment by yakov116** [comment]
I had it if they have a large news feed and it's in middle of pagination. Go away from the card and go back. Never raised an issue since it's so rare

**Comment by fregante** [comment]
It does seem to happen rarely. I caught it here, however I hovered the same user twice, possibly while one request was still happening:


![](https://user-images.githubusercontent.com/1402241/95506883-31217800-0976-11eb-9731-0fe8abd4dbb1.gif)


User: https://github.com/zpao

**Comment by yakov116** [comment]
Worth fixing?

**Comment by fregante** [comment]
Sure. I wonder if simply memoizing the cached function would help: https://github.com/fregante/webext-storage-cache/issues/27

**Comment by fregante** [comment]
Fixed by https://github.com/fregante/webext-storage-cache/pull/28

**Comment by fregante** [comment]
<img width="390" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/116361719-77afc480-a82b-11eb-8f63-a4cab33d3af3.png">

I still regularly see it :(
