### ISSUE TITLE
Filename copy method

### ISSUE THREAD

**Issue by DojoGeekRA** [sindresorhus/refined-github#364]
The ability to toggle the file content during pull requests reviews is awesome, but sometimes the diff is hard to read and when you decide to copy the filename to read it in the IDE, the toggle feature interfere with this process (e.g. when you try to select the filename to copy it, you sometimes toggle the file's content several times).

It is possible to create method to copy the filename in the pull requests to the clipboard?

![captura de pantalla 2017-03-05 a la s 17 49 05](https://cloud.githubusercontent.com/assets/5356595/23592826/168451e4-01cc-11e7-85de-0cf7f97401bf.png)

Thanks!

**Comment by sindresorhus** [comment]
Sure, that could be useful. Pull request welcome if anyone wants this.

**Comment by AshikNesin** [comment]
I'm working on it @sindresorhus :)

**Comment by hkdobrev** [comment]
Just to mention the issue initially reported in this issue is now obsolete after #405 as GitHub has implemented collapsing. I think we should close this issue even with #417 in the works.

**Comment by bfred-it** [comment]
Has anyone ever used this button? What's the use? It's a bit weird that it only appears in PR files and nowhere else.
