### ISSUE TITLE
`GetCurrentBranch` Stopped working on issues

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3641]
This is a major problem

Test on https://github.com/sindresorhus/refined-github/issues/3638 or even this issue.

**Comment by fregante** [comment]
???

There's no branch on issues.

**Comment by yakov116** [comment]
But the more-dropdown...

**Comment by fregante** [comment]
Then the more dropdown… stopped working 😉

**Comment by fregante** [comment]
We should either ensure that more-dropdown doesn’t call the function where it doesn’t make sense, or that the function returns undefined when it doesn’t find the expected URL format

**Comment by notlmn** [comment]
I think https://github.com/sindresorhus/refined-github/blob/d7d700a20befb552f9f64e15504b845dbe04e699/source/github-helpers/get-default-branch.ts can be used if `getCurrentBranch()` fails (combined with returning `undefined` if it can not find expected URL?

``` js
const reference = getCurrentBranch() || getDefaultBranch();
```

--------

OR... should it be the other way, `getCurrentBranch()` returning `getDefaultBranch()` as a fallback?

**Comment by yakov116** [comment]
> `getCurrentBranch()` returning `getDefaultBranch()` as a fallback?

☝️

**Comment by fregante** [comment]
I think getCurrentBranch does not make sense outside of code pages, it’s best to make it explicit like in your first example, only where necessary.

**Comment by fregante** [comment]
On this issue:
```js
$('[type="application/atom+xml"]').href
"https://github.com/sindresorhus/refined-github/commits/master.atom"
```

So what's the error? It exists and it's already the default branch

**Comment by yakov116** [comment]
```ts
$('[type="application/atom+xml"]').href
// Uncaught TypeError: Cannot read property 'href' of null
```

not for me

**Comment by notlmn** [comment]
``` js
$('[type="application/atom+xml"]').href
// Uncaught TypeError: $(...) is null
```

Me neither (on Firefox)

**Comment by fregante** [comment]
I think I encountered the same issue that caused https://github.com/sindresorhus/refined-github/issues/2799 (i.e. GitHub doesn't cleanup the `link`s after AJAX navigation)

**Comment by yakov116** [comment]
I think we should send a ticket into github. We really depend on it, (the whole GithubURL will not work). I hope they are not removing it.

**Comment by fregante** [comment]
This is not a bug. **Issues don’t have a branch.** 


GitHubURL does not depend on it. It works just fine.
