### ISSUE TITLE
Make sure that GitHub hovercard doesn't open under the cursor

### ISSUE THREAD

**Issue by maricn** [sindresorhus/refined-github#3643]
I often just want to click on a link, and I position my cursor over it and click on it just to discover a hovercard popped up and blocked me doing so. Then I need to pick up the mouse and specifically locate where to point the cursor in a freshly changed environment, navigate there, and click again. Big waste of calories and time.

Would be great if we could guarantee that hovercards never block the clicking tip of the pointer.

**Comment by yakov116** [comment]
Please provide an example

**Comment by maricn** [comment]
@yakov116 
![image](https://user-images.githubusercontent.com/3995223/95770857-942e4a00-0ca9-11eb-9f22-265c35f64c68.png)

Not sure if this is a task for refined-github, but maybe someone has a suggestion how to deal with this..

P.S. Same thing happens without Stylus dark theme as well.

**Comment by fregante** [comment]
I don’t think much can be done about it other than disabling/delaying the hovercard, but RG can do neither. 

Thoughts?

**Comment by notlmn** [comment]
Maybe the delay could be increased on some set of URL _somehow_?

**Comment by fregante** [comment]
I don’t think slowing down **every** hover interaction is an acceptable feature for RGH

**Comment by fregante** [comment]
There's no way to figure out whether the hover is intentional or not, we can't read minds. I don't think it's worth making it harder to trigger mouseenter events to avoid the occasional involuntary hover, it just opens up to a number of issues I don't want to deal with.
