### ISSUE TITLE
`The HEAD of master isn't tagged` but it is !

### ISSUE THREAD

**Issue by Seluj78** [sindresorhus/refined-github#3645]
As you can see in the following screenshots, the master HEAD is tagged with `v0.14.1` but it still says `v0.8.0` :/ Any idea why ?

here's the repo link if needed !

https://github.com/Seluj78/Potodo

<img width="1336" alt="Screenshot 2020-10-13 at 13 41 08" src="https://user-images.githubusercontent.com/4641317/95856182-e9299900-0d59-11eb-8d52-2444eb633564.png">
<img width="941" alt="Screenshot 2020-10-13 at 13 41 23" src="https://user-images.githubusercontent.com/4641317/95856189-ec248980-0d59-11eb-986a-58380de5fd15.png">

**Comment by yakov116** [comment]
Because you just tagged it. 
We do not make a new request every time you refresh the page, we have a cache expiration of an hour. That mean since the last time we made a request we will wait an hour to make another one.

https://github.com/sindresorhus/refined-github/blob/d7d700a20befb552f9f64e15504b845dbe04e699/source/features/latest-tag-button.tsx#L75-L79

**Comment by Seluj78** [comment]
ooooh ! Alright ! It's just weird it feels like the `v0.8.0` tag has been here for months !
Let me check something

**Comment by Seluj78** [comment]
Okay so I just checked my tags page and it shouldn't be on `v0.8.0` 🤔 

<img width="639" alt="Screenshot 2020-10-13 at 13 53 03" src="https://user-images.githubusercontent.com/4641317/95857188-83d6a780-0d5b-11eb-9584-fa77bacd6d10.png">
https://github.com/seluj78/potodo/releases

**Comment by Seluj78** [comment]
It seems to have finally updated 🤷‍♂️ 

I will close the issue now, and let you know how it goes !

<img width="693" alt="Screenshot 2020-10-13 at 17 12 46" src="https://user-images.githubusercontent.com/4641317/95880033-58fa4c80-0d77-11eb-99ef-f77db3cb6cd4.png">
