### ISSUE TITLE
Release links are lowercased

### ISSUE THREAD

**Issue by mikhaelkh** [sindresorhus/refined-github#3648]
https://github.com/BtbN/FFmpeg-Builds has Releases link https://github.com/btbn/ffmpeg-builds/releases instead of https://github.com/BtbN/FFmpeg-Builds/releases
All other tabs respect letter case, `releases-tab` feature should respect it too. Sidebar Releases block which is removed by this feature also respects letter case.

**Comment by fregante** [comment]
This is because we *normalize* the capitalization in the function getRepoURL. Maybe we should review its usage and see if it can reliably get the correct the capitalization elsewhere, at least when we use it to generate links (as opposed to comparisons and cache keys)

**Comment by busches** [comment]
What's the harm in having it lower cased? The link still works as expected for me and I likely wouldn't have even noticed.

**Comment by fregante** [comment]
@busches generally I agree, this is not an actual issue, but the solution seems easy enough. Even if we forget to preserve the capitalization sometimes, we can still try.
