### ISSUE TITLE
Stylize OP name in comments

### ISSUE THREAD

**Issue by schmuli** [sindresorhus/refined-github#365]
Similar to how StackOverflow does it, can the OP name be stylized slightly differently when adding a comment to issues and pull requests?

**Comment by sindresorhus** [comment]
Any suggestion on what kind of styling?

**Comment by schmuli** [comment]
Something simple, like a background color?

If you look at any question on StackOverflow, you can see how the OP's name is displayed with a light blue background, including in any comments on the page, and also if the OP provides an answer.

**Comment by jacobbearden** [comment]
Made a couple of mockups:

- Gray border (matching the Owner/Contributor tags)
![1](https://cloud.githubusercontent.com/assets/5340692/23699681/45a3512c-03ad-11e7-97b7-1cedb1ab2e24.PNG)

- GitHub's normal link color
![2](https://cloud.githubusercontent.com/assets/5340692/23699683/46fdba26-03ad-11e7-8547-14c50a5c7424.PNG)

- Light gray background, the same gray as the border above
![3](https://cloud.githubusercontent.com/assets/5340692/23699688/487295d4-03ad-11e7-9b69-3386782bd2a3.PNG)


// @schmuli @sindresorhus

**Comment by schmuli** [comment]
Actually, I just noticed that when viewing your own comments, GitHub will add a slight blue background color to the whole comment header. Maybe something along those lines?

Otherwise, @jacobbearden mockups are great too, and also reuse existing GitHub styles/colors. I would probably go with the light gray background (3rd option).

**Comment by hkdobrev** [comment]
I really like the badges from GitHub saying "Owner", "Collaborator", "Contributor". Do you think we could another one next to it saying "OP" or something like that?

**Comment by paulmolluzzo** [comment]
> I really like the badges from GitHub saying "Owner", "Collaborator", "Contributor". Do you think we could another one next to it saying "OP" or something like that?

This idea is most aligned with GH's styling. Also, it's more accessible than a colored BG or something, which might be hard to see/notice for some users.

**Comment by hkdobrev** [comment]
It's also more explicit as some people might not be aware what the colouring is for.

**Comment by schmuli** [comment]
The thing about using the badge is that the User may have their own "Owner"/"Collaborator"/etc. badge, and adding another badge might not be so clean.

Additionally, this feature will be included in the README of the extension, so anyone can find out about it and what decoration it will use. Personally, I don't like the abbreviation "OP", especially as a badge in this case.

**Comment by paulmolluzzo** [comment]
> The thing about using the badge is that the User may have their own "Owner"/"Collaborator"/etc. badge, and adding another badge might not be so clean.

They'd have to stack to the left. I'm not sure this is a major detraction.

(I used @hkdobrev here only because he had the "Collaborator" badge already.)
![screen shot 2017-03-08 at 10 00 15 am](https://cloud.githubusercontent.com/assets/737065/23709041/1a233222-03e6-11e7-9a58-9212e5af71b2.png)

> Additionally, this feature will be included in the README of the extension, so anyone can find out about it and what decoration it will use.

LOL, I'm not sure I've read the whole README on this project. :rofl:

> Personally, I don't like the abbreviation "OP", especially as a badge in this case.

"OP" might not be the best choice, I agree. What about "Original Poster"?

BTW, there is another project that is more robust, but doesn't "follow" the poster through all comments in a thread. Check out: https://github.com/hzoo/contributors-on-github

![screen shot 2017-03-08 at 9 55 49 am](https://cloud.githubusercontent.com/assets/737065/23709032/121cc0fc-03e6-11e7-8575-47d2bfa3be35.png)

**Comment by schmuli** [comment]
@paulmolluzzo Having seen your mockup, I agree that this is not bad at all.

**Comment by hkdobrev** [comment]
I'm still not sure whether "Original Poster" should be on the left or on the right side when there's a badge already, but I'm leaning more on keeping the original position of the GitHub badges and adding new ones on the left.

**Comment by paulmolluzzo** [comment]
> I'm still not sure whether "Original Poster" should be on the left or on the right side when there's a badge already, but I'm leaning more on keeping the original position of the GitHub badges and adding new ones on the left.

Sure. That works fine too.

**Comment by hkdobrev** [comment]
It's important to note that the user badge is on the left when the comment is left on a line of code. Example: https://github.com/sindresorhus/refined-github/pull/369#discussion_r105855587

**Comment by sindresorhus** [comment]
I think our custom badge should be where the native ones are, either right or left, depending on context.

**Comment by sindresorhus** [comment]
@schmuli @jacobbearden @jgierer12 If you haven't done it already, can you contact GitHub support and request this feature?

From the readme:

> Our hope is that GitHub will notice and implement some of these much needed improvements. So if you like any of these improvements, please email [GitHub support](mailto:support@github.com) about doing it.
