### ISSUE TITLE
`Release-tab` throws an error if `more-dropdown` is turned off

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3652]
```
refined-github.js:5841 ❌ Refined GitHub → releases-tab → TypeError: Cannot read property 'before' of null
    at init (refined-github.js:9463)
    at async runFeature (refined-github.js:5881)
    at async setupPageLoad (refined-github.js:5894) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'before'%20of%20null

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60releases-tab%60%3A%20Cannot%20read%20property%20'before'%20of%20null
```

**Comment by busches** [comment]
I know we discussed in the past that disabling features was kind of at your own risk. If it's an easy fix, let's go for it, otherwise, if you disable one, you disable both. 🤷

**Comment by yakov116** [comment]
> I know we discussed in the past that disabling features was kind of at your own risk. If it's an easy fix, let's go for it, otherwise, if you disable one, you disable both. 🤷

Agree.

However (does not really make a difference) really it goes the other way around `more-dropdown` is erroring out and then `release-tab` crashes.

**Comment by fregante** [comment]
Yeah we generally try not to make the features interdependent simply for maintainability’s sake, but if it’s too hard we just add a comment in `refined-github.TS` and call it a day.
