### ISSUE TITLE
Add link to all milestones on milestone page

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#366]
Milestones listing page is currently accessible through the Issues or Pull requests listing page. However, when you open a specific milestone page, there is no link to all milestones. You need to go to issues/PRs to see the link.

Changing the URL manually or clicking back when you have come from the milestones page works, but a link to the index should also be there.

Milestone page: https://github.com/composer/composer/milestone/18
Milestones page: https://github.com/composer/composer/milestones

I think we should add the same navigation buttons which are visible on the Milestones page on the Milestone page as well:

<img width="214" alt="screen shot 2017-03-08 at 16 56 09" src="https://cloud.githubusercontent.com/assets/506129/23708878/35a5156c-0420-11e7-836b-f25a1ac4b625.png">

**Comment by sindresorhus** [comment]
Make sure you email GitHub support about this too. Seems like an oversight on their part.

**Comment by hkdobrev** [comment]
Contacted. ✅
