### ISSUE TITLE
`comment-fields-keyboard-shortcuts`  Up arrow to edit last comment is broken

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3662]
Looks strange. My issue?
Test URL: https://github.com/sindresorhus/refined-github/issues/3633
Screenshot:
![image](https://user-images.githubusercontent.com/49396421/96268923-3a58b780-0ffc-11eb-9113-51f1f99bf66c.gif)

**Comment by yakov116** [comment]
test

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/6d339762d762b669bb48b2977f40a83c48305a2d/source/features/comment-fields-keyboard-shortcuts.tsx#L30-L34

Looks like these selectors need to be updated
