### ISSUE TITLE
`conversation-filters` should keep your current query

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3663]
Such as `is:pr is:open`

Currently it just sets it to 

https://github.com/sindresorhus/refined-github/blob/daf633137ec08e6f5647a6f8bb0b02d5dce58ef9/source/features/conversation-filters.tsx#L20

**Comment by fregante** [comment]
None of the conversation filters preserve the query, ours shouldn’t either

**Comment by yakov116** [comment]
Didn't notice that.
