### ISSUE TITLE
Drop `remove-checks-tab` feature or make it dynamic

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3667]
This feature is a bit annoying because checks are asynchronous so even if it's 0 now, there might actually be checks appearing later.

I see 2 options:

- restore the tab _if_ the number changes dynamically (unchecked)
- drop the feature, especially if most repos now use it (GitHub Actions surely made it useful)

**Comment by yakov116** [comment]
Drop it

**Comment by fregante** [comment]
🤜 
🎤

**Comment by fregante** [comment]
Ask @sindresorhus

**Comment by sindresorhus** [comment]
https://en.wikipedia.org/wiki/Mic_drop

**Comment by yakov116** [comment]
> * drop the feature, especially if most repos now use it (GitHub Actions surely made it useful)

This is the main reason to drop it

But as you said yourself (if you need another excuse)

> From what I understand if it’s empty then it probably shouldn’t, so it’s serving a purpose anyway (i.e. nagging you to add checks)

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/1304#issuecomment-387284956_
