### ISSUE TITLE
`hide-empty-meta` stopped working

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3668]
https://github.com/Witold101/wpw
![image](https://user-images.githubusercontent.com/16872793/96359169-731c8d80-10dd-11eb-8bca-7d0260bcbb6d.png)

I had an idea https://github.com/sindresorhus/refined-github/pull/3566#issuecomment-701668970

> What if we merged https://github.com/sindresorhus/refined-github/blob/master/source/features/hide-empty-meta.tsx
With https://github.com/sindresorhus/refined-github/pull/3566 and 47a2849 into one feature of clean-repo-sidebar?

**Comment by fregante** [comment]
Idea sounds good
