### ISSUE TITLE
Link to pull request from blame view

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#367]
I often use GitHub blame to find a commit which introduced something, just to then find the PR which added this to see it in more context.

I think it would be useful to have a small button pointing to the PR directly from the blame view. For performance reasons, I imagine it would be calculated with an HTTP request only when the button is clicked, and not for every commit shown on the blame page.

It's not a really big change in terms of functionality as it just saves one more click, but I guess it would be useful for people to integrate this more into their workflow and see things in context.

What do you think?

**Comment by sindresorhus** [comment]
> For performance reasons, I imagine it would be calculated with an HTTP request only when the button is clicked, and not for every commit shown on the blame page.

How would it know whether to show the button or not without first doing a HTTP request?

**Comment by hkdobrev** [comment]
Closing this as I honestly how it'd be possible in a performant manner.
