### ISSUE TITLE
Misalignment in the home

### ISSUE THREAD

**Issue by stenalpjolly** [sindresorhus/refined-github#3671]
After enabling the personal token with Github

![image](https://user-images.githubusercontent.com/8219855/96542448-b5052980-12bf-11eb-99ab-0b7c297455e7.png)

**Comment by fregante** [comment]
It looks like you also have a [JetBrains extension](https://chrome.google.com/webstore/detail/jetbrains-toolbox-extensi/offnedcbhjldheanlbojaefbfbllddna?hl=en) enabled. Either disable that or disable the `latest-tag-button` feature.

**Comment by fregante** [comment]
Or ask them to apply the `d-flex` class on their `.BtnGroup` element to avoid the wrapping:

<img width="794" alt="" src="https://user-images.githubusercontent.com/1402241/96543913-10f19300-126b-11eb-8f78-dc1101882fbb.png">
