### ISSUE TITLE
`latest-tag-button`, `default-branch-button` and `list-prs-for-file` are not fast/reliable enough

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3673]
1. Visit https://github.com/sindresorhus/refined-github/blob/42dfa16cd5366de26b475de94f8225003df07364/source/features/list-prs-for-file.tsx (or any file with an open PR) 
2. Refresh the page
3. Wait for each button to appear, if ever

![a212](https://user-images.githubusercontent.com/1402241/96651315-3679ad80-12fa-11eb-9c96-6436d9fa40b1.gif)

These are 3 separate features but they affect the same area. I think they should be reviewed to understand why they're so slow and why `latest-tag-button` sometimes doesn't appear at all. 

`default-branch-button` is the most annoying one because it's a simple feature with data that's easily available, it should be instant.

**Comment by yakov116** [comment]
Debugged `default-branch-button`
If we move this
https://github.com/sindresorhus/refined-github/blob/017c17b36565186d87edb7618d781b0e87b206f3/source/features/default-branch-button.tsx#L19-L19
Before this
https://github.com/sindresorhus/refined-github/blob/017c17b36565186d87edb7618d781b0e87b206f3/source/features/default-branch-button.tsx#L13-L13

There is almost no jump at all. (not perfect but better then before)

**Comment by fregante** [comment]
Makes sense! Any API calls should appear before `elementReady`, or else we _definitely_ wait too long.

**Comment by fregante** [comment]
Here's an error:

```
refined-github.js:5657 ❌ Refined GitHub → latest-tag-button → TypeError: Cannot read property 'parentElement' of null
    at init (refined-github.js:6078)
    at async runFeature (refined-github.js:5697)
    at async setupPageLoad (refined-github.js:5710)
```

It can't find `#branch-select-menu`. It happened on the root of a fork:

https://github.com/fregante/refined-github
