### ISSUE TITLE
"Enhanced" recently-pushed branches box is the wrong color with GitHub Dark style

### ISSUE THREAD

**Issue by dgw** [sindresorhus/refined-github#3674]
This issue is a combination of updated styles from GitHub (see StylishThemes/GitHub-Dark#1236, but I wasn't sure until now if the fix for that had also fixed this) and the `recently-pushed-branches-enhancements` feature from Refined GitHub.

Without RGH:
![image](https://user-images.githubusercontent.com/164140/96671170-dbaa7b00-1326-11eb-971d-5cd9e3cd54c9.png)

With RGH (and the `recently-pushed-branches-enhancements` feature enabled):
![image](https://user-images.githubusercontent.com/164140/96671242-f7ae1c80-1326-11eb-9b59-bfd63323bc78.png)

I can't really link to a page that shows this issue, but I think the maintainers of this extension probably push code often enough that they'll be able to reproduce really quickly! 😁

I'm honestly not sure "who" was responsible for correctly styling the box when it gets moved to the header, but in the interest of covering all bases I also submitted StylishThemes/GitHub-Dark#1242.

**Comment by fregante** [comment]
The feature was not changed at least since July, so this is likely due to new styles in GitHub Dark

**Comment by the-j0k3r** [comment]
> The feature was not changed at least since July, so this is likely due to new styles in GitHub Dark

Since GitHub recently changed to use CSS vars that are only available to logged in users (for some reason). This is still causing havoc in GHD but all refined GH stuffs are generated so as long as there are primer classes in use by refined GH then it will eventually sort itself out, that or manual overrides.
