### ISSUE TITLE
Tooltip doens't appear on "Add File"

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [sindresorhus/refined-github#3675]
**Bug**
When hovering over the "Go to file" button, there is a little message, when hovering over the "Add file" button the little message doesn't appear, only once clicked.

_this might be a minor issue_

**Gif**
![](https://media3.giphy.com/media/Aa7uz5i1yeMfgInBct/giphy.gif)

**Browser**
Firefox 82 On MacOS & Windows.

**Comment by notlmn** [comment]
Funnily https://github.com/sindresorhus/refined-github/pull/3646/files#diff-5ba5120afe524f2d5eed502b044996a1db29ba24221b41edee322940746bf553R15-R16 assumed that the element after the search button would be the "file button", but in a single file view it is the "more options" button, causing this to happen: 

![image](https://user-images.githubusercontent.com/37769974/96722445-06e6a600-13cb-11eb-8a0e-45516e1aadd2.png)

**Comment by yakov116** [comment]
If I am not mistaken https://github.com/sindresorhus/refined-github/pull/3531 is taking care of it.

**Comment by ocarreterom** [comment]
Works for me on Chrome 86 for macOS.

![Grabación de pantalla 2020-10-22 a las 0 16 31](https://user-images.githubusercontent.com/11599942/96793618-0109b880-13fd-11eb-8d15-caffecf7d02d.gif)

**Comment by fregante** [comment]
> Works for me on Chrome 86 for macOS.

Same for me on Safari 
<img width="219" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/106485096-dc01f880-6475-11eb-9c6e-bf4392fb1398.png">
