### ISSUE TITLE
Template responses for issues

### ISSUE THREAD

**Issue by ssbarnea** [sindresorhus/refined-github#3679]
It is quite common for users to abuse the freely accessible project issue tracker to post what counts as support tickets, even if the owner did his best to avoid this by improving the new issue github templates.

It would be very useful to be able to define templated replies to be used for these where you can produce a polite response.

**Comment by fregante** [comment]
Do you mean [Saved replies](https://github.blog/2016-03-29-saved-replies/)?

**Comment by ssbarnea** [comment]
Oops, sorry and thanks! Time to running and hide.
