### ISSUE TITLE
`cleanup-repo-filelist-actions`: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by jl-applied** [sindresorhus/refined-github#3685]
1. Make sure the bug is caused by Refined GitHub. Try disabling the extension first.
Confirmed. Also noticed the page loads substantially faster when disabled

2. Include a full URL where the bug appears.
https://github.com/docsifyjs/docsify/blob/da9af18c4e4aa8b2c42773a01104f5a7c0a628a4/src/core/util/dom.js

```
refined-github.js:1 ❌ Refined GitHub → cleanup-repo-filelist-actions → TypeError: Cannot read property 'classList' of null
    at init (refined-github.js:1)
    at c (refined-github.js:1)
    at at (refined-github.js:1)
    at refined-github.js:1 
```

3. Include a screenshot/gif
![Peek 2020-10-23 12-27](https://user-images.githubusercontent.com/49570001/97045949-7e334b80-152b-11eb-86e6-98b8a1be76db.gif)

**Comment by fregante** [comment]
Might be fixed by https://github.com/sindresorhus/refined-github/pull/3531
