### ISSUE TITLE
Parse Markdown feature descriptions

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#3687]
_Originally posted by @fregante in <https://github.com/sindresorhus/refined-github/pull/3678#discussion_r510589853>:_

> I'd like to see the most lightweight Markdown parser being run directly to the description text to store HTML so the entire `parseDescription` function can be dropped.
>
> Parser example: [Holixus/nano-markdown](https://github.com/Holixus/nano-markdown)
> [bundlephobia.com/result?p=nano-markdown@1.2.1](https://bundlephobia.com/result?p=nano-markdown@1.2.1)

I've done a little comparison between multiple lightweight Markdown parsers, and I don't think we can directly use any of them 🙁

Features they should support:

1. code span with single backtick: ``` `` ` `` ```
2. code span with a backticked word: ``` `` `bla` `` ```
3. inline URLs: `https://example.org` or `<https://example.org>`
4. don't escape HTML tags: `**bold** or <b>bold</b>`

| Parser                                                    | Size                                                   | 1. single backtick | 2. backticked word | 3. inline URLs | 4. don't escape HTML |
|-----------------------------------------------------------|--------------------------------------------------------|---------------------|---------------------|---------------------|----------------------|
| [nano-markdown](https://github.com/Holixus/nano-markdown) | [2kB](https://bundlephobia.com/result?p=nano-markdown) | :x:                 | :x:                 | :x:                 | :heavy_check_mark:   |
| [snarkdown](https://github.com/developit/snarkdown)       | [2kB](https://bundlephobia.com/result?p=snarkdown)     | :x:                 | :x:                 | :x:                 | :heavy_check_mark:   |
| [downa](https://github.com/mrvautin/downa)                | [1.9kB](https://bundlephobia.com/result?p=downa)       | :x:                 | :x:                 | :x:                 | :heavy_check_mark:   |
| [md.js](https://github.com/thysultan/md.js)               | [2.7kB](https://bundlephobia.com/result?p=md.js)       | :x:                 | :x:                 | :x:                 | :heavy_check_mark:   |
| [tinydown](https://www.npmjs.com/package/tinydown)        | [4kB](https://bundlephobia.com/result?p=tinydown)      | :heavy_check_mark:  | :heavy_check_mark:  | :x:                 | :x:                  |
| [drawdown](https://github.com/adamvleggett/drawdown)      | 1.5kB <sup>1)</sup>                                    | :heavy_check_mark:  | :x:                 | :x:                 | :x:                  |
| [mmd.js](https://github.com/p01/mmd.js)                   | 0.8kB <sup>2)</sup>                                    | :x:                 | :x:                 | :x:                 | :x:                  |

Notes:

1) not distributed via npm, 2.8kB [unminified](https://github.com/adamvleggett/drawdown/blob/master/drawdown.js), about 1.5kB minified
2) not distributed via npm, 1.0kB [unminified](https://github.com/p01/mmd.js/blob/master/mmd.js), 0.8kB [minified](https://github.com/p01/mmd.js/blob/master/mmd.min.js)

**Comment by fregante** [comment]
I don’t think that the first column is correct, Snarkdown *does* support back ticks, it’s in the first example. 

Also what happens when “html is not supported”? Support means leaving it untouched; does it mean it escapes it instead?

**Comment by fregante** [comment]
Double backticks aren’t on my priority list by the way; if they’re supported without a mess, it’s good; if not, no problem, we can use `<code>` in the readme.

**Comment by fregante** [comment]
Actually the module isn’t meant to be packaged, I wrongly mentioned the need to be small. What matters is speed, since we don’t want it to slow down the build further. 

Any decent CommonMark library should do.

**Comment by FloEdelmann** [comment]
> Snarkdown _does_ support back ticks, it’s in the first example

All modules do support simple ``lorem `ipsum` dolor`` code spans. The first column is specifically about code spans with single backtick (``` `` ` `` ```), the second one about code spans with a backticked word (``` `` `bla` `` ```). I didn't think about just being able to use `<code>` in the readme though.

> Also what happens when “html is not supported”? Support means leaving it untouched; does it mean it escapes it instead?

:heavy_check_mark: = HTML is untouched
:x: = HTML is escaped (e.g. `<b>bold</b>` → `&lt;b&gt;bold&lt;/b&gt;`)

> Actually the module isn’t meant to be packaged, I wrongly mentioned the need to be small. What matters is speed, since we don’t want it to slow down the build further.
> 
> Any decent CommonMark library should do.

I think that makes finding a suitable library much easier, though it's difficult to judge the speed. I'll try to find one :)

**Comment by fregante** [comment]
To judge the speed: use the library and run the build again. If it takes ~the same time we’re good.
