### ISSUE TITLE
Why are those PR-s grayed out?

### ISSUE THREAD

**Issue by TheChilliPL** [sindresorhus/refined-github#3690]
![image](https://user-images.githubusercontent.com/18823939/97498137-efc82b00-196b-11eb-9bef-ded7cf5e1557.png)
I couldn't find any feature in the options that could make those PR-s grayed out.

**Comment by yakov116** [comment]
Because they are bots PRs.
The feature is called [dim bots](https://github.com/sindresorhus/refined-github/blob/master/source/features/dim-bots.tsx ) you can disable it in the options.

**Comment by TheChilliPL** [comment]
Oh, I can see that now, thanks!
