### ISSUE TITLE
Option to disable hiding bot issues / commits 

### ISSUE THREAD

**Issue by l1ving** [sindresorhus/refined-github#3691]
Hi, I use a Github App as a Github Bot to create issues from a Discord Bot onto Github (quite confusing, I know), and it's annoying to have these issues collapsed by refined github

![image](https://user-images.githubusercontent.com/17222512/97604414-d8c51f80-19e3-11eb-9828-3bddccee5a4c.png)

An option to disable this functionality would be great

**Comment by yakov116** [comment]
The feature is called dim bots you can disable it in the options.

**Comment by l1ving** [comment]
Oh, thank you!
