### ISSUE TITLE
Add a keyboard shortcut to cancel editing title

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3692]
Add a keyboard shortcut to cancel editing title (e.g. <kbd>esc</kbd>, just like #961 when editing a comment).

**Comment by fregante** [comment]
This is a super simple feature, could you send a PR? Can be named generically `esc-to-cancel`. There’s another similar feature as well, but they’re different enough to be separate.

**Comment by Geeyun-JY3** [comment]
> This is a super simple feature, could you send a PR?

I am not a coder😂.

**Comment by Liberatys** [comment]
I took the liberty of working on this ^^
