### ISSUE TITLE
Toggle for load diff option in a PR to allow always load or don't load

### ISSUE THREAD

**Issue by audip** [sindresorhus/refined-github#3700]
![image](https://user-images.githubusercontent.com/4290846/98292647-e178a100-1f61-11eb-81ab-385c4e561496.png)

When someone deletes a file, refined github should always show the diff instead of the `Load diff` as deleting files is a risky change. As I understand that `always` is not a stance that everyone will agree with, consider an option for refined github to allow loading of diffs (always).

Screenshot is an example of an important file that was getting removed and we could have missed it without actually loading the diffs

**Comment by yakov116** [comment]
## 2. It makes sense as a default for everyone.

"Disabled by default" means most people don't need it, so it doesn't belong to Refined GitHub. In that case, it's best to keep it as a standalone userscript or extension.

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382_

**Comment by audip** [comment]
Okay, that's fair. Thank you!
