### ISSUE TITLE
The highlight style of the highest rated comment looks strange

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3703]
The highlight style of the highest rated comment looks strange. I am sure that it's not like this before.

URL: https://github.com/sindresorhus/refined-github/issues/2357#issuecomment-523254108

Screenshot: 
![image](https://user-images.githubusercontent.com/49396421/98360460-d0648880-2064-11eb-9a49-038e014f04c0.png)

**Comment by fregante** [comment]
GH change the Discussion style completely. Example: https://github.com/vercel/vercel/discussions/5135

<img width="650" alt="Screen Shot 2020-11-21 at 22 41 32" src="https://user-images.githubusercontent.com/1402241/99894572-bcb34780-2c4a-11eb-9601-49108f459bad.png">
