### ISSUE TITLE
`selection-in-new-tab` stopped working in notifications

### ISSUE THREAD

**Issue by yeled** [sindresorhus/refined-github#3704]
https://github.com/sindresorhus/refined-github/pull/1240 has stopped working.

I can no longer `shift + O` to open notifications in a new tab.

In fact, a lot of my notifications shortcuts are no longer working, including `open-all-notifications`

**Comment by fregante** [comment]
It looks like #3695 broke the extension on every non-repository page. I'll have to release a hotfix
