### ISSUE TITLE
auto-expand PR deployment preview environments

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#3705]
E.g. for Vercel PR previews (not sure if it applies also to Netlify etc.).

From:

![image](https://user-images.githubusercontent.com/5153846/98411785-fc890500-2076-11eb-8b59-191adb0ee67d.png)

To:

![image](https://user-images.githubusercontent.com/5153846/98411808-03b01300-2077-11eb-863a-84daadc91cfd.png)

Check it out on https://github.com/excalidraw/excalidraw/pull/2341 (scroll to the bottom).

It wastes a lot of time having to expand that preview manually every time.

**Comment by yakov116** [comment]
Does this still apply?

Looks like there is a direct button now

![image](https://user-images.githubusercontent.com/16872793/110657620-f9ba3000-818e-11eb-9b84-b717c6a9d0dd.png)

**Comment by dwelle** [comment]
Technically true, but if there's a lot of comments or other events after the last deployment, you'd need to hunt down the button in the mess. But feel free to close this.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/2918 ?

**Comment by dwelle** [comment]
Woah, that's super nice. Let's close it in favor of #2918 then!
