### ISSUE TITLE
`Releases` widget is hidden away on all repos

### ISSUE THREAD

**Issue by epk** [sindresorhus/refined-github#3706]
`Releases` widget is hidden away on all repos

With refined-github disabled
![image](https://user-images.githubusercontent.com/9075816/98434594-3110b700-209f-11eb-848d-e4b5a0e9235e.png)

With refined-github enabled
![image](https://user-images.githubusercontent.com/9075816/98434573-045c9f80-209f-11eb-849b-16425149c5ab.png)

**Comment by Geeyun-JY3** [comment]
See #3566 ?

**Comment by fregante** [comment]
This is part of `releases-tab`

**Comment by epk** [comment]
> This is part of `releases-tab`

Oh sorry, I wasn't aware this was purposefully removed.

Is this something I can toggle? 

IMO the releases widget provides quick access to the latest release version, it is quite helpful to just open a repo and see what the latest release is.

**Comment by Geeyun-JY3** [comment]
@fregante https://github.com/sindresorhus/refined-github/pull/3566#issuecomment-699485859
This should be mentioned in the description of `releases-tab` and also be showen in the screenshot.

**Comment by fregante** [comment]
> IMO the releases widget provides quick access to the latest release version

So does the Releases tab that Refined GitHub adds; it even appears on every page of the repo instead of just the home tab

> see what the latest release is.

The extension also shows the latest tag right next to the branch selector.

We hide that widget because we already have better features that display the same information. 

If you want to disable it, the feature is called `releases-tab` (and it can’t be split)

**Comment by fregante** [comment]
This part of `releases-tab` was consolidated into `clean-repo-sidebar` so it can be disabled independently from `releases-tab`

**Comment by fregante** [comment]
It was discussed here: https://github.com/sindresorhus/refined-github/pull/3566#issuecomment-700611153
