### ISSUE TITLE
show-whitespace shows too many placeholders on Firefox with Minimum font size

### ISSUE THREAD

**Issue by oprypin** [sindresorhus/refined-github#3709]
The grey-colored placeholders are inserted at a rate of about 120% compared to what the real amount of whitespace is.

![Screenshot with spaces](https://user-images.githubusercontent.com/371383/98464189-69101b00-21c1-11eb-811e-c9d97b6c970c.png)

![Screenshot with tabs](https://user-images.githubusercontent.com/371383/98464282-108d4d80-21c2-11eb-8781-f524d8b299fa.png)

Firefox 82.0.2 running on Arch Linux, KDE Plasma

My zoom level and my DPI settings (`GDK_DPI_SCALE=1.1`) are non-default but changing those has **no** effect on the problem.

I have reduced the problem by creating a new profile (`firefox -P`) and only changing the setting "Minimum font size" from *None* to *15*. It still reproduces then.

![Minimum font size setting](https://user-images.githubusercontent.com/371383/98464537-df158180-21c3-11eb-9e9c-21736318a90c.png)

**Comment by fregante** [comment]
Unfortunately this is a Firefox bug. 

We use the `ch` character to define how wide the "tab" image should be. Firefox does not adjust the size of the `ch` unit to match the actual character size.

Here's a barebones example: https://codepen.io/fregante/pen/rNLEqPr

```html
<p>ciao</p>
<div></div>
```
```css
html {
  font-family: monospace;
}
div {
  width: 4ch;
  height: 4ch;
  background: red
}
```
Regular on the left; minimum size 20 on the right

<img width="195" alt="" src="https://user-images.githubusercontent.com/1402241/99894508-eddf4800-2c49-11eb-91f0-247990cf8f43.png">


You can see that the word size increased, but the `4ch*4ch` square doesn't follow it.
