### ISSUE TITLE
Toggle changes in Markdown preview diff

### ISSUE THREAD

**Issue by privatenumber** [sindresorhus/refined-github#3711]
### Feature
To be able to hide/show the diff in Markdown change previews.

For example, when editing a Markdown file on GitHub.com, you can preview your changes:
https://github.com/sindresorhus/refined-github/edit/master/readme.md

### Use-case
I often edit markdown files in the GitHub UI because it's quick and easy, but when the changes are complex, it becomes hard to see the final output because the diff clutters the preview.

In these cases, I would love to be able to just see the final output instead of what I removed/modified.

<img width="1112" alt="Screen Shot 2020-11-10 at 2 22 05 PM" src="https://user-images.githubusercontent.com/1075694/98723305-2f294b00-2360-11eb-9716-5cc93364b09c.png">

**Comment by fregante** [comment]
I just looked into the DOM and apparently there's a keyboard shortcut to toggle the preview: `Control+P,Meta+Shift+p`

Unfortunately the preview is rendered server-side, so keeping it visible means sending and waiting for every (few) keystroke(s).

There's probably an extension that does this by the way, but we likely won't implement this for that reason.
