### ISSUE TITLE
Add a link from the branch commits page to the PR page

### ISSUE THREAD

**Issue by leventov** [sindresorhus/refined-github#3713]
Branch commits page: `https://github.com/<user>/<repo>/commits/<branch-name>`

Would be nice to add a link from this page to the PR page, if a PR exists for the branch.

**Comment by yakov116** [comment]
Can you provide a real URL? With a real example?

**Comment by leventov** [comment]
https://github.com/sindresorhus/refined-github/commits/ghat (I'm not sure whether there is a PR for this branch)

**Comment by yakov116** [comment]
Not pushing away the issue just trying to see the use case.

I usually go to the branches screen to see if the open PR's on a local branch.

**Comment by fregante** [comment]
Currently you can click on the latest commit and then GitHub will show a link:

![](https://user-images.githubusercontent.com/1402241/98844981-b6cf9200-2412-11eb-9048-d288b4fc3834.jpeg)

However I agree with the general idea that the UI sometimes lacks a way to go from the code to the PR. For example also on any Action Run page it shows the commit but nothing else.
