### ISSUE TITLE
`align-issue-labels` doesn't work in milestone issue listing page

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3715]
URL:
1. https://github.com/microsoft/PowerToys/milestone/8?closed=1
2. https://github.com/microsoft/PowerToys/milestone/4
Screenshot: 
1. ![image](https://user-images.githubusercontent.com/49396421/98892917-51e06e80-24dc-11eb-87b2-410c9390af10.png)
2. ![image](https://user-images.githubusercontent.com/49396421/98895052-1bf1b900-24e1-11eb-8464-6a2348b3ca24.png)

**Comment by fregante** [comment]
`isConversationList` in https://github.com/fregante/github-url-detection probably needs to include that page too

**Comment by fregante** [comment]
Thanks for the report! It will appear fixed in the next dependency update here.
