### ISSUE TITLE
`parse-backticks` is broken on the dashboard “Recent activity”(or more?)

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3716]
I don't know if it still works in “All activity”. I only test it in “Recent activity”.
URL: https://github.com/
Screenshot: 
![image](https://user-images.githubusercontent.com/49396421/98932352-3300cd00-251a-11eb-913b-c8b34cd017e6.png)

**Comment by yakov116** [comment]
Working fine for me

![image](https://user-images.githubusercontent.com/16872793/99085882-c0820280-2596-11eb-88f7-7c502b30783b.png)

**Comment by Geeyun-JY3** [comment]
Strange. I cannot reproduce it now. Also working fine now🤦‍♂️.
