### ISSUE TITLE
Remove upgrade link from menu

### ISSUE THREAD

**Issue by aliglelo** [sindresorhus/refined-github#3717]
There is some chane in menu on right side of github.There appears now an option of `"upgrade"` instead of `"marketplace"` which i don'think every normal user has to see every time when he/she clicks the menu.SO please try to remove the option or replace it with `MArketplace` option.

**Comment by fregante** [comment]
Screenshot? I'm not seeing it

<img width="733" alt="" src="https://user-images.githubusercontent.com/1402241/99896288-c0e46280-2c54-11eb-80b1-2688595cffd8.png">

**Comment by aliglelo** [comment]
![Screenshot_20201122_1148-1](https://user-images.githubusercontent.com/30858084/99897141-d5f2dd00-2cb8-11eb-92d4-cb1668b41478.png)

See right after the **Marketplace** link

**Comment by fregante** [comment]
It's already hidden in a menu, we shouldn't hide what makes GitHub money.
