### ISSUE TITLE
Make `one-key-formatting` also works in any title field

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3718]
Now that `parse-backticks` feature works in issue titles, commit titles and more places, why not make `one-key-formatting` also works in any title field? I think many RGH users who enable `parse-backticks` feature have get used to adding backticks when writing a title. It would be a great convenience.
IMO, not all the symbols supported in comment field also need to be supported in title textarea. Maybe supporting ``[ ` ' "`` is enough.

BTW, it seems that `one-key-formatting` doesn't work consistently. But I don't know how to reproduce it. Just encouter this bug again and again🤣.

URL: issue page, pull request page and more

**Comment by fregante** [comment]
> all the symbols supported in comment field also need to be supported in title textarea. Maybe supporting `` [ ` ' " `` is enough.

👍
