### ISSUE TITLE
Mark comments as resolved/unresolved

### ISSUE THREAD

**Issue by jiaweihli** [sindresorhus/refined-github#372]
https://github.com/benbernard/CommentTracker has a good implementation of this.  Could we add this to refined-github and enable it via an option on a per-repo basis?

**Comment by paulmolluzzo** [comment]
From the README:

> We're not interested in adding options as it's a slippery slope into adding it for everything.

As for the feature itself, personally, I don't want it. GH has a native way for putting a revision request on a PR and that seems more in line with what I want. It seems like if I don't deselect all the repos I'll have an "Unresolved" badge on all comments and have to click them just to change the color. :-1:

Besides, this extension was updated two months ago. Why not install their extension?

**Comment by jiaweihli** [comment]
Being able to request reviews is different from being able to resolve a comment.

When reviewing large PRs, Github automatically folds a comment as outdated if the code around that area's changed.  But outdated doesn't necessarily mean resolved.  As the number of comments on a PR increases, it becomes more and more difficult to make sure everything's been addressed.  I've seen many projects use the equivalent of replying 'Done' to each comment to make up for this.

If you don't want this to be an option, this could be enabled but opt-in on a per-repo basis.  As in, you can show comment resolution statuses by hitting a shortcut, and refined-github would remember this preference until you choose to turn it off.  It'd be similar to how Github implements split/unified view, but at a per-repo level.

One reason why I proposed adding this is because I'd rather use 1 extension instead of 2, and I know other people who'd feel similarly.  Part of the value of refined-github is that it centralizes a lot of quality of life improvements.  As an extreme counterargument: if refined-github were split out modularly and I needed to do a separate installation for each improvement, I wouldn't use any of them.

Also, I'm proposing the slightly tweaked implementation I mentioned above.

**Comment by hkdobrev** [comment]
I think this is not a simple problem and efforts should be targetted in improving the other browser extension instead of duplicating non-trivial functionality.

**Comment by hkdobrev** [comment]
- GitHub now has PR review dismissals
- We're heavily using 👍 on review comments on reply comments to mark something is updated
- I'll suggest contacting GitHub about adding ✅ to emoji reactions
- You could contact GitHub with more suggestions on PR review comment resolutions
- You could spend time improving the other extension focusing on PR review comments
- It's too big of a scope and effort for Refined GitHub

Let me know if someone else from the core team disagrees and think we should add this. @sindresorhus @jgierer12 @bfred-it @busches @DrewML

**Comment by jiaweihli** [comment]
That's fair, thanks for following up on this.

**Comment by paulmolluzzo** [comment]
> there's no easy way to ask GitHub for all the comments that don't have a 👍, right?

Filter by reaction. Someone please build this! 🙏🙏🙏

**Comment by tibdex** [comment]
GitHub just shipped https://blog.github.com/changelog/2018-08-31-resolvable-conversations/.
