### ISSUE TITLE
A number of items in the issue sidebar are missing

### ISSUE THREAD

**Issue by knowler** [sindresorhus/refined-github#3728]
Using Firefox 82.0.3 on macOS 11.0.1.

Seems like everything would be missing unless it is already set. So for example, the label is set here because it comes from a template (note the missing header tho), the issue was added to a project via the Projects UI. Stuff like assignee, milestone, linked pull requests, etc. are missing.

<img width="316" alt="Screen Shot 2020-11-16 at 10 11 37 AM" src="https://user-images.githubusercontent.com/6908001/99278469-b3624f00-27f4-11eb-997e-b91c58c949bf.png">

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/master/source/features/sticky-sidebar.tsx

**Comment by knowler** [comment]
huh, just disabled the feature, I don’t know how I’ve never noticed that until today. Aside, there seems to be a GitHub-at-large issue where the sidebar items are unactionable. Closing this. Thanks for the quick reply.

**Comment by fregante** [comment]
> huh, just

Why? All that the feature does is hide empty sections. What's the point of showing "Labels: none"?

**Comment by knowler** [comment]
@fregante Sorry, I meant that _I_ had just disabled the feature for myself and noticed the feature which I hadn’t known existed. I definitely agree that it is valuable — and I even turned it back on. My confusion stemmed from admins of the org I am a part of who set everyone in the org to read access which hid those sections which, with my previous permissions, I would have been able to see even when empty. Since my initial impression was that this was an issue larger than our org, I thought, “Oh, GitHub must have changed something that broke Refined GitHub,” and sure enough disabling the Firefox addon seemed to fix the issue — except I failed to notice that I still couldn’t edit those sections as my previous permissions would have allowed, missing the real issue, the change in our organization settings.

Sorry that my confusion has spilled over into this issue tracker.
