### ISSUE TITLE
Duplicating comments section

### ISSUE THREAD

**Issue by smac89** [sindresorhus/refined-github#3729]
This is the error I see in FF devtools:

```
`profile-hotkey`: can't access property "dataset", select_dom(...) is null
```
And in Vivaldi (a Chromium-based browser):
```
`profile-hotkey`: Cannot read property 'dataset' of null
```

I'm not sure if the above actually has anything to do with the error which I will now describe in full

### URL
https://github.com/ytdl-org/youtube-dl/commit/1fb034d029c8b7feafe45f64e6a0808663ad315e

The main issue I noticed is that after being on the page for a while, it starts duplicating the comments.

### Example on FF:
![Peek 2020-11-16 16-07](https://user-images.githubusercontent.com/8305511/99314036-6617c900-2858-11eb-914d-001d66048e5c.gif)

As of creating this issue, it has duplicated the comments **6 times!**.

### On Vivaldi:
![Peek 2020-11-16 15-56](https://user-images.githubusercontent.com/8305511/99313230-1684cd80-2857-11eb-97b8-0d134e94eadc.gif)

### Live example showing how it occurs on FF
![Peek 2020-11-16 14-24](https://user-images.githubusercontent.com/8305511/99305667-fac7fa00-284b-11eb-86e2-a1f6f0d7d904.gif)

What I do is scroll to the bottom of the page, then I scroll to about 3/4  of the page and start scrolling up and down erratically. After a couple seconds of doing this, the comments are duplicated and I scroll all the way down. You will notice the duplicated comments do not show profile icons beside the reaction emojis for each comment.

Furthermore, this does not seem to occur where I am not logged into github. I've opened a FF container tab where I'm not logged into Github, and I do not notice this issue. The same is true with Vivaldi: When I'm not logged in, the page displays as usual, no duplication.

**Comment by yakov116** [comment]
I get the duplicate issue even with RG turned off

**Comment by fregante** [comment]
I can't replicate either way, I assume it was GitHub themselves glitching up because the comment section was quite active (including the reactions)

**Comment by fregante** [comment]
Yep, it just happened to me without Refined GitHub (notice the lack of avatars)

<img width="889" alt="" src="https://user-images.githubusercontent.com/1402241/99324810-a23c3100-283a-11eb-8449-fef473a4966b.png">

**Comment by smac89** [comment]
Oh wow that's quite interesting. I guess I will raise the issue with Github...if that's even possible lol
