### ISSUE TITLE
Strike through link to closed issue

### ISSUE THREAD

**Issue by durka** [sindresorhus/refined-github#373]
Like Bugzilla, strike through the link to a closed issue or PR. Perhaps some slightly different formatting for merged PRs as well. cf https://github.com/isaacs/github/issues/451, https://github.com/isaacs/github/issues/313

**Comment by sindresorhus** [comment]
Would be useful indeed, but we would have to use the GitHub API for this, which has limits on how many requests we can do, so it gets complicated fast. We would also need to have an options page for the user to save their token. We could fetch the whole page instead and have no limits, but that's wasteful.

**Comment by hkdobrev** [comment]
I would have liked that if it could have been done without requests.

Regarding the actual UI, I'd go with an icon of open/closed issue/PR. This way you'll also know what's this number is referring to.

**Comment by durka** [comment]
This seems to be the same as #202.

**Comment by hkdobrev** [comment]
@durka You are absolutely right! Closing in favour of #202.
