### ISSUE TITLE
`global-conversation-list-filters` creates faulty links

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#3731]
<img width="1679" alt="스크린샷 2020-11-18 오후 1 43 31" src="https://user-images.githubusercontent.com/29705162/99484581-134b2800-29a4-11eb-893f-5da11de31320.png">
In my review requests tab of PRs menu, whenever to click commented tab, the error occurs.

How to fix that? or already has it fixed?

----
Using extension's version is 20.11.12 and my chrome's version is 86.0.4240.111.

**Comment by yakov116** [comment]
It will be fixed in the next release (tomorrow)

**Comment by KSH-code** [comment]
Thank you for help.
close it, because my problem's been solved.

**Comment by KSH-code** [comment]
@yakov116 The bug has not been solved until now.
Is this fixed?

**Comment by yakov116** [comment]
Not happening by me

**Comment by yakov116** [comment]
Can you please paste the error here?

**Comment by fregante** [comment]
Could there be an issue with a dashed username?

**Comment by fregante** [comment]
Can you paste the URLs of the steps 2 and 4? We will know exactly what's happening

**Comment by KSH-code** [comment]
1. https://github.com/pulls/review-requested
2. https://github.com/pulls/review-requested?q=is%3Apr+is%3Aopen+archived%3Afalse+commenter%3AKSH-code

when 2, Review Requests tab is still active.
@fregante @yakov116 

There is no error in console.

**Comment by fregante** [comment]
This piece of code is not working:

https://github.com/sindresorhus/refined-github/blob/ae020ab5d6c851045b39cd794e384e7aa4c91f1e/source/features/global-conversation-list-filters.tsx#L35-L38

Or rather, the `SearchQuery` is probably unable to correctly remove the `commenter:` query due to the dash in the username

**Comment by KSH-code** [comment]
@fregante 
Hey, I'm back here issue.
I was wondering this issue can be fixed soon.
If no and I have time to fix this, I will fix on my own. but I'm newbie about TS.
so to fix it will spend lots of time. 😂

**Comment by fregante** [comment]
The problem doesn't seem to be what I thought. This `SearchQuery` test passes correctly:

```ts
test('.remove with dash', t => {
	// Native "Review requested" query after user visits the `Commented` tab
	const query = new SearchQuery({q: 'is:pr is:open archived:false commenter:KSH-code sort:updated-desc review-requested:KSH-code'});

	// Replicates line 37 shown above
	query.remove('commenter:KSH-code');

	t.is(query.get(), 'is:pr is:open archived:false sort:updated-desc review-requested:KSH-code');
});
```

**Comment by KSH-code** [comment]
@fregante 
Hey, It's been a while.
The problem has been solved by update via Chrome developer mode.
It occurs when pathname ends with review-requested but now, only pathname represents pulls.

**Comment by KSH-code** [comment]
Oooops, I have just found the bug.
The reason why the bug occurs is because of sort option.
I'll fix soon.

**Comment by KimGenius** [comment]
Thanks ! :)
