### ISSUE TITLE
Footer is in front of the dialog

### ISSUE THREAD

**Issue by eai04191** [sindresorhus/refined-github#3732]
![2020-11-19_01-43-12_chrome](https://user-images.githubusercontent.com/3516343/99560481-41168800-2a09-11eb-8fe5-6c0aa543433d.png)

It's usually a cosmetic issue, but if the repository is very small (I just created it), the content is so short that Footer can overlap. In this case, the Save Changes button cannot be pressed.

### How to reproduce

1. Create new repository
2. Open `Edit repository details` dialog

**Comment by fregante** [comment]
One step missing:

3. Resize the window to be ~300px tall

Confirmed. This is likely due to `sticky-conversation-sidebar`.

Help wanted to fix this, but fixing this requires a good understanding of what's happening first (and how the `z-index` works in CSS)
