### ISSUE TITLE
`set-default-repositories-type-to-sources` not working

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3733]
<s>

1. Click my username
2. Visit the "Repositories" tab on my profile

or
</s>

1. Click your "user dropdown" (top-right corner of every page)
2. Click "Your repositories"

The URL should be

```
https://github.com/fregante?tab=projects&type=source
```

But is

```
https://github.com/fregante?tab=projects
```

**Comment by cheap-glitch** [comment]
Just tested this feature on the latest commit with both Firefox and Chromium, it's working fine for me.

**Comment by fregante** [comment]
How about your user dropdown?

<img width="213" alt="" src="https://user-images.githubusercontent.com/1402241/99846991-f4cc6480-2b3c-11eb-93bb-50702aec13ec.png">

Only this doesn't work for me

**Comment by cheap-glitch** [comment]
> How about your user dropdown?
> Only this doesn't work for me

Same here, I read your post too quickly, sorry about that.

It's probably caused by the lazy loading, using `selector-observer` would be appropriate here I guess?
