### ISSUE TITLE
Suggest changes on the PR when review particular commit

### ISSUE THREAD

**Issue by sleshchenko** [sindresorhus/refined-github#3736]
Hello, first of all, thank you for the great work!

Sorry if that exists but I missed it somewhere, I read all tooltips but did not found it.
So, during PR review - there is an ability to suggest changes on raw Github (at least that existed before I started using your extension).
See 6th item in https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request#starting-a-review

So, it mainly copies the content of the commented line into the `suggest` block

**Comment by sleshchenko** [comment]
Discovered that it's shown on PR review changes, but is not shown when the commit is chosen, which seems to be strange for me:
![Screenshot_20201119_114735](https://user-images.githubusercontent.com/5887312/99649753-4271a000-2a5d-11eb-91c0-85ddc3d37e2a.png)

![Screenshot_20201119_114756](https://user-images.githubusercontent.com/5887312/99649761-456c9080-2a5d-11eb-9f76-99fe210d737e.png)

Probably it's even better to ask Github to fix it, is so - let me know and close the issue.

**Comment by busches** [comment]
This is Github's behavior, not ours. You can suggest it to them, but if you're on commit two of twenty not sure how it'd be able to apply the suggestion.
