### ISSUE TITLE
`hide-zero-packages` hides packages tab on profiles when you only have private packages

### ISSUE THREAD

**Issue by hoshsadiq** [sindresorhus/refined-github#3737]
Somewhat relates to #3631. Seems when `hide-zero-packages` is enabled, and you only have private packages under your name, the packages tab is hidden in your profile. This makes it hard to find your packages (specifically, you can only find them by putting the URL directly).

On the repositories tab:
![image](https://user-images.githubusercontent.com/600045/99655758-ff5eff00-2a53-11eb-9ad4-495cada0772e.png)
On the packages tab:
![image](https://user-images.githubusercontent.com/600045/99655878-21588180-2a54-11eb-9306-eb231fec3513.png)

**Comment by fregante** [comment]
This is sort of a GitHub bug that we fall into. The Packages tab does not display the number of private packages inside, can you report this bug to GitHub?

**Comment by hoshsadiq** [comment]
Suppose that makes sense. I've reported it on their support page, let's see what happens.

**Comment by hoshsadiq** [comment]
I got a reply from GitHub support. The there is disabled on purpose due to performance issues:

> I don't think the count will include public packages either at the moment. There were performance implications when calculating the number of visible packages. I believe this is why the count was disabled.

**Comment by fregante** [comment]
It's great that you actually got an answer. 

We have 2 choices:

- drop the feature because it can't be reliable unless we query GitHub (doesn't seem worth it)
- suggest that you disable it 😬

**Comment by hoshsadiq** [comment]
I've already disabled it since I raised this. Perhaps an alternative would be to disable it for packages on profile pages? That is, providing it works fine everywhere else. If not, this can be closed, but this sounds like others will eventually come and report it.

**Comment by yakov116** [comment]
What if we disable on your own profile?

**Comment by fregante** [comment]
That would be a good compromise, we already do it with a number of features. It might be worth mentioning this issue in a JS comment as well.

The exclusion list also needs to include your organizations as well.
