### ISSUE TITLE
Pull request / Tab Files - Toggle files by clicking on their header bar

### ISSUE THREAD

**Issue by MrChocolatine** [sindresorhus/refined-github#3738]
When viewing the files list of a pull request,
it would be nice to be allowed to toggle any file by clicking on their "header bar" (bar that contains the filename, the checkbox `[ ] Viewed` and the 3-dots menu).

For instance on this page:
https://github.com/microsoft/TypeScript/pull/12114/files

This feature should appear on this kind of URL:
`https://github.com/<owner>/<repository>/pull/<pr_id>/files`

**Comment by fregante** [comment]
Not a bad idea. The hard part would be avoiding this behavior when clicking any other element on that bar.

Maybe

```js
document.addEventListener('click', handleClick)
function handleClick(event) {
	if (event.target.matches('that bar’s selector')) {
		select('that toggle’s selector', event.target)!.click()
	}
}

**Comment by MrChocolatine** [comment]
I dug a little bit and I got something working (by playing in the DevTools so _quick & dirty_):

```js
const listFiles = document.querySelector('#files');

listFiles.addEventListener('click', (event) => {

  const selectorHeaderBar = '.file-header.file-header--expandable';

  const elemClicked = event.target;
  const { parentElement } = elemClicked;
  const headerBar = parentElement.matches(selectorHeaderBar)
    ? parentElement
    : elemClicked;

  if (headerBar.matches(selectorHeaderBar) === false) {
    return
  }

  headerBar.querySelector('button').click();
});
```

**Comment by MrChocolatine** [comment]
@fregante I just sent a PR. Let me know if it fits how you work in your project.
