### ISSUE TITLE
Submission in CWS failed due to `Publish condition not met: To publish your item, you must certify that your data usage complies with our Developer Program Policies`

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#3739]
It's been 3 hours since the 20.11.19 release, and in [CWS](https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf) it's still the previous version, 20.11.12. That's why I checked the relevant Submit action and I see that it has failed for Chrome: 
https://github.com/sindresorhus/refined-github/runs/1425836312?check_suite_focus=true

Here is the error message:

> "message": "Publish condition not met: To publish your item, you must certify that your data usage complies with our Developer Program Policies. You can certify this on the Privacy tab of the item edit page of the Developer Dashboard.",

**Comment by sindresorhus** [comment]
I've submitted it for review.

**Comment by darkred** [comment]
The new version is now published in CWS.
Thank you.
