### ISSUE TITLE
Prevent copy from copying text from the adjacent column in a diff

### ISSUE THREAD

**Issue by karanrajpal14** [sindresorhus/refined-github#374]
When I try to copy text from a split diff, it should restrict the copying to one column only and not both. Would you please consider adding this?

**Comment by sindresorhus** [comment]
👎 That would add a lot of complexity for very limited gain. Just switch to Unified diff if you want to copy from a diff.

**Comment by karanrajpal14** [comment]
Fair enough. Thank you!
