### ISSUE TITLE
`close-out-of-view-modals` Breaks the new watch settings

### ISSUE THREAD

**Issue by maximousblk** [sindresorhus/refined-github#3742]
>  Make sure the bug is caused by Refined GitHub. Try disabling the extension first.

It is caused by Refined GitHub and disabling the extension fixes the issue.

> Include a full URL where the bug appears.

On any repository

> Include a screenshot/gif

![ezgif com-gif-maker](https://user-images.githubusercontent.com/28438021/99793406-a9bb4d00-2b4e-11eb-9ad7-be850c8660bf.gif)

**Comment by dnknn** [comment]
See →_→ https://github.blog/changelog/2020-11-20-custom-notification-controls/


<details>
<summary>Details</summary>

![image](https://i2.wp.com/user-images.githubusercontent.com/158833/99257818-83747500-280f-11eb-9619-65fe7a983458.gif?ssl=1)


</details>

**Comment by maximousblk** [comment]
@dnknn yes I read the changelog post.

It does it not work for me. When i click the "custom" option, the popup just disappears. But when i disable the extension, it works fine.

**Comment by dnknn** [comment]
As you said, this is an incompatible Bug of `refined-github` extension, I think it should be prioritized to fix this problem, and the release of this fix will be pushed soon.

**Comment by yakov116** [comment]
I will look into the issue shortly and take care of it. 
Thanks for the report

**Comment by yakov116** [comment]
Its `hide-watch-and-fork-count` I am going to disable the feature until we get it resolved. There is no need to update the extension, we can disable it globally (for all users).

**Comment by yakov116** [comment]
See https://github.com/sindresorhus/refined-github/tree/hotfix
https://github.com/sindresorhus/refined-github/commit/9c263eb04534598598f7dd27b20c00d02cb6cc61

**Comment by fregante** [comment]
I'm glad that the `hotfix` feature became useful. Let's always use it as soon as something like this happens since fixing always takes longer.

**Comment by yakov116** [comment]
I was actually excited to use it for the first time :sunglasses:
