### ISSUE TITLE
Broken links in repository tabs dropdown when viewing an action log

### ISSUE THREAD

**Issue by lbguilherme** [sindresorhus/refined-github#3743]
When opening some Action's logs to links added to the main dropdown seems to fail to recognize the repository path. It seems to only happen on this specific page. For example: https://github.com/sindresorhus/refined-github/runs/1428929640?check_suite_focus=true

![image](https://user-images.githubusercontent.com/546954/99796450-45779980-2b0c-11eb-8089-381205c05f00.png)

**Comment by fregante** [comment]
Thanks for the report, it needs to be fixed in https://github.com/fregante/github-url-detection/issues/53
