### ISSUE TITLE
Render :emoji: codes where not natively supported

### ISSUE THREAD

**Issue by KaKi87** [sindresorhus/refined-github#3744]
GitHub displays emoji codes (e.g. : `:bug:`) as emoji icons (e.g. : :bug:), *almost* everywhere :
- [repository description](https://github.com/KaKi87/emoji-codes-test)
- [commit message](https://github.com/KaKi87/emoji-codes-test/commits/main)
- [commit comment](https://github.com/KaKi87/emoji-codes-test/commit/d1353f29c045919e694c3374e369fc88b5b042ee#commitcomment-44383995)
- [issue/PR message & comment](https://github.com/KaKi87/emoji-codes-test/issues/1)

But not in :
- [issue/PR title](https://github.com/KaKi87/emoji-codes-test/issues)
- [action title](https://github.com/KaKi87/emoji-codes-test/actions)

The list is probably incomplete, but you get the idea.

Would Refined GitHub be suitable to fix it ?

This is mostly interesting when using the [gitmoji](/carloscuesta/gitmoji) project.

Thanks !

**Comment by fregante** [comment]
Thanks for the detailed request.

I'm not sure it's worth supporting emoji codes when one could just use the real emojis, but… I don't feel strongly about it.

**Comment by KaKi87** [comment]
Well, some git software and terminal emulators doesn't support or badly displays emojis, either because of encoding issues, or because of font issues, that's why I (and some gitmoji users) use emoji codes instead, which, for instance, are fully supported in Gitea (a self-hosted alternative to GitHub, like GitLab but 100% FLOSS).

Thanks

**Comment by KaKi87** [comment]
Is there something I can do to make it happen ? Thanks.

**Comment by fregante** [comment]
There’s a feature called “format-discussion-titles” I think which you can extend with this. As for GitHub Actions, I’m afraid that it might slow down the page when the log is long.

**Comment by KaKi87** [comment]
Oh, I really wanted to try doing it, but I just discovered you're using TypeScript and I really hate that thing, I'm truly sorry :cry:

**Comment by yakov116** [comment]
https://github.blog/changelog/2021-02-11-additional-emoji-support/

**Comment by fregante** [comment]
@yakov116 I noticed, but the 2 example links are unchanged.

**Comment by fregante** [comment]
Emojis are the future. Not worth supporting the past here, sorry.

**Comment by KaKi87** [comment]
There are interfaces that renders unicode emojis badly especially in terminal emulators and native apps, that's why emoji codes are preferred.

**Comment by fregante** [comment]
I know, those should be fixed instead.

**Comment by KaKi87** [comment]
Agreed, but it's much more work than making GitHub render emoji codes. Additionally, emoji codes features cross-platform autocompletion, while autocompleting unicode emojis usually require specific software on each operating system.
