### ISSUE TITLE
Drop `recently-pushed-branches-enhancements`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3748]
I'm tired of having to rewrite this every few months because of class changes. Maybe we should just drop it.

<img width="793" alt="99847230-5db3dc80-2b3d-11eb-9e57-09147b77ef63" src="https://user-images.githubusercontent.com/1402241/99847495-cac77200-2b3d-11eb-8ee3-7fb54caa72aa.png">
<img width="580" alt="Screen Shot 2020-11-20 at 14 35 32" src="https://user-images.githubusercontent.com/1402241/99847496-cbf89f00-2b3d-11eb-98dc-2ced3b85b8ef.png">

Feature also temporarily disabled in https://github.com/sindresorhus/refined-github/commit/c8a50197b2695b7f4bf5c96d87dd5211a5d9c7a6

**Comment by jshah** [comment]
I'm seeing the same issue from my end.

**Comment by busches** [comment]
Enterprise only feature? It's super stable there. 🤣
