### ISSUE TITLE
'Restore file' for submodule

### ISSUE THREAD

**Issue by elbaro** [sindresorhus/refined-github#3751]
'Restore file' button in PR pages are very useful. Can this be added for submodule updates as well? ('Restore submodule')

**Comment by fregante** [comment]
Can you provide a link to such PR like the issue template requests? I've never seen this before and I doubt it will be possible since we make the change via GitHub.com instead of the API.

**Comment by elbaro** [comment]
It's a private repo. I cannot find a way to update submodules in the web ui too.

**Comment by fregante** [comment]
I can't determine whether this can/should be done without seeing it. I'll have to close it until someone finds an example PR and posts it here. ✌️
