### ISSUE TITLE
Verify token in options

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3752]
When the user pastes a token, we could verify that the token:

1. Is active/valid
2. Has the expected scope(s)

#3734 will add a function that helps with this validation.

**Comment by yakov116** [comment]
Did a drop of testing here it does not give back all scopes. For example discussion is not passed back.

**Comment by fregante** [comment]
We don't need `discussion` and currently we only soft-require `repo` and `delete_repo`, both of which are reported.

We could take the opportunity to better explain why the token is needed:

<img width="457" alt="" src="https://user-images.githubusercontent.com/1402241/99917499-56740680-2cd6-11eb-83ed-dff7c572bb21.png">

```
- The token enables some features to read data from public repositories
- The `public_repo` scope lets them edit your public repositories
- The `repo` scope lets them edit private repositories as well
- The `delete_repo` scope is only used by the `quick-fork-deletion` feature
```

And then add something like `✅ Valid` or `❌ Not set/invalid` next to each that is updated with the validation.

**Comment by yakov116** [comment]
From my testing we cannot see if they have public and/or private repo enabled it just returns `repo`

**Comment by fregante** [comment]
![maxresdefault](https://user-images.githubusercontent.com/1402241/100186906-8c6ae380-2eac-11eb-88d4-84bf15b78dca.jpg)


`public_repo` means that they only have access to public repositories. 

`repo` means access to all repositories; this includes `public_repo`

It's in the notes I added in #3757 

Try creating a token with just `public_repo` and it will show up.

**Comment by yakov116** [comment]
I will try again tomorrow.
I need help understanding how to reset on domain change.

**Comment by yakov116** [comment]
I just tested and confirmed. It only gives you back what you selected when you created the token. Which means that if you made any changes, the header **does not** update! It will update if you regenerate the token.

So if a users adds a permission there will be no way for us to update it

**Comment by yakov116** [comment]
@fregante can you confirm too?

**Comment by fregante** [comment]
That's not right either. You can see the same token changing scopes here, seconds after changing them:

```
❯ http HEAD https://api.github.com/ "Authorization: token b77a804af914872e62b8c84d009f37f509cf2b58"
HTTP/1.1 200 OK
X-OAuth-Scopes: public_repo

❯ http HEAD https://api.github.com/ "Authorization: token b77a804af914872e62b8c84d009f37f509cf2b58"
HTTP/1.1 200 OK
X-OAuth-Scopes: repo

❯ http HEAD https://api.github.com/ "Authorization: token b77a804af914872e62b8c84d009f37f509cf2b58"
HTTP/1.1 200 OK
X-OAuth-Scopes: delete_repo, public_repo
```

**Comment by fregante** [comment]
I think you're confusing "token regeneration" with "token update." The regeneration creates a new token, but that's not what you're supposed to do:

![nook](https://user-images.githubusercontent.com/1402241/100392544-84ba5480-2ffc-11eb-89b3-58a73e8290e5.gif)

**Comment by yakov116** [comment]
I did both. I will make a screencast. Maybe something was wrong with Github yesterday.

**Comment by fregante** [comment]
Keep in mind that `api.v3` is memoized. Use `fetch` directly instead

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/09323918b5a3031fcb525a98474df0025d5a9f66/source/options.tsx#L14-L24

I will try it again in an hour

**Comment by fregante** [comment]
It's a cache problem, not an API problem

<img width="1002" alt="Screen Shot 2020-11-26 at 17 37 11" src="https://user-images.githubusercontent.com/1402241/100397207-12eb0680-300e-11eb-9248-d0108a1e0f9a.png">


Use `cache: 'no-store'`

```js
const {headers} = await fetch('https://api.github.com/', { 
	cache: 'no-store',
 	headers: {...}
});
```

**Comment by yakov116** [comment]
THANKS! How did you know I just started wording on it!
