### ISSUE TITLE
Shortcut compare & pull request header interface broken

### ISSUE THREAD

**Issue by tcelestino** [sindresorhus/refined-github#3763]
Using Firefox 83 on Ubuntu 18.04, shortcut `compare & pull request` in the header is broken.

![Screenshot from 2020-11-23 18-42-35](https://user-images.githubusercontent.com/190265/100100779-192b8800-2e40-11eb-8b5d-76d1a578b65a.png)

**Comment by yakov116** [comment]
@tcelestino what version of the extension are you on?? This was disabled globally.

**Comment by fregante** [comment]
Duplicate of #3748

**Comment by tcelestino** [comment]
@fregante after update this issue is done. 

@yakov116 sorry man, this week I worked a lot 😄  

thanks guys!!
