### ISSUE TITLE
Toggle/Hide TimelineItem elements (e.g. added label etc)

### ISSUE THREAD

**Issue by ElijahLynn** [sindresorhus/refined-github#3764]
I have searched the issues and installed the extension but don't see functionality for hiding `TimelineItem`s. 

My request is to be able to hide/toggle all Timelineitems from an issue or pull request view/page. 

![image](https://user-images.githubusercontent.com/1504756/100150342-4e41d580-2e54-11eb-8af6-192b090c35c5.png)

GitLab has this built-in and I think GitHub should too, but next best thing would be for Refined GitHub to have this feature:
![image](https://user-images.githubusercontent.com/1504756/100150459-80ebce00-2e54-11eb-9535-84950a9cb833.png)

**Comment by fregante** [comment]
This would be an alternative solution to https://github.com/sindresorhus/refined-github/issues/615, but it doesn't feel like an action I would need to take often, if ever. Why do you need/want to hide events?

**Comment by ElijahLynn** [comment]
> This would be an alternative solution to #615, but it doesn't feel like an action I would need to take often, if ever. Why do you need/want to hide events?

Thanks for the reply. I routinely have issues that have like 20 timeline events and it is really noisy. My use case is nearly every day I would want it on, and I would want it defaulted to my last selection, which will most of the time be turned off. And only if I need an important bit of info will I toggle it on temporarily. Here is a sample issue where it gets out of control: 

![image](https://user-images.githubusercontent.com/1504756/100160350-425e0f80-2e64-11eb-822a-802cf895e6a8.png)


source: https://github.com/department-of-veterans-affairs/va.gov-cms/issues/910

**Comment by ElijahLynn** [comment]
Interesting to note that _some_ of the timeline events are only shown with the ZenHub extension enabled, which I just disabled and took this same screenshot:
![image](https://user-images.githubusercontent.com/1504756/100160590-bbf5fd80-2e64-11eb-9167-fd989032d637.png)

**Comment by fregante** [comment]
Maybe #3847

**Comment by ElijahLynn** [comment]
> Maybe #3847

Looks hopeful, subscribed, thanks!
