### ISSUE TITLE
`unfinished-comments` doesn't work after toggling Preview comment tab.

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#3765]
`unfinished-comments` doesn't work after toggling Preview comment tab.
Screenshot: 
![unfinished](https://user-images.githubusercontent.com/49396421/100323787-378cb180-3001-11eb-9c27-4b4499cef1fd.gif)

**Comment by fregante** [comment]
This is due to:

https://github.com/sindresorhus/refined-github/blob/ccdcb93a1763ad4397de9010f37c2a5fa2ca7f81/source/features/unfinished-comments.tsx#L12
