### ISSUE TITLE
Issue with "Easier copy-pasting from diffs by making +/- signs unselectable"

### ISSUE THREAD

**Issue by karanrajpal14** [sindresorhus/refined-github#377]
It doesn't seem to be working all the time with all the pages. Sometimes I see both the "unselectable +" and the "selectable +". I haven't found a pattern to reproduce the issue but, I can link you to a page in which I was facing the same issue. Here's a link to it, and a screenshot as well. If you need anything else, let me know.

[Issue](https://github.com/DmitryMalkovich/stock-hawk-app/commit/13709ac740fe82fb5d607f90c78cd490f5686093)

[Screenshot](https://www.dropbox.com/s/qjhvrxpb7763eff/Screenshot%20%2817%29.png?dl=0)

**Comment by jgierer12** [comment]
Seems to be an issue with lazy loaded diffs since all of them are broken after a certain point

**Comment by karanrajpal14** [comment]
@jgierer12 Any way to prevent it from happening?

**Comment by jgierer12** [comment]
Not right now 🙁

It also happens when you switch between raw and rendered Markdown: 
![Switching between raw and rendered Markdown](https://cloud.githubusercontent.com/assets/4331946/25352433/4ce9eeba-292c-11e7-83e6-9d598015d6d0.gif)
