### ISSUE TITLE
Drop `cycle-lists-with-keyboard-shortcuts` 

### ISSUE THREAD

**Issue by MrChocolatine** [sindresorhus/refined-github#3776]
It appears the feature `cycle-lists-with-keyboard-shortcuts` became useless.

From its description:
> Allows the ↑ and ↓ keys to cycle "popover lists" (labels, milestones, etc).

But when I disable this feature or when I disable the extension, I can still navigate through labels/milestones etc on the page of an Issue, a PR, etc.

I guess you can delete it from your extension? Or do you usually simply deactivate a feature in the situation?

**Comment by fregante** [comment]
That appears to be correct! It works on every dropdown I tested
