### ISSUE TITLE
Feature Request - Ability to sort repository lists on Dashboard

### ISSUE THREAD

**Issue by stramel** [sindresorhus/refined-github#378]
It would be nice if we could sort these lists A-Z. 

Also, another nice thing would be to have the option to prioritize the non-fork repositories in the list.

Image for reference:

![image](https://cloud.githubusercontent.com/assets/855184/25135879/2c4c8702-2419-11e7-8b17-09c4906b1acb.png)

**Comment by jgierer12** [comment]
Regarding the non-fork repos, you get those when you click the 'Sources' tab

**Comment by sindresorhus** [comment]
👎 I don't really see the usefulness of A-Z sorting. Just use the search if you're looking for something specific. That list is mostly useful to quickly go to recently active repos.

> Also, another nice thing would be to have the option to prioritize the non-fork repositories in the list.

Click "Sources".
