### ISSUE TITLE
Add option to revert aligning of repo header to content

### ISSUE THREAD

**Issue by mimecry** [sindresorhus/refined-github#3785]
Hi, it seems that the setting to align the repo header to content on widescreen monitors is hardcoded, and overrides any other extension's attempt to move the header. I tried adding the following CSS to Refined Github but it didn't seem to have any effect 

`body:not(.full-width):not(.enterprise) main > .hide-full-screen > * {
	padding-left: 0px !important;
}`

Is it possible to expose this option in the UI, so that addons like Wide Github can be used in conjunction with it?

What the two addons currently look like together

![image](https://user-images.githubusercontent.com/10742312/100890862-47b5fc80-34eb-11eb-894d-891581df7d8d.png)

What they should look like 

![image](https://user-images.githubusercontent.com/10742312/100891186-982d5a00-34eb-11eb-9ee9-3e86004932c7.png)

**Comment by fregante** [comment]
It feels like `wide-github` could implement an override for us since their intent is clear and sole. Our CSS is at: https://github.com/sindresorhus/refined-github/blob/master/source/features/align-repository-header.css

If you want to override it yourself, you'll have to make the selector a little stronger, like:

```css
:root body:not(.full-width):not(.enterprise) main > .hide-full-screen > * {
	padding-left: calc(50% - 1280px / 2) !important;
}
```

**Comment by mimecry** [comment]
right, i forgot to apply !important.. the css works now, thank you. i'll raise the issue with the wide-github dev and see what he thinks

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
