### ISSUE TITLE
Reinstate `friendlier-requested-changes` feature

### ISSUE THREAD

**Issue by TehShrike** [sindresorhus/refined-github#3786]
`friendlier-requested-changes` was dropped in #2860 – I was a big fan of the gray text, personally.  The red text looks so angry, it keeps me from using the "request changes" feature at all.

How do y'all feel about reinstating the feature, but perhaps defaulting it to off if people are still not universally sold on it?

**Comment by fregante** [comment]
Changing it to orange would also lower the contrast. Maybe GitHub can do it, but we tried it already and it was not particularly better nor well accepted. 

I know it won't change it for anyone else, but you can implement it in your CSS
