### ISSUE TITLE
Timeline year list layout issue when switching tabs

### ISSUE THREAD

**Issue by dnicolson** [sindresorhus/refined-github#3789]
When switching from the Repositories tab to the Overview tab the timeline year list overlaps with the graph. Reloading the page resolves the issue.

1. Go to a GitHub profile
2. Click Repositories
3. Click Overview
4. Scroll down

![Screen Recording 2020-12-04 at 00 56 04 480p](https://user-images.githubusercontent.com/2276355/101190501-bd8ba680-3658-11eb-9a9b-1bfeb2759f12.gif)

Refined GitHub 20.12.3, Chrome 87.0.4280.88 and 89.0.4345.0 on macOS.

**Comment by yakov116** [comment]
unable to reproduce on windows

**Comment by dnicolson** [comment]
@yakov116 what versions are you using? I just downloaded a Windows 7 image and Chrome 87.0.4280.88.

![Windows 480p](https://user-images.githubusercontent.com/2276355/101210346-9bece800-3675-11eb-8536-bc8822b7c5af.gif)

**Comment by yakov116** [comment]
Does it happen without RGH?

**Comment by dnicolson** [comment]
No, I'm reasonably sure it's a Refined GitHub issue.

**Comment by yakov116** [comment]
I see it now. Github must be rolling something out now.

**Comment by fregante** [comment]
It’s possible that this is conflicting with the new sticky sidebar feature?

**Comment by fregante** [comment]
Can't replicate on Chrome/macOS. I'm guessing they fixed the underlying issue. Comment/reopen if you still experience it

**Comment by dnicolson** [comment]
The issue still exists.

**Comment by fregante** [comment]
Found the culprit: `stop-pjax-loading-with-esc`
