### ISSUE TITLE
`pr-easy-toggle-files` improvements

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#3793]
Three suggestions for the `pr-easy-toggle-files` feature:

1. Enable <kbd>alt</kbd>-clicking to toggle all files. This already works when clicking directly on the arrow, but not on the whole file header bar. Test URL: Any PR's files tab.
2. Enable the feature on *Unchanged files with check annotations* that are shown in the files tab below the files that actually changed. Test URL: https://github.com/OpenLightingProject/open-fixture-library/pull/1619/files?file-filters%5B%5D=
3. Enable the feature in compare view. Test URL: https://github.com/typicode/husky/compare/v4.3.0...v4.3.5

**Comment by FloEdelmann** [comment]
@cheap-glitch I added a third item to my wishlist :wink:

Would you mind integrating this into your PR as well?

**Comment by cheap-glitch** [comment]
> Would you mind integrating this into your PR as well?

Done!
