### ISSUE TITLE
GitHub dark mode support

### ISSUE THREAD

**Issue by Dev-CasperTheGhost** [sindresorhus/refined-github#3799]
GitHub just released darkmode, and it would be nice to have support for it with this extension (dashboard page)!

## URL
https://github.com/dashboard

## Screenshots

<details>
  <summary> extension disabled </summary>

![image](https://user-images.githubusercontent.com/53900565/101520353-a87a8480-3984-11eb-90c2-d1631952e7fe.png)

</details>

<details>
  <summary> Extension enabled</summary>

![image](https://user-images.githubusercontent.com/53900565/101520307-97317800-3984-11eb-8296-acc815f0bc73.png) 

</details>

**Comment by pqt** [comment]
You _just_ missed being the first by a couple minutes or so #3798 !

**Comment by Dev-CasperTheGhost** [comment]
oh yea, haha! I'll close this issue to avoid confusion.

**Comment by yakov116** [comment]
Duplicate of #3798
