### ISSUE TITLE
Link issues in code comments

### ISSUE THREAD

**Issue by Loilo** [sindresorhus/refined-github#380]
I've seen that in several bigger projects, so if I'm not mistaken it's a common practice to clarify non-intuitive code sections that fix a certain behaviour with an issue ID, like "see #123".

See [here](https://github.com/contao/core/blob/549738f9a41974d963bd09a3a83ae0f46f887f01/system/modules/core/pages/PageForward.php#L51) for an example.

It would be nice to have those in-comment mentions—`/#[0-9]+/` in RegExp terms—linked to the according issues.

**Comment by sindresorhus** [comment]
Big :+1:

URLs in comments too.

**Comment by paulmolluzzo** [comment]
🎉

**Comment by Loilo** [comment]
Wow. That was fast. 👍

**Comment by paulmolluzzo** [comment]
Whoops. Fat fingers. 😅
