### ISSUE TITLE
Missing "New" button in the left side menu on the Home page

### ISSUE THREAD

**Issue by kubukoz** [sindresorhus/refined-github#3800]
It's visible without refined-github, but gone after enabling the extension - I'm not sure if this is deliberate.

No plugin:

![image](https://user-images.githubusercontent.com/894884/101520791-42dac800-3985-11eb-8b6e-0519c62e96b4.png)

Yes plugin:

![image](https://user-images.githubusercontent.com/894884/101520821-4bcb9980-3985-11eb-9ea8-eba0689f91dd.png)

**Comment by fregante** [comment]
Yes this is deliberate to clean up the interface. There’s a button in the top right next to the notification button

**Comment by kubukoz** [comment]
Ah, true. Thanks for the clarification :)
