### ISSUE TITLE
Toggle for Github Theme

### ISSUE THREAD

**Issue by aliglelo** [sindresorhus/refined-github#3802]
Since github is supporting theme natively now, Could you please add a toggle on home screen for toggling the theme right away from the Homepage of github instead of sifting through appearance settings?

**Comment by sindresorhus** [comment]
Why?

**Comment by aliglelo** [comment]
> Why?

Why? :disappointed: 
Because it will be easier for changing theme on website according to your time...as most people switch to dark-mode during night time to get rid of eye strain,and use light mode during day time

**Comment by connor-baer** [comment]
One way of achieving this is on macOS is to configure the GitHub theme to follow the system settings:

<img width="769" alt="Screen Shot 2020-12-09 at 10 29 55" src="https://user-images.githubusercontent.com/11017722/101611392-ba523b00-3a09-11eb-8fa1-8e1608b9bfa7.png">

And also configure your macOS appearance to switch automatically depending on the time of day:

<img width="358" alt="Screen Shot 2020-12-09 at 10 31 17" src="https://user-images.githubusercontent.com/11017722/101611465-d6ee7300-3a09-11eb-8cc6-051e4b68455e.png">

As an added bonus, you can use [NightOwl](https://nightowl.kramser.xyz/) to switch the appearance from your menu bar and customize it per app.

**Comment by kidonng** [comment]
You can use the "auto" option.

That said, I see this feature is useful and easy to implement. Will spin up a script (and possibly a PR) later.

**Comment by kidonng** [comment]
![image](https://user-images.githubusercontent.com/44045911/101623046-d29a7800-3a52-11eb-804f-f9982f0a3716.png)

**Comment by sindresorhus** [comment]
> Because it will be easier for changing theme on website according to your time...as most people switch to dark-mode during night time to get rid of eye strain,and use light mode during day time

As mentioned, you can already do this by making it follow your system. I don't really see the point in having a different theme on GitHub than your system.

**Comment by fregante** [comment]
Both macOS and Windows have a system dark mode. Having to switch every website when the sun goes down sounds like extra unnecessary work. 

Set “auto” and use your system’s dark mode to change everything at once.

**Comment by kidonng** [comment]
But there are Linux users too. And this is also useful for developers who need to test both light and dark themes for their GitHub related applications (such as me right now 😄).

As this feature doesn't likely go into Refined GitHub, here is a [user script](https://github.com/kidonng/cherry/tree/master/scripts#github-theme-switch) based on my PR.

**Comment by cheap-glitch** [comment]
> But there are Linux users too.

It's a bit hackish, but you can have a "global" dark mode switch in Linux too, at least for GTK-based applications like Firefox. Not sure about Chrome/Chromium.

I agree this belongs more in a separate user script.

**Comment by fregante** [comment]
> But there are Linux users too 

It’s Linux. They can do everything they set their mind to. 

> And this is also useful for developers who need to test both light and dark themes for their GitHub related applications (such as me right now 😄).

I do it too, globally. There’s no point in adding a switch to every website. You can probably have a global shortcut on every OS that changes the color everywhere in an instant.

**Comment by fregante** [comment]
If it’s something you need to do frequently, I suggest a bookmarklet that toggles the color in one click by fetching the form and resubmitting it.

**Comment by sindresorhus** [comment]
> And this is also useful for developers who need to test both light and dark themes for their GitHub related applications

This is a very niche use-case though.

**Comment by sindresorhus** [comment]
By the way, if you go to your GitHub profile, there's a toggle in the top-right corner.

**Comment by kidonng** [comment]
As it stands, this is included in [Command palette](https://github.blog/changelog/2021-10-27-command-palette-beta/):

<img width="730" alt="截屏2021-11-12 01 07 48" src="https://user-images.githubusercontent.com/44045911/141339469-6c2448c1-fb60-40c7-acee-5b41e33b1fef.png">
