### ISSUE TITLE
Copy file path of reviewed file in the PR Conversation tab

### ISSUE THREAD

**Issue by cihati** [sindresorhus/refined-github#3803]
I searched through the old issues, and couldn't find any so here I am.

In https://github.com/<my_org/<my_repo>/pull/<pr_number> link (which corresponds to the "Conversations" tab), you see code review blocks like the following:

![image](https://user-images.githubusercontent.com/461998/101615216-ef1cbd00-3a1e-11eb-8e2e-0c8263832d71.png)

I think they should have the copy button/icon like in "Files changed" tab:
![image](https://user-images.githubusercontent.com/461998/101615325-0a87c800-3a1f-11eb-9c2c-924696ec3d1f.png)

**Comment by fregante** [comment]
I’m not sure which part of a review block you want to copy. The reviewed code? The filename? Any code inside the review comment itself?

**Comment by cihati** [comment]
@fregante The filename (that's what the button in the screenshot does it "Files changed" tab as well)

**Comment by yakov116** [comment]
Why can you not just highlight it and copy it? Don't see the need for another thing on that line. (We already have `highlight-deleted-and-added-files-in-diffs`)

**Comment by cihati** [comment]
@yakov116 yes, I can do that, like most things refined-github provides, it'd be more convenient not having to do that (and consistent with other copy buttons).

**Comment by fregante** [comment]
You can see the same review on the Files tab, which has the buttons already
