### ISSUE TITLE
Base branch missing from PR view

### ISSUE THREAD

**Issue by matschaffer** [sindresorhus/refined-github#3808]
Version: 20.12.9

Perhaps the is a feature, but I was pretty sure the merge destination used to show up. Now it doesn't. Or maybe doesn't when it's the main branch of the parent repo? 

Anyway, it confused a few of us this morning so thought it'd be good to open a bug.

https://github.com/Safecast/safecastapi/pull/743

With extension on:

![Screen_Shot_2020-12-10_at_0_15_34](https://user-images.githubusercontent.com/690/101704756-50737900-3a7d-11eb-8b13-055796eab9ab.png)

With extension off:

![Screen_Shot_2020-12-10_at_0_15_42](https://user-images.githubusercontent.com/690/101704778-5d906800-3a7d-11eb-8979-739e42f39cfd.png)

**Comment by busches** [comment]
Correct, it doesn't show when you're merging to the default branch.

**Comment by fregante** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/3089

**Comment by asmeurer** [comment]
Is there a way to disable this? I searched the options list and didn't find anything, but there are a lot of options, so I may have missed it.

**Comment by asmeurer** [comment]
Found it, it's "clean up conversation headers". I wouldn't mind the other changes so much, but hiding the default branch is confusing and isn't actually duplicated information.

**Comment by philonor** [comment]
@fregante You seem to mention issues where this behavior poses a problem/confusion within the original issue. I think this feature is fine except for hiding the base branch name. The base branch name is important when operating in different repositories with different base branches/git workflows. Maybe we could split this into two features:
1. clean up conversation headers
2. hide base branch name from pr headers

**Comment by fregante** [comment]
Since the default would still mean hiding both, from the extension’s point of view it’s easier to just hide them both at once. 

> The base branch name is important when operating in different repositories with different base branches/git workflows

Question: How do you use this piece of information?

**Comment by asmeurer** [comment]
Personally I just found that fact that "no branch means default branch" confusing. It's clearer to always show it. Another thing is that the default branch isn't necessarily obvious if you aren't familiar with the repo, especially given that many repos are now changing their default branch name from `master` to `main`. Finally, it's a symmetry break to hide the information in some cases. My eyes look to a particular part of the screen to find the branch information, and when it's not there, it makes it harder to figure out what is going on (I have to stop and carefully reread what everything says).

**Comment by yakov116** [comment]
> My eyes look to a particular part of the screen to find the branch information, and when it's not there, it makes it harder to figure out what is going on (I have to stop and carefully reread what everything says).

Took me some time to get used to this too.

**Comment by fregante** [comment]
PR welcome to restore it
