### ISSUE TITLE
Show entire conversation by default

### ISSUE THREAD

**Issue by hyperfekt** [sindresorhus/refined-github#3814]
For very long conversations, GitHub hides everything but the beginning and end by default. Not only is it very annoying to keep expanding new items to read through a conversation, it also makes it very easy to miss comments when using the browser's search function.
Refined GitHub should automatically display all items in a conversation.

An example of the problem can be found [here](https://github.com/isaacs/github/issues/50#:~:text=hidden%20items) (search for 'hidden items').

**Comment by yakov116** [comment]
You can press ALT and click on unhide and it will unhide 200 items

**Comment by hyperfekt** [comment]
For me it's only 60?

**Comment by fregante** [comment]
Showing long discussions is relatively heavy and more often than not I’m not interested in “middle” messages in conversations with hundreds of comments. If I am, I’ll expand the discussion. 

As Yakov mentioned, we have a feature that expands the entire conversation on alt-click, but it’s possible that it’s not working at the moment.

**Comment by hyperfekt** [comment]
Hm, I presume there isn't space for disabled-by-default features in this extension, given that the preference for our against this is variable. In that case a userscript is probably more appropriate.
