### ISSUE TITLE
Hide "Explore repositories" sidebar as part of `clean-dashboard`

### ISSUE THREAD

**Issue by cheap-glitch** [sindresorhus/refined-github#3818]
Concerned URL: https://github.com (the dashboard)

I find the "Explore repositories" section on the dashboard very distracting, and mostly useless since there's already an "Explore" link in the header of every page. Plus it takes quite a bit of horizontal space away from the "Recent activity" section which is arguably the most useful part of the dashboard.

I think this section could be hidden as part of the `clean-dashboard` feature (which #3817 makes possible to disable).

**Comment by yakov116** [comment]
I happen to like it. I actually used something it suggested recently.

I am not saying no, just stating my opinion. I am also bias here since a have a 27" screen so there is plenty of room there.

**Comment by cheap-glitch** [comment]
> I happen to like it. I actually used something it suggested recently.

Just to be perfectly clear, I'm not saying the "Explore" feature is useless (I have benefited from it too), but that having it on the dashboard is. Then again, maybe it's me that's just too easily distracted :smile:

**Comment by yakov116** [comment]
But we can't hide the pop-up message box, that has info the the user should see. Therefore what will it help just hiding the explore part. You will still have the sidebar.

**Comment by cheap-glitch** [comment]
> You will still have the sidebar.

Yes, I'm talking about hiding this sidebar:
![image](https://user-images.githubusercontent.com/46634000/102015277-dbdd5a80-3d5a-11eb-8d4d-15a036b173ce.png)

**Comment by yakov116** [comment]
Above that sidebar GitHub displays messages

**Comment by cheap-glitch** [comment]
> Above that sidebar GitHub displays messages

Oh you mean like product announcements and such? I didn't think about those. But it's probably still feasible to hide the suggestions without hiding the whole sidebar element.

**Comment by FloEdelmann** [comment]
@cheap-glitch If it bothers you so much, you can apply the following CSS in Refined GitHub's *Custom CSS* option:

```css
aside[aria-label="Explore"] > :not(:first-child) {
	/* The first child is an empty div that likely displays GitHub's announcements */
	display: none !important;
}
```

I'd also vote against including this in Refined GitHub natively, as it just creates more empty space without use, and I like the suggestions there. I rarely ever visit the "Explore" page explicitly.

**Comment by cheap-glitch** [comment]
Thanks for the suggestion, this is good enough for now! Closing this since everybody who commented seems against it.
