### ISSUE TITLE
Installing extension set up process

### ISSUE THREAD

**Issue by CubeOfCheese** [sindresorhus/refined-github#3820]
When the extension is first installed, it opens this page automatically.
https://github.com/sindresorhus/refined-github/issues/3543

Can someone edit that issue to link to this documentation on how to create a personal access token?
https://docs.github.com/en/free-pro-team@latest/github/authenticating-to-github/creating-a-personal-access-token
Instead of just being bolded, it should be a link to that doc page
`Make sure you create and add a **Personal Access Token** in the extension’s options to ensure every feature works correctly.`

**Comment by yakov116** [comment]
Updated the issue to a link that directs you to the create token page.

**Comment by CubeOfCheese** [comment]
Wow that's even better! Thanks

**Comment by fregante** [comment]
Bad idea:

1. The user already has to open the options page, where the link already exists
2. The link might change over time and I don’t want that issue to become stale

Due to point 1, I don’t think any changes are necessary.
