### ISSUE TITLE
Git Blame page broken by extension

### ISSUE THREAD

**Issue by rbclark** [sindresorhus/refined-github#3821]
I noticed that when clicking on the Blame button in Github, it seems to not be rendering properly when this extension is installed:

With extension:
<img width="1899" alt="Screen Shot 2020-12-14 at 9 42 20 AM" src="https://user-images.githubusercontent.com/2308869/102094737-aaaf6980-3df0-11eb-883f-08fd54a9046b.png">

Without extension:
<img width="1215" alt="Screen Shot 2020-12-14 at 9 42 59 AM" src="https://user-images.githubusercontent.com/2308869/102094813-c1ee5700-3df0-11eb-98a1-71bd9d8aef34.png">

Link to page: https://github.com/mitre/heimdall_tools/blame/2bfa20705491867e04eae78d762a0aae241418c3/heimdall_tools.gemspec

I am using the extension with Firefox specifically.

**Comment by fregante** [comment]
Can't replicate on Firefox. This doesn't look like a bug that the extension can cause. It's more likely to be a GitHub bug that was already resolved

**Comment by rbclark** [comment]
Yep, I'm now seeing it in incognito as well so it seems you are correct. Sorry about that.

**Comment by fregante** [comment]
No worries, thanks for reporting it
