### ISSUE TITLE
0 results on "The token enables [some features]" link in Firefox add-on preferences

### ISSUE THREAD

**Issue by anko** [sindresorhus/refined-github#3825]
This link points to a search with 0 results:

![out](https://user-images.githubusercontent.com/5231746/102269343-c9128380-3f1c-11eb-868b-4e5a95acc84a.gif)

- - -

 - Mozilla Firefox 83.0
 - Refined Github version 20.12.9

**Comment by yakov116** [comment]
Its working for me in chrome. Can you copy the link and paste it here?

**Comment by anko** [comment]
https://github.com/sindresorhus/refined-github/search?q=github-helpers/api

It's the same link.  It works in the sense that the page _exists_, it just contains no information relevant to what I thought the link was supposed to show me.  I think it's pointing at the wrong URL.

Based on the context where the link appears, I would have expected the link to bring me to a page with a list of features that would be enabled by adding a personal token, but it links to a seemingly unrelated search with 0 results.

**Comment by fregante** [comment]
That’s weird. I get 36 code results on that page

**Comment by anko** [comment]
I checked Chrome, and it indeed shows 36 results too.  Copied and pasted the same link into Firefox: 0 results. :dizzy:

Testing theories: 

 - __Maybe Firefox gets confused by `/` not being percent-escaped?__

   :x: https://github.com/sindresorhus/refined-github/search?q=github-helpers%2Fapi also shows 0 results.

 - __Maybe my profile or add-ons have some setting I don't know about that's causing this?__

   :heavy_check_mark:  This seems to be it.  If I start a Private Window in Firefox (so I'm not signed in to Github, and most add-ons are disabled), I also get 36 results.

I'll try disabling extensions one by one to narrow this down, then report back.

**Comment by anko** [comment]
If I am _logged in to Github_, I get 0 results for https://github.com/sindresorhus/refined-github/search?q=github-helpers/api in both Chrome and Firefox.  If I'm logged out, I see the 36 results I'm supposed to.  Disabling add-ons has no effect.

But why?

 - __Have I forgotten about some search-related Github setting that might affect this?__

   :x: I went through [the settings](https://github.com/settings). There's nothing relating to search.

 - __Dark mode bug?__

   :x: Same problem with dark or light appearance setting.

 - __Is the code search API behind a magic account-tied API key that my account has somehow managed to get rate-limited on?__

   :x: No.  I see code results when searching other repositories, for other search terms on this repo, and when searching globally.

 - __Am I for some reason blocked from this repo, or blocked by Sindre Sorhus so I see no results from his repos?__

   :x: No.  If I search for other keywords, I can find code results from this repo.

While trying random stuff, I noticed that I get the intended 36 results if I search this repository for _github-helpers api_ (the same search, but with a space instead of `/`); https://github.com/sindresorhus/refined-github/search?q=github-helpers+api&type=code

I also noticed that I get 0 code results even if I [search Github __globally__ for _github-helpers/api_](https://github.com/search?q=github-helpers%2Fapi), so one would think the `/` is universally bad, but every other search I've tried that has a `/` in it works fine. And slashes are _supposed to_ do nothing anyway, according to [Github documentation for code search](https://docs.github.com/en/free-pro-team@latest/github/searching-for-information-on-github/searching-code):

> You can't use the following wildcard characters as part of your search query: `. , : ; / \ `` ' " = * ! ? # $ & + ^ | ~ < > ( ) { } [ ]`. The search will simply ignore these symbols.

But for some reason, seemingly only on my account, and seemingly only for this specific search query, I get 0 results.  Except if I remove the slash that is supposed to do nothing; then it works.

![defenestrating a laptop](https://user-images.githubusercontent.com/5231746/102365262-a41f1e80-3fb7-11eb-826e-47ae9f20cabe.gif)


I must herefore conclude that my Github account is cursed.

- - -

Here's the whole mystery summarised in one screenshot:

![shot](https://user-images.githubusercontent.com/5231746/102363015-4e497700-3fb5-11eb-9644-6f5ae469b18e.png)

If allowing mysteriously cursed users to access documentation is a priority, then I would propose amending the problematic search link to contain a space instead of a slash.

The slash is supposedly a no-op, so replacing it with a space shouldn't affect non-cursed users.  (Someone non-cursed please confirm, by visiting https://github.com/sindresorhus/refined-github/search?q=github-helpers+api&type=code and observing 36 results?)

**Comment by fregante** [comment]
This is for you: https://youtube.com/watch?v=KXBI2_zH9Js

Could you report it to GitHub?

in the meantime, yes, we can replace it with a space. My non-cursed account reports 36 results either way

**Comment by anko** [comment]
@fregante Thanks for the fix and music. :smile: 

I emailed Github support about this, and [added a mention to Isaacs' unofficial issue tracker](https://github.com/isaacs/github/issues/908#issuecomment-747527153).
