### ISSUE TITLE
`sync-pr-commit-title` messing up PR title

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#3829]
I squashed and merged [this PR](https://github.com/OpenLightingProject/open-fixture-library/pull/1641) without changing the commit title. Afterwards, the PR title was messed up:

![grafik](https://user-images.githubusercontent.com/202916/102659013-fb202180-4178-11eb-9d5e-b0cf32fa0b8e.png)

The commit title is fine:

![grafik](https://user-images.githubusercontent.com/202916/102659047-0e32f180-4179-11eb-936e-d7db1efbf3d1.png)

Unfortunately, I cannot remember if the feature suggested the title change before merging.

**Comment by FloEdelmann** [comment]
It didn't happen for a similar PR: https://github.com/OpenLightingProject/open-fixture-library/pull/1642

**Comment by fregante** [comment]
The event happened 10 minutes after the merge, how is that possible? 🤔

<img width="822" alt="" src="https://user-images.githubusercontent.com/1402241/102660642-5a663d80-4149-11eb-90b3-c64fac3cce01.png">

**Comment by FloEdelmann** [comment]
It happened again: https://github.com/OpenLightingProject/open-fixture-library/pull/1645

Now I am sure that it didn't suggest (or rather warn in this case :sweat_smile:) to change the title before merging.

**Comment by FloEdelmann** [comment]
#### New insights :bulb:

It's caused by GitHub's new (beta) [auto-merge feature](https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/automatically-merging-a-pull-request):

When a PR can't be merged immediately due to failing tests or missing reviews, the `.is-squashing` element now contains two similar forms: One for overriding branch restrictions as an admin, and a new one to enable auto-merge once all restrictions are met.

In both, there is an commit message input with id `merge_title_field`.

The code in `sync-pr-commit-title` expects this input to exist only once and thus only operates on the first one, whether it is hidden (which was the case for aforementioned PRs) or not.
