### ISSUE TITLE
Move labels so things align nicely

### ISSUE THREAD

**Issue by steveoh** [sindresorhus/refined-github#383]
I do not think

![image](https://cloud.githubusercontent.com/assets/325813/25363124/9d03331e-2915-11e7-8d0b-cbc739e6893e.png)

looks as nice as

![image](https://cloud.githubusercontent.com/assets/325813/25363195/0a50bcde-2916-11e7-9eed-fb20753b531d.png)

Is that something this plugin would appreciate as well? I can work on adding it if you like the idea.

**Comment by hkdobrev** [comment]
Personally, I like the current layout more as the focus is on the title and you see that first. The labels to me are secondary.

**Comment by sindresorhus** [comment]
The latter looks a lot more messy in my opinion. The title is the important part and we should optimize for that, not the labels.
