### ISSUE TITLE
Expand but hide "1 similar comment" in `hide-useless-comments`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3830]
<img width="876" alt="" src="https://user-images.githubusercontent.com/1402241/102661213-67376100-414a-11eb-8828-df7c8e6fdbdf.png">

"Similar" comments are useless comments, so they should be hidden by `hide-useless-comments`.

The feature should run on these comments and, if they are indeed useless, the should be expanded ¹ and hidden.

---

¹ the user shouldn't have to click that comment to expand it again if they already clicked "show useless comments"

Test URL: https://github.com/justinfrankel/licecap/issues/97#issuecomment-737063337

**Comment by fregante** [comment]
Needs to be restored after https://github.com/sindresorhus/refined-github/pull/4013

**Comment by cheap-glitch** [comment]
It works for me on Firefox and Chromium with the latest RGH release, both similar comment boxes are expanded.

**Comment by fregante** [comment]
Interesting, it works in Chrome but not Safari. I just built `main` and still nothing

**Comment by cheap-glitch** [comment]
Unfortunately I can't test it in Safari, but maybe simplifying the selector as mentioned in https://github.com/sindresorhus/refined-github/pull/4013#discussion_r581093205 could fix this.

**Comment by fregante** [comment]
Fixed in 6d52cb1
