### ISSUE TITLE
Allow toggling autoscroll on Github Actions build output

### ISSUE THREAD

**Issue by weirdan** [sindresorhus/refined-github#3836]
Currently Github Actions always do automatic scroll to the bottom on any output. It's fairly annoying when you noticed potential issue in an earlier step and want to check it out while the build is still running.
It would be nice to have a control (with fixed position in regards to the viewport) that you could click to toggle the autoscroll on or off.

URLs: `https://github.com/{org}/{repo}/runs/{run id}` and `https://github.com/{org}/{repo}/pull/{pr id}/checks`

**Comment by fregante** [comment]
Preventing GitHub’s native scroll would be tough. I suggest asking GitHub to implement it as “autoscroll unless the user has scrolled up” behavior that all shells have.

**Comment by weirdan** [comment]
Already asked them, with no response so far.

**Comment by fregante** [comment]
I'll close this as it's impossible to reliably prevent scrolling (without flickering, hacks, possibly-annoying bugs)

**Comment by elecnix** [comment]
@weirdan Coming from Bitbucket Pipelines, the autoscroll behavior of GitHub Actions is... shocking. Did you end up getting a response from GitHub?

**Comment by weirdan** [comment]
@elecnix I don't think I did get any response. In fact, I can't even find where I reported it.
