### ISSUE TITLE
Link to the specific file for the PRs which touches given file

### ISSUE THREAD

**Issue by ThomsonTan** [sindresorhus/refined-github#3838]
"This file is affected by PRs" as below screenshot shows is very useful feature to search potential work conflict, a minor suggestion is linking to the specific requested file in the PR link instead of just link the the whole PR. This will be helpful for PRs with many files so manual search and file navigation could be saved.

https://user-images.githubusercontent.com/55841/60622834-879e1f00-9de1-11e9-9a9e-bae5ec0b3728.png

**Comment by fregante** [comment]
Good point, but I don’t think it’s possible since the file’s linkable IDs appear as hashes. We first need to find a way to link to a file by name (ideally without having to add extra code on the PR Files page)

**Comment by ThomsonTan** [comment]
Another thought is in the drop down list of PR number, could the PR title be put there in the drop down list, like `#111: PR title`? This could be give more visual indication on potential common work.

**Comment by fregante** [comment]
Closing as impossible. The last comment was discussed elsewhere and I think we ended up going for the tooltips when hovering the PR item
