### ISSUE TITLE
Graphical glitches when zoom IS 100% when viewing preferences in Firefox.

### ISSUE THREAD

**Issue by mwoolweaver** [sindresorhus/refined-github#3842]
|        |  Version    |
| :------------- | :----------: |
|  Firefox | 84.0.1 (64-bit)   |
| OS   | Linux Mint 20 | 

https://twitter.com/mdwoolweaver/status/1342177572076052493

Setting the Zoom to any other value makes these glitches stop.

**Comment by cheap-glitch** [comment]
I'm seeing this too on Firefox. The glitching stops when typing a few characters in the search box and making the list of issues smaller.

I'm not seeing this behavior with Chromium though, so there's a good chance it's a Firefox bug.

**Comment by mwoolweaver** [comment]
where shoudl i file this report so it gets the proper attention?

**Comment by fregante** [comment]
Let’s see what’s causing it exactly. Perhaps we can avoid it with some margin-bottom on body

**Comment by fregante** [comment]
This should now be fixed, but it won't appear until the dependency is updated here and then pushed to the store. It might be a couple of weeks

**Comment by mwoolweaver** [comment]
any eta on when 

> and then pushed to the store 

might happen?

**Comment by fregante** [comment]
It should already be there actually!

**Comment by jdreesen** [comment]
Works for me. Finally, the options page is usable (Firefox), thank you so much! :)
