### ISSUE TITLE
`comments-time-machine-links`: Cannot read property 'attributes' of null

### ISSUE THREAD

**Issue by ThomsonTan** [sindresorhus/refined-github#3845]
When opening some github PR page (it could reproduce for many PR links), below error shows up in the F12 console window. The top frame in below stack is listed as the last line in below code snippet.

❌ Refined GitHub → comments-time-machine-links → TypeError: Cannot read property 'attributes' of null
    at init (refined-github.js:5062)
    at runFeature (refined-github.js:2116)
    at setupPageLoad (refined-github.js:2124)
    at refined-github.js:2157 

```js
    }), source_features.add("comments-time-machine-links", {
      include: [ hasComments ],
      init: function() {
        const comments = select_dom.all('\n\t\t:not(.js-new-comment-form):not([id^="pullrequestreview"]) > .timeline-comment:not(.rgh-time-machine-links),\n\t\t.review-comment > .previewable-edit:not(.is-pending):not(.rgh-time-machine-links)\n\t');
        for (const comment of comments) {
          const timestamp = select_dom("relative-time", comment).attributes.datetime.value;
```

**Comment by fregante** [comment]
Thanks for the report! I believe this will be fixed by https://github.com/sindresorhus/refined-github/pull/3844
