### ISSUE TITLE
Teams Page missing when organization has no teams

### ISSUE THREAD

**Issue by stramel** [sindresorhus/refined-github#386]
With no teams and Refined-GitHub enabled:

![image](https://cloud.githubusercontent.com/assets/855184/25448869/8e9527e0-2a7f-11e7-8769-b8a99e0c1c4a.png)

With no teams and Refined-GitHub disabled:

![image](https://cloud.githubusercontent.com/assets/855184/25448888/a20fe5da-2a7f-11e7-8b3e-00a6b216f2d7.png)

Appears this line is the cause: https://github.com/sindresorhus/refined-github/blob/5a86c08fe6b6ed15eea74fceecdcd9602213a288/extension/content.css#L175

**Comment by sindresorhus** [comment]
Thanks for reporting. Fixed by https://github.com/sindresorhus/refined-github/commit/c879036c58e8131bf2f4d3f1bbe8651f77631704.

**Comment by stramel** [comment]
Wow, @sindresorhus is ⚡️ quick! 👏
