### ISSUE TITLE
Enhance `quick-repo-deletion` with a fallback method

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#3860]
I am trying to remove my dummy fork of https://github.com/stdedos/shellcheck, and I saw the button there; which is nice.

However, paranoid as I am, I haven't given the `delete_repo` rights, which gives me this:
![image](https://user-images.githubusercontent.com/133706/103630383-3dec4280-4f4a-11eb-9e3b-7f6c6ad3fa57.png)

Can this be enhanced, by adding a button that leads to this url instead?

https://github.com/stdedos/shellcheck/settings#danger-zone

Something like:
```
Update token...
       or
Manually Delete
```

and/or click the button, if possible.

**Comment by fregante** [comment]
Native solution:

1. Click on Settings tab
2. Scroll to bottom


What you’re requesting:

1. Click “Delete repo” button
2. Click “Manually delete” link


I see no improvement. If you don’t want to add the scope, it’s better to just disable the feature.

**Comment by fregante** [comment]
FYI I'm changing how this button works, basically following your advice:

- https://github.com/refined-github/refined-github/pull/7830
