### ISSUE TITLE
`cleanup-repo-filelist-actions`: Cannot read property 'classList' of null

### ISSUE THREAD

**Issue by nixel2007** [sindresorhus/refined-github#3864]
Tried to disable extension: yes, no error in console if RG is disabled.

URL: https://github.com/spring-projects/spring-framework/blob/master/spring-context/src/main/java/org/springframework/context/annotation/CommonAnnotationBeanPostProcessor.java

no screenshot, just console error.

latest Chrome x64, Windows 10 Pro

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/3685

**Comment by nixel2007** [comment]
Oh, sorry, didn't see this is a duplicate :(
