### ISSUE TITLE
embed-gist-inline removes link text

### ISSUE THREAD

**Issue by paulirish** [sindresorhus/refined-github#3865]
[This comment](https://github.com/expressjs/express/issues/2761#issuecomment-628549001) links to a gist, but the link text is useful

Without / With refined github:

![image](https://user-images.githubusercontent.com/39191/103804892-a2210c00-5007-11eb-8861-b4880246f23f.png)

Of course, if the link text is just the straight URL being linked, then no big deal
But in this case, i'd love to have the "This gist can help somebody who needs to use spdy only for development http2 server with express js" text before the embed.

Test On:

https://gist.github.com/sompylasar/99b5d307da3168b833c1119fb95caf11

**Comment by yakov116** [comment]
PLease give us a link to test on...

**Comment by yakov116** [comment]
Look like we need to tweak the feature. We may need to update some selectors since were missing the header bar

**Comment by paulirish** [comment]
> PLease give us a link to test on...

lol my bad. def thought i added that. https://github.com/expressjs/express/issues/2761#issuecomment-628549001

**Comment by fregante** [comment]
Thanks for the report Paul!
