### ISSUE TITLE
`conversation-filters` is broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3868]
1. Visit https://github.com/sindresorhus/refined-github/issues
2. Notice error `TypeError: undefined is not an object (evaluating 'sourceItem.cloneNode')`

Probably the selector needs to be updated

https://github.com/sindresorhus/refined-github/blob/e5a7fa02be0f56f034ffaf3bca7fdb523d3ef90f/source/features/conversation-filters.tsx#L9

**Comment by yakov116** [comment]
Um I commented on the PR that the wrong selector was dropped. I will send a PR soon to fix it

**Comment by yakov116** [comment]
Looks like I will not have time before the release

See the post below what needs to be restored

>Looks like this was wrongly labeled ⬆️ works ⬇️ does not
>
>_Originally posted by @yakov116 in https://github.com/sindresorhus/refined-github/pull/3831#discussion_r551062737_
