### ISSUE TITLE
Extend no-whitespace button (from `faster-pr-diff-options`?) to "

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#3869]

**Comment by sindresorhus** [comment]
To what?

**Comment by sindresorhus** [comment]
Please don't open multiple issues for the same thing.

**Comment by stdedos** [comment]
Oops 😕 I don't know how this happened!
Apologies

**Comment by fregante** [comment]
My guess is that you mistakenly pressed enter while in the title field and then esc to stop the submission, but it still went though. 👍
