### ISSUE TITLE
Wait for attachments to be uploaded before allowing comment submission

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3881]
## Problem

1. Write a comment
2. Attach file
3. Click the "Comment" button before it's done uploading

This is the result: (image will be missing)

![Uploading Screen Shot 2.png…]()

## Solution

When the user tries to submit a comment, the form should be disabled. Interestingly enough, the "New issue" form has this feature already, so we might be able to reuse it somehow.

Notice the green button fading:

![gif](https://user-images.githubusercontent.com/1402241/104117414-bc4c3a00-52e6-11eb-9df7-6d83c14b4d61.gif)

**Comment by artusm** [comment]
> the "New issue" form has this feature already, so we might be able to reuse it somehow.

The "New Comment/Update Comment" form has this feature too/
![aaa](https://user-images.githubusercontent.com/36174850/104245571-8d180300-5475-11eb-909b-62d47b6f0f15.gif)
![Peek 2021-01-12 01-37](https://user-images.githubusercontent.com/36174850/104246290-c8670180-5476-11eb-99bc-4ddb705b492d.gif)



It just doesn't work due to conflict with 
```javascript
                S("[data-required-trimmed]", function (t) {
                    const e = t.currentTarget;
                    "" === e.value.trim() ? e.setCustomValidity(e.getAttribute("data-required-trimmed")) : e.setCustomValidity("");
                }),
                n("change", "[data-required-trimmed]", function (t) {
                    const e = t.currentTarget;
                    "" === e.value.trim() ? e.setCustomValidity(e.getAttribute("data-required-trimmed")) : e.setCustomValidity(""), O(e.form);
                }),
```

**Comment by fregante** [comment]
Not in Safari?

![gif](https://user-images.githubusercontent.com/1402241/104248231-b95c6100-542e-11eb-8520-4f37d17bc94c.gif)

**Comment by fregante** [comment]
> It just doesn't work due to conflict with

Did you take those 2 screenshots after changing something? Does it work or not? 🤔

**Comment by artusm** [comment]
> after changing something?

```javascript
for (const textarea of $$('.js-new-comment-form textarea, .js-new-comment-form textarea')) {
	textarea.removeAttribute('data-required-trimmed');
	textarea.required = true;
}
```

**Comment by fregante** [comment]
I see what's going on now.

1. Upload code calls `e.setCustomValidity('uploading')`, disabling submission
1. `data-required-trimmed` calls `e.setCustomValidity('')`, enabling submission immediately after

All of this overlapping logic is why I was hoping that this could be solved by GitHub themselves rather than adding more code like in #3886.

**Comment by fregante** [comment]
Silly idea: Since the cause of this behavior overlap is `data-required-trimmed`, what if we dropped the attribute during the upload? I wonder if it's possible to fit right between the steps 1 and 2 described above.
