### ISSUE TITLE
Page freezes after refinded-github Chrome ext runs

### ISSUE THREAD

**Issue by Braunson** [sindresorhus/refined-github#3889]
Page that seems to freeze in Chrome when using this ext is: https://github.com/hashicorp/vagrant/issues/11987
Disabling the Refined Github plugin resolves the issue.

I also noticed in the Chrome task manager, the tab jumps to 100% CPU and uses at ~455 MB of memory.

**Comment by fregante** [comment]
Investigating, thanks for the report

**Comment by fregante** [comment]
Believe it or not, it's `embed-gist-inline`. I'll disable it via hotfix

**Comment by yakov116** [comment]
Haha was just about to post!

**Comment by fregante** [comment]
It's because the linked file is gigantic. A limit needs to be put in place before embedding. PR welcome

**Comment by yakov116** [comment]
A limit or if the file is to large don't embed?

**Comment by fregante** [comment]
What kind of limit are you thinking?

**Comment by yakov116** [comment]
Didn't have any in mind. I was trying to clarify what you wanted to do.

**Comment by fregante** [comment]
Yeah, I meant a "limit on gist size", therefore "don't embed if it's larger than the limit"

I'm thinking this can be done in the background fetch via parameter:

```js
const gistData = await browser.runtime.sendMessage({
	fetchJSON: `${link.href}.json`,
	lengthLimit: 1000
});
```

And then compare that `lengthLimit` to the `Content-Length` header _before_ calling `.json()`
