### ISSUE TITLE
Search filter for "Everything commented by you"

### ISSUE THREAD

**Issue by leocaseiro** [sindresorhus/refined-github#389]
I use the search input a lot, and pretty much every day I see myself typing: "commenter:leocaseiro" which is my login.

I was wondering what you guys think if we add a filter that fills that up on "Filters" that populates our login on the search.

Eq: 
![screen shot 2017-04-28 at 5 18 55 pm](https://cloud.githubusercontent.com/assets/940070/25518367/cb917d3e-2c36-11e7-8475-c4e6dbe0ed6c.png)

**Comment by sindresorhus** [comment]
I use that filter a lot too.

**Comment by hkdobrev** [comment]
Let's do it! 🙌

**Comment by sindresorhus** [comment]
@leocaseiro @busches If you haven't done it already, can you contact GitHub support about doing this natively?

From the readme:

> Our hope is that GitHub will notice and implement some of these much needed improvements. So if you like any of these improvements, please email [GitHub support](mailto:support@github.com) about doing it.

**Comment by leocaseiro** [comment]
@sindresorhus 

I emailed the support team!!!

**Comment by leocaseiro** [comment]
Here's the answer from the support:
<img width="488" alt="screen shot 2017-05-11 at 8 33 39 pm" src="https://cloud.githubusercontent.com/assets/940070/25945143/363b6ba2-3689-11e7-8325-bf412b17bbf5.png">

**Comment by paulmolluzzo** [comment]
> Dear Sir/Madam

:rofl:

That's awesome @leocaseiro!

**Comment by leocaseiro** [comment]
Dear @paulmolluzzo,

I am flattered with your reply.

LOL

**Comment by farzher** [comment]
how the heck is this not a github feature ??????
definitely installing this Refined GitHub thingy!

**Comment by davaya** [comment]
Two years later it still isn't on GitHub.   I'll request a "Your comments" menu item again ... who knows what will happen this time.

![github-issue-filter](https://user-images.githubusercontent.com/19152940/57487116-b84c5700-727d-11e9-96ea-4e19cba2f912.jpg)

**Comment by toli-belo** [comment]
Was this feature added to github?

**Comment by yakov116** [comment]
@leocaseiro 	no

**Comment by leocaseiro** [comment]
Thanks, but it wasn’t me asking :)

It was @toli-belo

**Comment by jimmywarting** [comment]
found this by searching on google, github should add this! Or better yet allow us to make up filters and save it with a label so i can create that myself and have it appear in the dropdown

**Comment by MuYunyun** [comment]
Is there any plan to add it in the refined-github?

**Comment by vmario89** [comment]
i am messing around really often because i dont find all the stuff i need :-(

**Comment by fregante** [comment]
The feature exists but it was broken: https://github.com/sindresorhus/refined-github/issues/2647

It will be fixed in the next release
