### ISSUE TITLE
Replace `more-dropdown` with `extend-repo-tabs`?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3894]
What do you think about dropping "more dropdown" in favor of just _adding_ links to the tab bar? The new links could be faded or just be icons so that they're not too noisy.

## Example text-only

<img width="1219" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/104838627-cb506080-5881-11eb-81fa-e4b291fa3073.png">

## Example text-only dimmed

<img width="1228" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/104838633-d3100500-5881-11eb-94e5-ba4bed51c21a.png">

**Comment by sindresorhus** [comment]
I personally prefer hiding them, but I don't feel strongly about it.

**Comment by fregante** [comment]
Same, but I've come to realize that I never actually use the dropdown because I just forget what links it has
