### ISSUE TITLE
Improve auto-inserted ordered list markup

### ISSUE THREAD

**Issue by agarzola** [sindresorhus/refined-github#3895]
GitHub recently introduced a feature which auto-inserts list markup (e.g. `- ` for unordered, `- [ ] ` for checklists) when the `Enter` key is pressed from an existing list item within a comment field. The issue with this implementation is that it auto-increments the number on ordered lists, so if you enter this:

```
1. This is my first item.
```

And press `Enter`, you get this:

```
1. This is my first item.
2. 
```

The problem with this is that it hard-codes the item numbers into the comment, which makes it cumbersome to reorder it otherwise modify the list items in the ordered list. So if I wanted to add an item below the first item, I would end up with this:

```
1. This is my first item.
2. Newly inserted item.
2. This is item number two.
3. My third item.
```

It would be an improvement to have ordered lists always use `1. ` to denote a new ordered list item (i.e. do not auto-increment the number), so that modifying the list does not result in item numbers that are out of order. Markdown will still correctly identify the list as an ordered list. The resulting markup should look like this:

```
1. This is my first item.
1. Newly inserted item.
1. This is item number two.
1. My third item.
```

Is this feasible?

---

As for where this feature should appear, the comment field at the bottom of this very issue page is a great example. 😄 Of course, it should apply to any comment field where GitHub auto-increments ordered list markup.

**Comment by fregante** [comment]
> Is this feasible?

It's feasible, but is it worth it? `1.` or `90.` work the same and they're then forgotten forever once you post the comment. Changing this value means either reimplementing the whole logic or changing the text after it's been injected by GitHub, which then causes another _undo history_ entry.

**Comment by agarzola** [comment]
🤔 You make a good point. I suppose it hadn’t occurred to me that as long as it’s a number at the beginning of a line, Markdown will interpret that to mean it’s another item in the ordered list.

So this:

```markdown
1. Hello!
4. Oh, noes!
2. Originally the second item
3. Third item
10. Item with `10.` in front of it
```

Renders to this:

1. Hello!
4. Oh, noes!
2. Originally the second item
3. Third item
10. Item with `10.` in front of it

I’ll let maintainers determine whether this is worth pursuing or whether it should be closed (seeing there are a couple of 👍s on the original post), but —as irritating as I find this behavior— I do think @fregante’s reasoning is sound.

**Comment by fregante** [comment]
> as long as it’s a number at the beginning of a line

Correct. The only number that matters is the one at the beginning of the list

9000. so you can start your list with
9001. whatever number you please

**Comment by fregante** [comment]
Sorry but I'll have to close this. It feels like a lot of code and potential for conflict and lack of future features to be worth the minimal, non-user-facing improvement.
