### ISSUE TITLE
`tag-changelog-link`: null is not an object (evaluating '/\/releases\/tag\/(.*)/.exec(tagUrl)[1]

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3899]
1. Visit https://github.com/sindresorhus/refined-github/releases
2. See error, no link added
<img width="344" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/104860687-05594b00-58f2-11eb-8cbe-7999a44c1052.png">
<img width="506" alt="Screen Shot 10" src="https://user-images.githubusercontent.com/1402241/104860704-0a1dff00-58f2-11eb-921d-19c3fcf03881.png">

**Comment by yakov116** [comment]
Not seeing it. Same for #3898 

Me think that its safari.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/issues/3898 rarely appears for me too, but I've seen it a few times.

For this one… wow… what is going on here? It fails on the first tag of the next page, the link isn't properly parsed so the regex fails

<img width="668" alt="" src="https://user-images.githubusercontent.com/1402241/104874008-75c69300-5917-11eb-9ed5-5c7ca1d9e457.png">

You may be right about this being Safari-related 🤦‍♂️
