### ISSUE TITLE
Linkify issue when switching tabs on a PR

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#390]
Steps to reproduce:

- Go to https://github.com/sindresorhus/awesome/pull/899
- Click the "Files changed" tab
- Click the "Conversation" tab
- Click the "Files changed" tab

You'll now see that the output went from:

```md
- [Digital Nomads](https://github.com/cbovis/awesome-digital-nomads)
```

To:

```md
- [Digital Nomads](https://github.com/cbovis/awesome-digital-nomads" target="_blank">https://github.com/cbovis/awesome-digital-nomads)
```

// @paulmolluzzo

**Comment by paulmolluzzo** [comment]
Will do!
