### ISSUE TITLE
Unofficial mirror of this extension in the MS Edge extension store

### ISSUE THREAD

**Issue by boarnoah** [sindresorhus/refined-github#3900]
Noticed that the Refined Github extension on the MS Edge store (https://microsoftedge.microsoft.com/addons/) is by a third party who seems to be mirroring extensions off the chrome store while adding a home page redirect to their own site.

Reported it as abuse the MS Store, I thought you folks might be a bit interested in knowing.

**Comment by fregante** [comment]
<details>
<summary>I got its source</summary>

Link:

```js
// https://microsoftedge.microsoft.com/addons/detail/refined-github/hcjnhfcilhlgjbneobbbefooajhmnkfg
```

Download source: https://edge.microsoft.com/extensionwebstorebase/v1/crx?response=redirect&prod=chromiumcrx&prodchannel=&x=id%3Dhcjnhfcilhlgjbneobbbefooajhmnkfg%26installsource%3Dondemand%26uc
Extract .crx file with: https://crxextractor.com
Download same version from Chrome store: https://www.crx4chrome.com/crx/227988/
```

</details>

Not only does it _link_ to its own site, it sets the new_tab page to it! 

Thanks for the issue, I'll report it too.

**Comment by fregante** [comment]
If you have the chance to do so, please leave a negative review about this too, until it's removed.

**Comment by fregante** [comment]
It was finally dropped

<img width="600" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/107556841-811b8000-6b9e-11eb-8a34-6b6daac8b4b1.png">
