### ISSUE TITLE
Make scrollable-code-and-blockquote disable-able

### ISSUE THREAD

**Issue by inducer** [sindresorhus/refined-github#3906]
From [this snippet](https://github.com/sindresorhus/refined-github/blob/b01263379d091df018286360968f48cadfe43a86/source/refined-github.ts#L6-L28) I gather that the `scrollable-code-and-blockquote` feature can't be disabled. Unfortunately, I hate it. :) What would it take to change that?

**Comment by busches** [comment]
You can override the CSS of the feature. https://github.com/sindresorhus/refined-github/blob/b01263379d091df018286360968f48cadfe43a86/source/features/scrollable-code-and-blockquote.css

**Comment by inducer** [comment]
Ah! Makes sense, had not occurred to me. A checkbox might have saved me time in finding this, but your suggestion works for me.

**Comment by fregante** [comment]
Since #6333 (version 23.2.11) you can disable the feature in the options page.
It's now called `scrollable-areas`
