### ISSUE TITLE
Avoid "Done" button in notifications bar navigating to Unread Notifications

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#3907]
First of all, thanks for the continued work on `refined-github`. One of my favorite browser extensions!

Sometimes when I click on the `Done` button in the notifications bar, it returns me to the "Unread Notifications" page, although I wasn't there before.

Not sure what is causing this, but if it's from GitHub, it would be nice to disable this behavior (so that it returns to the unfiltered notification page).

**Comment by fregante** [comment]
GitHub remembers the last view you used. If you clicked “Unread” once, every time you open the notifications you’ll land there. The Done button just points to the notifications page, in whichever view you used last.

**Comment by karlhorky** [comment]
Hm... but I never click on that button 🤔  It is a useless view for me.

I think something else is going on here...

**Comment by karlhorky** [comment]
I guess no interest from `refined-github` to have an option for this then?

**Comment by karlhorky** [comment]
@fregante would you be open for reconsidering this one, considering my comments above?

**Comment by karlhorky** [comment]
For now, I'm using this userscript to avoid this behavior:

https://github.com/karlhorky/dotfiles/blob/main/userscripts/disable-github-unread-notifications-view.user.js

**Comment by karlhorky** [comment]
I wonder if this has anything to do with this [Notifications Preview for GitHub](https://github.com/tanmayrajani/notifications-preview-github) extension that I installed - maybe it is silently sending me to that "Unread" view? I didn't see an option to turn this off though in this extension...
