### ISSUE TITLE
`highlight-non-default-base-branch` Should exclude branch master

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3910]
With everyone switching the base branch to main...

https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged

![image](https://user-images.githubusercontent.com/16872793/105634617-e8120880-5e2c-11eb-8981-b9e07d71cb23.png)

**Comment by fregante** [comment]
Some repositories use something other than `master` as their default branch (e.g. `dev`) and have treated `master` as a "production" branch, so PRs pointing to `master` don't necessarily match the current situation ("this PR was merged into the default branch at the time").

Given that we do not have a history of default branches to properly address this issue, perhaps we can hide `master` if the default branch is `main`, so we cover this use-case exactly.

**Comment by fregante** [comment]
This also applies to `clean-conversation-headers`

**Comment by yakov116** [comment]
Also keep in mind this should only happen on deleted branches. Since if the branch was changed the PR branch (if it was open) would also change

**Comment by fregante** [comment]
Rather than deleted branches I’d do that for “closed PRs”

**Comment by yakov116** [comment]
> Rather than deleted branches I’d do that for “closed PRs”

Merged too? or only closed?

**Comment by fregante** [comment]
Merged and closed

**Comment by yakov116** [comment]
I tried looking for a CSS selector and could not find one. Can you give a look? If not I will add the state to the API call.
