### ISSUE TITLE
Display confirmation popup whenever trying to submit a issue/comment in GitHub that's too short, and maybe every time

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#3911]
GitHub allows in the Issues and Discussions section of repos:

- to submit a new issue with just 1 character as title and no body, and
- to submit a comment with just 1 character .

Apart from that, personally, I sometimes accidentally press the submit keyboard shortcut before my issue/comment text is ready.
mainly because the build-in hotkey for submitting an issue/comment is <kbd>Ctrl + Enter</kbd> (I confuse it with <kbd>Shift + Enter</kbd>)
or just <kbd>Enter</kbd> if typing in the title textbox.
This is embarrassing, having the other members trying to reply to your half-made issue/comment while you still try to finish it...

Also, posting a comment of just a few characters instead of using a reaction is rarely useful.

&nbsp;
So, my suggestion is to add a feature to RG to display a confirmation popup (or a subtle warning message, to press again Submit to confirm) in such edge cases,
and, maybe every time you try to submit a new issue/comment .
I believe that getting a confirmation serves as a reminder to make sure that you have it indeed ready before submitting.

Thank you

---

For reference I have this script: [GitHub - Confirmations before submitting issues and comments](https://greasyfork.org/en/scripts/22288-github-confirmations-before-submitting-issues-and-comments)
which displays a confirmation popup whenever trying to submit a new issue or comment via <kbd>Ctrl+Enter</kbd> or <kbd>Enter</kbd>,
but it's too simple (it doesn't even take into account the text length), in general it's way too far from perfect.

---

<sub>I have already posted this suggestion in https://github.com/isaacs/github/issues/842 and contacted support@github.com years ago.</sub>

**Comment by fregante** [comment]
We can’t block submissions because that would annoy people. We have some warnings like “pr from master” but they’re just warnings. If you press Enter it’s too late to display a warning without also block the submissions.

**Comment by sindresorhus** [comment]
@fregante Can we not block the submit event, and if the user responds yes, just synthesize it again?

**Comment by fregante** [comment]
So you’re suggesting we ask for confirmation when **if** the body is too short? Given that `confirm()` is synchronous we’d just need `if !confirm(), then event.preventDefault()`

**Comment by darkred** [comment]
Would it be possible, instead of using the `confirm()` synchronous modal,
to follow another approach: the more subtle **[popup bubble](http://www.htmldrive.net/items/demo/295/jQuery-Bubble-Popup)** ?

In details:
- RG to disable in advance all ways of submission (i.e. the <kbd>Submit new issue</kbd> and <kbd>Comment</kbd> buttons as well as <kbd>Ctrl+Enter</kbd>/<kbd>Enter</kbd>),
- then RO to attach its own listeners for these buttons and keypress,
- if the user clicks/presses them, to show a popup bubble hovering on the textarea (or the button) with a warning message
- And if user clicks e.g. Enter, RG to make the submission itself?

**Comment by fregante** [comment]
Indeed, either way it requires _one more action_ from the user, however from a code standpoint:

- `confirm()` is easy, but we need to re-enable the form if the user clicks "Cancel" because GitHub breaks it on submit regardless of our confirmation.
- what you're suggesting requires the same changes (since the first submission will be cancelled) + appending a message in the DOM (I'm thinking [something like this](https://primer.style/css/components/alerts#with-icon) rather than the tooltip) + making sure that the user sees the message (it might be out of the viewport)

**Comment by darkred** [comment]
You are totally right, the `confirm()` way is more preferable to implement and maintain in RG 👍 The approach I suggested doesn't seem worth the trouble in the long run.

**Comment by fregante** [comment]
I'm thinking something like:

```js
function handleComment() {
	if (body.length < 3 && !confirm('body too short, sure?')) {
		event.preventDefault()
	}
}

function handleNewConversation() {
	if ((body.length < 3 || title.length < 3) && !confirm('body too short, sure?')) {
		event.preventDefault()
	}
}

// pageDetect.hasComments
delegate(…,'submit', handleComment)

// pageDetect.isNewIssue / isNewPR
delegate(…,'submit', handleNewConversation)
```

**Comment by darkred** [comment]
@fregante 
I've made an effort to turn your code example into actual ts code to be added to RG.
Unfortunately it doesn't block submissions.
Of course I am nowhere near your experience level, and I'll surely need your help to make it working. 
It's just that I'd like to contribute and thought I might be of help into implementing this feature.
Do you think my effort is worth into turning it into a draft PR? What do you say?

<details>
<summary>My effort</summary>

```ts
// import select from 'select-dom';
import delegate from 'delegate-it';
import * as pageDetect from 'github-url-detection';

import features from '.';


// function handleComment() {
function handleComment(event: delegate.Event<MouseEvent, HTMLAnchorElement>): void {    
    let body = event.delegateTarget.closest('.timeline-comment').querySelector('input').value.length;
alert(body)
    if (body < 3 && !confirm('body too short, sure?')) {
        event.preventDefault();
        event.stopImmediatePropagation(); // I don't know if it's necessary to stop comments, they're sent via ajax
    }
}


// function handleNewConversation() {
function handleNewConversation(event: delegate.Event<MouseEvent, HTMLAnchorElement>): void {    
    let body = event.delegateTarget.closest('textarea#issue_body').value.length;
    let title = event.delegateTarget.closest('input#issue_title').value.length;
    if ((body < 3 || title < 3) && !confirm('body too short, sure?')) {
        event.preventDefault()
    }
}

if (pageDetect.isIssue()){
    delegate(document, '.js-new-comment-form button[type="submit"]', 'click', handleComment);
} else if (pageDetect.isNewIssue()){
    delegate(document, 'form[class="new_issue"] button[type="submit"]', 'click', handleNewConversation);
}


void features.add(__filebasename, {
    awaitDomReady: false,
include: [
    pageDetect.isNewIssue, // Find which one you need on https://fregante.github.io/github-url-detection/
    pageDetect.isIssue
],
init,
deinit
});

```

</details>

**Comment by darkred** [comment]
I updated my code: it now it blocks submissions when clicking the Submit button.
Unfortunately I can't find a proper way to capture the keypresses (Enter/Ctrl+Enter).

**Comment by fregante** [comment]
> I can't find a proper way to capture keypresses (Enter/Ctrl+Enter).

Detect the `submit` event instead of click/keypresses



> Do you think my effort is worth turning it into a draft PR? What do you say?

Feel free to open a PR, at least to allow proper reviewing

**Comment by darkred** [comment]
Here it is: #4123 

Thank you!

**Comment by fregante** [comment]
This just happened to me because I fat-fingered the enter key; This feature would not have saved me because the title was long enough, but just not done.

The only way to fix it would be to disable the regular enter key and always use cmd+enter even in `input[type=text]` fields like commits titles, conversation titles, PR merge titles, … but this would likely annoy everyone. 🤷‍♂️

**Comment by darkred** [comment]
What if we followed a different approach? 

Currently, as described in the OP:
- in the "New Issue" form, its "Submit" button becomes active when you type 1 character in title (keeping body empty), 
i.e. with `title.length = 1` and `body.length = 0` 
- in the "Comment" form, the "Submit" button becomes active when you type 1 character in body.
i.e. with `body.length = 0` .

My idea is to drop the use of the admittedly obtrusive `confirm()`,
and just modify the forms functionality so that their "Submit" button  only become activated when what you have typed is long enough? Till then to remain disabled/grayed-out.

And of course rename the feature to: `disallow-short-comments`

**Comment by fregante** [comment]
Again, shortness has nothing to do with the issue since the problem is “fat-fingering `enter` before you’re done”, which can happen at any length.

Adding a confirmation regardless of length will just be annoying.

**Comment by darkred** [comment]
I'm afraid I wasn't clear enough or too verbose.. 
What I suggested with my last comment is something very different:

1. Disable submitting via <kbd>Enter</kbd> in `input[type=text]` fields in Issue/PR titles :
i.e. when you have focus to the title field in new Issue/PR pages, to be able to submit only via <kbd>Ctrl+Enter</kbd> or clicking 'Submit' .
This would take case of mistyping Enter, as it occurred to you.

2. Not display any confirmation at all. Instead, enable submitting based on length,  
i.e. the Submit button to remain disabled until both title and body content have length more than a given limit.
This is the aim for my whole feature request, to prevent too short messages.

**Comment by fregante** [comment]
Moved to updated issue

**Comment by darkred** [comment]
@fregante Thanks for opening the updated issue.

---

I just wanted to clarify, regarding my other suggested feature :

> 1. `disallow-short-comments`:
> Enable submitting based on length, 
> i.e. the Submit button to remain disabled until both title and body content have length more than a given value, e.g. 3. 
> _<sup>(no `confirm()`, no confirmation dialog at all)</sup>_

Don't you think this would be useful as well?
It would prevent submitting issues with just 1 character title and no body, and comments with just 1 character,
As I wrote in the OP, posting a comment of just a few characters instead of using a reaction is rarely if ever useful.

**Comment by fregante** [comment]
We can’t block actions by the user. If they want to open a 1-emoji issue, let them. The other issue takes care of accidental presses

**Comment by darkred** [comment]
Ok, thank you for replying.
