### ISSUE TITLE
Original "Create pull request button" isn't removed

### ISSUE THREAD

**Issue by mischnic** [sindresorhus/refined-github#3914]
Refined Github adds a separate button for a draft PR, but the original button isn't removed:

![Bildschirmfoto 2021-01-27 um 19 24 51](https://user-images.githubusercontent.com/4586894/106036233-55e05d80-60d5-11eb-87cc-59b876e23ba3.png)

**Comment by busches** [comment]
Last change broke the feature on GHE as well, I'll see if I can fix both sometime this week.

**Comment by busches** [comment]
I can't recreate this 🤷

**Comment by mischnic** [comment]
Strange, I don't get it here: 

https://github.com/sindresorhus/refined-github/compare/unknow-feature-name?expand=1

![Bildschirmfoto 2021-01-28 um 11 40 47](https://user-images.githubusercontent.com/4586894/106126450-abf8e380-615d-11eb-903f-2101c711e0b6.png)


but for example here:

https://github.com/parcel-bundler/parcel/compare/abstract-fs-part-2?expand=1

![Bildschirmfoto 2021-01-28 um 11 41 17](https://user-images.githubusercontent.com/4586894/106126514-bd41f000-615d-11eb-8cbc-a321ef0ddf3d.png)

The only difference I can think of is that I have push access to the Parcel repo.

**Comment by MrChocolatine** [comment]
Same problem spotted on a private repository, I was about to create an issue.

**Comment by fregante** [comment]
Draft PRs aren't available on private repos of non-PRO users, so probably the DOM is different there. If you see any errors in the console, paste it here

**Comment by fregante** [comment]
Strangely I can't replicate it. Do you see any errors in the console?

<img width="693" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/106211972-3b6aba80-618f-11eb-945d-94f076e6602c.png">

**Comment by mischnic** [comment]
Yes:
```
refined-github.js:2134 ❌ Refined GitHub → separate-draft-pr-button → TypeError: Cannot read property 'name' of undefined
    at init (refined-github.js:6722)
    at runFeature (refined-github.js:2152)
    at setupPageLoad (refined-github.js:2160)
    at refined-github.js:2193 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'name'%20of%20undefined

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60separate-draft-pr-button%60%3A%20Cannot%20read%20property%20'name'%20of%20undefined
```

**Comment by mischnic** [comment]
In the loop iteration where the error is thrown, `dropdownItem` here

https://github.com/sindresorhus/refined-github/blob/3aadf2f9141107d7ca92e8753f2a66cbc10ebd9d/source/features/separate-draft-pr-button.tsx#L24

is this element:
 
<img width="768" alt="Bildschirmfoto 2021-01-29 um 00 42 36" src="https://user-images.githubusercontent.com/4586894/106212423-e482d680-61ca-11eb-9771-3b4f1a14b690.png">

where `<details>` at the very top is the assignee menu:

<img width="1302" alt="Bildschirmfoto 2021-01-29 um 00 40 00" src="https://user-images.githubusercontent.com/4586894/106212271-8655f380-61ca-11eb-8e67-3e1b1550b1d6.png">

If I'm not a member of the repo, there is no assignee/reviewer dropdown at all. So that would explain the differing behaviour on my side.
