### ISSUE TITLE
Keep diff stats on PR file list when header is fixed

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#3925]
There's a bug in the GitHub UI with the Jump to file list on PR pages.

To be clear, this is not a bug from Refined GitHub. It's a UI glitch which GitHub has and I hope Refined GitHub could improve similar to others.

To reproduce:

1. Open a PR Files tab on GitHub with enough changes - e.g. https://github.com/sindresorhus/refined-github/pull/3922/files
2. Open the "Jump to..." files list.
3. Notice the diff stats on the right of each file.
4. Scroll down the whole page until the header is fixed.
5. Notice the diff stats disappear when the header is fixed.

---

Top of the page, header not fixed:
![Screenshot 2021-01-29 at 13 43 54](https://user-images.githubusercontent.com/506129/106271793-ba67fd80-6238-11eb-80c4-e342d5cbb5eb.png)

---

Scrolled down, header fixed:
![Screenshot 2021-01-29 at 13 44 02](https://user-images.githubusercontent.com/506129/106271790-b936d080-6238-11eb-9cef-f5567ca9d423.png)

**Comment by fregante** [comment]
This can probably be just some CSS in the main css file.
