### ISSUE TITLE
Custom css section does not change monospace font

### ISSUE THREAD

**Issue by aminomancer** [sindresorhus/refined-github#3928]
Here's what I'm seeing in textboxes:
```
.rgh-monospace-textareas #merge_title_field,
.rgh-monospace-textareas #commit-summary-input,
.rgh-monospace-textareas textarea {
	font-family: SFMono-Regular, Consolas, 'Liberation Mono', Menlo, Courier, monospace !important;
}
```
So I copied the rule to the "Custom CSS" text area in the extension's options page, replacing the font with the monospace font I'm using for my overall github theme and other extensions. But it has no effect. I'd use another method to inject this but RGH's stylesheet takes precedence over my inline styles. I'm sure I'll work it out on my own but just thought I'd let you know

**Comment by fregante** [comment]
Yeah we don’t decide the order of injection, you’ll have to use important or increase the specificity of the selector, for example by or ending :root on every line
