### ISSUE TITLE
`onPrMergePanelOpen()` may be broken

### ISSUE THREAD

**Issue by cheap-glitch** [sindresorhus/refined-github#3932]
1. Go to a PR page (e.g. https://github.com/sindresorhus/refined-github/pull/3886)
2. Type something in the comment form at the bottom
3. Reload the page

Two features will produce an error (sometimes only one of them appear):
```text
clear-pr-merge-commit-message → TypeError: messageField is undefined
suggest-commit-title-limit → TypeError: inputField is undefined
```

Since both of these features make use of `onPrMergePanelOpen`, I'm guessing that's where the problem is.

**Comment by fregante** [comment]
I think they’re both referring to the textarea or input, likely their selector needs to be updated

**Comment by cheap-glitch** [comment]
> I think they’re both referring to the textarea or input, likely their selector needs to be updated

I may be wrong, but I think it's more a case of the features being triggered when they shouldn't be.

**Comment by fregante** [comment]
Can't replicate the error in any way

**Comment by cheap-glitch** [comment]
I still see the errors on latest `main` commit. @fregante did you type something in the comment box? The errors only appear for me if some text is already present in the comment textarea when the page loads.

**Comment by yakov116** [comment]
I attempted this once https://github.com/sindresorhus/refined-github/pull/2956

**Comment by fregante** [comment]
Wow, it feels like I left that review yesterday, but it’s been nearly a year
