### ISSUE TITLE
Add ability to dismiss server banners

### ISSUE THREAD

**Issue by jmerdich** [sindresorhus/refined-github#3937]
Putting feelers out for interest on this, willing to implement it, but want to gauge interest first. At my workplace, we use Github Enterprise, and our admins are keen to use the site-wide banner in order to reiterate policies at the cost of screen space.

![Example screenshot](https://user-images.githubusercontent.com/6345033/106673154-2ae78500-657f-11eb-939e-df4d0e6e7594.png)

This is on the top of every page, including the login page, and banners are a [core github-ent feature](https://docs.github.com/en/enterprise-server@2.22/admin/user-management/customizing-user-messages-for-your-enterprise), not custom css/html. I'd like to be able to dismiss it if I've already been welcomed 100+ times before.

To that end, I'd like to put in a new feature that does the following:
 - Checks for the presence of a enterprise-wide/server-wide banner
 - Make an 'X' on the side of the banner
 - Upon clicking the 'X', cache the text of the banner (or a hash of it) in per-site local storage and hide it.
 - With an existing cache from dismissing a banner before, hide the banner on page load unless it does not match the cache. That way, actual useful information (eg, an upcoming maintenance) is not hidden unless you dismiss it again.

This is not seen by most github users, being rather gh-ent specific, but I feel it's unobtrusive and useful enough to be included here.

**Comment by fregante** [comment]
It's a little niche to be part of RGH, also because none of us will end up using it and can easily become a forgotten feature.

**Comment by mikeev261** [comment]
Hi @fregante, can you please elaborate more on why this was closed? As a new Github enterprise user, I too would love to be able to dismiss my company's banner. It's absolutely massive, and hurts usability of the product given how much vertical real-estate it consumes.

**Comment by busches** [comment]
As he said, the feature is very niche and not likely to be maintained. You should be able to hide it with a CSS override in the extension.

**Comment by mikeev261** [comment]
I guess my disconnects are: 

1) The assertion that a desire to hide this massive banner is "niche". I don't understand how this banner doesn't drive virtually every user crazy. 

2) That it would be difficult to implement and maintain. Github's UI already has examples that are very close to this request: 

![image](https://user-images.githubusercontent.com/4935661/142454528-380aaa76-7090-46dd-8c7f-d39c29fc34ce.png)

**Comment by mikeev261** [comment]
Please disregard- you guys are right. I was looking at the wrong thing.
