### ISSUE TITLE
Firefox is not seeing 21.2.1 release for upgrading

### ISSUE THREAD

**Issue by marcphilipp** [sindresorhus/refined-github#3941]
I've been trying for days now to upgrade to https://github.com/sindresorhus/refined-github/releases/tag/21.2.1, but Firefox doesn't see any updates. I'm currently on 21.1.23. Any idea what's going on there?

**Comment by cheap-glitch** [comment]
@fregante It seems the new version wasn't released to AMO, latest version is 21.1.23: https://addons.mozilla.org/en-US/firefox/addon/refined-github-/versions

**Comment by fregante** [comment]
Yeah it’s stuck in the review queue. Nothing we can do about it

**Comment by marcphilipp** [comment]
Thanks for checking and sorry for the noise. Keep up the great work, I really enjoy using the extension every day.

**Comment by fregante** [comment]
No worries, sometimes we don't notice that the release failed so it's good to be notified

**Comment by fregante** [comment]
21.2.1 has been approved for Firefox 👍
