### ISSUE TITLE
`releases-tab` not shown occasionally

### ISSUE THREAD

**Issue by scris** [sindresorhus/refined-github#3942]
Hello, this extension is fantastic, but recently I ran into a trouble that the release button is not shown. It was probably related with the `.latest-tag-button → TypeError: select_dom(...) is undefined` error, which may be linked with the newly added buttons on that list. （Sometimes the Release button shows, but most of the times not, with only this error shown）

Thanks for making this extension and for your time spent on this issue.

(On)<img width="1552" alt="Screen Shot 2021-02-04 at 15 18 58" src="https://user-images.githubusercontent.com/23412857/106858279-63f93400-66fc-11eb-8883-bbb1a8d5becd.png">
(Off)<img width="1552" alt="Screen Shot 2021-02-04 at 15 19 23" src="https://user-images.githubusercontent.com/23412857/106858302-6a87ab80-66fc-11eb-83d7-d582101d62b9.png">

On Firefox 85.0 on macOS, using Refined GitHub 21.1.23.

**Comment by busches** [comment]
Is the release button the release section?

**Comment by fregante** [comment]
Yeah the release tab is missing for me regularly too, I have to refresh the page to see it. I don’t know how to replicate it though

**Comment by scris** [comment]
> Is the release button the release section?

@busches I can't tell what should it be called, but I think I'm talking about the one beside Code, Issues, Pull requests etc.

**Comment by fregante** [comment]
It's `releases-tab`

**Comment by yakov116** [comment]
Is this still an issue?

**Comment by fregante** [comment]
Yes, no idea what's causing it. Still no errors in the console and a refresh makes it appear:

<img width="1017" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/111014206-43aa3e00-8368-11eb-948c-90c566acea74.png">

(still on v21.3.5 though)

**Comment by cheap-glitch** [comment]
@notDavid If the issue persists, please open a new ticket instead of bumping old ones. Thanks
