### ISSUE TITLE
Make card navigation via j/k smooth?

### ISSUE THREAD

**Issue by ThomsonTan** [sindresorhus/refined-github#3943]
`j/k` could be used as keyboard shortcut to move focused card in issue or pull request page which is convenient, but navigation is not smooth (no moving animation). Is it possible to make the navigation smooth like `window.scroll({behavior: 'smooth'});`?

**Comment by fregante** [comment]
This can already be achieved globally with `html {scroll-behavior: smooth}`

![gif](https://user-images.githubusercontent.com/1402241/106939832-66e92a00-66e6-11eb-88e3-637ce2757513.gif)

I'm not sure whether we should include this because people are pretty sensitive about their scroll behavior.

**Comment by ThomsonTan** [comment]
Thanks for the pointer. It seems this global CSS style doesn't work well with `j/k` navigation like in this page. It indeed triggers smooth scrolling but the focused card could miss go to the top (I guess smooth scrolling interferes with some navigation setting in JavsScript).

I'd agree that this might not be expected by others, I'll try add this to my local script.

**Comment by fregante** [comment]
> the focused card could miss go to the top

I don't understand what you mean

**Comment by ThomsonTan** [comment]
Sorry for the confusion. I meant the focused card would lose focus for any mouse click on the area out side the car, then `j` keyboard shortcut will start navigation from the top. This seems a little annoy.

Is there a way to auto-focus the card which was clicked, then the following `j/k` command starts navigation from the clicked card?

**Comment by fregante** [comment]
> I meant the focused card would lose focus for any mouse click on the area out side the car

That's just how j/k has been implemented and making it smooth would not affect that. Closing this issue since smoothing can be achieved via CSS, if desired
