### ISSUE TITLE
Copy button doesn't show (and other file-related features)

### ISSUE THREAD

**Issue by munael** [sindresorhus/refined-github#3945]
E.g.: https://github.com/TRSasasusu/SpikingMoYF/blob/master/network.py
![image](https://user-images.githubusercontent.com/5769148/107047735-d20f2b00-67d0-11eb-85e7-11f67024b288.png)

**Comment by fregante** [comment]
I found this too. It appears after a refresh. It probably has something to do with Ajax navigation

**Comment by yakov116** [comment]
This issue is very complex. Basically any time you navigate from a file selection any feature that needs to run does not.
This includes not just features that are within the file box. Even `fork-to` is affected.

**Comment by fregante** [comment]
> Even `fork-to` is affected.

I don’t think so, that area is not updated when navigating the files, so the RG changes aren't lost nor do they need to be re-applied.

![gif](https://user-images.githubusercontent.com/1402241/108640914-0f76e800-7462-11eb-8930-a2758c369400.gif)


> This issue is very complex

This issue just means that we can't rely on `has-rgh` to deduplicate our features. Fixing this would mean making `features.add` aware of which features need to be run on filelists as well and having their own `filelist-has-rgh` file.

I think it's easier to just use per-feature checks on filelist features, as described in https://github.com/sindresorhus/refined-github/pull/3968#discussion_r574831236

**Comment by fregante** [comment]
The comment on https://github.com/sindresorhus/refined-github/blob/61bfebbb2be4007c4b9a89b1e4c6cacea5123c31/source/features/download-folder-button.tsx#L25:L25 will also have to be updated as part of this PR

**Comment by yakov116** [comment]
> I don’t think so, that area is not updated when navigating the files, so the RG changes aren't lost nor do they need to be re-applied.

When going to a single file fork-to is supposed to link to the file on the fork. (Maybe I am mixing up feature nanes)

**Comment by fregante** [comment]
Ah crap, you may be right. That part of the feature isn't update.

It appears that the issue affects every feature on files and filelists. Another example:

1. Visit https://github.com/sindresorhus/refined-github/find/main
2. Type forkedto
3. Open the feature
4. No `rgh-feature-descriptions` enabled 😕 
5. Refresh the page
6. There it is…

**Comment by kidonng** [comment]
Just FYI, navigation through Octotree does pair nicely with Refined GitHub (sadly they are closed source now, so it doesn't help much).

**Comment by fregante** [comment]
What do you mean by "pair nicely"? If I remember correctly OctoTree implemented its own loading mechanism (for no good reason) so many other extensions didn't work because of it. I don't know if that has been changed since.

**Comment by cheap-glitch** [comment]
> navigation through Octotree does pair nicely with Refined GitHub 

+1

I've been using the paid version of Octotree for a few months now, and it works great. RGH features are correctly enabled whenever navigating between files, there's no need to reload the page.

Afaik it seems to use the native GH navigation (or at least some kind of AJAX navigation) because the page is never fully reloaded.

**Comment by yakov116** [comment]
I have never used octo but am I correct they only need to monitor the tree part of github? We need to monitor the whole page.


What about  about we add a config called `repeatWhereNotExist: 'selector here'` and do a select.exists on run?

I know this is a bit manual but it can work until we find a good solution.

**Comment by kidonng** [comment]
> If I remember correctly OctoTree implemented its own loading mechanism (for no good reason) so many other extensions didn't work because of it.

If you are referring to ovity/octotree#490, that has been fixed a long time ago.

> I don't know if that has been changed since.

It certainly does, but we won't know exactly how now 🤷‍♀️

**Comment by fregante** [comment]
I think I know why it works with octotree: they load the whole page as GitHub used to do before. The issue here doesn’t apply because GitHub replaces part of the page, leaving `has-rgh` untouched. 

@yakov116 that’s an interesting solution, which basically standardizes what we already do manually inside init in some cases. 

Either way I’d like this issue fixed before the next release, so if no one opens a PR with their solution I will

**Comment by yakov116** [comment]
> @yakov116 that’s an interesting solution, which basically standardizes what we already do manually inside init in some cases.

Exactly my thought.


> Either way I’d like this issue fixed before the next release, so if no one opens a PR with their solution I will

Do you like my idea? or do you want another idea.

**Comment by fregante** [comment]
Your either could work. It could even be merged with the existing deduplication key: `deduplicate: 'selector'` for your suggestion and `deduplicate: true` for the current behavior (equivalent to `deduplicate: 'has-rgh'`)

**Comment by yakov116** [comment]
I want to finish up my other PR(s) so your free to take this. If not I can try sometime next week.

**Comment by fregante** [comment]
`onetime` _could_ also be merged into the same property if it makes sense, since it's also used to avoid running multiple times, but naming the option might be tough. Maybe:

```diff
- init: onetime(init)
+ deduplicate: 'once',
+ init
```

```diff
- repeatOnBackButton: false,
+ deduplicate: 'auto',
```
```diff
- if (select.exists('.rgh-selector')) {
- 	return false;
- }
...
+ deduplicate: '.rgh-selector',
```

**Comment by yakov116** [comment]
What about

https://github.com/softvar/enhanced-github/blob/master/src/background.js

**Comment by fregante** [comment]
There's no deduplication there, they're just tracking the URL in an unnecessarily-complex way (we do the same by just listening to `pjax:end`)

**Comment by fregante** [comment]
`show-whitespace` seems to be missing too

1. Open https://github.com/sindresorhus/refined-github/tree/main/build
2. Open file
3. See no whitespace

![gif](https://user-images.githubusercontent.com/1402241/119999567-16326f80-bffc-11eb-98d0-793ced6c2a3c.gif)
