### ISSUE TITLE
Move `download-folder-button` to the dropdown

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3949]
It looks like GitHub added a "Delete directory" button in a dropdown:

<img width="378" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/107127379-4c948500-687b-11eb-853b-382a8d4bf09e.png">

Now there are too many buttons, so we should move `download-folder-button` to the dropdown. We can drop the icon and name use "Download directory" as label

**Comment by yakov116** [comment]
I think the text should also be changed to "Download directory" it should be on top of the delete.
