### ISSUE TITLE
Add a top-level “Open in Desktop” button to the repo homepage

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#3957]
Example URL: https://github.com/sindresorhus/refined-github

This functionality is already available under Code → Open with GitHub Desktop, but this would make it available with a single click:

<img width="697" alt="Screenshot_2021-02-08 14 54 37" src="https://user-images.githubusercontent.com/25517624/107273847-9ddc7a00-6a1d-11eb-9b8f-161b425b65c8.png">

Copying over the URL from the menu item would be a good start, but it would be awesome if the link could take into account the current branch (so that the Desktop app can automatically check it out).

The URL format is <code>x-github-client://openRepo/https<span>://</span>github.com/<strong>user</strong>/<strong>repo</strong>?branch=<strong>branch</strong></code>.

**Comment by fregante** [comment]
While I use GitHub Desktop myself, I don't think this is an action done often enough that it needs to be moved outside the dropdown, especially considering that there are other methods that are probably used by more people.
