### ISSUE TITLE
Inline code in title became very small

### ISSUE THREAD

**Issue by fisker** [sindresorhus/refined-github#3959]
GH updated style?

![image](https://user-images.githubusercontent.com/172584/107333828-f0d33180-6af0-11eb-8dc8-07c173ae9753.png)

**Comment by cheap-glitch** [comment]
I'm not seeing this on Firefox or Chromium with the latest RGH version (`21.2.1`).

**Comment by fregante** [comment]
Same for me in every browser. I've only seen that happen when you disable the extension in Firefox after it runs since it removes the stylesheet (while the new dom elements remain)

**Comment by fisker** [comment]
I remember when I check the style I got a  `code, ... {font-size: 12px}`, and it's from github server, I should wrote down that css file url, I'll check again if problem still exists tomorrow(on phone right now).

**Comment by fisker** [comment]
I can still see it

![image](https://user-images.githubusercontent.com/172584/107501869-ea1ceb00-6bd2-11eb-901b-4295116b68ce.png)

The style sheet url display a scss file

![image](https://user-images.githubusercontent.com/172584/107502224-5f88bb80-6bd3-11eb-9143-fbacd8029591.png)

And my browser is ms edge 90.0.793.0.

**Comment by fregante** [comment]
The ridiculous part here is that our selector is already higher than theirs, so I’m not sure of how it could happen in the first place.

**Comment by fisker** [comment]
I tried to find where it come from, not very sure but most possible is from github self, I think they updated it, but still testing.

Do you think it's safe to add `font-size: inherit`?

**Comment by fregante** [comment]
> Do you think it's safe to add `font-size: inherit`?

That means `1em` (or whatever the title has), which would be too big, and wouldn't solve the issue because it'd still be overridden.

> possible is from github self

The source points to it, so yeah. It might just be an Edge issue 🤔

**Comment by fisker** [comment]
> because it'd still be overridden

Sorry, I didn't notice `.rgh-` class already set font-size.

**Comment by fregante** [comment]
> It might just be an Edge issue 🤔

All signs point to it. It works well in every browser and the selector should definitely override it.

As a quick fix you could apply some custom CSS to fix it locally and/or you could report it to Microsoft.

Closing because Edge isn't directly supported (none of us use it) and because this is a browser bug.
