### ISSUE TITLE
"Add collapsible content" button has wrong border (/color)

### ISSUE THREAD

**Issue by mischnic** [sindresorhus/refined-github#3961]
Occurs on every page with the editor (not just when creating an issue)

<img width="922" alt="Bildschirmfoto 2021-02-09 um 15 00 27" src="https://user-images.githubusercontent.com/4586894/107374120-8bc70e00-6ae7-11eb-959d-f266816bdc0f.png">

**Comment by kidonng** [comment]
This also affects `table-input` button. I'm working on the updated classes.

**Comment by fregante** [comment]
> **Update: seems like the issue is gone**.

My guess is that they sent some breaking CSS, same for #3959.

**Comment by mischnic** [comment]
> seems like the issue is gone

Indeed. Works in both dark and light mode now.

**Comment by fregante** [comment]
Closing until it appears again
