### ISSUE TITLE
In markdown PR's, show referenced images inline on hover.

### ISSUE THREAD

**Issue by dylang** [sindresorhus/refined-github#3967]
With many of us writing documentation to markdown files, maybe we can make the review a little easier if we show referenced images:

# Before
<img width="839" alt="Screen Shot 2021-02-11 at 2 21 17 PM" src="https://user-images.githubusercontent.com/51505/107689262-9a8ffb00-6c76-11eb-80e3-3869b760dcfa.png">

# On mouse over (mock up, not a real design)
<img width="820" alt="Screen Shot 2021-02-11 at 2 34 36 PM" src="https://user-images.githubusercontent.com/51505/107689273-9d8aeb80-6c76-11eb-848b-a4864c8ae05b.png">

I'm not great with CSS so that's the best I could mock up quickly in Chrome debug tools. 😄

**Comment by fregante** [comment]
The only thing we should help with here is linkifying that URL, but I think this request has been rejected before. I'd suggest asking this in https://github.com/Justineo/github-hovercard or even just a more generic "show image on hover" extension, of which there are a few.

**Comment by fregante** [comment]
Relative URL linkification request moved to https://github.com/sindresorhus/refined-github/issues/4081
