### ISSUE TITLE
Button to mark all "merged" items as done in notifications.

### ISSUE THREAD

**Issue by fugkco** [sindresorhus/refined-github#3969]
Hello, could we have a button in the [notifications](https://github.com/notifications) page that automatically marks all merged items as done? Currently I'm having to click on each item, then mark as read. It's fine if the whole project has all items merged, as there's a `Mark as done` button, but e.g. when there's one or two not merged, I'd like to make sure they stay in my notifications.

**Comment by fregante** [comment]
This is too specific for a single button, but https://github.com/sindresorhus/refined-github/issues/3229 could be a 2-click solution.
