### ISSUE TITLE
Diff lines indented incorrectly

### ISSUE THREAD

**Issue by karlhorky** [sindresorhus/refined-github#397]
It looks like a GitHub update has caused the easier copy/paste feature from #282 to start indenting diffs incorrectly in some places.

For instance, in the diff of #282 itself:

<img width="127" alt="screen shot 2017-05-03 at 10 02 36" src="https://cloud.githubusercontent.com/assets/1935696/25652450/91491f46-2fe8-11e7-8df9-fa81a6cde1d7.png">

https://github.com/sindresorhus/refined-github/pull/282/files

The `td` selector is not vertically aligned with the closing curly bracket.

---

However, as a counterexample (to show that it doesn't always happen everywhere), the `if` conditional also in this pull request does line up correctly:

<img width="111" alt="screen shot 2017-05-03 at 10 30 22" src="https://cloud.githubusercontent.com/assets/1935696/25653076/9aa1d49a-2feb-11e7-90a0-4c4aab34ebc4.png">

cc @jacobbearden

**Comment by paulmolluzzo** [comment]
We just merged in #396, which might fix this issue. Would you mind updating to use `master` (not the latest version in the Chrome store) and see if it resolves the issue? If you're already using the latest version on `master` then, yeah, it's a bug. 😀

**Comment by karlhorky** [comment]
Looks great @paulmolluzzo ! Sorry, I didn't see this merged PR - just looked through the open ones. When do you think this will be released?

Closing this issue. 😄

**Comment by sindresorhus** [comment]
I just did a new release. It will take up to an hour to rollout to browsers.
