### ISSUE TITLE
`parse-backticks` doesn't work in Discussions

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#3975]
I've started this discussion https://github.com/tophf/mpiv/discussions/50
and the text in backticks is not rendered, not in the post title, in the listing,
even though the `parse-backticks` feature is listed ok in Console (![2021-02-14_174406](https://user-images.githubusercontent.com/723651/107881276-5574fe80-6eec-11eb-95e2-32b0e447107e.jpg))
 
There's no error in Console.

Using Refined GitHub 21.2.9 with Chrome 88/Firefox 85.

<details>
<summary>Screenshots</summary>

(in a fresh Chrome profile)

![2021-02-14_174256](https://user-images.githubusercontent.com/723651/107881284-6160c080-6eec-11eb-8050-fd266d0a9c3d.jpg)
![2021-02-14_174309](https://user-images.githubusercontent.com/723651/107881285-64f44780-6eec-11eb-85e6-43f711fe1f2a.jpg)
</details>

If I may help, checking https://github.com/sindresorhus/refined-github/blob/main/source/features/parse-backticks.tsx I see there's no selector for Discussion pages/listings.
I think these would be:
- `.js-issue-title` for discussion pages
- `a[data-hovercard-type="discussion"]` for discussion listings

Thank you

**Comment by yakov116** [comment]
PR Welcome @darkred willing to send one?

**Comment by darkred** [comment]
Yes, of course. I'll try to send one in a few minutes.

**Comment by darkred** [comment]
Here it is: https://github.com/sindresorhus/refined-github/pull/3977 🙂

**Comment by darkred** [comment]
My PR #3977 had enabled `parse-backticks` in both discussion listings/pages.
 
Recently I've noticed that the text in backticks in discussion *pages* is not rendered anymore.
( but, the relevant selector (`.js-issue-title`) I had added with the PR is still valid )

- discussion listing (working)  : https://github.com/tophf/mpiv/discussions
- discussion page (not working) : https://github.com/tophf/mpiv/discussions/50

Screenshot of the latter:
![2021-04-07_122531](https://user-images.githubusercontent.com/723651/113843604-64fe1e80-979c-11eb-9706-e4f755f52139.jpg)

*Note that the native rendering of backticks doesn't apply to discussion pages/listings as of yet.*

**Comment by darkred** [comment]
I see that the selector `.js-issue-title` for Discussion page titles, that was added in my PR,
has been removed in this PR https://github.com/sindresorhus/refined-github/pull/4136#issuecomment-805101315

**Comment by yakov116** [comment]
Correct the selector was too general

**Comment by darkred** [comment]
Should I make a new PR for adding `.gh-header-title > span.js-issue-title` instead?
I believe this selector is ok.

**Comment by yakov116** [comment]
No that is still not good since it applies to every issue page.

Also I would rather wait for #4135 before doing this change.

**Comment by darkred** [comment]
Ok I'll just share the unique selector I found:
`.js-discussions-title-container .gh-header-title > span.js-issue-title`.

*(so I'll wait for #4135 to be addressed, and then ask you again at that time)*

**Comment by kidonng** [comment]
This should be reopened
