### ISSUE TITLE
Enable `reactions-avatars` on discussions  and releases

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#3978]
Such as https://github.com/tophf/mpiv/discussions/50

**Comment by yakov116** [comment]
Its not so easy as its lazy loaded. (The element gets replaced on load)

**Comment by fregante** [comment]
Yeah I'm afraid that it would require substantial rewrite of the feature just to apply to a completely different dom and events 🤔

**Comment by fregante** [comment]
If anyone picks this up, it’d have to be considered brand-new feature. It can be merged later, but likely all the JS needs to be different.

**Comment by kidonng** [comment]
Maybe also on releases: https://github.com/microsoft/winget-cli/releases/tag/v-0.3.11102-preview

![image](https://user-images.githubusercontent.com/44045911/117522707-61ea8e00-afe7-11eb-8b8a-6d19ec07ca2a.png)

**Comment by fregante** [comment]
I think it's less useful on releases

**Comment by fregante** [comment]
> I think it's less useful on releases

I changed my mind
