### ISSUE TITLE
`latest-tag-button` is sometimes misaligned

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#3979]
<img width="422" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/107891549-01b2e700-6ee5-11eb-8096-654919f804fc.png">

Example: https://github.com/GhostText/GhostText/tree/21.2.3.221

A bug fix for this needs to be tested on different pages, like on the latest tag, old tag, branch, folder, file, …

**Comment by yakov116** [comment]
Happens to me all the time when you go from a file list page
