### ISSUE TITLE
Code Page Not Loading On Org Repo with Error `bugs-tab`: Extension context invalidated

### ISSUE THREAD

**Issue by sheldonhull** [sindresorhus/refined-github#3997]
Version: `20.7.16`
- Main code body won't load without disabling extension on a specific org repo (internal). 
- Private personal repo loads fine
- Public repo loads fine.

I can't provide the url for the org repo due to privacy.
I'll add further details if I can figure out what is different about the readme, maybe an html clip or something?

<details closed>
<summary>ℹ️  With Public Repo - Works Both On and Off</summary>

![public-repo-visible](https://user-images.githubusercontent.com/3526320/108548711-d861d480-72b1-11eb-9c86-c005ed771645.png)

</details>

<details closed>
<summary>ℹ️  With Extension Enabled on Private Org Repo</summary>

![org-repo-not-loading](https://user-images.githubusercontent.com/3526320/108548547-99cc1a00-72b1-11eb-8317-ab966f13024b.png)

</details>

I looked at console and found this error. (btw, cool idea about having the console log link to open issue, very smart 👍 )

```
 Refined GitHub → bugs-tab → Error: Extension context invalidated.
    at refined-github.js:618
    at refined-github.js:611
    at new Promise (<anonymous>)
    at refined-github.js:610
    at refined-github.js:676
    at bugs_tab_init (refined-github.js:8079)
    at runFeature (refined-github.js:2861)
    at setupPageLoad (refined-github.js:2869)
    at HTMLDocument.<anonymous> (refined-github.js:2906) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Extension%20context%20invalidated.

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60bugs-tab%60%3A%20Extension%20context%20invalidated.
		
logError @ refined-github.js:2839
```

**Comment by yakov116** [comment]
Did you try to refresh the page?

**Comment by sheldonhull** [comment]
Yes. I disabled and attempted to reload the page as well as click to issues and then click back to the code page.

**Comment by sheldonhull** [comment]
@yakov116 I was able to reproduce on this public repo too.
https://github.com/jaroslawhartman/TimeZones-Alfred

**Comment by fregante** [comment]
> Version: `20.7.16`

Update Refined GitHub

**Comment by sheldonhull** [comment]
Uninstall and reinstall forced an update. The page immediately loaded. 
Thank you for this! :tada: Nice work

**Comment by fregante** [comment]
Glad it fixed it! I’m surprised it never updated, did your browser disable the autoupdates? RGH updates pretty often and that’s because GitHub does too, so it’s best to always have the latest version.
