### ISSUE TITLE
Support more filenames in `link-to-changelog-file`

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#3999]
While `CHANGELOG` is one way people call changelog files, it is not the only popular one out there.
I've personally seen [`CHANGES`](https://github.com/sphinx-doc/sphinx/), [`NEWS`](https://github.com/pypa/pip), and [`HISTORY`](https://github.com/psf/requests) used often too.

I think that [names supported by dependabot](https://github.com/dependabot/dependabot-core/blob/e7c9f44410c16a8ef3da41bda949d2c110c3ed0e/common/lib/dependabot/metadata_finders/base/changelog_finder.rb#L20) are a good reference on what names are used in the wild.

**Comment by tooomm** [comment]
I assume in the example repo https://github.com/pypa/pip, this feature is supposed to link to https://github.com/pypa/pip/blob/master/NEWS.rst, not https://github.com/pypa/pip/tree/master/news?

**Comment by jack1142** [comment]
Yeah, it should be linking to a changelog file, not the folder with changelog fragments.
It seems that this has been mentioned in https://github.com/sindresorhus/refined-github/pull/4005#issuecomment-782845287, but I'm not sure if there was a reason for this to not be updated.

If detecting folders was intentional, I think the extension should *at least* prioritize the files but I'm not sure what was the original intention here.

**Comment by yakov116** [comment]
> If detecting folders was intentional, I think the extension should _at least_ prioritize the files but I'm not sure what was the original intention here.

👍 

https://github.com/sindresorhus/refined-github/blob/d5b8ecf08b6a5d63127c2e4308da71383ec5c63e/source/features/link-to-changelog-file.tsx#L26

Adding a simple `.reverse()` should work here

https://github.com/sindresorhus/refined-github/blob/d5b8ecf08b6a5d63127c2e4308da71383ec5c63e/source/features/link-to-changelog-file.tsx#L43

It might work ⬆️ too but I am not sure.

**Comment by fregante** [comment]
Unfortunately a reverse would also catch `changelog.3.md` over `changelog.md`

Maybe we should just filter both by type, then only match exactly `*` and `*.*`, never `*.*.*`

**Comment by yakov116** [comment]
Api might be simple to do that. DOM not so much, It would require another select to check the icon

**Comment by fregante** [comment]
Select the icon first, get the filename from there.
