### ISSUE TITLE
Org switcher disappears

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/refined-github#4]
Not sure if I'm doing something wrong, but the organization switcher seems to have disappeared after enabling.

![screen shot 2016-02-15 at 11 37 37](https://cloud.githubusercontent.com/assets/885648/13057332/9cb00b28-d3d8-11e5-9b5a-0e88e3b9bbda.png)

**Comment by sindresorhus** [comment]
Weird. Not all the overrides are applied either. Can you check the console whether there's any errors?

**Comment by Qix-** [comment]
None.

![screen shot 2016-02-15 at 11 59 41](https://cloud.githubusercontent.com/assets/885648/13057784/a0f912ee-d3db-11e5-8889-4d1dff48461e.png)
