### ISSUE TITLE
Click to edit readme from the main repo page

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#40]
@hkdobrev suggested in https://github.com/sindresorhus/refined-github/pull/33#issuecomment-189283145.

-

Usually you have to click into the readme from the file browser first.

I think we could have an edit button on the top right. Maybe only shows on hover?

**Comment by sindresorhus** [comment]
I think @stephenplusplus wanted something like this in the past too if I remember correctly.

**Comment by stephenplusplus** [comment]
Yes (good memory, sheesh), this would be awesome! The on-hover sounds good to me, maybe an icon: :memo: or :pencil2:, or just a button is cool too.

**Comment by sindresorhus** [comment]
Cool. Yeah, we'll use the pencil icon GitHub provides.

```svg
<svg class="octicon octicon-pencil" height="16" version="1.1" viewBox="0 0 14 16" width="14"><path d="M0 12v3h3l8-8-3-3L0 12z m3 2H1V12h1v1h1v1z m10.3-9.3l-1.3 1.3-3-3 1.3-1.3c0.39-0.39 1.02-0.39 1.41 0l1.59 1.59c0.39 0.39 0.39 1.02 0 1.41z"></path></svg>
```

**Comment by paulmolluzzo** [comment]
PR coming in 3... 2...
