### ISSUE TITLE
JavaScript error on Compare screen

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#400]
If you navigate to the empty Compare screen, https://github.com/sindresorhus/refined-github/compare/, you'll get the following JS error from the plugin.
```
content.js:446 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at gitHubInjection (content.js:446)
    at gitHubInjection (gh-injection.js:40)
    at HTMLDocument.document.addEventListener (content.js:417)
```

The code is assuming we always find an element with `$('.js-discussion, #files')`, but in the case of a blank comparison, we do not.
```
new MutationObserver(removeDiffSigns).observe($('.js-discussion, #files')[0], {childList: true, subtree: true});
```

Easy enough fix that I can tackle tomorrow if no one beats me to it.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/sindresorhus/refined-github/pull/402.
