### ISSUE TITLE
⚠ grouped tabs becoming 'New Tab' (loss of content) with Firefox 86 and Simple Tab Groups

### ISSUE THREAD

**Issue by grahamperrin** [sindresorhus/refined-github#4001]
Spun off from https://github.com/Drive4ik/simple-tab-groups/issues/779#issuecomment-782650906

If a group with more than one tab is opened into a new window whilst Refined GitHub is enabled: 

* tabs that are not loaded are lost when the window closes. 

https://user-images.githubusercontent.com/192271/108603525-4e446980-73a0-11eb-8834-b5500166dea9.mp4

**Comment by fregante** [comment]
I don’t know what I’m looking at. Refined GitHub does not interact with tabs, we don’t have the `tabs` permission so we can only ever touch GitHub tabs.

**Comment by grahamperrin** [comment]
Interesting. I wonder why the bug occurs when Refined GitHub is enabled …

**Comment by fregante** [comment]
It happens with any other extension enabled, as you noticed since you opened issues in 5 other repos.
