### ISSUE TITLE
Specify Personal Access Token Requirements For Features

### ISSUE THREAD

**Issue by Tbhesswebber** [sindresorhus/refined-github#4007]
It's bad practice to freely give permissions to apps.  As such, it would be incredibly valuable to tag features with the level of access required and to provide documentation for the permissions necessary to enable all features.

**Comment by yakov116** [comment]
We give it. Just open the options of the extensions. Or do a simple issue search

**Comment by Tbhesswebber** [comment]
Ah, thanks! I was looking in the README, which seemed the intuitive place for it to be. Sorry for the duplicate!
