### ISSUE TITLE
Triple-equals font doesn't look very good on lower dpi screens

### ISSUE THREAD

**Issue by SCdF** [sindresorhus/refined-github#401]
To me this triple equals makes me think my eyes have lost focus: 
![image](https://cloud.githubusercontent.com/assets/583851/25727386/ddd99e1a-3120-11e7-823b-a8d2841ab501.png)

If I zoom in a bunch, it looks how I presume it's supposed to look:
![image](https://cloud.githubusercontent.com/assets/583851/25727398/f2bede4e-3120-11e7-8880-5b91100eb96f.png)

This on a Dell U3415W, which according to the internet has a DPI of ~109. While this is low for a laptop display (a 13" macbook is 226), for an external monitor it's not too bad.

**Comment by jgierer12** [comment]
This issue is specific to [FiraCode](https://github.com/tonsky/FiraCode). I tried changing the `text-rendering` which didn't help, so I don't think we can do much about it.
