### ISSUE TITLE
bypass-checks doesn't work any more.

### ISSUE THREAD

**Issue by dgeelen-uipath** [sindresorhus/refined-github#4015]
A similar previous report is #3418, although there it still worked sometimes.

This used to work a while (some months) ago, but now it always opens the 'details' page.
URL where the bug appears: https://github.com/<organisation>/<project>/pull/1216
Screenshot: ![image](https://user-images.githubusercontent.com/59690011/108823612-f6387d80-75c0-11eb-8259-a17d506e139f.png)
As per my reading of #3418 this URL should go directly to CI.

There is a link on the checks page that can be followed, which goes to `https://<organisation>.visualstudio.com/<GUID>/_build/results?buildId=<number>`:
![image](https://user-images.githubusercontent.com/59690011/108824155-b02fe980-75c1-11eb-9d53-af342acb7e5b.png)

The HTML for this link looks like this, if it helps:
```
<div class="mx-4 mb-4">
        <a class="text-small text-gray-light" target="_blank" rel="noopener noreferrer" data-hydro-click="{&quot;event_type&quot;:&quot;check_suite.external_click&quot;,&quot;payload&quot;:{&quot;check_suite_id&quot;:2102516452,&quot;check_run_id&quot;:1959824889,&quot;link_url&quot;:&quot;https://<organisation>.visualstudio.com/<GUID>/_build/results?buildId=<number>&quot;,&quot;link_text&quot;:&quot;View more details on&quot;,&quot;originating_url&quot;:&quot;https://github.com/<organisation>/<project>/pull/1216/checks?check_run_id=1959824889&quot;,&quot;user_id&quot;:59690011}}" data-hydro-click-hmac="<gibberish>" href="https://<organisation>.visualstudio.com/<GUID>/_build/results?buildId=<number>">
          <svg class="octicon octicon-link-external mr-2" viewBox="0 0 16 16" version="1.1" width="16" height="16" aria-hidden="true"><path fill-rule="evenodd" d="M10.604 1h4.146a.25.25 0 01.25.25v4.146a.25.25 0 01-.427.177L13.03 4.03 9.28 7.78a.75.75 0 01-1.06-1.06l3.75-3.75-1.543-1.543A.25.25 0 0110.604 1zM3.75 2A1.75 1.75 0 002 3.75v8.5c0 .966.784 1.75 1.75 1.75h8.5A1.75 1.75 0 0014 12.25v-3.5a.75.75 0 00-1.5 0v3.5a.25.25 0 01-.25.25h-8.5a.25.25 0 01-.25-.25v-8.5a.25.25 0 01.25-.25h3.5a.75.75 0 000-1.5h-3.5z"></path></svg>View more details on Azure Pipelines
</a>      </div>
```
This does seem to include the `$('[data-hydro-click*="check_suite.external_click"]')` mentioned on #3418.

Current version of GitHub Refined is 21.2.23, Firefox 85.0.2 (64-bit)

**Comment by fregante** [comment]
> URL where the bug appears: [github.com](https://github.com/)/[/pull/1216](https://github.com/sindresorhus/refined-github/pull/1216)

Can you find and post a real, public URL?

**Comment by dgeelen-uipath** [comment]
I've tried to look for a public link, but curiously it seems like this does work for public repositories?? E.g. on `https://github.com/Azure/azure-powershell/pull/14304` the details links are linked directly to azure for me... However in my private repo it still doesn't work and links to `https://github.com/<organisation>/<project>/pull/1216/checks?check_run_id=1968477386` instead. Is there something I can look at to help debug this?

Working links for me on public repositories:
https://github.com/Azure/azure-powershell/pull/14304
https://github.com/microsoft/azure-pipelines-tasks/pull/14445
https://github.com/vercel/next.js/pull/11408
https://github.com/jet/XRay/pull/3
https://github.com/commitizen/cz-cli/pull/808

**Comment by fregante** [comment]
Do you see any errors in the console? In the Network tab of the developer tools there should also be a `fetch` to that URL ending i `check_run_id=*********`

**Comment by dgeelen-uipath** [comment]
The only thing that stands out is an error that is thrown on the private repo page, but not on the public one:
![image](https://user-images.githubusercontent.com/59690011/109172031-a0133800-7782-11eb-858d-da5ebda9a0cf.png)

There doesn't appear to be a network request to `check_run_id` as far as I can tell.

**Comment by fregante** [comment]
Can't replicate. I'd probably accept a PR if you sent it.
