### ISSUE TITLE
`align-issue-labels` is broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4026]
URL: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

<img width="682" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/109341986-d4453200-7830-11eb-973d-bf4f8b5f8719.png">

I'm disabling it via hotfix.

**Comment by AlCalzone** [comment]
I'm not sure if this is the same problem, but the PR list is somewhat broken too. Double checkboxes, no color highlight for "review required".
![grafik](https://user-images.githubusercontent.com/17641229/109365134-c2937700-7890-11eb-9f17-deded2e5144f.png)

**Comment by cheap-glitch** [comment]
@AlCalzone I'm not seeing the doubled checkboxes. Can you make sure this is caused by RGH and if yes, provide an URL?

**Comment by fregante** [comment]
I don’t have any other extensions and I’m see it (Safari, but the user above likely a different browser)

**Comment by fregante** [comment]
Checkbox feature disabled via hotfix as well

**Comment by AlCalzone** [comment]
In my case it's Firefox and no other extensions.
