### ISSUE TITLE
option: enable message "_user_ wants to merge _n_ commits into _branch_ from _branch_"

### ISSUE THREAD

**Issue by lsloan** [sindresorhus/refined-github#4027]
When GitHub is used without refined-github, a message like this appears near the top of each pull request:

> _user_ wants to merge _n_ commits into _branch_ from _branch_

For example, PR #4016 in this repo shows:

> yakov116 wants to merge 2 commits into main from markEmAll

When refined-github is used, that message is reduced to:

> from _branch_

Again, for #4016, it shows:

> from markEmAll

For some PRs I was working with, I wanted to be certain they were opened using the correct destination branch, but it isn't shown.

I looked through the extension options to find one that might enable the original message, but I couldn't find one.  Please add an option to enable this message.

**Comment by fregante** [comment]
All of that content is already on the page: https://github.com/sindresorhus/refined-github/issues/3089

The feature `clean-conversation-headers` can already be disabled, but I don't know why you would want duplicate information on the page.

**Comment by fregante** [comment]
> using the correct destination branch, but it isn't shown.

The default branch isn't shown, it's the default.

**Comment by lsloan** [comment]
Thank you for the pointer and the information.

I spent an hour searching through the extension options for phrases and words like "branch", "merge", "commits", "wants", etc.

**Comment by fregante** [comment]
Thanks, I updated the description of the feature. This is a recurrent issue
