### ISSUE TITLE
`hide-comments-faster` is broken on <700px viewports

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4032]
1. Resize your window to be 700px wide or less
1. Visit an issue or PR on a repo you're a collaborator to / owner of
2. Open its context menu
3. Select "Hide comment"
4. Notice:

<img width="198" alt="Screen Shot 8" src="https://user-images.githubusercontent.com/1402241/109400060-1db67f80-790c-11eb-8741-fa5222522ed2.png">

This is probably due to a mobile-only flex class. The class should be removed

**Comment by carl-evans** [comment]
Hey fregante. Just wanted to check is this what you are trying to achieve?
<img width="794" alt="Screenshot 2021-02-27 at 21 28 50" src="https://user-images.githubusercontent.com/32574150/109400838-e7e0bd80-7942-11eb-88c8-8dea7fe6ccd6.png">

**Comment by fregante** [comment]
Yes. It works above 700px, but not below

**Comment by fregante** [comment]
![gif](https://user-images.githubusercontent.com/1402241/109400901-09c14c80-7911-11eb-9eaf-0093f16992b2.gif)
