### ISSUE TITLE
Method definition popover position

### ISSUE THREAD

**Issue by dnicolson** [sindresorhus/refined-github#4033]
All extension are disabled except for Refined GitHub.
https://github.com/no2chem/bigint-buffer

<img width="1607" alt="Screen Shot 2021-02-27 at 22 01 02" src="https://user-images.githubusercontent.com/2276355/109400178-7b1bf200-7947-11eb-9c4f-64f53a02206c.png">

Clicking on `toBufferBE` shows the method definition popover near the bottom of the window. Disabling Refined GitHub results in the popover appearing near the `toBufferBE` text.

Chrome 88.0.4324.192
Refined GitHub 21.2.23

**Comment by fregante** [comment]
Confirmed. No idea what's causing it. #2586 would have been useful again.

**Comment by mobilutz** [comment]
Out of curiosity I looked into this bug. And I think I found the problem.
It is a CSS `position: relative` that is added here:
https://github.com/sindresorhus/refined-github/blob/main/source/features/hide-readme-header.css#L2-L4

When I manually set `position: initial` on the `#readme` HTML element, the position of the popover is correct.
