### ISSUE TITLE
Use ES2015 modules when available

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#404]
https://twitter.com/addyosmani/status/859296190323597313

**Comment by paulmolluzzo** [comment]
Yeah, I'm stoked for this to make it to dev/stable.

What channel of Chrome are we waiting for? Does it have to be in stable? @sindresorhus do you have any analytics from the web store that tells us what version users are on?

**Comment by jgierer12** [comment]
Great article on this: https://jakearchibald.com/2017/es-modules-in-browsers/

**Comment by sindresorhus** [comment]
Yes. It has to be stable Chrome, but we can do it as soon as it's out. Chrome is auto-upgraded, so we can always target latest.

**Comment by bfred-it** [comment]
Don't forget Firefox! #403 

Let's keep an eye on this: https://caniuse.com/#feat=es6-module

**Comment by sindresorhus** [comment]
One thing we haven't considered is that even with ES2015 module support, we will not be able to use npm packages that have dependencies. That is very inconvenient. We will also have to use the full path to the JS files.

**Comment by bfred-it** [comment]
I'm not sure how extensions will handle es modules but I assume you do not need to list them there; if you did, they wouldn't be loaded as modules. 

About node_modules: yes, using them will not be very convenient. There would still need to be some bundler that takes all of them out of that folder. 

So yes, maybe it's best to just go with a regular bundler. 

I used rollup before: https://github.com/npmhub/npmhub/pull/55

**Comment by bfred-it** [comment]
If the config in https://github.com/npmhub/npmhub/pull/55 looks good to you I'll open a PR

**Comment by sindresorhus** [comment]
@paulmolluzzo @hkdobrev ⬆️ Thoughts?

**Comment by paulmolluzzo** [comment]
If we can't use npm packages with dependencies then we're going to be pretty limited I think. I'm also a little concerned that if we add in a lot of busywork to use npm package then new contributors might get overwhelmed when thinking about starting a PR.

If @bfred-it wants to open a PR, it looks like the config in https://github.com/npmhub/npmhub/pull/55 makes sense, but some documentation could be worthwhile to include. We might even want to add a `pre-commit` hook to ensure the build step works, or include it in the tests.

We have a fair amount of new GH users contributing, which is awesome, and I'd like to keep the barrier to entry manageable. If we can get the benefits of the vast library of npm packages while keeping the rest, then I'm on board.

**Comment by bfred-it** [comment]
I can work on the build and the docs, but I'd need help with the tests and the git hook (which afaik is not added automatically unless we add something like [`husky`](https://github.com/typicode/husky))

I'll do it once most of the current PRs are merged

**Comment by bfred-it** [comment]
@paulmolluzzo how do df5290024c68533259d2fd7000f1c0d81516ba8e and 884fdfc41e8e08459d80e658828bc29a7fb76a5d look regarding the docs+tests?

**Comment by paulmolluzzo** [comment]
> @paulmolluzzo how do df52900 and 884fdfc look regarding the docs+tests?

Looks good to me, thanks! 👍
