### ISSUE TITLE
PR approval counts not visible anymore

### ISSUE THREAD

**Issue by mobilutz** [sindresorhus/refined-github#4043]
In the v21.2.23 the `PR approval count` is not displayed correctly anymore:
![Screenshot 2021-03-01 at 12 29 51](https://user-images.githubusercontent.com/491877/109491483-e837a080-7a89-11eb-841e-de15a6149cf5.png)

This is how it looked until a couple of days ago (don't know exactly when it "broke")
![Screenshot 2021-03-01 at 16 25 42](https://user-images.githubusercontent.com/491877/109518809-e500dc80-7aaa-11eb-9756-ea838edc6a50.png)

This is the CSS that should do this:
https://github.com/sindresorhus/refined-github/blob/main/source/features/pr-approvals-count.css

I am running this setup:
* MS Edge `Version 88.0.705.81 (Official build) (64-bit)`
* Refined GitHub `21.2.23`

There is no error in the JS-console that correlates to this. Although I do see some other non-related errors, but I do not want to bring them up here. **I am just adding the errors here, to show what they are!!!**
![Screenshot 2021-03-01 at 12 32 57](https://user-images.githubusercontent.com/491877/109491748-482e4700-7a8a-11eb-9e00-756b26b7807f.png)

PS:
I disabled the features that are throwing the JS-console errors:
* `clean-conversation-filters`
* `highlight-non-default-base-branch`

Outcome is still the same - approval count not displayed.

PPS: 
Source of this feature: https://github.com/sindresorhus/refined-github/pull/816

**Comment by yakov116** [comment]
What URL are you seeing the errors?

**Comment by mobilutz** [comment]
> What URL are you seeing the errors?

This is the `Pull Requests` URL `.../pulls`. I currently only work on a private repo, so providing the full URL does not help.

**Comment by yakov116** [comment]
But I dont see any errors on https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

**Comment by cheap-glitch** [comment]
This was fixed by #4021 and should be released soon.

**Comment by mobilutz** [comment]
Thanks @cheap-glitch - I am now on v21.3.1 and it works again.

I though that the release with these changed happend already before I created the ticket.

**Comment by fregante** [comment]
No worries, thanks for the detailed report Lutz!
