### ISSUE TITLE
Add `)` and `]` to `one-key-formatting`

### ISSUE THREAD

**Issue by Geeyun-JY3** [sindresorhus/refined-github#4047]
Add right parenthesis `)` and right square bracket `]` to `one-key-formatting`.

BTW, I don’t know whether the curly quotation marks like single quotation marks `‘’` and double quotation marks`“”` should be added to this feature, because they aren’t commonly used as Markdown symbols. But sometimees we do use them to wrap selected text.

URL: any page

**Comment by fregante** [comment]
Why? You can achieve the same result with just ( and [ respectively.

**Comment by Geeyun-JY3** [comment]
> You can achieve the same result with just ( and [ respectively.

I know. Just wanna make this feature better. Sometimes I would accidentally press `)` and `]`when I want to press  `(` and `[`. Do we use these two symbols to do other things besides pairing them?

**Comment by fregante** [comment]
I just tried in a few editors, none of them handle the closing character this way. Since this feature exists to match how editors handle the existing characters, we shouldn’t handle these either

**Comment by fregante** [comment]
We could handle the fancy quotes though, even if they’re kind of rare

**Comment by Geeyun-JY3** [comment]
> I just tried in a few editors, none of them handle the closing character this way. Since this feature exists to match how editors handle the existing characters, we shouldn’t handle these either.

Fine. It looks reasonable.
Remeber to update the description. `(`, `{`, `“`, `‘` aren't mentioned.
