### ISSUE TITLE
Replace `Previously part of Refined GitHub` section in readme with a PR list link

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4057]
Instead of keeping a list in the readme (which nobody reads because the readme is already hundreds of lines long) we can just a link to: https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+in%3Atitle+is%3Amerged+-label%3Ameta+drop+feature

Separately, it might be worth going through some old PRs to ensure that they have the "drop feature" in the title.

**Comment by yakov116** [comment]
Can we make a new label called "implemented by github"?

**Comment by fregante** [comment]
hmmm I think that instead of pointing to features that specifically have been added by GitHub, I'd like to keep a list of _all_ the features that have been dropped. Sometimes we just drop features for other reasons.

**Comment by sindresorhus** [comment]
Sounds good, but I think we should do the "implemented by GitHub" label.

**Comment by fregante** [comment]
Same link as I proposed + "implemented by GitHub" to highlight them in such a list?

**Comment by sindresorhus** [comment]
I would do two links. "Implemented by GitHub" and "Dropped features".
