### ISSUE TITLE
Dark Mode: 404 Github Pages have wrong color with Dark Mode

### ISSUE THREAD

**Issue by oscard0m** [sindresorhus/refined-github#4062]
### Example:
https://github.com/oscard0m/a

### Screenshot:
![image](https://user-images.githubusercontent.com/2574275/110130044-e42cbb00-7dc8-11eb-9122-8f8b0d69af80.png)

### More Details:
https://github.com/github/feedback/discussions/3482#discussioncomment-433368

**Comment by busches** [comment]
You can disable the feature, but this is working as designed. See the comments in the original PR https://github.com/sindresorhus/refined-github/pull/4048

**Comment by oscard0m** [comment]
Oh sorry! I didn’t know this was a feature. Sorry to not find it in the quick search I did before openinn the issue.

And thanks for the quick reply! :)
