### ISSUE TITLE
Hide/rename “Only show unresolved comments” on issues

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#4063]
I’m using `conversation-activity-filter` in the recently released Safari extension.

<img width="472" alt="" src="https://user-images.githubusercontent.com/25517624/110158908-f81bf100-7db7-11eb-8f9d-e1c15f5960dd.png">

It shows an option for “Only show unresolved comments” ~even though there’s no concept of “resolved comments” on issues (as far as I know)~

Correction: this choice also hides hidden comments — maybe the text should change to clarify that (perhaps only for issues)?

**Comment by fregante** [comment]
GitHub calls them hidden comments, which include a “resolved” status (among others), but “Only show unhidden comments” is a little mind-bending.

I’m not sure reversing it would help or be just as confusing: “Hide hidden comments”

**Comment by j-f1** [comment]
* Show all
* Hide events
* Hide events and collapsed comments

.
* Show all comments & events
* Show all comments
* Show uncollapsed comments

**Comment by fregante** [comment]
Yeah `collapsed` is the next logical word, but it's not used by GitHub. Is it clear what collapsed/uncollapsed comment is?

If yes, it could work:

> * Show all activity
> * Hide events
> * Hide events and collapsed comments

**Comment by j-f1** [comment]
I think it’s fairly clear because the comments are still shown in a shorter (ie collapsed) manner (not entirely hidden), and because the icons GitHub uses for toggling such comments is frequently used<sup>[_citation needed_]</sup> to indicate “expanded“ and “collapsed” states.

**Comment by fregante** [comment]
Oh no, this guy is looking at me

<img width="105" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/110179239-530c1300-7dcd-11eb-9cd6-83534fe27480.png">


> I also think that in the context there isn’t anything else it could be referring to.

<img width="241" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/110179284-69b26a00-7dcd-11eb-8c8e-48fa84586e97.png">

**Comment by fregante** [comment]
<img width="117" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/110179391-99fa0880-7dcd-11eb-833d-3d06cae1cadb.png">

Gee who implemented this feature?
