### ISSUE TITLE
Multiple eye icons

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4067]
![img](https://salvage.is-inside.me/GDqWGVMv.png)
https://github.com/harryfei/which-rs/pull/30

This only happens occasionally.

**Comment by ahmed2m** [comment]
Reproduction step navigate in and out of the issue/pr

https://user-images.githubusercontent.com/26524089/110222889-5a6f1180-7ede-11eb-9398-a6d104dfcc97.mp4

**Comment by Milo123459** [comment]
Yes. If you don't mind me asking, how did you get that bugs tab?

**Comment by ahmed2m** [comment]
> Yes. How can you turn on that "bugs" tab system?

It's a feature in this very extension, `bugs-tab`

**Comment by fregante** [comment]
This is strange, I saw that only once, and then I couldn’t replicate it. The code has deduplication logic but it seems to fail at times in this case.

**Comment by kidonng** [comment]
I found the cause: for some reason GitHub doesn't trigger `pjax:start`, so `deinit` doesn't run.

**Comment by fregante** [comment]
Feature disabled via hotfix. It'll be re-enabled in the next version sometimes this week
