### ISSUE TITLE
`hide-issue-list-autocomplete` doesn't work on global PR search pages

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4079]
1. Visit https://github.com/pulls
2. Try to trigger the autocomplete on the field on the right

<img width="998" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/110422215-87e5c780-8064-11eb-8719-bdcf4196904e.png">

**Comment by yakov116** [comment]
I just tried it working for me in chrome

**Comment by fregante** [comment]
Indeed I see an autocomplete attribute on the form, but the autocomplete is still shown for me until I move it to the field itself

**Comment by fregante** [comment]
🤷‍♂️ can't replicate anymore
