### ISSUE TITLE
Reduce `batch-open-conversations` to `open-all-conversations`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4085]
It seems to me that this feature doesn’t make any sense. It doesn’t help that it’s a pretty long feature too. 

![](https://user-images.githubusercontent.com/1402241/38084752-4820b0d8-3378-11e8-868c-a1582b16f915.gif)

In the demo gif we have, it literally shows you can open 2 tabs in 3 clicks… but why not just ctrl-click the links?

I think the feature should only be “open all in tabs” and disregard any selections.

**Comment by kidonng** [comment]
I wanted to use this feature for several times and just realized it was dropped. Here's a bookmarklet for some compensation:

```js
javascript:document.querySelectorAll('.js-issue-row.selected a.Link--primary').forEach(i => window.open(i.href))
```

> but why not just ctrl-click the links

That case seems to be exaggerating. It is useful for reverse selecting (open all but some, "just go close those unnecessary tabs manually" is not the answer), or when you want to both triage (what the select box _is_ used for) and open issues at the same time.
