### ISSUE TITLE
Release notes please

### ISSUE THREAD

**Issue by inspector71** [sindresorhus/refined-github#4088]
Hi

Would like to consider contributing / donating however cannot without consistent release notes as I do not believe in automatic upgrades always invariably being an improvement, so I manually check notes first.

Nonetheless, thanks for all your hard work to even produce this add-on.

**Comment by busches** [comment]
Releases and notes are automatically generated, does this meet your need?
https://github.com/sindresorhus/refined-github/releases

**Comment by fregante** [comment]
Yes, as @busches mentions, we do have release notes for every release, just not in the extension store since there’s no API for that.

**Comment by inspector71** [comment]
Thanks. I was looking for them in the Release Notes tab available, 
seemingly if extensions provide notes (otherwise hidden rather than 
perhaps greyed out) with releases.

Tab example:

https://i.imgur.com/74QsaDg.png

... vs:

https://i.imgur.com/iqtbhrS.png

uBlock Origin even curates highlights, with hyperlinks directly to 
Issues, along with including a link to all changes for the ultra curious 
:) ...

https://i.imgur.com/tcqyATG.png

That might be considered, perhaps, the 'gold standard' of what I can 
recall seeing as Release Notes over the years.

Often they are much less meaningful and useful :(

Yep, those release notes alongside the actual releases on github itself 
are great. That said, unless users go outside the addons.mozilla.org 
(AMO) funnel / store, will they see them?

Suspect the Release Notes tab might appear with just a small change to 
the extension's manifest? Hmmmm

Grrr, nothing immediately jumps out here:

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json

thanks for the hard work to compile documentation and notes. I do 
understand it is arguably an extra overhead to actual development of the 
'product'.

------ Original Message ------
From: "Scott Busche" ***@***.***>
To: "sindresorhus/refined-github" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" 
***@***.***>
Sent: 12/03/2021 1:14:45 PM
Subject: Re: [sindresorhus/refined-github] Release notes please (#4088)

**Comment by inspector71** [comment]
At least link to your github site in the addon description.

------ Original Message ------
From: "Federico" ***@***.***>
To: "sindresorhus/refined-github" ***@***.***>
Cc: "inspector71" ***@***.***>; "Author" 
***@***.***>
Sent: 12/03/2021 2:00:53 PM
Subject: Re: [sindresorhus/refined-github] Release notes please (#4088)

**Comment by fregante** [comment]
> At least link to your github site in the addon description.

Good point, the Mozilla Addons page was rather skimp on details. I added the entire readme there and linked to the release notes: https://addons.mozilla.org/en-US/firefox/addon/refined-github-/

> I do understand it is arguably an extra overhead to actual development of the 'product'.

That's why most extensions don't have it. If you like the free extension please consider contributing via [bug fixing](https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug), [sponsorships](https://github.com/sponsors/fregante) or by [funding specific issues](https://github.com/sindresorhus/refined-github/issues/2730).

**Comment by inspector71** [comment]
> 
> 
> > At least link to your github site in the addon description.
> 
> Good point, the Mozilla Addons page was rather empty. I added the entire readme there and linked to the release notes: [addons.mozilla.org/en-US/firefox/addon/refined-github-](https://addons.mozilla.org/en-US/firefox/addon/refined-github-/)

Sweet :)
 
> > I do understand it is arguably an extra overhead to actual development of the 'product'.
> 
> That's why most extensions don't have it. 

Weeeell, would beg to differe there. Most of my extensions have Release Notes. However, that is of course only my experience and the quality thereof does vary wildly.

Surprising there is not an obvious way to pump a git commit log into an extension's packaging. Or, simply, paste a link to a git (or other version control system) commit log in the extension's release file (is that still manifest.json?).
