### ISSUE TITLE
[support] How to disable the feature `night-not-found`

### ISSUE THREAD

**Issue by oscard0m** [sindresorhus/refined-github#4091]
Looking for the feature in extension's option, I don't find it: `night-not-found `

![image](https://user-images.githubusercontent.com/2574275/110942558-3d04d200-833a-11eb-8002-e5f3bb77bb27.png)

Is there a parent feature to disable it maybe?

_Originally posted by @busches in https://github.com/sindresorhus/refined-github/issues/4062#issuecomment-791467657_

**Comment by sindresorhus** [comment]
Why are you trying to disable it? Just curious.

**Comment by oscard0m** [comment]
> Why are you trying to disable it? Just curious.

I see it too dark in my opinion... I prefer the default one.

**Comment by fregante** [comment]
You can find the selectors in its CSS files and use `filter: none !important` to disable the feature in the options page.

**Comment by oscard0m** [comment]
> You can find the selectors in its CSS files and use `filter: none !important` to disable the feature in the options page.

Nice! Thanks @fregante

**Comment by oscard0m** [comment]
> You can find the selectors in its CSS files and use `filter: none !important` to disable the feature in the options page.

Nice! Thanks @fregante
