### ISSUE TITLE
Hide duplicate query from header search field

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4095]
Like https://github.com/sindresorhus/refined-github/issues/1253

<img width="459" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/111014315-c7642a80-8368-11eb-87c8-61a5cef7ae8f.png">

Not sure if this is a bug or if that feature was only added to global results pages.

Test URLs:

- https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug
- https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3Afregante+archived%3Afalse+sort%3Aupdated-desc (here it works)

**Comment by fregante** [comment]
On the global page it works:

<img width="858" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/111014377-fed2d700-8368-11eb-956b-5bb95e315dda.png">

**Comment by fregante** [comment]
I think we only need to extract this function into its own feature https://github.com/sindresorhus/refined-github/blob/6a1fe774f53f233b6b525b1c81339a9b357a7cc9/source/features/sort-conversations-by-update-time.tsx#L9-L11

**Comment by yakov116** [comment]
I cannot reproduce in chrome

**Comment by fregante** [comment]
<img width="671" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/111409146-01e90280-869c-11eb-83d7-40c583332317.png">

**Comment by fregante** [comment]
It's a GitHub feature, it's in the received HTML

<img width="457" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/111409284-47a5cb00-869c-11eb-8154-6752197ab320.png">
