### ISSUE TITLE
Show a button for the star history of the repo in the stargazers page

### ISSUE THREAD

**Issue by ouuan** [sindresorhus/refined-github#4097]
I want to have a button that links to [https://star-history.t9t.io/#owner/repo](https://star-history.t9t.io/#sindresorhus/refined-github) in the [stargazers](https://github.com/sindresorhus/refined-github/stargazers) page. It's similar to [`useful-forks`](https://github.com/sindresorhus/refined-github/issues?q="useful-forks").

![screenshot](https://user-images.githubusercontent.com/30581822/111034893-a2e47d00-8452-11eb-9dab-1839c7d41559.png)

**Comment by kidonng** [comment]
While I can see this is useful to repo owners/collaborators, it may not be [suitable to include in this extension](https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382) given it so trivial you can simply use a bookmarklet:

```
javascript:window.open(`https://star-history.t9t.io/#${location.pathname.split('/').slice(1, 3).join('/')}`)
```

Or if you prefer a button instead, you can use [a user script](https://github.com/kidonng/cherry/blob/master/scripts/github-star-history.user.js) I just rolled up:

![image](https://user-images.githubusercontent.com/44045911/111070242-b1db3600-850b-11eb-80f0-bec0e6c1c2c5.png)
