### ISSUE TITLE
Special formatting for Pull Request trains

### ISSUE THREAD

**Issue by igorlvicente** [sindresorhus/refined-github#4102]
Where it would be used: https://github.com/pulls and in the tab Pull Requests of a repo.

I use Pull Request trains for development.
That is useful to split the task into minor parts to facilitate pull request reviews.
So, for example (a bad example), if I would create a CRUD and I would like to create 4 pull request (one for each letter), this is how the PR train would look like:
`<base branch>` <- `crud_c` <- `crud_r` <- `crud_u` <- `crud_d`

When this happens, I would like some visual to make it easier to recognize these PR trains in the list.
Something like this:
```
- Pull request of C of CRUD
  |- Pull request of R of CRUD
     |- Pull Request of U of CRUD
     |  |- Pull Request of D of CRUD
     |- Pull request of fixes on R of CRUD
```

**Comment by fregante** [comment]
Unfortunately this is just one of the many complex workflows available and it'd probably require constant tweaking to adjust to everyone's preferences and internal uses.

As such, it can't be part of Refined GitHub
