### ISSUE TITLE
Use 1k instead of 1000 in `bugs-tab`

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4107]
The bugs count should format like the issues count.
![e](https://salvage.is-inside.me/gkr2km5b.png)

**Comment by yakov116** [comment]
Please follow the issue template

**Comment by Milo123459** [comment]
[Here](https://github.com/microsoft/vscode)

**Comment by yakov116** [comment]
What do you want changed?

**Comment by Milo123459** [comment]
The 1,037 should be 1.3K, like how the issues tab is formatted

**Comment by fregante** [comment]
Indeed this happens as soon as they hit 1000. I think it didn’t before

Example repo with 1000 issues: https://github.com/nodejs/node/issues

**Comment by fregante** [comment]
Indeed:

![00E680F6-324B-4B13-BA54-67A566C2D1AB](https://user-images.githubusercontent.com/1402241/111247026-ecf16e00-85cc-11eb-88ec-3333ac579670.png)
