### ISSUE TITLE
Draft icon looks bad

### ISSUE THREAD

**Issue by FoxtrotSierra6829** [sindresorhus/refined-github#4112]
The extension somehow modifies the draft icon in the PR list to this
**Before**
![grafik](https://user-images.githubusercontent.com/50082450/111365336-a9f9ce00-8692-11eb-8e14-d2e29d69abd9.png)

I then had to add this to custom CSS:
```
.js-issue-row [aria-label="Open draft pull request"] svg {
stroke: none !important;
fill: var(--color-text-tertiary) !important;
}
```
**After**
![grafik](https://user-images.githubusercontent.com/50082450/111365251-8df62c80-8692-11eb-8196-478776ba32ba.png)

After should be the default behavior though

**Comment by fregante** [comment]
This is a feature: https://github.com/sindresorhus/refined-github/blob/main/source/features/emphasize-draft-pr-label.css

This is the reasoning: https://github.com/sindresorhus/refined-github/issues/2450

**Comment by fregante** [comment]
Alternative styles suggestions welcome, but we're not going back to the default because the difference/contrast is just so little

<img width="81" alt="Screen Shot 3" src="https://user-images.githubusercontent.com/1402241/111373819-faa50300-8661-11eb-812f-e0331f264c5c.png"> 

Compared to:

<img width="81" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/111373822-fbd63000-8661-11eb-876f-32e12f5091e7.png">

**Comment by fregante** [comment]
Maybe the style can be tweaked (via low-dpi media query) to look better on low-dpi displays. Here are the zoomed in screenshots you posted

<img width="119" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/111374102-553e5f00-8662-11eb-937a-8baab4e653e3.png"> <img width="105" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/111374103-55d6f580-8662-11eb-8f3a-a529a433877b.png">

**Comment by FoxtrotSierra6829** [comment]
Well then why not making it a selectable feature? Because I can imagine I'm not the only one who is currently not really happy with this. Same with the repo header width, that I had to find out how to revert the changes myself. I understand the reasons behind why people prefer it this way, but since there are so many features that are selectable, why don't you make the style selectable as well? Speaking for myself, I like to use the additional features, but I prefer to keep the default style.

**Comment by busches** [comment]
@FoxtrotSierra6829 PRs welcome, both to potentially make it toggleable or improve it as @fregante is talking about.

**Comment by fregante** [comment]
> I prefer to keep the default style.

We offer a CSS style field in the options where you can use CSS to undo the feature if you prefer it that way, probably with:

```css
.js-issue-row [aria-label='Open draft pull request'] svg {
	stroke-width: 0 !important;
	color: gray !important;
}
```

Since you prefer the feature to be off, there's no need to improve it on low-dpi. Closing
