### ISSUE TITLE
Use the new `toast` component in `restore-file`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4113]
`restore-file` changes the menu item inline

![](https://user-images.githubusercontent.com/1402241/62826118-73b7bb00-bbe0-11e9-9449-2dd64c469bb9.gif)

But instead of changing the menu, we should use the new toast introduced by https://github.com/sindresorhus/refined-github/pull/4016

![gif](https://user-images.githubusercontent.com/1402241/110071282-5fe32500-7d41-11eb-8d29-a141094a8de9.gif)

Some changes will be needed in the toast to show possible errors. Refer to https://primer.style/css/components/toasts for classnames and icons.

**Comment by fregante** [comment]
Likewise, we should use the toast in every feature that isn't instantaneous. If you think of any, please list them below.

**Comment by jayeshmann** [comment]
Can I take this? If Yes, Where should I begin?

**Comment by fregante** [comment]
This is our implementation of the toast:

https://github.com/sindresorhus/refined-github/blob/ba878fc91552f41f1860a70864917ca3c40914f4/source/github-helpers/toast.tsx#L17

It needs error handling (just an extra `catch` + a custom message)

And it should be used instead of changing the `.textContent` in this file:

https://github.com/sindresorhus/refined-github/blob/ba878fc91552f41f1860a70864917ca3c40914f4/source/features/restore-file.tsx#L82

**Comment by fregante** [comment]
Probably you'll want to change this:

https://github.com/sindresorhus/refined-github/blob/ba878fc91552f41f1860a70864917ca3c40914f4/source/features/restore-file.tsx#L86-L109

To something like:

```

async function restoreFile() {
	const file = await getFile(filePath);

	if (!file) {
		// The file was created by this PR.
		// This code won’t be reached if `highlight-deleted-and-added-files-in-diffs` works.
		throw new Error('Nothing to restore. Delete file instead');
		return;
	}

	if (file.isTruncated) {
		throw new Error('Restore failed: File too big');
		return;
	}

	await commitFileContent(menuItem, file.text, filePath);
}

try {
	const filePath = menuItem.closest<HTMLDivElement>('[data-path]')!.dataset.path!;
	const task = restoreFile();
	showToast(task);

	// Hide file from view
	await task;
	menuItem.closest('.file')!.remove();
} catch (error: unknown) {
	features.error(__filebasename, error);
}
```

**Comment by jayeshmann** [comment]
I hope everything is good now!

**Comment by fregante** [comment]
@yakov116 are there other features that might benefit from this? 🤔

**Comment by yakov116** [comment]
I think the update branch feature and maybe `clone-branch`, `git-reblame`.

Basically wherever we are using the loading icon.
(On mobile this is what I can think of offhand)

**Comment by fregante** [comment]
> Basically wherever we are using the loading icon.

Good thinking.

> clone-branch

👍 

> `git-reblame`.

I think I prefer the small in-place icon in this case, maybe because it's not an _action_ but a link that will change the current page.
