### ISSUE TITLE
Provide option for feature

### ISSUE THREAD

**Issue by EaseTheWorld** [sindresorhus/refined-github#4114]
I found show-names feature very useful.
I want to contribute someday.

What I really want is totally hide id and only show-names but
it would be conflicted to show-names.

So I think it would be better if feature can provide options.
ex> for show-names there could be three options.
   single-select option : id(user-name), user-name(id), user-name only
   multi-select option : in conversation, in commits, in change files....

**Comment by busches** [comment]
Please check out this comment on the issue about new features: https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658

**Comment by EaseTheWorld** [comment]
You are right. I just saw it. Sorry.
