### ISSUE TITLE
`conflict-marker` icon is different from the screenshot.

### ISSUE THREAD

**Issue by EaseTheWorld** [sindresorhus/refined-github#4117]
conflict-marker is the motivation I installed refined-github. Thank you.
But the '!' icon is different from what I expected.(it looks the fill is inverted)
<img width="30" alt="스크린샷 2021-03-17 오후 12 02 34" src="https://user-images.githubusercontent.com/1066923/111419047-170d7200-872c-11eb-974d-944050f1576b.png">
I don't know it is bug or my browser.(I don't apply any other setting or ui plugin)

MacOS 10.15.7, Chrome 88

**Comment by fregante** [comment]
GitHub updated their icons last year, we just use those:

https://octicons-primer.vercel.app/octicons/alert-16

**Comment by EaseTheWorld** [comment]
ok, the svg is from github.
I'm still wondering the left margin is missing.
<img width="75" alt="스크린샷 2021-03-17 오후 3 36 22" src="https://user-images.githubusercontent.com/1066923/111429455-5c39a000-873c-11eb-818d-d3867e71a2cb.png">

If this helps, X and V icon is inside
<span class="d-inline-block mr-1"
  <div class="commit-build-statuses">
    <a>
      <svg>
but ! doesn't have span&div parent.

**Comment by fregante** [comment]
The spacing seems correct to me: https://github.com/eslint/eslint/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+comments+ (👈 don't forget to always include a URL when you open issues, like the _issue template_ requests.)

<img width="694" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/111529070-5ab1ad00-8727-11eb-8dbb-aa9e551455dc.png">

**Comment by EaseTheWorld** [comment]
I think `align-issue-labels` is related.
When I uncheck it,(this is my preference to save vertical space) the margin is missing.
<img width="1063" alt="스크린샷 2021-03-18 오전 9 34 11" src="https://user-images.githubusercontent.com/1066923/111556118-2690c780-87cd-11eb-8fea-a73f07907ac8.png">

When I check it, then the margin looks right, which comes from of the title.
.rgh-align-issue-labels .js-issue-row .h4, .rgh-align-issue-labels .js-issue-row .d-inline-block.mr-1 {
    padding-right: 4px;
}

**Comment by yakov116** [comment]
Can you please provide a link so WE can see the issue

**Comment by EaseTheWorld** [comment]
I tested the same url fregant provided.
eslint/eslint/pulls (is:open sort:updated-desc comments)

**Comment by fregante** [comment]
What browser are you testing in?
Can you find the element in the developer tools and take a screenshot of it? So we can see what other CSS is being applied there.

**Comment by EaseTheWorld** [comment]
I tested chrome88(mac) and chrome89(win), both reproducible.
align-issue-labels checked
![issue-4117-screenshot-align-issue-labels-check](https://user-images.githubusercontent.com/1066923/111649954-326d9f80-8848-11eb-8fef-e399e8da8e54.jpg)
align-issue-labels unchecked
![issue-4117-screenshot-align-issue-labels-uncheck](https://user-images.githubusercontent.com/1066923/111649962-34376300-8848-11eb-9440-f2befd8f611e.jpg)

**Comment by EaseTheWorld** [comment]
After applying the fix above, margin looks fine.

**Comment by fregante** [comment]
Ah the problem is that that `h4` selector is being applied in the wrong feature, it should be part of `conflict-marker`, not `align-issue-labels`

Probably it should be avoided altogether and the `conflict-marker` should come with `.ml-2`

Either way the margins need to be reviewed (disabling `conflict-marker` and/or `align-issue-labels`) to ensure they're applied in the correct place
