### ISSUE TITLE
Cross-repo issue link in issue title

### ISSUE THREAD

**Issue by durka** [sindresorhus/refined-github#412]
See https://github.com/rust-lang/rust/pull/41830. The link in the title goes to `#4000` of the current repo even though it should be possible to match the `org/repo#num` pattern and make the correct link.

**Comment by sindresorhus** [comment]
We already have the regex to make it happen here: https://github.com/sindresorhus/refined-github/blob/b1d48b1916674bdbd0ab4d12b1a9d80295677cb2/extension/linkify-urls-in-code.js#L2 We should move it to `util.js`.

**Comment by hkdobrev** [comment]
@durka Good catch! Do you think you'd be able to work on a PR for this?

**Comment by durka** [comment]
Absolutely, not until later this week though.
