### ISSUE TITLE
`linkify-full-profile-readme-title` is broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4122]
And the description has a verb not in third person: ("Linkify" instead of "Linkifies")

![2gif](https://user-images.githubusercontent.com/1402241/111528258-8ed89e00-8726-11eb-8603-1988b206c2c3.gif)

URL: https://github.com/sindresorhus

**Comment by kidonng** [comment]
This feature breaks again because the cat is missing 🐱
