### ISSUE TITLE
Expand only PR merge status list to fit all items

### ISSUE THREAD

**Issue by jameschensmith** [sindresorhus/refined-github#4124]
## Summary

There was previously introduced [a CSS rule to show all PR merge status items instead of scrollable div](https://github.com/sindresorhus/refined-github/blob/19330b2a4d1715c2d2496e6435a6b43263031c03/source/refined-github.css#L78-L81). The original intention was using it for PR merge statuses, but this CSS rule also applies to the modals as well (in some cases, it doesn't due to the class `open` not being applied). For repositories with a sizable merge status list ([npm/arborist](https://github.com/npm/arborist) is the example in the screenshot), the height of the list without a scrollbar is quite silly :yum:

I would like to recommend a more modest size (maybe up to 10 items?). I understand the original reason to make it longer, but with no overflow the user will still have to scroll (the page), which defeats the purpose of the original intention of showing all items :sweat_smile:

I would also like to expand on this (in the spirit of this repository), and suggest a future potential enhancement. Maybe this would turn into its own feature. It may be nice to add the ability to resize the merge status list.

This is my first issue in this repository, by the way. Thank you for developing this! Why did I not start using this sooner! :blush: :clap: 

## Screenshot(s)

<details>
  <summary>Long merge status list</summary>
  
  ![Long merge status list](https://user-images.githubusercontent.com/15643597/111572608-ef8fc700-8776-11eb-96eb-a002fffaf0d6.png)
</details>

## References

Relates to #1004.

**Comment by fregante** [comment]
We can increase the size to avoid extreme cases indeed, I’ve seen repos with dozens of platform tests. 

As for making it resizable, probably an overkill, unless this is feasible by adding a single `resize: vertical` property somewhere.

**Comment by jameschensmith** [comment]
Sounds good :slightly_smiling_face: I'll take care of it :+1:

**Comment by jameschensmith** [comment]
Updated the title to reflect the new request. This now covers addressing the popups/dropdowns, while keeping the PR merge status list infinite.
