### ISSUE TITLE
The *feature-linkification* _part_ of `format-conversation-titles` appears to be broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4129]
This part:

https://github.com/sindresorhus/refined-github/blob/19330b2a4d1715c2d2496e6435a6b43263031c03/source/features/format-conversation-titles.tsx#L20-L22

On Chrome:
<img width="579" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/111685274-52bc4080-87ed-11eb-8046-315bd3174543.png">

URL: https://github.com/sindresorhus/refined-github/issues/4117 and this issue too

That part was already a little broken because it would be lost when the title updated, but it generally worked.

---

Also in the screenshot you can see a _very cool_ one-time `release-tab` bug

**Comment by yakov116** [comment]
One second... looks like github added parse backticks to issue titles!!

**Comment by fregante** [comment]
INCREDIBRU

So the linkification part of this should ve moved/merged into `rgh-linkify-features`

**Comment by kidonng** [comment]
Wow, I can finally use backticks everywhere without feeling weird (since not everyone is using RG... yet™️)
<small>Things are still weird on the mobile app, of course</small>
