### ISSUE TITLE
Clean up `parse-backticks` selectors

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#4135]
`parse-backticks` rendering in title is now native!
https://twitter.com/natfriedman/status/1372917225993080849

**Comment by yakov116** [comment]
Thanks #4129

**Comment by jack1142** [comment]
Ah, sorry then, I didn't notice 😬 
Closing...

**Comment by yakov116** [comment]
No worries

**Comment by kidonng** [comment]
`parse-backticks` also native for commits, post here so it doesn't get lost:

![image](https://user-images.githubusercontent.com/44045911/116532280-a5236d80-a912-11eb-9c16-e04c3f14857f.png)

**Comment by yakov116** [comment]
I don't like the way it looks and its buggy

**Comment by fregante** [comment]
We can extend `parse-backticks` to detect them and style them correctly. Ideally just via CSS

**Comment by kidonng** [comment]
> its buggy

If you refer to this:

![image](https://user-images.githubusercontent.com/44045911/116716572-7ee0f900-aa0a-11eb-8f57-a19df9a532c6.png)

(The issue is that if the commit title has a reference (issue/PR), the markup becomes `code > a` instead of the styled `a > code`)

**Comment by fregante** [comment]
However it happens, we can fix it via CSS. Hopefully it will be a temporary issue from GitHub

**Comment by fregante** [comment]
I opened a more specific issue
