### ISSUE TITLE
`sync-pr-commit-title` conflicts with GitHub’s backtick parsing

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4139]
1. Open a mergeable PR that has \`backticks\` in the title, like #4134 
2. Try merging it
3. The suggested commit title does not include the backticks

<img width="599" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/111845998-96857780-88cb-11eb-9805-bfc056abb567.png">

Related: #4135 #4129

**Comment by fregante** [comment]
Note: If you add the backticks to the commit title field, it will attempt to update the title (but will cause no issues)

<img width="759" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/111846185-e49a7b00-88cb-11eb-90f2-5e32c48ebdcc.png">

**Comment by fregante** [comment]
This is an ugly bug because it keeps dropping backticks right when merging. Example commits just this week: https://github.com/sindresorhus/refined-github/commit/b60ba4f377d19e6f556babc0e42d77050126fc2d https://github.com/sindresorhus/refined-github/commit/1a507c5d3c3eed9f9ee5453a5fcd4e487841b742

**Comment by yakov116** [comment]
All my fault! I started doing merges on mobile due to this. 😃
