### ISSUE TITLE
`sort-conversations-by-update-time` is overly keen to modify links away from GitHub

### ISSUE THREAD

**Issue by sersorrel** [sindresorhus/refined-github#4142]
https://github.com/sindresorhus/refined-github/blob/31f08464f89dea86e20f9e09b8e7a1aae82c7780/source/features/sort-conversations-by-update-time.tsx#L15-L22

It's probably worth checking that the links found are actually to `https://github.com/*/*/(issues|pulls)`, otherwise any link in a comment to a URL ending in `/issues` or `/pulls` will get modified (example: https://github.com/eslint/eslint/issues/13269#issuecomment-640345544, which links to https://eslint.org/docs/maintainer-guide/issues#when-to-close-an-issue, but gets rewritten to https://eslint.org/docs/maintainer-guide/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc#when-to-close-an-issue).

**Comment by yakov116** [comment]
Maybe we should add `&& !link.hash`?

**Comment by fregante** [comment]
Indeed that's a little too broad. `github-url-detection` accepts an argument, so you can probably check `pageDetect.isConversationList(link)`

---

Also it might be worth checking if this is still needed: https://github.com/sindresorhus/refined-github/blob/31f08464f89dea86e20f9e09b8e7a1aae82c7780/source/features/sort-conversations-by-update-time.tsx#L27-L30

It needs to be `blame`d to find the original issue.
