### ISSUE TITLE
Change the `collapse-wiki-sections` trigger

### ISSUE THREAD

**Issue by mathieucaroff** [sindresorhus/refined-github#4144]
Consider changing the collapsing behavior trigger to something else than the full title. I believe showing a collapse arrow to the left of the title on hover, next to the anchor icon would be a good idea. Like any other collapse arrow, it would have to change to horizontal direction when the section is collapsed.

Possibly, the arrow would stay visible when the title is collapse, so as to inform the user that some content is hidden.

Mildly related #4126

Thank you for making Refined Github

**Comment by mathieucaroff** [comment]
+ I temporarily disabled `collapse-markdown-sections` because it reacts when I click on the anchor symbol. A behavior hopefully solved by the above linked issue's closing pull request.

**Comment by mathieucaroff** [comment]
+ I realized the PR #4127 has a lot more discussions in it than the issue itself:

> _@fregante in https://github.com/sindresorhus/refined-github/issues/4127#issuecomment-803179552_
>
> Also I think we should add a cursor via CSS to show that clicking does _something_, probably:
>
> ```css
> .markdown-body :is(h1, …) {cursor: expand-y or whatever}
> .markdown-body :is(a, details) :is(h1, …) {cursor: initial}
> ```

> _@kidonng in https://github.com/sindresorhus/refined-github/issues/4127#issuecomment-803193226_
>
> Indeed. Currently it doesn't give any visual clue what has happened if one triggers the feature without knowing it. 
>
> In fact, I only realized this feature is implemented after I accidentally triggered it 😅

**Comment by kidonng** [comment]
> + I temporarily disabled `collapse-markdown-sections` because it reacts when I click on the anchor symbol. A behavior hopefully solved by the above linked issue's closing pull request.

Unfortunately I think we missed that in the mentioned PR.

> I believe showing a collapse arrow to the left of the title on hover, next to the anchor icon would be a good idea.

Ideally we should do that (maybe like `<details>`), but since GitHub is already showing an anchor link for the titles, would an additional arrow looks weird?

**Comment by fregante** [comment]
Buttons could be added to the left of the anchor button, to be shown on hover, only when the window is wide enough. 

However this issue is something that being already taken care of by https://github.com/sindresorhus/refined-github/pull/4127, not yet released

**Comment by deflock** [comment]
Yes, a bit annoying behavior. I click sometimes in random places on the page to make window focused and often these clicks collapse sections :(

**Comment by fregante** [comment]
PR welcome to fix the 2 immediate issues:

- cursor via CSS
- don't toggle inside `details`

so we can release a new version today/tomorrow. We can think of an alternative trigger later

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/pull/4335: This feature will be disabled everywhere except on wikis in the next version (maybe 7-10 days away)

But this issue still applies to Wikis

**Comment by fregante** [comment]
This feature has now been disabled. The hidden trigger is just confusing. Also it's not clear when a section is collapsed, so this feature needs to be rethought with a visible trigger button.

**Comment by kidonng** [comment]
GitHub seems to have enhanced the wiki pages, pages in sidebar are now loaded via AJAX and **gained table of contents**:

Example: https://github.com/lukesampson/scoop/wiki

![image](https://user-images.githubusercontent.com/44045911/130123247-59e108ce-6a71-4b01-b19c-9cfdb3621290.png)

This may become a reason to just drop this feature, but the sidebar is not very convenient compared to it.

The wiki sidebar makes a good candidate for `sticky-sidebar` (and possibly related to https://github.com/sindresorhus/refined-github/issues/4664#issuecomment-898896739).

**Comment by yakov116** [comment]
https://github.blog/changelog/2021-08-19-table-of-content-for-wikis/

**Comment by fregante** [comment]
Let's drop the feature

**Comment by shinenelson** [comment]
I have modified #4664 to include https://github.com/sindresorhus/refined-github/issues/4144#issuecomment-902142687; I hope it is okay to mark #4690 as closing this one.
