### ISSUE TITLE
`latest-tag-button`: Cannot read property 'after' of null

### ISSUE THREAD

**Issue by dgrant** [sindresorhus/refined-github#4147]
Happening on a private repo running on GitHub Enterprise Server 2.20.1

**Comment by yakov116** [comment]
Going to need more of an error. (Entire console error)

**Comment by fregante** [comment]
For the record, 2.20.1 is [older than 1 year](https://docs.github.com/en/enterprise-server@2.20/admin/release-notes#2.20.1) and technically not supported by RG. This will only be fixed by someone who experiences the bug.

**Comment by yakov116** [comment]
Going to close this as we have not got any response and its an unsupported GHE
