### ISSUE TITLE
Source link in extension settings doesn't work for features with `.ts` extension

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#4158]
As an example, `collapse-markdown-sections` feature links to:
`https://github.com/sindresorhus/refined-github/blob/main/source/features/collapse-markdown-sections.tsx`
rather than:
`https://github.com/sindresorhus/refined-github/blob/main/source/features/collapse-markdown-sections.ts`

**Comment by fregante** [comment]
All features must end in tsx. That one slipped past the cracks

**Comment by jack1142** [comment]
There's also `clean-dashboard` and `wait-for-attachments` with `.ts` extension in that case.

**Comment by kidonng** [comment]
> All features must end in tsx. That one slipped past the cracks

I was going to say that! I remember [it used to cause more troubles](https://github.com/sindresorhus/refined-github/pull/2375#issuecomment-528259771).

> There's also [`clean-dashboard`](/sindresorhus/refined-github/blob/main/source/features/clean-dashboard.tsx) and [`wait-for-attachments`](/sindresorhus/refined-github/blob/main/source/features/wait-for-attachments.tsx) with `.ts` extension in that case.

You missed one 😃

![image](https://user-images.githubusercontent.com/44045911/112659982-e77b0a00-8e8f-11eb-85fd-7ffd03fdfdfa.png)

**Comment by fregante** [comment]
This should also be enforced in the build to ensure it never happens
