### ISSUE TITLE
Disable Github empty status hover effect

### ISSUE THREAD

**Issue by Krausso** [sindresorhus/refined-github#4160]
Hey, everyone😉

Recently, I've found one thing that's kinda annoying.
So that, I wanna propose a new feature, although it can be a fix or something.
As for me, it'll be a nice idea to disable expanding that small status container while hovering if status is empty at all.

To see an example, you can enter my profile by following the link below:
https://github.com/Krausso

Thanks for your attention!
Have a nice day!

**Comment by fregante** [comment]
I don't know what you're referring to, please include a screenshot. I don't see anything expanding on your profile or my profile

**Comment by Krausso** [comment]
Good morning:) I mean this container with an electron emoji.
Now it's hovered(expanded)
![зображення](https://user-images.githubusercontent.com/52201020/112745008-aa0c9e80-8fad-11eb-96ff-3668e0d10f18.png)

And now it's not
![зображення](https://user-images.githubusercontent.com/52201020/112745026-d4f6f280-8fad-11eb-951e-9b5a4aa16567.png)

**Comment by fregante** [comment]
I see it now. This might be doable by dropping the margin added on hover and readding it on `.user-status-message-wrapper > div`, which only exists when the text exists
