### ISSUE TITLE
Conversation filters issue

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#4161]
update:  The Conversation filters page was incorrectly redirected, see at https://github.com/sindresorhus/refined-github/issues/4161#issuecomment-808770093

- open: 👉  https://github.com/issues  then copy bug 👇

![image](https://user-images.githubusercontent.com/10995302/112726899-ab60ab80-8f5a-11eb-812c-b50ee80eb457.png)

Try disabling the extension first: no problem! 
This problem has existed for a long time

configuration [image](https://user-images.githubusercontent.com/10995302/112726993-2aee7a80-8f5b-11eb-9b5b-593d61152706.png)

**Comment by fregante** [comment]
Use a correct title for this issue to describe it. 

Can you paste the link you the final page that shows no results?

**Comment by dnknn** [comment]
> Use a correct title for this issue to describe it.

sorry for my English.....sorry... 


> Can you paste the link to the final page that shows no results?

```
https://github.com/pulls?q=is%3Aissue+is%3Aopen+author%3A👤🆔+archived%3Afalse+sort%3Aupdated-desc+is%3Aprivate
```

```
https://github.com/issues?q=is%3Aissue+is%3Aopen+author%3A👤🆔+archived%3Afalse+sort%3Aupdated-desc+is%3Aprivate
```

I understand the cause of this problem, i try  `/pulls` ⟶⟿ `/issues` ,  It works fine!

But I don’t know why it is redirected as `/pulls`

**Comment by fregante** [comment]
Likely this is why:

https://github.com/sindresorhus/refined-github/blob/3aadf2f9141107d7ca92e8753f2a66cbc10ebd9d/source/features/sort-conversations-by-update-time.tsx#L28

But it shouldn't happen in this case. I still haven't tried to replicate. @yakov116 can you see it?

**Comment by yakov116** [comment]
Yup those lines are the issue.

**Comment by fregante** [comment]
Lol I get it now. It happens because the `is%3Apr` selector also matches `is%3Aprivate`
