### ISSUE TITLE
Incorrect tab gets highlighted when opening an issue in the bugs section

### ISSUE THREAD

**Issue by yashshah1** [sindresorhus/refined-github#4164]
## STR:
1. Goto https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug.
2. Notice that the tab highlighted on the top is Bugs
3. Open any active issue, the tab highlighted switches to Issues.

Shouldn't the tab highlighted be the bugs tab?

## Video:  

https://user-images.githubusercontent.com/31387795/112757564-e371f800-9007-11eb-98a9-ed645fd6b30b.mov

**Comment by fregante** [comment]
Not a bad idea

**Comment by yakov116** [comment]
If I remember correctly, we had this at one point and we dropped it. I don't remember why.

**Comment by yakov116** [comment]
Something like this should work

**goes at the end of the init not to delay anywhere else**

```ts
	if (pageDetect.isIssue()) {
		const sideBarLables = await elementReady('#partial-discussion-sidebar .sidebar-labels');
		const hasBugLabel = select.exists('.IssueLabel[href$="bug" i]', sideBarLables);
		bugsTab.classList.toggle('selected', hasBugLabel);
		issuesTab.classList.remove('selected');
		issuesTab.removeAttribute('aria-current');
	}
```

however this does not work on `history.back()`
