### ISSUE TITLE
Error truncating `#:~:text=` URL

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#4165]
For example `#:~:text=` URLs : 

```
https://github.com/sindresorhus/refined-github/issues/3686#gh-csc-3:~:text=register%20for%20the%20(free)%20developer%20account
```
or
```
https://github.com/sindresorhus/refined-github/issues/3686#:~:text=register%20for%20the%20(free)%20developer%20account
```

-----

### ❌ Current error behavior (live demo) : 👇
https://github.com/sindresorhus/refined-github/issues/3686#gh-csc-3:~:text=register%20for%20the%20(free)%20developer%20account
https://github.com/sindresorhus/refined-github/issues/3686#:~:text=register%20for%20the%20(free)%20developer%20account

The beginning of `:~:text=.......` will be truncated, so the original anchor function of the API link is lost.

---------------------------------------------------------
### About `:~:text=.......` API (Chrome⁸¹ᐩ ):

![image](https://user-images.githubusercontent.com/10995302/112767620-62882000-904a-11eb-8fdf-829b41af0709.png)

- Link to Text Fragment
https://chrome.google.com/webstore/detail/pbcodcjpfjdpcineamnnmbkkmkdpajjg

```js
//Bookmarklet
javascript:if(target=prompt("⚓", location.href+'#:~:text=' +window.getSelection())) {window.open(target);}
```

### 📖 Documentation :

[https://developer.chrome.com/blog/new-in-chrome-80](https://developer.chrome.com/blog/new-in-chrome-80/#more:~:text=%2C%20by%20using%20%23%3A~%3Atext%3Dsomething)

[https://github.com/WICG/scroll-to-text-fragment](https://github.com/WICG/scroll-to-text-fragment#user-content-identifying-a-text-snippet:~:text=Here's%20an%20example%20URL%20encoding%20some%20text%20to%20indicate%20on%20the%20destination%20page%3A,interpreted)

https://wicg.github.io/scroll-to-text-fragment/

https://web.dev/text-fragments/#text-fragments

**Comment by fregante** [comment]
Thanks for the detailed report, but it's unrelated to Refined GitHub
