### ISSUE TITLE
👋👋👉👉All repository tabs invisible (FIXED)

### ISSUE THREAD

**Issue by kylemh** [sindresorhus/refined-github#4166]
![Screen Shot 2021-03-29 at 9 48 58 AM](https://user-images.githubusercontent.com/9523719/112871311-ffab7e80-9073-11eb-96ed-682a60340b6b.png)

This just started happening minutes ago.

```
❌ Refined GitHub → releases-tab → TypeError: Cannot read property 'append' of undefined
    at init (refined-github.js:3835)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'append'%20of%20undefined
```

**Comment by sharkykh** [comment]
`more-dropdown` seems to be causing the issue.

**Comment by privatenumber** [comment]
Seeing this too. Here's my debugger logs if it's helpful:

<img width="1821" alt="Screen Shot 2021-03-29 at 12 54 04 PM" src="https://user-images.githubusercontent.com/1075694/112872159-0a730d00-908e-11eb-8685-879a6d04d07f.png">

**Comment by maicol07** [comment]
I would like to contribute with my logs if it helps:

```
❌ Refined GitHub → more-dropdown → TypeError: tabItem is undefined
   onlyShowInDropdown more-dropdown.tsx:46
   init more-dropdown.tsx:81
   runFeature index.tsx:125
   setupPageLoad index.tsx:147
   add index.tsx:243
   async* more-dropdown.tsx:125
   <anonymous> refined-github.js:9108
   <anonymous> refined-github.js:9109

Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+tabItem%20is%20undefined
Open an issue: https://github.com/sindresorhus/refined-github/issues/new?la…t.md&title=%60more-dropdown%60%3A%20tabItem%20is%20undefined
 index.tsx:60:9
 
❌ Refined GitHub → releases-tab → TypeError: select_dom(...) is undefined
   init releases-tab.tsx:85
   runFeature index.tsx:125
   setupPageLoad index.tsx:147
   add index.tsx:243
   async* releases-tab.tsx:140
   <anonymous> refined-github.js:9108
   <anonymous> refined-github.js:9109

Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+select_dom(...)%20is%20undefined
Open an issue: https://github.com/sindresorhus/refined-github/issues/new?la…tle=%60releases-tab%60%3A%20select_dom(...)%20is%20undefined
 index.tsx:60:9
```

**Comment by Vadorequest** [comment]
Same thing here. 

Had to disable the extension for now. 😢 

![image](https://user-images.githubusercontent.com/3807458/112874877-c00c8300-90c3-11eb-8d89-d98ad319def4.png)

**Comment by bramkragten** [comment]
> Same thing here.
> 
> Had to disable the extension for now. 😢
> 

You can just disable `more-dropdown`, then you can at least use the rest of refined github!

**Comment by frankli0324** [comment]
seems that the id for tabs are renamed from `${name}-tab` to `i${order}${name}-tab`
![image](https://user-images.githubusercontent.com/20221896/112889258-fbc93c00-9107-11eb-922f-b57417ee6061.png)
![image](https://user-images.githubusercontent.com/20221896/112889497-4945a900-9108-11eb-9c8f-3748c02d1574.png)

**Comment by dnknn** [comment]
But a bigger problem is coming, the Chrome kernel currently required by Refined GitHub must be ⩾88+ ......Can't upgrade in a short time because of use fork of Chromium (86)

**Comment by yakov116** [comment]
I have disabled `more-dropdown` via a hotfix for now

**Comment by micalevisk** [comment]
I've disabled `more-dropdown` but now, sometimes(?), I'm getting this:

![bug](https://user-images.githubusercontent.com/13461315/112925117-54381380-90df-11eb-9096-998dd9a4e2e3.png)

which sould be this:

![after disabling Refined GitHub addon](https://user-images.githubusercontent.com/13461315/112925216-7f226780-90df-11eb-91a8-d47a467584e9.png)

:confused:

**Comment by fregante** [comment]
👆 Refined GitHub users: No further action is required if you’re seeing this issue after 4 hours from this message. 

GitHub changed the layout so things break when that happens. Sorry you had to go through this.

**Comment by fregante** [comment]
@micalevisk that might be due either `bugs-tab` or `releases-tab`. They’ve already been fixed

@yakov116 they should probably be hotfixed as well.

**Comment by yakov116** [comment]
`bugs-tab`

**Comment by Gravifer** [comment]
With Edge I am having this problem starting minutes ago. Leaving this comment only for the sake of reference.

**Comment by douglasduteil** [comment]
# Call The UX 👮‍♂️

**Comment by kubukoz** [comment]
Works for me on FF. Thanks for the fix :)

**Comment by RtYkk** [comment]
Thanks for the fix :)

**Comment by fregante** [comment]
I'm leaving this open for a few more days if you don't mind

**Comment by yakov116** [comment]
Going to close as the new release has been out for a few days already
