### ISSUE TITLE
code/issues/pull requests selector is missing

### ISSUE THREAD

**Issue by kubukoz** [sindresorhus/refined-github#4167]
Happens on all repositories, including this one.

Plugin enabled:

![image](https://user-images.githubusercontent.com/894884/112871229-568a7580-90bf-11eb-87a2-7872fac7c679.png)

Plugin disabled:

![image](https://user-images.githubusercontent.com/894884/112871288-6609be80-90bf-11eb-98d6-00c4d7aa6f9a.png)

Browser: firefox

Console errors:

```
❌ Refined GitHub → releases-tab → TypeError: select_dom(...) is undefined
    init releases-tab.tsx:85
    runFeature index.tsx:125
    setupPageLoad index.tsx:147
    add index.tsx:243
    async* releases-tab.tsx:140
    <anonymous> refined-github.js:9108
    <anonymous> refined-github.js:9109
 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+select_dom(...)%20is%20undefined

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?la…tle=%60releases-tab%60%3A%20select_dom(...)%20is%20undefined
```

**Comment by mateuszkwiecinski** [comment]
The same happens on Chrome. I can share that disabling `more-dropdown` feature restores tabs
![image](https://user-images.githubusercontent.com/36954793/112872403-a3228080-90c0-11eb-942f-ed7e53bb60f3.png)

**Comment by munael** [comment]
I wonder if any devs at GitHub use Refined Github 🤔 

Not implying anything. Just wondering what it'd feel like then.

**Comment by aw-was-here** [comment]
> The same happens on Chrome. I can share that disabling [`more-dropdown`] feature restores tabs

Confirming this also fixes Firefox.

**Comment by bramkragten** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/4166

**Comment by kubukoz** [comment]
Hah, one minute late!
