### ISSUE TITLE
Repo navigation bar disappears

### ISSUE THREAD

**Issue by davidhu2000** [sindresorhus/refined-github#4170]
With Refined github
![Screen Shot 2021-03-29 at 12 54 33 PM](https://user-images.githubusercontent.com/15827041/112892243-f0392f00-908d-11eb-91f2-f0e38b4ce7b4.png)

Without Refined github
![Screen Shot 2021-03-29 at 12 54 13 PM](https://user-images.githubusercontent.com/15827041/112892261-f5967980-908d-11eb-910c-d5b49aa7017c.png)

The nav bar disappears. 

![Screen Shot 2021-03-29 at 12 55 15 PM](https://user-images.githubusercontent.com/15827041/112892327-05ae5900-908e-11eb-88e2-66d6cf66ad22.png)

**Comment by mtsibulski** [comment]
i was able to temporarily fix by disabling `more-dropdown` feature

error stack, if it helps: 
`Refined GitHub → more-dropdown → TypeError: Cannot read property 'parentElement' of undefined
    at onlyShowInDropdown (refined-github.js:3654)
    at init (refined-github.js:3671)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) `

**Comment by FloEdelmann** [comment]
Duplicate of #4166

**Comment by davidhu2000** [comment]
yeah. that worked. I'll close this issue for #4166
