### ISSUE TITLE
How to restore the navigation bar?

### ISSUE THREAD

**Issue by DoveBoy** [sindresorhus/refined-github#4174]
**Before**
![image](https://user-images.githubusercontent.com/19201447/112929993-1a512680-914c-11eb-9b90-bb4775b0b9a7.png)

**After**
![image](https://user-images.githubusercontent.com/19201447/112930058-2fc65080-914c-11eb-92b2-b9af4a2df131.png)

How do I restore the before settings?

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/4166

Just refresh you extension cache

**Comment by kidonng** [comment]
@yakov116 maybe pin the main issue?

**Comment by yakov116** [comment]
Done
