### ISSUE TITLE
Allow only Assignee to merge a pull request

### ISSUE THREAD

**Issue by coorasse** [sindresorhus/refined-github#4176]
We would like to make only people assigned to a Pull Request able to merge it.
A person that is a Reviewer should see the button as disabled, with a pop-up explaining that only the Assignee can merge the PR.

**Comment by fregante** [comment]
Refined GitHub can’t block users from doing things, they can just disable the extension. You’ll have to as GitHub.

**Comment by coorasse** [comment]
The use case is that within our company, we would like only assignees to merge pull requests and not reviewers.
As a reviewer, I don't see that clearly and I might merge by mistake a Pull Request. 
Having this button disabled would prevent this from happening.
Of course I can always disable the extension but I have no interest in doing so, because it prevents me from such mistake.
