### ISSUE TITLE
`edit-readme`, `latest-tag-button`, and `edit-files-faster` console errors with "Error: GitHubURL can only be used on pages with a branch/reference."

### ISSUE THREAD

**Issue by MatthewL246** [sindresorhus/refined-github#4179]
## Whenever I load any GitHub repository page, I get three errors in the console related to Refined GitHub -  *Error: GitHubURL can only be used on pages with a branch/reference.*

This happens in any repository for me, including this one or [my hello-world repository](https://github.com/MatthewL246/hello-world) (which does have a test release tag, so it should work). Here are the errors in the logs: 

```js
❌ Refined GitHub → edit-readme → Error: GitHubURL can only be used on pages with a branch/reference.
    at GitHubURL.disambiguateReference (refined-github.js:4580)
    at GitHubURL.set pathname [as pathname] (refined-github.js:4600)
    at new GitHubURL (refined-github.js:4562)
    at init (refined-github.js:6865)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60edit-readme%60%3A%20GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.
		
logError @ refined-github.js:1884
runFeature @ refined-github.js:1904
async function (async)
runFeature @ refined-github.js:1902
setupPageLoad @ refined-github.js:1915
add @ refined-github.js:1949
async function (async)
add @ refined-github.js:1934
(anonymous) @ refined-github.js:6859
(anonymous) @ refined-github.js:9108
(anonymous) @ refined-github.js:9109
refined-github.js:1884


❌ Refined GitHub → latest-tag-button → Error: GitHubURL can only be used on pages with a branch/reference.
    at GitHubURL.disambiguateReference (refined-github.js:4580)
    at GitHubURL.set pathname [as pathname] (refined-github.js:4600)
    at new GitHubURL (refined-github.js:4562)
    at init (refined-github.js:5158)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915) 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60latest-tag-button%60%3A%20GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.
		
logError @ refined-github.js:1884
runFeature @ refined-github.js:1904
async function (async)
runFeature @ refined-github.js:1902
setupPageLoad @ refined-github.js:1915
add @ refined-github.js:1949
async function (async)
add @ refined-github.js:1934
(anonymous) @ refined-github.js:5152
(anonymous) @ refined-github.js:9108
(anonymous) @ refined-github.js:9109
refined-github.js:1884


❌ Refined GitHub → edit-files-faster → Error: GitHubURL can only be used on pages with a branch/reference.
    at GitHubURL.disambiguateReference (refined-github.js:4580)
    at GitHubURL.set pathname [as pathname] (refined-github.js:4600)
    at new GitHubURL (refined-github.js:4562)
    at init (refined-github.js:6312)
    at async runFeature (refined-github.js:1902)
    at async setupPageLoad (refined-github.js:1915)
    at async chrome-extension:/hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1948 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60edit-files-faster%60%3A%20GitHubURL%20can%20only%20be%20used%20on%20pages%20with%20a%20branch%2Freference.
```

### My settings:
I am currently using a token that only has API access without any extra permissions. Here is the list of features (with errors omitted):

```
↩️ Skipping align-issue-labels
↩️ Skipping clean-dashboard
↩️ Skipping hide-useless-newsfeed-events
↩️ Skipping hide-watch-and-fork-count
↩️ Skipping minimize-upload-bar
↩️ Skipping remove-diff-signs
↩️ Skipping more-dropdown
↩️ Skipping releases-tab
↩️ Skipping remove-projects-tab
↩️ Skipping hide-navigation-hover-highlight
↩️ Skipping deprioritize-marketplace-link
↩️ Skipping hide-own-stars
↩️ Skipping sync-pr-commit-title
↩️ Skipping hide-inactive-deployments
↩️ Skipping hide-issue-list-autocomplete
↩️ Skipping set-default-repositories-type-to-sources
↩️ Skipping bypass-checks
↩️ Skipping clean-conversation-sidebar
↩️ Skipping hide-zero-packages
↩️ Skipping clean-rich-text-editor
↩️ Skipping bugs-tab
↩️ Skipping clear-pr-merge-commit-message
↩️ Skipping clean-repo-filelist-actions
↩️ Skipping clean-conversation-headers
↩️ Skipping clean-repo-sidebar
↩️ Skipping wait-for-attachments
↩️ Skipping no-duplicate-list-update-time
✅ one-key-formatting
✅ selection-in-new-tab
✅ profile-hotkey
✅ close-out-of-view-modals
✅ improve-shortcut-help
✅ esc-to-deselect-line
✅ file-finder-buffer
✅ esc-to-cancel
✅ trending-menu-item
✅ shorten-links
✅ linkify-code
✅ navigate-pages-with-arrow-keys
✅ sort-conversations-by-update-time
✅ sort-milestones-by-closest-due-date
✅ star-repo-hotkey
✅ parse-backticks
✅ sticky-sidebar
✅ show-whitespace
✅ reload-failed-proxied-images
✅ linkify-user-location
✅ user-local-time
✅ stop-pjax-loading-with-esc
✅ rgh-sponsor-button
✅ collapse-markdown-sections
✅ toggle-files-button
✅ ci-link
✅ repo-age
```

The only visual difference is that the tag compare button does not appear because of that error. One strange thing is that it was working soon after I first installed the extension, but now it is not, even when I create a new profile with the default settings. I did turn off `more-dropdown` to deal with #4166, but I have turned it back on now in settings (now that it appears to be temporarily disabled for everyone through `hotfix.json`).

Please let me know if you need any more information, and I will be happy to help.

**Comment by yakov116** [comment]
Shoot I knew this would happen one day.

**Comment by yakov116** [comment]
Same as https://github.com/sindresorhus/refined-github/issues/4178

GitHubURL as of now is 🚭. `$('link[type="application/atom+xml"]')` stopped working on pages. I think we need to ask github to help us out. I dont see any way to fix this. This allowed us to load branch stuff without depending on specific dom and waiting for the dom to be ready.

This is a real bummer.

**Comment by cheap-glitch** [comment]
> This allowed us to load branch stuff without depending on specific dom and waiting for the dom to be ready.

Can't we replace this with API calls?

**Comment by yakov116** [comment]
No, we need to know the branch of the current page

**Comment by altrisi** [comment]
Don't know about typescript or anything, but would this be useful for anything?

`$('#branch-select-menu > [data-hotkey=w] > .css-truncate-target').innerHTML`

This selects the branch switcher button's text, which is basically the current branch or commit. Even though it only has the truncated commit hash, Github seems to accept going to an url with only the first characters of it.

It's not the first thing that gets loaded, but in case it's useful. It seems to be present in any page when exploring files, although not in PRs.

**Comment by fregante** [comment]
> Don't know about typescript or anything, but would this be useful for anything?
> 
> `$('#branch-select-menu > [data-hotkey=w] > .css-truncate-target').innerHTML`

Yes and no. Some features can read that piece of information, others can't. GitHub sometimes either delays its loading or just doesn't display it (like on `/commits/` pages).

Anyway most of these issues will be fixed by #4193

**Comment by fregante** [comment]
I'm hesitant to add an `unaffected` key to our hotfix file after https://github.com/sindresorhus/refined-github/issues/4166

@yakov116 are all the features actually fixed in the latest version? Can you add the `unaffected` version in the hotfix after it's verified?

**Comment by yakov116** [comment]
They were never added to the list....

**Comment by MatthewL246** [comment]
After letting the extension auto-update to version `21.4.6`, all of these problems are now fixed. Thank you to everyone!
