### ISSUE TITLE
Projects Tab Still Visible on GHE

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#418]
For some reason GHE has the class name on the span as `counter` instead of `Counter`, meaning we don't find the count and don't remove the tab. Can we search for the span instead or just `ounter` with `projectsTab.find('span[class$="ounter"]')`? 

Current code: https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L354-L359
```
function removeProjectsTab() {
 	const projectsTab = $('.js-repo-nav').find('.reponav-item[data-selected-links^="repo_projects"]');
 	if (projectsTab.length > 0 && projectsTab.find('.Counter').text() === '0') {
 		projectsTab.remove();
 	}
 }
```

**Comment by sindresorhus** [comment]
I don't understand. We don't support GHE.

**Comment by busches** [comment]
Maybe not directly, but a small change would allow this feature to work for both and you're against that? Also if we ever do Issue #315, then this would come up.

**Comment by jgierer12** [comment]
👍, but I'd rather look for `.Counter, .counter` than `span[class$="ounter"]`

**Comment by sindresorhus** [comment]
Do we really want the overhead of that when we can't test it, is all I'm saying. GHE is always a little bit behind, so there's very likely other things will be broken in the future or are already broken.

**Comment by busches** [comment]
@sindresorhus that's up to the project maintainers to decide. If the decision is not to support it, then I think so much should be said on #315 as well to make it clear this isn't something the project wants.

**Comment by sindresorhus** [comment]
I'm willing to do it if someone using GHE wants to join the project. If not, it's pretty hopeless for us to fix issues that come up.

**Comment by hkdobrev** [comment]
I'll insist on supporting GHE even though I'm not using GHE myself.

Users of GHE are often power users and are the customers paying the most to GitHub, so this would make GitHub take changes from the extension even more seriously if enterprise customers are adding a browser extension to ad

@sindresorhus 
> I'm willing to do it if someone using GHE wants to join the project. If not, it's pretty hopeless for us to fix issues that come up.

@busches has already contributed and is a GHE user. We also have others like @bfred-it, I think. Perhaps he could try to tackle the GHE support so even more GHE users join in the future.

---

On the actual issue, I think this is pretty minor and the effort to fix it is significantly lower than the benefit.

> I'd rather look for `.Counter, .counter` than `span[class$="ounter"]`

👍 

---

@busches Could you open a PR for the Projects tabs with the suggestion from @jgierer12? I guess you'd test whether it works on GHE.

**Comment by busches** [comment]
@hkdobrev I certainly can tonight. I've applied @jgierer12's fix in my local fork that works on our GHE and it's working fine.

**Comment by sindresorhus** [comment]
> Users of GHE are often power users and are the customers paying the most to GitHub, so this would make GitHub take changes from the extension even more seriously if enterprise customers are adding a browser extension to extend GH functionality.

Good point. Maybe it's time to introduce that settings page to enable GHE out of the box then.

**Comment by sindresorhus** [comment]
@busches Would you be interested in joining the project? You've already done some good PRs :)

**Comment by bfred-it** [comment]
Side note: @hkdobrev I'm not a GHE user :D
