### ISSUE TITLE
Unfurl of diff code not working

### ISSUE THREAD

**Issue by snackattas** [sindresorhus/refined-github#4182]
I think unfurl url is broken. this is sad because its my favorite feature
https://github.com/sindresorhus/refined-github/issues/2151

seems broken on any url. here's a sample https://github.com/grosser/parallel_tests/pull/755/files
In the gif i was ctrl+clicking and alt+clicking with latest refined github extension, but no dice

![2021-03-31 10 07 19](https://user-images.githubusercontent.com/12533693/113167041-f1db3200-9208-11eb-9e7c-3ba7a93d1f6b.gif)

Only things in js console were these
```
DevTools failed to load SourceMap: Could not load content for chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js.map: HTTP error: status code 404, net::ERR_UNKNOWN_URL_SCHEME

[Violation] Forced reflow while executing JavaScript took 58ms

810:1 [Deprecation] ::-webkit-details-marker pseudo element selector is deprecated. Please use ::marker instead. See https://chromestatus.com/feature/6730096436051968 for more details.

refined-github.js:1884 ℹ️ Refined GitHub → update-pr-from-base-branch → Personal token required for this feature

refined-github.js:1884 ℹ️ Refined GitHub → show-names → Personal token required for this feature

refined-github.js:1884 ℹ️ Refined GitHub → repo-wide-file-finder → Personal token required for this feature
```

**Comment by yakov116** [comment]
GitHub added the expand all button
