### ISSUE TITLE
"Search in files" button does not cancel navigation

### ISSUE THREAD

**Issue by nao20010128nao** [sindresorhus/refined-github#4183]
# "Search in files" button does not cancel navigation
This problem happens in any repository, with URL like: https://github.com/sindresorhus/refined-github

Here's the video showing this behavior:

https://user-images.githubusercontent.com/10355528/113172844-cba6a800-9283-11eb-92ec-dd5782dd02f6.mp4

This also happens with <kbd>t</kbd> key, which is equivalent to push the button.

Thanks.

**Comment by fregante** [comment]
You’re not supposed to click that, it’s already focused. Just start typing immediately
