### ISSUE TITLE
Collapse successive deleted/hidden comments

### ISSUE THREAD

**Issue by Krzmbrzl** [sindresorhus/refined-github#4186]
Consider the following PR of mine: https://github.com/mumble-voip/mumble/pull/3743
It contains an awful lot of comments that were outdated or otherwise not longer relevant. In order to bring down the amount of posts in the PR, I decided to delete some of them.
However there were now dozens of entries of me having deleted these comments and thus it kinda failed its purpose.

I am proposing to collapse successive "xy deleted comment from yz" messages into something like "xy deleted x comments".
Maybe it would also make sense to do the same for hidden comments (aka: collapse multiple successive hidden comments with "N comments hidden").

**Comment by Krzmbrzl** [comment]
Maybe it could even make sense to collapse successive commits in such PRs :thinking:

**Comment by fregante** [comment]
We discussed this before and decided that this would be the best way to handle noise in discussions without hiding events by default, which are sometimes useful anyway: https://github.com/sindresorhus/refined-github/pull/4029

**Comment by Krzmbrzl** [comment]
Well I don't want to _hide_ these things. I would like for them to be _collapsed_. Therefore if someone is interested in these, they can expand them again.

This seems like a more fine-tuned approach than #4029. If you have already discussed this though, then I guess #4029 will do :shrug:
