### ISSUE TITLE
Linking the branch's feed in an issue gets replaced with "`branch.atom` (commits)"

### ISSUE THREAD

**Issue by altrisi** [sindresorhus/refined-github#4189]
URL where the bug appears: Below.

https://github.com/sindresorhus/refined-github/commits/main.atom

No errors, it's just the extension considering it being a file in the repo and thinking that it is the commit list for that file.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/pull/3437#discussion_r467058486
I think the following commit will help.
https://github.com/sindresorhus/refined-github/pull/3437/commits/a06753b482434d523596f42d8f77e07d7371b3ce

Not by a computer so I cant check. Are you able to see if that would work?

**Comment by yakov116** [comment]
Can you open an issue on https://github.com/fregante/shorten-repo-url/issues

Thanks

**Comment by fregante** [comment]
Not really a bug, it's `shorten-links` at work.

**Comment by fregante** [comment]
I opened https://github.com/fregante/shorten-repo-url/issues/28 for a possible improvement
