### ISSUE TITLE
`quick-repo-deletion` z-index issue

### ISSUE THREAD

**Issue by RtYkk** [sindresorhus/refined-github#4192]
Just look at the screenshot or the gif.
![chrome_hxisgJyK48](https://user-images.githubusercontent.com/45971730/113467137-9c568d80-9473-11eb-8bec-39e64f782ae6.png)
![CWCVlcjpML](https://user-images.githubusercontent.com/45971730/113467141-9f517e00-9473-11eb-9e8c-00be50fac685.gif)

I guess that it's because of GitHub's new MARKDOWN viewer.

**Comment by fregante** [comment]
Confirmed, only a visual issue

**Comment by RtYkk** [comment]
Hi @yakov116 ! Thanks for fixing.
But it seems that #4251 introduced new visual bug, please check it in the screenshots below.

Without Refined GitHub opened ↓
![chrome_qCf5hpohEM](https://user-images.githubusercontent.com/45971730/116395855-3c2aef80-a857-11eb-88cc-d826a211ff6a.png)

With Refined GitHub opened ↓
![chrome_g0obqpr9AN](https://user-images.githubusercontent.com/45971730/116395743-1998d680-a857-11eb-9453-dc4e27455266.png)
https://github.com/chromium/mini_chromium

This bug doesn't happen in every repo. I can't reproduce it in [sindresorhus/refined-github](https://github.com/sindresorhus/refined-github), but it truly happens in many other repos. And I'm not sure what causes this weird difference. Should I open a new issue or just in this one?

**Comment by fregante** [comment]
This is unrelated to this issue and is fixed by https://github.com/sindresorhus/refined-github/pull/4279 in the next release.

**Comment by RtYkk** [comment]
OK. I'll close this issue.
