### ISSUE TITLE
`edit-readme` stopped working

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4195]
As a consequence of them adding the TOC https://github.com/sindresorhus/refined-github/issues/4157, probably the selector changed and it's no longer found.

Try it on https://github.com/typescript-eslint/typescript-eslint/tree/chore/lerna-4/docs/getting-started

Follows #4179 and #4193, which report and fix another underlying broken part of the feature.

**Comment by kidonng** [comment]
Not sure why, it still works on some places, example: https://github.com/Qv2ray/mochi

**Comment by fregante** [comment]
No, that's the native edit button offered by GitHub. Our feature makes it work on repos you don't have access to.
