### ISSUE TITLE
What features should be removed and why?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4197]
There are 2 types of features I'm expecting to hear:

- controversial features could be dropped or made less controversial
- rare/broken/unnecessary features that either don't belong to Refined GitHub or aren't worth supporting

Not promising that the changes will happen, but it's a good time to discuss since we have 200+ features and some changes need to edit/test _many features_ before going live.

**Comment by dorian-marchal** [comment]
I always disable these features:
 - __Automatically deletes the branch right after merging a PR, if possible.__
  I don't want to delete my colleagues branches when I merge them.
- __Uses the PR’s title as the default squash commit title and updates the PR’s title to match the commit title, if changed.__
  My team relies on the default behavior to identify Merge commits.
  I see that this refers to "squash commit" now, so maybe I could reenable that.
- __Hides forks and watchers counters.__
  That's valuable information I don't want to hide.

**Comment by kidonng** [comment]
@dorian-marchal The first two may be addressed in #3964

**Comment by fregante** [comment]
Thanks for the comment. 

How is the fork and watchers count useful to you that the Star count doesn’t already tell?

**Comment by dorian-marchal** [comment]
I feel like watching a repo shows more involvement than simply starring it.
However after thinking about it, the main reason I disabled this option was that it removed the direct links to watchers/forks. It seems like the watchers link has since been added back.
The forks link is still missing though, and there is a "Find useful forks" button on this page that I like.

**Comment by fregante** [comment]
Indeed, but do they really tell you what you hope? 

- This repo has 189 watchers but I only ever see about 10 people active in comments;
- As for the forks, if you want to know the actual number of contributors, it appears on the repo home tab. People (mis-) use forks to bookmark and backup repositories, so the fork count is way off too.

This watchers count is visible and clickable when you open the watchers dropdown, by the way. This wasn’t possible for forks #4206 

However I feel you about the **link** to the forks list. We turned that from 1-click to 3 clicks (more dropdown, insights, forks)

**Comment by cheap-glitch** [comment]
> However I feel you about the link to the forks list. We turned that from 1-click to 3 clicks (more dropdown, insights, forks)

We could re-add it as a dropdown item in `more-dropdown`.

**Comment by fregante** [comment]
> > However I feel you about the link to the forks list. We turned that from 1-click to 3 clicks (more dropdown, insights, forks)
> 
> We could re-add it as a dropdown item in [`more-dropdown`](/sindresorhus/refined-github/blob/main/source/features/more-dropdown.tsx).

If that link is useful, it shouldn't be removed in the first place. It does save 40px and cleans up the view a little, but… when we have to implement workarounds for our features, they start to make less sense. A few alternatives

- Drop the "Fork" label instead of the count
- Only hide the count only on small screens
- Reduce the feature to just `hide-watch-count` or a generic `clean-repo-header` (which can hide "Unstar" and "Stop ignoring")

**Comment by yakov116** [comment]
> * Drop the "Fork" label instead of the count

👎 
> * Only hide the count only on small screens

👍 
> * Reduce the feature to just `hide-watch-count` or a generic `clean-repo-header` (which can hide "Unstar" and "Stop ignoring")

👎

**Comment by cheap-glitch** [comment]
Now that GitHub provides a ToC on every markdown doc, I think we can drop `collapse-markdown-sections`. I can only think of two cases where it was useful:
 * When navigating back and forth in an API doc, e.g.: https://github.com/yargs/yargs/blob/master/docs/api.md. This is now better accomplished by the built-in ToC.
 * When navigating a long wiki page. But most of them are pretty short, and the big ones know to provide a homemade ToC, e.g.: https://github.com/junegunn/fzf/wiki/Examples.

**Comment by fregante** [comment]
Agreed. We can probably limit the feature to wikis until they add the TOC there as well.

**Comment by fregante** [comment]
- [ ] Rewrite `copy-file` so that it uses the native `clipboard-copy` element.

I'm not sure if this is possible, but I'm imagining that if we use a "capture: true" we can run before their event and set the required attribute:

1. Onclick -> `button.setAttribute('value', blob.innerText)`
2. `clipboard-copy` takes care of showing the tooltip and actually copying to the clipboard

Also our onclick handler only needs to run once (if this optimization is possible)

**Comment by noftaly** [comment]
I personally don't like `new-repo-disable-projects-and-wikis` and find myself un-checking the checkbox every time 😄 I find GitHub projects very useful.

I also disable `clean-pinned-issues` because I don't think it makes them cleaner 😄 but perhaps that's just me.

Then there is a feature I personally never used: `selection-in-new-tabs`. It doesn't bother me, but I don't really see a use case, and it is pretty easy with a simple keyboard shortcut to open a link in a new tab (CMD + click or CMD + shift + click on safari for example).

Hope it hekps

**Comment by fregante** [comment]
> I personally don't like `new-repo-disable-projects-and-wikis`

We get that a lot, also as part of https://github.com/sindresorhus/refined-github/issues/3964

But from a quick look at your pinned and top repositories, only 1 uses wikis and 2 use projects. The vast majority of repositories don't need either feature, that's why it's a default here.

> `clean-pinned-issues` because I don't think it makes them cleaner

It is a bit subjective as a style change, but:

- it takes less vertical space, which is objectively good so more fresh content can be seen
- it lets us show even more content in the same space, without making it taller (`pinned-issues-update-time`)


> there is a feature I personally never used: `selection-in-new-tab`

Probably I haven't use it either, but just because I don't use most keyboard shortcuts either. There are a few keyboard shortcut features that really don't affect the end user when they're enabled, so disabling them brings minimal advantage.

Here however I do see that it catches `keypress` on every page, so it should probably be improved. https://github.com/sindresorhus/refined-github/issues/4272

**Comment by fregante** [comment]
I recreated this issue to start fresh since these comments have been discussed.

**Comment by fregante** [comment]
Since #6333 (version 23.2.11) you can disable a couple of the features mentioned here by visiting the options 🎉
