### ISSUE TITLE
Pulls: 'View file' broken links

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4205]
Moved to here from https://support.github.com/ticket/1094756

1. 'A REAL URL': https://github.com/elementary/wallpapers/pull/138/files

![gh_404link_Screenshot_20210406_165006](https://user-images.githubusercontent.com/38327267/113721782-59005700-96df-11eb-9382-efb2af69ae66.png)

Look at the link, `blob//backgrounds`.

**Comment by yakov116** [comment]
It will be fixed in the next release. For now disable `enable-file-links-in-compare-view`

**Comment by fregante** [comment]
21.4.6 coming right up! Given the bugs it's worth releasing early

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/releases/tag/21.4.6 Just wait for it
