### ISSUE TITLE
Remove Milestones filter if there are no milestones

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#421]
![image](https://cloud.githubusercontent.com/assets/506129/26025465/29c6047c-37f1-11e7-8c20-32e3a3a6559c.png)

When there are no milestones the filter in issues and PRs listing page in a repo still have a filter for milestones which is not useful at all. There's just one option which just shows all issues/PRs with no milestones which are basically every issue/PR.

I think this would reduce clutter for projects not using milestones and not change anything if you're using milestones.

**Comment by sindresorhus** [comment]
👍

**Comment by busches** [comment]
I took a stab at this, but the milestone list isn't loaded until you attempt to filter on it. Is there another way we can determine if they're using milestones outside of what's in the list and if not, do we want to call the list all the time just to remove it?

**Comment by sindresorhus** [comment]
@busches Use `MutationObserver`.

**Comment by busches** [comment]
@sindresorhus that seems clunky though. I'd click on `Milestones` and then it'd load the list, it has no milestones, and we'd immediately remove it?

**Comment by sindresorhus** [comment]
MutationObserver is pretty fast, so not sure it would even be visible before it was removed. Any other suggestions?

**Comment by sindresorhus** [comment]
Ok, I misunderstood how it worked.

**Comment by bfred-it** [comment]
1. Fetch and cache Milestones count at earlier convenience
2. Use it
3. Make it expire after a day (expiration just means storing the retrieval date, it doesn't need to be cleaned up since it's just a handful of bytes: `{'sindresorhus/refined-github': [0, 1501042347424]})

**Comment by bfred-it** [comment]
This requires a fetch to the API to check if a project has any Milestones. Is it worth it?
