### ISSUE TITLE
Keyboard shortcut to the Insights tab

### ISSUE THREAD

**Issue by Pixel48** [sindresorhus/refined-github#4211]
### Go to Graphs (shortcut)
Shortcut like `g` `c` for ***Go to Code*** or `g` `r` for ***Go to Releases*** (Love this one) to jump into repository `Insights` tab
> Example link: Go to [insights](https://github.com/sindresorhus/refined-github/pulse) from [repo](https://github.com/sindresorhus/refined-github) by hitting `g` `h`

**Comment by yakov116** [comment]
In other words you want shortcut to the Insights tab?

**Comment by Pixel48** [comment]
Yes

**Comment by fregante** [comment]
`more-dropdown` hides the Insights tab into the More dropdown because considered of infrequent use. A shortcut would mean that it’s of frequent use, I think, therefore contradicting the existing feature.
