### ISSUE TITLE
Fix GitHub Actions scrollbar

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#4215]
Example URL: https://github.com/sindresorhus/got/runs/2308257136

The tiny scrollbar is so annoying... GitHub fixes this automatically but it takes them seconds to take effect.

![image](https://user-images.githubusercontent.com/36894700/114223020-9d098b00-996f-11eb-9328-1c42ff10c71c.png)

**Comment by fregante** [comment]
I'm not seeing this. Is it caused by other extensions?

**Comment by szmarczak** [comment]
Hmm... I'll check this and let you know.

**Comment by szmarczak** [comment]
@fregante Yeah, Adblock Plus causes this...
