### ISSUE TITLE
`swap-branches-on-compare` not working?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4223]
The arrow isn't clickable

![gif](https://user-images.githubusercontent.com/1402241/114288518-dbe82f80-9a9a-11eb-8550-5903f7a14638.gif)

URL: https://github.com/sindresorhus/refined-github/compare/main

Follows: https://github.com/sindresorhus/refined-github/issues/1217

**Comment by ceelo777** [comment]
I'd be interested in taking on this issue!

**Comment by yakov116** [comment]
@ceelo777 go for it!

**Comment by ceelo777** [comment]
Is there a way to debug using the chrome dev tools? Or something else?

**Comment by yakov116** [comment]
> Is there a way to debug using the chrome dev tools? Or something else? Not really sure how to debug extensions

Sure did you follow https://github.com/sindresorhus/refined-github/blob/main/contributing.md#workflow?

**Comment by ceelo777** [comment]
Yep - are there instructions on there for debugging extensions?

**Comment by yakov116** [comment]
Your should see any errors/logging in your dev tools. Did you load the manually created ext in chrome?

**Comment by ceelo777** [comment]
Yea it works - but I want to be able to set breakpoints on certain files and check variables and whatnot

**Comment by yakov116** [comment]
To find the line you need to stop by make a `console.log`. Chrome will tell you what line it is in the file

**Comment by ceelo777** [comment]
Ah gotchu, thanks

**Comment by busches** [comment]
Or use `debugger;`
