### ISSUE TITLE
`latest-tag-button` and `list-prs-for-file` are not aligned to the branch selector

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4229]
1. https://github.com/sindresorhus/refined-github/blob/48dcf91bc6d20e5fde93af139636a3a7cef0e412/source/github-helpers/index.ts 
2. Resize to 800px

<img width="776" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/114391273-7b074700-9bc1-11eb-8ac2-d2fae80b71a1.png">

**Comment by yakov116** [comment]
I think we should hide them

**Comment by fregante** [comment]
hmmm perhaps we should wrap them below the branch selector. If it's gonna wrap onto multiple lines, we might as well make use of the space.
