### ISSUE TITLE
Enable `one-key-formatting` on new issue/PR title

### ISSUE THREAD

**Issue by rly** [sindresorhus/refined-github#4231]
When creating a new issue, the one-key-formatting feature (i.e., select text, press `` ` ``, `"`, etc. to wrap text with symbol) does not work on the body text or title text. You can try it when creating a new issue in this repo. 

It also does not work in the title text for a new PR. Interestingly, it works fine in the PR body and elsewhere (e.g., comments)

https://user-images.githubusercontent.com/310197/114456843-344e2880-9b92-11eb-8d7d-35bfd5a199cf.mp4

**Comment by rly** [comment]
Ah I see that #4115 solves the title issue.

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/cda8197bc35a3b04e4cc2509536cf05c87555b3f/source/features/one-key-formatting.tsx#L40-L42

I _think_ it should just need `isNewIssue` to be added here

**Comment by yakov116** [comment]
> Ah I see that #4115 solves the title issue.

No that was already released https://github.com/sindresorhus/refined-github/releases/tag/21.3.26

We want to enable the feature on another page
