### ISSUE TITLE
Add support for Safari 14 on macOS 10.14.6 through simple build setting change

### ISSUE THREAD

**Issue by gingerbeardman** [sindresorhus/refined-github#4234]
Please activate support for Safari 14 on macOS 10.14.6 in the Refined GitHub Safari Extension.

As previously mentioned https://github.com/sindresorhus/refined-github/issues/3686#issuecomment-734803755 support for Safari 14 on macOS 10.14.6 was promised/planned, but it has not materialised in the extension released on the Mac App Store.

Adding this compatibility is a simple build setting change to target 10.14. This requires no additional testing or maintenance and in my personal experience shipping extensions for Safari 14+ this sort of build process works as advertised.

Thank you!

**Comment by sindresorhus** [comment]
The thread you linked to doesn't, as far as I can see, include any promise or comment about planned 10.14 support.

---

> This requires no additional testing or maintenance

This is not entirely true. It's likely it will have the same behavior, but Safari behavior can differ between OS versions. For example, it seems https://github.com/sindresorhus/refined-github/issues/4216 only happens on macOS 11.

---

My main concern with supporting macOS 10.14, is that later this year, Apple will release macOS 12 and Safari 15, and I doubt Safari 15 will be compatible with macOS 10.14. This means that if we support macOS 10.14 now, and Safari 15 includes new API's/fixes, we will not be able to take advantage of those without dropping macOS 10.14 support, and if we drop support for 10.14 then, users will complain using negative reviews (happens all the time with my apps, super annoying).

**Comment by sindresorhus** [comment]
I'm going to leave the decision to @fregante.

**Comment by gingerbeardman** [comment]
Thanks for the reply. 

I linked to the specific comment where a contributor promised 10.14 support (it's one of the minimised comments but it can be expanded to be read).  Here is a screen grab:

![E321736C-6DAF-477A-A8C0-6D4C7063AE9E](https://user-images.githubusercontent.com/49612/114890172-b0e73e00-9e02-11eb-8c30-b015fda23290.jpeg)

That said, I don't quite follow your reasoning for not adding Safari 14 support. It seems to be based on unknowns and presumptions about what the future may or may not hold. What about here and now?

**Comment by fregante** [comment]
Contributor != collaborator. Lautis has been maintaining a Safari fork for the past few years and that still works and hopefully will continue working everywhere.

- Mojave is already 2 years old 
- Apple won't be releasing Safari 15 for it this summer, as is usual. You can already see that [the next beta version](https://developer.apple.com/safari/download/) is only available for Catalina and Big Sur
- Safari 14 is already holding us back and forcing to keep old dependencies so when 15 comes out, we'll drop 14. Which means dropping Mojave support anyway (due to Apple).

I thought supporting Mojave was going to be straightforward but Apple doesn't make it so. The homebrew version still works anyway, so it's best to use that on old systems.

**Comment by fregante** [comment]
> minimised comments, not sure why,

Because that issue is about auto-publishing to the store, not a generic Safari support discussion issue.

**Comment by gingerbeardman** [comment]
Thanks for the reasoning. Somewhat disappointing, but I understand.

**Comment by gingerbeardman** [comment]
Just wanted to put a few more thoughts down on this that I had whilst making some tea. 

- Safari 15 won't be publicly released until ~ October. That's 6 months away, which means we're half way between major releases right now. Enough time to continue Safari 14 support in all places it can be (Mojave, Catalina, Big Sur)
- If Safari 14 support will be dropped by this project as soon as possible, the worry about bad reviews on the Mac App Store is inevitable
- It seems like the project target users balance is tipped towards cutting edge users rather than widest userbase
- To support Mojave is a single drop-down change in the project build settings
