### ISSUE TITLE
`clean-conversation-sidebar` is broken

### ISSUE THREAD

**Issue by SimonBrandner** [sindresorhus/refined-github#4238]
Extension enabled:
![Screenshot_20210414_080246](https://user-images.githubusercontent.com/25768714/114661762-d0457480-9cf7-11eb-8bb4-921cfccb6521.png)
Extension disabled:
![Screenshot_20210414_080311](https://user-images.githubusercontent.com/25768714/114661792-df2c2700-9cf7-11eb-97fa-6ffde73f49eb.png)

Extension version: 21.4.13
FF version: 78.9.0esr

Note: Sorry if I am missing something here :sweat_smile:

**Comment by SimonBrandner** [comment]
Ah, solution is to disable this: 

![Screenshot_20210414_080824](https://user-images.githubusercontent.com/25768714/114662219-97f26600-9cf8-11eb-851d-3466abb5977a.png)


But still seems like a bug to me. At least if I have triage access to the repo at question, I don't expect that to be hidden. Please correct me if I am wrong though

**Comment by yakov116** [comment]
Hmm looking at the code I don't think that should happen.

Are you able to copy the DOM here?

**Comment by SimonBrandner** [comment]
[Here](https://pastebin.com/63HAS7uv) you go

**Comment by yakov116** [comment]
Thanks

I dont see the `.discussion-sidebar-item` selector there 😕 

Can you do $('.discussion-sidebar-item') in the console (with the ext off) and copy that elements DOM?

**Comment by SimonBrandner** [comment]
[Here](https://pastebin.com/5GdZbD59). Thanks for looking into this, btw!

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/blob/36425c2c174fe04352a29e0f886f6930c40a6738/source/features/clean-conversation-sidebar.tsx#L68

Did not fully debug but it looks like the selector here _maybe_ `.sidebar-assignee `

**Comment by fregante** [comment]
Maybe this has something to do with how we detect "can user edit repo" since it's a "all or nothing" check. As you can see, you Projects section does not have a gear icon, but collaborators do 
<img width="310" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/114746457-fb70a800-9d79-11eb-8b7b-4e37c0a7d0df.png">

**Comment by fregante** [comment]
I don’t think it's enterprise only. Triage is a type of collaborator

**Comment by yakov116** [comment]
I would try to fix it. Do you have a repo you can add me on to debug?

**Comment by yakov116** [comment]
@fregante can you reenable and disable via hotfix?

**Comment by fregante** [comment]
I'm not sure I understand

**Comment by yakov116** [comment]
We commented out the line

**Comment by fregante** [comment]
What's the situation on this feature? Is it still completely broken? I think there's no difference between how it is now and "hotfixing" it

**Comment by yakov116** [comment]
Correct but hotfixing it will allow users to know it was disabled and why.
