### ISSUE TITLE
`default-branch-button` feature breaks the branch switcher

### ISSUE THREAD

**Issue by jack1142** [sindresorhus/refined-github#4240]
Here's a GIF:
![2021-04-14_17-05-04](https://user-images.githubusercontent.com/6032823/114733456-a2861d00-9d43-11eb-8746-4eef2a9884cb.gif)
And a link to the place where this can be reproduced:
https://github.com/File-New-Project/EarTrumpet/blob/2.1.8.0/README.md

**Comment by yakov116** [comment]
I cannot reproduce in chrome

**Comment by yakov116** [comment]
I can only get it on a tag page not a branch.

@cheap-glitch I used your bitsect feature and it works great!! Thanks

**Comment by jack1142** [comment]
> I used your bitsect feature and it works great!! Thanks

I agree, it's awesome :)

**Comment by fregante** [comment]
Also a bug here 
<img width="332" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/114745747-2eff0280-9d79-11eb-9143-2c0a597658d2.png">

**Comment by jack1142** [comment]
That was already reported in #4239 so I didn't mention it :)

**Comment by fregante** [comment]
What the heck of a bug is this 😂 I don't understand how can this happen. Nothing in the dom seems to change on mousedown

**Comment by Araxeus** [comment]
#4370 has a tiny bit more details on how to reproduce this if needed
