### ISSUE TITLE
Wiki: Show number of pages.

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4246]
There are many repos that have wiki enabled, yet they don't have anything in there.

Ideally, I'd prefer the wiki index below everything else, in the main repo page.  
![image](https://user-images.githubusercontent.com/38327267/114880875-fe0ee400-9df1-11eb-9c3a-5ebd7a74d540.png)

***

Though, here I'm proposing a number counter for the wiki.  
ex URL: https://github.com/koalaman/shellcheck

Before:  
![image](https://user-images.githubusercontent.com/38327267/114881125-3dd5cb80-9df2-11eb-8ba1-ab8b3d4fdcd6.png)

After:  
![image](https://user-images.githubusercontent.com/38327267/114881349-72e21e00-9df2-11eb-9a1c-d0a311ce47e2.png)

**Comment by kidonng** [comment]
I don't think this is useful its own, but perhaps we can add the number or hide the Wiki Tab if it's empty, just like `hide-zero-packages`.

**Comment by jtagcat** [comment]
I wrote a nice detailed thing and the tab crashed with oom. :^)

The number is useful on it's own, showing whether you should bother with the wiki (is the project likely to have a 4-question FAQ or full documentation in the wiki).

> Ideally, I'd prefer the wiki index below everything else, in the main repo page.

I did a mockup.

![image](https://user-images.githubusercontent.com/38327267/116051484-2efbde00-a668-11eb-878a-170fecee568b.png)

The problem is that the wiki is likely to break the scroll-along of the other content. Giving up on aesthetics, it could be placed on the left side:

![image](https://user-images.githubusercontent.com/38327267/116051990-bcd7c900-a668-11eb-8df5-cf73d7891df5.png)

On screens wide enough, it could be an additional column:

![image](https://user-images.githubusercontent.com/38327267/116051875-9ade4680-a668-11eb-9a85-5373bf15dbff.png)

**Comment by yakov116** [comment]
FYI this is only possible via fetchDom there is no API for it

**Comment by fregante** [comment]
> Ideally, I'd prefer the wiki index below everything else, in the main repo page.

That's a bit much, we can't add that
