### ISSUE TITLE
Fork button: Show if fork already exists.

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4253]
![image](https://user-images.githubusercontent.com/38327267/115150447-f781a600-a057-11eb-81e6-f0eb8a5e0777.png)

 - If the fork button would redirect you to your repo, then indicate it, with something like 'Forked', instead of 'Fork'.
 - The 'Fork' button may open the 'select an org' menu. Split? the button, so you could jump directly to your already existing fork.

**Comment by fregante** [comment]
This actually already exists, it's called `forked-to`

The only handicap is that it will only show a button _after_ you open your own fork. This is to avoid making an unnecessary API request on every single repo you open.

**Comment by jtagcat** [comment]
In that case, it seems that the feature doesn't work for me. I have added a personal token, the feature is enabled, and visited my fork, and refreshed the fork's parent's page.

**Comment by jerone** [comment]
Confirmed on Firefox.

Wen enabling debug checkbox of showing all page enable features, `forked-to` is not in that list.

**Comment by jerone** [comment]
Any page; this issue page, repo root, single file, PR, ...

**Comment by jerone** [comment]
I see some work being done on this feature, but for me it still doesn't work.

Test: this repo.

Current situation:

![](https://user-images.githubusercontent.com/55841/115922864-bafde200-a47d-11eb-848f-d5390fa615f5.png)

I expected to see a drop-down with 2 results:

![](https://user-images.githubusercontent.com/55841/115922955-d36dfc80-a47d-11eb-8791-f8eb9c4a7822.png)

Feature is enabled in options.

Clearing cache did nothing.

Latest version installed.

No error in console.

Interestingly this feature does **not** appear in the console of enabled features, at all.

_Refined GitHub: 21.4.23_  
_Firefox 88.0_

**Comment by fregante** [comment]
Can you clear the cache? One bug I definitely noticed is:

1. Create your first fork
2. Visit it
3. The button will now appear on the source
4. Create a new fork in an org
5. Visit it
6. The button will stay a button, it won't be updated to a list

Clearing the cache shows the dropdown correctly.

**Comment by jerone** [comment]
Visiting one of the forks for this repo did create the dropdown again.

**Comment by fregante** [comment]
Yes. That's how this feature works and it's in my first comment. Closing this feature request. A new issue can be opened for the bug I described above

**Comment by kidonng** [comment]
> Yes. That's how this feature works and it's in my first comment. 

Guess I'm not the only one just knowing this (well, I didn't seem that feature's code).
Is this piece of information mentioned elsewhere? Or should it be added to the description?
