### ISSUE TITLE
Move `Settings` tab to `more-dropdown`

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4255]
I went looking for repo settings under `more-dropdown`, and couldn't find it. Settings is not accessed frequently, definitely not in the middle of other tabs.

![image](https://user-images.githubusercontent.com/38327267/115150852-aecaec80-a059-11eb-8d38-8133b579d1fd.png)

**Comment by yakov116** [comment]
I don't think this is something we want, the settings should always be available.

**Comment by fregante** [comment]
> not in the middle of other tabs

Ideally it should be before the Releases tab but since that tab might take a second to appear we preferred appending it to the list instead of moving the Settings tab and cause layout shift
