### ISSUE TITLE
Can't click (on tabs) while `more-dropdown` is open.

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4256]
https://github.com/sindresorhus/refined-github/issues/new?assignees=&labels=bug&template=bug_report.md

While more-dropdown is open/activated:
![image](https://user-images.githubusercontent.com/38327267/115150927-13864700-a05a-11eb-8330-60c080c2228c.png)

You can't click nor middle-click tabs such as Code, Issues, reponame, github 'jump to', or anything else.

I get that it makes sense to have a click to dismiss, yet I'd expect to be able to click something on the other side of the screen.

**Comment by fregante** [comment]
That's how every dropdown works on the site, they're set up as lightboxes

**Comment by jtagcat** [comment]
_It's not a bug, it's a feature!_
