### ISSUE TITLE
`clean-conversation-sidebar` broken

### ISSUE THREAD

**Issue by premnepak** [sindresorhus/refined-github#4258]
CHROME Version 90.0.4430.72 (Official Build) (64-bit)

Installed the Chrome Extension and it is not working. I am getting the below console error. (It is a private repo). 

Refined GitHub → clean-conversation-sidebar → TypeError: Cannot read property 'remove' of undefined
    at clean (refined-github.js:6568)
    at runFeature (refined-github.js:1942)
    at setupPageLoad (refined-github.js:1955)
    at refined-github.js:1988 
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'remove'%20of%20undefined

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60clean-conversation-sidebar%60%3A%20Cannot%20read%20property%20'remove'%20of%20undefined
		
logError @ refined-github.js:1923

![image](https://user-images.githubusercontent.com/44958378/115310239-97a70e80-a1c1-11eb-8d1d-366f209be5aa.png)

**Comment by yakov116** [comment]
Yup, Looks like they are removing all the class names and making the generic

**Comment by fregante** [comment]
We’ll have to use select().closest() to find them. Each block likely has a form element with a URL that ends in /assignees or something

**Comment by fregante** [comment]
Actually that form and `.js-*` classes *might* appear only when you’re a collaborator/triager. If there are no specific classes we might have to find each section via textContent 😟

**Comment by yakov116** [comment]
I see `aria-label="Select milestones"` on for example `https://github.com/sindresorhus/got/issues/1306`

**Comment by fregante** [comment]
Indeed each section has either the form itself, even when not editable, or some identificative class 🎉
