### ISSUE TITLE
`first-published-tag-for-merged-pr` finds the third-last tag

### ISSUE THREAD

**Issue by jean** [sindresorhus/refined-github#4259]
I noticed that one PR showed a tag that's not the `last-child` on the `.../branch_commits/...` page. 
This is on a private repo, and I haven't noticed this on a public repo. I'll look out and update if I do.

![35e36d15cb9fa5f06d91e915dbb412c2b75deb47](https://user-images.githubusercontent.com/84800/115343419-18700580-a1d6-11eb-8437-f19db809adb2.png)
![63d9ab78169c0fe2b7824a7e2d87239cd2b7c1ea](https://user-images.githubusercontent.com/84800/115343423-19a13280-a1d6-11eb-841b-7bf342a1a34b.png)

**Comment by yakov116** [comment]
We will heed a real URL to be able to look into it

**Comment by fregante** [comment]
This sounds like a cache issue. Try clearing the cache at the end of Refined GitHub’s options page.

**Comment by fregante** [comment]
Temporarily closing for lack of URL as asked by issue template.
