### ISSUE TITLE
`ci-link` is broken

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#4260]
Github now lazy loads the commit checks 😢 

<img width="208" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/115506971-b383e080-a2a5-11eb-9fbf-3a51b36dfbc0.png">

**Comment by yakov116** [comment]
@fregante are we going to accept 2 API requests for this?

If someone wants to reverse engineer the request it does not look too hard.
`https://github.com/sindresorhus/refined-github/commits/checks-statuses-rollups`
We have all the DOM (after the first fetchDom) needed for the second request.

**Comment by fregante** [comment]
I disabled the feature for everyone via `hotfix`

To fix this I think we only need to update the selector to use the new `batch-deferred-content` element
