### ISSUE TITLE
On Firefox, refined-github is a CPU sink

### ISSUE THREAD

**Issue by andreasabel** [sindresorhus/refined-github#4263]
I noticed that on a freshly restarted Firefox, having some page on `github.com` open used 50-100% of a CPU.  Closing the `github` page fixed this.  This got me the idea that `refined-github` is to blame, and indeed, switching off the extension also fixed the problem.

This is unfortunate, since I enjoyed the extra functionality that `refined-github` gave me.

Versions:
- Firefox 87.0 on Mac OS X Mojave
- refined-github: 21.4.13

**Comment by fregante** [comment]
Please try running “Find feature” at the bottom of the options page to identify the offending feature

**Comment by fregante** [comment]
This might have been the fastest comment I’ve ever left. 😂 I opened the issues page and you had just submitted this issue 😃

**Comment by andreasabel** [comment]
Wow, binary search through the features, I am thrilled!
I repeated the search 4 times, these are the results: 
> The change or issue is caused by ci-link.
> The change or issue is caused by bypass-checks.
> The change or issue is caused by ci-link.
> The change or issue is caused by ci-link.

So I suppose I made a mistake the second time, and the winner is ci-link.

**Comment by yakov116** [comment]
on github.com plain?! Or when going into a repo?

**Comment by yakov116** [comment]
Also is more likely to be `bypass-checks`. Can you try to disable that feature in the options and see if you have the issue?

**Comment by andreasabel** [comment]
Well, I tried switching off for both features.  It is when I switch off `ci-link` that I get a clear drop in Firefox CPU usage.

**Comment by yakov116** [comment]
It there a URL you can provide that I can test it?

**Comment by andreasabel** [comment]
I had edited my comment to say that the page we are seeing is the test page.  
However, I am not testing under lab conditions since I have quite a few Firefox tabs open.  I need to switch to a clean session to confirm the experiment.

**Comment by yakov116** [comment]
`ci-link` is broken but it should not be causing any issues. Very interesting.

**Comment by fregante** [comment]
It might be causing issues specifically because it’s broken, but it seems strange nonetheless, it just fetched a page and appends a dom element. On what URL does this happen? Does it happen on every repo on every page of the repo? We need a URL

**Comment by cheap-glitch** [comment]
I'm seeing something similar on my system (Arch Linux), although not quite as drastic. With a single idle tab opened to any repo page and `ci-link` disabled, Firefox's CPU usage oscillates around 10%. When `ci-link` is enabled it's around 20%, with spikes over 30% (even though no interaction is performed at all). And from what I can see, a single thread is responsible for almost 50% of that usage.

**Comment by fregante** [comment]
For now I disabled `ci-link` for everyone since it's broken anyway #4260. If you still see CPU issues related to RG please comment again.

**Comment by Krzmbrzl** [comment]
I also experience this. I have disabled ci-link for now to see if that indeed fixes the issue.

However I would say that this ticket should stay open until the CPU issues are either fixed or ci-link is removed/deactivated by default :point_up: 

One thing to note though: For me the ci-link stuff did work quite well (except for the CPU issue)

**Comment by jdreesen** [comment]
After today's update RGH is using very much CPU, too. But this happens unregulary and I'm not yet sure what the cause is.

I'm using Firefox 88.0 with Ubuntu 18.04.

**Comment by Krzmbrzl** [comment]
I'm also using Firefox 88.0 but on Ubuntu 20.04

**Comment by Krzmbrzl** [comment]
So disabling ci-link did not solve the issue for me.

Something seems to get caught in an endless loop when loading a new GitHub page (in a new tab), preventing the page from loading. During that time the CPU usage goes to 100%.
The page can only be loaded by temporarily disabling the RG addon or by retrying to open that page in a new tab (several times).

Is there a way to figure out what script is causing the seemingly endless loop?

**Comment by jdreesen** [comment]
I haven't seen this behavior anymore lately... maybe it has been fixed with `21.5.10`?

**Comment by Krzmbrzl** [comment]
> Refer to #4343

Thanks for the hint. The issue described there does indeed seem to be the same thing I am experiencing :+1:
