### ISSUE TITLE
`edit-readme` button is misplaced, when readme contains no headings

### ISSUE THREAD

**Issue by anko** [sindresorhus/refined-github#4269]
Screenshot:

> ![shot](https://user-images.githubusercontent.com/5231746/115797060-4c644a00-a3d3-11eb-96da-a1240396f6b9.png)

I think the edit button with the pencil icon should be in the top right.

Example pages where the bug manifests:

 - https://github.com/theam/aws-lambda-haskell-runtime
 - https://github.com/ThomasTerp/LunkyBox

Example where everything is fine, despite the document not starting with a heading: https://github.com/scottrogowski/mongita  (Presumably OK because the document contains headings later on.)

Reproduces in FF and Chrome. Extension version 21.4.13.

- - -

Probably related to https://github.com/sindresorhus/refined-github/issues/4157.

**Comment by kidonng** [comment]
In the no TOC variant page `.Box-title` is now wrapped in a flexbox, which breaks `edit-readme`.
