### ISSUE TITLE
Unread count in notification page

### ISSUE THREAD

**Issue by AshikNesin** [sindresorhus/refined-github#427]
Right now unread count in notification page doesn't include the things we bookmarked using "Mark as unread" button.

Don't we need to include that too ? @sindresorhus @hkdobrev 

![image](https://cloud.githubusercontent.com/assets/4201088/26029065/14576f32-384a-11e7-987b-bdf55c46e7ce.png)

**Comment by hkdobrev** [comment]
👍 This is similar to #292. Looks like we don't take into consideration these manually unread notifications in quite a few places.

**Comment by AshikNesin** [comment]
Will work on this issue & #292 tomorrow :)

**Comment by AshikNesin** [comment]
Have fixed it and submitted PR (https://github.com/sindresorhus/refined-github/pull/428 )
