### ISSUE TITLE
`vertical-front-matter` is broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4273]
https://github.com/sindresorhus/refined-github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

No errors in the console. Tested in Safari

<img width="1027" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/115965754-d1c33800-a554-11eb-954b-c1253645bd5f.png">

**Comment by kidonng** [comment]
There's no more `[data-table-type="yaml-metadata"]`. I wonder how should we handle this. Perhaps always format first `.markdown-body > table`?
