### ISSUE TITLE
`fit-textareas` causing major performance issue when typing in PR description textarea with Chrome

### ISSUE THREAD

**Issue by with-heart** [sindresorhus/refined-github#4275]
With the `fit-textarea` feature enabled in `refined-github@21.4.23`, I'm experiencing a severe performance degradation when typing in a PR description textarea. Each letter appears to be taking ~500ms to be handled, making the feature unusable as it takes multiple seconds for a few words to appear.

Performance profile shows this line taking 1.5s per call:
![image](https://user-images.githubusercontent.com/1954752/115977908-18f7fb80-a54a-11eb-998f-02e0ed55facb.png)

Disabling the `fit-textarea` feature removes the delay.

I've uploaded the Chrome performance profile json file here: https://gist.githubusercontent.com/with-heart/f0d3b0914d2c25e6f635d82f91404e10/raw/af6e016d11ddf07e73a4459a6f40b1cc4ad58885/refined-github-performance-profile.json

This issue appears to be related to #4266.

**Comment by fregante** [comment]
Is this something that changed in the last release? Can you post a link to an affected PR? I see this
<img width="615" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/115984801-1f7e8580-a5d3-11eb-9a02-ee668f20a035.png">

**Comment by SimenB** [comment]
I'm seeing the same thing. E.g. in https://github.com/facebook/jest/pull/11033, but it happens in every PR for me (although the lag/delay gets worse the larger the diff is)

**Comment by fregante** [comment]
I'll revert this change in the next release, let's see how it will be.

The strange part is that `.scrollHeight` was actually in the previous version as well. This version was supposed to improve performance since it no longer resets the whole textarea every time: https://github.com/fregante/fit-textarea/pull/15

I reopened https://github.com/fregante/fit-textarea/issues/14

**Comment by kylemh** [comment]
I'm also seeing it a PR review comment textarea. It seems very heavy onFocus, onBlur, and on key stroke.

![Screen Shot 2021-04-26 at 8 50 24 AM](https://user-images.githubusercontent.com/9523719/116112496-784e2c80-a66c-11eb-9fd1-49c7795bdb64.png)

**Comment by yakov116** [comment]
We are going to revert the change in the next release.

**Comment by fregante** [comment]
Feature disabled via hotfix for the time being
