### ISSUE TITLE
`view-last-pr-deployment` is not spaced correctly on editable PRs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4277]
<img width="333" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/115997615-e8799580-a60d-11eb-89b3-956c1de0f011.png">

In my case the PR was https://github.com/npmgraph/npmgraph/pull/75

It's only missing a single space character

**Comment by kidonng** [comment]
I must say the native gap between `Edit` and `Open with` is too small, compared to others:
![image](https://user-images.githubusercontent.com/44045911/116002802-fa6b3080-a62d-11eb-9bac-23d68c15bdb6.png)
