### ISSUE TITLE
Excalidraw editing

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4278]
Hi! 

[excalidraw](https://excalidraw.com) is essential for a lot of teams, and maybe a GUI that when viewing a file that ends with `.excalidraw` you get a neat gui like excalidraw's gui. They have a react component: [view here](https://www.npmjs.com/package/@excalidraw/excalidraw) which might work good!

Thank you, and keep up the great work!

**Comment by kidonng** [comment]
https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765382

**Comment by Milo123459** [comment]
But then why not enable it by default? It would be something much more helpful then just viewing a long json file imo.

**Comment by busches** [comment]
This is a very specific feature and the majority of users likely will not use it, thus it should be in it's own extension.

**Comment by yakov116** [comment]
Do you mean to have it enabled on https://github.com/vadimdemedes/excalidraw-ui/blob/master/ui.excalidraw file?

**Comment by Milo123459** [comment]
> Do you mean to have it enabled on [https://github.com/vadimdemedes/excalidraw-ui/blob/master/ui.excalidraw](https://github.com/vadimdemedes/excalidraw-ui/blob/master/ui.excalidraw?rgh-link-date=2021-04-25T17%3A21%3A51Z) file?

Yes

**Comment by kidonng** [comment]
> But then why not enable it by default?

Sorry for the confusion, I'm trying to say it makes sense as a default *feature* for everyone.

> It would be something much more helpful then just viewing a long json file imo.

IMO, more file formats support is beyond the scope of Refined GitHub. And there's just too many formats out there.

**Comment by Milo123459** [comment]
> > But then why not enable it by default?
> 
> Sorry for the confusion, I'm trying to say it makes sense as a default _feature_ for everyone.
> Oh ok
> > It would be something much more helpful then just viewing a long json file imo.
> 
> IMO, more file formats support is beyond the scope of Refined GitHub. And there's just too many formats out there.

Ah, ok, do you know of any web extensions that does something like this? Ie, support for editing excalidraw / rendering files?

**Comment by kidonng** [comment]
Not to my knowledge, sorry. It's best to stick to the official website for now.
