### ISSUE TITLE
Add an option to rename branch for "Propose changes" field

### ISSUE THREAD

**Issue by Andre601** [sindresorhus/refined-github#4285]
## Feature
When you want to make quick changes to a Repository without having push rights does GitHub offer to "Propose changes" which results in a fork being created and the commit being made to that fork.

However, there is no way for you to define your own branch name when proposing changes and the branch name is always set to a specific pattern.

My feature request is to make Refined GitHub add the radio buttons you usually have for when committing changes to a Repo you have push rights on (The one where you can choose to either commit to the current branch or create a new one from it).

## Reason
The fact that the branch names are always in the form of `:username-patch-:number` is kind of frustrating. While it can be a quick and dirty way to propose changes for minor typos, corrections or similar is it still sad that there is no option to actually name your own branch, which often is a crucial part of making pull requests as the branch can give a quick info about what it is. Or perhaps the repository follows a strict naming pattern for branches and deny any patch branch in the process.

## Example
Here is a before and after example of how the "Propose changes" field may look like when committing changes for a Repo you don't have push rights for.

*Before:*
![image](https://user-images.githubusercontent.com/11576465/116262315-b6d10d80-a778-11eb-865e-da60aa0c38c4.png)

*After:*
![image](https://user-images.githubusercontent.com/11576465/116262246-a9b41e80-a778-11eb-9ac3-83d388db3f07.png)

**Comment by fregante** [comment]
I checked and:

- There's no existing hidden field for the branch name
- Copying the branch name field from another page doesn't seem to work from a simple try

Maybe the form needs to be customized further to allow this. Further exploration needed. PR welcome if you'd like to try.

🤷‍♂️

**Comment by fregante** [comment]
No big deal, just let it be patch-1 or just use Codespaces

**Comment by Andre601** [comment]
> No big deal, just let it be patch-1 or just use Codespaces. We can't add all the features 😅

Or - and that is the option I now chose - make a GitHub feedback: https://github.com/github/feedback/discussions/5696

**Comment by cheap-glitch** [comment]
Looks like this was implemented by GitHub?

![image](https://user-images.githubusercontent.com/46634000/143008830-aab0b1ca-d767-407d-a0b7-fca8103a581b.png)

**Comment by yakov116** [comment]
Ate you on a fork or something you have access to? This issue was about a fork.

**Comment by Andre601** [comment]
> Looks like this was implemented by GitHub?
> 
> ![image](https://user-images.githubusercontent.com/46634000/143008830-aab0b1ca-d767-407d-a0b7-fca8103a581b.png)

You misunderstood my issue here...
What you're showing is for when you make changes in a Repo you have write access. My issue is about when you edit a file on a repo you do **not** have write access...
Like go to any repo on the github org and edit a readme there, you'll see this text box at the bottom:
![image](https://user-images.githubusercontent.com/11576465/143034662-2f3f065f-7458-49a1-939a-78e4137b3101.png)
