### ISSUE TITLE
`rgh-feature-descriptions` is not detected by the bisect feature

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#4288]
If I run the bisect functionality, e.g. for https://github.com/sindresorhus/refined-github/blob/main/source/features/action-used-by-link.tsx, the box that showcases the feature is not detected, neither on all-yes, neither on all-no responses.

**Comment by sindresorhus** [comment]
// @cheap-glitch

**Comment by fregante** [comment]
Oh you're referring to `rgh-feature-description`. Features named `rgh-*` can't be disabled as they only run on this repository.

**Comment by stdedos** [comment]
Sounds about right.

Something still that should be searchable on the extension and noted on the bisecter, since I cannot know about those things otherwise by myself ...
Unless I start opening tickets like this one that is 😛

**Comment by fregante** [comment]
> I start opening tickets like this one that is

That's fine, we generally don't receive many issues so we don't complain about requests or duplicates.

Now I wonder why you were searching that specific feature though

**Comment by stdedos** [comment]
Because I am ever-curious, I cannot navigate the https://github.com/sindresorhus/refined-github/tree/main/source (it's not that flat), and I usually people don't appreciate _tickets like that_ 😛.

Also e.g., for the tab-size feature, searching didn't help:
![image](https://user-images.githubusercontent.com/133706/116365917-6a381180-a80e-11eb-9db3-d4604a21c740.png)

If a search returns more that ~20 results, the probability I'll try to dig in myself (instead of asking) decreases significantly.

**Comment by fregante** [comment]
> Also e.g., for the tab-size feature, searching didn't help:

Tiny CSS features are in https://github.com/sindresorhus/refined-github/blob/main/source/refined-github.css

**Comment by kidonng** [comment]
> Unless I start opening tickets like this one that is 😛

You are not alone #4163

It's not searchable/bisectable in the extension itself, because it doesn't appear in `README.md`, which the feature list is generated from.

---

However I think we do need a place/document to explain some Refined GitHub magic/internals, as I occasionally see questions like this (even myself have these questions sometimes). Besides, some features' description don't cover more details, like https://github.com/sindresorhus/refined-github/issues/4253#issuecomment-822021725 and #4289.

**Comment by fregante** [comment]
Closing this specific issue as per

> Oh you're referring to [`rgh-feature-descriptions`](/sindresorhus/refined-github/blob/main/source/features/rgh-feature-descriptions.tsx). Features named `rgh-*` can't be disabled as they only run on this repository or are deemed innocuous easter eggs.



> However I think we do need a page/document/whatever to explain some Refined GitHub magic/internals

Opened https://github.com/sindresorhus/refined-github/issues/4485

**Comment by fregante** [comment]
> However I think we do need a page/document/whatever to explain some Refined GitHub magic/internals

Opened https://github.com/sindresorhus/refined-github/issues/4485
