### ISSUE TITLE
Cannot find the feature that reduces tabs' size to 4 spaces, nor change it

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#4289]
On the frontpage https://github.com/sindresorhus/refined-github/ it says
> Reduces tabs’ size to 4 spaces instead of 8.

but I cannot find such feature from the Extension search.

Neither can the bisect search find it.
Also, can it be configurable? The `ts` parameter https://github.com/isaacs/github/issues/170#issuecomment-40763086 still works

**Comment by fregante** [comment]
This is a CSS-only feature, it can be disabled with the CSS field or https://github.com/lukechilds/github-custom-tab-size

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/1244

**Comment by stdedos** [comment]
It would be nice if:
* that was detectable by the Extension's "search feature"
* there was some note on the bisect plugin, and
* the links on the front page lead to the feature Readme, rather than "just" an image URL that cannot be connected to anything

**Comment by fregante** [comment]
> * that was detectable by the Extension's "search feature"

We have many tiny CSS-only features that aren't disableable. Showing them in the list will just prompt more issues to ask for them to be disabled. I'd rather not mention this anywhere. Tiny fixes are just added and not documented, like https://github.com/sindresorhus/refined-github/blob/44f4ddc09618b2dadea8ff1a7aa19380708f2e1a/source/refined-github.css#L58


> * the links on the front page lead to the feature Readme

If we find a neat way to do that, yes. We already have that information hidden on every line

https://github.com/sindresorhus/refined-github/blob/44f4ddc09618b2dadea8ff1a7aa19380708f2e1a/readme.md#L110

**Comment by stdedos** [comment]
Well, given all the above, I am fine as-is 😀
