### ISSUE TITLE
`done-and-close` Notifications: Mark as done and close tab.

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4293]
Before:
![image](https://user-images.githubusercontent.com/38327267/116402349-d5d4ab80-a81b-11eb-911d-e1b53753f0c9.png)
After:
![image](https://user-images.githubusercontent.com/38327267/116403237-dae62a80-a81c-11eb-8f73-2b9246714364.png)
(icon FF Photon, not final at all)

Goes well with 'open 30 in new tabs'.

A kb shortcut would be very nice as well. Instead of Ctrl-w, I have to click done, wait for some indication, that the request was received (often I just switch to the next tab, then later check and close them), and close the tab.  
The kb-shortcut could be small on the button as well.

**Comment by fregante** [comment]
Closing the tab should already be super easy since your hand is most likely already on the keyboard. Not worth adding extra UI
