### ISSUE TITLE
The buttons added by `faster-pr-diff-options` don't include the current URL hash

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#4298]
`https://github.com/ShareX/ShareX/compare/v13.4.0...master#files_bucket`

Github mangles URL: https://github.com/ShareX/ShareX/compare/v13.4.0...master#files_bucket

**Comment by fregante** [comment]
Can you explain more what's happening and what you expect? The link you posted is broken by GitHub, and is unrelated to that button

**Comment by stdedos** [comment]
If I press the "No Whitespace" button on the Files tab, I expect to end up again on the Files tab (and not the first one)

**Comment by fregante** [comment]
Gotcha.

1. Visit `https://github.com/ShareX/ShareX/compare/v13.4.0...master#files_bucket`
2. Click `No Whitespace`
3. This opens: `https://github.com/ShareX/ShareX/compare/v13.4.0...master?w=1`
   Instead of `https://github.com/ShareX/ShareX/compare/v13.4.0...master?w=1#files_bucket`
