### ISSUE TITLE
Account switcher thumbnail next to the text

### ISSUE THREAD

**Issue by ionutvmi** [sindresorhus/refined-github#43]
I think it looks better to have the icon next to the text in the account switcher button

Before: http://puu.sh/noPzl/03c424d342.png
After: http://puu.sh/noPph/e7fe675c88.png

Should I make a PR for this ?

**Comment by paulmolluzzo** [comment]
@ionutvmi These are the same images.

**Comment by ionutvmi** [comment]
Sorry about that. I have updated my post.

**Comment by sindresorhus** [comment]
Yeah, that looks better. PR welcome :)
