### ISSUE TITLE
Open Fork button leads to dead page when Fork is deleted

### ISSUE THREAD

**Issue by Oliver-Saer** [sindresorhus/refined-github#4301]
Just noticed a small bug after deleting my fork of this repository - the quick open button next to the 'Fork' button is still present but leads to a dead page.

## Template Questions
1. A REAL URL where the bug appears. If it happens on a private repo, find an equivalent public URL.
A. https://github.com/sindresorhus/refined-github (in the state my GitHub profile is in)

2. A screenshot/video/gif of the issue, if it’s visual.
A. https://streamable.com/xmlo6f

3. Any related errors in the browser’s console, if any.
A. N/A

**Comment by fregante** [comment]
It's the cache. Either that happens or we have to query the fork at every page load.

**Comment by fregante** [comment]
Also please follow the template instead of including its instructions
