### ISSUE TITLE
Add a Gitstalk link on user profile page

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4305]
[Gitstalk](https://gitstalk.netlify.app/) is a nice little web app that shows a user's recent activities. Lately I've been using it a lot, so I'm wondering if it makes sense to add a link to it on user profile pages, such as at the bottom of the left side: 
![image](https://user-images.githubusercontent.com/44045911/116738958-b4dfa680-aa25-11eb-95bb-3977cbc24c52.png)

**Comment by fregante** [comment]
I like the tool but I don't like making stalking easier 😅

**Comment by kidonng** [comment]
Hmm, that's fine. Just roll my own script...
