### ISSUE TITLE
Show `useful-not-found-page` on https://github.com/404

### ISSUE THREAD

**Issue by bl-ue** [sindresorhus/refined-github#4308]
Visit https://github.com/aldjksfaslkfjh/asdflkasldk and you'll see this:

<img width="336" alt="Screen Shot 2021-04-30 at 8 16 31 PM" src="https://user-images.githubusercontent.com/54780737/116764994-1afe0680-a9f1-11eb-89e1-fa7e0bc5c24a.png">

But https://github.com/aldjksfaslkfjh doesn't have that useful info:

<img width="274" alt="Screen Shot 2021-04-30 at 8 16 39 PM" src="https://user-images.githubusercontent.com/54780737/116765000-22251480-a9f1-11eb-8594-842e184d5d8c.png">

It would be cool to show the username crossed out when trying to visit the user profile of a user that doesn't exist.

**Comment by kidonng** [comment]
> It would be cool to show the username crossed out when trying to visit the user profile of a user that doesn't exist.

That doesn't provide any extra info.

**Comment by bl-ue** [comment]
Of course not, you're right.  But the inconsistencies bothers me.

**Comment by yakov116** [comment]
> That doesn't provide any extra info.

Don't think we need to add any info here.

Thanks for the request
