### ISSUE TITLE
Indicate yesterday/tomorrow in `user-local-time`

### ISSUE THREAD

**Issue by bl-ue** [sindresorhus/refined-github#4309]
Would it be possible to add something like `(Yesterday)` or `(Tomorrow)` if the user's local time is a different day than my own?

Btw, `user-local-time` is definitely one of my _favorite_ rgh features!! ❤️

**Comment by fregante** [comment]
I'd either show -1/+1 like booking sites do, or the day of the week, so "10:00 PM Friday"

**Comment by kidonng** [comment]
The timezone info is already present in the title:
![image](https://user-images.githubusercontent.com/44045911/116771123-8987a680-aa7b-11eb-9179-849125d5b44c.png)

Maybe we can make it shorter:

![image](https://user-images.githubusercontent.com/44045911/116771227-411cb880-aa7c-11eb-8c54-f0ebbd2739e9.png)

Or even:

![image](https://user-images.githubusercontent.com/44045911/116771217-33ffc980-aa7c-11eb-808a-3a9be884ae26.png)

**Comment by bl-ue** [comment]
I like both ideas.  Is it possible to configure a specific feature?  I'd love to be able to switch between one mode or the other.

**Comment by fregante** [comment]
-1/+1 would indicate the date difference, not the timezone. We have already gone over this in the original PR and indeed the actual timezone is already present in the tooltip. The tooltip includes an extra piece of information too: When was this updated?

**Comment by bl-ue** [comment]
> Or even (which I prefer):
> 
> ![image](https://user-images.githubusercontent.com/44045911/116771217-33ffc980-aa7c-11eb-808a-3a9be884ae26.png)

I agree, it looks good.  But for people who aren't in GMT time, it's not that helpful.  I'd like it if it showed _their GMT offset - my GMT offset_, so in this case (+7) - (-4) = +11.

**Comment by bl-ue** [comment]
> Maybe we can make it shorter:
> 
> ![image](https://user-images.githubusercontent.com/44045911/116771227-411cb880-aa7c-11eb-8c54-f0ebbd2739e9.png)

Yeah, tha looks good!  I don't think the full date being in their is materially useful, but it is definitely annoying to see it broken up on two lines.

**Comment by yakov116** [comment]
> or the day of the week, so "10:00 PM Friday"

I like this one.

**Comment by fregante** [comment]
> I'd like it if it showed _their GMT offset - my GMT offset_, so in this case (+7) - (-4) = +11.

This is probably why we avoided placing a number there, it was just confusing and "relative". If we put "+11" is it relative to me or relative to GMT?

If we show the day of the week it avoids every ambiguity.

**Comment by bl-ue** [comment]
>If we put "+11" is it relative to me or relative to GMT?

Relative to me, because I can easily imagine "11 hours ahead of me", but "7 hours ahead of GMT" is not so intuitive (at least for me).

>If we show the day of the week it avoids any ambiguity.

True.  That's fine with me (although I'm attached to the idea of the relative differe said above :)
