### ISSUE TITLE
Transform text to Markdown links by pasting

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4310]
I did a brief searching and didn't find this request, so here I am.

Many text editors supports transforming text to Markdown links by pasting, for example, if I select `GitHub` and paste `https://github.com`, it becomes `[GitHub](https://github.com)`.

This can already achieved by pressing <kbd>ctrl</kbd>/<kbd>cmd</kbd> + <kbd>k</kbd> then pasting, but it can be a nice addition to `one-key-formatting` (or its own feature).

**Comment by fregante** [comment]
Not a bad idea, GitHub already seems to do it in a few cases, for example when you copy an image from internet and paste it, it will automatically generate the right markdown code.

The problem for us is that to do this we need access to the clipboard, which means adding an extra "This extension will be able to read your clipboard" permission, which is pretty scary.

**Comment by kidonng** [comment]
> The problem for us is that to do this we need access to the clipboard, which means adding an extra "This extension will be able to read your clipboard" permission, which is pretty scary.

I see some applications (for example Notion) achieves this without asking clipboard permission. Is this because they have control of the text field or some magic? Are browser extensions limited to use those methods?

**Comment by fregante** [comment]
> Are browser extensions limited to use those methods?

We had some limitations that required us to use `clipboardWrite` at some point but they were lifted because we no longer have that permission. It might be worth a try, but then we still have another problem: GitHub already handles some pastes, so we need to make sure we don't override them. For example:

1. Right-click on this image <img width="77" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/118354855-44916300-b597-11eb-9213-df4247a0b583.png">
2. Click "Copy image"
3. Paste into a field, you will already get markdown

**Comment by fregante** [comment]
I’m a bit conflicted on this one. It seems to make sense and not require a markdown parser to get this right, but also the same is achievable with a single additional key press:

``` diff 
+ ctrl k
  ctrl v

**Comment by KSH-code** [comment]
I guess that if [using paste event](https://developer.mozilla.org/en-US/docs/Web/API/Element/paste_event), it does not need edit programtically

**Comment by fregante** [comment]
Rereading this thread, I think it’s not worth the many “just one problem”

**Comment by fregante** [comment]
@KSH-code

> To override the default behavior (for example to insert some different data or a transformation of the clipboard contents) an event handler must cancel the default action using event.preventDefault(), and then insert its desired data manually.

**Comment by KSH-code** [comment]
Thanks for my misunderstanding to be corrected.

**Comment by fregante** [comment]
Done: https://github.blog/changelog/2021-11-10-linkify-selected-text-on-url-paste/

**Comment by kidonng** [comment]
THAT'S ILLEGAL

**Comment by fregante** [comment]
As I has previously suggested, this is possibly the most annoying "feature" GitHub implemented EVER and I honestly want to break it. Absolutely awful. I can't paste anything normally in the text box anymore.
