### ISSUE TITLE
`release-download-count`: filter downloads

### ISSUE THREAD

**Issue by jtagcat** [sindresorhus/refined-github#4311]
Ex URL: https://github.com/sharkdp/hyperfine/releases/tag/v1.11.0

Add a button to toggle between sorting alphabetical and download count order.

Note: there were issue templates, are they broken or gone?

**Comment by fregante** [comment]
> Note: there were issue templates, are they broken or gone?

Where did you click? They're here: https://github.com/sindresorhus/refined-github/issues/new/choose

<img width="597" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/116820144-aae0b380-ab9d-11eb-8d61-868b40ede661.png">

**Comment by jtagcat** [comment]
Ah, I didn't click anywhere. URL bar: 'refined issues', and added `/new`, ending up with `https://github.com/sindresorhus/refined-github/issues/new`. I'll go feedback to gh.

**Comment by jerone** [comment]
If not implemented here, it might be a good candidate for https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-sort-content

**Comment by kidonng** [comment]
> download count order

Then you are tend to get e.g. Windows assets sorted before Linux/macOS, x64 assets sorted before x86.

Maybe something like "only show assets for current/specific platform" could be a useful alternative, not related to this issue though.

**Comment by jtagcat** [comment]
That'd need either fzf or pre-made buttons.

Ctrl-f is quite fast, except I'd wish I could recursively search within a search (search for say rpm, and then 64)

**Comment by jtagcat** [comment]
I feel like filtering is too much work to be worth it. It needs a long list of include-exclude lists, UX work, revisions, etc.
