### ISSUE TITLE
`dim-bots` hides GitHub Actions commits

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4318]
https://github.com/fregante/github-url-detection/commits/master?after=e58ce98ffd6a45822d035598eda8f699e1839f06+1&branch=master

<img width="414" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/116993708-09bf3d80-ad02-11eb-863c-e93a84aca8db.png">

Notice the 4.11.0 commit being dimmed.

**Comment by fregante** [comment]
While GHA commits are made by a bot, maybe they're "custom" enough that should be excluded from this feature.

**Comment by yakov116** [comment]
I would rather exclude any commit that has a tag associated with it

**Comment by fregante** [comment]
That would be an alternative, but I personally haven't seen "useless" commits by GHA-bot in the wild so maybe my second comment still applies.

**Comment by fregante** [comment]
> "useless" commits by GHA-bot

Well… maybe my example does fit this description. Version commits aren't that useful.

> I would rather exclude any commit that has a tag associated with it

This is sound
