### ISSUE TITLE
Refined Github has been loaded twice

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#4319]
- Vivalid 3.7.2218.52 / Chrome 89.04389
- GHE 3.0.6
- <https://github.com/sindresorhus/refined-github/>-equivalent
- Both with and without token (except delete-repo)

(also edit-readme 21.5.1 fails: `Cannot read property 'textContent' of undefined`, if that has anything to do with that)

**Comment by fregante** [comment]
Thank you for the issue, does this happen on your GHE site? Not on github.com?

**Comment by stdedos** [comment]
I am not signed in on GitHub.com from the computer that browses GHE.

**Comment by busches** [comment]
Noticed the same issue today, only happening on GHE, not GH.

**Comment by yakov116** [comment]
All pages?

**Comment by busches** [comment]
Yes.

**Comment by fregante** [comment]
Confirmed, testing on http://neverssl.com/

Looking into this now. It might just be https://github.com/fregante/content-scripts-register-polyfill
