### ISSUE TITLE
Use blue color for issue links

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#4322]
Unclear whether a bug or intentional by GH, but recently the issue link color have been changed to primary text color. This is a an a11y regression in my opinion as it's hard to see the links at a glance.

Repro: https://github.com/excalidraw/excalidraw/issues/3535#issuecomment-832830138

before: 

![image](https://user-images.githubusercontent.com/5153846/117287815-0dba9f00-ae6b-11eb-8790-38ad63d8097f.png)

current:

![image](https://user-images.githubusercontent.com/5153846/117287831-14491680-ae6b-11eb-8d41-6c670e090e6e.png)

In light mode it's not that bad because the blue link color itself isn't extra visible (which leads me to believe the change was intentional on GH's part), but in dark mode it's noticeable:

previous:

![image](https://user-images.githubusercontent.com/5153846/117287942-3b9fe380-ae6b-11eb-8ba9-0f8617e6d7de.png)

current:

![image](https://user-images.githubusercontent.com/5153846/117286813-f0390580-ae69-11eb-9e3b-f10baac6296c.png)

**Comment by yakov116** [comment]
Get https://github.com/fregante/github-issue-link-status and you never have an issue again 😄

**Comment by fregante** [comment]
I’d advise adding some CSS locally to address this for the time being. It’s kind of a weird choice so they might have something in mind 🤷‍♂️

**Comment by dwelle** [comment]
@yakov116 nice!
@fregante yeah — anyway, I think your extension is the superior solution here :)
