### ISSUE TITLE
Disable automatic PR sort order

### ISSUE THREAD

**Issue by Blackjacx** [sindresorhus/refined-github#4326]
Whenever I click the pull request link on github the extension changes the sort order to `recently updated` but I prefer newest-to-oldest. Is there a way to change this?

**Comment by yakov116** [comment]
Its a feature called `sort-conversations-by-update-time` you can disable it in the extension options.

**Comment by cheap-glitch** [comment]
↑ Note that this will also revert the sort order of issues to the default.

**Comment by Blackjacx** [comment]
Okay I found that but didn't think about that conversations are issue lists :D Thank you lads 👍
