### ISSUE TITLE
Submodule diffs are misaligned

### ISSUE THREAD

**Issue by tacc-wbomar** [sindresorhus/refined-github#4328]
# What?

1. __Primary__: Prevent center-aligned filenames in submodule diff.
2. _Secondary_: If submodule diffs were previously ignored during styling, then reconsider the styling.

# Why?

A center-aligned file path listing is not as easy to scan as is a left-aligned file path listing, because similarities in paths are not aligned as they are in a left-aligned file path listing.

# Where?

https://github.com/TACC/Core-CMS/pull/216/commits/c8b7cbe270ad083dd11d3f81da35cb281fe3d56f

<details><summary>Screenshot while using Github Refined</summary>

![Github Refined](https://user-images.githubusercontent.com/62723358/117503885-3b751600-af47-11eb-98c0-4d27cc640d15.png)

</details>

<details><summary>Screenshot while using Github</summary>

![Github](https://user-images.githubusercontent.com/62723358/117503887-3c0dac80-af47-11eb-94d1-bfc49f405e81.png)

</details>

# How?

__Offending Style__:
https://github.com/sindresorhus/refined-github/blob/8c1ab3125fcdb5edf4d78e86bca2da30da97ca45/source/refined-github.css#L99-L103

__Suggestions__: None

**Comment by fregante** [comment]
This is due to https://github.com/sindresorhus/refined-github/blob/cdebcef8dc30c76cf4fdd4cbea005272704f761f/source/refined-github.css#L99-L103

And the feature: https://github.com/sindresorhus/refined-github/pull/1639

**Comment by fregante** [comment]
Let's try to find a selector that matches this: https://github.com/webpack/webpack/pull/6446/files#diff-4cb0a7248ed91703f66f261958573976e311153c7273acaa2f6960be6dd84e98

But doesn't match this: https://github.com/TACC/Core-CMS/commit/c8b7cbe270ad083dd11d3f81da35cb281fe3d56f#diff-00db495ec685cbdb37dc9dfede576323eb49fd5d4156be453590c5b7650bb9e6

If it doesn't exist, we can only override the text centering via `:root .file .data.empty *` or something, but that won't fix everything

**Comment by harshgoel05** [comment]
Can I take this up?

**Comment by yakov116** [comment]
Sure

**Comment by harshgoel05** [comment]
![image](https://user-images.githubusercontent.com/48649088/122075487-bd464200-ce17-11eb-8d02-6b9218517929.png)


I'm able to shift the table by overwriting `text-align: center;` to `text-align: left;`
```
:root .file .data table {
	padding: 54px;
	text-align: left !important;
}
```

But the `Submodule taccsite_custom updated 9 files` isn't overwriteable as the class of [TACC/Core-CMS@c8b7cbe#diff-00db495ec685cbdb37dc9dfede576323eb49fd5d4156be453590c5b7650bb9e6](https://github.com/TACC/Core-CMS/commit/c8b7cbe270ad083dd11d3f81da35cb281fe3d56f#diff-00db495ec685cbdb37dc9dfede576323eb49fd5d4156be453590c5b7650bb9e6) and this clashes.

Is this good to go as this is the best which we can get without much complexity I feel? Any suggestions?
