### ISSUE TITLE
See the differences between a release and the main branch

### ISSUE THREAD

**Issue by dorian-marchal** [sindresorhus/refined-github#4329]
The release page shows a changelog for every release but doesn't let us see the diff between the latest release and the main branch (i.e. the next release).

More precisely, I'd like to have new links on the release page:
- Unreleased commits (commits in `main` missing from latest release): https://github.com/$user/$repo/compare/$tag...master
- Hotfixed commits (released commits but not in `main`): https://github.com/$user/$repo/compare/master...$tag
- "Real" files changes between the latest release and `main`: https://github.com/$user/$repo/compare/$tag..master

As I'm writing this, I notice that this may not be relevant for all git flows (e.g. the ones where the main branch always match the latest release) but maybe there is a clever way to make this feature helpful to everyone?

Some examples of release pages:
- https://github.com/Mottie/GitHub-userscripts/releases (simple raw tags)
- https://github.com/sindresorhus/refined-github/releases (full featured releases with title and description)
- https://github.com/phoenixframework/phoenix/releases (collapsed releases)
- https://github.com/elixir-lang/elixir/releases (pre-releases)

Currently, I use a simple userscript to do that but it has some issues and I'd love to see this feature baked in Refined Github:

```js

// ==UserScript==
// @name         Get next release changelog
// @match        https://github.com/*
// @grant        GM_registerMenuCommand
// ==/UserScript==

// Caveats:
// - only works for tags (not full featured releases).
// - doesn't work with "folded" releases (e.g. https://github.com/phoenixframework/phoenix/releases)
// - hardcoded "master" branch.

const goToCompareUrl = (getRange) => {
  const latestTag = document
    .querySelector(".release-entry .release-entry .commit-title a")
    .innerText.trim();
  window.location.href = window.location.href.replace(
    /\/releases/,
    `/compare/${getRange(latestTag)}`
  );
};

GM_registerMenuCommand("Files changes (..)", () => {
  goToCompareUrl((tag) => `${tag}..master`);
});
GM_registerMenuCommand("Unreleased commits (...)", () => {
  goToCompareUrl((tag) => `${tag}...master`);
});
GM_registerMenuCommand("Hotfixed commits", () => {
  goToCompareUrl((tag) => `master...${tag}`);
});
```

**Comment by busches** [comment]
> - Unreleased commits (commits in `main` missing from latest release): https://github.com/$user/$repo/compare/$tag...master

This already exists, but only when on a specific release it seems, example: https://github.com/sindresorhus/refined-github/releases/tag/21.5.1 shows "11 commits to main since release" right now. 

> - Hotfixed commits (released commits but not in `main`): https://github.com/$user/$repo/compare/master...$tag

How do you know what tag to use here? This seems hard to make generic.

> - "Real" files changes between the latest release and `main`: https://github.com/$user/$repo/compare/$tag..master

You get this view with some scrolling from the first link or a new tab when there's a lot of changed, e.g. https://github.com/phoenixframework/phoenix/compare/v1.5.3...master

Like you said, this likely isn't generic to all users of GitHub, except maybe the first bullet. I think the userscript you have makes the most sense, but let's see what others thing.

**Comment by yakov116** [comment]
> I think the userscript you have makes the most sense, but let's see what others think.

👍

**Comment by fregante** [comment]
GitHub already has one of those links in 1 click and let's you pick one of the others in 2 clicks. $tag is arbitrary and dependent on the repo so if you have to *pick* it you can just do so with the dropdown GitHub provides next to each release.
