### ISSUE TITLE
Show "Pulse" item in "Insights" dropdown

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#433]
The "Pulse" item in the new "Insights" dropdown menu seems to be hidden by this extension.

**Comment by sindresorhus** [comment]
We should also ensure `Insights` is the last item.

**Comment by jgierer12** [comment]
> We should also ensure Insights is the last item.

@lukaszklis could do that in #432

**Comment by sindresorhus** [comment]
Actually, nevermind. It was already handled by #432.

**Comment by hkdobrev** [comment]
So we should just remove the code which hides the Pulse tab, right?

**Comment by sindresorhus** [comment]
Yes
