### ISSUE TITLE
No word wrap in 'Suggested change' diffs in PR reviews

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#4337]
I've noticed in PR reviews, that 'Suggested change' diffs are displayed with word wrap.
*The word wrap is applied by GitHub itself.*

I believe it would be more convenient if there was no word wrap, but a scrollbar, to easier spot the differences between the lines.
In other words, to be just like it's on linked diff to the upper part of the screenshot:

Example URL:
https://github.com/sindresorhus/refined-github/pull/4336#discussion_r628897301

Screenshot:
![2021-05-09_185458](https://user-images.githubusercontent.com/723651/117578676-1c69b600-b0f8-11eb-8bb5-044ab3287594.jpg)

**Comment by yakov116** [comment]
Had this same issue many times!
I happen to love this idea but would love a check box 'Wrap Diff' since this can VERY annoying in many cases.

**Comment by fregante** [comment]
We actually used to have a feature that would apply softwrapping like that everywhere I think

**Comment by yakov116** [comment]
https://github.com/sindresorhus/refined-github/issues/2729 `indented-code-wrapping`.
