### ISSUE TITLE
`fit-textareas` isn't enabled on discussions

### ISSUE THREAD

**Issue by aminomancer** [sindresorhus/refined-github#4342]
I think the fit-textareas module needs to add some inline CSS to the textareas to revert the `max-width: 500px` rule on comment boxes, from form-validation.scss line 286. That's all, thanks for the great extension.

**Comment by fregante** [comment]
`fit-textareas` has been disabled in previous version due to https://github.com/sindresorhus/refined-github/issues/4275

What you're seeing is GitHub’s native feature. Ensure you're on the last Refined GitHub version and that `fit-textareas` is not disabled in your settings

**Comment by aminomancer** [comment]
Yeah I'm on 21.5.9. The issues comment box I'm typing in right now seems to expand indefinitely. But when typing responses in discussions or PRs it seems to only expand to 500px height. fit-textareas is still showing up in options.html. I have it enabled currently. So it's doing nothing and github is expanding comment boxes itself?

**Comment by aminomancer** [comment]
Thought I'd mention something else while I'm here. This might be caused by some other incompatibility, but when opening github URLs in new tabs, about 30% of the time the page is stuck loading indefinitely, and Firefox gives me a notification that Refined Github is slowing the browser down, and offering a button to "Stop" the extension. The button callback doesn't disable the extension or anything, and doesn't actually help the page load, so maybe it just destroys the extension's content scripts for that particular tab. The tab doesn't crash either, just gets stuck loading. Next time I notice it I'll try to inspect it a bit and maybe offer some better insight. I didn't notice any similar complaints in here and I do use other github-related extensions and a stylesheet, so I assumed it must be on my end somehow.

**Comment by fregante** [comment]
The freezing issue is https://github.com/sindresorhus/refined-github/issues/4343 and should be fixed in 21.5.10

Where does this fit textareas issue happen exactly? Please post a link to such a page like the issue template requests. Also ideally a gif showing the problem would be super helpful

**Comment by fregante** [comment]
Thanks! Indeed `fit-textareas` isn't un on Discussions.

I opened an issue in the relevant repo: https://github.com/fregante/github-url-detection/issues/78
