### ISSUE TITLE
Enable `copy-on-y` on more pages

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4349]
The feature is currently enabled on commits but it doesn't work on `isPRFiles` for example. 

Example URL: https://github.com/sindresorhus/refined-github/pull/4348/files

Help wanted finding **where else this feature should be enabled**

**Comment by yakov116** [comment]
Guys this is urgent we got 2 requests within 2 weeks!
https://github.com/sindresorhus/refined-github/issues/4290

**Comment by fregante** [comment]
Damn spammers! hahaha

**Comment by fregante** [comment]
Not the first time I do this 😃
