### ISSUE TITLE
Refined GitHub has reached 5000 users on Chrome 🎉 

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#435]
https://chrome.google.com/webstore/detail/refined-github/hlepfoohegkhhmjieoechaddaejaokhf

This is not an actual issue, but just a thread for celebration!

It's amazing when you think that a power-user extension for a single browser for a particular developer-specific website could reach so many users. 😎 

Thanks to @sindresorhus for starting it and all of the collaborators for so actively maintaining it! Also thanks to the 38 contributors and all of the people using it and posting issues, suggestions and comments who helped shape it! ❤️ 

Big thanks to GitHub of course for providing this platform which most of us use every day! Thanks to several of the GitHub staff who have used the extension and chimed in on a specific thread! 🙌 

🎊 🎉 🍾

**Comment by paulmolluzzo** [comment]
Wow! That's awesome! Thanks for highlighting the milestone @hkdobrev!

Thanks to everyone who's contributed!

🎉🙌👏👏👏

**Comment by sindresorhus** [comment]
🙌✨
