### ISSUE TITLE
Watch shows count when clicked

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4351]
[repo](https://github.com/Discord-Datamining/Discord-Datamining)
![img](https://salvage.is-inside.me/S4Zqu8DJ.png)

it shouldn't show the count, that's all

**Comment by yakov116** [comment]
Why? That is how the feature is intended to work.

**Comment by Milo123459** [comment]
Oh, maybe an option that does what I'm suggesting? Always hide the count?

**Comment by yakov116** [comment]
You can add some custom CSS to override it

**Comment by fregante** [comment]
This is a compromise I picked in order to hide the count but still keep it accessible somehow. I’d have done the same for the fork count if the DOM allowed it
