### ISSUE TITLE
Error from extension app

### ISSUE THREAD

**Issue by gingerbeardman** [sindresorhus/refined-github#4353]
## Reproduce
1. I open the extension app and I get the error.
2. If I dismiss and  click the blue button to "Quit and Open Safari..." and I the same error again.

## Error

> The operation couldn’t be completed. (SFErrorDomain error 1.)

<img width="492" alt="Screen shot 2021-05-12 at 12 35 10" src="https://user-images.githubusercontent.com/49612/117968799-7fd52d00-b31e-11eb-8945-ff8e235efb5c.png">

## Setup

- Big Sur 11.3.1 (20E241)
- Safari 14.1 (16611.1.21.161.6)
- Refined GitHub 21.5.9

**Comment by sindresorhus** [comment]
Can you try running the below command in the terminal, restart your computer, and then launch Refined GitHub again?

```
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f /Applications/Safari.app
```

**Comment by gingerbeardman** [comment]
That worked even without restarting the computer.

After I issued the command Safari showed a banner to activate some extensions, including Refined GitHub.

Cheers!

**Comment by fregante** [comment]
@sindresorhus didn't the app include a custom message to handle this specific issue?

**Comment by sindresorhus** [comment]
@fregante Yes, it was not shown until after the error message. Fixed now: https://github.com/sindresorhus/refined-github/commit/db73952af994eba4debf3aa084a4d06aec8ec948

**Comment by gingerbeardman** [comment]
I just got this again on a fresh download.

I did not see the custom message, just the error.

<img width="420" alt="Screen shot 2022-06-22 at 16 12 46" src="https://user-images.githubusercontent.com/49612/175066641-04d552d8-5b52-4d9c-ad54-83f4b74a0ec7.png">
