### ISSUE TITLE
`table-input` and others don’t appear when creating PRs

### ISSUE THREAD

**Issue by Araxeus** [sindresorhus/refined-github#4356]
Missing Control Buttons:
* Table
* Image
* Collapsible Content

### Shows up when:
* Creating issues
* Commenting on pull requests and issues

### Doesn't show up when:
* **Creating a PR** (thats when I need it the most 😢)
* Creating/Commenting in discussions (less important)

----

See Example below:
(PR creation and comment side by side, missing buttons highlighted)

![https://github.com/AlexTorresSk/custom-electron-titlebar/pull/150](https://user-images.githubusercontent.com/78568641/118069705-4bf51880-b3ad-11eb-8cd1-d9f8b3d9b97a.png)

> [screenshot source](https://github.com/AlexTorresSk/custom-electron-titlebar/pull/150) (shouldn't matter)

**Comment by fregante** [comment]
hmmm I see it both when creating PRs and when editing them (as in your screenshot)

<img width="809" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/118094441-ee86b900-b3f8-11eb-9e90-13082eaa036d.png">

<img width="817" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/118094467-f8102100-b3f8-11eb-86d6-33681e0e69a4.png">

**Comment by Araxeus** [comment]
Ok thats really weird, it happened to me multiple times, and you can see in the screenshot that It actually happened somehow..

But now I can't reproduce this bug in PR creating again, and I have no idea how it happened in the first place

> Table + Collapsible content still doesn't show up in discussions but I guess that's expected

So ill be closing this issue
Thanks for all the hard work on this extension 🙂

**Comment by fregante** [comment]
You have a screenshot so it certainly happened 😃 let us know if you figure out when it happens or how to replicate it.
