### ISSUE TITLE
Prevent discussion comment link loss

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#4357]
_Originally posted by @smichel17 in https://github.com/streetcomplete/StreetComplete/issues/2283#issuecomment-840723380_:

> There is one annoying bug where GitHub's auto-shorten feature messes up if you have any query params. So, `https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707` gets shortened to https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707 and links the top-level discussion instead of [#2789 (comment)](https://github.com/streetcomplete/StreetComplete/discussions/2789?sort=top#discussioncomment-646707) (this link created manually).

* `…/discussions/2789?sort=top#discussioncomment-646707` → `#2789` :x:
* `…/discussions/2789?sort=top` → `#2789` :x:
* `…/discussions/2789#discussioncomment-646707` → `#2789 (comment)` :heavy_check_mark:
* `…/discussions/2789` → `#2789` :heavy_check_mark: 

Maybe this case could be added to `prevent-pr-commit-link-loss`? (And rename the feature to `prevent-link-loss` then?)

**Comment by yakov116** [comment]
If accepted I would make it its own feature and just export common items. That feature is complex enough as it is.

**Comment by fregante** [comment]
It doesn’t look too complex, I think it can be improved. For example the 2 existing replacement regexes could be joined with regex-join (plus 1 more regex coming here) so the condition would be just one. 

Maybe the “complex” part would be matching the DOM.

I don’t mind duplicating the feature to get started, but it can probably be merged once it’s ready.
