### ISSUE TITLE
Add button to interact with Dependabot

### ISSUE THREAD

**Issue by mainrs** [sindresorhus/refined-github#4359]
Not sure if this fits into Refined GitHub, but this is my idea: Have a dedicated button to quickly interact with Dependabot (like rebasing, merge, reopen etc.).

I'd imagine it to be a button either on the top of the page or inside the reply editor (although I'd say top of the page makes more sense).

The button could be conditionally added to PRs that are actually opened by the bot.

![top](https://user-images.githubusercontent.com/5113257/118295014-a68c9280-b4db-11eb-8e5e-3f753db40315.png)

---

![comment](https://user-images.githubusercontent.com/5113257/118295021-a8565600-b4db-11eb-8c6c-f3dbe6080217.png)

**Comment by busches** [comment]
Not sure it fits as part of RGH, as not everyone is going to use it. Renovate does their PRs in a way that allow for easy retries/rebases IMO, that or a user script may solve your issue.

**Comment by SirWindfield** [comment]
My reasoning behind it was that, since Dependabot is officially part of GitHub now, it would make sense and justify the inclusion of such functionality (compared to Renovate, which is a third party service).

Feel free to close the issue if you think it doesn't fit :)

**Comment by fregante** [comment]
Probably best handled by a dedicated extension since there are a number of useful features it could have.
