### ISSUE TITLE
`sticky-sidebar` z-index issue

### ISSUE THREAD

**Issue by Araxeus** [sindresorhus/refined-github#4363]
Self explanatory

(lowering the `z-index` of the sticky header from 90 to 1 seems to fix that specific problem)

Example:
![image](https://user-images.githubusercontent.com/78568641/118348701-c9a75880-b554-11eb-9e96-b07dc9fcd38a.png)

**Comment by fregante** [comment]
Thanks for the report! I will be fixed by #4364
