### ISSUE TITLE
Change gist creation dropdown to 2 separate buttons

### ISSUE THREAD

**Issue by Araxeus** [sindresorhus/refined-github#4366]
Similar to other already existing tweaks (draft PR), 
Separate "Public Gist" and "Secret Gist" to 2 buttons instead of 1 button and a dropdown.

Gist creation dropdown example:
![image](https://user-images.githubusercontent.com/78568641/118351161-ed719b00-b562-11eb-8b24-16b267e3266a.png)

**Comment by fregante** [comment]
This feature should be almost a copy-paste of separate-draft-pr-button

If you do copy-paste, please review every line to ensure it still makes sense.

**Comment by darkred** [comment]
I made PR #4382
