### ISSUE TITLE
File tree gets hidden when loading a repo

### ISSUE THREAD

**Issue by deanylev** [sindresorhus/refined-github#4367]
Since this morning, if I load any repo the file tree gets hidden as soon as the page is done loading. The issue is resolved as soon as I disable Refined GitHub.

![image](https://user-images.githubusercontent.com/22049511/118417110-fcd51d80-b6f5-11eb-8a59-f95531f818e9.png)

**Comment by fregante** [comment]
Click the expandable button where the commit line appears. If you leave it closed, it remembers its position https://github.com/sindresorhus/refined-github/issues/3588

**Comment by deanylev** [comment]
Embarrassing, sorry

**Comment by fregante** [comment]
No worries! Thanks for opening an issue
