### ISSUE TITLE
Long GitHub user name in two lines lead to broken design on PR-overview page

### ISSUE THREAD

**Issue by mobilutz** [sindresorhus/refined-github#4373]
With active `refined-github`, a long github username sometimes lead to broken layout in PullRequest views, see screenshot.
This occurs even more often, when the PullRequest is against the non default branch, as then the PullRequest row has more information in it.

I am often seeing this in a private repository, so I changed the HTML on the refined-github PullRequest overview page so create the screenshot.
https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc

![Screenshot 2021-05-19 at 12 11 47](https://user-images.githubusercontent.com/491877/118796536-fda7b400-b89b-11eb-81d2-f4f2c59bf9a0.png)

**Comment by fregante** [comment]
This is what it looks like without Refined GitHub, this is not caused by us

<img width="1344" alt="Screen Shot 2" src="https://user-images.githubusercontent.com/1402241/118806256-0b2b6100-b8d1-11eb-8373-63516422149d.png">

**Comment by mobilutz** [comment]
🤦🏻  I thought I tested that without refined-github ...

Then lets close this issue.

**Comment by fregante** [comment]
Related https://github.com/sindresorhus/refined-github/issues/4405
