### ISSUE TITLE
Add button towards flatgithub.com

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4375]
- A button to view the flat data if there is a flat action in the repo, opens a new tab with flatgithub.com/user/repo
- Whenever you open data affected by flat data, view it like flatgithub.com would
- URL: https://github.com/githubocto/flat-demo-bitcoin-price/blob/main/btc-price.json
- URl: https://github.com/githubocto/flat-demo-bitcoin-price/blob/main/btc-price-postprocessed.json

More info: https://octo.github.com/projects/flat-data

**Comment by fregante** [comment]
Please fill in the issue template

**Comment by Milo123459** [comment]
My bad, can you please reopen this issue?

**Comment by kidonng** [comment]
I thought this is another random GitHub integration, and then I saw it is developed by GitHub 😅 so perhaps the best way is to suggest GitHub supporting it.

For the time being though, you can use _the universal integration bookmarklet_:

```js
javascript:window.open(`https://some.github.integration.website/#${location.pathname.split('/').slice(1, 3).join('/')}`)
```

**Comment by fregante** [comment]
So it seems that this is a glorified JSON/CSV viewer + separate updater part. I assume GitHub will add their own button at some point, it's rather strange that they haven't already.

I don't think Flat GitHub is going to be particularly popular outside of a few data circles, so adding an extra `fetch` for the `flat.yml` file would be unnecessary noise for most.

We could add it if there's a simple indicator that the current file is compatible with Flat GitHub and can benefit from being seen there.

Indicators could include:

- larger file size (the linked files don't seem to be useful at all in the Flat Viewer)
- file path including `flatdata` or flat-data` anywhere

---

Here's another example repo https://github.com/the-pudding/data with data that looks great in the viewer: https://github.com/the-pudding/data/blob/master/census-history/full_data.csv

**Comment by fregante** [comment]
I don’t think it's common/useful enough. Even GitHub decided against it until now
