### ISSUE TITLE
Extension sometimes fails to run when custom CSS is injected

### ISSUE THREAD

**Issue by cheap-glitch** [sindresorhus/refined-github#4376]
I've recently added some custom CSS to hide the "Explore repositories" sidebar on the dashboard. This makes the extension fail regularly with the following error (Firefox 88.0.1, RGH 21.5.19):
```text
TypeError: document.head is null refined-github.js:1913:30
```

The line in question:
https://github.com/sindresorhus/refined-github/blob/83f233677157d21fb6ae11958fa45aa7ee99d65a/source/features/index.tsx#L91

Since this only happens (afaik) when opening new tabs (regardless of the URL), I'm guessing the extension tries to inject the CSS before the `<head>` exists and thus execution stops. This was probably introduced by #4352.

Edit: can confirm the bug goes away when removing the custom CSS.

**Comment by yakov116** [comment]
I also had issues load too fast. I think we should up the delay to 15-20ms

**Comment by fregante** [comment]
Delays never work. We need to check the dom first, that’s it. No timers will fix it. I wonder if we should just use contentScript.register to inject it. It’d be perfect on Firefox but I don’t know about Chrome (polyfilled). Its worth a try

**Comment by yakov116** [comment]
Why dont we just add the css after the while?

**Comment by fregante** [comment]
For the reason described by the issue your original PR solved https://github.com/sindresorhus/refined-github/issues/4312

**Comment by yakov116** [comment]
That was when loading took 220ms now it's about 20-40ms.
To put thing into perspective, I dont see any jump now for any css only feature.
