### ISSUE TITLE
Wrong repo age

### ISSUE THREAD

**Issue by luizfernandonb** [sindresorhus/refined-github#4377]
I just created [a repository](https://github.com/luizstudios/BitConverter) and the extension is showing it as if it had been created 2 years ago
![image](https://user-images.githubusercontent.com/42288418/119060628-f7ebc480-b9a8-11eb-9d2f-7662b48a8efb.png)

**Comment by yakov116** [comment]
Not sure what your doing there. But...

![image](https://user-images.githubusercontent.com/16872793/119060914-2d8caf80-b9a1-11eb-85c5-db46d64d34fc.png)

Do you have this issue anywhere else? Any errors? What version of the extention?

**Comment by luizfernandonb** [comment]
> Not sure what your doing there. But...
> 
> ![image](https://user-images.githubusercontent.com/16872793/119060914-2d8caf80-b9a1-11eb-85c5-db46d64d34fc.png)
> 
> Do you have this issue anywhere else? Any errors? What version of the extention?

I believe that I have no more errors, as this was the only one I found and my version is 21.5.19

**Comment by luizfernandonb** [comment]
![image](https://user-images.githubusercontent.com/42288418/119061343-8745a780-b9aa-11eb-94e2-c5fdbfce182e.png)

**Comment by luizfernandonb** [comment]
I believe that the extension has some kind of cache, because before creating this repository, I had a fork in which its name was exactly the same as this, and before creating this repository I deleted this fork and soon after I created a new one repository in my organization with the same name as the fork, I believe that's it

**Comment by yakov116** [comment]
That would be it,  clear the cache. (extension options all the way on the bottom)

**Comment by luizfernandonb** [comment]
Worked, thank you
