### ISSUE TITLE
More control over news-feed visibility

### ISSUE THREAD

**Issue by vibhavagarwal5** [sindresorhus/refined-github#4379]
It would make sense to give the users more control over whats visible in the github newsfeed
`hide-useless-newsfeed-events` should define more user control if they want to which of the following things: 
- .push, 
- .fork, 
- .delete, 
- .follow, 
- .release

**Comment by yakov116** [comment]
Its simple css. Disable the feature and copy what you would like into the custom css box.

**Comment by vibhavagarwal5** [comment]
I did not know this. Thanks.

**Comment by vibhavagarwal5** [comment]
Ok, I tried pasting modified `https://github.com/sindresorhus/refined-github/blob/main/source/features/hide-useless-newsfeed-events.css` into the "Custom CSS" box but its not working

**Comment by vibhavagarwal5** [comment]
Ok, I tried pasting modified `https://github.com/sindresorhus/refined-github/blob/main/source/features/hide-useless-newsfeed-events.css` into the "Custom CSS" box but its not working

**Comment by yakov116** [comment]
Did you try? 
```css
.news :is(.push, .fork, .delete, .follow, .release) {	display: none !important;}
```

**Comment by vibhavagarwal5** [comment]
I was adding `.rgh-hide-useless-newsfeed-events` as well which was causing the issue.
