### ISSUE TITLE
Highlight issues and PRs from org members

### ISSUE THREAD

**Issue by markspolakovs** [sindresorhus/refined-github#438]
Context: for example, in the [React](https://github.com/facebook/react/pulls) team, much of the work happens via PRs, even by the core team. However, these core team PRs are lost in the long, long list of contributions.

Proposal: highlight PRs that are from members of the repo owning org, Facebook in the example of React.

**Comment by bfred-it** [comment]
I think we'd need an API key for that. This works, except no pagination for orgs with 101+ members:

```js
fetch('https://api.github.com/orgs/facebook/members?per_page=100')
.then(r => r.json()).then(members => {
    $('.opened-by a').each((i, contributor) => {
        if(members.some(m => m.login === contributor.textContent)) {
            $(contributor).parents('.Box-row').css('background', '#eee')
        }
    });
});
```

**Comment by sindresorhus** [comment]
I think we should wait for the GraphQL API. It will make this much simpler to implement.

**Comment by markspolakovs** [comment]
If you mean "wait for it to come out of early access", see https://github.com/blog/2359-introducing-github-marketplace-and-more-tools-to-customize-your-workflow

**Comment by bfred-it** [comment]
It doesn't look like GraphQL simplifies things, from what I understand the only advantage is getting only what's needed as opposed to a big JSON. 

I hoped you could query the visible user names directly but I don't think that's possible.

**Comment by bfred-it** [comment]
This is actually sort of possible in a single GraphQL query:

```gql
query {
  sindresorhus: user(login:"sindresorhus") {
    organizations(first: 100) {
      edges {
        node {
          login
        }
      }
    }
  }
  bfredit: user(login:"bfred-it") {
    organizations(first: 100) {
      edges {
        node {
          login
        }
      }
    }
  }
}
```

This lets you query multiple specific users at once for their organizations.

It still is paginated but I doubt that there are many users that joined more than 100 orgs.

**Comment by DerTieran** [comment]
Just stumbled upon this and if I find the time I will take another look at it, but I see two ways to solve this.

**1. Get all members of an organisation**
This would be the best way if the members could be reused (maybe in the *Author* filter) and/or saved for that repository/organisation context so we only need to get them once.
A query could look like this:
```graphql
query ($org: String!, $cursor: String) {
  organization(login: $org) {
    login
    members(first: 100, after: $cursor) {
      pageInfo{
        hasNextPage
        endCursor
      }
      nodes {
        login
      }
    }
  }
}
```
This would return a list of members and the page information
```json
{
  "data": {
    "organization": {
      "login": "bfred-it-obsolete",
      "members": {
        "pageInfo": {
          "hasNextPage": false,
          "endCursor": "Y3Vyc29yOnYyOpHOABVlgQ=="
        },
        "nodes": [
          {
            "login": "bfred-it"
          }
        ]
      }
    }
  }
}
```
If the passed `$org` isn't an organization the response would be an error/empty.
```json
{
  "data": {
    "organization": null
  },
  "errors": [
    {
      "message": "Could not resolve to an Organization with the login of 'bfred-it'.",
      "type": "NOT_FOUND",
      "path": [
        "organization"
      ],
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ]
    }
  ]
}
```


**2. Test the `organization` connection for each user**
This would mean that we have a list of users we want to test.
Instead of the suggested query of @bfred-it it would also be possible to test for that one `organization`.
```graphql
query ($org: String!) {
  sindresorhus: user(login: "sindresorhus") {
    organization(login: $org) {
      login
    }
  }
  bfredit: user(login: "bfred-it") {
    organization(login: $org) {
      login
    }
  }
}
```
This would return the `organization` or `null` if the user isn't a member
```json
{
  "data": {
    "sindresorhus": {
      "organization": null
    },
    "bfredit": {
      "organization": {
        "login": "bfred-it-obsolete"
      }
    }
  }
}
```
Two problems I can see here are that
1. There is no indication if the `$org` is actually an organization
2. The query can't be build that easily and could lead to problems, e.g. there is a limit to how many users could be request at once (something around 50 when I tested it)

**Comment by bfred-it** [comment]
> 1. There is no indication if the $org is actually an organization

This might need a separate request for each user, perhaps cached forever.

> 2. The query can't be build that easily and could lead to problems, e.g. there is a limit to how many users could be request at once (something around 50 when I tested it)

The PR list only shows 20 PRs at a time, so that's not much of an issue. I built this type of query for my other extension, perhaps you can just copy-paste most of it: https://github.com/bfred-it/github-issue-link-status

**Comment by bfred-it** [comment]
If anyone wants to pick this up:

<img width="427" alt="" src="https://user-images.githubusercontent.com/1402241/48546981-339b0480-e8fc-11e8-97c0-e662545115e6.png">

```css
.rgh-collaborator {
    border: 1px solid #c0d3eb;
    border-radius: 3px;
    padding: 2px 5px;
}
```

```gql
{
  repository(owner: "sindresorhus", name: "refined-github") {
    collaborators(first: 100) {
      nodes {
        login
      }
    }
  }
}
```

```gql
{
  "data": {
    "repository": {
      "collaborators": {
        "nodes": [
          {
            "login": "sindresorhus"
          },
          {
            "login": "hkdobrev"
          },
          {
            "login": "SpaceK33z"
          },
          {
            "login": "kevva"
          },
          {
            "login": "paulmolluzzo"
          },
          {
            "login": "busches"
          },
          {
            "login": "bfred-it"
          },
          {
            "login": "SamVerschueren"
          },
          {
            "login": "jgierer12"
          },
          {
            "login": "DrewML"
          }
        ]
      }
    }
  }
}
```
