### ISSUE TITLE
`user-profile-follower-badge` is misplaced when there are "@"s in the user's bio

### ISSUE THREAD

**Issue by ouuan** [sindresorhus/refined-github#4388]
When there's no "@" in the bio, the "follows you" is in the correct place:

![screenshot](https://user-images.githubusercontent.com/30581822/119246951-71a5cd00-bbb8-11eb-95d2-6049e12c2dda.png)

When there are "@"s in the bio, the "follows you" is placed after the last "@":

![screenshot](https://user-images.githubusercontent.com/30581822/119246989-b29de180-bbb8-11eb-923b-e4225cde2ed8.png)

![screenshot](https://user-images.githubusercontent.com/30581822/119247007-dbbe7200-bbb8-11eb-8099-d09677f78faf.png)

**Comment by fregante** [comment]
Include testable URLs in the issue description, like it was requested by the issue template:

https://github.com/wizardforcel
https://github.com/gaocegege

**Comment by fregante** [comment]
Please include some URLs  in the issue, like the template requests. This helps us determine the cause

https://github.com/wizardforcel
https://github.com/gaocegege

**Comment by fregante** [comment]
The selector in `user-profile-follower-badge` can be changed to select the star icon

**Comment by ouuan** [comment]
> Please include some URLs in the issue, like the template requests. This helps us determine the cause
> 
> https://github.com/wizardforcel
> https://github.com/gaocegege

Sorry, I mistakenly thought that they were not useful because these users may not be following you. I didn't realize that they are still useful without the "follows you".
