### ISSUE TITLE
Deploy to AMO

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#439]
- [x] Initial submit to AMO
  @sindresorhus do you want to submit it yourself? Otherwise I'll do it. Either way you're going to have to create an account on https://addons.mozilla.org/en-US/developers/
- [x] Set up auto-deployment using [web-ext](https://github.com/mozilla/web-ext)
  https://github.com/sindresorhus/refined-github/pull/403#issuecomment-302838065
- [ ] Fix review warnings:
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L26"><code>linkify-urls-in-code.js 26:5</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/linkify-urls-in-code.js#L36"><code>linkify-urls-in-code.js 36:5</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L60"><code>content.js 60:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L62"><code>content.js 62:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">Unsafe assignment to innerHTML <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L284"><code>content.js 284:3</code></a></summary><blockquote>Warning: Due to both security and performance concerns, this may not be set using dynamic values which have not been adequately sanitized. This can lead to security issues or fairly serious performance degradation.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/show-names.js#L5"><code>show-names.js 5:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>
  <details><summary markdown="true">"storage.local" can cause issues when loaded temporarily <a href="https://github.com/sindresorhus/refined-github/blob/master/extension/show-names.js#L9"><code>show-names.js 9:3</code></a></summary><blockquote>Warning: This API can cause issues when loaded temporarily using about:debugging in Firefox unless you specify applications > gecko > id in the manifest. Please see: https://mzl.la/2hizK4a for more.</blockquote></details>

**Comment by sindresorhus** [comment]
@jgierer12 I've submitted it for review and added you as owner on AMO.

@hkdobrev @paulmolluzzo Register on https://addons.mozilla.org/en-US/developers/ and let me know and I'll add you as owners too.

**Comment by paulmolluzzo** [comment]
@sindresorhus Here you go: https://addons.mozilla.org/en-US/firefox/user/paulmolluzzo/

**Comment by bfred-it** [comment]
I can set up the amo autodeployment if you want

**Comment by jgierer12** [comment]
Wow, that was fast!
![:tada:](https://cloud.githubusercontent.com/assets/4331946/26702584/eb793362-4725-11e7-9713-2a24dc7418b3.png)

**Comment by hkdobrev** [comment]
@sindresorhus https://addons.mozilla.org/en-US/firefox/user/hkdobrev/ Thanks!

**Comment by bfred-it** [comment]
Why does the URL contain a dash at the end?

https://addons.mozilla.org/en-US/firefox/addon/refined-github-/
https://addons.mozilla.org/en-US/firefox/addon/refined-github/ ⬅️ doesn't work

**Comment by sindresorhus** [comment]
@bfred-it I had to add a dash as the AMO UI insisted the one without a dash was already taken.

**Comment by bfred-it** [comment]
Can you give [me](https://addons.mozilla.org/en-US/firefox/user/bfred_it/) access to AMO? I can try contacting them

**Comment by sindresorhus** [comment]
@hkdobrev @bfred-it I need the email you used to sign up for the AMO account.

**Comment by bfred-it** [comment]
me@bfred.it

**Comment by sindresorhus** [comment]
Added

**Comment by bfred-it** [comment]
Still missing: #470 (auto-deployment) and #467 (unsafe innerHTML)

**Comment by bfred-it** [comment]
I think we're good for now.
