### ISSUE TITLE
`conflict-marker` doesn't work in Milestone page

### ISSUE THREAD

**Issue by EaseTheWorld** [sindresorhus/refined-github#4391]
I found `conflict-marker` feature quite useful.
I can see conflict icon in pr page
https://github.com/the-tcpdump-group/libpcap/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+milestone%3Anext-release
<img width="885" alt="conflict_marker_in_pr" src="https://user-images.githubusercontent.com/1066923/119283778-0839c300-bc79-11eb-8aad-5aac1d2e86b4.png">

but not in milestone page
https://github.com/the-tcpdump-group/libpcap/milestone/1
<img width="885" alt="no_conflict_marker_in_milestone" src="https://user-images.githubusercontent.com/1066923/119283793-0c65e080-bc79-11eb-9b64-8daa372415ee.png">

**Comment by fregante** [comment]
It should work, our code is set up for that 

https://github.com/sindresorhus/refined-github/blob/b48d3ebfa0ea467aefe5d33741b364212874efbb/source/features/conflict-marker.tsx#L70

https://github.com/fregante/github-url-detection/blob/7347684f872abef509ea44bcae26a6bb18e928e2/index.ts#L117
