### ISSUE TITLE
Filter for the news feed

### ISSUE THREAD

**Issue by andrepolischuk** [sindresorhus/refined-github#44]
What do you think about adding some filter for news feed items? Like this:

![image](https://cloud.githubusercontent.com/assets/8956796/13381819/5d3f44ce-de76-11e5-80c0-197259bc2935.png)

**Comment by paulmolluzzo** [comment]
Nice idea. Are you thinking a toggle for each notification type? Or more like a radio select for only one of a type?

I'd also be considerate of the "More" button and maintaining the illusion that the list is complete from the initial load.

**Comment by sindresorhus** [comment]
Can you elaborate a bit more about the idea? What would be the value of such feature?

**Comment by andrepolischuk** [comment]
I want to separate activities from following users and notifications from repos I'm watching. Or hide notifications from news feed completely without filter buttons. Because:

* I can read notifications in https://github.com/notifications section
* I can't just track starred repos and following users activity due to large number of notifications in the news feed

**Comment by hkdobrev** [comment]
I will totally use this! I want to see pushes and stars separately. These are two independent sources of information for me and I want to use them at a different time for different purposes.

**Comment by sindresorhus** [comment]
> Or hide notifications from news feed completely without filter buttons.

I would be more interested in this. Is there a way to easily detect that?

**Comment by paulmolluzzo** [comment]
What kind of notifications do you mean @sindresorhus? It looks like there's selector overlap between issues and PRs. I also can't tell if a repo that I'm watching is treated differently than if I've starred it, but either way there's a level of granularity that we probably won't get regardless.

I'm seeing classes like this:
* `create` - created repo
* `issue_opened` - new issue
* `watch_started` - someone starred something
* `issues_comment` - new comment on issue
* `issues_closed` - closed issue _or pull request_ but there's an HTML comment and an `aria-label`.
* `push` - someone pushed code

IMO a lot of this is just clutter I won't read and things like people starring and creating repos are really easy to overlook. (Those all have the class `.simple` on the container.) Personally, I don't care much about people pushing to a branch, and just doing a `display:none` on `.alert.push` really cleaned up the list.

**Comment by andrepolischuk** [comment]
> Is there a way to easily detect that?

Notifications from watching repos haves classes: `push`, `issue_opened`, `issues_comment`, `issues_closed`.

I thought to hide this items to make news feed cleaner.

**Comment by lukyth** [comment]
I ran [this gist](https://gist.github.com/lukyth/014f844d7f35b5eaf0bd) on my GitHub homepage to get all feed type I can. After some brute force analysis, here's all I found and my conclusion

`commit_comment`
- Someone commented on a commit in a repository you're watching.

`create`
- People you follow created a repository.  
- Someone created a branch in a repository you're watching.

`delete`
- Someone deleted a branch in a repository you're watching.

`fork`
- People you follow forked a repository.

`issues_closed`
- Someone closed an issue in a repository you're watching.
- Someone closed a pull request in a repository you're watching.

`issues_comment`
- Someone commented an issue in a repository you're watching.
- Someone commented a pull request in a repository you're watching.

`issues_opened`
- Someone opened an issue in a repository you're watching.
- Someone opened a pull request in a repository you're watching.

`member_add`
- People you follow was added to a repository.

`public`
- People you follow made a repository public.

`push`
- Someone pushed to a repository you're watching.

`release`
- Someone made a release in a repository you're watching.

`watch_started`
- People you follow stared a repository.

If I'm not wrong, our notification has the same things as `commit_comment`, `issues_closed`, `issues_comment`, `issues_opened`, `release`. So, we can create a button which will toggle those feed type, or we can create a button to toggle all these things one by one. What do you think?

Please correct me if I got anything wrong! :)

**Comment by hkdobrev** [comment]
Thanks @lukyth! I will gladly use buttons to filter the news feed items to:
- all
- issues & PRs
- releases
- commits
- created/open-sourced a new repo

**Comment by paulmolluzzo** [comment]
That's interesting @lukyth, thanks! You should add the results you wrote to the gist.

I agree with @hkdobrev on the buttons and would add something for when people star a repo. I use that for discovering new repos.

**Comment by hkdobrev** [comment]
:+1: for the stars @paulmolluzzo. Of course we should exclude stars and watching of own repos as @sindresorhus have initially did to reduce his clutter in the news feed.

**Comment by sindresorhus** [comment]
:-1: I honestly don't see the point of littering the UI with filter buttons. When you remove all the noise of stars/forks of your own projects, like we've done, there's not a lot left, and using the filter buttons wouldn't show much or be of much benefit. Remember, we can only filter on what's already in the news feed. For example `releases` will usually be empty. There will be very few `created/open-sourced a new repo`. That leaves `issues & PRs` and `commits`, which I don't really see the point of separating.

Why do you think you need filter buttons? Remember, the best UI is none.

**Comment by paulmolluzzo** [comment]
Ok, but the "weight" of the feed items doesn't match my interest. I don't care for seeing "XXXX pushed to whatever/master" - pushes are sort of worthless if it's not a merge or new PR. Seeing if people I follow starred a repo is too small. If we can address that without extra UI clutter I'm all for it.

What do you think of something like that @sindresorhus? No buttons, hide a few more garbage things, somehow increase the visibility of starring repos.

**Comment by sindresorhus** [comment]
:+1:
