### ISSUE TITLE
Repo tabs doesn't fit when Wiki and Projects tabs are enabled

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#440]
<img width="939" alt="screen shot 2017-05-25 at 14 43 49" src="https://cloud.githubusercontent.com/assets/170270/26440906/9512c24a-4158-11e7-9b3a-db1e9bbf7156.png">

Maybe we should renamed `Insights` to `More` and move `Settings` there too?

**Comment by hkdobrev** [comment]
To clarify they don't fit when you have Issues, Projects and Wiki enabled and Settings available.

**Comment by hkdobrev** [comment]
I'd prefer to remove the Compare tab in these cases. If we do the More drop down suggestion, I'd move Compare in there instead of Settings.

**Comment by sindresorhus** [comment]
How often do you really need Settings though?

**Comment by hkdobrev** [comment]
Well, I use the tab 2-3 times per week on various repositories. However, I am yet to use the Compare tab.

To clarify we'd always have the Compare tab except for cases when you have admin access to a repo with a project.

**Comment by hkdobrev** [comment]
We can consider reducing spacing or using just icons with a shortcut letter just in this case.

**Comment by sindresorhus** [comment]
Ok, let's put Compare in the More dropdown if it doesn't fit.

**Comment by hkdobrev** [comment]
Steps to reproduce for anyone who want to pick this up:
1. Create a repo
2. Go to settings
3. Create a project

**Comment by bfred-it** [comment]
Possible alternatives:

- Shorten Pull Requests to PRs
- Use the "Settings" icon only, no text
- Use the "Graphs" icon for "Insights", no text
