### ISSUE TITLE
`edit-comments-faster` is enabled in discussions even without sufficient permissions

### ISSUE THREAD

**Issue by FloEdelmann** [sindresorhus/refined-github#4400]
In https://github.com/streetcomplete/StreetComplete/discussions/2671, I see an edit icon in all comments, even though I can't actually edit those:

![grafik](https://user-images.githubusercontent.com/202916/119571912-3c64cf00-bdb2-11eb-9dc5-ed6840a0f478.png)

When clicking the button, the edit interface actually appears, but saving reloads the page and drops the changes.

**Comment by yakov116** [comment]
I think you mean `edit-comments-faster`

**Comment by yakov116** [comment]
// cc @darkred

**Comment by darkred** [comment]
I've made PR #4415

**Comment by fregante** [comment]
@FloEdelmann do you know why you cannot edit those comments? I see you're a member. What type of member are you?

**Comment by FloEdelmann** [comment]
I see a "Member" badge in https://github.com/streetcomplete/StreetComplete/issues/2833.

My role in the streetcomplete organization seems to be "member" as well:

> ![grafik](https://user-images.githubusercontent.com/202916/120297205-29c62a80-c2c9-11eb-986b-47a6b5bf31f0.png)

#4415 seems to work fine for me: I see the edit icon button for my own topics and comments, but not for others.
