### ISSUE TITLE
The browse-code/files section is disappearing in Firefox Nightly

### ISSUE THREAD

**Issue by sideshowbarker** [sindresorhus/refined-github#4402]
Browser version: current Firefox Nightly, 90.0a1 (2021-05-25) (64-bit) on macOS.

1. Open https://github.com/sindresorhus/refined-github or any other GitHub repo URL in Firefox Nightly, with Refined GitHub enabled; observe that the entire browser-code/files section disappears, and instead just the README section is shown:

   ![image](https://user-images.githubusercontent.com/194984/119592639-d446d500-be13-11eb-86f2-16842cd916af.png)

2. Open devtools in Firefox Nightly and switch to the **Inspector** tab; observe that, in the `div` previous adjacent sibling of the `readme-toc` element, there’s this descendant `div`:

    ```html
    <div class="js-details-container Details">
    ```

3. Observe that in the styles panel, that `div` element has the following associated stylesheet rule:

    ```css
    .rgh-files-hidden .files, .rgh-files-hidden #files ~ .Details {
        display: none;
    }
    ```
   …like this:

   ![image](https://user-images.githubusercontent.com/194984/119594399-add66900-be16-11eb-9022-e64383b79919.png)

4. Toggle off the Refined GitHub add-on, and observe that the browse-code/files section reappears — and that in the Inspector, that `<div class="js-details-container Details">` element no longer has that CSS stylesheet rule<br>  `.rgh-files-hidden .files, .rgh-files-hidden #files ~ .Details {  display: none; }` associated with it.

5. Switch to the **Console** tab in devtools in Firefox Nightly and, logged there, observe the following:

   > Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). moz-extension:1:5003
   > Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://github.githubassets.com/assets/optimizely-c839a608.js. (Reason: CORS request did not succeed).
   > None of the “sha512” hashes in the integrity attribute match the content of the subresource. refined-github
   > ℹ️ latest-tag-button → The token seems to be incorrect or expired. Update it in the options. index.tsx:53:10
   > ℹ️ repo-age → The token seems to be incorrect or expired. Update it in the options. index.tsx:53:10
   > ℹ️ bugs-tab → The token seems to be incorrect or expired. Update it in the options. index.tsx:53:10

   (I don’t have any idea of those console messages are related at all…)

**Comment by yakov116** [comment]
You clicked on the icon all the way on the left

**Comment by yakov116** [comment]
>(I don’t have any idea of those console messages are related at all…)

They are not they are saying that you have not put in a access token so non of those features are able to run.

**Comment by sideshowbarker** [comment]
> You clicked on the icon all the way on the right

d’oh — I really didn’t even know that icon was there 😬

Thanks much!

**Comment by sideshowbarker** [comment]
> They are not they are saying that you have not put in a access token so non of those features are able to run.

Aha — I thought I had put in the access token, but I guess need to re-do it.

Anyway, thanks again much — I’ll go ahead and close this now
