### ISSUE TITLE
Plain-GitHub and `sticky-sidebar` lead to zindex problem

### ISSUE THREAD

**Issue by mobilutz** [sindresorhus/refined-github#4419]
When adding an emoji at the right site of the textarea box, the GitHub created emoji popup does not play nice with images and dividers in the sidebar, see screenshot.
![Screenshot 2021-05-27 at 16 07 54](https://user-images.githubusercontent.com/491877/119841871-7ba43480-bf06-11eb-8374-c798aed3bbcd.png)

I did try this out without RefinedGitHub and also saw the problem when editing a PR descriptions, so I guess this is not Refined-GitHub related.
![Screenshot 2021-05-27 at 16 09 59](https://user-images.githubusercontent.com/491877/119841937-865ec980-bf06-11eb-896c-6d3bdff00a73.png)

But this addon could fix it in regards of `sticky-sidebar` as the error can occure more often with this addon on.

**Comment by fregante** [comment]
Can't replicate with or without Refined GitHub

<img width="355" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/133895112-1d46363d-59d0-4290-87d0-66a1fad2f5f9.png">
