### ISSUE TITLE
Improve `rgh-linkify-features`

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#4436]
rgh-linkify-features.tsx is implemented for only here repository and supported extension is tsx.
Its function is excellent and convenient.
So I'd like to use auto referencing file in all repositories for any extension.

**Comment by fregante** [comment]
The feature can’t be made generic. We include a list of the feature in the extension itself, it works without any HTTP requests. Linkifying files would mean fetching any `/code` that looks like a URL.

If you have the full path the file, you probably have the URL anyway. 

https://github.com/sindresorhus/refined-github/issues/2176 is a better solution

**Comment by KSH-code** [comment]
@fregante 
Thanks for share the details.
But I think that are a little bit different. My proposal is about link, not the auto completion.
I know what you mean however My work style is, first I write commit message via Sourcetree, second I commit, third I push, then finally create a PR using pushed commit.

So I need the just link about file anyways.
And if proposal is passed, then I'll be in progress.

Do you happen to mean this extension must not use any HTTP request?
