### ISSUE TITLE
Auto update base branch using prefix of compare branch

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#4437]
In general, Most repositories use multiple branches like main, develop or something.

and each branch has a rule for naming of compare branch such as `fix/something-blah`, `chore/blah-typo`

so, My proposal is to set automatically base branch with check prefix of compare branch.

e.g.

- `fix/` is to set to main
- `chore/` is to set to develop

**Comment by KSH-code** [comment]
By the way, that needs to have rule, convention or importing configuration files.

**Comment by busches** [comment]
> By the way, that needs to have rule, convention or importing configuration files.

And it's this complication that makes it not a good candidate for RGH. https://github.com/sindresorhus/refined-github/issues/2960
