### ISSUE TITLE
The  «All Activity» section does not work 

### ISSUE THREAD

**Issue by taqyon** [sindresorhus/refined-github#4438]
# Hey, guys! 
I've been using the extension for a long time, it's super cool! But since I've been using it, I noticed that my all activity section doesn't work. 

As soon as I disable the extension in google chrome settings, the all activity section restores its work. 

I made two videos, put them on google drive, maybe they will help to understand what is wrong? 

### Video

1. [Enabled extension](https://drive.google.com/file/d/1zzd3GNBUIBJjD9M06FHe3FC-Ynbo2wGU/view?usp=sharing)
2. [Disabled extension](https://drive.google.com/file/d/1LRkzYslEkMtU71B1oF0GKjUt4JdiSRQA/view?usp=sharing)

### Pics

<details>
<summary>Details</summary>

![Снимок экрана 2021-06-02 в 18 44 58](https://user-images.githubusercontent.com/14002721/120511076-b6a8db00-c3d2-11eb-92d3-90e7f278a9bc.png)

</details>

### Some tech info
- Browser: 91.0.4472.77
- OS: Mac OS Big Sur 11.4 (20F71)
- Extension version: 21.6.1

**Comment by yakov116** [comment]
Can you disable `hide-useless-newsfeed-events` maybe you have nothing to show?

**Comment by taqyon** [comment]
> Can you disable `hide-useless-newsfeed-events` in the extension settings maybe you have nothing to show?

Yep! It worked! 

Can you please explain what this feature is, before I close the ticket?

**Comment by taqyon** [comment]
Nvm, i see: 
![Снимок экрана 2021-06-02 в 19 15 41](https://user-images.githubusercontent.com/14002721/120515416-f5409480-c3d6-11eb-9a19-4b4455589c40.png)
