### ISSUE TITLE
`copy-file` doesn't work on SVG files

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4451]
~~I thought I reported this already, but I can't find the issue.~~

1. Open https://github.com/sindresorhus/refined-github/blob/main/media/icon.svg
2. Click the "Copy" button
3. Nothing happens, there's no code visible, it should only appear when the raw code is visible

~~We should find other rendered filetypes and make sure they all work the same way so we don't play wackamole.~~

Related: https://github.com/sindresorhus/refined-github/issues/4244

**Comment by fregante** [comment]
Basically a duplicate of https://github.com/sindresorhus/refined-github/issues/2957

**Comment by yakov116** [comment]
You are talking about CSV

**Comment by fregante** [comment]
Yes, this is also a duplicate of https://github.com/sindresorhus/refined-github/issues/4369

**Comment by fregante** [comment]
We should find other rendered filetypes and make sure they all work the same way so we don't play wackamole

**Comment by fregante** [comment]
Fix: Revert the condition.

```py
if there's code on the page
	renderButton()
else if view-markdown-source is applicable
	wait for its events
else 
	return false
```
