### ISSUE TITLE
Auto refresh after changes

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#4454]
<img width="1379" alt="스크린샷 2021-06-10 오후 2 20 12" src="https://user-images.githubusercontent.com/29705162/121469192-043ace80-c9f7-11eb-9d9e-9aec099e62d4.png">

like above, Files changed tab shows `Refresh` after changed branch.
I'd like to refresh automatically after changed branch because I always press down `F5` when it shows.

**Comment by fregante** [comment]
Not a good idea, if I’m on that page I’m looking at the code and I don’t want things to disappear in front of me. GitHub’s solution is right

**Comment by KSH-code** [comment]
Yup, close. 
because this issue is against rule No. 2
