### ISSUE TITLE
Hide releases of starred repositories in news feed

### ISSUE THREAD

**Issue by Scriptim** [sindresorhus/refined-github#4455]
For a few days now, the news feed on the [front page of GitHub](https://github.com/) has been showing me new releases from repositories that I've given a star to. Neither do I follow the developers nor do I watch these repositories.

![Example Release of tiangolo/fastapi in GitHub news feed](https://user-images.githubusercontent.com/13003924/121496040-620ced80-c9da-11eb-9cbc-d703cb095983.png)

These releases take up a lot of space and fill most of the feed. I feel like this is uninteresting noise, especially for minor or even patch version increments.

I'd love to see a feature that completely hides these types of release announcements.

**Comment by fregante** [comment]
I'm not seeing this. Did you disable any Refined GitHub features?

**Comment by Scriptim** [comment]
@fregante 
Oh, I actually had `hide-useless-newsfeed-events` disabled. That feature removes the releases when I enable it.

However, it also removes some other events that I would like to see. It might make sense to split this into multiple features so you can be a bit more granular about which events you want to see. Or would that be undesirable complexity?

**Comment by fregante** [comment]
Indeed, it’s already part of Refined GitHub. If you disable it you can hide each event via CSS on your own.

**Comment by Scriptim** [comment]
As far as I can tell, the release announcements for starred repositories don't have a specific CSS class to address them (and only them).

Anyway, I guess I'll just live with the noise then.

**Comment by akinsho** [comment]
I've just stumbled upon this issue as well trying to find the exact same solution, so this is just a slightly louder plus one. I do think what counts to a user as useless varies, I think the new release addition is infuriatingly loud an dull, but would definitely like to allow other things like stars and follows through (personal preference). It'd be fantastic to get these split out into options or a multiselect of some kind. 

Anyway there's my plus one, alternatively regarding the css solution, is there some way to do this easily across machines? also what exactly is the solution? which class do I hide etc?

**Comment by Scriptim** [comment]
For anyone interested, you can use this custom CSS to significantly reduce the height and noise of the release announcements
```css
#dashboard div.news div.release > div.body > div.d-flex {
	align-items: center !important;
}

#dashboard div.news div.release > div.body > div.d-flex > div > div.Box.p-3.mt-2 {
	display: none;
}
```
or the following CSS to completely hide them
```css
#dashboard div.news div.release {
	display: none;
}
```
(Custom CSS can be added in the options menu of Refined Github.)

**Comment by fregante** [comment]
> get these split out into options or a multiselect of some kind

No options per feature https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658

From our point of view, we want to disable them all, so splitting those 200 features into sub features only adds code and complexity.

If you need granularity you can copy the selectors and use them autonomously as @Scriptim just suggested 👍 which is the reason why we offer a CSS field.
