### ISSUE TITLE
github1s.com integration

### ISSUE THREAD

**Issue by fabiospampinato** [sindresorhus/refined-github#4457]
There's a really nice service called github1s.com, the way it works is say you want to explore a repository, rather than downloading it and opening up vscode you just add "1s" in the url between "github" and ".com" and you immediately get an online instance of vscode for it.

Example:

- Regular repo: https://github.com/vasturiano/force-graph
- Github1s-ified repo: https://github1s.com/vasturiano/force-graph

IMHO code is one of the biggest things that github provides obviously, and github1s enhances the browsing experience quite a bit, at least for me, so I'd definitely use a button that would allow me to use github1s in one click.

Ideally I'd personally put a small button for this next to the fork button, whenever the fork button is currently displayed.

**Comment by fregante** [comment]
As you mentioned, the good thing about that service is that you just need to add `1s` to the URL. 

While an exciting project, I haven't found it useful enough that it warrants a link on every single page of every single repo.

At most I'd add it to the dropdown in the "Code" tab:


<img width="422" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/121532276-657b9580-ca29-11eb-985d-01d6d35657db.png">
but at 2 clicks in, you're not far from just typing `1s` in the URL bar.

**Comment by fabiospampinato** [comment]
> I haven't found it useful enough that it warrants a link on every single page of every single repo.

Would you feel any different about adding it only on the home/readme page of a repo?

> but at 2 clicks in, you're not far from just typing `1s` in the URL bar.

Yeah, a one-click button would be a lot more handy.

At the end of the day it's not too much of a hassle to add the "1s" manually, but having a one-click button for this would make the whole experience much nicer, plus I'd bet a lot of people don't even know github1s exists, even I sometimes kind of forget to use it rather than downloading a repo.

**Comment by kidonng** [comment]
If you **really** need a button, checkout [surf](https://github.com/surfcodes/surf), which is pretty much the same thing, but also comes with a *extension* and *CLI*.

###### Honestly, I don't see why anyone would want to use these local "vscode". They use LOTS OF API QUOTA while providing no LSP, Terminal, GitHub integration and whatever you expect. If you really need a decent online code browser, use [Sourcegraph](https://sourcegraph.com/search).

**Comment by fregante** [comment]
Perfect. Surf is the extension you can use

**Comment by fregante** [comment]
> I'd bet a lot of people don't even know github1s exists

GitHub offers their own Codespaces, which is basically the same, so other than speed it’s not something that people are particularly unaware of.

**Comment by fabiospampinato** [comment]
Yeah the whole point of github1s is speed, convenience and ease of use, I have no interest in whatever github's codespaces can do.

I'll look into surf, thanks for the suggestion @kidonng. 

IMHO though there's an argument to be made for turning 180 degrees and implementing everything that makes sense and is easy to maintain into refined github, doing the same thing via 1 trusted extension is much better than using 10 extensions for the same thing, these things are an accident waiting to happen, the fewer extension one can install the better.

**Comment by kidonng** [comment]
VSCode folks added exactly this feature in today's 1.57.0 release: https://code.visualstudio.com/updates/v1_57#_remote-repositories

**Comment by fregante** [comment]
> doing something via 1 trusted extension is much better than using 10 extensions

True, but that means you're asking 1 trusted person to do the work for 10 extensions. Given it's a free tool, that argument is a bit much.

**Comment by fregante** [comment]
> VSCode folks added exactly this feature in today's 1.57.0 release: [code.visualstudio.com/updates/v1_57#_remote-repositories](https://code.visualstudio.com/updates/v1_57#_remote-repositories)

That's pretty cool! It's great to be able to use one’s own local IDE instead of a limited version in the browser.

**Comment by fabiospampinato** [comment]
> True, but that means you're asking 1 trusted person to do the work for 10 extensions. Given it's a free tool, that argument is a bit much.

Sure sure resources are always limited unfortunately, even if this weren't a free tool.

On this regard I was thinking: github1s seems to have 3 sponsors (listed in the statusbar), if this extension linked to github1s, assuming that that's something users of this extension would like, surely those sponsors should have to pay more because they'll get (significantly?) more pageviews and this extension should deserve some percentage of that sponsor money. Maybe this is something that should be brought up to the people behind github1s to try to get refined-github some more resources. Or maybe some opt-in/out integrations with vercel/sourcegraph/gitpod could be added directly to the extension, I don't think people would have a problem with that if those integrations could be disabled and especially if they'll provide some more resources to this project.

> We have 200+ features already and it seems that we rejected about 400 feature requests. Would you like an extension that big?

Assuming those 400 feature requests made sense to me on average, sure, the more useful feature the better, kind of by definition.

> VSCode folks added exactly this feature in today's 1.57.0 release: code.visualstudio.com/updates/v1_57#_remote-repositories

Nice! I'll check that out.
