### ISSUE TITLE
Add a Go to file button on forks

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4459]
I don't know why, but apparently GitHub doesn't provide the Go to file button on forks (and the shortcut won't work either, unless with Refined GitHub), even though the feature is actually available.

Example: https://github.com/zen-kernel/zen-kernel

**Comment by fregante** [comment]
We could… but <kbd>t</kbd> already works

**Comment by kidonng** [comment]
But we can do better than the status quo. Sure `t` works, but that's only for those who know the shortcut. And people may be mislead into thinking that it doesn't work because there's no Go to file button on the page.

**Comment by kidonng** [comment]
I imagine this can be part of `repo-wide-file-finder`.

- find a file tree toolbar
  - if there's already a find file button, do nothing
  - else add the button
- if no file tree toolbar we append a hidden find file button with the hotkey

**Comment by fregante** [comment]
> * if there's already a find file button, do nothing (improvement over current implementation)

How is it an improvement? I think that if a `data-hotkey` element already exists it's already excluded

**Comment by kidonng** [comment]
> How is it an improvement? I think that if a `data-hotkey` element already exists it's already excluded

My bad, I didn't saw the exclude.
