### ISSUE TITLE
`Cancel` button when editing wiki pages

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#4460]
When editing a page on a GitHub wiki, there is no intuitive way to stop editing and discarding the changes. 
Unlike editing e.g. issue titles or issue text. (Note that the first shows a link, the second has a red-label button)

The only cancel-ish thing users see is a red-label `Delete` button which could easily be confused with the same looking `Cancel` button known from issues already:
![wiki](https://user-images.githubusercontent.com/9874850/121651868-5f260180-ca9b-11eb-957a-89747f64f9a6.png)
(To remove the danger here, the delete one could have a trash can icon as well.)

**Comment by fregante** [comment]
Can you add a clickable link to that page?

**Comment by tooomm** [comment]
This is a public wiki for testing. It may stop working at any time.
https://github.com/tooomm/wikitest/wiki/Getting-Started/_edit
