### ISSUE TITLE
`collapse-wiki-sections` should not run on Wiki edit pages

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4463]
1. Visit https://github.com/webpack/webpack/wiki/_new
2. Paste:

	  ```
	  # hello
	  
	  world
	  ```

3. Click "Preview" tab
4. Click "hello"

![agif](https://user-images.githubusercontent.com/1402241/121685461-27927600-caea-11eb-922b-c03e60fa441d.gif)

**Comment by kidonng** [comment]
This should be done in `github-url-detection` first I think?
