### ISSUE TITLE
Add comment-commands to add labels, etc...

### ISSUE THREAD

**Issue by AlCalzone** [sindresorhus/refined-github#4465]
I'm not sure if this is even possible in Github or through this extension. GitLab has so-called quick actions which (among other things) can add labels to an issue/PR: https://docs.gitlab.com/ee/user/project/quick_actions.html

In a project I maintain, I frequently have to request logs from users and set a label to mark the issue as "waiting for info". Being able to do this with Github's saved replies would be super helpful, for example like this:
```
Please post this and that.

/label "waiting for info"
```

The /label part should not appear in the comment, but instead add a label when the comment button is pressed.

**Comment by fregante** [comment]
It would be possible for an extension to catch this, unless it’s done when replying via email, but it sounds like a feature that could stand alone in its own extension.

**Comment by AlCalzone** [comment]
Fair enough - I just figured it would fit here, since most of the infrastructure is already in place.
