### ISSUE TITLE
Cannot use the new Personal token now 

### ISSUE THREAD

**Issue by dnknn** [sindresorhus/refined-github#4466]
![image](https://user-images.githubusercontent.com/10995302/121770614-dbecd480-cb9c-11eb-9962-1386e79cb8f8.png)

> Refined GitHub cannot support the new github token formats ?

I clicked on it to update and generate a new Token, and then pasted it into Refined GitHub, prompting an error format.

![image](https://user-images.githubusercontent.com/10995302/121770662-2d955f00-cb9d-11eb-8830-f9a420a18516.png)

- https://github.blog/2021-04-05-behind-githubs-new-authentication-token-formats/

- https://github.com/settings/tokens

What should I do to fill in the new format Token?

**Comment by fregante** [comment]
Are you using the latest version of Refined GitHub? this was fixed months ago

**Comment by dnknn** [comment]
> Are you using the latest version of Refined GitHub? this was fixed months ago

`V21.3.1`  OK, ThankYouVeryMuch! I see, I will be able to use it after I upgrade the version.
