### ISSUE TITLE
`hide-zero-packages` never runs

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#4472]
Test on https://github.com/sindresorhus

This is because the detection is not dom ready safe.
https://github.com/sindresorhus/refined-github/blob/6f2b3731cfcbc4af1915dac0cb35526594df141f/source/features/hide-zero-packages.tsx#L17-L24

**Comment by fregante** [comment]
This is something we can prevent in the future: `isUserProfile.length === 0 && awaitDomReady === false` -> `throw Error`

The length check means that the function is DOM-based; it would have to be repeated for each function in the `include` array.

**Comment by yakov116** [comment]
But there are domReady safe detections (Those in meta tags).

I was thinking of allowing elementReady pageDetections (With no plan of how to implement)

**Comment by fregante** [comment]
> But there are domReady safe detections (Those in meta tags).

Good point

> I was thinking of allowing elementReady pageDetections (With no plan of how to implement)

This would mean copying the detections from `GitHub-url-detection` and replacing `exists()` with `elementReady`, I suppose, but I don't think I'd like that (because we have to update the selector in 2 places)
