### ISSUE TITLE
Make `follow-file-renames` more noticeable

### ISSUE THREAD

**Issue by adisuciu** [sindresorhus/refined-github#4477]
I've tried installing the extension and after doing this branch - https://github.com/analogdevicesinc/scopy/tree/try_rename_CI, which just changes the name of the folder for
https://github.com/analogdevicesinc/scopy/commits/try_rename_CI/ci/appveyor/build_appveyor_flatpak.sh . I can still see blame. Is there something I'm missing or I'm misinterpreting the follow-rename feature ?

**Comment by yakov116** [comment]
Working for me.

![image](https://user-images.githubusercontent.com/16872793/122077501-cb6d7180-cdc9-11eb-8142-4431eb09c06f.png)

**Comment by adisuciu** [comment]
I'm stupid ... Yea, it works for me as well, i just figured it would be open by default

**Comment by yakov116** [comment]
No worries.

**Comment by fregante** [comment]
We can add a visual indicator other than the tooltip to show that the file has been renamed. Does octicon have a good icon for that?

**Comment by yakov116** [comment]
Maybe the renamed arrow?

**Comment by fregante** [comment]
Yeah that works, as long as it's rotated 180deg on the Newer button
