### ISSUE TITLE
Show opened milestones as tab

### ISSUE THREAD

**Issue by EaseTheWorld** [sindresorhus/refined-github#4482]
This is similar to 'Bugs tab' feature.

My company keeps two milestones opened,
next version(say 2.1) and next next version(say 2.2).
To see the pr for current version, I needs to click 'Pull request' -> 'Milestones' -> '2.1'

I wish there were '2.1' tab and '2.2' tab in front of 'Pull requests' tab so I can check in one click.

**Comment by fregante** [comment]
Every repo has bugs, so an extra tab might be ok; Almost no repo has milestones. We can't implement it here.

**Comment by krlmlr** [comment]
I came here to request that.

> Almost no repo has milestones.

I tend to use them: labels categorize issues, with milestones I can define a rough implementation time and scope (e.g. grouping related issues together that are best reviewed when focusing on a specific part of the code).

It would be a big help to have the "Milestones" list accessible from the top bar, perhaps visible only if the project really has milestones?

**Comment by krlmlr** [comment]
Duplicate of #311, which has additional context.

The logic required here seems similar to the "Bugs" tab (counting something that perhaps is not available in the DOM).
