### ISSUE TITLE
`no-useless-split-diff-view` is broken on GitHub Enterprise

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4483]
> here's how a recent diff looks with this feature enabled:
> 
> ![chrome_2021-06-17T090052](https://user-images.githubusercontent.com/1781176/122356448-b835df80-cf4a-11eb-8c24-7e17eacc24b0.png)
> 
> What do you think changed in this commit? Well it looks like that line was added - but it wasn't. The normal split diff looks like this:
> 
> ![chrome_2021-06-17T090115](https://user-images.githubusercontent.com/1781176/122356527-cc79dc80-cf4a-11eb-9b1d-0d05fcc41424.png)
> 
> You can see there's a subtle difference between the commits which is actually very important (there was a bug!)
> 

_Originally posted by @danielsamuels in https://github.com/sindresorhus/refined-github/issues/4399#issuecomment-863023847_

> Strange, can't replicate.
> 
> Diff that's correctly unified: https://github.com/sindresorhus/refined-github/commit/f60cb71e0bc2708ebda622d6c684489241fd367a
> 
> Reportedly problematic diff: https://github.com/sindresorhus/refined-github/commit/26e778fd85f7db6c3d5bc6f508e23c77f3ed4a20

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/issues/4399#issuecomment-863172312_

> This is on a GitHub Enterprise instance running 2.22.10, perhaps it's an incompatibility with that version?

_Originally posted by @danielsamuels in https://github.com/sindresorhus/refined-github/pull/4399#issuecomment-863173685_

> I think I know what's happening. It checks the left column first, it doesn't find the expected element (`[data-split-side="${side}"]:is(.blob-code-addition, .blob-code-deletion)`) and therefore it assumes it's empty.

_Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/4399#issuecomment-863175358_

**Comment by fregante** [comment]
The side detection code needs to be rethought to avoid future issues with this. With the current code, if GitHub changes the selector, this bug will happen again.

**Comment by simbo** [comment]
and disabling this feature seems to have no effect... 🤷‍♂️

**Comment by fregante** [comment]
Sorry about that, the feature had actually a different name: `no-useless-split-diff-view`

[I disabled it globally](https://github.com/sindresorhus/refined-github/tree/hotfix#hotfixes-branch).

**Comment by dustinlineweber** [comment]
> Sorry about that, the feature was named `no-useless-split-diff-view`, not ` hide-empty-split-diff-side` as its PR title suggested.
> 
> [I disabled it globally](https://github.com/sindresorhus/refined-github/tree/hotfix#hotfixes-branch).

Is this related to whatever removed the only diff mode I don't need Dramamine ™️ to use from even being an option (today on github, split diff is the only option for me, and it is gross).
