### ISSUE TITLE
`no-useless-split-diff-view` doesn't work for diffs that are not loaded in time

### ISSUE THREAD

**Issue by ouuan** [sindresorhus/refined-github#4488]
1.  When the diff is shown after clicking a button, for example, "Large diffs are not rendered by default", `no-useless-split-diff-view` doesn't work.

    Example: <https://github.com/cpeditor/cpeditor/pull/223/files#diff-0f46ff9666ae4dc3789ffaed0f2c4a93fbd4469ab486af80f1b262cb44b7a038>

2.  When the diff is too long and the diff of the files at the bottom are lazy-loaded, `no-useless-split-diff-view` only works for files at the top.

    Example: https://github.com/cpeditor/cpeditor.github.io/commit/b349da5cefab537691e1988f74252759aff9c300

**Comment by fregante** [comment]
We probably just need to add this

https://github.com/sindresorhus/refined-github/blob/67a6719d57397496ff6136656ecf3339e1e9b867/source/features/show-whitespace.tsx#L77
