### ISSUE TITLE
`git-checkout-pr` is missing in some cases

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4489]
The sidebar overlap is tracked in #4490 

### Missing from https://github.com/sindresorhus/refined-github/pull/4395

<img width="511" alt="Screen Shot 16" src="https://user-images.githubusercontent.com/1402241/122522705-72f3d980-d040-11eb-9726-448ff38fff95.png">

### Present in https://github.com/twbs/bootstrap/pull/30329

<img width="449" alt="Screen Shot 17" src="https://user-images.githubusercontent.com/1402241/122522742-7d15d800-d040-11eb-8c92-257a1d2808f1.png">

### Probable error:

<img width="745" alt="Screen Shot 18" src="https://user-images.githubusercontent.com/1402241/122522835-94ed5c00-d040-11eb-8d88-0f298af6d673.png">

**Comment by yakov116** [comment]
Its now lazy-loaded it needs `oneMutation`, but be careful not to break GHE.
