### ISSUE TITLE
"Open with" PR dropdown overlapping `sticky-conversation-sidebar`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4490]
On any PR, such as https://github.com/sindresorhus/refined-github/pull/4395.

This is not an easy issue because it's due to z-index. A solution must be found by looking at the previous commits that affected the z-index of the sidebar and avoid regressions.

## Sticky

<img width="467" alt="Screen Shot 19" src="https://user-images.githubusercontent.com/1402241/122523001-c1a17380-d040-11eb-867c-0588cc48b6ec.png">

## Not sticky

<img width="476" alt="Screen Shot 20" src="https://user-images.githubusercontent.com/1402241/122522997-c0704680-d040-11eb-9cb9-2ab156359004.png">

**Comment by Nokel81** [comment]
I see this on the latest release too

**Comment by yakov116** [comment]
Due to https://github.com/sindresorhus/refined-github/issues/4192 and https://github.com/sindresorhus/refined-github/pull/4364

The PR dropdown is 81

**Comment by stdedos** [comment]
This still seems broken in my case:
![image](https://user-images.githubusercontent.com/133706/126077551-7130084f-30c8-4cff-a24f-7a7a349fd849.png)
https://github.com/sindresorhus/refined-github/pull/4556, Version: 21.6.8
