### ISSUE TITLE
Clean `clean-dashboard` is partially broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4491]
GitHub must have changed some classes:

## Expected look

<img src="https://user-images.githubusercontent.com/1402241/54401114-39192780-4701-11e9-9934-7c71f01e957f.png" width="400">

## Current look
<img width="600" alt="Screen Shot 21" src="https://user-images.githubusercontent.com/1402241/122536906-38456d80-d04f-11eb-9123-3d0fc603cb28.png">

**Comment by yakov116** [comment]
Plus `linkify-labels-on-dashboard` is broken too.

**Comment by kidonng** [comment]
Recent activity is moved to the left side. Will try to investigate 👀

**Comment by kidonng** [comment]
> Plus `linkify-labels-on-dashboard` is broken too.

This one isn't fixed yet. Mind opening a new issue?
