### ISSUE TITLE
Make a link format automatically when pasting link on content

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#4499]
When editing description, I often make a link like [issue](https://github.com/sindresorhus/refined-github/issues).

The step I followed is
1. write a content.
2. and I wrap it using `[]` for content and `()` for link.

so it is a hassle. I'd like to use link paste as function of backtick.

backtick is automatically to wrap up selected content which is dragged.

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/4310
