### ISSUE TITLE
Save preferences in Safari extension

### ISSUE THREAD

**Issue by domoritz** [sindresorhus/refined-github#4500]
Refined GitHub 21.6.8
Safari 15

When I head to the preferences to disable a feature, I can uncheck the box for a feature but when I refresh the preferences, the feature is enabled again.

**Comment by fregante** [comment]
Are you on the macOS 12 beta?

**Comment by domoritz** [comment]
Yes. Not sure whether that's the issue. If it is, feel free to close the issue until the stable version is out.

**Comment by kidonng** [comment]
I'm also on beta and I just checked there is no such issue for me. I'm running the main branch via Xcode though, but I don't think it makes a huge difference.

**Comment by domoritz** [comment]
The extension auto saves edits, right? I don't see a save button or anything like it.

**Comment by domoritz** [comment]
Hmm, I tried it again just now and saving works. Not sure what has changed. I'll report if I see this issue come up again.

**Comment by fregante** [comment]
> when I refresh the preferences, the feature is enabled again.

Is it possible that you were refreshing too soon? There's a throttle mechanism to save at most twice per second if I remember correctly

**Comment by domoritz** [comment]
I think I was giving it enough time but maybe I wasn't.

**Comment by fregante** [comment]
I'm seeing the same issue in Safari 15 on macOS 11. The storage API is just failing.

<img width="282" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/123550409-85d08180-d797-11eb-9cd9-ffbe03ddbb78.png">
