### ISSUE TITLE
automatically switch to `rich diff` for applicable binaries

### ISSUE THREAD

**Issue by dwelle** [sindresorhus/refined-github#4501]
When reviewing files, it's never useful to diff the source for binaries (`Binary file not shown.`), but more so for images. If it's possible, it'd be nice to automatically switch to rich diff (preview) for those.

https://github.com/excalidraw/excalidraw-libraries/pull/141/files

![image](https://user-images.githubusercontent.com/5153846/122830155-3ba75600-d2e8-11eb-8e65-c1fd2ff9e261.png)

**Comment by yakov116** [comment]
Duplicate of #2673

**Comment by dwelle** [comment]
Somehow missed it. Thanks!
