### ISSUE TITLE
redundant commit navigation in clean merge commits

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4504]
The commit navigation on the bottom clean merge commits seems redundant.

![image](https://user-images.githubusercontent.com/4771718/122905250-aef3ab00-d36e-11eb-99bb-c8cade87a7cc.png)

[source commit](https://github.com/sindresorhus/refined-github/pull/4448/commits/9a1f2cd549288e301e053d7ab033578b39389212)

But maybe the effort in excluding specific pages based on different criteria might not be worth it though.

**Comment by fregante** [comment]
In this case they’re only “redundant” because they’re so close together. I think the logic would be something like “display if there are more than 10 diff lines on screen”

but like you said maybe it’s not worth it.
