### ISSUE TITLE
`shorten-links` feature hides markdown images which are part of a link.

### ISSUE THREAD

**Issue by egormanga** [sindresorhus/refined-github#4505]
Example page: https://github.com/egormanga/egormanga/blob/3a6c21f809660a9f8bda63a72e2c2c339860f9ec/README.md

<details>
<summary>Before:</summary>

![image](https://user-images.githubusercontent.com/19863479/122919168-997b8280-d368-11eb-9a18-5ea822e5f7de.png)

</details>

<details>
<summary>After:</summary>

![image](https://user-images.githubusercontent.com/19863479/122919202-a4361780-d368-11eb-8393-fd430a2a6c2c.png)

</details>

Example of markup causing the issue:
```html
<th>
	<a href=...>
		<img src=...>   <!-- will disappear -->
		<p>Text</p>
	</a>
</th>
```

**Comment by fregante** [comment]
Heh, indeed, we use textContent to check whether it’s a customized link. We need to add a `!link.firstElementChild` check, probably on my `shorten-repo-url` package

**Comment by saarahasad** [comment]
Hello! Is this issue fixed? I noticed that it still exists when I downloaded the extension from the chrome web strore. But it seems to be fixed when I loaded it on chrome using web-ext

**Comment by saarahasad** [comment]
@fregante Hello! Hoped to work on this as my first contribution. I had a problem while load unpacking the extension and loading it through web-ext as well. It said - Could not load background script 'build/browser-polyfill.js' 

I noticed the browser-polyfill.js and background.js were missing from the build folder but were mentioned in the manifest.json file. Am I missing out on a step somewhere?

**Comment by fregante** [comment]
Yes you'll also have to run `npm run watch` to generate those files while you develop

**Comment by saarahasad** [comment]
@fregante I've made the necessary change and created a pull request. I checked if it works fine for the general use case using the URLs mentioned here https://github.com/fregante/shorten-repo-url/blob/main/test.js :)
