### ISSUE TITLE
Files tab supports `conversation-activity-filter`

### ISSUE THREAD

**Issue by KSH-code** [sindresorhus/refined-github#4506]
1. Visit https://github.com/sindresorhus/refined-github/pull/4395/files
2. Too many resolved comments are visible

I do not want to see resolved comments.
it is an obstacle to review.

**Comment by fregante** [comment]
The feature is too complex to be adjusted to a page where it only hides something that it’s already small and usually disappears once outdated. GitHub also added a Conversation dropdown that makes it easier to see what’s still unresolved
