### ISSUE TITLE
Rename “useless” features to “noise”

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4509]
hide useless comments -> hide comment noise
hide useless newsfeed events -> hide newsfeed noise
Etc 

This should be done in the file names, CSS classes, and UI.

Thoughts? Does this make them less clear?

**Comment by kidonng** [comment]
I like this proposal, sounds more neutral.

Or we can more specific in each "useless" feature:

- `unwrap-useless-dropdowns` -> `unwrap-binary-dropdowns`

**Comment by fregante** [comment]
That feature also unwraps dropdowns with a single option

**Comment by kidonng** [comment]
> That feature also unwraps dropdowns with a single option.

Today I learned. That's terrible design. Also, just noticed the button size has changed since the feature was created. Will create an issue.

**Comment by darkred** [comment]
> Or we can more specific in each "useless" feature:
> 
> * [`unwrap-useless-dropdowns`](/sindresorhus/refined-github/blob/main/source/features/unwrap-useless-dropdowns.tsx) -> `unwrap-binary-dropdowns`

I believe that seeing the word `binary` in RG at first sight brings in mind 
either the mathematics binary system, or the "Find a feature" binary search process.

Using `two-part`  i.e. `unwrap-two-part-dropdowns` instead,
feels more straightforward for me, especially when searching in "Find features" textbox.

**Comment by sahilcode17** [comment]
Hi, I wanted to Contribute to this issue @fregante  can you guide me on which files changes are to be done.

**Comment by fregante** [comment]
You can search the word "useless" in the repository and reword any feature name or description that makes use of it. 

The filenames needs to be changed too
