### ISSUE TITLE
Remove "Marketplace" nav item

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#451]
I think its position in the top nav is way too prominent. I'd move it into the profile drop-down, underneath "Explore"

**Comment by sindresorhus** [comment]
I was thinking the same thing.

**Comment by hkdobrev** [comment]
👍 Though, I'd recommend waiting a bit so people could explore it a bit.

**Comment by sindresorhus** [comment]
Sure

**Comment by bfred-it** [comment]
It showed up again for me. I'm just gonna add a uBlock filter:

```
github.com##.js-marketplace-callout-container
```

**Comment by pablopunk** [comment]
You guys think it's time for this? I would like this to be implemented, there are too many buttons in the nav bar

**Comment by hkdobrev** [comment]
@pablopunk Go for it!
