### ISSUE TITLE
Rename “remove” to “hide” in all features 

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4510]
To be more consistent across features, we should probably choose one of these similar verbs. I think “hide” is more correct. In many cases we should also stop using .remove() and use .hidden = true instead, unless the CSS order matters.

Related: #4509

**Comment by cheap-glitch** [comment]
I think the same could be said of "quick" vs "fast"/"faster".

**Comment by kidonng** [comment]
> I think the same could be said of "quick" vs "fast"/"faster".

Proposal: ✨🐢🚀✨

**Comment by fregante** [comment]
Proposals welcome. I’m not sure it quick/faster can be replaced as easily
