### ISSUE TITLE
Open With Dropdown is broken by `sticky-sidebar`

### ISSUE THREAD

**Issue by rbclark** [sindresorhus/refined-github#4511]
When navigating to a pull request with sticky sidebar enabled, I see the following behavior:

<img width="790" alt="Screen Shot 2021-06-24 at 7 04 43 AM" src="https://user-images.githubusercontent.com/2308869/123253325-5da50200-d4bb-11eb-8082-c7629c26119f.png">

if I disable `sticky-sidebar` the dropdown goes back to normal

<img width="656" alt="Screen Shot 2021-06-24 at 7 11 36 AM" src="https://user-images.githubusercontent.com/2308869/123253387-6bf31e00-d4bb-11eb-97a8-1bebc4b1ba1f.png">

**Comment by kidonng** [comment]
Duplicate of #4490

**Comment by rbclark** [comment]
Yep sorry just realized that as well, my bad.
