### ISSUE TITLE
No way to create a release if repo doesn't have one to begin with

### ISSUE THREAD

**Issue by rdsedmundo** [sindresorhus/refined-github#4515]
### With Refined Github:

<img width="324" alt="Screen Shot 2021-06-24 at 13 45 16" src="https://user-images.githubusercontent.com/5482378/123302227-dbd0cb00-d4f2-11eb-8a35-311864bd7765.png">
<img width="174" alt="Screen Shot 2021-06-24 at 13 45 12" src="https://user-images.githubusercontent.com/5482378/123302229-dd01f800-d4f2-11eb-9a50-3cab563c8291.png">
<img width="1545" alt="Screen Shot 2021-06-24 at 13 45 05" src="https://user-images.githubusercontent.com/5482378/123302232-dd01f800-d4f2-11eb-9ddf-70139958ada6.png">

---

### Without Refined Github there's an option on the side:

<img width="460" alt="Screen Shot 2021-06-24 at 13 49 44" src="https://user-images.githubusercontent.com/5482378/123302459-1b97b280-d4f3-11eb-9ad1-66b27c730be2.png">

**Comment by yakov116** [comment]
That will change in https://github.com/sindresorhus/refined-github/pull/4448

but you can use the + icon to add 

![image](https://user-images.githubusercontent.com/16872793/123302979-45e57200-d4eb-11eb-9976-5397d34145f1.png)

**Comment by rdsedmundo** [comment]
Thanks for the quick reply, unfortunately I don't see it there either:

### Github
<img width="233" alt="Screen Shot 2021-06-24 at 13 59 50" src="https://user-images.githubusercontent.com/5482378/123303751-839ac880-d4f4-11eb-9263-701aa0693306.png">

---

### Refined
<img width="235" alt="Screen Shot 2021-06-24 at 14 00 03" src="https://user-images.githubusercontent.com/5482378/123303746-83023200-d4f4-11eb-94fa-d9fefdbc0764.png">

**Comment by yakov116** [comment]
Ohh! I misread the title. I thought you wanted to create a project!

**Comment by kidonng** [comment]
You can still access the releases via tags I think?

**Comment by fregante** [comment]
> You can still access the releases via tags I think?

Yes, that's how it was always possible even before GitHub added the repo sidebar

<img width="454" alt="Screen Shot 4" src="https://user-images.githubusercontent.com/1402241/123357586-feff8700-d593-11eb-8947-d87ff0ab7b41.png">

<img width="623" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/123359037-bbf2e300-d596-11eb-92f6-084ebb0b69a9.png">
