### ISSUE TITLE
move 'delete fork' button

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4518]
This is an idea that popped into my head when I was jumping between an upstream repository and my fork.

`forked-to` adds a an extra element sandwiched between the 'Fork' button and the fork count. But `quick-repo-deletion` adds an extra button to the beginning of the button group.

The question / idea that I am trying to point to here is : **Can we possibly merge the _positions_ of these 2 features?**

The obvious advantage in doing this is the saving of space and not be thrown random number of buttons on different pages ( I am already annoyed with the 'Sponsor' button that comes and goes on different repositories ). I would expect a consistent number of buttons for my UX that does not take my focus as I move about different pages ( I am also kind of extra observant on such small UX changes ).

I think it is rare that people would have multiple forks of the same repository in more than one place. The most common scenario is to have only 1 fork per repository.

In that scenario, both these features are mutually exclusive. The button that opens the fork can be replaced with a button the deletes the fork ( :x: as the icon ).

In the other scenario where there are multiple forks and the dropdown is to be displayed, we could probably prepend the :x: button before the dropdown ( But it could cause some kind of confusion though ).

I am not sure whether this would be too complicated in terms of checking both of the features. Whether either of them are disabled by the user, etc. That is why I am opening this issue as a discussion rather than a feature request.

**Comment by fregante** [comment]
Can you edit the dom in your browser and take a screenshot to see what it would look like?

**Comment by shinenelson** [comment]
in the first scenario ( which is the majority, in my opinion ) where there is only one fork and no drop-down menu, it would look something like : 

![Screenshot 2021-06-26 at 10-50-47 move 'delete fork' button · Issue #4518 · sindresorhus refined-github](https://user-images.githubusercontent.com/4771718/123502808-acde6480-d66c-11eb-8c8f-d82dc1f5ccb7.png)

in the other scenario, where there are multiple forks and the drop-down is always displayed : 

![Screenshot 2021-06-26 at 10-49-12 move 'delete fork' button · Issue #4518 · sindresorhus refined-github](https://user-images.githubusercontent.com/4771718/123502813-b8319000-d66c-11eb-86e0-d8896d832230.png)

PS : I used :x: as the icon because I could paste the emoji ( and that is what I suggested in the description of the issue ). Ideally, we should use the trash bucket octicon.

**Comment by shinenelson** [comment]
> I’m afraid it wouldn’t be as clear if it’s merged into that Fork button

The risk of clicking the button? I think that the enlarging warning button and the red-ish hue overlay over the whole page is warning enough.

We could possibly increase the timeout to 10 seconds though. I have always felt the 5 second timeout is too short for slow pokes like me.

**Comment by fregante** [comment]
I think it's best where it is. Such change would mean adding the button exactly where the fork button is, so the user might click on it by mistake.
