### ISSUE TITLE
How do I disable the `align-repository-header` feature?

### ISSUE THREAD

**Issue by TheOnlyTails** [sindresorhus/refined-github#4519]
I find this feature a bit annoying, and I would like to get rid of it.

**Comment by fregante** [comment]
You can add this CSS in the options page https://github.com/sindresorhus/refined-github/issues/3785#issuecomment-739625313

**Comment by TheOnlyTails** [comment]
Thank you!

**Comment by fregante** [comment]
This feature has now been dropped in https://github.com/refined-github/refined-github/pull/6247
