### ISSUE TITLE
`avoid-accidental-submissions` breaks PR title changes with Enter

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4525]
1. Visit ~~an issue~~ _a PR_ you can edit, like https://github.com/sindresorhus/refined-github/pull/4528
2. Edit the title
3. Press enter
4. The changes are not saved, nothing happens

This is what the feature is supposed to do, but I think we should exclude issue/pr titles.

![demo](https://user-images.githubusercontent.com/1402241/123896560-fcce6b80-d98b-11eb-8896-7e73a8aaa76e.gif)

**Comment by darkred** [comment]
Then, I think that, what it only needs is adding this in `void features.add(` 
in order to only work in *new* Issue/PR forms, not existing ones:

```js
	exclude: [
		pageDetect.isIssue,
		pageDetect.isOpenPR,
		pageDetect.isDraftPR
	],
```

I could make a PR if you want.

**Comment by darkred** [comment]
I made PR #4528

**Comment by fregante** [comment]
> I think we should exclude issue/pr titles

The keyword here is the last word. Titles. Not whole issue/PRs

**Comment by fregante** [comment]
I made a mistake in this issue, the bug does not affect issues since the feature is not enabled on this page at all. It only affects PRs. I updated my issue

**Comment by darkred** [comment]
> The key word here is the last word. Titles. Not whole issue/PRs. It should let me save the title by pressing enter.

I updated my PR.
