### ISSUE TITLE
fix contribution graph's time interval selection

### ISSUE THREAD

**Issue by kiprasmel** [sindresorhus/refined-github#4536]
Visiting a profile on github and selecting a contribution year for the contribution graph sets the interval in the url query to the current month, or the last month of the given year. 

e.g. https://github.com/kiprasmel

`2020`: selects https://github.com/kiprasmel?tab=overview&from=2020-12-01&to=2020-12-31 - last month of 2020

`2021` (current year): selects https://github.com/kiprasmel?tab=overview&from=2021-07-01&to=2021-07-02 - current month

It seems the expected UX would be to select the whole year?

One would need to change the year selection's `<a href` attribute and replace the given start date's month to the first month `01`. I can try creating a PR if we agree on this fix.

**Comment by kidonng** [comment]
> It seems the expected UX would be to select the whole year?

Then it will need to load a year's worth of contributions, which can be very long.

I don't think there is anything to "fix", but rather, you are asking for a "expand" button.

Maybe we can extend `infinite-scroll` to support profile page.

**Comment by yakov116** [comment]
> Or maybe we can extend [`infinite-scroll`](/sindresorhus/refined-github/blob/main/source/features/infinite-scroll.tsx) to support profile page.

We can't it changes the URL on every load

**Comment by fregante** [comment]
I tried, it doesn't work. If I set the requested dates it just loads January:

https://github.com/fregante?tab=overview&from=2019-01-01&to=2019-12-31

In short, GitHub expects you to click the year and then go backwards, starting from the "latest month" of that year ("December" for past years or "the current month" for this year).
