### ISSUE TITLE
Disable "Comment" button when there is no text in gist.github.com

### ISSUE THREAD

**Issue by Yash-Singh1** [sindresorhus/refined-github#4550]
You can comment on any gist, here is one: https://gist.github.com/tterb/982ae14a9307b80117dbf49f624ce0e8.

When trying to comment and the comment is blank, the comment button is not marked as disabled. However, in the main GitHub UI, the "Comment" button is disabled when the comment is blank.

Current:

![Screenshot from 2021-07-08 20-40-25](https://user-images.githubusercontent.com/53054099/125020379-97cee180-e02d-11eb-9eed-0106e86accd4.png)

Desired:

![Screenshot from 2021-07-08 20-48-36](https://user-images.githubusercontent.com/53054099/125020544-e54b4e80-e02d-11eb-8c0f-ce90873e2747.png)

Here is the steps:

- Add disabled attribute
- Add `disabled` class
- Set the `aria-disabled` property to `true`

**Comment by fregante** [comment]
I mean… it’s right, but we’re not going to add code to handle this non-issue.

**Comment by meganfox-cmd** [comment]
What Are the Different Types of Bitcoin Wallets?
Get help finding a bitcoin visit us: 
[https://gist.github.com/easylogic/fc4e9ce2b60a8ab50ab9](https://gist.github.com/easylogic/fc4e9ce2b60a8ab50ab9)
