### ISSUE TITLE
Subword navigation

### ISSUE THREAD

**Issue by jacehensley-wf** [sindresorhus/refined-github#456]
Would it be possible to add support for subword navigation? Basically the same functionality as this [package](https://marketplace.visualstudio.com/items?itemName=OlleWestman.SubwordNavigation) for VS Code or how sublime works.

**Comment by jgierer12** [comment]
For GH's code editor? I don't edit/select code on GH enough to justify building such a complex feature

**Comment by jacehensley-wf** [comment]
I was thinking just the comment text area. I don't edit code on GH pretty much ever.

**Comment by bfred-it** [comment]
I'd suggest using GhostText if you want to use complex editor features: https://github.com/GhostText/GhostText
