### ISSUE TITLE
`remove-unused-repo-tabs` doesn't move tabs into "more" if `more-dropdown` is disabled

### ISSUE THREAD

**Issue by ouuan** [sindresorhus/refined-github#4562]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Describe the problem and how to replicate it

1. Enable `remove-unused-repo-tabs` and disable `more-dropdown`.
2. Go to a repo that you can't edit and has unused tabs.
3. The unused repo tabs disappears instead of being moved to "more".

### My suggestion

1. Add a feature that moves "security" and "insights" to the dropdown menu.
2. Add another feature that adds "Compare", "Dependencies", "Commits" and "Branches" in the dropdown menu.
3. Make `more-dropdown` not a "feature", so that any feature can use it, and if there are any features using it, the dropdown menu appears.

BTW, in [the current issue form](https://github.com/sindresorhus/refined-github/blob/9d03cc27e7ff17aaeb3cd56f3ce658141e6a5731/.github/ISSUE_TEMPLATE/1_bug_report.yml), there's no section like "Anything elses?" or "Your suggestions", so I don't know where to properly provide my suggestions.

### Screenshots/video/gif showing the issue, if it’s visual

![img](https://user-images.githubusercontent.com/30581822/125382734-d0bddc00-e3c8-11eb-8bcb-c48753af4e60.png)

### Example URL

https://github.com/trustwallet/assets

### Browser(s) used

Firefox 89.0.2

**Comment by fregante** [comment]
These are all good suggestions. Here are some more (some conflicting) suggestions:

- renamed `remove-unused-repo-tabs` to `clean-repo-tabs` and include moving Insights and Security as the same feature
- hide these tabs via `hidden` property instead of removing them altogether, if it works. This way each tab could be unhidden via CSS and we don’t need to granularize `clean-repo-tabs`

**Comment by yakov116** [comment]
> * renamed [`remove-unused-repo-tabs`](/sindresorhus/refined-github/blob/main/source/features/remove-unused-repo-tabs.tsx) to `clean-repo-tabs` and include moving Insights and Security as the same feature

Big 👍 



> * hide these tabs via `hidden` property instead of removing them altogether, if it works. This way each tab could be unhidden via CSS and we don’t need to granularize `clean-repo-tabs`

Only if it does not require too much work

**Comment by fregante** [comment]
> Only if it does not require too much work

I think it won't require much work, but it might conflict with GitHub’s "responsive nav" logic.
