### ISSUE TITLE
disable markdown rendering 

### ISSUE THREAD

**Issue by foolioo** [sindresorhus/refined-github#4564]
> [Appending `?plain=1` to the url for any Markdown file will now display the file without rendering.](https://github.blog/changelog/2021-06-30-parameter-to-disable-markdown-rendering/)

rather than adding this manually to markdown files, i would love to see a button that does this.

**Comment by fregante** [comment]
There’s a button already, we added it a long time ago: https://github.com/sindresorhus/refined-github/issues/946

The feature is called `view-markdown-source`
