### ISSUE TITLE
Display exact number of commits in hovercard in Contributors section in repository sidebar

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4566]
Often times, I am interested in knowing the number of commits the top contributors have on a particular repo to know the level of engagement / activity.

The repository sidebar has a contributors section which has hovercards for each contributor. However, the hovercard only displays the obvious **Committed to this repository**. ( For more recent contributors, it appends **in the past *[day|week|month]*** which is still not so useful ). It would be nice to display the exact number of commits the user has made to the repository. Something along the lines of **Committed *\<x\>* commits to this repository** and if the contributions are recent, append ***latest* in the past *[day|week|month]***.

There is a [HovercardContext interface](https://docs.github.com/en/graphql/reference/interfaces#hovercardcontext) for the graphQL API. But I have not tried it to see if that is what is used to manipulate the hovercard though.

Would this be a useful feature?

**Comment by fregante** [comment]
You can already see that in the Insights tab, with extra stats
