### ISSUE TITLE
"My Repos" tab in global "Issues" and "Pull requests" pages

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#458]
We've all been there. That issue that you just forgot about. That PR that has been sitting in your repo for months. GitHub offers no simple view that.

I can add "Your repos/PRs" links similar to #406:

* [Open issues on my repos](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+user%3Abfred-it) (link is actually to **my** repos)
* [Open PRs on my repos](https://github.com/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+user%3Abfred-it) (link is actually to **my** repos)

**Comment by busches** [comment]
The links you have there are the same as `Yours` links right now or are you suggesting we add additional criteria?

**Comment by bfred-it** [comment]
Duh, for whatever reason I thought they weren't. Sorry!
