### ISSUE TITLE
Refined GitHub for iOS and iPadOS 

### ISSUE THREAD

**Issue by mainrs** [sindresorhus/refined-github#4580]
Are there additional steps that need to be taken care of to publish a version suitable for iPadOS? Visiting the extension‘s AppStore page shows me a message that the app is not suitable for my device.

**Comment by fregante** [comment]
I think @sindresorhus is looking into this. As far as I know we only need to update the Xcode version and details and it should work. Help wanted anyway

**Comment by mainrs** [comment]
I have to check if I have access to the beta already. I should though since it has been made public on the 1st I think.

**Comment by sindresorhus** [comment]
I plan to look into it closer to the iOS 15 release. I don't want to deal with early-bird bugs and we cannot submit the iOS version until right before the iOS 15 release either.

**Comment by rakleed** [comment]
> we cannot submit the iOS version until right before the iOS 15 release either

@sindresorhus for now, you can use [TestFlight](https://developer.apple.com/testflight/). There are already [some extensions](https://www.reddit.com/r/iOSBeta/comments/om1q3k/list_of_safari_extension_on_testflight/) that work in the beta version of Safari for iOS.

**Comment by fregante** [comment]
PR welcome to make the necessary adjustments to the Xcode project. We can deal with deployment later on.
