### ISSUE TITLE
`avoid-accidental-submissions`: Do not allow a second enter to trigger the action

### ISSUE THREAD

**Issue by stdedos** [sindresorhus/refined-github#4581]
If I am reading https://github.com/sindresorhus/refined-github/pull/4556 correctly, a second Enter (at whatever time) will trigger the action underneath.

Is there a way for that to **never** happen?
I like the differentiation of the commit action to be Ctrl+Enter at all cases.

**Comment by fregante** [comment]
The feature was changed to show the message in order to make you focus while typing, rather than annoyingly change field or completely block the key. If you want a global block of the enter key, it can be written separately with a few lines (but not as part of Refined GitHub), probably:

``` JavaScript 
document.addEventListener(event => {
  if (event.target.closest('input') && !$('.suggester')
    event.preventDefault()
  }
})

**Comment by fregante** [comment]
Nice GitHub lost my comment when I tried to edit it. In short it’s meant to just make you focus rather than completely prevent it. That feature can be written as a userscript in 4 lines of code, but I’d rather not do that here

**Comment by stdedos** [comment]
> Nice GitHub lost my comment

Here it is if you need it:

> The feature was changed to show the message in order to make you focus while typing, rather than annoyingly change field or completely block the key. If you want a global block of the enter key, it can be written separately with a few lines (but not as part of Refined GitHub), probably:
> 
> ```js
> document.addEventListener(event => {
>   if (event.target.closest('input') && !$('.suggester')
>     event.preventDefault()
>   }
> })
> ```

E-mails-for-comments only fire exactly once, immediately 😉 

> because it would be as annoying as [dropping the “Backspace to go back” in Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=144832) IMHO

I was wondering: can't scripts have options? If so, this looks like a prime candidate (it's just a boolean)

**Comment by fregante** [comment]
> E-mails-for-comments only fire exactly once, immediately 😉

Thanks! Unfortunately I had extended that piece of code to actually make it work after the submission, but oh ell.



> I was wondering: can't scripts have options?

https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658

**Comment by fregante** [comment]
I think the feature accomplishes its purpose the way it is now
