### ISSUE TITLE
The same number of forks from one repository is appearing for any other fork

### ISSUE THREAD

**Issue by luizfernandonb** [sindresorhus/refined-github#4582]
Here's an example, the Linux repository has 38k forks
![image](https://user-images.githubusercontent.com/42288418/126085224-59cf1719-4d56-438f-892a-3dec06c02c4d.png)
If I click on the number of forks and enter any of the existing forks, the number of forks from the original repository (38k) will still appear
![image](https://user-images.githubusercontent.com/42288418/126085270-18202c71-8139-43c6-bc3d-da69c4fd525a.png)
Is this an extension bug or does Refined GitHub not do it? I didn't find anything related to this by going to "Find Features" in the extension options

**Comment by yakov116** [comment]
This is how Github works if I am not mistaken. Nothing to do with RG

**Comment by luizfernandonb** [comment]
> This is how Github works if I am not mistaken. Nothing to do with RG

But I didn't remember GitHub doing this before I installed the extension, are you sure what you said?

**Comment by yakov116** [comment]
Can you disable RG and see if this happens?

**Comment by fregante** [comment]
GitHub shows the fork count in the fork network, not the fork of each specific fork. Here’s an example on mobile (no extensions)

![0DCA6D5D-9F5C-40F7-948B-9D91C21D9F63](https://user-images.githubusercontent.com/1402241/126108609-7ba47ae8-25c2-4499-8447-4f0515e2b06c.jpeg)

**Comment by luizfernandonb** [comment]
> GitHub shows the fork count in the fork network, not the fork of each specific fork. Here’s an example on mobile (no extensions)
> 
> I don’t think it’s worth updating this number as forks of forks that matter are extremely rare on GitHub; In the vast majority of cases we could show a static 0 and be right 😃
> 
> ![0DCA6D5D-9F5C-40F7-948B-9D91C21D9F63](https://user-images.githubusercontent.com/1402241/126108609-7ba47ae8-25c2-4499-8447-4f0515e2b06c.jpeg)

Ok, thanks
