### ISSUE TITLE
Warn about lying links

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4588]
This link is a liar!
- [https://github.com/sindresorhus](https://octolinker-demo.vercel.app/sindresorhus)

``` md
[https://github.com/sindresorhus](https://octolinker-demo.vercel.app/sindresorhus)
```

If a link in a markdown area appears as a URL, we can ensure that the shown origin matches the real origin or its no-www version. If not, we can show a warning icon with “origin mismatch” tooltip or something similar, like `this link opens “other.domain.com”`

**Comment by kidonng** [comment]
This looks like it can benefits all websites, not just GitHub.
