### ISSUE TITLE
`reactions-avatars` disappears for a second after reacting

### ISSUE THREAD

**Issue by Milo123459** [sindresorhus/refined-github#4591]
Hey,

When you are reacting to something, it displays who reacts, but when you react, it removes that temporarily. It's very annoying and I suggest that it always shows who reacted and then that updates on refresh. 

More descriptive:

Go to a comment, with reactions, click the reactions and it'll remove who reacted temporarily. Make it so it stays when you react, and then it updates on refresh.

Thanks.

**Comment by Milo123459** [comment]
https://user-images.githubusercontent.com/50248166/126346869-a7d104a0-0c29-4c17-aa8b-7cc6379ef6f6.mp4

As you can see it disappears when I react, and I propose it stays and updates on refresh.

**Comment by fregante** [comment]
It's a minor inconvenience that we tried fixing before but there's no easy solution. It works well enough now so it's not worth using `selector-observer`, but perhaps we can deal with it with `onReplacedElement`

**Comment by Milo123459** [comment]
Are you sure you just make it update on refresh and not until refresh? Surely that has to be easier then updating every time you react.

**Comment by yakov116** [comment]
@fregante should we make a label feature disabled?

**Comment by Milo123459** [comment]
This is being disabled...?

**Comment by yakov116** [comment]
Via hotfix

**Comment by Milo123459** [comment]
Hotfix? For the new broken github reaction avatar?

**Comment by fregante** [comment]
Yes https://github.com/sindresorhus/refined-github/tree/hotfix

**Comment by Milo123459** [comment]
Are there any updates on this? 🤔
