### ISSUE TITLE
`clean-pinned-issues` contains vertically misaligned elements in Chrome

### ISSUE THREAD

**Issue by 4086606** [sindresorhus/refined-github#4598]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Text and icons in `clean-pinned-issues` appears misaligned and uses the table display mode for no discernable reason.

This issue occurs over 700px and makes the feature quite annoying to use.

### Screenshot

<img alt="github com_microsoft_vscode_issues_q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc" src="https://user-images.githubusercontent.com/82655227/126564310-2fad4029-39d1-43b9-9c5d-ccab682db99d.png" height="450"/>

### Example URL

https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

### Browser(s) used

Chrome 91.0.4472.124

**Comment by busches** [comment]
Not sure what I'm missing, looks like the example screenshot - https://user-images.githubusercontent.com/1402241/84509958-c82a3c00-acc4-11ea-8399-eaf06a59e9e4.png.

**Comment by fregante** [comment]
Can you post what it looks like on this repo since we have multiple lines? I see that the text is slightly lower, but it might just be attributable to the font and I don’t know if it can be fixed across-systems

**Comment by fregante** [comment]
In fact you can see that the text in the Labels | Milestones buttons are also slightly misaligned, but it's less evident because there isn't so much lowercase text in it.

**Comment by 4086606** [comment]
I believe it's using display: table but that's not really as versatile as flexbox which would do this easily across browsers

**Comment by fregante** [comment]
You can see the same misalignment in the buttons I mentioned, which are plain inline-block. 

As for flex vs table, you can find the reason why it was chosen in the original PR (I think it was because it just required less code). I don’t think flex would solve the issue, but if you can do that without altering the padding explicitly then sure 👍

**Comment by 4086606** [comment]
Alignment padding definitely does work differently between Firefox and Chrome, caused me a lot of grief in my UI bootcamp days

**Comment by 4086606** [comment]
One liner fix
