### ISSUE TITLE
Aborting after clicking "Delete fork" not possible

### ISSUE THREAD

**Issue by edisim** [sindresorhus/refined-github#4599]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

It's not possible to stop the deletion process after clicking the "Delete Fork" button in the top right corner.

### Screenshot

![screenshot](https://user-images.githubusercontent.com/1998736/126570414-9fbd8225-a648-4e87-b44a-c7b5d75bf4b0.png)

### Example URL

https://github.com/edisim/outline/tree/master

### Browser(s) used

Firefox Developer Edition 91.0b3 (64-Bit) on Windows 10

**Comment by fregante** [comment]
Oh god nightmare scenario. Let's

1. Fix the z-index issue
2. Add once:true global click listener to interrupt the process to ensure this can never happen
