### ISSUE TITLE
Add link to a user's twitter profile

### ISSUE THREAD

**Issue by kentcdodds** [sindresorhus/refined-github#46]
[Original Tweet](https://twitter.com/kentcdodds/status/704327479377285121):

<img width="595" alt="screen shot 2016-02-29 at 8 38 23 am" src="https://cloud.githubusercontent.com/assets/1500684/13399305/d3b0dafc-debf-11e5-8fbe-2317b65d4c3d.png">

I feel like there are services that try to collect accounts for a person on multiple platforms... Maybe we could find and use one of these?

Or a user could opt-in to something... But yeah... Thinking this is best as a built-in feature of GitHub for it to really work.

**Comment by hkdobrev** [comment]
I think this could be a separate extension. You could always add your Twitter profile URL instead of your website.

**Comment by kentcdodds** [comment]
> You could always add your Twitter profile URL instead of your website.

Right. I could do that myself, but my request is that it's easier for me to find other people's twitter account to mention them when I tweet about their project for example.

**Comment by bevacqua** [comment]
I'd like this in `refined-github` as well. Maybe if `Location` contains a Twitter address remove that and add the link as @kentcdodds shows in his mockup.

Location is an arbitrary text field so users who just pasted their Twitter link would get no Location info, and users who entered something like "https://twitter.com/nzgb | Buenos Aires, Argentina" would get the correct location and the Twitter link as well.

I could code this up

**Comment by bevacqua** [comment]
A weird alternative could be to come up with a package that looks up a GitHub user on npm, and then looks up the Twitter profile they've set up on npm, but it would probably not work for most people (who don't bother setting up npm profiles or don't even use npm).

**Comment by kentcdodds** [comment]
Interesting ideas! Honestly, I'm not personally interested enough to actually code anything up, but @sindresorhus recommended I file an issue anyway :-) Would love to see this implemented :-)

**Comment by bevacqua** [comment]
I'd implement the second one

**Comment by mohsen1** [comment]
:-1:

**Comment by sindresorhus** [comment]
I would really like to see this, but per https://github.com/sindresorhus/refined-github/pull/54#issuecomment-193690244, I think it would be better as a separate extension.

@bevacqua Any interest in publishing it as a separate extension?

**Comment by bevacqua** [comment]
@sindresorhus Published here: https://github.com/bevacqua/twitter-for-github
