### ISSUE TITLE
`dim-bots` not compressing all PRs

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4600]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The bot PRs are correctly detected and one of them is even compressed, but most of them aren't

### Screenshot

<img width="584" alt="Screen Shot 1" src="https://user-images.githubusercontent.com/1402241/126604564-3ce0b5c2-cc1d-4662-92f9-c5d3193f247c.png">

### Example URL

https://github.com/mozilla/dispensary/pulls

### Browser(s) used

safari

**Comment by kidonng** [comment]
Looks like a regression in #4383
