### ISSUE TITLE
`toggle-everything-with-alt` is not working for the expand diff button

### ISSUE THREAD

**Issue by a7madgamal** [sindresorhus/refined-github#4601]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

when I alt-click (opt-click in mac) on the file diff expand button it doesn't expand all other files in the PR as expected 

### Screenshot

![image](https://user-images.githubusercontent.com/939602/126617954-c0df076b-18e5-43f4-8c50-95f818e3ec2f.png)

### Example URL

https://github.com/sindresorhus/refined-github/pull/4585/files

### Browser(s) used

Chrome

**Comment by kidonng** [comment]
"not working" is not correct, it's just Refined GitHub hasn't added support for that button since it's pretty new.
