### ISSUE TITLE
Run the extension on different redirected Github Enterprise

### ISSUE THREAD

**Issue by vibhavagarwal5** [sindresorhus/refined-github#4612]
Our company uses the enterprise github with a different url than `github.com`. Is there any way to run the extension the same way on that url as it runs on `github.com`?

**Comment by busches** [comment]
Yes, see this link from the readme https://fregante.github.io/webext-domain-permission-toggle/?name=Refined%20GitHub&icon=https%3A%2F%2Fraw.githubusercontent.com%2Fsindresorhus%2Frefined-github%2Fmain%2Fdistribution%2Ficon.png

**Comment by vibhavagarwal5** [comment]
Doesnt work on brave browser, despite being chromium based.
