### ISSUE TITLE
 sync-pr-commit-title compatible with default merges

### ISSUE THREAD

**Issue by louisefindlay23** [sindresorhus/refined-github#4614]
### Description

The existing `sync-pr-commit-title` feature is very useful to automate replacing the merge commit default title `Merge pull request #3041 from achiengrhoda/Getting-started-with-Packet-Tracer` which is long and cluttered with the PR title which is far more succinct and to the point. 

However, it only works for squash and commit merges and not default merges. Having the ability to use this great feature for those who use default merges would be very useful and desireable.

### Screenshot

![sync-pr-commit-title Screenshot](https://user-images.githubusercontent.com/26024131/127146477-1324dfb1-aae1-46ff-9765-ec81c0bc870a.png)

### Example URL

https://github.com/section-engineering-education/engineering-education/pull/2896

**Comment by fregante** [comment]
That's how it worked initially but after some complaints we limited it to squash commits:

- https://github.com/sindresorhus/refined-github/issues/2713

**Comment by louisefindlay23** [comment]
Thanks, Federico. I think it would be nice to have a button to do this. 

Will close this issue in favour of #2768.
