### ISSUE TITLE
Remove GitHub Marketplace block from pull requests

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#462]
![image](https://cloud.githubusercontent.com/assets/506129/26692968/41fbe7ae-470b-11e7-8b9d-1b102c31c5b5.png)

You could find this on pull requests without a commit status where you are an administrator.

This should be removed in order to abide by the other UI elements we've removed which are not useful to power users.

**Comment by hkdobrev** [comment]
I can't reproduce this box anymore after I've dismissed it. I've cleared all my GitHub Application storage - cookies, localstorage etc. Tried with changing protected branches settings and still nothing. Either GitHub has removed it or they persist that I've dismissed it in the database.

If anyone sees it, please just remove it via CSS or paste the selector here. Thanks!

**Comment by bfred-it** [comment]
If it's something that only appears once _ever_ I think we can just let it live.

**Comment by sindresorhus** [comment]
Just display none this: `.js-marketplace-callout-container`

**Comment by bfred-it** [comment]
It showed up again for me. I'm just gonna add a uBlock filter:

```
github.com##.js-marketplace-callout-container
```
