### ISSUE TITLE
Execute `parse-backticks` on issue title edit

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4621]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

`parse-backticks` executes only `onetime` during page load. When an issue title is edited to add back-ticks, on save, the back-ticks are rendered as is until page refresh.

### Steps to Reproduce
1. Create issue without back-ticks in title
2. Edit issue title to add back-ticks
3. Save issue title

### Example URL

github.com/sindresorhus/refined-github/issues/4620

### Browser(s) used

Firefox

**Comment by yakov116** [comment]
Issue titles are parsed by github not by RG. 

I would give the issue ref but I am on mobile

**Comment by fregante** [comment]
> * [x]  The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

eeeeeeeeh 😅
