### ISSUE TITLE
`repo-age` appears duplicate

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4622]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

1. Visit https://github.com/vutran/twas/tree/v2.1.2
2. Go to the Master branch **from the branch dropdown** (not with our `default-branch-button`)
3. Go back in history
4. Go forward in history

It might be worth checking if other features are affected.

### Screenshot

https://user-images.githubusercontent.com/1402241/127603617-4eaba574-c1d3-4ba0-bf32-138ca88eef6e.mov

### Example URL

https://github.com/vutran/twas/tree/v2.1.2

### Browser(s) used

Safari

**Comment by kidonng** [comment]
This may have been brought up in other places, but I'd like add that pinned issues update time are also duplicated.

(Can't give a screenshot now because I'm outside)

**Comment by fregante** [comment]
<img width="1240" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/128303804-2f09df01-9a30-4dc7-991d-e84cec963f83.png">

Yes. Repro:

1. From this issue
2. Visit Issues tab
3. Go back
4. Go forward
