### ISSUE TITLE
Icon position and color issues

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4625]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

- `first-published-tag-for-merged-pr` is a little lower compared to the native copy button

  ![image](https://user-images.githubusercontent.com/44045911/127671115-5a59057f-4b54-4407-85a4-46681fd5e4ce.png)

- `conversation-activity-filter` (or perhaps it's `first-published-tag-for-merged-pr`, not sure) icon in the sticky header has wrong color
  
  ![image](https://user-images.githubusercontent.com/44045911/127671268-35100165-ba1a-4060-bdcc-041c92e91529.png)

  EDIT: it seems both icon don't match with the native copy button:

  - Copy button: `rgb(88, 96, 105)`
  - `first-published-tag-for-merged-pr`: `rgb(106, 115, 125)`
  - `conversation-activity-filter`: `rgb(36, 41, 46)`

- (Not a bug, this is a little opinionated) `conversation-activity-filter` can have a larger left margin if it follows the comment count

  ![image](https://user-images.githubusercontent.com/44045911/127671372-724d6481-015f-4fff-a06f-cf25468de3ce.png)

### Screenshot

See above

### Example URL

https://github.com/sindresorhus/refined-github/pull/4029

### Browser(s) used

Chrome

**Comment by fregante** [comment]
### 💯

**Comment by toth2000** [comment]
Can I work on this issue?

**Comment by yakov116** [comment]
Sure
