### ISSUE TITLE
`reactions-avatars` style applied to not implemented pages

### ISSUE THREAD

**Issue by altrisi** [sindresorhus/refined-github#4630]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The reaction count number in a discussion's or a release's reaction gets a gray background in a square around it.

Not only that, those counts also seem to get slightly misaligned and smaller in comparison to without Refined Github.

Find Feature can't find it, so it may be a problem in a global stylesheet.

### Screenshot

With Refined Github:
![imagen](https://user-images.githubusercontent.com/17107132/127853370-17a2cfce-e299-47c9-9e19-ac436299c373.png)

Without Refined Github:
![imagen](https://user-images.githubusercontent.com/17107132/127853817-4e60795a-29eb-4310-ab86-af1425bcbd30.png)

### Example URL

https://github.com/github/feedback/discussions/4291
https://github.com/sindresorhus/refined-github/releases/tag/21.8.1

### Browser(s) used

Firefox 90.0.2

**Comment by jdreesen** [comment]
It's the same for reactions in releases.

**Comment by fregante** [comment]
This should be an easy fix, it's just a matter of finding a stricter selector in the CSS. Pseudo-code:

```diff
- .reaction {
+ .comments .reaction {
```
