### ISSUE TITLE
`reactions-avatars` style applied to not implemented pages

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4632]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Related #3978

`reactions-avatars` is only implemented on issues and PR pages, however the styles apply to discussion pages (e.g. https://github.com/PatrickF1/fzf.fish/discussions/101)

![image](https://user-images.githubusercontent.com/44045911/127893160-cc438e71-4e42-41f5-b5c2-1d45cb85e94b.png)
![image](https://user-images.githubusercontent.com/44045911/127893168-8037bfd6-00b5-48be-9523-b81f40a328af.png)

... and releases pages (e.g. https://github.com/sindresorhus/refined-github/releases/tag/21.8.1) as well.

![image](https://user-images.githubusercontent.com/44045911/127893179-17bb0a36-e2aa-441c-9394-528a3c0ca616.png)
![image](https://user-images.githubusercontent.com/44045911/127893182-085c345a-d807-43ca-b54a-9b943fb3ed5d.png)

### Screenshot

See above

### Example URL

See above

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
#4630

**Comment by kidonng** [comment]
Was it because I'm too familiar with RGH? I literally just searched for `reactions-avatars` and opened this because I see nothing about it 😄

Anyway thanks for the pointer @yakov116
