### ISSUE TITLE
Drop `linkify-labels-on-dashboard`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4643]
## Expected

<img width="600" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/69045444-6ef97300-0a29-11ea-99a3-9a622c395709.png">

## Current

No labels

<img width="306" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/128231950-9ae37181-0b1e-4329-899c-80a3f2204c42.png">

**Comment by yakov116** [comment]
This also made all the All activity labels. Why can we not restore it for that?

**Comment by fregante** [comment]
Reopened the other issue
