### ISSUE TITLE
Support organization page redesign

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4644]
Seems like GitHub rolled out a redesign to organization page, with a new overview page ([example](https://github.com/NixOS)) and standalone repositories page ([example](https://github.com/orgs/NixOS/repositories)).

![image](https://user-images.githubusercontent.com/44045911/128506337-3ca8138a-eb83-4305-8396-6138a354068c.png)

Some existing features may have stopped working or no longer support the redesigned page. We should look into it.

**Comment by fregante** [comment]
What's broken exactly?

**Comment by kidonng** [comment]
I thought about `link-to-github-io` or `set-default-repositories-type-to-sources`, but they didn't break and possibly nothing breaks... I just thought the update is huge and want raise attention.

But `github-url-detection` can possibly get an update.

**Comment by fregante** [comment]
> But `github-url-detection` can possibly get an update, at least.

👍 

I checked `isOwnOrganizationProfile` and `isOrganizationProfile` and they still both apply (DOM-based). We don't have other checks related to the profile:

https://github.com/fregante/github-url-detection/blob/50bd30f39419be342986935af6ccfaadcc5c2df5/index.ts#L164

**Comment by fregante** [comment]
Thanks for checking, let's reopen when we find something.
