### ISSUE TITLE
Suppress link for an author in project cards

### ISSUE THREAD

**Issue by wacul-yamada** [sindresorhus/refined-github#4645]
### Description

When I am working with cards in the Projects screen, I often click on the author's link and the screen transitions, which is very frustrating. I can't imagine that there would be any incentive to jump from this screen to the author's profile page that often.
This link is very annoying and I think it should be suppressed.

It can be suppressed by css like below.

```css
.project-card a.color-text-primary {
    pointer-events: none;
}
```

### Screenshot

![image](https://user-images.githubusercontent.com/84360987/128585232-a9596170-ac2e-4de4-a383-6825dd9c564c.png)

### Example URL

https://github.com/kyoh86-tryouts/test/projects/1

**Comment by fregante** [comment]
Sorry we don't make any changes to Projects, and also this sounds like a "breaking" change as some users might be using that link like they would expect everywhere else on the site.
