### ISSUE TITLE
Add filter to allow specific bots to be visible when `dim-bots` is enabled

### ISSUE THREAD

**Issue by bbugh** [sindresorhus/refined-github#4652]
### Description

We use Sentry to capture errors, and when linking an issue to GitHub, Sentry uses `sentry-bot`. This results in important issues being dimmed out, making it hard to remember to check. We would like to allow these to be normal looking, while still hiding bots like `snyk` and `renovate` that automatically merge.

### Screenshot

This would appear as a regular issue for the filtered bots, instead of dimmed.

### Example URL

https://github.com/bbugh/vue-tsx-tailwind-starter/pulls?page=2&q=is%3Apr+is%3Aclosed

**Comment by fregante** [comment]
No options possible: https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658

I'm afraid you'll have to disable the feature

**Comment by bbugh** [comment]
Shazbot. Ok, thank you.
