### ISSUE TITLE
Surface outages from https://githubstatus.com to Github UI

### ISSUE THREAD

**Issue by seemethere** [sindresorhus/refined-github#4653]
### Description

As we become more reliant on Github for services like Actions, the Github API, etc., we should be more aware of outages that could effect our workflow. I'm suggesting that we provide a dropdown menu to the left of the notification bell that should show current outages (if any)

Currently there is an [RSS feed](https://www.githubstatus.com/history.rss) for Github Status updates or recent tweets can be surfaced from https://twitter.com/githubstatus

### Screenshot

![image](https://user-images.githubusercontent.com/1700823/128943830-8994df05-623e-4dc6-b0da-d15202d5f4e6.png)

### Example URL

https://github.com

**Comment by fregante** [comment]
Note: Something like this would require regular fetches of the status, like twice an hour or more frequently, which wouldn’t be great.

**Comment by kidonng** [comment]
Love the intention but I don't like this proposal.

None of the mainstream SaaS platform I know has this kind of outage indicator. Meanwhile, GitHub has always provided the status page link:

- In the footer of _every page_ (though the footer is muted by Refined GitHub)
- On the error page (e.g. [500](https://github.com/500), [502](https://github.com/502), [503](https://github.com/503))

Meanwhile the status page has provided 5 different ways for subscribing updates, including email, text message, webhook, Twitter and RSS:

![image](https://user-images.githubusercontent.com/44045911/129195742-01c8ab3d-9b10-4061-96e2-9fec35403665.png)

In my opinion they are both more reliable and prompt than whatever implementation Refined GitHub may get, there's no reason not to use them.

**Comment by fregante** [comment]
As mentioned, this would require too many requests. It's best as a dedicated extension
