### ISSUE TITLE
Simpler GraphQL syntax?

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4654]
Thinking out loud…

What if we went from:

```ts
repository() {
	ref(qualifiedName: "${branch}") {
		target {
			... on Commit {
				history(first: 1, path: "${filePath}") {
					nodes {
						oid
						commitDate
					}
				}
			}
		}
	}
}
```

To:

```ts
repository()
ref(qualifiedName: "${branch}")
target
... on Commit
history(first: 1, path: "${filePath}")
nodes
oid commitDate
```

where every line break is a `{` and every missing `}` is appended.

Most of our queries are allowed with this syntax. Others can keep using the native syntax.

It would be its own helper like:

```ts
api.v4(ql`
	  repository()
	  ref(qualifiedName: "${branch}")
	  target
	  ... on Commit
	  history(first: 1, path: "${filePath}")
	  nodes
	  oid commitDate
`)
```

and multiple queries can be concatenated as strings too:

```ts
api.v4(ql`
	  repository()
	  ref(qualifiedName: "${branch}")
	  target
	  ... on Commit
	  history(first: 1, path: "${filePath}")
	  nodes
	  oid commitDate
` + ql`
	  query2: repository()
	  name
`)
```

Thoughts? Worth it? 😂

**Comment by yakov116** [comment]
I think that kills the beauty of GraphQL. What I like it most is the way the call is made, that is what the response looks like.

It may take up more "lines" but I think the other way is clearer. JMHO

**Comment by yakov116** [comment]
> * `console.debug` for every call in `api.v4` when installed locally

Big 👍

**Comment by sindresorhus** [comment]
I find the original syntax more readable.
