### ISSUE TITLE
Support additional tokens for Github Enterprise

### ISSUE THREAD

**Issue by PatrickAuld** [sindresorhus/refined-github#4658]
### Description

Currently, only a single Github token may be set for Refined Github. For anyone working both in Github.com and an Enterprise server, this means some features only work in one place.

Supporting at most two tokens, one for Github.com and one for the Enterprise server would cover nearly everyone's use cases and would avoid extra logic around a dynamic number of tokens and how to support that. My example screenshot below gives two token fields, one that is always for Github.com and another that allows you to enter the Enterprise server domain.

### Screenshot

<img width="558" alt="Screen Shot 2021-08-11 at 2 24 50 PM" src="https://user-images.githubusercontent.com/708867/129105769-9c157a88-9c6b-43c2-93a8-7594fd111eb0.png">

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/distribution/options.html#L22

**Comment by yakov116** [comment]
From The readme
GitHub Enterprise is also supported: [How to enable it](https://fregante.github.io/webext-domain-permission-toggle/?name=Refined%20GitHub&icon=https%3A%2F%2Fraw.githubusercontent.com%2Fsindresorhus%2Frefined-github%2Fmain%2Fdistribution%2Ficon.png).

**Comment by busches** [comment]
The token is unique for each domain in the drop-down. I use GHE with a token everyday. If you're still not sure, see @yakov116's reply which includes more instructions.
