### ISSUE TITLE
`git-checkout-pr` is broken

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4661]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

<img width="426" alt="Screen Shot 11" src="https://user-images.githubusercontent.com/1402241/129320364-ad9ef70c-98a5-4ee3-a7e3-f33ddaedbe94.png">

### Console errors

It appears when clicking the Code dropdown 
```shell
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'select_dom('[action="/users/checkout-preference"]', dropdown).closest')
```

### Example URL

https://github.com/sindresorhus/refined-github/pull/4650

### Browser(s) used

safari

**Comment by cheap-glitch** [comment]
In my case there's not even tabs in the dropdown anymore:
![image](https://user-images.githubusercontent.com/46634000/129339841-8ddf4b16-0b97-4c64-9684-1beeed516d82.png)

**Comment by fregante** [comment]
The good part is that this should now just be part of the main/local tab, so it should work regardless of tabs.

**Comment by kidonng** [comment]
> In my case there's not even tabs in the dropdown anymore:

Did you have Codespaces enabled? Because I have and I see this error when opening the dropdown:

```
Uncaught (in promise) TypeError: Cannot read property 'defaultProps' of undefined
    at create (refined-github.js:3531)
    at Object.h [as createElement] (refined-github.js:3563)
    at checkoutOption (refined-github.js:7868)
    at HTMLHtmlElement.handleMenuOpening (refined-github.js:7895)
    at HTMLHtmlElement.listenerFn (refined-github.js:3365)
```
