### ISSUE TITLE
`sync-pr-commit-title` stopped working

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#4662]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Try to merge any PR

### Screenshot

![image](https://user-images.githubusercontent.com/16872793/129359305-7048540b-3cdf-4318-8acc-b4b75660329f.png)

### Console errors

```shell
None
```

### Example URL

https://github.com/sindresorhus/refined-github/pull/4650

### Browser(s) used

Chrome

**Comment by yakov116** [comment]
Looks like `convert-pr-to-draft-improvements` is broken too! anything on the merge box is broken

**Comment by fregante** [comment]
Related:

- https://github.com/sindresorhus/refined-github/issues/4647
- https://github.com/sindresorhus/refined-github/issues/3041 (might be a good time to improve the implementation as well, but maybe for now it's just a matter of updating the selectors)

**Comment by yakov116** [comment]
@cheap-glitch you want to take a shot at this? (Its your type of thing 😄 )

**Comment by cheap-glitch** [comment]
> @cheap-glitch you want to take a shot at this?

I wanted to but couldn't find a good testing page (none of my repos have GH Actions set up). Maybe I'll open a PR on `github-url-detection` first, I think I have merging rights there :thinking:

**Comment by fregante** [comment]
You can create a repo with this workflow so you can push as much as you want:

```yml
name: CI

on:
  - push

jobs:
  wait:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 30
```

**Comment by fregante** [comment]
Most likely it's just https://github.com/sindresorhus/refined-github/issues/4695

It [just worked](https://github.com/fregante/chrome-webstore-upload/pull/46#event-5322589168) for me in Safari
