### ISSUE TITLE
Extend `sticky-sidebar` to other places

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4664]
### Description

GitHub has revamped the organization profile pages to look consistent with the overall layout of the rest of the website.

It now has a sidebar that could possibly be made sticky with `sticky-sidebar`.

I made a quick attempt to evaluate whether this could be a small enough change to pursue even with the [summer feature freeze](https://github.com/sindresorhus/refined-github/issues/4596).

But it was not directly obvious to me for 2 reasons : 
1. The selector used to select the sidebar uses a ternary operator
	https://github.com/sindresorhus/refined-github/blob/fd71c473b92cc2597590f89b1e3aba22832837e9/source/features/sticky-sidebar.tsx#L11
	which would mean a non-trivial effort in adding a new selector.
2. `isOrganizationProfile` from [`github-url-detection`](https://github.com/fregante/github-url-detection) is a [`document`-based detection](https://github.com/fregante/github-url-detection#document-based-detections)

I could make an effort at this if it is okay to during the feature freeze.

### Screenshot

![image](https://user-images.githubusercontent.com/4771718/129445473-9eee7d97-286c-4b26-96ba-a69fefb55dca.png)

### Example URL

https://github.com/tc39

---

**EDIT** : from https://github.com/sindresorhus/refined-github/issues/4144#issuecomment-902142687, this feature could be extended to wiki table of contents too.

**Comment by fregante** [comment]
The content of the sidebar doesn't seem to be particularly useful to spend any time on it.

**Comment by cheap-glitch** [comment]
> The selector used to select the sidebar uses a ternary operator

This needs to be rewritten anyway, cf. https://github.com/sindresorhus/refined-github/pull/4522#discussion_r660576801
