### ISSUE TITLE
No checkbox next to the new `Log API calls in the console` option label

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#4666]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

In today's release 21.8.14, PR #4656 was merged.

Unfortunately, as you open the extension's Options, you'll notice there's no checkbox next to its "Log API calls in the console" label (see screenshot below). 

I also tested it in a fresh Chrome/Firefox profile, with only RG (w/ token).
There's no error in console.

### Screenshot

![2021-08-14_211141](https://user-images.githubusercontent.com/723651/129456489-9d6dde58-b6e5-42f0-9ddd-38ca066eca61.jpg)

### Console errors

```shell
```

### Example URL

Any page, e.g. this one

### Browser(s) used

Chrome 92, Firefox 91

**Comment by yakov116** [comment]
My mistake. That should not be visible at all.
It's only intended for development use.
