### ISSUE TITLE
Commits have excess backticks

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#4671]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Look at any page that lists commits, such as a PR

Expected behavior: the commit message is displayed without adornment
Actual behavior: the commit message has extra backticks surrounding it

### Screenshot

<img width="413" alt="Screenshot_2021-08-15 11 51 09" src="https://user-images.githubusercontent.com/25517624/129484426-d19b8ca1-b577-497f-b984-c5fdf4afe605.png">

### Example URL

https://github.com/sindresorhus/refined-github/pull/4667

### Browser(s) used

Safari Technology Preview Release 129 (Safari 15.0, WebKit 16612.1.24.11.7), Refined GitHub from the `main` branch (ac8de6bd)

**Comment by yakov116** [comment]
@fregante can you test this in Safari? I do not see this on windows

**Comment by j-f1** [comment]
🤦 it’s from a custom style extension — RGH adds a class to the code and some unrelated CSS selected for `code[class]` on all websites.
