### ISSUE TITLE
Add an option to disable merge conflict UI

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#4672]
Sometimes it doesn't work correctly and leads to something like this: [`533e423` (#1118)](https://github.com/apify/apify-js/pull/1118/commits/533e4239cb445a5b8bfaa95001593af887a8013e) (removal of `====================`)

**Comment by fregante** [comment]
The feature can already be disabled, it's called `resolve-conflicts`

**Comment by szmarczak** [comment]
Sorry, I meant to completely hide the `Resolve conflicts` button:

![image](https://user-images.githubusercontent.com/36894700/129772722-d5c23c69-9ee6-4ea4-8192-8303810fc5e1.png)

**Comment by szmarczak** [comment]
While I understand that this is a nice feature by GitHub, it's not the best tool to resolve conflicts. Sometimes I use this feature and come to a pitfall where something didn't go right and have to merge it manually.

**Comment by fregante** [comment]
If you don't like it don't use it. It's a great tool to resolve small conflicts on the fly, we won't just drop a whole GitHub feature. Sometimes they work, sometimes they don't, it's up to the user to decide that.
