### ISSUE TITLE
`resolve-conflicts` may remove unrelated `===================` strings

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4673]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

From https://github.com/sindresorhus/refined-github/issues/4672 by @szmarczak

> Sometimes it doesn't work correctly and leads to something like this: [`533e423` (#1118)](https://github.com/apify/apify-js/pull/1118/commits/533e4239cb445a5b8bfaa95001593af887a8013e) (removal of `====================`)

### Screenshot

<img width="448" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/129766314-f90e4cad-27dd-422a-9d41-8dd90848496a.png">

### Example URL

Any merge conflict page, like https://github.com/sindresorhus/refined-github/pull/148/conflicts

### Browser(s) used

unknown

**Comment by szmarczak** [comment]
https://user-images.githubusercontent.com/36894700/129774622-8b5c9ccc-a6fb-4502-a7c0-90e93e6e9471.mp4
