### ISSUE TITLE
Proposal: `linkify-code-block`

### ISSUE THREAD

**Issue by Yash-Singh1** [sindresorhus/refined-github#4687]
### Description

Currently, there is `linkify-code` to auto link in-code links inside files. However, code blocks in comments aren't linkified. For example:

```ts
/**
Returns a boolean for whether the given two types are equal.
@link https://github.com/microsoft/TypeScript/issues/27024#issuecomment-421529650
*/
```

This feature request is for the same thing as `linkify-code` but in markdown code.

### Screenshot

![Screenshot from 2021-08-19 20-00-28](https://user-images.githubusercontent.com/53054099/130172675-18c68af6-5f83-4ca5-8b76-e1e9a642f326.png)

### Example URL

https://github.com/sindresorhus/refined-github/issues/4687

**Comment by fregante** [comment]
That's already supposed to work in `linkify-code`, but it's broken. I opened a bug report: https://github.com/sindresorhus/refined-github/issues/4688
