### ISSUE TITLE
`conflict-marker` sometimes missing

### ISSUE THREAD

**Issue by Noordfrees** [sindresorhus/refined-github#4692]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The conflict marker is sometimes missing from the list of open PRs. To reproduce, head to [this PR list with some conflicting PRs](https://github.com/widelands/widelands/pulls) in it and scroll down. Possibly related is that all PRs with conflicts in this list are so far down that you need to scroll down before you reach any. The marker is not missing all the time, sometimes it's there and sometimes not. Press <kbd><kbd>g</kbd> <kbd>i</kbd></kbd> <kbd><kbd>g</kbd> <kbd>p</kbd></kbd> a few times to increase the chance of hitting this bug.

P.S. Thank you for this fantastic browser extension!

### Screenshot

![conflict-marker-1](https://user-images.githubusercontent.com/48293446/130231863-b127aa85-5941-40f8-9277-185364b37938.png)
![conflict-marker-2](https://user-images.githubusercontent.com/48293446/130231875-16c03fc6-ba51-4baa-bf18-953a03224cd3.png)

### Example URL

https://github.com/widelands/widelands/pulls

### Browser(s) used

Mozilla Firefox 91.0.1

**Comment by fregante** [comment]
I think a lot of features are often missing. I have to refresh the page to make them appear. The page update listener needs to be tweaked and there are already a couple of PRs around it.

**Comment by fregante** [comment]
Confirmed, related to:

- #4695 

Repro:

1. Open https://github.com/widelands/widelands/issues?q=label%3Abug
2. Click "Pull requests" tab
3. No PRs have conflict markers
4. Refresh page
5. Some PRs at the bottom have conflict markers
