### ISSUE TITLE
Make the Releases editor font monospace

### ISSUE THREAD

**Issue by szmarczak** [sindresorhus/refined-github#4693]
### Description

I'm not sure if this is best idea but definitely would be cool for code snippets 🤔 

### Screenshot

<details>
<summary>Before</summary>

![image](https://user-images.githubusercontent.com/36894700/130286484-d9c9f539-0662-47ad-b9ea-4697d930f33d.png)

</details>

<details>
<summary>After</summary>

![image](https://user-images.githubusercontent.com/36894700/130286564-1751e487-fc59-4682-bd17-82f4a7260463.png)

</details>

### Example URL

https://github.com/sindresorhus/got/releases/edit/v12.0.0-beta.1

**Comment by fregante** [comment]
I'm surprised this isn't already the case, we have a feature for "monospace textareas"

**Comment by kidonng** [comment]
Yup, this is actually a bug in `github-url-detection`. Waiting for fregante/github-url-detection#93
