### ISSUE TITLE
`rgh-feature-descriptions` is broken on `reactions-avatars`

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4697]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

```
`rgh-feature-descriptions`: undefined is not an object (evaluating '(await elementReady(".Box-header--blue.Details, include-fragment.commit-loader")).parentElement')
```

### Screenshot

<img width="388" alt="Screen Shot 13" src="https://user-images.githubusercontent.com/1402241/130325022-47db35dd-72d1-42d0-8a31-225be498b686.png">
<img width="1313" alt="Screen Shot 12" src="https://user-images.githubusercontent.com/1402241/130325025-4e640333-c361-46e3-b1c6-f25f0981b471.png">

### Console errors

```shell
Not really useful: 👇 


safari-web-extension://DE848C9B-F1EE-494A-9DE4-36164F895DBF/build/refined-github.js:9029:231
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
```

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/source/features/reactions-avatars.tsx

### Browser(s) used

Safari

**Comment by kidonng** [comment]
My best bet is this used to only break in Safari because GitHub is A/B testing the new styles
