### ISSUE TITLE
Verify every feature on CI

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4698]
- Replace https://github.com/sindresorhus/refined-github/pull/4495

This workflow should be replaced by a simple node script that ensures:

- only .tsx and .css files exist in `/features/`
- [`getFeaturesMeta`](https://github.com/sindresorhus/refined-github/blob/cb722b0639a0bf5f546b036ff95d9f4c26930517/build/readme-parser.ts) matches the `tsx` files in `/features/` exactly and is full
- each file appears in `refined-github.tsx`

Pseudo-code:

```js
const featuresFromReadme = getFeaturesMeta()

for (const file of featuresDirectory) {
	if (file.extension === 'css' || file === 'index.tsx') {
		continue;
	}
	
	if (!featuresFromReadme[file]) {
		throw error
	}

	if (featuresFromReadme[file].description.length < 20) {
		throw error too short
	}

	if (refinedGithubTex.includes(`import "./features/${file.name}"`) {
		throw error;
	}
}
```

Ideally written in a way that it can report multiple errors, for example by replacing the `throw` with `console.error` + a variable that will mark the run as failed.

**Comment by gamemaker1** [comment]
Hi, could I take a crack at this?

**Comment by fregante** [comment]
Sure! It can be a script in the `build` folder and it can be called by the `ci.yml` workflow as its own job, via something like `node build/verify-features.js`

**Comment by gamemaker1** [comment]
How would I go about using `getFeaturesMeta` (that's in a `build/readme-parser.ts`)?

**Comment by fregante** [comment]
With ts-node, we already have it but it's not used anywhere.

```sh
nix ts-node build/verify-features.ts
```

**Comment by gamemaker1** [comment]
Ohk thanks
