### ISSUE TITLE
Timestamps instead of relative time

### ISSUE THREAD

**Issue by stephenplusplus** [sindresorhus/refined-github#47]
Just an idea, but it's more useful to me to see the actual date and time when something occurred. The home feed simplifying it to "2 hours ago" might as well say "two episodes of House ago"-- I'm an adult, I want the real time!

Maybe it can be relative up until an hour?

Am I alone on this one?

**Comment by SpaceK33z** [comment]
I don't care about the exact time, I like the '2 hours ago', because it gives me a rough estimation. The actual date and time would require me to think a lot more.

**Comment by stephenplusplus** [comment]
I think if you want super minimal, that makes sense. For me, my day is pretty connected to what happens on GitHub, so having a reference to when things occur is important. Removing it would be like not seeing when you sent or received emails. I like to connect what I was doing in real life with when something happened on GitHub life, and as I use the clock for real-life, being able to link them in the same language (time) is crucial.

**Comment by sindresorhus** [comment]
> For me, my day is pretty connected to what happens on GitHub, so having a reference to when things occur is important.

I'm trying to understand this. What exact value do you get from the time? Someone commented something 2 hours ago or 4 hours. How does it make a difference?

> Removing it would be like not seeing when you sent or received emails.

I don't think I've ever looked at the time I've received an email. That's the beauty of asynchronous communication, the time really doesn't matter.

**Comment by stephenplusplus** [comment]
You're too hippy for me, man. I still live in the world where clocks matter. No arguments required, just different philosophies :) I'll shut this down!

**Comment by sindresorhus** [comment]
⏰💥🦄✨😬

**Comment by hkdobrev** [comment]
Just my 2 ¢:

I really like what GitHub is doing with timestamps at the moment. They show relative timestamps for recent events and absolute timestamps for older events. On hover you see the absolute timestamp (from the title attribute) and they show you it's in your timezone. They do this with JavaScript as far as I know. They also update recent relative timestamps dynamically on the page (from time to time).

Using relative timestamps they show you how long ago something was at a glance without making you think whether this is in your timezone (like you need to do in many other systems) and at the same time provide you with the absolute timestamp.

From my point of view - kudos to GitHub.

**Comment by CoSyBob** [comment]
Give me the timestamp .  I find hiding that data is as brain damaged as anything MS has ever done .

**Comment by hkdobrev** [comment]
Showing absolute timestamps from `<time>` elements is something which could be implemented as a separate extension probably even website-agnostic or supporting multiple websites which do what GitHub does at once.

We're just saying we understand why GitHub does it like they do and we wouldn't change it. Anyone is free to create a project for doing that :-)

Cheers! 🍻

**Comment by groovycol** [comment]
question: WHERE exactly is the timestamp shown on hover? I've spent 20 minutes trying to track down what time of day "3 days ago" something was merged and am coming up empty. I agree with the simplicity of relative time, but if you can't dig and get actual time, you're not able to trace events

**Comment by CoSyBob** [comment]
Just making the display a simple sortable directory table would be more useful .  I think was exists is too cute at the expense of function . Something I would expect from MS .

**Comment by bfred-it** [comment]
> WHERE exactly is the timestamp shown on hover?

Everywhere, for me. This the last-modified date of each file on the repo root:

<img width="205" src="https://user-images.githubusercontent.com/1402241/42400398-adb12f80-8171-11e8-8899-35806f821ed6.png">

It should work the same way on all relative dates.

**Comment by groovycol** [comment]
thanks, @bfred-it I see it now! I think I just wasn't being patient enough earlier, as it takes a bit before it shows up, or my network is a bit slow. As long as the timestamp is findable, it's all good.

**Comment by pgorod** [comment]
Recently I started seeing GitHub Issues list with absolute timestamps (`updated 08 Nov 2018`) instead of relative (`2 hours ago`) which I definitely prefer. I checked on another browser without Refined GitHub and they're still showing relative as always...

Is Refined GitHub doing this? If so, how can I turn it off?

Thanks!

**Comment by Phrynobatrachus** [comment]
Don't believe it should be, I see relative with or without RG enabled.

**Comment by pgorod** [comment]
I am seeing other strange behaviours on Github, things like dropdowns that won't open, or AJAX parts of the page that won't finish loading. I have turned off Adblock and Flashblock for the GitHub site, so that shouldn't be interfering.

I am using an outdated Firefox (v56), I can't update for reasons not worth explaining here.

Maybe some Github update made it less compatible with my browser, I don't know. Anyway thanks for your reply.

**Comment by heyitsaamir** [comment]
Had an issue where we found failures around a certain time. It was so hard to find the PR that might have caused it amongst all the "a day ago", and "6 hours ago" etc. It would be nice to simply tell the time.

**Comment by CoSyBob** [comment]
I'm finding GitHub so _far_ more complicated than it needs to be that I'm avoiding using it .

**Comment by jerone** [comment]
There is an UserScript for this available from the wonderful Mottie: [GitHub Static Time](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-static-time).

**Comment by Darklocq** [comment]
This relative dating is a nuisance.  If you're looking at an old project and trying to figure out which bits were last worked on, it's a really hassle, because EVERYTHING says "5 years ago".  Argh.

**Comment by CoSyBob** [comment]
I've quit using it : GitHub .  
I've just got to simple open directories on my http://CoSy.com , archiving stale `.zip`s .  _**CoSy**_ , the language is far , far more powerful to simply manipulate the raw directories and files .  The entire differencing function I see as the heart of Git is just a few lines in the evolved APL level of _**CoSy**_ .  And the bright non-programmer market I consider my core target never heard of GitHub and would have zero patience for it .

**Comment by lmilton-ithaka** [comment]
I agree. Relative dating is a nuisance. I am trying to find my last successful build after the commit. It is not quick.

**Comment by fregante** [comment]
> There is an UserScript for this available from the wonderful Mottie: [GitHub Static Time](https://github.com/Mottie/GitHub-userscripts/wiki/GitHub-static-time).

For those who find it a nuisance, there's already a solution. Not everything needs to be part of Refined GitHub.
