### ISSUE TITLE
`git-checkout-pr` style is inconsistent to GitHub

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4700]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

- `git-checkout-pr` use a different style from GitHub when clicking the copy button
- The button should have larger top and right margins and float on the text like regular code blocks

### Screenshot

GitHub:
<img width="362" alt="Screen Shot 2021-08-23 at 02 19 09" src="https://user-images.githubusercontent.com/44045911/130365776-caa439b3-b59a-4bbd-aaf7-806f8acee9e1.png">

Refined GitHub:

<img width="362" alt="Screen Shot 2021-08-23 at 02 19 29" src="https://user-images.githubusercontent.com/44045911/130365780-2be04d31-2678-4c37-a8e0-58e262e5260a.png">

### Example URL

https://togithub.com/sindresorhus/refined-github/pull/4639

### Browser(s) used

Chrome

**Comment by fregante** [comment]
If possible on multiline fields, yes!

**Comment by kidonng** [comment]
It should be possible because the copy button in comment's code block uses the same newer style.

Example:

```
I'm multiline
I'm also copiable
```

**Comment by mohilkhare1708** [comment]
I would like to work on this.

**Comment by fregante** [comment]
You're welcome to
