### ISSUE TITLE
`quick-review-buttons` does not working

### ISSUE THREAD

**Issue by donghyeon-kim98** [sindresorhus/refined-github#4702]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

`quick-review-buttons` does not working

### Screenshot

![스크린샷 2021-08-23 오전 10 04 13](https://user-images.githubusercontent.com/66946238/130376810-d3813a3d-a90c-437e-877e-bdbeb4961970.png)

![스크린샷 2021-08-23 오전 10 04 06](https://user-images.githubusercontent.com/66946238/130376808-130c6008-545a-41f8-9379-ded565f6eaa1.png)

### Example URL

https://github.com/python-poetry/poetry/pull/4425/files

### Browser(s) used

chrome

**Comment by fregante** [comment]
Thank you for the report, try refreshing the page. This is tracked in https://github.com/sindresorhus/refined-github/issues/4695

**Comment by donghyeon-kim98** [comment]
ty :)
