### ISSUE TITLE
Display rich diff for pictures by default

### ISSUE THREAD

**Issue by LOuroboros** [sindresorhus/refined-github#4703]
### Description

Hi. I wanted to drop a quick suggestion.
It would be cool to have a setting to make the addon display the rich diffs for changes done to graphic files using formats as .jpg, .png, and similar when looking at a commit by default, instead of the source diff.

### Example URL

https://github.com/sindresorhus/refined-github

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/2673
