### ISSUE TITLE
Meta: `npm run fix` not working anymore (`ERROR: Task not found: "'lint:*"`)

### ISSUE THREAD

**Issue by darkred** [sindresorhus/refined-github#4704]
*Possibly related: #4386*

Using Node 16.7.0 x64 on win10.
Tested with latest PowerShell 7.1.4, cmd, CygWin, MinGW64 (Git Bash of latest Git 2.33.0 ).

Running `npm run fix` results in:

```
>npm run fix

> fix
> run-p 'lint:* -- --fix'

ERROR: Task not found: "'lint:*"
```

<details>
<summary>screenshot:</summary>

![2021-08-23_173108](https://user-images.githubusercontent.com/723651/130479277-b4f01f32-3abe-457b-89c8-a23a2d409006.jpg)
</details>

The related lines in `package.json` are:
https://github.com/sindresorhus/refined-github/blob/c68ed1de16d10967c5e9a42b60d70427e1a2e7c0/package.json#L9-L12

If I remove the singlequotes from line 9, i.e.:
```
"fix": "run-p lint:* -- --fix",
```

then the procedure completes, but the fixable issues are **not** fixed:

<details>
<summary>output:</summary>

```
>npm run fix

> fix
> run-p lint:* -- --fix


> lint:css
> stylelint "source/**/*.css"


> lint:js
> xo


(list of errors)


  x warnings
  y errors
ERROR: "lint:js" exited with 1.
```
</details>

I verified that they are not fixed by using latest XO extension in VScode the command `XO: Fix all auto-fixable problems`: that command worked ok.

Maybe something has broken with latest Node version?

### How to reproduce:

In any existing .tsx file, add for example this line:

```js
const a = "";
```

which raises this fixable XO error: `Strings must use singlequote. XO(@typescript-eslint/quotes)`.

**Comment by fregante** [comment]
That’s because single quotes don’t work on Windows as far as I know. I thought they worked on cygwin, maybe now that you know why you can Google a solution. 

For now you can run this specifically: `npx xo --fix` and the equivalent stylelint command

**Comment by fregante** [comment]
Or you can replace the single quotes with double quotes in the package json and send a PR if that works.
