### ISSUE TITLE
Possible Good First Issues

### ISSUE THREAD

**Issue by Asdf0717** [sindresorhus/refined-github#4708]
Hello, we are a group of researchers developing machine learning techniques to locate issues suitable for newcomers, and our model considers the following issues as likely "good first issues":

#4456 #4531 #4638 #4647 #4678 #4679 #4688 #4692 #4697 #4700 #4701

May we recommend you to label them as "good first issue" so newcomers know where to choose?

Thank you!

**Comment by fregante** [comment]
Thank you. I labelled these but the rest aren't easy:

https://github.com/sindresorhus/refined-github/issues/4456
https://github.com/sindresorhus/refined-github/issues/4531
https://github.com/sindresorhus/refined-github/issues/4700
