### ISSUE TITLE
Using `shift` to mark multiple files as viewed in PR stopped working

### ISSUE THREAD

**Issue by artem-karpenko** [sindresorhus/refined-github#4709]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

1. Open any PR with more than 1 file in it, "Files changed" tab.
2. Mark first file as viewed by clicking on appropriate checkbox.
3. Press shift and while holding it mark any other file as viewed.
EXPECTED: all files between the first marked file and the last one inclusive are marked as viewed.
ACTUAL: no additional files are marked as viewed, text selection is added as if you clicked non-interactive element while holding shift.

### Example URL

https://github.com/artem-karpenko/archiver-zip-encrypted/pull/21/files

### Browser(s) used

Google Chrome Version 92.0.4515.159 (Official Build) (x86_64)

**Comment by fregante** [comment]
Thanks for the report.

It works, but you need to refresh the page first due to this bug:

- #4695 


![gif](https://user-images.githubusercontent.com/1402241/130610682-f0c25f2d-7d68-4142-917e-191974534409.gif)
