### ISSUE TITLE
`edit-comments-faster` appears on other users' comments in issues

### ISSUE THREAD

**Issue by gamemaker1** [sindresorhus/refined-github#4712]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Open an issue, e.g.: https://github.com/facebook/jest/issues/6316 and scroll through the comments in the conversations tab. You will see edit buttons on all comments, including comments from other users. When you click on the edit button, you see an error message: `Sorry, something went wrong`.

### Console errors

A 403 Forbidden when the page attempts to retrieve the edit form for that comment:

```
XHR GET https://github.com/facebook/jest/issue_comments/.../edit_form?textarea_id=issuecomment-...-body&comment_context= [HTTP/2 403 Forbidden 321 ms]
```

### Example URL

https://github.com/facebook/jest/issues/6316 (locked issue)
https://github.com/facebook/jest/issues/11791 (regular issue)

### Browser(s) used

Firefox

**Comment by gamemaker1** [comment]
https://github.com/sindresorhus/refined-github/blob/b9dea1a78f79d4d8da129d3f2151892a655f0df9/source/features/edit-comments-faster.tsx#L16

I think its because of the `!pageDetect.isDiscussion()` check:

- on issue pages, that condition returns true and the `preSelector` is left blank.
- also, `canEditDiscussion()` checks if the page is a discussion already - removing the need for the `!pageDetect.isDiscussion()` check.

Removing the `!pageDetect.isDiscussion()` check might work, not sure if it has any other side effects though.

**Comment by fregante** [comment]
You're right, it's happening on every conversation, even those the current user did not start.

This is a new bug, so something must have changed either in the local selectors or in the detections: https://github.com/fregante/github-url-detection

**Comment by fregante** [comment]
> I think its because of the `!pageDetect.isDiscussion()` check:

Yeah, probably due to https://github.com/sindresorhus/refined-github/pull/4415

cc @darkred

**Comment by fregante** [comment]
Specifically the commit [`1f2610f` (#4415)](https://github.com/sindresorhus/refined-github/pull/4415/commits/1f2610f67e52db7b8b0cc7dd91c78484d957bd8d)

**Comment by fregante** [comment]
I just realized that GitHub finally started loading the "edit comment" form later. Until today(?) every editable comment _also_ loaded their own form, which was just there, hidden the whole time. This might be throwing it off (unless the bug has actually been there for 3 months and nobody noticed)

**Comment by yakov116** [comment]
I am almost positive this is a brand new thing.

**Comment by gamemaker1** [comment]
Might be new, even I noticed it just today.

Removing `!pageDetect.isDiscussion()` works, I tested it on an issue as well as a discussion. Not sure if it affects maintainers/collaborators editing comments on issues started by others though.

**Comment by yakov116** [comment]
Ok if the closest `div.TimelineItem` has `('[data-url$="variables%5BdeferredEditForm%5D=false"]')` they can edit.

**Comment by gamemaker1** [comment]
I see the `('[data-url$="variables%5BdeferredEditForm%5D=false"]')` on your comment just now too - but I should not be able to edit your comment right?

**Comment by gamemaker1** [comment]
If the `.js-discussion > div:nth-child(1)` has the `('[data-url$="variablesdeferredCommentActions%5D=true"]')`, it points to the current user being the author of the issue

**Comment by gamemaker1** [comment]
I'm a bit stuck - can't find a way (through DOM) to identify the user as 'edit all comments' or 'edit only own comments'. I had another idea though - can we go through each comment and check if that comment has a `Edit` button in the dropdown? That way Github can do the work of checking whether the user has edit access and we can simply put the edit button on the comment header if required.

Let me know if you have found a better way to do this.

Thanks

**Comment by gamemaker1** [comment]
That does not work - Github loads all the buttons in the dropdown after we click on the dropdown button (except the `view repo at this time`).

**Comment by fregante** [comment]
There's a variety of signals we can use to determine whether the current user can edit every comment, it's just a matter of finding them in each supported page.

Example:

- Can I edit the issue/PR sidebar?
- Can I edit the title even if I'm not the author?
- Is there a settings tab? (only for the owner)
- Is there a "you are a collaborator" anywhere on the page?

Also I see an element that's missing from the Jest conversation:
<img width="341" alt="Screen Shot 6" src="https://user-images.githubusercontent.com/1402241/131318135-7fbc4c0a-de8e-49d5-af5b-ad33b6e98a42.png">

but is available in this repo:

<img width="344" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/131318140-6fab9f60-a569-45b6-89c8-0bc332d395f6.png">

`js-previewable-comment-form previewable-comment-form write-selected`

**Comment by gamemaker1** [comment]
Thanks for the detailed reply, it really helped. I followed your suggestions and came up with the following solution:

```diff
diff --git a/source/features/edit-comments-faster.tsx b/source/features/edit-comments-faster.tsx
--- a/source/features/edit-comments-faster.tsx
+++ b/source/features/edit-comments-faster.tsx
@@ -7,13 +7,13 @@ import * as pageDetect from 'github-url-detection';
 
 import features from '.';
 
-function canEditDiscussion(): boolean {
-       return pageDetect.isDiscussion() && select.exists('[title^="You are a maintainer"], [title^="You are a collaborator"]');
+function canEditComments(): boolean {
+       return select.exists('[aria-label^="You are the owner"], [title^="You are a maintainer"], [title^="You are a collaborator"]');
 }
 
 function init(): void {
        // If true then the resulting selector will match all comments, otherwise it will only match those made by you
-       const preSelector = !pageDetect.isDiscussion() || canEditDiscussion() ? '' : '.current-user';
+       const preSelector = canEditComments() ? '' : '.current-user';
        // Find editable comments first, then traverse to the correct position
        observe(preSelector + '.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
                add(comment) {
```

Using `aria-label^="You are the owner"` shows the edit button on repos where you are the owner. Not sure whether the collaborator/maintainer check works - I'm not a collaborator on any repository. Otherwise it works properly on the test URL and this issue - I'm not able to edit any comments from other users.

Opening a PR so we can work on bettering the proposed solution.

**Comment by fregante** [comment]
Did you try `js-previewable-comment-form previewable-comment-form write-selected` first? If that's available in every editable comment you can just query that and avoid any global "current user"/"canEditComments" check

**Comment by gamemaker1** [comment]
Ok, will do that instead
