### ISSUE TITLE
Shorten links to files in comments (WIP)

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#472]
Look at these beautiful autolinking:

* https://github.com/sindresorhus/refined-github/commit/784a028af8c04da116e0bd5c0c07569eeef52486  
  it was `https://github.com/sindresorhus/refined-github/commit/784a028af8c04da116e0bd5c0c07569eeef52486`
* https://github.com/rollup/rollup/issues/1435  
  it was `https://github.com/rollup/rollup/issues/1435`

But file links don't get the same treatment:

* https://github.com/sindresorhus/refined-github/blob/master/icon.ai
* https://github.com/sindresorhus/refined-github/blob/784a028af8c04da116e0bd5c0c07569eeef52486/src/content.js
* https://github.com/rollup/rollup/blob/master/.eslintrc
* https://github.com/rollup/rollup/blob/rollup-init/.eslintrc
* https://github.com/sindresorhus/refined-github/blame/patch-diff-shortcuts/.editorconfig
* https://raw.githubusercontent.com/sindresorhus/refined-github/patch-diff-shortcuts/readme.md

They should be shortened to:

* [`master`/icon.ai](https://github.com/sindresorhus/refined-github/blob/master/icon.ai)
* [`784a028`/src/content.js](https://github.com/sindresorhus/refined-github/blob/784a028af8c04da116e0bd5c0c07569eeef52486/src/content.js)
* [rollup/rollup/`master`/.eslintrc](https://github.com/rollup/rollup/blob/master/.eslintrc)
* [rollup/rollup/`rollup-init`/.eslintrc](https://github.com/rollup/rollup/blob/rollup-init/.eslintrc)
* [blame/`patch-diff-shortcuts`/.editorconfig](https://github.com/sindresorhus/refined-github/blame/patch-diff-shortcuts/.editorconfig)
* [`patch-diff-shortcuts`/`readme.md`](https://raw.githubusercontent.com/sindresorhus/refined-github/patch-diff-shortcuts/readme.md) <-- link to `raw`

They might look a bit cryptic at first but perhaps they're better than multi-line full URLs. At the very least we can drop `https` (but not `http`), drop `github.com`, shorten commit hashes, and `highlight` branches and commits

**Comment by sindresorhus** [comment]
👍

**Comment by bfred-it** [comment]
Reopening to change the filename separator to `:`


[user/repo:filename@`master`](#nope) <-- changes to `:`
[/filename@`master`](#nope) <-- stays the same
