### ISSUE TITLE
Provide a link on "No commits found" page to remove the filters

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4721]
### Description

On the "Contribution activity" section of a user profile page, you can click the "* commits" link to view the commits during the corresponding month/day, using a time filter like `?since=2099-01-01&until=2099-01-02`. However it seems this date is not timezone-aware and sometimes the link will lead to a blank page (`No commits found for "octocat"`).

I propose we put a link pointing to the same page but without the time filter when we encounter such a blank page. (Another form of `useful-not-found-page`?)

Alternative implementation: put a link pointing to the same page without **any filter**, but preserve the `author=octocat` part if we come from a profile page.

### Screenshot

https://user-images.githubusercontent.com/44045911/130961359-195d8661-0e27-489e-9d6a-960e5cb456bd.mov

### Example URL

https://github.com/sindresorhus/refined-github/commits?author=fregante&since=2099-01-01&until=2099-01-02

**Comment by fregante** [comment]
Wow what a lame GitHub bug. Could you report it to GitHub? It's annoying but honestly not too useful since it comes from a user's ~~stalking~~ *history* page

**Comment by kidonng** [comment]
@fregante I think this feature will also help with wrong author besides wrong date, e.g. if someone put a link to `?author=foo` but the user `foo` has deleted their account, their commits will be authored by @ghost.

**Comment by fregante** [comment]
> if someone put a link to `?author=foo` but the user `foo` has deleted their account, their commits will be authored by @ghost.

In that case what are we supposed to do? If the user doesn't have an ID anymore, we can't find their commits either (without confusing them with other ghosts’)

**Comment by kidonng** [comment]
This issue is just asking for a convenient button/link to clear the filters. It's just like `useful-not-found-page` where we make the requested page "less specific".
