### ISSUE TITLE
Rename fast/faster features to "quick"

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4733]
Related:

- https://github.com/sindresorhus/refined-github/issues/4510#issuecomment-867505272
- https://github.com/sindresorhus/refined-github/issues/4509

Example: `edit-comment-faster` -> `quick-comment-edit`

I'm not sure if it works everywhere, rewording is also welcome (short feature names are still preferable though)

**Comment by himanshu007-creator** [comment]
hi, i would like to work on this issue

**Comment by Shreshtha13** [comment]
Hi @fregante ! I am new to open source and would like to work on this issue.

**Comment by himanshu007-creator** [comment]
okay @Shreshtha13 , its your, I'm out👍🏼

**Comment by Shreshtha13** [comment]
Thanks @himanshu007-creator :)
