### ISSUE TITLE
"This page is out of date" message shows in the wrong place when scrolled to the top

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#474]
<img width="600" alt="screen shot 2017-06-06 at 21 09 19" src="https://cloud.githubusercontent.com/assets/170270/26833397/82b5ede0-4afc-11e7-8500-4f9d1020ca0d.png">

It shouldn't be above other information. I'm not sure how it looks natively, but that's how it should look.

To reproduce: Open a PR, stay on the the diff view, and then push another commit or force push.

**Comment by hkdobrev** [comment]
@sindresorhus Are you reproducing this in every case? I'm seeing this quite a few times in my day because we're using rebasing and force-pushing a lot. It was never misaligned like that, though. So I think there could be something else to it.

**Comment by sindresorhus** [comment]
@hkdobrev Yes. @vadimdemedes Is seeing this all the time too. It only shows when you're scrolled to the top of the page. Otherwise it's fine.

**Comment by bfred-it** [comment]
This is due to #425. Possible solution:

<img width="502" alt="drop a few words" src="https://user-images.githubusercontent.com/1402241/27883051-c24344fa-6201-11e7-831d-1934b96f25de.png">

If you come up with a way to detect it the element when it appears, I'm all ears.

**Comment by bfred-it** [comment]
It also happens for this other message:

<img width="308" alt="Subset of changes" src="https://user-images.githubusercontent.com/1402241/27897901-a21a3266-6255-11e7-9241-47c3f4a32ddb.png">
