### ISSUE TITLE
Rename "PR" references to "Pull Request"

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4741]
### Description

While "PR" is easy to type and grasp for most people, it doesn't make much sense for casual users or newcomers to GitHub. I really like Refined GitHub works just like a native part of GitHub (and that's what makes it great), so I feel like "PR" is out of place and doesn't align with GitHub.

I propose to rename all **visible** "PR" references to "Pull Request" (case and plural may change). In README/internal code/comments we can probably keep using it.

### Screenshot

![image](https://user-images.githubusercontent.com/44045911/131237496-cb055bbe-6424-44d9-a2d1-3e78554f2d58.png)

### Example URL

N/A

**Comment by fregante** [comment]
Hmmmmmmmm it might be ok if there's space for it, for clarity and consistency, otherwise PR is understandable enough, fast to read, and takes 1/6 of the space.

**Comment by shinenelson** [comment]
One feature that can be updated is `comment-on-draft-pr-indicator`

### Screenshot

![image](https://user-images.githubusercontent.com/4771718/131340459-50771400-4d41-44af-b74e-924fe74f4f23.png)

---

I think this can be a https://github.com/sindresorhus/refined-github/labels/good%20first%20issue for newer contributors.

If we want to fix this sooner, please assign me to it and I will do it.

**Comment by fregante** [comment]
That's the problem, that button is already pretty long. If we add 2 words to it will be long enough to almost stop looking like a button.

**Comment by shinenelson** [comment]
I think it looks okay, but I am not a UX expert, so I would not know for sure.

![image](https://user-images.githubusercontent.com/4771718/131875431-3a1712b6-970c-4080-81c4-ceea5a11a8c9.png)

I feel that the 'PR' looks out of place especially when there is another button on the left that reads 'pull request'

**Comment by fregante** [comment]
> ### Screenshot
> ![image](https://user-images.githubusercontent.com/44045911/131237496-cb055bbe-6424-44d9-a2d1-3e78554f2d58.png)

The vast majority of those references are in comments

<img width="428" alt="Screen Shot" src="https://user-images.githubusercontent.com/1402241/132039589-69a20efb-c1a0-4ce6-9f2f-b941e6109228.png">

Feel free to open a PR with the few ones that are shown to the user, with screenshots of where they appear. I'll close this in the meanwhile.

I think `Comment on draft pull request` is too long since we'd be making the button 4 times longer.
