### ISSUE TITLE
modify `navigate-pages-with-arrow-keys` to match GitHub's `n` / `p` keys

### ISSUE THREAD

**Issue by shinenelson** [sindresorhus/refined-github#4742]
### Description

from https://github.com/sindresorhus/refined-github/pull/4691#issuecomment-907578663

> I think n/p has existed for a while actually. It might make more sense to change our feature to match n/p in order to extend it to more pages. Arrows feel wrong accessibility-wise.

While I agree with the change, I did a quick test to check whether the change was feasible. `p` is used as a hotkey for the **Project** filter on issues and pull request lists. I feel that the hotkey is most used on the issues and pull request lists.

Here are 2 options that I could think of ( both after modifying the feature to match GitHub's choice of `n` / `p` across all other supported pages ) : 
1. Maintain the arrow keys functionality for issues and pull request lists.
2. Drop the feature for issues and pull request lists

Either way, there is going to be a feature rename and migration that would be required.

### Example URLs

- Issue list : https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
- Pull request list : https://github.com/sindresorhus/refined-github/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed
- Search page : https://github.com/sindresorhus/refined-github/search?q=navigat
- Commits Page :
  - https://github.com/sindresorhus/refined-github/commits/main/source/features/navigate-pages-with-arrow-keys.tsx
  - https://github.com/sindresorhus/refined-github/commits/main
- Releases Page : https://github.com/sindresorhus/refined-github/releases
- Notifications Page : https://github.com/notifications
- Pull Request Commits : 
  - [`d9621aa` (#4699)](https://github.com/sindresorhus/refined-github/pull/4699/commits/d9621aaf54aae286b45b8805d34d9354224412ca)
  - [`dc04365` (#4699)](https://github.com/sindresorhus/refined-github/pull/4699/commits/dc0436589007560a77db22290427d7b7898657ee)

**Comment by kidonng** [comment]
Arrow key fans here (😄), can't we just support both?

**Comment by shinenelson** [comment]
> can't we just support both?

I thought about that too after I made https://github.com/sindresorhus/refined-github/pull/4691#issuecomment-907690478; but then I realized that it would not make sense ( and probably not work ) with 2 `data-hotkey` attributes for the same element.

**Comment by shinenelson** [comment]
@fregante, @yakov116 which among the 2 suggested options do you prefer to be implemented? Or do you have better suggestions?

**Comment by shinenelson** [comment]
oh, and I also forgot about another observation that I made [yesterday](https://github.com/sindresorhus/refined-github/pull/4691#issuecomment-907690478) : 

it does not work
> when `follow-file-renames` was in effect ( because it is loaded after `navigate-pages-with-arrow-keys` ); perhaps we should add an ordering rule for the 2 features.

**Comment by fregante** [comment]
Definitely not both, we should pick one. Since GitHub uses n/p it would make sense to match them, but I don't feel strongly to make the change yet, unless there are already other pages using n/p on GitHub.

**Comment by fregante** [comment]
This request was addressed in the open PR, which now only renames the feature instead.
