### ISSUE TITLE
 Uses a monospace font for all textareas.

### ISSUE THREAD

**Issue by foolioo** [sindresorhus/refined-github#4746]
### Description

Would love to benefit from the same feature on the textareas in support.github.com

https://github.com/sindresorhus/refined-github/blob/d8cadc830723728ab5c32f36cea31ea3f6aee814/readme.md#L212

### Example URL

https://support.github.com/contact

**Comment by fregante** [comment]
Ideally that's the case, unfortunately adding `support.github.com` will [disable the extension for everyone](https://timleland.com/adding-new-permissions-to-chrome-extension/) until they accept it and this change isn't worth the hassle.

**Comment by fregante** [comment]
I think it's best to use a regular stylesheet/userstyle for that page
