### ISSUE TITLE
Conversation filtering: make default & load more comments?

### ISSUE THREAD

**Issue by xmo-odoo** [sindresorhus/refined-github#4750]
### Description

refined has a "comments only" filter for conversations, which is extremely useful when PRs are noisy due to automated events, however it has to be enabled on every page open, and does not survive refresh.

Would be nice if it were possible to set it as the default behaviour.

Also, since the "items" in general are what affects github's pagination / hiding it would be nice if refined could also handle that a bit better e.g. have a button to "load more" (by batches of 200) higher in the thread so it doesn't have to be hunted down, maybe with a more visible indication that the thread has been cut off.

### Example URL

https://github.com/rust-lang/rust/pull/87073

**Comment by fregante** [comment]
This was the initial plan for such a feature but I think it's subjective; The "comment only" setting can hide a lot of useful events. 

If we don't have it already, we should add a keyboard shortcut to cycle through the options so at least you can quickly press the key when there's too much noise on the page.

**Comment by xmo-odoo** [comment]
> This was the initial plan for such a feature but I think it's subjective; The "comment only" setting can hide a lot of useful events.

Yes I don't think it should *be* the default when the extension is installed, but I think it could be *configured* as such, by users in situations / workflow where the non-comment events are almost entirely noise.

**Comment by fregante** [comment]
https://github.com/sindresorhus/refined-github/issues/2960#issuecomment-606765658

**Comment by fregante** [comment]
We can't change this, but feel free to open an issue or send a PR to add the shortcut.
