### ISSUE TITLE
Gist profile tab count lacks margin

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4751]
There's little space on the left side of the Gist count

<img width="280" alt="Screen Shot 5" src="https://user-images.githubusercontent.com/1402241/131729557-35102da5-ffa4-4e20-a029-67f4514c6594.png">

The same issue might apply to other tabs we add, we should also check them (if we have any)

### Example URL

https://github.com/xt0rted

### Browser(s) used

Safari

**Comment by kidonng** [comment]
Actually it's not margin but spaces:

<img width="470" alt="Screen Shot 2021-09-03 at 22 53 02" src="https://user-images.githubusercontent.com/44045911/132025534-e4fed0e8-68c2-4591-b3da-f4d9012fca83.png">

**Comment by kidonng** [comment]
I hit #4472 when working on this, can we remove `awaitDomReady` for `profile-gists-link` too?
