### ISSUE TITLE
`select-notifications` disappears after clicking Done

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#4752]
https://user-images.githubusercontent.com/1402241/131730615-64308775-edb1-4f75-836c-93c91faf08d4.mov

cc @cheap-glitch as you might know why

## URL

https://github.com/notifications

## Browser

Safari

**Comment by fregante** [comment]
Every time the list updates, it has to do with ajax loading because you can see it's delayed by a few seconds. Try again if the list is spread across multiple pages and GitHub will definitely attempt to load more items if you mark some as Done.

**Comment by Nirajn2311** [comment]
I could reproduce this now, by checking the network tab it seems like github implicitly refreshes the page and so the `Select By` button disappears.

**Comment by sambostock** [comment]
This reminds me of working with Turbolinks in Rails. I assume some event fires when the page "refreshes" which we would need to listen for and re-trigger injecting the "Select by..." dropdown insertion?

**Comment by fregante** [comment]
> This reminds me of working with Turbolinks in Rails

That's basically it, I think GitHub uses a custom version of jQuery-pjax.



> we could register a `change` event handler

If GitHub doesn't already [fire an event](https://github.com/sindresorhus/refined-github/blob/main/contributing.md#reverse-engineering-github), we can use onNodeRemoved or just selector-observer.
