### ISSUE TITLE
Load all button

### ISSUE THREAD

**Issue by eranelbaz** [sindresorhus/refined-github#4754]
### Description

Add Load all buttons, will be very useful for noisy PRs which have a lot of events on them,
currently i'm using this snippet in my console in order to press on all the `load more` buttons
```
$$('.merge-status-item').forEach(item => {
    let icon = item.querySelector('.color-text-success');
    if(icon) item.remove();
});

$$('.merge-status-item').forEach(item => {
    let icon = item.querySelector('.neutral-check');
    if(icon) item.remove();
});
```
hope you guys can put it into a button

this will be visible only on pr pages

### Screenshot

![image](https://user-images.githubusercontent.com/29000470/131851881-61d9c063-1b65-4da9-8d68-671c7a854030.png)

![image](https://user-images.githubusercontent.com/29000470/131870691-1b883025-a597-47dd-b8a6-13bcbc35e1c5.png)

### Example URL

https://github.com/sindresorhus/refined-github/pull/*

**Comment by fregante** [comment]
You can already alt-click that "Load more" button to load more pages at once, I think up to 3 at a time

**Comment by kjkrum** [comment]
@fregante This is terrible UX. The "Load more" button is somewhere down in the middle of a long page, so it's not apparent that there's even anything to click.

This is a case of trying to be modern and clever when the classic solution was better in every way. Collapsing content and infinite scrolling are hideous UX. Pagination would solve the problem of large page loads, and a URL obtained from a search or loaded from bookmarks would lead to the page where the search result appears, and browser find-in-page would work as expected.
