### ISSUE TITLE
The extensión does not allow me to upload files from the clipboard

### ISSUE THREAD

**Issue by khru** [sindresorhus/refined-github#4755]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

With the extension enabled I'm not able to upload pictures from the clipboard this started about 2 weeks ago.

### Screenshot

![Peek 03-09-2021 10-59](https://user-images.githubusercontent.com/6353105/131980180-d86c2164-9d78-45ea-b366-4ba0cf4191f5.gif)

### Example URL

https://github.com/nailted/nailted-api/pull/1013

### Browser(s) used

chrome

**Comment by busches** [comment]
The message your video shows is hidden, correct, the functionality is not off.
