### ISSUE TITLE
Newsfeed buttons are not aligned when  `hide-noisy-newsfeed-events`  is disabled

### ISSUE THREAD

**Issue by eungyeole** [sindresorhus/refined-github#4760]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

![image](https://user-images.githubusercontent.com/66717787/132169349-cb4456f8-1ece-414f-b480-73aeb22c11c0.png)

The issue appears to occur if you have the '.rgh-clean-dashboard.js-news-feed-event-group' css property on the main page of github.

![image](https://user-images.githubusercontent.com/66717787/132169182-2aa38e00-3416-49e7-91e5-701cb56d40bd.png)

The !important will be added to the padding-right of the '.rgh-clean-dashboard .dashboard .body > .border-bottom' css property.
Or 
delete !important from .rgh-clean-dashboard.js-news-feed-event-group.

### Example URL

https://github.com

### Browser(s) used

Chrome

**Comment by eungyeole** [comment]
This is not just an unfollow button. @fregante

**Comment by fregante** [comment]
I think this has been fixed by https://github.com/sindresorhus/refined-github/pull/4764

Leave a comment here if it hasn't

**Comment by eungyeole** [comment]
![image](https://user-images.githubusercontent.com/66717787/132627189-aa734df0-54e6-4033-b433-5cd405134ddf.png)
Although fixed, the button still seems to be out of position when 'hide-noisy-newsfeed-events' is turned off
