### ISSUE TITLE
Don't see Pushed branches or created branches in feed

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#477]
Is this on purpose?

**Comment by sindresorhus** [comment]
Yes

**Comment by yakov116** [comment]
Any way I can enable it?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/refined-github#customization

**Comment by yakov116** [comment]
Glad I found a bug :)

I think you should put this in the list of highlights no? (that you take this out)
