### ISSUE TITLE
`show-associated-branch-prs-on-fork` style inconsistent to GitHub

### ISSUE THREAD

**Issue by kidonng** [sindresorhus/refined-github#4771]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

GitHub shows link to PR in blue ([example](https://github.com/fregante/github-sandbox/branches)):

![image](https://user-images.githubusercontent.com/44045911/132676793-9044c0d3-9e58-4bb8-9d00-aba964145bb9.png)

While `show-associated-branch-prs-on-fork` shows in grey:

![image](https://user-images.githubusercontent.com/44045911/132676940-e943c94d-824f-4098-8f72-e6890675ee22.png)

The badge size and icon are also different.

~~I'm not entirely sure if this is a real bug as I'm on my phone and the latter screenshot is from README but there is [`muted-link Link--muted`](https://github.com/sindresorhus/refined-github/blob/7eff29fc90e51f81c95c1d6a6f13c406679250b2/source/features/show-associated-branch-prs-on-fork.tsx#L88) class for the link so I assume it's true.~~ Confirmed

### Example URL

(Link to fork where you have PR)

### Browser(s) used

Chrome

**Comment by fregante** [comment]
I confirm the bug, I see it on

https://github.com/fregante/yaml-jest/branches
