### ISSUE TITLE
Locally-built Safari Extension doesn’t work

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#4780]
After building the Safari extension locally, the below error appears in Safari Preferences

### Screenshot

<img width="904" alt="Screenshot_2021-09-12 14 36 40" src="https://user-images.githubusercontent.com/25517624/132998979-653d77db-061b-4d9d-8025-73319fcd6121.png">

### Browser(s) used

Safari Technology Preview Release 131 (Safari 15.0, WebKit 16612.2.2)

**Comment by fregante** [comment]
I'm using the extension daily so it does work. This issue is probably related to the local build or this issue maybe just be a duplicate of: https://github.com/sindresorhus/refined-github/issues/4500

Do you have a case-sensitive file system?

**Comment by fregante** [comment]
It works for me on the same version: `Release 131 (Safari 15.0, WebKit 16612.2.2)`

<img width="980" alt="Screen Shot 7" src="https://user-images.githubusercontent.com/1402241/133111944-c0193399-eeeb-4103-930e-fe01106ecbf6.png">

I've seen that "Failed to load images in `icons` manifest entry" before though, maybe you just need a clean build. cc @sindresorhus just in case anything looks familiar

**Comment by j-f1** [comment]
A clean rebuild fixed the issue, thanks! (I'm not on a case sensitive FS as far as I can tell — my drive is APFS (Encrypted))
