### ISSUE TITLE
Look into using `createcommitonbranch` for `restore-file`

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#4781]
https://github.blog/changelog/2021-09-13-a-simpler-api-for-authoring-commits/
https://docs.github.com/en/graphql/reference/mutations#createcommitonbranch

**Comment by fregante** [comment]
I assume you're referring to replacing this bit, in which case, yes plz

https://github.com/sindresorhus/refined-github/blob/32abfaaa4696053fa956f12b0186339e80f19292/source/features/restore-file.tsx#L68-L76

**Comment by fregante** [comment]
Hopefully they add a restore API at some point too so we can support restoring large files. 

Speaking of which, if we know a size limit, we can probably just detect this limit before sending the API request. 

E.G. on click immediately show the "file too big" error
