### ISSUE TITLE
How can I turn off `fix-first-tab-length`?

### ISSUE THREAD

**Issue by xnuk** [sindresorhus/refined-github#4784]
![image](https://user-images.githubusercontent.com/3071003/133352344-d2703e14-5893-4cbf-99d8-1066e8cc5288.png)
https://github.com/sindresorhus/refined-github/blob/main/source/features/fix-first-tab-length.css

Looks like it can't be turned off

**Comment by kidonng** [comment]
https://github.com/sindresorhus/refined-github/issues/4289#issuecomment-828213252

**Comment by fregante** [comment]
What for? Why do you want to disable a GitHub bugfix?
