### ISSUE TITLE
Option to actually remove hidden files from PR files tab

### ISSUE THREAD

**Issue by osdiab** [sindresorhus/refined-github#4786]
### Description

When you hide files in github, it collapses them to a thin line. Normally this is good enough, but with some tools like Yarn Berry's Zero-Installs function, you can end up with an overwhelmingly large number of collapsed files, so that it's basically impossible to do a code review. I'd like the option to just completely make them go away.

### Screenshot

<img width="1209" alt="Screen Shot 2021-09-15 at 16 20 16" src="https://user-images.githubusercontent.com/1890926/133525568-4ff8328c-c5ce-4821-95fa-02019baa8544.png">

### Example URL

https://github.com/spinachhr/web-app/pull/213/files?file-filters%5B%5D=dotfile

**Comment by fregante** [comment]
This is sort of another variation of https://github.com/sindresorhus/refined-github/pull/1085 or one of the issues that were linked to it. 

But actually I'm surprised that the file filter does not hide the files, 🤔 I just don't know whether we can detect whether a file is toggled by the user or hidden by the filter.

**Comment by kidonng** [comment]
Maybe hide folded files with "BIN" label, like the ones on the screenshot?

**Comment by fregante** [comment]
That's an arbitrary change. Binaries are still part of the diff

**Comment by osdiab** [comment]
yeah, my problem isn't having binaries in the diff - my problem is that the default layout takes up too much space + the sheer number of dom nodes in this kind of scenario causes my computer to lag up. I can probably just make a user script that does this in my browser, but since anyone using Yarn with Zero-Installs on Github would probably run into this issue it seems like something that would be broadly useful.

**Comment by kidonng** [comment]
Actually for I have think the native filter is enough for Yarn's case, just deselect `.zip`.

**Comment by kidonng** [comment]
The example URL is a private repository, may as well use something else like: https://github.com/avevlad/ts-data-analysis-with-zero-install/commit/0d541184f2bcc20e4a419fc591ae44c7111e27c3

**Comment by osdiab** [comment]
yep that's it - it can just be arbitrarily large depending on what you've installed - in teh case in my screenshot it was a crazy number of zips lol

**Comment by osdiab** [comment]
BTW not sure but this might be somewhat complex to do since large diffs do cause files to be lazy loaded, not sure what github's behavior is in those cases

**Comment by fregante** [comment]
We can probably do this, if it really doesn't happen already: completely hide files if filtered. 

The issue is probably that we have to manually apply the filters (i.e. `select` all "zip" filers, for example) because I assume GitHub does not expose "this file was toggled because of a filter" in the DOM; for us every filtered file is likely indistinguishable from a file that the user just toggled by clicking its toggle. 

This might not be an easy feature and thus probably not worth it.

**Comment by FloEdelmann** [comment]
Seems like GitHub listened to you :wink: 
https://github.blog/changelog/2021-09-27-improved-pull-request-file-filtering/

**Comment by fregante** [comment]
Excellent!
