### ISSUE TITLE
`quick-file-edit` conflicts with file icon extension (browser’s back button)

### ISSUE THREAD

**Issue by BlueskyFR** [sindresorhus/refined-github#4788]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Didn't know what to write in the title so please feel free to edit it :sweat_smile: 

Using the Vivaldi browser, and refined Github, when going on a Github repo, then another page of the repo, then going back through the history, the icons on the left duplicate themselves.
Please see the screenshots below.

### Screenshot

Initial page:
![image](https://user-images.githubusercontent.com/25421460/133651214-aca4a6fa-9ba6-4ecb-b7ae-8e49d2cdab65.png)

Then change branch:
![image](https://user-images.githubusercontent.com/25421460/133651162-4085b435-ef21-42be-b087-2450a30fe377.png)

Then go back to the previous page (usually alt + left key on most browsers):
![image](https://user-images.githubusercontent.com/25421460/133651331-51890b2e-aaab-4f34-82c2-6051a0f6003e.png)

We can clearly see the problem:
![image](https://user-images.githubusercontent.com/25421460/133651464-08ececcc-5a3a-4873-8ef4-8168c6a97b2c.png)

### Example URL

https://github.com/sindresorhus/refined-github

### Browser(s) used

Vivaldi, cannot reproduce on Chromium

**Comment by fregante** [comment]
What icons extension are you using? That's not just Refined GitHub

**Comment by kidonng** [comment]
> What icons extension are you using?

That looks like https://github.com/homerchen19/github-file-icons. There is an issue regarding this: homerchen19/github-file-icons#85 but it seems to have been fixed last year.

@BlueskyFR You can also try the one I'm using: https://github.com/Claudiohbsantos/github-material-icons-extension, it doesn't have issue with Refined GitHub.

> It's also possible that the extension is adding the second icon because Refined GitHub is wrapping the previous icon in a `<a>`

Welp, I _should have_ fixed that for every icon extension I find:

- homerchen19/github-file-icons#82
- dderevjanik/github-vscode-icons#27
- lvarayut/github-file-icons#17
- mallowigi/a-file-icon-idea#96

**Comment by fregante** [comment]
Thanks for the work Kidong! We have had issues with them and usually I ask people to change to one that works.
