### ISSUE TITLE
GitHub Discussions Should Hide Older Comments Instead of New Ones

### ISSUE THREAD

**Issue by Blackjacx** [sindresorhus/refined-github#4789]
### Description

At the moemnt GH discussions hides NEWER comments which is weird, since I usually want to read them and usually I have already read the older ones.

Therefore it would be nice if this is reversed. It could be similar to other options where you let the user define the order of certain elements like PRs, issues, etc.

### Screenshot

![Screen Shot 2021-09-16 at 19 51 01](https://user-images.githubusercontent.com/794372/133660758-3a566786-6a2b-47a0-9c15-c6c7ba709a80.png)

### Example URL

https://github.com/Blackjacx/Assist/discussions/23

**Comment by fregante** [comment]
I think it's best to ask GitHub. Doing this in the extension means loading every thread and then reversing it after, which will cause plenty of network requests and also be visible to the user (the content will shift in front of your eyes)
