### ISSUE TITLE
`useful-not-found-page` shows 'This object exists on the default branch' when viewing a deleted issue

### ISSUE THREAD

**Issue by gamemaker1** [sindresorhus/refined-github#4790]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Problem breakdown:

- The `getUrlToFileOnDefaultBranch` ([called by `showDefaultBranchLink`](https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L101)) function checks if the URL is a non-404 when the 'branch' part is replaced with the default branch:

https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L60-L64

- In this case, the 'branch' part is in fact the issue number. So it changes https://github.com/octokit/rest.js/issues/558 => https://github.com/octokit/rest.js/issues/master.
- When we visit an issue page with the issue number set to a string, (e.g.: `https://github.com/octokit/rest.js/issues/master`), Github searches for issues with the string as the `author`.
- This means that the `getUrlToFileOnDefaultBranch` function does not receive a 404, and it returns https://github.com/octokit/rest.js/issues/master as a valid issue link.
- The same does not occur on discussions as it does not support this type of query.

To prevent this bug from occurring, I think we should fix the `GithubURL` class, and make sure it does not set the `branch` variable when it gets an issue link as follows:

```diff
diff --git a/source/github-helpers/github-url.ts b/source/github-helpers/github-url.ts
index e8acd411..ec4e8c53 100644
--- a/source/github-helpers/github-url.ts
+++ b/source/github-helpers/github-url.ts
@@ -77,8 +77,12 @@ export default class GitHubURL {
 
   set pathname(pathname: string) {
     const [user, repository, route, ...ambiguousReference] = pathname.replace(/^\/|\/$/g, '').split('/');
-    const {branch, filePath} = this.disambiguateReference(ambiguousReference);
-    this.assign({user, repository, route, branch, filePath});
+    if (route === 'blob' || route === 'tree') {
+      let { branch, filePath } = this.disambiguateReference(ambiguousReference);
+      this.assign({ user, repository, route, branch, filePath });
+    } else {
+      this.assign({ user, repository, route, branch: undefined, filePath: undefined });
+    }
   }
 
   get href(): string {
```

This will trigger the condition on https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L62 and the function will return, thus not showing the incorrect link.

Let me know if this sounds like an acceptable solution. If so, I'll be happy to send in a PR.

Thanks!

### Screenshot

![image](https://user-images.githubusercontent.com/34235681/133761286-bb0f48f8-82c5-4915-99f7-06adc914d763.png)

Clicking on [`This object`](https://github.com/octokit/rest.js/issues/master) takes you to https://github.com/octokit/rest.js/issues/master.

### Console errors

```shell
None
```

### Example URL

https://github.com/octokit/rest.js/issues/558

### Browser(s) used

Firefox

**Comment by fregante** [comment]
The easy solution here is to use `isSingleFile || isTree` (I don't remember the name) to only run those functions on blob/tree URLs, no need for custom code.

**Comment by gamemaker1** [comment]
> - showDefaultBranchLink, showAlternateLink: `isSingleFile || isTree`
> - showMissingPart: current detection is fine

Hmm I remember this being in the original code... My PR seems to have messed quite a bit of stuff up 😬

Will split this up and submit a PR though, thanks.

**Comment by gamemaker1** [comment]
It did exist - commit 6047ca569d61638025a26f29a31ab9069b0dd108, line 111 of `source/features/useful-not-found-page.tsx`
