### ISSUE TITLE
Display Branch Commit Stats

### ISSUE THREAD

**Issue by achillesrasquinha** [sindresorhus/refined-github#4791]
### Description

Maybe show image stats like GitLab does?

### Screenshot

<img width="774" alt="Screen Shot 2021-09-17 at 11 20 37 AM" src="https://user-images.githubusercontent.com/9742568/133821362-7004fb73-2e0a-49e1-b92d-abd4fe849dcc.png">

Show Image stats like this.

### Example URL

https://github.com/achillesrasquinha/pipupgrade

**Comment by kidonng** [comment]
What image stats? Did you mean those numbers on the right? Doesn't GitHub already provide them?

<img width="895" alt="Screen Shot 2021-09-18 at 00 27 01 1" src="https://user-images.githubusercontent.com/44045911/133822270-032deaf8-54bf-446f-9e11-0b86198b8855.png">

**Comment by fregante** [comment]
I think he refers to the commit information after each branch. 

It's interesting, but I think it adds a lot of noise, making the branch list twice as long. 

Also the list is filterable/dynamic, so the user will see the list become compact and then expand multiple times as they filter it. Not good UX and not worth the trouble in Refined GitHub
