### ISSUE TITLE
Add `show-open-prs-of-forks-on-repo-list`

### ISSUE THREAD

**Issue by Yash-Singh1** [sindresorhus/refined-github#4795]
### Description

A new feature based on `show-open-prs-of-forks` on Repository lists. I can submit a PR for this.

### Screenshot

![Screenshot from 2021-09-18 17-27-11](https://user-images.githubusercontent.com/53054099/133911759-a4f94819-bd31-4ea5-a371-ec83bd32778e.png)

### Example URL

https://github.com/Yash-Singh1?tab=repositories&q=&type=fork&language=&sort=

**Comment by fregante** [comment]
Refer to https://github.com/sindresorhus/refined-github/issues/1130#issuecomment-529137735
