### ISSUE TITLE
[Idea] Add remove fork button to pull requests

### ISSUE THREAD

**Issue by vinkla** [sindresorhus/refined-github#48]
Once a pull request has been merged I get the option to delete the branch from my fork. It would also be nice if I'd the possibility to delete the entire fork. Right now I have to go the the fork and then click on the settings tab where I find the delete button. What do you think? Is it even possible?

**Comment by sindresorhus** [comment]
Yeah, that would be useful. Not sure whether it's possible though. Someone should look into that.

**Comment by vinkla** [comment]
If it isn't possible maybe we could add a button which takes you to the settings page?

**Comment by hkdobrev** [comment]
> If it isn't possible maybe we could add a button which takes you to the settings page instead?
I'd prefer that as it's not only more easy, but more safe as well. You need to confirm a repository name when deleting it as a precaution as well. Having a single button which deletes a repo, even though it's a fork sounds dangerous.

We could have the link say "Go to fork settings to delete it" or something like that.

**Comment by SpaceK33z** [comment]
Nice idea! :+1:

**Comment by vinkla** [comment]
@hkdobrev Yeah, you're probably right. It would be nice if we could trigger a click on the delete button on the settings page though. Then it would be more secure.

**Comment by hkdobrev** [comment]
We could have a link with something in the location hash/query and then detect this on the settings page and click the delete button.

**Comment by paulmolluzzo** [comment]
I can do this

**Comment by vinkla** [comment]
:+1: @paulmolluzzo
