### ISSUE TITLE
Format code blocks in comments with Prettier

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#480]
I often get comments on my repos with some example code from a user and the code is close to unreadable because of bad formatting. Would be nice to have [Prettier](https://github.com/prettier/prettier) run on JS code blocks in comments.

Not entirely sure how we can have it syntax highlighted again after the formatting though.

**Comment by hkdobrev** [comment]
Do you think this is more suitable as a separate extension? I think it would need to use not only Prettier, but then its own code highlighting tool.

**Comment by bfred-it** [comment]
I agree with @hkdobrev; `prettier` is 360KB, more than double RGH.

**Comment by sindresorhus** [comment]
I really like the idea of doing a bot instead. It would work even for people not using Refined GitHub and syntax highlighting would just work as normal without any extra work. Someone please do this!

**Comment by jgierer12** [comment]
Check out https://github.com/jgierer12/prettier-github

**Comment by bfred-it** [comment]
Excellent! I love the preservation of the original as well! The only big issue is that the instructions are for one repo at a time. Is it possible have it apply to all repos?

**Comment by busches** [comment]
Is there still interest in adding this to Refined Github? Having it separate seems to be the way to go.

**Comment by bfred-it** [comment]
The GitHub app works well for me, although it needs to be enabled by the repos/org's owner. I'd rather not have it inside Refined GitHub
