### ISSUE TITLE
Manifest warning in Firefox: event pages are not supported

### ISSUE THREAD

**Issue by gamemaker1** [sindresorhus/refined-github#4805]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Going to `about:debugging` > `This Firefox` in Firefox shows you the following error:

```
Warning details

Reading manifest: Warning processing background.persistent: Event pages are not currently supported. This will run as a persistent background page.
```

Not sure if this is significant, since I don't see any features erroring or not working.

### Screenshot

![image](https://user-images.githubusercontent.com/34235681/134137622-cbf5177b-af3e-442f-8da9-05b14340b6e9.png)

### Console errors

```shell
None
```

### Example URL

--

### Browser(s) used

Firefox

**Comment by fregante** [comment]
It’s a development warning, ignore it.
