### ISSUE TITLE
`bugs-tab` doesn't take into account bug labels with uppercase letters

### ISSUE THREAD

**Issue by mcornella** [sindresorhus/refined-github#4811]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The `Bugs` tab doesn't appear on repositories that have uppercase characters in the bug label, like `Type: Bug` [1] or `Bug` [2].

[1] https://github.com/MithrilJS/mithril.js/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22+sort%3Aupdated-desc
[2] https://github.com/ohmyzsh/ohmyzsh/labels/Bug

NOTE: on testing this bug with the developer extension, I had to make sure to clear the cache before trying new code.

### Screenshot

For URL [1] above:
![Captura de pantalla de 2021-09-23 19-14-46](https://user-images.githubusercontent.com/1441704/134553576-87d40f62-fc7b-48af-8a4f-c991bd87da40.png)

For URL [2] above:
![Captura de pantalla de 2021-09-23 20-11-26](https://user-images.githubusercontent.com/1441704/134561196-0abd05f1-c91d-48f6-8bee-722f51ae8b7d.png)

### Example URL

https://github.com/MithrilJS/mithril.js/issues?q=is%3Aissue+is%3Aopen+label%3A%22Type%3A+Bug%22+sort%3Aupdated-desc

### Browser(s) used

Chrome 94

**Comment by fregante** [comment]
The screenshot in https://github.com/sindresorhus/refined-github/pull/4592 showed a working feature, but it was taken before the rewrite in https://github.com/sindresorhus/refined-github/pull/4592#event-5046928154

cc @yakov116

**Comment by yakov116** [comment]
> The screenshot in #4592 showed a working feature, but it was taken before the rewrite in [#4592 (comment)](https://github.com/sindresorhus/refined-github/pull/4592#event-5046928154)
> 
> cc @yakov116

Correct.

However once it was in my cache I did not notice the mistake.

Should be a simple regex fix
