### ISSUE TITLE
`rgh-feature-descriptions` is broken

### ISSUE THREAD

**Issue by gamemaker1** [sindresorhus/refined-github#4815]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Again! It seems Github removed both `.hx_commit-tease` and `include-fragment.commit-loader`. The closest other one I could find is `#blob_contributors_box`.

### Screenshot

![image](https://user-images.githubusercontent.com/34235681/134762462-9654c646-0635-4390-a531-24e946a0e1af.png)

### Console errors

```shell
❌ rgh-feature-descriptions 21.9.18 → TypeError: undefined has no properties
    init rgh-feature-descriptions.tsx:98
index.tsx:57:9
```

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/source/features/batch-mark-files-as-viewed.tsx

### Browser(s) used

Firefox

**Comment by kidonng** [comment]
> The closest other one I could find is `#blob_contributors_box`.

I think we should just use `.Box-header.Details` as I suggested in https://github.com/sindresorhus/refined-github/pull/4732#discussion_r697866325. We had lots of issues like this which depends on *too* specific selector that is easy to break.

**Comment by kidonng** [comment]
Actually this is not broken on all pages: https://github.com/sindresorhus/refined-github/blob/main/source/features/useful-not-found-page.tsx

**Comment by gamemaker1** [comment]
Hmmm... I don't see it:

![image](https://user-images.githubusercontent.com/34235681/134767251-47f0ddcd-f8b1-4901-86a6-9209cb10b26f.png)

**Comment by kidonng** [comment]
It's like [the last time](https://github.com/sindresorhus/refined-github/pull/4732#issuecomment-907621777), the page is different for us then.
