### ISSUE TITLE
CPU usage

### ISSUE THREAD

**Issue by sahlouls** [sindresorhus/refined-github#4829]
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

During review, the extension hammers CPU usage, github will be inaccessible while writing reviews.

### Screenshot

Not possible to take screenshots, a video maybe

### Console errors

```shell
There a no errors
```

### Example URL

any repo

### Browser(s) used

Chrome

**Comment by fregante** [comment]
Please enter an exact URL where this happens. 

Do you have any other extensions enabled?

**Comment by sahlouls** [comment]
On a private repo, sorry.
I disabled the extension and re-activated it, now it seems to work properly.

**Comment by fregante** [comment]
Good to hear!
