### ISSUE TITLE
[Firefox] Broken tab-indents in markdown code blocks

### ISSUE THREAD

**Issue by jdreesen** [sindresorhus/refined-github#483]
Tab-indented code in markdown is broken in firefox when refined-github extension is enabled:
![broken](https://user-images.githubusercontent.com/424602/27011370-4398e8ee-4eba-11e7-98f5-1bb4ba2fe19b.png)

This is how it should look (with disabled refined-github extension):
![fine](https://user-images.githubusercontent.com/424602/27011372-59f8f070-4eba-11e7-9e4e-3d71d70dec27.png)

If I uncheck this line in the Firefox dev tools, the indentation is correct again: https://github.com/sindresorhus/refined-github/blob/68fd4d17f947089758f344b9f424286f3d39fe48/extension/content.css#L670

Space-indented code seems to work fine, though.

**Comment by jgierer12** [comment]
Can you link to somewhere this is happening?

**Comment by jdreesen** [comment]
Yes of course, sorry, the screenshots are from https://github.com/sindresorhus/element-ready/issues/4 but I noticed this in several other places since I installed the plugin in Firefox.

**Comment by sindresorhus** [comment]
@hkdobrev :arrow_up: (https://github.com/sindresorhus/refined-github/commit/f979305eeea10252433104f1c6c84d4291b9acca)

**Comment by hkdobrev** [comment]
@jgierer12 
> do we still need `letter-spacing: -0.02px;`?

Well, I don't see why not. I admit the difference is minor, so if it's a problem for something, please remove.
