### ISSUE TITLE
Incompatible with Firefox-ESR 78.14.0

### ISSUE THREAD

**Issue by nerdCopter** [sindresorhus/refined-github#4831]
### What I don't like

Incompatible with ESR ☹️

**Comment by fregante** [comment]
Duplicate of https://github.com/sindresorhus/refined-github/issues/4561

**Comment by busches** [comment]
ESR 91.2 comes out next week!

**Comment by nerdCopter** [comment]
Now for Debian 11 to actually use it :P :wink:
