### ISSUE TITLE
Make 404 pages more useful

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#485]
**Examples:**

- non-existent branch https://github.com/sindresorhus/refined-github/tree/404-branch
- existent file https://github.com/sindresorhus/refined-github/blob/shorten-url-labels/test/404.js
- deleted file https://github.com/sindresorhus/refined-github/blob/master/extension/content.js

**Possible content:**
- link to repo root
- link to closest existing directory
- link to last commit that had the file ([example](https://github.com/sindresorhus/refined-github/blob/be756e68dd4bf24d53e802e1fec126506979fa80/extension/content.js)) (possible? edit: [yes](https://github.com/sindresorhus/refined-github/issues/485#issuecomment-309264006))

Perhaps this could be a separate extension though.

**Comment by bfred-it** [comment]
It could display the full URL clickable piece by piece. This URL:

```
https://github.com/sindresorhus/refined-github/blob/shorten-url-labels/test/404.js
```

would become:

## [sindresorhus](https://github.com/sindresorhus/) / [refined-github](https://github.com/sindresorhus/refined-github) / [shorten-url-labels](https://github.com/sindresorhus/refined-github/tree/shorten-url-labels) / [test](https://github.com/sindresorhus/refined-github/blob/shorten-url-labels/test/) / [~~404.js~~](https://github.com/sindresorhus/refined-github/blob/shorten-url-labels/test/404.js)

It could also do a series of light HEAD fetches to the links from right to left, to gradually ~~strikethrough~~ each 404 link until it finds a 200.

**Comment by sindresorhus** [comment]
@bfred-it I like it!

**Comment by hkdobrev** [comment]
This is not that hard and the same time it's too good for a separate extension! 🙌

**Comment by hkdobrev** [comment]
@bfred-it The URL to the upper directory should be using `tree` instead of `blob` to save some redirects on GitHub side.

**Comment by bfred-it** [comment]
@hkdobrev gotcha. Yep it'd need some URL detection as well to skip the `blob` in the original URL and to redirect the branch part to `tree/branch` instead of the original URL's `blob/branch`

**Comment by bfred-it** [comment]
Idea! This file went missing:

https://github.com/sindresorhus/refined-github/blob/master/extension/content.js

Now replace `blob` with `commits` and:

https://github.com/sindresorhus/refined-github/commits/master/extension/content.js

Yep, we can get the URL to the last know commit this way. Or just link to the above.

**Comment by sindresorhus** [comment]
Cool idea. Let's do it.

**Comment by DerTieran** [comment]
I started working on this https://github.com/DerTieran/refined-github/tree/useful-404-page.

Right now it is just the separat `pathname` parts similar to [above](https://github.com/sindresorhus/refined-github/issues/485#issuecomment-308693521), but for now without replacing `blob` with `tree`.

I will try to find some time to finish it or bring it to a PR ready state, but input is always welcome.

**Comment by caxvis** [comment]
How did this PR started at 2017 and hasn't yet be merged

**Comment by yakov116** [comment]
@caxvis what?

**Comment by caxvis** [comment]
This PR was created on 14th June 2018 and was merged to the master branch on 4th October 2018.

lololol

**Comment by bfred-it** [comment]
This is not a PR

**Comment by caxvis** [comment]
oh right
