### ISSUE TITLE
Copy markdown from comments

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#486]
Crazy idea. _What_ **if** [you](https://youtu.be/djV11Xbc914) ~~could~~ <img align="center" width="32" alt="copy" src="http://i.imgur.com/KcadL6G.png"> `this` as markdown by just selecting the page?

```markdown
_What_ **if** [you](https://youtu.be/djV11Xbc914) ~~could~~
<img align="center" width="32" alt="copy" src="http://i.imgur.com/KcadL6G.png">
`this` as markdown by just selecting the page?
```

It'd make copy+replying easier.

Test:

- Juan
- to
- tree

  and a half

1. hey
2. bee
3. see

**Comment by styfle** [comment]
@bfred-it @sindresorhus How about a "view source" button instead of copy to clipboard?

**Comment by bfred-it** [comment]
You can only view the real source of you can edit the comments. What we used here was a converter that wasn’t 1:1 with the source

**Comment by paulirish** [comment]
http://localhost:8696/devtools-protocol/tot/Tracing/#type-MemoryDumpConfighttp://localhost:8696/devtools-protocol/tot/Tracing/#type-MemoryDumpConfig
