### ISSUE TITLE
Most of the feature don't work anymore for me, Safari 15

### ISSUE THREAD

**Issue by noftaly** [sindresorhus/refined-github#4862]
Hey there!
I've used refined-github for a long time, and enjoy it very much.

I've recently updated my Mac to macOS Monterey, and with it, Safari to v15 (precisely Version 15.0 (17612.1.28.5)). Since then, most of the feature of refined-github don't work anymore. Just eyeballing the feature list very very very fast, I can already note all those don't work:
- ci-link
- default-branch-button
- swap-branches-on-compare
- forked-to
- repo-age
- download-folder-button
- toggle-files-button
- copy-file
- list-prs-for-file
- quick-comment-edit
- comment-fields-keyboard-shortcuts
- and many more

### Information:
Safari v15.0
refined-github: latest master at this date (I build it from source)
Only enabled extension
All features are enabled
I have provided a token with all needed scopes but `delete_repo`
I don't use GitHub Enterprise.

I have some errors in the console :
```
[Error] TypeError: mimicFn is not a function. (In 'mimicFn(memoized, fn, {
          ignoreNonConfigurable: !0
        })', 'mimicFn' is an instance of Module)
	mem (refined-github.js:405)
	(anonymous function) (refined-github.js:2950)
	(anonymous function) (refined-github.js:9784)
	Global Code (refined-github.js:9785)
```

Is this expected with the new Safari release, or have I done something wrong?
I figured that there are way too much problems for it to be a bug on your side, so I did not use the "bug" template. Tell me if I should have, I will reopen an issue :)
Thanks for your help!

**Comment by fregante** [comment]
The issue in your console is a build issue. Try running `npm install` from zero and then ensure you're running Node 16

**Comment by noftaly** [comment]
Indeed, removing node_modules fixed it. Idk why I haven't though of this :(
thanks for the help!
