### ISSUE TITLE
Pinned issue's border is very bold/bright in dark mode

### ISSUE THREAD

**Issue by ritikbheda** [sindresorhus/refined-github#4867]
### Description

The pinned issues on top of the page is very bright. I think making it look like other borders in the page would be great and easy for the user.

| Right Now             |  How it Should Be |
:-------------------------:|:-------------------------:
![before_pinnedIssues](https://user-images.githubusercontent.com/60680215/135945601-47ef9a67-3c9a-4199-8410-aac57c0be8ee.png) |  ![after_pinnedIssues](https://user-images.githubusercontent.com/60680215/135945627-af7fc1ad-86e3-42be-86a9-5b81b8aeb854.png)

Although [3806](https://github.com/sindresorhus/refined-github/pull/3806) PR says it works on this issue, it still is very bright right now. Please update me if I am missing something.

Thanks.

### Example URL

https://github.com/sindresorhus/refined-github/issues

**Comment by yakov116** [comment]
Probably #4855

**Comment by ritikbheda** [comment]
I think #4855 has a broader vision than this. I think I should close this issue and follow #4855 ?

**Comment by fregante** [comment]
It was fixed in v21.10.4 as part of https://github.com/sindresorhus/refined-github/pull/4842
