### ISSUE TITLE
Real names aren't shown

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#489]
I just noticed while reviewing #488 that the real names from #251 aren't even showing up for me. I'm getting the following error:

```
TypeError: /arkon/following is not a valid URL.
Stack trace:
showRealNames/</requests<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2394:16
showRealNames/<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2393:20
getCachedUsers/<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2361:47
```

Perhaps a Firefox issue?

BTW @bfred-it would it be possible to set up source maps?

**Comment by sindresorhus** [comment]
Real names are shown for me in Chrome, so looks Firefox specific.

**Comment by bfred-it** [comment]
@jgierer12 source maps enabled in 1b9c989015474260d66172d7f9fae6cd404afd47. Run `npm i`
