### ISSUE TITLE
Change real name styling

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#493]
#488 sparked a discussion about how the real name of comment authors (added in #251) should be styled. See https://github.com/sindresorhus/refined-github/pull/488#issuecomment-308613406 and following comments for context.

Here's a comparison between proposed styles:

1. > **jgierer12** Jonas Gierer • commented 5 hours ago • edited by arkon Eugene Cheung
1. > **jgierer12** Jonas Gierer - commented 5 hours ago • edited by arkon Eugene Cheung
1. > **jgierer12** Jonas Gierer • commented 5 hours ago • edited by arkon *Eugene Cheung*
1. > **jgierer12** Jonas Gierer • commented 5 hours ago • edited by **arkon** Eugene Cheung
1. > **jgierer12** (Jonas Gierer) commented 5 hours ago • edited by arkon (Eugene Cheung)

**Comment by jgierer12** [comment]
I'd prefer 4 or 5

**Comment by hkdobrev** [comment]
:four: :+1:

**Comment by bfred-it** [comment]
5️⃣

**Comment by arkon** [comment]
Seems like :four: is already winning out, but I vote for :five:

**Comment by sindresorhus** [comment]
:four: 👍

**Comment by kumarharsh** [comment]
:five: but #515

**Comment by bfred-it** [comment]
I'm gonna change my vote back to 5 😅

**Comment by hkdobrev** [comment]
@jgierer12 Could you please choose one of :four: or :five:? 😆

**Comment by bfred-it** [comment]
[jgierer12]: https://avatars0.githubusercontent.com/u/4331946?v=3&s=16
  [bfred-it]: https://avatars3.githubusercontent.com/u/1402241?v=3&s=16
  [arkon]: https://avatars2.githubusercontent.com/u/4098258?v=3&s=16
  [sindresorhus]: https://avatars2.githubusercontent.com/u/170270?v=3&s=16
  [kumarharsh]: https://avatars0.githubusercontent.com/u/760112?v=3&s=16
  [hkdobrev]: https://avatars0.githubusercontent.com/u/506129?v=3&s=16


| :one: | :two: | :three: | :four: | :five: | 
| - | - | - | - | - |
|  | | | ![][hkdobrev] ![][jgierer12] ![][sindresorhus] | ![][jgierer12] ![][bfred-it] ![][arkon] ![][kumarharsh] |

@hkdobrev 😄

**Comment by kumarharsh** [comment]
In :five:, shouldn't arkon be bold also?

> **jgierer12** (Jonas Gierer) commented 5 hours ago • edited by **arkon** (Eugene Cheung)

**Comment by bfred-it** [comment]
> In github, bold denotes that the name is linked

Not always. _5 hours ago_ is also a link and it's not bolded. "edited by arkon" is secondary information and that's why it makes sense that it's not bold.

**Comment by arkon** [comment]
I agree that the "edited by arkon" portion is secondary. It makes sense to have the first username bolded since that's the main focus of that entire string, and complements the picture to its left.

**Comment by jgierer12** [comment]
> @jgierer12 Could you please choose one of 4️⃣ or 5️⃣? 😆

It's 5️⃣ then 😊
