### ISSUE TITLE
Embed linked Gists

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#494]
If we find a Gist link in a Markdown container, replace it with an embedded version of the Gist.

i.e.
```html
<a href="https://gist.github.com/jgierer12/06a8e3913ce4ae608c010b6f47efd257">https://gist.github.com/jgierer12/06a8e3913ce4ae608c010b6f47efd257</a>
```
would be replaced with (the result of)
```html
<script src="https://gist.github.com/jgierer12/06a8e3913ce4ae608c010b6f47efd257.js"></script>
```

Slightly related to #472/#473

**Comment by sindresorhus** [comment]
Good idea. We should limit the height though, maybe with some kind of arrow to expand the whole thing.

**Comment by bfred-it** [comment]
https://gist.github.com/jgierer12/06a8e3913ce4ae608c010b6f47efd257

Try this from Refined GitHub's context in the console:

```js
const link = document.querySelector('p a[href^="https://gist.github.com"]:only-child');
fetch(link.href + '.js').then(a => a.text()).then(js => {
	link.outerHTML = eval(js.replace(/document[.]write/g, ';'));
});
``` 

eval-uate alternatives.

**Comment by jgierer12** [comment]
https://gist.github.com/jgierer12/06a8e3913ce4ae608c010b6f47efd257.json actually contains the raw HTML and CSS for the Gist, so we don't need to `eval` the embed script 🙌
