### ISSUE TITLE
Use Promised `browser.*` APIs

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#495]
Firefox copied Chrome's extensions API, renamed `chrome.*` to `browser.*` and made them Promised.

Do you think it's worthwhile to use a `browser.*` polyfill like [mozilla/webextension-polyfill](https://github.com/mozilla/webextension-polyfill) so we can leave callback APIs (and the awful `chrome.runtime.lastError`) in the dust?

I'm guessing that the polyfill also works with unsupported APIs like `chrome.permissions.*`

**Comment by sindresorhus** [comment]
If the polyfill is good, sure.

**Comment by bfred-it** [comment]
Closing because this comment also applies: https://github.com/sindresorhus/refined-github/pull/576#issuecomment-313107015

**Comment by sindresorhus** [comment]
Reopening as I think it's still worth doing, just not right now. Maybe we could only introduce it for new features? That would limit the churn :)

**Comment by bfred-it** [comment]
Leaving this open just as a reminder. `browser.*` APIs are now available with:

```
import browser from 'webextension-polyfill';
```

Example: https://github.com/sindresorhus/refined-github/blob/a88b2d1bc86e4e2fc0464067da54d23448f2005e/src/libs/mark-unread.js#L1
