### ISSUE TITLE
Add minimize/maximize buttons to PR blocks

### ISSUE THREAD

**Issue by tdlm** [sindresorhus/refined-github#50]
I've done this in my own extension but I figure it might help some other people if I contribute it to yours (assuming you're interested).

I used jQuery for mine but it can easily be made in plain JS: https://github.com/tdlm/tdlm-github-tools/blob/master/background.js

Essentially this lets you minimize/maximize PR blocks by clicking on individual blocks or by clicking buttons at the top, like so:

![Minimize/Maximize Blocks](http://i.imgur.com/GSvtiu5.gif)

Either way, it wouldn't be tough to add but it's something I use every day.

**Comment by nikolay** [comment]
:+1:

**Comment by remarkablemark** [comment]
+1

**Comment by hkdobrev** [comment]
I'm curious why do you need that. Looking at this I have a different idea - expanding and collapsing diff contexts. Why do you need to collapse files in the diffs? When I'm looking at a big diff I usually use the diffstat links as table of contents.

**Comment by tdlm** [comment]
@hkdobrev I don't need it; it's just sort of a way to minimize visual clutter when I've looked at something already. A lot of what this plugin does is the same in that respect. For example, moving the +1 votes to the sidebar. Unnecessary but very nice.

**Comment by hkdobrev** [comment]
> minimize visual clutter when I've looked at something already
Got it now. Makes sense during a large code review where you review the changes file-by-file.

**Comment by tdlm** [comment]
@hkdobrev Exactly!

**Comment by paulmolluzzo** [comment]
@tdlm I actually saw your repo about a week or so ago. (Maybe a different one, but very similar in functionality.) Neat!

This repo has Sprint, which is similar to jQuery, so I bet most of it will port easily.
