### ISSUE TITLE
Keep the tabs Insights and Settings on the right

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#502]
Without RGH, **Settings** and **Insights** are the last two tabs.

RGH adds the new **Releases** and **Compare** tabs at the end but I feel that **Settings** and **Insights** should stay at the end.

This is the current situation:

<img width="700" alt="screen shot 2017-06-17 at 20 48 06" src="https://user-images.githubusercontent.com/1402241/27253055-bc32bbe8-539e-11e7-95d0-98f17aa95136.png">

<img width="540" alt="screen shot 2017-06-17 at 20 52 09" src="https://user-images.githubusercontent.com/1402241/27253060-dedaca46-539e-11e7-866e-d241899cecc8.png">

**Comment by jgierer12** [comment]
This has already been attempted in https://github.com/sindresorhus/refined-github/pull/432, but it often doesn't work for me
