### ISSUE TITLE
Org drop down is overlapping on Developer Register page

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#507]
We've moved it to the right on the homepage, but this breaks it on other pages.

Developer regster page: https://github.com/developer/register

![image](https://user-images.githubusercontent.com/506129/27260612-2e27e972-5439-11e7-90c1-df3b43acdbaf.png)

P.S. It's interesting this bug was reported to me on Twitter from fellow Bulgarian - a user of the extension who seems to have mutually blocked @sindresorhus years ago - https://twitter.com/tunnckoCore/status/870761386237988864

**Comment by bfred-it** [comment]
I'm wondering if that picker needs to be moved at all, I feel we had a few related issues before.
