### ISSUE TITLE
Use GitHub releases for new releases

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#508]
So far we have used just Git tags instead of the GitHub releases on top of them. I suggest creating GitHub releases for new versions going forward.

The main reason is that GitHub shows a notification on a new release only for GitHub releases and not Git tags.

Also, we can actually shortly describe what went into that release.

I know the extensions are usually updated automatically, but people following the project would have some more info and also people looking at the repo and visiting the releases page would have something to look on, get some inspiration and probably contribute an idea, enhancement or at least a bug report to a recent feature. It would act as a changelog which is always nice.

**Comment by jgierer12** [comment]
Might be irrelevant if we decide to implement #504

**Comment by bfred-it** [comment]
@hkdobrev given that people don't have a choice nor are informed when extensions update, the commit list is the most appropriate and comprehensive changelog.

**Comment by sindresorhus** [comment]
I agree with @bfred-it
