### ISSUE TITLE
Support & in linkified URLs

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#511]
`linkifyCode` passes HTML to the linkifier (because it musts: #510), but this means that `&` is first escaped and this causes some URls to break. Example:

```js
"<img src='https://avatars1.githubusercontent.com/u/1402241?v=3&;s=40'>"
//                               The parameters should be: ?v=3&s=40
```

See it here in action: https://github.com/bfred-it/sandbox/blob/master/index.js

A solution I could think of would be to have the linkifier return actual DOM nodes so we don't have to inject plain HTML **and** this means we can pass unescaped data to it.

**Comment by bfred-it** [comment]
21fd5f059aaa015fe8a5f1554039125265b628f3 causes this issue because we don't want tags to be converted to real DOM during the `.innerHTML = ` injection.

I'm thinking that we can revert 21fd5f059aaa015fe8a5f1554039125265b628f3 + instead of parsing the whole string returned by `linkify-urls`, we could **exclusively** _domify_ the `<a>`'s generated by `linkify-urls`. Headache.

Or just implement this, really: https://github.com/sindresorhus/linkify-urls/issues/2

**Comment by sindresorhus** [comment]
> Or just implement this, really: [sindresorhus/linkify-urls#2](https://github.com/sindresorhus/linkify-urls/issues/2 "Get DOM nodes back instead of HTML")

This would IMHO be the correct fix.
