### ISSUE TITLE
CSP error when running in firefox Developer Edition

### ISSUE THREAD

**Issue by plessbd** [sindresorhus/refined-github#516]
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: onsubmit attribute on DIV element.
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: onchange attribute on DIV element.
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src https://assets-cdn.github.com”). Source: onfocusin attribute on DIV element.

empty string passed to getElementById().  https://assets-cdn.github.com/assets/github-7e18623cbda14e6a1f6a72e839ed27bd65df61d15e56c8b06540f7a5f2c57149.js:6:29412
```
I will admit I might be doing something wrong, but I have tried to get this to work in firefox, and firefox develoepr edition without success.

The only error sI have been able to find are those above.

Any suggestions?

**Comment by bfred-it** [comment]
Strange, those don't seem to be related to refined-github

**Comment by plessbd** [comment]
I am going to blame my newborn (really lack of sleep) you are correct, if I disable every other extension I do not get the CSP errors.

The only error I get is the empty string one.

Still have not been able to get refined-github to work on firefox.

Sorry for the erroneous issue.

**Comment by jdreesen** [comment]
I get the same errors when uBlock is enabled:

```
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: !function(t){function __webpack_require_.... 516:1
Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src https://assets-cdn.github.com"). Source: ;(function installGlobalHook(window) {  .... 516:1
Leerer String an getElementById() übergeben.  github-7e18623cbda14e6a1f6a72e839ed27bd65df61d15e56c8b06540f7a5f2c57149.js:6:29412
TypeError: NetworkError when attempting to fetch resource.  (unbekannt)
```

When disabling uBlock I only get the empty string one, too.

I'm using Firefox 54.0 (64-Bit).

**Comment by bfred-it** [comment]
<img width="745" alt="screen shot 2017-06-23 at 01 41 22" src="https://user-images.githubusercontent.com/1402241/27447837-244a7288-57b5-11e7-93c5-7b8ef1133494.png">

It works fine for me in both v49 and v55.0b3
