### ISSUE TITLE
AMO release not working with Firefox Developer Edition

### ISSUE THREAD

**Issue by plessbd** [sindresorhus/refined-github#517]
I am not positive why, but the AMO release did not work with Firefox Nightly.
However, after I installed https://addons.mozilla.org/en-US/firefox/addon/chrome-store-foxified/ and installed the version from the chrome webstore it worked without issue.

Thought I would share incase anyone else has issues or if there is something else going on.

**Comment by bfred-it** [comment]
<img width="745" alt="screen shot 2017-06-23 at 01 41 22" src="https://user-images.githubusercontent.com/1402241/27447837-244a7288-57b5-11e7-93c5-7b8ef1133494.png">

It works fine for me in both v49 and v55.0b3 — both the current version on master and the version on Mozilla Addons.

The console errors in my console are GitHub's own.

**Comment by plessbd** [comment]
First thing I did was a new profile:
<img width="1160" alt="screen shot 2017-06-22 at 3 56 47 pm" src="https://user-images.githubusercontent.com/683012/27453142-732bc052-5763-11e7-961e-eb96a2286c31.png">

**Comment by plessbd** [comment]
looks like it might be page specific.
The news feed as you show does work on mine as well.  But the repository pages are not working

**Comment by plessbd** [comment]
I have gotten a bit further, when visiting this issue page and having the debugger
"stop on exception" it stops with an SyntaxError Exception on 
unreadIndicatorIcon@moz-extension://66e81471-ae34-184e-8fcc-4697b3c8ef52/mark-unread.js:237:6
which when looking at the source code looks quite a bit different

```js
function unreadIndicatorIcon() {
		const $notificationIndicator = $('.header-nav-link.notification-indicator');
		const $notificationStatus = $notificationIndicator.find('.mail-status');

		let hasNotifications = $notificationStatus.hasClass('unread');
		if (JSON.parse(localStorage.unreadNotifications).length > 0) { /* THIS IS LINE 237 (according to ff) /*
			hasNotifications = true;
			$notificationStatus.addClass('local-unread');
		} else {
			$notificationStatus.removeClass('local-unread');
		}

		$notificationIndicator.attr('aria-label', hasNotifications ? 'You have unread notifications' : 'You have no unread notifications');
	}
```

which does seem like a syntax error...

**Comment by bfred-it** [comment]
What are you using exactly, that code is not there anymore: 

```js
function unreadIndicatorIcon() {
	const notificationIndicator = select('.header-nav-link.notification-indicator');
	const notificationStatus = notificationIndicator.querySelector('.mail-status');
	const hasUnread = select.exists('li.js-notification.unread') || loadNotifications().length > 0;
	const label = hasUnread ? 'You have unread notifications' : 'You have no unread notifications';

	notificationStatus.classList.toggle('unread', hasUnread);
	notificationIndicator.setAttribute('aria-label', label);
}
```

https://github.com/sindresorhus/refined-github/blob/f073dd2/src/libs/mark-unread.js#L236-L244

**Comment by bfred-it** [comment]
Ah. 1.20.1 is not on AMO. Investigating...

**Comment by bfred-it** [comment]
The extension's ID did not match the ID on AMO, so AMO thought it was an unlisted extension and it just signed it:

<img width="624" alt="screen shot 2017-06-23 at 22 22 23" src="https://user-images.githubusercontent.com/1402241/27486209-75e7a7ca-5862-11e7-8d47-86e189956e02.png">

**Comment by bfred-it** [comment]
1.20.1 is now on AMO. Update!

**Comment by plessbd** [comment]
@bfred-it I knew the code wasnt there that is why I said it didnt look the same :)

I can confirm this is now working thank you

**Comment by bfred-it** [comment]
Excellent! Thanks :)
