### ISSUE TITLE
Deploy is failing

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#519]
https://travis-ci.org/sindresorhus/refined-github/builds/245849567

```
> refined-github@ release:amo /home/travis/build/sindresorhus/refined-github
> cd extension && webext submit
/home/travis/build/sindresorhus/refined-github/node_modules/.bin/web-ext sign
Missing required arguments: api-key, api-secret
```

**Comment by sindresorhus** [comment]
// @bfred-it

**Comment by bfred-it** [comment]
Ahhh true, you'll have to set up the keys in travis. Hold on

**Comment by bfred-it** [comment]
Get them here: https://addons.mozilla.org/en-US/developers/addon/api/key/

**Comment by bfred-it** [comment]
Save them as:

<img width="181" alt="screen shot 2017-06-23 at 01 13 15" src="https://user-images.githubusercontent.com/1402241/27446712-285aee10-57b1-11e7-8463-bc94a98baf0b.png">

**Comment by bfred-it** [comment]
Which module is trying to include `html-tags`?

**Comment by sindresorhus** [comment]
> Save them as `WEB_EXT_API_KEY` and `WEB_EXT_API_SECRET`

Done

**Comment by sindresorhus** [comment]
@bfred-it Why is this failing? https://travis-ci.org/sindresorhus/refined-github/builds/246668987#L239

> Building web extension from /home/travis/build/sindresorhus/refined-github/extension
Validating add-on [                          .  .          .     .             ]
sign: Error: Received bad response from https://addons.mozilla.org/api/v3/addons/%7Ba4c4eda4-fb84-4a84-b4a1-f7c1cbf2a1ad%7D/versions/17.6.24.2348/uploads/52d3cf7ea30c4516a135f2f7baaaa07f/; status: 401; response: {"detail":"JWT iat (issued at time) is invalid. Make sure your system clock is synchronized with something like TLSdate."}
    at /home/travis/build/sindresorhus/refined-github/node_modules/sign-addon/dist/webpack:/src/amo-client.js:485:17
    at tryCatchReject (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/makePromise.js:845:30)
    at runContinuation1 (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/makePromise.js:804:4)
    at Fulfilled.when (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/makePromise.js:592:4)
    at Thenable.Pending.run (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/makePromise.js:483:13)
    at Scheduler._drain (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/Scheduler.js:62:19)
    at Scheduler.drain (/home/travis/build/sindresorhus/refined-github/node_modules/when/lib/Scheduler.js:27:9)
    at _combinedTickCallback (internal/process/next_tick.js:95:7)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by bfred-it** [comment]
Whoah that never happened. It might be a good idea to open an issue on web-ext. 

I should specify that `web-ext submit` doesn't exist so I created a wrapper that calls `web-ext sign` and discards the "submitted but not yet signed" error.

**Comment by bfred-it** [comment]
Uh, AMO review:

> Comments:
> This version did not pass the review because of the following issues:

> 1) I'm sorry, but we can't allow fragments/blocks of minified/3rd party library/obfuscated sources/templates code to be spliced in with other scripts. If you do include minified code, we also need access to clear text sources.

> Established libraries must be included separately, from their official source, in their original format without any modification (changing the file name does not matter). Please note that only stable releases of are acceptable (not beta, pre, RC, dev etc). Minified versions are better. Please note that third party CDNs are not considered official sources for this purpose.
> There is no need to include .map files for established libraries.
> eg:
> content.js



> Please fix them and submit again. Thank you.

I'm going to assume that the only change necessary would be unminifying jQuery and **not** unbundling all the dependencies.

**Comment by sindresorhus** [comment]
I assumed so too.
