### ISSUE TITLE
Blog post - Feedback wanted

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#521]
I wrote a quick blog post about what's new in Refined GitHub lately. Could use some feedback.

https://medium.com/@sindresorhus/whats-new-in-refined-github-836d05582df7

**Comment by bfred-it** [comment]
> Search filter for ‘Everything commented by you’

Nice! I had missed that one.

The post looks pretty good!

**Comment by busches** [comment]
Looks good.

**Comment by jgierer12** [comment]
Looking great :)

**Comment by hkdobrev** [comment]
Gosh, you guys are putting features out so fast that one starts to forget about them! Great post and almost feels like a retrospective for me. @sindresorhus Thank you for that! ❤️ 

Even though I like the spirit of the last sentence:
> The goal of Refined GitHub is to make itself obsolete.

It's funny that this seems so impossible at the moment (compared to the beginning) with us adding so many new things so fast and with GitHub adding mostly things about newcomers to grow even more. 😆 

Props go to the whole team and especially @bfred-it who is on fire lately! 🎉

**Comment by paulmolluzzo** [comment]
This is excellent! I've been head down lately, but WOW the work done lately has beeen so awesome!

> Props go to the whole team and especially @bfred-it who is on fire lately! 🎉

🔥🔥🔥 For real @bfred-it!

**Comment by sindresorhus** [comment]
Published: https://blog.sindresorhus.com/whats-new-in-refined-github-836d05582df7

**Comment by sindresorhus** [comment]
850 more people are using Refined GitHub after the blog post was published.

**Comment by paulmolluzzo** [comment]
🎉
