### ISSUE TITLE
Right-aligned issue labels

### ISSUE THREAD

**Issue by jthegedus** [sindresorhus/refined-github#523]
Right-aligned issue labels would improve visual grepping as they would be horizontally aligned, unlike the staggered pattern we have now.

![github-issue-labels](https://user-images.githubusercontent.com/20798510/27468037-80fc8424-582a-11e7-83c3-ac47267496d8.png)

The proposed placement would be to the left of where the Assignee is, regardless of if there is any. Milestones and Author appear on the line below so do not interfere with this proposition. 

![github-issue-labels-right-aligned](https://user-images.githubusercontent.com/20798510/27468038-85a53b60-582a-11e7-8bb7-a291dd6c0c7b.png)

When the labels no longer fit due to issue title length, they should appear on a new line as the current behaviour on GitHub, just right-aligned from the same point as in the above image.

Cheers for the awesome extension everyone!

**Comment by bfred-it** [comment]
Definitely :+1: for me. Tags are messy. Let's see what the others say

**Comment by vadimdemedes** [comment]
Interesting idea! I'd also mention that tags should be sorted to make "visual grepping" even easier.

**Comment by sindresorhus** [comment]
I'm not really bothered by how it currently works, but I'm fine with changing it to this proposal.
