### ISSUE TITLE
Feature Change: Reaction Avatars should link to user

### ISSUE THREAD

**Issue by plessbd** [sindresorhus/refined-github#525]
Currently if you click on a reaction avatar it will add you to that reaction, which I found a bit odd.
I think it should either link that that persons profile or do nothing.

**Comment by fnky** [comment]
The problem is actually that the event handler for reaction prevents any clicks to the underlying anchor tags inside of it. You will notice that there actually is a link to the avatar when you hover it.

**Comment by plessbd** [comment]
Well that explains it.  Firefox actually doesn't show this on hover, so I didn't see it.

**Comment by bfred-it** [comment]
In Chrome you can right click on the avatars to open the link, but Firefox disables links inside buttons.
