### ISSUE TITLE
Automatically refresh an empty notification page on new notifications

### ISSUE THREAD

**Issue by fregante** [sindresorhus/refined-github#530]
1. Empty: https://github.com/notifications
  
    <img width="275" alt="no notif" src="https://user-images.githubusercontent.com/1402241/27506095-c35b0a70-58e3-11e7-91c5-f5dfd886ba81.png">

2. New notification comes

    <img width="275" alt="yes notif" src="https://user-images.githubusercontent.com/1402241/27506096-c55cf388-58e3-11e7-8f1b-c5c754e306b2.png">

3. _GitHub don't care_
4. Refined GitHub cares and reloads the page

    <img width="275" alt="yes rgh" src="https://user-images.githubusercontent.com/1402241/27506109-0dce81ea-58e4-11e7-89bd-f1918cf995fd.png">

### One concern

It's easy to do this when the first notification comes in because the indicator appears in the dom, but I'm not sure if we can know if any further notifications are there without repeating API calls.

If anyone picks this up, they should probably keep this in mind.

**Comment by hkdobrev** [comment]
Is that possible? I've don't think GitHub would update the notification icon.

**Comment by bfred-it** [comment]
Yeah they do update the icon, which is why it's strange they wouldn't also update the view.

If we do this, we should only update if the view is empty or `document.hidden === true`, otherwise it's hard to manage a _diff_ and it'd make links move down.

**Comment by bfred-it** [comment]
I think the **one concern** kinda kills the idea, short of regularly fetching the notifications. I pull the request

**Comment by bfred-it** [comment]
> short of regularly fetching the notifications

We could do that, right?

- fetch if the tab is visible
- display instantly if the page is empty
- otherwise display _"There are X more notifications. Click to display"_

**Comment by fregante** [comment]
Notifications Beta has it! 🎉
