### ISSUE TITLE
Using JSX to create elements XSS-free

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#539]
We use HTML strings with user-provided data all over the extension, this is XSS 101.

The alternative to that is a lot of inelegant calls and de-XSS-ifying [this piece of code](https://github.com/sindresorhus/refined-github/blob/82c11c1a1906bc735892256f25295e436153b53a/src/libs/mark-unread.js#L187-L214) gets ugly real fast.

I wish there was a JSX-to-DOM compiler that allowed use to write safe HTML:

```jsx
const element = <a class="one two" href="{element.title}">{name}</a>
```
```js
const element = document.createElement('a');
element.className = 'one two';
element.href = element.title;
element.textContent = name;
```

Well, it turns out we have some options:

https://www.npmjs.com/package/rollup-plugin-jsx

A factory for that would be something like [`h`](https://github.com/dominictarr/h/blob/master/index.js), which appears to be pretty small.

Just like that, all `.innerHTML` calls are gone.

**Comment by vadimdemedes** [comment]
> I wish there was a JSX-to-DOM compiler that allowed use to write safe HTML:

Excellent idea. I would be more than happy to implement that project.

**Comment by bfred-it** [comment]
If anyone starts, it'd be nice to have that exact big chunk of HTML be the first part to be JSX-ified to make sure it actually solves a problem :)

**Comment by vadimdemedes** [comment]
Done - https://github.com/vadimdemedes/dom-chef! Submitting a demo PR soon.
