### ISSUE TITLE
JS Error on Repo when behind proxy

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#543]
On the latest master, I'm getting the following JS error when navigating basically anywhere on Github itself.

The first error I don't care about, but the second and third are coming from Refined GitHub  
![image](https://user-images.githubusercontent.com/857700/27557298-b29deb02-5a7e-11e7-87cd-2ffa43af4542.png)

I'm not sure where the below error is being thrown from, even with sourcemaps on I get that line number which is minified.
`github-29b5a05….js:3 OPTIONS https://api.github.com/_private/browser/stats net::ERR_BLOCKED_BY_CLIENT`
I'm not sure why it's coming back `ERR_BLOCKED_BY_CLIENT` but the page itself returns this value:
```json
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3"
}
```

**Comment by bfred-it** [comment]
That's not us, it's likely an ad blocker
