### ISSUE TITLE
Duplicate the expand button in the middle on split diffs

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#547]
When you are looking at a diff, you have an Expand button to show more context around the changed lines.

When you are using the Unified diff, the expand button is on the left and it's all good.

When you are using the Split diff, though, the expand button is still only on the left and it's pushed too far to the left.

I suggest to either duplicate or move the expand button on Split diffs to be present just in the middle between the left and the right side of the diffs.

**Comment by bfred-it** [comment]
For reference:

<img width="207" alt="screen shot 2017-06-27 at 18 19 06" src="https://user-images.githubusercontent.com/1402241/27582886-23c71ab0-5b65-11e7-85a1-01f784b73261.png">

**Comment by bfred-it** [comment]
Perhaps the whole line can become a button. Add a hover state and then `.onclick => expand.click()`
