### ISSUE TITLE
Add dropdown menu to the search bar scope

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/refined-github#548]
Currently:

* On a repo page:
    <img width="313" alt="This repository | Search" src="https://user-images.githubusercontent.com/25517624/27594328-793b0f26-5b27-11e7-980a-fa2c7edbc8a2.png">
* On an organization page:
    <img width="312" alt="This organization | Search" src="https://user-images.githubusercontent.com/25517624/27594353-8705ac7e-5b27-11e7-9b46-44601d89c6e3.png">
* Elsewhere:
    <img width="312" alt="Search GitHub" src="https://user-images.githubusercontent.com/25517624/27594461-cdbbdeae-5b27-11e7-9352-519b104d681a.png">

Feature requests:

* Support searching a user’s content:
    <img width="310" alt="This user | Search" src="https://user-images.githubusercontent.com/25517624/27594423-b4c45e94-5b27-11e7-9150-66fa65711edc.png">
* Add a scope dropdown to all pages:
    <img width="312" alt="screen shot 2017-06-27 at 11 03 20" src="https://user-images.githubusercontent.com/25517624/27594679-6f74a154-5b28-11e7-826f-b4259cea2e3f.png">

**Comment by bfred-it** [comment]
What would the scope dropdown include?

**Comment by j-f1** [comment]
On a repo page: repo, org/user, all of GitHub.

On an org/user page: org/user and all of GitHub

**Comment by bfred-it** [comment]
1. ✅ "user search" on User page sounds good. There's only a simple search in the user's Repositories view
2. ❌ "User search" from repo page sounds rare and it'd just be a click away anyway (click user page, use the User search of point 1)
3. ❌ "all of GitHub" is always one <kbd>backspace</kdb> away everywhere, so no dropdown is ever necessary.

**Comment by hkdobrev** [comment]
A bit off-topic, but I'm using https://chrome.google.com/webstore/detail/awesome-autocomplete-for/djkfdjpoelphhdclfjhnffmnlnoknfnd which significantly changes the search experience on GitHub when you are just using the search box on every page. I wouldn't say it's useful everyday, but it's worth a try if you are searching a lot for different things.

**Comment by bfred-it** [comment]
True! I installed it so long ago that I forget it's not part of GitHub itself

**Comment by bfred-it** [comment]
I think the user search is still useful. I always need my Sindresearch.

**Comment by bfred-it** [comment]
Moved to a specific issue for clarity
