### ISSUE TITLE
Hide repo meta-info when empty and no access to edit

### ISSUE THREAD

**Issue by michaelzoidl** [sindresorhus/refined-github#549]
If a repo-admin didn't set a description it shows `No description, website, or topics provided.`, my proposal is to hide those informations for non-admins, its a obvious information i don't need always on the top of a repo. (space is everything 👆)

**Here is a preview how it looks at the moment and how it could look:**

At the moment:
![](https://mjz.io/htSQ5.png)

Prosposal:
![](https://mjz.io/rmT1w.png)

**Comment by hkdobrev** [comment]
@michaelzoidl This is an excellent suggestion for this extension! Would you care to create a pull request?

**Comment by bfred-it** [comment]
Only if it's instant though, I wouldn't like the whole page to jump up seconds later.

**Comment by paulmolluzzo** [comment]
> Only if it's instant though, I wouldn't like the whole page to jump up seconds later.

As long as the solution is CSS it won't jump.

**Comment by hkdobrev** [comment]
Implemented in #553.
