### ISSUE TITLE
Option to disable font override

### ISSUE THREAD

**Issue by aaronjensen** [sindresorhus/refined-github#556]
GH now has SF Mono by default, which is quite a nice font. I'd rather not see operator mono. Would it be possible to make the font override an option? Thanks!

**Comment by sindresorhus** [comment]
Yeah. Either we drop it altogether or we disable it by default and add a font and font size option.

**Comment by bfred-it** [comment]
I'd vote to drop it 👍

**Comment by sindresorhus** [comment]
If anyone misses this feature, see: https://github.com/sindresorhus/module-requests/issues/97

**Comment by yorch** [comment]
First of all, thanks for this great extension!

One of the features that I like the most was the custom font (FiraCode) so I'm definitely missing it. IMHO, it would have been a better transition path to keep this feature on (or to merge the `disable font` feature) until there is a decent Chrome Extension to change the font for code blocks on Github. I've tried couple of other Chrome Extensions but they are not too good, so now I'm stuck with the non-ligatures font on Github until I get some time to write my own extension (or fork this one and bring custom font back :)) or @sindresorhus adds another project under his belt (big kudos man btw!).

Anyways, just my 2 cents
