### ISSUE TITLE
Collapse "+1" comments

### ISSUE THREAD

**Issue by arkon** [sindresorhus/refined-github#559]
Threads sometimes end up having a bunch of comments that just consist of "+1", which are pretty annoying. See [this thread](https://github.com/Microsoft/vscode/issues/178) as an example.

A nice feature would be to show these comments in a more collapsed way so they don't waste as much space.

**Comment by sindresorhus** [comment]
Users should just use reactions. If you have a problem with users not using those, a bot that auto-deletes such comments would be a better solution.

**Comment by well1791** [comment]
Agreed, if those comments give no value to the issue, it's better to delete them. But still, having a feature that collapse those things is useful.

**Comment by arkon** [comment]
If I could go around deleting all the +1 comments, I would. ¯\_(ツ)_/¯

**Comment by sindresorhus** [comment]
We used to have this feature, but it was removed in favor of GitHub reactions.
