### ISSUE TITLE
"Project" tab under a repository doesn't show up, even under dropdown

### ISSUE THREAD

**Issue by fluffywaffles** [sindresorhus/refined-github#560]
The entire issue is in the title!

Let me know if there's some way I can help fix. Thanks!

**Comment by sindresorhus** [comment]
It only shows up if you have a project. This is documented in the readme.

**Comment by bfred-it** [comment]
Since we have a drop down now I suggest stuffing it in there instead. We already decided that More is full of stuff we don't use anyway.

**Comment by sindresorhus** [comment]
@bfred-it 👎 I don't see how that changes anything. We shouldn't use it as a junk drawer. "Projects" was removed for other reasons. The ones in the "More" are just less useful, not completely useless.

**Comment by fluffywaffles** [comment]
@sindresorhus I thought my use-case (I don't have a project and I want to add one) was useful. But this is your project, of course; I'll just disable it so I can make projects from my repo pages if I can't find the button.

**Comment by bfred-it** [comment]
You can create Projects from your repo's settings page:

<img width="430" alt="screen shot 2017-07-02 at 09 39 22" src="https://user-images.githubusercontent.com/1402241/27766649-56e2cd9c-5f0a-11e7-99bf-c43d5c968ed1.png">

After creating one, the Project tab will re-appear.

**Comment by fluffywaffles** [comment]
Thanks for the tip, @bfred-it ! I didn't realize you could do that.

I don't think this project is actually for me, regardless. I guess I prefer having a common UI with my collaborators over the improvements from the extension. Thanks though!

**Comment by hkdobrev** [comment]
Hey @fluffywaffles, thanks for dropping by! The extension is meant for power users who already know their way around GitHub fairly well. But even that said, it's quite opinionated. Any feedback on non-intuitive things is always welcome!

BTW the add project button in the settings is added by the extension specifically because we are hiding the projects tab when there aren't projects. This way users don't need to guys the URL.

**Comment by bfred-it** [comment]
@sindresorhus makes sense. How about just putting the **Add a project** button in the dropdown then? It doesn't affect you, nobody else but admins will see it and those who can see it and are bothered by it can also disable the projects altogether.

**Comment by sindresorhus** [comment]
> How about just putting the **Add a project** button in the dropdown then? It doesn't affect you, nobody else but admins will see it and those who can see it and are bothered by it can also disable the projects altogether.

👎 from me.

- It doesn't fit with the other buttons. This is an action, the other buttons are for going to root pages.
- It will clutter the menu for no good reason. It's not like you add a project to repos daily. Only things you use very often should be in the main UI. The rest fits in the Settings page.
- It's easy to say that users can just disable "Projects", but most won't bother to do that, and the point of this extension is to improve the "default" experience for power users.
- This extension is for power users.

**Comment by sarupbanskota** [comment]
From #596 

> Maybe it would be worth adding a section in the quick setup page that mentions projects aren't visible cuz 0, and supply a new project button ¯\(ツ)/¯

(altho I'm not sure how often the quick setup gets read by pro users)
