### ISSUE TITLE
Delete comment button should not be next to edit

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#562]
In the spirit of #410, we should move the delete comment button next to inline review comments away from the edit comment button. It's even worse with these small buttons which show up only on hover.

![image](https://user-images.githubusercontent.com/506129/27803169-12fc3e30-6020-11e7-8029-45bd046c340d.png)

**Comment by bfred-it** [comment]
I don't see the issue, delete requires a confirmation

**Comment by hkdobrev** [comment]
@bfred-it As does the cancel button we've moved before.

**Comment by sindresorhus** [comment]
> As does the cancel button we've moved before.

The confirmation on cancel is also added by Refined GitHub though.

**Comment by sindresorhus** [comment]
I think this should be an exception as it would look ugly to move the `x` button and it has a confirmation anyway.
