### ISSUE TITLE
Content scripts/styles are erroneously injected multiple times

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#565]
Caused by https://github.com/bfred-it/webext-dynamic-content-scripts. Hard to debug because it only happens to some.

Related issue: https://github.com/bfred-it/webext-dynamic-content-scripts/issues/2

Replaces issue: https://github.com/sindresorhus/refined-github/issues/479

**Comment by OmgImAlexis** [comment]
@bfred-it any idea on how I can try and debug this? I'm getting this 100% of the time that I load a page. When Ajax kicks in it seems to only happen for the issues tab and the PR tab.

```
Refined GitHub was loaded multiple times: https://github.com/sindresorhus/refined-github/issues/479: 1
```

**Comment by hkdobrev** [comment]
@bfred-it Do you think this is still reproducible with the latest loading changes?

**Comment by bfred-it** [comment]
Probably. I'm gonna have to sprinkle `console.log`s all over the place for everyone and then hopefully we'll figure it out.

**Comment by bfred-it** [comment]
Version `17.11.7.548` should soon appear in the store, you can force an update from the `chrome://extensions` page. This should give us a better understanding of what's happening.

@OmgImAlexis @hkdobrev @busches @derimagia @SimenB do you still see the error in the console? In this new version, the error is no longer just `Refined GitHub was loaded multiple times` but this:

<img width="520" alt="screen shot 2017-11-07 at 13 53 28" src="https://user-images.githubusercontent.com/1402241/32479074-1431c7aa-c3c3-11e7-861a-db2d85e4bcae.png">

**Comment by SimenB** [comment]
I got the message by just opening this issue. Will update to latest and see if it still appears 🙂 

![image](https://user-images.githubusercontent.com/1404810/32479423-13f9c0fa-c38a-11e7-89f5-b967f00d9246.png)

**Comment by OmgImAlexis** [comment]
1 and 2 are no. The extra noise on the first screenshot is a privacy extension I use.

![screen shot 2017-11-07 at 5 03 56 pm](https://user-images.githubusercontent.com/6525926/32480276-c672974a-c3dd-11e7-8d5b-2b44ae47d2af.png)
![screen shot 2017-11-07 at 5 05 02 pm](https://user-images.githubusercontent.com/6525926/32480278-c95dfdbe-c3dd-11e7-85f1-c6417bcd86fc.png)

**Comment by bfred-it** [comment]
@SimenB it looks like is a simple timeout. I’m gonna have to increase it. 

@OmgImAlexis is that all? I’m not seeing the “injecting” message. The log seems correct as the ping happens in time so no injection occurs.

**Comment by OmgImAlexis** [comment]
Yeah I'm not seeing any issues now. One of the last few updates has caused it all to work again.

**Comment by bfred-it** [comment]
I just pushed a new release: `17.11.7.1252`

This changed the whole underlying mechanism (https://github.com/bfred-it/webext-dynamic-content-scripts/commit/95eb02c30e957aa3b170e9a167bbb59f9bfb41e0?diff=split) and probably this will be more reliable and faster because it doesn't need a timeout; Chrome should just run the code and handle the callback when ready.

**Comment by SimenB** [comment]
@bfred-it Log message is gone with 1252 🎉

**Comment by bfred-it** [comment]
Great! Now we just need to make sure it works on GHE.

**Comment by hkdobrev** [comment]
Thanks for everyone providing feedback so quickly here! I couldn't reproduce this from the get go anyway.

**Comment by SimenB** [comment]
I use GHE at work, but I haven't notices the same issue there. Can check tomorrow anyways

**Comment by bfred-it** [comment]
Thanks everyone! Hopefully this will no longer be a problem after `v17.11.7` :)

**Comment by waldyrious** [comment]
> Hopefully this will no longer be a problem after `v17.11.7` :)

@bfred-it I just noticed this — I'm on `v19.2.18`.

**Comment by bfred-it** [comment]
Probably because you're running both the Chrome Store version and the side-loaded dev version.

**Comment by waldyrious** [comment]
I don't recall doing so. How can I check to make sure? Btw, I'm on Firefox on macOS.

**Comment by bfred-it** [comment]
1. Disable Refined GitHub
2. Open GitHub and see if Refined GitHub enhancements are still applied

If they are, then you have 2 separate instances running.

Also:

- just try disabling and reenabling RGH
- are you running it on GitHub enterprise?

**Comment by waldyrious** [comment]
> Just try disabling and reenabling RGH

Hahaha this solved it! Another win for the "turning it off and on again" move -- dammit! :)

**Comment by yakov116** [comment]
Getting the issue on GitHub main page

**Comment by Krzmbrzl** [comment]
I just got this message while reviewing a PR. Any additional info that you need on that?

**Comment by busches** [comment]
@Krzmbrzl were you running a local copy and the extension from the store?

**Comment by Krzmbrzl** [comment]
> Krzmbrzl were you running a local copy and the extension from the store?

Not that I know of. I only installed it from the Firefox addon store.

Note that when this happened I also experienced my CPU going up to 100% while GitHub Refined was running. After turning it off, the CPU load went back to normal. Idk if that is related to this problem though.

**Comment by fregante** [comment]
Is this something that happens repeatedly or did it happen once? It might happen if Firefox updates the extension and runs the code a second time on the open tabs.

For high CPU usage in Firefox refer to https://github.com/sindresorhus/refined-github/issues/4263

Maybe you can try using the "Find feature" if it's something you see regularly on some page. We have to fix that

**Comment by Krzmbrzl** [comment]
For now it only happened once (at least I only noticed it once). I will let you know if I experience it again.

Thanks for your help :+1:
