### ISSUE TITLE
Add shortcuts to navigate to PR tabs

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#568]
I think it would be useful to have keyboard shortcuts to navigate to Conversation, Commits and Files changed tabs in a pull request.

I think the keyboard shortcuts should start with <kbd>g</kbd> so they don't collide with other things or be unintuitive.

Do you support that so we could disucss specific shortcuts?

**Comment by sindresorhus** [comment]
I like it. I change between those so often that keyboard shortcuts would be useful.

**Comment by hkdobrev** [comment]
I'll propose the following variants for shortcuts:

**Variant 1**

Start with <kbd>g</kbd> like other navigational shortcuts:

- <kbd>g</kbd> + <kbd>g</kbd> Conversation (~~Discussion~~ g + d is Dashboard, ~~Conversation~~ <kbd>g</kbd> + <kbd>c</kbd> is Code, ~~Just <kbd>c</kbd>~~ is create issue/PR. gg is like go to beginning in vi)
- <kbd>g</kbd> + <kbd>l</kbd> Commits (like go to log, as <kbd>g</kbd> + <kbd>c</kbd> is taken for going to the Code repo tab)
- <kbd>g</kbd> + <kbd>f</kbd> - Files changed

**Variant 2**

Start with another prefix for navigating in a PR: <kbd>p</kbd>:

- <kbd>p</kbd> + <kbd>c</kbd> Conversation
- <kbd>p</kbd> + <kbd>l</kbd> Commits (like PR log)
- <kbd>p</kbd> + <kbd>f</kbd> - Files changed

**Comment by hkdobrev** [comment]
Would you do another emoji vote, please? /cc @sindresorhus @bfred-it @jgierer12

**Comment by sindresorhus** [comment]
Variant 3, just use numbers. p+1, p+2, p+3, like with browser tabs in Chrome (Cmd+1,2,3...).

**Comment by bfred-it** [comment]
I like numbers the most. Easier to remember and can be used anywhere they have tabs too.

**Comment by hkdobrev** [comment]
Hmm, you'd need two hands for this or move your hand across the keyboard. It's also a bit ambiguous which tabs you navigating to.

**Comment by sindresorhus** [comment]
> you'd need two hands for this or move your hand across the keyboard

Only if we make it `p`. Could use `q` or `w` instead.

> It's also a bit ambiguous which tabs you navigating to.

Not really more ambiguous than arbitrary characters as shortcuts (like `p`+`l`).

**Comment by hkdobrev** [comment]
Ambiguous as in it's not really clear which tabs you're navigating - the repository tabs, the PR tabs or something else? The `p` prefix could hint that you're navigating the PR tabs, but on another page with nested tabs, it won't make sense for navigating the tabs.

If we go with numbers I'd suggest <kbd>t</kbd> + <kbd>1</kbd>, <kbd>t</kbd> + <kbd>2</kbd> for the main tabs on the page - usually the repo tabs and some other generic letter for the nested tabs.

**Comment by sindresorhus** [comment]
How about `t` `<number>` and `t` `<arrow-left/right>` for the main repo tabs and `p` instead of `t` for the pull request tabs?

**Comment by vanniktech** [comment]
To give this another bump. I'm in favor of p+numbers. I'd be interested in implementing this. Are there any hints for some files where I can look aroud how I'd implement this?

**Comment by hkdobrev** [comment]
@vanniktech 👍 

On the actual implementation, I think the last suggestion from Sindre is the most sensible as it would make sense in more scenarios if we decide to expand it.

> How about `t` `<number>` and `t` `<arrow-left/right>` for the main repo tabs and `p` instead of `t` for the pull request tabs?

**Comment by vanniktech** [comment]
`t` searches die files on the main page. Are we sure we want to use t then?

**Comment by bfred-it** [comment]
This is easy. Someone who interested please send a PR :)

**Comment by stivaugoin** [comment]
Hi, I started to work on this issue but the `t` hotkey open the `Jump to...` menu in the `Files` tab.

![github-pr-tabs](https://user-images.githubusercontent.com/1130466/37372553-76fd5d7a-26e9-11e8-8fd4-a155a3fcff4d.png)

And like @vanniktech said, `t` is used to search files on the main page. I don't think `t` is the best choice. 

Any suggestion?

**Comment by hkdobrev** [comment]
Why not just implement what Sindre suggested earlier, but just on for the PR tabs.

https://github.com/sindresorhus/refined-github/issues/568#issuecomment-337464005

So

- <kbd>p</kbd> <kbd>1</kbd> **Conversation**
- <kbd>p</kbd> <kbd>2</kbd> **Commits**
- <kbd>p</kbd> <kbd>3</kbd> **Files changed**
- <kbd>p</kbd> <kbd>&larr;</kbd> _Previous tab_
- <kbd>p</kbd> <kbd>&rarr;</kbd> _Next tab_

**Comment by philBrown** [comment]
What happened to this? The <kbd>p</kbd> key triggers the _Projects_ selector and the <kbd>g</kbd>+<kbd>[tab number]</kbd> does nothing.

It doesn't seem to be mentioned in https://docs.github.com/en/get-started/using-github/keyboard-shortcuts either
