### ISSUE TITLE
Folder icon svg color 

### ISSUE THREAD

**Issue by ankurk91** [sindresorhus/refined-github#574]
Hi,

After installing this extension in chrome (59), the folder icon color is faded.
Compare
**Before**
![before](https://user-images.githubusercontent.com/6111524/27849345-339797c0-616a-11e7-84d4-854046732825.png)
**After**
![after](https://user-images.githubusercontent.com/6111524/27849351-3b806250-616a-11e7-8891-3116386859cc.png)

Can you restore the color ?

Thanks for your awesome work.

**Comment by hkdobrev** [comment]
Hmm, I didn't know that. Was that on purpose?

**Comment by ankurk91** [comment]
@bfred-it @jdreesen
It would be great if you can let us know the purpose rather than reacting as **thumbs-down**

**Comment by bfred-it** [comment]
I don't see the issue with that being lighter, hence the 👎.

It's so minor there's not much to add, remove, or discuss IMHO.

**Comment by hkdobrev** [comment]
I like the lighter colour as well (and completely fine with the 👎). I'm interested in whether you knew we did this on purpose or was a side effect of some other colour changes.
