### ISSUE TITLE
Minimize/Maximize mouse cursors for PR show in non PR areas

### ISSUE THREAD

**Issue by tdlm** [sindresorhus/refined-github#58]
I was casually using the unpacked extension today and noticed the cursor showing up in file headers that don't belong to the PR. Incidentally, we should probably add the behavior to commit review areas now that I think about it but for now, we can nix this bug until we decide to incorporate that behavior.

**Comment by hkdobrev** [comment]
:+1: for incorporating this in any diffs like commit views and compare views.

**Comment by tdlm** [comment]
@hkdobrev I'll create a new issue for the behavior applying to commit views, etc. That work?

**Comment by hkdobrev** [comment]
@tdlm Well, I'd prefer to just call the `addMinimizeMaximize()` function on commits and compare views as well, instead of fixing the cursors first and then implementing it on the other pages where the cursor is broken. now.
