### ISSUE TITLE
Show delete repo button on visiting a recent pull request

### ISSUE THREAD

**Issue by morajabi** [sindresorhus/refined-github#580]
It's better and cleaner to remove unneeded forks after a closed or merged pull request.

**Comment by bfred-it** [comment]
This?

> Adds a shortcut to quickly delete a forked repo

![](https://cloud.githubusercontent.com/assets/170270/13520281/b2c9335c-e211-11e5-9e36-b0f325166356.png)

It should be in already.

**Comment by morajabi** [comment]
Oh sorry, I didn't notice that.
