### ISSUE TITLE
We're on Product Hunt

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#594]
Help vote us up 👍👍👍👍👍

You can find the submission here:
https://www.producthunt.com/newest
*(You might need to scroll down)*

**Comment by jgierer12** [comment]
We made it to the 3rd most upvoted product 🎉
![Product Hunt graph](https://pbs.twimg.com/media/DESWaJhXoAEnHkY.jpg:large)

**Comment by bfred-it** [comment]
This added more than 200 stars to the repo! It was 1776 stars just 6 days ago.
