### ISSUE TITLE
Created/deleted branch activity shows up as empty space

### ISSUE THREAD

**Issue by kamranahmedse** [sindresorhus/refined-github#597]
![image](https://user-images.githubusercontent.com/4921183/27992110-db0d4ed4-649c-11e7-874c-1baaf8d67125.png)

**Comment by bfred-it** [comment]
Thanks for the report! 

It should be fixed by #555, but I'm not seeing any holes so I don't know if the PR works.

I'm closing this since it's a duplicate of #475
