### ISSUE TITLE
Add support to fold the repository like github in mobile browser.

### ISSUE THREAD

**Issue by Celthi** [sindresorhus/refined-github#598]
Nearly all the large repo have a lot of files, so it will be better to fold these lots of file. In case I  don't convey my thought well. Following it the email I sent to GitHub support, and got a friendly reply to mention   the feature to the github developing team.

> When we open a project in github, such as youtube-dl, is it better to let the website collapse most of the files or folders by default, SO we can see the project description and the readme file at one sight. Because every time when I visit a project, the first thing I'm doing is srolling down to the readme to see what the project exactly do. I guess maybe there are many guys do the same thing. SO I send this feedback, great thank for the github.com.

**Comment by bfred-it** [comment]
I wouldn't mind toggling it on click:

![list toggle](https://user-images.githubusercontent.com/1402241/27993255-075e3aca-64d9-11e7-9af9-62f0a8670427.gif)

It's pretty easy:

```js
select('.commit-tease').addEventListener('click', e => {
       if (e.currentTarget === e.target) {
		const list = select('.files');
		list.hidden = !list.hidden
       }
});
```

**Comment by jgierer12** [comment]
Maybe make it an icon/button instead to stay in line with native folding (on PR files)
![PR files toggle button](https://user-images.githubusercontent.com/4331946/27994358-860cc96c-64bc-11e7-9a6e-9b9f1fc39ead.gif)

**Comment by sindresorhus** [comment]
There's also my [hide-files-on-github](https://github.com/sindresorhus/hide-files-on-github) extension which reduces this problem a little bit.
