### ISSUE TITLE
Prompt user to confirm when writing a comment and hit Cancel

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#60]
See https://github.com/isaacs/github/issues/14

I think GitHub fixed the problem with <kbd>Esc</kbd>, but it still deletes what you've written when you hit  *Cancel* without a confirmation prompt. You might click it accidentally instead of the other button. And I'm sure for heavy users of GitHub, clicking the Cancel button would be a rare occasion, so the prompt won't be an issue.

**Comment by sindresorhus** [comment]
:+1:

**Comment by paulmolluzzo** [comment]
Is there something better to use than a basic JS confirm? Is there a modal or something we can use to make it look like this is built into GitHub?

**Comment by hkdobrev** [comment]
@paulmolluzzo The only confirmation modal which comes to mind is the delete repo confirmation. However it is too much. I like the built-in confirm dialogs for simple things, because you cannot escape them and you can use the keyboard reliably. They are also OS-specific and the users are used to them.

**Comment by sindresorhus** [comment]
I think the built in confirm is fine for this. It's not like you're going to encounter it very often.
