### ISSUE TITLE
"No Whitespace" button label in diffs is broken when enabled

### ISSUE THREAD

**Issue by jdreesen** [sindresorhus/refined-github#602]
When viewing the diffs of a PR the label of the `No Whitespace` button is broken when it's enabled:
![no-whitespace](https://user-images.githubusercontent.com/424602/27997662-b3b2042c-64fd-11e7-9c5d-5411cdedd8f8.png)
The button itself works fine though, only the label seems to be affected.

I'm using Firefox 54.0.1 with Refined GitHub 17.7.8.1317 on Windows 10.

**Comment by bfred-it** [comment]
This was just now fixed by https://github.com/sindresorhus/refined-github/pull/586 :)
