### ISSUE TITLE
Add keyboard shortcuts to navigate the dashboard events

### ISSUE THREAD

**Issue by roccomuso** [sindresorhus/refined-github#614]
It Would be cool to have a shortcut that lets you select the latest entries in the dashboard with the key arrows and easily hit enter to open it, as in the google search results page.

**Comment by arkon** [comment]
Can't you just tab through the page...?

**Comment by roccomuso** [comment]
@arkon seriously? did you try it? You need like 25 tabs to have the focus on the first entry in the feed.

**Comment by arkon** [comment]
@roccomuso It's 4 presses.

1. Tab once to "Skip to content"
2. Press enter
3. Focused on account/org feed picker, press tab again
4. Already on the first item

**Comment by sindresorhus** [comment]
This would be useful. Should use `j`/`k` instead of arrow keys though.

---

*For anyone that wants this, please also send this feature request to GitHub: support@github.com*

**Comment by fregante** [comment]
It's been 3 years and not much interest. I don't think it's worth implementing navigation/styles for a page that's essentially just for fun/discovery.
