### ISSUE TITLE
Sorting labels based on colour and filter replaced by goto

### ISSUE THREAD

**Issue by AndreasBackx** [sindresorhus/refined-github#616]
We are grouping labels by color to indicate that these belong together. Would it not be better to see the choices next to one another per colour?

Here's a comparison for one of our private repos' use of labels:

| Current sorting | Sorting based on color |
| - | - |
| ![Current sorting](https://i.imgur.com/OtNLYdi.png) | ![Sorting based on color](https://i.imgur.com/71taTYG.png) |

I personally think the sorting based on color is more readable. We could start to sort alphabetically and then show the labels with the same color:

- Color red (this is the color of label **A**)
    - **A**
    - K
    - Z
- Color blue (this is the color of label **B**)
    - **B**
    - X
- Color green (this is the color of label **C**)
    - **C**
    - G

This approach makes it easier to find labels that you're searching for because you memorise colours very easily. You'd find yourself scrolling until you see the colour after which you can immediately click on the label you wanted to use because you memorised the colour.

Additionally what I'd like to propose is a replacement of the "Filter labels" field. Because labels are now grouped by colour, you might find yourself wanting to click on a different label with the same colour. So you search for 1 label by name, but currently it hides all of the other results. What I'd do is filter them, but still show the other results. It'd just scroll to the best result(s). If multiple are found, maybe the best one is shown or they're reordered and those are shown at the top.

Example of how I'd imagine it looked:
![Searching labels](https://i.imgur.com/m1jyOrn.png)

**Comment by bfred-it** [comment]
The problem with this is that it assumes everyone groups by color instead of by name. That isn't always the case.

Sorting this list by color would make no sense: https://github.com/babel/babel/labels

<img width="100" alt="screen shot 2017-07-13 at 09 56 23" src="https://user-images.githubusercontent.com/1402241/28147203-8e1742ac-67b1-11e7-98e7-2dcc07757581.png">
