### ISSUE TITLE
Idea: Customizable Issue URL Templates

### ISSUE THREAD

**Issue by mareksuscak** [sindresorhus/refined-github#618]
The idea builds on top of the existing `Linkifies issue references in pull requests` feature. Specifically, most companies I have worked for didn’t use GitHub’s issue tracker but a 3rd party issue tracker instead (Pivotal, Asana, Jira). So I’ve realized it might not be a bad idea to let the user customize the URL template.

I'm happy to contribute this feature if interested.

**Comment by sindresorhus** [comment]
I think that could be useful for some, but not the majority of our users. It would probably be better done as a separate extension.

**Comment by mareksuscak** [comment]
@sindresorhus thanks for clarifying, closing.

**Comment by sindresorhus** [comment]
More than happy to link to such extension in the readme if someone makes it :)
