### ISSUE TITLE
Add a button next to Raw to copy file contents

### ISSUE THREAD

**Issue by stevemao** [sindresorhus/refined-github#62]
I sometimes want to quickly copy everything in a file on GitHub and paste in my text editor.
cmd (ctrl) + A partially works, but it would select everything on the page.

~~Ideally if there was a hotkey to select current highlighted block it would be great. EG: highlight a comment box and select the whole comment, then hit "R" to reply.~~

**Comment by hkdobrev** [comment]
> I sometimes want to quickly copy everything in a file on GitHub and paste in my text editor.
cmd (ctrl) + A partially works, but it would select everything on the page.

I personally use the Raw link and then Select all keyboard shortcut. However we can add a shortcut for the Raw link.

**Comment by paulmolluzzo** [comment]
:+1: on copying from raw. Copying from the styled content usually includes all sorts of line numbers and formatting garbage.

A way to select and quote a comment in a new comment is a great idea. Ideally without a shortcut. Just add include anything selected when you click the "Comment" button.

**Comment by paulmolluzzo** [comment]
Looks like this is done already: https://github.com/blog/1399-quick-quotes

**Comment by sindresorhus** [comment]
:+1:

**Comment by hkdobrev** [comment]
I want to limit this issue to one thing, a useful thing.

Do you think we should add a button (with a hotkey) for _selecting_ or _copying_ file contents?

**Comment by paulmolluzzo** [comment]
:heavy_check_mark: Selecting

**Comment by sindresorhus** [comment]
Why only selecting? When would you ever just select and not copy?

**Comment by paulmolluzzo** [comment]
If it's a hotkey (which you can't see) that copies to the clipboard (which you can't see) then how will you know what you copied? If it selects then you can see what you are going to copy and ctrl-c or escape.

If this is for a button, then copy, but if it's all "hidden" it should have some visual indication mixed in for UX.

**Comment by hkdobrev** [comment]
I think it should be a copy button next to the Raw button.

**Comment by hkdobrev** [comment]
@paulmolluzzo What do you think about my suggestion above?
> I think it should be a copy button next to the Raw button.

You said:
> If this is for a button, then copy

**Comment by paulmolluzzo** [comment]
@hkdobrev yeah, I agree with your suggestion in that context. I go to Raw to copy a lot. :+1:

**Comment by paulmolluzzo** [comment]
Just as examples: .gitignore and licenses and base CSS and yml files are all pretty much raw->copy workflows.
