### ISSUE TITLE
Block WIP PRs from being merged

### ISSUE THREAD

**Issue by kshvmdn** [sindresorhus/refined-github#620]
To prevent accidental merges of incomplete work, I think it'd be cool if the `Merge Pull Request` button were to be disabled while the PR title includes `[WIP]` or `WIP:`.

Another route is to just confirm that they'd like to proceed with the merge, something like, `"This pull request is marked as a work-in-progress, are you sure you'd like to continue?"` (this way the owner can still merge the incomplete work if that's what they want).

[GitLab currently supports the first option.](https://docs.gitlab.com/ce/user/project/merge_requests/work_in_progress_merge_requests.html)

**Comment by bfred-it** [comment]
It exists and it works fairly well, considering it listens to title changes too:
https://chrome.google.com/webstore/detail/do-not-merge-wip-for-gith/nimelepbpejjlbmoobocpfnjhihnpked

**Comment by hkdobrev** [comment]
@bfred-it Thanks for sharing! 🙌

**Comment by hkdobrev** [comment]
I think the other extension is really nice! @kshvmdn Do you think you could use that? If so, could you please create a pull request to add it to the related extensions sections in the readme so more people could find it? Thanks!

**Comment by kshvmdn** [comment]
@bfred-it Cool, thanks for letting me know about this!

@hkdobrev For sure! I'll give a try when I get the chance -- at first glance, it looks somewhat inactive though. 😞

**Comment by tl-adrian-bridgett** [comment]
The other plugin sadly only exists for Chrome - so it would still be useful to have this facility built-in to refined-github.
