### ISSUE TITLE
Merge Pool

### ISSUE THREAD

**Issue by NielEXXCRO** [sindresorhus/refined-github#621]
How long would the button be disabled for and would the user need to have the button in the end product? Couldn't it just be disabled without the button?

**Comment by sindresorhus** [comment]
What are you talking about?

**Comment by NielEXXCRO** [comment]
How long would the Merge Pull Request Button be disabled for? 

https://docs.gitlab.com/ce/user/project/merge_requests/work_in_progress_merge_requests.html

![capture](https://user-images.githubusercontent.com/21984500/28225537-aca49944-6898-11e7-93ae-d278f745787d.JPG)

**Comment by sindresorhus** [comment]
I think you meant to just comment on https://github.com/sindresorhus/refined-github/issues/620 or open this issue on https://github.com/sanemat/do-not-merge-wip-for-github.

**Comment by NielEXXCRO** [comment]
Yeah i was commenting on @kshvmdn post about the wip block
