### ISSUE TITLE
Can't close 'More' Button

### ISSUE THREAD

**Issue by JPeer264** [sindresorhus/refined-github#622]
The `More` button (picture below) cannot be closed after doing following:

- Opening `More` dropdown
- Click `Compare` 
- Go Back

After going back the overlay for the close action is still active, but the JavaScript doesn't trigger the action.
![morebutton](https://user-images.githubusercontent.com/10677263/28245138-04eafa18-6a00-11e7-8d8b-d3dd21e6552b.png)

**Possible solution**
Close the `More` dropdown after clicking on the  `.refined-github-compare-tab`.

**Comment by bfred-it** [comment]
It's just missing the `data-skip-pjax` attribute the other items have. Adding it seems to fix it.
