### ISSUE TITLE
Add diff and patch links on commit pages

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#63]
Many people don't know that, but GitHub offers diff and patch pages for every commit on GitHub. Just append `.diff` or `.patch` to the commit URL.

E.g. for https://github.com/sindresorhus/refined-github/commit/f5544cad792fd62e9ce778b5788b4d602f8d0e72, go to:
- https://github.com/sindresorhus/refined-github/commit/f5544cad792fd62e9ce778b5788b4d602f8d0e72.diff
- https://github.com/sindresorhus/refined-github/commit/f5544cad792fd62e9ce778b5788b4d602f8d0e72.patch

I personally find the patch URLs useful to get the email address which was used configured in Git for that commit. The diffs and patches could also be used to pass to some CLI tools which don't work with Git, but work with these formats which pre-date Git. I think some people not knowing that, but who need the patch, would actually clone the repo to get them, only because they don't know GitHub serves them on the web.

I don't want to type `.patch` every time in the URL when I need this and a link would help me. But it would also help other people to teach them these links exist.

I suggest the position of the links to be on the right of the full commit hash in the commit header.

![github-commit-hash-position](https://cloud.githubusercontent.com/assets/506129/13588134/0a3ef786-e4d6-11e5-8c36-4f0666e2d020.png)

**Comment by paulmolluzzo** [comment]
:+1: but I have a question: If there's a link on the right, you just want it to say "patch" and "diff" and be a link? Is there some icon we can use that looks nice and makes sense?

**Comment by hkdobrev** [comment]
@paulmolluzzo Well, the only icon I've seen somewhere for diffs/patches was a stylised `+/-` sign, because of the `+` and `-` signs used in the formats. However I don't see that working here. I've also seen `[PATCH]` as this is used in the email subjects for applying patches and people who use them have learnt to recognize it.

In conclusion I've thought of that, but haven't found a very satisfiable answer either.

**Comment by paulmolluzzo** [comment]
I think just putting a link like [.patch] and [.diff] could work.

**Comment by hkdobrev** [comment]
> I think just putting a link like [.patch] and [.diff] could work.

:ok_hand:

**Comment by sindresorhus** [comment]
:+1:
