### ISSUE TITLE
Trending Menu Item from the Main Navigation header is missing

### ISSUE THREAD

**Issue by Alexandre-Nourissier** [sindresorhus/refined-github#638]
I noticed this morning that the Trending Menu Item disappeared.
After inspection, the selector need to be changed  from  
<pre>'.header-nav.left .header-nav-item:nth-child(2)'</pre>
to
<pre> '.header[role="banner"] ul[role="navigation"] li:nth-child(3)'</pre>

**Comment by bfred-it** [comment]
If this change is necessary and correct, we need to review any other possible similar selectors we have.
