### ISSUE TITLE
"Your Issues" filter is not replaced by other issue filters

### ISSUE THREAD

**Issue by JustinLivi** [sindresorhus/refined-github#641]
It's possible that this is the intended behavior, but as an end user I found it surprising and seems inconsistent with the behavior of the default GitHub UI.

# Test

1. Click any of the default GitHub Issues filter tabs
![state1](https://user-images.githubusercontent.com/2466999/28585136-4c053c3a-713d-11e7-92c6-afdbfd6c5a29.png)
2. Click "Yours" tab
![state2](https://user-images.githubusercontent.com/2466999/28585156-5b2c3cb8-713d-11e7-9cff-8667d396833a.png)
3. Click any of the default GitHub Issues filter tabs again
![state3](https://user-images.githubusercontent.com/2466999/28585176-6aba1466-713d-11e7-9133-7c297470841a.png)

# Result

The filters field retains the `user` filter and appends the `author`, `assignee`, or `mentions` filter.

# Expected

The filters field should not retain the `user` filter. Using the above example, the issues flags should be `is:open is:issue mentions:JustinLivi` as opposed to `is:open is:issue user:JustinLivi mentions:JustinLivi`.

When switching between the Created, Assigned, and Mentioned tabs the previous filter is replaced. Based on the placement of the Yours tab I would expect the functionality to be identical. Additionally, when selecting the Yours tab, the `author`, `assignee`, and `mentions` are stripped.

So this is actually a bug and not a feature right?

**Comment by bfred-it** [comment]
This is a GitHub feature that's not what we want. The feature is: preserve existing search terms across tabs. For example in this case `is:closed` is automatically added to all tabs: https://github.com/issues?q=is%3Aclosed+mentions%3Abfred-it

`user:***` is part of our tab so it should not be preserved.
