### ISSUE TITLE
Disable functionality temporarily

### ISSUE THREAD

**Issue by janpio** [sindresorhus/refined-github#646]
I love the extension, but sometimes it would be great to being able to disable it temporarily by clicking on the extension icon, selecting "Disable" and reload the Github page I am currently on (especially as I am not aware of all the functionality and sometimes want to just check what the page would look like without the extension).

**Comment by bfred-it** [comment]
I don't see this happening. I suggest using something like https://github.com/HangYang/one-click-extensions-manager

[![](https://github.com/HangYang/one-click-extensions-manager/raw/master/screencast.gif)](https://github.com/HangYang/one-click-extensions-manager)

**Comment by janpio** [comment]
Fair enough.
