### ISSUE TITLE
Userscript version

### ISSUE THREAD

**Issue by vpontin** [sindresorhus/refined-github#654]
I love this script, so i want to request if you can make a userscrpt version of this, for use in other browsers (even Edge using tampermonkey).

Is this possible?

**Comment by bfred-it** [comment]
I've seen this request a few times on various extensions. Safari compatibility would be a plus. The problems are generally API incompatibility, no content/background script separation, autodeployment and support. 

Someone could look into a compatibility layer for `chrome.*` and `browser.*` APIs (e.g. a wrapper for webext-polyfill) and then we can see if it can be added to the project with little effort.

**Comment by sindresorhus** [comment]
I don't see us ever taking on that kind of burden. Even with a good compatibility layer, it will have limitations and bugs, and it adds testing overhead. I'm going to close this, but we'd be happy to link to a port or user script version of Refined GitHub if anyone decides to make and maintain that.
