### ISSUE TITLE
Subset files tab wrapping into new line

### ISSUE THREAD

**Issue by DerTieran** [sindresorhus/refined-github#655]
Having many additions / deletions cause the `.subset-files-tab` to wrap.

With Redefined Github enabled:
![Redefined](https://user-images.githubusercontent.com/9264728/28862495-8c8280a0-7765-11e7-890c-4c80b8f2b206.png)

With Redefined Github disabled:
![Default](https://user-images.githubusercontent.com/9264728/28862500-8f8cc3fa-7765-11e7-97fb-f38a5220dee0.png)

**Comment by bfred-it** [comment]
Perhaps we can half the space around No Whitespace and/or reduce the font size of the blue label (like GitHub already did in the second screenshot)

**Comment by bfred-it** [comment]
Can you post a link to that PR?

**Comment by DerTieran** [comment]
Not to that specific PR, but I can try to recreate.
But I haven't seen the `No Whitespace` button lately, is it gone or what changes are needed for to appear?

**Comment by tanmayrajani** [comment]
@DerTieran you might need to update your extension. I remember some DOM changes by GitHub regarding marketplace link breaking almost all the features of the extension few days ago. That have been fixed lately so see if updating it makes the no whitespace reappear.

**Comment by DerTieran** [comment]
@tanmayrajani Oh yea it is back again thanks.

@bfred-it I made a quick script that generates some changes.
See https://github.com/DerTieran/laughing-octo-adventure/pull/1/files/344b3e6f6c96f2074ac265753d021d200a3218b2..46be8e3e7ff93944d666ca13ebb0eea717b0090a

Let me know if you need even more additions/deletions didn't realise I was this close to 10,000 😄

**Comment by bfred-it** [comment]
Still looking good on Chrome/macOSX 10.11

**Comment by DerTieran** [comment]
Do we have different container width's (for me `980px`)?
![image](https://user-images.githubusercontent.com/9264728/29870752-6301df2a-8d89-11e7-96e7-64fda2663a07.png)

**Comment by bfred-it** [comment]
You're right, I forgot that GitHub is partially flexible. I'm seeing it now.

**Comment by bfred-it** [comment]
I'd suggest to drop `Changes from` on the left:

# From

<img width="721" alt="screen shot 2017-08-30 at 18 50 04" src="https://user-images.githubusercontent.com/1402241/29870943-21d995c6-8db4-11e7-9b5c-dd580ad256b5.png">

# To

<img width="727" alt="screen shot 2017-08-30 at 18 50 10" src="https://user-images.githubusercontent.com/1402241/29870944-21da9b6a-8db4-11e7-8261-e3fa632eac0b.png">
