### ISSUE TITLE
Full name display breaks on comments edited by someone else

### ISSUE THREAD

**Issue by durka** [sindresorhus/refined-github#656]
See for example [this comment](https://github.com/rust-lang/rust/issues/31681#issuecomment-222826343):

![screenshot](http://www.seas.upenn.edu/~aburka/tmp/Screen%20Shot%202017-08-05%20at%208.30.37%20PM.png)

It displays the editor's name, but not the author's, and the dash is out of place.

**Comment by bfred-it** [comment]
- The dash is not in our code, it might have been part of the name.
- The line break is necessary if it doesn't fit (however I'm not seeing it)

<img width="632" alt="screen shot 2017-08-24 at 18 42 46" src="https://user-images.githubusercontent.com/1402241/29664953-15177ab8-88fc-11e7-958c-bb8feef2c363.png">

**Comment by durka** [comment]
Strange. OK it must be in my user style or something.

**Comment by durka** [comment]
@bfred-it anyway, it still doesn't show the full name of the comment author.

**Comment by bfred-it** [comment]
I noticed you somehow have an old version. We removed `commented` and that `-` months ago https://github.com/sindresorhus/refined-github/pull/488

That user doesn't have a full name set: https://github.com/eefriedman

**Comment by durka** [comment]
Oh OK, I will update.

**Comment by bfred-it** [comment]
How come it didn't update? What browser are you using? Is the extension a fork?

**Comment by durka** [comment]
It was my fault. I had the extension installed from a fork because I submitted a PR a while back.

**Comment by bfred-it** [comment]
No worries, it happens :)

**Comment by durka** [comment]
Yes, and I was quite confused when I reinstalled from the official store and nothing happened at all due to #675. But it's all working now :)
