### ISSUE TITLE
Add dropdown to quickly switch between repositories

### ISSUE THREAD

**Issue by nMustaki** [sindresorhus/refined-github#657]
Hi,

first thanks for all your work !
I came across this extension because I am switching between our private org repositories multiple times a day, and I am dreaming of a toggle near the repository name to easily select the one I need.

Do you think it could be done ?

Regards,
Nathan

**Comment by bfred-it** [comment]
I don't think this should be part of RGH, you can already switch between frequently used repos by using the browser's search bar or this search optimizer: https://github.algolia.com/

Many people have dozens of repos, this would need search and that already exists.

**Comment by nMustaki** [comment]
I didn't know that, thanks for the explanation !
