### ISSUE TITLE
Add option to hide translation commits

### ISSUE THREAD

**Issue by benwaffle** [sindresorhus/refined-github#658]
<img width="668" alt="screen shot 2017-08-07 at 5 30 49 pm" src="https://user-images.githubusercontent.com/1713819/29046596-2f60850e-7b96-11e7-818e-d373297d8a7b.png">

I'd like to hide `Update [lang] translation` commits. Although, identifying every translation commit sounds hard. Perhaps just allowing users to add a regex filter?

**Comment by sindresorhus** [comment]
This would be hard to do automatically as different projects have different commit message conventions. We could have an option to supply a regex, but not sure it's worth having an option for this.
