### ISSUE TITLE
Maintain whitespace option on next/previous in review mode.

### ISSUE THREAD

**Issue by abernix** [sindresorhus/refined-github#660]
I'm curious if you'd review a pull request which would allow the preservation of the "whitespace" option (if it's enabled) when navigating individual commits using the "Next" and "Previous" buttons (`n` and `p` shortcuts) in review mode.  Presently, when using the "No whitespace" (`w=1`) option, it has to be re-enabled on each additional commit.

**Comment by sindresorhus** [comment]
👍 Makes sense.
