### ISSUE TITLE
Tellmewhenitcloses.com support

### ISSUE THREAD

**Issue by passcod** [sindresorhus/refined-github#662]
Would it be interesting to have a button to add to https://tellmewhenitcloses.com/ below the "Subscribe" button on issues/PRs?

I'm willing to try to implement.

**Comment by bfred-it** [comment]
Interesting. I think this makes sense as a special extension just for that, featured on their site, for their own good.

**Comment by sindresorhus** [comment]
I also think this should be a separate extension. We would be more than happy to link to it in the readme if someone makes it. If you don't want to make it, you could request someone to make it here: https://github.com/sindresorhus/module-requests/issues

**Comment by bfred-it** [comment]
I've been using this service since this issue, I very much prefer it to "Subscribe" pretty often. I'd like to still add it to RGH but it looks like they use an authenticity token so we can't just `POST` to it. I'll have to stick to the two-click bookmarklet.

**Comment by denolfe** [comment]
For anyone interested, I created a script that adds an additional button to the notifications sidebar that will pop open Tell Me When It Closes with the link pre-populated. It is loaded with TamperMonkey/VoilentMonkey. https://github.com/denolfe/dotfiles/blob/master/chrome/github-tellmewhenitcloses.js
