### ISSUE TITLE
Scroll to top of file header after collapse in PR review

### ISSUE THREAD

**Issue by bradzacher** [sindresorhus/refined-github#665]
With the floating file header that helpfully hovers over a file, it's easy to close a file after you're done reviewing it.

However if you do that (esp with really long files), you can often end up several files out of place.
It would be great if collapsing a file via the floating header would auto-scroll to top of the file, so that you can start reviewing the next file without searching for it it.

**Comment by sindresorhus** [comment]
@bradzacher Would you be interested in doing a pull request?

**Comment by bradzacher** [comment]
i can certainly have a look into

**Comment by tanmayrajani** [comment]
I think it's happening right now. I am not sure if that's what you are looking for but currently once a file gets collapsed, it goes to next one directly for me. I have [sample PR here](https://github.com/tanmayishisys/testrepo/pull/2/files) with long file(s) to check

**Comment by bradzacher** [comment]
This was actioned via https://github.com/sindresorhus/refined-github/pull/748

**Comment by hkdobrev** [comment]
Thanks @bradzacher!
