### ISSUE TITLE
Mention github-custom-tab-size in readme

### ISSUE THREAD

**Issue by lukechilds** [sindresorhus/refined-github#667]
Just started using Refined GitHub and I'm absolutely loving it! However I was sad when I realised it sets the default tab size to 4 (I like 2) and there's no way to change this.

I have my own extension to set a custom size but Refined GitHub was overwriting it. I've just updated my extension to be compatible with Refined GitHub.

I was wondering if there's any chance you wanted to give my extension a mention in the readme as there may be other people who love Refined GitHub but aren't keen on the default tab width. I was thinking maybe in the "Community tweaks" or "Customization" sections?

Here it is: https://github.com/lukechilds/github-custom-tab-size

It lets you choose your own tab width with a live preview and your setting is synced across all Chrome browsers you're logged into.

Demo:

![Demo](https://i.imgur.com/Y3Rf9SF.gif)

**Comment by hkdobrev** [comment]
Please make a PR for the readme section mentioning related extensions! Thanks!

**Comment by lukechilds** [comment]
Oops, missed that section. Done 🎉
