### ISSUE TITLE
[Enhancement] Dark Mode

### ISSUE THREAD

**Issue by ItsPugle** [sindresorhus/refined-github#669]
It'd be really good if there was an option for Refined GItHub to include a dark mode.

**Comment by bfred-it** [comment]
This would be best as a separate Userstyle/Userscript and you can probably find one already

**Comment by ItsPugle** [comment]
Just because we can find other ones, why wouldn't you add it to here?
If you have people with a desire to use a product, and you have that product, then people use your product. i.e. If you add this, it means that people who don't want to install `Stylish` can just install this.

**Comment by bfred-it** [comment]
Refined GitHub doesn't have to be everything for everyone.

Keeping a dark mode up to date for the whole site is not gonna be easy work and it will easily become out of date. It's easier to just build it as a separate extension so once the maintainer loses interest, another one pops up.

I've seen this all the time for Facebook and YouTube: No one wants to put that much work for too long.

**Comment by sindresorhus** [comment]
https://github.com/StylishThemes/GitHub-Dark
