### ISSUE TITLE
Wrong URL for GitHub Enterprise environments

### ISSUE THREAD

**Issue by cH40z-Lord** [sindresorhus/refined-github#671]
I was reviewing a Pull Request on our local GitHub Enterprise Installation which was referencing another PR in its title. Luckily Refined GitHub adds a link around that, sadly it was pointing to `github.com` instead of the GitHub Enterprise URL.

I haven't had the time to check for other sources where this might happen but I'm pretty sure this isn't the only case where it has the wrong URL.

**Comment by bfred-it** [comment]
Due to: https://github.com/sindresorhus/linkify-issues/blob/f04221a/index.js#L47

To fix it, pass `''` as the `baseUrl` option.

**Comment by bfred-it** [comment]
@cH40z-Lord can you try #685?
