### ISSUE TITLE
Keyboard shortcut conflicts: Control-Shift-U

### ISSUE THREAD

**Issue by grahamperrin** [sindresorhus/refined-github#673]
Normally, with KDE Plasma 5 on FreeBSD (probably also on Linux), key chords <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> and <kbd>Shift</kbd>-<kbd>Control</kbd>-<kbd>U</kbd> can be used for Unicode character composition. For example:

<kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> <kbd>2</kbd> <kbd>0</kbd> <kbd>2</kbd> <kbd>6</kbd> <kbd>Spacebar</kbd> = …

– the ellipsis character. 

When _Refined GitHub_ is enabled, <kbd>Control</kbd>-<kbd>Shift</kbd>-<kbd>U</kbd> and <kbd>Shift</kbd>-<kbd>Control</kbd>-<kbd>U</kbd> seem to be misinterpreted as prompts to present a _File Upload_ dialogue.

**Comment by bfred-it** [comment]
If you're willing to sacrifice the Upload button and just rely on drag-drop, you can now disable it+shortcut in the options. Add `upload-button` to the [Disabled features.](https://github.com/sindresorhus/refined-github/pull/877)
