### ISSUE TITLE
Categorize starred projects

### ISSUE THREAD

**Issue by techvoltage** [sindresorhus/refined-github#674]
Hi,
Is it currently possible to add a feature to categorize the starred projects according to custom topics?
Example, I can create a topic called AI and add all the starred projects that belong to the field of AI to the topic.

**Comment by bfred-it** [comment]
This should be a separate extension.

**Comment by sindresorhus** [comment]
I agree. You can request a separate extension for this at https://github.com/sindresorhus/module-requests
