### ISSUE TITLE
Explore link has been moved

### ISSUE THREAD

**Issue by LeoColomb** [sindresorhus/refined-github#675]
* In the function `moveMarketplaceLinkToProfileDropdown()`, a "Explore" link in the drobdown is wanted.

https://github.com/sindresorhus/refined-github/blob/04f3763c3d41dc3687d7d6c11a5b3b2d87cded3d/src/content.js#L109-L113

* But this link is not anymore in the dropdown, and has been moved to the navbar.

![image](https://user-images.githubusercontent.com/846943/29607299-14fc39a8-87f1-11e7-82b1-d22ba64f3f96.png)

* Then an error is raised in the console.

```
chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/content.js:650 Uncaught (in promise) TypeError: Cannot read property 'insertAdjacentElement' of null
    at moveMarketplaceLinkToProfileDropdown (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/content.js:650)
    at onDomReady (chrome-extension://hlepfoohegkhhmjieoechaddaejaokhf/content.js:843)
    at <anonymous>
```

---
The side note is that following js tweaks are not processed…

**Comment by bfred-it** [comment]
Thanks for the report! Can you send a PR to fix this?

**Comment by LeoColomb** [comment]
@

**Comment by LeoColomb** [comment]
I would love to, but it depends on how you want to manage this change:
* Simply remove the function?
* Add the link after another item? (but which one?)

**Comment by sindresorhus** [comment]
I've been mostly AFK for awhile, so I didn't see this. I've now disabled this feature to make Refined GitHub work again until we can fix it for real. [And done a new release.](https://travis-ci.org/sindresorhus/refined-github/builds/267850465)

**Comment by sindresorhus** [comment]
@LeoColomb Should be placed after "Your Gists" with a divider between. Like this:

<img width="234" alt="screen shot 2017-08-24 at 12 45 10" src="https://user-images.githubusercontent.com/170270/29651270-28ace978-88ca-11e7-9446-16dc91efd514.png">
