### ISSUE TITLE
Make features more resilient to failure

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#678]
In https://github.com/sindresorhus/refined-github/issues/675, one tiny feature broke and took down all of RG. Would be nice if we could somehow compartmentalize each feature, so if one feature broke, only that feature would be broken.

**Comment by bfred-it** [comment]
Possible easy solutions:
- Adding `async` to functions
- Convert `init`+`domready` to some sort of launcher, e.g. `run([fnA, fnB, fnC])`

The first one is easy, but can be forgotten (i.e. new features are added without `async`).

The second one needs a bit more work, but you can't escape it.

**Comment by sindresorhus** [comment]
`2.` 👍
