### ISSUE TITLE
Releases Tab gone?

### ISSUE THREAD

**Issue by IzzySoft** [sindresorhus/refined-github#686]
Is it just me, or did something break? For a few days, the "Releases" tab doesn't show up anymore for any repo (including this) on all of my machines (Linux at home, Windows at work, 1 at ff54, 2 at ff55). In the latter place on Windows, it's version 17.8.22.1346 (and seems to have updated today) – if it helps, I can check my other machines later when I've returned home.

**Comment by hkdobrev** [comment]
@IzzySoft Could you please try to go to `chrome://extensions` and press "Update extensions now" button and see if that fixes it for you? Thanks!

**Comment by jdreesen** [comment]
17.8.22.1346 (previous release on MDN) is broken, and mozilla was a bit slow approving new releases lately, but luckily already approved today's release 17.8.29.1352 which works for me (using FF55). Updating the addon should fix it.

**Comment by IzzySoft** [comment]
Firefox 55.0.2 here on Linux. Let's see: `chrome://extensions` starts a Google search for that expression (sounds logical on Firefox). `about:addons` shows 17.8.29.1352 being available. Updated. Oh! Yes!!! That brought the "Releases" tab back, thanks! Will check on the Windows machine (FF55) tomorrow as well and report back. One of my Linux machines is still on FF54 and cannot be updated before next week – but if these two machines with FF55 have it fixed, I'm confident the other will have it as well after the update.

Thanks a lot! That was fast!

**Comment by hkdobrev** [comment]
Cheers!

**Comment by IzzySoft** [comment]
Yeah! Thanks again – and as promised, feedback from the "dark side": tab is back on FF55/Win7 as well, as expected. :clinking_glasses:
