### ISSUE TITLE
The projects tab disappears when using Refined Github

### ISSUE THREAD

**Issue by anvil008** [sindresorhus/refined-github#687]
The projects tab (kanban board) is not visible in Refined Github. 

Referring to this -
![chrome_2017-09-01_11-41-17](https://user-images.githubusercontent.com/5589732/29962135-acfa301e-8f0a-11e7-840a-d258c034d8e5.jpg)

**Comment by hkdobrev** [comment]
@anvil008 This is intentional. It is removed when there are no projects. There is a link in the settings to add one. See #596 and #560.
