### ISSUE TITLE
Go to profile keyboard shortcut

### ISSUE THREAD

**Issue by palashmon** [sindresorhus/refined-github#688]
Thanks so much for this browser extension!

Do we have any keyboard shortcut to go to my profile page from dashboard?
Currently, if we try <kbd>g</kbd> <kbd>p</kbd> hotkey, it take us to Pull Request.

It would be nice if we have some keyboard shortcut to go to the profile page.

Regards!

**Comment by sindresorhus** [comment]
Any suggestion on what keyboard shortcut to use?

**Comment by palashmon** [comment]
@sindresorhus Wow! I can believe the legend himself is replying to me. Truly inspired my your inspirational journey. Simply out of the box. :unicorn:

Regarding this FR, I am not sure where to start in the first place as I have never worked in developing any browser extension before. 

For keyboard shortcut, I think we can use <kbd>g</kbd> <kbd>r</kbd>, as we can also see our pinned (r)epositories in the profile page.

**Comment by sindresorhus** [comment]
We already use `g` `r` to go to the Releases tab. Maybe `g` `pf`.

We have a very good setup for Refined GitHub. So it's easy to work with. Just clone the repo, `npm install`, and run `npm run watch`. Then go to the Extensions page in Chrome, check "Developer mode", load the extension. Then do your changes, and click Reload to see the changes in the extension.

**Comment by yakov116** [comment]
@sindresorhus I also find the I need to do npm update too. Am I missing somthing?

**Comment by sindresorhus** [comment]
@yakov116 That should not be needed. Make sure you're on the latest `npm` version though.

**Comment by CrowderSoup** [comment]
Where are the current keyboard shortcuts implemented?

**Comment by bfred-it** [comment]
They're implemented directly on the buttons and links with the attribute `data-hotkey`

For example, this is the Notifications link:

<img width="333" alt="notifications hotkey" src="https://user-images.githubusercontent.com/1402241/31807184-4a7e4b2a-b532-11e7-8679-29f676fc7f61.png">

**Comment by CrowderSoup** [comment]
@bfred-it Thanks! I hadn't seen this before. I'm going to take a stab at this.
