### ISSUE TITLE
Tooltips in a PR are hidden under the section above it 

### ISSUE THREAD

**Issue by tanmayrajani** [sindresorhus/refined-github#689]
In a PR, tooltips shown while hovering over "view" or the edit icon are hidden under the section above it. Note that the tooltips are visible normally without the extension.
  
![hover-pr-github](https://user-images.githubusercontent.com/8295888/30000484-9674298a-908b-11e7-98b5-001a43630bf4.png)

**Comment by sindresorhus** [comment]
We should just remove that tooltip. It's not useful for power users.

**Comment by tanmayrajani** [comment]
Also, we should hide the edit icon when disabled (i.e. user doesn't have permission to edit). I think we do the same for projects tab when 0 projects.

**Comment by bfred-it** [comment]
The disabled icon makes sense though, it shows that it should be there and reminds you to switch to a branch.

**Comment by bfred-it** [comment]
#719 broke other things. Reopening.

If JS is required to solve this, we might as well just change the direction of the tooltips to show below. `s/tooltipped-n/tooltipped-s/`
