### ISSUE TITLE
Subtle shift when hovering on "Create new file" button

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#693]
![nimbus-record-video-2017-09-11-22-22-33](https://user-images.githubusercontent.com/10110245/30309411-192b69e6-9740-11e7-83e7-6da23c48c82a.gif)

**Comment by bfred-it** [comment]
We have two possible solutions:

- https://github.com/sindresorhus/refined-github/commit/644ad6efece7e4f61298a4744ffdf44f5f01a787
- https://github.com/sindresorhus/refined-github/commit/a0163f57f9613192e4b46ec3b98630931bb7df6a

**Comment by ifvictr** [comment]
The first one works -- it solves the problem of the minor shift on hover _and_ the `Find file` button being hidden in repositories with the name `upload` (case-sensitive).

![2017-09-24_09-23-57-249](https://user-images.githubusercontent.com/10110245/30784456-2ec00c52-a10a-11e7-8535-0b1f31cf0300.png)

The second one will also work, but only on the `master` branch.

**Comment by ifvictr** [comment]
@bfred-it Any update on this?

**Comment by bfred-it** [comment]
I'd have to ask @sindresorhus if he wants to restore the button. I think _The Right Way™_ would be to remove it via JS so we don't have to hack around CSS first/last selectors. PRs welcome for that.

**Comment by sindresorhus** [comment]
> I'd have to ask @sindresorhus if he wants to restore the button.

I don't

**Comment by hkdobrev** [comment]
👍 on JS removal

**Comment by sindresorhus** [comment]
@ifvictr Would you be interested in doing a pull request?

**Comment by ifvictr** [comment]
@sindresorhus Yeah, I'd love take this on.

**Comment by ifvictr** [comment]
@sindresorhus Would love to, but I've never really done something like this before. Could you tell me where I'd put the logic for this? Thanks!

**Comment by ShalokShalom** [comment]
Give me at least an option to restore the upload button. You can design it a bit leaner, there is no reason for this whole text:  ![screenshot_20180414_190158](https://user-images.githubusercontent.com/6344099/38770743-e72110c8-4017-11e8-85a9-16677c0a31ba.png)

So, something like a simple upload button which shows an icon?
