### ISSUE TITLE
Auto-linking is not correctly applied to links in diffs

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/refined-github#695]
Ref: https://github.com/Homebrew/homebrew-core/pull/18015/files

```
 url "https://github.com/mholt/caddy/archive/v0.10.9.tar.gz"
```

**Comment by arungalva** [comment]
I think it isn't picking up anything after "10." because the whole url isn't in the same element. since you edited part of the url, GitHub adds the 'x' class to it giving it the green background colour to show code addition

The same link is working in the original file [here](https://github.com/ilovezfs/homebrew-core/blob/e85f2ade7d45b919b398ab4459e704072926517b/Formula/caddy.rb)

Here is how the css looks like on original GitHub when you change something in the url
```
<span class="pl-s">
    <span class="pl-pds">"</span>
    https://github.com/mholt/caddy/archive/v0.10.
    <span class="x x-first x-last">9</span>
    .tar.gz<span class="pl-pds">"</span>
</span>
```

If the Url isn't changed, this is the css that is rendered
```
<span class="pl-s">
    <span class="pl-pds">"</span>
    https://caddyserver.com/
    <span class="pl-pds">"</span>
</span>
```

**Comment by OmgImAlexis** [comment]
This may be related to this and #703.

[This](https://github.com/agenda/human-interval/commit/0f5567bacf9609adb28b7df44e609ade0e15075f) is from the screenshot yet if you look at the file [here](https://github.com/agenda/human-interval/blob/0f5567bacf9609adb28b7df44e609ade0e15075f/package.json) the slash is missing where it changed `github.com` into a link.

![screen shot 2017-10-29 at 11 14 33 am](https://user-images.githubusercontent.com/6525926/32139755-6843c044-bc9a-11e7-8f14-4267fb2164c7.png)

**Comment by bfred-it** [comment]
Yeah it’s not about the characters but about the diff. The color change breaks the url in multiple `textNodes`. #103 already takes this into consideration.

**Comment by bfred-it** [comment]
Thinking out loud. Discarding tags while parsing the URLs and preserving them in the output is a pain, especially if they need to be split (e.g. half linked, half not linked)

So here's a possible solution, drawn. This shows the old, full-line parsing, by pushing a flat `textContent` to `linkify-urls`, therefore initially discarding all extra elements in the line.

Legend:
* ` ` (spaces) are irrelevant characters
* `-` is a URL
* `#` is an element in the URL, like a `<span class="x">` for diffs
* `A` is a linked URL, like `<a href="----------">`

```
Input, text with `span`:
       --####----

Output, text with `a` but not `span`:
       AAAAAAAAAA
```

How do we merge the two?

Character data has not been changed, so it can _somehow_ zipped together.

The question now is: how do we zip them? Char-by-char comparison to find boundaries and then select+extract the tags with `Range`?

**Comment by wearhere** [comment]
Related problem: https://github.com/sindresorhus/refined-github/issues/1499

**Comment by bfred-it** [comment]
:tada: https://github.com/sindresorhus/refined-github/pull/2066
