### ISSUE TITLE
'right-to-left override' unicode character in full name reverses timestamp

### ISSUE THREAD

**Issue by equinox** [sindresorhus/refined-github#698]
If you have the unicode character for '[right-to-left override](http://www.fileformat.info/info/unicode/char/202e/index.htm)' in your profile name, it gets rendered and thus makes the timestamp of the comment read right-to-left, as shown below:

![](https://i.imgur.com/yDDYyyc.png)

**Comment by bfred-it** [comment]
Confirmed: https://github.com/FortAwesome/Font-Awesome/issues/2465

**Comment by bfred-it** [comment]
We can also avoid HTML/JSX and just stick the opposite character, always, after the name
