### ISSUE TITLE
Add list of voters to vote counter

### ISSUE THREAD

**Issue by paulmolluzzo** [sindresorhus/refined-github#70]
Now that there is that simple vote count, it'd be nice to be able to see who voted in a simple way. (In particular I want to see if the owner or regular contributors voted yes or no.) My first thought is to see a list of usernames when hovering, but maybe there's a better idea? Would it be cool to have a "block" of user avatars in each section like GitHub participants?

![gh-participants](https://cloud.githubusercontent.com/assets/737065/13658114/399f1e62-e642-11e5-8dc2-55313b7f46e9.png)

**Comment by sindresorhus** [comment]
:+1:

**Comment by SpaceK33z** [comment]
Yeah I think we should make it work exactly like the participants part.
