### ISSUE TITLE
Ability to change repo descripton and edit topics in empty repo

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#700]
I find it a bit annoying that I have to delete a repo and create it again when I make a typo during creation. Would it be possible to add the "Edit (description)" and "Manage topics" functionalities to the empty repo? Thanks!

**Comment by bfred-it** [comment]
I don't think that's accurate. Description and topics can always be changed. What are the steps to make the buttons disappear exactly?

**Comment by ifvictr** [comment]
@bfred-it No, this is a feature request. Currently, when you create an empty repo, GitHub shows you the "Quick setup" page, which is void of the buttons to edit the description or change the topics. The buttons only show in populated repositories.

**Comment by sindresorhus** [comment]
@ifvictr So just populate the repo then? I don't see why you need to change it before populating the repo?

**Comment by bfred-it** [comment]
Mostly the issue with this is that the implementation is not trivial. We'd need to either `fetch` the form from another repo you can edit or recreate it via API (lotsa work)

**Comment by sindresorhus** [comment]
Yes, too much work for very little gain. Passing on this suggestion.
