### ISSUE TITLE
Add "open all in tabs" button for Github notifications

### ISSUE THREAD

**Issue by gibfahn** [sindresorhus/refined-github#701]
This is something I use all the time, and if it's useful for others, it might be worth incorporating into Refined Github.

I ended up [implementing it myself](https://github.com/gibfahn/gnt) (partly just to learn webextensions), so I'd be happy to try and incorporate it into this extension if this is something that might be wanted.

![image](https://user-images.githubusercontent.com/15943089/30744845-d0d0f652-9f9b-11e7-9db0-d47386bb5338.png)

**Comment by gibfahn** [comment]
To clarify, this only opens the currently visible notifications as tabs, trying to open 481 tabs at once is probably too much to ask of any browser.

**Comment by bfred-it** [comment]
That’s not a terrible idea. As far as I know there are only ever up to 50 notifications on screen

**Comment by sindresorhus** [comment]
I would use this.

**Comment by hkdobrev** [comment]
What do you think of moving the button to each repo header next to the ✅ icon for marking as read? I think this is more sensible rather than selecting the visible notifications.

**Comment by gibfahn** [comment]
@hkdobrev I'd rather keep it as is, I often end up with five or six repos, each of which have three or four notifications. Being able to open them all at once is really useful.

If you only want to open notifications from a specific repo, you can just select it from the list on the left and then click `Open all in tabs` there:

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/15943089/30785822-bf33e34e-a164-11e7-8496-9a1e0e7fe65e.png">

Having it this way allows you to do both, what you're suggesting makes it impossible to easily open a whole page of commits as tabs.

**Comment by bfred-it** [comment]
Why not both? That’s what GitHub does with “Mark all as read” 😜

**Comment by kevva** [comment]
This feature would be super useful!

**Comment by tanmayrajani** [comment]
I worked on this feature. Here's the [diff](https://github.com/sindresorhus/refined-github/compare/master...tanmayrajani:master). 

Few things to ask:
- I haven't used `browser.tabs` here. Should I do so or `window.open` is fine?
- Should there be a confirm popup since it can potentially open 50 tabs? 
- Should this be just an icon (with tooltip maybe?) instead of the button with text?
- Should the notifications page be refreshed (or just the content) once the all notifications are opened?

**Comment by bfred-it** [comment]
- I think window.open triggers the popup blocker and the user has to whitelist github.com but I may be wrong
- I think the confirmation is pretty standard, for example when trying to open all bookmarks in a folder in Chrome. Perhaps it should appear above 10-15 tabs
- I vote for text. 
- “Mark all as read” doesn’t, so it’s best it doesn’t either for consistency

**Comment by gibfahn** [comment]
- I found `browser.tabs.create({url}))` a lot faster, and it also always creates tabs (window.open sometimes opened new windows for me depending on the browser).
- Maybe a one-off confirmation might be helpful, but when going through 1000 Github notifications adding an extra click every time is going to be painful.
- If you can find an icon that obviously means "Open all in tabs" then I guess that would work (but I can't think of one). As suggested above, using `Open all in tabs` next to the `Mark as Read` button, and then an icon next to the `✓` mark (for just opening tabs from a specific repo) might make sense.
- I had it auto-refreshing originally, but ended up finding it annoying. Having the set of tabs you just opened there is helpful, you often want to go back to one.

**Comment by bfred-it** [comment]
@givfahn what do you mean by “one-off confirmation”? One prompt for the extension’s lifetime? Kinda defeats the purpose

**Comment by gibfahn** [comment]
>@gibfahn what do you mean by “one-off confirmation”? One prompt for the extension’s lifetime? Kinda defeats the purpose

I guess the question is why you'd want a prompt. If you know what the button does you don't need to be prompted (and being prompted every time will get annoying quickly). So AIUI the point of a prompt is for people who just downloaded the extension and don't know what the button does, in which case a one-off prompt seems fine to me.

**Comment by bfred-it** [comment]
The button essentially erases your notifications and clobbers your browser and network with up to 50 tabs, so I'd keep the prompt (it's a <kbd>Enter</kbd> keypress away anyway). If "Mark all as read" has a prompt, a button that does _that **and more**_ by proxy it should also have a prompt.

**Comment by gibfahn** [comment]
@bfred-it could we compromise and say "warn by default, have an option to not warn"?

FWIW if your browser crashes the notifications usually aren't erased (you usually have to switch to the tab before it counts) but I take your point.

**Comment by tanmayrajani** [comment]
I like not showing confirmation popup for <10 tabs too. Implemented the same for now.

Also, refreshing the page is kinda weird here (at least that's what I encountered) since the task of opening the tabs has been sent to `background.js` using `browser.runtime.sendMessage`, we don't know when all the tabs have been opened. **Hence, it sometimes have all/few notifications still unread even after refresh.** Any suggestions? (I tried adding some timeout but not the best of ideas I guess.)

Here's current [diff](https://github.com/sindresorhus/refined-github/compare/master...tanmayrajani:master)

**Comment by bfred-it** [comment]
@tanmayrajani can you send a PR? It's easier to comment there directly 😄 

Yeah the issue you're describing has no easy solution. You probably would have to track each tab's loading — which might take a while anyway.

So how about this:

1. Add `<base target="_blank">` so all links open in tabs
2. `for link of select.all('a'), link.click()` should open all links **and** mark them as read natively
3. Refresh the page when all the links have been _grayed out_

😅 

I know, a bit of a stretch and it probably still triggers the popup blocker. Worth a try? Or maybe we should just abandon the refresh idea? In that case we should at least gray out the links in the view.

**Comment by tanmayrajani** [comment]
@bfred-it sent a PR (#712). Went with graying out the notifications for now.
