### ISSUE TITLE
Explore is highlighted when selecting trending

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#705]
![image](https://user-images.githubusercontent.com/16872793/30933108-8b1ab85a-a397-11e7-916b-b243ccd3512f.png)

**Comment by nothingrandom** [comment]
**Potential problem**
The explore a href has the props
`data-selected-links="/explore /trending /trending/developers /integrations /integrations/feature/code /integrations/feature/collaborate /integrations/feature/ship showcases showcases_search showcases_landing /explore"`

**Potential solution**
Remove the `data-selected-links` `/trending` from the explore link and add it to the trending link instead.

**Comment by yakov116** [comment]
Was fixed but not closed.

Thanks @busches

**Comment by bfred-it** [comment]
Yeah I think the “fixes#XXX” needs to be in the PR body, not the singular commits. I dropped it from the squashed commit to avoid yet another mention here.
