### ISSUE TITLE
(maybe) XSS Vulnerability in notifications

### ISSUE THREAD

**Issue by CompuIves** [sindresorhus/refined-github#706]
Hey! I'm an avid user of Refined Github and love the extension. Today I found out that my notification wasn't showing properly:

![screen shot 2017-09-30 at 22 35 24](https://user-images.githubusercontent.com/587016/31049269-1519f8be-a630-11e7-9d7b-13df252379b8.png)

And it was because there was an issue with the title: "\<svg tabIndex="2"\> doesn't work". After some digging, I found out that the issue was resolved when I disabled Refined Github, so it seems that there could be an XSS vulnerability in the notification page. I'm not sure, maybe it could also be because there maybe is support for markdown. I thought I'd open an issue to make you aware regardless.

**Comment by bfred-it** [comment]
That’d b strange because we’re not using innerHTML anywhere I think. Are you referring to Mark as Unread? Can you link to the issue?

**Comment by 2qw** [comment]
Then what may it be


hitekforu


On Sep 30, 2017 5:25 PM, Federico Brigante <notifications@github.com> wrote:

That’d b strange because we’re not using innerHTML anywhere I think. Are you referring to Mark as Unread? Can you link to the issue?

**Comment by bfred-it** [comment]
Can you leave a comment here so I can see what's happening? https://github.com/bfred-it-obsolete/empty/issues/1

**Comment by bfred-it** [comment]
Thanks! But can't reproduce. Are you using the latest version?

<img width="311" alt="no XSS" src="https://user-images.githubusercontent.com/1402241/31054793-031b1bde-a680-11e7-9f37-fe25688bf97f.png">

**Comment by bfred-it** [comment]
I see a "tooltipstered" class in your screenshot on there so it might be some other extension doing it. I don't think we're doing anything on that page if there are no items _marked as unread_
