### ISSUE TITLE
Link Tooltips are broken

### ISSUE THREAD

**Issue by jridgewell** [sindresorhus/refined-github#711]
Seems Github added tooltips to link to other issues:

![screen shot 2017-10-09 at 4 25 27 pm](https://user-images.githubusercontent.com/112982/31357107-7f3aee30-ad0e-11e7-886b-ca5f49b27bbb.png)

However, refined-github breaks them:

![screen shot 2017-10-09 at 4 26 13 pm](https://user-images.githubusercontent.com/112982/31357155-9a86cd76-ad0e-11e7-98c7-66e2f640873b.png)

**Comment by jdreesen** [comment]
This was fixed in #710 and relesed as `17.10.8.1623` yesterday. Updating you addons should fix this.

**Comment by jridgewell** [comment]
Confirmed, thanks!
