### ISSUE TITLE
The "Hides other users starring/forking your repos from the news feed" feature no longer works

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#723]
Stopped working after the recent news feed refresh.

**Comment by kevva** [comment]
Also, it doesn't hide pushes to branches anymore which clutters the news feed extremely much.

**Comment by sindresorhus** [comment]
@kevva Even after https://github.com/sindresorhus/refined-github/pull/724? If so, can you open a new issue?
