### ISSUE TITLE
Link to travis if .travis.yml is found

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#726]
It'd be nice to have a small indicator/icon next to the title, that links out to travis. Example:

<img width="374" alt="travis indicator mockup" src="https://user-images.githubusercontent.com/1402241/31625954-8f5f9e1e-b26d-11e7-87fe-86099b8bcbe3.png">

If we can steal GitHub's own marker from the [commits list](https://github.com/sindresorhus/refined-github/commits/master), it'd be great, otherwise just a link to travis would suffice.

**Comment by yakov116** [comment]
@bfred-it Why not all ci's?

**Comment by bfred-it** [comment]
Sure, if we can actually use GH's own indicator + link we're set, otherwise it might not be as easy.

**Comment by bfred-it** [comment]
This is the core functionality:

```js
const doc = await fetch('/sindresorhus/refined-github/commits/').then(r => r.text()).then(domify);
const status = select('.commit-build-statuses', doc);
if (status) {
    select('.pagehead [itemprop="name"]').append(status);
}
```

I needs styling fixes

**Comment by hkdobrev** [comment]
I still think this would be much better if we detect whether this is Travis CI, Circle CI etc. (via filenames or another method) and add the respective icon next to the repo name. On Travis CI they link back to the GitHub repo with a GitHub icon.

Also, keep in mind a repo could use multiple services adding a commit status so this becomes more tricky. We might not have a single link to add.

I've previously used this: https://chrome.google.com/webstore/detail/github-travis-ci-builds/dphnhapafaimelkockemokgfdocadbdo But it had its problems and I found myself using it mostly to find out if the repo has Travis CI and go to the latest build.

**Comment by bfred-it** [comment]
Why would a link be better than the GitHub’s own status indicator? I think the commits page automatically includes all CIs

**Comment by hkdobrev** [comment]
@bfred-it The status indicator is fine and should be there, but I think a direct link to the latest build is superior in terms of experience.

**Comment by bfred-it** [comment]
Yep that's part of the indicator itself:

<img width="649" alt="indicator URL" src="https://user-images.githubusercontent.com/1402241/31699414-9db28366-b388-11e7-85f0-a6293cef6a8a.png">

**Comment by bfred-it** [comment]
I think this is a killer feature and GitHub should implement it. Just by looking at the amount of `build` badges people care a whole lot about it being green.
