### ISSUE TITLE
Automatically focus "Confirm" in Mark all as read dialog

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#730]
# Current dialog

<img width="505" alt="mark all as read" src="https://user-images.githubusercontent.com/1402241/31700152-0b66da3e-b38d-11e7-9d15-b0df73ce0430.png">

# Should be (focused)

<img width="500" alt="mark all as read (focused)" src="https://user-images.githubusercontent.com/1402241/31700158-1499bdd8-b38d-11e7-9aba-77a0a4b6bf3c.png">

# Also, our own dialog

<img width="496" alt="open all notifications" src="https://user-images.githubusercontent.com/1402241/31700161-1e84fee8-b38d-11e7-83d1-540a100e48e9.png">

**Comment by CrowderSoup** [comment]
I'd love to work on this! Just pulled and build the extension. I'll start digging in now.

**Comment by CrowderSoup** [comment]
This was a fairly simple change! I have a PR open (referenced above).
