### ISSUE TITLE
Tooltips: yay or nay?

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#731]
Our "Removes tooltips" feature is currently broken (`:not(multiple,selectors)` doesn't work) and parts of RGH add `.tooltipped` explicitly. What do we do?

- Tooltips are a-ok: 👍 
- Tooltips begone: 👎 
- I hate binary polls: 🎉

**Comment by bfred-it** [comment]
I don't particularly mind tooltips, except maybe in this case (which is actually covered by RGH):

<img width="272" alt="screen shot 2017-10-18 at 12 11 02" src="https://user-images.githubusercontent.com/1402241/31700599-158f72b6-b390-11e7-83e4-6928da91fdff.png">

**Comment by sindresorhus** [comment]
I personally find the tooltips annoying. Refined GitHub is for power users and they should know what different buttons do.

**Comment by bfred-it** [comment]
This is what it looks like to completely remove tooltips from RGH: https://github.com/sindresorhus/refined-github/commit/b8508b05ae944d4dd5498bbabe12bff161150b5e

**Comment by sindresorhus** [comment]
@bfred-it Thanks, that made me realize there's a few places it's worth preserving the tooltip:

- https://github.com/sindresorhus/refined-github/commit/b8508b05ae944d4dd5498bbabe12bff161150b5e#diff-95ffcbff3c841ad0a802793cabd8940eL191 It's good to explain to the user that this goes to the latest tagged version of the readme. That's not clear from the icon.
- https://github.com/sindresorhus/refined-github/commit/b8508b05ae944d4dd5498bbabe12bff161150b5e#diff-95ffcbff3c841ad0a802793cabd8940eL392 This too, as it's makes it clear what it does.
- https://github.com/sindresorhus/refined-github/commit/b8508b05ae944d4dd5498bbabe12bff161150b5e#diff-0d912ef671d7a99c2ddabf2ae8a3a653L26 This adds extra information not shown in the UI.

**Comment by xt0rted** [comment]
I'd prefer the ability to pick what features to enable vs. straight up removing something. For now my vote goes to keeping them.
