### ISSUE TITLE
Link to repo at time of issue comment

### ISSUE THREAD

**Issue by ianstormtaylor** [sindresorhus/refined-github#732]
Hey, first off, thank you for this awesome extension! I just went through the features list to check if this one was already implemented, and I didn't realize that so many things I've come to rely on aren't even native GitHub UX things 😄 

I've got an idea for a feature...

I often find myself browsing through old issues, and sometimes when reading a discussion I think to myself, "I wonder what that part of the code looked like while that was being discussed". Right now it's super tedious to find out, because you have to remember the comment date, then page through the commits until you find something roughly at that date, and then find the "view files at" button, etc.

It would be super awesome if there was an extra little icon button next to comments that let you "jump to the repo at this point on time"!

**Comment by sindresorhus** [comment]
That's a very cool idea. I could have used this many times. Pull request welcome if anyone wants to see this happen.
