### ISSUE TITLE
Getting started guide

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#733]
How to get started contributing to the project. Starting watch mode and adding the extension as development extension to Chrome, etc. See: https://github.com/sindresorhus/refined-github/issues/688#issuecomment-337463374

**Comment by hkdobrev** [comment]
I'd go for `.github/CONTRIBUTING.md`, mention it in the readme with a short excerpt and a link.
(We could later add issue/PR templates and even a code owners file.)

Also, I think introducing Git hooks running some of the scripts could help as I often forget to run something right away when switching branches when I haven't checked it out locally for a while.

**Comment by bfred-it** [comment]
Re: git hooks

I usually fire up `npm run watch` and then keep it open as I check out branches, that always keeps the build up to date. The only thing missing is the occasional `npm install`. Maybe it can be added with https://www.npmjs.com/package/npm-install-webpack-plugin?
