### ISSUE TITLE
Move dependency graph into tab bar

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#737]
Since GitHub added the [dependency graph](https://github.com/sindresorhus/refined-github/network/dependencies) in the 'Insights' section, I disabled the [npmhub](https://github.com/npmhub/npmhub) extension I used to view dependencies previously (sorry @bfred-it 😜). However, the page is currently hidden behind 2 clicks. Can we move it into the 'More' dropdown?

**Comment by bfred-it** [comment]
Related: https://github.com/npmhub/npmhub/issues/78

**Comment by jgierer12** [comment]
Yeah, it's still a bit rough around the edges (somehow it often picks up `package.json` twice), but I try to keep my extension count as low as possible so it has to suffice.

**Comment by bfred-it** [comment]
> I try to keep my extension count as low as possible so it has to suffice.

Me too.

<img width="221" alt="48 extensions enabled" src="https://user-images.githubusercontent.com/1402241/31761314-162f5e5a-b47d-11e7-8677-735f7b740200.png">

**Comment by jgierer12** [comment]
![image](https://user-images.githubusercontent.com/4331946/31777275-fa99319a-b4ed-11e7-8c87-14d8f9ff8a27.png)
💪

**Comment by bfred-it** [comment]
Not really comparable at this stage though, GH doesn't distinguish between normal dependencies and developer dependencies. If there's a `package-lock.json` it even shows sub dependencies of dev dependencies. 

Essentially useless in this case: https://github.com/bfred-it/iphone-inline-video/network/dependencies (it only has two dependencies without sub-dependencies)

**Comment by bfred-it** [comment]
It's been added by #739
