### ISSUE TITLE
Remove thumbsup support.

### ISSUE THREAD

**Issue by joshmanders** [sindresorhus/refined-github#74]
GitHub just added reactions so we don't need this anymore.

https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments

**Comment by nikolay** [comment]
Copycats! :smile:

**Comment by simov** [comment]
:wave: I just though you might like this https://github.com/StylishThemes/GitHub-Dark/issues/292

**Comment by paulmolluzzo** [comment]
Obviously, people will be using reactions, so this feature might be overlooked entirely. On the other hand, GH isn't converting old votes into reactions, so any thread older than 2 days probably won't have many reactions.

Keep in mind, if there are no votes nothing is displayed. Where is the harm in leaving in the code? Should we take out a (possibly) useful feature just because _eventually_ it'll be entirely pointless?

**Comment by sindresorhus** [comment]
I still think this is useful for now, and it's going to take time for all users to adjust to "reactions". We can revisit removing it in the future.

**Comment by hkdobrev** [comment]
Recently when I look at some :+1: comments which get moved to the sidebar, I need to know when they were made - after the first posting of the issue, or after some discussion. Often I open the page in incognito to check that out or if the repo is private, I need to turn off the extension for a second.

The new GitHub reactions separate reactions to description from reactions to comments, they still don't show you the time of reaction, but that's out of scope here.

There are less and less new +1 comments now with the new GitHub reactions. So with all that said I'd vote to remove the +/-1 comments from the sidebar.

We could potentially collapse all adjacent +/-1 comments into a single comment inside of the comment timeline, so we still streamline old issues with a ton of +1 _votes_. But this use case would become less and less relevant with the reactions being used.

**Comment by sindresorhus** [comment]
I guess that makes sense.

**Comment by DrewML** [comment]
If we did remove this, and users are still interested in hiding those, a similar feature is provided by [this chrome extension](https://github.com/ryanflorence/github-plusone-extension)

**Comment by hkdobrev** [comment]
@paulmolluzzo Any thoughts on this or #159?

**Comment by paulmolluzzo** [comment]
I'm OK with removing thumbs up, though some older threads will be annoying if they have 7382$382837 +1 only comments.

I haven't reviewed #159 yet but will comment there when I do.

**Comment by rubyFeedback** [comment]
One problem I have is that it works on some projects but not on others.

For instance on github ladybird, any upvote is automatically removed.

I think it would be useful to explain to users why it does not work on a given project.
