### ISSUE TITLE
What happened to the preview of line links?

### ISSUE THREAD

**Issue by olstenlarck** [sindresorhus/refined-github#743]
Hey there :wave:  Using this extension, still – from the beginning.

Before few days i just notice in few times that when link to a line is posted in issue/pr it was automatically shown/rendered. It was like embedded gist (almost).

Don't know. I don't think it was from another extension, cuz i don't have much for GitHub stuff.

**Comment by bfred-it** [comment]
That’s a native GitHub feature. Testing

https://github.com/sindresorhus/refined-github/blob/36dfa3bddae209492c083738e12043aafa2cb736/src/content.js#L28

**Comment by bfred-it** [comment]
Yep still works

**Comment by olstenlarck** [comment]
Hm. Yea. Okey, thanks!

But in any way it would be great to work for branches too.

(random line)
```
https://github.com/sindresorhus/refined-github/blob/master/src/content.js#L6
```

**Comment by bfred-it** [comment]
The probably didn't implement that because branches change and for that reason those links will become wrong at some point. In short they're encouraging you to get the permalink

<img width="199" alt="permalink" src="https://user-images.githubusercontent.com/1402241/31758378-d445074c-b472-11e7-8188-5f628b51bbe1.png">

**Comment by hkdobrev** [comment]
A reminder here that with Refined GitHub pressing <kbd>y</kbd> would also add the permalink to your clipboard.

**Comment by jdreesen** [comment]
<kbd>y</kbd> is a keyboard shortcut [from GitHub itself](https://help.github.com/articles/using-keyboard-shortcuts/#source-code-browsing) ;)

**Comment by bfred-it** [comment]
@jdreesen GitHub's shortcut will open the permalink; Refined GitHub will also copy its URL.

**Comment by jdreesen** [comment]
Oh wow, I didn't know that, that's very nice :)
