### ISSUE TITLE
Auto load more Repositories 

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#745]
Since we are hiding the "Repositories you contributed to" Can we auto load more?

![image](https://user-images.githubusercontent.com/16872793/31774241-2e82d92e-b4b3-11e7-81f5-acd2ec83d7b3.png)

**Comment by sindresorhus** [comment]
Yeah, makes sense to click "Load more..." once.

**Comment by yakov116** [comment]
@sindresorhus Oh.. I forgot that people have more repo's than me and would need to click more then once 😄

**Comment by yakov116** [comment]
Well with the new changes I dont know if this is needed

**Comment by hkdobrev** [comment]
See https://help.github.com/articles/about-your-personal-dashboard/#finding-your-top-repositories-and-teams
