### ISSUE TITLE
Add "Stars" Next to "Forks"

### ISSUE THREAD

**Issue by yakov116** [sindresorhus/refined-github#746]
![image](https://user-images.githubusercontent.com/16872793/31783016-cb164c96-b4ca-11e7-859e-a33f243b96bb.png)

**Comment by sindresorhus** [comment]
Can you elaborate on why this should be added and how it will work?

**Comment by yakov116** [comment]
@sindresorhus In that list (The box) you see all the repo's you are associated with . The only way to see your starts is by loading a new menu.

The way it would work would be an api call when stars is clicked or when the page is loaded.

**Comment by sindresorhus** [comment]
I mean, why is it important to have the "Stars" there when you can just go to https://github.com/stars and have search, filter, and sorting.

**Comment by yakov116** [comment]
@sindresorhus I personally use this to check if a repo was updated. Many times I don't want to watch a repo, but I would like to know if they added stuff to it. One of the things I like most while working, is having everything on one page.
Is it _important_? nope, would it be nice to have it? I think so.

**Comment by hkdobrev** [comment]
Thanks for the suggestion, but I'm not going to use that as I have thousands of starred repos and they are usable only on https://github.com/stars.

I don't think adding a 6th tab is helping especially when the other 5 tabs are about your repos and the 6th is most probably not about your repos.

**Comment by yakov116** [comment]
@hkdobrev true. But it could be useful for some. 

Not to argue, just curious.  Why would this be any different that someone that has a few hundred repo's? In other words why is the amount making the difference?

**Comment by hkdobrev** [comment]
@yakov116 Sometimes I'm starring dozens of repos per day so listing a few of them don't make it useful. I usually go to the stars page and search something which I know I've starred or that I might have starred.

**Comment by yakov116** [comment]
@hkdobrev You can do the same search there? 

The way I am looking at it is that the only thing that I have to leave the dashboard is for stars. Doing this would solve that.

**Comment by bfred-it** [comment]
1. Your Stars is always 2 clicks away on all pages (User dropdown) 
2. I don't see the sort-by-activity being a common use case to justify the whole feature

So:

1. Not faster than just opening Your Stars and resorting it
2. Can be replaced by an old-style browser bookmark to https://github.com/yakov116?direction=desc&sort=updated&tab=stars
