### ISSUE TITLE
Pushes are hidden

### ISSUE THREAD

**Issue by casz** [sindresorhus/refined-github#747]
I had to disable refined-github because it's messing with the feed. Seems GitHub changed something a few days ago.

Issue seems to be https://github.com/sindresorhus/refined-github/blob/8196bc88b9737404c26cb286aa439fa42bc015a0/src/libs/auto-load-more-news.js#L41

Refined enabled:
![image](https://user-images.githubusercontent.com/1661688/31809409-e778618c-b577-11e7-8660-42c1c81c47f2.png)

Refined disabled:
![image](https://user-images.githubusercontent.com/1661688/31809437-086b9224-b578-11e7-92ba-dba436a74152.png)

**Comment by bfred-it** [comment]
What's the mess exactly? The error doesn't cause any visible issues.

**Comment by casz** [comment]
Full page, with Refined enabled:
![image](https://user-images.githubusercontent.com/1661688/31809610-d0412610-b578-11e7-9aa3-c90232baf5f4.png)

Full page, with Refined disabled;
![image](https://user-images.githubusercontent.com/1661688/31809658-fadb5e90-b578-11e7-8785-f1f8a7700348.png)

**Comment by bfred-it** [comment]
Yes, that's as designed. Pushes are hidden: https://github.com/sindresorhus/refined-github/pull/728

**Comment by casz** [comment]
That to me makes my feed useless 👎 Can it be made optional?

**Comment by bfred-it** [comment]
Yeah, the latest changes by GitHub essentially only left out stars, forks, and pushes and [added labels](https://github.com/sindresorhus/refined-github/pull/744)

**Comment by kumarharsh** [comment]
@bfred-it it also seems like the feed is filtered to not show other people starring my repository. The new feed redesign of github seems to be *much better* than before, and I'd like it if maybe refined-github can not mess up the feed?

**Comment by bfred-it** [comment]
There's an option for that. Check out the settings page: 

```
chrome://extensions/?options=hlepfoohegkhhmjieoechaddaejaokhf
```

**Comment by kumarharsh** [comment]
Oh, didn't notice that. Thanks. People forking other people are still hidden though.
