### ISSUE TITLE
Feature Toggle

### ISSUE THREAD

**Issue by alexbooker** [sindresorhus/refined-github#75]
Hi :wave:. I like so many things about this extension, but there are also a couple of things I'd rather disable. For instance, it makes a lot of sense for someone like you, @sindresorhus, to _"hide other users starring/forking your repos from the newsfeed"_, but I would rather see that info in my newsfeed.

Would you consider adding or accepting a pull request for a feature toggle interface?

**Comment by paulmolluzzo** [comment]
See #10.

**Comment by sindresorhus** [comment]
> but there are also a couple of things I'd rather disable. 

Now imagine every user have something different they want to disable. Introducing feature toggle is a slippery slope to having to feature toggle everything.

Creating great products is about saying *no* to thousands of things.

> "hide other users starring/forking your repos from the newsfeed", but I would rather see that info in my newsfeed.

For what purpose? IMHO the stars news items is just a useless ego-boost with no actual value. Try using this plugin for a week and see how little you actually need that info.

-

Just use your own fork if you strongly disagree.
