### ISSUE TITLE
"Upload files" button is hidden

### ISSUE THREAD

**Issue by MilesBHuff** [sindresorhus/refined-github#750]
The "Upload files" button is hidden when this addon is enabled.  This is a useful button, and there's no reason for it to be disabled.  I'm aware that we can still drag & drop files to upload, even without this button -- but it's often more convenient to be able to manually select files.

**Comment by bfred-it** [comment]
This confuses me a bit, we're showing it in the comments box (https://github.com/sindresorhus/refined-github/pull/408) but [hiding it](https://github.com/sindresorhus/refined-github/blob/af1bc0f5734487e7e199443d504d2913528c6880/extension/content.css#L199-L202) on the repo home.

**Comment by bfred-it** [comment]
The button was being recently discussed here: https://github.com/sindresorhus/refined-github/issues/693

**Comment by bfred-it** [comment]
This can now be restored, name of the feature: `remove-upload-files-button`
