### ISSUE TITLE
GitHub footer is hidden on Enterprise GitHub instances

### ISSUE THREAD

**Issue by fwextensions** [sindresorhus/refined-github#753]
I thought this was intentional at first, but then I saw that the `github.com` pages had the footer.  Here, the top window is an internal Enterprise GH instancej (version 2.8.7), and the bottom one is the public GitHub:

![image](https://user-images.githubusercontent.com/61631/31868664-a2ed7a26-b756-11e7-98de-26db006dd9e9.png)

Well, maybe it is intentional.  I do see this in `content.css`:

	.site-footer {
		visibility: hidden;
	}

But the public site's footer class is now just `footer`.  So if it's supposed to be hidden, that's no longer happening.  But I'm not sure hiding it is necessary.  The logo in the footer seems to be the one place you can see the version of EGH you're running: 

![image](https://user-images.githubusercontent.com/61631/31868748-49f21b1a-b757-11e7-9923-298459e966e7.png)

**Comment by bfred-it** [comment]
Yeah that rule is [ancient](https://github.com/sindresorhus/refined-github/commit/07ecc75e81cbc466d6bc98a12505ae58fec68d59#diff-83ab1d10d74dc75c62ac9cf612cfce51R53). Perhaps it should be hidden everywhere.
