### ISSUE TITLE
Solve the problem of truncated file names

### ISSUE THREAD

**Issue by alexbooker** [sindresorhus/refined-github#76]
Some repositories have longer file names that GitHub truncates:

![](http://i.imgur.com/92bwS50.png)

In order to view the full file name, you have to hover your cursor over the truncated file name.

I think it would be nicer if _refined-github_ would allow the user to dynamically resize the file name column with their mouse, sort-of like how Excel does:

![](http://static.chandoo.org/img/l/adjust-column-widths.gif)

Another (less ambitious) option would be to word wrap long file names.

What do you think?

**Comment by sindresorhus** [comment]
This has never been an issue for me. Why is `hover your cursor over the truncated file name` not good enough? Resizable columns is not an option as it's IMHO too clunky.

// @hkdobrev @paulmolluzzo

**Comment by hkdobrev** [comment]
The title on hover works for me.

**Comment by paulmolluzzo** [comment]
I agree, that'd be super clunky. I wouldn't take style cues from MS Excel. :)
