### ISSUE TITLE
Issue comment inline code snippets are masked/truncated

### ISSUE THREAD

**Issue by benjie** [sindresorhus/refined-github#765]
With Refined GitHub (incorrect):

![screenshot 2017-10-26 11 34 51](https://user-images.githubusercontent.com/129910/32048569-d511a99e-ba41-11e7-8603-f50f27fd602f.png)

---

Without Refined GitHub (correct):

![screenshot 2017-10-26 11 34 23](https://user-images.githubusercontent.com/129910/32048583-e3a998d6-ba41-11e7-90ee-ecb78c0e8702.png)

---

Comment for reproduction:

https://github.com/graphile/graphile-build/pull/101#issuecomment-339623628

---

Thanks for this plugin! 🙏

**Comment by bfred-it** [comment]
Neat! Another [`removeDiffSigns` bug](https://github.com/sindresorhus/refined-github/issues?utf8=%E2%9C%93&q=Diff%20Signs%20)!
