### ISSUE TITLE
Image Upload button not working

### ISSUE THREAD

**Issue by kyleshevlin** [sindresorhus/refined-github#770]
The image upload button stopped working for replies, comments, issues, etc.

I believe the culprit is that it is not a `button` but a `label` element. Seems like this is a mistake and that a click handler is likely missing/not working because of it.

Here is an image of the button I'm referring to: 
![screen shot 2017-10-26 at 9 34 44 am](https://user-images.githubusercontent.com/4333144/32065316-4a7a15ce-ba31-11e7-8540-bde4a30f958d.png)

And here is an image of the markup I'm seeing when I inspect it: 
![screen shot 2017-10-26 at 9 37 54 am](https://user-images.githubusercontent.com/4333144/32065354-6736e822-ba31-11e7-88c6-c7bb64813e94.png)

**Comment by bfred-it** [comment]
You're lucky, I fixed it 4 hours ago, but the PR hasn't been merged yet 😆
