### ISSUE TITLE
Please make the extension configurable in Chrome settings

### ISSUE THREAD

**Issue by simonschaufi** [sindresorhus/refined-github#779]
I love this extension but for me it removes a little bit too much. For example the formatting buttons in the editor are gone and also the merge with command line (I need this to test a pull request locally).
I know there are plenty of modifications available but can at least some be configured to be active and inactive?

**Comment by hkdobrev** [comment]
👍 
I wouldn't use this setting, but I see lots of people use the Markdown tools. Here's a review from the Firefox add-on reviews:

> This addon make GitHub better.
>
> I still need GitHub markdown tool in comment. It make me faster writing markdown. It should be great if you can bring it back.
>
> Keep up good work. Thank you.

https://addons.mozilla.org/en-US/firefox/addon/refined-github-/reviews/939957/

**Comment by busches** [comment]
We could extend the safely method to check for configuration now. Would
need a new name, but would centralize the config options.

**Comment by sindresorhus** [comment]
We have more than 9000 users and we've only gotten a couple of requests for bringing back the Markdown toolbar. From all the things we could make configurable, I don't think this is an important thing. It's super simple to learn and use the basics of Markdown by hand. I don't see the point of having buttons to insert `#`, `1.`, `>`, `_foo_`.

**Comment by bfred-it** [comment]
It's true that markdown is easy to type, but not always. I doubt you could quote more than one line with this ease or make a numbered list so quickly without manually typing `1. text \n 1. text2`

![toolbar demo](https://user-images.githubusercontent.com/1402241/32671319-e15d0e04-c681-11e7-92d7-f2f2774ccacf.gif)

**Bold** (cmd+b) and _italic_ (cmd+i) and links (cmd+k) are addable via keyboard but others don't (lists, quotes). Maybe they could at the very least be implemented as cmd+l and cmd+q 😋  — however without the toolbar these shortcuts would be rather obscure, just like our cmd+u for uploads.

**Comment by yakov116** [comment]
@bfred-it 100% This is one of the main reasons that I compile the extension myself. I use the lists all the time and code selector.

**Comment by bfred-it** [comment]
@bfred-it for fixes like this you can use Stylish to override the extension’s style. I have my own list of unwanted RGH styles that way

**Comment by sindresorhus** [comment]
@bred-it That’s a good argument. Maybe we should just bring it back then. I would prefer that over an option. It doesn’t bother me much anyway.

I’m curious what other things you override?

**Comment by bfred-it** [comment]
Maybe only these can be hidden since they're easy to add via keyboard:

<img width="388" alt="unwanted buttons" src="https://user-images.githubusercontent.com/1402241/32687183-f0a89232-c6f1-11e7-8657-7b5d727bd214.png">


@sindresorhus Overrides: #566, #637, #610 (although now I _prefer_ `hub checkout` since it preserves GitHub Desktop's ability to push to forks in one click), and I had more but recently Stylish forgot all of my userstyles 😢

**Comment by bfred-it** [comment]
👍 PRs welcome to restore the non-red comment buttons in my screenshot above.

Specific other requests can be searched or made in separate issues.

**Comment by gluons** [comment]
I also created [a simple userstyle](https://userstyles.org/styles/150195/refined-github-original-comment-tools) to bring it back. 🙂
