### ISSUE TITLE
Add functionality to expand all outdated comments at once

### ISSUE THREAD

**Issue by sgabler** [sindresorhus/refined-github#781]
Hey everyone, first comment in this repo, so wanted to give you a big "Thank You" first for creating this great extension!

What do you think of the following small tweak for pull requests:
- when hovering over the "Show outdated" text, a small popup tells you "Hold shift while clicking to expand all comments"
- when shift-clicking on the "Show outdated" text, all collapsed comments expand

![image](https://user-images.githubusercontent.com/3625477/32143703-dc59d05a-bcad-11e7-92e9-e611eba2adc4.png)

Alternative implementation ideas:
- Have a button/text next to "Show outdated"
- Use a different button combination

**Why?** My team is currently in the habit of manually going through all outdated comments to make sure they were implemented correctly. Sometimes those comments are outdated because of code formatting or similar. We are currently using JS via a bookmark to achieve that functionality, but it would be really nice to have this in this extension.

Very happy to try implementing this myself, but I wanted to check if this is something you might be interested in.

**Comment by bfred-it** [comment]
I find myself doing this often too. I feel that we should tackle this and other similar toggles via keyboard shortcut, eg `cmd+click=toggle all`. No UI clutter necessary. 

Alternatively it could be `alt+click` to match macOS’ *alternative* behavior, and perhaps we could show the alternative actions while `alt` is held down i.e. all *Show outdated* become *Show all outdated* (macOS does the same)

**Comment by bfred-it** [comment]
#212 is related. Maybe pressing `i` also works in the discussione tab? I’m away from keyboard now

**Comment by sgabler** [comment]
I didn't find anything and I think that Github doesn't provide that feature

Here's a screenshot of the shortcuts displayed for the discussion page

![image](https://user-images.githubusercontent.com/3625477/32145265-b98b921c-bcc5-11e7-872a-72c1c174db97.png)

**Comment by mgoveas** [comment]
To add to @laurenbrandstein solution, this worked for me
`javascript:Array.from(document.getElementsByClassName('outdated-comment')).forEach(l=>l.setAttribute('class','file js-comment-container has-inline-notes'));`

**Comment by haridsv** [comment]
@mgoveas I think the entire conversation needs to be unhidden and I have a few PRs where I have to meticulously scroll around to find these "hidden items" and click a few times and it is a pain.

**Comment by voppe** [comment]
2020 edition.

Open all resolved:
```
javascript:Array.from(document.getElementsByClassName("js-toggle-outdated-comments")).forEach(l => l.click());
```

Click all "Load More":
```
javascript:Array.from(document.getElementsByClassName("ajax-pagination-btn')).forEach(l => l.click());
```

**Comment by tekumara** [comment]
thanks @voppe that worked!

**Comment by haridsv** [comment]
The solution for "Load More" is too simplistic that only works for one level (I have PRs that nest at least 10 levels), so here is a my better solution: https://stackoverflow.com/a/62711702/95750

There are other solutions that I found later:
- https://github.com/isaacs/github/issues/1190
- https://github.com/sindresorhus/refined-github/issues/1892

**Comment by akpmohan07** [comment]
I am using https://marketplace.visualstudio.com/items?itemName=GitHub.vscode-pull-request-github
