### ISSUE TITLE
Permalink toolbar doesn't line up with selected line

### ISSUE THREAD

**Issue by xt0rted** [sindresorhus/refined-github#786]
The permalink toolbar doesn't show up on the line you select, but rather about 2 lines above it. This offset looks to be a result of the `position: sticky` style added to the file header.

![image](https://user-images.githubusercontent.com/831974/32205640-c6f16d08-bdc6-11e7-9f93-aaf0ba55e83a.png)

**Comment by bfred-it** [comment]
It’s been bothering me too, is it really caused by this extension? 😮

**Comment by xt0rted** [comment]
Yea, when I disable this extension it goes back to being on the right line

**Comment by bfred-it** [comment]
I can reproduce in my current Chrome profile, but I don't know why it's happening, it still happens after I disable RGH
