### ISSUE TITLE
[REQ] Search/filter notifications

### ISSUE THREAD

**Issue by stramel** [sindresorhus/refined-github#788]
I think it would be beneficial if we could:

- search through notifications for text
- view read participating notifications
- be able to filter based on notification reasons
- Don't know if this is possible but closed vs open issues/PRs

I imagine this being handled similarly to how issue search is but definitely open to alternate suggestions.

**Comment by bfred-it** [comment]
This would be a webapp-like revamp of the notifications, probably over API, it’s a big undertaking. 

Ironically the last point is the easiest one and can be done without any HTTP calls.

I don’t think any of this would be useful to me (except maybe a simple open/closed/merged filter) but let’s see what others say. You can propose it in [sindresorhus/module-requests](/sindresorhus/module-requests) as a separate extension.

**Comment by hkdobrev** [comment]
Once the GraphQL API of GitHub is mature enough to include everything you need for the notifications interface it would be pretty easy to do an app on top of it replacing the current github.com/notifications. However, this definitely should go into a separate extension. There are already separate extension for the notifications page doing similar things like https://github.com/ozlerhakan/categoric However it could only work with the notifications visible on the page.
