### ISSUE TITLE
Replacing URLs with links in PR diff view creates confusion

### ISSUE THREAD

**Issue by pawelad** [sindresorhus/refined-github#789]
Not sure if this is a bug or a feature but GitHub Redefined changed the `https://example.com/` into a `example.com` link on PR diff, which created a great amount of confusion when I was referencing the lack of `https` and trailing slash, linking to the line, which turned out to have both of these things, just not visible on my machine.

And if that is a feature, could we a) maybe disable it for diff's b) make it configurable?

Thanks!

**Comment by bfred-it** [comment]
Yes that’s involuntary. I sent a PR

**Comment by pawelad** [comment]
Same thing happened again - with extension:

![screen shot 2018-03-07 at 2 45 15 pm](https://user-images.githubusercontent.com/7062874/37114398-4051d2d8-2216-11e8-886d-21428e1c6b10.png)

Incognito:

![screen shot 2018-03-07 at 2 45 30 pm](https://user-images.githubusercontent.com/7062874/37114406-450205e6-2216-11e8-96d8-005588eb95de.png)


[Source](https://github.com/pawelad/pymonzo/pull/16/files)

**Comment by bfred-it** [comment]
Thanks @pawelad! I sent a new PR. I had mistakenly undone the protection
