### ISSUE TITLE
Real name not shown for logged-in user?

### ISSUE THREAD

**Issue by busches** [sindresorhus/refined-github#791]
For some reason my real name is not showing up next to my username. I'm assuming it's not working for the logged in user, not specific to me.
What's odd is the `refined-github-fullname` class is still added. Other names do work and this occurs on both GHE/GH for me when I'm logged in. I cleared the cache and can see it pulling down everyone else's but not myself.

![image](https://user-images.githubusercontent.com/857700/32280973-7330be6e-beeb-11e7-9061-c28f853a4633.png)

**Comment by bfred-it** [comment]
No, _it's a feature,_ you know your own name so no need for an extra request/store:

https://github.com/sindresorhus/refined-github/blob/34aa9dcafc63bee63cc3dc0e41ab29d1f4f8275f/src/libs/show-names.js#L38

**Comment by busches** [comment]
Suppose, swore it used to work. Thanks for the clarification.
