### ISSUE TITLE
Add link to releases on every repository page

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#8]
At the moment you can click to go to the releases page only when you're on the Code tab in a repository.

As I use the releases page quite often, I'd suggest to place a link to releases on every tab of the repo. Perhaps as another tab?

I hope others would find this useful as well.

**Comment by sindresorhus** [comment]
:+1: Great idea! I use the releases page a lot too. Another tab sounds good.

Interested in doing a pull request?

**Comment by hkdobrev** [comment]
Sure, I can suggest a PR later today or tomorrow though. That's why I wanted to make a suggestion and see if it's worth it.

**Comment by sindresorhus** [comment]
Cool. We could use this icon https://octicons.github.com/icon/tag/ (already part of the font icon on the site), unless you have a better suggestion.
