### ISSUE TITLE
Change default sort in issue tracker to "Recently updated"

### ISSUE THREAD

**Issue by mojavelinux** [sindresorhus/refined-github#80]
The Newest sort option in the issue tracker is rarely useful and not at all what I expect as the default sort. I want to see where the activity is. That's likely what needs my attention most. An update to an old issue and the addition of a new issue should have the same weight. Otherwise, old issues with recent activity stay buried.

I propose modifying the URL of the main Issues tab so the issues are sorted by Recently updated (in descending order) instead of Newest. That can be accomplished by adding the following query string:

```
?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc
```

**Comment by sindresorhus** [comment]
:+1: I always sort it by `Recently updated`.

@paulmolluzzo @hkdobrev What do you think?

**Comment by hkdobrev** [comment]
I think it's useful for some cases, but not useful for others.

Of course it is useful when you to respond to latest activity, but not useful when there's a high-activity open-source repository and you want to try to close new issues and PRs fast and look at some long-running issues/PRs just from time-to-time. Image issues with a lot of +1 comments or PRs with a lot of code review comments from others.

Whether `Recently updated` should be the default depends on what you do most often. For me personally most of the time I'd prefer the default sorting of `Newest`. Especially for work repositories, even the activity is from a few people, I'd prefer to look at the exact same order every time similar to a Trello board which we are also using. We have Slack and GitHub notifications for every comment.

I'm not sure if this is a commonly shared logic and I'm not even sure having `Recently updated` by default would not be useful to me and I just don't realise it yet.

What do you think of having a button which toggles between the two instead of having to click the drop down to the right?

**Comment by paulmolluzzo** [comment]
No strong opinion from me, except that I might get confused by changing the default (I don't know for sure).

I don't usually sort issues, tbh. When I'm triaging maybe?

**Comment by mojavelinux** [comment]
Adding a toggle button like @hkdobrev suggested would be my second choice.

In fact, it's the cognitive strain caused by the Sort drop down that initially motivated this request. I was finding that I'd navigate to a GitHub repository, click Issues, not immediately see the issue I wanted, click Sort and then... ... ... (blink) ... ... try to read the words and figure out which one applied to my case. The one I really need (Recently updated) sits second to the bottom, below options related to comments which sort of look the same.

That makes me think that the underlying issue here is that the Sort drop down causes cognitive strain. Too many options without enough differentiation.

**Comment by mojavelinux** [comment]
I'll provide a use case that explains why Recently updated comes up the most often.

I pick an issue to work on (perhaps because it came in via e-mail), do some coding, send a PR that references it (or perhaps someone else does). That's the issue on my mind (and others I worked on that day). I go to the Issues tab to follow-up on the issues, perhaps to add some additional notes or get information from an ongoing discussion. Where are those issues? No where to be found. Instead, what I see is new issues that came in since that have nothing to do with the activity going on in the project.

The projects that this most affects are projects with lots of activity, because new issues are always coming in and occupying the top slots in the Newest sort.

**Comment by hkdobrev** [comment]
Despite the obvious stand against options in this extension (which is quite right), this is the feature I feel is most suitable for an option. Of course in best case scenario that would be an option provided by GitHub itself similar to default diff view - split vs unified. When you choose a sort view, this could be persisted until you change it.

So I have 2 suggestions without adding options to the extension:

1. Add just a toggle button for newest/updated issues.
2. Implement persisted sort across repos which always uses the sort option you've selected last.

**Comment by mojavelinux** [comment]
Persisted sort definitely sounds intriguing.

**Comment by hkdobrev** [comment]
Just wanted to say I've tried this a couple of weeks ago and it isn't easy. Initially I thought I could fiddle directly with the URL - nope, GitHub changes the URLs in a few ways and also there are multiple URLs with the same search (e.g. `/search/label/bug` is the same as `/search?q=label....` and others). Then I've started playing with clicking the sort drop down and around that time I lost interest. With persisting the sorting you need to consider pages where both issues and PRs are listed and pages where there is a sorting, but with different sort options and the chrome storage is asynchronous and the sorting would change after a while and sometimes is slow and so on and so on. I don't say it's impossible to is, it is, but it's not easy. And it's really easy to do from the back-end just like how GitHub persists diff style - unified vs split.

That said I just wanted to warn people who think about taking this, I'll be willing to assist when possible.

However I think it'd be more useful to contact the GitHub team about it and say "please" :smile:

**Comment by giampaolo** [comment]
Definitively something I'm also looking for.

**Comment by pgorod** [comment]
I would also be interested. While it's not implemented, if anybody knows a workaround (some browser extension that can tweak html, for example), please share here. My desired behavior would be to change the tabs saying "Issues" and "Pull Requests" to a different URL (to specify my sorting preference). Thanks.

**Comment by BlaineBradbury** [comment]
yes, recently updated is the way to go

**Comment by giampaolo** [comment]
Google Code allowed to change the default via the settings tab. I think the best option is to maintain backward compatibility by keeping the current sort, but give administrator the ability to change it via the settings tab.

**Comment by r10s** [comment]
I would also like "recently updated" as my default issue ordering. An option would be the way to go.

**Comment by smeijer** [comment]
Especially for milestones, this would be awesome. Milestones are currently sorted on "recently updated", while "closest due date" is more useful in my opinion.

**Comment by bfred-it** [comment]
What's the decision on this?

I went ahead and implemented it as a simple change: default the tab to **Recently Updated**.

> Implement persisted sort across repos which always uses the sort option you've selected last.

I'd hate to find the issues in whatever weird order I checked the previous time. It should always be the same

> there are multiple URLs with the same search

The problem with touching the (issues/PRs) search is that you're gonna have to intercept XHR calls and/or visually change the search field under the user's eyes.

> Add just a toggle button for newest/updated issues.

One click vs two clicks. Perhaps it isn't enough of a time saver at that point.

**Comment by bfred-it** [comment]
@sindresorhus Open to make it an option?

**Comment by sindresorhus** [comment]
@bfred-it Can't we just make it the default?

**Comment by bfred-it** [comment]
Ask @hkdobrev and @jgierer12: https://github.com/sindresorhus/refined-github/pull/454#issuecomment-305630032

**Comment by nikohansen** [comment]
I would be in favor if the search field were to remember the search options/filter. Or, alternatively, there could be a user-defined default search filter. That would solve the sort-problem en passant.

**Comment by csb0730** [comment]
Please simply add a user defined option in settings for sort order. That's it.

**Comment by monperrus** [comment]
> I went ahead and implemented it as a simple change: default the tab to Recently Updated in #454

Is that already in the released version?

**Comment by bfred-it** [comment]
No

**Comment by monperrus** [comment]
Looking forward to it, that will be super useful!

**Comment by milholen** [comment]
Another vote here for using "Recently Updated" as the default sorting order.

**Comment by bfred-it** [comment]
Sorry peeps, this is now _coming like a wrecking ball_ (except you can now disable it in the options 😉)

**Comment by monperrus** [comment]
Is that feature already deployed?

**Comment by bfred-it** [comment]
Yes

**Comment by mojavelinux** [comment]
And it's a game changer!

**Comment by bsarrazin** [comment]
I just installed this extension recently and can't say how annoyed I am with this feature. Is there a way to turn it off?

**Comment by jgierer12** [comment]
@bsarrazin Yes, by opening the extension settings and pasting `sort-issues-by-update-time` into the "Features to disable" textbox

**Comment by bsarrazin** [comment]
@jgierer12 thank you sir! 🌮

**Comment by koppor** [comment]
Currently, one has to go to the settings of the extension and search for `sort-issues-by-update-time`. It is just a checkbox - not a generic free text field anymore:

![image](https://user-images.githubusercontent.com/1366654/60397385-062e5e80-9b4d-11e9-84dd-4ee49e10190d.png)

**Comment by koppor** [comment]
As of today, it is [sort-conversations-by-update-time](https://github.com/sindresorhus/refined-github/blob/6d339762d762b669bb48b2977f40a83c48305a2d/source/features/sort-conversations-by-update-time.tsx):

![grafik](https://user-images.githubusercontent.com/1366654/96798242-c144d000-1400-11eb-9974-d52510510468.png)

**Comment by KSH-code** [comment]
Thank you @koppor 
I was inconvenient to sort all of PRs by update time by default.
btw, how do I find how use some of features.
I think refined github provides good solutions but I could have not found.

**Comment by rshea0** [comment]
It's quite annoying how GH puts milestones without a due date first. Most of the times milestone version numbers are alphabetical. Could we just get an option to set what we want the default sort to be?
