### ISSUE TITLE
Mark as unread button spacing is off

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#810]
![screen shot 2017-11-13 at 16 50 43](https://user-images.githubusercontent.com/506129/32731611-fbd033ac-c892-11e7-8efe-218d23f2855c.png)

The button for marking an issue/PR as unread in notifications after you've looked at it is a bit off in terms of styling. There should be a bit of space between the "Subscribe"/"Unsubscribe" and the "Mark as unread" buttons.

The space used to be there but got broken either because of changes from GitHub or CSS changes on our side.

**Comment by yakov116** [comment]
@hkdobrev are you using chrome canary?

**Comment by hkdobrev** [comment]
Good catch! I'm using Chrome Dev build version 64. Do you think it's a Chrome issue which would get fixed on its own or should we do something about it?

**Comment by yakov116** [comment]
@hkdobrev wait for google. I had this in version 42, where they messed up the css. Yeah may seem like a long time ago, but i'll never forget how they messed my whole site. I spend about 5 hours trying to figure out what in the world went on! 😆 
That's when i switched to having both on my computer.
