### ISSUE TITLE
Download specific folder?

### ISSUE THREAD

**Issue by tom-sherman** [sindresorhus/refined-github#815]
Sometimes you're browsing through a massive codebase and want to download a suite of files, sometime there a single example in the docs which you want to download. Is this possible?

**Comment by bfred-it** [comment]
I can't fine the endpoint. This is what we currently have:

```sh
# single file
https://github.com/sindresorhus/refined-github/raw/master/package.json
https://raw.githubusercontent.com/sindresorhus/refined-github/master/package.json

# whole archive
https://github.com/sindresorhus/refined-github/archive/master.zip
https://codeload.github.com/sindresorhus/refined-github/zip/master
```

But these don't work for folders:

```sh
https://github.com/sindresorhus/refined-github/raw/master/media #  redirects to the regular view
https://raw.githubusercontent.com/sindresorhus/refined-github/master/media # 404
https://github.com/sindresorhus/refined-github/archive/master/media.zip # downloads the whole repo
https://codeload.github.com/sindresorhus/refined-github/zip/master/media # 404
```

**Comment by bfred-it** [comment]
Some extensions/webapps download all the files separately and then zip them up:

https://chrome.google.com/webstore/detail/gitzip-for-github/ffabmkklhbepgcgfonabamgnfafbdlkn

https://www.google.com.tw/search?q=download+folder+github

**Comment by tom-sherman** [comment]
@bfred-it Download the whole thing temporarily, unzip and rezip the desired subdirectory?

**Comment by yakov116** [comment]
@tom-sherman imagine doing that to 500MB repo...

**Comment by bfred-it** [comment]
Closing this for now. The only way this would get included would be if there was a site that downloaded each file and then zipped them up. We'd just link to it and the download should start. Perhaps ask for it in https://github.com/sindresorhus/module-requests/

In the meantime the linked extension should work (gitzip)

**Comment by bfred-it** [comment]
It turns out that GitZip exists as a standalone tool as I described it, however it requires an personal token and the interface is superfluous. 

Example: https://kinolien.github.io/gitzip/?download=https://github.com/KinoLien/gitzip/tree/gh-pages

**Comment by tom-sherman** [comment]
I'm not entirely sure of the capabilities of web workers/service workers, but is it not possible to unzip/rezip using them along with IndexedDB for temporary storage?

**Comment by bfred-it** [comment]
I’m not sure of what your intent is. The tool I built for this fetched each file into a `Blob` object and then passes them to JSZip

**Comment by tom-sherman** [comment]
@bfred-it The intent being to download and extract the desired sub-directory client side

**Comment by bfred-it** [comment]
I just implemented it as an external tool because:
- relatively unused feature 
- JSZip is bigger than the whole Refined GitHub extension
