### ISSUE TITLE
The editor buttons are being removed by the extension

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/refined-github#823]
Without the extension, you get these buttons, which I like:

![image](https://user-images.githubusercontent.com/54934/33085973-8eb3bf78-cee6-11e7-948c-4241f3d792d1.png)

Is this on purpose? If it is on purpose, could it be made optional?

**Comment by yakov116** [comment]
#779

**Comment by hkdobrev** [comment]
@wmertens Thank you for your suggestion! As @yakov116 pointed out, this exact issue is described in #779. I'm closing this as a duplicate. Please feel free to continue the discussion there or open a PR to discuss implementation once there's a consensus. Thank you!
