### ISSUE TITLE
Add option to have no-whitespace diffs permanently

### ISSUE THREAD

**Issue by monperrus** [sindresorhus/refined-github#824]
It would be great to add an option to have no-whitespace diffs permanently

**Comment by sindresorhus** [comment]
I don't think that's a good idea. You can't add inline comments/review in "no-whitespace" diffs.

**Comment by monperrus** [comment]
Then, the user who has set it by default can click on "With whitespace" to inline-comment.

**Comment by bfred-it** [comment]
Closing as there's consensus against it.
