### ISSUE TITLE
Dropdowns and other selections (labels) are rendered inactive

### ISSUE THREAD

**Issue by battlemidget** [sindresorhus/refined-github#826]
![screenshot-github com-2017-11-25-11-52-38-121](https://user-images.githubusercontent.com/51892/33232614-410c50c0-d1d7-11e7-98e2-7dbc46e41e49.png)

When trying to select my profile or assign labels to issues the entire page is rendered inactive and no selections can be made.

This is on Ubuntu 16.04 running Version 62.0.3202.94 (Official Build) (64-bit) of google chrome

**Comment by bfred-it** [comment]
Can’t test now but I suppose they changed some z-index

**Comment by bfred-it** [comment]
Can't reproduce

<img width="1045" alt="profile dropdown" src="https://user-images.githubusercontent.com/1402241/33436620-296c36c0-d618-11e7-9e68-269095ffa52e.png">
<img width="804" alt="label dropdown" src="https://user-images.githubusercontent.com/1402241/33436622-29cb16c2-d618-11e7-8380-76badfa90dd1.png">

**Comment by battlemidget** [comment]
I assume you tested on same version of chrome? distro? obviously a still a bug to me because it still is broken.

**Comment by bfred-it** [comment]
It works on Chrome 62, the distro shouldn't matter. There's more likely a some conflict with other extensions or userstyle.

- Can you test in a new/empty browser profile?
- Why is the backdrop above the content? (i.e. can you find their z-indexes?)
