### ISSUE TITLE
Add extra information on project board

### ISSUE THREAD

**Issue by fabio-baia** [sindresorhus/refined-github#829]
show when issue was created

**Comment by hkdobrev** [comment]
@fabio-baia Thanks for the suggestion, but I don't think this would be possible using the DOM as I can't find any timestamp in the project cards. That could either be achieved on GitHub's side or using the GraphQL API in the future to get all timestamps for the visible cards on the page.

**Comment by bfred-it** [comment]
Closing this as little interest, unclear suggestions and generally opposite direction of Refined GitHub (it hides Projects wherever possible)
