### ISSUE TITLE
Github review - unable to use "Submit Review" dialog

### ISSUE THREAD

**Issue by baohx2000** [sindresorhus/refined-github#836]
When I bring up the submit review dialog, a modal overlay shows up, disabling me from clicking on the dialog itself.
![modal-issue](https://user-images.githubusercontent.com/486322/33671532-19ba44d2-da65-11e7-9916-bbec7657c578.png)

**Comment by KnupMan** [comment]
I have the same problem

**Comment by ramlmn** [comment]
Bug added by https://github.com/sindresorhus/refined-github/pull/835/commits/590baa2a2575fb448820fb0217f83ba1a067c753.

Changing `z-index` of `28` worked for me!

/cc @bfred-it

**Comment by bfred-it** [comment]
Pushed a hotfix to the stores

**Comment by radu-matei** [comment]
Interesting, I am seeing the same behaviour and I just installed from the Firefox store:

![refined-gh](https://user-images.githubusercontent.com/13103165/53242233-d78b0d80-36ac-11e9-8e4b-eef4693884d5.png)


See below:

![refined-gh](https://user-images.githubusercontent.com/13103165/53242238-dfe34880-36ac-11e9-9f5b-bc745a079afa.gif)

**Comment by nesl247** [comment]
@radu-matei See #1805
