### ISSUE TITLE
Unable to give review changes

### ISSUE THREAD

**Issue by raz-adroll** [sindresorhus/refined-github#839]
Steps:
- Go to any PR
- Click "Files changed" tab
- Click "Review changes"

I should be able to click any option or write a comment.

But instead this gray overlay happens and as soon as I click anything it disappears along with all options.

![screen shot 2017-12-06 at 4 02 46 pm](https://user-images.githubusercontent.com/17753587/33687818-07deca82-da9f-11e7-8d20-91c6ec8a471d.png)

**Comment by yakov116** [comment]
@raz-adroll restart your chrome. This was fixed about 3 hours ago

https://github.com/sindresorhus/refined-github/releases/tag/hotfix
#836 efc8c307ccddb0b3558270e28551492bb3eb5a65
