### ISSUE TITLE
Be able to easily mass move repositories to another user or organization accounts

### ISSUE THREAD

**Issue by timofonic** [sindresorhus/refined-github#841]
Hello.

I really like GitHub, really. I think it's a great place to share and look other's people code!

Maybe it's my OCD, but I like to fork every project I'm interested in. Unfortunately, this mania made me have an unsustainable mess: 500+ plus +170 projects in timofonic + TimofonicJunkRoom.
 
I'm currently moving lots of forks to organization accounts, but I only found [this](https://gist.github.com/oriolgual/a5ac8139120d06b51b16b902c324d530) Selenium script to more or less automatize the task.

Despite the lack of an ideal solution, it's far from being an ideal solution and moving projects is still a very time consuming task. I would prefer a MidnightCommander-like UI, it would be a lot easier.

I suggested this to the Github's [hub](https://github.com/github/hub/) project at [issue 1634](https://github.com/github/hub/issues/1634) too.

I also wrote about this in [issue 277](https://github.com/dear-github/dear-github/issues/277) at [dear-github](https://github.com/dear-github/dear-github/) repository, a place I consider GitHub company members should look at for interesting feedback.

Kind regards.

**Comment by bfred-it** [comment]
I don't think this belongs to RGH. It makes sense as a command line tool, given its rare use, not as an extension.

**Comment by timofonic** [comment]
@bfred-it Okay, thanks. I already submitted it to hub project. Do you recommend me any other candidates?

**Comment by sindresorhus** [comment]
I agree. It would be better as a command-line tool.

You could try posting in https://github.com/sindresorhus/module-requests/issues
