### ISSUE TITLE
Make issue sidebar sticky

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#842]
I wish this could be implemented via a simple `position: sticky` but sometimes the sidebar might be taller than the viewport. Facebook handles this correctly in the profile sidebar on the desktop site.

Last time I did this I used `sticky-kit`, but alas it's a jQuery plugin.

See the behavior I'm looking for on the demo page, under _"Not sure if your sidebar or your main content is taller?"_ http://leafo.net/sticky-kit/

**Comment by ramlmn** [comment]
[Reference on Web Fundamentals](https://developers.google.com/web/updates/2017/09/sticky-headers)

**Comment by bfred-it** [comment]
That's a good article, but I don't think it contains a solution to the _taller than the viewport_ issue.

**Comment by ramlmn** [comment]
> but I don't think it contains a solution to the taller than the viewport issue.

That part, we have to figure out by ourselves!

**Comment by jgierer12** [comment]
> I wish this could be implemented via a simple position: sticky but sometimes the sidebar might be taller than the viewport.

`position: sticky` already handles that correctly by default: https://codepen.io/jgierer12/pen/GOVvOw

**Comment by bfred-it** [comment]
> position: sticky already handles that correctly by default: codepen.io/jgierer12/pen/GOVvOw

I didn't realize, but that's not very useful on long pages since it forces you to scroll all the way down to scroll the sidebar:

![long pages](https://user-images.githubusercontent.com/1402241/33795467-dd8d666e-dd1c-11e7-9d61-83b5c1c74679.gif)

**Comment by ramlmn** [comment]
> `position: sticky` already handles that correctly by default

The problem here is:
* **not only** when **viewport < content < sidebar**, which is handled by default using `position: sticky`
* **but also** when **viewport < sidebar < content** (in the demo as _Scrollable Sticky Element_)

**Comment by ramlmn** [comment]
Sorry if I am being ambiguous, but I was referring to **comment thread** as **content**, and condition when **viewport height < sidebar height < comment thread height**, as you demonstrated in https://github.com/sindresorhus/refined-github/issues/842#issuecomment-350456303

**Comment by bfred-it** [comment]
Sorry I misinterpreted. So yes, the gif was already proof :)

**Comment by jgierer12** [comment]
If it should be scrollable, we could just do

```css
max-height: 100vh;
overflow-y: scroll;
```

Like this: https://codepen.io/jgierer12/pen/vWoWgX

**Comment by bfred-it** [comment]
Not a fan of nested scrollbars 😕

**Comment by jgierer12** [comment]
How else would you solve it if not with scrollbars or the default `position: sticky` behaviour?

**Comment by bfred-it** [comment]
Like `sticky-kit` does, but without jQuery

**Comment by jgierer12** [comment]
Ah, I see now. That would be cool, but I'm not sure if it would be worth the effort if we can just do the scrollbar-based thing in CSS.

**Comment by bfred-it** [comment]
Perhaps it can just be done the old way: `if it fits, make it sticky` (repeat on resize)

**Comment by jgierer12** [comment]
> if it fits, make it sticky

That would be a good solution too. Especially since sidebar > viewport doesn't happen that often either.
