### ISSUE TITLE
Can't Add Review to PRs

### ISSUE THREAD

**Issue by danigol** [sindresorhus/refined-github#847]
Had to disable plugin. Every time I attempted to post a review, the review dropdown would be grayed out, and clicking anywhere within it would only close the review box.

**Comment by yakov116** [comment]
@danigol please restart your chrome

**Comment by hkdobrev** [comment]
@danigol Thanks for opening an issue! Could you please force-update the extension and try again? Go to `chrome://extensions`, enable the developer mode and click the update button. If that doesn't work, you can restart your browser.

And thanks for using Refined GitHub!

**Comment by danigol** [comment]
Apologies, I should have mentioned this was Firefox Quantum. I'll give it a restart, see if that works.

**Comment by danigol** [comment]
Restart did not solve the problem.

**Comment by bfred-it** [comment]
Mozilla blocked the last update. You'll have to load it locally until they accept it. A fix was pushed for #836
