### ISSUE TITLE
Blur textarea after posting a comment

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#848]
I often post a comment with <kbd>⌘</kbd>+<kbd>↵</kbd> and then try go to the notifications or PR list with a keyboard shortcut - e.g. <kbd>g</kbd>,<kbd>n</kbd>.

However, the comment field is still focused after posting my comment and I just end up typing `gn` in the textarea.

I suggest to trigger blur (unfocus) on tne textarea after successful submission so keyboard shortcuts on GitHub work immediately.

I don't think posting subsequent comments is often enough to be a problem.

An alternative approach which I also like is to map <kbd>Esc</kbd> to blurring the textarea.

**Comment by bfred-it** [comment]
shift+tab should also unfocus the textarea

**Comment by vjpr** [comment]
> I suggest to trigger blur (unfocus) on tne textarea after successful submission so keyboard shortcuts on GitHub work immediately.

This conflicts with: https://github.com/sindresorhus/refined-github/issues/858

> An alternative approach which I also like is to map Esc to blurring the textarea.

This would be much better.

**Comment by bfred-it** [comment]
> An alternative approach which I also like is to map Esc to blurring the textarea.

I like this one, but we need to figure out how to do this since Esc is currently mapped to "Cancel inline comment"

https://github.com/sindresorhus/refined-github/blob/d7768508c3919558daa6b2ccc5a15aa73d081551/source/features/add-keyboard-shortcuts-to-comment-fields.js#L51-L57
