### ISSUE TITLE
Collapse buttons are not added to new files changed view

### ISSUE THREAD

**Issue by hkdobrev** [sindresorhus/refined-github#85]
After recent changes to pull requests from GitHub, the maximise/minimise buttons are still added on single commit page and the compare page, but not on the PR files changed page which is now used when looking at a commit in a PR as well.

The collapsing still works though.

Admittedly there is no much space to put them and I don't find them so useful anyway. If you think they are needed we can move them in the dropdown for diff options where they've moved the split/unified diff buttons. Keep in mind GitHub has kept the old split/unified buttons like they were before on compare and commit pages.

**Comment by sindresorhus** [comment]
// @tdlm

**Comment by hkdobrev** [comment]
@sindresorhus @paulmolluzzo @tdlm Do you think we can remove the buttons the toggle all files and just keep the functionality when you click on file headers? That would be my preference.

**Comment by sindresorhus** [comment]
> That would be my preference.

Mine too.
