### ISSUE TITLE
Avoid jump caused by recently pushed branches

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#851]
This is generally useful, but sometimes you can't send a PR _right now_ so it'll keep pushing your content down about a second after page load, messing with your clicks. Perhaps we can make this less intrusive?

<img width="1004" alt="screen shot 2017-12-08 at 17 56 47" src="https://user-images.githubusercontent.com/1402241/33760623-3763b86e-dc41-11e7-90f6-1ae5bf2884ee.png">

**Comment by bfred-it** [comment]
Example:

<img width="396" alt="screen shot 2017-12-08 at 18 04 26" src="https://user-images.githubusercontent.com/1402241/33760879-4502ed68-dc42-11e7-8b11-a450345c6d5b.png">

1. `groupButtons()` out of **New pull request**
2. Add button with dropdown icon
3. Move `.RecentBranches` to a `<detail><summary>` like GH does everywhere
4. Hide **Compare && pull request** text from buttons

**Comment by hkdobrev** [comment]
I like the visibility of it and I always use it when I haven't created the PR through `hub` already. I see team members use it as well.

I'm 👍 on changing it to not push content, but I don't want to hide it under a button click. It could be like a dismissable alert or a drop down opening by default.

**Comment by bfred-it** [comment]
> I like the visibility of it

Agreed, perhaps it's best to just make it a `position: absolute` overlay so it doesn't push things down.

<img width="628" alt="1" src="https://user-images.githubusercontent.com/1402241/33761802-46adb0e6-dc45-11e7-8b5e-d95e0002d1d2.png">

<img width="627" alt="2" src="https://user-images.githubusercontent.com/1402241/33761800-462656fa-dc45-11e7-921b-728e92ec72fd.png">

Making it dismissable however is a whole other can of worms.

**Comment by hkdobrev** [comment]
99% of the cases you would have a single branch, we could probably shrink it just a bit so it fits the height of the tab row and looks nicer.
