### ISSUE TITLE
Account switcher isn't moved to sidebar on `Discover repositories` page

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#857]
Title says everything. Compare https://github.com to https://github.com/dashboard/discover (make sure you're logged in).

**Comment by jgierer12** [comment]
Seems like the page detection regex for the dashboard needs to be updated:

https://github.com/sindresorhus/refined-github/blob/b79db6e01895cda023e8bd2e89809e5456f390e7/source/libs/page-detect.js#L38

**Comment by bfred-it** [comment]
Yep I think we can just drop the index part: `dashboard([/]index[/]\d+)?)?$/` can become `dashboard([/]|$)/` so it matches any subpages of `/dashboard/`

**Comment by ifvictr** [comment]
#859 will fix this issue.
