### ISSUE TITLE
Pressing `up` key to edit your last Issue comment

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#858]
Just like Slack does. Makes it easy to edit your last comment for grammar, typos, etc.

Only would work when:

- text area is the `Leave a comment` box at the bottom of issues (not when editing a comment)
- text area is empty

**Comment by jgierer12** [comment]
I think it would be better (and easier to implement) to scroll to the comment and 'click' the edit button.

**Comment by bfred-it** [comment]
I just realized that this is the opposite of #848

**Comment by vjpr** [comment]
`escape` - blur (then you can use github keyboard shortcuts)
`up` - edit comment
