### ISSUE TITLE
Autoload contribution activities on scroll down

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#861]
This is already done for the newsfeed. It'd be nice if this was also made available for the contribution activities on user profiles.

**Comment by bfred-it** [comment]
I think this is a no-brainer 👍

**Comment by yakov116** [comment]
together with #745

**Comment by brucekchung** [comment]
Hi there! I’m a first-time contributor and was hoping to help out with this issue. I noticed nobody was assigned to it, but if there’s already a solution in progress I’m happy to try helping out elsewhere. Thanks!

**Comment by yakov116** [comment]
@brucekchung go ahead!

**Comment by goodalls** [comment]
Hi I am working with @brucekchung and @lexbonder for this issue and was wondering if you wanted us to throw in a test for the feature? if so, where would you like it, should we make a separate file for the feature?
