### ISSUE TITLE
Switch review and pr comment as default submit buttons

### ISSUE THREAD

**Issue by lode** [sindresorhus/refined-github#866]
I personally dislike the new 'review comments' style of commenting on a PR. In our team it is blocking our workflow. <sub>I've also [written about this problem](https://medium.com/@lodeclaassen/how-to-make-pull-requests-great-for-informal-teams-c2c46c6bec80).</sub>

![a single comment vs start a review](https://user-images.githubusercontent.com/511245/33874078-cb12d7b4-df1d-11e7-8ed7-4381ed2f6400.png)

Right now I just skip the big green button and always use the grey 'add single comment' button. But every now and then I make the mistake and reverting is annoying. It would be great to switch the default submit button or to just kill the 'start a review' button at all.

I can imagine other people really like the new comment style, but making it an option would be a great solution.

**Comment by bfred-it** [comment]
Considering the discussion in #312, this is unlikely to happen.

#751 however could be your workaround

**Comment by lode** [comment]
Thanks for the pointer!
