### ISSUE TITLE
Navigate from current repository to overview

### ISSUE THREAD

**Issue by Autarc** [sindresorhus/refined-github#87]
Could be that this is something only bugging me, but perhaps others find it also annoying:
after I've looked at a repository and wanted to know what other projects the creator has (by clicking on the link with his name), I will be navigated to his profile overview. Although it contains information about his contributions, it unfortunately doesn't provide a good overview about the stuff he created. So what do you think about changing this link towards the repository overview by default ?

[Contributions](https://github.com/sindresorhus?tab=repositories) | [Repositories](https://github.com/sindresorhus?tab=repositories)
:-----------------:|:-----------------:
![github-user-contributions](https://cloud.githubusercontent.com/assets/1060490/13845628/89fd04f0-ec41-11e5-9027-054d445715f0.png)|![github-user-repositories](https://cloud.githubusercontent.com/assets/1060490/13845630/8bcda10e-ec41-11e5-8307-60847e6d392f.png)

**Comment by hkdobrev** [comment]
:-1:

Repositories tab sorry projects by recently updated. The default cute at least shows the most popular projects of that author. I find that more useful. That said I often navigate to the repositories tab, but not as often as I need the default view.

**Comment by sindresorhus** [comment]
I think both tabs are about equally useless by default. Instead, maybe there's something we could improve in the `Contributions` page itself?

Personally I'd like to see the `Contributions graph` gone as it's completely useless and even inaccurate as it only shows commits, but I guess that would be too controversial as many people think they need it, but they don't.

Another idea would be to fetch some of the items from the `Activity` tab and show them there. I often go to the `Activity` tab to see what the author worked on last. We could either fetch it or do an iframe.

Any other ideas? What would be useful to have on a profile landing page? What could we remove?

**Comment by hkdobrev** [comment]
@sindresorhus thanks for this. We could close this one and create a new issue to discuss what kind of enhancements we could do to the user profile.

> Personally I'd like to see the Contributions graph gone as it's completely useless and even inaccurate as it only shows commits

The contributions graph shows issues and PRs as well though.

**Comment by sindresorhus** [comment]
@hkdobrev Good idea: https://github.com/sindresorhus/refined-github/issues/89

Can you do your above comment there instead?
