### ISSUE TITLE
Possible improvements for the "embed linked gists" feature

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#870]
https://github.com/sindresorhus/refined-github/pull/820#issuecomment-349998432

> - [x] some gists may be long or have multiple files
   GitHub limits their embeds to 12 lines + scroll: <img valign="top" width="300" alt="gh" src="https://user-images.githubusercontent.com/1402241/33730770-f550c4e2-dbbb-11e7-81e7-ce2621c053bb.png">

> - [ ] there's no clear indicator of what file belongs to what gist like for the regular github.com auto-embeds: 
    <img width="691" alt="" src="https://user-images.githubusercontent.com/1402241/33722517-25436d10-dba5-11e7-9487-318cb3e8a91a.png">

> - [ ] there's no loading indicator, the content just pops into place at some point in whatever loading order

**Comment by scottnonnenberg** [comment]
In the Signal Desktop repository we frequently link to thousand-line gists, and they really don't work inline. I'd really appreciate a max lines limit for embedded files. For example: https://github.com/WhisperSystems/Signal-Desktop/issues/1884

**Comment by sindresorhus** [comment]
@scottnonnenberg I agree. What do you think would be a sensible line limit?

**Comment by sindresorhus** [comment]
Or should we just make it scrollable with a max height?

**Comment by yakov116** [comment]
> What do you think would be a sensible line limit?

This

**Comment by scottnonnenberg** [comment]
What I want to avoid is completely losing the context of the discussion. A limit of something like half the height of the current viewport would help ensure that.

**Comment by bfred-it** [comment]
Like GitHub already does with permalink embeds, they should be limited to 12 lines via `max-height` + `overflow: auto`

The other problem is when they are multiple files.

* Do we limit to ~12 lines combined?
* Do we avoid embedding?
* Do we group the files together? 
* Do we leave the original gist link?

**Comment by bfred-it** [comment]
@scottnonnenberg this pr ⬆️ should let you re-enable Refined GitHub until a comprehensive solution is devised.

**Comment by sindresorhus** [comment]
I think we should just avoid embedding if there are multiple files. The embedding feature is intended for simple gists.

**Comment by bfred-it** [comment]
Should we then show this info by the link? Otherwise the RGH user would think that the embed didn't work.

**Comment by sindresorhus** [comment]
Can't we just document in the readme that it only applies to single-file gists?

**Comment by bfred-it** [comment]
Sure, but since we still have to load the gist and count the files we might as well attach some info, e.g.

[https://gist.github.com/staltz/868e7e9bc2a7b8c1f754](https://gist.github.com/staltz/868e7e9bc2a7b8c1f754) _(2 files)_

**Comment by sindresorhus** [comment]
Yeah, showing the file count could be useful.
