### ISSUE TITLE
Add a button to quickly approve the PR

### ISSUE THREAD

**Issue by jacehensley-wf** [sindresorhus/refined-github#883]
Looking something like this:

![image](https://user-images.githubusercontent.com/12398382/34118930-9f64bb9a-e3dd-11e7-995e-4037acbbafe6.png)

When clicking that button it would mark the PR as approved with/without comment based on the textarea.

**Comment by sindresorhus** [comment]
Would be useful, but the "Comment" button should be to the far right, otherwise I'll press "Approve" accidentally all the time.

**Comment by jacehensley-wf** [comment]
Good point 👍

**Comment by yakov116** [comment]
I would have the approve the color Blue (or something like that)

**Comment by bfred-it** [comment]
I’m conflicted: approve without looking at the code?

**Comment by yakov116** [comment]
No its instead of going to the Dropdown and selecting approve

**Comment by bfred-it** [comment]
But the dropdown appears in the files tab. This comment form appears on where there’s no code visible.

**Comment by ekweible** [comment]
@bfred-it I often times go back and forth between the files and conversation view so that I can look at the diffs as well as other people's reviews. In doing so, I find that about half the time, I've ended up at the bottom of the page on the conversation view trying to approve with no way to do so (maybe it's still a force of habit from before reviews were a thing). In that scenario, though, I would find this useful.

**Comment by bfred-it** [comment]
One note: this PR requires a fetch of the **Files** tab to get the form with the token.

In alternative or in addition, I'd like to see this: 

<img width="295" alt="Accept + review" src="https://user-images.githubusercontent.com/1402241/34146122-b13a4cb2-e4d3-11e7-84a2-5d6933d67520.png">

And/or this:

<img width="434" alt="Review in two clicks" src="https://user-images.githubusercontent.com/1402241/34146273-4c9c01e6-e4d4-11e7-8ddb-0f989ea76929.png">

And perhaps that whole dialog can be also shown in the **Conversation** and **Commits** tabs. However in those tabs, the header bar is not `position: fixed` like in **Files**, so you'll have to scroll up.

**Comment by bfred-it** [comment]
Anything that can be done here? Or is https://github.com/sindresorhus/refined-github/issues/1069 preferrable?

**Comment by ekweible** [comment]
A shortcut to open the reviews panel from the conversation view would work for me 👍

**Comment by bfred-it** [comment]
The link would be:

```
https://github.com/user/repo/pull/1/files#submit-review
```

**Comment by felixfbecker** [comment]
I'd love this feature. I often review automated PRs for dependency upgrades, and approving them requires three clicks with loading time in between.

Could this button be placed in the top right so one doesn't have to scroll down the thread? E.g. below the notifications buttons, or next to the "edit" button for the title.

**Comment by mahkoh** [comment]
I'm not seeing the button. Has this feature been removed? 

<img width="363" height="212" alt="Image" src="https://github.com/user-attachments/assets/eca1c920-620e-4606-b65a-2a1eecf04f63" />
