### ISSUE TITLE
`Scroll to bottom` button for Issue comments page

### ISSUE THREAD

**Issue by vjpr** [sindresorhus/refined-github#892]
Often I receive a notification in Gitify or an email that a new comment has been made. I click on the link and I then have to scroll to the bottom of the issue to see the update.

A button at the top to jump to the bottom would be great.

**Comment by hkdobrev** [comment]
BTW just noticed today, GitHub provide a jump to bottom link on mobile now.

**Comment by sgr-amboss** [comment]
My 2 cents: I personally would not really need this, as I just press the <kbd>End</kbd> button on my keyboard to jump to the bottom of the page in those scenarios. I forgot how to do the same thing on Mac, but I am sure it's possible. What do the others think?

**Comment by hkdobrev** [comment]
I constantly do this with <kbd>⌘</kbd>+<kbd>↓</kbd> on macOS. I don't really use jump to top/bottom buttons on websites. On mobile it's sometimes useful and I appreciate GitHub adding it, but I won't be using it on Desktop.

**Comment by hkdobrev** [comment]
Also, since the OP issue is about email notifications, GitHub notifications in both emails and website include links to a direct timestamp so this is mostly taken care of. If 3rd party tools are not doing that, this is mostly a problem with them.

**Comment by jgierer12** [comment]
I think this is useful sometimes, for example if you want to add a comment without reading the whole discussion or quickly check on the current status of an issue. @hkdobrev maybe take a look at how I implemented it in #904 and see if that would be acceptable for you. It doesn't really add too much clutter to the UI, so if you don't need it you can just ignore it.

**Comment by bfred-it** [comment]
I don't think I ever used this button. Can we drop it? Like @hkdobrev said:

> I constantly do this with <kbd>⌘</kbd>+<kbd>↓</kbd> on macOS. I don't really use jump to top/bottom buttons on websites. On mobile it's sometimes useful and I appreciate GitHub adding it, but I won't be using it on Desktop.

**Comment by Stanzilla** [comment]
@bfred-it that's not a good enough reason to drop it, I'd prefer clicking a ui element over using a key combination sometimes.

**Comment by dwijnand** [comment]
Me too.  One specific difference to the example given (removing buttons that have shortcuts) is that is done with a Refined GitHub feature, which can be disabled.

Given this button is present on mobile, could this remain as a feature in RGH, perhaps disable by default so users may opt-in to using it?

**Comment by bfred-it** [comment]
> Given this button is present on mobile

Mobile doesn't have keyboard shortcuts

**Comment by dwijnand** [comment]
You're right.  Nonetheless, the user experience I'm presenting is that I was used to having a UI button available in both views.

Perhaps @Stanzilla and I represent only a small minority, compared to @hkdobrev and @bfred-it, and we should just retrain our muscle memory.

**Comment by yakov116** [comment]
I happen to use this all the time. Even though I am a keyboard fanatic _sometimes_ my mouse is in my hand

**Comment by equinox** [comment]
Would it really hurt that much adding this as an optional setting? Through this issue and the one referenced right above this, you can see at least a good handful of users want this (myself included) ...

**Comment by grahamperrin** [comment]
Switching from Waterfox Classic (with an old version of Refined GitHub) to Firefox. 

I miss this feature. 

IIRC the keyboard-only approach sometimes goes too far, causing the final (bottom) comment to not appear as it should.
