### ISSUE TITLE
Hide follow events

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#894]
Hide or not?

<img width="681" alt="X followed Y" src="https://user-images.githubusercontent.com/1402241/34194012-9bd61d38-e591-11e7-91cb-2991c6be5688.png">

Class is `.follow`

**Comment by lukaszklis** [comment]
I’d vote to hide it. Would you do the same for ”watch repository” events too, or would you decide on what to do about it in a separate issue?

**Comment by bfred-it** [comment]
Separate issue, but if those are hidden what's left?

**Comment by lukaszklis** [comment]
Oh, you meant to hide those events completely… What I meant was hiding the preview shown below.

**Comment by hkdobrev** [comment]
I like them, but prefer to hide the previews as @lukaszklis mentioned.

**Comment by sindresorhus** [comment]
👍 Let's do it

**Comment by AshikNesin** [comment]
Hiding follow event is done → #909 

Are we going to hide anything else?

**Comment by bfred-it** [comment]
#909 hides the preview only, which is already handled by #899. 

This issue should completely hide follow events.
