### ISSUE TITLE
Make the ”repository starred” event more compact

### ISSUE THREAD

**Issue by lukaszklis** [sindresorhus/refined-github#896]
Currently GitHub shows a preview of the repository on your dashboard whenever someone has starred it.
![repositories](https://user-images.githubusercontent.com/11782/34200631-115c306c-e572-11e7-9561-9e6f5a16e744.png)

I’d suggest simplifying it so dashboard would be super compact as it used to be.

I would suggest some approaches on how to handle this:

1. Hide those previews completely.
1. Add a link to expand the event with a preview.

WDYT?

**Comment by bfred-it** [comment]
I wouldn’t mind showing that box on hover, but smaller and not clickable, just as extra info since we already have it in the dom. It can likely be done with CSS only.

**Comment by tanmayrajani** [comment]
I noticed one thing with the stars on the preivew box. I think it shows the number of stars at the moment of the person starring and not the current number of stars which is.. weird! This might not help with the issue, but I wonder why it's kept this way..
