### ISSUE TITLE
extension requires very new version of Chrome

### ISSUE THREAD

**Issue by helix84** [sindresorhus/refined-github#9]
Extension currently requires Chrome 48. After downgrading the requirement to Chrome 45 in the manifest, I tested several features and it seems to work. I assume most of this extension is just rewriting site content anyway, so in theory, there's no reason why it wouldn't work on even very old Chrome versions.

**Comment by sindresorhus** [comment]
That's true, but I only test on the latest version of Chrome, and Chrome is auto-updating so shouldn't matter. Why do you care?

**Comment by helix84** [comment]
It's auto-updatimg by default on Windows :) On Linux, you're just offered a package, not a repo.

Me personally, I downgraded for some reason that I don't remember at the moment. Now I upgraded to Chrome 48, so I don't mind anymore. Still, it's good practice not to require newer versions of dependencies than necessary.

**Comment by sindresorhus** [comment]
Alright
