### ISSUE TITLE
Breaks reaction user list

### ISSUE THREAD

**Issue by Limess** [sindresorhus/refined-github#90]
It seems that the newly added github reactions are slightly broken by this plugin.

They appear as expected, however without the plugin I can hover the reaction and get a list of users who added it. With the plugin enabled this list doesn't display.

Example screenshot of working functionality:
![screenshot 2016-03-21 14 04 50](https://cloud.githubusercontent.com/assets/3199181/13921063/0622ef84-ef6e-11e5-9d20-c286787e35cf.png)

**Comment by sindresorhus** [comment]
Yeah, we remove all tooltips as most are completely useless. We should add an exception for this.
