### ISSUE TITLE
updateReleasesCount: Uncaught (in promise) TypeError: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by sompylasar** [sindresorhus/refined-github#901]
```
Uncaught (in promise) TypeError: Cannot read property 'textContent' of null
    at updateReleasesCount (content.js:1605)
    at add_releases_tab (content.js:1622)
    at enableFeature (content.js:806)
    at <anonymous>
```
```js
  function updateReleasesCount() {
    if (isRepoRoot()) {
      // >>>>>>>>>>>>>>>>>>>> THERE >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
      const releasesCount = select_dom_default()('.numbers-summary a[href$="/releases"] .num').textContent.trim();
      localCache = {
        [repoKey]: releasesCount
      };
      browser.storage.local.set(localCache);
    }
  }
```

**Comment by bfred-it** [comment]
What page did you see this on?

**Comment by sompylasar** [comment]
@bfred-it This was on a private repo, but I reproduced here: https://github.com/sindresorhus/refined-github/tree/faster-reviews?files=1

**Comment by bfred-it** [comment]
Wow, how did you get there? Even GitHub has bugs on that page

<img width="516" alt="screen shot 2017-12-22 at 10 44 50" src="https://user-images.githubusercontent.com/1402241/34283154-3f98f9da-e705-11e7-95d4-6313b7aeae22.png">

Anyway, updates are needed to `page-detect.js`

**Comment by sompylasar** [comment]
@bfred-it Yes, I noticed (even checked whether this or the issue links extension is causing that). A colleague sent me the link to his branch (in our private repo). I just replaced our org name, repo name, and branch name with this repo's ones.

**Comment by hkdobrev** [comment]
This is reproducible even on a repo homepage without the `tree` segment: https://github.com/sindresorhus/refined-github?files=1

```
https://github.com/sindresorhus/refined-github?files=1
```

**Comment by bfred-it** [comment]
I gave it a further look and I think that the two features need a more specific check (like isRepoRoot) and isRepoRoot needs to be updated to check for `files=1`

**Comment by bfred-it** [comment]
Also on empty repos: https://github.com/bfred-it-obsolete/empty

It'd be a good idea to add a check for that missing element, on top of the `page-detect` changes I suggested.
