### ISSUE TITLE
On Wiki Edit, Single Item Shows

### ISSUE THREAD

**Issue by brandon93s** [sindresorhus/refined-github#902]
I've seen this a few times. When a "wiki edit" is at the top of my feed, it's the only thing that shows up:

![image](https://user-images.githubusercontent.com/4730164/34287675-c9deaad0-e6b6-11e7-8512-aa0d5b7153f3.png)

**Comment by bfred-it** [comment]
Can you verify why that happens? What CSS rule is hiding everything else? Are you sure it’s Refined GitHub?

**Comment by brandon93s** [comment]
> Can you verify why that happens? What CSS rule is hiding everything else? Are you sure it’s Refined GitHub?

I'll follow up the next time it happens.

**Comment by bfred-it** [comment]
Closing this until it materializes again :)
