### ISSUE TITLE
Does not work with the Vivaldi Browser

### ISSUE THREAD

**Issue by Ryonez** [sindresorhus/refined-github#905]
I use the Vivaldi web browser, which is a chromium based web browser.

Unfortunately, right clicking it while on a GitHub site does not display an "Enable Refined GitHub on this domain." option.

Any clue as to the cause of this?

https://i.imgur.com/qpFgBPC.png

**Comment by jgierer12** [comment]
You have to left click, not right click. Just tested it in Vivaldi, works flawlessly.

**Comment by Ryonez** [comment]
I'm sorry, but no it's not for me.

This is how it looks with just a left click:
https://i.imgur.com/loTAbyu.png

There's no option to "Enable Refined GitHub on this domain."

**Comment by jgierer12** [comment]
Sorry, I misread your issue. I don't have access to GHE so I can't test it, unfortunately

**Comment by Ryonez** [comment]
It's alright, I'm just glad you didn't brush the response off.

Beside, a left click instructs me to:

```While on your GitHub, right-click on Refined GitHub's icon in the toolbar and select Enable Refined GitHub on this domain.```

I'm noticing that you're mentioning GHE. I'm assuming this is meant to be GitHub Enterprise.

I've been trying to do this for the normal site without thought that's it's activated on GitHub itself by default. But I've been trying the right click thing because none of the features seem to be activated.

**Comment by hkdobrev** [comment]
@Ryonez Do you get any errors in the browser's console?

**Comment by hkdobrev** [comment]
Could you try loading from a local clone as it's described in the [contributing.md](../blob/master/contributing.md) file?

**Comment by Ryonez** [comment]
It did block some files, seems an extension rearmed in the last 10 mins.
I turned it off again but still gives the same result (No features).

I can try making a clone, but it'll have to be in the next day or two, just heading off to play a game with the misses sorry.

**Comment by bfred-it** [comment]
Vivaldi doesn't seem to support `chrome.contextMenus.create`: it executes without errors but doesn't show anything in the browser action's context menu. Try reporting a bug there

**Comment by Ryonez** [comment]
That'd make sense if the other extensions didn't work, but they do.

No one has mentioned yet if this extension is on by default on the default GitHub site, which is where I'm having the issues.
GitHub.com isn't getting the extension features.

**Comment by bfred-it** [comment]
I misread the conversation too. That message is under "GitHub Enterprise" in the popup, it's not for regular GitHub.

I don't know why it doesn't work, but it works for all of us, so there must be something wrong with your browser. Try loading it in a new profile.

**Comment by bfred-it** [comment]
Are you logged in?

**Comment by Ryonez** [comment]
Could you guys stop prematurely closing this before I even respond!!! It's not resolved.

```I misread the conversation too. That message is under "GitHub Enterprise" in the popup, it's not for regular GitHub.```
Okay, I'll assume that means that yes, it's enable on github.com by default. This message still shows up on github though.

```I don't know why it doesn't work, but it works for all of us, so there must be something wrong with your browser. Try loading it in a new profile.```
I allowed the plugin in a private window to test. No other extensions loaded, still no Refined Github features working. (Currently just testing the copy/paste markdown feature)

```Are you logged in to GitHub? It doesn't work otherwise.```
I always login.

And I'm sorry, but the "it works for us" thing is a horrible attitude. I'm glad it works for you and all, but it's not for me. It's a bug, they aren't always clear what's happening.

It's like the controller issue I had with Final Fantasy ARR. As my ex infuriatingly kept pointing out to me, it worked fine for everyone else so it was all my fault. (I did find extremely rare reports with others having the same issue, but none tracked it down)
After a lot of work I narrowed it down to my computer constantly rescanning connected devices(Never figured out why, reinstalled the OS since then and no more issues). But the game was coded so that when the computer did that it'd ignore controller inputs even though the computer still saw the controller sending inputs. Oh, and while the game ignored new inputs, if it was receiving one when the device list refreshed, it'd just maintain that signal until the refresh was over. So say I was moving in the game, I'd continue moving until the refresh stopped, and then get control back.
So that was a problem caused by two issues. My computer scanning the devices constantly for no reason, and poorly coded controller handling in the game.

The point is what works fine for you doesn't mean it'll work fine with others.

**Comment by Ryonez** [comment]
Just noticed this, isn't this one of the features?
https://i.imgur.com/Hy3HeF9.png

If so it might be some work and some don't. Copy pasting the code blocks from in the thread aren't working.

**Comment by Ryonez** [comment]
I just went back to the the normal page (non-private) and reloaded. Names suddenly appeared.
Still can't seem to copy pate markdown though.

**Comment by bfred-it** [comment]
So it does work, but that feature specifically was disabled and is no longer in the readme. #640

**Comment by Ryonez** [comment]
Yup, seems some features are now working, yet others aren't
https://i.imgur.com/v4sRxpk.png

**Comment by Ryonez** [comment]
Oh I see. That'd explain why I can't find it in the readme anymore.

And the notification thing wasn't working because I made this issue. Right, got that.

Pity, the markdown copy looked really good.

Well, thank you for you time today and for going through this all with me. I hope you have a good one, and a merry christmas.

**Comment by bfred-it** [comment]
Specify what doesn't work specifically in separate issues with detailed information. "It doesn't work" pretty much gives you the same response across the internet, 😅  especially when it's on an unsupported platform.

**Comment by Ryonez** [comment]
I was was specific at the start, with screenshots and all.

And when I told you that I was switching to assuming it's meant to be on by default for github, I told you why I though it still wasn't working:
https://i.imgur.com/sFhMhMK.png

I like detail, and I did give it.

**Comment by bfred-it** [comment]
And sorry about the short responses. I'm hungry and I'm waiting for everyone to show up to eat. Enjoy your holidays too. 🎄

**Comment by jgierer12** [comment]
Yeah, I was just about to write, your issue really only affects a browser we never intended to support and no one on the team uses it, so you shouldn't be surprised if we aren't motivated to solve the issue (especially on Christmas day). After all, this is an open source project and you're always welcome to modify the code yourself to make it work for your setup.

Have a merry christmas everyone! 🎅 🎁

**Comment by Ryonez** [comment]
Ehh, we got there in the end. Food sounds good though.

**Comment by bfred-it** [comment]
We were all too quick to dismiss your issue, but your first screenshot showed various RGH features working for you as well :)

![qpfgbpcr](https://user-images.githubusercontent.com/1402241/34327050-92db87e2-e8f5-11e7-984d-aeaebc5d9663.png)

Please feel free to open issues for broken features.

**Comment by Ryonez** [comment]
0.0

I need to use github more is seems.
