### ISSUE TITLE
Newly pushed branch display "conflicts" with ZenHub

### ISSUE THREAD

**Issue by eramdam** [sindresorhus/refined-github#906]
I'm using [ZenHub](https://www.zenhub.com/)'s Chrome extension and I noticed that the way Refined Github displays newly pushed branches conflicts with the fact that ZenHub adds two new tabs on every repositories 😕 
![screen shot 2017-12-24 at 12 18 49 am](https://user-images.githubusercontent.com/1409924/34325213-3d55f1aa-e840-11e7-974e-af1942e8a514.png)

**Comment by bfred-it** [comment]
hmmm this is a CSS-only option that can't be disabled... unless we add a "JS feature" that adds a class to body and enables it.

Alternatives?

**Comment by hkdobrev** [comment]
We can detect number of tabs and activate it with a CSS class only if there aren't too many?

**Comment by bfred-it** [comment]
I think they live in different containers, can’t be done via CSS. But yeah, the “JS feature” I mentioned could also count the tabs automatically.

**Comment by travispett** [comment]
👍 I do not use ZenHub or any other Github related Chrome extensions and this blocks the "More" and "Settings" tabs.

<img width="1046" alt="screen shot 2017-12-29 at 1 30 20 pm" src="https://user-images.githubusercontent.com/3758609/34444643-8c767780-ec9d-11e7-85f4-1dbe85eba9a4.png">

<img width="1015" alt="screen shot 2017-12-29 at 1 38 34 pm" src="https://user-images.githubusercontent.com/3758609/34444657-9ca183b6-ec9d-11e7-878b-ae8660efedde.png">

**Comment by bfred-it** [comment]
Maybe we should just add that X to close it.

**Comment by ramlmn** [comment]
> Maybe we should just add that X to close it.

You would still be displaying it on every page load, which would still be annoying. Even if you make it closable, you lose it completely on close and only get it back on complete page refresh.

------------

How about "reveal on hover on bottom right/left corner"? (need some inspirations before implementing this though)

**Comment by bfred-it** [comment]
The good thing about this feature (I mean GitHub's) is that it's very visible. If we hide it it won't be as good. Maybe we just need to find a better position

**Comment by jgierer12** [comment]
> by covering the watch/star/fork buttons

👍, can't think of a use case where you'd need one of those while already working on the project
