### ISSUE TITLE
API calls yield `NetworkError` in Firefox

### ISSUE THREAD

**Issue by jgierer12** [sindresorhus/refined-github#913]
API calls don't work and the `fetch` promise in https://github.com/sindresorhus/refined-github/blob/master/source/libs/api.js gets rejected with `NetworkError when attempting to fetch resource.`.

Edit: `fetch('https://github.com/')` works, `fetch('https://api.github.com/')` doesn't so it appears to be a CORS problem. Not sure what can be done about it.

**Comment by leggsimon** [comment]
FWIW it works for me fine on FF v57

**Comment by jgierer12** [comment]
The bug originally occurred to me on FF Nightly (59.0a1), but I just tested it on FF 57 and it's the same there for me.

**Comment by jgierer12** [comment]
@leggsimon did you modify any CORS specific settings? I'm not sure if this is a bug in FF or if it's intended.

**Comment by leggsimon** [comment]
@jgierer12 No I didn't
