### ISSUE TITLE
Add language next to repo name in dashboard

### ISSUE THREAD

**Issue by renatorib** [sindresorhus/refined-github#917]
It is a common task to make a "mental filter" in the timeline repositories based especially in the name and language. If I do not write in Rust I do not want to see Rust's repos. That way I can know which ones can interest me just looking at the name and realizing that it's a language I use or interest me.

I already do this, but I need hovering all repos to see the language in the popover.

![image](https://user-images.githubusercontent.com/3277185/34389316-0e67c5ac-eb20-11e7-90f6-cbd56d39c7f2.png)

**Comment by bfred-it** [comment]
This can be replaced by #922

**Comment by bfred-it** [comment]
Fixed by https://github.com/sindresorhus/refined-github/pull/1045
