### ISSUE TITLE
Add quick review buttons throws on merged PR

### ISSUE THREAD

**Issue by leggsimon** [sindresorhus/refined-github#918]
https://github.com/sindresorhus/refined-github/blob/7aad28997cdd9d6627c6620e242a17308f259897/source/features/add-quick-review-buttons.js#L60

```
Uncaught (in promise) TypeError: Cannot read property 'remove' of null
    at add_quick_review_buttons (content.js:2219)
    at enableFeature (content.js:806)
    at <anonymous>
```

Is thrown on an already merged PR. I guess it should check for it's existence before attempting to remove it.

**Comment by ms10398** [comment]
I would like to work on it as my first issue

**Comment by ms10398** [comment]
How can I check if this is working

**Comment by lukaszklis** [comment]
@ms10398 follow the README on how to run the project locally and test it in the browser. :) The described issue can be tested on a PR's page which has been merged, i.e. https://github.com/sindresorhus/refined-github/pull/921

**Comment by ms10398** [comment]
Okay Thanks will send a PR soon
