### ISSUE TITLE
Some features use underscores for feature disabling

### ISSUE THREAD

**Issue by lode** [sindresorhus/refined-github#920]
I tried disabling some features (btw great feature! pun intended), but some weren't working for me. When turning on the debug log I found that the one I wanted to disable was using underscores instead of dashes: `linkify_branch_refs`. Neither the overview (https://github.com/sindresorhus/refined-github/tree/master/source/features) nor the file (https://github.com/sindresorhus/refined-github/blob/master/source/features/linkify-branch-refs.js) reveal that.

It would be great if this (seems like an edge case) is fixed, or it becomes more discoverable.

**Comment by bfred-it** [comment]
Thanks! It was a mistake of https://github.com/sindresorhus/refined-github/pull/877/commits/1d31a5d6cc3137bbb02226c65df286fbecd0d734

**Comment by lode** [comment]
Thanks for the fix and the migration!

**Comment by bfred-it** [comment]
I wonder now why you were trying to disable `linkify_branch_refs`

**Comment by lode** [comment]
Because I usually double click the branch name on top of a PR to copy it to a CLI. I almost never go to the branch itself, so the link is also not that useful to me.

Maybe a copy button next to them would be helpful to support both cases.

**Comment by hkdobrev** [comment]
> Because I usually double click the branch name on top of a PR to copy it to a CLI. I almost never go to the branch itself, so the link is also not that useful to me.
> 
> Maybe a copy button next to them would be helpful to support both cases.

BTW related discussions were held in #77 and #78.

**Comment by bfred-it** [comment]
For reference, you can also select text in link with by holding <kbd>alt</kbd> (at least on Chrome/macOS)

**Comment by lode** [comment]
Ha thanks for the links to the long discussions :) For my and my teams workflow it is very useful to have the branch name. But it's okay. I'm very happy being able to disable the linkify as I never visit those links anyway.

The `alt` is working for me too, although a bit buggy. I'll see if I can get it into my workflow.
