### ISSUE TITLE
Restore, deduplicate, declutter activity cards

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#922]
Following #896 and #899

I think the cards are actually more useful than what we show now. Like my original [GitHub Clean Feed](https://github.com/bfred-it/github-clean-feed) did, I prefer focusing on the repo being acted on, rather than the people. Having 10 identical events for "X starred user/repo" is not that useful and it looks cluttered.

GitHub kinda got this right in their [dashboard/discover](https://github.com/dashboard/discover) page.

Mockup:

<img width="686" alt="screen shot 2017-12-28 at 03 07 45" src="https://user-images.githubusercontent.com/1402241/34392041-53f00db2-eb7c-11e7-8685-687951e4ff07.png">

It's more data, less repetition ("X starred same-user/same-repo")

Plus maybe show the small star overlaid on each avatar, or the "repo created" icon (✳️?)

**Comment by bfred-it** [comment]
This is my current CSS-only Stylish solution. No de-duplication, but it's compact enough.

<img width="595" alt="screen shot 2018-01-23 at 15 21 00" src="https://user-images.githubusercontent.com/1402241/35265158-eb1bd9b6-0051-11e8-8fcf-e7450292b06e.png">

**Comment by sindresorhus** [comment]
@bfred-it Looks good, but I don't think it's clear enough that those are starred repos.

**Comment by bfred-it** [comment]
Yeah for RGH we’d need a bit more info, like a star icon. That’s why I just did it for myself but no PR 😜

**Comment by bfred-it** [comment]
Essentially fixed by https://github.com/sindresorhus/refined-github/pull/1045

Also hiding the name goes against the popular #1065
