### ISSUE TITLE
Hides titles on reactions

### ISSUE THREAD

**Issue by ostrolucky** [sindresorhus/refined-github#936]
![screenshot from 2017-12-30 21-25-00](https://user-images.githubusercontent.com/496233/34457150-97f874da-eda8-11e7-92dc-cfebd8789936.png)

This extension hides this title bar. I have disabled all [modules](https://github.com/sindresorhus/refined-github/tree/master/source/features) and it didn't help, so probably CSS issue.

I am trying this extension now for 2nd time and this bug is still there. I consider knowing who liked which post as a vital feature and because of this I can't have this extension enabled :(

**Comment by bfred-it** [comment]
You're right, this was supposed to show up but there was a bug in the selector (`[attr~="words and spaces"]` doesn't work)
