### ISSUE TITLE
Auto linkify shouldn't work in code blocks in markdown

### ISSUE THREAD

**Issue by OmgImAlexis** [sindresorhus/refined-github#938]
The first code block should show the whole Github URL, the second is what I'm seeing on my page.
I had to refresh about 10 times for it to show up again.

Example repo https://github.com/drlogout/caddy-proxy

```bash
$ git clone https://github.com/drlogout/caddy-proxy
$ cd caddy-proxy
```

```bash
$ git clone drlogout/caddy-proxy
$ cd caddy-proxy
```

![screen shot 2017-12-31 at 6 17 00 pm](https://user-images.githubusercontent.com/6525926/34460154-f6e9314c-ee56-11e7-87ba-bda950cabb6e.png)

```
<div class="highlight highlight-source-shell refined-github-linkified-code"><pre>$ git clone <a href="https://github.com/drlogout/caddy-proxy">drlogout/caddy-proxy</a>
$ <span class="pl-c1">cd</span> caddy-proxy</pre></div>
```

**Comment by bfred-it** [comment]
This happened before because linkify was happening before the link shortening. Flipping the two fixed it. Is it the same bug now?
