### ISSUE TITLE
Make merge commits less noisy

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#94]
This looks very noisy:

<img width="641" alt="screen shot 2016-03-22 at 21 15 18" src="https://cloud.githubusercontent.com/assets/170270/13954403/343b18aa-f073-11e5-9ae4-c870e23cb514.png">

Maybe we can fade it out or something? Any other suggestions?

**Comment by paulmolluzzo** [comment]
All commits are "equal" to git. How would you want to target these? By the text inside the message?

You should be able to type a different commit message when you make the merge, so just write "Merge #91" or something like that to reduce the noise.

**Comment by sindresorhus** [comment]
> How would you want to target these? By the text inside the message?

Yes, by text. Should work for most merge commits.

> You should be able to type a different commit message when you make the merge, so just write "Merge #91" or something like that to reduce the noise.

I don't mean the commit message being noisy. I mean the commit itself.
