### ISSUE TITLE
file info overlay when scrolling in files

### ISSUE THREAD

**Issue by tooomm** [sindresorhus/refined-github#943]
I assume this overlay is part of the `Refined GitHub` extension?
It wasn't listed in the features...

![new](https://user-images.githubusercontent.com/9874850/34502695-f3f5a410-f014-11e7-8eaf-1dda5e712bb3.png)

I have suggestion regarding it:
When you follow a link that points you to a certain line in a file like:
https://github.com/sindresorhus/refined-github/blob/master/source/content.css#L214
This bar always ends up hiding the initial line which is a bit annoying... ;)
See this example taken with the above link. Line 214 is hidden:
![new2](https://user-images.githubusercontent.com/9874850/34502807-8ffeb180-f015-11e7-8560-b965c69880f5.png)
<br>

Maybe you want to tweak that too! 👍

**Comment by jgierer12** [comment]
Duplicate of #919

**Comment by tooomm** [comment]
Sorry, thanks for pointing me! 👍
