### ISSUE TITLE
Show issue resolution in header (was it closed by a PR?)

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#948]
Visit this issue: https://github.com/sindresorhus/refined-github/issues/80

<img width="237" alt="closed" src="https://user-images.githubusercontent.com/1402241/34565886-1d1004d2-f18f-11e7-9225-b6a8a9500c65.png">

Can you tell whether it was accepted? How about visiting what closed it?

How about this?

<img width="219" alt="closed by pr" src="https://user-images.githubusercontent.com/1402241/34565902-2b99137c-f18f-11e7-9a92-869f5f1e9b31.png">

This should be an easy fix since the PR ID is at the bottom of the page. The ID would be clickable.

**Comment by yakov116** [comment]
How would you do it if it was a commit that closed it?

**Comment by bfred-it** [comment]
Same, plus `<code>`

<img width="216" alt="commit mockup" src="https://user-images.githubusercontent.com/1402241/34567257-16ed9858-f194-11e7-8ea2-a4e567224698.png">

**Comment by yakov116** [comment]
I would do "via" instead of "by" for a commit and make the color different (purple is usually for merged)

**Comment by sindresorhus** [comment]
Yes! I can't believe GitHub doesn't do this. I'm gonna send a feature request to GitHub too (please do so too), although I doubt they'll do this.

**Comment by bfred-it** [comment]
I think the question would be: what if it's closed by something, then reopened, then closed by something

Example:

https://github.com/sindresorhus/refined-github/issues/479 (closed by pr, then closed manually)
https://github.com/sindresorhus/refined-github/issues/565 (closed by a commit, then by a pr)

**Comment by bfred-it** [comment]
**Color**: well, yeah, merged PRs are purple and they mean "accepted". In this case the issue would be "closed positively"

**Wording**: GitHub uses `user closed this in #1`, so maybe we should match `in`

**Comment by bfred-it** [comment]
Additionally: the whole label could link to the event in the timeline, while the PR/commit would link directly there (nested `<a>`s, yes. Both browsers support them)

**Comment by jgierer12** [comment]
> I think the question would be: what if it's closed, reopened, then closed again?

I'd always take the most recent action, i.e.

#479 => Red, 'Closed'
#565 => Purple, 'Closed in #804'

Purple + 'in' is best for commits too IMO since it's what GitHub uses for both PRs and commits.

> the whole label could link to the event in the timeline

👍, same for red 'Closed'

**Comment by hkdobrev** [comment]
I'd prefer to always keep the red closed label as it is, but add the link to the PR with purple and a tooltip for the title next to it. Due to habit and separation of the statuses. Sometimes an issue is closed because a PR closes it without the actual issue implemented as originally reported/requested. We could even mimic the chronology style GitHub does (it's just at the top and end of the page):

> 	mojavelinux opened this issue on 14 Mar 2016

>  bfred-it closed this in #935 20 hours ago

**Comment by bfred-it** [comment]
> without the actual issue implemented as originally reported/requested

Is that relevant though? If a PR closes an issue, it essentially marks it as _resolved_, as intended by the maintainer. The purple just matches the closing PR's color and that's what we're highlighting. 

Even purple PRs sometimes don't do what their intention was, or are undone later, so the only purpose that the color has is to mark a PR as merged, or in this case an issue closed by a merged PR.
