### ISSUE TITLE
Display collaborator reactions more prominently

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#95]
Previously, when we did `:+1:` as comments, I could quickly see which collaborators that :+1:'d something. Now it's intermixed with all other users reactions.

We could maybe show the avatar of collaborators inside the relevant reaction. Open to other suggestions though.

<img width="386" alt="screen shot 2016-03-22 at 22 51 03" src="https://cloud.githubusercontent.com/assets/170270/13957925/c73d39fa-f080-11e5-8547-ecb113b073d9.png">

**Comment by hkdobrev** [comment]
Good idea. I'd suggest showing avatars of all users on the right of reactions in the same horizontal space. So you'd see the avatars of users who reacted at a glance and you could go deeper by hovering over reactions as you can do now.

Of course we need to limit the user avatars to a reasonable number and use `overflow-x: hidden`.

**Comment by sindresorhus** [comment]
:+1: Good ideas!

**Comment by hkdobrev** [comment]
@sindresorhus Can you think of any way for getting avatars of users who reacted, but haven't commented on the issue/PR? The GitHub avatar URLs are based on their GitHub user ID, but it's not provided in the HTML. I can use the API, but I couldn't find a way neither to get multiple users data in a single request nor request just the image [like Facebook allows](https://developers.facebook.com/docs/graph-api/reference/user/picture/).

**Comment by paulmolluzzo** [comment]
Will this work? http://stackoverflow.com/questions/22932422/get-github-avatar-from-email-or-name

**Comment by hkdobrev** [comment]
@paulmolluzzo This is the endpoint I meant
> I can use the API

However I don't want a separate request for every user reacted on a page. I'd very much like a way to generate the avatar URL and just insert `<img>` elements.

**Comment by hkdobrev** [comment]
BTW for now I have this: https://github.com/sindresorhus/refined-github/compare/reactions-participants

**Comment by paulmolluzzo** [comment]
> However I don't want a separate request for every user reacted on a page. I'd very much like a way to generate the avatar URL and just insert <img> elements.

Build a micro app and deploy to Heroku? The endpoint should take an array of usernames and send back an array of key/values with username and image. That's the only way I see around this other than hitting each usename and parsing the JSON.

IMO the GitHub API is cumbersome. It sends back a ton of stuff I don't need and makes it hard to get specific stuff in a single request.

**Comment by hkdobrev** [comment]
A separate Heroku app is my last resort. If I go that way I prefer the Facebook way.

E.g. `heroku-url.com/username/avatar` to 301 redirect to the GitHub avatar URL and the browsers would take care of following the redirect when loading an `<img>` tag.

**Comment by hkdobrev** [comment]
BTW I've rebased my branch on latest master: https://github.com/sindresorhus/refined-github/compare/reactions-participants

I'm probably not going to dedicate the time to pursue this further, but if someone is willing to take it, please do.

**Comment by sindresorhus** [comment]
@hkdobrev Can you shortly describe what's in that branch and what's missing?

**Comment by hkdobrev** [comment]
@sindresorhus Sure.

The code in this branch just process the usernames from every reaction on every comment and puts them in a container after the reactions. It processes the username lists separated by comma or an `and` and builds an unique set.

The code in this branch **does not** deal with any styling and finding avatars for these usernames.

**Comment by paulmolluzzo** [comment]
I still don't see a way around making another app to get those avatars, "Facebook Way" or otherwise. GH doesn't have an endpoint for the avatar.

**Comment by paulmolluzzo** [comment]
@hkdobrev This is super ugly and will probably break frequently: https://pumpkin-cake-78790.herokuapp.com/ 

Code is here: https://github.com/paulmolluzzo/github-avatar-redirect

**Comment by hkdobrev** [comment]
@paulmolluzzo I've found it! https://github.com/hkdobrev.png If you append `.png` to usernames in GitHub you get redirected to the avatar image. It's just like Facebook, just not on the API, but on GitHub.com instead. Learned that from the 3rd tip in https://www.youtube.com/watch?v=jpMmboYadnA

**Comment by paulmolluzzo** [comment]
@hkdobrev LOL so I built that app for nothing?

**Comment by hkdobrev** [comment]
@paulmolluzzo Well, sorry about that :see_no_evil:

**Comment by paulmolluzzo** [comment]
@hkdobrev no worries! Good find! I'm sure I can reuse something in there someday anyway.

**Comment by hkdobrev** [comment]
Implemented in #145.
