### ISSUE TITLE
Gists profile link should be moved to right of Stars link

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#953]
This follows the order of the navbar profile dropdown.

**Comment by bfred-it** [comment]
I don't mind the position. Also adding it at the and doesn't move any other tab around, making its presence less annoying.

**Comment by ifvictr** [comment]
Yeah, I didn't think of that. :sweat_smile: Maybe use padding or height and width to hold the same amount of space before?

**Comment by ifvictr** [comment]
Or maybe placeholder content? Like `--`

**Comment by jgierer12** [comment]
Not worth the effort IMO
