### ISSUE TITLE
Repo CI status icon links to one provider even when multiple are enabled

### ISSUE THREAD

**Issue by Zac-HD** [sindresorhus/refined-github#956]
For https://github.com/HypothesisWorks/hypothesis-python this goes to Appveyor.  Contrast Github's default behaviour in this case - it pops up a little box with the status and details of each provider, with individual links.  Matching this behaviour would be really nice.

**Comment by jgierer12** [comment]
Sorry, which status icon and default behavior are you referring to? If you're talking about the one next to the repo title, it opens the popup for me as expected:

![CI Popup](https://user-images.githubusercontent.com/4331946/34642090-1620e47c-f30e-11e7-8f7b-832996abcd3b.png)

**Comment by shroudedcode** [comment]
> If you're talking about the one next to the repo title, it opens the popup for me as expected:

![](https://user-images.githubusercontent.com/29176678/34644441-ff1dcb54-f336-11e7-9bc0-2e8daf437b84.png)

Not for me. The :x: links directly to [the AppVeyor build](https://ci.appveyor.com/project/DRMacIver/hypothesis-python/build/1.0.2833). Maybe this only happens when one build failed?

**Comment by jgierer12** [comment]
Yep, that seems to be true. FWIW, we copy the icon from the first commit on [/commits/master/](https://github.com/HypothesisWorks/hypothesis-python/commits/master) where it behaves the same.

**Comment by bfred-it** [comment]
Looks like a build configuration or GitHub bug. The icon in the commit list only mentions and links to one failed build so we can't even know if it was actually supposed to be more than one and can't create the popup either.

# vscode repo

> <img width="341" alt="has popup" src="https://user-images.githubusercontent.com/1402241/34646266-0c8d265e-f396-11e7-9b5a-7c2e297f6ab5.png">

> <img width="350" alt="0 / 2 checks ok" src="https://user-images.githubusercontent.com/1402241/34646263-03d1ae86-f396-11e7-9b30-5e0efb48e99c.png">
(label is in HTML, but actually not visible to us)

# hypothesis-python

> <img width="366" alt="appveyor has failed" src="https://user-images.githubusercontent.com/1402241/34646279-2b7f1658-f396-11e7-8b73-66592c9baffd.png">
