### ISSUE TITLE
Rate-limited API breaks Gist counter during high-usage

### ISSUE THREAD

**Issue by lacymorrow** [sindresorhus/refined-github#969]
My Gist counter is currently returning a value of `undefined`, looking at the network requests, I'm receiving a 403 on the API request, claiming I've hit the rate limit.

**Comment by bfred-it** [comment]
Wanted:
- Options field for [personal token](https://github.com/settings/tokens)
- Automatic token usage by https://github.com/sindresorhus/refined-github/blob/master/source/libs/api.js, if present

We don't need to make the token mandatory, but if we don't we also need to handle failed requests as a consequence of it: **Do we alert the user?** Or do we just let them figure out the errors in the console?

**Comment by lacymorrow** [comment]
At the very least we can handle undefined cases, and output no badge or `( ! )`. For alerting the user, the exclamation badge element could have a title attribute explaining the error.

**Comment by sindresorhus** [comment]
A token should be mandatory for this feature, but not mandatory for the extension. If no token is included, we could `console.log` that the feature is not enabled because a token is not set.

**Comment by bfred-it** [comment]
Sounds good. One more thing:
- [ ] handle 401 errors when the key is wrong or expired.

**Comment by lacymorrow** [comment]
I'd say when key doesn't exist or is invalid/expired, the gists counter is hidden completely.

A more explicit option would be to test the rate limit to see if it has been hit or not using https://developer.github.com/v3/rate_limit/

**Comment by bfred-it** [comment]
@lacymorrow that’d mean querying the rate limit API almost every time before getting the gist. I’d say not worth it. 

@sindresorhus I realized that since we have to deal with errors anyway we might as well just try without token.

**Comment by bfred-it** [comment]
Moved to the generic #1374
