### ISSUE TITLE
Extra blank line when using "Copy" feature

### ISSUE THREAD

**Issue by anthony-robin** [sindresorhus/refined-github#978]
When I want to copy a file with the "Copy" button ([here](https://cloud.githubusercontent.com/assets/170270/14453865/8abeaefe-00c1-11e6-8718-9406cee1dc0d.png)), there is always 
an extra blank line at the top of the file (see screenshot).

<img width="603" alt="capture d ecran 2018-01-11 a 11 54 20" src="https://user-images.githubusercontent.com/5428510/34822389-11ba2fa8-f6c7-11e7-8d1a-458cba6dd505.png">

Is there a way to remove this line ?
Thanks for this amazing extension !

**Comment by bfred-it** [comment]
This is unlikely to be fixed because it would mean undoing https://github.com/sindresorhus/refined-github/pull/771/commits/f7365e1314319bbf2ef5b4802cd516e458f048c4 from https://github.com/sindresorhus/refined-github/pull/771

An extra line is worth the feedback: 

> From #771 
> Why: zeroclipboard offers feedback with a tooltip while the previous implementation feels like nothing happens when pressing the button.
