### ISSUE TITLE
Show filename in diff sticky header

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/refined-github#98]
https://twitter.com/soprano/status/712425703694700544

**Comment by paulmolluzzo** [comment]
:+1:

**Comment by DrewML** [comment]
Started working on this [here](https://github.com/DrewML/refined-github/tree/issue98). Working, but needs some cleanup before I submit a PR.

Todo:
- Unbind scroll/resize listeners on partial page nav to non-PR page
- Debounce scroll event to prevent hammering the DOM so much

**Comment by paulmolluzzo** [comment]
@DrewML This is rad! Make a PR like this and put `[WIP]` in the title for now.

A couple comments:
* :+1: on unbinding the events. I haven't seen any errors but there might be a gotcha lurking out there.
* :-1: for bothering with debounce. I don't think we'll notice any performance issue with this. There's no animations or anything going on.
* :+1: on only painting on change. Save the file name to a var, then where you test for length test that it's not equal to the existing var. That said, this isn't a deal breaker IMO.
* :+1: on removing it when it's not sticky. A CSS method is `.js-sticky-offset-scroll:not(.is-stuck) .diff-toolbar-filename {display:none;}`

Something else, it's possible that the last file will never actually make it into the sticky bar if the file sizes are too small. You can hit the bottom before scrolling past the second to last file (see below). You might want to have the logic be "if you can't see the file show the next one, but if you're at the very bottom show the last file name".  I'm not sure about this, and there are other scenarios where you can see the entirety of two files, and in that situation I don't know what's best exactly.

In this screenshot I've scrolled to the bottom of the page and see two "complete" files:
![scrolled_to_bottom](https://cloud.githubusercontent.com/assets/737065/14007541/05f16090-f14e-11e5-924b-3611b2af210c.png)

**Comment by DrewML** [comment]
@paulmolluzzo Appreciate the feedback - [WIP] PR opened. Will continue the discussion over there :)

**Comment by hkdobrev** [comment]
Implemented in #99. Thanks @DrewML!
