### ISSUE TITLE
Sort project boards by most recently updated

### ISSUE THREAD

**Issue by ifvictr** [sindresorhus/refined-github#982]
This one shouldn't be hard. Here's the URL structure for reference: `https://github.com/user/repo/projects?query=is%3Aopen+sort%3Aupdated-desc`

**Comment by bfred-it** [comment]
Related: https://github.com/sindresorhus/refined-github/pull/935/files

**Comment by sindresorhus** [comment]
Looks like GitHub implemented this at some point:

<img width="1038" alt="screen shot 2018-11-07 at 15 42 52" src="https://user-images.githubusercontent.com/170270/48120118-d374e480-e2a3-11e8-93a1-445afc109045.png">

**Comment by langri-sha** [comment]
My projects by default aren't sorted by MRU and I have to flick this every time. Did this feature make it in eventually?
