### ISSUE TITLE
"Jump to bottom" link disappears when the page updates

### ISSUE THREAD

**Issue by bfred-it** [sindresorhus/refined-github#987]
1. Visit an isssue/PR
2. Notice the Jump to bottom link (https://github.com/sindresorhus/refined-github/pull/904)
3. Wait for a comment to be ajaxed in
4. Link is gone

Similarly to https://github.com/sindresorhus/refined-github/issues/233, `observeEl` should probably be used to keep track of changes in the header.

**Comment by tom-sherman** [comment]
The "Mark as unread" button also disappears.

Instead of a MutationObserver, an alternative solution could be to watch for incoming `show_partial` requests and reinsert the features accordingly.

**Comment by bfred-it** [comment]
That’s what I tried to use for the update of the reaction avatars but it’s not reliable and it fires before the actual content. The event it fires is `socket:message`, you can look for it in our code to see how it works.

**Comment by bfred-it** [comment]
> The "Mark as unread" button also disappears.

Fixed by #996

**Comment by ramlmn** [comment]
@bfred-it The "Mark as unread" still disappears along with "Jump to bottom" link for me. Tested with this [tree](https://github.com/sindresorhus/refined-github/tree/1d559b9262735366a2a2b6c4f19387bbb6aac71d) on Chromium 63.

Context:
![ajax](https://user-images.githubusercontent.com/12368291/35163302-40ac7720-fd6c-11e7-890d-71aa4702ee17.gif)

---------------------------------

I would like to submit a PR when this is confirmed by others as well!

**Comment by bfred-it** [comment]
@ramlmn confirmed. It looks like there are multiple nested ajaxed areas. I wish there was an easy way to detect changes with `socket:message` events, but last time I tried for Reaction Avatars it turned out to be unreliable. Perhaps you have better luck.

The alternative I think is to fall back to `observeEl` on the highest `socket`-enabled element

**Comment by ramlmn** [comment]
> The alternative I think is to fall back to observeEl on the highest socket-enabled element

:+1:
