### ISSUE TITLE
Releases tab reponav incomplete markup and disappearing selected class

### ISSUE THREAD

**Issue by zmni** [sindresorhus/refined-github#989]
* Incomplete markup
*(actually, you can ignore this, because it work perfectly. It just missing the container)*

![rh](https://user-images.githubusercontent.com/841523/34906460-d5e863e2-f8a0-11e7-8de0-c051aa6fad09.jpg)
note that `a.reponav-releases` doesn't have `<span/>` container.

* Disappearing `.selected` class.
![rh-releases-tab-selected](https://user-images.githubusercontent.com/841523/34906554-6f586c42-f8a2-11e7-8cba-7e9dc1bd816b.gif)

---
Windows 10 & Firefox x64
Refined GitHub `v18.1.11.1457`

**Comment by bfred-it** [comment]
Thanks for the report @zmni!
