### ISSUE TITLE
Sidebar content sits above overlay

### ISSUE THREAD

**Issue by tom-sherman** [sindresorhus/refined-github#994]
The content in pull requests and issue sidebars sits above the dropdown overlay. In the image below you can see that the subscribe buttons, labels, and dividers sit above the overlay. This is also the case for assignees and milestones.

![image](https://user-images.githubusercontent.com/9257001/34915320-4372ca08-f91c-11e7-8800-e2eae3d6322f.png)

**Comment by bfred-it** [comment]
It’s best to reduce/remove the z-index on the buttons instead

**Comment by tom-sherman** [comment]
Agreed, I've updated my PR
